### ISSUE TITLE
select tags and their hidden field counterparts are rendered in the wrong order

### ISSUE THREAD

**Issue by aaronjensen** [rails/rails#13523]
Currently if you render a select tag with the form helper you end up with a hidden field followed by the select tag. This is fine in most cases, but on older versions of IE, when you are wrapping said select tag with a label tag, the label will get associated with the hidden field rather than the select. Subtle, but it has caused us some usability bugs.

The culprit is here: 
https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/tags/base.rb#L126

The solution is simply to swap the order of the `+` operands.

**Comment by robin850** [comment]
> Unfortunately this is not possible. The hidden input have to come before the select input or it will be always submitted, even if you select some value.

Actually this is not the problem here ; since this field is only added when we specify the `:multiple` option, the parameter is returned as an array so the selected values won't be removed from it. If we merge #13524, the only change would be that instead of having `["", "Foo", "Bar"]`, we would have `["Foo", "Bar", ""]` ([reproduction script](https://gist.github.com/robin850/51fe25be9a7ceb3cd95e)).

Actually is there any reason why we are keeping the blank string inside the array and we don't remove it when there's at least another value ? This is certainly something we can consider for Rails 5.0 as this would be a breaking change. Even though changing such behavior just for fixing forms on IE seems pretty dubious, I think we could call `#pop ` on the returned array when its length is greater than 1.

What do you guys think ?

**Comment by aaronjensen** [comment]
Popping on multiple seems dangerous. What if the multiple select tag was rendered manually? You may be losing real data. Even checking for the last entry being blank and then popping could be dangerous as they may have manually rendered the select tag and blank is an acceptable value. 

One idea would be to use a sentinel value either as the name or the value. As the key would probably cause less confusion. In other words, instead of the hidden having the same name as the select, it could be something like:

```
<select name="foo">
  <option ...>
</select>
<input type="hidden" name="__select__foo" value ="" />
```

Rails would then handle the case of no `foo` coming through but `__select__foo` being there and being "". It seems unlikely that this would any problems.

**Comment by robin850** [comment]
@aaronjensen : Yes, good call for `pop`, haven't thought about this! The simpler solution could be to simply `array.delete("")` since several blank values will be left if several calls to `select multiple: true` are done. But well, let's wait for some feedback from core ; it's maybe there for a good reason (looking at [the original pull request](https://github.com/rails/rails/pull/1552#discussion_r2533112), it turns out  to be just an implementation limit and there's no real goal in keeping it).

**Comment by aaronjensen** [comment]
@robin850, even `array.delete("")` could be problematic unless we say that the empty string is not a valid value for a multi select in rails, which isn't true in general. 

Is there any concern w/ accepting https://github.com/rails/rails/pull/13524 and then continuing to look for a way to get rid of the extra `""` after the fact?

**Comment by aaronjensen** [comment]
@rafaelfranca ping again on this, please merge!

**Comment by matthewd** [comment]
@aaronjensen can you please expand on "older versions of IE"? I'm not keen on making an observable behaviour change here without a very compelling argument we can point to when people get upset that we broke their applications.

**Comment by aaronjensen** [comment]
@matthewd IE8 and older. The change is only observable at the html output level. I've not been able to think of a scenario this would break except for people using javascript that expects that particular order.

**Comment by matthewd** [comment]
It seems we managed to take long enough that IE <= 8 is no longer worthy of concern. :confused:

At this point, I think the danger of the DOM change outweighs the ancient-IE benefit.
