### ISSUE TITLE
AR : Circular `dependent: :destroy` cause 'stack level too deep' error

### ISSUE THREAD

**Issue by bobbus** [rails/rails#13609]
I believe this bug wasn't present before Rails 4.

See a full runnable gist [here](https://gist.github.com/bobbus/8280199)

**Comment by vizo** [comment]
:+1: +1

**Comment by bughit** [comment]
1. It's not just callbacks, it seems to me that the entire operation should be protected both from reentry (destroy called while a previous destroy is still on the stack) and repeated invocations.  Both should raise by default, but perhaps allow a silent exit via an option.  
2. Why is dependent destruction done via before_destroy rather than after_destroy?  If it was done in after_destroy you could check the destroyed state of the associations.

**Comment by ioquatix** [comment]
+1

**Comment by gkop** [comment]
+1

**Comment by sgrif** [comment]
Fixed by #18548
