### ISSUE TITLE
Rails 4.0.2 ActiveRecord: has_many uniq through not removing order

### ISSUE THREAD

**Issue by pekeler** [rails/rails#13677]
Postgresql doesn't accept DISTINCT selects with an ORDER. In Rails 3, this :users association would generate sql without an ORDER.

```
has_many :comments, :order => :updated_at
has_many :users, :uniq => true, :through => :comments
```

In Rails 4, ORDER is preserved (breaking postgresql).

```
has_many :comments, -> {order(:updated_at)}
has_many :users, -> {uniq}, :through => :comments
```

Executable testcase: https://gist.github.com/pekeler/8377939

**Comment by pekeler** [comment]
I can still reproduce this with 4.1.11.

**Comment by rafaelfranca** [comment]
Thanks! Tagged with a label that doesn't allow the bot to complain anymore.

**Comment by trostli** [comment]
I can still reproduce this in Rails 4.2.6

**Comment by NielsKSchjoedt** [comment]
+1 in rails 5

**Comment by NielsKSchjoedt** [comment]
I think the best would be, that the attributes in the order by clause were automatically included in the select list. This will also produce problems when you do: `.user_ids`

**Comment by hishammalik** [comment]
+1 issue still exists in Rails 4.2.9 too

**Comment by LucasArruda** [comment]
I was able to reproduce what I (we) wanted AO to do, which is bring `unique` records and remove the order.

I could remove the other with `has_many`. It's just that I can't get the `.uniq` to work.

So what I did was this:

```ruby
  has_many :comments, -> { includes(:user) }, order: :updated_at

  def users
    comments.map(&:user).uniq
  end
```

And rails does a super optimized query for me, where it grabs the users_ids uniquely and selects `users.*` by that array of ids in the where. So, in total, 2 queries.

What I wanted was something like `SELECT DISTINCT ON (users.id) users.* FROM "users" …` joining with `comments`. 

DISTINCT only doesn't work because in the case `PG` has `json` fields, it fails. 
Also, another remark is that Rails would need to optimize this so `.count` doesn't fail, maybe replacing `DISTINCT on` with just `DISTINCT`, which will end up on a `SELECT COUNT(DISTINCT "users"."id") FROM "users" INNER JOIN`.
