### ISSUE TITLE
ActiveSupport::TimeWithZone#eql?(self.dup) returns false, if created from DateTime object

### ISSUE THREAD

**Issue by meismann** [rails/rails#14178]
When creating an `ActiveSupport::TimeWithZone` from a `DateTime` object like so, I expect `#eql?` to return true:

```
2.1-head :001 > n = DateTime.now.in_time_zone
=> Mon, 24 Feb 2014 12:33:43 UTC +00:00
2.1-head :002 > n.eql? n.dup
 => false
```
Here is the faulty code in `ActiveSupport::TimeWithZone#eql?`:
```
def eql?(other)
  utc.eql?(other)
end
```
`#utc` returns the original DateTime object, whose `#eql?` cannot handle a comparison with an `ActiveSupport::TimeWithZone` correctly.

This is bad for example in Hash merging, because comparison of Hash keys is done with `#eql?`:

```
2.1-head :009 > h1 = { n => 1 }; h2 = { n.dup => 2 }
2.1-head :010 > h1.merge h2
# Expecting a Hash with a single key here with the value 2:
 => {Mon, 24 Feb 2014 13:23:24 UTC +00:00=>1, Mon, 24 Feb 2014 13:23:24 UTC +00:00=>2} 
```
However, if the `ActiveSupport::TimeWithZone` object is created from a `Time` object instead of from a `DateTime` object, the code works as expected:
```
2.1-head :004 > n = Time.now.in_time_zone
 => Mon, 24 Feb 2014 13:07:37 UTC +00:00 
2.1-head :005 > n.eql? n.dup
 => true 
```
The issue occurs in Rails 4.0.3, Rails 4.1.0. rc, and on Ruby versions 2.1-head as well as 2.0.0. It was mentioned in #3431, but not solved.

**Comment by kai-kuchenbecker** [comment]
This is still an issue. And it sucks hard when you want to use timestamps as keys for hashes. (I just had this ... took a while to track down.)

The reproducing test referenced by @why-el may pass depending on whether or not the default time-zone is utc. It should fail whenever it is not utc. Therefore if you simply add a non-utc timezone parameter to the `in_time_zone` call, it will definitely fail.

While I'd agree with @jeremy [here](https://github.com/rails/rails/pull/14235#issuecomment-36433546) that one cannot
> expect standard library classes to be aware of all other classes the may be equal to
I cannot help but wonder why it is okay for `Time` to get its `eql?` monkey patched but not for `DateTime`. If the argument were that `TimeWithZone` is a wrapper around `Time` and not `DateTime`, then why can `DateTime` be wrapped in `TimeWithZone`?

Anyway the current implementation has most surprising behaviour. The easiest way I see to fix this issue is to call `utc` on both `self` and `other` for all comparisons (I think it's only `<=>` and `eql?`).

**Comment by kuldeepaggarwal** [comment]
It is still on master branch.

![screen shot 2015-06-26 at 8 53 07 am](https://cloud.githubusercontent.com/assets/1930730/8370077/da753632-1be0-11e5-93e7-a4cd53f2fe8a.png)

**Comment by rafaelfranca** [comment]
Thanks. Now the bot will not mark this issue as stale
