### ISSUE TITLE
Silent failure when attempting to filter by has_many association

### ISSUE THREAD

**Issue by jeremyevans** [rails/rails#14427]
I understand that ActiveRecord only supports filtering on belongs_to associations, but I'm guessing that silent failure if attempting to filter on a has_many associations is undesired. 

bug report gist: https://gist.github.com/jeremyevans/9645417

I see two possible fixes:

1) Raise an error if attempting to filter by an association that is not belongs_to
2) If the association is not belongs_to, treat the filter as a column instead of an association

Looks like the related code is one of these two places:

https://github.com/rails/rails/blob/a6f88d0924649c70d74efe5a09f9abd3117c3920/activerecord/lib/active_record/relation/predicate_builder.rb#L29
https://github.com/rails/rails/blob/a6f88d0924649c70d74efe5a09f9abd3117c3920/activerecord/lib/active_record/relation/predicate_builder.rb#L58

**Comment by magikid** [comment]
Is this still in the works?

**Comment by martinemde** [comment]
I'm not currently working on this. My patch didn't receive any feedback and keeping it working and applying was difficult when no one seemed to want to apply it. I think this needs to be solved or raised, especially because using a has_many is pretty easy to do and could produce wrong, yet not "invalid" queries that return incorrect results.

**Comment by kamipo** [comment]
It works on master.
