### ISSUE TITLE
after_commit :my_callback, :on => :create fires on update too 

### ISSUE THREAD

**Issue by basvk** [rails/rails#14493]
After upgrading from 4.0.0.beta1 to 4.1.0.rc2 my after_commit hooks are now getting triggered on update too, despite the :on => :create option.

**Comment by devilankur18** [comment]
+1

**Comment by lichtamberg** [comment]
Have the same problem again... ALso with 3.2.20..

**Comment by danielbonnell** [comment]
Was this issue ever resolved? I'm on `4.0.2` and upgrading is not an option for me at the moment.

**Comment by siannopollo** [comment]
This is still an issue as of rails 4.2.2. I can't say anything about newer releases, but I would imagine they still suffer from this as well.

**Comment by maclover7** [comment]
Ran reproduction script above, and Rails master is currently passing. Working on a bisect (and hopefully a solution) for 4-2-stable right now.

**Comment by maclover7** [comment]
Ok, so it looks like this bug is not existent on master. Reproduction script I used can be found [here](https://gist.github.com/maclover7/97bf765426debab99f17). Another slight complication -- it appears as though this behavior has been in the 4.x.x series for a while, because `git bisect` is broken due to not being able to find a correct merge base to get me start. Not sure how to move forward here. cc @sgrif

**Comment by rafaelfranca** [comment]
> Not sure how to move forward here.

We don't move forward. If it is fixed only on master that is fine.

**Comment by woniesong92** [comment]
+1: Isn't it very common for someone to want to call `save` inside the after_commit callback?

**Comment by dimoon** [comment]
@woniesong92 Why not use `update_columns` instead of `save`: validations and callbacks are skipped. Works good inside `after_commit on: :create` in `Rails 4.2.5.1`

**Comment by pirj** [comment]
@dimoon You mean that:

    update_columns(changes.transform_values(&:last))

This will work for most of the cases, but what about saving dependent models created in callback?

**Comment by eugeneius** [comment]
The script from https://github.com/rails/rails/issues/14493#issuecomment-177202810 passes on master, but only because it no longer reproduces the bug. `increment!` doesn't trigger callbacks any more since https://github.com/rails/rails/pull/11410 - if `update!` is used instead, it still fails.

https://github.com/rails/rails/pull/18367 is a proposed fix which does make the script pass, even using `update!`.

There's some confusion in the thread, so to clarify: this bug is present in every stable release of Rails since at least 3.2. It was fixed in 4.0.0.beta1, but the fix was reverted before 4.0.0.rc1.

**Comment by lichtamberg** [comment]
So maybe we should open this issue again?

**Comment by rafaelfranca** [comment]
No, we shouldn't https://github.com/rails/rails/issues/14493#issuecomment-39859811

**Comment by lichtamberg** [comment]
@rafaelfranca But then I would suggest to remove the ```on: :update/:create``` option entirely? If it is broken and won't be repaired? From my point of view this is not a good solution to just let it there in a broken state? What are your thoughts about removing it?

**Comment by rafaelfranca** [comment]
It works for the use case it exists. It only don't work when you do a update action inside a callback that is running because an create action started. In this case Rails consider all actions create.

**Comment by hegwin** [comment]
I encounter this infinite loop issue when using `after_create_commit` callback in Rails 5.0.0.

Currently I use `update_columns` instead of `update_attributes` to avoid this problem. So will this be fixed?

**Comment by zakwanhaj** [comment]
I did the following hack and it worked with me:

```ruby
after_commit :do_after_commit, on: :create

def do_after_commit
  self.class.find(id).update(name: 'New name')
end
```

**Comment by zakwanhaj** [comment]
I did the following hack and It works with me:

```ruby
  after_commit :do_after_commit, on: :create

  def do_after_commit
    self.class.find(id).update(name: 'New name')
    reload
  end
```

**Comment by SampsonCrowley** [comment]
I just want to point out this is still an issue with rails 5. zakwanhaj's work around works for me but this really should be fixed as it can be quite dangerous for those that find the bug the hard way.

**Comment by SampsonCrowley** [comment]
and using update_columns to skip callbacks isn't a proper solution. a lot of users depend on those call backs for things like auditing

**Comment by syedmahmad** [comment]
For rails version <= 4.1 use 
after_commit :do_after_commit, :only => :create
For rails version > 4.1 use
after_commit :do_after_commit, :on => :create.

This will solve my problem.

**Comment by SampsonCrowley** [comment]
@syedmahmad the syntax for how to limit to `on: :create` is not the issue, and using the proper syntax for your rails version does NOT fix the save after commit issue

**Comment by SampsonCrowley** [comment]
calling anything in `after_commit` should be part of a new transaction, not the transaction before committing. that's why it's call AFTER commit

**Comment by lichtamberg** [comment]
I'm stumbling again and again over this issue every year, it's really a big pain and it's sad that this doesn't get fixed - this is clearly a bug in my opinion.

**Comment by SampsonCrowley** [comment]
The problem seems to boil down to the object not being loaded properly in after_commit, i.e. the following function:
```
if self.group_id.blank? && group_id.blank?
  self.class.find(self.id).update(group_id: relations.where(self.class.arel_table[:group_id].not_eq(nil)).pluck(:group_id).first || get_athlete_or_coach.user_id)
  reload
end
```

I would expect the above `after_commit` to only run once since the `group_id` should be set after the first time this code runs. However, if I remove `reload` from inside the if statement the code runs infinitely since for some reason the loaded instance doesn't get the newly updated attribute set in between the time that the row is updated and the time after_commit gets called. even using `self.class.find` doesn't keep me from needing to add `reload` since `self.class.find` seems to return the cached version

**Comment by augustosamame** [comment]
I keep being bitten by this again and again. Each time I eventually reach this thread and I remember WHY this happens, but unfortunately the counterintuitive nature of the after_commit :on => :create is problematic to say the least.
I would suggest AT LEAST firing a warning in logger when a save is fired inside the callback. In this way it will be obvious what's happening and  we can a) change our logic or b) use the update_columns workaround.
IMO the somewhat obscure, counterintuitive behaviour in a common use case is the main problem.

**Comment by atitan** [comment]
Having the same problem, the solution I found is to use [this gem](https://github.com/Envek/after_commit_everywhere) in conjunction with `after_create`.

It looks like this, and everything works fine.

```
class A < ApplicationRecord
  include AfterCommitEverywhere

  after_create :do_something

  def do_something
    after_commit do
      self.update(....)
    end
  end
end
```
