### ISSUE TITLE
Requests that Accept */* do not have a #format of Mime::ALL

### ISSUE THREAD

**Issue by whittle** [rails/rails#15220]
Incoming requests that have an Accept header specifying */* (or, equivalently, requests which do not specify an Accept header) get assigned a `Request#format` which is a `Mime::Type` with `@string="*/*"` and `@symbol=nil`, rather than `Mime::ALL`. Compounding this is the fact that this anonymous `Mime::Type` is `==` to `Mime::ALL`, even though in some places equivalence is determined by matching against `@symbol`. 

This can cause some surprising behavior: for instance `request.format.html?` is false for requests accepting */*, even though `Mime::Type#html?` explicitly checks against `Mime::ALL`. This means that `request.format.html?` is not equivalent to `request.negotiate_mime([Mime[:html]])`. 

I would be happy to submit a PR against this, but I wanted to ask for guidance first. I understand that `Mime::ALL` is explicitly not added to `Mime::LOOKUP`, but I’m unclear why it’s preferable to have Mime lookups result in an anonymous `Mime::Type` that’s `==` to `Mime::ALL`, but isn’t actually `Mime::ALL`. If figuring that out is too contentious, it might instead be useful to change `Mime::Type#html?` to use a more consistent form of matching that an array of symbols.

**Comment by dreyks** [comment]
Rails 4.2.1 the issue still persists.

My case:
I have a root_path that accepts html and js formats (that is .erb and .js.erb templates exist). Some browsers (Safari) send `Accept */*` which is not mapped to html format, and for some reason (alphabetic order?) maps to js format. Then `protect_from_forgery` kicks in and since this request doesn't have X-Requested-With (why should it? it's an ordinary get) browser comes back with a 422 response. Even if I turn forgery protection off, a simple GET to `/` gets javascript instead of html

Well technically this is not an issue with Rails but with the browser, which sends such a stupid `Accept` header. It literally tells 'I don't care what you give me' and so it receives whatever Rails decided to throw.

However considering the situation rather common maybe we should do something about it?

My current workaround is
```ruby
before_action do
  if request.format == Mime::ALL
    request.format = request.xhr? ? :js : :html
  end
end
```

**Comment by dreyks** [comment]
Oh well turns out that my templates where named `main.js.erb` and `main.erb` (without .html). That's why it ended up with js for `Accept */*`.

**Comment by hron84** [comment]
What is the case for Rails 5? I have issue with jQuery POST requests, it sends form data, Rails parses it but somehow it ends up in redirect (with inherited resources) no matter if I do either `format.html` or `format.json`
