### ISSUE TITLE
Error preloading habtm association with hashed conditions

### ISSUE THREAD

**Issue by scambra** [rails/rails#15244]
This work on rails 4.0.5 but generates wrong sql on 4.1 and master
On 4.1 and master works with string conditions

This [gist](https://gist.github.com/scambra/322fd296e5dc882261a4) include test for rails 4.0.5, 4.1.1 and master, using similar models to used ones by has_and_belongs_to_many_associations_test

**Comment by kimrgrey** [comment]
Hi, guys! What about this bug? Is it was fixed in Rails 4.1? Or Rails 4.2? Or it's still there? It looks like I have same issue. I'm trying to preload HABTM relation with additional `where` caluse and it's failed because column isn't available for genereated query. Should I use only `references` in such cases?

**Comment by kamipo** [comment]
It works on master.
