### ISSUE TITLE
"reverse polymorphic" associated model isn't destroyed using :dependent => :destroy

### ISSUE THREAD

**Issue by ojab** [rails/rails#15468]
I have Foo model that has one of [Bar or Baz] through Qux, see [testcase](https://gist.github.com/ojab/d148814e5ba119315488)
Foo `has_one :qux` and `has_one :bar, :through => :qux` with `:dependent => :destroy` on both, but after Foo.destroy only Foo & Qux are destroyed, Bar stays in DB. Also Bar has `validates :qux, :foo, presence: true`, so it becomes invalid.

Basically, right now it's impossible to destroy all of the linked objects: various `:dependent => :destroy` combinations leads to leftovers in the DB or to the `SystemStackError: stack level too deep`.

Reproducible with both 4.1.1 and master.

**Comment by palkan** [comment]
Here is working [gist](https://gist.github.com/palkan/766b8d094c1e1f327c24). Works in master and 4.2.

Explanation: 
`has_one ..., through: ...` doesn't accept `dependent: ...` option (see [code](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/builder/has_one.rb#L18)). That's why it's not working.  
Adding `dependent: :destroy` to `belongs_to` association works as expected.
