### ISSUE TITLE
Constraints for route overriders constraints in parent scope

### ISSUE THREAD

**Issue by epidemian** [rails/rails#15668]
Given this `routes.rb`:

```ruby
Rails.application.routes.draw do
  scope :foo, constraints: proc { p 'foo constraint' } do
    get 'bar', to: 'home#index'
    get 'baz', to: 'home#index', constraints: proc { p 'baz constraint' }
  end
end
```

When requesting `/foo/bar` the constraint that prints "foo constraint" is called, as expected. 

But when requesting `/foo/baz` only the "baz constraint" gets called. Shouldn't both the "foo constraint" of the parent scope and the "baz constraint" be checked in this case?

This is a very dummy example. But i stumbled upon this problem on an app where a parent scope had a constraint to check that all its routes had a valid subdomain, and then a route inside of that scope had another constraint to check something specific to that route. That specific check was working, but not the subdomain check, leading to some confusing breakage hehe. A possible workaround is to also check for the subdomain inside that specific route constraint, but i think it'd be better if constraints could be naturally "nested".

BTW: This was tested on Rails 4.1.1.

**Comment by KeithYJohnson** [comment]
@epidemian I'm having some issues with routing constraints too.  Per the api version specified in a request, I want requests with the same URL to go to two different controller.  

Just wondering if in tackling your routing constraint problem you could shed some light on this one too.

``` ruby

Zipmark::Application.routes.draw do
  scope :constraints => lambda {|req| req.format == "application/v3+json" } do
    get 'kittens' => 'v3/fuzzy_kittens#index'
  end

  scope :constraints => lambda {|req| req.format != "application/v3+json" } do
    resources :kittens
  end
end
```

Even when setting the appropriate headers when making a request:

```ruby
  header "Accept", "application/v3+json"
  header "Content-Type", "application/v3+json"
```

It still always gets routed to the normal `KittensController` instead of `V3::FuzzyKittensController`

**Comment by epidemian** [comment]
@KeithYJohnson, sorry for taking too long to answer. I haven't tried your example, but it doesn't seem like the same issue, as it has no nested constrains. Have you tried debugging it and seeing what `req.format` returns inside the constraints' lambdas?

Also, in this case you might be able to use a hash with a regex for the constraint, as you're matching something [on the Request object](http://guides.rubyonrails.org/routing.html#request-based-constraints):

```ruby
Zipmark::Application.routes.draw do
  constraints format: /application\/v3\+json/ do
    get 'kittens', to: 'v3/fuzzy_kittens#index'
  end
  # Requests to /kittens without the specific format will hit KittensController
  resources :kittens
end
```

Let me know if you could make it work!

**Comment by KeithYJohnson** [comment]
@epidemian your suggestion worked thanks so much!

**Comment by epidemian** [comment]
I'm closing this issue in light of the discussion in #19075. It makes sense that a callable constraint on a nested route overrides the callable constraint on the parent scope, because regex constraints also do so (as long as they act on the same field).

**Comment by rmacklin** [comment]
For anyone else that stumbles on this issue:

<br>

I found that with this setup: 
```rb
  constraints ParentConstraint do
    get 'foo' => redirect('/bar'), constraints: ->(r) { r.format != :json }
  end
```
the inline `:constraints` callable overrides the `ParentConstraint`, but if you instead move the route declaration inside a second `constraints(...) do` block:

```rb
  constraints ParentConstraint do
    constraints ->(request) { request.format != :json } do
      get 'foo' => redirect('/bar')
    end
  end
```
both the `ParentConstraint` and the inner constraint have to match.

<hr>

I think this is one case of what @epidemian pointed out in https://github.com/rails/rails/issues/15668#issuecomment-46453064:
> When it's a nested scope, the constraints are merged in [`merge_blocks_scope,`](https://github.com/rails/rails/blob/96f28b6a9899889c5b9d1786ca155e0c97abae7a/actionpack/lib/action_dispatch/routing/mapper.rb#L986-L990)

though in this case it's still technically:
> a constraint on a particular route

(just not an _inline_ constraint - that's the key difference)

<br>

Anyway, just sharing because I figured this specific example might clarify the difference and potentially help someone else that comes across this issue.

**Comment by hderms** [comment]
This behavior seems to break common sense intuition regarding how constraint blocks compose, in short: this fails the 'principle of least surprise' test.

**Comment by tycobbb** [comment]
I also found this behavior particularly surprising, and it renders route-level callable constraints unusable for some use cases.

We're using the [`SignedIn`](https://github.com/thoughtbot/clearance/blob/master/lib/clearance/constraints/signed_in.rb) constraint from [Clearance](https://github.com/thoughtbot/clearance) to restrict certain routes to authenticated users. Adding unrelated callable constraints to authenticated routes unexpectedly made them publicly accessible.
