### ISSUE TITLE
Getting class using reflection on polymorphic belongs_to association does not work

### ISSUE THREAD

**Issue by robinroestenburg** [rails/rails#15833]
Over the last couple of weeks I've been upgrading our project from Rails 3.0 to 3.2. I came across a problem getting the class of a polymorphic `belongs_to` association using reflection in our code that produces audit information.

Consider the following models:

``` ruby
class Post < ActiveRecord::Base
  has_many :comments, as: :parent
end

class Comment < ActiveRecord::Base
  belongs_to :parent, polymorphic: true
end
```

In the above case, after adding a comment, an audit line would be written for the new **Comment** record. This audit line contains a (textual) reference to the parent **Post** record. Using reflection we can retrieve the class of this parent, something like this:

``` ruby
Comment.reflect_on_all_associations(:belongs_to).first.klass
```

The expected result of that code would be ```Post```, but instead it produces ```Comment::Parent```. 

See [this gist](https://gist.github.com/robinroestenburg/693341f75c4f28904d7e) for the reproduction script. The script uses master, but this is a problem in Rails 3.2 as well. 

A similar issue/problem has been solved in issue #10197, by looking up the class at runtime (see commit https://github.com/rails/rails/commit/2a8994122588a2bafb8cf052f2ca1a49a2b758d6).

I will work on a patch next week.

**Comment by eileencodes** [comment]
Hey @robinroestenburg - I took a look at this and I don't think this is possible. What version of Rails did this work on? I couldn't get less than 3.0.8 to run on my local machine but the test script still failed on 3.0.8.

Hopefully I don't make this explaination too confusing. I don't think that `Comment.reflect_on_association(:parent).klass` can possibly return "Post". This is because if we had another model that had `has_many :comments, as: :parent` say "Photos" how would the code know whether to return "Post" or "Photos" for the klass? 

First when `Comment.reflect_on_association(:parent).klass` is called we can see that `@klass` is nil.

```
#<ActiveRecord::Reflection::BelongsToReflection:0x007fee9d11b528 @name=:parent, @scope=nil, @options={:polymorphic=>true}, @active_record=Comment(id: integer, parent_id: integer, parent_type: string), @klass=nil, @plural_name="parents", @automatic_inverse_of=nil, @type=nil, @foreign_type="parent_type", @constructable=false, @association_scope_cache={}, @scope_lock=#<Mutex:0x007fee9d11b2f8>>
```

Since `@klass` is nil the Reflection then computes the class with `compute_class` which goes to `compute_type` on https://github.com/rails/rails/blob/master/activerecord/lib/active_record/inheritance.rb#L132. As it loops through the candidates on line 143 it gets "Comment::Parent" and "Parent" as possible candidates. Since neither are actual classes we get the raised error on 148 which just returns the first candidate that failed (even though all of them fail).

The reason that you can do this at runtime is because your code knows which owner base class you want (because at runtime you are giving it the association and not just the Reflection name) but the Rails source only knows that "Parent" and "Comment::Parent" are not valid class names. Even if it did know the about both owners "Photo" and "Post" it wouldn't know which one was being requested with `Comment.reflect_on_association(:parent).klass` call. I'm sorry this didn't have more of a solution but maybe this will help someone in the future so they don't go down the rabbit hole. :smile:

**Comment by eileencodes** [comment]
The reason that commit you linked to works by the way is because it's using the association at runtime. When we're just asking `Comment` about it's reflections it doesn't know what the association is so there's nothing to go off of. We don't have an association just the reflection names.

**Comment by robinroestenburg** [comment]
Hi @eileencodes - our previous codebase was on 3.0.17 I believe. Note sure why the script also fails on that codebase, but I don't think it is worthwhile to investigate further (or go down the rabbithole any further ;)).

I agree with you, I don't think `Comment.reflect_on_association(:parent).klass` should return `Post`. If you want to know the actual parent, it should be done at runtime using an instance of `Comment`.

I am closing the issue.
