### ISSUE TITLE
Bug: Counter cache not working for polymorphic relationship

### ISSUE THREAD

**Issue by nneal** [rails/rails#16407]
When using counter_cache with Rails' polymorphic relationship, the `increment` part of the counter_cache does not work. Decrement, on the other hand, does work.

Example:

```ruby
require 'active_record'
require 'minitest/autorun'
require 'sqlite3'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection 'sqlite3::memory:'

ActiveRecord::Schema.define do
  create_table(:upvotes) do |t|
    t.integer :upvotable_id
    t.string :upvotable_type
  end

  create_table(:comments) do |t|
    t.integer :upvotes_count, default: 0
  end
end

class Upvote < ActiveRecord::Base
  belongs_to :upvotable, counter_cache: true, polymorphic: true
end

class Comment < ActiveRecord::Base
  has_many :upvotes, as: :upvotable
end

class BugTest < Minitest::Test
  def test_counter_cache_increment
    upvote = Upvote.create!
    comment = Comment.create!

    assert_equal 0, comment.reload.upvotes_count.to_i
    comment.upvotes << upvote
    assert_equal 1, comment.reload.upvotes_count # fails here
  end

  def test_counter_cache_decrement
    comment = Comment.create!
    comment.upvotes << Upvote.create!

    comment.upvotes.first.destroy

    assert_equal 0, comment.reload.upvotes_count # fails here
  end
end
```

**Comment by jcode** [comment]
what's the status on this?

**Comment by rafaelfranca** [comment]
@jcode open :smile:

**Comment by Jarred-Sumner** [comment]
:cry:

**Comment by u2** [comment]
http://stackoverflow.com/questions/15725386/rails-has-many-through-polymorphic-counter-cache
> 
My suggestion would be to manually increment or decrement your counter cache in an after_commit callback so that you can test if the record was persisted and it updates outside of the transaction. This is because it will make your code more explicit, and less mysterious on how and when the cache is updated or invalidated.
> 
Also manually updating the cache gives you extra flexibility if for example you wanted to give some users more authority when they agree or disagree with a comment (e.g. karma systems).

**Comment by huobazi** [comment]
+1

**Comment by sgrif** [comment]
This has been fixed on master, but I will not be backporting to older versions of Rails. See https://github.com/rails/rails/pull/16445#issuecomment-122709166 for the reasoning.

**Comment by fatuhoku** [comment]
Has this been fixed on 4.2.5?

**Comment by dmitry** [comment]
@fatuhoku looks like it wasn't backported to the 4.x: https://github.com/rails/rails/commit/6765d4874e7afaa8da0c7790710fe43726ef412c

**Comment by shlok007** [comment]
@sgrif any update on this? :slightly_smiling_face:
