### ISSUE TITLE
No extensions in structure.sql when schema_search_path is defined

### ISSUE THREAD

**Issue by jimmykarily** [rails/rails#17157]
The rake task ```db:structure:dump``` is running [this](https://github.com/rails/rails/blob/9c6c5aa9297883cea779839299b08a2ee4548856/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L54) command to dump to database schema to the structure.sql file. There is a problem though, when schema_search_path is defined. When passing ```--schema``` flags to pg_dump extensions are skipped (not sure why) no matter which schema they live on. 

I am using the pg_trgm extension (and others) and I have indexes that use this extension. Commands to create those indexes are dumped in the file but the extension itself is missing. This way rake tasks that create the test database generate errors (non blocking though). If I remove the ```--schema``` flags from the pg_dump command everything is dumped correctly but I'm not sure if that will suit everybody. 

Versions:
Postgres 9.3.5
Rails 4.0.10

**Comment by rywall** [comment]
Some extra information I provided in a accidental duplicate ticket (#17261):

If the user has specified a schema_search_path and also has extensions, the resulting pg_dump call generated by rake db:structure:dump includes the --schema flag which means that no CREATE EXTENSION statements will be created in the resulting structure.sql. According to the pg_dump documentation:

> When --schema is specified, pg_dump makes no attempt to dump any other database objects that the selected schema(s) might depend upon. Therefore, there is no guarantee that the results of a specific-schema dump can be successfully restored by themselves into a clean database.

This will most likely cause any attempts to load this file to fail.

I'm not sure what the best solution is in this case... In my opinion, it would be better to disregard the schema_search_path and dump the structure of all schemas rather than create invalid SQL dumps. 

Thoughts?

**Comment by jimmykarily** [comment]
The problem is that schema_search_path configuration has two responsibilities:
- Defines the postgres search path
- Defines what schemas are dumped with pg_dump

so if you want the first one, you are forced to define the second one too (with the described consequences). My only concern on what you propose is that some people might be using the schema_search_path to exclude some schemas from the dump or, even worse, to exclude the "other database objects that the selected schema(s) might depend upon" as described in the documentation above.

The safest way to go imho, is to add one more configuration option which, when it exists, will define whether the dump should include only the search path schemas or everything. This way we will have an option to separate the two responsibilities if so desired. I would prefer a cleaner solution but that might break apps depending on the existing functionality.

**Comment by rywall** [comment]
I like this idea. A configuration option would allow it to be backwards compatible while still providing users who run into this problem with a solution. @senny would you accept a pull request that adds an option? Something like:
```ruby
config.active_record.dump_all_schemas = true
```

**Comment by senny** [comment]
@rywall This seems like a reasonable solution, we could use a more general option name and symbols for values:

```ruby
config.active_record.dump_schemas = :all
config.active_record.dump_schemas = :schema_search_path
# not saying we should support the array right now but it would be a possibility if we decide to do that later on
config.active_record.dump_schemas = ["schema_1", "schema_2"]
```

what do you think?

**Comment by rywall** [comment]
Perfect :clap: :smile:

**Comment by jimmykarily** [comment]
@rywall feel free to send a pull request, I appreciate it.

**Comment by maca** [comment]
In addition to defining `dump_schemas` configuration it would be nice to be able to have an `exclude_schemas` configuration.

`pg_dump` has a `--exclude-schema` argument that accepts an expression with wildcards and schemas matching the expression will not be dumped.

I am working on a multitenant app using postgres schemas, specifying a schema to dump won't work for me because extensions are not included in the dump. 

I had monkey patched ActiveRecord::Tasks::PostgreSQLDatabaseTasks as follows: https://gist.github.com/maca/1b9af55dc49109b17e0c, hardcoding --exclude-schema='tenants*'
since I have a schema for each tenant, and whenever I dump it will also include the schemas for tenants created in the development db.

**Comment by senny** [comment]
@maca thanks for your insights. The best place to discuss a feature is the [ruby-on-rails core mailing list](https://groups.google.com/d/forum/rubyonrails-core).

I think it would be wise to discuss how this addition could look before submitting a PR. I wonder wether we should just introduce a new option or make it that the users have more control over the specific flags passed to `pg_dump`.

**Comment by maca** [comment]
Thanks @senny I will write to the mailing list

**Comment by LorneCurrieHomes** [comment]
Is there any traction on this issue?

**Comment by Ch4s3** [comment]
What's the status on this?

**Comment by LorneCurrie** [comment]
Looks like the code fix for this was put into Rails v5.0.0.  Is there a way we can add it to Rails v4.2.9/10?

**Comment by agnessa** [comment]
I don't think it is possible to exclude schemas using the `--exclude-schema` switch as @maca suggested, which is the only way to dump without selected schemas but with all the extensions. I couldn't find a relevant thread on the mailing list, I wonder if this was ever followed up?

**Comment by Aquaj** [comment]
I was looking for a way to get a `structure.sql` with `CREATE EXTENSION`s but without a specific schema (so a combination of `config.active_record.dump_schemas = :all` and `--exclude-schema`).

I don't know if @maca's suggestion was followed up on but if you need to use `--exclude-schema`, @rainhead's [comment](https://github.com/rails/rails/pull/19347#issuecomment-337054480) in #19347 provides a way to do so and worked great.
