### ISSUE TITLE
ActiveRecord attempting to autosave empty associated records after failed transactions

### ISSUE THREAD

**Issue by moserrya** [rails/rails#17570]
The issue happens when creating an associated record in a transaction and that transaction fails. Models for this example:

```ruby
class Person < ActiveRecord::Base
  validates_presence_of :name
  has_many :feelings
end

class Feeling < ActiveRecord::Base
  # :person_id, :description
end
```

Let's create a transaction wherein a `person` gets a new `feeling`:

```ruby
person = Person.find(1)
person.transaction do
  person.feelings.create!(description: 'kaboom', size: 'large')
  person.update!(name: nil)
end
rescue ActiveRecord::AutosaveAssociation
person.name = 'Biglet'
person.save
```
 
The `feeling` is rightly rolled back when `person.update!` fails. However, if we rescue from the exception in our transaction block and call another `save` on the same `person` object later, it attempts (or succeeds) to autosave a new `Feeling`, but with all columns nulled out. Cannot imagine this is the correct behavior. Wanted to verify this is in fact a bug and discuss the correct behavior before I go about creating a PR.

Reproduced with AR 4.0.5, 4.1.7, 4.2.0.beta4

**Comment by yoongkang** [comment]
I can confirm that this still occurs on master, but I don't think it's necessarily a bug. A transaction is supposed to rollback the state of the database upon an exception, but not the state of an object's instance data.

From the docs for [Transactions](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html):

>Exceptions will force a ROLLBACK that returns the database to the state before the transaction began. Be aware, though, that the objects will not have their instance data returned to their pre-transactional state.

It appears that this behaviour has been around for a very long time, possibly since Rails was released.
