### ISSUE TITLE
file_field raises error when is the only input on the form and the form is sent empty

### ISSUE THREAD

**Issue by maurogeorge** [rails/rails#17947]
Today if the only input we have in a form is a input type file like this:

```slim
= form_for @document do |f|
  = f.label :image
  = f.file_field :image
  = f.button :submit
```
And we try to submit without fill the image, we got a `ActionController::ParameterMissing - param is missing or the value is empty: document` since nothing is sent on the form.

The data is sent like

```
Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "button"=>""}
```

In the controller the strong parameter is like:

```ruby
def document_params
  params.require(:document).permit(:image)
end
```

To fix this I created a `hidden_field_tag`.

```ruby
= form_for @document do |f|
  = hidden_field_tag 'document[image]'
  = f.file_field :image
  = f.button :submit
```

The data is sent like:

```
Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "document"=>{"image"=>""}, "button"=>""}  
```

With the `hiddent tag` if the user sent the form without fill any info I show a error message over a error 500. My only field on this form is the image, probably this is a edge case.

The same behavior occurs with `collection_radio_buttons`.

Do you guys think make sense add this input hidden on `file_field`?

Ref https://github.com/plataformatec/simple_form/issues/1153

**Comment by jnicklas** [comment]
I realize that I'm a bit late to the party on this one. But I'd like to make an argument against this feature.

I would argue that file fields are fundamentally different than checkboxes and multi-selects, and that this change represents a very, very breaking change, which I believe has not really been considered. Let me explain.

When a checkbox appears on a page, I have the option of checking or unchecking it. I expect the behaviour to be that if I uncheck the box, and submit the form, the result will be that the model is updated and toggled to `false`. From this perspective, adding a hidden field to checkboxes in Rails makes perfect sense, because if Rails didn't we'd have behaviour that the user would not expect.

The same is true for multi selects. If a user clears all selections in the multi select box and submits the form, they expect that it will be cleared.

So how about a file field? File fields cannot display the current value of the field when the page is loaded, and they cannot be cleared in the same way that a checkbox or multi select can. Imagine a form which contains name and avatar fields. If the user loads this form, changes his name and does absolutely *nothing* with the avatar field, what would they expect to happen? From every website they have ever used, they would expect the avatar *not* to change. They do not expect to have to attach their current avatar image again, because that is the only way to preserve the current state. This is a fundamental limitation of file input fields, and it makes no sense to break it in such a fashion.

This behaviour is fundamentally wrong, and against what a user expects will happen. The correct behaviour when a file field with no file attached is submitted is to *do nothing*.

The correct way to solve the original issue is to expect that `document` may not be submitted at all and use `params.fetch(:document, {})` instead of `params.require(:document)`.

Additionally it will break just about every file upload plugin, because they do not expect to suddenly be receiving empty strings.

**Comment by jnicklas** [comment]
(and invoking "but it caused an error in production" is not a valid argument, it just means you didn't test it thoroughly enough)

**Comment by janko-m** [comment]
I back up @jnicklas and his explanation on why this change should be reverted. If you have a form with only a file field, you should just use strong_parameters' less strict API (if one exists), the one where `params.require(:document).permit(:image)` would return an empty hash instead of raising an error for missing `image` query parameter.

This change breaks both [Refile](https://github.com/refile/refile) and [Shrine](https://github.com/janko-m/shrine).

**Comment by rafaelfranca** [comment]
@janko-m @jnicklas could you open an issue so we can track the fix for it?

**Comment by eileencodes** [comment]
The change has been reverted for the next Rails 5 release in https://github.com/rails/rails/commit/9d441579247b28979539d117b730548afa12fefb

**Comment by janko-m** [comment]
Thank you so much, @eileencodes!
