### ISSUE TITLE
"rails generate plugin gems/engine --full" fails at vendor_app test/dummy

### ISSUE THREAD

**Issue by sanderhahn** [rails/rails#18073]
# inside a new rails named "app"

$ rails generate plugin gems/engine --full
      create
      create  README.rdoc
...
  vendor_app  test/dummy
Invalid application name app, constant App is already in use. Please choose another application name.

**Comment by RISCfuture** [comment]
This issue should be reopened.  Running `rails generate plugin` to generate engines inside a Rails app should not create namespace conflicts.

Currently, generating an engine runs the `rails new` action to generate the `test/dummy` directory, but that fails because the namespace is already in use. Well of course it's in use -- the script is attempting to create a dummy version of the engine's parent application for testing purposes. This should not result in failure.

So as it stands, currently the way to generate engines for an application, according to the Rails Guides, results in an error that shouldn't be there.
