### ISSUE TITLE
belongs_to should default to required: true

### ISSUE THREAD

**Issue by dhh** [rails/rails#18233]
Almost every belongs_to declaration seems to be a required association. It's rare that you allow your foreign key to be nil. So let's have required: true be the default and required: false be the optional turn-off.

**Comment by dhh** [comment]
@simi still interested in finishing this up?

**Comment by simi** [comment]
Sure. Is the global switch good way how to implement this? Should it be turned on for new applications?

**Comment by dhh** [comment]
Awesome. Yes and yes.

**Comment by dhh** [comment]
@simi Any update on this?

**Comment by simi** [comment]
Sure. PR coming soon.

**Comment by simi** [comment]
@dhh I spent some time with this and I think @al2o3cr is right here. We should deprecate `required: true` and add `optional: true`. 

@sgrif Keyword arguments make sense here also, but it is not trivial change and all association macros should be updated also.

**Comment by dhh** [comment]
Agree, `optional: true` is the way to go :+1:.

**Comment by egilburg** [comment]
How feasible would it be do determine requirement based on db schema?

We are (or should be) encouraging good DB design for maintaining referential integrity instead of solely relying on validations which are not as consistent (e.g. model changes in future, application level bugs, batch jobs, performance-sensitive low-level updates, etc.

As such, if db table has `null: false` on a `belongs_to` field, it implies `required:true` on model, otherwise not. WDYT?

**Comment by dhh** [comment]
Not keen on tying this together. Lots of schemas out there that aren’t likely to change soon, and this change still makes sense for them.

**Comment by simi** [comment]
@egilburg I think this can be added to gems like [schema_validations](https://github.com/SchemaPlus/schema_validations).

**Comment by bwheeler96** [comment]
I realize I'm a little late to the party on this one, but what about the concern that now rails associations either fall into a "required" category, or a "not required" category. 

It seems like this change is now adding opinions to how I should model my data, whereas previously rails just gave me the tools to create whatever unopinionated data model I wanted. Would it not make more sense to relegate this functionality to a gem or a new method, something along the lines of `child_of :model`. 

Otherwise how are we deciding which associations are "required" and which are "not required". Has one *sounds* like it should be required (and belongs_to is almost always the complement of has_one). Also if possible it would be nice to see a deprecation warning included with the validation failure message

**Comment by dhh** [comment]
Party is over months ago. Rails is opinionated software. We always had conventions about how your data should be modeled and what the defaults were. This matches more of the use, more of the time.

**Comment by dhh** [comment]
http://rubyonrails.org/doctrine/#convention-over-configuration is a helpful guide on how these decisions are made and will continue to be made.

**Comment by sandeepravi** [comment]
This seems to be causing an issue with accepts_nested_attributes_for . If I want to create the child object along with the parent, it seems to throwing an error in the child model that the parent has to exist. 

This seems to be a pretty standard thing to do, right? Is there any workaround for this? Or am I missing something?

**Comment by dhh** [comment]
@sandeepravi I'd suggest adding `required: false` to child models in that case. Not a big fan of `accepts_nested_attributes_for` anyway and we should figure out a long-term path away from that. But saying `required: false` will return things to how they were for you.

**Comment by sandeepravi** [comment]
@dhh , yeah right now I've made it optional so it seems to work. But I would rather keep it required and not use accepts_nested_attributes.

Yeah, nested_attributes in multiple places can get messed up quite soon. You generally prefer to have form objects or just plain POROs?

**Comment by dhh** [comment]
I like aggregation through regular Ruby objects. For example, we have a Signup model that's just a Ruby object orchestrating the build process. So I'd give that a go!

**Comment by sandeepravi** [comment]
yeah, it seems the simplest option as well.

Cool, Thanks!

**Comment by ClaudioCarmeli** [comment]
@dhh Is there a recommended method for cases where you still need to validate the presence of the child objects on the parent object? I am using `optional: true` but that makes my validation tests pass even though the parents objects can be created without any of their "required" child objects.

**Comment by bluengreen** [comment]
@ClaudioCarmeli - a year of silence :(  

Exactly why rails is losing popularity. Brilliant idea - lets change default behavior that has been core for 12 years. Not the way to win the hearts and minds and expand adoption. Also not much in the way of solutions for fixing the issues with nested attributes using `accepts_nested_attributes_for`. Granted I try not to use them, but there are a ton of legacy projects from the glory days of jquery that still do. I mean, that is, other than touch every association. Also found that the global config to return to the previous behavior, doesn't seem to work for gems that add belongs_to associations. Dunno maybe it was just bewilderment and the lack of sleep staying up late trying to find and "fix" this problem and there may be other solutions. But must say - just another stupid "rails way" idea.
