### ISSUE TITLE
password input should by default add html argument autocomplete="off"

### ISSUE THREAD

**Issue by equivalent** [rails/rails#18453]
Just a security suggestion: Should the `password_field`, `password_field_tag` by default set the `autocomplete="off"` argument on password input ?

( as previously suggested in this discussion for `simple_form`: https://github.com/plataformatec/simple_form/issues/1191 )  

There is no real point not disabling it by default as newer browsers (Internet Explorer > 11, Mozilla Firefox > 30, Google Chrome > 34) no longer support HTML 'autocomplete' on password field

http://msdn.microsoft.com/en-us/library/ie/ms533486
https://bugzilla.mozilla.org/show_bug.cgi?id=956906
http://googlechromereleases.blogspot.ro/2014/04/stable-channel-update.html
...and it's just risk for old browsers

I can create Pull request for this if agreed.

**Comment by simi** [comment]
Good idea! :+1:

**Comment by matthewd** [comment]
I don't understand. Per your links, all the major browser developers have agreed that `autocomplete="off"` on password fields is such a bad idea that they now ignore it even if it's present.

Why would we consider that a reason to *add* it?

**Comment by justincase** [comment]
Have to agree with matthewd here. Old browsers are a security risk anyway.

**Comment by nateberkopec** [comment]
IE < 11 is not an insignificant portion of the browser world right now. I'm in support of this change.

**Comment by equivalent** [comment]
@matthewd @justincase In ideal world no-one would use an old browser, but real world is not the case :smile:  I agree we both of you that we should not encourage backporting of new features for old browsers but we should definitley protect security issuse that may come with using old browser

**Comment by simi** [comment]
There is still workaround for IE 5..8 in Rails (utf8 parameter, formerly mr. snowman ☃). It is not hard to maintain it. I think this is similar fix and should be part of the Rails

**Comment by matthewd** [comment]
@equivalent that seems to be a response to @justincase, but not to me: he said "agree with matthewd", then went on to say something entirely unrelated to my point.

Maybe I'm the one misunderstanding the situation, but it is my belief that you're advocating making old browsers behave in a different way from newer browsers.

Specifically, because people were misguidedly adding `autocomplete="off"` to password fields, newer browsers ignore that attribute, and behave the same way that older browsers did when the attribute was not present.

You're suggesting that we start adding that attribute, thereby changing the behaviour of older browsers *away* from the behaviour of newer browsers, and instead towards the behaviour that browser developers consider so poor that they now actively ignore the markup.

----

I'm feeling pretty lonely over here, because everyone else seems to believe that new browsers now behave like `autocomplete="off"` under all conditions, when my reading (and re-reading) of the linked documents clearly states the opposite.

**Comment by nateberkopec** [comment]
@matthewd indeed. I went back and read the linked documents again and now I'm confused as well. A helpful summary from the bottom of the Mozilla link:

Summary of the change, so people don't have to wade through a long discussion:

> Summary of the change, so people don't have to wade through a long discussion:
>
> - This change makes it so that `autocomplete=off` does not stop the Password Manager from working. Normal form autofill can be disabled as usual.
> - The password manager *always* prompts if it wants to save a password. Passwords are not saved without permission from the user.
> - We are the third browser to implement this change, after IE and Chrome.
> - This can be undone locally by flipping the `signon.storeWhenAutocompleteOff` pref (from about:config) off.
> - The rationale behind this change was the widespread abuse of the `autocomplete` attribute to prevent password saving where no prevention is required. This change gives users full control over password saving, without compromising on security (again, the user is always prompted).

The above quote suggests that "autocomplete=off" is a no-op in the browser versions stated in OP, and in browser versions <= will disable (or attempt to disable) password managers from autocompleting passwords. If that is correct and I understand all of this, then I am *not* in favor of this change.

**Comment by equivalent** [comment]
I do appologize @matthewd  (and  @justincase if that's the case) I thought that the comment was purely about "suporting older browsers in terms of new features don't need to be implemented as no one suppose to use them", I didn't realize you mean the implication to behavior of other browsers. 

so yes that's a valid point 

but to be honest even if it was the case that suddenly the password manager will stop filling in passwords (which @nateberkopec kindly explained is not the case) I would still wote for this change as security concern is higher then breaking exisiting depricated password manage feature workflow 

+ developers still can implement `autocompete="on"` on password fields (horible idea b.t.w.) if they choose to.

**Comment by equivalent** [comment]
...one more solution is that I would change my PR so that Rails will provide configuration option something like `disable_password_autocomplete` would be by defalt `true` and developer may turn this off.

**Comment by jrochkind** [comment]
It seems to be controversial advice to autocomplete=off on old browsers, precisely because it will disable password managers. https://blog.0xbadc0de.be/archives/124

I'm confused what this change is meant to accomplish.  On newer browsers, it will do nothing?  And an older browsers, it will disable password managers, which many people consider a bad thing to do?   That does not make the change seem attractive. But I may have it wrong. 

@equivalent, can you explain what you believe `autcomplete=off` this will accomplish on 'old' and 'new' browsers, and why those things are advisable? Possibly including citations supporting?

**Comment by nateberkopec** [comment]
> Rails will provide configuration option ...

I understand you're trying to make this seems less controversial, but this is something that should *just work*. Secure defaults are a good thing, and as an application developer, I want Rails to be as secure as possible right from the get-go without any input from me. A million twiddly config knobs is probably the worst possible solution for application security. Instead, let's try to agree on what the secure default is here.

My understanding is that "autocomplete=off" on "old" browsers (IE <= 11, Firefox <= 30, Chrome <= 34) will disable the password manager, which many people consider a "bad thing" since password managers are a great way for users to have many secure passwords. On "new" browsers, the setting will do nothing.

**Comment by equivalent** [comment]
Ok, after reading the article that @jrochkind I'm starting to see that I may be wrong here (and what everyone was trying to tell me the entire time) ...would want to here more opinions on this

@nateberkopec  I'm still keen on sort of `:paranoid => true` option for Rails config  that would implement this (and maybe other paranoid security checks) becouse this is one of those things you may necessary know if you building bulletproof bank-like system. But I'm starting to  agree that the autocomplete="off" may not be the best idea for all websites.

**Comment by equivalent** [comment]
Friend of my ( @tom-lord ) mentioned in a private dissussion a story of one company where they had `autocomplete=off` on login passwords and not on the login username. The way how lazy people mistreated this was that they were saving username+password to browser password manager under a username and just cut+paste the password.  

After reading several other articles and this story I fully see that I'm  wrong. I'm trying to help by introducing new bigger problem. This should be definitelly a browser decision not app decision.

I'm switching my opinion against my PR :)  ...but would like to hear more opinions

**Comment by justincase** [comment]
@equivalent Ingenious, haha. I didn't dig that deep though I understand the cons much better now. Thanks.

**Comment by chancancode** [comment]
Agree with @matthewd's interpretation, so I don't think there's anything we need to do here.

**Comment by equivalent** [comment]
@justincase  :)  this was one of those mornings where I was like "oh! I have a great idea for really simple, straight forward, one line code change that will be benefit without no side effect at all "   ...Nah, I should have coffee first, ...or vodka :)     

yep, never I though there could be so much "why" around that :)
