### ISSUE TITLE
Postgres's unnest query not returning as expected in array column

### ISSUE THREAD

**Issue by glaucocustodio** [rails/rails#18514]
Hi guys, I was migrating a project from 4.1.9 to 4.2.0 and a test related to a query using postgres's unnest function in an array column did not pass in the latest version.

I have searched for similar problems but I did not find, so I created this gist https://gist.github.com/glaucocustodio/b7d643b401e37ddd2045 with the scenario, I would like to know if it's a bug or not.

Thank you.

**Comment by sgrif** [comment]
I did make a conscious decision to have the type of the column on the AR class always override what the database says it should be. https://github.com/rails/rails/commit/da3b4b61732ca4717c99e680ebaf2af43e67ca74

This is because once the attributes API is made public we don't want the type you specified to get trampled by what the database thinks it should be.

That doesn't mean that this isn't a bug, but my vote would be for not supporting this use case. The work around is to name your select something other than `id`. @rafaelfranca WDYT?

**Comment by rafaelfranca** [comment]
Make a lot of sense. `id` is and should be what the database says it is.

**Comment by rafaelfranca** [comment]
I mean, the mapped type in AR say what it is.

**Comment by glaucocustodio** [comment]
Ok, I got it. What do you recommend then? What would be the best approach to pull it off?

**Comment by sgrif** [comment]
`select("unnest(tags) as unnest_tags").map(&:unnest_tags).uniq` would be the workaround in the general case.

**Comment by sgrif** [comment]
For your specific code, I'd also recommend rewriting it as: `pluck('unnest(tags)').uniq` or as `pluck('DISTINCT unnest(tags)')` if you don't need specific ordering

**Comment by glaucocustodio** [comment]
Great! I guess more people may be using some code similar with the one in gist.. I did not find any example like the one showed by @sgrif at http://edgeguides.rubyonrails.org/active_record_querying.html. Would not be nice if I include some example like that there?

**Comment by sgrif** [comment]
I'm not sure whether we need a specific example like that, since the method itself is covered here: http://edgeguides.rubyonrails.org/active_record_querying.html#pluck, and in general any method in AR can also take a SQL string. However, if you feel strongly about it, I encourage you to open a PR adding some examples
