### ISSUE TITLE
Inconsistent querying of serialized attibutes

### ISSUE THREAD

**Issue by MGotink** [rails/rails#18582]
With rails 4.2, when you query serialized attributes the result differs depending on whether you pass a single value or an array of values.

To reproduce:
 - create a new project and set up a scaffold: `rails g scaffold Post content`
 - add `serialize :content` to the post model
 - open the rails console
 - `Post.new(content: 'new post').save`
 - `Post.where(content: 'new post').count`, output: `SELECT "posts".* FROM "posts" WHERE "posts"."content" = ?  [["content", "--- new post\n...\n"]]`
 - `Post.where(content: ['new post']).count`, output: `SELECT "posts".* FROM "posts" WHERE "posts"."content" = 'new post'`

I would expect the last query to produce the same results as the former.

**Comment by sgrif** [comment]
Yes, I would as well. I wouldn't qualify this as a bug that can be fixed in older versions, since we don't have any documentation on how custom types affect `where` (and backporting the fix is not plausible due  the complexity of the code that was required to fix this).

**Comment by sgrif** [comment]
This is already fixed on master

**Comment by sgrif** [comment]
Since we usually mention the issue in the commit, this was fixed by:

https://github.com/rails/rails/compare/1d6bb77636aeec734079f63e1c14429b34e79ed9...de0cfd27a545
https://github.com/rails/rails/compare/266ff70...2223f49
https://github.com/rails/arel/commit/008445d6fd5f825d9b445ac75a7be67f0f7ab52c
https://github.com/rails/arel/commit/6160bfbda1d1781c3b08a33ec4955f170e95be11

**Comment by MGotink** [comment]
I'll work around it until rails 5 is released, thanks!
