### ISSUE TITLE
Sequence name passed to ActiveRecord::Relation#insert is  always nil

### ISSUE THREAD

**Issue by numidiasoft** [rails/rails#18611]
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L69

Configuration : 
 - activerecord-4.1.8
 - postgres 9.3

When i try to redefine the sequence_name value in an ActiveRecord class like below :

```ruby
class Account < ActiveRecord::Base
 self.sequence_name  = "public.accounts_id_seq"
end
```

The sequence name does not change, in fact the sequence name is always recalculated in https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L87

**Comment by jvanbaarsen** [comment]
@numidiasoft Can you provide reproduction steps?

**Comment by andyatkinson** [comment]
@numidiasoft I can look into this. It seems like there is somewhere a `sequence_name` argument is not being passed through.

**Comment by andyatkinson** [comment]
@senny @tardate Hello! I was wondering if either of you would be available to help me out with this issue? I believe I have a good starting point for a failing test, and an understanding of creating new sequences on an existing table. I have written out the SQL for this with postgres (can share if interested).

I believe the goal of the original poster here is to be able to specify the new sequence name, and have this `create` and `alter` happen in the background, perhaps on the next `insert`. I'm not sure if that is happening already in Rails. That is part of what I need help on.

I would be a new contributor to Rails so I would appreciate any help you could provide. I'm available to pair up remotely. I am messaging you because I git blamed the test file and you both had made commits in that area of the code. If you could suggest someone else that may be more appropriate to help me I would appreciate that too. Thanks for your time!

**Comment by senny** [comment]
@andyatkinson thank you for taking time to help Rails :yellow_heart: 

I went over the issue and got hung up on:

> I believe the goal of the original poster here is to be able to specify the new sequence name, and have this create and alter happen in the background, perhaps on the next insert.

Are you saying that `sequence_name = ""` in your model would automatically translate into DDL statements being run? If so, that's not something we are going to support. In ActiveRecord, migrations are the things that change the schema. However it's important to note that migrations do not know about the models and therefore do not use their configuration.

Reading the issue I suggest to continue as follows:
* Would be good to have a reproduction using [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) as a starting point. This will help to get everyone on the same page what the issue is about.
* Is it possible to use the migration DSL to create a table with a non standard sequence name?
* Do models with `sequence_name=` respect that setup?

**Comment by andyatkinson** [comment]
@senny Thanks for responding with details, much appreciated!

> * Would be good to have a reproduction using this script as a starting point. This will help to get everyone on the same page what the issue is about.

I have started a [script for 18611](https://github.com/andyatkinson/18611_issue/blob/master/app.rb) but haven't produced a failure case yet.

> * Is it possible to use the migration DSL to create a table with a non standard sequence name?

I'm not sure about specifying a non-standard sequence at table create time, but it is definitely possible to create one and then alter the table to use it.

> * Do models with sequence_name= respect that setup?

The script shows me that things are working as expected. By altering the table to specify a new sequence, then specifying the sequence name in the model, the ID value on the next record reflects that the new sequence was used.

That's as far as I've gotten on this issue at the moment.

**Comment by senny** [comment]
I still don't understand the actual problem. A failing script would be a big step to move this forward.

Of course you can use raw SQL in your migrations to create a non-default setup with sequences. I vaguely remember a Github discussion about it. I thought that use-case is working fine though. I'll see if I can dig it up.
