### ISSUE TITLE
All rails cli commands not working

### ISSUE THREAD

**Issue by maclover7** [rails/rails#18745]
For seemingly no reason a Rails 4.2.0 app I am working on (github: hackcentral/hackcentral) has all Rails commands not working. It displays the usage template in the terminal, small excerpt:

```shell
Usage:
  rails new APP_PATH [options]
```
I deleted the directory, uninstalled Ruby and Rails. Then I installed Ruby 2.1.5 via rbenv and Rails 4.2.0 via 'gem install', and then re-git-cloned the directory and ran bundle install. Rake db:migrate and bundle exec puma still work for the app though, not sure what is causing this.

Not sure how to solve this problem, any help is appreciated.

**Comment by yawboakye** [comment]
What's the command you ran? Here's the [documentation](http://guides.rubyonrails.org/command_line.html) on the Rails command line tool if it helps. But pay attention to what you type, there could be a typo hiding in there.

**Comment by vladzzag** [comment]
yawboakye, copy his app and run development server.

**Comment by yawboakye** [comment]
@maclover7 Turns out the problem is because you don't have a `bin/rails` file so the directory wasn't identified as a Rails app. Run `rake rails:update:bin` to generate the required (or default) binstubs. It includes `rake`, `rails`, `bundle`, and `setup`.

[This code file](https://github.com/rails/rails/blob/master/railties/lib/rails/app_rails_loader.rb) explains how the `rails` command determines whether or not a directory is a Rails project.

**Comment by yawboakye** [comment]
@maclover7 Also it's good practice to include your Ruby version in your Gemfile. You should commit your .ruby-version file too.

**Comment by sgrif** [comment]
This question is more appropriate for stack overflow, as it isn't a bug in Rails.

**Comment by maclover7** [comment]
Thank you very much @yawboakye, running 'rake rails:update:bin' solved my problem. Issue is resolved.

**Comment by yawboakye** [comment]
@maclover7 add the `bin` directory (and its contents) to git so anyone cloning the project won't run into similar errors. It's the recommended thing to do.
