### ISSUE TITLE
bigint column type being parsed as regular integer in sqlite3

### ISSUE THREAD

**Issue by kevgathuku** [rails/rails#18787]
I am trying to create an sqlite table on which one of the columns is a bigint. However, this is always getting parsed as a normal integer and creation of records is failing with the following error
`RangeError: 70026099423600 is out of range for ActiveRecord::Type::Integer with limit 4
`
Here is a reproduction script:
```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.0'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :logs, force: true do |t|
    t.string  :msg,    :null => false
    t.string  :level,  :null => false
    t.bigint  :thread_id
  end
end

class Log < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_bigint_parsing
    log = Log.create!(:msg => 'Debug message',:level => 'debug',:thread_id => '70026099423600')

    assert_equal 1, Log.count
  end
end
```

**Comment by borgand** [comment]
One could argue that it is more correct to set `limit: 8` to **all** SQLite3 `Integer` types, as per: https://www.sqlite.org/datatype3.html:

> INTEGER. The value is a signed integer, stored in 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.
> ...
> If the declared type contains the string "INT" then it is assigned INTEGER affinity.
> ...

That means that `INT`, `INTEGER`, `TINYINT`, `SMALLINT`, `MEDIUMINT`, `BIGINT`, `UNSIGNED BIG INT`, `INT2`, `INT8` all result in the datatype `INTEGER` and automatic limit up to 8 bytes.
**NB!**: the documentation does not mention `int4` but it is actually supported in a similar manner.

I would suggest that all integer types that do not explicitly state lower limit (i.e. `int`, `integer`, `int8` and `bigint`) should result in `limit: 8` as otherwise it might break expectations from the field type (with regards to the SQLite3 documentation).

This is relevant especially in the case where AR is not the creator of the database, thus the type definition might differ from what AR would assume.

**Comment by inspire22** [comment]
Is there any way to disable range checking?  It doesn't appear to be documented anywhere.

The feature seems quite prone to bugs, for example "smallint(5)" in a mysql database is read as "limit 2" for some reason.  The normal size for a smallint is 6, but I'm only storing zip-codes in it so it was 5.  Fixing the database isn't very easy with 20m rows...

**Comment by sgrif** [comment]
`SMALLINT` always has a limit of 2. MySQL just ignores the length and promotes the type for you. The correct way to write that would be `MEDIUMINT`

**Comment by sgrif** [comment]
See also: https://dev.mysql.com/doc/refman/5.1/en/integer-types.html

**Comment by inspire22** [comment]
Sorry, the issue seems to be that 91111 (a zip code) is raising the NotInRange error for length(2), when it should be (32767 or 65535 unsigned)

**Comment by sgrif** [comment]
91111 is greater than 65535 (which is the maximum value for an `UNSIGNED SMALLINT`).

**Comment by sgrif** [comment]
Also to answer your original question, there is no way to disable range checking, but using the attributes in Rails 5, you could set a larger range manually by adding

```
attribute :zip_code, :integer, limit: 8
```

In Rails 4.2 you could do the same (using a private, internal API, and standard warnings about doing that apply) with:

```
attribute :zip_code, Type::Integer.new(limit: 8)
```

**Comment by cenouro** [comment]
I have also had problems with Postgres. The migration with `t.integer :foo, limit: 2` ran fine but the schema generated was only `integer`. I'm using Rails 4.2.3.
