### ISSUE TITLE
rails 4.2 integer migration limit 4

### ISSUE THREAD

**Issue by richardrails** [rails/rails#18826]
why is DB limit for integer automatically only 4? Do you think that nobody has more than 10k records in tables? I mean foreign keys! This is not good idea.

from my schema.rb:
```
t.integer  "location_id",    limit: 4
```

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by glaszig** [comment]
@richardrails have you figure this out?

**Comment by rafaelfranca** [comment]
The reason is. It is a default, if you are not happy with the default just change it.

**Comment by glaszig** [comment]
in case anyone else will land here (this issue is among the first google links):

the cause of confusion here is that the unit for `limit` on integer columns is bytes. a limit of `nil`, `4`, `11` will all [yield `int(11)` in mysql](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L651) terms.

**Comment by veera** [comment]
@glaszig :+1:

**Comment by adamgeorgeson** [comment]
:+1: for @glaszig explanation on this.

**Comment by rodolfobandeira** [comment]
@glaszig Thank you for the clarification. 👍  
IMHO, its really odd having integers being represented in bytes and varchar in the number of characters.
