### ISSUE TITLE
Rails 4.2.0 - Very slow static file serving

### ISSUE THREAD

**Issue by jorge-marques** [rails/rails#18828]
Hi. I've updated a rails application to 4.2.0 and I've noticed a huge slowdown when serving static files in development mode. In particular, one .svg file that took less than a second to be downloaded in 4.1.9 is taking about 20s in 4.2.0. Reverting the project back to 4.1.9 makes everything run smoothly again.

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by jorge-marques** [comment]
@rafaelfranca Sorry, submitted the form accidentally.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by jorge-marques** [comment]
Here's the repo: github.com/jorge-marques/rails-4.2.0-slow-file-serving
I generated a rails 4.1.9 app, and added a page with a single .png image. It's taking about 60-70ms to download on my machine. I then upgraded to 4.2.0 and that same file is now it's taking up to 2s.

**Comment by rafaelfranca** [comment]
Cool! I'll take a look  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by mtarnovan** [comment]
I have the same issue. After adding some svg assets, some requests are unbearably slow. The Rails log hangs after outputting the first line `Started GET...` and the request takes 30+ seconds to finish, although when it finishes the last line shows normal render times (~100 ms or so).

**Comment by mtarnovan** [comment]
@jorge-marques what server are you using in development?

**Comment by jorge-marques** [comment]
@mtarnovan I'm using the default server, Webrick, if I'm not mistaken.

**Comment by mtarnovan** [comment]
I ran a dtruss on the ruby process when it got stuck again, and as far as I can tell it kept reloading the app over and over again. Could this be an issue with spring? I'll see if removing spring from the app solves the problem and report back.

**Comment by yann** [comment]
We encounter the same problem with a large base of static files in dev. The page takes a few minutes (instead of a few seconds in 4.1.6) to load and the CPU jumps to 100% during the load.

**Comment by noinkling** [comment]
Have been experiencing the same issue with my images (JPGs in my case). Using WEBrick (in an Ubuntu 14.04 Vagrant VM).

I'm also having a weird issue where occasionally WEBrick won't respond properly to `ctrl + c`. It'll say it's shutting down or whatever, then just sit there until I do a second `ctrl + c`, then it spits out an error with a trace. I only mention it here because it might be related. I'll try and get a copy of the trace if/when it happens again.

**Comment by jesseminer** [comment]
We're seeing the same issue with Puma, including the weird behavior around stopping the server that @noinkling described.

**Comment by vladimir-tikhonov** [comment]
Caused by [this](https://github.com/rack/rack/commit/ae78184e5c1fcf4ac133171ed4b47b0548cd9b44) commit in rack

**Comment by pixeltrix** [comment]
This is being caused by rack/rack@c5621e9 - it's setting an output buffer size of 5 which is ridiculously small.

**Comment by mtarnovan** [comment]
My issue seems to be unrelated to this. It only happens on some requests, and sometimes when reloading the console. I remove spring and it didn't solve the problem.

**Comment by pixeltrix** [comment]
@mtarnovan so you still get problems if you do `rails s --option OutputBufferSize=65536` ?

**Comment by mtarnovan** [comment]
@pixeltrix I'm using [pow](http://pow.cx/) so I'll have to check how to pass that option to it (if at all possible).

Still, I don't think this will solve my problem, as the same symptoms also appear when using `reload!` in the rails console. Dtracing the process shows the app endlessly requiring it's dependencies.

**Comment by pixeltrix** [comment]
@mtarnovan looks like we're not passing options down to the Rack hander so it won't work any way :cry:

**Comment by oskarpearson** [comment]
I had a look at this earlier - I think this ticket might be covering multiple issues that are now being bundled into one bug report.

There may be a different problem here - but it's impossible to tell without more debugging info.

@yann @mtarnovan @noinkling @jesseminer - could I trouble you to spend some time verifying that you definitely have exactly the same problem as @jorge-marques ? Building an empty repo or trying to re-create your issues with his repo above is a good start. (See my notes below about Virtualbox, though). You could then provide additional information or open new reports.

My reasoning is as follows:

1. The code repository supplied by @jorge-marques performs much much better once the buffer size is increased (the line of code that @pixeltrix referred to is commented out). That issue was directly related to https://github.com/rack/rack/pull/753/files - which changed the way the file is sent under webrick from one method to a different method.
2. The code repository supplied by @jorge-marques doesn't appear to show any delay on control-c (when using Docker on Vmware fusion), which then doesn't match the report by @noinkling 
3. The code repository supplied by @jorge-marques doesn't use Puma. The fix for the webrick problem is very webrick specific, and is unlikely to have the same root cause as @jesseminer which is about puma.

So there may be a different regression somewhere that's impacting everything else, but we need more info to be able to diagnose it.

# Code Changes

With the repo created by @jorge-marques  - and with a 10MB file added to it to make the change more visible:

Original rack-1.6.0 version (hot cache: 2nd curl run):
```shell
time curl -O -v http://localhost:3000/assets/large-file.dmp
...
real	0m6.250s
user	0m1.070s
sys	0m3.787s
```

With ``options[:OutputBufferSize] = 5`` commented out of rack-1.6.0/lib/rack/handler/webrick.rb (hot cache: 2nd curl):
```shell
...
real	0m0.122s
user	0m0.009s
sys	0m0.056s
```

# Virtualbox issues?

One thing to note - I had problems with VirtualBox shared folders a while back. Rails would recognise every asset file as having changed, and would re-render the asset pipeline on every page load.

I'm pretty sure this was related to VirtualBox not reflecting timestamps or similar on a shared folder, since replacing VirtualBox with Vmware Fusion made the problem go away.

If you're encountering problems under Virtualbox, please consider trying to replicate the issue on a native machine, or under Vmware Fusion. If this indeed the cause of the problems you are seeing, then please consider raising a separate bug request... or we can change the focus of this one.

**Comment by noinkling** [comment]
@oskarpearson 
Using @jorge-marques' repo:
````
time curl -O -v http://localhost:3000/assets/sonnet43.png
...
real    0m20.423s
user    0m7.985s
sys     0m7.328s
````
Subsequent requests give similar times.

Using the equivalent Rails 4.1.10 app:
````
time curl -O -v http://localhost:3000/assets/sonnet43.png
...
real    0m1.129s
user    0m0.005s
sys     0m0.044s
(first)

real    0m0.183s
user    0m0.015s
sys     0m0.044s
(subsequent)
````
Obviously my Rails 4.2 results are even slower even compared to other people, so Vbox shared folders may be having some effect, but keep in mind I'm using somewhat outdated hardware as well. It's a big change from 4.1 regardless.

How can you tell if all the assets are being reloaded with every request? For me, everything seems to be cached fine after the first load in the browser, and assets are served noticeably faster when they're unchanged vs when they're changed. Vbox shared folders might have its quirks but I would question its relevance here.

Regarding the issue about stopping the server: I can confirm it happens in 4.1 for me as well, I guess the issue only became apparent in 4.2 because before that nothing would load slow enough to have a need to interrupt it. I found a massive image so I could conceivably test it in 4.1 and yeah, same thing, so I guess it's an unrelated bug. Just to elaborate, it only occurs for me if interrupting the image load in the browser (pressing the stop button or navigating away - interrupting a curl request doesn't have the same effect).

**Comment by oskarpearson** [comment]
@noinkling is it possible that DNS on the vbox machine might not be working? DNS lookups often fail on multiples of 5, 10, or 20 seconds (or occasionally 75 seconds). If you ssh to the virtual box, can you ping www.google.com or similar without a long up-front delay? And does /etc/resolv.conf on virtualbox contain the right values? I had an occasional problem where if I switched from one physical network to another (work to home) virtualbox wouldn't detect the new DNS server IP.

In terms of re-render of the assets: correct handling of assets should return 304 not modified in the browser developer console. I was seeing them being reloaded from scratch every time.

**Comment by jesseminer** [comment]
Turns out my problem was related to the rails-dev-tweaks gem. It's supposed to skip reloading assets by default, so maybe something changed in Rails 4.2 that breaks whatever logic the gem uses to determine which files are assets. I added
```
config.dev_tweaks.autoload_rules do
  skip '/assets'
end
```
to development.rb and load times are back to normal.

Also, I've read that rails-dev-tweaks isn't needed in Rails 4, but assets still seemed to load faster with the gem than without it.

**Comment by noinkling** [comment]
@oskarpearson All that stuff is fine (and doesn't seem relevant to the difference between Rails 4.1 and 4.2). 304s are happening fine in both 4.1 and 4.2, it's just non-cached loads in 4.2 that are the issue, and only with WEBrick (as far as I can tell).

I'm not using `rails-dev-tweaks` (as you can see in my above post since I used @jorge-marques' repo).

**Comment by cycomachead** [comment]
I'm relatively new to Rails, so apologies in advance if I'm completely off base...

I'm currently seeing ~6-10 second load times in my Rails 4.2 app for static files being served from `public/`. However, my understanding is that this isn't related to the asset pipline at all, but i wasn't sure if the issue is still perhaps related? Currently I'm just serving the app using WEBrick.

The repo is here, if you'd like to take a look. The main file I've been trying to access is public/snap/index.html
https://github.com/snap-cloud/snap-cloud

FWIW, I've deployed the same app to Heroku, and the behavior is pretty much the same -- 6-10s load times. 

(I'll try to test on 4.1 though I'm having a bit of trouble downgrading, since this app initially started on 4.2.0)

**Comment by timsco** [comment]
I was using 4.1 with the rails_dev_tweaks gem and upgraded to 4.2 and noticed a slowdown with a lot of static assets. I have removed rails_dev_tweaks and the application load time seems to be back to normal.

**Comment by mahemoff** [comment]
"In terms of re-render of the assets: correct handling of assets should return 304"

@oskarpearson's comment reminds me to try enabling caching in the browser, as I had Chrome devtools disabling caching. This reduced much delay.

I was under the impression assets were output to public/ even in development mode (not pre-compiled, like in production, but generated on demand), but I'm not seeing them there, which is why enabling cache delivered the speedup. Is there a config setting to control whether files are generated on the fly in public?

**Comment by cycomachead** [comment]
> @cycomachead try change the relevant version of lib/rack/handler/webrick.rb and comment out the line that reads 'options[:OutputBufferSize] = 5'. Let us know if it solves your issue.

@oskarpearson I just tried this and reloaded a few times (no browser caching involved) and still saw 6-12s load times. So, no difference was made. Would it be worth filing a separate issue?

**Comment by mahemoff** [comment]
@cycomachead I wrote up some [asset loading gotchas](http://softwareas.com/speeding-up-rails-asset-loading-in-development-tips-and-gotchas/) after I had similar issues recently. It might help you find something missing from your setup. In particular, make sure your caching is enabled and working.

**Comment by scaryzet** [comment]
I'm experiencing the problem described in this issue.

@oskarpearson

> With options[:OutputBufferSize] = 5 commented out of rack-1.6.0/lib/rack/handler/webrick.rb

Commenting that line as suggested helped me a lot. Got like x100 speedup, serving times of static files went down from seconds to 20 ms and below.

**Comment by mahemoff** [comment]
Me too, seeing a massive speedup from commenting that out.

**Comment by noinkling** [comment]
Rack 1.6.1 seems to have fixed it (presumably due to the above commit) in the app that I used in my first example:
![Imgur](http://i.imgur.com/UmbfAQG.png)

However another test using @jorge-marques' repo (after updating to 1.6.1) shows no change using the [curl command from before](https://github.com/rails/rails/issues/18828#issuecomment-84722571). The Rack 1.5.x/Rails 4.1 result hasn't changed either.

**Comment by byroot** [comment]
Rack 1.6.2 have been release in June. I think this is resolved @rafaelfranca

**Comment by enwood** [comment]
In Rails 4.2.4, WRT jesseminer's comment above about using the rails-dev-tweaks gem, I'm noticing that there is a distinct difference in load times between specifying  ```skip :assets``` and ```skip '/assets'```.

```skip :assets``` seems to have no effect, but ```skip '/assets'``` definitely accelerates page loading. 

Odd?

**Comment by ronyvieira** [comment]
For Virtualbox i resolved it using rsync for my shared folder...

For vagrant just add this config to your Vagrantfile and it will work fine
```
config.vm.synced_folder ".", "/vagrant", type: "rsync"
```

**Comment by jayeff** [comment]
@ronyvieira FYI if you are not aware of this: Rsync is one way only (from host to guest machine). So you maybe need to sync some files from the vagrant box back to your host manually (eg. Gemfile.lock after updating dependencies, schema.rb after running migrations, etc) so that you can keep them under version control.

**Comment by ronyvieira** [comment]
Didn't know about it @jayeff. Thank you! I'll have to double check it when running migrations or updating Gemfile :/ It would be nice if i didn't have to worry about it but it's simply impossible to develop with regular sync. Do you know any alternative?

**Comment by jayeff** [comment]
@ronyvieira We use the standard synced folder from VirtualBox for Rails. This works fine for our use case and project size. Maybe you could use [NFS](https://www.vagrantup.com/docs/synced-folders/nfs.html) or [Unison](https://github.com/dmatora/vagrant-unison) for better performance. But I do not have experience with them.

**Comment by ronyvieira** [comment]
@jayeff I'll try it :) thanks again.

**Comment by khiav223577** [comment]
`rails-dev-tweaks` causes a performance issue... see: https://github.com/wavii/rails-dev-tweaks/pull/24
