### ISSUE TITLE
Expand the default watch list for Spring

### ISSUE THREAD

**Issue by dhh** [rails/rails#18874]
Here's what we use in Basecamp:

```ruby
Spring.watch_method = :listen

%w(
  .ruby-version .rbenv-vars
  tmp/caching-dev.txt tmp/restart.txt
).each { |path| Spring.watch path }
```

All these make sense as triggers for Spring reloading.

We should make sure that Spring reloading happens on all the common cases. This is a start.

**Comment by ajgrover** [comment]
Took a stab at implementing this [here](https://github.com/ajgrover/rails/commit/79aeb87a0c647574eee5e3804c96e06d5e9908a3). The config/spring.rb file is generated and called when Spring starts the application, but Spring doesn't seem to be watching the requested files. I've been trying to debug this for a little while now but am not familiar enough with Spring to figure it out. Any pointers would be appreciated!

**Comment by ajgrover** [comment]
So after debugging it looks like the solution I wrote actually works with `Spring.watch_method = :poller`. I am not sure if I have an error or if there is a bug in spring-watcher-listen. I have an [issue]() open and will submit a PR when I get that figured out.

Also, spring only watches files that exist when they are added to the watch list. Should I add the files in the watch list to the list of files generated by `rails new`? They would be blank or contain a comment about why they exists. I am not sure if devs would be aware of that or expect it to work right off the bat.

**Comment by rafaelfranca** [comment]
lol. Not my fault

**Comment by dhh** [comment]
@fxn Given you've been working in this area, do you mind investigating this?

**Comment by fxn** [comment]
👍🏼

**Comment by fxn** [comment]
Listen is only able to listen to existing files (inherits this limitation from the underlying OS libs).

The new evented monitor has some workarounds to make it behave similarly to the non-evented one. For example, if *db/schema.rb* does not exist when the application launches, it monitors the *db* directory and the callback is the one that filters. And since the interface is generic, indeed it needs to recurse the ascendants up until it finds a directory that exists, then watch that directory and filter in the callback if the evented source belongs to the ones to watch. The more upwards you go, the more irrelevant events you are going to receive generally speaking.

Would it be reasonable for this one to be in RC to add them to the watch list only if present?

**Comment by dhh** [comment]
Yes, I think it's fine that this is only picked up when the files are present for the RC. That just makes things better than they are today. Then we can improve from there.

**Comment by fxn** [comment]
@dhh excellent, guess Basecamp has that config in *config/spring.rb*?

**Comment by dhh** [comment]
Yep!
