### ISSUE TITLE
Controller views and mailer views have no shared directory for partials

### ISSUE THREAD

**Issue by brentdax** [rails/rails#18921]
Views rendered by controllers all share the `application` directory, which makes it a convenient place to put shared partials. However, views rendered by mailers share the `application_mailer` directory instead. That means there's no good place to put shared partials without putting them in a `shared` folder and prefixing all references to them, which seems to be out of style right now.

For example, my application has a partial that's used to render invoices, both in the website's billing management interface and in emails to customers about payments. I want to be able to say:

    <%= render partial: 'invoice', object: @invoice %>

In any controller and have it render the same partial, but there's no single location that behaves that way. For now, I've symlinked `application_mailer` to `application`, but that's a bit of a hack.

**Comment by andyatkinson** [comment]
@brentdax What version of Rails? Mailers in `RAILS_ROOT/app/mailers` have templates conventionally in `RAILS_ROOT/app/views` like `RAILS_ROOT/app/views/user_mailer` for a `UserMailer`. http://guides.rubyonrails.org/action_mailer_basics.html

**Comment by brentdax** [comment]
@andyatkinson I'm using Rails 4.2.0.

I may not be explaining myself clearly. If I have a `PaymentsMailer < ApplicationMailer`, its templates and partials are looked for first in `app/views/payments_mailer` and then `app/views/application_mailer`. Meanwhile, if I have a `BillingsController < ApplicationController`, its templates and partials are looked for first in `app/views/payments` and then in `app/views/application`. What I'm concerned with is that the fallback folders for the two are different; that makes it difficult to share partials between mailers and controllers.

**Comment by raouldevil** [comment]
@brentdax I think there is a separate process for feature requests, see the Rails documentation here: http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html. I don't think this is a case Rails should necessarily cater for unless commonly requested.

**Comment by rafaelfranca** [comment]
@dhh WDYT?

**Comment by dhh** [comment]
I actually didn't even know that partials would be looked for in `app/views/application` or `app/views/payments_mailer`. I almost always refer to a fully expanded path, and certainly so when I'm crossing boundaries. I suggest you do the same here, so you do `render "application/shared_partial"` rather than rely on `render "shared_partial"` happening to search in the right directory besides its own. It's far clearer.

**Comment by rafaelfranca** [comment]
This lookup is part of a feature called in Template Inheritance that exists since Rails 3.1. It is handy in some cases and when the controllers share the same ancestors, but I agree with @dhh about this one, mailers and controllers doesn't share the same ancestors so it would be a lot clear if you use explicit path.

Thank you for reporting the issue.

**Comment by dhh** [comment]
Also, for your specific case, you really should just have the partial in invoices/_invoice, if you can. Then `<%= render @invoice %>` will just work.
