### ISSUE TITLE
Docs for json_escape may introduce XSS venerability if followed incorrectly.

### ISSUE THREAD

**Issue by chrisjacob** [rails/rails#18954]
Docs: http://api.rubyonrails.org/classes/ERB/Util.html#method-c-json_escape

For this example:
```html
<script>
  var currentUser = <%= raw json_escape(current_user.to_json) %>;
</script>
```

If I latter do the following then any evils scripts on ```currentUser.first_name``` would be run:

```
$('#target').html(currentUser.first_name) 
```

.... unless each piece of data inside the ```current_user``` hash had ```html_escape(s)``` or ```html_escape_once(s)``` run over it BEFOREHAND e.g. 

``` ruby
@current_user['first_name'] = html_escape_once(row.first_name)
```

I ran into this issue myself here:
https://github.com/DataTables/DataTables/issues/497#issuecomment-74446906

It would be excellent if the docs could be updated to make clear that ```json_escape``` and ```to_json``` **does** make your data safe to be injected RAW into a script tag, but **not** safe to latter be injected into the DOM e.g. via jQuery - as seen in this jsFiddle - https://jsfiddle.net/fL4Leded/6/

**Comment by chancancode** [comment]
Yeah, so this is basically client-side XSS: if you insert user-supplied data as `innerHTML`, then you will have a problem. In general, this is of a different problem domain (client-side scripting) than Rails itself, which is why we don't offer much guidance in our docs. The docs on [master](http://edgeapi.rubyonrails.org/classes/ERB/Util.html#method-c-json_escape) attempts to cover a little bit of that, what do you think about that?

If you have ideas for improvement, please feel free to send another PR on top of it. However, I don't think we can go too deep into these topics because it is ultimately not Rails' responsibility here.

**Comment by chrisjacob** [comment]
@chancancode 

Yes that extra piece of information in the master docs is exactly what I feel was missing. Thank you!

```
If your JSON is being used downstream for insertion into the DOM, be aware of whether or not it is being inserted via +html()+. Most JQuery plugins do this. If that is the case, be sure to html_escape or sanitize any user-generated content returned by your JSON.
```
