### ISSUE TITLE
callbacks inside objects created by Something.where(..).create keep the scope inside before_/after_ methods?

### ISSUE THREAD

**Issue by joevandyk** [rails/rails#18952]
Below is a reproduction script. Note that when `Something.all.to_sql` is called inside the callback method, the `age: 28` condition is used. When we call a normal method, the `age: 28` condition is not kept. 

Is this a bug? Or expected behavior? If expected behavior, seems weird that the same method behaves differently when it's being used in an AR callback.

```ruby
require 'active_record'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :somethings, force: true do |t|
    t.text :name
    t.integer :age
  end
end

class Something < ActiveRecord::Base
  before_create :callback
  def no_callback
    puts "No callback: #{the_sql}"
    # No callback: SELECT "somethings".* FROM "somethings"
    # This is expected
  end

  def callback
    puts "Callback: #{the_sql}"
    # Callback: SELECT "somethings".* FROM "somethings" WHERE "somethings"."age" = 28
    # Why does the scope carry over?
  end

  def the_sql
    Something.all.to_sql
  end
end

Something.where(age: 28).create(name: 'joe').no_callback

# Also, first_or_initialize behaves differently than #first_or_create, there is different
# SQL generated inside the callback method.

puts "first or initialize"
s1 = Something.where(age: 20).first_or_initialize(name: 'bob')
s1.save
# Callback: SELECT "somethings".* FROM "somethings"

puts
puts "first or create"
s2 = Something.where(age: 30).first_or_create(name: 'joe')
# Callback: SELECT "somethings".* FROM "somethings" WHERE "somethings"."age" = 30
```

**Comment by joevandyk** [comment]
Here's a slightly different test case:

```ruby
require 'active_record'
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Schema.define do
  create_table :somethings, force: true do |t|
    t.integer :age
    t.integer :count
  end
end

class Something < ActiveRecord::Base
  after_create -> { self.count = Something.count }
end

require 'minitest/autorun'
class TestScope < MiniTest::Test
  def setup
    Something.delete_all
  end

  def test_first_or_initialize
    s = Something.where(age: 20).first_or_initialize.tap(&:save)
    assert_equal 1, s.count

    s2 = Something.where(age: 21).first_or_initialize.tap(&:save)
    assert_equal 2, s2.count
  end


  def test_first_or_create
    s = Something.where(age: 20).first_or_create
    assert_equal 1, s.count

    s2 = Something.where(age: 21).first_or_create
    assert_equal 2, s2.count # This fails, because Something.count has different SQL (keeps the scope)
  end
end
```

**Comment by senny** [comment]
@joevandyk is this the same as #9894 ?

**Comment by joevandyk** [comment]
Pretty similar, looks like. 

The only difference is that this ticket mentions that the scope in the before_create callbacks changes. Could be the same root cause, but I don't know.

**Comment by joevandyk** [comment]
Is this expected behavior?

**Comment by matthewd** [comment]
I think this is "known" behaviour. i.e., given knowledge of how the implementation works, one could reasonably expect this. But I wouldn't consider it to be behaviour that a user can reasonably be.. expected to expect.

(I'm thus tying it in with our other rather questionable behaviours around when and how scopes are active.)

**Comment by latortuga** [comment]
As an example of how this is problematic, this behavior messes with ability to reliably query for duplicates in a `before_save`. Obviously `unscoped` is still in play, however it was quite unexpected to come across this behavior today!

It does seem like the fix for this (as mentioned in #7853) is to use `find_or_create_by` from `ActiveRecord::Relation`, and that's how I think we'll go. However, I hope it won't be too controversial to question if this is even the proper behavior in the first place. Does it make sense that any queries you run in model callbacks would be scoped to the attributes you used to create the object? Under what circumstance would that be useful? It's certainly unexpected, especially given that `Model.first_or_initialize.save` does not have the same issue.

**Comment by latortuga** [comment]
I've also extended the test case provided by @joevandyk above.

https://gist.github.com/latortuga/ca7ed1d87593640f0d8f

The results make it seem like it's a bit of a minefield to create objects via scopes if we can't rely on querying in callbacks.

**Comment by GeorgeDewar** [comment]
I've just encountered this issue in a validation (which attempts to verify that there is at least one other team with admin rights before removing admin rights from a team).

It was quite difficult to debug (mainly because I didn't know where the query logs were going during seed execution, to be fair...).

I didn't expect this behaviour at all, and can't imagine why it would be desirable.

**Comment by vladimir-tikhonov** [comment]
I think this behaviour should be at least mentioned in docs/guides. It's utterly unexpected, especially when record is created via association which contains `where`.

**Comment by joevandyk** [comment]
I think this is still a problem in 4-2-stable. Not sure if it's a WONTFIX or what.

**Comment by rafaelfranca** [comment]
Closing as duplicated of #9894
