### ISSUE TITLE
Deprecate assigns() and assert_template in controller testing

### ISSUE THREAD

**Issue by dhh** [rails/rails#18950]
Testing what instance variables are set by your controller is a bad idea. That's grossly overstepping the boundaries of what the test should know about. You can test what cookies are set, what HTTP code is returned, how the view looks, or what mutations happened to the DB, but testing the innards of the controller is just not a good idea.

The same goes for assert_template. This ties the test to the internal structure of how your views are organized. That's not what the test should be testing. It should be testing what DOM elements it expect to be there. Rearranging your templates and partials should not cause these tests to break. Deprecate and recommend using assert_select instead.

**Comment by ajgrover** [comment]
Just sent a PR with deprecation warnings. I tried to follow the style in other actionpack warnings.

**Comment by renanoronfle** [comment]
i agree testing what instance variables are set is a bad idea, but i'm not sure to test what mutations happened to the DB, because this  is not innards of the controller too.
I think the better way is test what HTTP code is returned

**Comment by dhh** [comment]
That’s more a matter of whether you’re testing the controller or doing a full system test. I’m very sympathetic to system testing, but the black box can also appear in shades of grey for greater efficiency or other concerns.

**Comment by renanoronfle** [comment]
Ok, but if you check mutations happened in DB, are you overstepping controllers tests?
For test full system you can test in controller the http code and make a model test to check DB mutations.
I understand your point, at present moment my tests check DB mutations, but your commentary made me think if is right.

**Comment by dhh** [comment]
I don’t think so. Controllers don’t own the model. They do own their ivars, though. So I see no issue there.

**Comment by listrophy** [comment]
When testing a unit, you want to see the result of calling a function. That result comprises a) return values and b) external state modifications. In nearly any other case, internal (ivar) modification should not be tested, but this is not true with controllers. Why? Because the next high-level step of the render chain is to copy the controller's ivars* to the view. That's an external—albeit delayed—state change, and the fact that it occurs with ivars is merely an implementation detail/convenience.

If there was an accepted, default way to pass information to views *without* using ivars, then I'd agree with removing assigns(). Until such a mechanism is "The Rails Way" (yes, one can do it already with mechanisms like decent_exposure, but the guides do not encourage that), assigns is crucial, especially when trying to fix some "bad" controller code.

* Well, some of them, at least.

**Comment by cupakromer** [comment]
This is an honest question. With the removal of these two checks, what is the benefit of continuing to use a controller test over an integration test that tests a single controller?

**Comment by arthurnn** [comment]
@cupakromer performance. ATM controller tests are still a bit faster then integration tests. We would like those to have the same performance, so we can only have one.

**Comment by phoet** [comment]
i think that @listrophy has some valid points there. in case i actually want to test the way a controller accesses views or sets instance variables (because maybe i use it as some kind of internal API), what would be the recommended way?

**Comment by dmitry** [comment]
I agree with @listrophy and @phoet. It should be possible to test what messages are passing to external interface (messages - instance variables, external interface - views/templates).

**Comment by dhh** [comment]
You can of course do whatever you want. Ruby is open. But Rails does not have to encourage this behavior, and won't, starting from the next version.

**Comment by listrophy** [comment]
@dhh how, specifically, do you think we should test the interface between controllers and views? Strictly integration testing? just trying to get clarification here.

**Comment by calebthompson** [comment]
Since this is for 5.0, could we remove and also deprecate for the remainder of the 4.X lifecycle?

**Comment by calebthompson** [comment]
@listrophy I think that's the point. You shouldn't test that interface as their being separate is an implementation detail of your framework, not something you should care about.

**Comment by dhh** [comment]
If you want to continue to test ivars, you can just do #instance_variable_get. 

And yes, this is a change for Rails 5.0.

The change may well be that we’re dropping controller tests entirely in favor of integration tests, now that the latter is faster on rails/master than the former was on 4.2.

**Comment by listrophy** [comment]
Honestly, I don't actually want to test ivars. I (sometimes) want to test what data is getting sent from controllers to views. It just so happens that the main way to do that right now is through ivars.

And to be completely fair, I usually don't write controller unit tests. I still think it's important to not shut that door in cases where it's useful, such as all those brownfield projects out there. If such functionality were pulled into a gem rather than just removed, you wouldn't hear me complain.

**Comment by cupakromer** [comment]
I agree with @listrophy, I'd rather not test ivars. As has been pointed out, it is necessary when attempting to isolate the controller's contract with the view. Honestly, for me, what the controller passes into the view and what the view decides to do, or not do, with that information are fairly separate concerns. As long as the base contract is met.

These two parts of Rails have always been tightly coupled, I'm guessing due to ERB's behavior for how it evals on an object. I have recently notice Rails even takes extra steps to prevent certain ivars from crossing this "invisible" barrier.

If the future route is to drop controller testing in favor of integration testing you won't hear me complain. Nor if this behavior is extract into a gem as suggested above.

**Comment by jrochkind** [comment]
iVars essentially serve as the recommended "API" between controllers and views. It's how controllers pass data to views, as instructed and given by examples in almost all the Rails docs, it seems to be the way Rails wants you to do it. 

So I'd disagree that controllers "own" their iVars, in Rails design the iVars serve as the interface between controllers and views. 

I don't see any good way to 'unit' test a controller without testing iVars as well as templates rendered. The output of a controller is essentially just those, iVars and templates rendered. 

If you only test HTTP status codes and HTML returned, as output, I think you're basically doing a "full system test," you might as well be doing an integration test. Which, part of this thread suggests that's what Rails means to encourage, do not unit test controllers, only do integration tests. Myself, I find unit testing controllers to be useful -- most especially when delivering a controller (or controller mix-in in an engine).  It would be difficult for me if they were to go away. 

But if you mean to promote "only integration tests for rails", I guess that's consistent, that's basically what happens when you can't test iVars or templates rendered anymore, whether you use the Rails integration test base class or the functional/controller test base class, you're basically doing an integration test now. 

It will be easy to work around the missing assigns with `instance_variable_get`, indeed, but the missing `assert_template` is going to be harder, perhaps not possible to do in any reliable way without getting into Rails internals that can change with every release.

**Comment by msaspence** [comment]
How should I test my controllers in isolation of my views? Is that not the advantage of the MVC model?

This feels like a very heavy handed way of strong arming people into writing integration tests rather than unit tests. I appreciate that Rails is "convention over configuration", and perhaps the convention should be to to write integration tests but I should be able to choose to unit test controllers, just as easily.

I know I could probably reimplement these myself if I so wished such is the nature of ruby, but it feels a bit like fighting against the framework. I can't help but feel that there are better ways to point people towards integration tests without removing these helpers.

**Comment by Tekhne** [comment]
One of the foundations of object-oriented programming is the idea that encapsulated objects pass messages between each other to produce systemic behavior. When I'm testing that those objects are correctly implemented, I want to know that the messages they are sending to collaborators are happening at the right time, and in the right way. For better or worse, Rails controllers send messages to templates/views via ivars (instead of method calls). Therefore, I need to test that ivars are being set. I can certainly do that with things like #instance_variable_get, but I would prefer that #assigns and #assert_template stay in place.

**Comment by shekibobo** [comment]
Since iVars are considered a public interface for the views, and nobody really likes that we have to access what is considered private variables from outside the class, would it make sense to instead change the access of those iVars to be delivered from a public `assigns` method on the controller? Or perhaps from dynamically generated methods based on the assigned name? Assignment is a fundamental responsibility of Rails controllers, and to eliminate the method of testing because it breaks the rules that the views and controllers are already breaking seems misguided. Consider this usage:

```ruby
# posts_controller.rb
def index
  assign :posts, Post.published
end
```

```erb
# index.html.erb
<% posts.each do |post| %>
  <%= render post %>
<% end %>

<!-- alternatively -->
<% assigns(:posts).each do |post| %>
  <%= render post %>
<% end %>
```

This way, we get a nice interface for the views to get things in the controller without accessing it's iVars, we can get an `assigns` method in the views (and directly on the controller) to access them by name or see what assigns are available, and we can still test this fundamentally important part of controllers through an interface that is consistent for all interactors.

**Comment by kaspth** [comment]
For those missing `assigns` take a look at `assert_select` here: https://github.com/rails/rails-dom-testing.
That will let you test the interface of your views instead of what instance variables were used to build it.

The Rails team has heard your points, but we'll go ahead with the deprecations.
Thanks everyone :heart:

--
Kasper

**Comment by jrochkind** [comment]
The assert_select approach lets you test the controler+view as an integrated unit. 

Those of us unhappy with that want to test the controller a unit isolated from the view. This is particularly useful/important when delivering an engine, where the controller (or mix-in to local controller) might be used with a locally overridden view -- you want the controller, as an isolated unit separated from the view, to have a contractual interface, so the local app can provide a view depending on that interface. Devise would be one example. 

But okay, it's clear that Rails team does not see the value in testing controllers as an isolated unit separate from views, but thinks it's preferable to do systems or integration tests instead, or controller+view 'functional' tests. 

Hopefully there's enough people who disagree that there will be capacity to create a third party plugin that restore the ability to test controller as an isolated unit, and maintain it across versions of rails that may otherwise break it. We will see.

**Comment by dhh** [comment]
I'd be happy to see a plugin that provides this testing approach. Just because it's not in core doesn't mean you can't use it. If someone wants to do the work, we can update the deprecation notice to point to this plugin.

**Comment by tgxworld** [comment]
@rafaelfranca This issue can be closed :smile:

**Comment by kayakyakr** [comment]
Has anyone evaluated how this affects testing on API apps that are rendering JSON in the controller? Is the new recommendation to test the controller and serializer at once in an integration test?

**Comment by mmhan** [comment]
I am also wondering how I should test API controllers that are rendering JSONs. Parsing JSON after rendering the view seems counter-intuitive. 

With controller testing's assign and assert_template removed, two programmers one working on controller and another working on views have no hard specification for them to communicate. 

If it's rails' core team's decision to remove it, I guess I can't do much about it. However, I support a seperate gem approach. Please let me know if anyone in this discussion had started working on it.

**Comment by tgxworld** [comment]
@mmhan The two methods have been extracted into [rails-controller-testing](https://github.com/rails/rails-controller-testing).

**Comment by mmhan** [comment]
@tgxworld - Thanks!

**Comment by dhh** [comment]
Parsing the returned json is exactly what I would recommend. I see nothing counter-intuitive in that. But you can also use the gem, if you please.

**Comment by mmhan** [comment]
@dhh - Got the gem. Thanks. I would rather use the gem than parse my json though. As I mentioned I'd rather have the controller tests/spec act as a contract of its behaviors and the data it pass on to view.

I gotta say I agree with your underlying principle behind this decision: 

    Testing what instance variables are set by your controller is a bad idea. That's grossly overstepping the boundaries of what the test should know about.

However, I wonder what's the core team's rationale against the approach of changing the way controller passes data to view, something along the line of @shekibobo suggestion. One I could see is that it's a lot more work than simply deprecating some methods away. 

I'm no master of ruby nor rails, but if it's just that reason alone, I'd be happy to start hacking together an alternative solution. After all, that's a small gesture to contribute back to the community for all the productivity rails has given me.

**Comment by dhh** [comment]
The argument we're making with the new testing regime is that testing
controller actions independently and separately from the view isn't a good
way to do it. The view is a like testing a private method. What the
controller returns, and what we should be testing, is the result of a
compiled view. Thus trying to pry into the space between controller and
view is breaking the encapsulation that's inherent in the relationship
between the two.

Again, you may not view it like that, or not care, and thus still pursue
the prying tests. But Rails will follow defaults that respect that
encapsulation.

**Comment by mmhan** [comment]
Thanks for the explanation. @dhh It's a fair reason.

Personally, I will stick to separate testings of views and controllers and I will, perhaps, also look into de-coupling of view and controller. With my use of `respond_to` with a bunch of formats and variants, if I were to consider all the corresponding view as part of the controller, it would give me endless nightmares full of obese controllers-view-hybrids.

**Comment by jrochkind** [comment]
I want to test controllers and views seperately when I have an engine that provides a controller, and let's the client app provide or customize the view. (I think Devise does this for instance).  Or an engine that provides a view that the client can use with it's own controller. 

@dhh, do you consider this an anti-pattern that should be avoided?  An engine that provides a controller that can be used with a local view, or a view that can be used with a local controller? It sounds like you do, and think views and controllers should be tightly coupled, when you say "Thus trying to pry into the space between controller and view is breaking the encapsulation that's inherent in the relationship between the two."

Do I understand correctly?

**Comment by dhh** [comment]
Yeah, I'm not a big fan of sharing controllers like that as a general case.
But even in that case, I'd still say that the controller presumably would
have a default view, and you should be testing against that default. Even
if you allow someone to overwrite it.

But it's worth asking yourself why your controller is so complicated that
sharing it without a view really makes sense. To me it would indicate that
you should be extracting logic into models or concerns.

On Tue, Jun 23, 2015 at 7:59 PM, Jonathan Rochkind <notifications@github.com

**Comment by stevecj** [comment]
I know this is a closed issue and I pretty much agree with not asserting assignments, but I'm not making sense of the logic of not being able to assert the template.

I use Integration tests or Feature specs to test end-to-end, and then I want to be able to test alternative paths against the controller itself. I should not need to have my tests know about the HTML rendered by a template just to find out which template the controller decided to render. If a view is non-trivial and might break, then I'll usually want to test that separately from the controller.

To me, rendering a template is an outcome of the controller, not an "innard".

**Comment by Xenofex** [comment]
Agree with @jrochkind : ivar is the output of the controller and the input of the view, and controller testing should be there. A lot of web MVC frameworks use return value as the bridge between controllers and views. In that case, testing the return values of the controller methods seems fair.

I'm pretty happy that Rails didn't choose to use return value as the bridge between controllers and views, for which being too restricted. 

I think besides the controller in an engine which could probably have another view at the client developer's hand,  even if a view belongs exclusively to a controller which is the 95% of the case, I still want to test the controller without the view. Not being able to call the private/protected method during a test doesn't mean that those methods are really 'private' to the controller's internal usage. That's simply because the controller is designed to be calling the methods inside itself. The public interface is mostly the framework's concern. I even want to expose all the non action methods of a controller during a test, or at least those protected ones. For instance, checking controller's `current_user` method for testing my customized login/registration flow, is much more intuitive than asserting the templates, for the controller's correctness.

**Comment by fweep** [comment]
I'm not sure how to test for this specific concern without `render_template`:

If my controller is leaking data it shouldn't (another user's records), and my view is receiving the data but *is not rendering it as a DOM element*, how can I detect that? The view could include it in HTML comments, in JavaScript code that doesn't execute, in disabled DOM elements, in invalid HTML tags, or in any number of other ways that send the data to the client but are not testable in a request or feature spec.

I don't care which template is rendered. I care very much what data is sent to that template. I don't care that `assigns()` has been removed, because no one should ever have been using ivars in the first place. The right way to send data to templates has always been via `locals`, and it's that aspect of `render_template` that I need to test.

I'm open to suggestions about "the right way" to test this, but I've read everything in this thread so far, and I haven't seen a solution. I've installed the `rails-controller-testing` gem, and I'm using it only to test for `locals`, but if I haven't made a case for keeping it in the core, I'd like to understand what I'm missing.

**Comment by vanboom** [comment]
Totally disagree with this philosophy like others above.  Controller variables are not internals of the controller, they are the interface between the controller and the view and should be rigorously tested.  Integration tests do not allow you to test specifically enough. 

Simple example:  a view formats a date <%= @startdate.to_s(:long) %>  Is it not reasonable to test the controller to ensure that @startdate is never nil? 

Furthermore, please do not change the method of controller to view interface in order to justify this deprecation.  Setting an ivar in the controller and using it in the view is one of the beautiful RoR conventions that enable great productivity imho.  Poll the community and you will find everyone using the gem and moving forward into Rails 5 with controller tests that use assigns(...).

**Comment by robzolkos** [comment]
@vanboom  Why can't you test that @startdate is set in the view.  As you said, they are the interface between controller and view.  Rails by default lets you check the assignment in the view and optionally (for those that prefer the original implementation there is the gem).   There can only be one default.

| Poll the community and you will find everyone

And if you polled the community there are many that prefer the new way, myself included.  It works great.

**Comment by smtlaissezfaire** [comment]
Here's a little snippet that was handy for me:

```
    private def assigns(ivar)
      controller.instance_variable_get("@#{ivar}")
    end
```
