### ISSUE TITLE
Strange actionmailer behaviuor

### ISSUE THREAD

**Issue by TheR2** [rails/rails#18971]
Strange issue when I upgraded to Rails 4.2. It is so strange, that I created simple test code, to confirm it. Problem appears in development as well as in production environment. 

The code inside test method doesn't get executed at all.
Example:
```ruby
class MailSender < ActionMailer::Base
default :from => 'no.reply@some.where'

def test()
  should_die_here
  mail(
    :to => 'to@to.com',
    :subject => 'Test',
    :text => 'Text').deliver
end
end

#controller
class TestController < ApplicationController
def test_must_die
   MailSender.test() # nothing happens. It should be error in should_die_here
#even tried this
   MailSender.test1() # no method error
end
end
```

What can cause ActionMailer class to recognize that it has method, but not executing it?

When I reverted to 4.1.9 everything works as expected.

by
TheR

**Comment by georgeclaghorn** [comment]
Can't reproduce on Rails master:

```
irb(main):004:0> MailSender.test

MailSender#test: processed outbound mail in 0.7ms
NameError: undefined local variable or method `should_die_here' for #<MailSender:0x007f8e7660bb78>
```

**Comment by cristianbica** [comment]
@TheR2 this is the intended behaviour because of the `ActiveJob` implementation. How `ActiveJob` for mailers works is that it wraps any call to a mailer method into a `Delegator` (at this point your mailer method is not yet called). On the wrapper you can call `deliver_later` and your mail will be enqueued to ActiveJob (without calling your mailer method), `deliver_now` and your mail will be delivered (the mailer method is invoked). Also you can call `message` on the wrapper (result of calling `MailSender.test`) to force execution of your mailer method.
see: http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#masked-authenticity-tokens or https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/message_delivery.rb

**Comment by cristianbica** [comment]
@georgeclaghorn In your console example the console will actually call `inspect` on the result of `MailSender.test` (the wrapper) and at this point the wrapper will call the mailer method. See https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/message_delivery.rb

**Comment by TheR2** [comment]
Works. I guess I should read documentation more thoroughly next time.

Thanks
TheR
