### ISSUE TITLE
Bug in belongs_to when using counter_cache together with foreign_key

### ISSUE THREAD

**Issue by arnodirlam** [rails/rails#18988]
Hi,

when I use belongs_to with both counter_cache and foreign_key it doesn't update the counter cache correctly, since the update_counters method always operates on the table's primary key, instead of the foreign_key relevant in this case - as can be seen [here](https://github.com/rails/rails/blob/1152219fa2d7968f864b3a5ebb78d2f95ca4fb5c/activerecord/lib/active_record/counter_cache.rb#L83).

I guess what could be done is to add a parameter holding the column that id references, which evaluates to the table's primary_key by default. This would have to be passed on by belongs_to when using increment_counter and decrement_counter [here](https://github.com/rails/rails/blob/78dab2a8569408658542e462a957ea5a35aa4679/activerecord/lib/active_record/associations/builder/belongs_to.rb#L42).

Should I try to make a pull request (would be my first to rails)? If yes, could someone please point me to file(s) appropriate fro the tests?

Cheers, Arno

**Comment by rafaelfranca** [comment]
Hey @arnodirlam sorry for the delay. If you are still interested on writing a patch I'd recommend you to start with a reproduction script like this one https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb. If you can reproduce we can try to isolate the place of the code that could be changed to fix this. Thanks you for the report.

**Comment by enknamel** [comment]
I'm running into this same issue. Here is a very contrived gist that will show incorrect behavior with counter_cache. Counter caches appear to be incorrectly relying on the id of a record rather than the the stated primary key of the relation. It will use the listed primary key for some queries and then use the primary key value for the id of the record even though this isn't correct to do.

https://gist.github.com/enknamel/8b0c57095d1be86f2607

**Comment by amalagaura** [comment]
This is the same issue, I have some more tests and comments: https://github.com/rails/rails/issues/22602
