### ISSUE TITLE
undefined method 'bytesize'

### ISSUE THREAD

**Issue by resistorsoftware** [rails/rails#19006]
I am trying to get at an attribute in a DelayedJob model, defined as a text column in Active Record. When I access it I get an undefined method 'bytesize'. 

A gist is here: https://gist.github.com/resistorsoftware/ac4351616b729dcc224c

Not sure why this error is being thrown.

**Comment by rafaelfranca** [comment]
Almost all the stacktrace is from sinatra. I don't see how this is related with Rails.

Check why sinatra is passing a Active Model object to `Rack::Utils.bytesize` https://github.com/sinatra/sinatra/blob/v1.4.5/lib/sinatra/base.rb#L152

**Comment by resistorsoftware** [comment]
Wow. Ok.. First... we have an Active Record mapping for a DelayedJob. 

    class DelayedJob < ActiveRecord::Base; end

Then we have some delayed jobs in a PostgreSQL table with attributes that are things like integers, text and timestamps. 

So if we use Ruby idioms like this... 

    DelayedJob.all.each do | dj |
      handler = YAML.load(dj.handler)
    end

And the stack trace shows bytesize was a problem from ActiveModel and you are saying Sinatra magically handed that above code off to Rack::Utils... well.. you're just so smart... but I wish you would point as how the above code, as a simple example, is such a problem whereby this bytesize issue crops up.

**Comment by rafaelfranca** [comment]
Yes, bytesize problem is raised at Active Model but just because sinatra pass an Active Model (or Active Record) instance to `Rack::Utils.bytesize`. I don't know why this is happening, but I think it doesn't come from the code you provided since everything that your stacktrace shows is not application code.

I suggest you to try to dig deep in that stacktrace because it may be a problem in one of your gems.
