### ISSUE TITLE
ActionView fails to load Kramdown SyntaxHighlighter

### ISSUE THREAD

**Issue by commel** [rails/rails#19145]
I use Rails 4.2.0 with JRuby 9000 and I am using [Kramdown](https://github.com/gettalong/kramdown) 1.5.0 with [Coderay](https://github.com/rubychan/coderay) to produce HTML from Markdown-Syntax.

If the text contains anything that triggers the Coderay-Plugin to be loaded from Kramdown, it fails with:

```ruby
ActionView::Template::Error (wrong constant name ::Kramdown::Converter::SyntaxHighlighter::Coderay)
```

The Author of Kramdown told me to [verify](https://github.com/gettalong/kramdown/issues/227#issuecomment-76585535) that this is a Rails bug, so I [tried](https://github.com/commel/kramdown-bug) to do the same without Rails and it works fine for Kramdown 1.4.2, 1.5.0 and 1.6.0. 

The module path is defined [here](https://github.com/gettalong/kramdown/blob/fcbd88af46069f1b495aaaba87664dd03068e19f/lib/kramdown/converter.rb#L38).

In Rails it works only with 1.4.2.

**Comment by cristianbica** [comment]
I don't think this is a rails bug. I suspect it's caused by this line:
https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter.rb#L38
which calls:
https://github.com/gettalong/kramdown/blob/master/lib/kramdown/utils.rb#L51
which calls `Object.const_get(str)` but `const_get` only supports relative modules paths (not starting with `::`):
```ruby
~$ irb
irb(main):001:0> Object.const_get(:"String")
=> String
irb(main):002:0> Object.const_get(:"::String")
NameError: wrong constant name ::String
	from (irb):2:in `const_get'
```

Anyway unless you can provide more info (like a full backtrace where we can see that the error originated from Rails) there's nothing we can do. You're seeing the error as `ActionView::Template::Error` because we encapsulate any error raised while rendering a view in a `ActionView::Template::Error` (see [here](https://github.com/rails/rails/blob/master/actionview/lib/action_view/template.rb#L156) and [here](https://github.com/rails/rails/blob/master/actionview/lib/action_view/template.rb#L318))

**Comment by commel** [comment]
Indeed not a Rails bug, thanks to your hint to Object.const_get only accepting relative paths, I managed to create a patch which makes it work again. Hopefully the author will accept it. Thanks a bunch!

**Comment by gettalong** [comment]
Yes, and it is also not a kramdown bug:

Command:

~~~
ruby -ve "p Object.const_get('::String')"
~~~

Output:

~~~
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
String
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
String
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
String
~~~

This fails for JRuby in 2.0 mode.

**Comment by cristianbica** [comment]
Yep seems like a jruby issue. Now I see that MRI accepts strings starting
with :: but not symbols.
