### ISSUE TITLE
.json.jbuilder isn't a hook extension for jbuilder

### ISSUE THREAD

**Issue by lifeiscontent** [rails/rails#19158]
I'm unsure if this is rails or jbuilder but if you have a file `index.json.jbuilder` it will not render automatically by rails

though if you do something like `index.css.scss` it does....

**Comment by paulociecomp** [comment]
Can you provide a sample application that reproduces the error?

**Comment by lifeiscontent** [comment]
@paulociecomp https://github.com/lifeiscontent/rails-19158 just look at the commit history. I left notes in there.

**Comment by carlosantoniodasilva** [comment]
@lifeiscontent how are you accessing your application, through a browser, the command line? Is it being recognized as html or json request (you can see that in the log)?

**Comment by lifeiscontent** [comment]
@carlosantoniodasilva I guess this is a contrived example but if you setup a resource like `Todo` and then hit the `/todos` route in a browser you would see the correct template loaded if you call it `index.jbuilder` but you would not see it if you called it `index.json.jbuilder`

**Comment by carlosantoniodasilva** [comment]
@lifeiscontent that is because if you hit the app with a browser, it will infer the html format, so it will look for either `index.html.jbuilder` or `index.jbuilder` for example (same for `index.html.erb` or `index.erb`), it works as a fallback in case the format is not specified. If you hit the app with `/todos.json`, Rails will detect you're asking for json and should then look for `index.json.jbuilder`, with the same fallback for `index.jbuilder` I think.

Does that make sense?

**Comment by lifeiscontent** [comment]
@carlosantoniodasilva I'll try it later and let you know if that's the case. Thanks for the explanation though :+1:

**Comment by carlosantoniodasilva** [comment]
Alright, I'm giving it a close for now, but please let me know if you think it's something else and we'll gladly reopen. Thanks!
