### ISSUE TITLE
 Custom routing constraint is called multiple times on a single routing request

### ISSUE THREAD

**Issue by seanknox** [rails/rails#19184]
I have a custom routing constraint to limit access to routes. I noticed that the constraint is called multiple times on a single `GET` request to `controller#new`. I believe this is because `ActionDispatch::Journey::Route#matches?` returns too many route objects.

STR: 
- Set a custom route constraint on a resource
- The resource controller should have #show and #new actions
- Hit the route and the constraint will be invoked two times (instead of once)

## Correct match
***
- Resource being requested: `get: '/admin/users/new'`
- route.verb: `^GET$/`
- route.defaults: `{:controller=>"admin/users", :action=>"new"}`

admin_controller#new: `ActionDispatch::Journey::Route#matches?` returns true (_correct!_)

## Wrong match
- Resource being requested: `get: '/admin/users/new'`
- route.verb: `^GET$/`
- route.defaults: `{:controller=>"admin/users", :action=>"show"}`

admin_controller#show: `ActionDispatch::Journey::Route#matches?` returns true (**wrong!**)

I believe it's because `ActionDispatch::Journey::Route#matches?` only checks if the `:request_method` and the route verb regex match, despite being in a separate controller action.

Code and test to reproduce (uses `rspec-rails`)

```ruby
# config.routes.rb
Rails.application.routes.draw do
  shallow do
    constraints Constraints::Admin do
      namespace :admin do
        resources :users
      end
    end
  end
end
```

```ruby
# lib/constraints/admin.rb
module Constraints
  # Only allow authenticated admins access to precious resources.
 Admin = Struct.new(:request) do
    def self.matches?(request)
      new(request).matches?
    end

    def matches?
      warden.authenticated? && warden.user.is_admin?
    end

    private

    def warden
      request.env.fetch('warden')
    end
  end
end
```

```ruby
# spec/routing/admin/users_routing_spec.rb
require 'rails_helper'

RSpec.describe Admin::UsersController do
  describe 'routing' do
    before do
      allow(Constraints::Admin).to receive(:matches?).once
        .and_return(authorized?)
    end

    context 'user authorized' do
      let(:authorized?) { true }

      # fails because Constraints::Admin is called twice
      it 'does not route to #new' do
        expect(get: '/admin/users/new').not_to be_routable
      end
      # passes, Constraints::Admin is called once
      it 'does not route to #show' do
        expect(get: '/admin/users/1').not_to be_routable
      end
    end
  end
end
```

**Comment by tgxworld** [comment]
Is this on Rails 4.2?

**Comment by seanknox** [comment]
Oh yes, 4.2.

**Comment by kennyj** [comment]
I could probably reproduce this issue.

```ruby
# I added the following code to actionpack/test/dispatch/routing_test.rb, and ran tests.
def test_constrains_be_called_only_once
  count = 0
  draw do
    constraints ->(req) { count += 1; false } do
       resources :users
    end
  end

  get '/users/new'
  assert_equal 1, count # fails !
end
```

BTW If executing `get '/users/1'` or `get '/users/newsss'`, the test passes.
Does `get '/users/new'` match 'get /users/new' and ' get /users/:id' ??

**Comment by seanknox** [comment]
Haven't tested that yet but I'd bet those routes would match.

**Comment by pixeltrix** [comment]
@seanknox is the constraint returning false for `/admin/users/new`, if so then it will try it with the `show` action and an `id: 'new'` because it fits the url pattern of `/admin/users/:id` unless you put a constraint on the `:id` parameter to force it to be numeric. This is what's expected to happen.

**Comment by seanknox** [comment]
@pixeltrix For a single HTTP request to `/admin/users/new` the routing constraint is invoked twice. The routing constraint result has nothing to do with the issue here. It's that the constraint is hit multiple times for a single request instead of once. Please reread the thread before closing.

**Comment by pixeltrix** [comment]
@seanknox my point is that `GET /admin/users/new` matches both the `/admin/users/new` and `/admin/users/:id` path patterns so whether or not the constraint is returning false for the new action is important because if it does return false then the router will continue to search for a matching route.

Looking at the spec you have given it appears that `GET /admin/users/new` returns false because you are asserting that it should not be routable. If this is the case then the `once` expectation will fail because it will then try the show route since it matches the path pattern. If this understanding is wrong please try using the [templates][1] we have written to help you provide a bug reproduction script that I can look at.

I closed it because it sounds very similar to a number issues I've seen over the years where people have not realised that `new` matches `:id` in paths. If you can say for certain that the routing constraints continue to be called with other routes after the original route has been matched and the constraint satisfied I'm more than happy to reopen the issue - it doesn't affect how we treat comments on the issue and sometimes we reopen after months have passed.

[1]: https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_gem.rb

**Comment by seanknox** [comment]
Hi @pixeltrix, in this case, the constraint is returning true and then continues to be called with other route paths. That's what seems to be a bug.

**Comment by pixeltrix** [comment]
@seanknox I've tried reproducing use one of our templates but can't seem to get to call the constraint twice when `/admin/users/new` is matched - maybe you can have better luck:

``` ruby
# Activate the gem you are reporting the issue against.
gem 'rails', '4.2.0'

require 'rails'
require 'rack/test'
require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  config.action_dispatch.show_exceptions = true
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new('/dev/null')
  Rails.logger  = config.logger

  routes.draw do
    is_admin = lambda do |request|
      request.env['constraint_count'] += 1
      request.env['HTTP_HOST'] == 'admin.example.com'
    end

    constraints(is_admin) do
      namespace :admin do
        resources :users
      end
    end

    get '*path', to: 'errors#not_found'
  end
end

module Admin
  class UsersController < ActionController::Base
    include Rails.application.routes.url_helpers

    def new
      render text: "New"
    end

    def show
      render text: "Show #{params[:id]}"
    end
  end
end

class ErrorsController < ActionController::Base
  include Rails.application.routes.url_helpers

  def not_found
    render text: "Not Found", status: 404
  end
end

require 'minitest/autorun'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_constraint_called_twice_when_constraint_is_false
    env = {
      'HTTP_HOST' => 'www.example.com',
      'constraint_count' => 0
    }

    get '/admin/users/new', {}, env

    assert_equal 2, last_request.env['constraint_count']
    assert_equal 404, last_response.status
    assert_equal 'Not Found', last_response.body
  end

  def test_constraint_called_once_when_constraint_is_true
    env = {
      'HTTP_HOST' => 'admin.example.com',
      'constraint_count' => 0
    }

    get '/admin/users/new', {}, env

    assert_equal 1, last_request.env['constraint_count']
    assert_equal 200, last_response.status
    assert_equal 'New', last_response.body
  end

  private
    def app
      Rails.application
    end
end
```
