### ISSUE TITLE
ActionView:Template turning locals Hash into an array

### ISSUE THREAD

**Issue by anthonydahanne** [rails/rails#19204]
Hello,
I've been trying (with Rails 4.1.9) to register and use a template handler : 
```ruby
module MustacheTemplateHandler
  def self.call(template)
    if template.locals.include? :mustache
      "Mustache.render(#{template.source.inspect}, mustache).html_safe"
    else
      "#{template.source.inspect}.html_safe"
    end
  end
end
ActionView::Template.register_template_handler(:mustache, MustacheTemplateHandler)
```

and then I've been trying to use it, from an erb view, in particular with a Hash as a template local : 
```ruby
<%= render "project", :mustache => "{'planet':'world'}" %>
```

well, guess what, template.locals turns out to be an array with a single element being the string "mustache" - no trace of the rest of the Hash (:mustache => "{'planet':'world'}")
It seems like the locals array was turned into an array of strings (the strings being the hashes key) between the view and my template handler, I have no clue how it happened, 
Do you have any idea why ? How should I use my template handler with views variables ? 
thanks a lot in advance !

**Comment by amaierhofer** [comment]
`Template#locals` only contains a string array of keys passed.

The locals hash you are looking for is not present at compile time of the template. The decision to render mustache or not must be inlined in the ruby code returned from your handler.

```
module MustacheTemplateHandler
  def self.call(template)
    <<-RUBY
    if local_assigns.key?(:mustache)
      Mustache.render(#{template.source.inspect}, mustache).html_safe
    else
      #{template.source.inspect}.html_safe
    end
    RUBY
  end
end
```

Also mustache seems needs a hash to work on, so you should probably render your template like

```
<%= render "project", :mustache => { :greeting => 'hi there' }  %>
```

and reference the value in your template like so

```
<p>says {{greeting}}</h1>
```

Also you should be careful with using `html_safe` here.

**Comment by rafaelfranca** [comment]
Please don't use the mailing list to ask question.

**Comment by kreba** [comment]
Dear @rafaelfranca, I highly respect your many contributions to Rails. However, this was rude.
The issue had been open for two weeks without anyone caring, then when someone finally steps in and helps the guy, you join the stage and slap everyone in the face. Not very nice.
Especially since a member of the Rails Core Team had suggested amaierhofer and me to look into this issue.

**Comment by rafaelfranca** [comment]
Sorry, that was an automatic comment.

I'm very happy that the question was answered and I also do agree I could
thank you guys for doing so, next time I'll try to do.

Although I agree I could say a lot of nice words, this issue is still a
question, and our contributing guides and contributing.md files say that we
don't accept questions in the issue tracker so I could not see why keep it
open.

Anyway, thank you much for looking this issue, and also for the protest, I
did a mistake sorry 🙏

♥

**Comment by kreba** [comment]
Aaaah, thanks for your nice words! ;)
Educating people on how to use the issue tracker must be tedious work at times. Thank you for taking care of that! :heart:

**Comment by anthonydahanne** [comment]
hello all 
Thanks for your answer @amaierhofer - that makes sense,  I guess debugging the rendering can't be done effectively during compile time of the template ! (I was observing the values during a debugging session)
Sorry about not asking the question in the rails talk mailing list first - at the time I thought it might be a bug.
But yeah I should have asked first on the ML.
Thanks again all for your time
