### ISSUE TITLE
where.not(x: true) not including rows with x == null in MySQL

### ISSUE THREAD

**Issue by vemv** [rails/rails#19262]
Given a `MyModel` AR::Base class where `x` is a nullable boolean field, I believe Rails generates incorrect SQL -for MySQL- for the following query:

```
MyModel.where.not(x: true)
# SELECT `users`.* FROM `my_models` WHERE (`my_models`.`x` != 1)
```

The problem being that `my_models` rows where `x` is `NULL` are not returned.

FWIW, I do not know how to correctly write the SQL query.

Also, I am using the `mysql2` gem, but I think SQL generation happens at Rails level.

Lastly, I'm using MySQL 5.6.22 - essentially the latest.

Thanks!

Victor

**Comment by senny** [comment]
@vemv can you attach an executable test case to reproduce the issue? You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point.

**Comment by exviva** [comment]
I think that's the ternary logic of NULLs kicking in. Not sure if Rails should try to be smart here and generate an `IS NULL OR ...` clause?

**Comment by matthewd** [comment]
Indeed. I believe our position here is that `where.not` isn't an inversion of a `where`, but rather a means of invoking an SQL `NOT`. (See also, our behaviour on a multi-key `where.not`, e.g., `where.not(a: 1, b: 2)`.)

**Comment by Gytax** [comment]
This isn't a bug in Rails, this is how NULLs work in MySQL. NULL is NULL, it's nothing. It's not true, it's not false. It's NULL. So basically, always check for not NULL.
```
MyModel.where.not(x: [true, nil])
```
Should do the trick.

**Comment by vemv** [comment]
@Gytax isn't "nothing" different from `true`?

`where.not(x: true)` should include rows with null values, because null ("nothing") is different from true.

Your suggested query is wrong - only `where(x: [nil, false])` accomplished what `where.not(x: true)` should.

As I see it Rails is providing a faulty abstraction here. MySQL has no such thing as booleans. If Rails wants me to believe (which is a good thing) that my column is of boolean type, then it should ensure that a "not-true" query yields whatever is not true.

Please reopen?

**Comment by rafaelfranca** [comment]
> I believe our position here is that where.not isn't an inversion of a where, but rather a means of invoking an SQL NOT

Exactly this. `where.not(x: true)` is `WHERE x != true`, not the negative form of `WHERE x == true`.

**Comment by Gytax** [comment]
The thing with the MySQL NULL is that it's not true nor false, it also isn't !true or !false. It's nothing. And while nothing is different than true, NULL still doesn't match. I've run into this myself on more than one occasion. With MySQL you simple have to check for NULL values if the column is ALLOW NULL.

Whenever I create a bool column, I default it to false (or 0), to prevent NULL values.

Rails has little to do with this, because it simple translates to valid SQL. I don't think Rails should incorporate NULL values here, because it is simply a different thing.

NULL is very interesting imo, some reading matter:
http://en.m.wikipedia.org/wiki/Null_(SQL)
This sentence might clear thing up:
"a good way to remember what null means is to remember that in terms of information, "lack of a value" is not the same thing as "a value of zero"; similarly, "lack of an answer" is not the same thing as "an answer of no". For example, consider the question "How many books does Juan own?" The answer may be "zero" (we know that he owns none) or "null" (we do not know how many he owns, or doesn't own)"

**Comment by Gytax** [comment]
And in this case, not true means false for SQL, not 'lack of an answer'.

**Comment by CarlosCD** [comment]
By the way, this happens in PostgreSQL as well, probably as with any other relational database.

It is going to be a gotcha for many, while using a Ruby DSL instead of SQL. Specially when using boolean columns, expecting that NULL as just another possible value, as the AR DSL maps it to Ruby's nil... so `where.not(something: true)` would not return any records in which something is NULL.

    [ true, false, nil ].select{ |v| !(v == true) }
    #=> [false, nil]

I guess a solution is to modify the schema to avoid NULL values, if possible (`default: false, null: false`).

**Comment by olivierpichon** [comment]
Sure guys this behaviour comes from Postgres or any RDBMS. But what is anticipated from Active Record is to write the correct SQL request for us. Otherwise it leads to some inconsistencies like:

```
Project.count
  (0.6ms)  SELECT COUNT(*) FROM "projects"
=> 829
```

```
[16] pry(main)> Project.where.not(cloned_from_id: nil).count + Project.where(cloned_from_id: nil).count
   (0.7ms)  SELECT COUNT(*) FROM "projects" WHERE ("projects"."cloned_from_id" IS NOT NULL)
   (0.4ms)  SELECT COUNT(*) FROM "projects" WHERE "projects"."cloned_from_id" IS NULL
=> 829
```

```
[17] pry(main)> Project.where.not(cloned_from_id: 1260).count + Project.where(cloned_from_id: 1260).count
   (0.6ms)  SELECT COUNT(*) FROM "projects" WHERE ("projects"."cloned_from_id" != $1)  [["cloned_from_id", 1260]]
   (0.5ms)  SELECT COUNT(*) FROM "projects" WHERE "projects"."cloned_from_id" = $1  [["cloned_from_id", 1260]]
=> 199
```

I think AR should write a SQL which looks like:

```
SELECT "projects".* FROM "projects" WHERE (projects.cloned_from_id != 1260 OR projects.cloned_from_id is NULL)
```

**Comment by feliperaul** [comment]
This is much more a logic question then a programming question. 

If I write `.where.not(attribute: true)`, I obviously want anything where the attribute IS NOT true, including nil or whatever.

Rails should account for this and I consider this a bug.

**Comment by feliperaul** [comment]
@senny Could you please reconsider opening this bug?

**Comment by matthewd** [comment]
@feliperaul no; this is not a bug.

The above discussion both confirms that the behaviour is intended, and explains *why* that is the chosen intended behaviour.

It's also been true since `where.not` was introduced, making any potential change a compatibility issue for the many people currently expecting it to behave the same as SQL equality.

**Comment by feliperaul** [comment]
For the ones suffering from this (like me), and you're using PostgresSQL, I think the solution is use `Model.where("column_name IS DISTINCT FROM ?", value)` as explained here: https://stackoverflow.com/a/17680845/1290457 . This query will return null values as expected as they are distinct from the value passed.

**Comment by clst** [comment]
I just stumbled about this too. The Rails way is correct in this case.  
Even if you do: `.not('x = 1')` the x: nil rows won't show up (at least with mysql). It produces this SQL: `WHERE (NOT (x = 1))`

**Comment by gregblass** [comment]
> This is much more a logic question then a programming question.
> 
> If I write `.where.not(attribute: true)`, I obviously want anything where the attribute IS NOT true, including nil or whatever.
> 
> Rails should account for this and I consider this a bug.

Couldn't agree with @feliperaul more here. ActiveRecord should account for this, regardless of how NULLs work on the database level. If someone says `where.not(attribute: true)`, I can almost guarantee you they intended that to mean 'any time this is not true'. Logic/common sense would include false and NULL in that. I would argue that most people using ActiveRecord did not know that databases work that way.

The fact that you've already stuck with this direction in other areas of Rails complicates things though.

Anyway - I'm at least glad that I found this. Just wish I had before insisting to my client that not: true would include NULL values, and that all the jobs that she caught that were not regenerating for this year (and potentially losing them tons of business) were not due to this reason...

At least I can tell her that there was some level of programmer disagreement though?!

**Comment by ethn** [comment]
A quick note on this long-quiet issue:

Currently `where.not(x: true)` is translated into `x != TRUE` in MySQL. If instead it were translated into `x IS NOT TRUE`, the behavior would be more as expected (and would include null values in the results). This would actually seem _more_ consistent with how the adapter treats other special values. For example, `where.not(x: nil)` currently becomes `x IS NOT NULL`.

**Comment by zzak** [comment]
@ethn I understand your perspective here but based on this thread, I think we are not going to change the behavior for `where.not`: https://github.com/rails/rails/issues/19262#issuecomment-273767821
