### ISSUE TITLE
has_many :through references wrong table alias when joining on same table in rails 4.1.x and 4.2.x, but not on 4.0.x

### ISSUE THREAD

**Issue by yuthura** [rails/rails#19276]
For a full working example, please see https://gist.github.com/yuthura/b69a358537c0c729d63d.

When I chain on a through relation, and then join the relation that resides inside the through definition on the resulting chain, Rails aliases the inclusion, but not the through-join. Rails 4.0.x then correctly uses this alias name for subsequent join clauses, but Rails 4.1.x and 4.2.x use the actual table name instead, resulting in incorrect SQL.

This is most easily explained with an example; suppose the following example data structure:

```ruby
class Shop < ActiveRecord::Base
  has_many :categories
  has_many :products, through: :categories
end

class Category < ActiveRecord::Base
  belongs_to :shop
  belongs_to :reseller
  has_many :products
end

class Product < ActiveRecord::Base
  belongs_to :category
end

class Reseller < ActiveRecord::Base
  has_many :categories
end
```

When executing the following statement:

```ruby
shop = Shop.first
shop.products.includes(category: :reseller).where(resellers: { id: 1 }).count
```

Then Rails 4.0.x will generate the following (correct) query (note the proper use of `categories_products.reseller_id`):

```sql
SELECT
  COUNT(DISTINCT `products`.`id`)
FROM `products`
LEFT OUTER JOIN `categories` `categories_products`
  ON `categories_products`.`id` = `products`.`category_id`
LEFT OUTER JOIN `resellers`
  ON `resellers`.`id` = `categories_products`.`reseller_id`
INNER JOIN `categories`
  ON `products`.`category_id` = `categories`.`id`
WHERE `categories`.`shop_id` = 1
  AND `resellers`.`id` = 1
```

Whereas Rails 4.1.x and 4.2.x will generate the following (incorrect) query (note the improper use of `categories.reseller_id`):

```sql
SELECT
  COUNT(DISTINCT `products`.`id`)
FROM `products`
LEFT OUTER JOIN `categories` `categories_products`
  ON `categories_products`.`id` = `products`.`category_id`
LEFT OUTER JOIN `resellers`
  ON `resellers`.`id` = `categories`.`reseller_id`
INNER JOIN `categories`
  ON `products`.`category_id` = `categories`.`id`
WHERE `categories`.`shop_id` = 1
  AND `resellers`.`id` = 1
```

This will result in `ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'categories.reseller_id' in 'on clause'`.

Note that this issue seems to present itself with `mysql2`, but not with `sqlite3`; presumably sqlite has more flexible support for join clause orders than mysql does. I have not tried other adapters.

Has anyone encountered similar issues when upgrading from Rails 4.0.x to Rails 4.1.x/4.2.x, and if so, has anyone found a solution (or a workaround)? This is currently preventing us from upgrading, since we have many such data structures in our application.

I've delved into activerecord and arel, but cannot for the life of me find exactly where this particular case is generated. If anyone can point me in the right direction as to where to find it in Rails' source, I might be willing to write a solution myself if time allows me to. Until then, our company is stuck at Rails 4.0.x.

**Comment by lafeber** [comment]
:+1:

**Comment by karsthammer** [comment]
:+1:

**Comment by pinglamb** [comment]
When you change

```
shop.products.includes(category: :reseller).where(resellers: { id: 1 }).count
```

to

```
shop.products.includes(category: :reseller).where(resellers: { id: 1 }).load
```

It works!

Tested this against mysql2/postgresql on Rails 4.2.1.

**Comment by pinglamb** [comment]
Seems the problem is in the file [activerecord/lib/active_record/relation/finder_methods.rb](https://github.com/pinglamb/rails/blob/f1ccb2e6ecb5486179ee6b20438d562ac45de4f4/activerecord/lib/active_record/relation/finder_methods.rb).

For ```#load```, ```#find_with_associations```([L345](https://github.com/pinglamb/rails/blob/f1ccb2e6ecb5486179ee6b20438d562ac45de4f4/activerecord/lib/active_record/relation/finder_methods.rb#L345)) is called, for ```#count```, ```#construct_relation_for_association_calculations```([L379](https://github.com/pinglamb/rails/blob/f1ccb2e6ecb5486179ee6b20438d562ac45de4f4/activerecord/lib/active_record/relation/finder_methods.rb#L379)) is called. And I found that they both called ```#construct_join_dependency``` ([L355](https://github.com/pinglamb/rails/blob/f1ccb2e6ecb5486179ee6b20438d562ac45de4f4/activerecord/lib/active_record/relation/finder_methods.rb#L355), [L382](https://github.com/pinglamb/rails/blob/f1ccb2e6ecb5486179ee6b20438d562ac45de4f4/activerecord/lib/active_record/relation/finder_methods.rb#L382)) but for ```#construct_relation_for_association_calculations``` it doesn't include ```joins_values``` as argument.

Here is the fix:
https://github.com/pinglamb/rails/commit/82717478eb0699972f7654f37bf5324f7d9abffc

If it looks good, I can prepare a MR.

**Comment by eileencodes** [comment]
@pinglamb if you have a fix open a PR, but make sure to add a regression test :smile:

**Comment by Gytax** [comment]
I am a colleague of @yuthura and I can confirm that the proposed fix fixes the bug where we originally encountered it.

@pinglamb Thank you!
