### ISSUE TITLE
Rails Documentation. Getting Started Tutorial not working.

### ISSUE THREAD

**Issue by itsportspe** [rails/rails#19330]
If you follow the "getting started" tutorial on the rubyonrails.org site (linked below) you will notice that at the end of section 5.2 upon filling out the form and clicking submit, there is a routing error that doesn't follow the tutorial. I don't know how to fix this. Can someone please fix this?

Link to the tutorial
http://guides.rubyonrails.org/getting_started.html

Here are some extra photos. Hope this helps.

The error that you are supposed to get.
http://snag.gy/dmtwH.jpg

The error that I am getting now.
http://snag.gy/gsEUD.jpg

**Comment by kaspth** [comment]
It would helpful if you could paste your form, so we can compare it to the one in the guide :wink:

Because the guide mentions the url of the form is incorrect (otherwise you'll get the routing error) and your form should be changed to:

```irb
<%= form_for :article, url: articles_path do |f| %>
```

I'm going to close this for now as the guide looks correct to me :smile:
