### ISSUE TITLE
Rails route error.

### ISSUE THREAD

**Issue by zw963** [rails/rails#19356]
From guides edge (4.2), I read this:

```sh
 When calling the process helpers in an integration test 

the path needs to have a leading slash. 

Previously you could omit it but that was a byproduct of 

the implementation and not an intentional feature, e.g.:

test "list all posts" do
  get "/posts"
  assert_response :success
end
```

So, I thought one issue should be mention:

routes.rb (worked)
```ruby
    resources :products do
      get 'abc'
    end
```
routes.rb (not worked)
```ruby
resources :products do
  get '/abc'
end
```
I thought route should consistent with test route usage, right ?

**Comment by zw963** [comment]
oh, it worked if change to:

```ruby
    resources :products do
      get '/abc' => 'products#abc'
    end
```

**Comment by carlosantoniodasilva** [comment]
These are different things, `get 'abc'` is in fact just a shortcut for the last route you posted, so it makes sense not to require a leading slash.

The test requires a slash because you need to give it the full path, which includes the `/`, so `/foo` and not `foo`, or `/foo/bar/baz`, not `foo/bar/baz`. It "worked" unintentionally before, as the comment says, but it was not supposed to be used like that.

Thanks!
