### ISSUE TITLE
ActiveRecord touch causing deadlocks

### ISSUE THREAD

**Issue by jjb** [rails/rails#19372]
My app uses `touch` extensively in order to take advantage of Rails' template caching system. There's a certain type of work my app does when many relationships are created between many different objects in a batch. Sometimes, some of this work results in the resulting cascading `touch`es causing deadlocks.

I can code around this for the one scenario where I am seeing it happen often, but seeing it has brought to light the larger problem, which could happen in other scenarios (albeit it's very unlikely).

As an example, think about two people following one another on Twitter at exactly the same moment. They both click "Follow", resulting in the relationship objects being created between them and then each of their records being `touch`ed. If these touches become interweaved:

1. process 1 touches user A
1. process 2 touches user B
1. process 1 touches user B
1. process 2 touches user A

... and each process is using a database transaction, this will result in deadlock.

I'm surprised to not find much discussion of this around the web, so am I wrong that this could happen in normal app operation outside of my weird batch job scenario?

If I'm not wrong, would it be valuable to move the `touch`es to be done after the transaction? Last Write Wins is fine for updating updated_at anyway. Although I imagine there are other ramifications of this.

**Comment by jjb** [comment]
See also this work being done to reduce redundant `touch`es: https://github.com/rails/rails/issues/19372

**Comment by jeremy** [comment]
Definitely an issue. Coalescing touches won't help with deadlocks, either,
since child objects will still be locked before parents, exposing
concurrent parent/child txns to different lock ordering.

One fix is to explicitly lock the record that represents your "transaction
boundary" in a before_save. That guarantees a consistent lock order which
avoids deadlock.

Performing the touches outside the txn is an option, but it comes with all
the drawbacks that implies. It can break common caching patterns since a
job may be initiated after commit, too, that'd then have a stale timestamp
and not expire cache.

Another option is to introduce a way to declare the txn boundary and its
participants, and have its participants always pessimisticly lock the
boundary first, hence serializing txns on object graphs within it. This
could be implemented with before_* callbacks and a belongs_to option to
mark the "path" to the root/boundary.

**Comment by jjb** [comment]
If I'm not mistaken, any solution relying on locking a row will have to essentially always lock when writing anything to the DB. I think we don't want to do this with all writes, so the question is if the situation with `touch` is special enough to warrant special treatment. I think it potentially is. It is perhaps reasonable to expect programmers to reason about the concurrency ramifications of their "normal" object manipulations and do locking themselves as needed, but perhaps shouldn't have to always be thinking about the big tree of cascading touches that their code generates.

As such, perhaps the PR I linked to before, https://github.com/rails/rails/pull/19324, is actually quite relevant. Since we are now batching touches at the end of a transaction, there is perhaps a clear opportunity to lock all those objects ahead of time.

(I'm not heavily advocating for this -- introducing DB locks into basic rails behavior is a big deal. But from where I sit it seems reasonable to consider it.)

**Comment by macksmind** [comment]
@jjb Can this be closed since #19324 is merged?

**Comment by jjb** [comment]
Sure (although my current position is that making this sort of thing a native part of AR is going to end up being too complicated).

**Comment by heaven** [comment]
Was this backported to 4?
