### ISSUE TITLE
Guides page for I18n with ActiveRecord outdated

### ISSUE THREAD

**Issue by rafamanzo** [rails/rails#19386]
Hello

I'm not sure this is the right channel to report this. So sorry if it is not. But it was what I understood from http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation .

I'm running a project with Rails 4.2.0.

On the guides page http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models you read that for using ```User.model_name.human``` you should have a locale file like:

    en:
      activerecord:
        models:
          user: Dude
        attributes:
          user:
            login: "Handle"
          # will translate User attribute "login" as "Handle"

This is not working for me with 4.2.0. What actually worked was the locale file as:

    en:
      activemodel:
        models:
          user: Dude
        attributes:
          user:
            login: "Handle"
          # will translate User attribute "login" as "Handle"

Thank you a lot!

**Comment by senny** [comment]
@rafamanzo The example in the docs is correct. If you have a model extending `ActiveRecord::Base` the  key is `activerecord`. If you have a class including `ActiveModel::Model` the key will be `activemodel`. Since the guides are about translating your Active Record models the key is alright. Check your `User` class to see what key corresponds to it.
