### ISSUE TITLE
Error in ActiveJob when logger defines method tagged, but logger formatter does not have method current_tags

### ISSUE THREAD

**Issue by robdimarco** [rails/rails#19439]
I use the gem [syslogger](https://github.com/crohr/syslogger). In the latest release of the gem (1.6.1), they defined a method `tagged` on the logger.

This seemingly innocuous change caused an error 

```
NoMethodError: undefined method `current_tags' for #<Proc:0x007f102dc0ed30>
```

to be thrown when I tried to enqueue an `Active Job`.

Digging in to the problem, I found that in [activejob/lib/active_job/logging.rb#50](https://github.com/rails/rails/blob/master/activejob/lib/active_job/logging.rb#L50), we are calling `current_tags` with no check that the method exists on the log formatter.

I would suggest that this be wrapped with a `logger.formatter.respond_to?(:current_tags)` to avoid the error. I would think that if the formatter does not respond to current tags then `logger_tagged_by_active_job?` should return true as we do not want to keep adding tags if we cannot track the current tags.

**Comment by ziggythehamster** [comment]
:+1:

Also experiencing this issue.

**Comment by lazyatom** [comment]
I've also hit this issue.

**Comment by jetheredge** [comment]
We are also running into this issue. We can make it work by wrapping Syslogger with ActiveSupport::TaggedLogging. When used in combination with lograge ActiveSupport::TaggedLogging ruins the output format though, so it really isn't a solution for us.

This is a difficult one because I'm not really clear on where the issue needs to be fixed (which gem), but I'm thinking that ActiveJob is the place for the fix since I'm not seeing this issue anywhere else in Rails with regards to logging.

**Comment by jetheredge** [comment]
I should have also added that if someone can indeed confirm that this is the correct location for a fix, I'm happy to take a stab at submitting a pull request.

**Comment by jetheredge** [comment]
After some additional digging on this issue, it comes down to the Syslogger gem exposing "tagged", which is what ActiveJob uses to check whether it is using tagged logging, but doesn't expose the current_tags method which causes the error. I'm going to try to get the change made in Syslogger, even though I guess technically the check in ActiveJob could be made a bit more robust.

**Comment by jetheredge** [comment]
It looks like Syslogger defines the current_tags on the logger not the formatter. Since ActiveJob checks the logger for tagged before calling current_tags on the formatter, it seems to me like this check should be made more robust. I'll submit a pull request for this.

**Comment by jetheredge** [comment]
Ends up it is actually a little more complicated since current_tags is being called on the formatter in ActiveJob and Syslogger's formatter is a proc not an object. It seems like the patch that @robdimarco provided above should be pulled in since the current check is assuming too much. Also, @cristianbica proposed a solution which involves allowing the current_tags to be at the logger or formatter level, which would help out quite a bit for loggers like Syslogger which exposes current_tags on the logger.
