### ISSUE TITLE
Possible bug in controller testing

### ISSUE THREAD

**Issue by andreynering** [rails/rails#19516]
Ruby 2.2.1 and Rails 4.2.1 (don't know about older versions and master).

I created an app that reproduce the issue: https://github.com/andreynering/controller_test_bug

Take a look at [these tests](https://github.com/andreynering/controller_test_bug/blob/master/test/controllers/comments_controller_test.rb). Just the [last one](https://github.com/andreynering/controller_test_bug/blob/master/test/controllers/comments_controller_test.rb#L32-40) fails. I think it shouldn't.

This is the error thrown:

```bash
$ bin/rake test
Run options: --seed 63986

# Running:

..E.

Finished in 0.468636s, 8.5354 runs/s, 6.4016 assertions/s.

  1) Error:
CommentsControllerTest#test_should_create_post_(json_2):
ActiveRecord::StatementInvalid: SQLite3::ConstraintException: NOT NULL constraint failed: comments.post_id: INSERT INTO "comments" ("text") VALUES (?)
    app/controllers/comments_controller.rb:35:in `block in create'
    app/controllers/comments_controller.rb:34:in `create'
    test/controllers/comments_controller_test.rb:34:in `block (2 levels) in <class:CommentsControllerTest>'
    test/controllers/comments_controller_test.rb:33:in `block in <class:CommentsControllerTest>'

4 runs, 3 assertions, 0 failures, 1 errors, 0 skips
```

[Debbugging the `params` hash](https://github.com/andreynering/controller_test_bug/blob/master/app/controllers/comments_controller.rb#L30), I noticed that `post_id` have a Post object (only for the failing test):

```ruby
{"comment"=>{"text"=>"foo", "post_id"=>#<Post id: 980190962, title: "MyString", text: "MyText">}, "format"=>"json", "controller"=>"comments", "action"=>"create"}
```

But the expected value is the `id` of the post as a string (right?).

The `params`hash in the other tests:

```ruby
{"comment"=>{"text"=>"foo", "post_id"=>"980190962"}, "controller"=>"comments", "action"=>"create"}
```

If [in the second test](https://github.com/andreynering/controller_test_bug/blob/master/test/controllers/comments_controller_test.rb#L17) the AR object is converted to the `id`, I think it should happen in the last too.

**Comment by imanel** [comment]
The exact line responsible for this behavior is here:

https://github.com/rails/rails/blob/82402e6583dfd749ac128f7db65f567c03beaf50/actionpack/lib/action_controller/test_case.rb#L637

Reasoning behind it is as follows:
- For HTML request you can only provide text, so you're unable to serialize record. Because of that we're calling `to_param`, which in turn will convert record to it's `primary_key` by default.
- For non-HTML you are usually able to serialize record (i.e. `to_json`) so `to_param` is not required (and sometimes might be harmful)

I would advise using `id` for all tests - cons are probably too heavy to change this behavior for non-HTML requests.

**Comment by andreynering** [comment]
@imanel Thank you for clarifying. What you said makes sense.

Closing the issue since this behavior is by design.

For reference:
- The commit that adds this behavior: https://github.com/rails/rails/commit/7a80b69e00f68e673c6ceb5cc684aa9196ed3d9f
- The issue closed by the commit: https://github.com/rails/rails/issues/5341
