### ISSUE TITLE
CollectionAssociation#merge_target_lists should should drop non-persisted "persisted?" items from "memory"

### ISSUE THREAD

**Issue by dgutov** [rails/rails#19557]
See https://gist.github.com/dgutov/23b3b5ffdc08ecb0e5e0 for a problem scenario. Since the last `.widgets` call touches the database anyway, I expect it to return an up-to-date result.

Also see the last line. I'd expect `.all` to be a no-op in this case, but apparently it can make a difference.

The patch should look like this:

``` diff
@@ -436,7 +438,6 @@
         #   * Otherwise, attributes should have the value found in the database
         def merge_target_lists(persisted, memory)
           return persisted if memory.empty?
-          return memory    if persisted.empty?

           persisted.map! do |record|
             if mem_record = memory.delete(record)
@@ -451,6 +452,8 @@
             end
           end

+          memory.reject!(&:persisted?)
+
           persisted + memory
         end
```

If there are no objections from the core, I can try to make a pull request, with a couple of new tests.

**Comment by sgrif** [comment]
This is the expected behavior. All relation methods `where` for example, build a new `Relation` object. Changes to the database are not reflected by an object unless it executed it, as we simply cannot inform all possibly live objects in memory when a change occurs in the database. Your proposed patch has much more sweeping implications, which would (for example) affect the ability to properly save new records on an association. That method is used for much more than just deletion.

The reason `gadget.widgets(true)` returns an empty set is because you are forcing a reload.

The reason `gadget.widgets.all` returns an empty set is because you are returning a new `Relation` object. (I disagree with you that it should be returning the same object, as we maintain a consistent contract that methods on `Relation` return a new object across the board).

**Comment by dgutov** [comment]
@sgrif

> Changes to the database are not reflected by an object unless it executed it, as we simply cannot inform all possibly live objects in memory when a change occurs in the database.

The last `@gadget.widgets` call does touch the database, yet the result contains a stale element. This does not make sense from the consumer's perspective.

> Your proposed patch has much more sweeping implications, which would (for example) affect the ability to properly save new records on an association.

How come? The new records don't return true to `persisted?`, do they? Then they should be unaffected.

Do you have some specific tests in mind that will fail, were this patch applied? I've ran the suite with and without, and found none.

**Comment by sgrif** [comment]
I'll take a deeper look at this when I have time to work on it. My understanding of what's happening might be incorrect.

**Comment by dgutov** [comment]
The problem is still present in `5-1-stable`, same scenario.

**Comment by dgutov** [comment]
@sgrif Please reopen.
