### ISSUE TITLE
Rails 4.2.1 layout rendering

### ISSUE THREAD

**Issue by John222** [rails/rails#19626]
Hi guys

since i did an update from rails 4.1.x to 4.2.1 the "layout" parameter is not working correctly anymore. In the application controller i have this parameter

```ruby
class ApplicationController < ActionController::Base
   layout "bootstrap_v1"
end
```

in another controller let's say home controller i have this parameter

```ruby
class HomeController < ActionController::Base
   layout "parallax_v1", only: [:index]
end
```

So when i trying to enter another action then "index" lets say "test" no layout gets rendered. I just get action itself without any layout rendering.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by manish-shrivastava** [comment]
@John222 , if you get any error message or something..

**Comment by John222** [comment]
no. it's just render the action view but not the layout around it.

**Comment by naliwajek** [comment]
@John222 in the second snippet I guess you meant:

```ruby
class HomeController < ApplicationController
# not "< ActionController::Base"
```

Is that correct?

With that in mind, I think I was able to reproduce what John described on Rails 4.2.1
https://github.com/naliwajek/example-19626

Run and see:
[http://localhost:3000/index](http://localhost:3000/index)
[http://localhost:3000/test](http://localhost:3000/index)

However, it behaves the same (like John described) in 4.1.9, 4.1.1 and even 4.0.9 for me.

@John222 confirm this up^ is what you meant (I suppose you've deleted the default layout `application.html.erb` and that's why you say you see _"nothing around it"_).

What I'm about to describe is even mentioned in the following ApiDock comments:
[comment](http://apidock.com/rails/ActionController/Layout/ClassMethods/layout#851-Caveat-when-using-dynamic-layouts)
[follow-up](http://apidock.com/rails/ActionController/Layout/ClassMethods/layout#854-Re-Caveat-when-using-dynamic-layouts)

Looks like combination of:

```ruby
class ApplicationController < ActionController::Base
  layout "layout1"
end

class HomeController < ApplicationController
  layout "layout2", only: [:index]

  def index; end # uses "layout2"
  def test; end # you'd guess it uses "layout1", but no
                # it will fallback to default layouts/application
end
```

tries to render the default layout for action _test_, instead of the `layout1`.

If we redefine the `layout` in the subclass, it doesn't matter what we wrote in the parent (in this case `ApplicationController`) - it falls back to default for actions not specified in the `only` option.

Now someone more experienced can say is this an intended behaviour or not ;)

**Comment by John222** [comment]
Yes, exactly. I am working with another layout then application. So should i remove the layout parameter from the application controller and rename my default layout to application?

**Comment by meinac** [comment]
The issue is in actionview/lib/action_view/layouts.rb
I've solved the problem but now some tests are failing :/
