### ISSUE TITLE
favicon_link_tag pointing to wrong place

### ISSUE THREAD

**Issue by Andsbf** [rails/rails#19642]
<%= favicon_link_tag 'favicon.ico' %>

On Rails 4.2.1 favicon_link_tag  points to app/assets/images/favicon.ico not public/favicon.ico(where favicon.ico sample is created by default 'rails create xxx').

**Comment by mxhold** [comment]
I believe `favicon_link_tag` is working correctly, but I see how this could be confusing.

The `favicon.ico` file that Rails generates with a new app is in `public/` so that it is at the top level (e.g. mywebsite.com/favicon.ico) because browsers will automatically look at this location for the favicon when loading the page and if it is not there, you will get a bunch of 404 errors. Rails gives you a blank one to avoid getting those 404s. If you just want to change the favicon to one thing across your entire app, you can just overwrite the `public/favicon.ico` file.

The `favicon_link_tag` helper is provided to make it easy to specify an alternate favicon on specific pages. It assumes you're storing the image like any other image in the asset pipeline so it will start look in `app/assets/images/`. On pages with that link tag, browsers will use that favicon instead of the one at the root level.

**Comment by Andsbf** [comment]
Thanks for the quick replay mxhold, I might be doing something wrong, but only overwriting the public/favicon.ico doesn't seems to be working!

**Comment by rafaelfranca** [comment]
Just tested in a new application and it is pointing to the right place. I guess you have other favicon in one of these folders.

**Comment by Andsbf** [comment]
You guys are right! It was a cache problem the reason it was not loading! thanks for the help!
