### ISSUE TITLE
ActiveModel - insecure defaults?

### ISSUE THREAD

**Issue by ninja-** [rails/rails#19645]
I came across an interesting problem which could be categorized as "insecure defaults".

When using for example string fields on user model such as "name", no one expects that it would contain newlines, but they are allowed in most cases without using full regex validations.

for example
https://github.com/gitlabhq/gitlabhq/blob/master/app/models/user.rb#L123

**Please correct me if I am wrong**, but that allows to use newlines in user's name.
That could cause broken page layout in best case (evil user) or if you are trying to export something containg user data(i.e. recent transactions), a broken file (that's the one that made me think about this problem).

There is no validation to ensure that no newlines are used.
I propose to add a "allow_newlines" validation or disable newlines if db field is of :string type and not :text.

**Comment by mxhold** [comment]
You're right that unless you make a validation, strings can contain characters you might not be expecting, like newlines.

The validation you're proposing already exists in a more general form. It's the [`format` validation](http://edgeguides.rubyonrails.org/active_record_validations.html#format). The example provided in the guide prevents newlines as well as any character other than A-z:

```
class Product < ActiveRecord::Base
  validates :legacy_code, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
end
```

I think that this not being the default ends up being less of an issue than you might think because of two things:

First, if the form field is a normal text input (not text area) then the newlines will automatically get removed by the browser. That doesn't prevent users from posting data that has newlines though, so if you need to be certain it won't contain newlines you should create a validation (and maybe also a database-level constraint if you need to be absolutely certain).

Second, even if the field has newlines in it, since whitespace in HTML is generally ignored, it will show up as a space instead of a newline when displaying later unless you use something like [`simple_format`](http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format) that replaces newlines with `<br>` tags.

It might be nice to have an `allow_newline` option but I think if you want to exclude newlines, it is likely you also want to exclude other whitespace too so you should probably just use a `format` validation to specify exactly what characters you do want.

**Comment by matthewd** [comment]
> but I think if you want to exclude newlines, it is likely you also want to exclude other whitespace too so you should probably just use a format validation to specify exactly what characters you do want.

Agree.

While I don't think it would've mattered here: @ninja-, in future, if you're creating an issue and feel the title should contain the word "insecure", please strongly consider applicability of http://rubyonrails.org/security/.
