### ISSUE TITLE
css.erb not working as expected

### ISSUE THREAD

**Issue by lifeiscontent** [rails/rails#19655]
``` erb
<%= CSS::Tools::Mixins.media_query 'small' do  # this throws up %>
  body {
    background-color: green;
  }
<% end %>

h1 {
  font-size: <%= CSS::Tools::Functions.rem(CSS::Settings.defaults.base_spacing_unit) %>;
}
```

playing around with an idea for CSS + ruby, ERB doesn't handle blocks in CSS Files.

**Comment by pixeltrix** [comment]
@lifeiscontent this is because it's not Rails rendering the ERb template it's the Tilt template engine that powers Sprockets. The `<%= foo do %> bar <% end %>` syntax is a Rails extension to ERb to allow for simpler creation of block helpers and isn't supported by Tilt so you need to use the standard syntax, e.g:

``` erb
<% CSS::Tools::Mixins.media_query 'small' do %>
  body {
    background-color: green;
  }
<% end %>
```

Then you've got the problem of outputting whatever you're doing inside of `media_query` which won't be straightforward as it looks as though it's a singleton method and so the context won't be the correct ERb context. However at this point this becomes more a support issue than a bug in Rails so you'd be best off using one of the regular channels for support like mailing lists, Stack Overflow, IRC, etc.
