### ISSUE TITLE
Add thread_mattr_accessor for convenient use of per-thread module attributes

### ISSUE THREAD

**Issue by dhh** [rails/rails#19693]
Intended to work like mattr_accessor, but be scoped on a per-thread basis. IMO, this is a simpler way about the problem than PerThreadRegistry, and we should replace that with this:

```ruby
class Module
  def thread_mattr_reader(*syms)
    options = syms.extract_options!

    syms.each do |sym|
      raise NameError.new("invalid attribute name: #{sym}") unless sym =~ /^[_A-Za-z]\w*$/
      class_eval(<<-EOS, __FILE__, __LINE__ + 1)
        def self.#{sym}
          Thread.current[:"attr_#{name}_#{sym}"]
        end
      EOS

      unless options[:instance_reader] == false || options[:instance_accessor] == false
        class_eval(<<-EOS, __FILE__, __LINE__ + 1)
          def #{sym}
            Thread.current[:"attr_#{self.class.name}_#{sym}"]
          end
        EOS
      end

      if block_given?
        Thread.current[:"attr_#{name}_#{sym}"] = yield
      end
    end
  end
  alias :thread_cattr_reader :thread_mattr_reader

  def thread_mattr_writer(*syms)
    options = syms.extract_options!
    syms.each do |sym|
      raise NameError.new("invalid attribute name: #{sym}") unless sym =~ /^[_A-Za-z]\w*$/
      class_eval(<<-EOS, __FILE__, __LINE__ + 1)
        def self.#{sym}=(obj)
          Thread.current[:"attr_#{name}_#{sym}"] = obj
        end
      EOS

      unless options[:instance_writer] == false || options[:instance_accessor] == false
        class_eval(<<-EOS, __FILE__, __LINE__ + 1)
          def #{sym}=(obj)
            Thread.current[:"attr_#{self.class.name}_#{sym}"] = obj
          end
        EOS
      end

      send("#{sym}=", yield) if block_given?
    end
  end
  alias :thread_cattr_writer :thread_mattr_writer

  def thread_mattr_accessor(*syms, &blk)
    thread_mattr_reader(*syms, &blk)
    thread_mattr_writer(*syms, &blk)
  end
  alias :thread_cattr_accessor :thread_mattr_accessor
end
```

**Comment by pixeltrix** [comment]
We should definitely measure the relative performance of this before switching away from PerThreadRegistry - both in terms of speed and memory usage

**Comment by dhh** [comment]
Since both are backed by one underlying thread variable per declaration, where do you worry speed/memory usage to be a problem? And even if it was, I think PerThreadRegistry should be an internal optimization for the hotspots we have where it makes sense. The API is just not nice for something exposed to the user.

**Comment by fxn** [comment]
Hey! Quick heads up.

Yeah that class is a little strange, I remember I simplified something in the original implementation and then worked on the docs, but usage is not very nice. I'll read the details of the patch later.

**Comment by pixeltrix** [comment]
@dhh I was thinking about the differences when defining methods using class_eval with strings vs define_method with blocks

Agreed that we should present a usuable interface to developers - just want to do it based on actual measurements since this is likely to be in performance hotspots.

**Comment by dhh** [comment]
You're thinking this would be a hotspot at compile time or at runtime?
Didn't think there was a difference at runtime between using class_eval vs
define_method, and I don't think it matters at compile time?

**Comment by pixeltrix** [comment]
This is what Aaron discovered awhile ago: http://tenderlovemaking.com/2013/03/03/dynamic_method_definitions.html

We should test whether this still holds true for Ruby 2.2

**Comment by dhh** [comment]
Ah cools. I'm totally fine with using define_method instead. Just want the user-facing API.

**Comment by kaspth** [comment]
Why introduce a new macro, instead of defining `mattr_accessor` to take a `threadsafe: false` option? Wouldn't that make more sense as Rails is thread safe by default?

**Comment by matthewd** [comment]
@kaspth not really; "have a different value for each thread" != "threadsafe"... it's a pretty deeply different concept. (Though it is sometimes a tool for higher level code to maintain thread safety.)

**Comment by dhh** [comment]
Agree that this is a significantly different concept. Thread.current vs
@@var is a big split.

**Comment by kaspth** [comment]
Right, I got it mixed up. Full steam ahead! :)

**Comment by fxn** [comment]
This is way better usage and coherent with existing macros :rocket:.

Only tiny detail is that `Thread.current#[]` [accepts a string](http://ruby-doc.org/core-2.2.0/Thread.html#method-i-5B-5D) so the leading colons are not needed.

**Comment by fxn** [comment]
One more thing: since the macro has `thread` in its name and we are thinking "thread locals", I wonder if the implementation should be based on `thread_variable_get` and `thread_variable_set` instead.

**Comment by fxn** [comment]
The name does not quite click to me, because we are declaring a class-level attribute that is local to the current thread and the name does not suggest this meaning.

What about an option to the existing macro like @kaspth suggested, but called `:per_thread`, or `:thread_local`?

**Comment by thedarkone** [comment]
Aaron's conclusions were that `class_eval`ed methods are faster to invoke, but slower to define and result in a slightly higher memory usage (per method defined). If this is considered a hotspot we should go with `class_eval`.

In case if we do end up using with `define_method` nonetheless, the derived keys (ie: `:"attr_#{name}_#{sym}"`) need to be precomputed outside the `define_method` (to avoid repeated string/symbol interpolation per invocation).

It is true, that `Thread#[]` and `Thread#thread_variable_get` do accept strings as arguments, but that is only because MRI auto-converts them into symbols behind the scenes, this imposes a perf penalty. We should always be calling those methods with symbols.

**Comment by fxn** [comment]
Regarding symbols vs strings, that's the documented contract.

Many years reading comp.lang.c, would never base something like this on
implementation or external observed behaviour ;).

El sábado, 11 de abril de 2015, thedarkone <notifications@github.com>
escribió:

> Aaron's conclusions were that class_evaled methods are faster to invoke,
> but slower to define and result in a slightly higher memory usage (per
> method defined). If this is considered a hotspot we should go with
> class_eval.
>
> In case if we do end up using with define_method nonetheless, the derived
> keys (ie: :"attr_#{name}_#{sym}") need to be precomputed outside the
> define_method (to avoid repeated string/symbol interpolation per
> invocation).
>
> It is true, that Thread#[] and Thread#thread_variable_get do accept
> strings as arguments, but that is only because MRI auto-converts them into
> symbols behind the scenes, this imposes a perf penalty. We should always be
> calling those methods with symbols.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails/issues/19693#issuecomment-91843913>.
>


-- 
Sent from Gmail Mobile

**Comment by fxn** [comment]
What about an interface that allows the user to choose among the three locality levels: process, thread, or fiber? Something like:

```ruby
mattr_accessor :pool, per: :thread
```

with a default of `:process`.

**Comment by kaspth** [comment]
@fxn I like where you're going with this. But how useful is the fiber option? And how much documentation would we need for people to grasp that?

**Comment by fxn** [comment]
@thedarkone on my mobile phone I didn't realize your second and third paragraphs are related.

Yeah, so according to the docs we passing strings is supported, and if the data you have at hand is a string then you are done, no need for conversion. But if you have the choice, as in this case extracting the literal out, then a symbol is preferred.

**Comment by matthewd** [comment]
@fxn I really think they're too different... e.g., "per-process" values would persist across a fork (unless you meant to make a `$$` thing?), whereas per-fiber/thread ones get reset for new spawns.

If we're worried about the name `thread_mattr_accessor` being misleading, I think we'd be better off finding a different name.

As for thread vs fiber... again, let's use a satisfactory name, but also let's stick with what's useful to implement our own higher-level APIs. Evidence there says we want something backed by `Thread#[]`, whatever we decide call it.

Elegantly exposing our low-level support API is fair, for people who want to use it. But I'm not sure this is popular enough to warrant us manufacturing API purely for applications to use. (If anything, it actually sounds more like ruby-concurrency's bailiwick than ours.)

**Comment by fxn** [comment]
@kaspth I don't think it needs much explanation because the programmer should learn about that in Ruby docs. Like the docs of Ruby, they say `Thread.current#[]` is fiber-local, whereas `Thread#thread_variable_*` is thread-local. And they do not go further, because the concept of fiber and thread has to be learned somewhere else.

By the way, the "Thread" in the current name `PerThreadRegistry`, is misleading. That's a per fiber registry (that's why I wondered about using `thread_variable_*` instead. 

@matthewd The main design driver of Active Support is Rails itself, at least for me (and I bet for David), we just find this to be a better interface, and having this macro for Rails itself would be better. Even if it was private to Rails we would do it.

I see what you mean about the locality, but that's how processes work, you inherit, but they are still local (what the parent and child do the variable is local). I think people wouldn't find it a normal behaviour.

**Comment by fxn** [comment]
Hey, but that was just an idea though, the default could be `nil`. Docs could sort that out given the choices.

What I saw is that `:thread_local: true` doesn't work because `:fiber_local` would be a natural third option, and both at the same time do not make sense. Hence I arrived to factoring them out in something like `:per`, `:local_to`, etc.

**Comment by dhh** [comment]
Do we have a use case for the fiber option?

**Comment by matthewd** [comment]
Not AFAIK. (And to be clear, that's all I meant before: that we shouldn't build a wider API than what we need / have use for internally.)

**Comment by dhh** [comment]
I agree with that. No possibly-maybe extensions. And if it's just thread
and not, then I prefer having these like the PR started: as separate macros.

**Comment by matthewd** [comment]
Err, one self-correction: we actually only have a use case for the fiber one (aka `Thread#[]`) -- not the actually-thread one (`Thread#thread_variable_get`)

**Comment by fxn** [comment]
I think Rails itself does not depend on fiber-local variables as far as I can see. We use fibers only for streaming AFAIK.

The current `PerThreadRegistry` is implemented in a way that makes attributes fiber-local, but AS does not promise that, the name of the class and the RDoc says it is per thread. So if anyone is exploiting fiber-locality because they looked at the source code instead of the documentation, that's their issue. In this regard, in my opinion users could have filled a bug: "hey, this is not truly per-thread", but if they exploit the implementation, as far as me is concerned they are on their own.

My motivation for an option instead of a macro is that the name `thread_mattr_reader` doesn't quite click to me. It doesn't read well for my taste. Also, it's extension point for fiber locality is a third macro (but this can be counterargued via YAGNI :).

My motivation for fiber-locality is that this feature would belong to the public interface of Active Support. As a Ruby programmer, if AS provides class-level attributes with locality I'd expect it to have the three locality options in Ruby, to be aligned with the Universe! It would be for me the expected interface. Also, if anyone did exploit the implementation, they would have a way to emulate the previous behavior, but this point is minor.

But understand the YAGNI argument and I am fine with that. Only, if we get a PR with a third macro (in the new macro option), or `:fiber` or a new flag (in the second option), then we should be clear about what do we want to do.

**Comment by dhh** [comment]
Xavier, points well taken. I think thread_mattr_reader is a Good Enough
name for this. I don't like "threaded_" and I don't think the scope
argument for something that under the covers is so different is a good fit.
So I say we roll with this for now and reconsider if the fiber option is
proposed as a general use case.

**Comment by kaspth** [comment]
Fixed @ https://github.com/rails/rails/pull/22630
