### ISSUE TITLE
using require_relative inside initializers but the file loaded twice

### ISSUE THREAD

**Issue by phuongnd08** [rails/rails#19690]
I have 3 initializers files like these:

https://gist.github.com/phuongnd08/c3f97c1d847c7d0274c3

When the rails app boot, it says:

```
/tmp/build_2c28ce241ed1190103fabab3daa5f3de/config/initializers/redis.rb:1: warning: already initialized constant REDIS_WEBSOCKET_URL
       /tmp/build_2c28ce241ed1190103fabab3daa5f3de/config/initializers/redis.rb:1: warning: previous definition of REDIS_WEBSOCKET_URL was here
       /tmp/build_2c28ce241ed1190103fabab3daa5f3de/config/initializers/redis.rb:2: warning: already initialized constant REDIS_SIDEKIQ_URL
       /tmp/build_2c28ce241ed1190103fabab3daa5f3de/config/initializers/redis.rb:2: warning: previous definition of REDIS_SIDEKIQ_URL was here
```

**Comment by MhmoudGmal** [comment]
use require instead of require_relative to make sure the required file not loaded again, also I think in your case config/initializers you don't have to require other files in intializers if they loaded before where you access the constants defined there, and such case can occur if they has precedence alphabetical order.

in your case, I think you don't need to require redis, as it will be loaded before sidekiq and socket initializers

**Comment by phuongnd08** [comment]
@mhmoudgmal Isn't it require_relative would invoke require anyway? And what if the initializer not named `sidekiq` but `another_service`?

**Comment by mhmoudgmal** [comment]
@phuongnd08 yes you are right.. sorry, 
in the case you raised, in order to make sure your constants are present as you go, you can use ENV variables, this pattern is commonly used to configure connection strings, ..etc

another way to do this is to use the rails app initializtion process to load constants file say in YAML format and parse it, then inject it to the config object (Rails.application.config), all before initializers get invoked.

**Comment by phuongnd08** [comment]
@mhmoudgmal Fair points. Though what I would like to address is the initializer being loaded twice, which demonstrated by this particular example.
