### ISSUE TITLE
#average should not always cast to float

### ISSUE THREAD

**Issue by trandoanhung1991** [rails/rails#19701]
I'm trying to use AVG to calculate the mean difference between 2 timestamp columns and this default behaviour is just baffling. What's worse, there's no option to override this typecast.

**Comment by claudiob** [comment]
@trandoanhung1991 Hello! 

Are you suggesting a new feature that calculates the "average" of timestamps? 
Something like `Post.average(:created_at)`?

That behavior does not currently exist, and it's not a bug, just something not directly supported:

```
LINE 1: SELECT AVG("posts"."created_at") FROM "posts" ...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
ERROR:  function avg(timestamp without time zone) does not exist
```

If you'd like to open a discussion regarding how to tackle this, then I suggest you use the [Google Group](https://groups.google.com/forum/#!forum/rubyonrails-core) rather than GitHub issues.
