### ISSUE TITLE
fragment_exist? does not account for digested cache keys

### ISSUE THREAD

**Issue by akshaysmurthy** [rails/rails#19791]
This is especially problematic when we need to check if a fragment exists and that fragment has a digest appended to it. Something like this - 

```ruby
def index
  unless fragment_exist? "dashboard"
    // some complex database operation
  end
end
```

In the above case, I could avoid the query altogether by checking if the view fragment is cached. But since the cache key has a digest appended to it, the `fragment_exist? "dashboard"` would return `false`.

**Comment by arthurnn** [comment]
> to check if a fragment exists and that fragment has a digest appended to it

Is rails appending a digest?

**Comment by akshaysmurthy** [comment]
Sorry, I should have been more clear. A digest gets appended to the cache key unless you say 
`cache "dashboard", skip_digest: true`

**Comment by nasospsa** [comment]
+1
It happens in Rails 4 where cache digests are the default

**Comment by repinel** [comment]
Could you just use the `skip_digest` option when you need to know the exact key?

The main reason the digest is used by default is to expire the cache when the content change.

**Comment by akshaysmurthy** [comment]
@repinel But like you said, it is useful to expire the cache when the content changes.

**Comment by arthurnn** [comment]
I think I understand what the problem is now.
You are trying to re-use a fragment cache you created in a view, in the controller action, so you can jump a few expensive calls. However the cache on the view, appends a digest, so when the view changes the cache key will change.

See here https://github.com/rails/rails/blob/e7a265c0421915ee00ce3496d5a468375eb149ab/actionview/lib/action_view/helpers/cache_helper.rb#L166 how the cache_key is built for the view. You can see we need to lookup the file in order to calculate the MD5 of it, to append to the cache key. I am not sure how we would do that on the controller layer, as the view was not called yet.

I think you can solve this problem in a few different ways. I think you can use another cache key there. Or try to lazy load things. Not sure what your use case is TBH.

But I think this is not something we should fix on Rails, as the fragment cache is something calculated on the view side, and not on the controller action.

I hope that was helpful

**Comment by nasospsa** [comment]
In case someone may be helped from this. I read multiple times into @arthurnn comment and ended doing the "lazy loading" thing.

I was eager loading an object in the controller if the fragment existed:
```
@items = Items.order(updated_at: :desc)
@items = @items.includes(:subitems) unless fragment_exist? @items
```

And in the view of this action I had:
```
<%= cache(@items, skip_digest: true) do %>
```

This ended up **NOT** updating the view, if the file/template changed, but the items stayed the same.

So the first thing I had to do was to remove the `skip_digest: true`

Then I had to find a way to eager load the subitems only if the items hadn't changed. The trick here is that Rails, will need to preload the data even if you only need the date updated of the rows. So you get all the SQL load.

Here comes the lazy loading thing, where I created a helper method and used it inside the template.

```
# Controller
@items = Items.order(updated_at: :desc)

# Helper method
def preloaded_items
  @preloaded_items = @items.includes(:subitems) unless @preloaded_items
end

# View
<% cache(@items) do %>
  <% preloaded_items.each do |item| %>
    <% cache(item) do  #Russian Doll FTW %>
    ....
    <% end %>
  <% end %>
<% end %>
```
