### ISSUE TITLE
ActiveJob queue_adapter documentation is out of date

### ISSUE THREAD

**Issue by aripollak** [rails/rails#19801]
In each of the ActiveJob queue adapters (like [SidekiqAdapter](https://github.com/rails/rails/blob/503d9e12887e21015f9b241944dd850614c3e1b3/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb)), it documents how to set the queue adapter like this:

```
    # To use Sidekiq set the queue_adapter config to +:sidekiq+.
    #   Rails.application.config.active_job.queue_adapter = :sidekiq
```

However, this no longer works from an initializer, at least in the development and production environments. Setting it in application.rb works, and `ActiveJob::Base.queue_adapter = :sidekiq` does work from an initializer, but the config is then out of date with what's actually being used.

I'm not sure what the best solution is - should those comments just be removed, or should ActiveJob wait to be loaded until after the initializers so that configs from there get picked up appropriately?

**Comment by rafaelfranca** [comment]
:bomb:. These loading order problems are the worst. I'd say that ActiveJob should wait to be loaded after the initializer.

Could you provide an example application?

**Comment by aripollak** [comment]
When trying to isolate the problem, I finally tracked it down to https://github.com/newrelic/rpm. Without it, the problem doesn't happen because ActiveJob doesn't get loaded before the initializers.

I'm able to reproduce the problem in a fresh Rails 4.2.1 app by doing this, then hitting `http://localhost:3000`. In the development.log, you'll see that it performs the job inline instead of trying to enqueue it into DelayedJob.

```sh
rails new active_job_bug
cd active_job_bug
echo "gem 'newrelic_rpm'" >> Gemfile
echo "gem 'delayed_job_active_record'" >> Gemfile
bundle
echo 'Rails.application.config.active_job.queue_adapter = :delayed_job' > config/initializers/active_job.rb
echo 'class FooJob < ActiveJob::Base; def perform; end; end' > app/jobs/foo_job.rb
echo 'class FooController < ApplicationController; def landing; FooJob.perform_later; head :ok; end; end' > app/controllers/foo_controller.rb
echo "root 'foo#landing'" >> config/routes.rb
rails server
```


Here's a backtrace of ActiveJob getting loaded too soon: https://github.com/rails/rails/issues/19801

Is this actually a problem with newrelic_rpm or is it something that Rails should be supporting?

**Comment by rafaelfranca** [comment]
This is definitely a problem at newrelic_rpm but I don't think they have how to fix this since it is a limitation of the Rails initialization process. They are checking if `ActiveJob::Base` is defined here https://github.com/newrelic/rpm/blob/master/lib/new_relic/agent/instrumentation/active_job.rb#L9 so the class is being actually loaded what makes the Active Job's configuration initializer runs when newrelic_rom is loaded.

For cases like this you should change the configuration in the initializer directly `ActiveJob::Base.queue_adapter = :sidekiq`. Actually this is the recommended way to change configurations in initializers. The `config.some_framework.something` only works at environments and application.rb.

**Comment by aripollak** [comment]
So then this goes back to the original message - should the comments be changed, since that Rails.application.config syntax would probably only be used from an initializer?

**Comment by rafaelfranca** [comment]
:+1: for that.
