### ISSUE TITLE
Timezone MSK should be UTC+03:00, not UTC+04:00

### ISSUE THREAD

**Issue by bsanyi** [rails/rails#19825]
Time in Moscow should be UTC+3 ( see http://en.wikipedia.org/wiki/Moscow_Time ), but it is UTC+4 now:

```ruby
2.2.0 :001 > require 'active_support/time'
 => true 
2.2.0 :002 > Time.zone = 'Europe/Moscow'
 => "Europe/Moscow" 
2.2.0 :003 > tz = Time.zone.parse '2015-04-20 00:10:00'
 => Mon, 20 Apr 2015 00:10:00 MSK +04:00 
2.2.0 :004 > _
```

**Comment by gazay** [comment]
The problem is that `tzinfo` gem, which used by ActiveSupport, using user's TZif files located for example on mac in `/usr/share/zoneinfo`. Possible solutions – 1. we can add note that tz file for Europe/Moscow should be updated on server where it is needed. 2. We can create workaround just for Moscow TZ right in ActiveSupport as this problem can be present on many servers and user can't update it if he don't have rights.

I just checked on my new Digital Ocean instance with ubuntu 14.04 – there is +03:00. But as this timezone change was made only in oct 2014 – it still can be +04:00 on many servers.

**Comment by bsanyi** [comment]
I think it should be handled in the OS/tzinfo package.  Thanks for the effort!
