### ISSUE TITLE
Custom serialization of char(1) attribute to boolean using serializer class

### ISSUE THREAD

**Issue by bostrom** [rails/rails#19874]
Is the following behavior a bug or a feature (using rails 4.2.1 and mysql2 0.3.18)?

My model has a "boolean" attribute which is stored in the MySql database as ```char(1)``` having values 'Y' and 'N'. I want to treat the attribute as a boolean using ```true``` and ```false``` when creating, updating and querying records, and just serialize these values as 'Y' and 'N' to and from the database.

For this, I've written a serializer class that should convert true to 'Y' and false to 'N':

```ruby
  class YNSerializer
    # gets 'Y' / 'N' and returns true / false
    def self.load(val)
      val == 'Y'
    end

    # gets true / false and returns 'Y' / 'N'
    def self.dump(val)
      val ? 'Y' : 'N'
    end
  end

  serialize :is_deleted, YNSerializer
```
However, when I query the model I get the following result:

```
Model.where(is_deleted: false)
SELECT `model`.* FROM `model` WHERE `model`.`is_deleted` = '0'
Model.where(is_deleted: true)
SELECT `model`.* FROM `model` WHERE `model`.`is_deleted` = '1'
Model.where(is_deleted: nil)
SELECT `model`.* FROM `model` WHERE `model`.`is_deleted` IS NULL
```
It seems that rails is bypassing my serializer class when passed a true, false or nil as query value. Because if I pass a string instead:
```
Model.where(is_deleted: 'false')
SELECT `model`.* FROM `model` WHERE `model`.`is_deleted` = 'Y'
```
The 'false' string obviously is truthy and the serializer converts it to a 'Y' as expected. 

Why does rails or the mysql2 adapter bypass my serializer class when passed other values than strings? Is there something I can do about it?

**Comment by rafaelfranca** [comment]
cc @sgrif

**Comment by sgrif** [comment]
I was unable to reproduce this issue. This is the script that I used to test your report. https://gist.github.com/sgrif/b156ba959bb6c114178e

Can you please provide an executable test case that I can use to reproduce this issue, using [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)?

**Comment by bostrom** [comment]
Sure thing, here you go: https://gist.github.com/bostrom/48d284aae6c795f5e242

So it seems that in your test the ```Model.find_by(is_deleted: true)``` yields the correct result, but in my test using ```Model.where(is_deleted: true)``` does not.

**Comment by sgrif** [comment]
So the problem is actually pretty simple, I just needed to backport a small piece of the new type system from Rails 5. In 4.2 it's only partially implemented, and gets used with we use a placeholder for a parameter in a prepared statement, but is not used when the parameters are inlined (they're always inlined on mysql2, but we use the new type system if we would have used a prepared statement on other adapters). Booleans are never used for statement placeholders in 4.2, so I've just expanded it to do so.

You'll run into another problem, however, which is due to the contract of `Serialize`. Basically you'll never be able to query for or store `false` if you use `serialize` for this (at least not as written), as whatever is returned from `coder.dump(nil)` is going to be persisted as `NULL`.

Now there's a new API in Rails 5 that is much better suited for what you're trying to do, and I'd recommend using that instead. It's actually there already in 4.2, but with some slight changes.

```ruby
class YNType < ActiveRecord::Type::Value
  def cast_value(value)
    if value.is_a?(::String)
      value == "Y"
    else
      value
    end
  end

  def type_cast_for_database(value)
    if value.nil?
      nil
    elsif value
      "Y"
    else
      "N"
    end
  end
end

attribute :is_deleted, YNType.new
```

Note: In Rails 5, you'll need to rename `type_cast_for_database` to `serialize`. Keep in mind that in Rails 4.2, this is still an internal API so the normal caveats apply.

**Comment by bostrom** [comment]
Thanks @sgrif for the update! 

I tried the new Rails 5 type system as you recommend, but I still can't get my test file to pass. I updated the gist to reflect the changes, am I doing something wrong? https://gist.github.com/bostrom/48d284aae6c795f5e242/a801c31a43becdcc4874007ca0b89e7959feebee

Can I still use rails 4.2.1 from rubygems or do I need to pull it from github?

**Comment by sgrif** [comment]
You'd need to use the 4-2-stable branch

**Comment by bostrom** [comment]
Check. Working gist here, for reference: https://gist.github.com/bostrom/48d284aae6c795f5e242/add0e494ae7706409a02711e73db29191f1b0046

Thanks!
