### ISSUE TITLE
Rails 4.2 content_for not clear content

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#19890]
content_for(:somesing) do
  'something'
end

content_for(:something, flush: true) - not clear content
content_for(:something, nil, flush: true) - not clear content
content_for(:something, '', flush: true) - clear content but wrong future capture
content_for(:something, ''.html_safe, flush: true) - ONLY this clear content

**Comment by derekprior** [comment]
Took me a bit to get this, but sounds as if you want to use `flush` to empty the content in the named capture. Correct? 

The first two don't work because `content_for` sees the nil content supplied and the lack of a block and assumes you are trying to read the captured content back out. We could also key on whether any options were passed -- you wouldn't be passing options if you were reading.

I don't understand the problem you are reporting in the third example. The following test case passes:

```ruby
  def test_content_for_with_mutliple_calls_with_flush_empty_content
    assert ! content_for?(:title)
    content_for :title do
      'foo'
    end
    content_for :title, "", flush: true
    assert_equal nil, content_for(:title)
  end
```

Can you explain what you mean by "clear content but wrong future capture"? Or can you document it with a test case?

**Comment by Sega100500** [comment]
@derekprior 
Yes. I want just clear, empty content of named capture.

In your code
    content_for :title, "", flush: true
    assert_equal nil, content_for(:title) - this true

but, next after

    content_for(:title) do
      content_tag(:p, 'Test string')
    end

<%= content_for(:title) %>

will print:
<p>Test string</p>
raw string

Probably because '' passed in your example is not html_safe

**Comment by Sega100500** [comment]
@rafaelfranca 
My answer above. Still not readed?

**Comment by rafaelfranca** [comment]
hmm, got it. Seems like a bug indeed. Thank you for reporting.

**Comment by yoongkang** [comment]
PR submitted for this at #20046.
