### ISSUE TITLE
README links broken

### ISSUE THREAD

**Issue by oytuneyucel** [rails/rails#19893]
At the moment it's not possible to access to links provided in the Readme.

**Comment by derekprior** [comment]
Each link here seems to work fine for me: https://github.com/rails/rails/blob/master/README.md

Is there a link in particular that is giving you problems or were you talking about a different README?

**Comment by matthewd** [comment]
The individual library READMEs (e.g. https://github.com/rails/rails/blob/master/activerecord/README.rdoc) are intended to be read from http://api.rubyonrails.org/, so their Learn More links are broken when viewed on GitHub.

Thus, I think the problem is really the fact that the repo root README incorrectly encourages you to read them from GH, by using relative links.

**Comment by rafaelfranca** [comment]
Yeah :cry: I see issues like this one at least 2 times per month.

@fxn any idea how to improve this? I was thinking in making "Learn More" no real links on GitHub only

**Comment by cllns** [comment]
[github/markup#84](https://github.com/github/markup/issues/84) might be relevant, though not useful since it seems like there's no solution for relative links with a different base.

**Comment by kjcpaas** [comment]
I created a PR to point the "Learn more" links in README to api.rubyonrails.org. I think they are not supposed to be relative links as I don't see any of those content docs here in Github :confused:

**Comment by kaspth** [comment]
@kjcpaas They're not meant to be read on GitHub, as @matthewd points out above:

> are intended to be read from http://api.rubyonrails.org/, so their Learn More links are broken when viewed on GitHub.

**Comment by kjcpaas** [comment]
Oh ok. Got it :+1:
