### ISSUE TITLE
dynamic table_name

### ISSUE THREAD

**Issue by optimum-dulopin** [rails/rails#20015]
Hi,

I have a problem with dynamic table_name with 4.2.1. With 2.1.9, it was working well

here my simplify models :

class Aaaa < ActiveRecord::Base
  has_one :bbbb, dependent: :destroy, :inverse_of => :aaaa
end

class Bbbb < ActiveRecord::Base
  belongs_to :aaaa, :inverse_of => :bbbb
end

Bbbb.table_name = "cccccs"
aa = Aaaa.where(:id => 1)[0]
aa.bbbb
it runs a select query such as : SELECT  "cccccs".* FROM "cccccs" WHERE "cccccs"."aaaa_id" = $1 LIMIT 1  [["aaaa_id", 1]]
 
but if then I do

aa = Aaaa.where(:id => 2)[0]
Bbbb.table_name = "dddds"
aa.bbbb
it runs a select query still on table "cccccs" whereas it should be on "dddds" : SELECT  "cccccs".* FROM "cccccs" WHERE "cccccs"."aaaa_id" = $1 LIMIT 1  [["aaaa_id", 1]]

but if I display Bbbb.table_name , it prints "dddds"
 

when I do

Bbbb.table_name = "cccccs"
aa = Aaaa.where(:id => 1)[0]
aa.bbbb
it runs a select query such as : SELECT  "cccccs".* FROM "cccccs" WHERE "cccccs"."aaaa_id" = $1 LIMIT 1  [["aaaa_id", 1]]
 
but if then I do

Bbbb.table_name = "dddds"
aa = Aaaa.where(:id => 2)[0]
aa.bbbb
it runs a select query on good table such as : SELECT  "dddds".* FROM "dddds" WHERE "dddds"."aaaa_id" = $1 LIMIT 1  [["aaaa_id", 2]]

once again, with rails 4.1.9, it was working fine.

It seems that with 4.2.1, table for relation are instanciate when the object is create. Is there a reason for that ? Is there a way to avoid that.

Please no answer as "you shouldnt do this, doing this is not good, or whatever" , I cant also modify my database. I have to do like this, no choice, and for more than 2 years it was working well ;-)

**Comment by matthewd** [comment]
> Please no answer as "you shouldnt do this, doing this is not good, or whatever"

Sorry, but that's the answer. You're doing something that's (as far as I'm aware) not documented, and not supported.

You're welcome to find some other, possibly also unsupported, way of solving the same problem. The trade-off in using such behaviour is that you can't get official support for it.

I suspect that if you were to contact the mailing list, and describe the problem you're trying to solve (instead of your no-longer-functioning hacked solution), someone may be able to help you find a less fragile path to achieve it.

The fact you already knew you'd get this answer, demonstrates that you are fully aware you were relying on unsupported behaviour. You can't now insist we support it just because "I have to do [it] like this"... and I think you know that.

**Comment by optimum-dulopin** [comment]
thanks for quick answer.  Sorry if I offended you with my "Please no answer as "you shouldnt do this, doing this is not good, or whatever" ", that was really not the point, I was just trying to save time.

Yes Im aware that it is not supported, even if I dont understand why. Could it be at least possible to know  if there is a reason that now the relation is instantiate when the object is created ? I thought one of the good point of rails was to instantiate things only when you need them.

Are polymorphism or STI not supported anymore ? If they are still, why to force us to had a field on database when table_name can depend on domain name for instance.
