### ISSUE TITLE
Can't access server on other machine 

### ISSUE THREAD

**Issue by deepakshinde** [rails/rails#20139]
I have upgrade rails 4.2.1 version then start server but can't access server from other machine. I don't  known this any new feature added or bug?. Even I try thin server but same result.

**Comment by senny** [comment]
This is a bug tracker, not a support forum. Please use the [mailing-list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-talk) for usage questions.

As outlined in the [`Rails 4.2. release notes`](http://edgeguides.rubyonrails.org/4_2_release_notes.html#default-host-for-rails-server) this is the expected behavior. You should find guidance there how to get it working again.
