### ISSUE TITLE
Issue with Active Record Migrations Add Column migration

### ISSUE THREAD

**Issue by pramod-sharma** [rails/rails#20167]
rake db:migrate throws Mysql2::Error: Invalid default value ENGINE=InnoDB.
Default value for string datatype in AR is kept 255 for MySQL(not sure for Postgres). While this has been updated to 65535 beyond MySQL version 5.0.5 , and I am trying to use a string larger than 255 characters with default value.
<code>
  add_column :permissions, :string, default: 'abc.......'
</code>
I feel we can raise it beyond the specified limit of 255. Though we can currently use optional limit option for specifying the limit as of now.

**Comment by meinac** [comment]
`I feel we can raise it beyond the specified limit of 255` so what about older versions? This will cause problem on mysql versions before 5.0.3

**Comment by pramod-sharma** [comment]
But should not the limit specify the higher limit. Just asking?

**Comment by senny** [comment]
We use the Github issue tracker for bug reports and code discussion only. As this is the current expected behavior I'm going to close the issue.

To discuss changing the default value for `:limit` on MySQL please use the [rubyonrails-core mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core). You can find more details in our [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md).

Thank you for reporting.
