### ISSUE TITLE
Surprising parent_name on scoped ActiveRecord models

### ISSUE THREAD

**Issue by backus** [rails/rails#20177]
If I define an AR model with a scope

```ruby
class User < ActiveRecord::Base
  scope :male, -> { where(gender: 'M') }
end
```

Rails 4.2.x tells me that the name of the scoped class looks like this:

```ruby
User.male.class # => User::ActiveRecord_Relation
```

If the class is `User::ActiveRecord_Relation` then I would expect the [`parent_name`](http://api.rubyonrails.org/classes/Module.html#method-i-parent_name) to be `"User"`.  The actual `parent_name` turns out to be `"ActiveRecord"` which seems strange.

---

Until Rails 4.2, the scoped model's class would looked like this:

```ruby
User.male.class # => ActiveRecord::Relation::ActiveRecord_Relation_User
```

in which case the return value of `parent_name` would not violate the user's expectations. I believe this changed with https://github.com/rails/rails/commit/64c53d7ce40006bdfea59102bdac4cb265d3ecd1

---

I wrote up a few [tests if you are interested in replicating](https://gist.github.com/backus/622a5f685a54a15189b8). Running `rake` should test 4.0.13 followed by 4.2.1

**Comment by alainmeier** [comment]
:+1: good replicable tests

**Comment by chancancode** [comment]
This is why `User.male.class` is actually [an anonymous class](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/delegation.rb#L18-L20) which was [attached to the `User` class as a "private"/"internal" constant callsed "ActiveRecord_Relation"](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/delegation.rb#L21). This class [overrides the `name` class method](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/delegation.rb#L58-L60), which [is what the `parent_name` medthod uses](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/introspection.rb#L11) to provide that information.

If you look close enough, you'll see that it's working as expected:

```ruby
User.male.class.name # => "ActiveRecord::Relation"
User.male.class.parent_name # => "ActiveRecord"
```

What you are seeing is actually the `to_s`/`inspect` output:

```ruby
User.male.class.to_s # => "User::ActiveRecord_Relation"
User.male.class.inspect # => "User::ActiveRecord_Relation"
```

The reason is that (in MRI, at least), `to_s`/`inspect` is set as soon as you assigned the class to a constant:

```irb
>> c = Class.new do
?>   def self.name
>>     "ZOMG"
>>   end
>> end
=> #<Class:0x007fa07aada0f8>
>> 
?> c.name
=> "ZOMG"
>> c.to_s
=> "#<Class:0x007fa07aada0f8>"
>> c.inspect
=> "#<Class:0x007fa07aada0f8>"
>> 
?> 
?> LOL = c
=> LOL
>> 
?> 
?> c.name
=> "ZOMG"
>> c.to_s
=> "LOL"
>> c.inspect
=> "LOL"
>> 
```

So that is why `to_s` disagrees with `name` in this case. Since this is working as expected, I'm gonna close this issue for now (it's just a workflow thing, but feel free to keep discussing this here).

I don't think we care too much about the `to_s`/`inspect` output, *but* I am sure we won't mind improving that either. I can see a few solutions:

1. Override `to_s`/`inspect` (alias that to `name`)
2. Don't assign it to a constant (as far as I can tell, that is not meant to be public API, and I don't see why we couldn't operate without it. I could totally be wrong though, maybe someone else like @tenderlove or @sgrif or @matthewd would know!)

If you care enough about this, feel free to explore the feasibility/pros/cons for each approach and submit a PR!

**Comment by matthewd** [comment]
> Don't assign it to a constant

AFAIR, we do this for Marshal.

**Comment by chancancode** [comment]
:+1: that rings a bell, "can't dump anonymous class" :grin:
