### ISSUE TITLE
Rails 4.2.1 - Acceptance validation with accept option does not work

### ISSUE THREAD

**Issue by jacekgrzybowski** [rails/rails#20188]
Entries table:

    create_table "entries", force: :cascade do |t|
      t.string   "email",               limit: 255
      t.boolean  "terms_1",             limit: 1,     default: false, null: false
      t.boolean  "terms_2",             limit: 1,     default: false, null: false
      t.text     "answer",              limit: 65535
      t.datetime "created_at",                                        null: false
      t.datetime "updated_at",                                        null: false
    end

Entries model:

    class Entry < ActiveRecord::Base
      ...
      validates :terms1, :acceptance => {:accept => true}
      validates :terms2, :acceptance => {:accept => true}
      ...
    end

The problem:

I have 2 column corresponding to terms agreement in my form. I need to store those in DB - for this case I always used `{accept: true}` option passed to acceptance validator. However in `4.2.1` it doesn't seem to work:

    [1] pry(main)> Entry.create!(email: 'foo@bar.com', answer: 'some text')

The above does save the entry instance.

**Comment by repinel** [comment]
Could not reproduce using `4.2.1` or `master`.

https://gist.github.com/repinel/4c5ce8740d112796ed42

Did I miss something?

**Comment by jacekgrzybowski** [comment]
Well, apparently I was too tired at the end of the day yesterday to notice that I had been validating against "terms1" and my column was named "terms_1". Really sorry about that ;)

**Comment by jacekgrzybowski** [comment]
However, there's one more thing

**Comment by repinel** [comment]
It does't seem to be an issue. I would say that the `acceptance` doc is just missing a mention to the [default](https://github.com/rails/rails/blob/ffc3b33494fde0c628bd6ffa6d9b889b1e868aae/activemodel/lib/active_model/validations/acceptance.rb#L6) `allow_nil: true`option.

Please check this out https://gist.github.com/repinel/4c5ce8740d112796ed42#file-test_acceptance_validation_with_cast-rb

Since `terms1` is `boolean`, the empty string is casted to `nil` and the that validation rule will be skipped. As for `terms2`, it will still be an empty string, since it's a virtual attribute, and invalid according to the acceptance criteria.

**Comment by repinel** [comment]
My bad, the API doc does mention the `allow_nil` [here](https://github.com/rails/rails/blob/ffc3b33494fde0c628bd6ffa6d9b889b1e868aae/activemodel/lib/active_model/validations/acceptance.rb#L40).

**Comment by jacekgrzybowski** [comment]
Thanks, I didn't know that `allow_nil` defaults to `true` here. I'm closing the issue.
