### ISSUE TITLE
Mounting engine routes more than once under different resources doesn't work

### ISSUE THREAD

**Issue by leandro** [rails/rails#20204]
I have noticed that if you want to mount an engine routes set under multiple different resources, it simply doesn't work. Instead, one overwrites another.

Is this behaviour expected? I'm using Rails 4.2.1.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by leandro** [comment]
Yes. Definitely. A gist with a couple of files do? I'll get a spare time to do it.

**Comment by dptechdev** [comment]
I am glad to see this I also had questions regarding the same thing.

**Comment by leandro** [comment]
Here it is: https://gist.github.com/leandro/8581d36d09bd10453f39
I'm not sure if I did anything wrong or misused the mountable engine routes workflow.

**Comment by leandro** [comment]
I actually provided the requested information and steps.
I believe that @rafaelfranca forgot to take back the `needs feedback` tag.

**Comment by rafaelfranca** [comment]
DOne

**Comment by bogdanRada** [comment]
I am having a issue which could be related to this: 

If i have multiple gems mounted on same path '/products' , and the engine names are "my_gem1" and "my_gem2"

Calling in controller "my_gem1.product_index_path" results in "/products/my_gem1" 
While doing "my_gem2.product_index_path" results only in "/my_gem2" without the mounted path. 

Any idea what am i doing wrong? I don't have though an example to show ( because i descovered this on a private repository ) , but i can build one if you want.

**Comment by vedant1811** [comment]
Is anyone working on this?

**Comment by leandro** [comment]
@vedant1811 Not sure. @arthurnn is at least assigned to it.

**Comment by leandro** [comment]
Arthur, let me know if you need help on this. I can try to bring a solution for this matter.

**Comment by kaspth** [comment]
Have at it: https://twitter.com/arthurnn/status/793579322539773952 😉

**Comment by nicolrx** [comment]
Any update about this issue? Is anyone working on it?
