### ISSUE TITLE
Error lib/active_record/attribute_assignment.rb file

### ISSUE THREAD

**Issue by lawerna** [rails/rails#20220]
I got following error:

    undefined method `empty?' for nil:NilClass 

comming from lib/active_record/attribute_assignment.rb file. (method :extract_callstack_for_multiparameter_attributes)

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_assignment.rb#L84

Should it not be 'blank?', as empty is not nil safe?

**Comment by rafaelfranca** [comment]
Maybe, but it seems to me that `nil` should not enter that part of the code. Could you provide a way to reproduce this bug?

Thanks

**Comment by senny** [comment]
@lawerna are you still experiencing this issue? Please get back to us with a way to reproduce the problem otherwise it will be hard to decide how we are going to fix it. You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point to reproduce the issue.

**Comment by arthurnn** [comment]
Closing this as it has been almost 1y. Please re-open with more info if the problem still happens.
