### ISSUE TITLE
Constraint of param named subdomain

### ISSUE THREAD

**Issue by tomprats** [rails/rails#20233]
Rails: 4.2.0

So first some background, I'm trying to use the subdomain in the path for all my routes involving my `Organization` model. It was working until I found out that the `subdomain` field has to be able to contain more characters than the basic URL parameters allow. When I added the `constraints` block (also tried it inline), it came up with this error:

    No route matches {:action=>"edit", :controller=>"admin/organizations", :format=>nil} missing required keys: [:subdomain]

On:

    %td= link_to organization.name, edit_organization_path(organization)

With my routes file setup with these routes:

    scope :admin, module: "admin" do
      constraints(subdomain: /[^\/]+/) do
        resources :organizations, except: [:new, :show], param: :subdomain
      end
    end

    # Creates this route (and more)
    # edit_organization GET    /admin/organizations/:subdomain/edit(.:format)  admin/organizations#edit {:subdomain=>/[^\/]+/}

And my model with:

    def to_param
      subdomain # which is a string field that is unique and never nil
    end

Removing the constraints block has it working again (unless the subdomain contains something like a period). It looks like the constraint is being created for the `request.subdomain`, when I want it for the param

**Comment by tomprats** [comment]
I tried moving the constraint into a class and calling it on the parameter like so:

    constraint Constraint::Subdomain do
      resources :organizations, except: [:new, :show], param: :subdomain
    end

    module Constraint
      class Subdomain
        def self.matches?(request)
          subdomain = request.params[:subdomain] || ""
          subdomain.match(/[^\/]*/)
        end
      end
    end

But this seems like it just adds an additional constraint after the default constraint is already been verified. I get errors before it reaches the `Subdomain` class if the subdomain param has a dot in it. If the subdomain only contains letters, then it works like normal.

**Comment by simon2k** [comment]
Hi @tomprats,

The best idea is to rename the parameter, since it is a reserved one, here's the list of reserved params: https://github.com/rails/rails/blob/2f2c6247f5931982879bebeddf67b30f487e0811/actionpack/lib/action_dispatch/routing/route_set.rb#L745-L747

So later, the parameter is removed, in here:
https://github.com/rails/rails/blob/2f2c6247f5931982879bebeddf67b30f487e0811/actionpack/lib/action_dispatch/routing/route_set.rb#L782

That's why you have all the time the same error, about missing subdomain. If possible, just rename the param. Also, it could be good idea to add to the readme or guide info about reserved params, which can't be used, not sure what do you think about this @sgrif / @rafaelfranca? :)

**Comment by tomprats** [comment]
Ah, didn't know it was reserved. That explains it. It would be good to document it (maybe it already is somewhere!) but changing it seems to work out. Thanks!
