### ISSUE TITLE
PG::UnableToSend (SSL SYSCALL error: EOF detected)

### ISSUE THREAD

**Issue by christopher-b** [rails/rails#20411]
Hi, 
I'm seeing intermittent Postgres errors in my rails app:

```
PG::UnableToSend (SSL SYSCALL error: EOF detected):
  activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `exec'
  activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `dealloc'
  activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:198:in `block in clear'
  activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:197:in `each_value'
  activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:197:in `clear'
  activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:258:in `clear_cache!'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:291:in `reconnect!'
  activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:275:in `reconnect!'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:328:in `verify!'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:456:in `block in checkout_and_verify'
...
```

These errors are resulting in very long-running requests. I've googled this error, but all the results points to a problem (#12867) that was been fixed as of version 4.1.0, or to problems with gems I'm not using (Sideqik, Sequel). I haven't found any recent reports of a similar problem.

This is a low-traffic application, and I can't see any pattern as to when the errors occur, but it may be after a period of inactivity.

I'm running the following:
- Rails 4.2.1
- pg 0.18.2
- ruby 2.2.0
- PostgreSQL 9.1.11, with max_connections=200, current connections ~90
- Ubuntu 14.04.2
- Passenger 5.0.8

Stacktrace [here](https://gist.github.com/christopher-b/7cea858ff7008b85d353).

Does anyone have any idea what might be causing this, or how to track down a solution? Thanks!

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by matthewd** [comment]
There's a bug in there: we're trying to reconnect, but then failing to do so.

**Comment by rafaelfranca** [comment]
Is there any way to reproduce it?

**Comment by christopher-b** [comment]
The closest I can get is to kill the process on the Postgres server. 

In a Rails console, grab the adapter and cache a prepared statement:
```ruby
adapter = ActiveRecord::Base.connection
adapter.send :prepare_statement, 'SELECT 1'
```
Then find the connection PID on the Postgres server: 
```sql
SELECT datname,procpid,application_name,client_addr FROM pg_stat_activity WHERE datname='my_database_name';
```
Find the matching `procpid`, and kill it:
```bash
kill -9 $procpid
```

At this point, the PG connection will report a normal status:
```ruby
conn.status
=> 0
```

The error can be triggered by trying to reconnect 
```ruby

```

**Comment by christopher-b** [comment]
The closest I can get is to kill the process on the Postgres server, then call ```reconnect!``` directly, but it still leaves a mystery as to why the problem is happening.

In a Rails console, grab the adapter and cache a prepared statement:
```ruby
adapter = ActiveRecord::Base.connection
adapter.send :prepare_statement, 'SELECT 1'
```
Then find the connection PID on the Postgres server: 
```sql
SELECT datname,procpid,application_name,client_addr FROM pg_stat_activity WHERE datname='my_database_name';
```
Find the matching `procpid`, and kill it:
```bash
kill -9 $procpid
```

At this point, the PG connection will report a normal status:
```ruby
conn = adapter.instance_variable_get :@connection
conn.status
=> 0
pool = adapter.instance_variable_get :@statements
pool.send :connection_active?
=> true
```
This is how the StatementPool determines if it should actually execute the DEALLOCATE query.

The error can then be triggered by trying to reconnect:
```ruby
adapter.reconnect!
PG::UnableToSend: SSL SYSCALL error: EOF detected
```


What I don't understand is that ```verify!``` calls ```active?```, which runs a query on the connection, and only attempts to reconnect if that query fails. In that case, ```@connection.status``` should return non-zero, ```pool.connection_active?``` should be false, and ```dealloc``` shouldn't be running the DEALLOCATE query. What could cause  ```adapter.active?``` to be false but ```pool.connection_active?``` to be true?

**Comment by edpaget** [comment]
I'm running into the this issue too. I've created a test case for it [here](https://gist.github.com/edpaget/9b62b74ad2b4e7a53a94), but its a little wonky since it'll require a sudo password if you have postgresql running a separate user.

**Comment by christopher-b** [comment]
I made the problem go away by adding the following to my database config. But it would still be nice to address the cause of problem.

```yaml
  variables:
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 60
    tcp_keepalives_count: 100
```

**Comment by ruseel** [comment]
I saw just same stacktrace like @christopher-b.  And agree with his analysis 

```
verify! calls active? 
and active return false
and down the rabbit hole 
and connection_active? return true 
and try to use @connection.exec "DEACCLOCATE ..." 
```

**Comment by edpaget** [comment]
I found doing this https://github.com/edpaget/rails/commit/9f3f4b4de27152e751e8912c9856f4d120e255a3 fixed the issue for us, but I couldn't come with a test that worked without having to shell out as in my above test case. 

After more troubleshooting, I also discovered the underlying issue of PG timing-out was caused by networking changes in docker from 1.6 to 1.7 and the 1.7.1 release fixed them for us.

**Comment by ruseel** [comment]
edpaget@9f3f4b4 also seems to fix our issue for us. I appreciate a lot, @edpaget and all. 
I leave notes after few days about following up. 

(we are using docker 1.7.1 in amazon linux but experienced `PG::UnableToSend` in docker 1.7.1. 
It could be our unique situation, we are using PG in different AWS region)

**Comment by ruseel** [comment]
After 7 days, Our very low traffic server did not raise `PG::UnableToSend`.
But It's response time is around over 900 seconds sometimes.

**Comment by danowar2k** [comment]
I've encountered this since we installed our Redmine server.

Our Setup:
Redmine 3.3.0
Rails 4.2.6
PG 0.19.0

I would upgrade to Rails 5, but I am not really sure if Redmine 3.3.0 works with Rails 5.

Stack Trace:
F, [2016-10-28T09:18:36.914593 #64717] FATAL -- : 
PG::UnableToSend (server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
):
  activerecord (4.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `exec'
  activerecord (4.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `dealloc'
  activerecord (4.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:198:in `block in clear'
  activerecord (4.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:197:in `each_value'
  activerecord (4.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:197:in `clear'
  activerecord (4.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:258:in `clear_cache!'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract_adapter.rb:291:in `reconnect!'
  activerecord (4.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:275:in `reconnect!'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract_adapter.rb:328:in `verify!'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:456:in `block in checkout_and_verify'
  activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_checkout_callbacks'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:455:in `checkout_and_verify'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
  /tracker/tools/ruby/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  /tracker/tools/ruby/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
  activerecord (4.2.6) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.2.6) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.2.6) lib/active_record/query_cache.rb:31:in `call'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:22:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/ssl.rb:24:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  railties (4.2.6) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.6) lib/rails/railtie.rb:194:in `method_missing'
  puma (3.6.0) lib/puma/configuration.rb:225:in `call'
  puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
  puma (3.6.0) lib/puma/server.rb:415:in `process_client'
  puma (3.6.0) lib/puma/server.rb:275:in `block in run'
  puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'

**Comment by jwoertink** [comment]
I'm now seeing this error. I've only seen it come through bugsnag twice, but both times was trying to do a `Model.find`. 

I'm using Rails 4.2.7.1 with PG 0.19.0 with postgres `PostgreSQL 9.4.9 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit` with Ruby 2.3.3

```text
gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `exec': SSL SYSCALL error: EOF detected
 (PG::UnableToSend)
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `dealloc'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:198:in `block in clear'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:197:in `each_value'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:197:in `clear'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:258:in `clear_cache!'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:303:in `reconnect!'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:275:in `reconnect!'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:340:in `verify!'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:456:in `block in checkout_and_verify'
    from gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
    from gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_checkout_callbacks'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:455:in `checkout_and_verify'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
    from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
    from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
    from gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'
    from gems/activerecord-4.2.7.1/lib/active_record/core.rb:153:in `find'
    from app/mutations/postbacks/process.rb:9:in `execute'
    from gems/mutations-0.7.2/lib/mutations/command.rb:80:in `run'
    from gems/mutations-0.7.2/lib/mutations/command.rb:84:in `run!'
    from gems/mutations-0.7.2/lib/mutations/command.rb:36:in `run!'
    from gems/stan_services-1.13.4/lib/stan_services/events/dispatcher.rb:70:in `block (3 levels) in create_responder_workers'
    from gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158:in `execute_job'
    from gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
    from gems/sidekiq-4.2.9/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
    from gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
    from gems/scout_apm-3.0.0.pre3/lib/scout_apm/background_job_integrations/sidekiq.rb:81:in `call'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/sidekiq-history-0.0.7/lib/sidekiq/history/middleware.rb:40:in `call'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/sidekiq-failures-0.4.5/lib/sidekiq/failures/middleware.rb:9:in `call'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
    from gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32:in `with_context'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7:in `call'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
    from gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
    from gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
    from gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174:in `stats'
    from gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131:in `block in process'
    from gems/sidekiq-4.2.9/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
    from gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `process'
    from gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82:in `process_one'
    from gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70:in `run'
    from gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17:in `watchdog'
    from gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by nnluukhtn** [comment]
I am seeing this issue now.
```
gem 'rails', '~> 5.0.1'
gem 'pg', '~> 0.18'
```
ruby version 2.3.3

**Comment by al2o3cr** [comment]
@nnluukhtn No idea if it's related, but I recently tracked down an issue that manifested as similarly-bizarre behavior from ordinary-looking requests. In my case, the issue was code that looked like:
```ruby
module Foo
  DB = ActiveRecord::Base.connection
  
  def self.do_something
    # use DB here
  end
end
```
This code ran fine as originally deployed - to Heroku, with single-threaded Webrick - but started experiencing intermittent H12s on Heroku when we upgraded it to Puma (running 5 threads per worker). The underlying issue was that the module was loaded at server boot and captured the current thread's connection in `DB`, but `do_something` was subsequently called from request code running on multiple threads. The `pg` adapter did *not* like being accessed concurrently.

**Comment by aleksandrs-ledovskis** [comment]
In my experience, `PG::UnableToSend` error has occurred when stateful firewall was terminating opened connection before default TCP keepalive would start. Have solved it by adding PG server-side TCP keepalive configuration options to `postgresql.conf`.

Example:
```
tcp_keepalives_count = 10
tcp_keepalives_idle = 30
tcp_keepalives_interval = 30
```

Two keepalive requests per minute are very cheap, but this can be tweaked either way. Setup can be verified with `$ netstat --timers -tn` command

This way there's nothing extra to configure in `database.yml` and it will work for any PG client type or flavor.
