### ISSUE TITLE
has_many association bug: accepts_nested_attributes_for or adding a scope on association breaks the associations before objects are saved

### ISSUE THREAD

**Issue by joevandyk** [rails/rails#20451]
```ruby
class Developer
  has_many :contracts 
  # Developer.new(contracts: [Contract.new]).contracts.first.developer 
  #   returns a Developer. Works as expected.

  has_many :contracts
  accepts_nested_attributes_for :contracts 
  # Developer.new(contracts: [Contract.new]).contracts.first.developer 
  #   returns nil.  Not expected. Only difference is the accepts_nested_attributes for.

  has_many :contracts, -> { where(true) }
  # Developer.new(contracts: [Contract.new]).contracts.first.developer 
  #   returns nil. Not expected. Only difference is the scope.
end
```

https://github.com/joevandyk/rails/commit/c2a21922c12695a7b10b91c6161bf8f2464c99ea contains the failing test (should I do this via a pull request?)

On Rails 4-2-stable:

```
$ ruby -Itest test/cases/associations/has_many_associations_test.rb
Using sqlite3
Run options: --seed 24707

# Running:

............................FF.....................................................................................................................................................................................................

Finished in 1.585897s, 143.1367 runs/s, 332.3041 assertions/s.

  1) Failure:
HasManyAssociationsTest#test_broke_1 [test/cases/associations/has_many_associations_test.rb:162]:
--- expected
+++ actual
@@ -1 +1 @@
-nil
+#<Developer id: nil, name: nil, salary: 70000, created_at: nil, updated_at: nil, created_on: nil, updated_on: nil>



  2) Failure:
HasManyAssociationsTest#test_broke_2 [test/cases/associations/has_many_associations_test.rb:168]:
--- expected
+++ actual
@@ -1 +1 @@
-nil
+#<Developer id: nil, name: nil, salary: 70000, created_at: nil, updated_at: nil, created_on: nil, updated_on: nil>


227 runs, 527 assertions, 2 failures, 0 errors, 0 skips
```

**Comment by jamesdabbs** [comment]
`has_many :contracts` is [automatically invertable](https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/activerecord/lib/active_record/reflection.rb#L548), and so the `developer` association has its [`target`](https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/activerecord/lib/active_record/associations/association.rb#L109) set. A `has_many` with a condition is not automatically invertible, however, and so we [give up on finding](https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/activerecord/lib/active_record/associations/belongs_to_association.rb#L45) a target.

You can work around this by adding `inverse_of: :developer` to your `has_many`s, but I'm not seeing a sane way to deduce the target automatically otherwise. I'd love to take a swing at a patch though, if anyone with more experience here can point me in the right direction.

**Comment by Rafe** [comment]
For case 1, the `accepts_nested_attributes_for` enable [autosave](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/reflection.rb#L206), which disable automatic finding inverse on association. Therefore the [target will not be set in assignment](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/association.rb#L106).

For case 2, setting scope will disable automatic finding inverse too, as @jamesdabbs said, you can set `inverse_of: :developer` to make it findable.

The reason to disable `automatic_inverse_of` when enable autosave, is probably because the cache invalidation and circular reference, but it is not clear. I tried to remove `automatic_inverse_of = false` and found some failed tests due to circular reference.

in this case:
```ruby
class Developer
  has_many :contracts, inverse_of: :developer # emulate the case of circular reference 
  accepts_nested_attributes :contracts
end 

class Contract
  belongs_to :developer
  accepts_nested_attributes :developer
end

> developer = Developer.new(name: 'test', contracts: [Contract.new])
> developer.save!
# INSERT INTO "developers" ("name", "created_at", "updated_at") VALUES (?, ?, ?)  [["name", "test"], ["created_at", "2015-06-14 04:31:24.326546"], ["updated_at", "2015-06-14 04:31:24.326546"]]
# UPDATE "developers" SET "name" = ?, "created_at" = ?, "updated_at" = ?, "id" = ? WHERE "developers"."id" = ?  [["name", "test"], ["created_at", "2015-06-14 04:31:24.326546"], ["updated_at", "2015-06-14 04:31:24.326546"], ["id", 5], ["id", 5]]
# INSERT INTO "contracts" ("developer_id", "created_at", "updated_at") VALUES (?, ?, ?)  [ ["developer_id", 5], ["created_at", "2015-06-14 04:31:24.336964"], ["updated_at", "2015-06-14 04:31:24.336964"]]
```
Will trigger an extra update query from contract to developer.

So the patch might need to find a way to not generate extra query when autosave is enabled. Then we can let the model inversable when calling `accepts_nested_attributes_for`. Also need some suggestion from people with more experience on this.

**Comment by repinel** [comment]
It seems to be a known behavior. 

Original commit of `automatic_inverse_of` feature: https://github.com/rails/rails/commit/26d19b4661f3d89a075b5f05d926c578ff0c730f#commitcomment-9482625
