### ISSUE TITLE
Strange Use-case for ActiveRelation might?could to reveal a bug

### ISSUE THREAD

**Issue by JayTeeSF** [rails/rails#20540]
Heya Folks,

I've inherited some code that is, admittedly, attempting to do something in an overly clever way. That said, it seems to reveal a bug in active-relation or arel or ??? so I thought (before I replace this crazy code) I should provide the simplest test-case I could think of, to help in the battle to find & fix potential bugs.

In a nutshell:
1) the code creates a subclass of an active record class (yeah, yeah, that's probably the problem ...keep reading ;) ) ...for the purpose of adding some extra functionality
```
class SubClass < ::SomeActiveRecordClass
   def self.extra_functionality
      ...do stuff
      ::SomeActiveRecordClass.new(...)
      ...do other stuff
   end
end
```

2) the code then sets up an ActiveRecordRelation on the aforementioned subclass
```collection = SubClass.where(id: [@some_subset_of_ids])```

However:
3) when ```collection.extra_functionality``` is called, the instance of parent ActiveRecord class that gets generated is assigned the "id" used to setup the ActiveRecordRelation !?
I believe this is a bug.

The code gist which you can work with to see the behavior, is here:
https://gist.github.com/JayTeeSF/0af43b8b6312b4195e89

Create a new rails app, add that code to ./lib
chmod +x it, and then run it. The instructions tell you how-to exercise the test.
And the test prints (among the SQL statements) when the unexpected behavior occurs

Anyway, I realize this all sounds a bit convoluted and crazy, but I'd appreciate some feedback as to whether or not this is actually a bug (worth fixing) or if this is just the price one pays for trying to subclass an ActiveRecord class.
As it turns out, while I was testing, I discovered that I can add my extra_functionality onto the ActiveRecordRelation instance and this bug does not occur.

In case you want to compare I wrote the ArWeirdness.test_ok method in that code referenced in the gist

Thanks!

**Comment by matthewd** [comment]
Thanks for the report. Next time, please use the templates listed in the contribution guidelines (http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case).

I believe you're describing expected behaviour.

And that it has nothing to do with subclassing: if you were to extend ExtraFunctionality into TestClass (instead of directly onto the `@filtered_collection` relation), you would get the same result.

You're taking a slightly circuitous route to get there, but you're basically doing:

``` ruby
post = Post.where(title: 'foo').new
post.title # => "foo"
```

The following conditions are combining:
* the method is defined on the class -- so when it gets forwarded from the relation, a scope is applied for the duration of the call (Because Reasons)
* you're creating a new instance of that same class (or at least, a member of the class's inheritance tree), so that scope affects the operation
* the `where` condition contains a single value (thus, any new object created inside the collection can be assumed to have that value set)

The simplest solutions are to either not call `create_instance_of_test_class` on the relation if it's not necessary (i.e., you can just call it straight on the class), or wrap the `new` with an `unscoped` block:

``` ruby
new_record = ::TestClass.unscoped { ::TestClass.new(attrs) }
```
