### ISSUE TITLE
any? is not as efficient as it could be.

### ISSUE THREAD

**Issue by reichertm** [rails/rails#20695]
rails/activerecord/lib/active_record/relation.rb

The `any?` methods is using `SQL count(*)` to determine if there are any matching records.
To make it more efficient it could use `exists?` which produces SQL with `LIMIT 1`.

**Comment by pcai** [comment]
I think `LIMIT 1` with `COUNT(*)` will have no effect as `SELECT COUNT` always returns 1 row. Perhaps you are referring to building a `SELECT EXISTS` query instead, which would indeed be faster because it can stop on the first occurrence of a matching row instead of a full table/index scan. Is this what you mean?

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
