### ISSUE TITLE
Named route helpers started generating incorrect formats in 4.1.11

### ISSUE THREAD

**Issue by coryosborn** [rails/rails#20707]
In upgrading from 4.1.8 to 4.1.11, I ran into an issue with some named routes when I passed a hash for parameters that included an :id key.  Specifically...

Given route
```ruby
MyApp::Application.routes.draw do
  resources :partners
end
```

We had named route helpers that looked like this so we could preserve a range of filtering parameters between requests:
```ruby
class PartnersController < ApplicationController
  def show
    partner = Partner.find(params[:id])
    group = partner.groups.first
    @example_path = partner_path(partner, params.merge(:group_id => group.id, :term => nil))
  end
```

```params``` at this point will include keys for :id, :action, and :controller.  In 4.1.8, this named route helper would work fine, producing @example_path along the lines of: ```/partners/1?group_id=5```

However in 4.1.11, I ran in to some weirdness where the :id in the hash would cause the first parameter (partner) to be used as the format.  This is what the same code produces in 4.1.11 (and presumably 4.1.10):  ```/partners/1.1?group_id=5```

I can pinpoint it to this commit being the cause:  rails/rails@a2f7f54a33d9a200a27a5b9156c7022c5c94e972

**Comment by rafaelfranca** [comment]
Thanks. Could you try to write a failing test case and maybe a patch for it?

**Comment by agis-** [comment]
Trying from 4.1.8 through 4.1.11, the behavior seems weird yet consistent:

```ruby
p = Partner.find(8)
app.partner_path(p, foo: 'bar') # => "/partners/8?foo=bar"
app.partner_path(p, id: 999, foo: 'bar') # => "/partners/999.8?foo=bar"
```

Not sure what is the expected output. I would expect the second route to be the same as the first one.

**Comment by meinac** [comment]
Normally Rails expects required url parameters as parameters of the helper method or Hash. If you have a route definition like;
```
resources :partners
```
in this case Rails expects 2 parameters from you. First one is the id of the partner and second one is the format. If you call the url helper like this;
```
partner_path(1, :json)
```
everything works fine. You can also call it like;
```
partner_path(1)
```
again everything works fine because only id parameter is required. But if you call it like;
```
partner_path(1, {id: 1})
```
then Rails says, id is given in the hash so the first parameter should be the format of the page and it generates the url which is not expected. I believe this won't fix.
I recommend you to use your url helper like;
```
@example_path = partner_path(params.merge(:group_id => group.id, :term => nil))
```
You already have the id of the partner inside of the params so you don't need to use partner as argument.

**Comment by coryosborn** [comment]
I've already changed my url helpers to exclude the id or partner_id in params when passing that hash.  It's an easy workaround.

My point of filing this issue was that the behavior changed considerably for what I thought was a minor security update.  I'm having to change code that has been in production for over 2 years and at least Rails 3.2.  

I would be surprised if I am the only one affected by this, and it seems to be an unintended consequence of this change: rails/rails@a2f7f54a33d9a200a27a5b9156c7022c5c94e972.

It's easy for me to create a patch that reverts that changes behavior, but I think it will take me a little bit to understand what their intention was and create a patch that fulfills its needs and retains what I think is the correct behavior coming from previous versions of Rails.

**Comment by agis-** [comment]
@coryosborn As I've said in my previous comment, the behavior seems consistent in 4.1.8, 4.1.9, 4.1.10, 4.1.11 and 4.2.3.

**Comment by pixeltrix** [comment]
Closing this as it's the intended behaviour.

@coryosborn the change was made in a non-security patch release where we do fix bugs - if we didn't then there wouldn't be much point of releasing them! It's always a tricky trade-off when merging these changes which is why our policy is for security updates to only include the relevant changes so that you can apply them when they come out with the confidence that it's unlikely to break your app outside of areas directly affected by the security issues. However in this case you jumped multiple patch releases in a single go so you got a bug-fix release as well - sorry for any problems caused.
