### ISSUE TITLE
ActiveJob NoQueueError when using Resuque queue adapter

### ISSUE THREAD

**Issue by utilum** [rails/rails#20754]
Resque requires us to set the queue_name in @queue, ActiveJob wants it done with queue_as, and offers some useful functionality in return.

But the two ways to name the queue do not collaborate, and out of the box they give a NoQueueError.

Here's a demo application with a test to demonstrate the issue: https://github.com/utilum/no_queue_error

One could change queue_name to set @queue, but other adapters don't need this, so the Resque adapter seems like the place to extend or override queue_name, but how?

**Comment by jvanbaarsen** [comment]
I would like to take a look at this :)

**Comment by seuros** [comment]
@jvanbaarsen :+1:

**Comment by jvanbaarsen** [comment]
@utilum It looks like your testcase was wrong. You're calling Resque directly from your rails app. This will  bypass the ActiveJob code. If you write the testcase as follow it works as expected:

```ruby
require 'test_helper'

class DemoJobTest < ActiveJob::TestCase
  test "Resque job enqueued without errors" do
    assert_nothing_raised do
      DemoJob.perform_now
    end
  end
end
```

So in your app you should call `DemoJob.perform_now` instead of `Resque.enqueue(DemoJob, 'demo arg')`

Can you try this in the app you encountered this issue in?

**Comment by jvanbaarsen** [comment]
@seuros Thanks :yellow_heart:

**Comment by seuros** [comment]
@jvanbaarsen Thank you for figuring out the issue.
