### ISSUE TITLE
serialize :column, Hash returns string

### ISSUE THREAD

**Issue by abezzub** [rails/rails#20798]
We upgraded our app from Rails 4.1 to Rails 4.2 recently. We have following column in the DB on one of the models:

`t.text     "simulation_outputs"`
In the model:
`serialize :simulation_outputs, Hash`

Sometimes when model is loaded hash is returned as string:
```
> foo.simulation_outputs
=> "{3000.0=>0.068}”
```
Is there something we should've done during upgrade? Is this a known issue?

There is nothing weird with how hash is constructed: it is created manually by assigning keys to a hash and then saved to a model.

**Comment by abezzub** [comment]
It seems to be the problem is where hash is saved. I see following saved in the DB:
```
"{3000.0=>0.0665}"
```
While for record that is loaded normally I see:
```
---\n3000.0: 0.0665\n
```

**Comment by senny** [comment]
@abezzub can you reproduce this error using [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point?

**Comment by abezzub** [comment]
I'll try, but bug does not happen reliably.

**Comment by senny** [comment]
@abezzub any updates? Without a way to reproduce the issue we can't efficiently debug the problem.

**Comment by abezzub** [comment]
I can't reliably reproduce it. This does not happen often, but it keeps happening once in a while. Last time it happened about 3 weeks ago. My guess is there is a race condition and when app is loaded  it sometimes ends up breaking serialization. This problem happens only inside of our workers that are eager loaded.

**Comment by sgrif** [comment]
Unfortunately without the ability to reproduce, there's nothing we can do.

**Comment by akira** [comment]
I seem to be seeing this issue as well and it is reproducible for me.  This happens when I load my ActiveRecord model and then attempt to access the serialized field in a threaded fashion. I am using an array for the serialized field. 

Here is an example that throws errors for me:
```ruby
# Load user but don't access serialized field until the threads start
user = User.first

# access serialized field via thread
20.times do 
  Thread.new do 
    begin 
      # values is a serialized array
      # include? fails for string
      user.values.include?(1) 
    rescue => e 
      puts e
    end
  end
end
```
I get a few "can't convert Fixnum into String" error on the first run of this, but subsequent run of the thread loop (minus loading the model) do not get errors, so I'm guessing it's a race condition in deserializing the field?

**Comment by sgrif** [comment]
Sharing a record across threads is not supported.

**Comment by ah-tunecore** [comment]
After a 4.1 -> 4.2 upgrade I was also seeing this behavior, even in a single thread.  It seemed to be happening when first assigning the attribute to an empty hash and then trying to assign values to keys in the hash. Like so:

```
class MediaLink < ActiveRecord::Base
  serialize :extra_data, Hash
end

@media_link = MediaLink.new

@media_link.extra_data = {}
puts @media_link.extra_data
  "{}"
```
Of course trying to do this blows up now:
```
@media_link.extra_data[:something] = "text"
```

I was easily able to overcome this by assigning the attribute a non-empty Hash.

```
@media_link.extra_data = {something: "text"}
```

**Comment by curtp** [comment]
Logging this info here just in case it helps someone else out.  We're using Rails 4.2 and MySQL.

I was seeing this when creating a new model which had a serialized hash on it in our staging environment.  It worked local just fine.  After digging in, I discovered that our MySQL database was configured differently between local and staging.

Local we have strict: true and in staging we had strict: false.  When I changed staging to match local, everything worked properly.

**Comment by mltsy** [comment]
FWIW: I had the same problem with `ActiveRecord::Store.store` (which is just a thin wrapper around serialize) occasionally, with no discernible pattern, returning a string instead of a deserialized hash.  But just switching to `serialize` has seemed to fix my problem... at least so far.

**Comment by dppcode** [comment]
If you're also using attr_encrypted, make sure all serialize declarations come before attr_encrypted declarations.

**Comment by dustinbrownman** [comment]
I was able to track down what was causing this issue for us. It only happened when attributes were being "mass assigned" (so in the `create`, `update`, `new`, or `build` methods). It had to do with how `attr_encrypted` was overriding that assignment behavior.

`attr_encrypted < 1.3.5` converts the assigning attributes to a `HashWithIndifferentAccess` ([source](https://github.com/attr-encrypted/attr_encrypted/blob/1.3.3/lib/attr_encrypted/adapters/active_record.rb#L16)). This causes the attribute keys to be represented by strings instead of symbols, including the nested hash-serialized attributes, thus saving them to the database as strings.

This is a particularly tricky issue for us because now we have production data where they keys have been "stringified". Upgrading `attr_encrypted` would cause is to have inconsistent keys for production data. We haven't decided on a path forward, but one option is to create a custom serializer that can handle these mismatched key types.

Anyway, spent the better part of a day searching for why this was happening. I'm hoping this is helpful to future folks :)

**Comment by sebach1** [comment]
> I was able to track down what was causing this issue for us. It only happened when attributes were being "mass assigned" (so in the `create`, `update`, `new`, or `build` methods). It had to do with how `attr_encrypted` was overriding that assignment behavior.
> 
> `attr_encrypted < 1.3.4` converts the assigning attributes to a `HashWithIndifferentAccess` ([source](https://github.com/attr-encrypted/attr_encrypted/blob/1.3.3/lib/attr_encrypted/adapters/active_record.rb#L16)). This causes the attribute keys to be represented by strings instead of symbols, including the nested hash-serialized attributes, thus saving them to the database as strings.
> 
> This is a particularly tricky issue for us because now we have production data where they keys have been "stringified". Upgrading `attr_encrypted` would cause is to have inconsistent keys for production data. We haven't decided on a path forward, but one option is to create a custom serializer that can handle these mismatched key types.
> 
> Anyway, spent the better part of a day searching for why this was happening. I'm hoping this is helpful to future folks :)

Same here. After searching about massive assigning with serialization, I've found that reply.
So I supposed the problem was on the assignation, and doing:
Obj.serialized_field = {k: v}
Obj.save
Obj.update(fields)
within the same session (not restarting console nor the container), works. After restarting the console, I've got all the keys stringified, but not more:
"{k: v}"
else, with a YAML format:
---\n:k: \n
So i've inserted a get_serialized_field format which YAML-loads it.
But I think thats so dirty.

**Comment by a17levine** [comment]
I just had this problem upgrading a 4.1 app to 4.2. It was only happening with one of my models but happening consistently in that model so I wrote a test. 

What fixed the problem was moving the `serialize` call closer to the top of the model file. It was originally way down.

4.2 must be implementing `serialize` in a way that is affected by load order because the same test passed with Rails 4.1 but failed in 4.2

**Comment by grdmnt** [comment]
@a17levine This happened to me when I was updating our app from 4.1 to 4.2. I'm glad I saw your comment and by just moving the `serialize` method on top of the model file, it worked magically 😂
