### ISSUE TITLE
ActionDispatch::Response#[] delegated to @header.[], but @header is nil

### ISSUE THREAD

**Issue by sgringwe** [rails/rails#20837]
In Rspec specs for API controllers using http token auth I am getting failures after upgrading from rails 4.2.1 to 4.2.3.

The error is:
```
Failure/Error: api_call "/api/v1/educations", 'post', education_params
     Module::DelegationError:
       ActionDispatch::Response#[] delegated to @header.[], but @header is nil: #<ActionDispatch::TestResponse:0x007f9740e66660 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x007f9740e66610>, @stream=#<ActionDispatch::Response::Buffer:0x007f9740e66570 @response=#<ActionDispatch::TestResponse:0x007f9740e66660 ...>, @buf=["{\"success\":false}"], @closed=false>, @header=nil, @status=200, @sending_file=false, @blank=false, @cv=#<MonitorMixin::ConditionVariable:0x007f9740e66548 @monitor=#<ActionDispatch::TestResponse:0x007f9740e66660 ...>, @cond=#<Thread::ConditionVariable:0x007f9740e66520>>, @committed=false, @sending=false, @sent=false, @content_type=nil, @charset=nil>
     # ./spec/support/request_helpers.rb:30:in `api_call'
     # ./spec/requests/api/v1/educations_spec.rb:13:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'
```

Code is:
```
def api_call(url, type, params={}, auth=true)
    if auth
      @authentication_params = {
        'HTTP_AUTHORIZATION' => ActionController::HttpAuthentication::Token.encode_credentials(@api_key.access_token)
      }
    else
      @authentication_params = {}
    end

    if type.downcase == 'get'
      get url, params, @authentication_params
    elsif type.downcase == 'put'
      put url, params, @authentication_params
    elsif type.downcase == 'delete'
      delete url, params, @authentication_params
    elsif type.downcase == 'post'
      post url, params, @authentication_params
    end

    # We assume we want a success
    expect(response).to be_success
  end
```

**Comment by skolem** [comment]
I’m seeing this also. I believe this is a side effect of changes in this commit: a63760cea7d858984f83549019297221f18ed574

Specifically, the Error is thrown if an ActionDispatch::Response is initialized with a nil header param and a nil default_headers option. I believe this typically will occur in the context of tests since the commit updated ActionDispatch::TestResponse.from_response(response) to pass in a nil default_headers option.  The result is an attempt in the ActionDispatch::Response.initialize method (on line 135) to access an array element on nil (via the delegate on line 51).

A work around in a testing context is to monkey patch ActionDispatch:TestResponse.from_response(response) to pass in an empty default_headers hash instead of nil.

One fix could be to update ActionDispatch::TestResponse as done in the work around. The right fix is probably to change ActionDispatch::Response to handle initialization with a nil header param and a nil default_headers option.

Here’s a test that shows a passing scenario when the header parameter is {} and a failing scenario when it is nil.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '4.2.3'
end

require 'minitest/autorun'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class ActionDispatchResponseBugTest < Minitest::Test

  # Passes
  def test_empty_headers_with_nil_default_headers
    response = ActionDispatch::Response.new 200, {}, [], default_headers: nil
  end

  # Throws error: Module::DelegationError: ActionDispatch::Response#[] delegated to @header.[], but @header is nil
  #
  # See commit https://github.com/rails/rails/commit/a63760cea7d858984f83549019297221f18ed574
  def test_nil_headers_with_nil_default_headers
    response = ActionDispatch::Response.new 200, nil, [], default_headers: nil
  end
end
```

**Comment by sgringwe** [comment]
@skolem Are you using cancan by chance? See https://github.com/CanCanCommunity/cancancan/issues/229 for a discussion and the solution I ended up with.

**Comment by skolem** [comment]
@sgringwe Thanks for the pointer. We do use cancancan, but not in the context of these tests and not in the context of the testcase in my previous post. The only explicit reference to "include CanCan::Ability" in our codebase is in our central Ability class.  I suspect there may be multiple paths to the resulting error.

In my situation, I had a working spec test suite that produced 13 errors after upgrading to Rails 4.2.3. I inserted the monkey patch I mentioned earlier which fixed them all for now.

Thanks again...

**Comment by outdooricon** [comment]
Why was this closed? @skolem stated this was not the same issue as the cancan issue, so there's no resolution for this yet...

**Comment by sgringwe** [comment]
@outdooricon sorry! reopened.

**Comment by outdooricon** [comment]
no worries, thanks for reopening!

**Comment by skolem** [comment]
I ran the test case I provided previously against both Rails 4.2.5 and branch 4-2-stable (gem 'rails', :git => 'https://github.com/rails/rails.git', :branch => '4-2-stable') and the Module::DelegationError still occurs.

**Comment by rafaelfranca** [comment]
How about master?

**Comment by skolem** [comment]
My test case no longer runs against master due to the changes in this commit:  e16afe61abd78c55f80752ca020b90d59ae1940f 

The good news is that I believe the changes to ActionDispatch::TestResponse and ActionDispatch::Response fix the issue.  I don't have an easy way to test this against my rspec suite in a Rails 5.0.0 environment; however, I'm 99% sure it's fixed based on a look through the changes.

This item can be closed and I'll pull out my monkey patch and verify all is well once we upgrade to 5.0.0 down the road.  

Thanks!
