### ISSUE TITLE
We need better integration test coverage

### ISSUE THREAD

**Issue by sgrif** [rails/rails#20945]
There's a serious gap in our test coverage, in places that our gems interface with each other. https://github.com/rails/rails/issues/20922 for example, should never have happened. It looks like at the moment the closest thing we have to integration tests are the railties tests, but that is insufficient. I'd like to propose that we introduce an additional test suite that involves running unit tests for a "simple" Rails app, which includes the minimum usage of pretty much every feature in Rails in a normal context.

I do not think we need to cover edge cases, but we should have better smoke tests to prevent breakage such as "I can no longer pass `params` to Active Record if I'm using `accepts_nested_attributes_for`

**Comment by senny** [comment]
There is the [AWDwR test suite](http://intertwingly.net/projects/AWDwR4/checkdepot-42/) which catches a lot of regressions.

**Comment by rafaelfranca** [comment]
Well remembered. Is that sufficient? (But we need to get it green again, right now it is broken)

**Comment by sgrif** [comment]
While it's definitely a useful tool to have, I don't think it's sufficient for a few reasons:

- It isn't fully comprehensive (nor should it be expected to be)
- It isn't part of the standard Travis build
- If the test itself needs to be updated, we aren't able to do so
- Half of us don't know how to read the output

**Comment by senny** [comment]
My point was that there is a very good test suite already in place but not many committers care about it. Everything related to that test suite is on GitHub, you can run it on your local machine as well, @rubys is very kind and helpful if you have questions. I'm not against building stronger integration tests on our own but I think it's worth to fully use what we have right now.

* I don't think that any test suite we build will be fully comprehensive.
* That's true
* We can do that.
* That's like saying I don't understand a flamegraph. One can learn to read the output and if there are areas where we can improve the reporting, we should do that.

**Comment by rubys** [comment]
What would I need to do to address @sgrif's concerns?

**Comment by rafaelfranca** [comment]
@rubys right now we need to get the AWDwR tests passing. They are not passing for 4-2-stable branch and neither with master. I know you are working in a new version of the book and it is just a matter of time for getting both passing.

Other thing we can do is get back the test result alerts in our new Campfire room.

> If the test itself needs to be updated, we aren't able to do so

This one I don't know if we would be able to do. I think we are not.

> Half of us don't know how to read the output

This one can be improved indeed but right now I'm out of ideas but I'm happy to help with the improvement in the output of the tests.

**Comment by rubys** [comment]
@rafaelfranca how important is getting these tests passing on 4.2?  I'll also make the comment that it would be in everybody's best interest if multiple people were able to run and interpret the results.  All code needed to run the tests is published on GitHub.  All code is tested on both Mac OS/X and Ubuntu; I even have a Vagrant file.  Expanding the tests to include scenarios not covered by the book is fine with me, and I'll even help.

Backing up, for the benefit of anybody who might be interested.

Agile Web Development with Rails is a book targeted at experienced developers who are new to Rails, and possibly even Ruby itself.  It is a book organized into chapters, and in those chapters are step by step instructions, exercises, and (in the back of the book) code fragments demonstrating a specific concept.

The AWDwR test suite is organized by chapter sections, and within each section is a series of steps.  Steps generally take one of the following forms:
 * edit a file
 * run a command, as if from the command line
 * issue a HTTP request, as if from a browser.

All steps, as well as their output, are captured in the form of a HTML page per chapter section.  Validation of the results is accomplished via a series of `assert_select` commands run against that page.  If you know how to write Ruby code and have a basic knowledge of Rails externals, you have everything you need to know to write both scenarios and tests.

At the present time, the tests are mostly passing (except for deployment) with Rails 4.1:

  http://intertwingly.net/projects/AWDwR4/checkdepot-41/

The very same tests are failing with Rails 4.2:

  http://intertwingly.net/projects/AWDwR4/checkdepot-42/

The first step that fails is in section 6.2.  Selecting it and scrolling down, you will see:
 
    Sprockets::Rails::Helper::AssetNotPrecompiled in Products#index
 
Given that I'm running the rails server in development mode, and I didn't adjust the scenario, it is not obvious to me what the problem is.  It could be a problem with Rails.  It could mean that I need to adjust the scenario.  It could be both.  As far as helping people debug it, I don't know what more information I can publish than what commands I ran, in what sequence, and what output those commands produced.  I also capture environment information (versions of ruby, gems, OS, etc).

---

What's annoying about this code?

 * There is a bootstrap problem where knowing what gems to install for developing on "edge" depends on first installing Rails; I get around that by parsing Rails source files.  Ugly, but it works.  It also means that I can update to the latest Rails and retest without reinstalling everything.  That's handy when I do a git bisect.
 * editing of files and running of commands both turn out to be very release specific.  Rails may change a generator in a "dot" release as that's not advertised as a stable API.  Rails 5.0 plans to change a large number of commands (e.g. `rake` => `rails`).  Some of the command changes I can automate: my general approach is to have the scenarios be defined in terms of the latest commands, and to intercept those commands and substitute equivalents for prior versions of rails.
 * if I have a failure late in the overall scenario, describing the problem with a minimal number of steps can be tricky and time consuming.  Providing a complete snapshot of the application at the point of the failure, however, is no problem.

---

As far as plans go, if I can get others to look at this, I'll be glad to enable and assist with ensuring that these tests run on various versions of Rails and support scenarios other than the ones described in my book.  Failing that, I'll likely focus primarily on Rails 5.  I also plan to add a Docker file.

**Comment by rafaelfranca** [comment]
I believe this is being addressed with the AWDwR test suite. We should evolve it if we feel it is not sufficient but I don't want to introduce a new test infrastructure that does the same thing that the books suite do now.

**Comment by sgrif** [comment]
I still feel that the book is not a great answer to this. Its test suite is not exhaustive, and is ultimately testing the book -- not Rails. Because of that, its structure makes it difficult to know what is or isn't covered, and there's not a good harness in place for tests to be added covering features or interactions that aren't covered by the book.

**Comment by rafaelfranca** [comment]
We also have the railties tests. It creates applications and can be as exhaustive we want it to be.

**Comment by rubys** [comment]
@rafaelfranca Note that @sgrif said "at the moment the closest thing we have to integration tests are the railties tests, but that is insufficient".  I agree.

@sgrif Note that @rafaelfranca said "We should evolve it if we feel it is not sufficient".  I fully support the notion of adding tests that cover things that the book does not cover.  If you want 'a "simple" Rails app, which includes the minimum usage of pretty much every feature in Rails in a normal context', I do believe that I have a running head start on that.  Feel free to add to it.

**Comment by sgrif** [comment]
> and can be as exhaustive we want it to be.

That's the reason I opened this issue. They're not as exhaustive as they should be, and I think we should work to improve it.

**Comment by rafaelfranca** [comment]
Yeah I agree with that but having the issue open here will not fix anything. We don't use the issue tracker to `things that needs to be improved' and this is the biggest reason that I closed it.

The only way to improve this is working on it. We can improve the integration test coverage as we need (what I prefer) or we can get someone focused on identifying what is missing and writing the tests. In 9 months that this issue is open we didn't do any of these things and I don't think this will change keeping this issue open.

**Comment by sgrif** [comment]
Yeah, I'm fine with closing this. I just wanted to acknowledge that it doesn't mean our test coverage is sufficient.
