### ISSUE TITLE
railties 3.2.22 pins rack-ssl to 1.3

### ISSUE THREAD

**Issue by pxlpnk** [rails/rails#20964]
Because of this updating to a new version of rack-ssl is not possible. Which leaves a security vulnerability open.
Is there a special reason why this is pinned down to 1.3?
I would propose a PR if this will help.

CVE: http://cve.mitre.org/cgi-bin/cvename.cgi?name=2014-2538
ruby-adivsory-db: https://github.com/rubysec/ruby-advisory-db/blob/970b2377902c5d034a227c4d422ad691f95262e0/gems/rack-ssl/OSVDB-104734.yml
gemspec: https://github.com/rails/rails/blob/v3.2.22/railties/railties.gemspec#L27

**Comment by rafaelfranca** [comment]
The reason is just historical, there is no good reason but since Rails 3 is not supported anymore we are not going to change. However, when this security issue come out we worked with rack-ssl's maintainer and got the fix also in 1.3.4. See https://github.com/josh/rack-ssl/compare/v1.3.3...v1.3.4 and https://github.com/josh/rack-ssl/pull/34

**Comment by pxlpnk** [comment]
thank you for the update.
