### ISSUE TITLE
Time zone should default to system offset

### ISSUE THREAD

**Issue by aeberlin** [rails/rails#20970]
See below:
```
frozen_time = Time.parse('2015-07-21 19:24:33 -0500')


# Without active support, CDT system time zone.


irb(main):008:0> Timecop.freeze(frozen_time) { Date.today }
=> #<Date: 2015-07-21 ((2457225j,0s,0n),+0s,2299161j)>


# With active support, no default time zone configured, CDT system time zone.


[1] pry(main)> Timecop.freeze(frozen_time) { Date.current }
=> Wed, 22 Jul 2015
[2] pry(main)> Timecop.freeze(frozen_time) { Date.today }
=> Tue, 21 Jul 2015

[3] pry(main)> Time.zone
=> #<ActiveSupport::TimeZone:0x007f919cce55d8
 @current_period=#<TZInfo::TimezonePeriod: nil,nil,#<TZInfo::TimezoneOffset: 0,0,UTC>>>,
 @name="UTC",
 @tzinfo=#<TZInfo::TimezoneProxy: Etc/UTC>,
 @utc_offset=nil>

[4] pry(main)> Thread.current[:time_zone]
=> nil
[5] pry(main)> Time.now.getlocal.zone
=> "CDT"
```

So, as we can see, time zone is correctly inferred with `Date.today`, but not with `Date.current`. That being said, this is a breakdown of expectations, IMO, as `Date.current` should always be _more accurate_ than `Date.today`. If a time zone is not configured, I believe the system time zone offset should be used as the default, and not UTC.

**Comment by pixeltrix** [comment]
It's not that no default timezone is configured it's just the default timezone is UTC. This is so that there's consistency between running your app locally and on the server - if we defaulted to using the system timezone then there could be discrepancies between your development environment and the server depending on how each was configured.

Since this setting is in a prominent place in `config/application.rb` then I can't see any pressing need to change what has been a long-standing default setting. Thanks for your input.
