### ISSUE TITLE
My PR was locked and seems to be ignored

### ISSUE THREAD

**Issue by bquorning** [rails/rails#21034]
24 days ago, I opened https://github.com/rails/rails/pull/20757, changing some v4.2 related documentation that was incorrect due to a change in Rack.

I had a couple of coworkers give review my changes, after which @matthewd locked the PR (without explanation), and there has been no conversation on the PR since.

What’s the policy regarding locked conversations? How do I get it unlocked, or reviewed by a repository collaborator?

**Comment by rafaelfranca** [comment]
Sorry about that. We usually locks issues that have only +1 comments because they don't add anything to the discussion and just pings the contributors. We have limited time and resources and pings are usually annoying to us, so we tends to lock issues with many pings. 

Your case just had two, but I believe Matthew locked to avoid that becoming a trend. 

I just unlocked the PR and added to my review queue. Thank you so much for reporting.
