### ISSUE TITLE
disable_ddl_transaction! is a misleading name

### ISSUE THREAD

**Issue by PhilCoggins** [rails/rails#21044]
[`disable_ddl_transaction!`](https://github.com/rails/rails/blob/v4.2.3/activerecord/lib/active_record/migration.rb#L424) is used in AR migrations to prevent your migration from being wrapped in a transaction. The name is misleading because *your entire migration* will have transactions disabled, not just for DDL SQL statements.

If I have a migration that contains a mixture of DDL and DML SQL, and declare `disable_ddl_transaction!` at the top of my migration, I would still expect DML to be wrapped in a transaction, but this is not the case, as the DML SQL statements are still executed outside of a transaction.

If the desired behavior is to disable only DDL transactions, then I would consider this a bug, but I believe the intent of this method is to prevent your entire migration from running in a transaction, and thus the method is poorly named. Perhaps `disable_transaction!` would be more appropriate?

**Comment by mgodwin** [comment]
:+1: I agree.  

I also find it misleading because you're not disabling *all* transactions for the duration of the entire migration, just that the migration as *a whole* is wrapped in a transaction.  (You can still start up transactions/ddl transactions on your own).  The [rails guides](http://guides.rubyonrails.org/active_record_migrations.html) and the [rdoc](http://api.rubyonrails.org/classes/ActiveRecord/Migration.html#method-c-disable_ddl_transaction-21) don't really mention that fact anywhere and more generally say:

> Disable DDL transactions for this migration.

Which would imply to me that you can't run any DDL transactions at *all*, which isn't true :confused:

I think clarifying the docs could go a long way or renaming the method could help.  Some suggestions I have could be: `without_transaction!` or `manual_transactions!` - I think the latter is more clear.  I'm not sure that the `ddl` part is necessary since you won't get transaction support if the adapter doesn't support ddl transactions anyways, right?

**Comment by senny** [comment]
I agree that the name could be better. The `ddl_` part was chosen to make it clear that this only affects adapters supporting ddl transactions. For example to a MySQL adapter user `without_transaction!` is not clear as there is no wrapping transaction.

:+1: on making the docs more clear. I'm not sure we have to change the name though.

/cc @rafaelfranca @carlosantoniodasilva

**Comment by carlosantoniodasilva** [comment]
I think the documentation on the [`ActiveRecord::Migration` module that talks about Transactional Migrations]http://api.rubyonrails.org/classes/ActiveRecord/Migration.html) explains better the intention of the method, including the "transaction wrapping". With this in mind, I'm leaning towards improving the method documentation a bit as well, rather than a method name change :+1:

**Comment by rafaelfranca** [comment]
Same here :+1: for doc change.
