### ISSUE TITLE
undefined method `helper_method' for ActionController::API:Class (NoMethodError)

### ISSUE THREAD

**Issue by ballPointPenguin** [rails/rails#21067]
I encountered this with a new Rails 5 api only application using devise.
It seems to have been addressed in the rails_api project once before:
https://github.com/rails-api/rails-api/pull/10
https://github.com/rails-api/rails-api/issues/6

**Comment by pixeltrix** [comment]
@jmbejar @spastorino I guess we now remember why the compatibility module was added (ref: fd2508522c341c3f708219b5fc1834f24caf04e3) - do we want to add it back in?

**Comment by jmbejar** [comment]
@pixeltrix I'm not sure if we should add a stub method here instead of having Devise asking for the method presence before invoking (as discussed [here](https://github.com/rails-api/rails-api/pull/10) in the past).

Thinking about the need for this fix: I understand that this exception happens when the user browse any of the Devise's routes, however using those routes are valid for the user authentication flows implemented by the library where rendering html pages happens. But rendering html is not the case in an Rails API app.

@ballPointPenguin How do you plan to use Devise in the context of a Rails API app? How the authentication flow work and when the exception is happening?
If we know how the exception was raised in the context of a real use case, we could better decide how/where to fix it.

**Comment by jeffdill2** [comment]
@jmbejar I can't speak for @ballPointPenguin but I plan on using Devise for token-based authentication. For me the error occurs simply when the app is initialized from `environment.rb`. However, it's not happening locally, only when I push to Heroku.

**Comment by jmbejar** [comment]
@jeffdill2 I would like to reproduce the error so I can have some opinion about how to fix it. What Rails/Devise versions are you using?
If you can provide the app source - or maybe just the Gemfile - could help me to reproduce the error.

**Comment by ballPointPenguin** [comment]
Similar to @jeffdill2's experience, I plan to use token authentication for my API with Devise. I am experiencing the error when the app is initialized locally.
I have the basis of a new Rails 5 api app here https://github.com/ballPointPenguin/adopt-a-api
But the issue is solved on master because I'm using my #21151 fork of Rails.

**Comment by ballPointPenguin** [comment]
I think I agree in principle, @jmbejar that the onus should be on Devise, or other gems, to be safer when calling Rails methods. That said, I feel that the nicest :smile_cat: solution is to preserve backwards-compatibility, or non-api compatibility as it were, in rails itself.

**Comment by jmbejar** [comment]
@ballPointPenguin Given that https://github.com/plataformatec/devise/issues/3690 was fixed in their own, should we close this issue?

**Comment by ballPointPenguin** [comment]
yes. good.
