### ISSUE TITLE
nested attributes validation on updating

### ISSUE THREAD

**Issue by bennylin77** [rails/rails#21117]
I have two models 'Product' and 'ProductBoxing', product has many product_boxings.  
```ruby
class Product < ActiveRecord::Base
  has_many   :product_boxings
  accepts_nested_attributes_for :product_boxings 
  validates :name, presence: { presence: true, message: 'please give a name' }, on: :update
end

class ProductBoxing < ActiveRecord::Base
  belongs_to :product
  validates :quantity, presence: { presence: true, message: 'please fill in quantity' }, on: :update 
end
```

```ruby
<%= form_for(@product, html: {class: "form-horizontal", role: "form", multipart: true}) do |f| %>
    <%= f.text_field :name%>
    <%= f.fields_for :product_boxings do |g| %>		 
		<%= g.text_field :quantity %>		
    <% end %>		
<% end %>
```

For some reasons, I create both product and product_boxing without validation first. After that, I want to validate both on updating. The validation works for 'Product', but not for 'ProductBoxing'.

Are there any problem in my code? or it is a rails issue?

BTW,  I remove validation option  "on: :update" and validate both on creating, the validations work for both.

**Comment by bennylin77** [comment]
I found a new situation, if quantity has been filled, the validations of quantity works.

**Comment by delphaber** [comment]
Same happens here. I had to remove the `on: :update` and build the nested resources in memory instead of creating in database

**Comment by alexanderchr** [comment]
If your problem is that a `Product` may appear valid while an attached `ProductBoxing` is invalid, it can be solved by adding `validates_association: :product_boxing` to your `Product` model.

This issue stems from the default behavior of has_many, which is to validate members of the collection but only when a new record is added (see https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_many_association.rb#L46). It would probably be better if the default behavior of `has_many` was the same as that of `validates_association`.
