### ISSUE TITLE
Marking a class as unloadable causes code reload to throw "Unable to autoload constant, expected ...rb to define it"

### ISSUE THREAD

**Issue by pierre-pretorius** [rails/rails#21198]
The following steps explain and reproduce the problem:

1) Create new Rails 4.2.3 app:
```
rails new polls
cd polls
bundle exec rails generate scaffold Question name:string
bundle exec rake db:migrate
```

2) Mark the Question model as unloadable:
```
nano app/models/question.rb

# Edit the content so that it looks as follows:
class Question < ActiveRecord::Base
  unloadable
end
```

3) Do something that causes Rails to reload code:

```
rails s &
curl localhost:3000/questions -s > /dev/null
touch app/models/question.rb
curl localhost:3000/questions -s > /dev/null
```

The following is printed by the rails server:
```
Started GET "/questions" for 127.0.0.1 at 2015-08-11 19:31:11 +0200
Processing by QuestionsController#index as */*
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)

LoadError (Unable to autoload constant Question, expected /home/pierre/poll/app/models/question.rb to define it):
  app/controllers/questions_controller.rb:9:in `index'


  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.7ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.3ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (11.5ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.2ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.2ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (8.2ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.2ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.2ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (17.8ms)
```

Unloadable is used extensively by Redmine plugins (it's been in their plugin generate scripts for years) and their latest stable is now Rails 4.2.3:
http://www.redmine.org/issues/20513

**Comment by pixeltrix** [comment]
The `unloadable` method is typically used for classes that would normally not be unloaded - a model in `app/models` would be unloadable by default and that may be what's causing the error. Does the same problem occur if the class is a standard class placed in the `lib` folder of a new 4.2.4 app (which is on the load path but is not in the autoload paths).

**Comment by maxjacobson** [comment]
@pixeltrix just did a little investigation to try and answer your question. Here's a test repo: https://github.com/maxjacobson/test_unloadable and the relevant commit: https://github.com/maxjacobson/test_unloadable/commit/98065aca599e8477d766c0f60a2b51ccf5bb2c3f

The behavior is different here. Saving the `lib/dog.rb` file doesn't cause any problems, but saving `dogs_controller.rb` (which has `require 'dog'`) does cause it to lose its reference to the constant. It fails in a different way, though. Instead of failing with the `Unable to autoload constant` message, it fails with `uninitialized constant DogsController::Dog`. I'm not sure if that's the desired behavior for unloadable or not.

**Comment by thedarkone** [comment]
@pierre-pretorius this is all quite complicated, if you haven't, you should check out [Autoloading and Reloading Constants Guide](http://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html).

First thing, we [can't use `require` with autoloadable/unloadable constants](http://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-require). So we need to replace `require 'dog'` with `require_dependency 'dog'`, the error then goes away.

Though another issue then appears instead: any changes made to `lib/dog.rb` are not visible until `app/controllers/dogs_controller.rb` is also saved. This is caused by Rails optimization that performs const reload only if any relevant (autoloaded) `.rb` files are changed. To fix this, either the optimization needs to be turned off `config.reload_classes_only_on_change = false` or Rails needs to be made aware of `dog.rb` directory `config.watchable_dirs["#{Rails.root}/lib"] = [:rb]`.

Other than that, in general, it is best to avoid ever using `unloadble`, just point Rails at the proper directories and let it do its thing.

**Comment by pixeltrix** [comment]
@maxjacobson as @thedarkone points out anytime you're dealing with autoloading of constants you need to use `require_dependency`. It's better to try and work within the app directory for reloadable code - for instance add a app/lib directory for code that's actively been worked on that doesn't fit one of the other directories.
