### ISSUE TITLE
unexpected inconsistency with durations when using JSON.dump vs to_json

### ISSUE THREAD

**Issue by imtayadeway** [rails/rails#21242]
Pairing with @plribeiro3000 a while ago I recalled we discovered an inconsistency when using `JSON.dump` vs `to_json` on objects that contained durations. To illustrate:

```
irb(main):001:0> JSON.dump({"foo" => 1.minute})
=> "{\"foo\":\"60\"}"
irb(main):002:0> JSON.dump({"foo" => 60})
=> "{\"foo\":60}"
irb(main):003:0> {"foo" => 1.minute}.to_json
=> "{\"foo\":60}"
irb(main):004:0> {"foo" => 60}.to_json
=> "{\"foo\":60}"
```

As you can see, each expression represents the value as `60` apart from the first which represents the number as a string. This was (to us) a surprising and subtle difference between the two.

Interestingly, I notice that this was not the case on an earlier release of Rails (4.0), the above being 4.2.3. Was this an intentional change in behavior, or could this be a bug?

**Comment by rafaelfranca** [comment]
I believe it is a bug, but @chancancode can know better

**Comment by chancancode** [comment]
I *think* this is expected behavior. The top-level `::JSON` constant is provided by the standard library `json` gem. In the past it just so happens that we have been accidentally "fighting" over APIs with the same name but different meaning (to_json) which resulting in many conflicts, incompatibilities and bugs.

Starting in 4.1 we take special care to not interfere with each other. That is, JSON.dump/generate (an API provided by json gem) will give you the same result with or without Rails being loaded.

If you want the Rails JSON encoder (which is completely different from the standard lib one, specifically we take into account the as_json hook but they don't) then you should use ActiveSupport::JSON.encode, which is usually aliases as *.to_json unless you go out of your way to disable core extensions.

**Comment by chancancode** [comment]
In this case json gem doesn't know what to do with the Duration object it encountered, so it defaulted to 'to_s'; AS encoder called as_json on it instead

**Comment by imtayadeway** [comment]
thanks @chancancode :D

**Comment by plribeiro3000** [comment]
Hmmmm. Thanks @imtayadeway @chancancode
