### ISSUE TITLE
ActiveRecord has_many guessing wrong foreign_key when STI on 4.2.X

### ISSUE THREAD

**Issue by mmontossi** [rails/rails#21295]
Test case provided: https://gist.github.com/mmontossi/111bdd947f5665c6ef8b

**Comment by al2o3cr** [comment]
The `locations` association is declared in the `Place` class, so `place_id` is the default foreign key name. 

If the result you're expecting in the test case was the default behavior, it would cause difficulties for code like this:
```ruby
class Place < ActiveRecord::Base
  has_many :locations
end

class City < Place
end

class Lake < Place
end

class Location < ActiveRecord::Base
  # what's the foreign key now? Should there be a city_id AND a lake_id column on the locations table?
end
```

You can get the behavior you're expecting by declaring the `has_many :locations` in `City`, but that will also mean redeclaring it in each descendant of `Location` - and you'll lose the ability to do things like `Location.includes(:place)`, since the parent class will not know about the association.


An unrelated side-note: your example is not using STI, as the `inheritance_column` (default name `type`) does not exist on the `places` table. If you execute `Place.first` with those models, you will always receive a `Place` object back, even if you originally wrote the object to the database with `City.create`.

**Comment by mmontossi** [comment]
I think is a big cost to lost the ability to do things like includes, I made this after_initialization callback to keep the app working in the meantime:

```ruby
def fix_bug
  r = self.class.reflect_on_association(:locations)
  r.instance_variable_set :@foreign_key, "#{self.class.model_name.singular}_id"
end
```

Wouldn't be possible to make ActiveRecord build the association object at that moment so it picks the right column? (I notice extracts the column from the model but uses the base class because the code is cached before inheritance)

I think it may be a little related  to the issue of STI populating type column with the base class, I know this was the original intention (to have a references to the table), but it's really the most intuitive and lean way to solve it for the point of view of api usage?

I didn't include the type column intentionally to simplify the example.

**Comment by al2o3cr** [comment]
@mmontossi It sounds like what you want would look more like:
```ruby
class Place < ActiveRecord::Base
  # no association here
end

class City < Place
  has_many :locations
end

class Lake < Place
  has_many :locations
end

class Location < ActiveRecord::Base
  belongs_to :city
  belongs_to :lake
end
```
This is still not ideal as mentioned above (what SQL would make `Place.joins(:locations)` work?) but relatively straightforward.

I would STRONGLY advise against the `fix_bug` strategy you proposed, as it will not work for anything that depends on associations outside of a single object (`joins`, `includes`, etc).

I did not quite understand your last statement ("I know this was the original intention (to have a references to the table), but it's really the most intuitive and lean way to solve it for the point of view of api usage"). If you mean "API usage" from the perspective of a REST API, it's possible and frequently useful for your API to present a different view to the outside world than the underlying database schema.

In any case, I'd say this issue is not a bug but a feature request; this is not the appropriate forum to discuss feature requests. Please reach out to me on [rubyonrails-talk](https://groups.google.com/forum/#!forum/rubyonrails-talk) if you'd like to continue discussing how to represent your data.

**Comment by mmontossi** [comment]
I notice something else, if I have some others associations like this:

```ruby
class Place < ActiveRecord::Base
  has_many :locations
  has_many :shops, through: :locations
  has_many :products, through: :shops
end
```

Or any method using those associations:

```ruby
class Place < ActiveRecord::Base
  def do_something
    shops.count
  end
end
```

I would have to move copy all of them to the descendants.

**Comment by mmontossi** [comment]
The fix_bug is temporary to study which would be the best solution, don't worry I know is REALLY dirty.

What I mean it by API was the ActiveRecord interface not an REST API, maybe it was not the most correct way to express it. Searching through the issue tracker I found some others issues about the type column in STI classes using the base class:

#4729
#5441

It sounded related to me, so I thought about mention it. I thing would be nice if rails always uses the final class and not the base class in STI cases.

**Comment by henrik** [comment]
For future googlers – we had a similar but not identical issue. We had STI models on both ends of the association, and we had the equivalent of `place_id` rather than `city_id`.

We could fix our issue by adding a `foreign_key` like

```
class Place < ActiveRecord::Base
  has_many :locations, foreign_key: :place_id
end
```
