### ISSUE TITLE
Association Guide use Order as example, which is already used.

### ISSUE THREAD

**Issue by yxhuvud** [rails/rails#21500]
The association guide, http://edgeguides.rubyonrails.org/association_basics.html use the Order class as an example for expressing most association information.

However, that name conflicts with the 'order' scoping directive meaning that it is harder than necessary to search the guide for how to set up a default ordering.

Noticed when upgrading to 4.x and looking for the correct ordering syntax.

**Comment by yxhuvud** [comment]
Well, I were looking for how the new way of setting up a default ordering of an association looked like. Doing Ctrl-F for 'order' gave a zillion matches due to the Order example. Earlier (ie 3.x) :order was an option to the association methods, but now it is changed to being passed in a lambda like the other scope directives.

Of course, it is a minor detail that may not be worth rewriting the whole document for :)

**Comment by senny** [comment]
I see. I personally don't feel like this naming collision warrants rewriting all the examples. However if someone submits a PR with an equally good example I guess we can merge.

@zzak thoughts?

**Comment by zzak** [comment]
It's probably good to avoid naming classes that collide with options or other methods that someone might be searching for. But I think that ship has already sailed.

I agree it's confusing, but I'm not sure it's worth rewriting all of the examples to avoid the collision.

Like YS said, if someone wants to write a patch for this, sure, because the actual classes in this guide are just there for example. It could just as easily be Author -> Books association or something else for this example.

**Comment by maclover7** [comment]
PR at #21555.
