### ISSUE TITLE
Rails 4.2 not symbolizing string keys when using params in url helper

### ISSUE THREAD

**Issue by jfragoulis** [rails/rails#21645]
```ruby
# produces http://localhost:3000/blog/post?action=index&controller=blog/post&published=true
blog_post_path(params.merge(published: 'true')) 

# produces http://localhost:3000/blog/post?published=true
blog_post_path(params.merge(published: 'true').symbolize_keys) 
blog_post_path(params.merge(published: 'true').to_h)
```

Looking at the code [here](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/route_set.rb#L313) I realized that `options` is clearly **required** to be a `Hash`, which is **not** when the client is passing `params` directly in a url helper.

That happens because `params` returns `ActionController::Parameters` which internally uses `HashWithIndifferentAccess`. 

The solution is to use either `params.to_h` or `params.symbolize_keys`. The latter would also _hide_ any deprecation warnings.

I do not know whether this is [intended or not](https://github.com/rails/rails/issues/20353#issuecomment-106652511) but it would surely make everyone's life easier to just make sure that `options` is a `Hash` before symbolizing its keys [here](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/route_set.rb#L320), because right now when you pass `params` in a url helper, it **does not work neither does it throw a warning/error**.

I suggest we change the [line](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/route_set.rb#L313):

```ruby
# from
options ||= {}

# to
options = options ? options.to_h : {}
```

Related to:
https://github.com/rails/rails/issues/20353
https://github.com/rails/rails/pull/17743#issuecomment-102393355

**Comment by jasonnoble** [comment]
Alternative:

    # from
    options ||= {}

    # to
    options = options.to_h

`nil.to_h` returns `{}`.

**Comment by pixeltrix** [comment]
Symbolising the params passed from a request would lead to a DoS attack on the symbol table in versions of Ruby earlier than 2.2 so converting those keys is not an option and why we've explicitly deprecated string keys for controller and action too.

Passing in a params hash to url helpers is really a bad idea - you should whitelist them first otherwise you could create a security hole in your application. When dealing with user submitted params in url generation you should treat them in the same way as you would do when preventing SQL injection or XSS attacks.

In your example above it's straightforward to use `slice`:

``` ruby
blog_post_path(params.slice(:published).merge(published: 'true'))
```

Closing because this is the intended behaviour

**Comment by jfragoulis** [comment]
I am sorry but you missed the point. 

The point is that the implementation is buggy. The fact that I (or anyone else) misuses the API or whatever is secondary.

The reality is that currently 4.2-stable has a bug there @ `#deprecate_string_options`. You can close the issue but there is PR for this #21648 which needs to be merged regardless.

**Comment by pixeltrix** [comment]
@jfragoulis what about the implementation is buggy?

From the original description it seems like your bug is that the controller and action appear in the query string - is this what you're saying?

**Comment by jfragoulis** [comment]
No. Consider the following:

```ruby
my_hash = HashWithIndifferentAccess.new "key" => "value"
...
blog_post_path(my_hash)
```

This will print a deprecation message about `"key"` but `#deprecate_string_options` will still return `{"key" => "value"}` instead of `:key => "value"`.

**Comment by pixeltrix** [comment]
@jfragoulis yes, I understand that the internal representation will still have string keys but adding extra checks and conversions there will slow down a hotspot within Rails applications. If the only affect is that controller and action keys are appended to the url then I'm loathe to slow down other people's applications to accommodate what is not a recommended practise. The deprecation is there for people either using string keys in routes.rb or string keys with `url_for` in controllers and views where it's likely to be a hash already.

Historically, Rails has been forgiving in these kinds of situations but these accommodations have a tendency to spread throughout the code and we end up having to call `dup`, `to_sym`, `to_s`, etc. which can lead to to unnecessary object creation and memory usage. There's been a lot of work gone into eliminating these and that's why I'm questioning the value of merging the PR.

However given that it appears to be a regression from 4.0 and 4.1 that the controller and action are added to the query params (they're present in 3.2), there's an argument to be made that we should fix it on that grounds. If you want to update the PR to include a test case for this scenario then I'd be happier about merging it - if we have to do it to be right then we'll live with the extra cost.

Thanks for your patience.

**Comment by agis-** [comment]
> Symbolising the params passed from a request would lead to a DoS attack on the symbol table in versions of Ruby earlier than 2.2 so converting those keys is not an option [...]

@pixeltrix Considering this, I don't think there is a way to fix this issue at the moment. So I'm kinda confused by your following statement:

> However given that it appears to be a regression from 4.0 and 4.1 that the controller and action are added to the query params (they're present in 3.2), there's an argument to be made that we should fix it on that grounds.

I don't see any way of fixing this without converting the *whole* `inner_options` to a hash.
