### ISSUE TITLE
seconds_since_midnight does not take utc_offset into account

### ISSUE THREAD

**Issue by MarcosMenegazzo** [rails/rails#21750]
The current implementation of `seconds_since_midnight` does not take `utc_offset` into account. Maybe its the intended behavior, maybe not. 
```ruby
require "spec_helper"

describe ActiveSupport::TimeWithZone do
  describe "#seconds_since_midnight" do
    # 8 * 60 * 60
    let(:eight_hours_secs) { 28800 }

    it "Timezone aware" do
      # Works
      Time.use_zone("UTC") do
        expect(Time
               .zone
               .at(eight_hours_secs)
               .seconds_since_midnight).to eq(eight_hours_secs)
      end
      # Fails. Will return 18000 instead of 28800
      Time.use_zone("Brasilia") do
        expect(Time
               .zone
               .at(eight_hours_secs)
               .seconds_since_midnight).to eq(eight_hours_secs)
      end
    end
  end
end
```
IMO, using the example above, 8 hours in seconds will always be 28800, no matter what TimeZone is. 

But because ActiveSupport has different implementations of `seconds_since_midnight` for [Time](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/time/calculations.rb#L57) and [DateTime](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/date_time/calculations.rb#L18), and of course because this method is added directly to those classes, i'm not sure what would be the best fix for this.

Something like:
```ruby
module ActiveSupport
  class TimeWithZone
    # Returns a number of seconds of a Time, since midnight and
    # considering timezone offset
    def seconds_since_midnight_utc
      seconds_since_midnight - utc_offset
    end
    alias :seconds_since_midnight_with_offset, :seconds_since_midnight_utc
  end
end
```

What do you think?

**Comment by al2o3cr** [comment]
`at` is defined to return a `Time` object with that number of seconds since the Unix epoch (1970-01-01 00:00Z). In the Brasilia TZ, eight hours past epoch is `1970-01-01 05:00:00 -0300`, so returning 18000 seems like a correct result...

**Comment by MarcosMenegazzo** [comment]
Time.at -> ok. Its returning a Time, not a TimeWithZone
Time.zone.at -> not ok. Its returning a TimeWithZone, not a time.

If you try to rebuild a TimeWithZone using 18000, you will get a different hour.

**Comment by rafaelfranca** [comment]
PDI. `TimeWithZone#at` maybe is being called directly in `Time` without timezone information.

**Comment by al2o3cr** [comment]
@MarcosMenegazzo The Unix epoch is not specific to a particular timezone. In anything other than UTC it isn't at midnight. In irb:
```
[5] pry(main)> Time.use_zone("Brasilia") { Time.at(0) }
=> 1969-12-31 19:00:00 -0500
[6] pry(main)> Time.use_zone("Brasilia") { Time.zone.at(0) }
=> Wed, 31 Dec 1969 21:00:00 BRT -03:00
```

Both return the same time, 0 seconds past the epoch, but in either the system TZ (I'm in US Eastern) or the selected TZ.

Can you provide more information on what you're expecting `at` and `seconds_after_midnight` to be able to do?

**Comment by MarcosMenegazzo** [comment]
@rafaelfranca  I think the problem is not `TimeWithZone#at`, is `seconds_since_midnight`.

@al2o3cr What i'm trying to demonstrate is that rebuilding a TimeWithZone using a `seconds_since_midnight` return value will not give the same time information:

```ruby
# Using UTC
[11] pry(main)> Time.use_zone("UTC") { Time.zone.at(28800) }
=> Thu, 01 Jan 1970 08:00:00 UTC +00:00
[12] pry(main)> Time.use_zone("UTC") { Time.zone.at(28800).seconds_since_midnight }
=> 28800.0 # correct, please note the input and output values

# Changing timezone
[13] pry(main)> Time.use_zone("Brasilia") { Time.zone.at(28800) }
=> Thu, 01 Jan 1970 05:00:00 BRT -03:00
[14] pry(main)> Time.use_zone("Brasilia") { Time.zone.at(28800).seconds_since_midnight }
=> 18000.0 # WRONG, must be 28800, because:

# If you try to use the return value above to rebuild, you'll get:
[15] pry(main)> Time.use_zone("Brasilia") { Time.zone.at(18000) }
=> Thu, 01 Jan 1970 02:00:00 BRT -03:00 # 
```

**Comment by pixeltrix** [comment]
@MarcosMenegazzo the `seconds_since_midnight` implementation only deals with time relative to the instance of `Time` or `TimeWithZone` so the problem isn't there. The cause of the problem is that `Time.zone.at(0)` does a `Time.at(0).utc.in_time_zone(Time.zone)` - i.e. it converts from UTC to the timezone whereas what you're trying to do is set the time in the timezone, e.g.:

``` irb
>> "1970-01-01T00:00:00Z".in_time_zone('Brasilia').seconds_since_midnight
=> 75600.0
```

In your example above you're trying to feedback a app timezone adjusted value into a method that expects a UTC timezone value - in other words you are trying to do this:

``` irb
>> "1970-01-01T21:00:00Z".in_time_zone('Brasilia').seconds_since_midnight
=> 64800.0
```

What you probably think you're doing is this:

``` irb
>> "1970-01-01T21:00:00".in_time_zone('Brasilia').seconds_since_midnight
=> 75600.0
```

You could argue that `Time.zone.at` should work in the app timezone but the problem lies there and not with `seconds_since_midnight`.

@rafaelfranca have any opinions on whether we should change this?

**Comment by MarcosMenegazzo** [comment]
Another example:
```ruby
Time.use_zone("Brasilia") do
  p "1970-01-01T21:00:00Z".in_time_zone
  p Time.zone.at("1970-01-01T21:00:00Z".in_time_zone.seconds_since_midnight)
end
=> Thu, 01 Jan 1970 18:00:00 BRT -03:00
=> Thu, 01 Jan 1970 15:00:00 BRT -03:00
```

**Comment by matthewd** [comment]
> ```
Time.zone.at("1970-01-01T21:00:00Z".in_time_zone.seconds_since_midnight)
```

That really doesn't make any sense, unless you ignore everything @pixeltrix has said.

`Time.zone.at(N)` means "the time, in this zone, at N seconds past the epoch... which *is not midnight*.

You don't want `at`, you want something like:

```ruby
"1970-01-01T00:00:00".in_time_zone + "1970-01-01T21:00:00Z".in_time_zone.seconds_since_midnight
=> Thu, 01 Jan 1970 18:00:00 BRT -03:00
```

To confirm there's no problem in `seconds_since_midnight`:

```ruby
"1970-01-01T21:00:00Z".in_time_zone
=> Thu, 01 Jan 1970 18:00:00 BRT -03:00
"1970-01-01T21:00:00Z".in_time_zone.seconds_since_midnight
=> 64800.0
```

... and `64800 / 3600 == 18`. `18:00:00` is definitely 18 hours since midnight.

---

The other possible interpretation of what you're saying, is that you *do* want `at`, but you don't want `seconds_since_midnight` -- are you actually looking for "seconds since the epoch"? That's called `to_i`.

```ruby
"1970-01-01T21:00:00Z".in_time_zone.to_i
=> 75600
Time.zone.at("1970-01-01T21:00:00Z".in_time_zone.to_i)
=> Thu, 01 Jan 1970 18:00:00 BRT -03:00
```

**Comment by MarcosMenegazzo** [comment]
Thanks @matthewd, @pixeltrix and @rafaelfranca. You are right. `to_i` is the way, and maybe, Time.zone.at  should work in the app timezone.
