### ISSUE TITLE
ActiveRecord::save should not succeed if the record has been deleted out from under us

### ISSUE THREAD

**Issue by baumanj** [rails/rails#21801]
Here's the heart of the issue:
```ruby
    post = Post.create!(foo: 1)
    Post.destroy(post.id)
    post.foo += 1
    post.save   # surprisingly returns true
    post.reload # raises ActiveRecord::RecordNotFound, confirming it's not actually there
```
Executable test case: https://gist.github.com/baumanj/1b42394dedbb3f2c3f56

**Comment by baumanj** [comment]
I'm guessing the fix would be in activerecord/lib/active_record/persistence.rb:

```ruby
def create_or_update(*args)
raise ReadOnlyRecord, "#{self.class} is marked as readonly" if readonly?
      result = new_record? ? _create_record : _update_record(*args)
      result != false
end
```

Perhaps just changing those last two lines to:
```ruby
      expect_nonzero_result = changed?
      result = new_record? ? _create_record : _update_record(*args)
      expect_nonzero_result ? result.nonzero? : result != false
```

**Comment by pixeltrix** [comment]
@baumanj the problem is that the number of records updated returned by the query being zero doesn't necessarily mean the record has been deleted - the record could've already been updated in another browser window.

If you want to make sure that a record isn't deleted from underneath you then you need to use pessimistic locking: http://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html

**Comment by baumanj** [comment]
Thanks very much for the prompt response. This makes total sense, but I just didn't find this feature when I went looking. Perhaps a reference from the Active Record Persistence documentation would be helpful.
