### ISSUE TITLE
Rake db:test:prepare modifies rails environment 

### ISSUE THREAD

**Issue by bolshakov** [rails/rails#21880]
Run `rake db:test:prepare db:seed` -- it populates test db with seed data instead of develppment

**Comment by senny** [comment]
Probably due to https://github.com/rails/rails/blob/master/railties/lib/rails/test_unit/railtie.rb#L1-L3

Since Rails maintains the test database on it's own `rake db:test:prepare` is only necessary in rare cases. For example when you rollback a migration, change it and re-apply that migration.

I wonder, in what scenario did you want to run `db:test:prepare` combined with a non test task?

**Comment by bolshakov** [comment]
After pulling latest versions of the rails app I want to prepare test database and dev environment, So it is convenient to do this at once. 

My current workaround is to swam prepare and seed: `rake db:seed db:test:prepare`

**Comment by senny** [comment]
@bolshakov there should be no need to do `db:test:prepare` in that case. If the database exists you can run your tests right away. The test setup will prepare the database accordingly.

**Comment by bolshakov** [comment]
Oh, I have not heard about `db:setup`. It do exactly what I need.

**Comment by senny** [comment]
I'm leaning towards closing this as `wontfix`. The `db:test:prepare` is fading away and should only be used in rare scenarios to sync the test database. See this snippet in the [testing guide](http://edgeguides.rubyonrails.org/testing.html)

![screen shot 2015-10-13 at 09 36 57](https://cloud.githubusercontent.com/assets/5402/10448592/1e03fbc4-718e-11e5-9711-6f35c5c82cf6.png)

While I agree that modifying the env is not good the task is really no longer meant to be used in setup procedures.

/cc @rafaelfranca

**Comment by rafaelfranca** [comment]
Yeah, agree.
