### ISSUE TITLE
where_sql generation broken after c99bea1df

### ISSUE THREAD

**Issue by etehtsea** [rails/rails#21958]
```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.4'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:things) do |t|
    t.boolean :hidden
  end
end

class Thing < ActiveRecord::Base
  scope :hidden, -> { where(hidden: true) }
end


class ReproTest < Minitest::Test
  def test_generates_correct_where_sql
    sql = Thing.hidden.arel.where_sql
    puts sql
    assert sql == "WHERE \"things\".\"hidden\" = 't'"
  end
end

# 4.2.2: WHERE "things"."hidden" = 't'
# 4.2.3: WHERE "things"."hidden" = ?
# 4.2.4: WHERE "things"."hidden" = ?
```

**Comment by sgrif** [comment]
`where_sql` is not part of the public API.

**Comment by milushov** [comment]
![image](https://cloud.githubusercontent.com/assets/424326/10493195/81dc199e-72b8-11e5-928c-9853ee285026.png)

**Comment by seanlinsley** [comment]
Is there a new way to get a SQL string with the bind value embedded? It would be extremely valuable for ActiveAdmin. https://github.com/activeadmin/activeadmin/issues/4132

**Comment by seanlinsley** [comment]
Given the responses so far, I expect the answer is no.

I'm instead trying to build a custom visitor, but am having trouble.

Using [this](https://stackoverflow.com/questions/46193046/rails-activerecord-where-to-sql#comment79534750_46231931) as a base (thanks @tcopeland):

```ruby
module Arel
  module Visitors
    class MyWhereSsqlWithoutSql < Arel::Visitors::ToSql
      def initialize(inner_visitor, *args, &block)
        @inner_visitor = inner_visitor
        super(*args, &block)
      end

      private

      def visit_Arel_Nodes_SelectCore o, collector
        collector << ""
        wheres = o.wheres.map do |where|
          Nodes::SqlLiteral.new(@inner_visitor.accept(where, collector.class.new).value)
        end
        inject_join wheres, collector, ' AND '
      end
    end
  end
end

module Arel
  class SelectManager < Arel::TreeManager
    def where_sql_without_where(engine=Table.engine)
      return if @ctx.wheres.empty?
      viz = Visitors::MyWhereSsqlWithoutSql.new(engine.connection.visitor, engine.connection)
      Nodes::SqlLiteral.new viz.accept(@ctx, Collectors::SQLString.new).value
    end
  end
end
```

And given Rails' `to_sql` implementation:
```ruby
def to_sql
  @to_sql ||= begin
                relation   = self
                connection = klass.connection
                visitor    = connection.visitor

                if eager_loading?
                  find_with_associations { |rel| relation = rel }
                end

                binds = relation.bound_attributes
                binds = connection.prepare_binds_for_database(binds)
                binds.map! { |value| connection.quote(value) }
                collect = visitor.accept(relation.arel.ast, Arel::Collectors::Bind.new)
                collect.substitute_binds(binds).join
              end
end
```

I'm trying to do this:
```ruby
relation = User.enabled
connection = User.connection
visitor = connection.visitor

visitor = Arel::Visitors::MyWhereSsqlWithoutSql.new(visitor, connection)

binds = relation.bound_attributes
binds = connection.prepare_binds_for_database(binds)
binds.map! { |value| connection.quote(value) }
collect = visitor.accept(relation.arel.ast, Arel::Collectors::Bind.new)
collect.substitute_binds(binds).join
```

But this is an array while `Nodes::SqlLiteral.new` expects a string:
```ruby
>> @inner_visitor.accept(where, collector.class.new).value
=> ["\"users\".\"status\"", " = ", #<Arel::Nodes::BindParam:0x00007fbcfd09a0f8>]
```

Could someone help me figure this out?

**Comment by milushov** [comment]
omg ActiveAdmin still alive

**Comment by seanlinsley** [comment]
software never really dies once enough projects come to rely on it 😄

**Comment by rafaelfranca** [comment]
@seanlinsley try: `Model.connection.unprepared_statement { Thing.hidden.to_sql }`

**Comment by seanlinsley** [comment]
That definitely works to get the entire query:
```ruby
User.connection.unprepared_statement{ User.enabled.to_sql }
 => "SELECT \"users\".* FROM \"users\" WHERE \"users\".\"status\" = 'enabled'"
```

But I'm wanting to compose a query from multiple scopes in order to limit the number of queries that ActiveAdmin needs to do (that all are operating on the same data).

Given this code:
```ruby
class User < ApplicationRecord
  scope :enabled, ->{ where status: 'enabled' }
  scope :disabled, ->{ where status: 'disabled' }
end

ActiveAdmin.register User do
  scope :all, default: true
  scope :enabled
  scope :disabled
end
```

I want to be able to generate this database query:
```sql
select
  count(*) as all,
  count(*) filter (where status = 'enabled') as enabled,
  count(*) filter (where status = 'disabled') as disabled
from users;
```

My options are to:
- get `where_sql` working
- do regex string substitution on the result from `unprepared_statement` 🙈
- require ActiveAdmin users to duplicate the scope as SQL, like this:
  ```ruby
  ActiveAdmin.register User do
    scope :all, default: true
    scope :enabled, sql: "status = 'enabled'"
    scope :disabled, sql: "status = 'disabled'"
  end
  ```

**Comment by sgrif** [comment]
Caveat: Everything in this comment is not public API. I do not want to hear about it if this stops working. That said I don't expect this to break any time soon....

As you may be aware, the way that we deal with bind parameters changed significantly in 5.2. Bind params are stored on the AST itself, rather than kept separately as they were in previous versions (which was brittle and bug-prone). A lot of the motivation for that was to make AST manipulation like this much easier. You can very easily access the Arel AST for the where clause in 5.2 by doing `relation.where_clause.ast`. This should give you everything you need to construct the query you want, without needing to embed the where clause. For earlier versions, I'd just do multiple queries, and encourage people to upgrade to 5.2
