### ISSUE TITLE
Occasional Deadlock in ConnectionPool::connected? on Rails startup

### ISSUE THREAD

**Issue by Taytay** [rails/rails#22031]
We are using ActiveRecord `4.2.4`, and sometimes we are seeing a Rails server that won't be able to handle requests. All of its requests time out (we use the timeout gem to ensure none of our requests go for more than 25s). The call stack that we see for every failed request is this one:

```
vendor/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:185:in `lock'
vendor/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:185:in `mon_enter'
vendor/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:209:in `mon_synchronize'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:299:in `connected?'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:580:in `connected?'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:118:in `connected?'
vendor/bundle/ruby/2.2.0/gems/rollbar-2.1.2/lib/rollbar/middleware/rails/rollbar.rb:63:in `person_data_proc'
vendor/bundle/ruby/2.2.0/gems/rollbar-2.1.2/lib/rollbar/middleware/rails/rollbar.rb:44:in `fetch_scope'
vendor/bundle/ruby/2.2.0/gems/rollbar-2.1.2/lib/rollbar/middleware/rails/rollbar.rb:20:in `call'
vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
vendor/bundle/ruby/2.2.0/gems/rollbar-2.1.2/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.1.300/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
```

So something in the ConnectionPool appears to be holding on to the lock, and not letting it go. I am not able to do a thread dump, so I don't know what else is holding on to the lock, but I am pretty sure that it's never been able to grab even a single connection (although other machines connecting to this Postgres server are connecting, so the issue is isolated to individual machines). I'm not familiar enough with ConnectionPool to know what other method might hang while holding on to the lock. Has anyone else ever seen this before?

**Comment by agis-** [comment]
I don't know if this is the actual issue but `Timeout` (stdlib) is infamous for playing bad with threads.

See:

* http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/
* http://blog.headius.com/2008/02/rubys-threadraise-threadkill-timeoutrb.html
* http://stackoverflow.com/questions/25803089/is-ruby-2-1-2-timeout-still-not-thread-safe

**Comment by Taytay** [comment]
I was afraid you'd say that @agis. I've had my eye on killing Timeout for a while. I don't know if it's the culprit here or not, but at the very least you've given me more ammo to kill that thing and be done with it. :/

**Comment by vrinek** [comment]
@Taytay we've been experiencing similar issues (Rails deployment to Heroku with Puma). Have you had any luck fixing it?
Also, we're experiencing the "sometimes" effect, it seems random. Have you found a reliable way to reproduce this issue?

**Comment by maclover7** [comment]
Can you reproduce on master?

**Comment by simonmorley** [comment]
We're also experiencing this. Since 4.1 though, appeared around December last year. Been debugging since.

Initially I thought it was Puma, opened a ticket their side - all connections sitting in the CLOSE_WAIT state. 

Installing the rack timeout gem sorted that in a miserable way - the issue appeared to come from the connection pool. I was able to extract all requests that caused the issue onto a separate set of servers with haproxy.

We run two master databases (not master master - we have two separate dbs). **The problem ONLY appears on the servers connecting to the second database server.**

I don't think it's chance that this server has little traffic. If we load the servers, we don't see the issue. If we let them go idle for a few minutes / hours, we get the timeouts.

I've tried using GDB to debug the stuck process but failed miserably due to an issue with docker, lack of time and basic knowledge.

Throughout the debugging process, I've been through everything from adjusting the pool size, db timeouts, reaping frequency, system limits on Rails servers and MySQL, replaced the database, swapped from MySQL to Maria, tested non-docker images, removed any internal load balancers between Rails and the DBs and refactored the application. I've tried running the queries with find_by_sql or wrapping in with_connection block. There are zero errors db side and only a few connections open. Nothing has fixed.

We don't use Timeout and I'm down to a limit set of gems now after a massive clear out. We do use sidekiq although it doesn't run jobs on these servers.

I can reproduce by backing off all traffic and then calling and end point which eventually connects to the db. As soon as send traffic we see timeouts - this actually blocks the whole app and we have to restart.

We use Ruby 2.2.2,  Rails 4.2.5.1, Puma 2.16.0

**Comment by simonmorley** [comment]
@Taytay Any chance you can share your Gemfile and versions. We've been systematically going through and removing each one to eliminate any external issues.

Our application is quite large and we're making slow progress tracking this down.

I just noticed the title of the post - we actually have during runtime, not just on startup.

**Comment by bryandavisweb** [comment]
@simonmorley did y'all ever get this issue sorted out? we're experiencing something similar.

**Comment by simonmorley** [comment]
@bryandavisweb Nope. We broke the application into two parts to isolate. Both still suffer. Although it's much much better. It still happens a few times per day but they recover. 

The only thing the two apps have in common, aside from Ruby, is the db. I'm 99% certain there's something up with the second connection. 

I'm about to remove the reconnect option as apparently that interferes with innodb (I think that's the right way round). I'll let you know...

**Comment by bryandavisweb** [comment]
@simonmorley we also connect to two different databases in this app and run rack timeout. i wonder if that's related? could it have something to do with the rollbar gem or are we purely in activerecord territoy at this point?

**Comment by simonmorley** [comment]
We have rack timeout but no rollbar anymore. We have the same issue with rollbar and airbrake. 

If we load the connection up all is much better. It's like the connections go to sleep and never wake up.

**Comment by nullaus** [comment]
+1, also have this issue happening
