### ISSUE TITLE
ActiveRecord::QueryMethods unscope for nested attributes

### ISSUE THREAD

**Issue by sintro** [rails/rails#22100]
Hello! I faced the problem with applying ActiveRecord::QueryMethods unscope method for nested attributes, when I need to remove where: for included associated model's attribute. Here it example:

```
@approved = User.orders.references(:users_orders).where(users_orders: {approved: true})
@blocked = @approved.unscope(where: {users_orders: :approved}).where(users_orders: {approved: false})
```

In this case the unscope method is helpless (as I can judge from results and source code).
Of course, in this case I could use more effective ways to perform such queries, but in my real example I have really big scopes, and it would be nice if rails supports this feature.
Is there any way to fix or override unscope for handling nested attributes?

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by sintro** [comment]
Here is it, I reviewed as many cases to unscope :approved key, as possible
https://github.com/sintro/rails_unscope_test/blob/master/unscope_test.rb

**Comment by maclover7** [comment]
Reproduction script still failing on master.

**Comment by sintro** [comment]
What is failing exactly? I have no errors in script, just 3 assertion fails and 2 successes

**Comment by maclover7** [comment]
Just saying that the issue(s) still exists.

**Comment by jokklan** [comment]
You can use `unscope` with the attribute name alone like `unscope(where: :approved)` which should work, however the attribute name is stored as a symbol for nested where clauses instead of a string, which breaks the functionality because Rails expects a string: https://github.com/rails/rails/blob/v4.2.6/activerecord/lib/active_record/relation/query_methods.rb#L908-L914

However I can't figure out exactly where Rails decide to set the attribute name as a symbol instead of a string.

**Comment by swistaczek** [comment]
Hey, issue is still not closed. Problem is still valid for rails 5.2.

**Comment by abhaynikam** [comment]
@sintro @maclover7 : After debugging the issue for unscoping the nested attributes, found that unscoping the nested where clause is not working because column names are not converted properly to array in this case. 

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L390

In the example given in the reproduction script:
```
@event.reload.awards.unscope(where: {nominations: :approved})
```

target_values, in this case, would be `{nominations: :approved}` which is converted to `[[:nominations, :approved]]` and then mapped to `["[:nominations, :approved]"]` due to which the unscope was not working. 

I have tried to fix the issue. Will raise PR shortly for it.

**Comment by ngouy** [comment]
any update on this? Issue is still ongoing in last rails version (6.0.3.4)
