### ISSUE TITLE
Dependent destroy uses default scope, should be able to specify a scope or unscoped

### ISSUE THREAD

**Issue by airimie** [rails/rails#22201]
Having two models:

User: default_scope { where(archived: false) }
Account: has_many :users, :dependent => :destroy

When account.destroy is called, only users within the default scope are destroyed (in this case only users that are not archived), the other users not in the scope are not destroyed.

The options here should be: be able to specify an 'unscoped' on destroy, or being able to specify the scope for destroy.

**Comment by sgrif** [comment]
We do not accept feature requests on the issues tracker, which is reserved only for bugs. You can submit feature requests on the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core), although I don't think this is a use case we'd accept.

**Comment by khiav223577** [comment]
Is there any solution for this case now?

**Comment by bonafernando** [comment]
@khiav223577 , I'm also looking for the answer for that.

**Comment by timolehto** [comment]
Since it seems like ppl are looking for a solution to this still and ending up here every now and then let me elaborate how to handle these cases since there's no support for specifying the scope for the destroy option. Or is there 🤔 😁? What if we defined an additional duplicated relation we don't otherwise intend to use, but for which we unscope the query so that we can define dependent option for them all. That would be something like this:

```
class Contents
  belongs_to :container
  default_scope -> { where soft_deleted_at: nil }
end

class Container
  has_many :contents
  has_many :___contents_including_soft_deleted, -> { unscope(where: :soft_deleted_at) },
                    class_name: 'Contents', inverse_of: :container, dependent: :destroy
end
```
