### ISSUE TITLE
Rails 5: `rake test` with failing tests returns exit code zero

### ISSUE THREAD

**Issue by jgrau** [rails/rails#22232]
Steps to reproduce:

```
# Generate a new rails 5 application.
git clone git@github.com:rails/rails rails
rails/railties/exe/rails new test-rails --edge
cd test-rails

# Create a failing test
bin/rails g controller test
vim test/controllers/test_controller_test.rb
# Uncomment code. Change to assert false. Save

# Run tests
bundle exec rake test

# Check exit code
echo $?
```

I would expect to see a failing test and an exit code that is non-zero. Instead, I see an exit code of zero.

**Comment by gaurish** [comment]
Rails 5 onwards, `rake` should not be used. everything is run via `rails` command. Please see https://github.com/rails/rails/issues/18878

**Comment by jgrau** [comment]
That solves it. And I realise that using `rails` instead of `rake` is the new preferred way, however, I feel that running `rake` should either return the correct error code or exit with a message notifying of the change in behaviour.

**Comment by arekf** [comment]
Looks like `test` command invoked via `rails` is exiting using Minitest return code:
```ruby
# railties/lib/rails/commands/test.rb:9
exit Minitest.run(ARGV)
```

when "regular" `rake` test tasks doesn't use exit:
```ruby
# railties/lib/rails/test_unit/testing.rake:10
Minitest.rake_run(["test"])
```
so the exit code isn't being returned.

I can send PR if you think this is correct solution to fix the issue.

**Comment by arekf** [comment]
I've sent the PR ;)
https://github.com/rails/rails/pull/22248

**Comment by jgrau** [comment]
Thanks @arekf ! 

I could be worried that other differences in behaviour could occur down the line. I wonder if it's better that `rake test` just exists with a message saying something like 

> From rails v. 5 `rake test` is no longer supported. Use `rails test` instead

But to be honest I don't know what the best solution is. :)

**Comment by kaspth** [comment]
@jgrau the plan is to deprecate the `rake` setup and funnel everything through `rails`, but that's later :)

**Comment by jgrau** [comment]
:ok_hand:

**Comment by jrochkind** [comment]
Huh, I'm finding it super confusing what the difference between `rake test` and `rails test` is. 

I actually have tests that are passing with `rake test` and failing with `rails test`, due to different setup apparently?

CI all often defaults to `rake test` or even just `rake` (default task), so I thought all my tests were passing in a migration of a project to rails5... but one is still failing with `rails test`, huh?

Very confused what's going on. What does `rails test` do that's different than `rake test`?

I got the idea from what I had read on rails 5 `rails $raketask` was just a cover for `rake`, but apparently it's actually using a different code path?  That's a definite gotcha for people accidentally using `rake test`, including CI scripts or other automation scripts. 

Has this been documented or explained anywhere, what's going on here, what the diff between `rails test` and `rake test` is now?  Explanation would be appreciated.
