### ISSUE TITLE
JS runtime not in Gemfile -> why ?

### ISSUE THREAD

**Issue by waghanza** [rails/rails#22339]
Hi folks,

I regularly upgrade our gitlab version, and I have always when getting the last `Gemfile`
~~~
Could not find a JavaScript runtime
~~~

I have to add `therubyracer` or else in the `Gemfile` manually.

Is there any reason whe a `javascript runtime` is not in the `Gemfile` ?

Regards,

**Comment by luke-gru** [comment]
The reason it's not there is because the JavaScript runtime is auto-detected using the `execjs` gem. If you have `nodejs` or `rhino` installed, it would be redundant to also have `therubyracer` installed.
See [exejs](https://github.com/sstephenson/execjs) for more details.

**Comment by sevenseacat** [comment]
A lot of us don't like using `therubyracer` as a runtime, and on some systems (Windows IIRC) it can't even be installed!

**Comment by luke-gru** [comment]
It doesn't make sense to need a JS runtime in your non Dev environment if you're precompiling all your assets,  though. Unless you're doing something nuts that involves evaling some JS in your app. I'm not sure if that's been fixed in recent rails versions  or not.  Does anyone know?

**Comment by rafaelfranca** [comment]
If you are getting that exception it is because some code is loading execjs. It doesn't matter the environment, it the code is loading it, it will require a runtime.

The runtime is not in the Gemfile because you need to be able to choice the runtime. For those that don't like `therubyracer` there are a lot available runtimes https://github.com/rails/execjs#execjs.
