### ISSUE TITLE
ConfirmationValidator doesn't fail if confirmation is absent

### ISSUE THREAD

**Issue by Lacrymology** [rails/rails#22344]
from https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/confirmation.rb#L10

```ruby
      def validate_each(record, attribute, value)
        if (confirmed = record.send("#{attribute}_confirmation"))
          unless confirmation_value_equal?(record, attribute, value, confirmed)
```

here, if `value` is truthy but `record.<attribute>_confirmation` is falsey (i.e. absent from the params), this validation doesn't fail.

I guess this is good enough for html sites where the main interaction is done through web forms, but for a REST API this is buggy if the client sends e.g. a `password` but not a `password_confirmation` parameter.

I was about to send a patch, but I realized that the code seems quite deliberate, so I'm filing a bug instead. If this is the intended behavior, what's the right way to validate this?

currently I've added

```ruby
  validates_presence_of :password_confirmation, if: :password?
```

**Comment by sgrif** [comment]
[sarcasm]
Luckily, the commit which originally introduced this code was very specific in the reasoning behind what the code is doing, and why it's doing it that way. As we can see from https://github.com/rails/rails/commit/9ddc6143e06cdb3c86d0c954a4fed523e171886c, we do not validate if it's nil because "reasons". Helpful.
[/sarcasm]

If I had to guess, the thought process was that if the field isn't present, the validation would always fail, and you might not want a confirmation all of the time? I'm honestly not sure. It seems dumb. I wish we could change it. The cost to our users for migration would be too high to justify, IMO. You can work around this by adding a presence validation as well.
