### ISSUE TITLE
Rails doesn't force duplication in collection_singular_ids=  method

### ISSUE THREAD

**Issue by asiniy** [rails/rails#22432]
Let's consider my models:

``` ruby
class Dealer < AR::Base
  has_many :dealer_locations
  has_many :locations, through: :dealer_locations
end

class DealerLocation < AR::Base
  belongs_to :dealer
  belongs_to :location
end

class Location < AR::Base
  has_many :dealer_locations
  has_many :dealers, through: :dealer_locations
end
```

Now I'm starting to assign ids:

``` ruby
d = Dealer.new
d.location_ids = [1, 1]
d.locations # => [
# <Location id=1 ...>,
# <Location id=1 ...>,
#]
```

Was ist das? Bug or feature? Why rails doesn't force duplication on low level?

**Comment by Shwetakale** [comment]
@asiniy I think this is feature.

 Let's assume there is ```product_name``` in ```DealerLocation``` model.
One dealer can deliver multiple products on same location. In this case same location will be associated with that particular dealer. 

And I tried code snippet you provided in this case 2 different objects of ```DealerLocation``` are created.

     d.dealer_locations
     #<ActiveRecord::Associations::CollectionProxy [#<DealerLocation id: 4, dealer_id: 1, location_id: 1, created_at: "2015-11-28 11:21:54", updated_at: "2015-11-28 11:21:54">, #<DealerLocation id: 5, dealer_id: 1, location_id: 1, created_at: "2015-11-28 11:21:54", updated_at: "2015-11-28 11:21:54">]> 


According to me this is expected behavior.
