### ISSUE TITLE
Relation#destroy_all should perform its work in batches

### ISSUE THREAD

**Issue by dhh** [rails/rails#22510]
Since destroy_all actually loads the entire relation and then iteratively destroys the records one by one, you can blow your memory gasket very easily. So let's do the right thing by default and do this work in batches of 100 by default and allow you to specify the batch size like so: #destroy_all(batch_size: 100).

**Comment by shakycode** [comment]
I like this.  Makes a lot of sense.

**Comment by dhh** [comment]
Summary of concerns:

* #destroy_all currently promises the destroyed values are returned. This naturally doesn't work with a batch approach, so we need a feature toggle like `config.active_record.destroy_all_in_batches` to switch between the old and new way. We will set this to `true` in an initializer for new apps. Old apps will get a warning.
* Need to see how this interacts with a relation that already has #limit applied to it. It should probably just not try to further limit things.

**Comment by egilburg** [comment]
`each` does not work in batches, one has to write `find_in_batches` (or I think newer api is `in_batches.each`). Perhaps support `in_batches.destroy_all` instead?

**Comment by bogdan** [comment]
I think this feature is not sufficient to cover all problems with destroy a large set of records.
As I remember currently we can do the following:

``` ruby
records.in_batches.destroy_all
```

And this patch doesn't make it a lot easier.

Especially if we consider associations and cascade deletes.

``` ruby
Merchant.has_many :campaigns, dependent: :destroy
# Suppose Member is a lighter object and Offer is heavy object
Campaign.has_many :offers, dependent: :destroy
Campaign.has_many :members, dependent: :delete
```

* dependent records need to also be deleted in batches
* those batches size should be configurable
* delete strategy should also work in batches because large deletion (more than 100k records) locks table for writing for a long time on MySQL - as I remember PG does it as well but I am not 100% sure


### The ideal solution

would be embed batches into relation by itself, so that any potential operation on relation would use specified batch size:

``` ruby
relation.in_batches.delete_all
relation.in_batches.destroy_all
relation.in_batches.map(&:hello)
relation.in_batches.join(",")
# etc
```

All of the methods above should not use
In this way we can embed batches into relation like a chained scope:

```
User.in_batches.where("logged_in_at < ?", 1.year.ago).destroy_all

Campaign.has_many :members, -> { in_batches(size: 5000)}, dependent: :delete
Campaign.has_many :offers, -> { in_batches(size: 500)}, dependent: :destroy
```

It makes all the AR infrastructure available for batches not just individual features.

**Comment by dhh** [comment]
@bogdan I think that's a pretty fair analysis. I hadn't considered the cascading aspect. But I think we're still taking a step forward and making more calls to destroy_all safer for more people more of the time. I don't think we necessarily need a solution that covers all cases to have something worth merging. I am interested in seeing additional work happen on the more comprehensive solution, though, so if you're interested in that, please do pursue!

**Comment by bogdan** [comment]
@dhh what is your overall opinion on embedding batches to relations object and make it a chainable scope?

This feature requires a lot of changes in Relation and a lot of general refactoring and I want to consider implementation only after core team will agree that it is valuable.

**Comment by matthewd** [comment]
@bogdan I'm worried that batching really relates to the operation, rather than the collection itself... seems like it could create another layer of Very Different Behaviour from relations in many different places, like `group_by` does.

**Comment by bogdan** [comment]
@matthewd 

When you say "Very Different Behaviour" what use case do you mean? Explain when calling a method on Relation and Relation with batches will produce different results. Different number of queries to DB is not a part of behaviour but part of implementation so it is not a significant difference.

We should be judging classes not by their implementation but by their API.
And here is how it looks for me from that aspect:

I want all the operations available on Relation to be available on Relation with batches. LSP and other theory tell me that in this case either RelationWithBatches and Relation should have the same base class (even if Relation itself will be this class) or they should be the same class.

**Comment by bogdan** [comment]
@matthewd these are not examples of actual use cases. 

`to_sql` should probably work the same on both and therefore usage as subquery should be identical.

Explicit limit, offset as well as order is simply incompatible with batches so I think it should just raise an exception when you try to combine them in one relation. Currently they are just ignored and we can leave this behaviors as is.

I don't see any problems with `eager_loads` `group_by` `distinct` `order`. These operation are applied before `limit`. Can you show the actual use case? Like

``` ruby
relation.in_batches.order(id: :desc).map(&:id) != relation.order(id: :desc).map(&:id) # => false
```

**Comment by matthewd** [comment]
@bogdan while I think "just raise an error" becomes more problematic when the relation could've been "infected" with batching by any previous caller, that is indeed a possible choice.

I can't give you an example of something specific that won't work due to batching, because we don't have an implementation, and it's all just a matter of programming. I think those will be very difficult to make work correctly (to the point that they may end up with differing behaviour because it gets Too Hard); if you disagree, I'll look forward to being proved wrong.

**Comment by bogdan** [comment]
@matthewd I agree that it will be very hard. As I said initially: this is really hard to do and I want to consider it only if core team will approve. Having an implementation is very expensive here. If we can figure at least something beforehand that would be very cool. But let's at least discuss the concept.

**Comment by mbhnyc** [comment]
This is still an active concern — what's the best practice here until we move forward on a real solution?

**Comment by dhh** [comment]
Just do it by hand. We already have a way of destroying in bulk. This would
just make it the default behavior.

**Comment by SurajSJagtap** [comment]
`public`

**Comment by thisismydesign** [comment]
As far as best practices go I think `destroy_all` can easily be substituted with "manual" batching since it's explicit to begin with.
I'm more concerned with `dependent` associations which are not. To handle those I created the gem [`batch_dependent_associations`](https://github.com/thisismydesign/batch_dependent_associations) which takes care of batching `dependent` associations automatically. It's fairly straightforward with no additional dependencies. Feedback is appreciated.

**Comment by stanhu** [comment]
@thisismydesign Thanks for the gem! I like what you've done there. Are there any concerns discuss here that this gem doesn't handle? (e.g. second item in https://github.com/rails/rails/issues/22510#issuecomment-162319226).

**Comment by thisismydesign** [comment]
@stanhu I'm not sure about that specific point but it should be easy to try it. What I can tell you is that it uses [`find_each`](https://github.com/thisismydesign/batch_dependent_associations/blob/1c3daf491cec059230fffa217d0e256436998230/lib/batch_dependent_associations.rb#L25-L26) in the background so I expect there to be no concerns from Rails' perspective.

**Comment by robertomiranda** [comment]
I've opened a PR addressing this issue https://github.com/rails/rails/pull/40445
