### ISSUE TITLE
Testing ActionController::Live with recent master raises exception

### ISSUE THREAD

**Issue by kalabiyau** [rails/rails#22524]
Followed by guide on `bf9facb` rails ref.

```ruby
class FlowsController < ActionController::Base
  include ActionController::Live

  def show
    response.headers['Content-Type'] = 'text/event-stream'
    sse = SSE.new(response.stream)
    sse.write("{\"name\":\"John\"}")
    sse.write({ name: "Ryan" })
  ensure
    response.stream.close
 end

end
```

raises `undefined method 'request' for #<ActionDispatch::Request:0x00000003ad1148>`

That leads to https://github.com/rails/rails/commit/42eb37ab514060c4217ad2dd845d3bf05007db0f#diff-5055d9f16b442adb1d2f0f65903a196bR39 and where response is assumed request arrives.

@eileencodes maybe you have good idea what is going on there.

From my little investigation `ActionDispatch::Routing::RouteSet` is already makes response and then in `ActionController::Live` we once again going to `.make_response!` via set_response! 

what is really a big surprise that tests are not catching that regression. 

@eileencodes please let me know if you need any time of help

**Comment by eileencodes** [comment]
Thanks for the report @kalabiyau I'll take a look at this.

**Comment by kalabiyau** [comment]
@eileencodes also - small question

`set_response!` in `ActionController::Live` is overwrites one from `ActionController::Metal` is that correct and why it is needed? 

For myself I monkey-patched Live by removing set_response! and all green and smooth

**Comment by eileencodes** [comment]
I don't remember off the top of my head. But the goal is to get rid of Response::Live and use Response for everything.

**Comment by eileencodes** [comment]
This is so that we can move the controller test code to be integration test code and get rid of controller test code. It's a yak shave for sure :grin: and there are a lot of moving parts that need to be changed.

**Comment by kalabiyau** [comment]
@eileencodes I see, thanks a lot for the explanation! Let me know if anything.

**Comment by nateberkopec** [comment]
Do we need to add a test here?

**Comment by eileencodes** [comment]
Actually yea, if someone could write a test quick using this guide https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb that'd be great, if not I'll try to get to this tonight or tomorrow.

Can you also post your stack trace @kalabiyau?

**Comment by eileencodes** [comment]
Nevermind, this was reproducible with the main script and just adding an include. 

```ruby
class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index'
  end 
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  include ActionController::Live

  def index
    render plain: 'Home'
  end 
end

require 'minitest/autorun'
require 'rack/test'

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get '/' 
    assert last_response.ok?
  end 

  private
    def app 
      Rails.application
    end 
end
```

**Comment by eileencodes** [comment]
Ok so I took a look at this and I'm not really sure how to fix it yet but here's what I found:

In the tests anything that hits `make_response!` in `Live` is coming from `set_response!`. But in the standalone test we're hitting `serve` first which goes to `make_response` and never hits `set_response`. 

The issue is that in the tests that means that a `ActionController::Live::Response` is getting passed into the `make_response!` in live, but in the standalone test we're getting `ActionDispatch::Request` which blows up because we were expecting a Response not a Request.

If I go back to before that commit, I still get an error but a different one.
`ActionController::RoutingError (undefined method 'env' for #<ActionController::Live::Response:0x007fa9e2d9f718>)` which points to this commit from @tenderlove https://github.com/rails/rails/commit/51c7ac142d31095d4c699f44cc44ddea627da1eb. Maybe you have an idea of what's going here Aaron? I'm unsure of how all this ties together.

I'm not sure why the tests aren't blowing up - except that all of them are passing a response instead of a request, but that doesn't explain why our standalone test is different.

@kalabiyau when you said you monkey-patched `set_response!` did you mean you removed `make_response!`? I can get the standalone to pass that way (but Rails test fail) and I don't think that's correct. Can you update my gist if it is doing something different than what you're working on? Thanks!

**Comment by kalabiyau** [comment]
@eileencodes here is my monkey patch 

```diff
diff --git i/actionpack/lib/action_controller/metal/live.rb w/actionpack/lib/action_controller/metal/live.rb
index 6804e57..5b4ad86 100644
--- i/actionpack/lib/action_controller/metal/live.rb
+++ w/actionpack/lib/action_controller/metal/live.rb
@@ -36,8 +36,7 @@ module ActionController
     extend ActiveSupport::Concern
 
     module ClassMethods
-      def make_response!(response)
-        request = response.request
+      def make_response!(request)
         if request.get_header("HTTP_VERSION") == "HTTP/1.0"
           super
         else
@@ -288,8 +287,5 @@ module ActionController
       response.close if response
     end
 
-    def set_response!(response)
-      @_response = self.class.make_response! response
-    end
   end
 end
```

It sits on top of what 51c7ac1 expects https://github.com/rails/rails/commit/51c7ac142d31095d4c699f44cc44ddea627da1eb#diff-4150e8175b9a99c0e92bfdcaabf8455dR274 where it should be request.

**Comment by eileencodes** [comment]
Hey @kalabiyau thanks for the monkey patch. I used that as the fix and wrote a test. I added both our names to the commit. Thanks for working with me to find the solution!
