### ISSUE TITLE
Sprockets match in routes returns missing controller key.

### ISSUE THREAD

**Issue by zjeraar** [rails/rails#22579]
On a fresh rails 4.2.5 application, this example from the documentation (http://guides.rubyonrails.org/routing.html#routing-to-rack-applications):

```match '/application.js', to: Sprockets, via: :all```

Returns:

```
bundle exec rake routes
rake aborted!

ArgumentError: Missing :controller key on routes definition, please check your routes.
config/routes.rb:3:in `block in <top (required)>'
config/routes.rb:1:in `<top (required)>'
config/environment.rb:5:in `<top (required)>'
Tasks: TOP => routes => environment
```

**Comment by trueinviso** [comment]
I'd like to start helping on the rails project so I thought I'd give this ticket a go.  The error is happening in:  `/actionpack/lib/action_dispatch/routing/mapper.rb` in the `default_controller_and_action` method.  The :to option of a route can receive a RackApp that must respond_to the call method.
  
`def default_controller_and_action
    if to.respond_to?(:call)
      { }   
    else`

This is failing because `Sprockets.respond_to?(:call)` is false, so this RackApp doesn't respond_to call like expected.  The call method in Sprockets is an instance method of Base class and Server module, it is not a class method.  `Sprockets::Base.method_defined?(:call)` returns true, however.  

I am not sure what the expected behavior is here, is it required that call be a class method on the RackApp, or is an instance method ok?  If the instance method was ok then we could just check for that.
