### ISSUE TITLE
request.format does not obey routing information in Rails 5

### ISSUE THREAD

**Issue by pwnall** [rails/rails#22747]
Executable test case: https://gist.github.com/pwnall/b06265f317b90857a274

Before Rails 5, it was possible to use "." in the last route segment, like this.

```ruby
    get '/(:course_id)' => 'test#index', constraints: { course_id: /[^\/]+/ }
```

In Rails 5.0.0 beta1 and master, having such a segment will trick the MIME format negotiation code. I think the problem is in `format_from_path_extension` here:
https://github.com/rails/rails/blob/v5.0.0.beta1/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L166

I think that the method should pull the format extension from routing output, not straight from the HTTP path.

**Comment by matthewd** [comment]
cc @jmbejar

**Comment by jmbejar** [comment]
Ideally we should pull the format extension from routing, but routing code is executed too late in some cases. For this reason I decided to implement this method as a fallback when the format parameter is pending to be parsed from the route. Assuming that format is the extension in the URL is just an heuristic (I know it's not always true), but it would help to generate a response error with the correct format for most of the cases even when route parsing is never executed because of the error.

In any case, I think I see the problem in this test case because of the use of "." in the last segment, and we should come up with a fix for that. I will take a look asap.

**Comment by jmbejar** [comment]
Thanks @pwnall for providing this test case that helped to identify and fix the problem.
