### ISSUE TITLE
Unexpected session sharing with integration tests leads to errors

### ISSUE THREAD

**Issue by jhubert** [rails/rails#22742]
We're experiencing some weird behavior in an integration test that uses open_session multiple times. I've put together a fresh sample app to and made the code as close to the [integration test examples](http://guides.rubyonrails.org/testing.html#integration-testing-examples) as possible, and I'm still seeing the issue.

```ruby
class SessionIntegrationTest < ActionDispatch::IntegrationTest
  test 'two session test' do # passes
    mel = login(:melissa)
    luis = login(:luis)

    assert_equal 'Welcome melissa!', mel.flash[:notice]
    assert_equal 'Welcome luis!', luis.flash[:notice]
  end

  test 'three session test' do # fails
    mel = login(:melissa)
    luis = login(:luis)
    frank = login(:frank)

    assert_equal 'Welcome melissa!', mel.flash[:notice]
    assert_equal 'Welcome luis!', luis.flash[:notice]  # <---- fails here with "Welcome frank!"
    assert_equal 'Welcome frank!', frank.flash[:notice]
  end

  private

  def login(name, password: 'password')
    open_session do |sess|
      sess.post sessions_url, username: name, password: password
      assert_equal '/sessions', sess.path
    end
  end
end
```

It seems as though the 2nd session is shared with the 3rd session. Any idea what could be causing this? I've tried digging into the source code for the integration tests but I'm not finding the logic that easy to follow.

cc @dvallance

**Comment by jhubert** [comment]
The sample app is here: https://github.com/jhubert/SessionTest

**Comment by tawan** [comment]
Hi,

I attached a PR to master which resolves the issue. The issue is actually present since 15c31c7639b so maybe it would make sense to backport the fix to previous versions. Pls, let me know if I can be of any help.

@jhubert For now, you can circumvent this behaviour by avoiding to invoke `#session_url` on the current instance.Like this:
```Ruby
open_session do |sess|
  #sess.post sessions_url, username: name, password: password
  sess.post sess.sessions_url, username: name, password: password
  assert_equal '/sessions', sess.path
end
```

This prevents instantiating an `@integration_session` object in the "mother" test instance from which
further sessions are copied. Hope this helps.

**Comment by jeremy** [comment]
#23093
