### ISSUE TITLE
raise_runtime_errors is not working with recent sprockets

### ISSUE THREAD

**Issue by rosenfeld** [rails/rails#22813]
From the official guides:

http://guides.rubyonrails.org/asset_pipeline.html

"3.1 Runtime Error Checking
By default the asset pipeline will check for potential errors in development mode during runtime. To disable this behavior you can set:

config.assets.raise_runtime_errors = false

When this option is true, the asset pipeline will check if all the assets loaded in your application are included in the config.assets.precompile list."

This indeed used to work with previous versions of sprockets but when I tried to upgrade it stopped working. You can easily reproduce it by running "rails new demo" using latest Rails (4.2.5). sprockets 3.5.2 is installed currently and sprockets-rails 3.0.0 will always generate an "Asset was not declared to be precompiled in production" error.

It assumes it's always an error to not add the asset to precompile but for my use case I need a way to circumvent this error. I use an approach to test my client-side code that will require only the dependencies for a given test, so that I can be sure all dependencies are fully specified for my JS modules. The testing framework will then include individual assets that shouldn't be precompiled because those individual compiled files won't be sent to production and are only using in the test and development environments.

Could you please get raise_runtime_errors back to work with recent versions of sprocket/sprocket-rails?

**Comment by rafaelfranca** [comment]
Yes, we are aware of it. It was one of the main changes in sprockets-rails 3.

> Could you please get raise_runtime_errors back to work with recent versions of sprocket/sprocket-rails?

No. That option was made optional before because we introduced in a minor version. Now that we released a major version I don't see any reason to disable that check that was made to avoid surprising errors.

> I use an approach to test my client-side code that will require only the dependencies for a given test, so that I can be sure all dependencies are fully specified for my JS modules. The testing framework will then include individual assets that shouldn't be precompiled because those individual compiled files won't be sent to production and are only using in the test and development environments.

If you are talking about teaspoon they have how to handle that without you needing to disable that check. Just to be clear I use this same approach in Shopify test suite without to having to disable this check. If you are not using teaspoon, you can also handle that without needing to disable the check. If you know the files that need to be included you can also use this information to tell the checker to not raise the error for those files.

**Comment by rosenfeld** [comment]
I'm using my own framework and runner. How can I allow it to include the debug dependencies without getting into this error?

**Comment by rafaelfranca** [comment]
I had not check that yet but you can use `precompiled_asset_checker` as I commented here https://github.com/modeset/teaspoon/issues/443#issuecomment-166371352. If that doesn't work we should make it work.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets-rails#299

**Comment by rafaelfranca** [comment]
I moved this issue to sprockets-rails so we can discuss there. If that solution don't work let work together in a solution that works but without introducing the option.
