### ISSUE TITLE
Host constraint not working until I modify routes file. Rails 4.2.2

### ISSUE THREAD

**Issue by drewhamlett** [rails/rails#22893]
I have an issue with host constraint.

I made a youtube video to possibly show the problem a little better

https://youtu.be/pA0JuqJfj9c

Basic gist is 

I start up the server.  
I go to localhost:3000 
It renders the dashboard#index route
I then go to residentsurveys.localhost 
It renders the home#index method in the resident_surveys_co module.  This is located in controllers/resident_surveys_co/home_controller.  
I then go to the route get '/r/:campaign_short_id/:customer_short_id' => 'survey_responses#new'.  It renders that route but the layout is wrong, as if it's inheriting from the wrong application_controller.

The main application layout expects data like the current location.  So it fails.

I make a modification to the routes file(delete whitespace) and then re save it.  Everything works fine after that.  This happens every time I start a rails application.

My routes file looks like this.

```rb
Rails.application.routes.draw do
  constraints host: 'residentsurveys.local' do
    scope(module: :resident_surveys_co) do
      root 'home#index', as: :resident_surveys_root # then go here second
      get '/r/:campaign_short_id/:customer_short_id' => 'survey_responses#new' # then go here third
    end
  end

 root 'dashboard#index' # in video I go here first
```

```rb
module ResidentSurveysCo
  class SurveyResponsesController < ApplicationController
  end
end
```

```rb
module ResidentSurveysCo
  class HomeController < ApplicationController
    def index
      render(layout: false)
    end
  end
end
```

```rb
module ResidentSurveysCo
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    layout 'resident_surveys_co/layouts/application'

    def not_found
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end
```

Thanks for any help

**Comment by matthewd** [comment]
http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#when-constants-aren-t-missed

**Comment by drewhamlett** [comment]
Oh wow ok thanks!  But how does that explain everything working after I change the routes file.  If it doesn't auto load the correct ApplicationController on startup then why does it do it after changing a file?

**Comment by pixeltrix** [comment]
@drewhamlett it depends on the order in which you visit the routes - if you go to a non-namespaced controller first then it defines `ApplicationController` and then when you subsequently visit a namespaced route it finds the top level `ApplicationController` because `Object` is in the ancestor chain. Rails can't prevent this from happening because Ruby will find it without called `const_missing` so the autoloading code doesn't know about it.

The reason it works when you touch the routes file is that the `ApplicationController` constant is unloaded and when you then visit a namespaced route it finds the namespaced version because the top level constant hasn't been loaded.

The fix is to add a `require_dependency` call to the top of your namespaced controllers, e.g;

``` ruby
require_dependency 'resident_surveys_co/application_controller'

module ResidentSurveysCo
  class HomeController < ApplicationController
    def index
      render(layout: false)
    end
  end
end
```

This makes sure that the namespaced version is defined. Note that you must use `require_dependency` and not `require` so that Rails will know to unload the constant when the file changes.

Unfortunately you're not the first to encounter this weird edge condition with constant loading - I remember answering questions about this topic 7 years ago on a different bug tracker :older_man:

**Comment by drewhamlett** [comment]
Thanks for your help @pixeltrix .  Great write up.  Also that's funny about answer the same question a long time ago!
