### ISSUE TITLE
Updating default settings of ApplicationController.renderer is not working

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [rails/rails#22975]
We generate an initializer `application_controller_renderer` to allow users to update the default config options for rendering templates outside of controller with following content.

``` ruby
# ApplicationController.renderer.defaults.merge!(
#   http_host: 'bigbinary.com',
#   https: true
# )
```

But the `ApplicationController.renderer.defaults` hash is frozen - https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/renderer.rb#L45. So it raises an error if we try to modify it.

**Comment by matthewd** [comment]
Hmm. It seems undesirable that you'd be changing the defaults for *all* renderers, rather than just those for controllers inherited from ApplicationController. But it's also not very useful to configure only ApplicationController's renderer, and miss those for its subclasses. :confused:

**Comment by prathamesh-sonpatki** [comment]
@matthewd I agree. I think this is just an example to show how the defaults can be customized. But it does not work because of the frozen hash. Should we use `DEFAULTS.dup` here - https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/renderer.rb#L48? to allow users updating this hash?

**Comment by tomprats** [comment]
@prathamesh-sonpatki + @matthewd: Is this something I should create a pull request for? I ran into this too and it seems a little odd that a generated file's commented code doesn't work if you try to use it

**Comment by pctj101** [comment]
1) Yes it is confusing for the generated file to offer code which prevents startup of server.  Example:
```
 ApplicationController.renderer.defaults.merge!(
   http_host: 'example.com',
   https: true
 )
```

Result on 'rails s'
```
config/initializers/application_controller_renderer.rb:3:in `merge!': can't modify frozen Hash (RuntimeError)
```

2) Furthermore, setting ApplicationController#default_url_options does not seem to work.  For example after sign in devise, I am redirected to http, even when my default protocol is https.

```
def default_url_options
  { protocol: "https" }
end
```

3) Since the new way doesn't work, and the old way seems to be ignored, perhaps it would be helpful to offer some text guidance.

I'd be happy to help, but viewing the above comments, it's not clear what direction is the best. 

If anyone needs me to write some comments, let me know.

**Comment by maclover7** [comment]
Putting this on the 5.0.0 milestone, since this initializer (and the current issue) was first added in the 5.0 betas.

**Comment by maclover7** [comment]
Opened #24661 to `dup` the `DEFAULTS` hash, and included a regression test.
