### ISSUE TITLE
No bind parameters for ranges in where clause

### ISSUE THREAD

**Issue by nathansamson** [rails/rails#23074]
For example `Model.where(numerical_value: 5..10)` still generates an entry in the prepared statements cache (tested with v4.2.5 and v5.0.0-beta1)

This is very bad because of #21992 
Similar issues where solved in https://github.com/rails/rails/commit/cbcdecd2c55fca9613722779231de2d8dd67ad02 
A similar problem was reported in #22250 and fixed as well for v5.0.0

@sgrif If you could have a stab at this, that would be very much appreciated.

**Comment by sgrif** [comment]
To summarize the problem in case anybody wants to take a stab at this before I get a chance:

- There are exactly 6 possible queries that can be generated by passing a range:
  - `foo BETWEEN 1 AND 3` for `1..3`
  - `foo >= 1 AND foo < 3` for `1...3`
  - `foo >= 1` for `1..INFINITY`
  - `foo <= 3` for `-INFINITY..3`
  - `foo < 3` for `-INFINITY...3`
  - `1 = 1` for `-INFINITY..INFINITY`
- We can use bind params for all of those cases. 6 prepared statements is fine.
- We cannot "just use bind params" because the conditionals on infinity are in Arel, which would receive a bind param in that case.
  - A possible change is to remove the `between` behavior from Arel, and move it to Active Record.
- An acceptable workaround would be to simply not prepare statements that pass a range to where.
  - A possible implementation of this would be to change our check from `In` and `SqlLiteral` to `Casted`, `Quoted` and `SqlLiteral`
