### ISSUE TITLE
undefined method `dig' for {}:ActionController::Parameters

### ISSUE THREAD

**Issue by Gedrovits** [rails/rails#23104]
Hey, currently this is not considered Hash, so .dig added in Ruby 2.3 is not usable on ActionController::Parameters

Are there plans to support new Ruby 2.3 syntax sugar and speed optimization in Rails 5?

```
params = ActionController::Parameters.new
params.dig(:something).dig(:else)
undefined method `dig' for {}:ActionController::Parameters
```

Workaround is transforming params to regular Hash, which is not looks good to me...

```
params = ActionController::Parameters.new.to_h
params.dig(:something).dig(:else)
nil
```

**Comment by maclover7** [comment]
This is correct behavior -- ActionController::Parameters is not a hash anymore. This means that isn't Ruby or Rails' fault that `dig` doesn't work -- it's just the new way that the public API is structured. See #20868 and #23084 for more details about this change in behavior.

**Comment by joshuaflanagan** [comment]
I get that this is the correct behavior - ActionController::Parameters is not a hash.

However, would you accept a PR that adds `#dig` to the ActionController::Parameters API? It is a really convenient API, and developers will get used to it as 2.3 is adopted.

I don't see how it would expose any security issues that aren't already exposed by `#[]`, since it can be just a wrapper around that existing API:

```
def dig(*keys)
  keys.reduce(self){|val, key| val && val[key]}
end
```

**Comment by sunny** [comment]
This has been added in https://github.com/rails/rails/pull/32446 🎉
