### ISSUE TITLE
Can't Pass frozen strings as arguments to Rails::Generators::Actions#gem  

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#23137]
In railties-4.2.5

I get a frozen modification error `can't modify frozen String (RuntimeError)` when I attempt to pass frozen strings to the `gem` method.

I encountered this when adding the new `frozen_string_literal` pragma to my generator. 

https://github.com/rails/rails/blob/v4.2.5/railties/lib/rails/generators/actions.rb#L17

**Comment by prathamesh-sonpatki** [comment]
@jcoyne Can you post full stacktrace? I think https://github.com/rails/rails/blob/v4.2.5/railties/lib/rails/generators/actions.rb#L23 may be the issue but can confirm after seeing stacktrace.

**Comment by bronzle** [comment]
I'm going to wager a guess the error is caused by: https://github.com/rails/rails/blob/v4.2.5/railties/lib/rails/generators/actions.rb#L26

But, with that said, I think it is unwise (and maybe should be not supported) to be passing frozen strings into rails internals, as I don't believe rails is guaranteeing to not modify arguments passed in. (The same issue would occur without the magic comment, and just passing #gem("blah".freeze))

Until rails has a ruby dependency of 3.0 (in which rails will have to follow frozen string literal rules), I keep to using the pragma for strings that stay inside your files with the comment. The comment is there to ease the transition, but it provides no interoperability between different gems (just because you are using it, doesn't mean rails is)

**Comment by jcoyne** [comment]
I'm willing to concede that this is not a bug. I just thought it might be worth raising the issue.

**Comment by matthewd** [comment]
Yeah, this is a bug.

**Comment by msxavi** [comment]
Are there, perhaps, lacking of changes to work with Ruby 2.3.0?
