### ISSUE TITLE
Rails 4.1.1: caveat, when using respond_to in pair with respond_with

### ISSUE THREAD

**Issue by d3crypt3d** [rails/rails#23160]
A nice approach - using respond_to in pair with respond_with:
```ruby
class MyProjectsController < ApplicationController
    before_action :set_project, only: [:show, :update, :destroy]
    respond_to :json

    # GET /projects
    # GET /projects.json
    def index
      respond_with Project.all 
    end

   # POST /projects
   # POST /projects.json
   def create
      project = Project.new(resource_params)

      if project.save                   
         respond_with project, location: [:api, project] 
      else
        render json: project.errors, status: :unprocessable_entity
      end
  end
 # ...
end
```
But there is a caveat, though - before responding with 406 status, It still performs some of the controller actions: creats, updates and destroys the resource. So, one having requested wrong format, still can delete/update/create the reource. 
E. g. 
```bash
curl http://foo.example.net:3000/projects -H "Content-Type: application/json" -H "Accept: application/xml" -i -X POST -d '{"data":{"type": "projects", "attributes": {"name": "foo"}}}' 
```
returns `HTTP/1.1 406 Not Acceptable`, *but* creates a resource!

**Comment by pixeltrix** [comment]
@d3crypt3d the class method `respond_to` and the instance method `respond_with` have been moved to the [responders gem] so the caveat you point out doesn't apply to supported Rails versions so any note/warning PR should be submitted to that repository. Given that, it's always been the case that mime responds aren't a security feature, e.g. the following code is still subject to the same "flaw":

``` ruby
def create
  @project = Project.create(project_params)

  respond_to do |format|
    format.json {
      if @project.persisted?
        render json: @project
      else
        render json: @project.errors
      end
    end
  end
end
```

The `Project.create` still happens because it's outside the `format.json` block.

[responders gem]: https://github.com/plataformatec/responders
