### ISSUE TITLE
Time.use_zone isn't respected if an ActiveRecord object is loaded before the block 

### ISSUE THREAD

**Issue by yjukaku** [rails/rails#23195]
Using Rails 4.2.1 and a mysql2/maria DB

If you load an ActiveRecord object from the database before using a `Time.use_zone(time_zone)` block, and try to `srftime` format that object's timestamp column (eg. `created_at`), then it will not respect the given `time_zone`. However, if you load the ActiveRecord object while inside of the block, it will be respected.

```ruby
Loading development environment (Rails 4.2.1)
irb(main):001:0> s = Shift.first
  Shift Load (0.2ms)  SELECT  `shifts`.* FROM `shifts`  ORDER BY `shifts`.`id` ASC LIMIT 1
=> #<Shift id: 1, created_at: "2016-01-18 19:20:05", updated_at: "2016-01-18 20:31:00">
irb(main):002:0> s.updated_at.strftime("%H:%M")
=> "20:31"
irb(main):003:0> Time.use_zone("America/New_York"){s.updated_at.strftime("%H:%M")}
=> "20:31"
irb(main):005:0> Time.use_zone("America/New_York"){Shift.find(s.id).updated_at.strftime("%H:%M")}
  Shift Load (6.3ms)  SELECT  `shifts`.* FROM `shifts` WHERE `shifts`.`id` = 1 LIMIT 1
=> "15:31"
```

TBH, I'm not sure if this is a bug or if this is expected behavior.  This problem can be easily worked around by using `s.updated_at.in_time_zone`, but I was under the impression that using a `Time.use_zone` block should render that unnecessary.

**Comment by pixeltrix** [comment]
@yjukaku this is what I'd expect but then I know that accessing the timestamp attribute will convert the DB value to a `ActiveSupport::TimeWithZone` and cache that because it's an expensive operation. I don't see how we could fix this without having to redo the conversion on every attribute read which would be a significant performance hit. There are a few other places in Active Record where this kind of scoping needs all actions carried out inside the block - the `Model.scoping`method is one that springs to mind. I'll see that we update the documentation with a note pointing out this issue with `use_zone`.

Thanks for your report, sorry we can't do much about it other than a documentation change.

**Comment by yjukaku** [comment]
Thanks for the update!
