### ISSUE TITLE
#simple_format does not work as expected

### ISSUE THREAD

**Issue by chumakoff** [rails/rails#23230]
The method cuts off the part of a text that goes after '<' sign:

simple_format("one < two")
=> 
``` html
<p>one </p>
```

related issue: https://github.com/sparklemotion/nokogiri/issues/1419

**Comment by chumakoff** [comment]
Rails 4.2.4

**Comment by kaspth** [comment]
https://github.com/rails/rails-html-sanitizer/issues/46#issuecomment-174477326

Thanks! :heart:

**Comment by chumakoff** [comment]
It seems to be that on https://github.com/sparklemotion/nokogiri/issues/1419 they are not going to solve the problem. But this issue is appeared on different servers and operating systems. Will you leave it as it is ?

**Comment by flavorjones** [comment]
Nokogiri is operating as expected here. Not sure there's anything anyone can do about invalid HTML being treated as invalid HTML by an HTML parser.

My reading of `simple_format`'s docs indicate that it's intended to accept **text**, and transform it into HTML. In that case, I'd argue that the `text` parameter should be HTML-escaped before being treated as HTML. @kaspth can you tell me if I'm misunderstanding the purpose of this method?

**Comment by matthewd** [comment]
`simple_format`'s expected behaviour is ambiguously defined, I think.

What it *actually does*, unless it's instructed otherwise, is pass the given string through `sanitize` -- that is, it treats its input as [untrusted, by default] HTML, only with significant newlines. But the documentation doesn't make that clear.

I suspect this dates back to before we added HTML safety to strings: when, apart from well-documented exceptions, HTML-out implied HTML-in.

**Comment by kaspth** [comment]
@matthewd I see, you're saying `simple_format` isn't `html_safe` safe aware?

**Comment by chumakoff** [comment]
It looks like on Rails 5-0-stable this error has been resolved
