### ISSUE TITLE
Cannot validate associated model on custom context

### ISSUE THREAD

**Issue by RagunovichVlad** [rails/rails#23261]
When we try to validate associated model with `validates_associated` on custom context, we get `true` on the first call of method `valid?(:my_context)` and get `false` on the second call method `valid?(:my_context)`.
If we place `accepts_nested_attributes_for` before validation validation works wrong, but if we place  `accepts_nested_attributes_for` after validation validation works good.

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.5'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :profiles, force: true do |t|
    t.integer :user_id
    t.string :info
  end
end

class User < ActiveRecord::Base
  has_one :profile

  accepts_nested_attributes_for :profile, allow_destroy: true

  validates_presence_of :profile, on: :my_context
  validates_associated :profile, on: :my_context
end

class Profile < ActiveRecord::Base
  belongs_to :user
  validates :info, presence: true, on: :my_context
end

class BugTest < Minitest::Test
  def test_context_validation_stuff
    user = User.create
    user.create_profile(info: nil)

    user = User.last

    assert !user.valid?(:my_context) #=> false
    assert !user.valid?(:my_context) #=> true
  end
end
```

**Comment by vipulnsward** [comment]
Thanks for the reproduction script. Confirming that this fails on master.

**Comment by RagunovichVlad** [comment]
@vipulnsward I want to try to fix it by myself and it will be good if you point me where may be bug

**Comment by vipulnsward** [comment]
Great. You can start at https://github.com/vipulnsward/rails/blob/4642d68d8021893c69bfd16ed6e926ae03a6d777/activemodel/lib/active_model/validations.rb and check validation_context. First check if this actually the expected behaviour, and if not, what maybe the case.

**Comment by rafal-brize** [comment]
Hi.
I've looked into this issue a bit and here are my findings

It is actually the fault of `autosave` generated validation callbacks.

If you rewrite your code a bit you will see the same thing happening here:
```
class User < ActiveRecord::Base
  has_one :profile, autosave: true
  validates_associated :profile, on: :my_context
end

class Profile < ActiveRecord::Base
  belongs_to :user
  validates :info, presence: true, on: :my_context
end

class BugTest < Minitest::Test
  def test_context_validation_stuff
    user = User.create
    user.create_profile(info: nil)

    user = User.last

    user.valid?(:my_context) #=> true
    user.valid?(:my_context) #=> false
  end
end
```
If you load the profile with ` user.profile` before validating you see it works.
It is consistent with the autosave entry in guides 
>If you set the :autosave option to true, Rails will save any **loaded** members and destroy members that are marked for destruction whenever you save the parent object.

So what happens here? Why those strange results?
* user does not have profile loaded so autosave callbacks skip the validation of profile
* `validates_associated` callback calls `valid?` on profile. It loads the profile in order to do so. there is no validation_context logic there, is is not forwarded from `user.valid?`, so validation passes.
* This is why first call to  `user.valid?(:my_context)` returns `true`
* The second time we call `user.valid?(:my_context)` `profile` is loaded and validation callbacks perform validation on a profile
* For `:autosave` validation_context logic is present and `:my_context` is passed down from user.
* And so validation error is created.

This is why one should always load associations if one uses `autosave` or `accepts_nested_attributes_for` 

This is a big issue, and would like ask core members how they prefer to handle it.
This lesson has given me 2 different thoughts on what could be improved. 

1) Loading associations for `:autosave`. Started working on it, but than decided to stop and ask if this is a good idea, i am mainly concerned about the impact on performance.

2) `validates_associated` could have an option to receive validation_context of a parent. Is this something you would welcome in your code?

**Comment by byroot** [comment]
The reproduction script now pass successfully on `main`. Not quite sure when this was fixed but seems like it was at some point.
