### ISSUE TITLE
Publish "Using Rails for API-only Applications" guide

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#23322]
Since it is one of the big features in Rails 5 we should publish with in the release.

Right now it is marked as work in progress.

A few things we need to do:

- [x] Check if the list of modules/middleware are correct.
- [ ] Check if it conform our documentation guidelines.

cc @rails/documentation @fxn

**Comment by fxn** [comment]
@rafaelfranca just an ACK here, I'll do a pass before we release.

**Comment by vijaydev** [comment]
I did a pass. Looks real good :+1:

**Comment by fxn** [comment]
If @vijaydev revised it then it is good to go. I'll also read it but we can publish already.

**Comment by vijaydev** [comment]
Merged the PR to publish. Closing this.

**Comment by fxn** [comment]
I just generated an API app from master and got a middleware stack that is different from the one in the guide. In development mode:

- `Rack::Sendfile`
- `ActionDispatch::Static`
- `ActionDispatch::LoadInterlock`
- `ActiveSupport::Cache::Strategy::LocalCache::Middleware`
- `Rack::Runtime`
- `ActionDispatch::RequestId`
- `Rails::Rack::Logger`
- `ActionDispatch::ShowExceptions`
- `ActionDispatch::DebugExceptions`
- `ActionDispatch::RemoteIp`
- `ActionDispatch::Reloader`
- `ActionDispatch::Callbacks`
- `ActiveRecord::Migration::CheckPending`
- `ActiveRecord::ConnectionAdapters::ConnectionManagement`
- `ActiveRecord::QueryCache`
- `Rack::Head`
- `Rack::ConditionalGet`
- `Rack::ETag`

and in production mode

- `Rack::Sendfile`
- `ActionDispatch::LoadInterlock`
- `ActiveSupport::Cache::Strategy::LocalCache::Middleware`
- `Rack::Runtime`
- `ActionDispatch::RequestId`
- `Rails::Rack::Logger`
- `ActionDispatch::ShowExceptions`
- `ActionDispatch::DebugExceptions`
- `ActionDispatch::RemoteIp`
- `ActionDispatch::Callbacks`
- `ActiveRecord::ConnectionAdapters::ConnectionManagement`
- `ActiveRecord::QueryCache`
- `Rack::Head`
- `Rack::ConditionalGet`
- `Rack::ETag`

Just double-checking in case there was a reason for the reduced listing. Otherwise, I'd push both lists in the pass I am doing.

**Comment by rafaelfranca** [comment]
@fxn :+1: for your list.

**Comment by fxn** [comment]
Thanks @rafaelfranca!

**Comment by fxn** [comment]
This paragraph also makes no sense:

> By default, Rails will add a middleware that provides a cache store based on the configuration of your application (memcache by default). This means that the built-in HTTP cache will rely on it.

The default is not memcache(d), and HTTP caching and `stale?` are about conditional GETs, nothing to do with Rails caching.

Going to factor all those middleware sections out to the Rack guide revised, and just leave a link there.
