### ISSUE TITLE
Rails g Controller issue

### ISSUE THREAD

**Issue by sai43** [rails/rails#23333]
Hi,

I am using Rails 4.2.4, in my application. By using rails generator create controller called **Blobs**, in my route file I've added **resource :blobs*.

When I am trying to find routes for that controller, it shows all routes except index

![screen shot 2016-01-29 at 6 15 27 pm](https://cloud.githubusercontent.com/assets/4579664/12675968/51b85eb2-c6b4-11e5-8f8e-43095503255a.png)

**Comment by nbulaj** [comment]
Hi @sai43 . Check out your code - you write:

> resource :blobs

`resource` is for _singular_ resources, that's why you don't have an _index_ action (that represent collections in most of cases). If you will change it to `resources` then it will generate _index_ action.

Read more on Rails Guides - http://guides.rubyonrails.org/routing.htm

**Comment by eileencodes** [comment]
Hi @sai43! We reserve the Rails issues tracker for issues/bugs in the Rails code base. For questions regarding your application and how to use rails please use Stack Overflow where a wider community will be able to help debug your issue. Thanks for understanding!
