### ISSUE TITLE
dev:cache command isn't listed in rails --help

### ISSUE THREAD

**Issue by bronson** [rails/rails#23410]
Easiest fix is to add a line to `ADDITIONAL_COMMANDS` in `railties/lib/rails/commands/commands_tasks.rb`.  I'm happy to submit a PR for that.

However, this seems like a short-term fix...  Is there any reason Rails commands don't self-document the way Rake tasks do?  (It seems odd that all Rake tasks -- but not all Rails commands -- are listed in `rails --help`.)

I can submit a more comprehensive PR to move documentation into the individual commands if desired.  It seems like this was the original intention of `set_banner` in https://github.com/rails/rails/commit/2ddb5997108c4612dd96747fb082ba7f93427a31.

**Comment by maclover7** [comment]
cc @kaspth

**Comment by kaspth** [comment]
After some internal discussion, we've learned that the command infrastructure left much to be desired and was pretty much unfit to compose our own commands (e.g. `server` etc.).

As such, since `dev:cache` was the only task to make the transition, we should just convert that back to a Rake task.

@ccallebs has expressed interest in working on this. So coordinate with him, if any of you want to take over 😁

**Comment by bronson** [comment]
Sounds good, I'll file a PR to revert `dev:cache` back to rake.

I had the same feeling about the `rails/commands` code.  Fixing it, proper fixed, looks to be a pretty big job.  @ccallebs have you looked into it yet?

**Comment by bronson** [comment]
@kaspth I think #23552 is ready to go.
