### ISSUE TITLE
Rails 5 - Incorrect foreign key type when specifying references in model generator

### ISSUE THREAD

**Issue by stephenorr** [rails/rails#23422]
While playing with Rails 5 (5.0.0.beta2), I've run into a problem with foreign keys and generated models.

I have two models:

```ruby
class Gateway < ApplicationRecord
  belongs_to :site
end

class Site < ApplicationRecord
  has_many :gateways
end
```

I wanted to use Postgres and UUID primary keys for this, so I followed the examples at http://blog.mccartie.com/2015/10/20/default-uuid's-in-rails.html, and enabled UUID primary keys in my `config/application.rb`, as follows:

```ruby
config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid
end
```

The generated migrations looked like this:

```ruby
class EnableUuidExtension < ActiveRecord::Migration[5.0]
  def change
    enable_extension "uuid-ossp"
  end
end

class CreateSites < ActiveRecord::Migration[5.0]
  def change
    create_table :sites, id: :uuid do |t|
      t.string :name

      t.timestamps
    end
  end
end

class CreateGateways < ActiveRecord::Migration[5.0]
  def change
    create_table :gateways, id: :uuid do |t|
      t.string :name
      t.string :ip_address
      t.references :site, foreign_key: true

      t.timestamps
    end
  end
end
```

When running the final migration, to create the `gateways` table, I get this error message:

```
$ rails db:migrate
== 20160202103820 CreateGateways: migrating ===================================
-- create_table(:gateways, {:id=>:uuid})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  foreign key constraint "fk_rails_a0c8241d05" cannot be implemented
DETAIL:  Key columns "site_id" and "id" are of incompatible types: integer and uuid.
: CREATE TABLE "gateways" ("id" uuid DEFAULT uuid_generate_v4() PRIMARY KEY, "name" character varying, "ip_address" character varying, "site_id" integer, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, CONSTRAINT "fk_rails_a0c8241d05"
FOREIGN KEY ("site_id")
  REFERENCES "sites" ("id")
) /Users/steve/heroku/guru-api/db/migrate/20160202103820_create_gateways.rb:3:in `change'
/Users/steve/heroku/guru-api/bin/rails:9:in `require'
/Users/steve/heroku/guru-api/bin/rails:9:in `<top (required)>'
/Users/steve/heroku/guru-api/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
ActiveRecord::StatementInvalid: PG::DatatypeMismatch: ERROR:  foreign key constraint "fk_rails_a0c8241d05" cannot be implemented
DETAIL:  Key columns "site_id" and "id" are of incompatible types: integer and uuid.
: CREATE TABLE "gateways" ("id" uuid DEFAULT uuid_generate_v4() PRIMARY KEY, "name" character varying, "ip_address" character varying, "site_id" integer, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, CONSTRAINT "fk_rails_a0c8241d05"
FOREIGN KEY ("site_id")
  REFERENCES "sites" ("id")
)
/Users/steve/heroku/guru-api/db/migrate/20160202103820_create_gateways.rb:3:in `change'
/Users/steve/heroku/guru-api/bin/rails:9:in `require'
/Users/steve/heroku/guru-api/bin/rails:9:in `<top (required)>'
/Users/steve/heroku/guru-api/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
PG::DatatypeMismatch: ERROR:  foreign key constraint "fk_rails_a0c8241d05" cannot be implemented
DETAIL:  Key columns "site_id" and "id" are of incompatible types: integer and uuid.
/Users/steve/heroku/guru-api/db/migrate/20160202103820_create_gateways.rb:3:in `change'
/Users/steve/heroku/guru-api/bin/rails:9:in `require'
/Users/steve/heroku/guru-api/bin/rails:9:in `<top (required)>'
/Users/steve/heroku/guru-api/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

It looks to me like the model generator is not checking to see what type of primary key is set on the referenced model - so it's assuming (incorrectly, in this case) that it will be an integer type.

I've dumped my basic app into a public GitHub repo here: https://github.com/stephenorr/rails-api

If you need me to do anything else to help diagnose this, let me know.

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing? This would allow for easier debugging. :)

**Comment by matthewd** [comment]
> It looks to me like the model generator is not checking to see what type of primary key is set on the referenced model - so it's assuming (incorrectly, in this case) that it will be an integer type.

That's expected. Migrations need to work the same everywhere, so they can't vary their behaviour by inspecting the current state of the database.

**Comment by rafaecheve** [comment]
to solve this add uuid type as it says here: http://edgeguides.rubyonrails.org/active_record_postgresql.html

# db/migrate/20150418012400_create_blog.rb
enable_extension 'pgcrypto' unless extension_enabled?('pgcrypto')
create_table :posts, id: :uuid, default: 'gen_random_uuid()'
 
create_table :comments, id: :uuid, default: 'gen_random_uuid()' do |t|
  # t.belongs_to :post, type: :uuid
  t.references :post, type: :uuid
end
 
# app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end
 
# app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

**Comment by fnando** [comment]
Rails clearly has a broken behavior here because `belongs_to/references` is not respecting a system-wide configuration. Would a PR fixing this be accepted?

**Comment by BM5k** [comment]
Same problem here, rails 5 master. I have explicitly configured the primary key type and migration to add a child table 💥. 

Contrary to what @matthewd says above, no database inspection should be needed to follow the application wide explicit configuration.

As @rafaecheve pointed out, it _is_ possible to manually set the foreign key type. However, the fact that rails doesn't use the provided config is surprising. IMO the least-surprising behavior would be for the migration generator to automatically add the `type:` option to references.

Less desirable (because it introduces _yet another configuration_ and could allow for situations in which someone sets the two options to incompatible values) would be to add a `foreign_key_type` option to the generators so that developers can explicitly declare the intent for foreign keys to be a particular type. Then, as in the other--clearly superior in every way--behavior, the migration generator could automatically add the `type:` option to references.

Regardless, while the current behavior violates the principle of least surprise and requires manual developer intervention, at least the error message was relatively clear.

@maclover7 here's the executable test script you asked for. I was hesitant to include it because I think the script (and @stephenorr's example app) only demonstrate the `PG::DatatypeMismatch` error. That error just a _symptom_ of the bug in the migration generator. Without running the generator yourself, it's probably pretty easy to say "just add the `type` option and problem solved".

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile true do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'pg'
end

require 'active_record'
require 'logger'

ActiveRecord::Base.logger = Logger.new STDOUT
ActiveRecord::Base.establish_connection adapter: 'postgresql',
                                        url: "postgres://#{ `whoami` }@localhost/rails-issue-23422"

ActiveRecord::Schema.define do
  enable_extension 'uuid-ossp'

  create_table 'dogs', default: -> { 'uuid_generate_v4()' },
                       force:   :cascade,
                       id:      :uuid
end

class CreateToys < ActiveRecord::Migration[5.0]
  def change
    create_table :toy, id: :uuid do |t|
      t.belongs_to :dog, foreign_key: true
    end
  end
end

CreateToys.migrate :up
```

**Comment by zspencer** [comment]
I have also ran into this issue; running the latest production release of rails 4.

It was very surprising that that when we used the `references` method to tie to a tables with a uuid id it created integer fields.

**Comment by obie** [comment]
Just ran into this issue myself and was pretty confusing... Is it really not possible/desirable for the migration to introspect on the current state of the database?

**Comment by jpwynn** [comment]
Ran into this in Rails 5.0.1... if Rails "knows" to globally use uuid for the reference via 

    g.orm :active_record, primary_key_type: :uuid

it is counterintuitive in the extreme that when creating a foreign key reference to ANY new model that it assume an integer.

On one hand, an app COULD have some legacy tables that have integer primary key (in which case fixing the rails model generator so it relies upon the primary_key_type: :uuid would give a mismatch. 

But on the other hand, right now, it currently ALWAYS fails on new tables if primary_key_type: :uuid is simply ignored as it is now.

So... it seems to me the better choice is to break 'sometimes' in the case of legacy integer-key tables (and require a manual edit to _those_ migrations), as opposed to continue breaking 'always' on all new tables (and requiring a manual edit to _every_ migration involving a foreign key).

If reluctant to change the default to use primary_key_type when creating foreign keys, a  solution might be to introduce a similar setting for foreign keys that lets developers 'opt in' to using uuid for both primary and foreign keys

    g.orm :active_record, force_foreign_key_type: :uuid

**Comment by jpwynn** [comment]
FWIW adding the ar-uuid gem I used back in Rails 4 handles the associations correctly in Rails 5.0.1 at least for new tables, but I have not tested if associations to legacy integer-key tables are handled correctly or not since I have no legacy tables in my Rails 5 app. 

That said, doesn't seem a gem should be required in Rails 5 with the addition of the primary_key_type setting.

**Comment by thomas-siimpl** [comment]
```
class AddUserToProjects < ActiveRecord::Migration[5.0]
  def change
    add_reference :getaways, :site, type: :uuid, foreign_key: true
  end
end
```

**Comment by kylefox** [comment]
I was also surprised by this behavior. I'm using this snippet to have all generated migrations use `uuid` as the primary key type:

```ruby
Rails.application.config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid
end
```

Perhaps one could opt-in to using `:uuid` as the default type for foreign keys in generated migrations (similar to what @jpwynn suggested). I like this approach because it very closely mirrors how one opts-in to `:uuid` for primary keys:

```ruby
Rails.application.config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid

  # Because I'm using :uuid for PKs, let me specify them as the default for FKs too.
  g.orm :active_record, foreign_key_type: :uuid
end
```

**Comment by matthewd** [comment]
@stevenpetryk what is the "this" that you are proposing to implement?

**Comment by danielrhodes** [comment]
@matthewd The issue here that @stevenpetryk is noting here is the default behavior assumes the foreign key should be an integer. My expectation, having run into the same issue, is that if you use `references` while creating a table that it will infer the type of the column to match the PK.

**Comment by matthewd** [comment]
@danielrhodes thanks, but I did read the issue. We cannot meet your expectation because migrations need to leave the database in a consistent state when run in different orders. @stevenpetryk offered to provide a solution, and the nature of that solution is what I was asking about.

**Comment by stevenpetryk** [comment]
Of course! ☺️ 

My argument is predicated on the principle of least surprise. I think it is surprising that Rails doesn't assume every primary key is a UUID when the configuration is set as such. I'll write this as if it's a bug report to show what behavior I think is least surprising!

### Steps to reproduce

1. Configure Rails to use UUIDs:

  ```rb
  config.generators do |g|
    g.orm :active_record, primary_key_type: :uuid
  end
  ```

2. Generate a migration with a foreign key, one way or another:
  
  ```sh
  rails g migration add_location_to_users location:references
  ```

3. Open `/db/migrate/xxxxx_add_location_to_users.rb`

### Expected behavior

The generated migration should have specified `type: :uuid` in `add_column`.

### Actual behavior

The generator did not specify the `type` in `add_column`.

Note that this suggestion is just for Rails to make better assumptions. Right now, its assumption is that foreign keys always reference integers. My argument is that it should assume that foreign keys reference UUIDs if primary keys are set to be UUIDs.

This suggestion doesn't require any knowledge of the schema, it just requires changing the generator to look at the `primary_key_type` config.

---

P.S., I'm not sure what you mean when you say "migrations need to leave the database in a consistent state when run in different orders". How does that work with foreign keys? The foreign table has to exist first, yeah?

**Comment by danielrhodes** [comment]
I'm also very curious what the "different orders" means here, as I have thus far thought that is exactly what I didn't want. Wouldn't you want it in order so that, for example, if you are creating a table in migration 1, and then adding a column to that table in migration 2, that migration 1 runs first. Isn't that order one of the reasons for the ID?

**Comment by matthewd** [comment]
@stevenpetryk :+1: thanks, changing the generator sounds like a fine idea.

> P.S., I'm not sure what you mean when you say "migrations need to leave the database in a consistent state when run in different orders". How does that work with foreign keys? The foreign table has to exist first, yeah?

Right.. migrations aren't run in *random* order, and very often depend on other migrations having been run first (you can't remove a column if it hasn't been added).

The situation we need to be wary around is [branch] merges: if migration A and migration B are both reasonable things for two different people to have created independently from the same starting state, then it's possible that will happen. That will mean the author of A runs them in the order A, B; the author of B runs them in the order B, A; and everyone who sees them appear simultaneously will run them in whichever order is dictated by their relative timestamps.

The concrete risk here is that A is "change type of x.id from integer to bigint" and B is "add column y.x_id references x.id". If the latter attempted to infer x.id's type, the authors of those two migrations would end up with clearly different databases (that is, with differing types on y.x_id), while both believing they're up to the same schema version.

**Comment by stevenpetryk** [comment]
Ah I see what you're saying, I misunderstood you to say that the intention was for migrations to be able to run out of order.

I definitely agree that merging could cause conflicts on types. Do you think it'll be that big of a problem? I have a feeling that most people who use UUID primary keys will do so from the beginning of the project, since changing primary key types on production apps is a huge PITA. 

Plus, large Rails teams are totally used to migrations causing trouble when they're merged out of order in my experience!

But yeah, I'll open a PR for it next week and see if it gathers any interest.

**Comment by danielrhodes** [comment]
@matthewd Thanks for the thorough explanation. Perhaps the solution here then is to require a `type` param on `references` as this would remove the current inference of integer without an explicit type, solve for the case where there could be overlapping migrations, and of course mine and others confusion in the matter.

**Comment by hderms** [comment]
This problem is plaguing a project I'm currently working on

**Comment by hderms** [comment]
@stevenpetryk is right I think in the sense that rails shouldn't be assuming integers as primary keys if it was configured to generate them as UUIDs

**Comment by groe** [comment]
I regularly run into this issue because the behaviour is so counterintuitive. Having primary keys configured for UUIDs via `primary_key_type: :uuid` should make foreign keys in generated migrations UUIDs too. Or at least there should be a `foreign_key_type: :uuid` setting.

Such behaviour would be independent from the current state of the database and consistent with the existing generator behaviour for primary keys.

Why is this issue closed?

**Comment by kenigbolo** [comment]
Seems I'm a bit late to the party however I just came across the same issue and was quite surprised how rails handled the foreign key constraint. In my honest opinion it makes sense to have rails making the foreign keys `uuid`s if the primary key has been specified to be uuid. Worse case scenario we should be able to configure it ourselves by setting the foreign key type. This issue isn't resolved so it's quite weird that this is a closed issue already.

**Comment by etcook** [comment]
Late to the party, but was also struck by how inelegant ActiveRecord handles this, especially when you've already explicitly defined the primary key type.

If the argument against implementing introspection is that the migration should operate consistently, then there should be no project wide generator option for uuid either.

**Comment by jjviscomi** [comment]
I am with everyone here ... in your migration you can do the following and it will all work: `t.references  :xxxxxxxx, type: :uuid, foreign_key: true`

**Comment by bjgaynor** [comment]
I'll jump on the bandwagon and say this should definitely not be a closed issue - it's not very often Rails behaves in surprising and unintuitive ways.  It should definitely respect the primary key generator or have a foreign key generator setting.

**Comment by stevehill1981** [comment]
Has anyone checked to see if Rails 6 exhibits the same issue?

**Comment by kenigbolo** [comment]
It might be fixed in rails 6 but I’m not sure if there was anything in regards to this in any RFC or in the changelog. Difficult to say from my end as I haven’t tried rails 6 out yet

**Comment by stevehill1981** [comment]
Will give it a whirl later today if I get chance.

**Comment by stevehill1981** [comment]
Alright, I've created a gist that contains a minimal demonstration of this bug in both Rails 6 master and Rails 5.2.3.

https://gist.github.com/stevehill1981/12a58fc0203a95f32a3bcd19aa50950e

Hopefully that's enough to help fix it; I can have a go at a PR myself if nobody else is keen :)

**Comment by stevehill1981** [comment]
> In your migration you can do the following and it will all work: `t.references :xxxxxxxx, type: :uuid, foreign_key: true`, sometimes automagical things rails does isn't optimal ...

The `type: :uuid` is necessary here because `ActiveRecord::ConnectionAdapters::ReferenceDefinition` defaults to `:bigint`, and doesn't attempt to look up the type of the referenced column.

I think the proper behaviour should be:

1. **If no type is specified and the referenced table exists**, find the primary key for the referenced table and use that type.
2. **If no type is specified, but the referenced table does not exist**, default to the `primary_key_type` specified for the generator (in the assumption that will be correct most of the time - except for legacy tables).
3. **If a type is specified**, use that type, don't bother sniffing.

I'm generally of the opinion that the sniffing should be done even if we're not creating a foreign key - because it's nonsensical to create a column of a different type to the one being referenced.

I've got some code that sort of works, but I've managed to break the tests in the process and I'm not confident in my ability to fix them 😢

**Comment by meltheadorable** [comment]
I don't actually care if the sniffing happens, I'd be perfectly happy with the generators respecting the primary key setting in the application config so that -- the same way they know to ad `id: :uuid` to new table definitions they add `type: :uuid` to new `references/belongs_to` columns. 

I encountered this issue today while setting up a new database and having to manually edit all of the migrations I write to account for this is consistently tripping me up in what should be a relatively smooth process.

**Comment by stevehill1981** [comment]
@meltheadorable That makes sense, and I'd imagine it'll be easier to accomplish (I hope!)

I've been poking around in the generators, but I haven't yet found the correct place to put the new logic; if you specify a `primary_key_type` in the tests, no columns end up getting added. No doubt I'm missing something obvious.

**Comment by swsalsify** [comment]
@stevehill1981's solution has my vote, but I also agree that just using the primary key setting (without sniffing) is a reasonable improvement. Otherwise, the `t.references` method feels like a misfeature and possibly should be deprecated and removed. Other people have said it's surprising, but to illustrate the general principle:

```
t.string :status
t.float :percent_complete
t.references :other_table
```

The method `.references` inhabiting the space where the datatype goes implies that the datatype will be inferred, either directly or with some reasonably-accurate heuristic. But if no inference is happening, then why was this syntax chosen instead of the less-surprising `t.<datatype>, references: :other_table`?

**Comment by xiaohui-zhangxh** [comment]
I write a hot fix for this. Add below code to `config/application.rb`

```
config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid
  hacker = Module.new do
    def options_for_migration
      ar = Rails.application.config.generators.active_record
      default = ar[:primary_key_type] == :uuid ? { type: :uuid } : {}
      default.merge(super)
    end
  end
  require 'rails/generators/generated_attribute'
  Rails::Generators::GeneratedAttribute.prepend hacker
end
```

**Comment by JeremyKirkham** [comment]
Can confirm this issue still exists in the stable 6.0 release.

**Comment by MilanVilov** [comment]
> to solve this add uuid type as it says here: http://edgeguides.rubyonrails.org/active_record_postgresql.html
> 
> create_table :comments, id: :uuid, default: 'gen_random_uuid()' do |t|
> 
> # t.belongs_to :post, type: :uuid
> t.references :post, type: :uuid
> end

Praise!

**Comment by ivancortesromero** [comment]
> Can confirm this issue still exists in the stable 6.0 release.

@JeremyKirkham I just tried replicated it:

Rails version:  `6.0.2.2`

Referenced table:
```rb
class CreatePricing < ActiveRecord::Migration[6.0]
  def change
    create_table :pricings, id: :uuid do |t|
      t.string :original_id, null: false
      t.decimal :total, null: false

      t.timestamps
    end
    add_index :pricings, :id, unique: true
  end
end
```

Table with the foreign key:

```rb
class CreateQuotation < ActiveRecord::Migration[6.0]
  def change
    create_table :quotations, id: :uuid do |t|
      t.string :uid, null: false
      t.decimal :number, null: false
      t.belongs_to :pricing, foreign_key: true

      t.timestamps
    end
    add_index :quotations, :id, unique: true
  end
end
````

Here is the first difference, no error was raised when migrations were run. And from PostgreSQL console:

```pg
development=# \d quotations
    Column     |              Type              | Collation | Nullable |      Default      
---------------+--------------------------------+-----------+----------+-------------------
 id            | uuid                           |           | not null | gen_random_uuid()
 uid           | character varying              |           | not null | 
 number        | numeric                        |           | not null | 
 pricing_id    | bigint                         |           |          | 
 created_at    | timestamp(6) without time zone |           | not null | 
 updated_at    | timestamp(6) without time zone |           | not null | 
Indexes:
    "quotations_pkey" PRIMARY KEY, btree (id)
    "index_quotations_on_id" UNIQUE, btree (id)
    "index_quotations_on_pricing_id" btree (pricing_id)

``` 
Anyway, the data type of `pricing_id` is `bigint`.

Now, I try to create a `quotation` from the Rails console. First, I created a `pricing`: 

```rb
[1] pry(main)> V1::Pricing.create!(original_id: '1212', total: 123123)
   (0.6ms)  BEGIN
  V1::Pricing Create (1.4ms)  INSERT INTO "pricings" ("original_id", "total", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["original_id", "1212"], ["total", "123123.0"],["created_at", "2020-04-22 03:14:01.233253"], ["updated_at", "2020-04-22 03:14:01.233253"]]
   (3.3ms)  COMMIT
=> #<V1::Pricing:0x0000564964e87c50
 id: "1f0bdbb1-580b-4a70-8ad9-20a086af4b42",
 original_id: "1212",
 total: 0.123123e6,
 created_at: Wed, 22 Apr 2020 03:14:01 UTC +00:00,
 updated_at: Wed, 22 Apr 2020 03:14:01 UTC +00:00>
```
Finally, I created a `quotation`:

```rb
[2] pry(main)> V1::Quotation.create!(total: 123123, pricing: V1::Pricing.last, uid: 'uid')
  V1::Pricing Load (0.4ms)  SELECT "pricings".* FROM "pricings" ORDER BY "pricings"."id" DESC LIMIT $1  [["LIMIT", 1]]
   (0.2ms)  BEGIN
  V1::Quotation Create (0.3ms)  INSERT INTO "quotations" ("uid", "total", "pricing_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["uid", "uid"], ["total", "123123.0"], ["pricing_id", 1], ["created_at", "2020-04-22 03:18:03.347784"], ["updated_at", "2020-04-22 03:18:03.347784"]]
   (3.2ms)  COMMIT
=> #<V1::Quotation:0x00005649643a2358
 id: "ebb7b5c0-f471-493d-be34-28afb3334dcf",
 uid: "uid",
 total: 0.123123e6,
 pricing_id: 1,
 created_at: Wed, 22 Apr 2020 03:18:03 UTC +00:00,
 updated_at: Wed, 22 Apr 2020 03:18:03 UTC +00:00>
```
At this point, I was surprised.

1. No error has been raised so far event though I could create the quotation.
2. What is that `pricing_id` `1`? where was it found? Maybe @matthewd could you answer this?
3. Sincerely,  I prefer the original behavior: raising the error which @stevehill1981 has reported.

Please tell me if I have made a mistake.

**Comment by zersiax** [comment]
Late to the party for sure,but this tripped me up in a project today as well.  Magic is cool, but if the devs decide it should work differently  than most people expect, it just gets in the way :(

**Comment by pankajdoharey** [comment]
This problem still exists in Rails 6 and I am revisiting rails development after some yrs.

**Comment by jayzalowitz** [comment]
This really should at least reference the previous schema's id type. This is sort of silly, I realize there is a fix, but this makes rails fail on sharding really hard.

**Comment by MattRogish** [comment]
FYI y'all if you're on Rails 8 here's what I use to hijack references and default to :uuid unless you specify something else (essentially invert the current behavior). It's not really something that is applicable to land in Rails upstream code itself but if you're like me and only use UUID, it feels reasonable to invert but provide an off-ramp in case I need bigInt in my project. Which I don't, but...

```
module DefaultUuidReferences
  def initialize(*args, **kwargs)
    # If no explicit type was given, default to :uuid
    kwargs[:type] ||= :uuid
    super(*args, **kwargs)
  end
end

ActiveRecord::ConnectionAdapters::ReferenceDefinition.prepend(DefaultUuidReferences)

```
