### ISSUE TITLE
Rails 5 Beta2 link_to issue with post method

### ISSUE THREAD

**Issue by lohqua** [rails/rails#23509]
`resources :smiley_images do
    member do
      ...
      post :random_add_to_default
    end
  end`

which produces this route: `random_add_to_default_smiley_image POST   /smiley_images/:id/random_add_to_default(.:format)`

`<%= link_to 'Random smiley collection', random_add_to_default_smiley_image_path(@sc.id), method: :post, class: 'link' %>`

Generates: `<a class="link" rel="nofollow" data-method="post" href="/smiley_images/1/random_add_to_default">Random smiley collection</a>`

Which produces:

`ActionController::RoutingError (No route matches [GET] "/smiley_images/1/random_add_to_default")`

I have `<%= javascript_include_tag 'application' %>` no turbolinks since it blows up on multiple layouts and themes, at least it did in Rails 4.

**Comment by maclover7** [comment]
I believe that the correct way to solve the problem you are seeing is to use a `button_to` tag, instead of a `link_to` tag.

**Comment by meinac** [comment]
I've tested this with rails versions, `4.2.5.1`, `5.0.0.beta2` and `master` using `link_to` helper. All seems work as expected.
@lohqua can you please provide an example app which demonstrates the bug?

**Comment by diego-silva** [comment]
Hi @lohqua

I looked here and it seems to me that you might have removed the ```jquery_ujs``` entry from the ```app/assets/javascripts/application.js``` file, can you confirm this for me?

If that is the case the ```link_to``` will definitely not work for methods different than GET since web browsers do not support this and its the Rails ```jquery_ujs``` library that adds support for it.
(ps: it depends on the jQuery library being available)

You can get more information on what are the features and requirements for the ```jquery_ujs``` library by looking into their repo at https://github.com/rails/jquery-ujs#unobtrusive-scripting-adapter-for-jquery
