### ISSUE TITLE
rails5 master most validations fail

### ISSUE THREAD

**Issue by rubys** [rails/rails#23590]
The Agile Web Development with Rails tests are now failing.  Git bisect identifies [enables the evented monitor in new applications ](https://github.com/rails/rails/commit/de6ad5665d2679944a9ee9407826ba88395a1003) as the problematic commit:

```
de6ad5665d2679944a9ee9407826ba88395a1003 is the first bad commit
commit de6ad5665d2679944a9ee9407826ba88395a1003
Author: Xavier Noria <fxn@hashref.com>
Date:   Wed Feb 10 00:18:25 2016 +0100

    enables the evented monitor in new applications

:040000 040000 91906e3d6e4d1e9d5ee1314bad13249040c19ec2 03a1b63d4102eb3d8ed48431804eaed2540ce88b M	railties
bisect run success
```

Failure is early in the scenario: create scaffold for product, add some validations, go to the add product page, and press create product to see the validations fail.

Expected test results (as seen with Rails 4.2): http://intertwingly.net/projects/AWDwR4/checkdepot-215-42/section-7.1.html

Current test results (with master): http://intertwingly.net/projects/AWDwR4/checkdepot/section-7.1.html

**Comment by fxn** [comment]
@rubys Fan of your test suite over here!

In principle the monitor has nothing to do with these regular web flows... off the top of my head I can't image which could be the relationship. Do you have any idea maybe?

**Comment by diego-silva** [comment]
I was able to reproduce this behaviour when I started the server from a VM with the application path being inside a VBox shared folder or a NFS.

When I kept the server running and edited the model file from outside the VM, the server would not pickup the changes.

It's a know limitation of the listen gem and it makes sense since the guest OS cannot know about those changes:
> Some filesystems won't work without polling (VM/Vagrant Shared folders, NFS, Samba, sshfs, etc.).
> \- https://github.com/guard/listen#issues--limitations

@rubys are you running your tests in an setup somewhat similar to this?

**Comment by fxn** [comment]
@diego-silva awesome, yes that makes sense.

**Comment by rubys** [comment]
I'm running native on both OS/X and Ubuntu - no VM.

That being said, this should be reproducible on rails-dev-box - without any shared files.

I'll post more in a minute.

**Comment by fxn** [comment]
@rubys if the test suite is programmatically modifying the model, it could be the case that this is showing a race condition. The tree walker is deterministic, but with the evented monitor we depend on the event.

In my casual usage of the feature I have not seen the race condition, but in a fast scenario like that (if confirmed) it could perhaps show up.

**Comment by rubys** [comment]
As expected, undoing this line solves the problem:

https://github.com/rails/rails/commit/de6ad5665d2679944a9ee9407826ba88395a1003#diff-669ddf1ccccfa4a2b750c27d2d3d0de3L61

My script does edit the file then post to the page in under a second.

**Comment by rubys** [comment]
Reproduction instructions using rails-dev-box:

    eval "$(curl https://raw.githubusercontent.com/rubys/awdwr/master/rdb-setup)"
    testrails 6.1-7.1

At that point, cd to `~/git/railties/lib/rails/generators/rails/app/templates/config/environments` and edit `development.rb.tt`.  Rerun *just* the test without any downloads using:

    depot 6.1-7.1

Undo the change (e.g. by using `git checkout .`).  You can run a git bisect on rails with the normal `git checkout master`, `git bisect start`, `git bisect bad`, checking out some revision prior to this change, verifying that it is a good revision using `depot 6.1-7.1` and running `git bisect good`, followed by `git bisect run 6.1-7.1`.

**Comment by rubys** [comment]
All that being said, it may very well be that awdwr needs to modify the generated `config/environments/development.rb` in order to produce predictable results.

**Comment by fxn** [comment]
@rubys :+1:

**Comment by rubys** [comment]
Suggestion: https://github.com/rails/rails/commit/de6ad5665d2679944a9ee9407826ba88395a1003#commitcomment-16005284

**Comment by fxn** [comment]
@rubys Sounds good at first sight.

If the generator chooses to generate listen-based stuff it would do it with guards checking that env variable probably. I have a feeling of over-complication if I imagine the guards, but on the other hand *Gemfile* and *config/environments/development.rb* are shared in a project and people should be able to opt-out depending on each one's setup. This was possible before because the project could put some conditional in the `config.file_watcher` assignment, but with the introduction of the spring variant this changes.

Let me think a little bit about it and we'll do something soon.

@matthewd WDTY?

**Comment by fxn** [comment]
@rubys In principle I don't quite see the env var as something generated. I envision the generated defaults as something people can opt-out from by manual edit.

But your use case seems to justify a flag to opt-out at generation time right? `--skip-listen` or something like that. Would that be enough for your test suite?

**Comment by matthewd** [comment]
I agree `--skip-listen` is probably a good idea... but if the AWDwR suite is doing things in the right order, on a non-shared filesystem, then I don't think I would expect a race condition to be very likely. :confused:

**Comment by rubys** [comment]
@fxn a flag would work for me.  @matthewd AWDwR running on a non-shared file system reproducibly shows that there is a race condition on both OS/X and Ubuntu.

**Comment by fxn** [comment]
@e2 in your experience is this suspicious or makes sense? Executive summary: the test suite of @rubys performs edits in files and requests programmatically, so the time window between a change in a file and a request is really small and the code reloader does not seem to be triggered in time. Is it normal that we see a race condition here?

**Comment by rubys** [comment]
I will say that the 0.5 seconds is *generally* enough time for the results of the edit to be reflected in the results of a subsequent HTTP get.

**Comment by rubys** [comment]
Oh, and by the way, I plan to strongly suggest rails-dev-box to readers of AWDwR (the book), that way they have a known version of Ruby, etc.  Many of my readers are on Windows, which isn't exactly a hospitable environment for developers.  For those that take that suggestion, I will be suggesting that they use `--skip-listen`.

**Comment by e2** [comment]
A few things here:

1. `Listen` should work on Windows - the `wdm` backend should work reasonably well, and paths should be supported properly (except for possible FS/OS encoding mismatches in rare setups)
2. `Listen` should work fine in polling mode on NFS shares
3. `Listen` is mostly focused on editors, so it has special options and logic to workaround save/edit/create issues. This includes options (https://github.com/guard/listen#options) like `wait_for_delay` which waits until "disk activity" in watched folder stops before firing events (this may be an issue here).
4. `Listen` has a debug mode to determine if events are coming in, how they're collected and when the callback is called. (By setting the env var `LISTEN_GEM_DEBUGGING=2`). If you provide the output (STDERR) for a given test, I can take a look and explain what happened (or what didn't happen).

At some point I wanted to allow configuring listen through environment variables, e.g. using JSON or YAML. (For options: `:wait_for_delay`, `:force_polling`, `:latency` and `:ignore` for project-specific files).

But reading Listen options from env can be handled here too. (Env makes more sense since those are OS/System/FS related options).

**Comment by fxn** [comment]
@e2 thanks for the feedback.

The application generator is including `listen` by default on Mac OS X and Linux because it works out of the box there. Users still can opt-in in other platforms.

As of this writing polling is not a something that we want to use. The motivation for this feature is to avoid precisely walking the application tree. For the Rails use case, If we need to poll the filesystem better use the regular monitor, which walks once per request and is deterministic. If you edit for sure the application is going to be reloaded in the next request.

I wonder, though, if Rails could configure smaller values for `:latency` or `:wait_for_delay`, though 0.25 s + 0.10 s = 0.35 s does not seem to be a lot to create race conditions when people edit applications normally.

**Comment by fxn** [comment]
@rubys there you go!

By the way, the rails-dev-box is thought for Rails core development (I am sure you know it). If the book recommends it to follow, there is the risk that readers believe it is something for development, create an expectation, and start opening PRs for stuff we are not interested in, like application-level gems, rbenv, or others we've closed in the past to keep the box focused on its sole purpose.

If you believe this is not a risk, your call, just giving feedback :).

**Comment by rubys** [comment]
Looks good, I tested it locally and it works for me.  It will be picked up in the next awdwr run.

I can add a disclaimer.  Should our need diverge down the road, I can always create an awdwr-dev-box.  :-)
