### ISSUE TITLE
rails 5.0.0.beta2 api only app does not work with jbuilder

### ISSUE THREAD

**Issue by leomayleomay** [rails/rails#23833]
I am trying to build a API only app using the Rails 5.0.0.beta2. The problem is the API endpoint doesn't generate any json output, not sure why this is the case. I have included the `ActionController::ImplicitRender` as suggested, still no luck.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by leomayleomay** [comment]
@rafaelfranca you can find the sample app from https://github.com/leomayleomay/api_only, thank you

**Comment by tak1n** [comment]
@leomayleomay when starting your app and going to `/api/v1/guides.json`, I'm seeing:
```
{
"guides": []
}
```

If you mean the failing spec, this is due to rspec-rails controller specs which doesn't render views.
You have to explicitly say `render_views`.

IMO everything works like expected. See this commit: https://github.com/tak1n/api_only/commit/48c23119ebe05afebfa722fb107f8b6ab457bae2

**Comment by leomayleomay** [comment]
@tak1n thank you, that fixes the spec, not sure why i didn't find that instruction before.
