### ISSUE TITLE
Behaviour of ActiveRecord::Calculations#count when a block is supplied

### ISSUE THREAD

**Issue by paulleader** [rails/rails#23919]
So yesterday we had a bug in our code caused by accidentally calling `#count` with a block on an `ActiveRecord::Relation` rather than a plain Ruby `Array`.

Supplying a block to `Array#count` returns the count of array elements for which the block returns true.

A block supplied to `ActiveRecord::Relation#count` is silently ignored and a normal SQL COUNT is executed.

In the spirit of the Principal of Least Surprise, would it be sensible to have `ActiveRecord::Relation#count` behave like `Array#count` if a block is supplied?

I'd understand if you didn't want to change this, but if not, it might be a good idea for it to at least fail with an exception, or a warning.

**Comment by ianfleeton** [comment]
`ActiveRecord::Relation` could fall back on `Array#count` after calling `#to_a` on itself, which causes all rows to be fetched from the database so the block can filter each row (unlike a preceding `where` clause).

Hacky example ignoring the optional `column_name` parameter:

```ruby
def count(column_name = nil, &block)
  if block_given? # && column_name.nil?
    to_a.count(&block)
  else
    calculate(:count, column_name)
  end
end
```

Since a normal count is done inside the database I think an explicit call to `#to_a` in the client code makes this performance consideration obvious.

Would we want this to instantiate all rows implicitly?

```ruby
accounts = Account.where(active: true)
#...
accounts.count {|a| a.credit_limit > 50 && a.derived_val == 1 }
```

In the `Calculations` module there are also `#sum`, `#maximum`, etc. which have the same or similarly named methods in `Enumerable` & `Array` that take blocks and have different parameters... Maybe a warning/exception for all such methods receiving an unexpected block?

**Comment by paulleader** [comment]
Falling back to `Array#count` would be my preferred approach. Alternatively raising an exception (ArgumentError in this case).

Personally I see passing a block to a method as a pretty clear signal of intent from a programmer that they are expecting that block to do something, so I'm not sure just having a warning is a good compromise. Either do something with the block or stop and error.

I'll try and make some time this week to compare `Array` and `ActiveRecord::Relation` for other methods where this sort of confusion can arise.

**Comment by AndreasWurm** [comment]
> A block supplied to ActiveRecord::Relation#count is silently ignored and a normal SQL COUNT is executed.

> Personally I see passing a block to a method as a pretty clear signal of intent from a programmer that they are expecting that block to do something, so I'm not sure just having a warning is a good compromise. Either do something with the block or stop and error.

well thats were you are wrong. this is how ruby works, you can always pass a block to a method.

**Comment by paulleader** [comment]
Fair enough.

**Comment by eval** [comment]
This is addressed by https://github.com/rails/rails/pull/24203

**Comment by paulleader** [comment]
Ah, brilliant.

I was going to work on a pull request for that tonight, guess I'll look for something else to fix :)
