### ISSUE TITLE
5.0.0.beta3 behaves differently than 5.0.0.beta2 when validating polymorphic associations

### ISSUE THREAD

**Issue by claudiob** [rails/rails#23911]
Hello! I upgraded my app from 5.0.0.beta2 to 5.0.0.beta3 and I started getting an error.
You can reproduce it by running the code below both with beta2 (tests pass) and with beta3 (tests fail).

https://gist.github.com/claudiob/e453503c47074bab1617

---

##### Description of this issue

This issue only affects a very specific case that I believe is uncommon to most Rails apps.
Imagine you have the following code

```ruby
class Authorization < ActiveRecord::Base
  validates :authority_id, :authority_type, presence: true
  belongs_to :authority, polymorphic: true
  belongs_to :partner, foreign_key: 'authority_id', class_name: 'Authorization'
end
```

All your authorizations *belong to* some authority. In other words, the `belongs_to :authority` above is a **required** association.

For *some* authorizations, their authority is actually another instance of `Authorization` that we call partner. This is just for *some* authorizations, in other words the `belongs_to :partner` above is an **optional** association.

Let's call `partnerships` all those authorizations where the authority is a partner:

```ruby
class Partnership < Authorization
  validates_associated :authority
end
```

To be extra-sure of the validity of our data, we use `validates_associated`, so whenever a partnership is created, we also make sure that the associated partner is valid. 

Until Rails 5.0.0.beta2, the code above was working correctly.

If we upgrade our app to Rails 5.0.0.beta3 and **already have in our database** authorizations that do not belong to a partner, then the validation above will fail (see [attached gist](
https://gist.github.com/claudiob/e453503c47074bab1617)).

---

##### Impact of this issue

Although this issue is reproducible, it affects only a specific case where you already have in your database some records that are "valid" according to 5.0.0.beta2 and "invalid" according to 5.0.0.beta3.

The current behavior of 5.0.0.beta3 (and master) is in line with the desire of having `belongs_to` required by default. This issue would only affect people who are upgrading apps where they are validating an associated polymorphic field and do not have that association in the database (since it was not required until 5.0.0.beta2).

Therefore, I'm okay if we decide that this issue should not be fixed, but in that case it should be clearly documented in the upgrade notes of Rails.

---

##### Cause of this issue

I used `git bisect` and I think the culprit commit is https://github.com/rails/rails/commit/6f15b276cb69ae1241e5c021fdc8e73fd3fe1197.

**Comment by dhh** [comment]
cc @eileencodes

**Comment by claudiob** [comment]
> Therefore, I'm okay if we decide that this issue should not be fixed, but in that case it should be clearly documented in the upgrade notes of Rails.

What I meant by this is that we have to warn users that they have to add `optional: true` if the scenario above applies to them. In other words, the following code would work:

```ruby
class Authorization < ActiveRecord::Base
  validates :authority_id, :authority_type, presence: true
  belongs_to :authority, polymorphic: true
  belongs_to :partner, foreign_key: 'authority_id', class_name: 'Authorization', optional: true
end
```

**Comment by eileencodes** [comment]
I've already reverted that commit on master because of another bug. It should be in beta3.

**Comment by claudiob** [comment]
@eileencodes I saw that, so maybe my `git bisect` was wrong because this issue happen on beta3 and not on beta2

**Comment by claudiob** [comment]
I'll try to bisect again…

**Comment by eileencodes** [comment]
Oh ... I think I might have reverted too much.

**Comment by claudiob** [comment]
:sweat_smile:

**Comment by eileencodes** [comment]
No I didn't revert too much but the revert broke this. I don't know what to do because adding it back causes a whole host of bugs. :cry:

**Comment by claudiob** [comment]
I wonder how many people will be affected by this convoluted case.

If it's not too many, we could leave it and add documentation to the upgrade guides and to the "belongs_to required by default" option.

**Comment by eileencodes** [comment]
The bug in this issue was something like 5 years old. Last year someone reported it (https://github.com/rails/rails/issues/17621) and I worked with Aaron to fix it by checking if records were `!record.persisted? || record.changed? || record.marked_for_destruction?` and not validating unless `should_validate?` was true.

This unfortunately broke the `valid?` check and `invalid?` check because of the persistence check in the `should_validate?` method. Adding it back would mean `valid?` on a persisted record does not actually check validation. That's why I reverted it because we couldn't see an easy way to fixing it and didn't want it to block RC.

Because it never ended up in any stable version of Rails none of the bugs were reported until beta 2.

**Comment by claudiob** [comment]
Right… I agree with you. We could leave things as they are now, release RC1 with documentation, and just include this special case in the list of issues caused by that original bug.

**Comment by eileencodes** [comment]
I was explaining for anyone else who comes past this bug.

I'll look at this this weekend and see if it affects our app and if anything can be done to fix the bug and not break `valid?`. Thanks for the solid :bug: report @claudiob :)

**Comment by eileencodes** [comment]
Ok we should leave things as they are now and add documentation. I've been looking at this bug and it's correct behavior. The association is invalid. The previous behavior was incorrect behavior because `valid?` wasn't correctly checking. Since you never tell it not to validate the record asking `valid?` correctly returns not valid in Rails 5 beta3. The behavior in Rails 5 beta2 was incorrect and shows `valid?` was broken.

We should however update the documentation to match. @claudiob do you want to do that since you found the behavior change? Let me know :smile:

**Comment by eileencodes** [comment]
I don't really see a good place to add more documentation for this. The default required is only present in new applications. Upgraded applications don't get the `Rails.application.config.active_record.belongs_to_required_by_default = true` initializer. It's already in the release notes. It doesn't make sense to add it to the upgrade guide because it's not a required step in upgrading.

There's documentation and it's in the changelog. This was an issue because you happened to already be on 5.0, but the behavior was incorrect. If you have an idea of where to add this let me know. I'm closing for now :smile:

**Comment by claudiob** [comment]
Thanks for the solid counter-report, agent Eileen!! :cop: :laughing:

**Comment by bl4ckdu5t** [comment]
I think I understood that this required `belongs_to` validation was added to tackle some existing bugs. But for anyone else seeing this it's not just for polymorphic associations but every field that has a `belongs_to` in the model. I'm glad it has a configuration to save me from having to add `optional: true` for everything

**Comment by onlyyouandty** [comment]
That's valid @bl4ckdu5t thanks for the report @claudiob and @eileencodes
