### ISSUE TITLE
Rails 5 polymorphic associations not saving

### ISSUE THREAD

**Issue by petermumford** [rails/rails#23960]
Hello. I am trying to create a polymorphic association with a has_many :through for categories.

### Steps to reproduce
I have created two very simple repositories one with **[Rails 5.0.0.beta3](https://github.com/petermumford/testpoly5)** and the other using **[Rails 4.1.13](https://github.com/petermumford/testpoly)**, **which works as expected**. 

### Expected behavior
When you create an event with multiple categories selected it should create the association between the event and category on the categorisations model.

### Actual behavior
However, when saving the event with multiple categories selected I get the following error: `@messages={:categorisations=>["is invalid"]}` when using Rails **5.0.0.beta3**

Below is the output when debugging from _byebug_:

`(byebug) event_params
<ActionController::Parameters {"name"=>"Test", "location"=>"london", "category_ids"=>["", "1", "2"]} permitted: true>`

`(byebug) @event
#<Event id: nil, name: "Test", location: "london", created_at: nil, updated_at: nil>`

`(byebug) @event.categorisations
#<ActiveRecord::Associations::CollectionProxy [#<Categorisation id: nil, category_id: 1, categorisable_type: "Event", categorisable_id: nil, created_at: nil, updated_at: nil>, #<Categorisation id: nil, category_id: 2, categorisable_type: "Event", categorisable_id: nil, created_at: nil, updated_at: nil>]>`

`(byebug) @event.categories
#<ActiveRecord::Associations::CollectionProxy [#<Category id: 1, name: "Category 1", created_at: "2016-02-28 21:51:16", updated_at: "2016-02-28 21:51:16">, #<Category id: 2, name: "Category 2", created_at: "2016-02-28 21:51:24", updated_at: "2016-02-28 21:51:24">]>`

`(byebug) @event.valid?
false`

`(byebug) @event.errors
#<ActiveModel::Errors:0x007fa113eda628 @base=#<Event id: nil, name: "Test", location: "london", created_at: nil, updated_at: nil>, @messages={:categorisations=>["is invalid"]}, @details={:categorisations=>[{:error=>:invalid}, {:error=>:invalid}]}>`

### System configuration
**Rails version**: 5.0.0.beta3
**Ruby version**: 2.2.3

**Comment by eileencodes** [comment]
Hi @petermumford, thanks for the report! In Rails 5 belongs_to is required by default so if you add `optional: true` to your belongs to does the test pass? Technically this is correct behavior because the record is not valid because it's required by default. There was a change I made to validations where this would have been returning `valid?` as true but that was incorrect behavior and I reverted it between beta2 and beta3 . 

I believe this is the same issue as here; https://github.com/rails/rails/issues/23911

**Comment by petermumford** [comment]
Hi @eileencodes. I've added optional to my `belongs_to` association and now it works. So my model looks like this now:

> class Categorisation < ApplicationRecord
  belongs_to :category
  belongs_to :categorisable, polymorphic: true, optional: true
end

Thank you. What is the correct way of doing this now then? Do you have this documented anywhere, appreciate this is still new but thought I'd ask just in case.

**Comment by eileencodes** [comment]
Yup @petermumford that's the correct way. I'm going to update the documentation. Sorry for the confusion! 

To get the old Rails 4.1 behavior you can change this line to `false` in your app. https://github.com/petermumford/testpoly5/blob/master/config/initializers/active_record_belongs_to_required_by_default.rb#L6

The reason you're seeing the error on categorizations and not category is because your category isn't nil, but your categorizations are. So when you ask if it's `valid?` it's false.

**Comment by eileencodes** [comment]
I closed because there's another open issue to fix the documentation so we don't need two :smile:

**Comment by petermumford** [comment]
That's great. Fully understand, thank you.

**Comment by acrolink** [comment]
Thank you very much @eileencodes

**Comment by JarLowrey** [comment]
So I'm trying to create a `has_one address, as: :addressable` (in Event) but am [running into issues](https://stackoverflow.com/questions/44865191/polymorphic-associaton-transaction-fails-in-rails-5/44866913?noredirect=1#comment76754572_44866913). I believe it is because the event/address is not created yet in the nested form, and causes a validation issue. Adding `optional: true` to Address allows the form to save, but then what's the point of the optional? This relationship is not optional, every event should have an address, but that seems to be the only way I can get this new behavior to work.
