### ISSUE TITLE
remove js_compressor and css_compressor in production.rb made precompile quickly.

### ISSUE THREAD

**Issue by TangMonk** [rails/rails#24058]
I am trying to precompile assets in production, It very slowly in production, But quickly on development.

So I try to remove this lines in production.rb

```
# Compress JavaScripts and CSS.
config.assets.js_compressor = :uglifier
config.assets.css_compressor = :sass
```

It made compile faster than development, Why?

using 4.2.4 Rails

**Comment by sikachu** [comment]
By "compile" do you mean running `rake assets:precompile`?

IIRC `rake assets:precompile` switches your environment to `production` when you runs it. It's doing that so it can take production assets setting into account.

It's possible that your production environment compiles the asset slower just because of the resource and platform difference.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
