### ISSUE TITLE
has_one :inverse association not updated in time on create, :after_save callbacks have stale instance

### ISSUE THREAD

**Issue by dzajic** [rails/rails#24112]
### Steps to reproduce

```
class Foo < ActiveRecord::Base
  has_one :bar, inverse_of: :foo
end

class Bar < ActiveRecord::Base
  belongs_to :foo, inverse_of: :bar
  after_save "raise 'self and foo.bar are not the same object' unless equal?(foo.bar)"
end

foo = Foo.create; foo.create_bar # raises exception
foo = Foo.create; bar = foo.build_bar; bar.save # doesn't raise exception
```

### Expected behavior
Lines 73 and 74 in activerecord/associations/singular_association.rb should be reversed so the association should is set *before* calling save, to ensure :after_save callbacks have the right instance.

### Actual behavior
Association is set after calling save, so :after_save callbacks have a stale instance.

### System configuration
**Rails version**: 4.2.4.5

**Ruby version**:
2.2.4p230

**Comment by maclover7** [comment]
Is this reproducible on master?

**Comment by maletor** [comment]
[It seems that way](https://gist.github.com/maletor/677d1cc0b1086c5bd1ba).

**Comment by sgrif** [comment]
You've got it backwards. `bar = foo.build_bar; bar.save` is not the same as `foo.create_bar`. And in your example, the problem isn't that `Foo` has the wrong instance of `Bar`, but that `bar.foo` returns `nil`. This is the expected behavior, as the association is never set the other way around until after saving, as it needs to know the id to work properly, and potentially has side effects when replacing an existing associated record. This cannot take place before the call to `save`, as we need to know if it was successful in order to continue (which includes executing callbacks).

**Comment by dzajic** [comment]
@sgrif Thanks for the reply. AFAICT, in my steps to reproduce, both `self` and `foo.bar` are Bar instances, but have different `object_id`s. Also, this is adding to the confusion: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/singular_association.rb#L37
```
def build(attributes = {})
        record = build_record(attributes)
        yield(record) if block_given?
        set_new_record(record)
        record
      end
```
Here the record is being built and the association is updated before saving.

**Comment by sgrif** [comment]
Correct. And you will see that the behavior is very different after calling `save` as a result of that fact.

**Comment by dzajic** [comment]
Yeah, that's what we ended up doing as a workaround. It's still surprising to me. At least anyone that runs into this in the future may find this issues and get an explanation. Thanks again.
