### ISSUE TITLE
ActiveSupport::TimeWithZone converts to date wrongly

### ISSUE THREAD

**Issue by kritik** [rails/rails#24118]
### Steps to reproduce
Time.zone.parse("Mon, 18 Jul 0016 00:00:00 UTC +00:00").class #=> ActiveSupport::TimeWithZone
Time.zone.parse("Mon, 18 Jul 0016 00:00:00 UTC +00:00") #=> Mon, 18 Jul 0016 00:00:00 UTC +00:00
Time.zone.parse("Mon, 18 Jul 0016 00:00:00 UTC +00:00").to_date #=> Mon, 20 Jul 0016
Time.zone.parse("18 Jul 0016 00:00:00 UTC +00:00").to_date  #=> Mon, 20 Jul 0016

### But if year is normal, then
Time.zone.parse("Mon, 18 Jul 2016 00:00:00 UTC +00:00").to_date #=> Mon, 18 Jul 2016

**Comment by basvijzendoorn** [comment]
Reproduced the issue. I would like to work on it.

**Comment by rafaelfranca** [comment]
I think this is not an issue. I believe there were some changes in the calendars that add offsets to these dates.

@pixeltrix do you remember something about this?

**Comment by rafaelfranca** [comment]
Yeah. I think it is because before 1582 it is using the Julian calendar and when you call `to_date` we always use the Gregorian calendar.

**Comment by kritik** [comment]
The bad thing is that this time is saved in db and it's ok there. When I load model and get date I get this problem. So, I think this is an issue as you couldn't predict this behavior.

**Comment by pixeltrix** [comment]
@kritik as @rafaelfranca says it's because it's being converted between a proleptic Gregorian calendar and the Julian calendar when you do `to_date`. Unfortunately historical dates are complicated and how you handle them tend to be app specific so I don't think we should change how this is done in Rails since we'd be changing it from how Ruby itself behaves.

Interestingly I appear to have discovered a bug in Ruby - if you use `to_datetime` first before doing `to_date` then it doesn't transform the date because of [this line][1]. It should be doing what [this line][2] is doing - setting the instance to being in the gregorian calendar and then changing it to the default calendar reform date (that's done by `set_sg` in those methods). I'll have to write a PR to change this so don't rely on it. :smile:

[1]: https://github.com/ruby/ruby/blob/08753137deb7f1f5349f4cade146251a6106c521/ext/date/date_core.c#L8501
[2]: https://github.com/ruby/ruby/blob/08753137deb7f1f5349f4cade146251a6106c521/ext/date/date_core.c#L8461
