### ISSUE TITLE
Numericality validator error messages do not respect localized number formatting

### ISSUE THREAD

**Issue by nathansamson** [rails/rails#24154]
### Steps to reproduce

* Set language to dutch (or any language where the decimal seperator is , and the thousands separator is .)
* Add a model / form with a floating value
* Add a numericality validator with a greater_than value being a floating number
* Enter form value with a value lower than the greater than value

(https://gist.github.com/nathansamson/772352d021b2d301dd48)

### Expected behavior
* The error message should respect the localized number formatting

### Actual behavior
* Is displaying the normal/ruby display of the number

### System configuration
**Rails version**: 4.2.6, but observed in all earlier versions as well

**Ruby version**: 2.3 but observer in any ruby version

**Comment by sgrif** [comment]
Unfortunately, there's no way to fix this in a backwards compatible way. Number formatting is a feature of Rails' view helpers, not I18n. The only way we could give you your expected behavior would be to pass everything through `ActiveSupport::NumberHelpers.number_to_delimited` before calling `I18n.translate`, but that would be a breaking change to anybody using format specifiers in their error messages.

To be clear what I mean, the following code works:

```ruby
I18n.backend.store_translations(:en, foo: "%<bar>.d")
I18n.translate(:foo, bar: 123.4)
```

But any fix for this issue would require at minimum doing the equivalent of

```ruby
I18n.translate(:foo, bar: "123.4")
```

which would result in an error. You may be able to work around this using some combination of sprintf format options.
