### ISSUE TITLE
The v2.3 link on RailsGuides redirects to edgeguides

### ISSUE THREAD

**Issue by koenpunt** [rails/rails#24236]
### Steps to reproduce

Visit this link http://guides.rubyonrails.org/v2.3/ 

### Expected behavior

It displays the guides for Rails 2.3

### Actual behavior

It redirects to http://edgeguides.rubyonrails.org/

**Comment by maclover7** [comment]
cc @fxn

**Comment by Gaurav2728** [comment]
@maclover7 @koenpunt  May be prior to Rails 3.0 `http://guides.rubyonrails.org/` is not available (maintain) currently.

**Comment by koenpunt** [comment]
Not entirely, http://guides.rubyonrails.org/v2.3.11/ does work

**Comment by Gaurav2728** [comment]
@koenpunt  you can use http://guides.rubyonrails.org/v2.3.8/

**Comment by sikachu** [comment]
We redirects all 404s to `edgeguide` because we _assumes_ that those ones that aren't available are available in newer versions, and we stopped building guides/docs for the old version.

@fxn maybe we should add more rewrite rules to redirect 2.3.* and 3.0.* to the latest known version in those majors.

**Comment by fxn** [comment]
I have manually generated the guides for v2.3.17, and API and guides for the last v2.3.18. The convenience v2.3 points to v2.3.18.

Thanks to my knowledge of applied software archeology I have managed to do so installing Ruby 1.8, with Rake 0.8.7, and a bunch of other things.

If OSS earns points in some heaven, I've certainly got some extra bonus today.
