### ISSUE TITLE
Adding an engine to API rails app results in engine routes behaving like API routes

### ISSUE THREAD

**Issue by ivanjolic95** [rails/rails#24264]
### Steps to reproduce

When I add engine to API rails application, routes in the engine are messed up.

### Expected behavior
Shouldn't it be possible to use engines as regular apps even when their parent app is in API mode? I want to add an engine that behaves like a regular rails app.

### Actual behavior
When I use `resources` in the `config/routes.rb` of the engine it doesn't generate routes for `new` and `edit` actions. Also when I try to save a record it raises `ActionController::InvalidAuthenticityToken`. And it throws errors in json format.

### System configuration
**Rails version**: 5.0.0.beta3

**Comment by prathamesh-sonpatki** [comment]
@ivanjolic95 Can you upload a sample app on Github to reproduce the issue?

**Comment by TikiTDO** [comment]
I tried to reproduce the routing error [here](https://github.com/TikiTDO/rails_issue_24264) but could not do so.

**Comment by rafaelfranca** [comment]
@ivanjolic95 ping. Do you have any more information to us? Could you create the sample application?

**Comment by jeremy** [comment]
Is this blocking 5.0.0 release candidate? Is it blocking beta4?

**Comment by vipulnsward** [comment]
Related: https://github.com/rails/rails/pull/24654

**Comment by spastorino** [comment]
@jeremy I'd block the release candidate, I will fix this during RailsConf :).

**Comment by jeremy** [comment]
Desirable for RC, but needn't block. Let's give it our best shot :)

**Comment by spastorino** [comment]
OK, now re-reading the issue this is expected behavior. API-only modes is application wide. There's no way with our current solution to support this.

We should state this in a more clear way in the guides. Please if you want to help us a bit go ahead and add some documentation to explain this.

The most important reason is that we do not have a way to differentiate middleware stacks per set of controllers, that's only possible to do per app.

So you could use two separate applications to accomplish what you want to do.
