### ISSUE TITLE
Curves singular is wrong

### ISSUE THREAD

**Issue by tdeo** [rails/rails#24270]
I think that curves should be added to the list of irregulars in [inflections.rb](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb), but the comment at the beginning of the file says that rules are frozen, and I'm not sure whether rules refers only to the regexp based rules or everything.  

### Expected behavior

`'curves'` singular should be `'curve'`

### Actual behavior
```
Loading development environment (Rails 4.2.3)
irb(main):001:0> 'curve'.pluralize
=> "curves"
irb(main):002:0> 'curve'.pluralize.singularize
=> "curf"
```

### System configuration
**Rails version**: 4.2.3

**Ruby version**: 2.2.4p230

**Comment by prathamesh-sonpatki** [comment]
@tdeo The inflector is frozen, for backwards compatibility.

You can define a custom inflection in config/initializers/inflections.rb as per the application needs.

**Comment by BookOfGreg** [comment]
Please can we break backward compatibility in Rails 6 for this?

Or even better, have all the old defaults expressed in the `inflections.rb` uncommented.

Just had a whole host of fun due to `drives => drife`. It would be better to either attempt to catch all or nothing at all than permanent partial inconsistent support.

**Comment by benreyn** [comment]
Im curious about this as well. A colleague recently ran into this with `drives => drife`. Is there reason that this fix cant be upstreamed?
