### ISSUE TITLE
(Rails 4.1.15) Unexpected `.constantize` behavior

### ISSUE THREAD

**Issue by iandonovan** [rails/rails#24347]
### Steps to reproduce
I have a model, `Pod`, that looks like this:

```ruby
class Pod < ActiveRecord::Base
 # . . . 
end
```

And it has a child, `Pod::Default`, that looks like this:

```ruby
class Pod::Default < Pod
  # . . .
end
```

I don't _think_ the background details on this are important -- please let me know if I'm wrong! -- but when I call `"Pod::Default".constantize`, it returns `ActiveRecord::Scoping::Default`.

### Expected behavior
`"Pod::Default".constantize` should return `Pod::Default`.

### Actual behavior
Instead, `"Pod::Default".constantize` returns `ActiveRecord::Scoping::Default`.

### System configuration
**Rails version**: 4.1.15

**Ruby version**: 2.1.2, via rvm.

I have a feeling this is a bug in my app, so I'm mostly asking for clarification as to what's going on here. :)

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by tejasbubane** [comment]
Here is a small script I wrote trying to reproduce this issue:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '4.1.15'
end

require 'active_record'
require 'active_support'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)


class Pod < ActiveRecord::Base
end

class Pod::Default < Pod
end

class BugTest < Minitest::Test
  def test_class_name
    assert_equal "Pod::Default", Pod::Default.to_s
  end

  def test_constantize
    assert_equal Pod::Default, "Pod::Default".constantize
  end
end
```
The test here pass and there seems to be no issue. 

But a strange thing happened when I created a new rails app with these models (`app/models/pod.rb` and `app/models/pod/default.rb`). In the rails console I see this:

```
⇒  bin/rails c
Loading development environment (Rails 4.1.15)
2.3.0 :001 > Pod::Default
 => ActiveRecord::Scoping::Default
2.3.0 :002 >
```

Looks like some Rails autoload thing.

**Comment by maclover7** [comment]
cc @fxn - I feel like this has something to do with how ActiveSupport loads in Ruby classes.

**Comment by fxn** [comment]
Yep.

The module `ActiveRecord::Scoping` is an ancestor of AR models:

```
Post.ancestors.map(&:name).grep(/Scoping$/)
# => ["ActiveRecord::Scoping"]
```

When Ruby resolves `Post::Default` it first checks if the class `Post` has a constant called `Default` (1). If not found, it walks up the ancestor chain of `Post` looking for a `Default` constant in each ancestor. That lookup succeeds because the module `ActiveRecord::Scoping` is an ancestor of `Post` that has a `Default` constant. Ruby resolves `Post::Default` as `ActiveRecord::Scoping::Default`.

Therefore, Rails autoloading doesn't get a chance, because the constant is not missing. Rails autoloading is triggered when a constant is missing (via `const_missing`).

If the application's `Post::Default` was known at that time this wouldn't happen, because Ruby would find it in the check (1) above. A possible workaround is to make sure the file is loaded with `require_relative 'post/default'` in a place that is executed before that `constantize` call happens.

**Comment by iandonovan** [comment]
Thank you! Appreciate the help.

**Comment by matrinox** [comment]
Hi, I have a similar problem with `constantize`. @fxn explanation seems to make sense for your case so perhaps mine is a separate issue. Can you guys take a look at it and see if there's another solution to it? https://github.com/rails/rails/pull/29773
