### ISSUE TITLE
remove_index fails to find expression index on postgresql

### ISSUE THREAD

**Issue by glebm** [rails/rails#24359]
### Steps to reproduce

```ruby
require 'bundler/setup'
require 'active_record'
ActiveRecord::Base.establish_connection("postgres://postgres@localhost:5432/test")
ActiveRecord::Base.connection.tap do |conn|
  conn.create_table(:a_table) { |t| t.text :a_column }
  conn.exec_query 'CREATE INDEX expr_index ON a_table (LOWER(a_column))'
  conn.remove_index :a_table, name: :expr_index
end
```
### Expected behavior
The index should be removed. Works correctly in Rails 4.1 and 4.2, but not Rails 5.

### Actual behavior

```
ArgumentError:
  No indexes found on a_table with the options provided.
```

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: MRI 2.3.0

**Comment by vsorlov** [comment]
confirm error
`ActiveRecord::Base.connection.indexes(:a_table)` returns empty array after that index is added, but if I try to add the index one more time, it fails with `PG::DuplicateTable: ERROR:  relation "expr_index" already exists`. Maybe there is a problem in `#indexes` method, I'm trying to understand.

**Comment by vsorlov** [comment]
hm, this is 'expression' index and indkey for that index is 0 in pg_index
and `#indexes` method returns only column indexes https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L198
not sure when and how it was broken in rails 5, I'll investigate further

**Comment by meinac** [comment]
`indkey` is '0' because PostgreSQL stores it as '0' if it is an index which consist of an expression.

From the documentation about `indkey`: *This is an array of indnatts values that indicate which table columns this index indexes. For example a value of 1 3 would mean that the first and the third table columns make up the index key. A zero in this array indicates that the corresponding index attribute is an expression over the table columns, rather than a simple column reference.*

As far as I see, for expression indexes PostgreSQL stores expression as `pg_node_tree` in `indexprs` column. I had a look into documentation to get `varattno`(because this refers to `pg_attribute` table's `attnum` column) from the tree but couldn't manage it. Maybe the only way to make this work is running regex on it to get `varattno` and then asking `pg_attribute` table to attribute information with table oid and this value. :disappointed:

**Comment by vsorlov** [comment]
it was broken in Rails 5 after `remove_index` method was added to postgresql adapter https://github.com/rails/rails/commit/ce17e232a12861bce4bd950d7143df3fe0cd1991#diff-6e377cf054cb4121e6f207bd7c14b492R450
it uses `index_name_for_remove` and it was changed to use `indexes` method here https://github.com/rails/rails/commit/8ceb883b0630e0d010fbef0c621cc9690b0bcad6#diff-a0775e1ec64264dc76a8ee71a5211ae3R1148
so it seems the bug was in `indexes` method before, but it was revealed in rails 5

**Comment by vsorlov** [comment]
this is the change after which `indexes` postgresql adapter method started to return only column indexes https://github.com/rails/rails/commit/4464d10e68045e6723d4eb62734213c4296ef339?diff=unified#diff-cc31fc1dd1e78db64638200f710b2f59R626
why is it bad for dump to include full text indexes?

**Comment by vsorlov** [comment]
I'm actually not sure that `remove_index` needs to support removing indexes, that were not created with `add_index` method, but with custom sql query.
To support it we can return these indexes in `ActiveRecord::ConnectionAdapters::PostgreSQL::SchemaStatements#indexes`, but make sure they are not included in schema dump.
I can create a PR if someone from Rails team advice.

**Comment by glebm** [comment]
Here is some context on how this issue came up. I was writing a gem that works with different databases, and handles index creation but leaves index removal up to Rails. Because of this issue I had to add [special handling](https://github.com/thredded/db_text_search/blob/a3b1f223f8193017a67c5811c6bb6d27651a7b70/spec/db_text_search/case_insensitive_eq_spec.rb#L28) for Rails 5. Hopefully this is a compelling use case to support fixing this regression.

**Comment by vsorlov** [comment]
@glebm, yes, this needs to be fixed, rails 5 should not break backward compatibility

**Comment by vsorlov** [comment]
so I see two possible solutions:
1) change `ActiveRecord::ConnectionAdapters::PostgreSQL::SchemaStatements#indexes` to return all indexes and make sure expression indexes are not included in a dump. this breaks `#indexes` previous behavior.
2) add parameter to `#indexes` method with which that method will return all indexes. use that parameter in `index_name_for_remove`

**Comment by glebm** [comment]
When the name is specified explicitly, why does Rails need to fetch the indexes before deletion?

**Comment by sevaorlov** [comment]
@glebm, hm, actually the only benefit of it is that `ArgumentError` is raised instead of `ActiveRecord::StatementInvalid`
Indexes need to be fetched only when `columns` parameter is specified.

**Comment by glebm** [comment]
@sevaorlov Doesn't seem like a big deal. Rails doesn't do this for other statements, e.g. `create_table` fails with `StatementInvalid` when a table already exists IIRC.

**Comment by sevaorlov** [comment]
connected with https://github.com/rails/rails/issues/21765
and also there are two PRs https://github.com/rails/rails/pull/21819 and https://github.com/rails/rails/pull/23393

so this issue will be fixed if https://github.com/rails/rails/issues/21765 is implemented. but anyway `remove_index` can be optimized to remove index without fetching all the indexes if name is specified.

**Comment by arthurnn** [comment]
> but anyway remove_index can be optimized to remove index without fetching all the indexes if name is specified.

I think thats a good solution to unblock the 5.0.0 release. 

@sevaorlov Do you want to create a PR, to change `remove_index` to the old `DROP` statement, and if it fails it will just raise the good/old `StatementInvalid`.

Thanks

**Comment by sevaorlov** [comment]
@arthurnn, sure, I'll create a PR

**Comment by jeremy** [comment]
#24507

**Comment by kolisayeed** [comment]
openproject run rails db:migrate:redo VERSION=20180122135443

== 20180122135443 AddTsvColumnsToAttachments: reverting =======================
-- remove_index(:attachments, {:column=>:file_tsv})
rails aborted!
**StandardError: An error has occurred, this and all later migrations canceled:**

**No indexes found on attachments with the options provided.**
/opt/openproject/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1236:in `index_name_for_remove'
/opt/openproject/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:502:in `remove_index'


I installed openproject via atp-get.
