### ISSUE TITLE
ActiveRecord::Type module bleeds into ActiveRecord::Base

### ISSUE THREAD

**Issue by kenaniah** [rails/rails#24428]
It appears as though the `ActiveRecord::Type` module has been included in `ActiveRecord::Base`. 

```ruby
class Foo < ActiveRecord::Base
end

Foo::Type # should raise a name error, currently resolves to ActiveRecord::Type
```

This causes an autoloading issue when trying to use namespaced models, as models with a class name of `Type` will need to first be required in the parent model before they are referenced.

**Comment by kenaniah** [comment]
This issue exists in the `4-2-stable` branch, but appears to be fixed in `master`

**Comment by rafaelfranca** [comment]
cc @fxn

**Comment by fxn** [comment]
It's kind of a gray area, because generally speaking the ancestor chain of AR::Base is not a public contract. The API is, where is stuff actually implemented is not.

So, the ancestor chain may change, AR internals may be reorganized. Problem is code organization in modules and constant name resolution are coupled in Ruby, so there is a private part of your design that has a global consequence.

You need to pick some names, and any choice may conflict with existing code unfortunately.

I don't know of a good solution to this issue, it has always looked like an unavoidable gotcha unless AR starts using some funky/non-idiomatic naming internally. For Rails 5, at least, guess your app can no longer rely on autoloading for that one.

**Comment by sgrif** [comment]
For the record, this is intentional behavior. `ActiveRecord::Type` is part of the public API, and is intended to be referenced as just `Type` inside of AR classes. `Type` is a reserved word elsewhere in Active Record. As was mentioned by others, this is a gray area API-wise. In this case I don't think there's any action to be taken.
