### ISSUE TITLE
Rails destroy does not remove routes previously included

### ISSUE THREAD

**Issue by EdDeAlmeidaJr** [rails/rails#24437]
Assume I created a Welcome controller with just one method using 
**$ rails g controller Welcome index**

This will create in my config/routes.rb a route
**get 'welcome/index'**

Then I changed my mind and decided to remove this Welcome controller with 
**$ rails destroy controller Welcome**

It removes the controller and other files, but the route is still there. 

As I see things, rails destroy should restore the state previous to the creation of the controller, including the route to its methods.

I'm using Rails 4.2.6 with Ruby 2.3.0

**Comment by maclover7** [comment]
Can you check and see if this appears on Rails master, too?

**Comment by EdDeAlmeidaJr** [comment]
I'll try and report here, @maclover7.

**Comment by vipulnsward** [comment]
It does exist no master.

**Comment by EdDeAlmeidaJr** [comment]
Yes, it is the same on master.

**Comment by vipulnsward** [comment]
So the issue is that you are creating with 
> rails generate controller Welcome index

and removing with
> rails destroy controller Welcome

If you try with 
> rails destroy controller Welcome index

this will work as expected.

`rails destroy controller Welcome` has a different meaning, similar to how `rails generate controller Welcome` is different from `rails generate controller Welcome index`, in that they create a different route.

@EdDeAlmeidaJr Thanks for reporting, going to close as its not an issue.

**Comment by EdDeAlmeidaJr** [comment]
Okay, I got it. But I still ask myself what is the meaning, semantically, of destroying a controller without destroying all the routes associated with it.
