### ISSUE TITLE
Rails 4.2.6 - has_many through, undefined method 'name' do nil:NilClass (ruby 2.3.0, fails only on production)

### ISSUE THREAD

**Issue by kryna** [rails/rails#24480]
I have prototype model

``` ruby
class ArchMagazine::Prototype < ActiveRecord::Base
  self.table_name = 'arch_magazine_prototypes'

  has_many :custom_dictionaries, through: :dictionaries_prototypes, source: :custom_dictionary, foreign_key: :custom_dictionary_id
  has_many :dictionaries_prototypes, -> { where(kind: 'normal') }, dependent: :destroy, class_name: 'ArchMagazine::DictionariesPrototype'
end
```

and service

``` ruby
class ArchMagazine::UpdatePrototype < ArchMagazine::PrototypeCore

  def process
    if prototype_form.valid?
      prototype.update(prototype_form.prototype_attrs)
      add_custom_dictionaries(prototype, true)
    else
      raise ValidationError.new
    end
  end

  def add_custom_dictionaries(prototype, with_destroy = false)
    prototype.custom_dictionaries.destroy_all if with_destroy
    prototype_form.custom_dictionary_ids.present? and prototype_form.custom_dictionary_ids.each do |dictionary_id|
      create_record(prototype, dictionary_id, 'normal')
    end
  end

end
```

When I'm trying to update prototype object (creating works fine) with some new custom_dictionaries_ids, application fails at 

``` ruby
prototype.custom_dictionaries.destroy_all if with_destroy
```

Error link (not exactly mine but same active_record error): http://pastebin.com/TZugtfrd 

Funny thing is that code from my example works on development just fine. **Production** is the problem. Some time before, **development** would run on **ruby 2.0.0-p195**, **rails 4.0.4** and everything were fine. Then I updated **ruby** version on **production** to **2.3** and applications started to fail. Situation repeats itself on **development** when I updated **ruby** on this environment. After that I updated **rails** on **development** to **4.2.6** and everything started to run smoothly. But nothing changes on **production** after deploying updated **rails** line in **Gemfile**.

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by al2o3cr** [comment]
@kryna That stack trace specifically relates to a model with an association that uses `counter_cache`. If your models use that feature, please include the relevant code. It's hard to say what the issue might be otherwise, as there are many things that have `name` methods that could be `nil`.

Likely unrelated but good style: `foreign_key` is ignored on `through` associations - that option is extracted from the association specified as `source`. Also, there are occasional weird bugs caused by declaring a `through` association prior to the association it goes `through` - swapping the order of `custom_dictionaries` and `dictionaries_prototypes` will prevent that, although I do not believe it's a cause of the behavior you're experiencing.
