### ISSUE TITLE
Date.today.in_time_zone does not appear to work

### ISSUE THREAD

**Issue by roberts1000** [rails/rails#24513]
### Steps to reproduce

Let's play around with time zones.  I ran into an unexpected conversion (I'm writing this issue around 7:40pm Eastern time on a Monday): 

1. The time zone on my computer is "Eastern Time (US & Canada)".
2. Set the Time.zone = "Fiji"
3. Let's see how Time behaves
  1. `Time.now`            =>  2016-04-11 19:40:33 -0400 **(This is correct)**
  2. `Time.current`          =>  Tue, 12 Apr 2016 11:43:01 FJT +12:00 **(This is correct)**
  3. `Time.now.in_time_zone` => Tue, 12 Apr 2016 11:40:38 FJT +12:00` **(This is correct)**
4. Now let's see how Date behaves
  1. `Date.today` => Mon, 11 Apr 2016 **(This is correct)**
  2. `Date.current` => Tue, 12 Apr 2016 **(This is correct)**
  3. `Time.zone.today` => Tue, 12 Apr 2016 **(This is correct)**
  4. `Date.today.in_time_zone` => Mon, 11 Apr 2016 00:00:00 FJT +12:00 **(Uh...)**
  5. `Date.today.in_time_zone("Fiji")` => Mon, 11 Apr 2016 00:00:00 FJT +12:00 **(Umm...)**

### Expected behavior
I expected `Date.today.in_time_zone` to be similar to `Time.now.in_time_zone`.

### Actual behavior
`Time.now.in_time_zone` correctly converts the system time into Fiji time and produced the correct date and time in the output string.   `Date.today.in_time_zone` however does not seem to be aware of the time zone and it looks like it returns the date based on the system (although it does show FJT +12:00 in the output so it's somewhat timezone aware).  It shows 'Monday' in the output which is correct for Eastern time, but not Fiji.

### System configuration
**Rails version**:
4.2.6

**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing? Also, can you see if this is occurring on master?

**Comment by al2o3cr** [comment]
These two computations return the same thing (on 2016-04-11 in PDT):
```ruby
  Date.today.in_time_zone # => Mon, 11 Apr 2016 00:00:00 FJT +12:00
  Date.parse('2016-04-11').in_time_zone # => Mon, 11 Apr 2016 00:00:00 FJT +12:00
```
To get the behavior you're expecting here they would need to return *different* values.

**Comment by roberts1000** [comment]
@al2o3cr Assuming we're talking about 2016-04-11, `Date.today` and `Date.parse('2016-04-11')` will each return an instance of Date for 2016-04-11.  Calling `in_time_zone` is going to do the exact same thing on both of those instances.  The output will be the same for both statements as long as today's date is passed to the `parse` method.  What am I missing?  Did you mean

```ruby
Date.today # => Mon, 11 Apr 2016
Date.parse('2016-04-11').in_time_zone # => Mon, 11 Apr 2016 00:00:00 FJT +12:00
```

I agree that whose two values should be different

@maclover7 I verified the problem exists on master.  I'll create a script as soon as I can; I'm not a MiniTest guy so I got some learn'n to do.

**Comment by tijwelch** [comment]
I believe this is how `Date.today.in_time_zone` is supposed to work since you're calling `in_time_zone` on a Date instance. 

The Date is converted to Time with `to_time` which sets the time to the beginning of the day.

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/date_and_time/zones.rb#L35

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/date/conversions.rb#L73

**Comment by vipulnsward** [comment]
_NOTE: I have changed my system time to match the time you mentioned in this issue_

If you do `Date.today.to_time` => "2016-04-11 00:00:00 -0400". As mentioned by @tijwelch it's stripping it of time value.
So essentially, you are calling `in_time_zone` on this value, and not calling on the one that includes time offset as well. So when you do 

`Date.today.in_time_zone`

it results in expected behaviour.

Since, `Time.now.in_time_zone` has the time offset, it would output as expected something like -`Tue, 12 Apr 2016 11:53:46 FJT +12:00`

Giving this a close, since this is expected behaviour. Thanks for reporting @roberts1000 !

**Comment by roberts1000** [comment]
It's not expected behavior.  It may be how the current implementation works, but as an end user, I expect `in_time_zone` to put me on the correct DAY regardless of whether or not it's called on a Date instance or Time instance.

**Comment by pixeltrix** [comment]
@roberts1000 that's why we have Date.current, DateTime.current and Time.current - they're timezone aware methods that don't mess with the behaviour of the standard Ruby methods.
