### ISSUE TITLE
merge! on hstore set dirty to changed even if no changes

### ISSUE THREAD

**Issue by fabien-michel** [rails/rails#24725]
### Steps to reproduce
Create a Model :
```ruby
class CreateAnimals < ActiveRecord::Migration
  def change
    enable_extension 'hstore'
    create_table :animals do |t|
      t.hstore :data
    end
  end
end
```

Code to test:
```ruby    

   h = {a:"1", b:"2"}

    puts "1. merge"

    animal = Animal.create!(data: h)
    animal.data = animal.data.merge h
    puts animal.changed? ? "changed" : "not changed"
    puts animal.changes.inspect

    puts "2. merge!"
    animal = Animal.create!(data: h)
    animal.data.merge! h
    puts animal.changed? ? "changed" : "not changed"
    puts animal.changes.inspect

# 1. merge
# not changed
# {}
# 2. merge!
# changed
# {"data"=>[{"a"=>"1", "b"=>"2"}, {"a"=>"1", "b"=>"2"}]}

```

### Expected behavior
In the second test (with merge!) the object shouldn't have been marked has changed (as merge do)

### Actual behavior
The object is marked has changed and changes prove that there is no changes

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.0
**Database**: postgres

**Comment by fabien-michel** [comment]
To complete the issue I can indicate that merge! in faster than merge : 
Code to try benchmark : https://gist.github.com/fabien-michel/202a5a9ae2ccb9f6889f55858f6806fc
```ruby
#        user     system      total        real
# merge  3.640000   0.020000   3.660000 (  3.728977)
# merge!  0.000000   0.000000   0.000000 (  0.005567)
```

**Comment by maclover7** [comment]
Can you edit your example, and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by vipulnsward** [comment]
https://gist.github.com/vipulnsward/35b161e16e03bd586d71ba47d222ae5d
Looking at this, looks like an issue with type cast behaviour. We change symbols to strings in hashes, hence this behaviour. Checking it out.

**Comment by maclover7** [comment]
I think I have a fix for this -- let me just add a test.

**Comment by sgrif** [comment]
So there is a bug here, but it's not where you'd think. The HStore type is working correctly. The field has changed. If you look at the value of the field, it is now `{ "a" => "1", "b" => "2", :a => "1", :b => "2" }`. `changes` should be reflecting the correct value of the field. I'm unsure why it isn't, and am digging into that now. But the bug is that the change isn't being displayed, not that the hstore type is doing the wrong thing

**Comment by sgrif** [comment]
I'm actually not sure we can do anything about this. `ActiveModel::Dirty#changes` returns a `HashWithIndifferentAccess`, which doesn't allow a normal hash to be placed inside of it. To fix this, we'd have to make a breaking change to either `HashWithIndifferentAccess` or `ActiveModel::Dirty#changes`, neither of which are tenable here.

Since this is a pretty major edge case, I'm just going to close as wontfix. We should be displaying the changes properly, but I don't see a path forward for that.
