### ISSUE TITLE
Array#sum is very slow

### ISSUE THREAD

**Issue by mrkn** [rails/rails#24804]
AS's Array#sum is much slower than core's implementation.

### Steps to reproduce

```
$ git rev-parse --short HEAD
a4b3c78
$ cat array_sum.rb
class Array
  alias core_sum sum
end

require 'benchmark/ips'
require 'active_support/core_ext/enumerable'

ary = [1.0] * 1_000_000

Benchmark.ips do |x|
  x.report("core sum") { ary.core_sum }
  x.report("AS's sum") { ary.sum }

   x.compare!
end
$ ruby -v -I lib array_sum.rb
ruby 2.4.0dev (2016-04-30 trunk 54853) [x86_64-darwin15]
Calculating -------------------------------------
            core sum    12.000  i/100ms
            AS's sum     2.000  i/100ms
-------------------------------------------------
            core sum    122.514  (± 8.2%) i/s -    612.000
            AS's sum     27.684  (±10.8%) i/s -    138.000

Comparison:
            core sum:      122.5 i/s
            AS's sum:       27.7 i/s - 4.43x slower
```

### Expected behavior

Ruby 2.4 has Array#sum, so AS's implementation should be as fast as core's implementation.

### Actual behavior

AS's implementation is about 4x slower than core's implementation.

### System configuration

**Rails version**: a4b3c78

**Ruby version**: ruby 2.4.0dev (2016-04-30 trunk 54853) [x86_64-darwin15]

**Comment by egilburg** [comment]
AFAIK it's a choice between performance and flexibility+backwards compatibleness, since AS `#sum` works on all enumerables, and on all arrays where each member responds to `:+` (e.g. Strings), while core `#sum` works only on integers/floats. Due to the nature of the problem, it's not even possible to have a core+fallback implementation, since that would require checking whether each item in the array is a number, which is slower than any benefit gained from core+fallback approach.

**Comment by jeremy** [comment]
#24805
