### ISSUE TITLE
`rails db:drop:all db:create:all db:migrate` w/ postgresql adapter runs db:migrate for production database 

### ISSUE THREAD

**Issue by ojab** [rails/rails#24813]
### Steps to reproduce

$ rails new --edge test_app -d postgresql
$ cd test_app
$ bundle exec rails db:drop:all db:create:all db:migrate ; echo '\d+' | rails dbconsole

> No relations found.
### Expected behavior

development DB is migrated
### Actual behavior

production DB is migrated

With sqlite3 adapter rails correctly migrates development DB.

**Comment by vipulnsward** [comment]
Are you seeing this is on master?

**Comment by ojab** [comment]
Yes, tested on master.

**Comment by vipulnsward** [comment]
Hmm, actually we don't migrate anything here. Let me see what causes this.

**Comment by vipulnsward** [comment]
So the issue here is that we have different handling of connections on PG adapter. When trying to run all of these in a single process, the schema is getting cached/non-standard on the connection, and is sometimes causing issues that the "users" table exists, etc. Will need to see how to uncache, and safely drop/create DB, till we reach here.

**Comment by IamNaN** [comment]
I'm seeing this in 5.1.0-alpha, only `rails db:drop:all` is dropping production three times, once for each environment configured.

**Comment by kamipo** [comment]
This is probably fixed by #32274.
