### ISSUE TITLE
Should the Raw template handler render HTML-safe strings by default?

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#24949]
This is related with https://github.com/rails/rails/pull/24929.

TL;DR;, in Rails 5 we changed the default template handler from ERB to Raw.

That means that `render 'foo.js'` where `foo.js` is not going through the ERB handler anymore but it is rendering HTML unsafe string.

At first it seems dangerous to mark raw templates as html safe but I can't see any problem that would be caused by this change that would not be caused by users blindly marking these render call as html safe.

cc @rails/security

**Comment by rosenfeld** [comment]
Maybe an option would be to provide a white list of extensions that should be considered html safe when using the raw handler, like .js and .htm(l), and allow the user to override that list.

**Comment by matthewd** [comment]
I don't understand why #24949 is true. @rosenfeld could you show some more context in the example template you gave?

**Comment by rosenfeld** [comment]
Hi @matthewd, sure. The discussion has started in the rails-core mailing list actually, but I can give more details here.

When you are supporting IE8 you don't have access to the new navigation timing and resources timing APIs, so a better guess involves measuring the initial time assigning the current date to some variable in the html header. This is often used by tools like NewRelic, Pingdom, Google Analytics (I guess, I never tried to understand their code to be sure) and so on, so sometimes we want to follow the vendor instructions and simply paste the JS snippet in a header inline script. NewRelic will inject the script using a middleware by default but other alternatives will indicate how the page should be changed.

You could add the complete HTML partial markup including the script tag in an ERB partial, but if you have a few of such scripts and want to put them all in the same script tag you might want to simply save them as separate JS files. This has the advantage of being able to highlight it accordingly in most editors since they would be plain JS and also you can build some kind of build system that would minify some custom JS and the view would then use the minified script as the partial.

Even though I don't have plain HTML partials myself, I can see where they would be useful when you want to use the same content to render common HTML in the server-side and in XHR requests.

I've pointed a few examples why someone might want to use plain JS or HTML documents as partials even though they shouldn't be handled by the ERB parser. But the original request seemed to be worried about processing plain JS as if it was ERB which could lead to wrong results if the JS happened to contain the `<% %>` anywhere in the code... But it didn't seem to be motivated by any security related issue.

Since my application was affected by that change, I thought that maybe it could affect other applications as well and maybe this change is not really necessary and Rails could avoid that in the migration path... Also, I could only detect this problem after deploying to my Cert environment since I conditionally render the Pingdom partial so that it doesn't get rendered in the development environment... There are some cases that it might be even trickier to detect the problem...

Please let me know if I didn't answer what you have asked for.

**Comment by spastorino** [comment]
@rafaelfranca why did you say "unsafe" HTML?. I don't see anything unsafe in rendering your own JavaScript files when they do not have user input.

**Comment by kevinskoglund** [comment]
I think it is acceptable for explicitly-declared Raw templates to be marked html_safe by default. The name "raw" indicates opting out of template processing, and it is fair for it to act like #raw() does.

The problem is that the default template handler is Raw now. I do not think it is a good idea for implicitly-selected Raw templates to be marked html_safe. It should be "secure by default".

Currently, if a file extension is accidentally omitted, a template will expose its unprocessed code. Here too, I think secure by default would be a better security choice.

Could the default template handler be changed to render nothing or to render a message about missing the handler? This would secure the default state and allow setting html_safe on all templates explicitly-declared as Raw.

**Comment by sgrif** [comment]
On principle it doesn't seem like the raw handler should mark things as html safe by default, but really neither should the erb handler (since ERB doesn't actually imply HTML content). I think it's better to be consistent in this case though. I could see an annoyance if you actually have text content containing the right characters for the browser to lose them, but that annoyance would already be present here. I can't see any way this would cause a security issue.

**Comment by connorshea** [comment]
Should a warning be included in the Release Notes? That's the best solution I see here.

I agree with the above, if the user is relying on the `render` method to sanitize input, where there's no indication that it would sanitize things, that's their own fault.

**Comment by eileencodes** [comment]
Closed by https://github.com/rails/rails/commit/1de0df86695f8fa2eeae6b8b46f9b53decfa6ec8

**Comment by rosenfeld** [comment]
Thanks, Eileen and everyone!

**Comment by marcamillion** [comment]
This issue (and the PR related to it, I believe) have broken the way I format code on my site.

Before, I would simply do: `<%= raw rouge(@question.test_suite, @question.language) %>`, but now that doesn't work.

Any suggestions on how I might be able to get my output to be the same as it was before? In other words, before `.html_safe` would not work for the above call, but `raw` did.

So that's why now that raw calls `html_safe` it breaks.

How do I override that, so I can go back to how `raw` behaved before?

**Comment by rosenfeld** [comment]
This PR is about `render` I think. What does your `rouge` method do?

**Comment by marcamillion** [comment]
It highlights syntax (which is output as HTML), which comes from [this gem](https://github.com/jneen/rouge).

**Comment by rosenfeld** [comment]
I really don't think your case is related to this PR. Could you expand on what is the real reason? What is the expected output? What is it showing instead?

**Comment by rosenfeld** [comment]
It also happens if you show what is the code for the `rouge` helper (it doesn't seem to be defined in the gem) or if you could create a sample application demonstrating the issue on Github and share the link with us.

**Comment by marcamillion** [comment]
@rosenfeld It was working perfectly up to rc2, so unless there was something else that broke it in 5.0.0, this `raw` method is what I came up with.

So to implement this gem, I did the following:

- Added `gem 'rouge', '~> 2.0', '>= 2.0.2'` to my Gemfile and ran `bundle`
- Created a file called `app/assets/stylesheets/rouge.css.erb`, that has this one line: `<%= Rouge::Themes::Github.render(scope: '.highlight') %>`
- I created a file called `RougeHelper`, which has the following code:

```
module RougeHelper
  def rouge(text, language)
    formatter = Rouge::Formatters::HTML.new(css_class: 'highlight')
    lexer = Rouge::Lexer.find(language)
    formatter.format(lexer.lex(text))
  end
end

```

In my view, I then simply do: `<%= raw rouge(@question.test_suite, @question.language) %>`.

`@question.language` simply contains a string like `ruby`, whereas `@question.test_suite` contains text like this:

```
  context 'when user is male' do
    let(:u1) { create(:user, gender: 0) }
    let(:ft) { create(:family_tree, user: u1) }
    let(:u2) { create(:user, gender: 0) }
    let(:ft2) { create(:family_tree, user: u2) }
    let(:mem1) { create(:membership, invited: u2, relation: rel1, inviter: u1, family_tree: ft) }
    let(:mem2) { create(:membership, invited: u1, relation: rel2, inviter: u2, family_tree: ft2) }

    it "should convert the relation from 'son' to 'dad'" do
      rel1 = "son"
      rel2 = "dad"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'daughter' to 'dad'" do
      rel1 = "daughter"
      rel2 = "dad"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'mom' to 'son'" do
      rel1 = "mom"
      rel2 = "son"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'dad' to 'son'" do
      rel1 = "dad"
      rel2 = "son"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'grandfather' to 'grandson'" do
      rel1 = "grandfather"
      rel2 = "grandson"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'grandmother' to 'grandson'" do
      rel1 = "grandmother"
      rel2 = "grandson"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'great_grandfather' to 'great_grandson'" do
      rel1 = "great_grandfather"
      rel2 = "great_grandson"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'great_grandmother' to 'great_grandson'" do
      rel1 = "great_grandmother"
      rel2 = "great_grandson"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'niece' to 'uncle'" do
      rel1 = "niece"
      rel2 = "uncle"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'nephew' to 'uncle'" do
      rel1 = "nephew"
      rel2 = "uncle"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'aunt' to 'nephew'" do
      rel1 = "aunt"
      rel2 = "nephew"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'uncle' to 'nephew'" do
      rel1 = "uncle"
      rel2 = "nephew"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'sister' to 'brother'" do
      rel1 = "sister"
      rel2 = "brother"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'brother' to 'brother'" do
      rel1 = "brother"
      rel2 = "brother"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'wife' to 'husband'" do
      rel1 = "wife"
      rel2 = "husband"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'husband' to 'husband'" do
      rel1 = "husband"
      rel2 = "husband"
      expect(u1.convert_relation(rel1)).to eq rel2
    end

    it "should convert the relation from 'cousin' to 'cousin'" do
      rel1 = "cousin"
      rel2 = "cousin"
      expect(u1.convert_relation(rel1)).to eq rel2
    end
  end
```

Right now, that is being rendered like this:

<img width="830" alt="screen shot 2016-07-08 at 6 35 22 pm" src="https://cloud.githubusercontent.com/assets/137772/16704266/c909f1c4-453a-11e6-9f9f-34b7844d8fa4.png">

Whereas, it should be rendered like this - http://rouge.jneen.net/pastes/DKvV  (or something similar, per the theme I specified in the `rouge.css.erb`.

I didn't mean to hijack this issue, but I can't find another reason that this display broke going from `rc2` to `5.0.0`.

**Comment by rosenfeld** [comment]
That seems like an issue with your CSS. Did you check your CSS rendered content? Also take a look at the html source and compare them with output on rc2. If the problem lies on CSS then it doesn't seem to be an issue with the rouge helper. I'd have to check how render is implemented in the gem, but I'm currently out of home.

**Comment by marcamillion** [comment]
So I found what seems to be a solution, but the strange thing is that it worked before. 

Basically, I just had to wrap the `raw rouge` helper method call in my view with `pre` tags that had a class of `highlight`.

Now the formatting works. 

I don't understand why it worked before though, and then stopped working once I upgraded to 5.0.0. I still think this had something to do with it.

The weird thing is now it is still adding a weird spacing at the beginning of all my code snippets that are highlighted now....which I don't understand. But at least the bulk of the code is fixed.

Thanks for the help @rosenfeld! :)

**Comment by rosenfeld** [comment]
I still find it very unlikely that something like that was caused by this PR. Most likely you upgraded rouge altogether with Rails or changed another code which changed this behavior. I can't see how the changes in this PR would break your case in that way... Glad you were able to find a fix, congrats.

**Comment by marcamillion** [comment]
You may be right, I am going to review the last few commits to see if anything else major was changed that I never realized. 

Thanks.

**Comment by marcamillion** [comment]
By the way....can you tell me if both of these are identical -- based on this PR?

    <%= rouge(@question.test_suite, @question.language).html_safe %>

and

    <%= raw rouge(@question.test_suite, @question.language) %>

Or are there more differences I am not fully appreciating?

**Comment by marcamillion** [comment]
@rosenfeld Just looking through the Rails 5 commit, as it turns out, that `bundle update` I did for that, did also update the `rouge` gem from `1.11.0` to `2.0.2` without me realizing. So that could very well have broken it, but it was hidden in the "Rails 5" update.

**Comment by rosenfeld** [comment]
Those should be equivalent as far as I understand, but I don't think this PR changed the meaning of either raw or html_safe. This PR only calls html_safe when render is used with some non erb file. Since your helper doesn't call render it shouldn't be affected by this PR.

**Comment by rosenfeld** [comment]
Most likely rouge introduced a breaking change in the upgraded version.

**Comment by marcamillion** [comment]
So would you say it is safer to just use `.html_safe` than `raw`?

I agree re: breaking change in the upgraded version.

**Comment by rosenfeld** [comment]
I always thought they were equivalent in this case so if there's any difference I can't tell you. That's why I don't recommend a particular one. I guess any of those would be fine.
