### ISSUE TITLE
Rails Update Misses Feedback

### ISSUE THREAD

**Issue by hmistry** [rails/rails#24983]
I recently updated my Rails project from 5.0.0.beta2 to 5.0.0.rc1 using `rails rails:update`. Here's a list of things where it missed or did not provide feedback.

I resolved this manually but posting only to provide you with feedback. Hope this helps.

Context:
- I used http://railsdiff.org/5.0.0.beta2/5.0.0.rc1 to see the difference of new vs old.
- My project is configured to use SASS, HAML, and Rspec.

### Steps to reproduce
Take existing Rails 5.0.0.beta2 app, update `Gemfile`, run `bundle install`, and then run `rails rails:update`.

### Expected behavior
It magically updated all the config files to the new one with all my edits in place! (just kidding on last part)

### Actual behavior
It did not make the following changes:
- delete cable.coffee and replace with cable.js
- changes to `application.html.erb`. Since I'm using HAML, I don't expect it to autofix it, but I think a print out in STDOUT to change the `data-turbolinks-track` from `true` to `reload` would be nice.
- all changes to require paths in Rakefile, config.ru, config/*
- did not create `config/initializers/ssl_options.rb` and `config/initializers/to_time_preserves_timezone.rb` files

In cases where config options were removed or it can't make changes like in my application.haml file, falling back to a note STDOUT to inform the user of the changes would be really nice to have and prevents pain down the road.

### System configuration
**Rails version**: 5.0.0.rc1
**Ruby version**: 2.3.0

**Comment by prathamesh-sonpatki** [comment]
@hmistry Thanks for the report. But Rails update task does not guarantee automagically replacing files or configs during upgrades between beta to beta or beta to RC releases. It is guaranteed during upgrade from one major release to another.  This is because things keep changing between beta and RC releases. (Example - cable.coffee to cable.js)

Also check discussion on https://github.com/rails/rails/issues/23450 for similar issue report.

`config/initializers/ssl_options.rb` and `config/initializers/to_time_preserves_timezone.rb` are not created for applications upgraded from older versions. This is to maintain the backward compatibility. 

> In cases where config options were removed or it can't make changes like in my application.haml file, falling back to a note STDOUT to inform the user of the changes would be really nice to have and prevents pain down the road.

Though this is nice to have feature, upgrades during beta and RC releases are expected to have such things. Also this is sort of a feature request so please discuss it on rubyonrails core mailing list. The issue tracker is reserved for bug reports only.

**Comment by hmistry** [comment]
@prathamesh-sonpatki Yep I was not expecting it to automagically upgrade. I tried the feature and provided feedback where it fell short so the team can look into it depending on time and resources. I was pleased to see that it performed as well as it did.

I'll pass the nice to have feature to the mailing group.

> `config/initializers/ssl_options.rb` and `config/initializers/to_time_preserves_timezone.rb` are not created for applications upgraded from older versions. This is to maintain the backward compatibility.


This sounds contradictory. If this is not for upgrades from old applications, then what backward compatibility is it trying to maintain?

**Comment by prathamesh-sonpatki** [comment]
@hmistry Because those are breaking changes for old applications. See https://github.com/rails/rails/pull/22663#issuecomment-165811499 and https://github.com/rails/rails/commit/c9c5788a for the reasons behind why these are breaking changes for older apps. 

In case of `config/initializers/ssl_options.rb` you will get a [deprecation warning] (https://github.com/rails/rails/blob/e35b98e6f5c54330245645f2ed40d56c74538902/actionpack/lib/action_dispatch/middleware/ssl.rb#L70-L72) in an older app upgraded to Rails 5 explaining you about the new HSTS option so you can upgrade your app accordingly.

I am not sure how we should handle the case of `config/initializers/to_time_preserves_timezone.rb`. May be follow the same approach of deprecation warning of HSTS subdomains config for older apps, so that they know of this change. @pixeltrix Thoughts?
