### ISSUE TITLE
Rails.root encoding problem

### ISSUE THREAD

**Issue by mollat** [rails/rails#25078]
Just found some weird behavior with the Rails.root path while upgrading an app. Did not find anything on the web, so maybe someone here can tell me if this is a bug or a feature that I have to add 'force_encoding' to lots of lines... Thanks!

### Steps to reproduce
```
$ rails new testapp
[...]
cd testapp
$ rails c
2.2.5 :001 > Rails.root.to_s.encoding
 => #<Encoding:US-ASCII> 
2.2.5 :002 > 'some_string'.encoding
 => #<Encoding:UTF-8> 
2.2.5 :003 > 
```
### Expected behavior
I expected to have equally encoded strings all over the application.

### Actual behavior
Rails.root gives an US-ASCII encoded string back and raises 'invalid byte sequence in UTF-8' exception if some filename string is added.

### System configuration
Ubuntu 14.04, rvm 1.26.11
```
$ ruby -v
ruby 2.2.5p319
$ rails -v
Rails 4.2.6
```

**Comment by vipulnsward** [comment]
Hmm, I am able to see this. Let me see.

**Comment by marekkirejczyk** [comment]
Root cause of the problem seems to have source in Pathname#expand_path that is part of Ruby API.

Take a look at Rails:: Engine::Configuration#root= 
```
      def root=(value)
        @root = paths.path = Pathname.new(value).expand_path
      end
```

Now:
`Pathname.new("/").to_s.encoding == #<Encoding:UTF-8>`
but
`Pathname.new("/").expand_path.to_s.encoding == #<Encoding:US-ASCII>`

However for some reason:
`Pathname.new(".").expand_path.to_s.encoding == #<Encoding:UTF-8>`

Works the same way in Rails application as in pure ruby script.
Strange behaviour, but should be reported on ruby github.

**Comment by rafaelfranca** [comment]
:+1:

**Comment by rafaelfranca** [comment]
Thank you for investigating.

**Comment by mollat** [comment]
Thank you for looking at this... !
