### ISSUE TITLE
Bundle install issue

### ISSUE THREAD

**Issue by sai43** [rails/rails#25154]
sasmple_app$ bundle install

Fetching source index from http://localhost:9292/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from http://localhost:9292/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from http://localhost:9292/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from http://localhost:9292/
Could not fetch specs from http://localhost:9292/

### System configuration
**Rails version**:  4.2.6

**Ruby version**:  ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]

**Comment by rafaelfranca** [comment]
bundle install issues are usually not Rails issues. In this case it seems that you gemfile is defining a source at `http://localhost:9292/` and it is not accessible.

**Comment by sai43** [comment]
I got it, any way FYI my gem file source 'https://rubygems.org'

**Comment by Ingosmar89219** [comment]
i have something similar. somebody can help me? thanks a lot guys! the gem that i wrote is gem "will_paginate"  my error is:
noeblack@garyhost:~/redsocialRails$ bundle install
The git source `git://github.com/plataformatec/devise.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/urielhdz/remotipart.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/rails/activemodel-serializers-xml.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/audionerd/draper.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/Could not fetch specs from https://rubygems.org/

**Comment by Rashindrie** [comment]
Did you find a solution for this?
