### ISSUE TITLE
incorret sydney time zone

### ISSUE THREAD

**Issue by anklos** [rails/rails#25159]
### Steps to reproduce

start Rails Console, then do `Date.today.in_time_zone('Sydney').strftime("%Z")`

### Expected behavior
 should always print `AEST`

### Actual behavior
on different computers, it prints `EST` or `AEST`. I dont know what server configs would make that difference yet. 

### System configuration
**Rails version**: 4.1

**Ruby version**: 2.1.1p76 and 2.3.0, both show `EST` on my macbook.

**Comment by vipulnsward** [comment]
Without steps to reproduce, or in which scenario this is happening, it is going to be hard to reproduce. 
When/where are you seeing this behaviour?

**Comment by anklos** [comment]
@vipulnsward i have tried 6 machines, three mac, and 3 digital ocean standard instances.

macbook one prints `EST`
macbook two prints `AEST`
macmini prints `AEST`

Three digital ocean instances all print `EST`.

Looks like it relates timezone settings on the machine, does it? I thought this `in_time_zone(xxx)` method is independent from server timezone settings? Not like `Time.now`, which depends on server timezone.

**Comment by vipulnsward** [comment]
See https://github.com/tzinfo/tzinfo-data/blob/master/data/australasia#L854

You are probably seeing this due to difference in tzinfo-data versions on these machines. This was updated here- https://github.com/tzinfo/tzinfo-data/commit/0e431a28b917626ca0df2ab6fe95e412df859cc2. Previously it was a combination of EST and AEST, and now it is preferred to AEST.
Going to give this a close. Let me know if you see some other issue.

**Comment by anklos** [comment]
@vipulnsward thanks so much! just updated tzdata package on those machines and it works!
