### ISSUE TITLE
ActiveSupport looks for application_records table when there is no such table

### ISSUE THREAD

**Issue by paneer-tikka** [rails/rails#25379]
### Steps to reproduce
* Clone git@github.com:paneer-tikka/rails5bug.git
* Follow [README](https://github.com/paneer-tikka/rails5bug/blob/master/README.md)

### Expected behavior
rails db:seed should succeed without having to specify self.table_name on the model.

### Actual behavior
db:seed goes looking for a table application_records which doesn't exist and then crashes.

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

Tagging @prathamesh-sonpatki as requested [here](http://stackoverflow.com/questions/37771127/rails-5-pgundefinedtable-error-relation-application-records-does-not-exi)

**Comment by prathamesh-sonpatki** [comment]
This issue is related to https://github.com/lowjoel/activerecord-userstamp and not Rails. I verified that once this gem is commented then everything works as expected.

Seems to be something similar to https://github.com/lowjoel/activerecord-userstamp/issues/7.

Thanks for the report! I am closing it as it is not related to Rails.

**Comment by paneer-tikka** [comment]
Thanks... will look into patching activerecord-userstamp.

**Comment by TylerRick** [comment]
I ran into this problem as well in my app after I upgraded to Rails 5 and changed all of my models to subclass `ApplicationRecord`.

I wish there were a built-in way to tell Rails: "include this Concern into all subclasses of `ApplicationRecord`". Because sometimes you need subclass-specific code (such as doing something with the list of `columns` of the model you are including the concern into) in your Concern's `included` block, so you can't just include it directly into your `ApplicationRecord` base class.

Since I didn't see a standard way to do this, I wrote a little gem ([active_record_include](https://github.com/TylerRick/active_record_include)) that does that. I hope it can be helpful to others as well (and please tell me if there's a better way to accomplish this).
