### ISSUE TITLE
Schema migrations in structure.sql, in single line (multi value insert)

### ISSUE THREAD

**Issue by michaldarda** [rails/rails#25504]
### Steps to reproduce

Set schema format to sql, and execute rake db:structure:dump

### Expected behavior
I should have schema migrations in separate lines, like so:

```sql

INSERT INTO schema_migrations (version) VALUES ('20160303124410');
INSERT INTO schema_migrations (version) VALUES ('20160315083252');
INSERT INTO schema_migrations (version) VALUES ('20160315120137');
INSERT INTO schema_migrations (version) VALUES ('20160317122847');
```

### Actual behavior
All migrations in single like, like so:
```sql
INSERT INTO schema_migrations (version) VALUES ('20150304132711'), ('20150306141924'), ('20150330084039')
```

### System configuration
**Rails version**: 5.0.0rc2

**Ruby version**: 2.2.3
**psql (PostgreSQL)**: 9.4.7

This is important for me because with one long line it is hard to see the diff

**Comment by esparta** [comment]
This change of behavior was introduced on https://github.com/rails/rails/commit/42dd2336b31a8d98776d039a2b9fd7f834156a78:
```diff
         sm_table = ActiveRecord::Migrator.schema_migrations_table_name
 
-        ActiveRecord::SchemaMigration.order('version').map { |sm|
-          "INSERT INTO #{sm_table} (version) VALUES ('#{sm.version}');"
-        }.join "\n\n"
+        sql = "INSERT INTO #{sm_table} (version) VALUES "
+        sql << ActiveRecord::SchemaMigration.order('version').pluck(:version).map {|v| "('#{v}')" }.join(', ')
+        sql << ";\n\n"
       end
```

According with the commit is an improvement of performance. I'm agree this is a change related to Rails 4.2.x and perhaps you should do a proposal on the Rails Core Forum: https://groups.google.com/forum/#!topic/rubyonrails-core/

Personally I think the diff is a legitimate use case, but that's a Core Devs call on how to proceed.

**Comment by rafaelfranca** [comment]
Is not important to the structure.sql file be diff friendly. In this case performance is more important.

**Comment by rosenfeld** [comment]
If someone decided to create a ticket just because they value diff, it's likely it's important to some people. @esparta has also seemed to understand the reasoning and agree with that and so do I. Those who usually don't use the sql format probably didn't notice how this made things bad for us who use the sql format. Diff is only one of the problems and if someone is using "git diff" directly, then it's a simple matter of running `git diff --word-diff` but this is not the only issue. Another issue is that it will always conflict when you are using multiple branches with different migrations and you want to rebase some branch on top of another. Previously there were good chances the rebase would just work for many cases. But now it will always conflict. I think it should be possible to keep the same performance while splitting a new line after each comma and use the semi-colon in a new line. Something like this:

```
INSERT INTO schema_migrations (version) VALUES ('20160615142359')
, ('20160628184326')
, ('20160901183422')
, ('20161014184941')
;
```

**Comment by rosenfeld** [comment]
I just noticed it was implemented with a slight different approach here: https://github.com/rails/rails/commit/574b87d42e5a03966d83e5cdf5caf16f3a9031f2
