### ISSUE TITLE
Has many through with nested attributes problem

### ISSUE THREAD

**Issue by piotrpietrusewicz** [rails/rails#25561]
### Steps to reproduce
I have associations:  Training has many Exercises through TrainingExercise and reverse.
I have also 7 ( muscle group)  scopes in Exercises. 
### Expected behavior
I would like to have form with field type date from training and all 7 scopes from exercise and when button Send is clicked then save record to only Training and TrainingExercise. 
### Actual behavior
Recently  I have form with date, and 7 fields type select with collection of each scope. Just only date and only one exercise is saved into ActiveRecord. I don't know how solve this. Shortly, I would like to freeze my model Exercise, that anything couldn't  be saved into it. 

### System configuration
Rails 5.0.0.rc1
Ruby 2.2.5

**Comment by sgrif** [comment]
This looks like a help request, not a bug report. Please take requests for help to stack overflow or the mailing lists, where the larger community will be available to help. If there is a bug that you're reporting here, please comment with a link to a minimal rails app that can reproduce the issue, and a tests case for the expected behavior, and I will reopen.
