### ISSUE TITLE
Unexpected behaviour using .group(:enum_field).count for postgresql adapter

### ISSUE THREAD

**Issue by crackedmind** [rails/rails#25595]
### Steps to reproduce

```ruby
require 'minitest/autorun'
require 'rack/test'
require 'active_record'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'some_db')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :tickets, force: true do |t|
    t.integer "priority"
  end
end

class Ticket < ActiveRecord::Base
  enum priority: [:high, :middle, :low]
end

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    Ticket.create!(priority: :high)
    assert_equal({"high" => 1}, Ticket.group(:priority).count)
  end
end
```
But if i change adapter to mysql2 or sqlite3 everything work as expected

### Expected behavior
```ruby
Ticket.group(:priority).count
#=> {'high'=>1}
```
### Actual behavior
```ruby
Ticket.group(:priority).count
#=> {0=>1}
```

### System configuration
**Rails version**: 5.0.0.rc2

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by aranair** [comment]
Hi, I had a quick look and have a few thoughts on where its happening, and was wondering if I could have a go at this? (that is if `{'high' =>}` is indeed the expected behaviour)

**Comment by rafaelfranca** [comment]
No it is not. enum are mapping to integers in the database. `group` and `count` are database operations that doesn't know anything about the model and how it is defined. The correct behavior is to it return integers like it is doing right now.

**Comment by aranair** [comment]
So its meant to have a different behaviour across the different adapters?

**Comment by rafaelfranca** [comment]
No, all adapters should behaves in the same way. If mysql is working differently from postgresql we should fix.

**Comment by aranair** [comment]
Sure, I'll dig abit and have a shot at it then, thanks!

**Comment by aranair** [comment]
Initialising the `ActiveRecord::Result` with an extra hash of types for each of the columns in the results at [mysql/database_statements](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb#L39) seem to pass the new test cases. When deserializing, it correctly treats it as an `int` instead of an `enum`. [relation/calculations](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/calculations.rb#L315-L317) 

However, it doesn't seem like the `mysql2` gem currently exposes any method like the one `pg` provides. Should I be looking into the mysql2 to expose a similar method first? Or is there a way easier approach to this that I am missing?

**Comment by aranair** [comment]
These [changes](https://github.com/rails/rails/compare/master...aranair:25595) passes all the tests, along with the additional ones in this ticket but I'm unsure where most of that code should be, or if there is something similar already. Any suggestion would be great :P

**Comment by sgrif** [comment]
Backporting to 5.0 in #25778

**Comment by aranair** [comment]
quick questions @sgrif, in every case, the class type is preferred? (e.g. `string` instead of `int` in the case of an enum)? @rafaelfranca seems to suggest that it shouldn't know about the class type for a database operation?

**Comment by sgrif** [comment]
The code was already using the class type (as it should be), but there was
a precedence issue as described in the commit.
