### ISSUE TITLE
Puma doesn't start in ssl mode

### ISSUE THREAD

**Issue by janwendt** [rails/rails#25700]
I have added this one to my puma.rb

```
ssl_bind '0.0.0.0', '3000', {
  key: 'config/ssl-certificate/my-server.key.pem',
  cert: 'config/ssl-certificate/my-server.crt.pem'
}
```

and `rails s` doesn't start puma in ssl mode. 
`puma -C config/puma.rb` works just fine!!!

**Comment by schneems** [comment]
This is related to https://github.com/rails/rails/issues/24435 and https://github.com/puma/puma/issues/939.

Here is the issue. Puma favors config you pass in directly over config in your `puma.rb`. For example if you have

```
port 3001
```

and you run

```
$ puma --port 5001
```

Then `5001` will win. Why does this matter? Rails allows you to run `$ rails server -p 5001` however it also specifies a default port of 3000 when running `$ rails server`. Puma doesn't know the difference between the default passed in and an explicit user supplied argument. So it always uses what it thinks is the "passed in" argument which in this case would be using a port of 3000 even though it's only the default. This takes precedence over your connection config since all that method does is build a port to connect to:

```ruby
      def ssl_bind(host, port, opts)
        o = [
          "cert=#{opts[:cert]}",
          "key=#{opts[:key]}"
        ]

        @options[:binds] << "ssl://#{host}:#{port}?#{o.join('&')}"
      end
```

It works with the `$ puma` command (btw it auto reads `config/puma.rb` no need to specifiy the config file) because there is no provided default port.

The answer is to not use the `$ rails s` command.

**Comment by daniel-g** [comment]
This problem is really weird. One of my rails apps reads the config file, and one does not.

**Comment by daniel-g** [comment]
@janwendt it worked for me using these versions:
* rails (5.0.1)
* puma (3.7.0)
