### ISSUE TITLE
undefined method `call' for nil:NilClass when calling parsed_body on a TestResponse

### ISSUE THREAD

**Issue by Morpheu5** [rails/rails#25762]
I have a RSpec test case which includes the following:

    expect(response.parsed_body.count).to eq(4)

This produces the following error:

    1) UsersController when logged in as a user GET #index shows a list of all the users
       Failure/Error: expect(response.parsed_body.count).to eq(4)

       NoMethodError:
         undefined method `call' for nil:NilClass
         Did you mean?  caller
       # ./spec/controllers/users_controller_spec.rb:22:in `block (4 levels) in <top (required)>'

Changing that line to

    expect(JSON.parse(response.body).count).to eq(4)

does not produce the error and the test passes.

Ruby: 2.3.1
Rails 5.0.0

**Comment by maclover7** [comment]
Thank you for reporting! Did this work for you on previous versions of Rails? 
Also, can you use your code above and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by Morpheu5** [comment]
I don't know if it worked, this is a new project I started with Rails 5 straight away, and I haven't touched Rails in a long time (probably since 3 was released…).

I'd love to create that script but I'm not sure how to get a TestResponse object. I'm getting a Rack::MockResponse instead.

**Comment by Morpheu5** [comment]
Nevermind, I hope this is OK

https://gist.github.com/Morpheu5/29ba0400a76f2ef57c83a14d8d8a08e1

**Comment by maclover7** [comment]
Hmm, after some further investigation it _seems_ like this behavior may be on purpose. `TestResponse#parsed_body` was added via #23597, but it seems like it was only meant to be used with `ActionDispatch::IntegrationTest`, not `ActionController::TestCase` (which I think is soft deprecated...?), which is causing the error you are seeing above. Even if the only supported usage for `@response.parsed_body` is via `AD::IntegrationTest` (where `@response_parser=` is called), we should figure out a way for this to "fail with a smile", not trigger a non-descriptive error when you call `@response.parsed_body` through `ActionController::TestCase`.

r? @kaspth since you worked on the initial implementation of this 😬

**Comment by Morpheu5** [comment]
But I'm getting an `ActionDispatch::TestCase`, not `ActionController`. Anyway, I wonder what's the rationale for not providing `parsed_body` for `TestCase`s too. I may not be writing the best specs, but I sometimes have to check the content of the body two or three times per example.

**Comment by kaspth** [comment]
@Morpheu5 hey, thanks for spotting this! ❤️ I've opened up https://github.com/rails/rails/pull/25771 to try to fix your reproduction script.

It seems, however, your reproduction script is different from the code in your original issue description. I'd like to know if my PR also solves your original problem.

It looks like RSpec tests. So was the reason you instantiated `ActionDispatch::TestResponse`'s manually in your repro because RSpec does that internally?

@maclover7 luckily we should be able to make this work from the test responses angle entirely ❤️

**Comment by Morpheu5** [comment]
> It looks like RSpec tests. So was the reason you instantiated ActionDispatch::TestResponse's manually in your repro because RSpec does that internally?

Precisely.

(Sorry for the delay)

**Comment by kaspth** [comment]
@Morpheu5 great, can you verify that my PR fixes your issue? Then I'll happily merge, backport, and then you can look forword to having the fix out in Rails 5.0.1 😁

**Comment by Morpheu5** [comment]
@kaspth Yes, looks like it does! I'm looking forward to 5.0.1, then, and I'll come back to this issue if anything goes wrong.

**Comment by kaspth** [comment]
Fantastic!
