### ISSUE TITLE
OpenSSL::Random.random_bytes significantly slower in Rails than in plain Ruby on Windows

### ISSUE THREAD

**Issue by vais** [rails/rails#25805]
### Steps to reproduce

```
C:\>rails -v
Rails 5.0.0

C:\>ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

C:\>ruby -ropenssl -e "t = Time.now; OpenSSL::Random.random_bytes(16); p Time.now - t"
0.858001

C:\>rails new blah
      create...

C:\>cd blah

C:\blah>rails runner "t = Time.now; OpenSSL::Random.random_bytes(16); p Time.now - t"
6.28982
```

Without Rails loaded: `0.858001`, with Rails loaded: `6.28982`. Calling `OpenSSL::Random.random_bytes` is slow only on the first invocation - subsequent invocations are fast in both cases.

Interestingly, the work-around I found for this issue is to call `OpenSSL::Random.random_bytes` at least once **before** Rails is loaded. I have literally this on the first line of my `config/boot.rb`:

``` ruby
require 'openssl'; OpenSSL::Random.random_bytes(1) # Make Windows fast.
...
```

So, all signs point to this being a seeding issue, but I cannot figure out where/what/how in the process of loading up the Rails environment is causing this. Again, calling `OpenSSL::Random.random_bytes` at least once **before** loading up Rails mitigates the issue.

This issue has significant negative effect on various aspects of working with Rails on Windows (i.e. it affects many new people coming to Rails). E.g. it affects the time it takes Rails to render the first page (at least in dev mode, 10+ seconds on 4 core 8Gb machine vs <1 second after the "fix"), it makes testing models that use `bcrypt` intolerable on Windows, since `bcrypt` relies on `OpenSSL::Random.random_bytes` internally, etc.
### Expected behavior

`OpenSSL::Random.random_bytes` should have the same performance profile regardless of whether it's called in Rails environment or in plain Ruby.
### Actual behavior

Instead, `OpenSSL::Random.random_bytes` is orders of magnitude slower on first invocation in Rails than in plain Ruby.
### System configuration

**Rails version**: Rails 5.0.0

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

**Comment by vipulnsward** [comment]
Not on Windows, so can't verify this perfectly, we don't happen to do anything specific in this case on Rails.
This is actually handled differently on ruby's side- https://github.com/vipulnsward/ruby/blob/b402cc71616169bab03fb856e73a7d6519330ca3/lib/securerandom.rb#L67-L67

When you say the workaround makes it faster, can you share some results about this?
After doing this- 
```
require 'openssl'; OpenSSL::Random.random_bytes(1) # Make Windows fast.
...
```

What is the difference in output for 
```
rails runner "t = Time.now; OpenSSL::Random.random_bytes(16); p Time.now - t"
```

**Comment by vais** [comment]
Hi, @vipulnsward,

First, to answer your question about the difference in output before and after adding the "magic" line to `config/boot.rb`, here is the full transcript:
```
C:\blah>rails runner "t = Time.now; p OpenSSL::Random.random_bytes(16); p Time.now - t"
"\xF0\xA8,i\x7F\xA5\a'5\xA8\xCDz\xD04RP"
5.22701

C:\blah>echo require 'openssl'; OpenSSL::Random.random_bytes(1) # Make Windows fast. >> config\boot.rb

C:\blah>rails runner "t = Time.now; p OpenSSL::Random.random_bytes(16); p Time.now - t"
"\x93\x06\x1A\x96\x8B\xC8^\x90\x93#\xD2\x13n\xEFg\\"
0.0
```
Second, the example you referenced is `SecureRandom`, which also has a `random_bytes` method that works exactly the same as `OpenSSL::Random.random_bytes`, but it's a different implementation that deliberately accounts for Windows quirks, and it happens to have the same performance profile whether or not Rails is loaded. If only all gems used `SecureRandom.random_bytes` instead of `OpenSSL::Random.random_bytes`, there'd be no issue.

A little background info: I originally stumbled on this problem while following @mhartl's [Rails Tutorial](https://www.railstutorial.org/). I noticed that after adding `has_secure_password` to the `User` model in [section 6.3.1 of the book](https://www.railstutorial.org/book/modeling_users#sec-a_hashed_password), the time it took to run my model tests jumped from milliseconds to 10-20 seconds. I realize `has_secure_password` uses bcrypt, which is slow by design, but not *that* slow, so I started digging. Turns out bcrypt uses `OpenSSL::Random.random_bytes` in its implementation (https://github.com/codahale/bcrypt-ruby/blob/master/lib/bcrypt/engine.rb#L72). Changing that line to use `SecureRandom` instead also fixed the problem for me. So, whatever's happening in Rails does not affect the performance of `SecureRandom.random_bytes`, but affects the performance of `OpenSSL::Random.random_bytes`.

Hope this helps, and thank you for following up!

**Comment by vipulnsward** [comment]
Turns out its a Windows issue on openssl-  https://wiki.openssl.org/index.php/Random_Numbers#Windows_Issues

More details at https://github.com/vipulnsward/ruby/blob/c016898e79edec4fe3c5106ba7e7742a5eaa3f17/ChangeLog#L4756-L4770

Its fixed on securerandom to handle it, but openssl(trying to shadow lib openssl?) still uses native macro causing this issue.

Going to give this a close, since its not a Rails issue, thanks!

P.S: You can probably open this up on bcrypt, to see if they want to find an alternative to this in Windows.

**Comment by vais** [comment]
@vipulnsward, that still doesn't explain why it's fast without Rails loaded. Also, fixing this in bcrypt will not make the slow-first-page-access problem go away. ¯\_(ツ)_/¯

**Comment by vipulnsward** [comment]
@vais adding OpenSSL::Random.random_bytes(1) to boot.rb is not making it fast. Its still taking time to get the seed / handle to urandom . In first case you are seeing the time, because its spending that time in raw_seed for the first time. In your second case, it has *already* spent that time, and subsequent call is faster, and you are just measuring second call time, hence the difference.

So its not any faster, both are the same.

**Comment by frcake** [comment]
http://stackoverflow.com/questions/39840573/rails-5-very-slow-startup-on-windows

i have a lot of performance(?) problems with RoR on w7 , tried a lot of stuff , haven't found anything yet.
I'm sharing my SO post , some beautiful people contributed, so someone else might understand better than me , or have more luck!

**Comment by evolve2k** [comment]
@vipulnsward so what's the answer for people who come here stuck with a very slow windows load of Rails. The issue is that especially for newcomers, this can be enough to turn them away from the Rails ecosystem.

Does this just require people to upgrade their version of ruby, or download a updated version of OpenSSL (for windows). Or is there more to it than that?

One of the windows issue seems to date back to 2009.  Final comment  on the issue.

> "timer-limiting for windows heap-walking, etc., seems to have been implemented some time ago."

And the references above it seem to imply that if you are above OpenSSL version 1.0.0 that should be resolved (which I would imagine the vast majority of people would be on newer version than that at this stage).

The other issue refers to the fix as: 

> "I think the correct fix for this is to skip the two calls to NetStatisticsGet in RAND_poll if the calling thread does not have the Administrators SID in its token. There's sample code in the MSDN documentation for the CheckTokenMembership API showing how to make that test. "

Which is fairly low level for most people coming looking for an opinionated convention over config stack.

How to fix this so that Rails Windows users aren't suffering? What do people do to get a usable speed from Rails on Windows?

**Comment by evolve2k** [comment]
poke

**Comment by schlamar** [comment]
Further details related to this issue are in #31337. Especially the last comment shows that the conclusion in https://github.com/rails/rails/issues/25805#issuecomment-232537039 is wrong.
