### ISSUE TITLE
rails db:migrate should default to migrating both dev and test

### ISSUE THREAD

**Issue by dhh** [rails/rails#25804]
By default, we are only migrating the dev environment when you run `rails db:migrate`. This means that when you then run `rails test`, through the new test runner, you won't have a migrated test db. Which then requires you to run `rails db:migrate RAILS_ENV=test`, which is just a hassle.

We should default to having `rails db:migrate` migrating both dev and test. If you want only one or the other, RAILS_ENV can be set to overwrite.

**Comment by rafaelfranca** [comment]
That is weird. We do run migrations automatically in test since Rails 4.1 https://github.com/rails/rails/pull/13528

**Comment by rafaelfranca** [comment]
The code that maintain the test schema automatically is still there blob/master/railties/lib/rails/test_help.rb#L15

**Comment by dhh** [comment]
This changed with the new Spring-powered default test runner.

**Comment by dhh** [comment]
Because we didn't want to do the full DB recreate when you just want to run a single test or whatever.

**Comment by rafaelfranca** [comment]
So it is a bug with the new Spring-powered default test runner. That command doesn't do the full db recreate, it just run things if there are migrations pending.

**Comment by dhh** [comment]
It's not a bug, it's the intended behavior. We don't want to do a full db schema refresh as it slows things down. So a way of making this a kinder experience for more people, more of the time, is just to migrate the test environment by default when you call db:migrate.

**Comment by rafaelfranca** [comment]
What I want to say is, the Spring-powered default test runner removed a feature that we had since Rails 4.1, this should be considered a bug and should be fixed. If we want to change the way this automatic migration schema it is fine, but we should not break a feature we had and not provide equivalent feature.

There is no full db schema refresh in the previous implementation, it only runs the pending migrations and only in the first run, so if you test more than once only the first call is slowed down. I'm not saying that it is better than running in db:migrate, but we should not have removed it just because there is a better implementation.

**Comment by rafaelfranca** [comment]
I just tested in a new application and the automatic schema migration is working.

**Comment by dhh** [comment]
The change wasn't a bug, is what I'm saying. We decided that the overhead of refreshing fixtures and checking the schema wasn't worth it with the runner.

Try this test: 1) "New app", 2) "Run tests", 3) "Some migration", 4) "Run tests again". Pretty sure 4 is going to fail.

**Comment by rafaelfranca** [comment]
Right, it it is still working. If there is no pending migration in development the schema will be loaded automatically in test, and after it is loaded the first time it is not being loaded again.

You reproduction steps indeed failed but it is because the migration where not run in dev.

1) "New app", 2) "Run tests", 3) "Add and run migration", 4) "Run tests again" works fine.

I added a debug information to when the schema is loaded in test:

```
[2.3.0 omg]$ bin/rails test
Loading schema
Run options: --seed 45128

# Running:

.......

Finished in 0.708099s, 9.8856 runs/s, 12.7101 assertions/s.

7 runs, 9 assertions, 0 failures, 0 errors, 0 skips
[2.3.0 omg]$ bin/rails test
Run options: --seed 1809

# Running:

.......

Finished in 0.655423s, 10.6801 runs/s, 13.7316 assertions/s.

7 runs, 9 assertions, 0 failures, 0 errors, 0 skips
[2.3.0 omg]$
```

Not saying that we should not change it to run when running the migration in dev, just that it is working right now and the only overhead is in the first run after the migration is run.

**Comment by dhh** [comment]
Hmm, actually, I can't seem to replicate this at the moment either. Maybe we have some special hijinks in Basecamp that's preventing this from running. Closing for now until I can verify what's up.

**Comment by rafaelfranca** [comment]
Check if `maintain_test_schema` is not set to false in your application.

**Comment by rafaelfranca** [comment]
Maybe you were seeing a huge overhead in the first execution and decided to disable it.

**Comment by dhh** [comment]
Hm, no such setting set. But I think we have another hijack to run tests/fixtures from a plugin. Maybe that's causing it. Anyway, not a Rails problem at the moment it appears. Thanks for the sanity check!

**Comment by rono23** [comment]
I think #25777 does not related to this issue, but `maintain_test_schema` is sometimes affected by initializers.

**Comment by coaxial** [comment]
> So a way of making this a kinder experience for more people, more of the time, is just to migrate the test environment by default when you call db:migrate.

Sorry to revive such an old thread, and pardon my ignorance: how would you have `db:migrate` run migrations for both development and test at once without a shell alias?
