### ISSUE TITLE
private_constant macro dosn't work with ActiveSupport::Autoload

### ISSUE THREAD

**Issue by bolshakov** [rails/rails#25813]
### Steps to reproduce

```ruby
# File: a.rb
module A
  extend ActiveSupport::Autoload

  autoload :B
end
```

```ruby
# File: a/b.rb
module A
  B = Class.new
  private_constant :B
end
```

### Expected behavior

```ruby
>> A::B 
NameError: private constant A::B referenced
```

### Actual behavior

```ruby
>> A::B 
=> A::B 
```

### System configuration

**activesupport version**: 4.2.5

**Ruby version**: 2.3

This is know ruby bug as well https://bugs.ruby-lang.org/issues/11055

**Comment by fxn** [comment]
Interesting! Could this be a problem in Ruby itself? Given

```ruby
# a.rb
module A
  autoload :B, 'b'
end
p A::B

# b.rb
module A
  B = 1
  private_constant :B
end
```

MRI does not raise:

```
$ ruby -I. a.rb
1
```

while bypassing `Kernel#autoload` works as expected:

```
$ ruby -I. -rb -e 'p A::B'
-e:1:in `<main>': private constant A::B referenced (NameError)
```

**Comment by bolshakov** [comment]
Yep, I found the issue in ruby bug tracker https://bugs.ruby-lang.org/issues/11055
But I think this problem may be fixed in Active Support too, since it use its own autoload implementatin2

**Comment by fxn** [comment]
Not really.

Rails implements the constant autoloading that allows you to refer to `User` without loading _app/models/user.rb_ yourself.

The `autoload` in this issue is a different topic. That one is syntactic sugar to leverage file name conventions and avoid writing repetitive code. In the end [it delegates to Kernel#autoload](https://github.com/rails/rails/blob/451437c6f57e66cc7586ec966e530493927098c7/activesupport/lib/active_support/dependencies/autoload.rb#L45).

**Comment by bolshakov** [comment]
Got it. Thanks for explanation.
