### ISSUE TITLE
fail when database prepartion fails in load_schema_if_pending!

### ISSUE THREAD

**Issue by grosser** [rails/rails#25932]
Just had a nasty error not showing because when this executes a subcommand and ignores when it fails ... how about raise "db:test:prepare failed" unless system('bin/rails db:test:prepare') ... or invoking the task directly ?

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb#L581

rails 5.0.0 / ruby 2.3.1

**Comment by maclover7** [comment]
👍 Thank you for reporting this!

Agree we need to more prominently display this error to users -- can you change this line to invoke the `Rake::Task` directly, so that way the error can be seen upstream? Created a small script [here](https://gist.github.com/maclover7/860629094f087014850b4a872dfbdcde) as a sample for what that would look like.
