### ISSUE TITLE
Titleize inflector squashing "Id" at the end of a string

### ISSUE THREAD

**Issue by megahbite** [rails/rails#26011]
### Steps to reproduce

```
irb(main):001:0> "ThisIsAStringEndingWithId".titleize
=> "This Is A String Ending With"
```
### Expected behavior

Expected the resultant string to be "This Is A String Ending With Id"
### Actual behavior

Instead returns a string with the "Id" truncated
### System configuration

**Rails version**: 5.0.0

**Ruby version**: 2.3.1p112

**Comment by mubashirhanif** [comment]
As you pointed out it's `ActiveSupport::Inflectors#underscore` and `ActiveSupport::Inflectors#humanize` method calls inside `titleize`
`[underscore](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-underscore)` call changes your string to `"this_is_a_string_ending_with_id"` and since `"_id"` is suffix(at the end of you string) in the underscored string it gets removed by the `[humanize](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-humanize)` method call.

**Comment by amoludage** [comment]
Here is the code which is replacing `_id` from string i.e in [humanize](https://github.com/rails/rails/blob/f2489f493b794ee83a86e746b6240031acb8994e/activesupport/lib/active_support/inflector/methods.rb#L129) method.

But I'm not understand why this behavior is required?
can anyone please explain why `humanize` method having this behavior ?

**Comment by pixeltrix** [comment]
@amoludage the `humanize` method strips `_id` off strings because one of t's primary uses is to turn column names into labels for forms and where you have a `belongs_to` you rather see "Category" than "Category Id".

Since we already have an option to disable the capitalization of the first character then I don't see why we couldn't add an option to disable stripping of `_id`.

**Comment by amoludage** [comment]
@pixeltrix  Thanks for explaining this to me :smiley: 

And yes I also think that there should have an option to `disable` stripping of `_id`

**Comment by pixeltrix** [comment]
@amoludage yes, please create a PR

**Comment by KlotzAndrew** [comment]
@mubashirhanif any movement on that PR?

**Comment by j1wilmot** [comment]
I believe this can be closed since https://github.com/rails/rails/pull/28480 was merged.

**Comment by pixeltrix** [comment]
@j1wilmot yes, thanks 👍🏻
