### ISSUE TITLE
Non-html format rendering html view

### ISSUE THREAD

**Issue by bboe** [rails/rails#26083]
### Steps to reproduce
1. Create a new rails 5 project. `rails new bug`
2. Generate a scaffold for welcome. `rails generate scaffold welcome`
3. Migrate, and run development server `rails db:migrate; rails s`
4. Confirm that http://localhost:3000/welcomes.xml raises `ActionController::UnknownFormat`
5. Rename index.html.erb for the welcomes view to index.html. `mv app/views/welcomes/index.html.erb app/views/welcomes/index.html`
6. Run development server. `rails s`
7. Visit http://localhost:3000/welcomes.xml
### Expected behavior

An `ActionController::UnknownFormat` exception should occur, which in production mode results in a 406.
### Actual behavior

The index.html view is rendered with a 200 status code (the browser complains about invalid xml).
### System configuration

**Rails version**:
5.0.0

**Ruby version**:
2.3.0
### Additional Information

With rails 4.2.7 an `ActionView::MissingTemplate` is raised. Thus, unless this is expected behavior with rails 5, it would seem to be a bug. The behavior certainly caught me off-guard, is not intuitive, and took longer than I would like to admit to discover that the lack of the `.erb` suffix was the culprit.

**Comment by maclover7** [comment]
Taking a guess, I think that #23827 might be causing this, since it was a large change in implicit rendering behavior for 5.0.

cc @chancancode @matthewd

**Comment by alexsanford** [comment]
Looks like `:html` is being added as a template handler for the XML request.

I'm still learning my way around the Rails codebase, but I'm looking in `actionview/lib/action_view/lookup_context.rb` in the `detail_args_for` method. When I inspect the `@details` variable on Rails 5.0.0 vs. Rails 4.2.7, I get a different list of handlers:

**5.0.0:**

`{:locale=>[:en], :formats=>[:xml], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}`

**4.2.7:**

`{:locale=>[:en], :formats=>[:xml], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}`

I think that explains why it renders the `.html` template but not `.html.erb`. It's like it sees `.html` as a templating language that may be rendered to XML. Whereas with the `.erb` file, the `.html` portion is the file's format, which doesn't match `.xml`, so it doesn't render it.

I'm assuming that the right solution is to not include `:html` in the list of handlers when rendering an XML format.

I'm happy to keep digging into this one, and I can work on a patch if I figure it out. I haven't done a lot of poking around in actionview, so any pointers would be appreciated 😄

**Comment by pixeltrix** [comment]
This is technically 'not a bug' :smile:

You're essentially using the HTML template handler to render XML in the same way that you can use the ERB handler to render either HTML, JSON, JavaScript, etc. In the same way you could the Builder handler to render HTML using `index.html.builder` template.

However it's not particularly intuitive but I'm not sure we have a way of saying only use these handlers for these formats - though I'm prepared to be corrected on that.

**Comment by bboe** [comment]
@pixeltrix I'm curious what use there would be to use the HTML template handler to render anything other than HTML.

Similarly, I deduced from your comment that any `VIEW.HANDLER` file will act as a catch-all format renderer for VIEW with a corresponding HANDLER. Is that documented behavior? Again, I would expect that without two levels of extensions (e.g, `.html.erb`) that the extension would only work for a single format using that single handler. I can see how that might be useful if that was what someone wanted. However, due to the fact that HTML is both a format and a handler, it seems more likely that the result is not what many users would want.

**Comment by alexsanford** [comment]
I was thinking about this tonight, and this is just speculation, but I think one could argue the following:

- If you have an action that responds to multiple formats by rendering templates, then you would absolutely have to specify the format in the template file extension (e.g. `index.html.erb` instead of `index.erb`) for each template that you need for that action. In other words, you would need `index.html.erb`, `index.xml.erb`, etc.

- On the other hand, if you have an action that only responds to a single format by rendering a template, then you will only have a single template file, meaning that you can safely leave off the format part of the extension (e.g. `index.erb` is fine since the action only uses a single template file).

In this case, the only time this bug will crop up is when you have an action that uses a single non-html template but you create a `.html` file for that action. I think this is probably a pretty rare case.

That being said, I do think it's a little counterintuitive that template handlers may be used to render formats for which they weren't designed. I would expect only to be able to use `builder` for JSON data, for example. `index.html.builder` doesn't make any sense. But I suppose it doesn't technically do any harm to allow me to create such a template, if I really want to 😄

**Comment by pixeltrix** [comment]
> Again, I would expect that without two levels of extensions (e.g, .html.erb) that the extension would only work for a single format using that single handler.

@bboe where there is a single extension that is treated as the handler, not the format - assuming that a single extension indicates format == handler doesn't work because of erb, builder, etc. that are independent of the format.

@alexsanford `builder` is fine for HTML since HTML > XML - I think you're confusing it with `jbuilder` :smile:

Whether fixing this is worthwhile is debatable since it will add overhead to template resolution and we'd need to change the method signature for [`register_template_handler`][1] to accept a list of applicable formats - which would affect third party gems like haml, etc.

[1]: https://github.com/rails/rails/blob/1fd1fc3/actionview/lib/action_view/template/handlers.rb#L29-L35

**Comment by alexsanford** [comment]
@pixeltrix Haha. Whoops! Yes, definitely getting it mixed up with `jbuilder`. I think the point still stands though.

Yeah I'm thinking based on my points above that it's probably not worth the additional overhead. That being said, if we did want to make the change, we could change the `register_template_handler` signature in a backwards-compatible way by adding an optional `formats` argument. If it's not specified, default to allowing all formats. This way third-party gems wouldn't be affected.

**Comment by NicosKaralis** [comment]
Is this problem active? I have a similar problem with my `coffee` view files

http://stackoverflow.com/questions/40676703/coffeescript-part-being-ignored

**Comment by pixeltrix** [comment]
@NicosKaralis are you sure it's the same problem - the error in your SO post seems to suggest it's raising a CORS error. Can you create a simple app in a repo that I can have a look at?

**Comment by NicosKaralis** [comment]
I'm not sure if it is that same problem, it looks like it is. But I couldn't find how rails handles multiple handlers for a single format.

The is no CORS error

The exception you see there is because rails is rendering the `.html.erb` file with the `js` processor, if you check the logs it is pretty clear. The html rendered have `script` tags and other html tags that the `js` processor cannot handle and thus raise an exception

This is the explanation of the error:
```
Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.
```

```
Processing by Admin::SessionController#new as JS <- Request js
  Rendering admin/session/new.html.erb
  Rendered admin/session/new.html.erb (6.1ms)        <- Rendered html to a js request
```

**Comment by NicosKaralis** [comment]
Also, forgot to mention

I'm not doing a request with ajax. I literally just opened the request with a `.js` on the browser

```
Started GET "/login.js" for 127.0.0.1 at 2016-11-18 10:12:18 -0200
```

**Comment by pixeltrix** [comment]
@NicosKaralis okay, but according to the lines you're pointing out the template it's rendering is `new.html.erb` and this bug is about rendering `*.html` in response to non-HTML requests because `:html` is in the list of handlers in Rails 5.0. This is obviously not the same scenario so please create a new issue with steps to reproduce if you think there's a bug.

**Comment by NicosKaralis** [comment]
@pixeltrix c'mon man. Im requesting the `js` template and it is giving me the `html` template, which is:

> rendering *.html in response to non-HTML requests

I've also created an issue for my problem here #27095

**Comment by pixeltrix** [comment]
@NicosKaralis thanks for opening a new issue but it's not the same, because it's rendering the HTML format in response to a JS request using the ERB hander and not rendering using the HTML handler when there's no format (i.e. your template is `new.html.erb` not `new.html`).
