### ISSUE TITLE
ActionDispatch::Routing::RouteSet#url_for doesn't take defaults into consideration

### ISSUE THREAD

**Issue by davidcornu** [rails/rails#26126]
### Steps to reproduce

**Test case:** https://gist.github.com/davidcornu/23ca66e62f34add9bbd4aea49a4eefaf

Given the following `config/routes.rb`

``` ruby
Rails.application.routes.draw do
  resources :users, path: "/users/:category", defaults: { category: "admins" }
end
```

the path helper works as expected

```
irb(main):001:0> Rails.application.routes.url_helpers.users_path
=> "/users/admins"
```

but `ActionDispatch::Routing::RouteSet#url_for` fails to find the route.

```
irb(main):002:0> Rails.application.routes.url_for(controller: 'users', action: 'index', only_path: true)
ActionController::UrlGenerationError: No route matches {:action=>"index", :controller=>"users"}
```

This is happening because [`ActionDispatch::Journey::Formatter#match_route`](https://github.com/rails/rails/blob/b9f71e49ae43c53258da95bda50325a8d0c99a52/actionpack/lib/action_dispatch/journey/formatter.rb#L90) relies on [`ActionDispatch::Journey::Route#score`](https://github.com/rails/rails/blob/b9f71e49ae43c53258da95bda50325a8d0c99a52/actionpack/lib/action_dispatch/journey/route.rb#L98-L106) which uses [`ActionDispatch::Journey::Path::Pattern#required_names`](https://github.com/rails/rails/blob/b9f71e49ae43c53258da95bda50325a8d0c99a52/actionpack/lib/action_dispatch/journey/path/pattern.rb#L52-L54).

For that given route, `score` returns `-1` because `category` is a requirement

```
irb(main):001:0> route = Rails.application.routes.named_routes["users"]
=> #<ActionDispatch::Journey::Route:0x007f81b8c19b48 ...>
irb(main):002:0> route.score(controller: 'users', action: 'index')
=> -1
irb(main):003:0> route.path.required_names
=> ["category"]
irb(main):004:0> route.score(controller: 'users', action: 'index', category: 'editors')
=> 5
```
### Expected behaviour

`url_for` should have the same behaviour as the route helpers and take the defaults into consideration.
### System configuration

```
irb(main):001:0> Rails.version
=> "5.0.0"
irb(main):002:0> RUBY_VERSION
=> "2.3.1"
```

**Comment by davidcornu** [comment]
I'm have a tentative fix in https://github.com/rails/rails/compare/master...davidcornu:actionpack/url-for-path-defaults?expand=1.

**Comment by sgrif** [comment]
Can you provide a test case that uses our standard template ?https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb

**Comment by davidcornu** [comment]
@sgrif https://gist.github.com/davidcornu/23ca66e62f34add9bbd4aea49a4eefaf. Also added to the description.

**Comment by davidcornu** [comment]
@sgrif @pixeltrix any updates?

**Comment by pixeltrix** [comment]
@davidcornu sorry missed this as I was on holiday at the time. 

Defaults has never really worked this way - it's always either been a way of specifying a default value for an optional segment ( e.g. the default for `:action` being 'index' in `/:controller(/:action(/:id))` routes ) or actually passing a value in `params` from the routes.rb file.

I'm in two minds over whether to change this behaviour - it should have a low breakage count but I can see scenarios where it would break like the following:

``` ruby
get '/foo/:bar', to: 'foo#index', defaults: { bar: 'baz' }
get '/foo', to: 'foo#index'
```

If we were to change the behaviour to the way you're suggesting then:

```
url_for controller: 'foo', action: 'index'
```

would now generate `/foo/baz` instead of `/foo` like it did currently. This kind of breakage is subtle and easy to miss compared to an exception being raised so I'm leaning on the side of not changing it. However it does seem a little unexpected to not match that route so I'm not completely opposed to the change. I'll raise it in the campfire room and see what others think.

**Comment by davidcornu** [comment]
> I'll raise it in the campfire room and see what others think

@pixeltrix any updates? (sorry to pester)
