### ISSUE TITLE
Rails 4.2.7.1 generates new deprecation warnings in gems that did not previously generate them

### ISSUE THREAD

**Issue by joelpresence** [rails/rails#26142]
### Steps to reproduce
Thanks for your hard work on the 4.2.7.1 security update!  :-)

bundle update your Gemfile from rails 4.2.7 to 4.2.7.1
rake rails:update
rspec

Now, all of a sudden, I get a bunch of warnings like the following (which I never got before, and I have not changed the version of any other gems):
```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /Users/joel/.rvm/gems/ruby-2.2.2/gems/sass-rails-5.0.4/lib/sass/rails/railtie.rb:57)
```

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

Performing a simple rails security update should **NOT** cause new deprecation warnings.  These pollute the console log and make testing more difficult.

### Actual behavior
Tell us what happens instead

Security update from rails 4.2.7 to 4.2.7.1 causes new, previously-unseen deprecation warnings without changing versions of any other gems and without changing any code.

### System configuration
**Rails version**:
4.2.7.1

**Ruby version**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

**Comment by kaspth** [comment]
This happens because you don't have sprockets set with an upper bound, e.g. `gem 'sprockets', '< 3.7.0'`, in your Gemfile. As such this isn't Rails problem but one of how people manage their dependencies. In this case, `bundle update` also updates a Rails dependency .

You can check the git diff on your Gemfile.lock to see if the Sprockets version changed.

Thanks!

**Comment by joelpresence** [comment]
Thanks @kaspth .

However, I'd respectfully ask that this be re-opened.  I do not manage the version of the sprockets gem - rails does.  The sprockets gem is not even mentioned in my Gemfile nor is the sprockets gem mentioned anywhere in the Gemfile that `rails new myapp` creates.  So, respectfully, why is it "one of how people manage their dependencies" ... (And I do not mean that to sound sarcastic or snarky, it's just a question).  I'm not managing sprockets as a dependency, rails is, and if rails updates the version of sprockets and that then causes undesirable deprecation warnings, how is that not the "fault" of rails?

I also have the line
```
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
```
in my Gemfile, as many people do, because rails itself put that line there when I did `rails new myapp`.  So again, rails new I'd have a version of sass that might see this deprecation and yet rails still updated sprockets.

I do not want to update sass-rails since this is just a security update, so I want to make the update as minimal as possible.

Did somebody test this on the rails team?  I mean create a rails 4.2.7 app, then update to 4.2.7.1 and not see the deprecation warnings?

I don't understand ...

I don't see why the onus is on the end user to prevent these undesirable deprecation warnings.  Again, with respect.

Any suggestions for how to make this go away?

Thanks!

**Comment by kaspth** [comment]
Rails can't manage anything here. `bundle update rails` is all [Bundler's](http://bundler.io) work and Rails has no way to change what happens when you run that command.

It's true Rails has a dependency on Sprockets and that in turn forces you to deal with it when you run `bundle update rails`.

> rails knew I'd have a version of sass

We don't know what goes on in people's Gemfiles. We do ship default gems when people initially run `rails new`, but ultimately the Gemfile is your app's responsibility.

> I do not want to update sass-rails since this is just a security update, so I want to make the update as minimal as possible.

Right, and the only way to do that is to inspect the diff output in Gemfile.lock after `bundle update rails`. And revert gem changes you don't want.

> Did somebody test this on the rails team? I mean create a rails 4.2.7 app, then update to 4.2.7.1 and not see the deprecation warnings?

No, managing your apps dependencies, either a direct dependency or transient through a direct dependency, is your responsibility. I think your confusion stems from not knowing where Rails ends and Bundler begins. `rails new` and `rake rails:update` are Rails commands, while `bundle update` is all Bundler.

Hope that helps! 😄
