### ISSUE TITLE
Generating with --skip-action-mailer still generates app/mailers

### ISSUE THREAD

**Issue by bcardarella** [rails/rails#26145]
### Steps to reproduce

`rails new my-app --skip-action-mailer`

### Expected behavior
I would not expect the `app/mailers` directory to exist

### Actual behavior
The `app/mailers` directory is generated despite explicitly skipping `action-mailer` during app generation

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
Makes sense. Thanks!

**Comment by bcardarella** [comment]
@rafaelfranca I can try to PR if you'd like

**Comment by rafaelfranca** [comment]
That would be awesome. This happens because we do copy the entrire app template directory and mailers is present there https://github.com/rails/rails/tree/master/railties/lib/rails/generators/rails/app/templates/app. We should be removing the whole directory here https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/app_generator.rb#L322
