### ISSUE TITLE
Link to Rails Guide for 3.2 results in a 403 response

### ISSUE THREAD

**Issue by agrimm** [rails/rails#26171]
### Steps to reproduce

From http://edgeguides.rubyonrails.org/ , I click on the link for "Rails 3.2", and get taken to http://guides.rubyonrails.org/v3.2/

### Expected behavior
Guides for Rails version 3.2

### Actual behavior
403 Forbidden error message.

### System configuration
Not applicable - documentation related.

This has happened previously with #23984 and #24113 , but this one seems to be unrelated.

**Comment by vipulnsward** [comment]
cc @fxn

**Comment by prathamesh-sonpatki** [comment]
Noticed one more thing - http://guides.rubyonrails.org/v2.3/ redirects to http://edgeguides.rubyonrails.org/

**Comment by fxn** [comment]
Looking into this.

**Comment by RadicalZephyr** [comment]
Workaround for accessing at least a version of the 3.2 guides is googling for it.  I found this specific version works: http://guides.rubyonrails.org/v3.2.13/

**Comment by fxn** [comment]
These guides were not generated because 3.2.22.3 and 3.2.22.4 have missing requires in Action Pack the execution path of guides generation exposes.

The correct way to fix this is to patch the source tree in the [docs generator](https://github.com/rails/rails-docs-server), but I am there in the middle of a refactor and would take some days. So, I have added the requires manually and generated the docs.

Since strictly speaking the links are working now I think we can close this. The real fix in the docs generator and 3-2-stable will be eventually there.
