### ISSUE TITLE
Charset declaration on send_file lost

### ISSUE THREAD

**Issue by Confusion** [rails/rails#26298]
### Steps to reproduce
Use 
````
send_file filename, type: 'text/calendar; charset=utf-8'
````
as the last line in a controller, similar to an example in the documentation of `send_file`.

### Expected behavior
The http response contains the header 
````
Content-Type: 'text/calendar; charset=utf-8'
````

### Actual behavior
The http response contains the header 
````
Content-Type: 'text/calendar'
````

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

### Additional comments
During handling of the `send_file` call, the following effectively happens:
* at some point `content_type=` in ` actionpack-5.0.0.1/lib/action_dispatch/http/response.rb` is called with `'text/calendar; charset=utf-8'` as its argument.
* `parse_content_type` is called on the *current* `content_type`, which is `nil`
* `set_content_type` is called with `'text/calendar; charset=utf-8'` and 'utf-8' as arguments
* `set_header` is called with `"Content-Type"` and `"text/calendar; charset=utf-8; charset=utf-8"` [sic!] as arguments
* when execution returns to `send_file_headers!(options)`, we can see that `self.content_type` now returns the value `"text/calendar"`, even though `self.headers` contains:

         "Content-Type" => "text/calendar; charset=utf-8; charset=utf-8"
* one level further up, in `send_file` itself, there is a line

        self.content_type = options[:content_type] if options.key?(:content_type)

  but, as per the documentation, we were using the `:type` options, not `:content_type` and this doesn't fix things.
* The ultimate HTTP response contains `text/calendar`, without charset (neither once nor twice).

If you use `:content_type` instead of `:type`, you end up with the charset twice in the HTTP response.

If you use `content_type: 'text/calendar'` as the only argument to `send_file`, you get the response we wanted, but only because utf-8 is the default charset. A header with a different charset declaration seems impossible to create.

**Comment by aaronang** [comment]
To help out the Rails team, I have written a Ruby script that reproduces your problem.

<details>
  <summary>Click to expand</summary>
  ```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "rails", "5.0.0.1"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_token    = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/type" => "test#type"
    get "/content_type" => "test#content_type"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  FILE_NAME = "26298"

  def type
    send_file FILE_NAME, type: "text/calendar; charset=utf-8"
  end

  def content_type
    send_file FILE_NAME, content_type: "text/calendar"
  end
end

require "minitest/autorun"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  include Rack::Test::Methods

  FILE_NAME = "26298"

  def setup
    File.write(FILE_NAME, "Some content...")
  end

  def teardown
    File.delete(FILE_NAME)
  end

  def test_charset_with_type
    get "/type"
    assert_equal "text/calendar; charset=utf-8", last_response.original_headers["Content-type"]
  end

  def test_charset_with_content_type
    get "/content_type"
    assert_equal "text/calendar; charset=utf-8", last_response.original_headers["Content-type"]
  end

  private
    def app
      Rails.application
    end
end
```
</details>

**Comment by maclover7** [comment]
@Confusion, thanks for reporting this (and for providing such a nice walkthrough in your issue description)! (also thanks to @aaronang for creating a super helpful reproduction script!)

Investigating.

**Comment by maclover7** [comment]
So, I think I've found the source of what's causing this behavior. It stems from calling `response.sending_file = true` [here](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/data_streaming.rb#L139). In that method, we are mutating the headers hash, and are removing the charset. If the contents of that method are commented out, then both tests specified above pass. Not completely sure how we want to approach addressing this ticket, since technically speaking this behavior has existed since 2006. 😢 

(for anyone curious, here's the commit history for this feature --> https://github.com/rails/rails/commit/0adbeeb0c92c6de2e4a148e4b54d56cd4a325800, https://github.com/rails/rails/commit/f8f077945f4d108d676384106a9dfcf5c6f7a33d, https://github.com/rails/rails/commit/396b3f2befe5d75ac04e732eae195dc6d9d20201)

Also, small sidenote, we should probably deprecate the duplicative `:content_type` key in the options hash for `send_file` at some point in the future, after a verdict is reached on this ticket. 😬

**Comment by Confusion** [comment]
>  this behavior has existed since 2006.

There is something important I forgot to mention: I discovered this behavior after upgrading an app from Rails 4.1.4 to Rails 5.0.0.1. A test case on an HTTP response started failing. I just checked out the previous version to double check and Rails 4.1.4 correctly returns a `Content-Type: text/calendar; charset=utf-8` header.

**Comment by pixeltrix** [comment]
For context the `#6689` in 396b3f2 is an [old Trac ticket][1] - and not a GitHub PR. Looks like that was to prevent setting the default charset when sending a binary file which we shouldn't do but if @Confusion is correct we broke something either in 4.2 or 5.0.

[1]: https://web.archive.org/web/20061127231756/http://dev.rubyonrails.org/ticket/6689

**Comment by pixeltrix** [comment]
@Confusion a quick check with @aaronang's test script is failing in 4.1.4, 4.1.16, 4.2.7.1 and 5.0.0.1 for me - is it reproducing the problem correctly?

**Comment by Confusion** [comment]
@pixeltrix @aaronang's test script tests two cases: one using `type` and one using `content_type`. With 5.0.0.1 the one using `type` fails; with 4.1.4 the one using `content_type` fails. I think the one with `type` is the one we expect to pass, as it matches the documentation. I'm not clear on the behavior we expect from the use of `content_type`. So I think it reproduces the problem correctly, but includes an additional test that may be confounding.

**Comment by pixeltrix** [comment]
@Confusion thanks for clearing that up - yes, it looks like some of the refactoring that Aaron did in this area for Rails 5.0 changed the behaviour subtlety.

**Comment by pixeltrix** [comment]
@maclover7 whilst the behavior of not returning the default charset when sending a file has been around since 2006 what's changed in Rails 5.0 is that the response class doesn't realize that it's got an explicit charset so removes it all the time when using `:type` and when using `:content_type` it's using `ActionDispatch::Response#content_type=` which resets the charset because the response class no longer maintains an instance variable of the fact that it's sending a file. Coupled with the error that the method also doesn't check for the presence of the charset when setting the content type means that you get two charsets when passing `:content_type`.

I think since we've not explicitly deprecated `:type` we need to restore the behavior of 4.2 and earlier. I think also in the long run we want to maintain the separate options since there is extra logic layered on `:type` that we wouldn't want to transfer to `:content_type`.

**Comment by maclover7** [comment]
Found the commit that's causing this errant behavior, getting a patch ready locally.

**Comment by maclover7** [comment]
PR #26317 should fix this issue, the reproduction script is passing for me on master. PR 26322 will backport the changes to `5-0-stable`. 🎉
