### ISSUE TITLE
request.domain returns co.uk from domain.co.uk

### ISSUE THREAD

**Issue by kjellberg** [rails/rails#26304]
### Expected behavior
```ruby
request.domain => domain.co.uk
```

### Actual behavior
```ruby
request.domain => co.uk
```

### System configuration
**Rails version**:
5.0.0.1
**Ruby version**:
2.3.1p112

**Comment by prakashmurthy** [comment]
`request.domain(2)` gives `domain.co.uk`

The [tests for the domain functionality](https://github.com/rails/rails/blob/a63de6db433dffb610509a65aed02991aa718c32/actionpack/test/dispatch/request_test.rb#L270-L277)

**Comment by maclover7** [comment]
Hi @kjellberg!

Though this may seem unexpected, this is the expected behavior from `ActionDispatch::Request`.

I've created a small reproduction script [here](https://gist.github.com/maclover7/3dbe417bd5b43f6b5e457f408b75f845) to try and demonstrate this behavior. You can check out the relevant part of `ActionDispatch::Request`'s source here --> https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/url.rb#L328-L332.

If there's any way that you feel that this could be better documented, please feel free to open up a pull request. Thanks again for opening up this issue! :)

**Comment by kjellberg** [comment]
Yes, I know there is a parameter for the tld length. But why would you use `request.domain` if you have a static domain that you already know? Just to make it look cool? That makes no sense.

You want to use `request.domain` when you don't know the domain or when you're using multiple domains for one application. Or what if someone is developing an open source application? 

```ruby
# www.domain.co.uk
request.domain(2) => www.domain.co.uk # sure it works
# but...
# username.domain.com
request.domain(2) => username.domain.com
```

With `request.domain(2)` .com domains will return the subdomain instead so that doesn't solve the problem. 

**This issue should be opened again and labeled as a bug.** 

Here is a list of all the official second-level domains. Maybe they could be hard-coded into somewhere?

[https://en.wikipedia.org/wiki/Second-level_domain](https://en.wikipedia.org/wiki/Second-level_domain)
