### ISSUE TITLE
Calling as_json on non-ActiveRecord models does not serialize properly when passed with option :only

### ISSUE THREAD

**Issue by alexssung** [rails/rails#26312]
### Steps to reproduce
Given a non-ActiveRecord model, e.g:

    def DailyForm
      include ActiveModel::Model
      attr_accessor :date, :rows
    end

with :rows being an array of hashes

### Expected behavior
    d = DailyForm.new(date: Date.today, rows: [{a: 1}, {b: 2}])
    d.as_json(only: 'rows')
    #=> {"rows"=>[{"a"=>1},{"b"=>2}]}

### Actual behavior
    d = DailyForm.new(date: Date.today, rows: [{a: 1}, {b: 2}]
    d.as_json(only: 'rows')
    #=> {"rows"=>[{},{}]}

### Relevant details
Calling as_json on the model with no options serializes the full object properly
Calling as_json with option :except on other attributes also serializes the object properly
Therefore this bug seems to be exclusive to the :only option for as_json

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.1

**Comment by bf4** [comment]
That because they don't include `ActiveModel::Serializers::JSON`

**Comment by alexssung** [comment]
Thanks, I just found out about ActiveModel::Serializers::JSON and it solves this issue.

However, I feel that there is still a bug since as_json can be called on any class in Rails without including that module. The :only option should still be able to serialize the given attribute properly.

**Comment by maclover7** [comment]
Hi @alexssung! The reason why the default `as_json` method doesn't work with the `only` option is because that isn't supported behavior 😬. You can take a look through that method's source [here](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/json.rb).  If you want to serialize an Active Model object to JSON and [use `only`](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/serialization.rb#L128), you'll have to go through Active Model. 😬
