### ISSUE TITLE
Database drop task loads route file

### ISSUE THREAD

**Issue by Hugo-Hache** [rails/rails#26319]
### Steps to reproduce

1. Create a Rails 5 project
2. Insert a log in config/routes.rb
3. Run `bundle exec rails db:drop`
4. See you log waving at you in the terminal

### Expected behavior
Prior to version 5 route file was not loaded when using `bundle exec rake db:drop`
### Actual behavior
Route file is loaded when db:drop command runs `bundle exec rails db:drop`

### Why is it problematic ?
Some gem, as Devise, loads model in route file, and some logic in the model may try to execute database calls. If the database does not exist, which might be the case when running db:drop, the command will crash. 
It would have been much more problematic if it was also the case in database create task, but surprisingly the create task does not load the route file. 

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by prathamesh-sonpatki** [comment]
This is because `rake db:drop` invokes `check_protected_environments` which loads the environment. But that happens **before** dropping the database. So `routes.rb` or any other config file gets loaded when the database is present.

Can you upload a sample application on Github that reproduces the issue? Thanks.

**Comment by Hugo-Hache** [comment]
You can find a sample application here https://github.com/Hugo-Hache/DropDemo.

**Comment by prathamesh-sonpatki** [comment]
prathamesh ~/Projects/reproductions/DropDemo 2.3.1 (Hugo-Hache/DropDemo) -> master
$ be rake db:create
Created database 'DropDemoDev'
Created database 'DropDemoTest'

prathamesh ~/Projects/reproductions/DropDemo 2.3.1 (Hugo-Hache/DropDemo) -> master
$ be rake db:migrate
Loading routes

prathamesh ~/Projects/reproductions/DropDemo 2.3.1 (Hugo-Hache/DropDemo) -> master
$ 

prathamesh ~/Projects/reproductions/DropDemo 2.3.1 (Hugo-Hache/DropDemo) -> master
$ be rake db:drop
Loading routes
Dropped database 'DropDemoDev'
Dropped database 'DropDemoTest'

Not able to reproduce using the sample application.

**Comment by prathamesh-sonpatki** [comment]
Giving it a close for now, it looks like some third party issue. The `rake db:drop` task loads the enviornment, but as I said earlier, it happens before dropping the database. Same happens while migrating as well.

Thanks @Hugo-Hache

**Comment by Hugo-Hache** [comment]
It crashes only when you run db:drop and the database does not exist. I stated it in my issue description: 

> If the database does not exist, which might be the case when running db:drop, the command will crash.

If I stick with your workflow, adding one last db:drop triggers the crash:

```
be rake db:create
be rake db:migrate
be rake db:drop
be rake db:drop
```

**Comment by prathamesh-sonpatki** [comment]
If we try to drop already dropped database with sample app, we get this errror.

```
$ be rake db:drop
Loading routes
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "DropDemoDev" does not exist
/Users/prathamesh/Projects/reproductions/DropDemo/config/routes.rb:3:in `block in <top (required)>'
/Users/prathamesh/Projects/reproductions/DropDemo/config/routes.rb:1:in `<top (required)>'
/Users/prathamesh/Projects/reproductions/DropDemo/config/environment.rb:5:in `<top (required)>'
/Users/prathamesh/.rbenv/versions/2.3.1/bin/bundle:22:in `load'
/Users/prathamesh/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
PG::ConnectionBad: FATAL:  database "DropDemoDev" does not exist
/Users/prathamesh/Projects/reproductions/DropDemo/config/routes.rb:3:in `block in <top (required)>'
/Users/prathamesh/Projects/reproductions/DropDemo/config/routes.rb:1:in `<top (required)>'
/Users/prathamesh/Projects/reproductions/DropDemo/config/environment.rb:5:in `<top (required)>'
/Users/prathamesh/.rbenv/versions/2.3.1/bin/bundle:22:in `load'
/Users/prathamesh/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
Tasks: TOP => db:drop => db:check_protected_environments => environment
(See full trace by running task with --trace)
```

Now I removed the line 3 from routes.rb which tries to access the models and try to drop again.

Then also I get same error.

```
$ be rake db:migrate
Loading routes
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "DropDemoDev" does not exist
/Users/prathamesh/.rbenv/versions/2.3.1/bin/bundle:22:in `load'
/Users/prathamesh/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
PG::ConnectionBad: FATAL:  database "DropDemoDev" does not exist
/Users/prathamesh/.rbenv/versions/2.3.1/bin/bundle:22:in `load'
/Users/prathamesh/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

I don't think we should do anything in this case :)

**Comment by shakycode** [comment]
If the db doesn't exist and you try to drop shouldn't you expect an error?  This seems like semi normal behavior unless I'm reading this out of context. Unless you want a cleaner error with no trace.

**Comment by Hugo-Hache** [comment]
I encountered this crash on my CI server. My build script starts by a db:drop, db:create to ensure I start from a fresh clean database. 

I agree that it's a border case to call drop whereas the db does not exist. However I opened this issue for 2 reasons: 
- this use case was not crashing with Rails 4. I thought maybe I faced a regression.
- it would be nice to have a task able to enforce you're working on a brand new database. Currently I only see the drop if needed and create process.

Btw thanks for the time you're spending on this very specific issue 👍

**Comment by prathamesh-sonpatki** [comment]
Thanks @Hugo-Hache for the explanation. 

In CI you can solve this issue by using `DISABLE_DATABASE_ENVIRONMENT_CHECK=1`  before the command.

This will prevent the loading of environment and should have Rails 4 behavior. I have not verified it by myself but I think it will work :) 

You can find more details about this feature in https://github.com/rails/rails/pull/22967 Thanks!!

**Comment by brightbytes-dude** [comment]
Setting that ENV var does not fix the problem:

```
$ DISABLE_DATABASE_ENVIRONMENT_CHECK=1 rake db:drop
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "sql_cms_development" does not exist
... etc ...
```

And, similarly, this made me LOL, it's so in-my-face:  :-)

```
$ DISABLE_DATABASE_ENVIRONMENT_CHECK=1  bin/rails db:environment:set RAILS_ENV=development
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "sql_cms_development" does not exist
... etc ...
```

I'm using Rails 5.0.2, though the same issue occurred on 5.0.1.

My context is that I have a script that I use to recreate my local dev env for my app, and the script starts out by calling the following task, which works great once the DB has been created the first time.

`task recreate: ['db:drop', 'db:create']`

All naive attempts at scripted hackarounds fail: 

- If I change this to `db:create`, `db:drop`, `db:create`, Rake ignores the 2nd `db:create` because it's a dup dependency.  

- Same deal if I move the `db:create` into the block and do a Rake::Task['db:create'].invoke.

- If I shell-out to do `rake db:create` within the block for the `recreate` task, the `db:migrate` that comes after the `db:recreate` fails with `ERROR:  relation "schema_migrations" does not exist`.

I can see how this functionality could be very useful for preventing the dropping of a DB in production by a novice developer.

In the end, I just have to instruct new devs who wish to collaborate on my project to run `rake db:create` before running the automated script the first time.  Which is why this isn't a big deal, though it would be nice if the advertised method of disabling this check in development actually worked.  :-)
