### ISSUE TITLE
update and update_attributes are aliases for each other but still behaves differently. update doesn't provide any chnages in after_update callback but update_attributes does

### ISSUE THREAD

**Issue by ashutosh-singh-rawat** [rails/rails#26339]
### Steps to reproduce
class Task < ActiveRecord::Base
  after_update  :check_chnaged_attributes
  def check_chnaged_attributes
    puts self.chnages
  end
end

### Expected behavior
Both cases should return similar to this {"title"=>["213", "xyz"], "updated_at"=>[Wed, 31 Aug 2016 20:36:36 AEST +10:00, Wed, 31 Aug 2016 21:16:23 AEST +10:00]}

### Actual behavior
#update
Task.first.update(title: "xyz") gives {}

#update_attributes 
Task.first.update_attributes(title: "xyz") gives {"title"=>["213", "xyz"], "updated_at"=>[Wed, 31 Aug 2016 20:36:36 AEST +10:00, Wed, 31 Aug 2016 21:16:23 AEST +10:00]}

### System configuration
**Rails version**:
5.0.0
**Ruby version**:
2.3.1

**Comment by sgrif** [comment]
I'm unable to reproduce this using the steps provided. Given that as you've mentioned, those methods are simply aliases for each other, this is likely a bug in another gem or some other code in your application which is overriding one but not the other.

Keep in mind that if no attributes have changed (which is what would be the case if you ran exactly your code since you're just assigning the same value twice) then an empty has would be expected.

**Comment by alexcameron89** [comment]
> Keep in mind that if no attributes have changed (which is what would be the case if you ran exactly your code since you're just assigning the same value twice) then an empty has would be expected.

@ashutosh-singh-rawat  I tried reproducing this, and the likely reason you're having this issue is because the second update is trying to update the same record, which already has that title. If you change the title to something different in the second update(like "abc"), then you will see a `changes` hash.
