### ISSUE TITLE
DateTime not working properly.

### ISSUE THREAD

**Issue by rahul8sharma** [rails/rails#26369]
### Steps to reproduce

Input: DateTime.new(2007,11,19,8,37,48,"IST")
Output: Mon, 19 Nov 2007 08:37:48 +0530 (Correct)
Input: DateTime.new(2007,11,19,8,37,48,"MYT")
Output: Mon, 19 Nov 2007 08:37:48 +0000 (Incorrect)

Not Working for "MYT".

### Expected behavior
It should be "Mon, 19 Nov 2007 08:37:48 +0800"

### Actual behavior
Mon, 19 Nov 2007 08:37:48 +0000

### System configuration
**Rails version**: 4.2.3

**Ruby version**: 2.2.2

**Comment by maclover7** [comment]
Hi @rahul8sharma! `DateTime` is a class that's provided via Ruby's standard library, and although Rails does overwrite and add some new methods, I don't believe we touch the `new` method. The best advice I can offer would be to check [Ruby's documentation about `DateTime#new`](https://ruby-doc.org/stdlib-2.2.2/libdoc/date/rdoc/DateTime.html#method-c-new), and to maybe ask around on Stack Overflow for some help, since Rails is not at fault for this error. Thanks for opening up this issue! :)

**Comment by rahul8sharma** [comment]
Thank you @maclover7
