### ISSUE TITLE
mattr_accessor ignore access modifiers 

### ISSUE THREAD

**Issue by tbrisker** [rails/rails#26461]
### Steps to reproduce

`mattr_accessor` and all related functions disregard access modifiers (i.e. private/protected) and always creats public functions. This should either be documented or changed to respect modifiers.

Simple reproducer class:

``` ruby
class MyClass
  private
  cattr_accessor :private_name
end
```
### Expected behavior

``` ruby
pry(main) > MyClass.private_name
NoMethodError:  private method 'private_name' called for MyClass:Class
```
### Actual behavior

``` ruby
pry(main) > MyClass.private_name
=> nil
```
### System configuration

**Rails version**: 4.2.7.1

**Ruby version**: 2.0.0

**Comment by maclover7** [comment]
Hi @tbrisker! Unfortunately, I think this is the expected behavior, and I'm not sure what Rails can best do to support this use case. The `cattr_accessor` macro ends up calling some code which defines the reader/writer at the end of the file, not exactly where you call `cattr_accessor`. You can check out the source for this [here](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/core_ext/module/attribute_accessors.rb). Not sure if there's anything we can change here 😢

**Comment by tbrisker** [comment]
Thanks for your feedback @maclover7! 

Upon further digging, it would seem the issue lies with the fact the class methods are public by default, unless `private_class_method` is called explicitly on the method, or the method is defined inside the private block of the class singleton object. For example:

```ruby
[19] pry(main)> class MyClass
[19] pry(main)*   private  
[19] pry(main)*   def self.ddd
[19] pry(main)*     puts "ddd"
[19] pry(main)*   end  
[19] pry(main)* end  
=> nil
[20] pry(main)> MyClass.ddd
ddd
=> nil
```

So this is expected behaviour indeed.
However, I would suggest mentioning this in the documentation, both to clarify this, and since these functions also define instance accessors - which one may expect to respect the access modifier.

**Comment by maclover7** [comment]
@tbrisker Feel free to send a PR to the docs, I'm happy to merge it :)

**Comment by tbrisker** [comment]
@maclover7 Thanks, #26480 opened in attempt to clarify this.
