### ISSUE TITLE
Documentation clarification for url_for and engines

### ISSUE THREAD

**Issue by blakeloverain** [rails/rails#26464]
The routing guide should mention  at least briefly how to reference url's directly using :controller, :action, etc as is mentioned in the  API docs, rather than the helper functions <controller>_path, etc. ie something like:

<%= link_to("Update magazine", {controller: :magazine, action: :edit, id: @magazine.id}); %>

It's also helpful to know how to access url's that never will have resource-ful routing built in, ie explicit get/post routes. Since it's clearly documented how to create an arbitrary route, there should be something mentioning how to access that route as well without using the path helpers.

There's also not enough clarification between the routing guide and the engine guide on how to access an engine's controller's url's for link_to or url_for. It's only mentioned in the API here: 

http://edgeapi.rubyonrails.org/classes/Rails/Engine.html#class-Rails::Engine-label-Using+Engine-27s+routes+outside+Engine

Even then, it mentions nothing about how to call url_for within a given engine, which ought to be like my_engine.url_for(controller: my_controller, action: 'index') 

It might also be useful to mention an example url_for or link_to call:

link_to("View engine's widget", [my_engine, @widget])

Regardless, the "guides" that are my first stop (and probably the same for most people) ought to mention the my_engine.edit_widget_path(@widget) syntax. 

It would also be really helpful if the routing debugger at /rails/info/routes would mention the engine's variable name, ie instead of listing edit_magazine_path, etc for MyEngine, either having it mentioned as my_engine.edit_magazine_path or write a small blurb about prefixing with my_engine when not in the engine (ie different part of app). It's confusing why the debugger mentions edit_magazine_path, and yet I get an immediate error when I use that unqualified outside of the engine.

**Comment by maclover7** [comment]
@blakeloverain If you'd like to submit a PR to make some changes to the documentation, please do so! :)

**Comment by FunkyloverOne** [comment]
@blakeloverain, maybe I just do not know something... But this example:
`<%= link_to('Public posts', {controller: 'posts', action: 'public'}) %>`
is just **not working** when in my routes I have
`get 'public', to: 'posts#public', as: :public_practices`
The resulting link will be just `/`, instead of `/public`.

So the question is: is that behavior a bug, or there is something i got to config to make it work?

P.S It works correctly when I explicitly give it a url like this:
`<%= link_to('Public posts', public_posts_path) %>`

P.P.S I know that my route might be written in more resourceful style like this:
```
resources :posts do
  get 'public', on: :collection
end
```
But this will generate the url `/posts/public` and I want it to be just `/public`.
