### ISSUE TITLE
define_attribute_methods signature mismatch between ActiveModel and ActiveRecord

### ISSUE THREAD

**Issue by tilo** [rails/rails#26533]
### Steps to reproduce

1) define an ActiveRecord model
2) attr_accessor :virtual_attr1, :virtual_attr2
3) try to add a virtual attribute to the attribute methods:

define_attribute_methods :virtual_attr1, :virtual_attr2
=>
/Users/tilo/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.4/lib/active_record/attribute_methods.rb:79:in `define_attribute_methods': wrong number of arguments (given 2,  expected 0) (ArgumentError)

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

define_attribute_methods should add the names of the virtual attributes to the model.

ActiveRecord should not define a method with the same name, but different signature.

### Actual behavior
Tell us what happens instead

Rails called the 'define_attributes_method' from ActiveRecord instead of ActiveModel,
which does not have the same invocation / behavior

### System configuration
**Rails version**: 4.2.4

**Ruby version**:
2.3.1

**Comment by maclover7** [comment]
Hi @tilo! Per the documentation, the `define_attribute_methods` method is only public API in Active Model, and not in Active Record. In Active Model, the method is [documented(http://api.rubyonrails.org/classes/ActiveModel/AttributeMethods/ClassMethods.html#method-i-define_attribute_methods), and is for public consumption. On the other hand, in Active Record, the method is [`:nodoc:`'d](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods.rb#L55), meaning that it is available publicly, but is for internal usage only. This is expected behavior you are running into 😢
