### ISSUE TITLE
config.ssl_options are not passed to ActionDispatch::SSL

### ISSUE THREAD

**Issue by samphilipd** [rails/rails#26651]
### Steps to reproduce

In `config/development.rb` add these lines:

```
  config.ssl_options = {
    redirect: {
      exclude: -> (request) { warn request.path }
    },
    secure_cookies: false,
    hsts: {
      subdomains: false
    }
  }
```

### Expected behavior
Path should get warned to console.

### Actual behavior
Nothing gets logged to console.

Additionally in `ActionDispatch::SSL#initialize` none of the correct options are passed in.

### System configuration
**Rails version**:
5.0.0.1

**Ruby version**:
2.3.1

**Comment by rafaelfranca** [comment]
Maybe because you have the file `config/initializers/new_framework_defaults.rb` with the `config.ssl_options` being overridden there? https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults.rb.tt#L33

**Comment by samphilipd** [comment]
Oh! You are right. Thanks, this can be closed.

**Comment by techgique** [comment]
Was perplexed by this for a while. Documentation (http://api.rubyonrails.org/classes/ActionDispatch/SSL.html) makes no mention of this and there are no warnings. Won't everyone who generates a new Rails 5 app run into this issue? "Why aren't my config.ssl_options values being used!?"

I altered the code in the initializer in a way I think is friendlier and doesn't block users' config.ssl_options settings. If this seems appropriate, I'll be glad to submit a PR.

~~Rails.application.config.ssl_options = { hsts: { subdomains: true } }~~

```ruby
if Rails.application.config.ssl_options[:hsts].nil? || Rails.application.config.ssl_options[:hsts][:subdomains].nil?
  Rails.application.config.ssl_options[:hsts][:subdomains] = true
end
```

**Comment by matthewd** [comment]
@techgique it'll need to look a bit different to that, but sure, please do PR away.

**Comment by techgique** [comment]
Oops. Noticed that had a bug in that code this morning. If run in an environment without `config.ssl_options` set, it dies because the hsts associative array isn't initialized yet.
Needs to be:
```ruby
if Rails.application.config.ssl_options[:hsts].nil? || Rails.application.config.ssl_options[:hsts][:subdomains].nil?
  Rails.application.config.ssl_options[:hsts] = {}
  Rails.application.config.ssl_options[:hsts][:subdomains] = true
end
```

I haven't contributed before but the documents suggest writing a test for all PRs. I don't see a pre-existing test for the code within that initializer though. Just tests for the non-existence of that file if an app is updated or whether certain lines are printed in it if other features are disabled. Would I need to add a test for it or can I just pull down the rails repo, add this, and submit a PR quick?

**Comment by matthewd** [comment]
Railties has tests for the application generators. You could add a test that sets ssl_options in development.rb, then confirms the final value is the combined result.

**Comment by samphilipd** [comment]
@techgique may I suggest instead?

```ruby
Rails.application.config.ssl_options[:hsts] ||= {}
Rails.application.config.ssl_options[:hsts][:subdomains] ||= true
```

**Comment by lorenzsell** [comment]
I seem to be having trouble with the config.ssl_options.  I'm trying to get my application exclude certain subdomains from the force_ssl option.  It works locally, but in production does not.  Right now, force_ssl is preventing me from accessing mail.sutra.co, which points to google because it tries to force an ssl connection.

Here is the code:

```
config.force_ssl = true
config.ssl_options = { redirect: { exclude: -> (request) { return true if ((request.subdomain =~ /mail|link|blog/) != nil) } } }
```
As I mentioned, this works as expected locally.  I'm tried posting elsewhere but have not found an answer to this issue.
