### ISSUE TITLE
Scope with #or generate incorrect SQL

### ISSUE THREAD

**Issue by crawfoal** [rails/rails#26662]
### Steps to reproduce

Write a scope that calls `#or`:
```ruby
class Post < ActiveRecord::Base
  scope :or_empty, -> { self.or where(body: nil) }
end
```
Use it:
```ruby
Post.where(body: 'Today was a sad day :(').or_empty
```

### Expected behavior
Assuming both an empty post, and one with a body of "Today was a sad day :(" have been created, I'd expect the above to return two records.

### Actual behavior
Only the "Today was a sad day :(" post is returned.

The SQL that is generated is this:

```sql
SELECT COUNT(*) FROM "posts" WHERE ("posts"."body" = ? OR "posts"."body" = ? AND "posts"."body" IS NULL)  [["body", "Today was a sad day :("], ["body", "Today was a sad day :("]]
```

And for reference, what I'd expect is this:
```sql
SELECT COUNT(*) FROM "posts" WHERE ("posts"."body" = ? OR "posts"."body" IS NULL)  [["body", "Today was a great day!"]]
```
This is the SQL generated from calling `#or` directly, like this:
```ruby
Post.where(body: 'Today was a great day!').or(Post.where(body: nil))
```

### System configuration
**Rails version**: master

**Ruby version**: 2.3.1

**Comment by crawfoal** [comment]
When I was reading through the documentation on `scope`, I noticed this:

> A scope represents a narrowing of a database query

I had been thinking of scopes as just a nice way to package up a query in a re-useable way... so maybe I'm just trying to use scopes incorrectly, or maybe they should be modified to support this... (sorry if this should be considered a feature request, at first I thought it was definitely a bug).

**Comment by matthewd** [comment]
Yeah, this is expected behaviour.

If we expand the (explicit and implied) `self` references in your scope, we get:

```ruby
Post.where(body: 'Today was a sad day :(').or
  Post.where(body: 'Today was a sad day :(').where(body: nil)
```

The trouble with putting "half" the or condition in a scope is that it's not clear how far to stretch it.

```ruby
scope :or_happy, -> { self.or where("body LIKE '%:)'") }

Post.where("body LIKE 'Today%'").where(body: 'Today was an interesting day :|').or_happy
```

Does the above intend `today AND (interesting OR happy)`, or `(today AND interesting) OR happy`?

(As you've seen, what it actually ends up meaning is the far less useful `(today AND interesting) OR (today AND interesting AND happy)`.)

---

The closest I can think of to approximate your intent would be:

```ruby
scope :or_empty, -> &b { b.call(self).or where(body: nil) }

Post.or_empty { |x| x.where(body: 'Today was an interesting day :|') }
```

or

```ruby
scope :empty, -> { where(body: nil }

Post.where(body: 'Today was an interesting day :|').or(Post.empty)
```

But generally, my recommendation would be to rearrange the scope so it can apply both sides of the condition itself:

```ruby
scope :worth_remembering, -> {
  where(body: 'Today was an interesting day :|').or where("body LIKE '%:)'")
}
```

**Comment by crawfoal** [comment]
@matthewd Thanks for the helpful examples and suggestions!
