### ISSUE TITLE
Nesting of framesets when clicked on "API documentation link" on welcome page of api.rubyonrails.org

### ISSUE THREAD

**Issue by shirishwebonise** [rails/rails#26667]
### Steps to reproduce

Go to [api.rubyonrails.org](http://api.rubyonrails.org/)
Click on "API documentation" link

this will open up same page inside the frameset as a new frame.

Again click on the "API documentation" link

this will open up same page as a frame in the inner frameset
### Expected behavior

should do nothing when clicked on "API documentation" link
or should reload the page
### Actual behavior

Opens the page inside a frameset over and over as and when clicked on the link, in a nested fashion

**Comment by claudiob** [comment]
This could be fixed by adding 

```html
<base target="_parent" />
```

in the `<head>` of the page.

However, the page is generated with sdoc, which processes the [RDOC_MAIN.rdoc](https://github.com/rails/rails/blame/master/railties/RDOC_MAIN.rdoc#L62) file, so in order to add the `<base>` tag, we would need to change both rails and the source code of sdoc, somewhere around here: https://github.com/zzak/sdoc/blob/master/lib/rdoc/generator/template/rails/index.rhtml#L7

@zzak @fxn … what do you think?
