### ISSUE TITLE
JSON attributes out of strong parameters

### ISSUE THREAD

**Issue by thiagogsr** [rails/rails#26708]
### Steps to reproduce

My model

``` ruby
class User < ApplicationRecord
  attr_accessor :xyz # ActiveRecord - column in database
  validates :foo, :bar, presence: true
  store_accessor :settings, :foo, :bar
end
```

My Controller

``` ruby
def user_params
  params.require(:user).permit(:foo, :bar, :xyz)
end
```

Rails log

```
# POST /users { "foo": 10, "bar": 0, "xyz": 99 }
Processing by UsersController#create as JSON
  Parameters: {"foo"=>10, "bar"=>0, "xyz"=>99, "user"=>{"xyz"=>99}}
```
### Expected behavior

Access the `user_params` and return the `foo` and `bar` params.
### Actual behavior

So, I can't access the `json` attributes in my controller unless I call the param directly ex: `params[:foo]` and `params[:bar]`. If I send the parameters inside the `user` hash, it works, but it is an API so I send everything in the first level of hash.
### System configuration

**Rails version**:
5.0.0.1 API with Postgresql
**Ruby version**:
2.3.1

**Comment by renanoronfle** [comment]
It's working correctly, read documentation: http://api.rubyonrails.org/classes/ActionController/Parameters.html
you send params out of user node, for access with user_params you need send attributes inside user node.
like this: { "user"=>{"foo"=>10, "bar"=>0, "xyz"=>99}}

**Comment by renanoronfle** [comment]
The xyz attribute not inserted in user hash automatically, you send in parameters inside user node.
For you can access attributes out of user node you can remove require(:user) and permit attributes.
it does not seem to me rails issue.
And other thing you not need use attr_accessor for "xyz" because rails mapping automatically.
I think you need read strong parameters documentation to better understand how this works.

**Comment by thiagogsr** [comment]
It is inserted in user hash automatically @renanoronfle, you can test :)

**Comment by renanoronfle** [comment]
Also, if you've turned on config.wrap_parameters in your initializer or called wrap_parameters in your controller, you can safely omit the root element in the JSON parameter. In this case, the parameters will be cloned and wrapped with a key chosen based on your controller's name. So the above JSON request can be written as:

{ "name": "acme", "address": "123 Carrot Street" }
And, assuming that you're sending the data to CompaniesController, it would then be wrapped within the :company key like this:

{ name: "acme", address: "123 Carrot Street", company: { name: "acme", address: "123 Carrot Street" } }

**Comment by thiagogsr** [comment]
It is the bug I'm reporting. When the attribute is a `store_accessor`, it is not cloned.

**Comment by maclover7** [comment]
Hi @thiagogsr! I agree with @renanoronfle that this is the expected behavior, with regard to strong parameters' behavior here. Going to close out this issue as expected behavior.

**Comment by jmbejar** [comment]
Hi @maclover7. 

I think there is a bug or, at least, a bit of inconsistency in the behavior of stored parameters and wrap parameters.

I tested the following scenario in a new app to demonstrate the issue.

Scaffold generator command to generate a User resource:

`
bin/rails g scaffold user name data:text
`

Use the `data` column as a store attribute

```ruby
class User < ApplicationRecord
  store :data, accessors: [:color, :size], coder: JSON
end
``` 

Leaving the default `wrap_parameters` configuration, which only works with JSON requests, I tested a few ways to create users using curl:

1) Sending all parameters (including the store attributes) wrapped under a root element: 

`curl -v -H "Content-Type: application/json" -d '{"user": {"name": "This is my name", "size": "large", "color": "blue"}}' http://localhost:3000/users.json`

Output: `{"id":9,"name":"This is my name","data":{"color":"blue","size":"large"},"url":".../users/9.json"}`

2) Sending all parameters (including the store attributes) **without** root element:

`curl -v -H "Content-Type: application/json" -d '{"name": "This is my name", "size": "large", "color": "blue"}' http://localhost:3000/users.json`

Output: `{"id":11,"name":"This is my name","data":{},"url":".../users/11.json"}`

As you can see, in the first case the user is created including the data for the `color` and `size` accessors defined under the store attribute `data`. Please note the actual `data` attribute is never included in the request data, but it just works because the accessors for `size` and `color` are present in the model (thanks to the `store` class method).

However, when I tried to do the same request without the `user` key in the request JSON, the user was stored only with the `name` value while `size` and `color` were lost. It happened because the `name` attribute was properly wrapped but `size` and `color` were not wrapped.

For the second case, we got the following output in the console

`
Processing by UsersController#create as JSON
  Parameters: {"name"=>"This is my name", "size"=>"large", "color"=>"blue", "user"=>{"name"=>"This is my name"}}
`

In fact, this is what was reported by @thiagogsr. Store attributes accessors are not being wrapped, and this is because only "real" attributes are wrapped.

I think store attributes accessors were designed to behave just like regular accessors. For example, you can use `color` and `size` accessors in a form builder in the view layer and it would work fine when the data is submitted to the controller. However, the wrap parameters module just ignores store attribute accessors.

If we agree this is an issue, we could fix it by adding the store attributes into the wrapping mechanism. It can be done adding them [here](https://github.com/jmbejar/rails/blob/161b6079b55ed50d451d8be15b7fca14a870568e/actionpack/lib/action_controller/metal/params_wrapper.rb#L108)... or maybe redefining `attributes_names` to accept an argument to return all attributes names including store attributes accessors.

I already have some working code, and I'd be happy to open a PR if there is interest on improving this behavior.

Thoughts?

**Comment by thiagogsr** [comment]
I think my example was not so good, but the @jmbejar one is better, it is what I tried to say.

**Comment by maclover7** [comment]
Ahh, I apologize, I misread the bug report. Reopening the issue, and I agree the behavior here could be improved. Feel free to submit a PR @jmbejar

**Comment by vedant1811** [comment]
Is anyone working on this issue? @jmbejar ?
Because I can pick it up and try to fix it.

**Comment by jmbejar** [comment]
Sorry I couldn't make time for this issue yet.

@vedant1811 please go ahead!

**Comment by vedant1811** [comment]
Okay :)

Regards,
Vedant.

**Comment by sngeth** [comment]
Hi all,

I opened a PR to attempt to fix this issue. Since the issue seemed stale for several months I went ahead and worked on it for my own educational purposes, sorry if this may have inconvenienced anyone.

Regards,
Sid

**Comment by tarekdinaji** [comment]
Anybody has any fix for this?
