### ISSUE TITLE
Double rescue_from not called

### ISSUE THREAD

**Issue by passabilities** [rails/rails#26702]
So I ran into a bug where when having a controller wide `rescue_from` then raises a new error, another `rescue_from` meant to catch that specified error is not called.

### Steps to reproduce

**application_controller.rb**
```ruby
class ApplicationController < ActionController::Base
  rescue_from MyApp::Error do |e|
    render_json { success: false, message: e.message }, status: :bad_request
  end
end
```

**my_controller.rb**
```ruby
class MyController < ApplicationController
  rescue_from ActiveRecord::RecordInvalid do |e|
    raise MyApp::Error, e.message
  end
end
```

### Expected behavior
The `rescue_from` in `ApplicationController` should be called to render appropriate json to client.

### Actual behavior
The `MyApp::Error` thrown by `MyController` is raised and produces a 500 Internal Server Error.

### System configuration
**Rails version**: 4.2.7

**Ruby version**: 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

**Comment by jeremy** [comment]
This would be nice to support, but it's by design. Then we needn't detect exception handling loops and such. If an exception is raised by an exception handler, it's handled by a global fallback handler.

In this case, your best bet to share the exception-handling behavior is to extract the `MyApp::Error` handler to method and hook both `rescue_from` to that method.

PRs welcome to rationally + safely handle recursive rescue_from for a future Rails, though!

**Comment by passabilities** [comment]
Where is it defined that it calls the global fallback handler?

**Comment by jeremy** [comment]
@passabilities The exception will bubble up and be handled by the [ActionDispatch::ShowExceptions middleware](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/show_exceptions.rb) which provides a failsafe fallback.
