### ISSUE TITLE
ActionController::InvalidAuthenticityToken rails 5

### ISSUE THREAD

**Issue by prashantkb** [rails/rails#26704]
i m using rails version - 5.0.0.1

i used form_for to create form 
<%= form_for :session,:action => '/login/authenicate/',:remote => true, :authenticity_token => true, :html => { :class => 'validate', :id => 'form_login' } do |s| %>

and i am using ajax to send the request to the serve

this is the form that is display in the browser 

`<form class="validate" id="form_login" action="/login" accept-charset="UTF-8" data-remote="true" method="post" novalidate="novalidate"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="i3GVfaN2PbZ80JvdSqO921GuNLaxxo9ctsTBE21aYJYo/XtBG7lyqU7xAzoFjClwOGWSCrC+6mf3no39ua+rDQ==">
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-addon">
							<i class="fa fa-user" aria-hidden="true"></i>
						</div>
						<input class="form-control" id="username" placeholder="Email Id / Mobile No" type="text" name="session[username]">
					</div>
				</div>
				
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-addon">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</div>
						<input class="form-control" id="password" placeholder="Passowrd" type="password" name="session[password]">
					</div>
				</div>
				
				<div class="form-group">
					<button name="authenicatebtn" type="submit" class="btn btn-primary btn-block btn-login">Login</button>
				</div>
				
</form>`

it is a ajax request to the server when i view in the networks tab its showing ActionController::InvalidAuthenticityToken  error

**Comment by connorshea** [comment]
Do you have a "protect_from_forgery with: :exception" in the controller? Add "prepend: true" to it and it should be fixed.

**Comment by jmbejar** [comment]
You can not directly use `action: ` in the method `form_for` (according the [docs](http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_for)).

Maybe you can try using one of the following valid options:

`
<%= form_for :session, url: { action: 'authenticate', controller: 'login' }, :remote => true, :authenticity_token => true, :html => { :class => 'validate', :id => 'form_login' } do |s| %>
`

`
<%= form_for :session, url: '/login/authenticate/', :remote => true, :authenticity_token => true, :html => { :class => 'validate', :id => 'form_login' } do |s| %>
`

Both should work in the same way, at least if `login` is the name of the controller and `authenticate` is the name of the action (if it's not the case, just use `url: '/login/authenticate'`).

Last but not least, note there probably is a typo in your code. It says "authenicate" instead of "authenticate". It could be another cause of the error you're getting.
