### ISSUE TITLE
ActiveSupport::TimeZone inserts leap seconds at midnight for the time zone, not at the appropriate UTC-adjusted time

### ISSUE THREAD

**Issue by flora** [rails/rails#26807]
### Steps to reproduce
```
(main)> Time.utc( 2015, 06, 30, 23, 59, 59 )
=> 2015-06-30 23:59:59 UTC

(main)> Time.utc( 2015, 06, 30, 23, 59, 59 ) + 1
=> 2015-06-30 23:59:60 UTC # leap second appeared!

(main)> ( Time.utc( 2015, 06, 30, 23, 59, 59 ) + 1 ).to_f
=> 1435708800.0

(main)> pacific_time = ActiveSupport::TimeZone[ "Pacific Time (US & Canada)" ]
(main)> pacific_time.local( 2015, 6, 30, 16, 59, 59 )
=> 2015-06-30 17:59:59 -0700

(main)> pacific_time.local( 2015, 6, 30, 16, 59, 59 ) + 1
=> 2015-06-30 18:00:00 -0700 # no leap second here

(main)> ( pacific_time.local( 2015, 6, 30, 16, 59, 59 ) + 1 ).to_f
=> 1435708800.0 # same as when the UTC leap second occurred, but there was no leap second :/

(main)> pacific_time.local( 2015, 6, 30, 23, 59, 59 )
=> 2015-06-30 23:59:59 -0700

(main)> pacific_time.local( 2015, 6, 30, 23, 59, 59 ) + 1
=> 2015-06-30 23:59:60 -0700 # leap second appeared, not at the appropriate time!

(main)> ( pacific_time.local( 2015, 6, 30, 23, 59, 59 ) + 1 ).to_f
=> 1435712425.0 # this is a different time than when the UTC leap second occurred!
```

### Expected behavior
I expect that a leap second is inserted at the appropriate UTC time, as it is officially recognized: https://en.wikipedia.org/wiki/Leap_second
In other words, I expect a leap second to be inserted in each time zone at the time that corresponds to the same underlying timestamp as the UTC official leap second insertion time.

### Actual behavior
Instead, it seems that the current implementation inserts a leap second right after 23:59:59 in the timezone instead of at the same time in UTC.

### System configuration
**Rails version**: ActiveRecord 4.2.5.1

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by maclover7** [comment]
cc @pixeltrix

**Comment by pixeltrix** [comment]
@flora what hardware and Linux distribution were you using? By default you should't see leap seconds on a POSIX system unless you're synchronising your clock to [TAI (International Atomic Time)][3] and using "right" timezone info files which are adjusted for leap seconds and are usually in `/usr/share/zoneinfo/right`. For example here is Mac OS X and Ubuntu 14.04:

```
$ uname -a
Darwin localhost 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64

>> pacific_time = ActiveSupport::TimeZone[ "Pacific Time (US & Canada)" ]
>> pacific_time.local( 2015, 6, 30, 16, 59, 59 )
=> Tue, 30 Jun 2015 16:59:59 PDT -07:00 
>> pacific_time.local( 2015, 6, 30, 16, 59, 59 ) + 1
=> Tue, 30 Jun 2015 17:00:00 PDT -07:00 # No leap second where it should be
>> pacific_time.local( 2015, 6, 30, 23, 59, 59 )
=> Tue, 30 Jun 2015 23:59:59 PDT -07:00 
>> pacific_time.local( 2015, 6, 30, 23, 59, 59 ) + 1
=> Wed, 01 Jul 2015 00:00:00 PDT -07:00 # No leap second where it was in your example 
```

```
$ uname -a
Linux localhost 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

>> pacific_time = ActiveSupport::TimeZone[ "Pacific Time (US & Canada)" ]
>> pacific_time.local( 2015, 6, 30, 16, 59, 59 )
=> Tue, 30 Jun 2015 16:59:59 PDT -07:00
>> pacific_time.local( 2015, 6, 30, 16, 59, 59 ) + 1
=> Tue, 30 Jun 2015 17:00:00 PDT -07:00 # No leap second where it should be
>> pacific_time.local( 2015, 6, 30, 23, 59, 59 )
=> Tue, 30 Jun 2015 23:59:59 PDT -07:00
>> pacific_time.local( 2015, 6, 30, 23, 59, 59 ) + 1
=> Wed, 01 Jul 2015 00:00:00 PDT -07:00 # No leap second where it was in your example 
```

Also I'm not sure that leap seconds should be appearing when creating time objects - the point of them is to bring UTC into line with UT1 so that they correlate to approximately the same time so once that moment has passed it's not really relevant and could start introducing weird errors when calculating things based on durations (imagine paying extra interest because of a leap second!).

If you look at what [the UNIX spec][1] says about calculating seconds since the epoch it gives the following formula:

```
tm_sec + tm_min*60 + tm_hour*3600 + tm_yday*86400 +
    (tm_year-70)*31536000 + ((tm_year-69)/4)*86400 -
    ((tm_year-1)/100)*86400 + ((tm_year+299)/400)*86400
```

If you input `2015-06-30 23:59:60` and `2015-07-01 00:00:00` you'll get the same value: `1435708800`. How Ruby behaves at this point is down to the underlying system implementation. If you're interested [the Wikipedia page on Unix time][2] goes into more detail.

I'm going to close as we don't have any leap second code so "bugs" would either be in the `tzinfo` gem or Ruby itself.

[1]: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_16
[2]: https://en.wikipedia.org/wiki/Unix_time#Leap_seconds
[3]: https://en.wikipedia.org/wiki/International_Atomic_Time
