### ISSUE TITLE
XmlMini_REXML throws potentially undefined errors.

### ISSUE THREAD

**Issue by yxhuvud** [rails/rails#26813]
### Steps to reproduce

Assume a function looking roughly like this:

``` ruby
def read_and_process
  Hash.from_xml do_something
rescue REXML::ParseException
end
```

from_xml may raise REXML::ParseException, but if do_something also raise an exception, then REXML::ParseException may be undefined, depending on if something (potentially a successful earlier run) has managed to require rexml/document or not. 
### Expected behavior

I would expect to have all exceptions defined before the method is called the first time, so that it is possible to catch the exception. 
### Workaround

This can be worked around by manually requiring rexml/document.
### Suggested resolution:

Either make certain REXML::ParseException is defined or raise some other exception that is defined. 
### System configuration

**Rails version**: 4.2.6

**Ruby version**: 2.3.1

**Comment by arthurnn** [comment]
is that Rails related?

**Comment by yxhuvud** [comment]
It is a usability issue in Hash#from_xml which is a method that activesupport provide. How is it not related to Rails? It is *really* unexpected that you have to manually require rexml to catch the exception, while using rexml to actually parse it works without kinks or any manual action.

**Comment by prathamesh-sonpatki** [comment]
This is reproducible using https://gist.github.com/797e9d4b9e6fe04665c6f35f5d0069a8.

It is happening because we require `rexml/document` which defines the `ParseException` conditionally here - https://github.com/prathamesh-sonpatki/rails/blob/master/activesupport/lib/active_support/xml_mini/rexml.rb#L27

Because `do_something` fails and `Hash#from_xml`  method never gets called, https://github.com/prathamesh-sonpatki/rails/blob/master/activesupport/lib/active_support/xml_mini/rexml.rb#L27 does not get run and that's why `REXML::ParseException` constant does not get resolved.

Looking at the Rails history, looks like this condtional loading of `rexml/document` was present from the very start https://github.com/rails/rails/commit/822c41d69d9228c9912d29ac45155d3a16bb5c50 

@jeremy do you remember why we require `rexml/document` conditionally? :smile:

Once I move it to the top of the file, this test fails with expected error:

``` diff
modified   activesupport/lib/active_support/xml_mini/rexml.rb
@@ -1,6 +1,7 @@
 require "active_support/core_ext/kernel/reporting"
 require "active_support/core_ext/object/blank"
 require "stringio"
+require "rexml/document"
```

```
BugTest#test_stuff:
NameError: undefined local variable or method `do_something' for #<BugTest:0x007f9753f209d0>
    generic_master.rb:18:in `test_stuff'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```
