### ISSUE TITLE
Reading username from default_file

### ISSUE THREAD

**Issue by sgoyal1012** [rails/rails#26908]
### Steps to reproduce

I am trying to use the **default_file** option for mysql2 gem; and placing all db connections keys such as user, password, database... etc. in the conf file. 
So in the YAML file, I want to ideally specify ONLY 2 fields, **default_file** and **default_group**

Essentially, trying to mirror 

```
mysql --defaults-file="/path/to/default_file.cnf"
```
### Expected behavior

All the params (including the user) should be picked up from the conf file. I want the cnf file to be a single source of truth for my DB connection settings. 
### Actual behavior

Due to the code here: 

```
config[:username] = "root" if config[:username].nil?
```

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L14

If config that does not have username, it is **assumed** as root; thereby overriding the setting in the conf file. 
Any reason why this is?
### System configuration

**Rails version**:
Does not matter
**Ruby version**:
Does not matter

**Comment by utilum** [comment]
Is this not because in its default setup MySQL has a 'root' user without a password... so that on your dev box you can setup your databases, modify them, and manipulate data without preliminary steps?

**Comment by raejin** [comment]
@utilum It doesn't take into the consideration that if MySQL conf file specifies an username.

I feel like this issue can be solved at the [db client level](https://github.com/brianmario/mysql2/blob/master/lib/mysql2/client.rb#L74) by parsing MySQL conf file and check if username exists.

**Comment by utilum** [comment]
@raejin I agree that probing MySQL configuration for this would be out of scope for Rails. I think @sgoyal1012 desires to understand why this is Rails' default conf.

**Comment by pixeltrix** [comment]
That [line of code actually originates][1] from the mysql2 gem. Back in the early days of the gem, it supplied the Active Record adapter because you could use it with already released versions of Rails. Then from Rails 3.1 and mysql2 0.3.x onwards it has been incorporated into Rails itself. When [the code was migrated][2] it was just copied line for line so there's no specific reason that line has been added, however that doesn't mean it's safe to remove - we'd need to do some testing first.

[1]: https://github.com/brianmario/mysql2/commit/40f3a2c491a067b762b76171ab27b0a123c0fa7c
[2]: https://github.com/rails/rails/commit/70b9db173e958944fcf61ac8514408fba9ef0c9a
