### ISSUE TITLE
polymophic relation can't be included on scope with complex where

### ISSUE THREAD

**Issue by phuongnd08** [rails/rails#26939]
### Steps to reproduce

``` ruby
class Transaction < ActiveRecord::Base
  belongs_to :operation, polymorphic: true
  belongs_to :account
end

class Account < ActiveRecord::Base
   belongs_to :user
end

class User < ActiveRecord::Base
  # has field country_code
end

Transaction.where(accounts: {:users=>{:country_code=>["us"]}}).includes(:operation).count
```

### Expected behavior

It should return a count

### Actual behavior

``` ruby
ActiveRecord::EagerLoadPolymorphicError Exception: Cannot eagerly load the polymorphic association :operation
```
### System configuration

**Rails version**: 4.2.6

**Ruby version**: 2.1.5

**Comment by phuongnd08** [comment]
It's fine this way: Transaction.joins(:account => :user).where("users.country_code"=>["us"]).includes(:operation).count

**Comment by prathamesh-sonpatki** [comment]
This is by design. Eager loading polymorphic associations is only possible using [preload](http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-preload).

That is why [this error is raised](http://api.rubyonrails.org/classes/ActiveRecord/EagerLoadPolymorphicError.html).

The explanation for this can be found [here](https://github.com/rails/rails/blob/e39e7112bdb0da9a1c3b23d45fc1093703796468/activerecord/lib/active_record/associations.rb#L925-L932)

Thanks @phuongnd08. 💚

**Comment by phuongnd08** [comment]
Not sure I understand this correctly. I noticed eager loading means that the data loaded, then based on the id (and the type) of each of the association, then rails will perform another query. So query => data => parse data to do another query. Not sure how the join in the 1st query could hinder this?
