### ISSUE TITLE
Rails5 concurrency, with_connection and executor.wrap interaction

### ISSUE THREAD

**Issue by jrochkind** [rails/rails#26956]
I am exploring concurrency involving new Rails5 API, and ActiveRecord. 

I am used to, in Rails 4, wrapping all my AR use in 'created' threads in `ActiveRecord::Base.connection_pool.with_connection`, to ensure the connection is checked back in at end of block.  This is also one of the recommended ways to use AR with concurrency in the [docs](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html). 

In Rails5, I learned from @matthewd about `Rails.application.executor.wrap`.  

If I try to do some concurrency wrapping in _both_ `executor.wrap` _and_ `connection_pool.with_connection`, it seems to deadlock. This is in a rake task depending on `:environment`, in an app where `cache_classes = eager_load = true`, to isolate AR issues from autoload issues. 

~~~ruby
# DEADLOCKS
futures = 100.times.collect do |i|
    Concurrent::Future.execute do
      Rails.application.executor.wrap do
        ActiveRecord::Base.connection_pool.with_connection do
          SomeModel.find_or_create_by(value: i.to_s)
        end
      end
    end
  end
~~~

However, the reverse does not deadlock, an outer `with_connection` wrapping an `executor.wrap`

~~~ruby
  # DOES NOT DEADLOCK
  futures = 100.times.collect do |i|
    Concurrent::Future.execute do
      ActiveRecord::Base.connection_pool.with_connection do
        Rails.application.executor.wrap do
          SomeModel.find_or_create_by(value: i.to_s)
        end
      end
    end
  end
~~~

The trick is, the former deadlocking version seems quite likely to happen in real code to me. 

* Is the deadlock a bug, or as intended/designed?
* Or is my use of `Rails.executor.wrap` in this context a bug for some reason? My understanding is that it was required/recommended in this case, but I might still not get it. 
* Are new instructions explaining the AR concurrency contract needed in [ConnectionPool](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html), to take account of interactions with new Rails5 executor/interlock/reloader stuff?
* @matthewd mentioned that he thought maybe `Rails.executor.wrap` made `connection_pool.with_connection` unneccesary, but I haven't confirmed it yet (it's difficult to confirm without monkey-patching or reachign into internals of AR, AR lacks good API for verifying if you have leaked connections or not). 

In Rails4, `connection_pool.with_connection` was _the_ safe way to use ActiveRecord without having to know anything about your context. If you happened to be a in a thread that hadn't set up anything AR-related, it would work great, and was required. But if you were actually in a Rails request loop (action method), I believe it would still work fine. I think it even worked to nest `connection_pool.with_connection` in itself. So code could just do a `with_connection` without having to have non-local knowledge of what things lower in the call stack may have set up (or not). 

But with the above behavior, if you write such code, and then use it (possibly indirectly) via a call chain, in a block that in an outer scope did `executor.wrap` -- deadlock. So the decision about how to handle ActiveRecord concurrency needs to be made at the same code level as the decision about how to deal with ActiveSupport issues handled by `executor.wrap`, in the same place, coordinated. This is unfortunate, and makes it harder to write re-usable AR code that is concurrency-safe. 

In fact, I've run into a more complex issue in a real world app that I haven't figured out yet. To figure it out in the context of Rails5, I went back to some very basic demos to validate my understanding of what's going on and build basic building block knowledge. This was the first mystery I encountered.

**Comment by jrochkind** [comment]
I think some of these configurations _are_ leaking connections. Rails5 does a better job of reaping leaked connections, so it's hard to tell. But in my demos, based on huge slowdown plus occasionally a `could not obtain a connection from the pool` exception, I think connections are just being leaked. 

* I think _just_ using `Rails.application.executor.wrap` may leak connections. 
* I think an outer `connection_pool.with_connection` wrapping an `executor.wrap` still leaks connections. 
* Just a `connection_pool.with_connection` (Rails4 style) _seems_ not to leak connections. But am I subject to interlock problems, because of not using any of the new API to do that concurrency safely?

I need to figure out how to reach into the internals of the connection pool to see how many connections are checked out/available, etc., to verify for sure that connections are being leaked or not.

**Comment by jrochkind** [comment]
Drat, and with just `connection_pool.with_connection`, I'm getting the old `Circular dependency detected while autoloading constant FeedUpdater`, which I now know probably means a violation of the autolock concurrency contract. 

This happens even if I wrap my blocking waits in a `ActiveSupport::Dependencies.interlock.permit_concurrent_loads`. 

So every setup I've found either blocks immediately, seems to leak AR connections, or results in the "Circular dependency detected while autoloading" error. 

I still am not sure which pattern is actually the "correct" one to use, so I don't know which exceptions are because I'm doing something wrong, or which are because of a bug, or even because what I'm doing is literally impossible and intentionally not supported in Rails5 somehow. (The latter seems implausible -- there's got to be a supported way to make some threads and do some AR operations in them, like there was in Rails4!)

**Comment by matthewd** [comment]
> there's got to be a supported way to make some threads and do some AR operations in them

The Executor is what manages this for Actual HTTP Requests, so... yes, very much so. :smile:

---

Any inter-mixing of `with_connection` and `executor.wrap` should work fine (and if it doesn't, we should fix that). Off the top of my head, the most potentially-surprising outcome I'd anticipate is that `executor.wrap` inside `with_connection` would cause the connection to be returned early -- but `with_connection` will still clean up if any subsequent code happens to reacquire. (So, possibly surprising if you're actually watching the pool, but not generally observable / buggy.)

`with_connection` *inside* `executor.wrap` deadlocking is particularly surprising to me, because if the running thread already has a connection allocated (which `executor.wrap` will currently always do, for reasons outside our scope here, though we plan to fix that), then `with_connection` is a no-op yield.

FWIW, I was able to run both variants without issue. 

---

You should be able to see what the pool is doing by asking it:

`ActiveRecord::Base.connection_pool.connections.map(&:owner)` -- nil is self-explanatory; for the others, working out whether the given thread "should" own a connection at that time is left as an exercise for the reader 😁... corresponding poking inside c-r's internals may be called for.

Technically you should hold the connection pool's lock before doing that, but if there are deadlocks in play, it's likely involved, so you probably couldn't acquire it if you tried.

The other option is to (when experiencing an apparent deadlock) dump the backtraces on all the threads, either using DebugLocks or manually, to confirm exactly what is getting stuck, and how it's getting there / why it's holding a conflicting lock at the time.

---

So, to wrap a long answer into a short one:

As long as you're using `executor.wrap`, at some point, inside the thread and around the 'application' code, everything should Just Work.

If the connection pool appears to be leaking connections, or if calling `with_connection` at any point you like causes misbehaviour, or if anything else implies you need to understand complicated module interactions in this area, that is a bug I want to know about.

**Comment by jrochkind** [comment]
Thank you again for your very helpful response! I'm going to make a more careful demo/reproduction to share, to see why you're getting different observations than me. 

I am using postgres specifically, it seems that shoudln't matter, but I guess it could if there's a bug somewhere. 

Do you have recommendations for interlock-related code in my demo? Should I make the demo with eager_load=cache_classes=true, or not?  I'd be inclined to skip it and leave default settings, because that's of course my ultimate goal to get something that works with default settings in dev. 

I don't know how the interlock is handled in a Rake task with an `:environment` dependency, if it's already being wrapped in any interlock-related things.   It occurs to me that it might be the interlock rather than the connection pool that is blocking my threads. Especially since I curiously was getting `Circular dependency detected while autoloading` exceptions even _with_ eager_load=cache_classes=true, which doesn't seem like it should be possible.

**Comment by omederos** [comment]
Something similar happened to us. We always used `ActiveRecord::Base.connection_pool.with_connection do ... end` on rails 4.x whenever we wanted to hit the database from manually created threads, and we never had any issues. Yesterday we started creating a couple of manual threads in a rails 5.1.1 controller and we forgot to wrap the DB calls using the above method. We fixed that immediately, and the weirdest thing was... we kept getting the known  *FATAL: sorry, too many clients already* error. I started googling immediately and I found this and a couple other of issues here. I changed the above block by `Rails.application.executor.wrap do ... end` and the same happened, although we noticed that we started getting fewer errors :confused: 

I'm going to keep trying a few alternatives like using `executor.wrap` inside `with_connection`, etc...
