### ISSUE TITLE
Etag is not working in Rails 5 anymore - always returns 200 OK if query has datetime comparison

### ISSUE THREAD

**Issue by rkrayovskyy** [rails/rails#26987]
### Steps to reproduce
In model:
`scope :active,  ->(time) { where("active = ? AND (expiration_date >= ? OR expiration_date IS NULL)", true, time) }`

In controller:
```
def set_cards
  @cards = Card.active(Time.current.utc).approved.order(:id)
end
```

```
def index
    if stale?(@cards)
       ...
    end
end
```

In terminal:
`curl -i -H 'If-None-Match: W/"2452b384653c64b7fef4a88ccc2c519e"' http://localhost:3000/api/v1/mobile/cards`

### Expected behavior
Return 200 OK with data if fresh data available; or 304 Not Modified if no fresh data.

### Actual behavior
Always returns 200 OK and new Etag.
Worked well in Rails 4 and also works well in same controller for a 'show' with following:
```
def set_card
   @card = Card.find_by(id: params[:id])
end
```
Also works well in reported method if remove `expiration_date >= ?` from the scope.
So, I am assuming it is related to the following change in Rails 5: https://github.com/rails/rails/pull/15726

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.2.4p230

**Comment by maclover7** [comment]
@rkrayovskyy Since you said that this works fine for you in Rails 4.2.x, but is broken in 5.0.x, can you do a `git bisect` to determine where a possible regression may have been introduced? I know you posted a PR link above, but if you a bisect that'll determine exactly where things have changed. Thanks!!

**Comment by rkrayovskyy** [comment]
@maclover7 not sure if I got your request right... I ran git bisect but there were no regressions determined as I literally changed nothing in code other than upgrading Rails, related gems and some basic config to catch up with upgrade.

I have created a clean new project with this case only: https://bitbucket.org/roman_krayovskyy/stale_test
same issue - Etag/caching works well until I do `where('updated >= ?', Time.now)`

Hope it helps. thanks for your attention here!

**Comment by maclover7** [comment]
@rkrayovskyy I meant to do a bisect on the Rails codebase, since you said everything was fine in Rails 4.2.x, but was broken in 5.0.0.1; it sounds like something went wrong within Rails between those versions, based on this bug report.

**Comment by common-nighthawk** [comment]
@maclover7 looking into this issue, i dont see a problem.  #stale and #fresh_when work properly for me in both 4.2.x and 5.0.0.1.

i then ran it with repo @rkrayovskyy provided, and also get 200 and 304 properly.

screenshot of the log running https://bitbucket.org/roman_krayovskyy/stale_test is attached.
![screen shot 2016-12-17 at 1 33 48 pm](https://cloud.githubusercontent.com/assets/6483815/21289250/88faa982-c45d-11e6-98cc-2ee871fcef70.png)

i think this can be closed unless additional information is provided.

**Comment by lsylvester** [comment]
I think that this issue is happening because the etag is generated using the `collection_cache_key` which includes a digest of the query - which is changing every time because the current time is being passed in. 

I think that the old behaviour would have been loading up the association and then joining the cache key of each record. Maybe explicitly converting the relation to an array to load all of the records would work around this issue.
