### ISSUE TITLE
ActiveSupport.on_load(:action_controller) triggered twice in API mode

### ISSUE THREAD

**Issue by Aqualon** [rails/rails#27013]
During updating one of our apps to Rails 5, we tried to enable api mode and hit a stack level too deep error inside tests, which was caused by some gems using `ActiveSupport.on_load(:action_controller)` to redefine methods via `alias_method`. See https://github.com/skaes/logjam_agent/blob/d20305a91b1cf9c398701e687e14f02f105d7530/lib/logjam_agent/railtie.rb#L80-L94 for an example.

During investigation we found out, that the on_load was triggered twice, if we used `ActionController::API` as base class. Here are some smaller steps to reproduce it:

### Steps to reproduce
- `rails new my_api --api`
- `rails g controller Users show`
- Put the following code into Users controller:
```
ActiveSupport.on_load(:action_controller) do
  puts 'INSIDE ON_LOAD'
end

class UsersController < ActionController::API
  def show
    head :ok
  end
end
```
- `bundle exec rake test`

### Expected behavior
`ActiveSupport.on_load(:action_controller)` should only be triggered once.

### Actual behavior
The `INSIDE ON_LOAD` output is printed twice. If I replace `ActionController::API` with `ActionController::Base` it's only printed once.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by Aqualon** [comment]
I found two code places, that use `ActionController::Base` even in API mode, thus triggering the behavior:
 
https://github.com/rails/rails/blob/5-0-stable/actionpack/lib/action_dispatch/middleware/static.rb#L77
https://github.com/rails/rails/blob/5-0-stable/actionpack/lib/action_controller/log_subscriber.rb#L20

**Comment by rafaelfranca** [comment]
This is expected behavior. Even that you application is api only this doesn't mean you will not have `ActionController::Base` being used. If you only to the trigger run only once we will need to add a different trigger super class.

In you specific case instead of calling `ActiveSupport.on_load(:action_controller)` in the railties that code should be using `ActiveSupport.on_load(:action_controller_test_case)`.

**Comment by Aqualon** [comment]
@rafaelfranca in that specific case this could be an option. The code that broke for us could probably also check if the alias methods are already defined and not execute alias_method again. 

But I also saw other cases, where `ActiveSupport.on_load(:action_controller)` was used for various things. I wonder if it's in general a bad idea to use `on_load` and rely on it to be triggered only once?

**Comment by rafaelfranca** [comment]
It will be triggered as many times it is called, there is no guarantees that they only run once. If your application has `ActionController::Base` and `ActionController::Api` it will run twice.

**Comment by skaes** [comment]
Having on_load run more than once makes the whole on_load API really hard to use. Very often it's used to extend/monkey_patch ActionController methods. In order to make this work correctly every user of on_load needs to make sure the on_load code is idempotent, which sucks big time. In all prior Rails version, on_load was executed only once. Would be great to get this guarantee again.
