### ISSUE TITLE
ActiveSupport::Dependencies loading broken within engines

### ISSUE THREAD

**Issue by glebm** [rails/rails#27119]
Calling for the help of Ruby Heroes with `active_support/dependencies.rb`! @fxn! :mega: 

Calling `require 'non-autoloaded-file'` from an autoloaded file in Rails is broken if the non-autoloaded file defines a constant in a sub-namespace of an autoloaded file.

For example, if you have:

```ruby
# app/models/my_engine/my_model.rb
require 'my_lib'

module MyEngine
  class MyModel ...
end
```

```ruby
# lib/my_lib.rb
module MyEngine
  class MyLib ...
end
```

Then `MyEngine::MyLib` will be in `new_constants` for `my_model.rb`. So it will get unloaded on the next `MyModel` reload, and will never get loaded again :boom: .

(Original issue: https://github.com/thredded/thredded/issues/478).

### Steps to reproduce

Here is a repo of an Engine with a dummy app that exhibits the problem.
It also comes with logging of some of the `ActiveSupport::Dependencies` calls for ease of debugging.

```bash
git clone https://github.com/thredded/thredded.git
cd thredded
git checkout dependency-wat
bundle
rake db:create db:migrate db:seed
rake dev:server
```

```bash
curl 'http://localhost:9292/thredded?q=test'
echo 'puts "Reloaded"' >> app/models/thredded/topic.rb
curl 'http://localhost:9292/thredded?q=test'
```

:boom:

### Expected behavior

Constants defined in files required via `require` should not be unloadable.

Logging output (`+` is `new_constants`):
```s
(load_file "~/repos/thredded/thredded/app/models/thredded/topic.rb"  
  (require "thredded/topics_search"    
    (require "thredded/search_parser" 
      (+ Thredded::SearchParser)
      true)
    (+ Thredded::TopicsSearch)
    true)
  ( ... other calls: Thredded load_file, friendly_id requires ... )
  (+ Thredded::Topic)
  true)
```

### Actual behavior

Constants defined in files required via `require` become unloadable when they are defined in the `MyEngine` namespace. A `NameError` then happens on the next reload, as the constants are removed but not loaded again because `require` only loads the file once.

Logging output:
```s
(load_file "~/repos/thredded/thredded/app/models/thredded/topic.rb"  
  (require "thredded/topics_search"    
    (require "thredded/search_parser" true)
    true)
  ( ... other calls: Thredded load_file, friendly_id requires ... )
  (+ Thredded::SearchParser Thredded::TopicsSearch Thredded::Topic)
  true)
```

### System configuration

**Rails version**:
5.0.0.1

**Ruby version**:
2.3.1

The engine does not change the defaults for `paths` and is basically a vanilla Rails engine.

**Comment by maclover7** [comment]
cc @fxn

**Comment by al2o3cr** [comment]
Will dig in further this evening, but my first target would be "can you get the autoloader to not think `MyEngine::MyLib` is a new constant"? Maybe something like this early on in the engine's always-loaded code:

```ruby
module MyEngine
  class MyLib
  end
end
```
(with appropriate caveats about getting the superclass of `MyLib` correct)

My hypothesis is that the code above will mean that `MyEngine::MyLib` is an empty `Class` until a file that calls `require 'my_lib'`  causes its contents to be loaded once; since this is only re-opening an existing class the autoloader should stay out of the equation.

**Comment by fxn** [comment]
Hey, missed this one.

At first sight, the problem could be that `MyEngine` is actually autoloaded. That is, when you are executing _app/models/my_engine/my_model.rb_, autoloading needs first to resolve `MyEngine`. If there is a _my_engine.rb_ file in any of the autoload paths, it will load that one, otherwise it defines a module with that name. Only then proceeds to interpret the file.

So `MyEngine` is autoloaded and when constants are wiped, this module object is deleted, and with it all the constants that belong to it (constants belong to modules, you cannot distinguish autoloaded from non-autoloaded, if the parent is gone, all is gone.)

**Comment by fxn** [comment]
Ah, let me add that only happens if `MyEngine` is autoloaded. If it is not, for example by defining the namespace in an initializer, then it won't be considered to be autoloaded. I _think_ that would work, but allow me a safety % of uncertainty :).

**Comment by glebm** [comment]
@fxn The namespace (`Thredded`) is referenced in the [initializer](https://github.com/thredded/thredded/blob/dependency-wat/spec/dummy/config/initializers/thredded.rb).
