### ISSUE TITLE
Active Record: Add `use_index`

### ISSUE THREAD

**Issue by kaspth** [rails/rails#27110]
Sometimes it's useful to pass an index hint to the MySQL query planner. We'd like to have a proper method to do so in Active Record. Namely, a `use_index` method that would work like:

```ruby
# Allow passing index hints to MySQL in case the query planner gets confused.
#
# MySQL documentation:
#    http://dev.mysql.com/doc/refman/5.1/en/index-hints.html
#
# Example:
#   Message.first.events.use_index(:index_events_on_eventable_type_and_eventable_id)
#
#   => Event Load (0.5ms)  SELECT `events`.* FROM `events` USE INDEX (index_events_on_eventable_type_and_eventable_id)
#      WHERE `events`.`eventable_id` = 123 AND `events`.`eventable_type` = 'Message'
#
module UseIndex
  extend ActiveSupport::Concern

  module ClassMethods
    def use_index(name)
      from "#{quoted_table_name} USE INDEX (#{name})"
    end
  end
end
```

This needs to be generalized for other DB adapters if need be.

cc @dhh since you posted the original version internally

**Comment by virtualfunction** [comment]
Def think it's important to generalise this (I have to admit it's been a while since I've looked at AR source code to know if this is feasible), given transactions are similar in nature, i.e. they run in a certain scope / block of code. 

I don't use MySQL so I wouldn't use this feature as such (I personally fell out with MySQL because it's indexing and query planning is absolute rubbish compared to PG), but do think there are similar use cases for other DB's (I did find myself having to disable seq scan on PG to force it to use an index) hence why I think it'll be good to make a generalisation of this which developers can tailor to their own needs given that each DB uses it's own means / mechanisms to influence the query planner.

**Comment by prathamesh-sonpatki** [comment]
I will take a stab at this

**Comment by matthewd** [comment]
Making this a relation method is problematic because, as hinted by the above implementation, it's adding information to a particular entry in the FROM clause.

In the simplest case, where there's only one table listed, that's not a worry... but with joins involved, it seems less straight-forward. Perhaps there's a more Arel-ish place for this to slot in?

---

I do think PG should no-op [or fail] on this... I see no practical API that would incorporate the very different semantics of disabling seq scans, etc. This is about index hints only -- thus excluding `enable_seqscan` on PG, but also optimizer hints on MySQL.

SQLite appears to have [a relevant mechanism](https://www.sqlite.org/lang_indexedby.html), though it is "/not/ intended for use in tuning the performance of a query".

All I know of Oracle is that it is hint-happy, so I assume it also supports something similar; implementing it is up to the relevant adapter, but we should be aware of its needs while considering any API.

**Comment by dhh** [comment]
👍 to being a no-op on adapters that does not support it.

**Comment by gaurish** [comment]
*BUMP*

Is this PR ready to me merged? Any pending work that we can do to get this merged?

**Comment by kaspth** [comment]
@gaurish of course, take it away!

**Comment by gaurish** [comment]
Did the first-cut of the implementation, Please see #30514

**Comment by zakwanhaj** [comment]
Will this work with `includes`/`references` ?

**Comment by kaspth** [comment]
This is now up for grabs again. Note per #35558 that the API could also support finding indexes by columns:

```ruby
Message.first.events.use_index([ :eventable_type, :eventable_id ])
```

**Comment by intrip** [comment]
@kaspth can I take it?

**Comment by kaspth** [comment]
@intrip go for it 🙌

**Comment by slimdave** [comment]
Ref the difference between index and optimizer hints in MySQL, that seems to be more of a MySQL syntactic issue than a true functional difference.

Index hints would seem to be a subset of what Oracle would call an access path optimiser hint: https://docs.oracle.com/en/database/oracle/oracle-database/19/tgsql/influencing-the-optimizer.html#GUID-B198573A-C64B-4071-9CD8-738355A20DD7

See also "Table 2-23 Hints by Functional Category" under https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Comments.html#GUID-D316D545-89E2-4D54-977F-FC97815CD62E.

Which is just to say that as far as Active Record is concerned, the separate treatments provided by MySQL may be a red herring?

**Comment by yskkin** [comment]
Is this different from #35615?

**Comment by intrip** [comment]
I didn't know about optimizer hints, I've updated https://github.com/rails/rails/issues/27110#issuecomment-810909078 accordingly 👍 .

`Optimizer hints` is not a replacement for `USE INDEX` but starting from `Mysql 8` you can achieve a similar effect: [To cause MySQL to use the same index or set of indexes as with a given instance of USE INDEX, you can use NO_INDEX, NO_JOIN_INDEX, NO_GROUP_INDEX, NO_ORDER_INDEX, or some combination of these.](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html)

ATM `MariaDB` doesn't support `Optimizer hints`.

**Comment by yahonda** [comment]
When I said I was against this option, there were no `optimizer_hints` available.
Then I believe I worried about implementing `use_index` would prevent from implementing optimizer hints.

Now Rails has `optimizer_hints` method, I am not against implementing `use_index` method as long as it will not do harm other database adapters.

**Comment by intrip** [comment]
@kaspth @kamipo Thanks to https://github.com/rails/rails/issues/27110#issuecomment-810940663 looks like we have no major blockers.

About the API I was thinking of something closer to the actual MySql API

```ruby
# indexes: list of indexes
# for: one of JOIN|ORDER BY|GROUP BY default nil
def use_index(*indexes, for: nil)
```
Later on we can also expose `force_index|ignore_index` to comply with the whole [index hints API](https://dev.mysql.com/doc/refman/5.7/en/index-hints.html).

WDYT?

**Comment by intrip** [comment]
Feedback on https://github.com/rails/rails/issues/27110#issuecomment-811735340 from a core team member will be super appreciated so that I'll know to be on the right track 😄

**Comment by intrip** [comment]
@kaspth I've created #42046 which is now ready for review.
/cc @kamipo @matthewd @yahonda

**Comment by khiav223577** [comment]
use `joins("USE INDEX #{index_name}")` will be better than `from("#{table_name} USE INDEX #{index_name}")`
since `from` will overwrite original from tables that may cause unexpected problems.
