### ISSUE TITLE
validations and strange behaviours with boolean fields

### ISSUE THREAD

**Issue by xarael** [rails/rails#27153]
### Steps to reproduce

Have a field :active which is a boolean for a model. In the model file I have a before_validation :set_default method which contains the code self.active ||= false (and the method returns true else there's errors). I also have validates_presence_of :active in the model.

What I expect to happen is for the model to validate this field as having a present value, however it behaves as if it's nil. Appears boolean values nil and false have little difference.

Can work around this as I don't want the field to be evaluated as true which is a win, but would be good for validations to perhaps use something like the nil? method to evaluate blank values rather than false.

Rails 5.0.0.1 Ruby 2.3.0

**Comment by utilum** [comment]
Why do you need to validate presence if you have a default value?

**Comment by xarael** [comment]
Agreed. Removing the validation was actually how I got past this. Just wasn't expecting the presence to evaluate false (nil and false) rather than nil.



I like that defining validations self documents code and the model to some extent, and there may be instances where you want someone to explicitly define a boolean field and not set a default value (force thought and a decision).




---- On Wed, 23 Nov 2016 19:18:03 +1000utilum &lt;notifications@github.com&gt; wrote ----




Why do you need to validate presence if you have a default value?

**Comment by utilum** [comment]
It's actually [documented](http://api.rubyonrails.org/classes/ActiveModel/Validations/HelperMethods.html#method-i-validates_presence_of):
> If you want to validate the presence of a boolean field (where the real values are `true` and `false`), you will want to use `validates_inclusion_of :field_name, in: [true, false]`.
But I would also intuit `presence` to understand the nuance.

**Comment by sgrif** [comment]
This case is mentioned in the documentation

**Comment by xarael** [comment]
Great. Would you think it worthwhile validates_presence_of throws an exception if the field is a boolean?





---- On Thu, 24 Nov 2016 03:42:18 +1000Sean Griffin &lt;notifications@github.com&gt; wrote ----




Closed #27153.

**Comment by sjaveed** [comment]
This is still the current behavior as of Rails 6.0.x.  From a code perspective, it looks like it stems from the `FalseClass#blank?` [having been defined to always return true](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/blank.rb#L68).  I think in the case of validations this isn't intuitive, the document workaround notwithstanding.

I'd started playing around with a refinement of `FalseClass` limited to [`ActiveModel::Validations::Presence`](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/presence.rb#L7) that would change `FalseClass#blank?` so it always returned true.  This would allow `validates_presence_of` and other presence validation syntax to work more intuitively for Boolean fields, specifically only a nil value in a Boolean field would trigger a presence validation error.  Both true and false would be considered present for Boolean fields.

I can put a PR up if you'd like to look at it but I figure a description might be good enough since it's a small change.

Thoughts?
