### ISSUE TITLE
Parameters with object having empty arrays as values get dropped

### ISSUE THREAD

**Issue by lukebooth** [rails/rails#27215]
### Steps to reproduce

PUT/PATCH parameters that look like `{ id: "1", stuff: {"A" => [], "B" => [], "C" => [], "D" => []} }` will completely drop the `stuff` parameter by the time we're in the controller method.

### Notes
I've got a sample app [here](https://github.com/lukebooth/empty-array-params) with `rails-4.2` and `rails-5` branches where the tests pass and don't pass, respectively. I'm trying to figure out the differences between the rails versions that cause the empty object to be dropped.

I've seen some articles and issues with parameter [deep munging](https://github.com/rails/rails/pull/16924) does that have something to do with it? If this isn't the place to bring up this issue, please close this. Thanks!

### System configuration
**Rails version**:
tests pass in 4.2 and fail in 5.0.0.1

**Ruby version**:
2.2.4

**Comment by kaspth** [comment]
Could be related to: https://github.com/rails/rails/issues/26569

Can you write a reproducible test case?

**Comment by lukebooth** [comment]
@kaspth if you check out that sample app I linked to there are two tests. They both pass on the `rails-4-2` branch and one fails on the `rails-5` branch.

**Comment by kaspth** [comment]
@lukebooth doh! Totally missed that, thanks!

**Comment by sgrif** [comment]
This is the expected behavior. There is no way to encode an empty array using an HTML form (e.g. `Content-Type: url-form-encoded`). The reason your tests passed in Rails 4.2 is because controller tests did not encode their parameters, they simply passed the hash through directly. In Rails 5 it encodes them. If your controller cares about empty arrays, it's likely that you are dealing with JSON requests. You can do that in your test with `as: :json`. If you're just dealing with form input, you will never receive an empty array.

**Comment by lukebooth** [comment]
Thanks for the explanation @sgrif!

**Comment by sgrif** [comment]
Any time
