### ISSUE TITLE
append_before_action append_around_action and append_after_action are just alias methods

### ISSUE THREAD

**Issue by Vincent14** [rails/rails#27261]
### Steps to reproduce

I just tried to log when controller callbacks are triggered and found a strange behaviour of all append_* callbacks, depending of the declaration order.

### Expected behavior
For example, I want append_before_action to be triggered after before_action. Same logic for the two others. I need this to order my before_action callbacks, and I'm sad to see it's not possible to give a parameter to before_action like `order: 1` called by chronological order (regardless of the controller in which it is declared).

### Actual behavior
The current state, from Rails 3, is an alias to before_action, around_action and after_action, unlike prepend_before_action, prepend_around_action and prepend_after_action that are real callbacks, as you can see is the source code : https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/abstract_controller/callbacks.rb#L220

It's so counter-intuitive!

### System configuration
**Rails version**: 5

**Ruby version**: 2

**Comment by al2o3cr** [comment]
Not quite understanding the issue here - `prepend_*` puts them at the beginning, `append_*` and the regular declaration put them at the end. What alternative behavior would fix that issue in your case?

Regarding the ordering of callbacks - I'm more of a fan of callbacks than many people, but I'd still argue that if you've got *that* many `before_action` callbacks coming in from multiple places it's probably an indication you need to do some refactoring.

**Comment by Vincent14** [comment]
I would expect to see append_* executed after the regular declarations. Otherwise I don't see any reason to have two callbacks named differently. By the way, prepend_after_action if executed AFTER append_after_action, that is a complete non-sense (use loggers, you'll see).

You're misunderstanding my needs, it's not about refactoring, it's about ordering, because my actions need to be executed in order. By now, there is only two 'levels' but it should be an "order" parameter taking an integer giving the final priority.

One use case (in an ocean of examples): Just try to check the request IP by a private action in prepend_before_action, to allow or not the visitor to access the route or to be intercepted and redirected. It's basicaly a dynamic security in my application. This action *need* to be executed in first in *every* situation. I'll place it in the application_controller.rb. In this file, I also need to have something using prepend_before_action (just try to imagine, I don't know, I want to print the time when the request started) because of a priority on every other before_action. But if I declare this second prepend_before_action last, it will be executed first. Non-sense. Use loggers, try by yourself. So I decide to declare my prepend_before_actions in reverse order to let the IP verification executed first, in front of everything else.

It's not finished :) Now, I need to except some actions from the time print prepend_before_action, in a child controller. The redefinition of the prepend_before_action make it executed first. Always. No other way than redifining again the IP verification. So heavy to understand, no documentation, only experimentation. I've wrote a long post in french [over there](http://www.sois-net.fr/rails-comprendre-les-callbacks-de-controleur-telles-que-before_action-et-after_action/), it could help you ([Google translated](https://translate.google.fr/translate?sl=fr&tl=en&js=y&prev=_t&hl=fr&ie=UTF-8&u=http%3A%2F%2Fwww.sois-net.fr%2Frails-comprendre-les-callbacks-de-controleur-telles-que-before_action-et-after_action%2F&edit-text=))

**Comment by rafaelfranca** [comment]
If you have more than one callback and those callbacks are oder dependent I strongly recommend you to not use callbacks or merge them together. I got your request but we are not going to add a new option to callback to specify the order. We don't want to perpetuate this code smell.

Yes, we know that after callbacks are executed in backwards order it is also by design. It is not intuitive I agree and we are planning to change it.
