### ISSUE TITLE
`method redefined` warnings for ActiveSupport 5.0.1

### ISSUE THREAD

**Issue by cobaltsoda** [rails/rails#27513]
I've listed ActiveSupport as a runtime dependency for my gem in `.gemspec`. Running `rake test` on the command line succeeds with no errors, however I get the following warnings before any tests run:

    /Users/example/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/time/calculations.rb:243: warning: method redefined; discarding old +
    /Users/example/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/time/calculations.rb:253: warning: method redefined; discarding old -
    /Users/example/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/time/calculations.rb:263: warning: method redefined; discarding old -

I've tried running the same code that uses ActiveSupport in IRB and using the Ruby CLI tool, but the warnings don't appear.

The warnings also appear when I build my gem with [Travis CI](http://travis-ci.org), when `rake test` runs.

I'm running macOS Sierra 10.12.2 and using Ruby 2.3.0 with RVM.

**Comment by pixeltrix** [comment]
@cobaltsoda I think 47c1aee may be relevant here - I had to move the Active Support requires to before the Test::Unit require because that loaded the power_assert gem. This is the relevant section of code in power_assert: 

https://github.com/k-tsj/power_assert/blob/38c13595c068ab912981e1c41914ac1a4720bc83/lib/power_assert/enable_tracepoint_events.rb#L51-L60

Closing because this isn't an issue in Rails.
