### ISSUE TITLE
PostgreSQL 9.5.4 with Rails 5.0.1 JSONB column is returned as string

### ISSUE THREAD

**Issue by moreNilesh** [rails/rails#27788]
### Steps to reproduce
Running Rails 4.2.7.
Upgraded to Rails 5.0.1
Dropped and recreated the database. 
Jsonb column when queried from model comes back as a plain string. schema.rb file shows that the column is jsonb.
I looked at https://github.com/rails/rails/issues/25594 and changed to default: {} for jsonb attribute(earlier it had no default value). Then dropped and recreated the database. Still I hit the same issue.

While populating this attribute the passed arguments is of the form - 
{"A": "Choice A", "B": "Choice B", "C": "Choice C", "D": "Choice D"}.to_json

### Expected behavior
Same as Rails 4.2.7 where jsonb column would be returned as Hash.

### Actual behavior
jsonb column getting returned as a plain string.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.1p112
**PostgreSQL**: 9.5.4

**Comment by al2o3cr** [comment]
`Hash#to_json` is going to return a string, which is a valid object to put in a JSONB column. Do you get the correct result if you remove it?

**Comment by moreNilesh** [comment]
I tried removing it but no luck. The value is not being correctly stored for the jsonb attribute when I remove .to_json call. Stored value is simply default value: {} in this case.

Then I tried storing this attribute value as a string: '{"A": "Choice A", "B": "Choice B", "C": "Choice C", "D": "Choice D"}'; now the string is being correctly stored but while retrieving it, the attribute value is returned as a plain string instead of jsonb.

**Comment by maclover7** [comment]
@moreNilesh To better understand the issue, can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by moreNilesh** [comment]
Okay, I will do that and update once done.

**Comment by whistlerbrk** [comment]
I am getting inconsistent behaviour with JSONB columns whose default are {}

I suspect it may be related to my usage of the activerecord-import gem, I will verify and update my comment

**Comment by rhymes** [comment]
Any news or way to circumvent this ?

I'm trying to upgrade an app from 4.2 but a lot of my tests fail because the 4.2 code assumed the JSONB columns to be transformed to Hash in the user code.

So I can't do stuff like this anymore:

```ruby
object.jsonb_column[:foobar] = "value"
object.save!
```

where jsonb_column is a JSON hash in the database.

The alternative would be to use a method to parse the string coming to Rails 5, modify the hash and serialize it back to string before calling .save! but I assumed that's what Rails should do in the first place and has been doing in 4.x

Any ideas?

**Comment by rafiamafia** [comment]
I am seeing the same error on my end but **only** when I run the test suite locally and in Travis. The test fails when accessing a (postgresql) data column of type `json` for an `ActiveRecord` object, expecting the value to be a `Hash` instead it now returns a `String`.

This was not an issue until I locally upgraded the Rails gem. We are in the midst of upgrading our application to Rails 5.0.1 in attempt to upgrade to 5.1 next. I encountered this issue using RSpec 3.6.0, Ruby 2.4.1 and postgresql 9.5. Interestingly, I am not seeing this problem when accessing a similar `ActiveRecord` object in `rails console`; the `json` value on the object is returned as expected i.e a `Hash`. However, when running `rspec` and a new `ActiveRecord` object is created in the scope of the test, the same `json` attribute is returned as a `String`. When I revert back to Ruby 2.2.2 and Rails 4.2.8, this is not an issue. 

I am currently debugging this issue so any feedback would be valuable. I would like to come up with a resolution rather than a work around i.e check the data type of the attribute and if it is a `String` then do a `JSON.pares(attr)` e.t.c.

**Comment by rhymes** [comment]
Any update? This is a roadblock for us and we can't consider upgrading the app from 4.2.9 to 5.x

Thanks

**Comment by tristanoneil** [comment]
Also ran into this issue with Rails 5.0.4 and Postgres 9.4. Tried the suggestions laid out in https://github.com/rails/rails/issues/25594 (setting the default to `{}`) but that had no effect. Just recently upgraded from Rails 4.2. Overriding the reader for the column and parsing manually for now but definitely seems like a regression.

**Comment by pokonski** [comment]
Same here, upgraded the app from 4.2 and now values are returned as strings. In 4.2 it worked out of the box.

**Comment by maclover7** [comment]
Please see https://github.com/rails/rails/commit/835246e622dc0431af3cb951db22ef78876006af for the full explanation, but this is the expected behavior starting in v5.0.0.

cc @sgrif

**Comment by lumir** [comment]
https://github.com/rails/rails/issues/25594
