### ISSUE TITLE
Add unique and index on rails migration

### ISSUE THREAD

**Issue by matheussilvasantos** [rails/rails#27819]
#### timestamp_create_equipment.rb
```
class CreateEquipment < ActiveRecord::Migration[5.0]
  def change
    create_table :equipment do |t|
      t.string :code, limit: 50, null: false, unique: true, index: true
      t.string :description, limit: 100, null: false
      t.references :equipment_group, null: false, foreign_key: { on_delete: :cascade }, index: true

      t.timestamps
      t.userstamps
    end
  end
end
```

### Expected behavior
It should generate the following index on MySQL

`UNIQUE KEY 'index_equipment_on_code' ('code') USING BTREE`

### Actual behavior
It generates the following index on MySQL

`KEY 'index_equipment_on_code' ('code') USING BTREE`

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1p112

**Comment by kamipo** [comment]
Should be `index: { unique: true }` instead of `index: true`.

**Comment by matheussilvasantos** [comment]
Thank you @kamipo. That is it

**Comment by gooor** [comment]
@kamipo There's still a problem with this syntax. Migration still accepts `unique: true` and creates index as mat stated. That shouldn't be acceptable as it does thing it shouldn't do -> creates an index without unique constraint. Expected behavior should be either to create index with unique constraint or completely remove `unique: true` from being interpreted as it's misleading developer (what was my surprise after I noticed doubled records in DB thinking "but it has uniqe index" :)
