### ISSUE TITLE
require_dependency in model breaks rake db:migrate

### ISSUE THREAD

**Issue by aosyatnik** [rails/rails#27821]
### Steps to reproduce
Run: `rake db:migrate`

I'm running migration and get next error:
![image](https://cloud.githubusercontent.com/assets/8158404/22372202/04d50e42-e4a4-11e6-974a-27a5ea51c61c.png)

My model:
```ruby
require_dependency "core/app/models/concerns/vpos/enums"

class NodeGroup < ActiveRecord::Base
    # some model related code...
end
```

I had to add `require_dependency`, because I had circular dependency issue, when I ran sidekiq(without sidekiq everything is fine). The issue is the same, as here: https://github.com/mperham/sidekiq/issues/1281

One more interesting thing! If I change `require_dependency` into `require_relative`, then everything is working fine(i.e. I don't get circular dependency and LoadError: No such file to load). BUT according this article: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-require I should never do it.

I tried also to resolve this problem by calling `Rails.application.eager_load!`, but had to luck.
Adding to config.autoload_paths `core/app/models/concerns/vpos` also didn't help.

### Expected behavior
Migrations should run without error, when model has `require_dependency`.

### Actual behavior
It fails with message no file.

### System configuration
**Rails version**: Rails 4.1.6

**Ruby version**: ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]

**Comment by pixeltrix** [comment]
@aosyatnik firstly, thanks for not reporting this on that Sidekiq issue - Mike must be sick of that one by now :smile:

The best practise for migrations is not to use models within them and to stick to either the schema functions and if you need to modify data use `execute "<SQL>"`. This ensures that should you later delete a model then your old migrations still work. If you must use a model then defining a copy inline in the migration is the next best option, e.g.

``` ruby
class DeleteAllPosts < ActiveRecord::Migration
  class Post < ActiveRecord::Base; end

  def up
    Post.delete_all
  end

  def down
    raise ActiveRecord::IrreversibleMigration, "can't restore deleted posts"
  end
end
```

If those aren't an option because the model is really complicated for example then I think the problem with your path setup. Not sure where 'core' is coming from - I assume it's the apps root folder? If so then `app/models/concerns` should be in the auto/eager load paths already and you should change your `require_dependency` to `require_dependency 'vpos/enums'`. That's assuming that you've not modified `autoload_path` or `eager_load_path` in `config/application.rb` which is something you shouldn't do without very good cause.

I'm closing this because it appears to be a support issue - if you still think there's a bug in Rails please create a simple repo that replicates the problem and I'll take a look.

**Comment by aosyatnik** [comment]
Hi, @pixeltrix , your answer helped me a lot. `require_dependency` is really tricky :) When I deleted `core/app/models/concerns/` and left `vpos/enums`, it worked just fine. If I have other issues regarding circular dependencies, then I'll create another issue.
Many thanks.
