### ISSUE TITLE
Intermittent failure to recognise table_name_prefix in namespaced model

### ISSUE THREAD

**Issue by simmerz** [rails/rails#27841]
### Steps to reproduce

```
$ rails generate model blog::post title:string post:text
$ rails s
```

Create a controller to load `Blog::Post.all`

### Expected behavior
`Blog::Post.table_name` should be `blog_posts`

### Actual behavior
`Blog::Post.table_name` appears to be `posts` from time to time, but not consistently. It's almost as if the `Blog` module that was generated is loaded before `blog/post.rb` or not at all.

Interestingly, calling `Blog::Post.table_name` always yields the correct result in `rails console`

### System configuration
**Rails version**: 5.0.1

**Ruby version**: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]

**Comment by maclover7** [comment]
Hmm, maybe an autoloading / requiring issue then? cc @fxn

**Comment by fxn** [comment]
So the "actual behavior" is that when you hit the controller action, it blows up saying that there is no "posts" table?

**Comment by simmerz** [comment]
@fxn that's correct.

**Comment by fxn** [comment]
@simmerz could you please provide a minimal application where you verified that happened at least once? To remove variables, better reproduce with spring disabled.

It might be really simple according to the issue, but the description is not self-contained and prefer not to assume which files are exactly under _app_, and what do they exactly have.

**Comment by simmerz** [comment]
@fxn no problem. I'll try and replicate in a clean app and get it up to a repo here for you to look at.

**Comment by simmerz** [comment]
@fxn here you go: https://github.com/simmerz/broken_namespace_model

**Comment by fxn** [comment]
@simmerz thanks, I could reproduce. Replaced Postgres with SQLite, migrate, launch server, hit the endpoint, exception at first try.

Problem is the files _app/models/blog.rb_ and _app/helpers/blog/posts_helper.rb_. One of them defines the `Blog` module, and the other reopens it, and which does what depends on the execution path.

In the flow in which this fails, as described above, the helper gets loaded first, Ruby is able to resolve `::Blog` in the controller so _no autoloading is triggered_, the file _app/models/blog.rb_ is not executed, and hence `Blog` does not have the singleton method that defines the table name prefix.

That also explains why it works in the console, and why it may work intermittently.

There is little Rails can do here because reopening and autoloading on demand just do not play well together. However, the application may choose to force _app/models/foo.rb_ to be the definition and anything else reopening. To do so, always declare using fully-qualified constants:

```ruby
module Blog::PostHelper
  ...
end
```

If the `Blog` module is unknown at that point, autoloading will be triggered and _app/models/blog.rb_ will be loaded.

Alternatively, you could throw

```ruby
require_dependency "blog"
```

on top of _app/models/application_record.rb_ to make sure that file is loaded no matter what.

**Comment by simmerz** [comment]
@fxn Thanks for the really detailed explanation. All makes perfect sense. I guess this can be closed, given there isn't really anything that can be done to minimise this kind of problem automagically.

**Comment by fxn** [comment]
@simmerz awesome, thanks for working on this ticket anyway!
