### ISSUE TITLE
Memory doesn't release

### ISSUE THREAD

**Issue by rodrigorincon** [rails/rails#27965]
I have a function that create a backup of the app and download it in a zip file, with the datas in the databases, images, files, etc. For this i create a big temp file (using the Tempfile class) that send to browser with send_data, but when i delete it after send_data the download failed and its memory is not released.

```
send_file(zip_data.path, type: 'application/zip', filename: "#{model_name}.zip")
zip_data.unlink
```
Service class: http://pastebin.com/MskjP8d7
Controller method: http://pastebin.com/CV9Wr27h

**Comment by al2o3cr** [comment]
`send_file` causes a header to be output that tells the application server "send the data in this location back to the client" - calling `unlink` here could remove the file before the application server is done with it.

[This article](http://hiltmon.com/blog/2013/01/11/ruby-tempfile-aggressive-unlink/) seems relevant; you may want to try switching to `close` instead of `unlink` and rely on `Tempfile` cleaning up in its finalizer.

If that doesn't work, it will be useful to have more information to troubleshoot your issue: a stack trace from when it fails, or even better an executable application that exhibits the bug.
