### ISSUE TITLE
Include documentation on ar_internal_metadata in Active Record Migrations Guide

### ISSUE THREAD

**Issue by thewoolleyman** [rails/rails#27971]
### Steps to reproduce

Go to http://guides.rubyonrails.org/active_record_migrations.html and search for any of the following keywords:

* `NoEnvironmentInSchemaError`
* "Environment data"
* `ar_internal_metadata`
* `db:environment:set`

### Expected behavior

I should find some documentation of the behavior added in https://github.com/rails/rails/pull/22967/files

[This blog post](http://blog.bigbinary.com/2016/06/07/rails-5-prevents-destructive-action-on-production-db.html) would be a good start.

### Actual behavior

No official Rails documentation for this feature exists that I can find via google, and there were no updates to guides in the original PR, even though [it claims there is documentation](https://github.com/rails/rails/pull/22967#issuecomment-239876192).

### System configuration
**Rails version**: 5

**Ruby version**: N/A

**Comment by sgrif** [comment]
I don't see any reason to mention `NoEnvironmentInSchemaError` or `ar_internal_metadata` since these are entirely internal.

**Comment by sgrif** [comment]
Can you be more specific about what exactly you think needs to be documented here? It sounds like you just want the internals listed, which isn't going to happen. The linked page doesn't reference `schema_migrations` either, because how we go about storing that sort of thing isn't relevant to the end user. I don't see a ton of value in adding "Active Record prevents you from running destructive actions against the production database" there. If a user *does* run into an issue resulting from that feature, the error message should fully explain what happened and what they need to do. If you encountered a specific error that you found insufficient, please provide details on what you attempted to do, the error message you received, and how you think it could be improved.

> No official Rails documentation for this feature exists that I can find via google, and there were no updates to guides in the original PR, even though it claims there is documentation.

The relevant methods for interacting with this feature are documented [here](http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema.html#method-c-internal_metadata_table_name) and [here](http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema.html#method-c-protected_environments).

**Comment by thewoolleyman** [comment]
Thanks for the response.

I think my confusion is because when I was using early beta when this feature was first introduced, I got a misleading error message that omitted the part of the command that explicitly sets `RAILS_ENV`.  So, I ended up adding that to my `bin/setup` (with is a non-standard because I use [fixture-builder](https://github.com/rdy/fixture_builder) instead of seeds), and then I ended up getting exceptions I couldn't understand, and had to just swallow them.

However, I can't reproduce that behavior now, and the error messages in the current release seem helpful enough.   Perhaps something changed in [this commit](https://github.com/rails/rails/commit/d70c68d76abcbc24ef0e56b7a7b580d0013255dd).

So, I agree, the error message is informative enough to serve as adequate documentation as it currently behaves, and I'll close this ticket.

Thanks again,
-- Chad

**Comment by thewoolleyman** [comment]
@sgrif OK, here's a real life example where I would have liked some documentation about this in the guides.

I tried to run https://github.com/jalkoby/squasher to squash my schema migrations down.

It creates a temp db to do the migration, but it blew up with:

```
ActiveRecord::NoEnvironmentInSchemaError:

Environment data not found in the schema. To resolve this issue, run:

	bin/rails db:environment:set RAILS_ENV=development
```

Obviously that wasn't gonna work because it's not my default development db that needs the environment set.

So, I **knew** I had to set that env var to disable it, but I could not remember what it was - even though I'd just discussed it 8 days ago in this issue (memory goes with age).

I googled NoEnvironmentInSchemaError, but even though I knew exactly what I was looking for, it still took me a few tries and a few minutes to find it.  The first reference to it was halfway down the page of hits, on https://github.com/grosser/parallel_tests/issues/517#issuecomment-237907275.

Now, you can argue this is an edge case, not many tools will be creating temporary databases and encountering this problem.

However, this situation could also occur in other situations - e.g. restoring a database from a dump of a different env, etc.

Regardless of how likely it is to get these errors, my argument is that:

1. `DISABLE_DATABASE_ENVIRONMENT_CHECK=1` and `db:environment:set` are **not** internal implementation details, they are part of Rails' exposed user interface for controlling the feature added in https://github.com/rails/rails/pull/22967/files.
2. It's currently too hard to find documentation on this user interface.  I don't consider the method docs for `internal_metadata_table_name` or `protected_environments` to be adequate, because they are not at all discoverable if you searching for error messages emitted by this feature.  It took me a while to find the env var when I knew exactly what I was looking for!

Therefore, there should be some reference to this feature, and these two standard ways to control it, in a standard Rails Guide where it will end up being prominent in Google searches when people encounter errors like these.

In addition, (or alternately, if you still don't think this feature should be documented in Rails Guides), I would include the reference to `DISABLE_DATABASE_ENVIRONMENT_CHECK=1` as an alternate option in all of the error messages where `db:environment:set` is currently mentioned.

If you agree, I can try to get a PR together when I have time.

Thanks,
-- Chad

**Comment by AdrienGiboire** [comment]
I can reproduce this issue with the following:

**Comment by markrebec** [comment]
+1 to having this documented. It's almost hilarious how many seasoned rails developers I've heard mention being tripped up (even if briefly) by this feature, which as I understand it, primarily serves the purpose of preventing newbies from dropping their production database.

**Comment by evansgp** [comment]
This issue is now the doco. :) Thanks @thewoolleyman !

**Comment by ahimsauzi** [comment]
This issue becomes more complicated when using a deployment tool like Capistrano. Still can't find a solution or documentation...

**Comment by Schwad** [comment]
Happy 2018! Yes this must now be the documentation. I am currently fighting this flipping thing while running parallel_tests on gitlab ci. I'll let you all know if I find resolution. 

I am wondering if `DISABLE_DATABASE_ENVIRONMENT_CHECK=1` will save my bacon in CI.

**Comment by Schwad** [comment]
Testing now. For anyone on core reading this, I can verify that dealing with this has been a major pain in the rear on our linux-based self-hosted gitlab-ci servers for quite a while. 

It is wholly unclear what is needed to do when this error pops up (because running the recommended script does nothing if the db, which is faulty, already exists), and I have ended up trying to spend a chunk of time hacking around. Docs would have been nice.

**Comment by thewoolleyman** [comment]
@sgrif Since I'm obviously not the only one who was confused by the lack of docs around this, are you open to reconsidering this issue?

**Comment by Schwad** [comment]
I'm writing up a little something right now on my own fork. :) Will be
happy for your feedback when I do the PR formally and will mention here.

**Comment by Schwad** [comment]
@thewoolleyman I think @evansgp meant that this issue *is* the docs?

**Comment by evansgp** [comment]
I apologise, I'm just a passer buy that struggled with the same problem and this was the only discussion on it. I would have PRed something myself but I'm still not clear on the correct way to deal with this.

**Comment by emerak** [comment]
this is happening to me too, even though I have run `bin/rails db:environment:set RAILS_ENV=staging` when I try to load the schema, `db:check_protected_environments` prompts and ask to run `bin/rails db:environment:set RAILS_ENV=staging` again, I think is because `record_environment` only gets trigger when a migration is ran

**Comment by Schwad** [comment]
Currently on leave through next week, hoping to have a PR together and would really appreciate your reviews and thoughts when I submit.

**Comment by markrebec** [comment]
@emerak try putting your env vars in front of the command you're executing - `RAILS_ENV=staging bin/rails db:environment:set`. Also, I honestly couldn't tell ya how this feature behaves when using a non-standard environment like `staging` (and now I'm super curious...)
