### ISSUE TITLE
after_initialize callbacks missing associations on records created by multi-layered nested attribute chain

### ISSUE THREAD

**Issue by renandhein** [rails/rails#28004]
### Steps to reproduce

The following executable, as according to the current active_record bug report template, will throw an exception caused by the problem:
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :as, force: true do |t|
    t.integer :number
  end

  create_table :bs, force: true do |t|
    t.integer :number
    t.integer :a_id
  end

  create_table :cs, force: true do |t|
    t.integer :number
    t.integer :b_id
  end
end

class A < ActiveRecord::Base
  has_one :b, inverse_of: :a

  accepts_nested_attributes_for :b
end

class B < ActiveRecord::Base
  belongs_to :a, inverse_of: :b
  has_many :cs, inverse_of: :b

  accepts_nested_attributes_for :cs
end

class C < ActiveRecord::Base
  belongs_to :b, inverse_of: :cs

  after_initialize :reference_a

  def reference_a
    # causes an exception because a is nil when saving from a nested chain
    self.number = self.b.a.number
  end
end

# works without a problem
a = A.new(number: 12)
a.build_b(number: 15)
a.b.cs.build
a.save!

# does not work because the B to A association is missing on C's after_initialize when everything is built at the same time by rails' nested attributes
params = {a: {number: "12", b_attributes: {"number": "15", cs_attributes: {"0": {number: "17"}}}}}
A.new.assign_attributes(params[:a])
```

### Expected behavior
Consider an association of more than one layer where A belongs to B which belongs to C and building everything in a regular, rails-based standard form using accepts_nested_attributes_for and fields_for in a view. Example as such:

```
<%= form_for(a) do |f| %>
  <%= f.label :number %>
  <%= f.number_field :number %>

  <%= f.fields_for :b do |_b_form| %>
    <%= _b_form.label :number %>
    <%= _b_form.number_field :number %>

    <%= _b_form.fields_for :cs do |_c_form| %>
      <%= _c_form.label :number %>
      <%= _c_form.number_field :number %>
    <% end %>
  <% end %>

  <%= f.submit %>
<% end %>
```
When this submit reaches the controller, all three records are built at the same time by rails itself and therefore it seems reasonable to assume that all the associations in the chain are going to be present in after_initialize callbacks since it's A that creates B and B that creates C.

### Actual behavior
Though rails has had problems with the after_initialize callback not having proper associations loaded in the past in issues like [after_initialize no longer has access to associations](https://github.com/rails/rails/issues/1842), the direct associations are present in after_initialize now for quite some time. In an after_initialize callback in C, its B association that created it is present and working. However, in the after_initialize of C, the association between A and B is not present even though it was A that created B and it feels like it should be. It forces us to be careful about which associations are used in after_initialize callbacks because they might not be present yet in at least this specific, rails handled situation.

### System configuration
**Rails version**:
5.0.1

**Ruby version**:
2.3.0

**Comment by al2o3cr** [comment]
I was reminded of #7332 with this ticket - accessing associations in `after_initialize` can cause weird behavior.

My suspicion is that there's a sequencing issue in the code [here](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/associations/association.rb#L270). Will investigate further.

**Comment by roniegh** [comment]
@al2o3cr @renandhein  considering the example
`params = {a: {number: "12", b_attributes: {"number": "15", cs_attributes: {"0": {number: "17"}}}}}`
`A.new.assign_attributes(params[:a])`

I think this is the current flow:

1. [`assign_attributes({number: "12", b_attributes: {"number": "15", cs_attributes: {"0": {number: "17"}}}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L337)

1. [`assign_nested_attributes_for_one_to_one_association(:b, {"number": "15", cs_attributes: {"0": {number: "17"}}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/nested_attributes.rb#L361)

1. [`send(build_b, {"number": "15", cs_attributes: {"0": {number: "17"}}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/nested_attributes.rb#L419)

1. [`association(:b).build({"number": "15", cs_attributes: {"0": {number: "17"}}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/associations/builder/singular_association.rb#L27)

1. [`record = build_record({"number": "15", cs_attributes: {"0": {number: "17"}}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/associations/singular_association.rb#L19)

1. [`reflection.build_association({"number": "15", cs_attributes: {"0": {number: "17"}}}) do |record|`
`  initialize_attributes(record, {"number": "15", cs_attributes: {"0": {number: "17"}}})`
`end`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/associations/association.rb#L271)

1. [`klass.new({"number": "15", cs_attributes: {"0": {number: "17"}}}, initialize_attributes(record, {"number": "15", cs_attributes: {"0": {number: "17"}}}))`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/reflection.rb#L153)

1. [`assign_attributes({"number": "15", cs_attributes: {"0": {number: "17"}}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L337)

1. [`assign_nested_attributes_for_one_to_one_association(:cs_attributes, {"0": {number: "17"}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/nested_attributes.rb#L361)

1. [`send(build_cs, {"0": {number: "17"}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/nested_attributes.rb#L419)

1. [`association(:cs).build({"0": {number: "17"}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/associations/builder/singular_association.rb#L27)

1. [`record = build_record({"0": {number: "17"}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/associations/singular_association.rb#L19)

1. [`reflection.build_association({"0": {number: "17"}}) do |record|`
`  initialize_attributes(record, {"0": {number: "17"}})`
`end`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/associations/association.rb#L271)

1. [`klass.new({"0": {number: "17"}}, initialize_attributes(record, {"0": {number: "17"}}))`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/reflection.rb#L153)

1. [`assign_attributes({"0": {number: "17"}})`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L337)

1. [`yield self if block_given?`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L339) where block is `initialize_attributes(record, {"0": {number: "17"}})`

1. [`Cs#after_initialize` callback](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L340)

1. [`yield self if block_given?`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L339) where block is `initialize_attributes(record, {"number": "15", cs_attributes: {"0": {number: "17"}}})`

1. [`B#after_initialize` callback](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L340)

1. [`A#after_initialize` callback](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L340)

In my understanding, this issue is caused by the `Cs#after_initialize` callback being run before the `initialize_attributes(record, {"number": "15", cs_attributes: {"0": {number: "17"}}})` block which is responsible for [`set_inverse_instance(record)`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/associations/association.rb#L182)

One possible solution is to move [`yield self if block_given?`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L339) before [`assign_attributes(attributes) if attributes`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L337) if there is nothing else passing a block that must be run after the `assign_attributes` call

Also I think `assign_attributes` is being run twice for the same record, once [here](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L337) and once [here](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/associations/association.rb#L181) through [`yield self if block_given?`](https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/activerecord/lib/active_record/core.rb#L339)

**Comment by renandhein** [comment]
With the test case already done, I downloaded rails 5.1.1 into a clean directory:
$ rails -v
Rails 5.1.1

I ran it again to confirm that the same error verified in the earlier versions still occurs. I can confirm that the error still occurs on the following system configurations:

Rails version:
5.1.1

Ruby version:
2.3.0

**Comment by renandhein** [comment]
I took the liberty to test this error in the newest rails versions and can confirm that it still happens on rails 5.1.2 with ruby 2.4.1. To summarize, still happens on:

Rails version:
5.1.2

Ruby version:
2.4.1

**Comment by tekin** [comment]
@renandhein do you have an actual written test suite test? If so do you mind sharing it?

**Comment by renandhein** [comment]
@tekin Sorry, I don't have one! I can look into creating one if you want to give me the specifics of what you'd like to see, though.

**Comment by renandhein** [comment]
Nevermind! I made a small test case suite. The tests show that it works when building things once by one and, by the reasoning presented in the issue description, it should work when everything is created by mass-assignment as well. I also renamed the classes for the sake of clarity:

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.5"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :authors, force: true do |t|
    t.integer :number
  end

  create_table :galleries, force: true do |t|
    t.integer :number
    t.integer :author_id
  end

  create_table :posts, force: true do |t|
    t.integer :author_number
    t.integer :value
    t.integer :gallery_id
  end
end

class Author < ActiveRecord::Base
  has_one :gallery, inverse_of: :author

  accepts_nested_attributes_for :gallery
end

class Gallery < ActiveRecord::Base
  belongs_to :author, inverse_of: :gallery
  has_many :posts, inverse_of: :gallery

  accepts_nested_attributes_for :posts
end

class Post < ActiveRecord::Base
  belongs_to :gallery, inverse_of: :posts

  after_initialize :reference_author

  def reference_author
    # The try would not be necessary if we could be sure that in every situation gallery will always have author already associated
    self.author_number = self.gallery.author.try(:number)
  end
end

class BugTest < Minitest::Test
  def test_association_after_initialize_assignment
    # Building things one by one
    a = Author.new(number: 12)
    a.build_gallery(number: 15)
    a.gallery.posts.build

    assert_equal(a.number, a.gallery.posts.first.author_number)

    # Building everything at once through rails' nested attribute methods
    params = {author: {number: "12", gallery_attributes: {number: "15", posts_attributes: {"0": {value: "17"}}}}}
    a2 = Author.new
    a2.assign_attributes(params[:author])

    assert_equal(a2.number, a2.gallery.posts.first.author_number)
  end
end
```

I also wrote the test using activerecord 5.1.5 and ruby 2.4.2 to make sure this issue is still happening in these versions. I hope this helps!

**Comment by GBH** [comment]
Oh man. I got burned by this bug just now too. On Rails 5.2.3. Gonna need to find a work-around.

**Comment by patrykk21** [comment]
@GBH what did you opt for?

**Comment by dmitry** [comment]
@patrykk21 @GBH @renandhein  have you solved that issue?
