### ISSUE TITLE
after_initilzed is called after 'dup' for record without id that returns new_record?=false

### ISSUE THREAD

**Issue by thebravoman** [rails/rails#28028]
### Steps to reproduce
Add after_initialize callback in an ActiveRecord model
```
after_initialize do 
  puts self.id
  puts self.new_record?
end
```
Create an instance of the model
Call 
```
m = Model.first.dup
```
### Expected behavior
The after_initialize block is called twice. 
First for the Model.first then for the instance initialized because of dup.
When the second call happens, the one because of the dup in the after_initialize block this happens:
```
m = Model.first.dup
...
after_initialize do #for the dup instance
 self.id -> is nil
 self.new_record? -> is false
end
```
After the after_initialize block we call
```
m.new_record? -> this time it returns true
```

### Actual behavior
I would expect if the instance does not have an id and to be a duplicate of another instance then the self.new_record? in after_initialize to return true. It should return true in the after_initialize and after the after_initialize. Currently it return false in the after_initialize and true after after_initialize.

### System configuration
rails (4.2.7.1)
**Ruby version**:
ruby-2.2.2

**Comment by laertispappas** [comment]
Can't reproduce with Rails 4.2.7.1 and Ruby 2.2.3.

**Comment by laertispappas** [comment]
Extending your above example that you provided the `duped` object returns true on `#persisted?` method too. The code that changes the dup behavior on `ActiveRecord` objects exist  in `active_record/core.rb`. Inspecting the `Core` module you can see the expected behavior:

```ruby
    def initialize_dup(other) # :nodoc:
      @attributes = @attributes.deep_dup
      @attributes.reset(self.class.primary_key)

      _run_initialize_callbacks

      @new_record  = true
      @destroyed   = false

      super
    end
```

We first reset the primary key to nil, then we run the initialize callback and last we mark the record as new.  It's not clear to me from the side effects above why the primary key is reset to nil before the `init` callbacks are run.

**Comment by maclover7** [comment]
Agree with @laertispappas, per the source this is the expected behavior.

**Comment by ponny** [comment]
persisted? also has this strange behaviour.  In this case it's incorrect since it's definitely not persisted at that point.

**Comment by ozydingo** [comment]
I know this is closed but commenting for posterity since this thread allowed me to discover a nasty little bug and maybe it'll help someone else.

The problem I had with this `new_record` behavior is that a *second* `dup` has `new_record` set to `true` in the callbacks. I had a model that has an `after_initailize :set_default_data, if: :new_record?` callback. Elsewhere, we were `dup`ing instances of this model to compute some stats across many models, and recently we added a code path that resulted in the model getting `dup`'d twice. This means that the first `dup` did *not* have its data reset by the `initialize_data` method, but the second `dup` did.

```ruby
# initailize_data is not run on the dup, so `words` is correctly the copy from the original.
transcript.dup.words # => {0 => "foo", 1000 => "bar", ... }
# initailize_data *is* run, so `words` got clobber by `initialize_data`
transcript.dup.dup.words # => {}
```

(Yes, the code path having two dups or really even one is a code smell, but building features on top of monolithic legacy code means sometimes that happens)
