### ISSUE TITLE
Unexpected return (LocalJumpError) triggered in model scope methods in Ruby 2.4.0

### ISSUE THREAD

**Issue by linstantnoodles** [rails/rails#28130]
### Steps to reproduce

Create a model (lets call it `TestModel`) with a scope method.

```
  scope :search_by_params, ->(params) {
    return all if params.empty?
  }
```

Now open up the rails console and execute:

```
> TestModel.search_by_params({})
```

You will get an `unexpected return` error. 

### Expected behavior

I expect to be getting all of my models. 

### Actual behavior

I'm getting an `unexpected return` error. This does not happen with ruby 2.3.1 which I was previously using. 

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.4.0

**Comment by rafaelfranca** [comment]
This is the behavior in Ruby 2.4. You can return inside a proc/lambda

**Comment by linstantnoodles** [comment]
@rafaelfranca What do you mean by that? I tried to return but I'm getting an error. If I can return inside a proc/lambda (in this case, it's a lambda), then why am I getting an error?

**Comment by rafaelfranca** [comment]
I mean, you can't, sorry. But in fact, I just tested and it is not the case. Something changed in ruby that made this feature to change, but I don't think it is a Rails bug.

**Comment by linstantnoodles** [comment]
@rafaelfranca Gotcha. Wish they made it clear in the changelogs for the new release. Thanks for looking into it.

**Comment by Matt529** [comment]
@rafaelfranca I am sorry, but if I understand correctly then that's false. You can `return` in a lambda, this is one of the primary reasons _to_ use a lambda over a proc in some cases. This would be _very_ breaking behavior if this core ruby behavior were to change.

We are upgrading a scope-heavy application to rails 5 and this is an issue caused by, it seems, https://github.com/rails/rails/commit/5e0b555b453ea2ca36986c111512627d806101e7 since now anything that can be made into a proc (via `respond_to?(:to_proc)`) is executed via `instance_exec`.

Note: This was further moved to `Relation#_exec_scope` in https://github.com/rails/rails/commit/45a91511eeced0eb93a7dffd7c3a3f03de21818c.
