### ISSUE TITLE
Rails incorrectly returns 404 instead of 405 status for unsupported HTTP requests

### ISSUE THREAD

**Issue by danfstucky** [rails/rails#28228]
### Steps to reproduce
Make a POST request to a resource that only only accepts GET.
The route, for example could be `resources :my_resource, only: :index`

### Expected behavior
A 405 is returned

### Actual behavior
Rails returns a 404

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.2.3

One of the things that specifies a route is the http verb (GET, POST, etc) and in this situation rails is unable to find the route which is why it is returning a 404. However, according to the [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.6) when the resource exists and is identified correctly, but with an unsupported request method, then the correct status is a 405 NOT a 404. This is particularly important for APIs where there is limited feedback and the response code is important for a consumer to determine the problem.
The Rails framework is not adhering to the W3C standard in this case.

**Comment by meinac** [comment]
Same thing proposed for Phoenix framework [here](https://github.com/phoenixframework/phoenix/issues/2007).

**Comment by pixeltrix** [comment]
I'm generally in agreement with Chris's comments on that Phoenix issue, however I can see that we could do it for actions on `resources` and `resource` definitions by defining an error handler for the route when using the `:only` and `:except` options. e.g:

``` ruby
 resources :posts, only: [:index, :show]
```

That would add error handlers for the following:

```
GET /posts/new #new
POST /posts #create
GET /posts/:id/edit #edit
PATCH /posts/:id #update
DELETE /posts/:id #destroy
```

You can do this today by defining routes for those errors separately, e.g:

``` ruby
resources :posts, only: [:index, :show]

get "/posts/new", to: "errors#method_not_allowed"
post "/posts", to: "errors#method_not_allowed"
get "/posts/:id/edit", to: "errors#method_not_allowed"
patch "/posts/:id", to: "errors#method_not_allowed"
delete "/posts/:id", to: "errors#method_not_allowed"
```

However it'd be nice to wrap that up into `resources` option. I don't think we should extend it out generally since that would add too much complexity to the router which is already complex enough.
