### ISSUE TITLE
current_page? returns false if default_url_options are set

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#28253]
In a view context I see this:
```
(byebug) request.path
"/dashboard/collections"
(byebug) controller.class
Dashboard::CollectionsController
(byebug) current_page?(controller: 'dashboard/collections')
false
```

This should be returning true. It's not because `current_page?` is calling `url_for(options)` and seeing if the returned value contains a `?`.  https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/url_helper.rb#L546-L552

In my case I have a controller method setting the locale parameter on all generated urls:
```ruby
# app/controllers/application_controller.rb 
  # Ensure that the locale choice is persistent across requests
  def default_url_options
    super.merge(locale: I18n.locale)
  end
```

So, `url_for(controller: 'dashboard/collections')` is "/dashboard/collections?locale=en" and then the fullpath does not match.

**Comment by jcoyne** [comment]
Here is one way to work around this:
```ruby
current_page?(controller.default_url_options.each_with_object({}) { |(k, v), h| h[k] = nil }.merge(controller: 'dashboard/collections'))
# => true
```

**Comment by pixeltrix** [comment]
@jcoyne is `:locale` meant to be passed around via a query param or is it meant to be in the path?

**Comment by jcoyne** [comment]
@pixeltrix I'm doing it as a query param.

**Comment by sikachu** [comment]
From the sample you provided, I can confirm that I get the same result as yours. However, I'm not sure if it's really a problem.

Currently, Rails ignores the path parameters only if path generated form `url_for` contains no parameters (`?` sign, as you said). It makes sense because if someone actually passing a parameters to `current_page?` they would expect that that parameter is being used to match the current path with parameters in the URL.

For your case, the easiest way to do it is to pass in `:locale` explicitly instead:

```ruby
current_page?(controller: 'dashboard/collections') #=> false
current_page?(controller: 'dashboard/collections', locale: params[:locale]) #=> true
```

This should work in most of the case. Please let me know if it's not.

**Comment by jcoyne** [comment]
@sikachu yes, that solution will probably work, but it's a bit unsatisfying.  If I ever change `default_url_options` I will have to change dozens of calls to `current_page?`. This wouldn't be optimal.

**Comment by elsurudo** [comment]
@jcoyne Did you ever find a more satisfying solution to this?

**Comment by jcoyne** [comment]
@elsurudo No. :sad
