### ISSUE TITLE
Erubis deprecation warning with haml-rails

### ISSUE THREAD

**Issue by francescm** [rails/rails#28330]
### Steps to reproduce

add to Gemfile: `haml-rails`

execute:

    bundle exec rake -T

### Expected behavior
No deprecation warnings.

### Actual behavior
Received the warning:

    DEPRECATION WARNING: ActionView::Template::Handlers::Erubis is deprecated and will be removed from Rails 5.2. Switch to ActionView::Template::Handlers::ERB::Erubi instead. (called from <top (required)> at /Users/francesco/sviluppo/rails/moose/config/application.rb:7)

### System configuration
**Rails version**:
5.1.0.beta1
**Ruby version**:
2.4.0

**Comment by kaspth** [comment]
This is intentional: we're moving to a new ERB handler in future Rails versions and have discontinued the old `::Erubis` handler.

`haml-rails` needs to update itself to use that, which iirc, they already have. Try `bundle update haml-rails`ing or looking at their release notes (that likely says "Rails 5.1 support"). Thanks!
