### ISSUE TITLE
active_record calculations error with first_or_create conditions

### ISSUE THREAD

**Issue by aokolovich** [rails/rails#28424]
if use "first_or_create" method for create object with conditions:
user = User.where(email: 'foo@bar.com', name: 'Artemy').first_or_create
and in model User have this code:

  def set_num
    if self.num.nil?
      max = self.class.maximum('num')
      self.num = max + 1
    end
  end

executing this query:
SELECT MAX("ms_users"."num") FROM "ms_users" WHERE "ms_users"."email" = $1 AND "ms_users"."name" = $2  [
["email", "foo@bar.com"], ["name", "Artemy"]]

if use simple create:
user = User.create(email: 'foo@bar.com', name: 'Artemy')
executing this right query:
SELECT MAX("ms_users"."num") FROM "ms_users"

first_or_create conditions adding to calculations query

ruby 2.3.0
Rails 5.0.0.1

**Comment by musicmage4114** [comment]
Hey there!

Your issue request seems a little unclear, could you provide a few more details? What is the expected versus actual behavior you're experiencing?

**Comment by EddM** [comment]
In an attempt to clarify this, it seems to me the issue being reported is that the following AR query in `#set_num` (instance method of a `User` model) in the given example:

````ruby
self.class.max('num')
````

... is including the `where` clause from the AR query `first_or_create` is called on.

````ruby
User.where(email: 'foo@bar.com', name: 'Artemy').first_or_create
````

**Expected:**

````sql
SELECT MAX("ms_users"."num") FROM "ms_users"
````

**Actual:**
````sql
SELECT MAX("ms_users"."num") FROM "ms_users" WHERE "ms_users"."email" = $1 AND "ms_users"."name" = $2 [["email", "foo@bar.com"], ["name", "Artemy"]]
````

(BTW I haven't tried to repro this or anything, and I haven't looked to see if this is expected behaviour, I'm just trying to improve the readability of the issue)

**Comment by EddM** [comment]
Reporter's confusion could be because the `current_scope` established by the `#where` persists in instance methods on objects created by `#first_or_create` when you wouldn't expect it to. When working with `self.class` (or just `User`) in a model's instance method, you would expect to be working with an _unscoped_, or at least _default scoped_, `ActiveRecord::Relation`, yet the original scope still applies.

FWIW, I can only repro this when these instance methods are invoked as callbacks (`before_save`, etc.). And also, only with `#first_or_create` - when creating an object with `#first_or_initialize` and then calling `#save`, `current_scope` is behaving as expected.

I'd imagine this isn't intended behaviour, but correct me if I'm wrong.

@aokolovich as a workaround, explicitly applying the default scope should fix your problem? e.g.:

````ruby
self.class.default_scoped.maximum('num')
# => SELECT MAX("table"."num") FROM "table"
````

**Comment by seanlinsley** [comment]
This ticket should be re-opened IMO.

**Comment by aokolovich** [comment]
Rails 5.1.3 OK

class Project::Project < ApplicationRecord
  def max
    self.class.maximum(:title)
  end
end

2.4.1 :003 > p = Project::Project.where(title: 'sample2', slug: 'sss2').first_or_create
  Project::Project Load (0.4ms)  SELECT  "project_projects".* FROM "project_projects" WHERE "project_projects"."title" = $1 AND "project_projects"."slug" = $2 ORDER BY "project_projects"."id" ASC LIMIT $3  [["title", "sample2"], ["slug", "sss2"], ["LIMIT", 1]]
   (0.1ms)  BEGIN
  SQL (0.3ms)  INSERT INTO "project_projects" ("title", "slug", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["title", "sample2"], ["slug", "sss2"], ["created_at", "2017-08-31 05:20:55.647081"], ["updated_at", "2017-08-31 05:20:55.647081"]]
   (0.9ms)  COMMIT
 => #<Project::Project id: "142e7b09-5873-490e-bf98-7fcd5baa1877", title: "sample2", slug: "sss2", domain: "", state: nil, options: nil, created_at: "2017-08-31 05:20:55", updated_at: "2017-08-31 05:20:55"> 
2.4.1 :004 > p.max
   (0.5ms)  SELECT MAX("project_projects"."title") FROM "project_projects"
 => "sample2"
