### ISSUE TITLE
ActiveSupport::InheritableOptions does not work with string keys

### ISSUE THREAD

**Issue by Tonkpils** [rails/rails#28454]
### Steps to reproduce

```ruby
h = ActiveSupport::InheritableOptions.new({"test" => "key"})
=> {}
h.test
=> nil
```

(Guidelines for creating a bug report are [available here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
I should be able to interact with the `InheritableOptions` in the same manner as the `OrderedOptions` object. String keys should be converted to symbols.

### Actual behavior

From the documentation, initializing an `InheritableOptions` object should behave similarly to `OrderedOptions` on the given hash. However, this is not the case as seen here:

```ruby
2.3.1 :009 > h = ActiveSupport::OrderedOptions.new
 => {}
2.3.1 :012 > h["hello"] = "test"
 => "test"
2.3.1 :013 > h.hello
 => "test"
```

I would be glad to provide a fix for this if you all think this is something worth fixing. 

### System configuration
**Rails version**:
4.2.7.1

**Ruby version**:
2.3.1

**Comment by pixeltrix** [comment]
@Tonkpils what's your use case scenario here? The comparison with `ActiveSupport::OrderedOptions` isn't strictly correct - doing the same set of instructions with `ActiveSupport::InheritableOptions` works fine, e.g:

```
>> h = ActiveSupport::InheritableOptions.new
=> {}
>> h["hello"] = "test"
=> "test"
>> h.hello
=> "test"
```

Given that's it's used for simple configuration objects I'd rather not force a duplication - you can easily symbolize the hash manually when creating the instance, e.g:

```
>> h = ActiveSupport::InheritableOptions.new({"hello" => "test"}.symbolize_keys)
=> {}
>> h.hello
=> "test"
```

Doing that `symbolize_keys` internally would force creation of a new hash even when the keys were already symbols. This is something we've done in the past throughout Rails by constantly calling `to_sym` or `to_s` in various places and it's something we're trying to move away from since it has a tendency to cause memory bloat and unexpected side effects that can sometimes result in security issues. I remember one scenario where we stopped doing a `to_sym` for an Active Record associations because at the time symbols weren't garbage collected and the result was [GitHub spammed a bunch of people][2].

BTW, there are much bigger problems with this class - the fact that `inspect`, `keys` and `values` are all missing the inherited hash for one but I don't think we want write a general purpose class here - there's plenty of libraries that do that job such as the [hashie gem][1].

Thanks for your report.

[1]: https://github.com/intridea/hashie
[2]: https://github.com/blog/1440-today-s-email-incident
