### ISSUE TITLE
.last method working weirdly rails

### ISSUE THREAD

**Issue by Faisal-nfl** [rails/rails#28455]
I have an Model named Page
   ```
 class Page < ApplicationRecord
      has_many :details, dependent: :destroy
    end

```
and Detail
```

    class Detail < ApplicationRecord
      belongs_to :page
    end
```

Everything was working fine, but now when I call

`page.find(29).details.last(2), it gives`

   ```
  [#<Detail id: 379, followers: 1055869, follows: 42, media_count: 325, page_id: 29, created_at: "2017-03-15", updated_at: "2017-03-16 19:31:26">,
     
    #<Detail id: 309, followers: 785870, follows: 0, media_count: 0, page_id: 29, created_at: "2017-03-10", updated_at: "2017-03-10 23:30:10">]

```
and if I try `page.find(29).details.last`

     `#<Detail id: 309, followers: 785870, follows: 0, media_count: 0, page_id: 29, created_at: "2017-03-10", updated_at: "2017-03-10 23:30:10">
`
why its showing record with **id= 309** as latest instead of **id=379**

To clarify I manually updated record with `id=309` before this issue,

I tried to update `id='379'` but still its showing last record as `id=309`
**(moreover I also changed created_at type to date from datetime a month ago as I needed it)**

'm I missing something or its actually weird

**Rails version**:
Rails 5.0.0.1
**Ruby version**:
ruby 2.3.1p112

**Comment by nynhex** [comment]
Perhaps you manually altering database ids and changing the created_at to a date datatype had something to do with it?  Curious as to why you needed created_at as a date datatype since you have access to all of the date information with a datetime datatype?

Can you produce a script with some seeded data that reproduces this?  I'm thinking it has to do with you changing IDs and the created_at datatype but can't be sure without being able to reproduce.

I'm on 5.0.0.1 and 2.3.1 and have an app with similar associations and cannot replicate this.

**Comment by uzbekjon** [comment]
Let's try to identify where the problem lies (rails or db). What was the generated SQL query? With your setup it should have something along the lines of `ORDER BY "details"."id" DESC LIMIT 1`.

PS. I've just tried to replicate the problem and correct sql query is generated. So, you should file an issue with your db project. What db are you using?

**Comment by Faisal-nfl** [comment]
I 'm using PostgreSQL,
I never changed ids.
 local machine `SELECT  "details".* FROM "details" WHERE "details"."page_id" = $1 ORDER BY "details"."id" DESC LIMIT $2`

which is working fine,

 but on cloud66 server its causing the issue which I described.

I 'm not sure that I can reproduce it,
But I never changed ids.

**Comment by uzbekjon** [comment]
Query from working machine doesn't provide anything. Show the query from the machine that is having the issue. You can read it from the log file.
