### ISSUE TITLE
after_find/after_initialize execute on wrong object when calling model.reload

### ISSUE THREAD

**Issue by curtp** [rails/rails#28489]
Hello,

In encountered this issue when trying to clear some instance variables (@var) on the model when the model is reloaded via the reload method.  I tried both after_find and after_initialize with the same result.  Here is a sample class along with the output of the object_id's showing what object the callback is executed on when calling reload:

```
class Post < ActiveRecord::Base
	after_find :do_stuff

	def do_stuff
		puts "object_id: #{self.object_id}"
	end
end
```
In the console
=> post = Post.first
=> object_id: 70852720
=> post.object_id
=> 70852720
=> post.reload
=> object_id: 70900820

I expected the object id from the post.reload call to be 70852720, but it looks like it is a completely different object.  Since it is a different object, the variable I'm trying to clear doesn't exist.

Rails Version: 4.2.5.1
Ruby Version: 2.3

I was able to get around it by overloading the reload method as such:

```
def reload(options = nil)
	super(options)
	do_stuff
	return self
end
```

Thanks!

**Comment by maclover7** [comment]
Hi @curtp! This is the expected behavior -- within `reload`, we [create a fresh object, and then copy over the attributes to the original one](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/persistence.rb#L450-L459). The `after_find` callback is getting called with the new object, not the original one.

**Comment by thesmart** [comment]
I encountered this issue today also. This is not at all the expected behavior. What's the point of having `after_find` called with a random garbage model?  Seems that the entire point of a lifecycle callback is to deal with the lifecycle of the instance being reloaded.  Whoever implemented reload by calling find on this other instance ought to have called the hook on `self` as well.
