### ISSUE TITLE
Create association doesn't roll back

### ISSUE THREAD

**Issue by skukx** [rails/rails#28536]
Rails 5.0.2
Ruby 2.3.1

I'm not sure whether this is a feature or a bug. For the given models:

```ruby
class Foo < ApplicationRecord
  has_many :bars
end

class Bar < ApplicationRecord
  belongs_to :foo

  before_create do
    throw(:abort)
  end
end
```

And running:
```ruby
##
# These are expected and work as expected
foo = Foo.create
# => BEGIN
# => COMMIT

bar = Bar.create
# => BEGIN
# => ROLLBACK

##
# This is what I would expect
foo.bars.create
# => BEGIN
# => ROLLBACK

##
# This is what actually happens
foo.bars.create
# => BEGIN
# => COMMIT
```

So even though the class `Bar` throws `:abort`, Rollback is not called.
If this is a feature, and I rely on `after_rollback` to undo something crucial elsewhere; Then I shouldn't count the create association as reliable or rethink the way I'm undoing crucial code.

**Comment by betesh** [comment]
Possibly related: #27789

**Comment by betesh** [comment]
With rails 5.1.1:

```
$ bin/rails c
Running via Spring preloader in process 11107
Loading development environment (Rails 5.1.1)
2.3.4 :001 > foo = Foo.create
   (0.0ms)  begin transaction
  SQL (0.7ms)  INSERT INTO "foos" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2017-06-22 13:08:00.329485"], ["updated_at", "2017-06-22 13:08:00.329485"]]
   (13.6ms)  commit transaction
 => #<Foo id: 1, created_at: "2017-06-22 13:08:00", updated_at: "2017-06-22 13:08:00"> 
2.3.4 :002 > bar = Bar.create
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
 => #<Bar id: nil, foo_id: nil, created_at: nil, updated_at: nil> 
2.3.4 :003 > foo.bars.create
   (0.1ms)  begin transaction
   (0.1ms)  commit transaction
 => #<Bar id: nil, foo_id: 1, created_at: "2017-06-22 13:08:16", updated_at: "2017-06-22 13:08:16"> 
```

So the bar is not saved, but the transaction is not rolled back

**Comment by betesh** [comment]
Another way to demonstrate this (also rails 5.1.1):

```
2.3.4 :009 > foo=Foo.new
 => #<Foo id: nil, created_at: nil, updated_at: nil> 
2.3.4 :010 > foo.bars.build
 => #<Bar id: nil, foo_id: nil, created_at: nil, updated_at: nil> 
2.3.4 :011 > foo.save
   (0.2ms)  begin transaction
  SQL (0.2ms)  INSERT INTO "foos" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2017-06-22 13:14:57.322741"], ["updated_at", "2017-06-22 13:14:57.322741"]]
   (17.6ms)  commit transaction
 => true 
```

**Comment by betesh** [comment]
This is still happening on master (204c0407103ad924c4132636966421c74b49083d) and 5-1-stable (731c7f9ba7518645a0f48f40971afc486088f1ee).

------------------------

For reference, a script to quickly get setup (with master):

```
$ rails new issue_28536 && cd issue_28536 && git init . && git add . && git commit -m "Initial commit"
$ sed -ri "s/gem 'rails', '~> 5.2.0.alpha'/gem 'rails', github: 'rails\/rails'/" Gemfile
$ echo "gem 'arel', github: 'rails/arel'" >> Gemfile
$ bundle install && rails generate model foo && rails generate model bar foo:references && rails db:migrate
$ echo "class Foo < ApplicationRecord
  has_many :bars
end" > app/models/foo.rb
$ echo "class Bar < ApplicationRecord
  belongs_to :foo

  before_create do
    throw(:abort)
  end
end" > app/models/bar.rb
$ git add . && git commit -m "Add models"
$ rails console
```

The follow the instructions from my earlier comment: https://github.com/rails/rails/issues/28536#issuecomment-310376501

**Comment by al2o3cr** [comment]
I created a [standalone test case](https://gist.github.com/al2o3cr/6a27105e1e3e42d05423b681744cd922) for this. The first three all fail, as a record is written to the `posts` table and committed. I also verified this back to 4.1.x (with the callback returning `false` instead of `throw(:abort)` as needed).

The documentation is fuzzy on this - `ActiveRecord::Callbacks` says 

`If a before_* callback cancels the action a ROLLBACK is issued.`

In the cases where we call `post.save` or `post.save!`, the rollback happens inside two `ActiveRecord::Base.transaction` calls - so the nested transaction is popped but no rollback actually happens. This is described in [Nested Transactions](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html#module-ActiveRecord::Transactions::ClassMethods-label-Nested+transactions) in the documentation.

This behavior appears to date back quite a ways - the documentation linked above was already present in 2008.

I'm unsure what the correct behavior here is, but having `save!` silently return a partially-saved object graph does seem surprising to me.

**Comment by HDLP9** [comment]
Confirmed that this is still happening in rails 5.1.4 with ruby 2.4.2. I've managed to keep the transaction clean by avoiding the use of collection.create!

Workaround is to change:

`current_user.documents.create!(....)`

to something like:

`Document.create!(user: current_user, ...)`
