### ISSUE TITLE
Idea: Add interactive prompt y/n prompt before executing 'bin/rails db:drop'

### ISSUE THREAD

**Issue by frewsxcv** [rails/rails#28653]
Right now, when one executes `bin/rails db:drop`, the command is executed without warning the user about implications of the action, which could result in a loss of important data and a bad UX. I think some sort of warning prompt would be helpful for users to prevent these accidental scenarios.

As a comparison, here's what Django prompts when the user attempts to 'flush' (wipe) the databases:

```
$ ./manage.py flush
You have requested a flush of the database.
This will IRREVERSIBLY DESTROY all data currently in the '/private/tmp/lol/db.sqlite3' database,
and return each table to an empty state.
Are you sure you want to do this?

    Type 'yes' to continue, or 'no' to cancel: 
```

There could be a `bin/rails db:drop --noprompt` flag to override this and go back to the destructive no prompt behavior (or maybe `bin/rails db:drop NOPROMPT=1`?).

I'd be willing to implement this if this a desired change :)

**Comment by nthj** [comment]
I was curious if PostgreSQL had a prompt for `dropdb`. It does, but only if you pass the `-i` flag. My instinct is that `do:drop` is appropriately scary. 

If implemented, I would propose `--force` over `--noprompt`. Also, should we bypass the prompt in the test environment?

**Comment by rafaelfranca** [comment]
But why do you need prompt, if you ran the command it is not it what you want? The command already is really clear about that it does, drop the database.

**Comment by frewsxcv** [comment]
> But why do you need prompt?

Humans make mistakes sometimes. Adding a prompt is a helpful way to prevent a very bad scenario from occurring. I have certainly run commands on accident while navigating through my shell history. Just trying to look out for others :)

> The command already is really clear about that it does, drop the database.

In my opinion, it's not that clear, especially since one can't add `--help` to the task, and if one try to do `rake db:drop -- --help`, it deletes ones databases.

**Comment by rafaelfranca** [comment]
The name of the task is `db:drop` what it would do if not drop a database?

Thank you for the suggestion but I don't think is worth adding a protection to avoid people of doing mistakes. [Rails provides sharp knifes](http://rubyonrails.org/doctrine/#provide-sharp-knives), of course they can injure people, but it is not because of this that we will give a plastic knife to the users.

Other ways to avoid this mistake:
* don't give people access to the production database
* do backups regularly and test them
* ask for review of the commands you are going to run in production
