### ISSUE TITLE
routes.rb is not strictly followed in tests

### ISSUE THREAD

**Issue by sergiutruta** [rails/rails#28650]
### Steps to reproduce
[test_routing.zip](https://github.com/rails/rails/files/890129/test_routing.zip)

I have attached a sample of a simple Rails 5.0.2 app with a simple controller with two actions (in my sample it's home_controller.rb). Each has a route defined in routes.rb, one responding to GET and the other one responding to POST.
If I try to GET the post action in the browser, I'm getting an error which is correct, if I try to POST to the get action, I get an error which is correct.

But, if I POST to the get action from inside my controller test (which in my sample is home_controller_test.rb) I don't get any error, and also if I GET The post action from inside my controller test I don't get any error. I haven't investigated more inside the Rails stack but it looks like routes.rb is not followed strictly inside the testing environment. 

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
Inside tests when I POST to an action which only has a GET route defined, I should get an error.
Inside tests when I GET an action which only has a POST route defined, I should get an error.

### Actual behavior
Inside tests when I POST to an action which only has a GET route defined, it works.
Inside tests when I GET an action which only has a POST route defined, it works.

### System configuration
**Rails version**:
5.0.2

**Ruby version**:
2.2.2-p95

**Comment by mubashirhanif** [comment]
It because you are asserting the response as `:error` which works for HTTP Error Codes range ***500-599***, while if the action is not found it gives us ***404*** which is not in the range, for this ***404*** we use `:missing`. if you use `:missing` the tests will pass.
You can refer [here](http://api.rubyonrails.org/classes/ActionDispatch/Assertions/ResponseAssertions.html#method-i-assert_response) for the documentation on `assert_response`

**Comment by maclover7** [comment]
Can confirm this behavior on master. This is occurring because we simply assign [`HTTP_METHOD`](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L478), without doing any checks to make sure a route exists for the combination of HTTP method and controller action provided.

**Comment by pixeltrix** [comment]
This is the long standing behaviour of controller tests, which are unit tests. They don't send a request via a Rack app and instead just call a controller action directly with a mocked up request. If you want routing to be respected use an integration test instead - much work was done on them for Rails 5.0 and they're now faster that controller tests in Rails 4.2 so there's no excuse not to use them.

Since controller tests have been 'soft-deprecated' doing any work to fix this behaviour will only turn them into integration tests which seems somewhat pointless.
