### ISSUE TITLE
Cross schema foreign key

### ISSUE THREAD

**Issue by Bongs** [rails/rails#28654]
### Steps to reproduce
I'm working on multitenant rails app (using apartment gem) and have two tables, one in "public" schema and other in tenant-specific schema. I'm trying to create cross-schema foreign key in migration as below:
```
class CreateStates < ActiveRecord::Migration[5.0]
  def change
  	create_table :states do |t|
      t.string :name
      t.string :code, limit: 2
    end
  end
end

class CreateParties < ActiveRecord::Migration[5.0]
  def change
    create_table :parties do |t|
      t.string :name
      t.string :type
      t.integer :state_id
      t.timestamps
    end

    add_foreign_key :parties, "public.states", column: :state_id
  end
end
```
After running migration

### Expected behavior
It should associate "state_id" to "public.states" table.
**schema.rb** should have: `add_foreign_key "parties", "public.states", column: "state_id"`

### Actual behavior
It fails to create association to table in "public.states", instead associate with "<tenant_specific_schema>.states" table.
**schema.rb**: `add_foreign_key "parties", "states"`

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.4.0

**Database**: PostgreSQL (gem v0.20.0)

When I manually change the "schema.rb" and add `add_foreign_key "parties", "public.states", column: "state_id"` it work perfectly fine. To have this effect I've to do `rake db:schema:load` which I want to avoid.

Why does it work from "schema.rb" but doesn't work as expected from migration?

**Comment by Bongs** [comment]
Well seems like the code in migration generate correct foreign keys, just that it generates wrong entry in "schema.rb".

**Comment by joshaidan** [comment]
Hey, just taking a bit of time to study this issue. I noticed in #29023 @DmytroVasin commented that if you specify another schema, rails will detect it fine. So my guess is that since `public` is the default schema, then that's why it's hidden.

However, I'm not entirely familiar with apartment gem, but I suspect that you need the public schema specified on the `add_foreign_key` call, perhaps to prevent it from being associated to the tenant_specific_schemas when you run your migrations?

Anyway, the cause of your issue is likely related to this SQL query in `schema_statements.rb` in `def foreign_keys(table_name)` of the postgresql connection adapter, where the foreign key names are pulled:

```sql
SELECT t2.oid::regclass::text AS to_table, a1.attname AS column, a2.attname AS primary_key, c.conname AS name, c.confupdtype AS on_update, c.confdeltype AS on_delete
            FROM pg_constraint c
            JOIN pg_class t1 ON c.conrelid = t1.oid
            JOIN pg_class t2 ON c.confrelid = t2.oid
            JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid
            JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid
            JOIN pg_namespace t3 ON c.connamespace = t3.oid
            WHERE c.contype = 'f'
              AND t1.relname = #{scope[:name]}
              AND t3.nspname = #{scope[:schema]}
            ORDER BY c.conname
```

**Comment by DmytroVasin** [comment]
@Bongs Could you please create dummy app for this issue with step to reproduce?

**Comment by Bongs** [comment]
@DmytroVasin I'll create a dummy app for this and update as soon as possible.

**Comment by Bongs** [comment]
Here is a **[demo app](https://github.com/Bongs/demo_cross_schema_fk)** that you can clone to test. I've mentioned steps in its readme file. On a quick note, seems like apartment gem has issue with rails v5.1.x. It works fine with rails v5.0.2. So I've locked the versions in Gemfile. Hope it helps.

**Comment by DmytroVasin** [comment]
Thanks for such well-detailed demo. But I think that I will not say anything new:

When you add Foreign Key constraints in migration, for rails it is not a schema-specific reference. Thats why `t2.oid::regclass::text` does not return `public.something` key. Based on that - rails displays `add_foreign_key "companies", "states"` in `schema.rb`.

But when you do `Apartment::Tenant.create`: Apartment gem copy `schema.rb` and load all tables to tenant-specific schema. ( Current schema is equal to `testco`, because you applied `Apartment::Tenant.switch!('testco')` in the demo )

This is issue should be solved inside `apartment` gem.
It should not simple copy all tables from `schema.rb`. 
I'm not familiar enough with this gem, maybe author has [some restrictions](https://github.com/influitive/apartment#excluding-models). 

But in my opinion - that is not a Rails Issue.

**Comment by matthewd** [comment]
Yeah, `public.` is omitted (by PostgreSQL, not Rails) because it's unnecessary when we're already working in the `public` schema, which we are during the create/migrate/seed sequence.

Any behaviour related to the schema switching & duplication that comes after that is a matter for Apartment.

**Comment by joshaidan** [comment]
@Bongs what if you used a different schema other than public to store the states (non-tenant) table? When I take the demo app and specify a schema other than public for the states table, rails produces the tables names in the correct schema scope in schema.rb:

```ruby
  add_foreign_key "companies", "settings.states", column: "state_id"
  add_foreign_key "parties", "settings.states", column: "state_id"
```
I do seem to hit a different error though when rails tries to load the schema for the states table:
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "public.states" does not exist
LINE 8:                WHERE a.attrelid = '"public"."states"'::regcl...
```
But I haven't yet had time to troubleshoot why it's looking for states in the public schema. Hopefully I'll get to it soon.

**Comment by arturtr** [comment]
The solution found by me with `apartment`
```ruby
class AddForeignKeysForYearAssignments < ActiveRecord::Migration[5.1]
  def up
    execute <<~SQL
      ALTER TABLE #{schema}.year_assignments
        ADD CONSTRAINT fk_year_assignments_lessons FOREIGN KEY (lesson_id)
          REFERENCES public.lessons(id)
    SQL
  end

  def down
    execute <<-SQL
      ALTER TABLE #{schema}.year_assignments
        DROP CONSTRAINT fk_year_assignments_lessons
    SQL
  end

  private

  def schema
    Apartment::Tenant.current
  end
end
```

It will be good to add abilty to pass `add_foreign_key` arguments as a hash
```ruby
add_foreign_key {schema: schema, table_name: :year_assignments}, 
                {schema: 'public', table_name: :lessons}
```

**Comment by defaye** [comment]
Has any of this functionality been included within later versions of Rails?
