### ISSUE TITLE
ActiveSupport::TimeZone doesn't know standard timezones

### ISSUE THREAD

**Issue by 42he** [rails/rails#28696]
### Steps to reproduce

irb(main):002:0> Time.zone = "Berlin"
=> "Berlin"
irb(main):003:0> Time.now.strftime('%Z')
=> "CEST"
irb(main):004:0> ActiveSupport::TimeZone["CEST"]
=> nil

### Expected behavior

 ActiveSupport::TimeZone["CEST"] => "Berlin"

### Actual behavior
 ActiveSupport::TimeZone["CEST"] => nil

### System configuration

5.0.2

**Ruby version**:

ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]

**Comment by avit** [comment]
This doesn't look like a bug. `CEST` is not a TZ, it's an alias for a time offset:

1. The _S_ specifies "standard" time, which only applies part of the year. The DST change rules are not specified for when it becomes `CEDT`.

1. It's part of a "meta-zone" for Central Europe, which could (potentially) have different rules based on political boundaries. E.g. "CST" in North America technically includes Saskatchewan (`TZ=America/Regina`) even though that region doesn't follow DST along with the rest of the Central Time.

**Comment by 42he** [comment]
The CET (without DST) is accepted by Active Support. 

I would argue, that a TimeZone, wich Ruby automatically sets when you enter Paris or Berlin, should also be accepted by Rails. Because "Berlin" is what you normally have in the dropdown and save to the database....

**Comment by rafaelfranca** [comment]
This is not a Rails issue. Like @avit this identifier is invalid since it is not a time zone. You can see that it is not in the database:

```
>> require 'tzinfo'
=> true
>> TZInfo::Timezone.new("CEST")
TZInfo::InvalidTimezoneIdentifier: Invalid identifier
	from /Users/rafaelfranca/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/zoneinfo_data_source.rb:208:in `load_timezone_info'
	from /Users/rafaelfranca/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone.rb:92:in `get'
	from /Users/rafaelfranca/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone.rb:113:in `new'
	from (irb):2
	from /Users/rafaelfranca/.rbenv/versions/2.4.0/bin/irb:11:in `<main>'
>> TZInfo::Timezone.new("CET")
=> #<TZInfo::DataTimezone: CET>
```

**Comment by avit** [comment]
(Sorry, I got confused in my first reply, CEST is actually Summer Time including DST, and CET is the actual winter Standard Time.)

`"CET"` is in the database since it's the Standard Time version of CEST. The colloquial name for this "meta-zone" can be given as "CET", but that's still not a proper zone identifier.

Technically `CET` and `CEST` really only means `+0100` and `+0200`. This doesn't specify what the rules are for when time changes, so it is only an offset, not a zone.

**Comment by 42he** [comment]
https://en.wikipedia.org/wiki/Central_European_Summer_Time

CET/CEST not only mean +1/+2, because the have defined dates where the two switch. 

https://en.wikipedia.org/wiki/Summer_Time_in_Europe

But thats not the point. 

The Point it that RUBYs Time.zone delivers it back, when I set an real TZ String like "Berlin". 

I'm just saying, that ActiveSupport should accept every entry from a standard ruby lib... 

Perhaps it's a Bug in MRI that it makes Berlin to CEST?

**Comment by avit** [comment]
CET and CEST are not two different zones. There is only one "CET" zone, and it has different offsets used within the zone. (It just happens that the standard _offset_ name is the same as the _zone_ name.)

What you have is:

* "Europe/Berlin" (or Central European Time) is a **zone**
  * uses +0100 in winter (aka. "CET" **offset**)
  * uses +0200 in summer (aka. "CEST" **offset**)

> The Point it that RUBYs Time.zone delivers it back, when I set an real TZ String like "Berlin".

Ruby only outputs the _string_ "CEST" when you printf a summer time. At different times it may output "CET": these are just the friendly identifier strings for the +0100 and +0200 *offsets* within a zone, and they do not encode any rules about the time change.

> I'm just saying, that ActiveSupport should accept every entry from a standard ruby lib...
>
> Perhaps it's a Bug in MRI that it makes Berlin to CEST?

There is no "CEST" zone entry in any library because it's not a zone. There is an offset alias, which is (sometimes) shown on output depending on time of year.

> irb(main):010:0> Time.now.zone
> => "CEST"

That Ruby method name is very misleading, it should not be called `zone` since that string does not encode any rules. Maybe `offset_name` would make more sense. Standard ruby only uses the local TZ setting, and doesn't know anything about time zones: it just asks the system via [localtime][1], and that's the raw string it outputs for `%Z` based on the current time.

Beware of using these strings like a zone at different times of year:

```
tz = "CET"
Time.zone = tz
Time.zone.parse("2017-06-01 00:00:00 #{tz}")

# were you expecting 00:00 or 01:00?
#=> Thu, 01 Jun 2017 01:00:00 CEST +02:00
```

[1]: https://linux.die.net/man/3/localtime

**Comment by patrick-gleeson** [comment]
@avit your last comment in this thread is fantastically helpful and has cleared up a lot of my confusion today. Thank you.
