### ISSUE TITLE
Should test environment default to have eager_load as true?

### ISSUE THREAD

**Issue by shaokun** [rails/rails#28736]
### System configuration
**Rails version**:
Rails 5.0.2

**Ruby version**:
ruby 2.3.3p222

The current default config/environments/test.rb
````ruby
  # Do not eager load code on boot. This avoids loading your whole application
  # just for the purpose of running a single test. If you are using a tool that
  # preloads Rails for running tests, you may have to set it to true.
  config.eager_load = false
````

Even when I run the whole test with "rake test", it still doesn't load the whole application. And then after I release the "tested" version to production, I see that it crashes because of `uninitialized constant ... (NameError)`. It makes sense not to load the whole application when running a single test, but it's NOT when running the whole test.

**Comment by Bijendra** [comment]
@shaokun Can you please post your complete error stack from production environment and also the file where the error reference points to.

**Comment by pixeltrix** [comment]
@shaokun this is something that a developer can easily do with environment variable, e.g.

``` ruby
# config/environments/test.rb
config.eager_load = ENV.fetch('EAGER_LOAD', '0') == '1'
```

``` sh
$ EAGER_LOAD=1 bundle exec rake test
```

Thanks for the suggestion, but sorry I don't think it's worth adding it to Rails.

**Comment by kirillrdy** [comment]
I guess I'll try again explain what @shaokun was talking about since I've hit exactly same issue.
because in tests environment not all code is loaded, its possible to have a file lets say
`app/model/random_file.rb`
```ruby
class RandomFile
   SOME_CONSTANT_THAT_IS_NOT_DEFINED
end
```
in test environment, it will never load the file therefore it looks like app is tested, but in production environment it will try to load that file and crash when it reaches undefined constant.

I was hoping that there would be less differences between test and production environments.
So again to @shaokun's question, why is this not default behaviour for test environment ?

**Comment by cintamani** [comment]
I did stump upon the same issue described by @kirillrdy recently, due to our migration to use Zeitwerk loading in a Rails 6 application. So wondering if we can have an answer here

**Comment by ak15** [comment]
Nice thanks :)
