### ISSUE TITLE
accepts_nested_attributes_for cause has_many relation failed to save.

### ISSUE THREAD

**Issue by zw963** [rails/rails#28761]
### Steps to reproduce

```rb
# models/goods_item.rb
class GoodsItem < ApplicationRecord
   has_many :images
   accepts_nested_attributes_for :images
end
```

```rb
# models/image.rb
class Image < ApplicationRecord
  belongs_to :goods_item
end
```

Add a  ``create`` action to ``controllers/goods_items_controller.rb``
```rb
def create
  @goods_item = GoodsItem.new(goods_items_params)
  @goods_item.images.new(params[:image_keys].map {|key| {key: key} })

  if @goods_item.save  # <=accepts_nested_attributes_for cause failed to save.
     # do somethings
  else
     puts @goods_item.errors.messages  # => {:"images.goods_item"=>["must exist"]}
     puts @goods_item.errors.details        # => {:"images.goods_item"=>[{:error=>:blank}]}
  end
end
```
### System configuration
**Rails version**:

5.0.2

**Ruby version**:

2.3.3

**Comment by zw963** [comment]
if change 

```rb
@goods_item.images.new(params[:image_keys].map {|key| {key: key} })
```
to

```rb
@goods_item.images_attributes = params[:image_keys].map {|key| {key: key} }
```

Still not worked too.

Only change ``belongs_to :goods_item`` to ``belongs_to :goods_item, optional: true`` will work.

I don't understand ``new parent record + new child records`` save order, is this ``optional: true`` is
necessary? 

Thanks

**Comment by st0012** [comment]
According to the [document](http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html#module-ActiveRecord::NestedAttributes::ClassMethods-label-One-to-many), if you build your params correctly you won't need to build `images` that way. Just put `@goods_item = GoodsItem.new(goods_items_params)` and Rails will create images for you according to `images_attributes` in your params.

For example:
```ruby
params = {
  goods_item: {
    title: "Some item",
    images_attributes: [
      { title: "image1", url: "http://example.com/example.jpg" },
      { title: "image2", url: "http://example.com/example.jpg" },
    ]
  }
}
```

**Comment by zw963** [comment]
@st0012 ,  as i say, but 

```rb
@goods_item.images_attributes = params[:image_keys].map {|key| {key: key} }
```

not worked as well.

**Comment by zw963** [comment]
Just for more clear to explain my meaning:

1. if NOT add ``accepts_nested_attributes_for :images``,  use ``@goods_item.images.new(params[:image_keys].map {|key| {key: key} })`` always worked
whatever if or not add ``optional: true`` to ``belongs_to :goods_item``

2. if add ``accepts_nested_attributes_for :images``, we must add ``optional: true`` to ``belongs_to :goods_item``, to make either both usage to work.

Thanks

**Comment by maclover7** [comment]
Agree with @st0012, it seems like there's something weird going on with your `params`. This seems more like a bug in your app code than one in Rails, so I'd recommend using the mailing list or StackOverflow, where a wider community will be able to help you.

**Comment by ayushkamadji** [comment]
I'm experiencing same thing on 5.0.2. 
Reproduced from scratch:
1. Build new app and two models with (e.g. User) `has_one` and (e.g. Profile) `belongs_to` association
2. Add `accepts_nested_attributes_for` in User, passing the symbol `:profile`
3. Go to rails console and set `params = {user: {email: 'blabla', profile_attributes: {name: 'foobar'}}}`
4. `u = User.create(params[:user])` will fail and get rollbacked.
5. `u.errors.full_messages` will generate `["Profile user must exist."]`
6. `u.profile` will return a Profile object with `:user_id` attribute set to `nil`

My workaround was to use higher version rails (5.1.0 worked for me). 
Please confirm by others.

**Comment by zw963** [comment]
Cool, I have remove all use about `accpts_nested_attributes_for` in my project.

I add try this to my todo list, will try it if have time.

**Comment by JohnSmall** [comment]
This problem arises because Rails 5.x requires the parent record to exist if you declare a one to many association using `belongs_to` in the child model. 

But the operation that creates a record via `accepts_nested_attributes_for :x` tries to validate the child record before the parent has been written and gets an error because the parent_id hasn't been set.

The workaround is to add `optional: true` to your `belongs_to` declaration but the real problem is the order that create(permitted_params) is validating the created records. 

Oddly enough, I found that this was only a problem when had params with 2 levels of `accepts_nested_attributes`. Ie. If I have parent -> child -> grandchild, the problem is when validation on the grandchild happens, not on the child.

**Comment by stestaub** [comment]
@zw963 May a bit late but If you're still lokking for a fix, this problem can be solved by specifing the `inverse_of` attribute:

So your GoodItem

```ruby
# models/goods_item.rb
class GoodsItem < ApplicationRecord
   has_many :images, inverse_of: goods_item
   accepts_nested_attributes_for :images
end
```
Now when you create with new GoodsItem with the attributes as @st0012 suggested, your model will save as expceted.

This is because now Rails 'knows" that the belongs_to is actiually the parent you are currently creating and can therefore skip its validation.

**Comment by zw963** [comment]
> This is because now Rails 'knows" that the `belongs_to` is actually the parent you are currently creating and can therefore skip its validation.

Thanks.
