### ISSUE TITLE
doesn't throw exception when migration file and schema.rb have a typo

### ISSUE THREAD

**Issue by polyglot0027** [rails/rails#28963]
For example I have following string in my schema.rb:

`t.boolean :is_admin, null: false, defalut: false`

Where instead of `default` I wrote `defalut`, but there is no exception

**Comment by rafaelfranca** [comment]
How that end up in the schema.rb? Did you changed that file by hand or it was generated by a migration?

**Comment by polyglot0027** [comment]
Changed migration file by hand with`defalut` word and then run migration

**Comment by fishbullet** [comment]
I agree, it's common problem, make a typo in the generated migration. I think it's more about developer attention. To check what are you write in the migration.

**Comment by polyglot0027** [comment]
Yep absolutely agree, anyway suppose it can be useful remark

**Comment by EugZol** [comment]
+1

**Comment by rafaelfranca** [comment]
I see. Unfortunately we can't change the behavior. The options in the migration methods are open because some adapters may have options that other adapters don't have, and if we raise on non-registered options for one adapter the other adapters will have to monkey patch Rails to be able to register new options. We had some similar reports (which I can't find anymore) and we decided to not fix exactly because of this reason.

**Comment by polyglot0027** [comment]
OK thanks for attention!
