### ISSUE TITLE
ActiveSupport::TimeZone[] works incorrectly with DST

### ISSUE THREAD

**Issue by jusmat** [rails/rails#28982]
### Steps to reproduce
```
Time.zone = ActiveSupport::TimeZone[0]
```
=> #<ActiveSupport::TimeZone:0x00000008519c00 @name="Casablanca", @tzinfo=#<TZInfo::TimezoneProxy: Africa/Casablanca>, @utc_offset=nil>

```
Time.current.utc_offset
```
=> 3600

Following the online tools, the Cassablanca's time is currently ahead of UTC by 1 hour, and that explains why the offset is 3600, however, why `ActiveSupport::TimeZone[0]` gives me Cassablanca?

### Expected behavior
I think it could just set the time to UTC (that works right if I do it manually), or return any timezone with no offset (like https://www.timeanddate.com/worldclock/mali/bamako)

### Actual behavior
It sets the time zone to Casablanca's, which ends up with 3600s offset right now.

### System configuration
**Rails version**:
4.2.8
**Ruby version**:
2.3.3

**Comment by giovannibenussi** [comment]
Maybe this issue is related with daylight savings.
I'm pretty sure that when we're trying to get _utc_offset_, it executes [this line](https://github.com/rails/rails/blob/f626b47d56061fc414791217c7904a51df2de226/activesupport/lib/active_support/values/time_zone.rb#L285).

According to [TimezonePeriod](http://www.rubydoc.info/gems/tzinfo/TZInfo/TimezonePeriod):

- [TimezonePeriod#utc_offset](http://www.rubydoc.info/gems/tzinfo/TZInfo/TimezonePeriod#utc_offset-instance_method): Base offset of the timezone from UTC (seconds).
- [TimezonePeriod#std_offset](http://www.rubydoc.info/gems/tzinfo/TZInfo/TimezonePeriod#std_offset-instance_method): Offset from the local time where daylight savings is in effect (seconds). E.g.: utc_offset could be -5 hours. Normally, std_offset would be 0. During daylight savings, std_offset would typically become +1 hours.
- [TimezonePeriod#utc_total_offset](http://www.rubydoc.info/gems/tzinfo/TZInfo/TimezonePeriod#utc_total_offset-instance_method): Total offset from UTC (seconds). Equal to utc_offset + std_offset.

So Maybe, we should change [this line](https://github.com/rails/rails/blob/f626b47d56061fc414791217c7904a51df2de226/activesupport/lib/active_support/values/time_zone.rb#L249):

`all.find { |z| z.utc_offset == arg.to_i }`

To this one:

`all.find { |z| z.utc_total_offset == arg.to_i }`

**Comment by jeremy** [comment]
This is documented as finding the first matching time zone with that specific UTC offset, though, not the current total UTC offset. It's intentional.

Could you share more about why you're looking up time zones by UTC offset?

**Comment by jusmat** [comment]
@jeremy, I need to display the time model changed in visitors time zone. To achieve this I tried to calculate UTC offset using js ( https://www.w3schools.com/jsref/jsref_gettimezoneoffset.asp ) and then pass it to rails to handle the `updated_at`  time correctly.

**Comment by giovannibenussi** [comment]
@jusmat Why not save the `updated_at` value as UTC and then just display it in the user view with the offset applied?.

**Comment by jusmat** [comment]
It was a very simplified example of what I need. Basically there are a lot of dates which has to be converted into user's current_time. One for api, others for mailers, views. Also not all the dates might be in the UTC. So the solution was to set Time.zone inside of that current job (which does all of this) to skip all the hasle, It is of course could be done in other ways, I just surprised why it behaves like that. As long as it is intentional, I'll find another way of doing this :)
