### ISSUE TITLE
Migrations: Why is the default reference type hardcoded?

### ISSUE THREAD

**Issue by glebm** [rails/rails#29039]
Why is the default reference type hardcoded to bigint?
Seems like it should fetch the type of the column it is referring to and use that by default.

**Comment by matthewd** [comment]
Migrations need to have repeatable, order-independent, effects. Given a migration A that established a reference from X to Y [with automatic type inference], and a migration B that changed the type of Y.id, running A+B would give a different schema from B+A.

**Comment by doublemarket** [comment]
@matthewd I agree with the idea but a referenced column type (a definition of the key in a referenced table) can change (e.g. by adding `id:integer` or `unsigned: true` on MySQL) while a reference type cannot change. I think this is inconsistent. Therefore, a migration that creates a table which has a foreign key fails when a referenced column type is customized. Either of the followings can be the right way:

1. A referenced column type is also fixed as bigint because the reference type is hardcorded as bigint.
2. A reference type automatically becomes the same type of the referenced column (by fetching the type of the column referred to, like @glebm said)

**Comment by guilleiguaran** [comment]
I think we have found another case where the hardcoded default is causing a problem:

We upgraded to 5.1 recently, that means that our new migrations are 5.1 migrations and that the new default for references is `bigint`, while our old migrations and tables have `integer` keys.

Creating and running new migrations with references as we used to did in previous Rails versions:

```
% rails g model Bookmark user:references name
% rails db:migrate
```
is giving us a cryptic MySQL error message: `relation “bookmark” doesn’t exist`

To fix the problem we should edit the migration manually and set the `type` to `:integer`:

```
t.references :user, foreign_key: true, type: :integer
```

But in my opinion this isn't an ideal solution, wdyt??.

**Comment by guilleiguaran** [comment]
Maybe we can have a config for generators similar to `primary_key_type`?

```
config.generators do |g|
  g.orm :active_record, primary_key_type: :integer, reference_type: :integer
end
```

**Comment by matthewd** [comment]
@guilleiguaran that's a bug; you're supposed to get a [very specific error](https://github.com/rails/rails/pull/26266/files#diff-8058271a6540a6cf9846a95d3c6943abR126).
