### ISSUE TITLE
form_with - rails_ujs error on submit 

### ISSUE THREAD

**Issue by aandy28** [rails/rails#29046]
Standard form_with tag being handled via js without setting local true when hitting submit and not filling in form data I get an error in the js console of Cannot read property 'call' of undefined. 

This error leads to line 34 of rails/actionview/app/assets/javascripts/rails-ujs/utils/event.coffee

It responds to my error and displays the errors on the front end once i set up the respond to but there is still an error in the base code as handler is not being set.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by aandy28** [comment]
Unfortunately I can't as it is production code for work, however, this is the error in the js console after trying to submit a form, It throws this error whenever the submit button is hit:

Uncaught TypeError: Cannot read property 'call' of undefined
    at HTMLDocument.<anonymous> (rails-ujs.self-4174166….js?body=1:146)

this is the line inside the Rails.delegate function that is breaking.

if (target instanceof Element && handler.call(target, e) === false) {
  e.preventDefault();
  return e.stopPropagation();
}

**Comment by robin850** [comment]
Could you please create a brand new Rails application that reproduces the issue ? Otherwise, it's nearly impossible for us to solve your problem.

Also, did you take into consideration that UJS event handlers take the event as the first parameter ? For example:

~~~javascript
form.addEventListener('ajax:error', function(event, xhr, status, err) {
  // ...
});
~~~

**Comment by askehansen** [comment]
It seems that extra params are not passed to the event handler as described here https://github.com/rails/jquery-ujs/wiki/ajax#important

The following breaks when i use rails-ujs instead of jquery-ujs
```javascript
$("form").on("ajax:success", function(event, data, status, xhr) {
  console.log(data.someData)
}
```

Both `data`, `status` & `xhr` are undefined.
However i can find the params as an array in `event.detail`

**Comment by inopinatus** [comment]
I have a post about some of these undocumented surprises for rails-ujs users over at https://inopinatus.org/2017/05/05/undocumented-ujs-changes-when-upgrading-to-rails-5.1/

**Comment by robin850** [comment]
Hum, thanks for the insight @inopinatus but rails-ujs should be (mostly) backward compatible with jquery-ujs I guess. /cc @javan

**Comment by inopinatus** [comment]
@robin850 I thought you can still install jquery-rails and get real jquery-ujs with 5.1 apps if desired, I haven't checked this in practice but if so, goes a long way towards not needing to worry about a breaking change.

**Comment by robin850** [comment]
@inopinatus : Sure but even though it's intentional, we should document these changes as the [JavaScript guide](http://guides.rubyonrails.org/working_with_javascript_in_rails.html#dealing-with-ajax-events) isn't up-to-date at this level.

**Comment by inopinatus** [comment]
@robin850 strongly concur
