### ISSUE TITLE
local_cache + cleanup = ArgumentError

### ISSUE THREAD

**Issue by grosser** [rails/rails#29067]
on 5.1.0

```
/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache.rb:47 in clear
/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache.rb:90 in cleanup
/gems/dalli-2.7.6/lib/active_support/cache/dalli_store.rb:310 in write_entry
/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache.rb:119 in write_entry
```

local_cache calls clear with options ... which is clearly (ha!) not supported ... ok to just remove options ... or am I missing something ?

**Comment by grosser** [comment]
Monkey patch:

```Ruby
# https://github.com/rails/rails/issues/29067
# can be removed if this works:
# Rails.cache.with_local_cache { Rails.cache.write('xxx', true, unless_exist: true)  }
ActiveSupport::Cache::Strategy::LocalCache::LocalStore.prepend(Module.new do
  def clear(*)
    super()
  end
end)
```

**Comment by maclover7** [comment]
Almost positive this was caused by #25628, should be reverted?

cc @rafaelfranca

**Comment by grosser** [comment]
first we need a failing test ... then I'd rather avoid sending an argument in that will not be used ... should be simpler/cheaper ...

**Comment by eugeneius** [comment]
I've opened https://github.com/rails/rails/pull/29081 with a fix and a regression test.

I went with no longer passing `options` since it's the simplest solution, but personally I agree with @maclover7's position - I don't think we gained much by removing the argument, and the API is now less consistent.

Even if we don't want to bring it back, there are a few other problems:

1. The argument was (and still is) [publicly documented](https://github.com/rails/rails/blob/v5.1.1/activesupport/lib/active_support/cache.rb#L466). It probably should have had a deprecation cycle before it was removed.
2. @rafaelfranca [said](https://github.com/rails/rails/pull/25628#issuecomment-240320072) that backends which need the argument can define it, but that won't work with the local cache strategy since [it overrides the method and forces it to be 0-arity](https://github.com/rails/rails/blob/v5.1.1/activesupport/lib/active_support/cache/strategy/local_cache.rb#L82).  
3. The [MemCacheStore](https://github.com/rails/rails/blob/v5.1.1/activesupport/lib/active_support/cache/mem_cache_store.rb#L137) and [MemoryStore](https://github.com/rails/rails/blob/v5.1.1/activesupport/lib/active_support/cache/memory_store.rb#L32) backends still declare the argument, even though they don't use it.
