### ISSUE TITLE
Special characters in app directory path causes 'rails server' to fail on Windows systems

### ISSUE THREAD

**Issue by leifericf** [rails/rails#29087]
### Steps to reproduce

1. On Windows 10 system, create directory: `C:\Rails Server Test Ø`
2. Open command prompt, then navigate to `C:\Rails Server Test Ø`
3. From within `C:\Rails Server Test Ø`, run `rails new MyTestApp`
5. From within `C:\Rails Server Test Ø\MyTestApp`, run `rails server`
6. Notice error message: _C:/Rails Server Test ?/MyTestApp/Gemfile not found_
7. Rename directory `C:\Rails Server Test Ø` to `C:\Rails Server Test` (removing `Ø`)
8. Repeat step 4; notice `rails server` now works as expected

### Expected behavior
Rails server starts under localhost.

### Actual behavior
Rails server does not start and misleading error message occurs:
_C:/Rails Server Test ?/MyTestApp/Gemfile not found_

Error message is misleading, because `Gemfile` actually does exist within the working directory.

### System configuration
**Operating system**:
Windows 10 Enterprise (64-bit)

**Rails version**:
Rails 5.1.1

**Ruby version**:
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

**Comment by ISimion** [comment]
It is 2021, and this issue still persists, I am having the same issue using `Rails 6.1.4.1` on Windows 10. I think it should be opened again since it wasn't solved. I have already opened a [question](https://stackoverflow.com/questions/70224415/trying-to-start-a-server-on-my-newly-rails-application-on-a-path-with-diacritics?noredirect=1#comment124138879_70224415) about it on StackOverflow, and from this [answer](https://stackoverflow.com/a/32456278/7698694), it seems that I am not the only one experiencing it.

**Comment by jonathanhefner** [comment]
Hi,  @ISimion! :wave:  I am re-opening this issue.  Though, unfortunately, that is no guarantee it will be fixed.  One of the biggest hurdles to fixing a bug is reproducing it.  Many Rails contributors (myself included) do not have easy access to a Windows machine, so if a bug is Windows-specific, we can't track down the root cause.  If you or other Windows users can track down the root cause for this issue (and perhaps submit a PR! :smile:), we would welcome your help.

**Comment by fxn** [comment]
Reopened. I have Windows in Parallels Desktop. Let me play with it.

**Comment by fxn** [comment]
I have been able to reproduce, can't even execute `rails runner`:

```
PS C:\Users\fxn\tmp\Rails Server Test Ø\MyTestApp> rails runner 1
Traceback (most recent call last):
        1: from bin/rails:3:in `<main>'
bin/rails:3:in `require_relative': cannot load such file -- C:/Users/fxn/tmp/Rails Server Test ?/MyTestApp/config/boot (LoadError)
```

**Comment by mohits** [comment]
hi! This does not specifically seems to be a Rails issue. It's a Windows issue. I will open a ticket also on the RubyInstaller site to see if there is further help there.

In the same folder `Rails Server Test Ø` if you have a file `1.rb` with this:
```ruby
# encoding: UTF-8
require_relative "2.rb"

puts 'success'
```
and the file `2.rb` exists, you still get:

```
$ ruby 1.rb
1.rb:2:in `require_relative': cannot load such file -- D:/projects/blog/_posts-trials/rails/Rails Server Test ?/2.rb (LoadError)
        from 1.rb:2:in `<main>'
```

It's almost certainly to do with how Ruby is handling encoding on the system.
