### ISSUE TITLE
UndefinedTable error after interrupted pg:pull won't allow db:drop

### ISSUE THREAD

**Issue by atstockland** [rails/rails#29082]
### Steps to reproduce
I was pulling my production database using pg:pull and the process got interrupted.  Now, my dev database is incomplete.

### Expected behavior
Seems like I should be able to just db:drop the dev database and start over.  However I get the following error:  ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "xxxxx" does not exist.

### Actual behavior
ActiveRecord wont drop the dev database because a table does not exist.  Why does :drop care if a table is missing?  Furthermore...bin/rails db:drop DISABLE_DATABASE_ENVIRONMENT_CHECK=1 has no affect.

### System configuration
**Rails version**:
5.0.2

**Ruby version**:
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by atstockland** [comment]
I would consider this an issue.  This is an unwanted behavior seemingly introduced in Rails 5.  Ill move to SO.

**Comment by matthewd** [comment]
Sorry, I interpreted it as a support request because there isn't enough information for us to act on to make a change.

`pg:pull` isn't part of Rails; "this happened to me once" isn't really a practical interpretation of "steps to reproduce"; and the error has neither a backtrace, nor any indication of what the redacted table name suggests (is it a table corresponding to a model? is it one of our metadata tables?).

I can only guess about all of that, but having done so, my best available conclusion is that it's an application issue.

**Comment by atstockland** [comment]
Sorry for my incomplete question.  I should have offered more details.  It turned out to be an application issue...I was able to work through it.  However, it still begs the question why rails is doing so many checks (table structure, associations intact, etc) on db:drop...seems like rails should be able to drop the database under any conditions...or, have an option for --force.  The end result is the same...a dropped database, so who cares what it looks like before/during drop.  I had to jump through a few hoops to get the database dropped only because AR had a expectations as to what the database should look like.  I'm sure there is good reason for it, but it would have saved me hours if drop would have simply dropped it.  Sorry to clog up issues with what turned out to not be an issue.
