### ISSUE TITLE
When migrating down, enable_extension will delete every column from every table that use the extension

### ISSUE THREAD

**Issue by ClaudioFloreani** [rails/rails#29091]
When independent migrations apply the same extension,

e.g.:

```ruby
class CreateItems < ActiveRecord::Migration
  def change
    enable_extension 'citext'
    create_table :items do |t|
      …
      t.citext      :code
      …
    end
    …
  end
end

class CreateMembers < ActiveRecord::Migration
  def change
    enable_extension 'citext'
    create_table :members do |t|
      …
      t.citext      :email
      …
    end
    …
  end
end

```

migrating down one of these (e.g. Items) results in the extension being deleted even if other table still needs it, and _every column using the extension is being deleted from every table_.

I.e., after taking down “items” table — `rake db:migrate:down VERSION=xxxx # Create Items`,

```diff
diff --git a/db/structure.sql b/db/structure.sql
index 559dfab..b92fa7e 100644
--- a/db/structure.sql
+++ b/db/structure.sql
@@ -23,20 +23,6 @@ CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
 COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
 
 
---
--- Name: citext; Type: EXTENSION; Schema: -; Owner: -
---
-
-CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
-
-
…
@@ -103,7 +40,6 @@ CREATE TABLE members (
     …
-    email citext NOT NULL,
     …
```

citext is deleted at a whole, and email column in “members” table is deleted as well.

Worst of all, if “items” is brought up again — `rake db:migrate:up VERSION=xxxx # Create Items`, the extension is re-introduced but the columns from other table are not.

It makes sense that the extension is declared by every migration that needs it, there are some scenarios where you may want to be able to take down or redo some migration without affecting others. But deleting every column using the same extension from every other table without even a warning is a dangerous side effect.

Some checks should be done to make sure the extension is not needed elsewhere before deleting it.

**Comment by ClaudioFloreani** [comment]
A simple workaround is to always put `enable_extension` in a reversible block without down:

```ruby
  def change
    reversible do |migrate|
      migrate.up do
        enable_extension 'citext'
      end
    end
    …
  end
```

This of course has the lesser side effect to leave the extension enabled even when it's still not needed anywhere.

**Comment by matthewd** [comment]
The first solution that comes to mind would be to make `enable_extension` raise if the extension's already present.

While I'd argue that's more correct (migrations shouldn't [successfully] complete differently depending on the prior state of the database), I'm not so sure it'd be a widely popular change.

OTOH, maybe it's as simple as [switching from CASCADE to RESTRICT](https://github.com/rails/rails/blob/7cc526beb5c1ecc509db9f607c26fabaed4b4027/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L332). That's not quite as magical as the behaviour you described -- it'd just raise instead of dropping the extra stuff -- but is at least predictable and safe.
