### ISSUE TITLE
Fake DEPRECATION WARNING: Using positional arguments in integration tests has been deprecated, in favor of keyword arguments, and will be removed in Rails 5.1.

### ISSUE THREAD

**Issue by starrychloe** [rails/rails#29100]
### Steps to reproduce
http://stackoverflow.com/questions/43992479/deprecation-warning-for-rails-5-unit-tests

    post(user_session_path, session: { email: user.email, password: password, remember_me: remember_me })

### Expected behavior
No warnings. It should work. The method signature matches the docs. http://api.rubyonrails.org/classes/ActionController/TestCase/Behavior.html#method-i-get

### Actual behavior
Get lots of deprecation warnings. 

```
DEPRECATION WARNING: Using positional arguments in integration tests has been deprecated,
in favor of keyword arguments, and will be removed in Rails 5.1.

Deprecated style:
get "/profile", { id: 1 }, { "X-Extra-Header" => "123" }

New keyword style:
get "/profile", params: { id: 1 }, headers: { "X-Extra-Header" => "123" }
 (called from log_in_as at C:/Users/Chloe/workspace/fortuneempire/test/test_helper.rb:16)
```

### System configuration
**Rails version**: 5.0.2

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

**Comment by matthewd** [comment]
The signature you linked is for a controller test.

The integration test method is http://api.rubyonrails.org/v5.0/classes/ActionDispatch/Integration/RequestHelpers.html#method-i-post, which calls http://api.rubyonrails.org/v5.0/classes/ActionDispatch/Integration/Session.html#method-i-process.

It's very similar, but with one notable omission: integration tests don't support setting the session directly.

Given that you're using a `user_session_path` (and the contents of the hash), however, I imagine that line isn't attempting to set the *session*, but rather pass a parameter that happens to be named `session`:

```ruby
post(user_session_path, params: { session: { .. } })
```

(on the bright side, this would've been far more confusing if you had been writing a controller test, because it would've incorrectly interpreted the call as being in the new style)
