### ISSUE TITLE
ActiveRecord does not automatically reset bad PostgreSQL connections

### ISSUE THREAD

**Issue by ejholmes** [rails/rails#29189]
We recently started noticing that when Postgres/PGBouncer dies or otherwise gets restarted, queries on ActiveRecord connections will fail indefinitely until the rails app is restarted.

Presumably, this is because [ActiveRecord::ConnectionAdapters::ConnectionPool#connection](https://github.com/rails/rails/blob/v5.0.1/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L363-L365) never calls `verify!` on a connection once a thread has a cached connection.

### Steps to reproduce

1. Execute a query
2. Restart postgres
3. Execute a query again

https://gist.github.com/ejholmes/d0cbd3e2b3f419d4e2330aca6869f808

<details>
<summary>Console output from `ruby test.rb`</summary>

```console
# Running:

D, [2017-05-22T17:40:36.081846 #34104] DEBUG -- :    (0.1ms)  SELECT 1
Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
FATAL:  terminating connection due to unexpected postmaster exit
D, [2017-05-22T17:40:52.343025 #34104] DEBUG -- :    (0.6ms)  SELECT 1
PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
: SELECT 1
F

Finished in 16.281555s, 0.0614 runs/s, 0.1228 assertions/s.

  1) Failure:
Test#test_connection_reset [test.rb:61]:
Expected: :ok
  Actual: :bad

1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```
</details>

### Expected behavior

The underlying connection should reset, and queries should not fail.

### Actual behavior

Queries after the postgres restart fail with: `PG::ConnectionBad: PQsocket() can't get socket descriptor: SELECT 1`.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3 (but should be able to repro with any Ruby version)

**Comment by matthewd** [comment]
The behaviour shown in your gist is expected: it's unsafe to reconnect in the middle of a request, because the connection may have state we can't reproduce.

But when handling requests, the next request will fetch a new connection, which will be verified during checkout. Can you give more detail about what's happening when the error gets "stuck" in your real application?

I modified the gist to show closer to the multi-request flow: note the connection remains bad within the `with_connection` block, but after it goes back through the pool, it's verified and fixed.

https://gist.github.com/matthewd/e5a847a76576a98691f56607cf62ab0d

**Comment by ejholmes** [comment]
Thanks @matthewd, that may very well be our problem. Any pointers on where this would be getting called within the rails code base? I'm assuming there would be some rack middleware, but `git grep '\.with_connection` and `git grep '\.checkout'` don't reveal much.

**Comment by matthewd** [comment]
https://github.com/rails/rails/blob/v5.0.1/activerecord/lib/active_record/query_cache.rb#L43

(It's in a weird place at the moment, because I'm an awful person.)

I used `with_connection` in the example because it gave a better "encapsulated" feel; as you can see, in practice, we actually just do a `release_connection`.

BTW, while I don't recall anything relevant in 5.0.1..5.0.3, I'd definitely recommend you start with that.

**Comment by ejholmes** [comment]
Ok, so ActiveRecord::QueryCache now gets hooked into ActionDispatch::Executor in rails 5 (for anyone that's wondering where their ActiveRecord::QueryCache middleware went).

Thanks for the helpful info @matthewd! I think I have a much better idea of where the underlying issue is. I'll close this for now since I don't believe it's a Rails/AR related issue.

**Comment by MaicolBen** [comment]
It happens to me inside the console, not in web requests. @ejholmes What did you do to solve the issue?

**Comment by mbruszewski** [comment]
> It happens to me inside the console (similar error: `PQconsumeInput() server closed the connection unexpectedly`), not in web requests. @ejholmes What did you do to solve the issue?
Any news @MaicolBen ? I think I got similar issue as yours. Started a new thread here:
https://stackoverflow.com/questions/55240150/rails-pgbouncer-client-idle-timeout

**Comment by MaicolBen** [comment]
I will answer in your stackoverflow post, I had a similar issue than you but without knowing it.
