### ISSUE TITLE
Migration | PG::UndefinedTable: ERROR: relation create_roles does not exists | Rails 5, Ruby 2.4 

### ISSUE THREAD

**Issue by kaleemullah360** [rails/rails#29206]
### Steps to reproduce
in Rails migration file remove the following line **`::Migration[5.0]`**

```
class CreateRoles < ActiveRecord::Migration[5.0] # <-- remove this '::Migration[5.0]'
  def change
    create_table :roles do |t|
      t.string :name
      t.integer :code, limit: 2
      t.boolean :is_active, default: true

      t.timestamps
    end
  end
end
```

### Expected behavior
Should throw syntax error or something more clear

### Actual behavior
> PG::UndefinedTable: ERROR: relation create_roles does not exists

### System configuration
**Rails version**:
Rails 5.0.3
**Ruby version**:
ruby-2.4.0

**Comment by matthewd** [comment]
`class CreateRoles < ActiveRecord` absolutely does give an error: "TypeError: superclass must be a Class (Module given)"

`class CreateRoles < ActiveRecord::Base`, on the other hand, will likely behave as you describe... there's not much we can do about that, because it's a perfectly valid class definition. At some point, if you try hard enough to make thing A look like thing B, we're going to just start treating it as the latter.
