### ISSUE TITLE
undefined method `cwyear' for Time when using DateTime#utc

### ISSUE THREAD

**Issue by heaven** [rails/rails#29218]
The problem is that `DateTime#utc` now returns `Time` instead of `DateTime`:
```
def utc
  utc = new_offset(0)

  Time.utc(
    utc.year, utc.month, utc.day,
    utc.hour, utc.min, utc.sec + utc.sec_fraction
  )
end
```

Tried to upgrade from `4.2.7.1` to `4.2.8`. We do use DateTime's `#cweek` and `#cwyear` a lot and now this is broken.

Should we do `DateTime.now.utc.to_datetime.cweek`? This doesn't look good.

**Comment by pixeltrix** [comment]
@heaven I'd never originally intended for the change to take place in a stable release but it inadvertently got backported with the rest of the changes for Ruby 2.4's changes to `to_time`. It has however been fixed on [4-2-stable] where I've restored the behaviour of returning a `DateTime` instance. Not that the `getutc` and `getlocal` will still return `Time` in Rails 5.0 and later. The reasoning behind this is that `DateTime` doesn't have timezone support - it just understands offsets.

[4-2-stable]: https://github.com/rails/rails/commit/fccc031cb61d98b3fc401d8a323e71da222362ca

**Comment by pixeltrix** [comment]
In terms of working around it now, does not `Date.today.cwyear` not work? I assume that you're using `utc` because your system timezone is not set to UTC?

**Comment by heaven** [comment]
@pixeltrix, thanks for the reply. Correct, the timezone is different and we have a quite big cluster and can't rely on system's timezone, so `DateTime#utc` is mandatory in our case.

It's weird that `#utc`, `#getutc`,  `#getlocal` or any other method will return something other than `DateTime` unless `#to_time` was called explicitly. I am pretty sure this implicit conversion is wrong. I agree it wasn't good when `DateTime#getutc` might return either `Time` or `DateTime`, but now this is always wrong.

**Comment by pixeltrix** [comment]
@heaven if you're asking for a UTC time then that's what you should get. UTC time doesn't have the concept of calendar reform but the Ruby `DateTime` does, e.g:

```
# Battle of Hastings was fought on Saturday, 14th October 1066
>> DateTime.new(1066, 10, 14).strftime('%A')
=> "Saturday"
>> Time.utc(1066, 10, 14).strftime('%A')
=> "Sunday"
```

This is because `Time` implements a proleptic gregorian calendar whereas `DateTime` adjusts for calendar reform leading to the difference between them. I'd advise using `Time` wherever possible over `DateTime` for this reason. There's no `cwyear` or `cweek` on `Time` but you can do `strftime('%G').to_i` for `cwyear` and `strftime('%V').to_i` for `cweek` (you can drop the `to_i` if you're not using them in further calculations).

**Comment by heaven** [comment]
I believe that's exactly why we did use `cweek` and `cwyear`, thank you for the explanation, though. I don't see how's `strftime('%G').to_i` better than `cwyear` and to be fair I don't see how is this all relevant to the problem with the implicit type conversion that I described above.

**Comment by pixeltrix** [comment]
@heaven I don't regard it as implicit - the method is called `utc` or `getutc` after all. Previously it was returning a `DateTime` instance with an offset of `0` - this is not UTC so was incorrect in my mind.

**Comment by heaven** [comment]
@pixeltrix `Time#utc.to_datetime` returns exactly `DateTime` with an offset of 0.

But my concern is that I am calling `DateTime#getutc` and receive an instance of `Time`, which looks pretty much implicit. And in addition to that `DateTime.current.getutc.to_datetime` looks strange. And the fact that `#utc` will return `DateTime` but `#getutc` (which is an alias currently) will return `Time` looks even more strange. And the use case with `cweek` and `cwyear` is just an example, there are many other things where `DateTime` and `Time` behave differently.

**Comment by pixeltrix** [comment]
> there are many other things where DateTime and Time behave differently.

That is my point - encoded in the method name is UTC, which is a continuous timeline, whereas `DateTime` doesn't. It jumps at the date of calendar reform (which is different for different countries - Fri, 15 Oct 1582 for catholic countries and Thu, 14 Sep 1752 for the UK). e.g:

```
>> Date.civil(1752, 9, 14, Date::ENGLAND) - 1.week
=> Thu, 27 Aug 1752
>> Date.civil(1582, 10, 15, Date::ITALY) - 1.week
=> Fri, 28 Sep 1582
```

See how the dates go back more than 1 week? This is because the calendar was out of sync with the seasons so [Pope Gregory introduced calendar reform][1] to bring them back into sync. UTC is used for synchronising systems - you don't want days disappearing so it implements a [proleptic gregorian calendar] so that it's continuous. This is the best system to use for most apps since they're generally interested in continuous time periods. However if you're explicitly modelling historical dates which [is a nightmare given the different dates of calendar reform][3] then by all means use `DateTime`.

[1]: https://en.wikipedia.org/wiki/Gregorian_calendar#Gregorian_reform
[2]: https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar
[3]: https://en.wikipedia.org/wiki/Gregorian_calendar#Proleptic_Gregorian_calendar
