### ISSUE TITLE
Rails 5 render json got stack level too deep because of the action name

### ISSUE THREAD

**Issue by dfang** [rails/rails#29217]
### Steps to reproduce

for demonstration, i simplied the code...

```
class WxpayController < ApplicationController
  def config
    respond_to do |format|
      format.json { render json: { 'status': 'OK'}}
    end
  end
end
```

in any page do a ajax request
```
<script type="text/javascript">
  $(function(){
    url = location.href.split('#')[0]
    $.ajax({
      url:        "/wxpay/config.json?url=" + escape(url),
      global:     false
    })
    .done(function(data){
      console.log(data)
    })
  })
</script>
```

 config/initializers/trace.rb
```
$enable_tracing = false
$trace_out = File.open(Rails.root + 'trace.txt', 'w')

set_trace_func proc { |event, file, line, id, binding, classname|
  if $enable_tracing && event == 'call'
    $trace_out.puts "#{file}:#{line} #{classname}##{id}"
    raise "crash me" if caller_locations.length > 500
  end
}

$enable_tracing = true

```

### Expected behavior
should output {status: "OK"} in chrome console log

### Actual behavior
without trace.txt, SystemStackError  Stack level too deep
with trace.txt, i got this `app/controllers/wxpay_controller.rb:3:in config' ` repeated ...

### System configuration
**Rails version**:
TRIED rails 5.1.1 with ruby 2.3.0, ruby 2.3.3, ruby 2.4.0, but Ok in rails 4.2.5

### Conclusion
In the end, i realized maybe i should not name the action config, so i changed it to config2, the SystemStackError gone.

**Comment by alexcameron89** [comment]
Hey @dfang, can you provide us with a sample application that reproduces the error?

**Comment by michaeltaras** [comment]
I took a quick look at this.  Making an action named "config" seems to conflict with the ActiveSupport::Configurable code in ActionController.  When processing the request, the rendering code ends up invoking [this code here](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/controller_helper.rb#L16) which will call a config method on your controller if it exists.  Because the config method has been overwritten, it will call your config method which will render again, and spins into an infinite loop.

So I guess it's not a bug, but it is a bit of a poor experience if you're not aware of the config internals.

Here's a simple test case if it helps:

`begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  secrets.secret_token    = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#config"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def config
    render plain: "explode"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
`

**Comment by dfang** [comment]
@michaeltaras  i don't say it a bug ~_~,  my bad .
