### ISSUE TITLE
How to show an invalid date format message?

### ISSUE THREAD

**Issue by itay-grudev** [rails/rails#29272]
### Steps to reproduce

All I am really looking for is showing an invalid date format message from the model... Somehow.

```ruby
ActiveRecord::Schema.define(version: 20170529162250) do
  create_table "group_events", force: :cascade do |t|
    t.date     "start_date"
    t.datetime "created_at",              null: false
    t.datetime "updated_at",              null: false
  end
end

class GroupEvent < ActiveRecord::Base
  validates :start_date, format: { with: /\A\d+-\d{2}-\d{2}\z/ }, allow_nil: true
end
```

### Expected behavior

```ruby
e = GroupEvent.new(start_date: '-13-0')
e.start_date # '-13-0'
e.valid? # false
e.errors.messages[:start_date] # [ 'is invalid' ]
```

### Actual behavior

```ruby
e = GroupEvent.new(start_date: '-13-0')
e.start_date # nil
e.valid? # true
e.errors.messages[:start_date] # nil
```

### System configuration
**Rails version**: `4.2.7.1`

**Ruby version**: `ruby 2.3.1p112`

**Comment by daniel-rikowski** [comment]
This happens because Rails tries to parse the string as a date, fails, and instead writes `nil`. The same would happen if you assign a string to an integer column, for example.

You have to validate the attribute _before_ it is cast. Fortunately Rails provides the original value in the `*_before_type_cast` accessors. ([Read the docs for details](http://api.rubyonrails.org/classes/ActiveRecord/Base.html#class-ActiveRecord::Base-label-Accessing+attributes+before+they+have+been+typecasted))

In your case you can replace the validation with this:

```ruby
validates :start_date_before_type_cast, 
    format: { with: /\A\d+-\d{2}-\d{2}\z/ }, allow_nil: true

# ...

e.errors.messages[:start_date_before_type_cast] # [ 'is invalid' ]
```

**Comment by itay-grudev** [comment]
Thanks a lot. I couldn't find any reference to this behaviour.
