### ISSUE TITLE
ActionCable::Connection::Base#disconnect not called if cable client lost network connection

### ISSUE THREAD

**Issue by dechaoqiu** [rails/rails#29307]
### Steps to reproduce

Start Rails server with action cable enabled, then have any client connect to the cable server, and make the client lose network connection (eg. airplane your phone with websocket client runing on your phone).

```module ApplicationCable
  class Connection < ActionCable::Connection::Base
     def disconnect
      puts 'disconnect'
     end
  end
```

### Expected behavior

`disconnect` should have been called in 3 seconds( heartbeat interval) or less than 1 minute.

### Actual behavior

On Mac OS X: `disconnect` not called until ~1 minute later.
On Linux server: `disconnect` not called until ~15 minute later.

diagnosis:
After client lost network connection, https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/connection/stream_event_loop.rb#L94 `@nio.select` does not return any monitor until 15 minute later on Linux (1 minute later on Mac OS X). Once it returns a monitor, and `io.read_nonblock(4096, exception: false)` will raise exception which triggers the `disconnect` callback. We expect `@nio.select` return monitors sooner, so that the server knows the client got disconnected.

a quick dummy fix: https://github.com/dechaoqiu/rails/commit/defe9cd02c3741fb93e4c339edbca11bf4dece71

### System configuration
**Rails version**:
5.1.1
**Ruby version**:
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]

**Comment by csexton** [comment]
This is consistent with the behavior I am seeing in a slightly older versions of Rails and Ruby:

**Rails version:**
5.0.0.1
**Ruby version:**
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by XenorPLxx** [comment]
https://github.com/rails/rails/issues/24908
Disconnect is reported when system reports it, and for TCP connections there's buffer which waits for overflow. For ubuntu it's about 100MB before TCP connection is considered disconnected.
For real disconnect solution we need new feature with application ping/keepalive at ActionCable level.

**Comment by apodolny** [comment]
Still seeing this.

**Comment by dechaoqiu** [comment]
Any fix for this yet?

**Comment by shadowyq** [comment]
Any fix for this yet?

**Comment by csenszike** [comment]
Any fix for this yet?

**Comment by diclophis** [comment]
I am seeing weird issues with disconnects running puma in development... basically if any of my javascript assets update and i dont full-restart puma, all new actioncable subscriptions fail initially then reconnect successfully

**Comment by mrjaimisra** [comment]
Any fix for this issue? We desperately need a way to detect client disconnects!

**Comment by rafaelfranca** [comment]
If you need this, please do investigate and open a PR. Nothing is better than needing something to motivate an implementation.

**Comment by YarikST** [comment]
Your solution worked for me as a side api. but as soon as I connected the js ActionCable then I whispered that every 3-4 seconds I was disconnected from the js side.

The _class ActionCable.ConnectionMonitor_ is waiting - 
`transmit type: ActionCable::INTERNAL [:message_types] [:ping], message: Time.now.to_i` - 
and if it does not, then js does unsubscribed. so I modified your code [=)](https://github.com/YarikST/rails)

**Comment by scriptfans** [comment]
Still seeing this.

**Comment by venarius** [comment]
Also having this problem

**Comment by fsinisi90** [comment]
Having this issue too...

**Comment by WalkPhoneGo** [comment]
Still seeing this.
Rails 5.2.2
ruby 2.5.3
CentOS 7

**Comment by h0jeZvgoxFepBQ2C** [comment]
Still seeing this.

Rails 5.2.2.1
Ruby 2.5.3
Ubuntu 16.04

This issue should be reopened at least @rafaelfranca , thank you

**Comment by feliperaul** [comment]
@rafaelfranca Can you please consider reopening this?

**Comment by WalkPhoneGo** [comment]
@rafaelfranca Can you please consider reopening this?

**Comment by radalin** [comment]
I'm not sure if this has a quick solution. The problem occurs because current server side implementation does not expect and does not get a response from the client side for it's pings. Each 3 seconds (or whatever the configuration is set), server side sends a "ping" message to the client side (ActionCable JS library), client side monitors the incoming ping messages and saves the date, at some intervals it checks if the pings arrived or not and if it exceeds an interval it tries to reconnect.

We don't have an equivalent of the client side's code in the server side because client never sends a "pong" request back to the serve where server should listen to them and have it's own connection monitor. In hindsight it seems simple to add this to the connection class as a "periodically" executed function. This will work as a quick and dirty solution but it's performance is not very good as there will be a different function for each connection (for each connection to server we have another instance of the ApplicationCable::Channel) and when that connection is closed that instance is gone and it's recreated. If you had values like connection id etc on the instance level, they are gone as well (which is another problem for reconnects) you have to find a way to persist them.

The solution we found to all of this was to implement our own monitoring solution on top of the ActionCable. We added a new action called "ping" to the channel. We wrapped the ActionCable subscription method and we are making periodical requests to that "ping" action. Ping action basically saves the last time to DB  (we use Redis though). We then execute a "cron" job that checks the DB for the oldest pings and then we update the status to disconnected.

**Comment by csenszike** [comment]
@radalin, can you share your solution as code snippet?
I still couldn't solve this issue - I couldn't figure out how to disconnect properly.
Thank you in advance!

**Comment by radalin** [comment]
I have created a gist for it: https://gist.github.com/radalin/8a250c85a8f9bd8c727a1cf72ea3b188

I have tried to keep to the relevant bits so excuse any errors. But basically:

- we are keeping a track of active chats
- Send a "ping" request from client side to update the "last_updated" duration of each connected user/client
- Check periodically for each active call for missing "pings" and inform the people in the room about the updates from other clients.

Hope that it helps

**Comment by csenszike** [comment]
Thank you very much!

**Comment by lobin-z0x50** [comment]
Hello everyone,

I’d like to share a solution for detecting disconnections early in ActionCable by using the kernel parameter `tcp_retries2`. This parameter controls the number of retries for unacknowledged TCP segments before the connection is considered broken. By default, it is set to 15, which corresponds to approximately 15 minutes. Reducing this value allows faster detection of disconnections.

For example, setting `tcp_retries2=7` reduces the timeout to approximately 51 seconds. You can configure this as follows:

- **System-wide configuration**: Add the following to `/etc/sysctl.conf`:
  ```
  net.ipv4.tcp_retries2 = 7
  ```
- **For Docker containers**: Add this to your `docker-compose.yml`:
  ```
    sysctls:
      - net.ipv4.tcp_retries2=7
  ```

**Important Notes**
1. **Reverse Proxies**: If you are using a reverse proxy like Nginx, the `tcp_retries2` parameter should be configured on the proxy server, as it manages the TCP connection between the client and the server.
2. **NAT and Proxy Limitations**: If the client is behind a NAT or proxy (e.g., a home WiFi router), this method only detects disconnections between the server and the proxy, not the client device itself. However, for most business use cases, this is sufficient as it accounts for internet connectivity issues.
3. **Alternative for Idle Connections**: In protocols or applications where long periods of inactivity are expected, TCPKeepAlive is a better option for detecting disconnections.

By adjusting `tcp_retries2`, ActionCable can reliably detect disconnections even when heartbeats fail to be sent. I hope this solution helps, and I’d be happy to hear feedback or additional insights from others!
