### ISSUE TITLE
REQ: preallocate memory with Ruby 2.4's String.new(capacity: INT)

### ISSUE THREAD

**Issue by aCandidMind** [rails/rails#29326]
As is also visible when reading the [String.new constructor](https://ruby-doc.org/core-2.4.0/String.html#method-c-new) the capacity parameter can be used to
> improve performance, when the string will be concatenated many times (and call many realloc)

Not sure whether the magical limit of 23 characters to avoid heap strings (see this [article](http://patshaughnessy.net/2012/1/4/never-create-ruby-strings-longer-than-23-characters)) also applies for strings created with a bigger initial capacity, but even if the gain is just for concatenation I guess there's still plenty of areas in rails where this can yield benefits. String columns with fixed limits and so on.

I hope that I wasn't just stating the obvious that is even already on its way or already planned in the heads of a lot of experienced Rails devs as a future thing to do. My part here for now is just to spark the idea.

This also seems to be somewhat related to #29236.

**Comment by rafaelfranca** [comment]
Rails still support Ruby < 2.4 and I don't see a way to do this without having to spread checks for ruby version checks in the codebase, because the syntax is not backward compatible:

```
>> String.new("", capacity: 1)
ArgumentError: unknown keyword: capacity
	from (irb):2:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /opt/rubies/2.3.3/bin/irb:11:in `<main>'
```

Also, this kind of optimization only have benefits in some areas so we don't plan to try this unless there benchmarks and profiling showing that this optimization is worth.
