### ISSUE TITLE
Since activerecord-4.2.8 scopes are being applied to unrelated queries

### ISSUE THREAD

**Issue by mkilling** [rails/rails#29338]
### Steps to reproduce

When you define a scope like this
```
class User
  belongs_to :team
  has_and_belongs_to_many :interests

  def self.a_scope
    # Unrelated query that will raise ActiveRecord::StatementInvalid:
    ids = Team.joins(:users).ids # PROBLEMATIC QUERY
    where(id: ids)
  end
end
```
And then execute it as part of a chained query like this:
```
class Team < ActiveRecord::Base
  has_many :users

  def users_with_interest
    users.joins(:interests).where(interests: { id: 123 }).a_scope
  end
end
```

an exception is raised: `ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: interests.id`

I wrote this script to illustrate the issue which was introduced by rails commit c55a5d6b16d18b028c3642caaf5815072630de40. https://gist.github.com/mkilling/6cd6f43b9e7ce974b0ecdcb09e36047e

### Expected behavior
I would except the *PROBLEMATIC QUERY* above to generate the following SQL statement: `SELECT "teams"."id" FROM "teams" INNER JOIN "users" ON "users"."team_id" = "teams"."id" AND "users"."team_id" = ?`

### Actual behavior
Since rails commit c55a5d6b16d18b028c3642caaf5815072630de40 the *PROBLEMATIC_QUERY* will generate the following sql: `SELECT "teams"."id" FROM "teams" INNER JOIN "users" ON "users"."team_id" = "teams"."id" AND "users"."team_id" = ? AND "interests"."id" = ?`

Note how the where-clause `"interests"."id" = ?` is applied to a query that should be unrelated. A `ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: interests.id: SELECT "teams"."id" FROM "teams" INNER JOIN "users" ON "users"."team_id" = "teams"."id" AND "users"."team_id" = ? AND "interests"."id" = ?` is raised because there is no FROM-clause for the interests table.

### System configuration
**Rails version**: 4.2.8

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by mikecmpbll** [comment]
I too am experiencing this and can confirm the bug is still present in master.

**Comment by mikecmpbll** [comment]
@k0kubun this change you submitted: https://github.com/rails/rails/pull/18109 causes this issue. i'm not terribly familiar with this bit of code, would you be able to give any clues as to why this bug occurs? maybe we need to remove something from the scope before merging it? 😕

**Comment by k0kubun** [comment]
It changes to see current_scope. You should try to see how it's affected and used in your code. I'd try defining a_scope using scope method instead of class method.

**Comment by mkilling** [comment]
@k0kubun just tried that (see this gist: https://gist.github.com/mkilling/38c80dce51c6af760985185c294a60f7), I'm getting the same error as in the original gist.

**Comment by mkilling** [comment]
I really feel that this is something that needs to be tackled. It broke code for us that was working in 4.2.7.1, and I feel we got somewhat lucky that an exception was raised.

From my understanding this could have caused unwanted WHERE clauses to be applied to our scopes silently, without any exception being raised and the scopes just returning incorrect results.

At the moment we‘re hesitant to upgrade Rails to anything higher than 4.2.7.1, because it would require us to verify that all our scopes still do the same thing as before the upgrade, which would be a huge effort.

Apart from that, this bug is a breaking change in a PATCH release which I think is not acceptable.

**Comment by sgrif** [comment]
There's definitely an issue here. However, I'm not sure what I'd like the fix to be. The fact that `unscoped` affects joins at all (and the fact that joins are affected by the default scope of a model) certainly implies that `Team.joins(:users)` should be affected by any current scope on the `User` model. That would mean that the issue here is not that the where clause is being added, but that the join clause to `interests` is not being added. 

I think it would be inconsistent for us to *only* consider `current_scope` if the current scope is there for unscoping purposes. That said, I don't think allowing all scope changes to affect joins was our intent in that PR, and it's a pretty major breaking change.

With all that said, I do think having `joins` be affected by `current_scope` is more consistent with our API, and it's been around for two releases now so it would be a breaking change to revert it on 5.x. I'm honestly not sure what I want to do there. I need to give it some more thought.

Either way, the change in behavior on 4.2 is unacceptable and needs to be addressed.

**Comment by sgrif** [comment]
Fixed in https://github.com/rails/rails/commit/5e7fc65e4c3d4ef6f3584362376fc5f9ccbf39ff
