### ISSUE TITLE
IpSpoofAttackError is raised when it's not needed

### ISSUE THREAD

**Issue by palexvs** [rails/rails#29387]
### Steps to reproduce
Make request with headers `Client-IP: private_ip` and 'X-Forwarded-For: public_ip'. There is an example:
```
curl 'localhost:3000/' -H 'Client-IP: 10.0.0.1' -H 'X-Forwarded-For: 148.167.2.30'
```

### Expected behavior
Rails should use Public IP

### Actual behavior
Rails raises `IpSpoofAttackError` exception

### System configuration
**Rails version**: 5.*
**Ruby version**: any

**Comment by palexvs** [comment]
I would try to fix it in such way: https://github.com/palexvs/rails/commit/183b738548b4a4d26661b2cb7baa5e35c9f318d5

**Comment by eugeneius** [comment]
The file you edited in your commit contains [this comment](https://github.com/rails/rails/blob/v5.1.1/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L118-L130):

```
        # +Client-Ip+ and +X-Forwarded-For+ should not, generally, both be set.
        # If they are both set, it means that either:
        #
        # 1) This request passed through two proxies with incompatible IP header
        #    conventions.
        # 2) The client passed one of +Client-Ip+ or +X-Forwarded-For+
        #    (whichever the proxy servers weren't using) themselves.
        #
        # Either way, there is no way for us to determine which header is the
        # right one after the fact. Since we have no idea, if we are concerned
        # about IP spoofing we need to give up and explode. (If you're not
        # concerned about IP spoofing you can turn the +ip_spoofing_check+
        # option off.)
```

The current behaviour is intentional; there's even [a test for it](https://github.com/rails/rails/blob/v5.1.1/railties/test/application/middleware/remote_ip_test.rb#L30-L35).

**Comment by palexvs** [comment]
@eugeneius I do not agree. These comment and test cover the situation when these headers have two different PUBLIC IPs. When I say that Rails should not raise `IpSpoofAttackError` exception because of different PRIVATE IPs

**Comment by rafaelfranca** [comment]
We can't know about that and to avoid an attack happens because a proxy faked one of the IPs it is better to raise. If you are not concerned disable the configuration.

**Comment by palexvs** [comment]
@rafaelfranca can you describe a situation where my code would lead to the wrong behaviour?

Currently, some part of my visitors get 500 Error because of the current code, but they do not try to spoof my server. It's happening just because they have a proxy in their locale network that set `Client-IP` header:
client (10.0.0.1) -> Proxy (1.1.1.1) sets Client-IP: 10.0.0.1 -> AWS ELB sets X-Forwarded-For: 1.1.1.1 -> Rails raises exception `IpSpoofAttackError ` and return 500

**Comment by matthewd** [comment]
If a client-set `Client-IP` header is reaching the server, this would only fix the problem for people who happen to have [what your server considers to be] internal IPs in it. That's a rather half-strength fix, at best.

It also gets the result wrong when the all-internal-IPs header is the one that's right.

The error is called "IpSpoofAttackError", because it means the server *could* be open to a spoofing attack -- it's not necessarily making a claim about the actually-currently-connected client's intent. 

Perhaps we should offer a config option to state which header to trust. If we know that our immediate proxy always sets X-Forwarded-For, we can safely ignore Client-IP entirely. (Just turning off `ip_spoofing_check` is enough to do that right now, but I don't believe the order is documented/guaranteed... and we have no way of doing the reverse.)

**Comment by bogdan** [comment]
`X-Forwarded-For` is standardized in the RFC https://tools.ietf.org/html/rfc7239.

`Client-IP` header looks deprecated. Internet doesn't know a lot about it.
The only ok source about `Client-IP` header is https://stackoverflow.com/questions/7445592/what-is-the-difference-between-http-client-ip-and-http-x-forwarded-for which even tells that `Client-Ip` is not a valid header name and should be `X-Client-Ip` instead. @matthewd @eugeneius can you find any reliable source on this header?

Based on my research, I would just remove the `Client-Ip` header support from the middleware. I traced back when it was added to Rails and it goes up to 2004 when neither x-forwarded-for nor client-ip were a standard: https://github.com/bogdan/rails/commit/18d614040a709918ce97b9ef49781b0db78ed0cd. 



I would consider `Cli

**Comment by eugeneius** [comment]
Thanks for clarifying @palexvs - I think the fix proposed here is actually safe.

To determine the client's real IP, we walk backwards along the chain of IP addresses, and pick the first public one we encounter. The reason we reject requests with multiple IP forwarding headers is so that we don't process them in the wrong order and pick the wrong public IP. Filtering private IPs from the headers doesn't affect the order in which we will encounter public IPs.

Coincidentally, this issue was opened 3 years to the day after https://github.com/rails/rails/pull/15568, which proposes the same fix.

> It also gets the result wrong when the all-internal-IPs header is the one that's right.

If a trusted proxy sends an IP forwarding header that only contains private IPs, then the request originated inside your network. If an attacker can forge requests from there, they could just send that same header to the proxy and have it forwarded along, instead of trying to forge the _other_ header.
