### ISSUE TITLE
action cable disconnects when files change

### ISSUE THREAD

**Issue by catmando** [rails/rails#29384]
### Steps to reproduce

Touch an application source file (i.e. a view)
Do an HTTP request on the server
Action Cable connection is closed
It will immediately open again if you do a `.connection.open()` on the client

This prevents tools like js hot reloader from working.

### Expected behavior
There should be some kind of *documented* signal / callback so that the application knows that connection is offline

Better yet would be some way to turn off this behavior or choose what you want to do.

**Comment by matthewd** [comment]
The disconnect is expected behaviour, caused by the application reload: the only alternative would be to refuse to reload as long as the socket is connected, which seems less-than-useful.

The original theory was that the client-side application would have to handle that disconnection the same way it would any other -- if anything, acting as a reminder that transient disconnects are common when working over a network.

Can you expand on where this is going wrong? The fact it's disconnected *should* get noticed, and cause a reconnection. What "js hot reloader" is using the ActionCable connection? :confused:

**Comment by catmando** [comment]
@matthewd - so is there some "disconnect signal" that tells the client that connection closed?  How can the application know that the connection has gone down, and needs to try re-establishing the connection?
