### ISSUE TITLE
Setting cache_store in initializer not working

### ISSUE THREAD

**Issue by coreyhaines** [rails/rails#29489]
### Steps to reproduce

In Rails 4.2.7, I had moved my cache store initialization into an initializer from application.rb. I was using

```
Rails.configuration.cache_store = :redis_store, ENV["REDIS_URL"].to_s
```

I recently upgraded to Rails 5.1 and noticed that Redis had stopped being accessed. If I pulled up a rails console, then
```
Rails.cache.class #=> ActiveSupport::Cache::FileStore
```

If I moved back to setting the cache store in application.rb, it started working again.

```
config.cache_store = :redis_store, ENV["REDIS_URL"].to_s
```
in the rails console, I would get 
```
Rails.cache.class #=> ActiveSupport::Cache::RedisStore
```

### Expected behavior
I would expect that initializing the cache store in an initializer would set the cache store being used, since it seems like the guidance is to start using initializers more than putting everything into application.rb.

### System configuration
Rails 5.1
Ruby 2.4.1p11
Redis-Rails 5.0.2

**Comment by vipulnsward** [comment]
The cache store is initialized early on in the bootstrap process before the initializers are run.
As the comment states on https://github.com/vipulnsward/rails/blob/827bfe4f41c39eade078e26ad5653979891d89c7/railties/lib/rails/application/bootstrap.rb#L62 , its so that other railties can consume cache_store as well.

You can continue setting it in config from developement.rb/production.rb, try to run it before this cache hook - `: initialize_cache` (?), or set the cache instead directly from initalizer.

**Comment by coreyhaines** [comment]
Is this a recent change for Rails 5? I was setting it in an initializer in Rails 4. (I will verify this)

**Comment by coreyhaines** [comment]
Okay, just verified that I moved it out of application.rb into the initializer as part of the upgrade (done this week). My apologies. I moved everything out of application.rb into their initializers, because `rails app:update` was overwriting it.
Thanks.
