### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by wasif-saeed-confiz** [rails/rails#29532]
i am using rbenv. my rails version is 5.1.1. my ruby version is 2.4.1. 
When i run rails s command i got following one liner error. 

`Segmentation fault (core dumped)`

i have tried to reinstall ruby, try to start server using bundle exec rails s, bundle update but still getting error. Only rails -v command is working fine any other rails command is not working.

**Comment by meinac** [comment]
I'm not able to reproduce this, I've tried to reproduce with `Rails 5.1.1` and `Ruby 2.4.1p111`. Can you please share an example application which demonstrates this issue?

**Comment by wasif-saeed-confiz** [comment]
@meinac i have some other projects on my machine and all are working fine except one. I don`t know how to debug because error info is very generic and small. i  cannot share that project because companies privacy policies. Please can you give me a hints to fix this.

**Comment by meinac** [comment]
This implies that the root of the problem is not Rails itself, maybe a gem or something you've written inside of the project. I would love to help you but without information I can't. You can try to find last working version of the application by going back in the history of git or you can try to change the Rails/Ruby version of the application or you can try to remove gems one by one till application gets working. Also I recommend you to ask this question in stackoverflow or similar forums where you can access more people, we are using github issues for only issues about Rails and limited number of people are watching this issues.

**Comment by wasif-saeed-confiz** [comment]
@meinac very appreciated.

**Comment by eileencodes** [comment]
Hi @wasif-saeed-confiz generally Stack Overflow can be more helpful for these types of errors because they're not an issue with the overall framework. If you do find that it's a reproducible issue with the framework itself (and not your application) please open a new issue with reproduction steps. Thanks!
