### ISSUE TITLE
after_create_commit and after_update_commit alias don't always run when next to each other

### ISSUE THREAD

**Issue by sankalpk** [rails/rails#29554]
### Steps to reproduce
Create a model X and add this to the model file:
```ruby
after_create_commit :do_stuff
after_update_commit :do_stuff


def do_stuff
  puts "doing stuff"
end
```
Run rails console:
```
rails c
```
Create a new X
```
X.create(title: "Blah")
```
### Expected behavior
We would expect the after_create_commit callback to run and "doing stuff" should be printed out.
### Actual behavior
The after_create_commit callback does not run and "doing stuff" is not printed out.

### System configuration
**Rails version**:
5.0.4
**Ruby version**:
2.3.1

**Comment by alfie-max** [comment]
I just checked it out, and i do see the issue.

After checking the source, I seriously doubt the `after_update_commit` is overriding the previously set `after_create_commit` callback.

Seems like the only way to have commit callbacks on multiple actions is by using the previous syntax : `after_commit :do_stuff, on: [:create, :update]`

This could be a bug or needs to be properly documented.

**Comment by eugeneius** [comment]
See https://github.com/rails/rails/issues/19590, and in particular https://github.com/rails/rails/issues/19590#issuecomment-274209827.

The call to `after_update_commit` _does_ override the callback added by `after_create_commit`, because under the hood they both set `after_commit` callbacks with different conditions.

However the `after_*_commit` aliases look like they're implemented as distinct callbacks, which is confusing to the point where it could probably be considered a bug.

I experimented with fetching the existing callbacks and merging them with the ones being added, but the implementation was too messy and brittle (it would involve extracting and parsing [this string](https://github.com/rails/rails/blob/v5.1.1/activerecord/lib/active_record/transactions.rb#L286)).

Maybe these really should be distinct callbacks, rather than aliases for `after_commit`?

**Comment by yivo** [comment]
Related to #20911? https://github.com/rails/rails/issues/20911#issuecomment-286845056

**Comment by rafaelfranca** [comment]
> Maybe these really should be distinct callbacks, rather than aliases for after_commit?

No they are just aliases and this is not a bug, it just need to be properly documented.

**Comment by rafaelfranca** [comment]
Could someone open a PR to document this behavior?

**Comment by trafium** [comment]
Just encountered this issue and by trial and error figured out that:
this does not work:
```
after_create_commit :foo
after_update_commit :foo, if: :bar?
```

and this **does** work:
```
after_create_commit -> { foo }
after_update_commit -> { foo }, if: :bar?
```

**Comment by aditya-citrix** [comment]
I faced the same problem and changing it to solution provided by @trafium worked.
