### ISSUE TITLE
Getting started mislead

### ISSUE THREAD

**Issue by git-matt** [rails/rails#29558]
I was following the tutorial "Getting Started" and found a slight issue in 6.1.
Perhaps it was just worded in a strange way.
First it mentioned about the new addition and one should examine the 'db/scema.rb' file, and showed an example output.  I assumed this file would be identical to mine, however the 'create_table "comments"' section didn't exist (yet).
Next it said to do 'db:migrate'.
Only after that did the scema file appear like the example.

If I were writing this, I'd say 'db:migrate' first then show the output.  This was misleading and confusing.
So I would've put them around the other way.  Do you agree?

**Comment by shivabhusal** [comment]
yes, `schema.rb` is supposed to appear after the migration

**Comment by alexcameron89** [comment]
> You can get a better understanding after analyzing the db/schema.rb file below.

@git-matt That line should be talking about the migration file below, not a `schema.rb` file since there isn't one in the doc section to reference. Would you like to submit a pull request to make this more clear? [Here's our guide to contributing to the documentation](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation) if you'd like to do so.
