### ISSUE TITLE
ActiveRecord overridden getter/setters not called consistently in FormHelper when validation fails

### ISSUE THREAD

**Issue by mterwill** [rails/rails#29574]
### Steps to reproduce
Say we have a model, `Item` for which we want to track a title (`string`) and a price (`integer`) in _cents_. Writing the price in cents isn't logical for the user, so we provide override the getter and setter for the `price` field.

```ruby
class Item < ApplicationRecord
  validates :title, presence: true

  def price=(dollars)
    write_attribute(:price, dollars.to_f * 100.0)
  end

  def price
    (read_attribute(:price) || 0) / 100.0
  end
end
```

We use the form generated by the `rails g scaffold`:

```erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
```

and the controller action generated by `scaffold` as well:

```ruby
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
```

### Expected behavior
We expect our overridden methods to always be called and consistently return amounts in dollars while storing an integer value for cents in the database. 

### Actual behavior
If validation passes, this works as expected, no problems. If validation _fails_ on the other hand, say because you forgot to include the title, the value gets multiplied by 100 and presented to the user:

![image](https://user-images.githubusercontent.com/5882053/27521186-e7352584-59e7-11e7-8600-6d7c41262071.png)

-----

Now, press 'Update Item':

![image](https://user-images.githubusercontent.com/5882053/27521187-ec1cbc60-59e7-11e7-8b73-efd2c82d941e.png)

### System configuration
**Rails version**: 5.0.4

**Ruby version**: 2.3.1

**Comment by fuzzkat** [comment]
I can confirm this bug.  I reproduced it with Rails/ActiveRecord 5.1.1 and ruby 2.3.1.
It occurs during validation for create and update.

**Comment by rafaelfranca** [comment]
When the input come from the user, that is the case when  you show the error page, Rails will call `price_before_type_cast` instead of `price`. This is because if the user input `foo` in price you want to show them `foo` instead of `0` in case price is a number so the user can see what they did wrongly.

That said this behavior is not a bug. I recommend you to have a `price_in_cents` in the database and define the `price` reader and writer that set the value to `prince_in_cents`. It not only make this case work, but also is less confusing to who is working in the system since you know that price is stored in cents.

**Comment by vol7ron** [comment]
Why was this closed again?  I know @rafaelfranca said it's not a bug and expected behavior, but I'd like to challenge that.

I was doing something recently with date conversions.  The database stores it in a particular way, but a UI plugin expects the date in a specific format.  When creating/showing, using a getter works flawlessly.  Even editing/updating works as expected.

An issue occurs when an input does not pass the ActiveRecord requirement, as stated in the initial post above.  For example, consider a book (@book) that has:
* Title
* Author
* Publication Date
Let's say the ActiveRecord validates the presence_of all the fields.

You create a record and everything validates.  Then you realize you aren't sure who the author is and edit it.  Let's say for testing purposes you clear out the Author and try to update the record.  It fails validation.  However, when it reloads it doesn't use the getter for the @book[:publication_date] and instead spits out the value stored in the database.

Now the date UI plugin, which expected the date to be in a certain format chokes and displays nothing.  

See the issue?

The form helper works different when an error is encountered.  Why shouldn't it use the accompanying getter, which it uses for the *show* view/controller?  Correction: for all other views/controllers when an error is not encountered

**Comment by rafaelfranca** [comment]
Yeah, I see the issue, your date plugin expects an specific format and you spec Rails to automatically handle that for you, but I'm sorry it will not, if your plugin requires a format you need to handle that manually in your application.

The form helpers use the `_before_type_cast` methods for the reasons I explained above, if want to it to have the same behavior as the reader you can alias both methods.

**Comment by vol7ron** [comment]
@rafaelfranca   Thank you. I'm sure you've answered, but since I don't recall ever using the `*_before_type_cast` methods specifically, I probably didn't recognize what the solution was.

For clarification, in the original post that @mterwill so elegantly laid out, where would the `price_before_type_cast` method be placed, inside the model?

Is this the suggested solution?:

```Ruby
class Item < ApplicationRecord
  validates :title, presence: true

  def price=(dollars)
    write_attribute(:price, dollars.to_f * 100.0)
  end

  def price
    (read_attribute(:price) || 0) / 100.0
  end

  alias_method :price_before_type_cast, :price
end
```

**Comment by rafaelfranca** [comment]
Yeah, that would work, but that also has potential to mess other things. the value before type cast should match exactly what the input was.

```ruby
user.age = "foo"
user.age #=> 0
user.age_before_type_cast # => "foo"
```

This way you can use that method to generate the error message to tell the user what was typed wrongly.

In your case I'd explicitly set the value in the format you want:

```ruby
<%= f.text_field : publication_date, format_date(f.object.publication_date) %>
```

**Comment by vol7ron** [comment]
I see the dilemma, just wish didn't need to manually insert it into the view.  Just something else to be aware of, which could be easy to forget.  — thanks for the added information!

**Comment by rafaelfranca** [comment]
I tried to change this behavior some time ago, and the default UX for users of applications were not good at all. They typed "foo" and they got "0" when an validation error happened.

**Comment by vol7ron** [comment]
Yeah I can see, my case is particular because whatever the plugin I was using wasn't flexible, so while the date appears on the element which is close enough, the UI element is not rendered correctly because it wasn't the expected format.  I forget what it was.. a datepicker of some sort. Maybe Bootstrap?
