### ISSUE TITLE
No route matches [GET] "/favicon.ico"

### ISSUE THREAD

**Issue by davidrv** [rails/rails#29578]
### Steps to reproduce

Create new rails API project:

`rails new testapp --api`

Run the rails server for the project:

`rails s`

Open the rails welcome page on http://localhost:3000

### Expected behavior

It should just appear the welcome page without errors or warnings.

### Actual behavior

The welcome page appears, but it also returns an error related with the favicon:

```
Started GET "/favicon.ico" for 127.0.0.1 at 2017-06-21 10:10:01 +0100

ActionController::RoutingError (No route matches [GET] "/favicon.ico"):

actionpack (5.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.1) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
````

### System configuration
**Rails version**:  5.1.1 and 5.2.0.alpha

**Ruby version**: 2.4.1 (x86_64-darwin16)

**Comment by davidrv** [comment]
I can prepare a fix but I'm not sure if the expected behavior should be removing the favicon from the welcome page or just stop removing the `favicon.ico` file from the `public` directory.

What do you prefer?

**Comment by rafaelfranca** [comment]
Since the welcome page is inside the framework lets just move the favicon to inside the framework since it doesn't matter if the favicon is on the public folder or not.

**Comment by davidrv** [comment]
Hi @rafaelfranca, thanks for your feedback! Hope this PR fixes the issue :)

**Comment by tpal94** [comment]
You're getting this error because you don't have a favicon.ico in your public/ directory of your application. Because the file doesn't exist there, Rails moves on, looking for a route to match against /favicon.ico in the config/routes.rb.

You can fix this in one of two ways

Manually place the favicon.ico file in the public/ directory of your application.
Put the favicon.ico in app/assets/images/ and then change your <link ... tag to use image_path

<link href="<%= image_path("favicon.ico") %>" rel="shortcut icon" />
This will place the favicon.ico in public/assets/favicon.ico, not in the document root.
I suggest sticking with #1 above.

As for why this request is even showing up in your logs, many modern browsers look in the root of the domain for /favicon.ico to use for bookmarking, or presentation in a tab or the address bar. This is why it's a good idea to keep the favicon.ico in the root of your domain, in case a browser decides (for whatever reason) to ignore your <link rel="icon shortcut" ... tag.

**Comment by PrimeTimeTran** [comment]
@tpal94 I'm sorta experiencing the same problem since I've added a library to my project. However, I'm still in development mode so I thought that the asset pipeline compiles all the assets on the fly?

Whenever I load my app now I still get 404 not found for my four assets. Mind giving me a pointer?
![screen shot 2017-08-22 at 11 16 20 pm](https://user-images.githubusercontent.com/16382165/29575857-fdfaaea8-878f-11e7-842b-ec985d7dc228.jpg)
![screen shot 2017-08-22 at 11 16 12 pm](https://user-images.githubusercontent.com/16382165/29575858-fe0cbc6a-878f-11e7-9293-3cd2cadea226.jpg)

**Comment by composerinteralia** [comment]
@PrimeTimeTran this might help you: http://guides.rubyonrails.org/asset_pipeline.html#coding-links-to-assets

**Comment by luizkowalski** [comment]
I do have a favicon.ico icon on my public folder and I'm still seeing this issue

**Comment by wbotelhos** [comment]
And when do I want to use a favicon.*png*?

**Comment by hugobarthelemy** [comment]
I had the same bug with my new rails API and I doesn't want adding asset file. My solution is to add `config.serve_static_files = false` in config/environments/production.rb

**Comment by EmTee70** [comment]
I took `config.public_file_server.enabled = true` 
from: http://guides.rubyonrails.org/configuring.html 

Because, there was a mentioning of deprecating `config.serve_static_files = false` ??

**Comment by MicMicMon** [comment]
Putting a `favicon.ico` in the public folder fixed it for me.

**Comment by AlexVPopov** [comment]
While the comments here do provide both an explanation and a fix for the issue (namely put a favicon in public/), I don't think it's a sane default to create a new rails project (even with the `--api` flag), visit localhost:3000 and immediately hit an error. I think there should be a happy path right after `rails new` and `rails server`. What happened with @rafaelfranca's suggestion, of moving the favicon inside the framework?

**Comment by andrewfader** [comment]
What if we have a default route in rails that returns a binary 0 byte response to this request? I could prepare a PR if someone +1 that this is a good solution

**Comment by AlexVPopov** [comment]
Yeah, still, what happened to @rafaelfranca's suggestion, of moving the favicon inside the framework? What are the cons to this approach?

**Comment by tcd** [comment]
Why was this issue closed? This problem still exists.

**Comment by hahmed** [comment]
@tcd I will prepare a fix for this 👍

```
Started GET "/" for ::1 at 2021-07-02 20:06:51 +0100
Processing by Rails::WelcomeController#index as HTML
  Rendering /Users/haroon/.gem/ruby/2.7.2/gems/railties-7.0.0.alpha/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /Users/haroon/.gem/ruby/2.7.2/gems/railties-7.0.0.alpha/lib/rails/templates/rails/welcome/index.html.erb (Duration: 0.3ms | Allocations: 8)
Completed 200 OK in 1ms (Views: 0.8ms | ActiveRecord: 0.0ms | Allocations: 231)


Started GET "/favicon.ico" for ::1 at 2021-07-02 20:06:51 +0100
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
```

**Comment by sureshpvx** [comment]
Started GET "/demo" for 127.0.0.1 at 2023-04-25 17:37:49 +0530
Processing by DemoController#index as HTML
Completed 200 OK in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms | Allocations: 124)


Started GET "/favicon.ico" for 127.0.0.1 at 2023-04-25 17:37:49 +0530
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):


why i am getting this
