### ISSUE TITLE
ActiveSupport::Concern doesn't recognize Model class

### ISSUE THREAD

**Issue by invinc** [rails/rails#29694]
ActiveSupport::Concern doesn't recognize Model class

While I am refactoring my models by using model concern, I got an issue model can't be passed in concern. 
When I call House model in concern in rails console, model class is passed as Concerns::House instead House model.

Here is my code:
module Concerns::Channel::Booking
  extend ActiveSupport::Concern
  module ClassMethods
    def retrieve_xxx_api(channel_id, access_token)
      channel = Channel.find_by(id: channel_id)
      if channel.present?
        account = channel.account
        if (listing_data=Api.get_listings_api(access_token, 'xxx')).present?
          listing_data.each do |l|
            House.skip_callback(:create, :after, :after_create_jobs, raise: false)
            house = House.find_or_create_by(uid: l["code"], account: account) do |h|
               .......
            end
            House.set_callback(:create, :after, :after_create_jobs)
          end
        end
      end
    end
  end
end

In this function, House model was passed Concerns::House instead House model.

Rails Version: 5.0.3
Ruby Version: 2.3.1p112

I look forward to hear your solution.

**Comment by fxn** [comment]
Does Concerns::House exist?

Note that Concerns is not supposed to become a module. The _concerns_ directories belong to the autoload path, so that you don't need that namespace. (This is kind of an anomaly, but it is the way it works.)

**Comment by invinc** [comment]
Thanks for your answer.
I doesn't have Concerns::House, but I have other concerns associated with House model such as Concerns::House::Common and module Concerns::House::Calendar.
These house concerns with name space are associated with above issues?

**Comment by invinc** [comment]
I have solved this issue by remove concern name space in module name.

**Comment by fxn** [comment]
Awesome.

Let me just add that if `Concerns::House::Common` exists, then necessarily `Concerns::House` does exist and the code was just resolving that one because it is checked earlier than the top-level `House` in the resolution algorithm.

Since you weren't aware of its existence, probably the project had a directory called _concerns/house_, acting as a namespace. For those, Rails creates modules on the fly. That is why the constant path `Concerns::House::Common` works, because `Concerns::House` is a module.

That is a technical followup only, removing the `Concerns` namespace is the idiomatic solution.
