### ISSUE TITLE
parameter to find_by cached as has_many association on resulting object

### ISSUE THREAD

**Issue by zachwalton** [rails/rails#29702]
### Steps to reproduce

(script to reproduce: https://gist.github.com/zachwalton/b3789905de06633cb9f222ad2e5af272)

Create some models:

```
ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end
```

Create some instances:

```
post = Post.create!
post.comments << Comment.create!
post.comments << Comment.create!
post.comments << Comment.create!
    
search_comments = [Comment.first]
search_result = Post.includes(:comments).find_by(comments: { id: search_comments })
```

### Expected behavior
`post.comments.map(&:id) == search_result.comments.map(&:id)`

### Actual behavior

```
> post.comments.map(&:id)
[1, 2, 3]
> search_result.comments.map(&:id)
[1]
```
It appears that `search_result.comments` is getting cached as the array that's passed into the `find_by` query.

### System configuration
**Rails version**: `4.2.7.1`, also reproduced in `5.1.2`

**Ruby version**: `2.3.3`

**Comment by zachwalton** [comment]
Here's an AR bug report template reproducing this (last test case fails):

https://gist.github.com/zachwalton/b3789905de06633cb9f222ad2e5af272

**Comment by alexcameron89** [comment]
If I'm understanding your problem correctly, it's not a caching problem. The `search_result` query limits comments to the ids you pass into the find_by:

``` sql
SELECT "posts"."id" AS t0_r0, "comments"."id" AS t1_r0, "comments"."post_id" AS t1_r1 FROM "posts" LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id" WHERE "comments"."id" = 3 AND "posts"."id" = 1
```

I think the query you'd want to grab all of the comments are:

``` ruby
search_result = Post.includes(:comments).find_by(comments: { post_id: search_comments.first.post_id }
```

The reason `#count` works with your query is because it's going to run a count query on the database: `SELECT COUNT(*) FROM "comments" WHERE "comments"."post_id" = ?  [["post_id", 1]]`

I can see how the pluck is confusing. Pluck [is going to use the included records ](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/calculations.rb#L176)rather than calling a query, since they're considered loaded even though not all of the records are loaded. But, I don't see a way for pluck to know the true amount of comments for the post without doing another query, which negates the point of the `loaded?` check.

**Comment by che-burashco** [comment]
From what I understand the problem is that includes is used to get the comments. Includes is generally used to solve n+1 query problem and not to join on to table to get the associated table joined for the search. What you are looking for is 'joins'

The following statement, for example, would produce correct results:
`search_result = Post.joins(:comments).find_by(comments: { id: search_comments })`

**Comment by zachwalton** [comment]
Thanks @alexcameron89 for the detailed clarification!

@che-burashco, confirmed that using `joins` achieves the expected result. Thanks.

```
D, [2017-07-07T08:07:48.333784 #80648] DEBUG -- :   Post Load (0.2ms)  SELECT  "posts".* FROM "posts" INNER JOIN "comments" ON "comments"."post_id" = "posts"."id" WHERE "comments"."id" = 3 LIMIT ?  [["LIMIT", 1]]
D, [2017-07-07T08:07:48.335263 #80648] DEBUG -- :    (0.1ms)  SELECT COUNT(*) FROM "comments" WHERE "comments"."post_id" = ?  [["post_id", 1]]
D, [2017-07-07T08:07:48.335693 #80648] DEBUG -- :    (0.0ms)  SELECT "comments"."id" FROM "comments" WHERE "comments"."post_id" = ?  [["post_id", 1]]
D, [2017-07-07T08:07:48.336188 #80648] DEBUG -- :   Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ?  [["post_id", 1]]
```
