### ISSUE TITLE
Should a child touch its parent on destroy when the parent initiated the destroy?

### ISSUE THREAD

**Issue by brendon** [rails/rails#29707]
We have `destroyed_by_association` that is used to prevent unnecessary counter cache updating, but this could similarly be used to prevent unnecessary touching of parent relations when a parent initiates a destroy of the child.

I'd be keen to work on a PR for this but wanted to gauge whether others thought it was a good idea.

**Comment by matthewd** [comment]
> Should a child touch its parent on destroy when the parent initiated the destroy?

If the child is being destroyed because the parent will also be destroyed in the same transaction, then yes, it seems fine to skip the touch too. But I would've thought this was already handled by `touch_later` & friends -- we aggregate the touches until transaction commit, at which point the parent's already been destroyed.

If I'm wrong and we're currently getting so far as actually sending UPDATEs for parent records we already know are going away, then yes, that sounds PR worthy indeed. 👍🏻

**Comment by brendon** [comment]
Thanks @matthewd, sorry for the slow reply. Just looking through the code it appears you're right, though I'm struggling to get my head around the `Persistence` and `TouchLater` classes. I'm assuming `belongs_to_touch_method` in `Persistence` is overridden by the method in `TouchLater`?

I'm happy to let this lay :)
