### ISSUE TITLE
Active Record: Add GlobalID backed polymorphic associations

### ISSUE THREAD

**Issue by kaspth** [rails/rails#29729]
https://github.com/rails/activestorage/issues/20#issuecomment-313919968

Currently Active Record's polymorphic associations support looks like this:

```ruby
class Event < ActiveRecord::Base
  belongs_to :eventable, polymorphic: true
end

class Message < ActiveRecord::Base
  has_many :events, as: :eventable
end

class Post < ActiveRecord::Base
  has_many :events, as: :eventable
end
```

which wires `Event`s to the `eventable` via an `eventable_type` and `eventable_id` column.

Since Rails 4.2 brought along GlobalID we've had a way to encode a reference to a model as a URI — and then look that up later. These could also work for polymorphic associations. `Event` could have an `eventable_id` (or `eventable_gid`) column that stashes a GID for the `eventable` — e.g. `gid://app/Post/1` — and skips the `eventable_type` column all together.

Useful for Active Storage to convert it's `has_one_attached` and `has_many_attached` to use Rails' standard association methods under the hood.

### Compatibility

- Should GIDs be the new polymorphic association type going forward?
- Or should the columns dictate the polymorphic association type?
- What's the benefits/drawbacks for eager loading / indexes / looking up `Event`s for a particular eventable type?

cc @dhh @kamipo

**Comment by hundredwatt** [comment]
On the other hand, polymorphic associations as they exist today aren't broken. What are the benefits/drawbacks of using a polymorphic association for ActiveStorage rather than implementing a new approach for GlobalID associations? i.e.,  in ActiveStorage, `has_one_attached :avatar` could simply be a macro for `has_one :avatar, as: :record, class_name: 'Attachment'` 

One drawback I can think of for GlobalID assocationsh is not being able to use nested subqueries. e.g, With a polymorphic association, you could create this query which ActiveRecord w: 
```
rails(dev)> ActiveStorage::Attachment.where(record_type: User, record_id: User.where(account_id: 1))
  ActiveStorage::Attachment Load (4.1ms)  SELECT `attachments`.* FROM `attachments` WHERE `attachments`.`record_type` = 'User' AND `attachments`.`record_id` IN (SELECT `users`.`id` FROM `users` WHERE `users`.`trashed_at` IS NULL AND `users`.`account_id` = 1)
=> #<ActiveStorage::Attachment::ActiveRecord_Relation:0x3fe8c0fd7c38>```
Whereas with the a gid assocation, Rails would not be able to nest the query since gids need to be computed in Ruby, so we get 2 queries:
```
rails(dev)> ActiveStorage::Attachment.where(name: 'avatar', record_gid: User.where(account_id: 1).map(&:to_gid).map(&:to_s))
  User Load (2.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`trashed_at` IS NULL AND `users`.`account_id` = 1
  ActiveStorage::Attachment Load (1.1ms)  SELECT `attachments`.* FROM `attachments` WHERE `attachments`.`name` = 'avatar' AND `attachments`.`record_gid` = 'gid://rails/User/1'
=> #<ActiveStorage::Attachment::ActiveRecord_Relation:0x3fe8c0eea118>
```

cc @dhh @kaspth  @kamipo

**Comment by hundredwatt** [comment]
GlobalID associations do carry the primary benefit of supporting associations to non-ActiveRecord objects or ActiveRecord objects in other applications. I don't have a specific use case for this, but others may have some examples.

**Comment by dhh** [comment]
The primary limitation is that you can't currently eager load polymorphic associations without specifying a single class. So if you want an association to contain multiple types, the _type/_id combo does not suffice.

But I don't think we need to remove what we have today. I think we should simply allow polymorphic associations to work with _gid columns and then use GlobalID.

**Comment by hundredwatt** [comment]
> The primary limitation is that you can't currently eager load polymorphic associations without specifying a single class. So if you want an association to contain multiple types, the _type/_id combo does not suffice.

I tested this in a Rails 4.2 application expecting it not to workand was surprised that it did! ActiveRecord generates an eager load query for each type automatically: 

```
> PhotoAttachment.create(owner: Message.first, file: File.open('image.jpg'))
...
> PhotoAttachment.create(owner: User.first, file: File.open('image.jpg'))
...
> PhotoAttachment.includes(:owner).to_a.map(&:owner)
  PhotoAttachment Load (0.4ms)  SELECT `attachments`.* FROM `attachments` WHERE `attachments`.`type` IN ('PhotoAttachment')
  User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` IN (1)
  Message Load (0.3ms)  SELECT `messages`.* FROM `messages` WHERE `messages`.`id` IN (1)
=> [#<User..., #<Message...]
```

**Comment by dhh** [comment]
Ah yes, the problem occurs when you're using :through. See https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations.rb#L40

**Comment by kaspth** [comment]
Let's see how https://github.com/rails/activestorage/pull/32 plays out first.

**Comment by dlegr250** [comment]
I know this issue is closed, but wanted to see if this concept is still be considered?  I can present a use case where I found polymorphic associations with `global_id` to be useful.

I have a `task` model that can be associated to both `clients` and `partners`.  When I want to assign a `task`, I use a single `select` that combines both clients and partners, and stores the `global_id`.

```
# tasks/_form.html.erb
<%= f.select :assignee_global_id, grouped_options_for_select([["Clients", Client.all.collect { |c| [c.name, c.to_global_id] }], ["Partners", Partner.all.collect { |p| [p.name, p.to_global_id] }]], @task.assignee_global_id) %>
```

In my `task` model I have a callback that sets the proper `assignee` based on the global_id:

```
class Task < ApplicationRecord
  belongs_to :assignee, polymorphic: true
  before_save :set_assignee

  def set_assignee
    if assignee_global_id
      self.assignee = ::GlobalID::Locator.locate(assignee_global_id)
    end
  end
end
```

This allows me to use the simplicity of a single select for all assignable associations, but also the power of standard polymorphism.

The code above "works", but I'm always trying to find ways to simplify and reduce the same "logic" being stored in 2 methods.
