### ISSUE TITLE
Reseeding ignores engines' migrations paths

### ISSUE THREAD

**Issue by jefvlamings** [rails/rails#29852]
### Steps to reproduce
- Create a new Rails app (5.0.3), with some migrations
- Create an engine, with some migrations and append the path to the migrations paths:

```
      initializer :append_migrations do |app|
        unless app.root.to_s.match root.to_s
          config.paths['db/migrate'].expanded.each do |expanded_path|
            app.config.paths['db/migrate'] << expanded_path
          end
        end
      end
```

- Run `rake db:reset` or `rake db:drop db:setup`

### Expected behavior
The schema_migrations table should contain the application's migrations versions AND the engine's migrations versions.

### Actual behavior
Only the application's migrations versions are stored in the schema_migrations table.
This causes problems with later migrations.

### System configuration
**Rails version**: 5.0.3

**Ruby version**: 2.3.1

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by noniq** [comment]
I experience the same issue with Rails 5.1.2. But it only happens if `db:migrate` is run together with other tasks like `db:create`, while running `rails db:migrate` alone works as expected).

I think it boils down to what’s mentioned in https://content.pivotal.io/blog/leave-your-migrations-in-your-rails-engines#comment-3064097148: If the `db:load_config` task gets run *before*  the `environment` task, the migration paths have already been copied `ActiveRecord::Tasks::DatabaseTasks.migrations_paths` and `ActiveRecord::Migrator.migrations_paths` when the initializer modifies the paths in the config. Thus these modifications are never picked up.

Note that `db:migrate` depends on `[:environment, db:load_config]` (https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/railties/databases.rake#L57), while `db:drop` and others depend on `db:load_config` only.

A quick workaround is to simply explicitly add `environment` if running several tasks. For example, this works: `rails environment db:drop db:create db:migrate`
