### ISSUE TITLE
Discrepancy between ActionDispatch::TestResponse & ActionDispatch::Response behavior.

### ISSUE THREAD

**Issue by trev** [rails/rails#30072]
### Steps to reproduce

```
$ rails c
> ActionDispatch::TestResponse.new.success?
=> true
> ActionDispatch::Response.new.success?
NoMethodError: undefined method `success?' for #<ActionDispatch::Response:0x007ff3c8e1e4e8>
Did you mean?  successful?
> ActionDispatch::Response.new.successful?
=> true
```

### Expected behavior

You would expect `ActionDispatch::TestResponse` to only support messages that can also be sent to `ActionDispatch::Response`.

### Actual behavior

The `#success?` method does not exist on `ActionDispatch::Response`, it expects `#successful?` which is provided by Rack: https://github.com/rack/rack/blob/master/lib/rack/response.rb#L114

The above is fine but `ActionDispatch::TestResponse` will also respond to `success?` which leads to false-positives.

For example, the following test (abbreviated) would pass but would never work in production:

```
def can_I_pass?
  response.success?
end

it 'lets me pass' do
  expect(controller.can_I_pass?).to be true
end
```

### System configuration

**Rails version**: Rails 5.1.2
**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]

**Comment by trev** [comment]
Happy to submit a PR if I get the 👍 that I'm indeed not just missing something... it is Friday evening after all.

**Comment by kirs** [comment]
`success?` is just an [alias](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/test_response.rb#L23) for `successful?`. I agree with your point about not being consistent. [Looks](https://github.com/rails/rails/commit/308517e913ef1e8d9f13e023bc450374b5ed780a) like `successful?` was added back in 2010, when Rack may not had that helper.

Since it's a public and documented method on `TestResponse` I think it makes sense to first deprecate it before removing.
