### ISSUE TITLE
Foreign keys and associated primary keys are not quoted in the ALTER TABLE postgresql query

### ISSUE THREAD

**Issue by kaligrafy** [rails/rails#30075]
Foreign key name should be quoted, like column and table names.

### Steps to reproduce
Just add a camelized foreign key:
`add_foreign_key(:dw_od_sample_dimensions, "dw_od_survey_dimensions", {:exclude_index=>true, :name=>"fkDwOdSampleDSampleSurveyKey", :column=>"SampleSurveyKey", :primary_key=>"SurveyKey"})`

### Expected behavior
`: ALTER TABLE "dw_od_sample_dimensions" ADD CONSTRAINT "fkDwOdSampleDSampleSurveyKey" FOREIGN KEY ("SampleSurveyKey") REFERENCES "dw_od_survey_dimensions"("SurveyKey")`

### Actual behavior
`PG::UndefinedColumn: ERROR:  column "surveykey" referenced in foreign key constraint does not exist`
`: ALTER TABLE "dw_od_sample_dimensions" ADD CONSTRAINT "fkDwOdSampleDSampleSurveyKey" FOREIGN KEY ("SampleSurveyKey") REFERENCES "dw_od_survey_dimensions"(SurveyKey)`

### System configuration
**Rails version**: 4.2.7

**Ruby version**: 2.4.1

**Comment by sgrif** [comment]
Rails 4.2 only receives security fixes. If this issue is still present in Rails 5.1, please open a new issue and provide a script we can use to reproduce the problem [using our standard bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)
