### ISSUE TITLE
Scopes are being applied to unrelated queries

### ISSUE THREAD

**Issue by knjko** [rails/rails#30266]
### Steps to reproduce

https://gist.github.com/knjko/2b42062f4c9b831f8cb3297dcb0c5ed8

Given the following app:

```ruby
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments, through: :posts
end

class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  scope :by_user, ->(user) { joins(:user).where(users: { id: user }) }
end

class Comment < ActiveRecord::Base
  belongs_to :post
end
```

Retrieving associations with unrelated `scoping`:

```ruby
Post.by_user(user).scoping do
  puts user.comments
end

# => ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: users.id
```

I feel this may be the similar problem as https://github.com/rails/rails/issues/29338 .

### Expected behavior

```sql
SELECT "comments".*
FROM "comments"
INNER JOIN "posts" ON "comments"."post_id" = "posts"."id"
WHERE "posts"."user_id" = ?
```

### Actual behavior

```sql
SELECT "comments".*
FROM "comments"
INNER JOIN "posts" ON "comments"."post_id" = "posts"."id"
WHERE "users"."id" = 1
  AND "posts"."user_id" = ?
```

### System configuration

**Rails version**: 5.0.5
**Ruby version**: 2.4.1

**Comment by chopraanmol1** [comment]
Problem you are facing is because of this line: [active_record/associations/through_association.rb#L20](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/through_association.rb#L20)

As you may see for through association we are ignoring joins but not where, which in your case adds the users.id column in query.

So solution for this might be to simply only use where conditions which on both left and right side doesn't have reference to another table. So in your case that will ignore users.id, But I'm not sure what is needed to be done for rest of where query.
let's say if we consider rest of where query then for following query 
`Post.where(some_column: true).scoping{ user.comments }`

posts.some_column = true will also be applicable while fetching comments. Which I'm not sure is expected or not

And lets say if we ignore rest of where query then it will result into ignoring post's default scopes  as well

If first scenario is expected result than I'll create PR for this, but if it is not than there must be discussion regarding what is expected and what is not.

I guess we must wait for other people's input
