### ISSUE TITLE
Malformed parameters could make an example of ActionController raise NoMethodError

### ISSUE THREAD

**Issue by akihikodaki** [rails/rails#30519]
### Steps to reproduce

For example,
http://api.rubyonrails.org/v5.1/classes/ActionController/Parameters.html#method-i-permit
```Ruby
params = ActionController::Parameters.new(user: { name: "Francesco", age: 22, role: "admin" })
permitted = params.require(:user).permit(:name, :age)
```

That works perfectly, but it cannot properly handle the following parameter:
```Ruby
{ user: "Francesco" }
```

### Expected behavior
It should raise an error which can be handled easily like `ActionController::ParameterMissing`, and Rails should do so by returning 422.

### Actual behavior
It raises:
```
NoMethodError: undefined method `permit'
```

### System configuration
**Rails version**:
5.1.0

**Ruby version**:
```
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

**Comment by akihikodaki** [comment]
Even if `params.require(:user).permit(:name, :age)` is expected to be failed with the exception, the example and applications in real world aren't expected to fail with the exception, are they?
I think a new API should be introduced to avoid the issue.

**Comment by rafaelfranca** [comment]
Yes, they are. `require` doesn't return only hashes that responds to `permit`. It is the job of your application to handle those cases.

**Comment by sevenseacat** [comment]
I think this should be looked at again. Expecting a hash of data is a very very common use case of strong parameters - the `params.require(model_key).permit(field_names)` pattern appears _everywhere_ - and every single time is a potential 500 error to the user unless extra code is added to handle it. (Not just "those cases", it's almost every case.)

**Comment by akihikodaki** [comment]
It may be too late, but I missed a reply so let me make a late (but simple) reply.

If you don't think you need an additional API, you still need to update the documentation, as the example is cited from it. You have closed this issue, but do you have one for the documentation problem?

**Comment by monfresh** [comment]
It's very easy for some malicious person to generate 500 errors on your app by submitting POST requests with the key set to a String instead of a Hash, such as:
```console
curl -d "user=foo" -X POST http://localhost:3000/sign_up/enter_email
```
In order to prevent this, you have to handle this in every controller where you use strong parameters by doing something like this:
```ruby
def permitted_params
  user_params = params.require(:user)
  if user_params.respond_to?(:permit)
    user_params.permit(:email)
  else
    ActionController::Parameters.new({})
  end
end 
```

It would be nice if Rails handled this more gracefully, or as suggested above, by returning a 422 instead of a 500.

**Comment by collimarco** [comment]
I think that Rails should manage this more gracefully. 

The pattern `params.require(model_key).permit(field_names)` is everywhere and also the Rails generators use that code.

I understand that this is not a security issue, however it doesn't make sense that someone can produce an arbitrary number of `500` errors on the server... You should raise a `ActionController::ParameterMissing` so that `422` is returned.

**Comment by collimarco** [comment]
If the current behavior is difficult to change, it would be interesting to have at least a method like this:

```ruby
module ActionController
  class Parameters

    def require_params(key)
      params = require(key)
      if params.is_a? ActionController::Parameters
        params
      else
        raise ActionController::ParameterMissing.new()
      end
    end

  end
end 
```

Then use:

```
params.require_params(model_key).permit(field_names)
```
