### ISSUE TITLE
has_many dependent: :destroy causes _ids unassignment to delete child objects

### ISSUE THREAD

**Issue by trandoanhung1991** [rails/rails#30687]
### Steps to reproduce
```
class Product < ApplicationRecord
has_many :images, dependent: :destroy
end

class Image < ApplicationRecord
belongs_to :product, optional: true
end
```

### Expected behavior
The ruby guide explicitly state that dependent destroy behavior happens only when the object is destroyed. So I expected assigning _ids to not destroy the unassigned objects, but instead nullify the foreign key. Similar behavior to not having set dependent: :destroy

```
class Product < ApplicationRecord
has_many :images
end

2.4.0 :003 > Product.find(612).image_ids
  Product Load (0.5ms)  SELECT  "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 612], ["LIMIT", 1]]
   (2.0ms)  SELECT "images".id FROM "images" WHERE "images"."product_id" = $1  [["product_id", 612]]
 => [1272, 1273]
2.4.0 :004 > Product.find(612).image_ids = [1272]
  Product Load (0.6ms)  SELECT  "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 612], ["LIMIT", 1]]
  Image Load (6.5ms)  SELECT "images".* FROM "images" WHERE "images"."id" = 1272
  Image Load (0.4ms)  SELECT "images".* FROM "images" WHERE "images"."product_id" = $1  [["product_id", 612]]
   (0.3ms)  BEGIN
  SQL (7.0ms)  UPDATE "images" SET "product_id" = NULL WHERE "images"."product_id" = $1 AND "images"."id" = 1273  [["product_id", 612]]
   (5.4ms)  COMMIT
 => [1272]
2.4.0 :005 > Product.find(612).image_ids = [1272, 1273]
  Product Load (0.6ms)  SELECT  "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 612], ["LIMIT", 1]]
  Image Load (0.5ms)  SELECT "images".* FROM "images" WHERE "images"."id" IN (1272, 1273)
  Image Load (0.3ms)  SELECT "images".* FROM "images" WHERE "images"."product_id" = $1  [["product_id", 612]]
   (0.2ms)  BEGIN
  SQL (0.7ms)  UPDATE "images" SET "product_id" = $1, "updated_at" = $2 WHERE "images"."id" = $3  [["product_id", 612], ["updated_at", 2017-09-23 04:22:12 UTC], ["id", 1273]]
   (1.2ms)  COMMIT
 => [1272, 1273]
```

### Actual behavior
```
2.4.0 :026 > Product.find(5).image_ids
  Product Load (0.3ms)  SELECT  "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
   (0.4ms)  SELECT "images".id FROM "images" WHERE "images"."product_id" = $1  [["product_id", 5]]
 => [7, 40]
2.4.0 :027 > Product.find(5).image_ids = [7]
  Product Load (1.7ms)  SELECT  "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
  Image Load (0.5ms)  SELECT "images".* FROM "images" WHERE "images"."id" = 7
  Image Load (0.3ms)  SELECT "images".* FROM "images" WHERE "images"."product_id" = $1  [["product_id", 5]]
   (0.2ms)  BEGIN
  SQL (0.4ms)  DELETE FROM "images" WHERE "images"."id" = $1  [["id", 40]]
   (6.2ms)  COMMIT
 => [7]
```

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.4.0p0

**Comment by al2o3cr** [comment]
@trandoanhung1991 Can you clarify where you encountered that statement? It doesn't match the guide for `has_many`:

http://guides.rubyonrails.org/association_basics.html#methods-added-by-has-many-collection-objects

which says:
```
The collection_singular_ids= method makes the collection contain only the objects identified by the supplied primary key values, by adding and deleting as appropriate.
```

"... and deleting as appropriate" is the relevant part. See also the side-note on the collection's `delete` method a couple paragraphs above in the guide.

**Comment by trandoanhung1991** [comment]
That's interesting. Why would the behavior change when I remove the dependent: :destroy option, though?

My understanding is that it should only affect the collection, not the entities being dropped from the collection. Which is the expected behavior without the dependent: :destroy option.

**Comment by al2o3cr** [comment]
@trandoanhung1991 A trace through what's happening:

* the generated `collection_singular_ids=` calls `ids_writer` defined in [CollectionAssociation](https://github.com/rails/rails/blob/36888b9387731394f0079fc855ab9ad61ba8dfe5/activerecord/lib/active_record/associations/collection_association.rb#L54)

* `ids_writer` finds the objects, then calls `replace`, defined [here](https://github.com/rails/rails/blob/36888b9387731394f0079fc855ab9ad61ba8dfe5/activerecord/lib/active_record/associations/collection_association.rb#L241)

* `replace` calls `replace_records` ([definition](https://github.com/rails/rails/blob/36888b9387731394f0079fc855ab9ad61ba8dfe5/activerecord/lib/active_record/associations/collection_association.rb#L406)) which calls `delete` with the records that shouldn't be in the association anymore

* `delete` in turn calls `delete_or_destroy(records, options[:dependent])` [here](https://github.com/rails/rails/blob/36888b9387731394f0079fc855ab9ad61ba8dfe5/activerecord/lib/active_record/associations/collection_association.rb#L183)

* `delete_or_destroy` calls `delete_records` [here](https://github.com/rails/rails/blob/36888b9387731394f0079fc855ab9ad61ba8dfe5/activerecord/lib/active_record/associations/collection_association.rb#L384) for the case where the records being removed are already persisted

* `delete_records` is defined specifically for each kind of association. In this case, we want the `has_many` variety [here](https://github.com/rails/rails/blob/36888b9387731394f0079fc855ab9ad61ba8dfe5/activerecord/lib/active_record/associations/has_many_association.rb#L105). Together with `delete_count` a few lines above, this code makes the following possible choices:

  * if `method` is `:destroy`, call `destroy!` on each record
  * if `method` is `:delete_all`, call `delete_all` (generating a single `DELETE` query)
  * otherwise, `method` is either nil or `:nullify`, so update all the records to have `NULL` foreign keys.

I'm thinking [this line](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations.rb#L1203) from the documentation should be improved, as I read it as claiming that the foreign keys are *always* set to `NULL`, which isn't correct.

**Comment by sliminas** [comment]
I can reproduce this with AR 5.2.

I aggree with @trandoanhung1991 that this behavior is unexpected.

```ruby
class Album
  has_many :songs, dependent: :destroy
end
class Song
end

a = Album.create songs: [Song.build, Song.build, Song.build]
a.song_ids
# => 1,2,3
a.song_ids = [1,2] # this will now call .destroy on Song with id 3
```

The rails guide for `dependent: :destroy` [says this](https://guides.rubyonrails.org/association_basics.html#dependent):
```
4.3.2.5 :dependent
Controls what happens to the associated objects when their owner is destroyed:

:destroy causes all the associated objects to also be destroyed
```

This is not mentioning that the dependent option also has an effect if you don't destroy the owner.
In my example the owner is the Album instance and it doesn't get destroyed, so I would expect that it doesn't matter which `:dependent` option is selected, the song with id 3 should still exist, but should not be assigned to any album anymore.

In the [collection_singular_ids=(ids)](https://guides.rubyonrails.org/association_basics.html#methods-added-by-has-many-collection-singular-ids-ids) section there is some more information, but I also think it is not clear enough:
```
The collection_singular_ids= method makes the collection contain only the objects
identified by the supplied primary key values, by adding and deleting as appropriate. 
The changes are persisted to the database.
```
Since it's in the context of the association I would expect that `by adding and deleting as appropriate` means adding/deleting from the association collection, not from the database.

I think at least the documentation should be more clear about this "feature", although for me this seems to be a bug.

**Comment by sebastianludwig** [comment]
Just hit the same bug/documentation surprise. Can we reopen this issue? Is there a point in opening a new issue? Are there any workaround? @al2o3cr do you know?
