### ISSUE TITLE
Use .rb.erb file extensions for template files instead of .rb

### ISSUE THREAD

**Issue by glebm** [rails/rails#30690]
Currently, some template files here have the `.rb` file extension, e.g.:

https://github.com/rails/rails/blob/6aa56460d54518d126663b1ddc6091330b8d16b4/activejob/lib/rails/generators/job/templates/job.rb

This causes problems with static analysis tools (i18n-tasks, rubocop, etc) and syntax highlighting (in IDEs, on GitHub, etc).

Since they are not actually valid Ruby files, they should have the `.rb.erb` extension instead.

**Comment by pixeltrix** [comment]
@glebm this seems to stem from people scanning a `vendor/bundle` directory and even if we fix these then they'll be some other rule that the Rails codebase will fail on and we're not re-writing code to fit in with everyone's personal collection of rubocop rules.

**Comment by metafoo** [comment]
I would appreciate a proper extension too. The issue breaks JRuby compilation to .class files atm :(

**Comment by pixeltrix** [comment]
@metafoo how does it break JRuby compilation - when Rails is embedded in `vendor/bundle`? If so that's a better reason to change.

**Comment by Edouard-chin** [comment]
FYI some previous discussion around this were happening in this PR https://github.com/rails/rails/pull/23878 and associated issue https://github.com/rails/rails/issues/23847

**Comment by glebm** [comment]
Can someone else from the Rails team weigh in on this? 

I have doubts that pixeltrix@ opinion on this issue represents the opinion of the Rails team overall, because:

1. It's not very pragmatic: a small change for Rails, an impossible change for tool authors.
2. It goes against the established Rails conventions (e.g. we name files `.html.erb`, not `.html`).

This is regardless of whether it breaks JRuby.

Calling out to @cristianbica, the original author of one of the files in question, and @jvanbaarsen, the most recent contributor to the file.

**Comment by pixeltrix** [comment]
@glebm people having to create complex exclusions to get warbler to precompile a WAR file is a valid technical reason, whereas making other people's rubocop setups happy isn't.

The problem is that a bunch of these were renamed already and now there's some more to rename so how do we prevent it becoming a chore for the team? Is there a way to make rubocop ensure that generator template files end in `.tt` for example?

**Comment by rafaelfranca** [comment]
> Is there a way to make rubocop ensure that generator template files end in .tt for example?

Yes. It should be possible to implement a cop only for the Rails project that checks every file inside the `templates` folder to see if they have the `.tt` extension. The problem is that we can't always use `.tt`. If the method used in the generator is `copy_file` and not `template` the `.tt` extension will be not be removed.

I renamed all the files that we currently have in the framework that are templates to use the `.tt` extension.

**Comment by glebm** [comment]
For rubocop, you don't need to do anything special now, just remove [this line](https://github.com/rails/rails/blob/68fe6b08ee72cc47263e0d2c9ff07f75c4b42761/.rubocop.yml#L7) to analyze the files in `templates`. If you accidentally add a template file with the `.rb` extension, rubocop will throw a `ParseError`.
