### ISSUE TITLE
Join model not touching associated object on destroy

### ISSUE THREAD

**Issue by Linuus** [rails/rails#30842]
### Steps to reproduce

Run this test case:

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :sites, force: true do |t|
    t.datetime :updated_at, null: false
    t.datetime :created_at, null: false
  end

  create_table :site_publications, force: true do |t|
    t.integer :site_id
    t.integer :guide_id
    t.datetime :updated_at, null: false
    t.datetime :created_at, null: false
  end

  create_table :guides, force: true do |t|
    t.datetime :updated_at, null: false
    t.datetime :created_at, null: false
  end
end

class Site < ActiveRecord::Base
  has_many :site_publications
  has_many :guides, through: :site_publications
end

class SitePublication < ActiveRecord::Base
  belongs_to :site, touch: true
  belongs_to :guide
end

class Guide < ActiveRecord::Base
  has_many :site_publications
  has_many :sites, through: :site_publications
end


class BugTest < Minitest::Test
  def test_touch_callbacks
    site = Site.create!
    Guide.create!
    Guide.create!
    site_updated_at = site.updated_at
    site.guide_ids = [1, 2]

    assert site_updated_at < site.reload.updated_at, "Site#updated_at should have been updated when publication was created"

    site_updated_at = site.reload.updated_at
    site.guide_ids = [1]

    assert site_updated_at < site.reload.updated_at, "Site#updated_at should have been updated when publication was destroyed"
  end
end
```

### Expected behavior
It should touch the associated object on destroy. It doesn't seem to run any callbacks on destroy but it does when the join model (SitePublication in the test case) is created.

### Actual behavior
It does not touch the associated object on destroy.

### System configuration
**Rails version**: 4.2.7.1 (This is what I run locally, but it seems to affect master as well as seen in the test case above)

**Ruby version**: 2.3.3

**Comment by choncou** [comment]
@Linuus Did some digging in these docs: http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html

When you call `record.collection_ids=`, and are removing an item from the collection that existed by just not having it in the array, I believe that it is calling `delete` on the join table, removing it directly from the database, with no callbacks run. Therefore the record will not get updated.

In your example. This is the equivalent of the failing test:
```ruby
site.guides.delete(site.guides.last) # Same as `site.guide_ids = [1]`
```

But if instead you make it call `#destroy` on the collection item. The callbacks will be run and the record updated, which in turn will pass the test:
```ruby
site.guides.destroy(site.guides.last)
```

The cause of this unexpected behavior could be because of the `has_many :through` relationship, which changes the strategy of removing the item. And this is documented [here](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#module-ActiveRecord::Associations::ClassMethods-label-Delete+or+destroy-3F) if I understood correctly.

**Comment by choncou** [comment]
Update:
Also check out **collection=objects** header under `#has_many` [here: http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many)

**Comment by al2o3cr** [comment]
Amplifying @choncou - changing your association to `has_many :guides, through: :site_publications, dependent: :destroy` should do what you want. It makes the test case pass, at any rate. :)

**Comment by Linuus** [comment]
Thank you @choncou and @al2o3cr 

I'll try this when I get back to work this week and close this issue if it solves my problem :)

**Comment by Linuus** [comment]
Adding `dependent: :destroy` seems to fix the issue. It's a bit confusing IMO though, as it sound like the guide is destroyed :) But it works!

Thanks!
