### ISSUE TITLE
Referential integrity not disabled when a table name is shared across schemas (Postgresql)

### ISSUE THREAD

**Issue by jasonwinn** [rails/rails#30846]
### Steps to reproduce
1. Create a model with the same table name under two different database schemas.
   1. e.g. `User::Identity` (schema: user, table_name: identities) and `Account::Identity` (schema: account, table_name: identities)
       * These would live `under app/models/user/identity.rb` and `app/models/account/identity.rb`
2. Create fixtures:
   1. `test/fixtures/user/identities.yml`
   2. `test/fixtures/account/identities.yml`

3. run `rails test`

### Expected behavior
Referential integrity via `DISABLE TRIGGER ALL` should be triggered for `user.identities` and `account.identities`

Expected output in logs:
```
ALTER TABLE "user.identities" DISABLE TRIGGER ALL;ALTER TABLE "account.identities" DISABLE TRIGGER ALL;
```

### Actual behavior
Referential integrity is not disabled on _both tables_ because the schema names are not specified in the SQL being executed. E.g. The table "identities" is being referenced instead of "schema_name.identities".

The output will look like:
```
ALTER TABLE "identities" DISABLE TRIGGER ALL;ALTER TABLE "identities" DISABLE TRIGGER ALL;
```
  
### System configuration
**Rails version**:
5.1.4

**Ruby version**:
2.3.4

**Comment by pascalbetz** [comment]
Stumbled across this as well.

I can look into fixing this.

**Comment by pascalbetz** [comment]
Suggestions how to aproach this are welcome.

I could change 'data_source_sql' to return schema-prefixed names like so:

`sql = "SELECT n.nspname || '.' || c.relname FROM pg_class c LEFT JOIN pg_namespace n ON `

Good idea? It will break many tests for sure:-)

**Comment by pascalbetz** [comment]
I'd still be OK to handle this. Need some feedback though. See my Message above.

**Comment by mlt** [comment]
Can we re-open this?
@pascalbetz It is better to use `format('%I.%I', n.nspname, c.relname)` in #data_source_sql

**Comment by pascalbetz** [comment]
@mlt I can look into it, yes.

**Comment by pascalbetz** [comment]
@mlt I started a fix here: https://github.com/rails/rails/pull/35189

Mainly to see what breaks and what tests will fail and what it would take to fix them
WDYT? Is this the whole scope of the work? Could this change break existing Rails Apps?

**Comment by mlt** [comment]
That is a start! I don't see any CI tests on your PR though... and I'm really interested in seeing this fixed in 5.2.x.

How do you run tests? Somehow when I run `GEM=ar:postgresql ruby ci/travis.rb` (you'd want activerecord:postgresql with master) on my Windows machine I get tons of irrelevant failed tests even before proposed changes... and only a couple while using WSL with Debian, but still not clean.

I have a mixed feeling on how to approach the issue. The only thing that is broken is what is described in this issue. Whereas proposed changes to `#data_source_sql` affect many other functions.

That said, there might be a legit reason to return only names for (visible) tables... but with respect to *schema_search_path* in `config/database.yml`. That is not how it is done though.

Would it be better, at least for now, to introduce `#tables_with_schemas` or alike and call that while disabling referential integrity?

**Comment by pascalbetz** [comment]
I run the tests with `bundle exec rake test:postgresql TEST=test/cases/adapter_test.rb` (`TEST` param is optional).

I think globally changing the behaviour is probably a bad idea. I'll look into adding a param to switch behaviour (or adding a second method).

**Comment by pascalbetz** [comment]
Another stab: https://github.com/rails/rails/issues/30846

No tests added so far. I wonder if the `qualified_tables` method (naming OK?) should go into the abstract adapter? And if adding the `qualified:` key word to the postgres version of `data_source_sql` is OK (it kind of changes the interface, which was the same for all adapters shipped with rails, but does not break anything because it is keywords anyway.)

**Comment by mlt** [comment]
Uhm... have you seen my PR? It includes test case... all relevant tests (PG) pass alright but it failed on unrelated items... I think master had problems that time... that looks like were reverted. I'll rebase.

I would not touch abstract adapter. It is PG matter only...thus far...and we are not changing that method behavior for existing invocations. I would keep it contained.

I really think referential integrity shall be disabled in all schemas unconditionally. Otherwise, it is the only reason for me to explicitly name all schemas in *schema_search_path*... and I do not want to touch it just for referential integrity.

Also...I'm not 100% sure the order of tables returned matches that in *schema_search_path* as there is no explicit ordering in SQL.

**Comment by pascalbetz** [comment]
Nope, have not seen the PR.

I thin the `all` suffix is not really good (because it is more `include_schema` or similar) but other than that: 👍

**Comment by mlt** [comment]
I used to call it that way...until I changed its behavior. I would be okay with *all_with_schema*. Note that it does not just include schema name alongside with a table name, but does that for all schemas regardless of *schema_search_path*. Also I'm not sure whether I should exclude *pg_catalog* and *information_schema* only. I don't think at the time of call [other schemas I excluded](https://github.com/mlt/rails/commit/a54b4764dd248f71569a926ee7afb2e9ec81f096#diff-6e377cf054cb4121e6f207bd7c14b492R757) are populated at all. Though, perhaps, it is sequential scan on *pg_namespace* table due to its size no matter whether I use regex or direct comparison.

Let's wait until somebody else chimes in.

**Comment by mlt** [comment]
Can we reopen this?

**Comment by braindeaf** [comment]
Just seen this happen again on a new Rails 7 app using DatabaseCleaner. Is this likely to get picked up?

**Comment by braindeaf** [comment]
Happy to take a stab at it :)
