### ISSUE TITLE
Model ActiveRecord Relation Set as private constant

### ISSUE THREAD

**Issue by helmutrs** [rails/rails#30943]
### Steps to reproduce
countries = Country.where(name: 'Brazil')
(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
### Checking to make sure the query is valid
countries.is_a?(Country::ActiveRecord_Relation) 
the outcome should be true, since countries.class == Country::ActiveRecord_Relation
### Actual behavior
Tell us what happens instead
NameError: private constant #<Class:0x00007fed48f5b5a8>::ActiveRecord_Relation referenced
### System configuration
**Rails version**:
5.1.4
**Ruby version**:
2.4.2

**Comment by rafaelfranca** [comment]
That is expected. You are trying to access a private constant, this constant is not to be used in application.

**Comment by helmutrs** [comment]
That private constant was available on 4.2, have you change it on rails 5?

**Comment by rafaelfranca** [comment]
Yes, but it was always private API and should never be used.

**Comment by array42** [comment]
Something.first returns Something, while Something.all returns a Relation. If the following code depends on that information. I need to know the type and if it is a relation or not. I would say, there was a good reason to check that way what was returned. Where is the line between 'public API' and 'private API'? Something.is_a? is quite generic as a check! That should work. Don't you think? But well, let's write some ugly workaround code.

**Comment by array42** [comment]
In other words: Just telling 'mah private api' is not enough. What's the proposed way of doing things? No comment.

**Comment by rafaelfranca** [comment]
`something.is_a?(ActiveRecord::Relation)` is fine since `ActiveRecord::Relation` is part of the public API. `something.is_a?(Country::ActiveRecord_Relation)` is not fine because the fact that the `Country::ActiveRecord_Relation` exists is an implementation detail and not part of the public API. We may remove those classes without warning so we don't expect people to use it.

**Comment by PeterMozesMerl** [comment]
Unfortunately, I haven’t yet figured it out how to change this:

expect_any_instance_of(Message::ActiveRecord_Relation).to receive :update_all

**Comment by deepakmahakale** [comment]
Facing the same issue 

```ruby
expect_any_instance_of(Order::ActiveRecord_Relation)
  .to receive(:something)
```

**Comment by PeterMozesMerl** [comment]
I have `Model` and `Standby::Model` classes. The `Standby::Model` classes connect to a standby database server that should be read-only. Updates must be executed on the master server.

I used to test whether the `Standby::Model` relations ever receive `update_all`. They shouldn’t.

After this issue arose, I tried to find another solution.  Instead of a single line of code, I ended up lines like this: 

```ruby
expect(Standby::Model).to receive(:where).exactly(:twice).with(kind_of(String)).and_call_original
expect(Standby::Model).to receive(:xxx).and_call_original
expect(Standby::Model).to_not receive(:where)
```

```ruby
expect(Model).to receive(:where).with(id: model.id).and_return @models
expect(@models).to receive(:update_all).with(has_pending_notification: false).and_return nil
```

This may pass Code Climate/Rubocop/whatever guidelines because it’s explicit. Otherwise, it’s near to useless. 

It does not test whether the standby database receives an update through update_all. It only tests whether it does not happen after applying specific `.where` and scope calls in a particular order. It’s not what I need to test. 

The new spec would fail if I would change one line in the code, replacing `Standby::Model` to `Model`. But it would not catch any other `.update_all` call. In exchange, it would be unpredictable after refactoring the code. The `.with(kind_of(String))` is there for SQL, and the `:xxx` is a scope. As soon as I add another condition in the code, and I call `.update_all`, the test will pass. It won’t protect me at all.

Besides, chaining the `expect(xxx).to receive` on `.where` and scopes seemed buggy when I wrote the new spec.

It’s great to write explicit specs. It is unless we want to test something implicit. 

`expect_any_instance_of(Message::ActiveRecord_Relation).to receive :update_all` was perfect to make it sure the standby server won’t receive an update, until it stopped working. I didn’t find another way to test the same thing.

I understand the developers might change the name or the behaviour of the `Message::ActiveRecord_Relation` class. If they did, I could update my specs in no time. However, stubbing the return values of specific `.where` and scope calls is pointless in the case I tried to solve.

I used to use it in only two of 1,300 specs but it was essential.

**Comment by tambakoo** [comment]
Let to this party but `data.class.to_s.eql?("Program::ActiveRecord_Relation")` seems like an option.

**Comment by PeterMozesMerl** [comment]
> Let to this party but `data.class.to_s.eql?("Program::ActiveRecord_Relation")` seems like an option.

I would think that data.respond_to?(:select) or data.respond_to?(:each) is more Ruby/ducktyping code, hence I see Rafael’s point that one should not use it that way.

But I found no substitute for 
```ruby 
expect_any_instance_of(Message::ActiveRecord_Relation).to receive
```

**Comment by nbrustein** [comment]
If you want to, you can get around the private constraint with:

`MyActiveRecordClass.const_get(:ActiveRecord_Relation)`

(Nothing is REALLY private in ruby)

**Comment by chase439** [comment]
If your spec is specific and isolated enough, you can also do:

`expect_any_instance_of(ActiveRecord::Relation).to receive :blessing`

**Comment by decaruju** [comment]
You can also access Country::ActiveRecord_Relation with Country.all.class
