### ISSUE TITLE
Improving the README beginning section

### ISSUE THREAD

**Issue by ItsPugle** [rails/rails#31158]
The first section of README.md is litterally **a wall of text**. I wouldn't be surprised if Trump took inspiration from it.

I feel as though if it was shrunk (and humanised), new developers would be more encouraged to adapt to Rails.

EDIT: I mean this beginning section:
https://gist.github.com/ItsPugle/4100ce7ec7fbfe4a06cc5fac7d8d51e3

Yes. 6 paragraphs.

**Comment by matthewd** [comment]
The friendly front page is over at http://rubyonrails.org/

The repository readme is intended to be deeper, and at a certain point there's just a bunch of information to convey. Did you have a specific change in mind?

**Comment by ItsPugle** [comment]
Fair enough! I'm just thinking that it's a good six paragraphs of text, so maybe it's worth putting in a subtitle/catchline to break up some content & to possibly move the wall of text to different points throughout the README?

**Comment by rafaelfranca** [comment]
I know that over the years our attention spam is shorter but is that really a wall of text? It is 6 paragraphs because we need to explain 6 different things. I don't see how breaking that paragraphs with subtitles improve something, you still need to read the 6 subtitles to understand what is Rails, but now with less logical grouping. I'd understand the issue if that 6 paragraphs were just 1. I think the 6 paragraphs there is doing their job.

**Comment by rafaelfranca** [comment]
@dhh care to comment?

**Comment by ItsPugle** [comment]
@rafaelfranca I admit; I exaggerated when I say 'wall of text', but it's not something that can be dismissed in terms of length.

**Comment by dhh** [comment]
I don’t see any actionable suggestion here. “6 paragraphs in the beginning of the README is too much” is not a contribution of value. It’s a statement of fact combined with an opinion about Trump? Eh, okay.

**Comment by dhh** [comment]
If you want to open a PR that improves the writing by making it shorter while conveying the same information, have a go!
