### ISSUE TITLE
Memory leak through ActiveRecord::QueryCache

### ISSUE THREAD

**Issue by bogdan** [rails/rails#31175]
### Summary

`AR::QueryCache` has no limits. Heavy operations inside of HTTP request are not super common but they happen. Also the same problem occurs inside background jobs: memory is never released because of infinite cache growth.

### Steps to reproduce

Process a large amount of records in batches (expecting `posts` table to have 100k+ records):

``` ruby
ActiveRecord::QueryCache.cache do
  Post.find_each do |post|
    post.publish!
  end
end
```

### Expected behavior

`QueryCache` should have a limit on the number of entries that it can hold at a time.
When limit is reached, the last entry should be removed and new entry added.

Also it is a good idea to have a limit to the size of individual queries that can be cached. In other words: too large cache entries can be a problem too.

### Actual behavior

Infinite cache growth.

### System configuration

**Rails version**: 5.0

**Comment by matthewd** [comment]
Does #28867 solve this?

**Comment by bogdan** [comment]
That is a good attempt. The implementation looks very weird. 

Lets review the following scenario:

```
Post.belongs_to :author
  Post.find_each do |post|
    post.publish!
    Progress.unpublished_left(Post.unpublished.count)
  end
```

As I understood: any query inside the block will be cached (in my case `unpublished.count`). The patch only prevents batch query itself from being cached.

I would propose to flush query cache after each batch instead (via option or all the time). That would solve my case.


From other stand point: I would consider `QueryCache` limit as more ultimate solution that is not bounded to `AR::Batches`: it could reduce memory usage inside of general HTTP requests. That requires a research though...

**Comment by matthewd** [comment]
Writes already flush the cache :confused:

**Comment by bogdan** [comment]
It doesn't help in general case. It easily possible to have any nested request inside of `find_each` block that doesn't involve writing. Like:

``` ruby
csv = []
Post.find_each do |post|
  csv << [post.id, post.title, post.comments.count, post.comments.first.author.name].to_csv
end
```

**Comment by matthewd** [comment]
Sure.. but that's what the cache is *for*. I'm happy to explore more complex caching strategies as a possible new feature, but I don't think "the cache uses memory to store values while processing a request" is either a bug or a memory leak.

`find_each` flushing the cache seems much too aggressive to me; that makes it a dangerous method that could kill performance of an otherwise-simple page.

Maybe we could create an external gem that watches query cache activity, and then keeps track of what the hit rate would be under various eviction strategies -- that way we could then have some volunteer applications run with that, and we'd be in a better position to judge whether a more space-constrained policy can maintain the usefulness of the cache (and if so, which ones work best).

**Comment by bogdan** [comment]
I think `find_each` with `flush_cache` option is ideal solution: I don't think that current solution works even for 50% of cases. Real data exports require data from many tables where something is not preloaded (intentionally or by mistake). In my project, that has a lot of exports, this is the case for 90% of them.

> find_each flushing the cache seems much too aggressive to me; that makes it a dangerous method that could kill performance of an otherwise-simple page.

That doesn't seem to be a problem: requests with `find_each` are already heavy and cache doesn't make them super fast.
