### ISSUE TITLE
Inconsistent return value for to_sql with null conditions

### ISSUE THREAD

**Issue by tfwright** [rails/rails#31271]
This is probably an edge case but I thought the following behavior violates the principle of least surprise:

### Steps to reproduce

1. Call `.none.to_sql` on any standard AR model
2. Call `.where(id: []).to_sql`

### Expected behavior

I would expect the resulting strings to both be valid SQL.

### Actual behavior

```
[14] pry(#<Lists::ListPopulator>)> Person.where(id: []).to_sql
=> "SELECT \"people\".* FROM \"people\" WHERE 1=0"
[15] pry(#<Lists::ListPopulator>)> Person.none.to_sql
=> ""
```

but 

```
[9] pry(main)> Person.none.arel.where_sql
=> "WHERE (1=0)"
[10] pry(main)> Person.where(id: []).arel.where_sql
=> "WHERE 1=0"
``

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.3.3p222

**Comment by matthewd** [comment]
I think the distinction here is that `to_sql` is a relatively human-level interface, and is trying to act in that context, by indicating that what would actually happen if you called `.to_a` on that relation is: nothing. `none` outright disables a lot of relation operations, to save a pointless DB round-trip, whereas we aren't smart enough to infer that from a more localized impossibility ("where [false]").

If you crack the outer shell and dig in to the gooey insides, however, you can then see that the `none` relation also has a "fallback", in the form of an impossible where: at a certain point, it becomes simpler for us to just leave it to the DB's proper inference engine (especially if, say, it's in a subquery, so we're paying the round-trip either way).

In general, I'd say that if you care about this, you're probably doing something you don't want to anyway: `to_sql` provides a very close approximation of the SQL that would've been run, but's not the same as the real thing -- no bind variables, for example.

**Comment by tfwright** [comment]
Thanks for the response.

> In general, I'd say that if you care about this, you're probably doing something you don't want to anyway

Definitely agree with this. The issue arose because I encountered a bug in some preexisting code I was trying to build a feature on top of. The original author was using `to_sql` to manually construct an SQL to execute directly and had incorrectly tried to account for a case when the where clause would be blank by using `none`. I was able to "fix" the problem by switching from `none` to `where(id: [])`. I was just curious whether the different return values was intended behavior.

**Comment by collimarco** [comment]
`to_sql` is not an interface meant for humans: that is not documented in Rails and thus it is just a personal opinion.

`to_sql` must "return sql statement for the relation", as written in the docs.

**There are some edge cases where `to_sql` does not return valid SQL**: for example `Model.none.to_sql` does not return valid SQL. Instead it returns an **empty string**.

This may cause unexpected bugs like this:
https://github.com/afair/postgresql_cursor/issues/55

I think that this issue should be re-opened and one of the following solutions should be applied:

1. Fix `to_sql` so that it always return valid SQL
2. If the above solution is not practical, then **the documentation should be updated to warn about the edge cases where invalid SQL is returned**

**Comment by collimarco** [comment]
Why it's not using [WHERE 1 = 0](https://stackoverflow.com/questions/9140606/why-would-you-use-where-1-0-statement-in-sql) like in the other cases, instead of returning an empty string? 
Using two different behaviors (`WHERE 1 = 0` and `""`) is inconsistent and makes no sense.
