### ISSUE TITLE
What does rake rails:update do?

### ISSUE THREAD

**Issue by Arepo** [rails/rails#31377]
I'm trying to update our version of Rails (4.2.6) to the latest version, something I've never tried before, so suspect is going to be a painful journey with a lot of visits to SO. I started by following this guide at http://guides.rubyonrails.org/upgrading_ruby_on_rails.html

But the advice seems incomplete. I've started out following the advice to do one minor version at time, so switched to 4.2.7, ran bundle update, and then ran the test suite. So far so good - everything passed.

But the guide then instructs me to run rake rails:update, at which point everything goes haywire. The guide doesn't really say what the task does, and its description is "Update configs and some other initially generated files (or use just update:configs or update:bin)" - but the updates involved commenting out or deleting a bunch of config that the app relies on, and adding a bunch of lines with no sense of what they do. In a couple of cases it's obvious I would want to reject the change, but in many I don't have a deep enough understanding of the changes.

I'm also suspicious that there are so many suggested changes in a single patch update, which makes me wonder if it's essentially resetting these files to the state in which it would have generated them (I came onto the project after the app had been set up, and the people who did so no longer work on it, so I can't easily confirm this)

What's the best way to know what, if any of its suggestions to keep? And should I be running it after every step of the update, or just when tests break?

**Comment by AroSwift** [comment]
Updating Rails to 5.x can be painful especially for legacy projects. I recently did this on a massive legacy project from Rails 4.2.7 to 5.0.6 and would recommend the follow course of action:

1. Update Rails from 4.2.7 to 4.2.10
2. Run rake rails:update and chose to overwrite everything
3. Do a git compare to see the difference after (I love Git Desktop tool for this)
4. Selectively pick what you what from the new default configs and the old configs (this *can* be the painful part)
5. For the configuration files, checkout http://guides.rubyonrails.org/configuring.html to see what the new configurations do
6. You *should* not have to change the updates done to the bins folder from the rails:update task
7. Checkout http://railsdiff.org/ (generally this is helpful all throughout this process) to see what changes the previous developers might have missed
8. Run your tests — they *should* all pass because we are making small changes with the configs
9. Update to at least ruby 2.2.2 (I updated to ruby 2.4.x)
10. Fix any failing tests
11. Update Rails from 4.2.10 to 5.0.6. You could do each minor version if you want, but it was not necessary for me.
12. Updating rails will require some gems to be updated with bundle update. I used https://rubygems.org/ to update the gem to the most recent version in 2015 or the beginning of 2016 just for starters (to prevent unexplainable test failures). If the tests 
13. Use http://railsdiff.org/ again to see what initially generated files Rails 5.x produces and modify your existing configurations as needed
14. The javascript and/or css application.js file may need to be updated because of the gem changes
15. Run the tests again and fix errors and deprecation warnings as needed
16. Test the GUI
17. Repeat the appropriate steps for Rails 5.1.x

These are essentially what I used to upgrade, so hopefully they are helpful and answered your questions. Also, I highly recommend reading the Rails weblog release information (http://weblog.rubyonrails.org/releases/) so the update does not inadvertently and silently break something. Hopefully, the project already has good test coverage, if not, you might consider writing a few tests key to the function of the project before updating to Rails 5.x. Good luck!

**Comment by matthewd** [comment]
From the guide, where it advises you "do one minor version at time" (emphasis added):

> When changing Rails versions, it's best to move slowly, one minor version at a time, in order to make good use of the deprecation warnings. **Rails version numbers are in the form Major.Minor.Patch.** Major and Minor versions are allowed to make changes to the public API, so this may cause errors in your application. Patch versions only include bug fixes, and don't change any public API.

Updating to the latest patch release in a series (4.2.6 -> 4.2.10) is just a matter of changing the version and re-bundling; there is no further action required. 

`rake rails:update` is only intended to be run once per **minor** version: you'll first want to run it when you switch from 4.2.10 to 5.0.6.

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
