### ISSUE TITLE
ActiveStorage and Mongo

### ISSUE THREAD

**Issue by aledalgrande** [rails/rails#31408]
### Steps to reproduce

This is a possible feature request. I just installed Rails 5.2.0 beta2 and created a project with the `-O` option because I want to use Mongo instead of a relational database. What I noticed is that ActiveStorage, which I wanted to try out, was also disabled. I just saw that the gem is depending on ActiveRecord exclusively.

### Expected behavior

Create a project with `-O` but not with `--skip-active-storage` and have ActiveStorage available, while ActiveRecord is disabled.

### Actual behavior

ActiveRecord is not available.

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**Comment by rafaelfranca** [comment]
Active Storage only support Active Record and we have no plans to work in different ORMs support. Of course if you are willing to make Active Storage working with Mongo feel free to send PRs.

**Comment by aledalgrande** [comment]
Gotcha thanks @rafaelfranca

**Comment by rgaufman** [comment]
Has this changed at all?

I thought ActiveStorage would work with anything that uses ActiveModel, a bit like ActiveJob works with Sidekiq and others. But trying to use it immediately throws an active record migrations exception. Maybe it should be called ActiveRecordStorage as it is currently implemented 🙈

**Comment by georgeclaghorn** [comment]
No.

**Comment by zedtux** [comment]
@rafaelfranca Why is Active Storage supporting only Active Record and why don'y you have any plan to work with other ORMs support?
What is the reason behind as I fully agree with @rgaufman?

_Please avoid the "No." answer like @georgeclaghorn which is really useless_

**Comment by sikachu** [comment]
I understand the frustration.

However, from what I see, I think none of us are actually use ODM in our companies. Merging code into core comes with a maintenance burden. With us not really "eating our own dog food", I don't think it's a good idea for Active Storage to have ODM support as we probably do not know what we are doing (compared to, say, use job and queue with Resque backend)

However, I think we probably are open if anyone want to make a `activestorage-mongoid` or similar adapter, same as how Rails support multiple database backend. If someone would like to give a shot on making a gem, and maybe submit a few patches to make integration point easier, I really see no reason why core team wouldn't be okay with that.

**Comment by zedtux** [comment]
That sounds good ! Thank you @sikachu.

**Comment by rafaelfranca** [comment]
@sikachu said everything. We are happy to have a multi-adapter support for Active Storage but we are not going to do the work for it. If there is interest from a mongoid adapter I'd suggest people to try to implement it with the current API and as soon a new adapter takes traction we can change the framework to make new adapters easier. The reason for that is to avoid building an extension API that nobody will use.

**Comment by zedtux** [comment]
Thank you @rafaelfranca for the additional details

**Comment by rogerprz** [comment]
Any updates for ActiveStorage and mongoid?

**Comment by leoarnold** [comment]
@jafuentest In order to do this, one would need to disentangle ActiveStorage from ActiveRecord.

If we take for example a look at `ActiveStorage::Blob`, we find that it uses `ActiveRecord::Store`

https://github.com/rails/rails/blob/914caca2d31bd753f47f9168f2a375921d9e91cc/activestorage/app/models/active_storage/blob.rb#L42

and `ActiveRecord::Store` relies on `ActiveRecord::AttributeMethods::Serialization::ClassMethods#serialize`:
https://github.com/rails/rails/blob/914caca2d31bd753f47f9168f2a375921d9e91cc/activerecord/lib/active_record/store.rb#L105

which in turn uses `ActiveRecord::AttributeDecorators` and `ActiveRecord::ModelSchema::ClassMethods#reload_schema_from_cache`.

Therefore, `ActiveRecord::Store` cannot simply be included in a kind of "MongoidAdapter". One would have to find a different solution here. Note that the analyzers and variants make use of the `metadata` field as well.

Furthermore `ActiveStorage::Attached::Model` and `ActiveStorage::Attachment` use transaction callbacks like `after_create_commit` which are (AFAIK at time of writing) not available in Mongoid (but MongoDB 4 and the `mongo` driver at least support transactions).

And then, there are `ActiveRecord::Reflections` which also seem to be closely coupled to AR

https://github.com/rails/rails/blob/914caca2d31bd753f47f9168f2a375921d9e91cc/activestorage/lib/active_storage/attached/model.rb#L174-L181

If we can find suitable abstractions and indirections to decouple ActiveStorage from ActiveRecord, the rest seems pretty much a straightforward analogy to ActiveJob's queue adapter system:

https://github.com/rails/rails/blob/914caca2d31bd753f47f9168f2a375921d9e91cc/activejob/lib/active_job/queue_adapters.rb#L113-L141

**Comment by rgaufman** [comment]
Any solution for this?

**Comment by thomaswitt** [comment]
@aledalgrande FYI: I've just opened a PR that makes exactly this possible: rails/rails#57537. It lets Active Storage run on a non–Active Record (Active Model) backend, with a working DynamoDB adapter as proof. Active Record stays the unchanged default. Discussion: rails/rails#57558 — feedback very welcome.
