### ISSUE TITLE
Rails 5.1.4 Belongs_to validation

### ISSUE THREAD

**Issue by adrian282** [rails/rails#31437]
If child association will fail on its validation rules then I receive ActiveRecord::NotNullViolation after parent save

```
class Child
  validates :name, presence: true, length: { in: 2..4 }
end

class Parent 
  belongs_to :Child
end

parent = Parent.new
parent.child = Child.new ( name: "too long name")
parent.save
```

In this case, belongs_to validation doesn't work

**Comment by meinac** [comment]
I tried but couldn't reproduce the issue, can you please try to provide an executable reproduction script by using the information given in [this](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) page?

**Comment by adrian282** [comment]
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.4"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :companies, force: true do |t|
    t.string :name
  end

  create_table :owners, force: true do |t|
    t.references :company, foreign_key: true, :null => false
  end
end

class Company < ActiveRecord::Base
  validates :name, presence: true, length: { in: 2..4 }
end

class Owner < ActiveRecord::Base
  belongs_to :company
end

class BugTest < Minitest::Test
  def test_association_stuff
    owner = Owner.new
    owner.company = Company.new( { name: "too long name" } )
    owner.save
  end
end

**Comment by meinac** [comment]
There is no issue with rails. If you try with `autosave` option in your owner model it works.

```ruby
class Owner < ActiveRecord::Base
  belongs_to :company, autosave: true
end
```

But why? The thing is if you don't set `autosave` to **true** then Active Record does not try to save the company relation and since you have not null constraint in your database it raises the exception. What happens when you set `autosave` to **true** is, Active Record tries to save relation but first checks the validations and because of the validation error it rolls back.

**Comment by adrian282** [comment]
I can't agree with your answer...
If Company model data will be correct (name length in 2..4) then company will be saved (without this option).
**belongs_to** property (without optional flag) should care that relationship exists, without raising exception on database level!
According to documentatin, **autosave** flag is for different purpose (for saving in update action).

**Comment by meinac** [comment]
> AutosaveAssociation is a module that takes care of automatically saving associated records when their parent is saved. In addition to saving, it also destroys any associated records that were marked for destruction.

This is from the documentation, which means no matter whether its an update or insert or delete.

But here I see that there is an issue with the rails in autosave module. Since the owner belongs to company while saving owner the company should be saved as well so this is what Active Record is trying to do. By default rails saves associated records if they are new records even though the autosave option is not set, kind of an implicit autosave.

If you want a workaround you can set `autosave` to **true** till this issue is getting fixed.

**Comment by adrian282** [comment]
Without `autosave` flag company is also saved (as you said - implicit save).
In my opinion autosave = true should be as default option. When autosave = false, relationship shouldnt be saved.

I really don't know why (without autosave option) model is not validated (because autosave is implicitly)?

**Comment by meinac** [comment]
With or without autosave the parent model is validated. The only difference is when autosave option set as true, the validation failures rollback the transaction. If it's not set, it just ignores the validation error on parent model and tries to save object.

As far as I see from the code and test cases, this was done in purpose which does not make sense to me. If the relation is `belongs_to`, parent record validation should rollback the entire transaction, otherwise it leads to data integrity issues. In your case since you have not null constraint in database layer, database saves your life but the application itself should have this protection as well.

I'll try to fix this behaviour but I can't guarantee it will be merged since I don't know what the Rails team will think and this is kind of a breaking change.

**Comment by adrian282** [comment]
Yes, I fully agreed with you. Database exceptions should be the last way for keeping data consistency :)
Thanks for your support. Please update this topic if you will have any news about this.

**Comment by adrian282** [comment]
any news?

**Comment by adrian282** [comment]
and?

**Comment by meinac** [comment]
Sorry I was on vacation therefore couldn't find time to have a look at this. Maybe someone from Rails core team can give some opinion about the issue.
\cc @rafaelfranca

**Comment by adrian282** [comment]
and what do Rails team think?
We spent some time to investigate and will be stupid to allow to this subject `die`

**Comment by adrian282** [comment]
and what do Rails team think?

**Comment by victorhazbun** [comment]
This is not an issue. Please close.

**Comment by adrian282** [comment]
not issue, really? Please explain.

**Comment by adrian282** [comment]
@victorhazbun   and ??

**Comment by adrian282** [comment]
@victorhazbun  and ?

**Comment by adrian282** [comment]
@victorhazbun @meinac 
and ??

**Comment by rafaelfranca** [comment]
Please can you avoid bumping the issue. Rails is made by volunteers and they usually work in work they are interested. If this issue is so important to you please do investigate a try to open a pull request with the fix.

**Comment by adrian282** [comment]
I asked why not issue, so is it or not?

One volunteer confirmed that sth is wrong and why should I forget about it?

**Comment by etipton** [comment]
I believe I was just bitten by this bug with Rails 6.0.3.3 - here's the essence of my situation:

```ruby
class Message < ApplicationRecord
  belongs_to :sender, polymorphic: true
end

class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }
end

Message.create!(sender: User.new(username: "[a username that already exists in the db]"))
```

result:
```irb
...
D, [2021-02-07T11:40:15.449510 #16528] DEBUG -- :    (0.2ms)  BEGIN
D, [2021-02-07T11:40:15.450239 #16528] DEBUG -- :   User Exists? (0.6ms)  SELECT 1 AS one FROM "users" WHERE LOWER("users"."username") = LOWER($1) LIMIT $2  [["username", "[a username that already exists in the db]"], ["LIMIT", 1]]
D, [2021-02-07T11:40:15.452622 #16528] DEBUG -- :   Message Create (0.6ms)  INSERT INTO "messages" ("sender_type", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["sender_type", "User"], ["created_at", "2021-02-07 16:40:15.451397"], ["updated_at", "2021-02-07 16:40:15.451397"]]
D, [2021-02-07T11:40:15.453629 #16528] DEBUG -- :    (0.6ms)  COMMIT
=> #<Message id: 32, sender_type: "User", sender_id: nil ...>
```

If / when I get time I'll try to provide an example app or try to dig in myself.
