### ISSUE TITLE
simple_format bug with input like "a <) b"

### ISSUE THREAD

**Issue by henrik** [rails/rails#31443]
Saw some borked user input. Minimal repro:

```
>> Rails.version
=> "5.1.4"
>> puts helper.simple_format("a < b")
<p>a &lt; b</p>
# As expected.
>> puts helper.simple_format("a ) b")
<p>a ) b</p>
# As expected.
>> puts helper.simple_format("a <) b")
<p>a </p>
# Not expected! Expected this: a &lt;) b

**Comment by eileencodes** [comment]
Hey @henrik! Thanks for the report. I tried this in a console linked to the master branch and saw the same thing. Do you know the last version this was working correctly on?

**Comment by henrik** [comment]
Hi! Thank you for verifying that. I’m not sure whether it has worked previously. I saw the issue on Rails 4.2 when a customer reported it, and then could also see it on 5.

**Comment by mftaff** [comment]
@eileencodes @henrik I am looking to get my feet wet with my first open source contribution. Would I be able to have a shot at fixing this?
Thanks!

**Comment by eileencodes** [comment]
@mftaff yes, I think it's worth fixing. I tested this in the console in 4.1 and 4.2. It was present in 4.2, but not in 4.1. Looking at changes in 4.2 is probably a good place to start. Update this issue if you get stuck 😸

**Comment by mftaff** [comment]
@eileencodes Here is what I have found out so far. I temporarily added to the tests those examples used above, and when running the one that failed (ie: `simple_format("a <) b")`) got these results:

Here is an excerpt of `simple_format`, (note I added `puts` before and after calling `sanitize`:
```
def simple_format(text, html_options = {}, options = {})
  ...
  puts "\ntext before calling sanitize: #{text}"
  text = sanitize(text) if options.fetch(:sanitize, true)
  puts "text after calling sanitize:  #{text}"
  ...
end
```
And here is an excerpt from the console after running the test for this method:

```
Run options: -n test_simple_format --seed 46889
...
text before calling sanitize: a <) b
text after calling sanitize:  a 
...
Failure:
TextHelperTest#test_simple_format [test/template/text_helper_test.rb:49]:
Expected: "<p>a &lt;) b</p>"
  Actual: "<p>a </p>"
...
Finished in 0.031342s, 31.9058 runs/s, 95.7173 assertions/s.
1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
```
It seems that the sanitize method (which seems to really be calling sanitize from another repo: [rails-html-sanitizer](https://github.com/rails/rails-html-sanitizer/blob/7aea595ed0c9887b09484cd46435d1af165f24ef/lib/rails/html/sanitizer.rb#L116)) is seeing the `<)` part of the string as an unrecognized html element and therefore removing it. I tested this with other things (e.g <jook>, <fake_element, etc) and they all responded in the same way.

My conclusion is that the issue is coming from [rails-html-sanitizer](https://github.com/rails/rails-html-sanitizer/) which means this may not be the right place to work on this bug. Am I correct in thinking that? and if yes, do you think, I should head over to that repo and try and fix the issue there? Or do you think I missed something else entirely?

Thanks in advance for the help/advice 😃

**Comment by eileencodes** [comment]
@mftaff that does make sense. In Rails 4.2 we not only moved code out of rails and into rails-html-sanitizer and rails-dom-testing respectively, but we changed the underlying code that handles that to use loofah and nokogiri. Your investigation definitely points to rails-html-sanitizer being the culprit of the change.

**Comment by matthewd** [comment]
> seeing the `<)` part of the string as an unrecognized html element and therefore removing it

Yeah, that sounds like what's happening. This might just be a difference in how Nokogiri (via loofah, via rails-html-sanitizer) parses the string, that we have to live with.

`simple_format`'s documentation doesn't really make it clear, but it expects to receive pseudo-HTML input (which it then enhances with extra newline handling, etc); I think we treat invalid HTML as undefined behaviour.

**Comment by yskkin** [comment]
If `simple_format` only accepts valid html, for example, listing following user input into a page with autolink and sanitize feature, what is a recommended way?

```
see here (>_<)  https://example.com
```

I'm using

```
<%= simple_format(Rinku.auto_link(content, :all)) %>
```

this and saw this problem.
