### ISSUE TITLE
link_to ... data: {confirm: "Are you sure?"} not worked in Firefox 57

### ISSUE THREAD

**Issue by zw963** [rails/rails#31474]
All those code which use `data: {confirm: "Are you sure?"} not worked in firefox 57.

I am not sure this is a bug for Rails or Firefox, But, it just worked fine in chrome.

in firefox 57 (quantium), could not see any special error log in js console.

Thanks.

**Comment by y-yagi** [comment]
What is "not worked"? Do not show confirmation? Or, do not the reaction when click submit? 
They are seem working properly in my environment.(Firefox: 57.0.1).

Is this issue reproduce with newly application? And, if you use some add-ons, please disable those.

**Comment by zw963** [comment]
@y-yagi , weird,  the issue is don't do the reaction when click the submit.

I use linux 64-bit system (openSUSE), firefox 57.0.2

I open several add-ons in my browser, i will try it later.

thanks.

**Comment by eileencodes** [comment]
I tested this on Rails master with Firefox 57.0.1. It says that it's up to date and since I don't think the data-confirm code changed recently I don't think this is a Rails bug. If you can reproduce in a new application please provide the application, version of Rails, and version of FF and I'll reopen. Thanks!

**Comment by zw963** [comment]
Sorry for late reply.
This function is broken by following addon-ons, if disable, it worked now.

https://addons.mozilla.org/en-US/firefox/addon/enable-rightclick-and-copy/

If any have trouble with this, maybe can help. thanks
