### ISSUE TITLE
ActiveStorage doesn't respect `gravity` variant

### ISSUE THREAD

**Issue by kieraneglin** [rails/rails#31518]
### Steps to reproduce

Given a Rails `5.2.0beta2` app using `ActiveStorage` and `mini_magick`, attach a **rectangular** image to a model and then call it with `<image>.variant(thumbnail: '100x100^', gravity: 'center',  extent: '100x100')`

### Expected behavior
The image returned is 100px square with the excess cropped and the image centered

(centered cropping is described [here](http://www.imagemagick.org/Usage/thumbnails/#cut) and `gravity` is shown to work with `mini_magick` [here](https://github.com/minimagick/minimagick/issues/137#issuecomment-17471822))

### Actual behavior
The image returned is 100px square with excess cropped, however the image is anchored on the upper left

### System configuration
**Rails version**: 5.2.0beta2

**Ruby version**: 2.4.2

**mini_magick version:** 4.8.0

**ImageMagick version:** 7.0.7-15

**Comment by mrreynolds** [comment]
Looks like it's because the ActiveStorage blob transformations get applied sequentially. For `gravity` to have an effect on `resize`, MiniMagick expects those transformations as a block argument for [`combine_options`](http://www.rubydoc.info/github/minimagick/minimagick/MiniMagick/Image#combine_options-instance_method). In the current version of ActiveStorage I don't see how that's possible.

See also https://stackoverflow.com/a/20005154.

**Comment by mrreynolds** [comment]
I just added support for `combine_options` with this PR: #31544.

**Comment by rgbskills** [comment]
If this is added then how do I center crop in mage with combined_options?

**Comment by gogogoaldi** [comment]
Example: 
<%= image_tag user.avatar.variant(combine_options: {thumbnail: "500x500^", gravity: "center", extent: "500x300"}) %>

**Comment by mayeco** [comment]
This should be updated in the documentation.

https://github.com/rails/rails/blob/5-2-0/activestorage/app/models/active_storage/variant.rb
