### ISSUE TITLE
undefined method `purge' for nil:NilClass

### ISSUE THREAD

**Issue by atstockland** [rails/rails#31626]
### Steps to reproduce
I'm not exactly sure how I achieved this...somehow I have a user referencing a blob that no longer exists.  I apologize that I'm not able to contribute more towards a solution to this...I'm still wrapping my brain around how ActiveStorage works.  But, I thought this scenario worthy of sharing.

     user = User.find 155
     user.avatar.attached? ---- returns true
     user.avatar.purge ---- returns NoMethodError: undefined method `purge' for nil:NilClass
  
      ActiveStorage::Blob Load (0.3ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1  [["id", 739]]

      ActiveStorage::Blob.find(739) ---- Couldn't find
      ActiveStorage::Attachment.where(record_type: 'User', record_id: 155) --- returns one record also associated with blob 739

     user.avatar = nil  ---- Failed to save the new associated avatar_attachment

     ActiveStorage::Attachment.where(record_type: 'User', record_id: 155).take.destroy --- back in action

### Expected behavior
It seems that purge should destroy associated ActiveStorage::Blob and ActiveStorage::Attachment...even in the scenario I encountered.

### Actual behavior
purge fails because ActiveStorage::Blob no longer exists....somehow.

### System configuration
**Rails version**:
Rails 5.2.0.beta2

**Ruby version**:
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]

**Comment by mbodlund** [comment]
I have encountered the same behavior. Somehow there are blobs going missing.

Using Ruby 2.4.2, Rails 5.2.0.beta2,active_storage.service = :local and Sidekiq 5.0.5

**Comment by cassiopagnoncelli** [comment]
Same pain here. Development goes smooth, but fails on production.

**Comment by eileencodes** [comment]
@georgeclaghorn have you experienced this in production at all? Any insight as to what the problem may be?

**Comment by georgeclaghorn** [comment]
We see a variation of this occasionally, where a record that should have a blob appears not to:

```
NoMethodError: undefined method `representation' for #<Upload:0x00000000024b4db0>
```

When I check in a console, the record does have an associated blob. I haven’t had time to dig deeper yet.

**Comment by georgeclaghorn** [comment]
On further review, I can attribute the production issue I mentioned to replication lag, so it’s not related. Can you search your app’s logs to determine whether any of the missing blobs were deleted independently of their attachments?

I’m removing this from the 5.2.0 milestone pending evidence of an Active Storage bug.

**Comment by mbodlund** [comment]
I have tested a lot to try to reproduce the behaviour but I can't. The only reason I can think of was that I had two rails 5.2 test apps running on the same host sharing one redis db through sidekiq. I didn't configure anything on the redis part which led me to think this was the problem. Both used db 0. The issue I saw was that I suddenly had fewer blobs then attachments. So when I tried to destroy the record associated with these attachments/blobs I got errors due to the blob missing.

**Comment by NoNonsense126** [comment]
I had the same issue due to a misunderstanding of the edgeguides. A silly mistake, but maybe it will help.

Assuming a model, with a file attachment,
`
def create
  @model = Model.new(model_strong_params)
  if @model.save
    @model.file.attach(params[:file]) // Reattaches file to the model
   //other code
  else
    //other code
  end
end

def model_strong_params
  params.require(:model).permit(:file)
end
`

I believe what happens is that it tries to reattach the file attachment, while purging the previous one, deleting the blob. The attachment still works, but the blob is no longer there.

**Comment by fshin1988** [comment]
I had the same issue in production and I was able to reproduce the issue in development.
My case is the following.
1. An instance of user model has one attachment.
2. The instance saves changes but a validation error happens.
3. At that time, new blob is created and existing blob is destroyed by **ActiveStorage::PurgeJob**, but new attachment is not created because of validation error.
4. Existing attachment has association with the existing blob but there is no existing blob, so the problem happens.

This is my user model.
```
class User < ApplicationRecord
  has_one_attached :avatar

  validates :username, presence: true, length: { in: 1..20 }
end
```

This is the application log when reproducing the problem.
```
Started POST "/rails/active_storage/direct_uploads" for 127.0.0.1 at 2018-01-31 21:59:26 +0900
[...]
   (0.3ms)  BEGIN
  ActiveStorage::Blob Create (0.5ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "byte_size", "checksum", "created_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["key", "eub75YWHrKKPKTu834JfaGeG"], ["filename", "second_image.jpg"], ["content_type", "image/jpeg"], ["byte_size", 5757627], ["checksum", "rQ+ElHSCqJ1I6YBnUJvl4g=="], ["created_at", "2018-01-31 12:59:26.460639"]]
   (2.3ms)  COMMIT
[...]

Started PUT "/users" for 127.0.0.1 at 2018-01-31 21:59:26 +0900
[...]
   (0.4ms)  BEGIN
  ActiveStorage::Attachment Load (0.6ms)  SELECT  "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 1], ["record_type", "User"], ["name", "avatar"], ["LIMIT", 1]]
  ActiveStorage::Blob Load (0.5ms)  SELECT  "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 12], ["LIMIT", 1]]
  ActiveStorage::Attachment Destroy (0.5ms)  DELETE FROM "active_storage_attachments" WHERE "active_storage_attachments"."id" = $1  [["id", 12]]
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ActiveStorage::Blob Load (0.4ms)  SELECT  "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 13], ["LIMIT", 1]]
  ActiveStorage::Attachment Create (0.5ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "avatar"], ["record_type", "User"], ["record_id", 1], ["blob_id", 13], ["created_at", "2018-01-31 12:59:26.881881"]]
[ActiveJob] Enqueued ActiveStorage::PurgeJob (Job ID: f2790361-5edf-46f7-a918-6672710a788e) to Sidekiq(default) with arguments: #<GlobalID:0x00007fc79d8e8a70 @uri=#<URI::GID gid://jinro-rails/ActiveStorage::Blob/12>>
  User Exists (0.7ms)  SELECT  1 AS one FROM "users" WHERE "users"."username" = $1 AND "users"."id" != $2 LIMIT $3  [["username", "veeeeeeeeeeeeeeeeeeeeeeeeeeeeerylongusername"], ["id", 1], ["LIMIT", 1]]
   (0.2ms)  ROLLBACK
[...]
Completed 401 Unauthorized in 247ms (ActiveRecord: 6.0ms)
```

**Comment by hanyelbanna** [comment]
For me user.avatar.purge not destroy the actual resource files on local (Mac). Do you know a reason for that?

**Comment by georgeclaghorn** [comment]
There are a few issues here.

@NoNonsense126, I’m not sure why that wouldn’t work, ignoring that it’s not ideal. A blob should be created and attached to the model, then purged and replaced with a new blob. Please open a new issue and share a minimal app that reproduces the problem if you’re still experiencing it.

@fshin1988, I suspect you’re doing something like `user.update!(avatar: params[:avatar])`, which is undocumented and unsupported. Use the `attach` API (e.g. `user.avatar.attach(params[:avatar])`) for existing records.
