### ISSUE TITLE
Upcoming release: mysql2 gem 0.5.0

### ISSUE THREAD

**Issue by sodabrew** [rails/rails#31636]
Hello! When I last released a new "major" version of the mysql2 gem, there was some widespread grumbling as users were able to update their gems locally without constraints, but at runtime received errors because the gem version is specific in the mysql2 adapter https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L6 

I am planning a mysql2 0.5 release this quarter. It will be fully compatible with 0.4.x. Is there something I can do to help avoid the user pain this time around? Would calling the new version 1.0.0 help by allowing you to drop the requirement from within the adapter and instead put it into a gemspec, as seen at https://github.com/rails/rails/blob/master/Gemfile#L131 ?

Or is this simply an understood-enough situation that is common to all of the connection adapters, as seen by the gem versioning in many of https://github.com/rails/rails/tree/master/activerecord/lib/active_record/connection_adapters and I shouldn't worry about it.

Could I nudge Rails 5.2.0 to ship with `gem "mysql2", "~> 0.5.0"` at the appropriate time?

**Comment by matthewd** [comment]
As you note, 0.x versions are generally considered to be major, so we default to a more restrictive upper version. I'd say we're happy to accept your guidance on what the upper should be, based on which future versions you're happy to commit to not changing things we use in.

Given the gem's maturity and widespread use, bumping to 1.0.0 does seem like a potentially good idea, just because most people would then assume the API's going to be stable until 2.0. Granted, there's some irony in making a Very Major bump just to assert that nothing's changing :sweat_smile:. Alternatively, just declaring in the README that the API is stable as of 0.4, and any future incompatible change will be 1.0, would give the same result: we (and others) could use `>= 0.4.4, < 1.0`.

If you're not ready to make that sort of commitment, though, we'll gladly merge and backport a PR that expands the constraint to `>= 0.4.4, < 0.6`, say. (Right now, if you like; if done early enough before a 0.5 release, it might at least reduce the burden to "you need to bump AR too" -- at least for people running a supported release series.)

The adapters do all need an explicit requirement, because they each expect a given API version -- older versions are known not to work, and future versions [beyond any API commitments from maintainers] are unknowable. We *could* switch to a purely `>=` constraint, only excluding the known-bad old versions... but that just inverts the problem to one where your future release breaks applications because of an API change, and that's potentially a much more subtle breakage.

(We can't use a real gemspec requirement, because that'd mean everyone had to install libraries for all three of our supported adapters. Unfortunately Rubygems doesn't support a "it doesn't have to be here, but if it is, it needs to be this version" constraint, which, while imperfect, would give us a better approximation of desirable behaviour.)
