### ISSUE TITLE
Default redirect status of 301 Moved Permanently for routes

### ISSUE THREAD

**Issue by Umofomia** [rails/rails#31664]
### Background

While investigating some issues with a project we're working on, we came to the realization that the default HTTP status code for redirects generated by the `redirect` method in `routes.rb` is `301 Moved Permanently`:
* https://github.com/rails/rails/blob/v5.1.4/actionpack/lib/action_dispatch/routing/redirection.rb#L187

While this behavior [is documented](http://guides.rubyonrails.org/routing.html#redirection), that note is easy to overlook or forget about, and the behavior is rather surprising to us for a couple reasons:

* It's different from the default status that `redirect_to` returns in controllers, which is `302 Found`:
  * https://github.com/rails/rails/blob/v5.1.4/actionpack/lib/action_controller/metal/redirecting.rb#L118
* It doesn't seem like a "safe" default because many browsers effectively cache 301 redirects forever unless you can get the user to clear their browser cache. The following links go into more detail about why 301 redirects are often problematic:
  * [301 Redirects: The Horror That Cannot Be Uncached](http://getluky.net/2010/12/14/301-redirects-cannot-be-undon/)
  * [thomasrutter's answer to "How long do browsers cache HTTP 301s?"
on StackOverflow](https://stackoverflow.com/a/21396547/582414)

It appears that this behavior has always been the case since the `redirect` method was first introduced in Rails 3.

With respect to the issues that initiated this discovery -- because we had effectively set up a bunch of permanent 301 redirects in our routes, it will require much more effort for us to change or undo many of those redirects. In the case where some to these redirects went to URLs we don't have direct control over, it will be difficult for us to change them. Quoting the StackOverflow link I mentioned previously:
> If you don't have control over the site where the previous redirect target went to, then you are outta luck. Try and beg the site owner to redirect back to you.

### Request for Consideration

* Is there a reason why `301 Moved Permanently` was chosen as the default HTTP status over `302 Found`?
* Even though it would be a change to long-standing behavior, would you consider changing the default to 302, which in our opinion would be a "safer" default?

Before opening this issue I tried to see if anyone else ever raised a similar concern in the past and could not find anything similar, which is a bit surprising to me since the current default behavior has permanent effects. For that reason I'm wondering whether I'm missing something?

**Comment by Umofomia** [comment]
I will also note that commit message for the documentation of the 301 behavior also seems to indicate that the behavior seemed surprising to the committer as well, which is why the committer added the note:
https://github.com/rails/rails/commit/d6c7185d77158caee933e84b247e37bb6a67bf58#diff-e6f605812b6d75488fe435bd19acf354
> I had to try out myself to realize that it's 301, so this should be helpful to everyone.

**Comment by dwightwatson** [comment]
I would have thought that this was a sane default. If I was registering a redirect in my routes file it would generally be for legacy routes that I want to maintain for existing bookmarks or inbound links. They're generally static and meant to be permanent. If I wanted them to be temporary I think it makes sense that it should be done on an opt-in basis.

**Comment by utilum** [comment]
This seems misdirected, and worth changing, and I'd be happy to submit a patch.

**Comment by masonhale** [comment]
+1 default should be temporary. I've been stung by this default too. A default should not create a permanently irreversible situation. For years people though permanent redirects were "better" for SEO/Google juice reasons, but today those reasons don't hold water. 

- https://moz.com/blog/301-redirection-rules-for-seo
- https://searchengineland.com/google-no-pagerank-dilution-using-301-302-30x-redirects-anymore-254608

**Comment by rafaelfranca** [comment]
This is going to cause a huge breaking change if people is expecting the default to be 301. Maybe we should introduce a new `temporary_redirect` helper? Or we could require the `status` to be always defined.

@matthewd thoughts?

**Comment by eugeneius** [comment]
How about using a [new framework default](https://github.com/rails/rails/blob/8c42d1b6e537a50ae085a8669e604fca1729d56b/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_5_2.rb.tt)?

**Comment by matthewd** [comment]
Personally I think the current behaviour makes sense: if it's defined at the route level, I expect it to be as much of a forward-looking statement as any other cacheable response.

@rafaelfranca if you want to change it, though, I doubt it'd really be a big deal for people to start returning 302s instead of 301s -- by my same logic, the route's not going to change, so it doesn't matter if people keep requesting it. A config option could also work to grandfather existing apps; even for the rare app that might care, the chances of them encountering a 3rd party gem that also cares in the other direction seem vanishingly small.

**Comment by masonhale** [comment]
I would like to add that developers can use redirects for lots of different reasons. Assuming how any given feature is going to be used can be a dangerous game.

In my case, our company acquired another company. Both products provide hosted websites on customer-specific subdomains, but with different top-level domains. 

Post acquisition, these sites would be transfered one-by-one as customers where migrated and ready. The transfer itself was controlled at the DNS level (mapping the specific subdomain at the old TLD to a Rails app configured to support subdomains on both the old and new TLD). 

Those requests would hit our server still using the old top-level domain, so we initially we used a route-based rule to map requests for the old top-level-domain to a request for the new top-level-domain. 

Where we hit a snag is that customers sometimes change their minds. After making this change we had multiple customers give the go ahead the transfer their site from the old system to the new system. That resulted in a DNS change, which resulted in a 301-redirect to the new domain. 

Unfortunately, in a few cases, we had customers that "forgot something" or otherwise needed to get back to their old websites. At first we thought, no problem, we'll just remove the DNS rule and everything will go back to how it was before the redirect. But it didn't. Especially for the customers who wanted to go back to their old website, they simple could not do it, even after the DNS change. The 301 redirect was permanently cached in their browsers. We were able to work with those customer contacts to get them to clear their browser cache or use another browser, but this was fraught with problems because they are not very technical users. DNS is a mystery to them. It made us look bad. And compounding that any visitors to their website during this transition were similarly "stuck" redirecting to a new-partially migrated site.

So after doing a bit more research, we found that (1) Rails route redirects are 301's, unlike the controller level "redirect_to" method which is a 302 (which was a surprise), (2) 301 Redirects are more permanent than we thought and can in fact be almost impossible to reverse, and (3) in most cases the previously perceived SEO benefits of 301 redirects over 302 redirects simply do not exist anymore.

In my opinion, using 301 redirects in routes by default is setting a trap for developers to step into. It's an extremely difficult problem to fix once you run into it. And it is deceptively easy to run into this one by accident.

That said, I also understand the need to not change anything that has previously been a default. In this case, the danger of switching from 301 to 302 is low. It could result in additional requests if a developer relies on most clients to have cached the 301. But clients get updated and caches get cleared all the time, so it's not like one can *assume* your redirect is going to be cached. It's not something you can rely on anyway.

But conversely, the idea that a default setting would create a situation where 100's of thousands of end users need to clear their browser cache, or else they can't reach your site anymore? That's a huge problem.

Just my 2 cents. I hope adding a bit more first-hand, real-world experience helps explain why I believe the current 301 redirect default is a real problem and poses a real danger to developers.

Thank you for your consideration.
