### ISSUE TITLE
link_to url helper has unexpected behavior when an element of the array is nil

### ISSUE THREAD

**Issue by ardavis** [rails/rails#31716]
## Models
    class Source < ApplicationRecord
      has_many :subscriptions
    end
 
    class Subscription < ApplicationRecord
      belongs_to :source
    end

    ## Controllers
    class SourcesController < ApplicationRecord
      def destroy
        # Find Source and destroy it
      end
    end

    class SubscriptionsController < ApplicationRecord
      def show
        @source = Source.find(params[:source_id])
        @subscription = nil # Some logic that results in nil for whatever reason
      end

      def destroy
        # Find Subscription and destroy it
      end
    end

    ## Routes
    resources :sources do
      resources :subscriptions
    end

    ## View for Source#show
    # Using the shortcut to generate the URL instead of source_subscription_path(@source, @subscription)
    = link_to 'Unsubscribe', [@source, @subscription], method: :delete

### Expected behavior

Generally, I would expect the `link_to` above to call `Subscriptions#destroy`. However, a bug in my code led to one of the elements being `nil`. I would have expected the `link_to` to raise an error if any element of the array was `nil`

### Actual behavior

When the link is clicked, `Sources#destroy` gets called instead since the `link_to` uses this to generate the URL: `[@source, nil]`

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.5.0p0

**Comment by htanata** [comment]
This behavior for polymorphic_url is intentional, although it has changed back and forth a few times.

Here's the sequence:

1. Ignore nil: 94d6716324126028b89dde886f160474049b1b0c
2. Raise ArgumentError: dece005f0a8aa1f4210e381efb429eca5d793d91
3. Ignore nil (current): #16755

Given this scenario, I think raising ArgumentError is safer and less surprising since ignoring nil could cause data to be deleted.

What do you think, @tenderlove?
