### ISSUE TITLE
Rollback transactions without exceptions? Deprecate ActiveRecord::Transaction?

### ISSUE THREAD

**Issue by iGEL** [rails/rails#31760]
I have two - possibly controversial - issues with transaction and I wanted to gather some feedback before submitting patches.

## Deprecate ActiveRecord::Transaction

I'm not entirely happy, that you can call `.transaction` directly on a model, but it happens to affect all other models sharing the same database connection within the transaction block. I just tried to call `User.connection.transaction` (using Postgres) and it seems to work exactly like I expect it to. This way would make the actual behavior a lot clearer in my not so humble opinion.

To repeat it in code:
```ruby
# Deprecate
User.transaction do
  # things
end

# Recommend instead, works already
User.connection.transaction do
  # things
end
```

## Allow rolling back transactions without raising an exception

I do like that exceptions automatically rollback transactions. But I also think it's fine to use transactions for business logic which might not be exceptional. I think this violates the "Don't use exceptions for control flow" rule. Do you think it would be worth yielding an object which would allow to mark the transaction to be rolled back?

```ruby
User.transaction do |transaction|
  # things
  transaction.mark_rollback!
  # this will still be executed
end
```

What do you think about this?

**Comment by shirkavand** [comment]
@iGEL did you receive ny feed back or something for your second idea? (Allow rolling back transactions without raising an exception)

**Comment by shirkavand** [comment]
+1 to the "Rollback transactions without exceptions?" idea. 

I think transactions should work something around this: 

```ruby
# In the model...
class Model < ApplicationRecord
  ...
  Transaction do
    ActiveRecordRollback unless user.save
    ActiveRecordRollback unless invite.save
  end
  ...
end

# In the controller
If user && invite
   # All OK, render json etc
else
  # Something went wrong render errors, something around...
  # render json: user.errors or render json: invite.errors
end
```

**Comment by rafaelfranca** [comment]
`User.transaction` is the same as `User.connection.transaction` so I don't see why we should go through a deprecation cycle for this. https://github.com/rails/rails/blob/05b7b80bcaeeb0357cdb6143fbeca1b3c73b5fb9/activerecord/lib/active_record/transactions.rb#L212.

The transaction affects all models sharing the same connection because this is how databases works. Active Record abstracts databases but users should still know how databases works.

> I think this violates the "Don't use exceptions for control flow" rule

We are fine with violating that rule in this case. But if you fell strong about this please work in a PR explaining why it is better.

Also, thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by shqear93** [comment]
I'm trying to build an API with a generic exception handler for all APIs, and I need to put a list of database changes in a transaction, but I'm facing an issue that after rescuing the exceptions in block inside the transaction, but the transaction still being committed!

in the controller:

```ruby
  def handle_exceptions
    begin
      yield
    rescue ActiveRecord::ActiveRecordError => exception
      return render_failed(nil, exception.record) if exception.try(:record).present?
      return render_failed_with_exception('Something went wrong', exception)
    rescue StandardError => exception
      Raven.capture_exception(exception)
      return render_failed_with_exception('Something went wrong', exception)
    ensure
      raise ActiveRecord::Rollback rescue nil if ActiveRecord::Base.connection.open_transactions > 0
    end
  end
```

```ruby
    ActiveRecord::Base.transaction do
      handle_exceptions do
        @user.save
        raise "i want to force rollback"
      end and return
    end
```


I think this is relate, if I'm able to simple rollback the transaction it shuold fix the problem
