### ISSUE TITLE
Blob's metadata column casted as json

### ISSUE THREAD

**Issue by ribanez7** [rails/rails#31780]
### Steps to reproduce
Are there any plans to set the blob's metadata column type as json? Somehow I miss the possibility to directly query the attachments for specific filter data. The steps to reproduce the problem are shown on the following lines.

### Expected behavior
Having a json data type we could directly query the blob's custom metadata, without having to initialize the object and loop them to classify. It would give the freedom of saving custom data, enum like information for example (whenever an attachment is expired, or it is banned by the system, or any special category).
For PostgreSQL users it would look something like:

```ruby
event = Event.last
event.images.joins(:blob).where("active_storage_blobs.metadata->>'banned_date' = ?", nil)

```

For MySQL:

```ruby
event = Event.last
event.images.joins(:blob).where("JSON_EXTRACT(active_storage_blobs.metadata, '$.banned_date') = ?", nil)

```

### Actual behavior
Querying metadata directly is not possible:

```ruby
event.images.joins(:blob).where("active_storage_blobs.metadata->>'analyzed' = ?", true)
=> #<ActiveStorage::Attachment::ActiveRecord_AssociationRelation:0x2afa2cdf9f34>

```

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: 2.4.1p111

**Comment by georgeclaghorn** [comment]
> Are there any plans to set the blob's metadata column type as json?

No, sorry. Blob metadata isn’t intended to be queryable.

**Comment by RISCfuture** [comment]
Do you have any recommendations then if I wish to use a SQL query to pull only those records with associated blobs that are analyzed? I think this is a pretty typical use case; e.g., you don't want to show users those photos of theirs that haven't been processed yet.

I'm really struggling to find a good way to do this. There are no hooks on the analyze job, so it's not like I can set a column value in an `after_analyze` or something. And because the column is stored as JSON, it's not indexable. I even tried querying it using PostgreSQL's `json` functions, but it's stored double-escaped for some reason, so that didn't work. The only thing I can think of doing is to monkey-patch `analyze` in ActiveStorage::Blob, but that is hardly ideal.

**Comment by akaspick** [comment]
Since `ActiveStorage::Blob` supports `custom_metadata`, this is an idea situation for wanting to query the data as a json column.
