### ISSUE TITLE
Rails autoloading cannot load constant despite loading the file it lives in

### ISSUE THREAD

**Issue by michaelherold** [rails/rails#31792]
### Steps to reproduce

A minimal reproduction app can be found here: https://github.com/michaelherold/rails_constants_bug

Within that repository, there is a readme that contains all of the solutions I attempted and includes a  workaround that mostly works.

I don't think there's a way to reproduce this in a single file since it requires the autoloader to show the problem. I can add a test case to Rails itself if that would be easier to understand.

### Expected behavior

Rails' autoloading correctly loads a series of constants that live in the following places:

```
app/
  workflows/
    base.rb      #=> defines the Workflows::Base class
    null.rb      #=> inherits from Workflows::Base
    workflows.rb #=> defines a `Workflows.find` helper method
```

In a Rails console:

```
irb(main):001:0> Workflows::Null.ancestors.include?(Workflow::Base)
=> true
```

### Actual behavior

The autoloader cannot load the `Workflows::Base` constant, despite it looking in the correct location.

In a Rails console:

```
irb(main):001:0> Workflows::Null.ancestors.include?(Workflow::Base)
LoadError: Unable to autoload constant Base, expected /Users/michael/code/ruby/constants_bug/app/workflows/base.rb to define it
        from app/workflows/null.rb:2:in `<module:Workflows>'
        from app/workflows/null.rb:1:in `<top (required)>'
        from (irb):1
```

The weirdest part of this is if you drop `byebug` into the body of the `Workflows::Base` class, you can see that it loaded, but is not, for some reason, added to the environment.

### System configuration

**Rails version**: 5.1.4 and 5.2.0.beta2

**Ruby version**: 2.4.2

**Comment by matthewd** [comment]
Per the error, it is looking for `Base`. `base.rb` isn't defining that, though; it's defining `Workflows::Base`.

The autoloader uses *subdirectories* of `app/` as its roots, so `app/workflows/base.rb` is a top-level file, and expected to define a top-level `Base` constant.

As you noted in workaround 1, you can fix this by moving the files down one level. You don't need to put them in `app/models`, though: you could use `app/workflows/workflows`, or `app/anything-you-like/workflows`.

The default layout is intended to provide the filesystem separation you want... you're just running into issues because you also want constant-namespace separation. I think the Railsier way to arrange these would be `app/workflows/null_workflow.rb`, defining a `NullWorkflow` class, with no namespace.
