### ISSUE TITLE
[ActionCable]  Sec-WebSocket-Protocol header not supported

### ISSUE THREAD

**Issue by yaswanth-rails** [rails/rails#31835]
### Steps to reproduce

When client sends handshake it should be able to set "Sec-WebSocket-Protocol" header to establish connection, also Server should send "Sec-WebSocket-Protocol" header in handshake response

### Expected behavior
should support  "Sec-WebSocket-Protocol"

### Actual behavior
No "Sec-WebSocket-Protocol" supported

### System configuration
Rails-5.1.4
Ruby-2.4.0

**Comment by jeremy** [comment]
Action Cable does use protocol negotiation internally. It's handled automatically and not meant for external consumption.

**Comment by yaswanth-rails** [comment]
I did not get your point, can you please explain more. It is working fine in Firefox  but not working in chrome, due to Sec-WebSocket-Protocol not set in response header.

### Possible Solution

Please Update  RFC class at least to return "Sec-WebSocket-Protocol" in server response, and think how customize client request post processing to set "Sec-WebSocket-Protocol" header value.

**Comment by jeremy** [comment]
Hard to say what you're doing, how you're doing it, why, or what you're expecting, so I took a wild guess that you're implementing your own WebSocket client and perhaps expecting to implement your own protocol layer. Apparently not? 😊

Do investigate the Action Cable code to see exactly how protocols (Sec-WebSocket-Protocol) are handled and negotiated in JavaScript and in the [websocket-driver](https://github.com/faye/websocket-driver-ruby) Ruby library.

**Comment by yaswanth-rails** [comment]
Yes I am using   [AngularJS actioncable](https://github.com/angular-actioncable/angular-actioncable) as client and  rails actioncable as API.

**Comment by jtoy** [comment]
I am using this to connect different clients to actioncable including a javascript chrome client, I think the protocol should be exposed in the headers as well, that is the ONLY place the RFC allows one to add headers. Rails will eventually have to add support for this.

**Comment by thehenster** [comment]
The `Sec-WebSocket-Protocol` header is returned in the response, it's just probably not that useful to you. Here is a typical response to an upgrade request.

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: Qhmn0FiInwLwt21BOasseqc48WI=
Sec-WebSocket-Protocol: actioncable-v1-json
```

ActionCable only supports one protocol. The format of the messages passed between server and client are baked in.

Where the support protocols are defined: https://github.com/rails/rails/blob/5-2-stable/actioncable/lib/action_cable.rb#L41
websocket-driver setting the response header: https://github.com/faye/websocket-driver-ruby/blob/0.7.1/lib/websocket/driver/hybi.rb#L242

If you're trying to use the ActionCable protocol, then the problem is _probably_ that your client isn't sending the `Sec-WebSocket-Protocol` in the upgrade request.

If you're saying that ActionCable will eventually need to support non-ActionCable protocols - then that would be nice :)
