### ISSUE TITLE
Rails 5 loses schema cache on fork

### ISSUE THREAD

**Issue by iamjwc** [rails/rails#31928]
After upgrading to Rails 5.1.4, we started seeing an issue with our Resque worker process hitting our `information_schema` table many times per second. This was because our Resque workers fork for each job that they handle, meaning that the schema cache was refreshed for each job.

In an attempt to fix it, we attempted to clear and repopulate the schema_cache.yml file when each worker starts. The code we used is attached below (_**Fig 1**_). We have this code running inside the process so we can avoid loading `environment.rb` multiple times. The problem we encountered with this solution was that we have multiple workers on a box. This means that a worker could be starting, which clears and repopulates the cache, when another worker is about to load the cache off of disk. We're seeing this in production and it causes us to encounter a `NoMethodError` when trying to call `false.version` on this line:
https://github.com/rails/rails/blob/554dcc4c6ec3339507e9b05235c417e0ed00e1c4/activerecord/lib/active_record/railtie.rb#L99

We have a few ideas about potential fixes:
- Don't clear the cache upon fork
- Allow each parent process to write/load it's own version of the schema_cache.yml file (schema_cache.1234.yml, for example). We have code written that satisfies this that I will send over as a PR shortly, but I think the first fix might be more appropriate.

### Steps to reproduce
Fork process and reopen connection to MySQL.

### Expected behavior
The child process continues using the ActiveRecord schema cache from the parent.

### Actual behavior
The child process has to rebuild the schema cache, by querying the information_schema table.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.3.3

**Resque version**: 1.26.0 

### Fig 1

```ruby
load 'active_record/railties/databases.rake'
Rake::Task['db:schema:cache:clear'].execute
Rake::Task['db:schema:cache:dump'].execute
```

**Comment by rafaelfranca** [comment]
How can we reproduce this problem? There is no code in rails that cleans the schema cache after a fork. In fact, we store the schema cache in the connection pool exactly to make sure that any connection that is created use the same schema cache.

https://github.com/rails/rails/blob/554dcc4c6ec3339507e9b05235c417e0ed00e1c4/activerecord/lib/active_record/railtie.rb#L101

**Comment by iamjwc** [comment]
Ah, interesting. But that wouldn't run in the parent process if the schema_cache.yml file doesn't yet exist, right? Because we are generating the file in the process itself, only the child's connection pool would execute this line.

Also, does the connection pool get cleared on forking? I assume not?

**Comment by rafaelfranca** [comment]
You need to generate the schema cache before booting the application in the parent process.

Each process has it own connection pool, but every time a new process is created we copy the schema cache from the parent process.

https://github.com/rails/rails/blob/4ca73f448187c02b5474cf90dc7c3122ee0760ff/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L1042

**Comment by iamjwc** [comment]
Great. I'll attempt this.

**Comment by lritter** [comment]
FWIW, although the cache may be copied on fork, I still think this is a legitimate concern. Given a repo that has multiple applications (say a web app and a few background workers) any two of these starting up at the same time could cause a race condition where the second process clobbers the the schema cache file as the first process attempts to read it. So in this case it isn't forking related but is related to multiple processes using a shared resource without coordination. We've run into this problem.

It seems the solution is to either introduce some mechanism for global control of the cache generation or to remove the race condition. In essence the former is what is being proposed by suggesting "generate the schema cache before booting the application". Doing this effectively and resiliently is not always simple and certainly increases deployment and operational complexity.

My preferred solution would be to remove the contention on a shared resource. I think the PR attached to this issue is a fine solution since it doesn't preclude the current way AR works and anybody who wants to generate the cache in a globally coordinated way (an there are good reasons for doing so) can do so in exactly the way they do today.

Another option would be to allow for pre-populating the cache without the use of a file (populate the in-memory cache directly on boot). This removes the global resource but introduces a different mode of operation so I think the solution is less desirable than the PR.

**Comment by iamjwc** [comment]
A few things to wrap this issue up:

It seems the real solution to this problem would be to ensure that the `connection_pool.schema_cache` gets updated as the `connection.schema_cache` receives changes. Is there ever a time when you wouldn't want these to be in sync?

As for our issue, I'll paste our solution for anyone who might be searching for a way to fix the issue if they also encounter it.

```ruby

# [AP-4386] When we deployed Rails5 to production, we saw
# a lot of slow queries against database on worker tasks.
# It seems that these workers query the database to determine
# primary keys, etc. when an ActiveRecord class is used the
# the first time after load. Caching this information should
# stop the database from being hit.
#
# Caching logic taken directly from Rails' 'rake db:schema:cache:dump'
# task. This code clears the schema cache, then reloads every
# table in the db explicitly. Lastly, and most importantly,
# it sets `connection_pool.schema_cache` to the current
# connection's schema cache. This ensure's that every child
# process forked by Resque gets this schema_cache.
#
# References:
#   https://github.com/rails/rails/issues/31928
#   https://github.com/rails/rails/blob/1dfc3a248ac03b96696927159e5e1a00c8e96ec2/activerecord/lib/active_record/tasks/database_tasks.rb#L299
ActiveRecord::Base.connection.schema_cache.clear!
ActiveRecord::Base.connection.data_sources.each do |table|
  ActiveRecord::Base.connection.schema_cache.add(table)
end
ActiveRecord::Base.connection_pool.schema_cache = ActiveRecord::Base.connection.schema_cache.dup
```
