### ISSUE TITLE
[Rails5.2.0.rc1] TypeError: is not a class/module

### ISSUE THREAD

**Issue by liukun-lk** [rails/rails#31943]
### Steps to reproduce
https://gist.github.com/liukun-lk/c12c087e20f783a726526be25e957fdb

### System configuration
**Rails version**:
5.2.0.rc1
**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by composerinteralia** [comment]
That is because `self` inside the scope block is not the `Talk` class, but a Relation. You can refer to `Talk::STATUS_NORMAL` or just `STATUS_NORMAL`, but not `self::STATUS_NORMAL`.

@kamipo this behavior was changed in https://github.com/rails/rails/commit/4bdd86fb1e608d0031ee5e03af4ae0b13b41fea3
Thoughts?

**Comment by liukun-lk** [comment]
@composerinteralia Thanks. That means after Rails 5.2.0 we should use `klass` instead of `relation` in the scope block?

**Comment by kamipo** [comment]
Right, this is same issue with #31740.

This change is for all scopes (defined scope, default_scope, and association scope) are behaves consistently.

Before 5.2, if both an AR model class and a Relation instance have same named methods (e.g. `arel_attribute`, `predicate_builder`, etc),  defined scope doesn't respect relation instance information.

For example.

```ruby
class Post < ActiveRecord::Base
  has_many :comments1, class_name: "RecentComment1"
  has_many :comments2, class_name: "RecentComment2"
end

class RecentComment1 < ActiveRecord::Base
  self.table_name = "comments"
  default_scope { where(arel_attribute(:created_at).gteq(2.weeks.ago)) }
end


class RecentComment2 < ActiveRecord::Base
  self.table_name = "comments"
  default_scope { recent_updated }
  scope :recent_updated, -> { where(arel_attribute(:updated_at).gteq(2.weeks.ago)) }
end
```

If eager loading `Post.eager_load(:comments1, :comments2).to_a`, `:comments1` (default_scope) respects aliased table name, but `:comments2` (using defined scope) may not work correctly since defined scope doesn't respect relation instance information.

**Comment by liukun-lk** [comment]
@kamipo Thanks, I understand. : )
