### ISSUE TITLE
ExecJS::ProgramError in Say#goodbye, ActionView::Template::Error (TypeError: Object doesn't support this property or method):

### ISSUE THREAD

**Issue by robertlaub** [rails/rails#31983]
### Steps to reproduce
rails new Hello
rails generate controller say goodbye
visit URL: http://localhost:3000/say/goodbye

### Expected behavior
Web page should display properly.

### Actual behavior
Console Error:
Started GET "/say/goodbye" for 127.0.0.1 at 2018-02-13 10:52:02 -0500
Processing by SayController#goodbye as HTML
  Rendering say/goodbye.html.erb within layouts/application
  Rendered say/goodbye.html.erb within layouts/application (0.0ms)
Completed 500 Internal Server Error in 1202ms
ActionView::Template::Error (TypeError: Object doesn't support this property or method):
    4:     <title>Hello</title>
    5:     <%= csrf_meta_tags %>
    6:
    7:     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    8:     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    9:   </head>
   10:
app/views/layouts/application.html.erb:7:in `_app_views_layouts_application_html_erb__1475447606_69117360'

### System configuration
Windows 10
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...
* Version 3.11.2 (ruby 2.4.3-p205), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop

### Extra
This problem has been discussed on stackoverflow and elsewhere:
https://stackoverflow.com/questions/28421547/rails-execjsprogramerror-in-pageshome
The workaround suggested down the page by MK McKenzie worked for me but these posts are 3 years and it is hard to believe that they are still happening for such a basic use case.

**Comment by rafaelfranca** [comment]
This is a problem with CoffeeScript in Windows machine, since nobody in the Rails team uses windows we have no interest of fixing this issue.

You can generate the application without CoffeeScript or you could try to investigate yourself and try to fix this issue.

**Comment by knightjoe2222** [comment]
>since nobody in the Rails team uses windows we have no interest of fixing this issue.

Am I reading this right? What a disappointing reason to not address a problem that pops up in every new rails project.

**Comment by dub357** [comment]
We ran into this issue as well and it turns out that its related to coffeescript being compiled on windows using the jscript runtime.  A change was made in coffeescript v1.9 (https://github.com/jashkenas/coffeescript/commit/28c07d30cbd2add7ee762c7d532b2c9c972e441a#diff-bb48be8d5fd36ca0910d8e27a8fa65c9) which introduced a EMCAScript 5 dependency (specifically Object.create) but the Windows Scripting Host 'jscript' engine doesn't support EMCAScript 5.  
The following monkey patch should 'fix' the issue if you continue to use the execjs jscript runtime instead of some of the others.

<pre>
# this monkey patch shims the execjs jscript runtime w/ an emcascript5 shim since 
# jscript on windows isn't emcascript 5 compliant
# shim/sham js files courtesy of https://github.com/es-shims/es5-shim
module ExecJS
  class ExternalRuntime
    class Context
      alias_method :write_to_tempfile_orig, :write_to_tempfile
      
      protected
      
      def write_to_tempfile(contents)
        if @runtime == ExecJS::Runtimes::JScript
          shim_path = File.join(File.dirname(__FILE__), "../../lib/es5", "es5_shim.js")
          sham_path = File.join(File.dirname(__FILE__), "../../lib/es5", "es5_sham.js")
          contents = "#{IO.read(shim_path)}\n#{IO.read(sham_path)}\n#{contents}"
        end
        write_to_tempfile_orig(contents)
      end
    end
  end
end
</pre>
