### ISSUE TITLE
Conflict when using "Builder" as concern name

### ISSUE THREAD

**Issue by Spharian** [rails/rails#32059]
### Steps to reproduce

1. Define a concern named `Builder` for a model and declare a method in it (in my case, the concern is placed in the `models/foo/builder.rb` file):
```ruby
module Foo::Builder
  def say_hello
    "Hello!"
  end
end
```

2. Include this concern in your model:
```ruby
class Foo < ApplicationRecord
  include Builder
  # include Foo::Builder -> not working either
end
```

3. Try calling the method you declared in the concern:
```ruby
Foo.first.say_hello
```

A `Builder` concern name might look strange but I'm creating a game where users can "Build" things and this name fits my "module naming conventions".

### Expected behavior

```bash
$ Foo.first.say_hello
"Hello!"
```

### Actual behavior

```bash
$ Foo.first.say_hello
NoMethodError: undefined method `say_hello` for #Foo
```

### System configuration
**Rails version**: 5.0.6

**Ruby version**: 2.4.2

**Comment by rafaelfranca** [comment]
Does this happen with Ruby 2.5?

**Comment by rafaelfranca** [comment]
You `Builder` module is conflicting with the `Builder` module defined by the gem `builder`. This is happening because of this behavior in Ruby https://bugs.ruby-lang.org/issues/11547 that was removed in Ruby 2.5.

In you case you need to use `require_dependency` to require the right constant. See http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#common-gotchas

**Comment by Spharian** [comment]
Happens in Ruby 2.5 also.

The usage of `require_dependency` doesn't solve the problem :(

**Comment by Spharian** [comment]
Having the same issue with Ruby 2.5 and Rails 5.2.2. Ended up by renaming "Builder" to something else but I really like this module name. Can't figure out what's going on there, I just tried it again on a fresh app and I'm having the exact same problem.

**Comment by tadiou** [comment]
I think I'm experiencing the same issue too @Spharian, but coming at it from a slightly different spot.

The reason is, is because I think in the naming of things, `Foo::Builder` conflicts with `ActiveRecord::Associations::Builder`.

**Comment by tadiou** [comment]
I think I'm experiencing the same issue too @Spharian, but coming at it from a slightly different spot. (Rails 5.2.2, Ruby 2.5.1)

The reason is, is because I think actually a name clashing issue, not the constant issue that @rafaelfranca was alluding to. `Foo::Builder` conflicts with `ActiveRecord::Associations::Builder`.

Set this up in a fresh rails install

```ruby
# models/resource/builder.rb
class Resource::Builder
end

# models/resource/write.rb
class Resource
  module Write
  end
end

# models/resource.rb
class Resource < ApplicationRecord
  include Resource::Write
end
```

```ruby
irb(main):001:0> Resource::Builder.new
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `new' for ActiveRecord::Associations::Builder:Module)
irb(main):002:0> Resource::Write.new
Traceback (most recent call last):
        1: from (irb):2
NoMethodError (undefined method `new' for ActiveRecord::AttributeMethods::Write:Module)
```

https://github.com/rails/rails/blob/8a23a0e8c20c0cccf0073906d7dd7f809bfa836d/activerecord/lib/active_record/base.rb#L314

Because `Foo` is inheriting from `ActiveRecord`, and `ActiveRecord` inherits, `ActiveRecord::Associations`, the constant used to go `Foo::Builder`, targets `ActiveRecord::Association::Builder`, which probably doesn't implement `def say_hello`, which would explain why you would have the same issue above when you try to use `Write`.

I think there's probably about a dozen class names you _can't_ use when subclassing a top level constant that inherits from `ActiveRecord::Base`, but it's pretty opaque without really diving in as to what's going on (hello friday afternoon debugging).
