### ISSUE TITLE
Cannot set property 'ActionCable' of undefined

### ISSUE THREAD

**Issue by colorwheeloflife** [rails/rails#32074]
Hi — so yeah, this package won't even load for me.

Upon page rendering I get:

`Uncaught TypeError: Cannot set property 'ActionCable' of undefined`

and when I console 'this' within the package script I get:

![screen shot 2018-02-21 at 10 42 37 am](https://user-images.githubusercontent.com/10913613/36499848-5c35ae36-16f7-11e8-8612-1337876687ce.png)

It seems to fire correctly at first, calling 'this' as window, but then fires a second time and is undefined. 

I've established that the first successful call is coming from the reference script that I put into my html file as recommended in a previous issue. It does not solve the problem though as the second time always continues to come back as undefined. It also comes back undefined when there is no reference in the html script. 

Thanks

**Comment by utilum** [comment]
Thank you for sharing, @colorwheeloflife , it would be helpful if you: 
1) refer to previous issues with their number (linked), and (whatever happened with that issue) what the problem is, what you do, what the expected behaviour is, and the actual.
2) Use text, not an image thereof.
3) Provide a reproduction script using one of these templates:
https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_job_gem.rb
https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_job_master.rb

**Comment by colorwheeloflife** [comment]
#25649 was the previous issue. Their solutions did not work for this problem.

Solved it separately. I'll let you know what it was so you guys can decide if it leads to any cleanup in the package.

I am working with the client side in a javascript environment. We have a separate rails api.

I installed the actioncable npm and was just referencing it. Literally broke at that point without anything else besides including it in my package.json. The npm script did not recognize what 'this' is.  

Having the babel loader present "es2015" was breaking it. Just so you guys know. 

Thanks

**Comment by colorwheeloflife** [comment]
Both es2015 and env are not compatible with this actioncable package. 

Would you prefer that I open a new issue?

**Comment by pixeltrix** [comment]
@colorwheeloflife there's no need to open a new issue but a minimal rails app that replicates the problem would be helpful, thanks.
