### ISSUE TITLE
Form input type "tel" takes anything( your can type "text")  as input and allows to submit with our throwing error.

### ISSUE THREAD

**Issue by darkthirst** [rails/rails#32081]
### Steps to reproduce
Create a rails form with input type as "tel"...telephone number and try entering character in it

### Expected behavior
should throw error if isn't a number on client side only with out any regex

### Actual behavior
Allow to submit everything including numbers

### System configuration
**Rails version**: 4.0

**Ruby version**: 2.1

**Comment by pixeltrix** [comment]
@darkthirst as described in [this blog post][1], by default no validation is applied to `type="tel"` inputs because of the wide variety of telephone number formats available. If you want client-side validation you'll need to add a regex option.

[1]: https://martinwolf.org/blog/2015/04/html5-telephone-input-validation
