### ISSUE TITLE
routing guide doco

### ISSUE THREAD

**Issue by andyrooc** [rails/rails#32219]
Firstly, I'm new to Rails, so the mysteries are far and wide. Maybe a good test of the doco?

After installing Rails, my routes.db contains some basic boilerplate code
```
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
```
None of this construct is mentioned in the guide pointed to by the comment in the code. So one is left wondering whether this default code should be removed and replaced with samples in the guide, or are the examples supposed to be added within the code block (do / end)..or perhaps after it?

If the first line (Rails.application.routes...) is supposed to be there, should it not be mentioned in the documentation? Searching the web for examples hasn't shed any light so far, so I guess it's a matter of experimentation.

**Comment by AlainPilon** [comment]
Yes, the block `Rails.application.routes.draw do...` has to stay there, it is this block that will initialize all the routes available in your app.

You can remove the `get 'welcome/index'` and replace it with your own routes. 

I dont think it is worth a change in the doc since it would feel like over explaining. It is pretty straight forward for anyone who has followed a tutorial. Keep reading rails tutorials and as soon as you run a scaffolding command you should understand.

**Comment by pixeltrix** [comment]
I've added a section to the routing guide about config/routes.rb and added a note about not deleting the wrapping block. Thanks for the report @andyrooc 👍
