### ISSUE TITLE
ActionDispatch::Session::MemCacheStore compatibility with Dalli 2.7.7

### ISSUE THREAD

**Issue by petergoldstein** [rails/rails#32259]
There's an open issue in the Dalli repository that has emerged with the release of 2.7.7, but looks like it might be a Rails issue.  The Dalli issue can be found here - https://github.com/petergoldstein/dalli/issues/678

Essentially the problem is, when using ActionDispatch::Session::MemCacheStore with Dalli 2.7.7, new session creation fails.

### Steps to reproduce

1. Add Dalli 2.7.7 to the Gemfile and bundle
2. Start the Rails server with MemCacheStore configured as the session store
3. Access a page

### Expected behavior

The page should render

### Actual behavior

An error is raised - ActionView::Template::Error (nil can't be coerced into Integer)

This underlying exception is originally raised in the generate_sid method - https://github.com/rack/rack/blob/b37356ee881c0de4266165dacb8af4efaebaf4ec/lib/rack/session/abstract/id.rb#L254 - in Rack.  The '@sidbits' variable is nil, which causes the error in question.

The '@sidbits' variable is nil because of the inclusion of the ActionDispatch::Session::Compatibility module into MemCacheStore.  It's very unclear what this module is supposed to do, and doubly unclear why it's clearing out the '@sidbits' variable.

Does anyone on the Rails team have any insight on the above?  I suspect the best fix is to remove the Compatibility inclusion in MemCacheStore, but I don't know enough about its purpose to be sure.

### System configuration
**Rails version**: 5.1.x

**Ruby version**: 2.4.x

**Comment by pixeltrix** [comment]
@petergoldstein thanks, we're already aware and there's a PR (#32258) to fix this. I have concerns over the brittleness of the fix though and also whether it has any backward compatibility issues - do you have insights to share?

**Comment by petergoldstein** [comment]
@pixeltrix So the fix in #32258 looks odd to me.  I still don't understand the role of the Compatibility module, and the alias just adds more confusion.

If this is the behavior we wish to preserve (the generate_sid method from Compatibility), why wouldn't we just pull that into the Rack::Session::Dalli class and eliminate the Compatibility class entirely.  Using yet another method alias seems confusing and (as you note) brittle.

I can release a 2.7.8 on Dalli as needed to resolve this issue once we decide on the appropriate path forward.

**Comment by pixeltrix** [comment]
I'm unsure of the exact role that `Compatibility` plays but it's probably to normalize behaviour across versions and variants of the session stores since it affects the session key and id generation.

The problem is that `get_session` and `destroy_session` bypass `generate_sid` and call the `generate_sid_with` method instead - understandable since otherwise two clients will be checked out from the pool. If that's the case do you need to override `generate_sid`? Can you not just call the original `generate_sid` from within `generate_sid_with`? AFAICS nothing else calls `generate_sid` directly - I've made a PR with the change here: petergoldstein/dalli#679.
