### ISSUE TITLE
Errno::ENAMETOOLONG on system test screenshot

### ISSUE THREAD

**Issue by oniofchaos** [rails/rails#32346]
### Steps to reproduce

Have a sufficiently long series of describes/contexts such that their combined name causes the error. One example from my app is 
```
Errno::ENAMETOOLONG:
              File name too long @ rb_sysopen - /home/circleci/project/tmp/screenshots/failures_r_spec_example_groups_client_exports_a_csv_of_exceptions_by_visiting_the_exception_report_page_and_clicking_export_to_csv_and_filling_out_the_export_form_with_valid_information_and_clicking_download_downloads_a_file_named_"exception_report_csv"_599.png
```

### Expected behavior

Screenshot should save successfully in some fashion without error - maybe by truncating the name?

### Actual behavior

`Errno::ENAMETOOLONG` error and no screenshot saved.

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.5.0

**Comment by pixeltrix** [comment]
This is really a rspec-rails problem - the integration for system tests encodes the nested context as the method name when generating the image path. Either it needs to truncate the context used to [generate the name][1] or override the `absolute_image_path` method to create sub folders for nested contexts.

[1]: https://github.com/rspec/rspec-rails/blob/1d2935861c89246236b46f77de753cda5ea67d61/lib/rspec/rails/example/system_example_group.rb#L36-L42

**Comment by JonRowe** [comment]
@pixeltrix given that we (RSpec) don't have responsibility for how these are written to disk it would probably be better handled at the point of writing the file no? I mean we can guess that this is what its going to be used for and pre-emptively truncate it but then if Rails changes it's mind about where the files are to be written we'll have to keep following those hoops.

**Comment by pixeltrix** [comment]
@JonRowe the `method_name` in RSpec Rails is implemented like this:

``` ruby
def method_name
  @method_name ||= [
    self.class.name.underscore,
    RSpec.current_example.description.underscore,
    rand(1000)
  ].join("_").tr(CHARS_TO_TRANSLATE.join, "_")
end
```

If we were to truncate that after calling it in Rails then we'd remove the random number and end up overwriting screenshots. I'm happy to send you a PR that ensures that method is less than 255 characters and has a random number at the end if you're willing to accept it.

**Comment by JonRowe** [comment]
@pixeltrix I know where we're generating it, but anyone can encounter this, we're more prone because we use the full context name (so especially nested contexts will encounter this) but its entirely possible for someone to write a mini test name with a similar issue.

That said as you're more familiar with the internals if you were able to point us in the direction of / open a PR to implement "override the `absolute_image_path`method to create sub folders for nested contexts." I would be extremely keen.

**Comment by matthewd** [comment]
@pixeltrix  while I'd hesitate to call that a _reasonable_ method name, I think I agree with @JonRowe that we're obliged to work with all valid inputs, reasonable or otherwise. (Beyond length, it also seems fair to expect us to handle any more untoward characters in there.)

Maybe we could truncate + digest? ¯\\\_(ツ)_\/¯

**Comment by pixeltrix** [comment]
I don't think digesting would be a good option - would make it hard to find the correct name without copying and pasting the path from the test output. It would probably make sense to have the minitest case/top level RSpec group as a containing folder underneath `tmp/screenshots` and then have the image name from there. Unsure whether RSpec would want each context/describe block as a nested folder or just a flat namespace.

**Comment by matthewd** [comment]
I was thinking we'd keep the first ~200 filename-valid characters, then throw the digest on to defend against duplication. I wouldn't've thought many people would be using these filenames in a way other than copying/clicking on the test output anyway, tbh.

**Comment by pixeltrix** [comment]
> I was thinking we'd keep the first ~200 filename-valid characters, then throw the digest on to defend against duplication.

Something like this?

``` ruby
method_name.parameterize.first(200) + "-" + SecureRandom.hex(8)
```

or an actual digest based on `method_name`:

``` ruby
method_name.parameterize.first(200) + "-" + Digest::MD5.hexdigest(method_name)
```

Either way, Rspec Rails can then drop the number from their name since we'll be making it unique.

> I wouldn't've thought many people would be using these filenames in a way other than 
copying/clicking on the test output anyway, tbh.

Depends on how many test failures you've had 😉

**Comment by matthewd** [comment]
I went for digest over randomness to avoid us generating infinite names for unchanging input... but if rspec's likely to be the only popular library to hit this code, and they're already using randomness (I was assuming for their own reasons unrelated to our filename generation, but it sounds like I might have that wrong?), maybe such consistency doesn't gain us anything. 

If `method_name` only exists so that rspec can override our filename-generating, then I'm more ambivalent on who should change.. though even a minitest `test "foo..."` could conceivably get long*ish*.

I'd only add the wart if we're over 200 characters (`String#truncate`?), but yeah, that's what I was thinking.

**Comment by pixeltrix** [comment]
I think randomness was added to the method name because you can easily end up with duplicate example descriptions if you're meta-programming specs - however maybe the example id would be better than randomness as that could be added as a digest in RSpec.

**Comment by JonRowe** [comment]
The random-ness is due to the fact we have no constraints on spec names, this is valid:

```Ruby
RSpec.describe "some top level" do
  specify { expect(1).to eq 1 }
  specify { expect(1).to eq 1 }
end
```

And would produce two identical method names. I agree that example_id would be better but could also be identical across two files.

**Comment by pixeltrix** [comment]
Reopening because we need to do something

**Comment by oniofchaos** [comment]
As far as I'm aware, this has not been addressed

**Comment by JonRowe** [comment]
We truncate it on our side but this is still a potential issue for other consumers of this functionality

**Comment by oniofchaos** [comment]
Echoing what Jon said, when using RSpec the issue is fixed but I don't think the root issue within Rails has been fixed.

**Comment by deivid-rodriguez** [comment]
I think that since rails [prepends "failures_"](https://github.com/rails/rails/blob/7f870a5ba2aa9177aa4a0e03a9d027928ba60e49/actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb#L42) to the generated method name by RSpec, and RSpec now truncates it to 255, the maximum length is still exceeded.

**Comment by deivid-rodriguez** [comment]
Nah, not on Linux at least.

```
$ touch $(ruby -e 'puts "a"*255')
$ touch $(ruby -e 'puts "a"*256')
touch: no se puede efectuar `touch' sobre 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa': Nombre de archivo demasiado largo
```

**Comment by JonRowe** [comment]
Hi @rails-bot yes this is still an issue, just a low priority one :)

**Comment by JosiMcClellan** [comment]
Is anyone working on this? I'd like to pick it up.

**Comment by JosiMcClellan** [comment]
My reading is: Rails should handle `Errno::ENAMETOOLONG` in some way, because any filename is better than saving nothing, but specific frameworks can preempt the problem if they want to maintain control over how it happens.

As to digests/randomness/etc, I can leave that decision until the last minute, but here's a thought:
- 200+ chars from the start of `method_name`
- 1 happy little underscore
- 10 chars for seconds since epoch
- 2 chars to increment in case the file already exists

Another _tiny_ gain could come from changing `"failures_` to `"failures/`, which would still keep failures separated but not increase the length. 9 chars ain't much, but it's 9 more than 0. Would the change throw people off, or cause other problems?

Also @JonRowe, I know you patched for truncation already and I'm definitely not suggesting you change that, but based on your comment I thought I'd at least say that _if you want_ subfolders, using slashes in the string you return from `#method_name` should suffice (correct me if I'm wrong). There could even be additional problems, the goofiest of which is that someone could hit the 4096 char limit on paths, at which point our truncation would fail :scream: 

Thank you all in advance for any advice, as this will (hopefully) be my first contribution!

**Comment by JosiMcClellan** [comment]
I didn't realize my `--amend`ments would show up here, my bad.
Please anyone let me know if you don't like the truncation, suffixing, or anything else in my PR.
