### ISSUE TITLE
ActiveRecord duplicates primary key into column called ID

### ISSUE THREAD

**Issue by mlh758** [rails/rails#32505]
### Steps to reproduce
1. Have a model with a primary key that is not ID. 
2. Decide it's time to change the primary key over to a column called ID because the old primary key is no longer valid.
3. Add an ID column using a migration

[Here is a test case](https://gist.github.com/mlh758/58b9a2e7863d3c81b68ec7b261c3d94a)

### Expected behavior
After creating a new column called ID on my class, that column should be nil when I pull records from the database.

### Actual behavior
Whatever data is in the primary key column is duplicated into the column called ID. This is weird by itself, but it also prevents me from being able to pre-populate the ID column with unique values before altering the table to use that column as the primary key. Saves into ID just seem to get ignored since it doesn't detect a change. Things like this happen:
```
record.old_key # let's say it's 3
record.id # returns 3, it should be nil
record.id = 12345
record.save!
Klass.where(id: 12345).count # 0, it didn't actually save the change
```

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.4.1

**Comment by danhuynhdev** [comment]
That behavior is intended. It is that way so `find` would work with nonstandard primary keys. You could override `#id` for your use case.
https://github.com/rails/rails/blob/47eadb68bfcae1641b019e07e051aa39420685fb/activerecord/lib/active_record/attribute_methods/primary_key.rb#L15

**Comment by kamipo** [comment]
Right, it is the expected behavior of `#id` method.

**Comment by Yegorov** [comment]
@danhuynhdev, @kamipo i have same problem, i override `#id` methods, but this doesn't work as expected.
Example:
```
class MyModel < ApplicationRecord
  self.primary_key = :my_id

  def id
    read_attribute(:id)
  end
  def id=(id)
    write_attribute(:id, id)
  end
end

o = MyModel.create(id: 42)
o.my_id # 42 WHY? id is not primary key, in this case is simple attribute
o.id # 42
```

**Comment by danhuynhdev** [comment]
@Yegorov you should use `_read_attribute` and `_write_attribute` instead, because `read/write_attribute` will translate `:id` to primary key. With that said, I think you should write a migration to change your primary key to `id`, and the old id to another key, because a lot of rails internal relied on primary key being `id`.

**Comment by Yegorov** [comment]
@danhuynhdev Ok, thanks.
In my case I have legacy structure db, and the `id` attribute in it is used for its needs. And now I am faced with a choice: to use `pk_id` in ActiveRecord or rename `id` to `_id` in the legacy structure.
The latter is probably the best choice.

**Comment by pilgunboris** [comment]
I'm not sure if it makes sense to comment in this closed issue, but I'll try. Might be some configuration option could be added for my scenario.
 
So I have a pretty similar issue but arguments above to rename the column just doesn't work for me because I have a Postgres view and not a usual table:

Here is my view sample:
```SQL
SELECT
  id || '_TableA' AS todos_primary_key,
  id,
  name,
  description,
  'TableA' as todo_type
FROM table_a

UNION

SELECT
  id || '_TableB' AS todos_primary_key,
  id,
  name,
  description,
  'TableB' as todo_type
FROM table_b
```

To be able running AR queries in the `Todo` model I set `self.primary_key = :todos_primary_key`
However, this changes the actual `todos.id` to `todos_primary_key` which is absolutely not useful because I need the original value of ID for queries  and I need a unique value for primary key as a separate field because I have a combination of 2 tables and without it some AR queries like `first, last, etc.` just doesn't work.

 To handle that I added method:
```
  def id
    _read_attribute(:id)
  end
```
I will see how it help me. But it would be good to have this configurable.
