### ISSUE TITLE
Strange namespace issue of controllers in Rails Engine

### ISSUE THREAD

**Issue by JevanWu** [rails/rails#32501]
### Steps to reproduce
In a Rails Engine, I create a new `ApplicationController` under the namespace:
```
module Foo
  class ApplicationController < ActionController::Base
    def current_employee
      ...
    end
  end
end
```
and another controller inherits from this application controller, like:
```
module Foo
  class BarController < ApplicationController
    before_action :set_employee
    ...
    private
      def set_employee
        @employee = current_employee
      end
  end
end
```

### Expected behavior
The anticipated behavior should be that the superclass of `Foo::BarController` is `Foo::ApplicationController`, instead of the `ApplicationController` in the Rails application

### Actual behavior
The code works as what I expect in the development environment on my locale machine. However, after I deployed it to staging environment on the server(Ubuntu), the superclass of `Foo::BarController` becomes the `ApplicationController` in the Rails application and the `set_employee` method throwed the error `undefined method 'current_employee'`

### More info
It's a strange problem. After I tried out this in Ruby code, which worked well, I only can create an issue here.
Ruby code:
```
class Parent
end

module Foo
  class Parent
  end
end

module Foo
  class A < Parent
  end
end

Foo::A.ancestors
=> [Foo::A, Foo::Parent, Object, Kernel, BasicObject]

```

### System configuration
**Rails version**:
Rails 5.1.5
**Ruby version**:
ruby 2.4.1p111

**Comment by pixeltrix** [comment]
This sounds like a constant load order issue - can you try adding the follow to the top of `Foo::BarController`:

``` ruby
require_dependency 'foo/application_controller'
```

and see if that fixes your problem. This is a [known gotcha][1] since Ruby (before 2.5) will look for a constant in `Object` before calling `const_missing` which is what the Rails autoloading mechanism uses.

However, this behaviour has changed in Ruby 2.5, e.g:

```
>> RUBY_VERSION
=> "2.4.4"
>> String::Array
(irb):1: warning: toplevel constant Array referenced by String::Array
=> Array
```

vs.

```
>> RUBY_VERSION
=> "2.5.1"
>> String::Array
Traceback (most recent call last):
        2: from /Users/andyw/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        1: from (irb):3
NameError (uninitialized constant String::Array)
Did you mean?  Array
```

So if that's an option for you then try that instead.

[1]: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#when-constants-aren-t-missed-qualified-references
