### ISSUE TITLE
Flash does not work after a redirect

### ISSUE THREAD

**Issue by Voker57** [rails/rails#32528]
### Steps to reproduce

Set flash, redirect to page that includes flash.

https://gist.github.com/Voker57/48f7f990a9aff9a2a2512f8de4b81e27

### Expected behavior

Flash should persist between redirects

### Actual behavior

Flash is nil

### System configuration
**Rails version**:

5bca1f216770

**Ruby version**:

2.5.1

**Comment by y-yagi** [comment]
The flash is cleared with each request.  
In your reproduction steps, since `get "/"` is called after `get "/s"`, so flash is cleared.
Also, if you need the results to be redirected, you need to call `follow_redirect!` explicitly. 
Therefore, if you change the code as below, you probably can test it as expected. 

```ruby 
class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/s"
    follow_redirect!
    assert last_response.body == "error"
  end

  private
    def app
      Rails.application
    end
end 
```
