### ISSUE TITLE
must-revalidate Cache-Control header disappearing in Rails 5.2

### ISSUE THREAD

**Issue by oniofchaos** [rails/rails#32557]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))
```ruby
# application_controller.rb

before_action :prevent_page_caching

def prevent_page_caching
  response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
  response.headers['Pragma']        = 'no-cache'
  response.headers['Expires']       = '0'
end

# application_controller_spec.rb

  describe "prevent page caching" do # using RSpec
    before { get :index }
    subject { response.headers }

    it "requires to set http response headers" do
      expect(subject['Cache-Control']).to match /no-cache, no-store, must-revalidate/
      expect(subject['Pragma']).to match /no-cache/
      expect(subject['Expires']).to eq "0"
    end
  end
```

### Expected behavior
Tell us what should happen

Above spec passes

### Actual behavior
Tell us what happens instead

```ruby
ApplicationController
  prevent page caching
    requires to set http response headers (FAILED - 1)

Failures:

  1) ApplicationController prevent page caching requires to set http response headers
     Failure/Error: expect(subject['Cache-Control']).to match /no-cache, no-store, must-revalidate/
     
       expected "no-cache, no-store" to match /no-cache, no-store, must-revalidate/
       Diff:
       @@ -1,2 +1,2 @@
       -/no-cache, no-store, must-revalidate/
       +"no-cache, no-store"
       
     # ./spec/controllers/application_controller_spec.rb:23:in `block (3 levels) in <main>'
```
### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by Edouard-chin** [comment]
One of our test in our app was failing because of the same issue when we worked on upgrading to 5.2 a couple months ago. This is the commit I wrote to explain the problem

-----------------------------

Conflicting cache-control directives:

- The `no-cache` and the `must-revalidate;max-age=0` directives are conflicting and only the most restrictive one get applied (which in our case is the `no-cache` one [13.1.3](http://www.ietf.org/rfc/rfc2616.txt)
- There seems to be some contradictory answers provided by the community:
  1. `must-revalidate` means: Do not send back stale responses even when user explicly stated that stale responses are acceptable (this seems to be accurate according to [14.9.4](http://www.ietf.org/rfc/rfc2616.txt). Whereas `no-cache` implies `must-revalidate` plus the fact that the response becomes stale right away. The TL;DR is that if you have a response cacheable for 10 seconds, then the `must-revalidate` will kick in after that period whereas the `no-cache` will kick in after 0 seconds (same as `max-age=0`)
  2. `must-revalidate` will return a 504 in case the server doesn't respond to a cache revalidation request whereas `no-cache` will just show the cached-content
- I'm not sure exactly which interpretation is correct, but the rails test suite added a test which looks very similar to our use case https://github.com/rails/rails/blob/8a7e91b084c9d502ebe569c6c64616f1ebdba7fd/actionpack/test/controller/render_test.rb#L388-L392
- Prior to https://github.com/rails/rails/pull/30367 Rails wasn't normalizing Cache-Control values passed from a user and the cache-control was returned as is

**Comment by oniofchaos** [comment]
@rafaelfranca do you have a definitive answer to the OP? I appreciate the input everyone has given but it doesn't sound like there's an official answer.

**Comment by rafaelfranca** [comment]
The official answer was given above in the two comments:

"My understanding is that "no-cache" makes "must-revalidate" unnecessary" and "The no-cache and the must-revalidate;max-age=0 directives are conflicting and only the most restrictive one get applied (which in our case is the no-cache one 13.1.3"

**Comment by rafaelfranca** [comment]
And also tests added on the linked PR above https://github.com/rails/rails/pull/30367

**Comment by drl123** [comment]
@rafaelfranca  FWIW `must-revalidate` is still necessary if you have to support older versions of the mobile Safari browser.  We had to add `must-revalidate` specifically (under Rails 5.0.3) because it would not obey the `no-cache` and/or `no-store` headers.  Most browsers obey correctly, but certain versions of Mobile Safari do not (off hand, I do not remember the exact versions that are problematic).

**Comment by SleeplessByte** [comment]
To add on @drl123 

`no-cache` is also not supported by many HTTP/1.0 caches, which might not be under control of the developer, and still rely on `Pragma: no-cache`.  However, some CDNs (such as cloudfront), and therefore also other proxies don't support `Pragma`. The original implementation was a foolproof way to make something not cache.

```
   https://tools.ietf.org/html/rfc7234#section-5.2.2.2

   Note: Although it has been back-ported to many implementations, some
   HTTP/1.0 caches will not recognize or obey this directive.  Also,
   no-cache response directives with field-names are often handled by
   caches as if an unqualified no-cache directive was received; i.e.,
   the special handling for the qualified form is not widely
   implemented.
```

So yes, it's unnecessary with correctly implemented proxies, caches and agents, but they're not.

**Comment by aaronransley** [comment]
Any progress on this one? Currently running into issues with Firefox and Chrome's `bfcache` refusing to reload pages as needed. These headers are necessary to request a _full reload_.

I understand that the ideal header parsing deals only with correctly implemented clients, but the internet is full of software that is far from flawless.

In the spirit of maintaining purity of code and compatibility with real-world needs, would it be possible to introduce a feature flag allowing `no-cache` and `must-revalidate` to coexist in a single response?

**Comment by SampsonCrowley** [comment]
@aaronransley is right on this one. assuming that caching servers and browsers are following all the standards is not reliable.

@rafaelfranca even though it's "unnecessary", does having both headers actually present any issues for browsers/proxies that DO follow the standards? My understanding is that if the proxy/browser is implemented correctly, it would just ignore the "must-revalidate" on it's own and having it there for the clients that don't follow that standard is still helpful
