### ISSUE TITLE
Docker documentation

### ISSUE THREAD

**Issue by mroutis** [rails/rails#32568]
This isn't a bug report.

I searched the repository, looking for issues or documentation related to an opinionated way
to use Docker with Rails, without any luck.

Nowadays "docker + rails" is a common search term, where you face a lot of deprecated information.

I don't know if the Rails team should take an approach on it, maintaining an updated wiki (pain points, recommendations, etc.) 

The only effort I saw was the deprecated Docker image: https://hub.docker.com/_/rails/
in favor of the `ruby` image.

I'm aware that talking about developmet / deployment / production environments is sort of a _taboo_, or just something with a lot of customization and no standards at all, but would be amazing if we could gather the community knowledge about this.

Sorry if this issue is out of topic or just not up for discussion.

DISCLAIMER: I'm not trying to advocate the use of Docker, neither to prevent its usage at all cost.

**Comment by composerinteralia** [comment]
This will likely get closed, since we only use the Github issues for bug tracking. This does seem like something you could bring up in one of the mailing lists though: https://groups.google.com/forum/#!forum/rubyonrails-talk

**Comment by sikachu** [comment]
Yes, this discussion is actually more fitting to `rubyonrails-core` mailing list instead. However, since this could be considered as "lack of documentation" issue, I'm just going to keep it open here for now.

I think most of the contributors are actually not using container-based system for their production deployment. I know many people are using Heroku, and many of them are using VPS or dedicated server that have their application code in the server.

And yeah, I think everybody agrees that Docker and container-based approach is becoming more and more popular nowadays. I agree that we should have some kind of documentation about it as a "guide" to help people if they want to use container-based approach.

So yeah, I think we'd welcome a patch to Rails Guide (http://guides.rubyonrails.org) that talks about how you can use Rails with Docker. Maybe create another section about deployment from the top page. As long as there're people willing to create a reasonable guide and keep it maintain, I don't see no problem.

/cc @fxn and @matthewd ... what do you guys think?

**Comment by fxn** [comment]
I’m in general -1 about covering this kind of content in the Rails docs. While related, I see it as being out of scope.

If someone publish one particular image to the registry, I think the documentation of that image would be the one doing things by example, giving recommendations about web servers, logs, databases, etc.

**Comment by mroutis** [comment]
@sikachu, I found a [comment](https://groups.google.com/forum/#!searchin/rubyonrails-core/Docker|sort:date/rubyonrails-core/iZGNWaJF6Gw/Y2zwOOX5AQAJ) from someone at that mailing list:

> This mailing list (rubyonrails-core) is intended for discussion about development of the framework itself, not usage of it.

---

@fxn, I agree with that; stepping on deployment/production land isn't in Rails scope, however, I feel that there's no interest at all, because we have such an amazing tooling and services around (Heroku, Engine Yard, etc.) reducing the burden of dealing with infrastructure and operations.
Using Docker made me realize how much I was ignoring about my app and infrastructure.

The [12factor methodology](https://12factor.net/) it's a pretty good approach to prevent common problems, but having something more specifically, like a "production checklist", or some "[security habits](https://bauland42.com/a-week-with-a-rails-security-strategy/)".

I guess that, instead of writing _Docker_ related documentation (or any other related tool),  we could have a better approach summarizing what we have learned about running Rails in production environment. (quite a daunting task, tho)

_thanks for your comments, @fxn, @sikachu_, feel free to close this issue if this topic should be discussed in another channel (irc, mailing list, etc.)

**Comment by fxn** [comment]
Yep, I believe we can close here. In principle we don't want to officially cover these topics by now.

Thanks anyway for bringing it up!

**Comment by mroutis** [comment]
I'll leave this here: http://daniel-azuma.com/articles/talks/railsconf-2018

**Comment by fxn** [comment]
Excellent, thanks @mroutis.
