### ISSUE TITLE
IDE debugging of apps on Rails 5.2 broken

### ISSUE THREAD

**Issue by grumBit** [rails/rails#32737]
### Steps to reproduce
See attached development_machine_installation.txt, then follow steps in expected behaviour section
[development_machine_installation.txt](https://github.com/rails/rails/files/1953598/development_machine_installation.txt)

### Expected behavior
In IDE;
- add break point to first line of [app root]/ config/application.rb;
        require_relative 'boot'
- start debug.
- debugger should stop at breakpoint

### Actual behavior
- debugger continues without stopping
- NB: Any breakpoint further into execution of the Rails app fails to halt execution.

### Work around;
Edit [app root]/ config/boot.rb
Comment out line;
- require 'bootsnap/setup'

Debugging now works throughout app as expected.

### Notes;
Looking at https://github.com/Shopify/bootsnap/issues/93, I believe this problem occurs due a combination of the following;
- new Ruby 2.5 feature "Remove `trace` instructions" (https://bugs.ruby-lang.org/issues/14104)
- Rails 5.2 inclusion of bootsnap gem

NB: The same problem is occurring in a number of IDE's;
- Jetbrains;  https://youtrack.jetbrains.com/issue/RUBY-20684
- RubyMine; https://github.com/ruby-debug/ruby-debug-ide/issues/139
- VSCode; https://github.com/rubyide/vscode-ruby/issues/337

I believe this is a Ruby + Bootsnap issue rather than Rails, however, I'm wondering if a change to the Rails boot.rb could be used to workaround the issue for IDE developers via a test for a debug environment variable?

Also, I wanted to log the problem with a clear title so other Rails developers using IDE's will know what is going on, rather than spending time on searching for answers

(Apologies if my shotgun approach to submitting this issue on multiple repos is poor-form. I'm new to open-source development)

### System configuration
- `vscode-ruby` version: 0.18.0
- Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
- Rails version: 5.2.0
- ruby-debug-ide version: 0.6.1
- debase version: 0.2.2
- VS Code version: 1.22.2 (1.22.2)
- Operating System: macOS 10.13.4 (17E199)
- Hardware (optional): MacBook Pro (13-inch, Mid 2012) & MacBook (13-inch, Mid 2010)

**Comment by y-yagi** [comment]
Thanks for the issue. 
But, as you are aware, this is a matter of bootsnap. The issues of Rails repository manages only problems which Rails can solve. 
Let's track bootsnap's issue. Thanks.

**Comment by grumBit** [comment]
OK...
From Shopify/bootsnap#93, it would seem a lot of work is required to fix bootsnap, for which no one is able to address at present.

Does that mean the Rails repository needs to remove bootsnap integration or maybe to put in a workaround to config/boot.rb until bootsnap can work with Ruby 2.5.0? 

Perhaps I'm missing something here.  Can developers just remove the bootsnap gem manually or go back to a previous Ruby version and all will be good with Rails 5.2?
Thanks.

**Comment by y-yagi** [comment]
As far as https://github.com/ruby-debug/ruby-debug-ide/issues/139, this seems to be a problem with a particular debugger and bootsnap combination. If do not use that debugger, bootsnap works with Ruby 2.5 well. 
Therefore, I think there is no need to remove bootsnap integration in the Rails repository. 

Note that bootsnap integration is only added to `Gemfile` and `config/boot.rb`. If you remove them manually, bootsnap will not be used. 
You can also use the `--skip-bootsnap` option with the `rails new` command.  If you do not want to use bootsnap with the newly created application, please use that option.

**Comment by grumBit** [comment]
Thanks y-yagi, that is very helpful.  Is there a place I can post this information so others can find it easily (e.g. known limitations / faq)?

Also, I'll try to track down an alternative Ruby debugger that works with IDE's. (Would you happen to know of any?)

**Comment by y-yagi** [comment]
The official does not provide such a page. I think that this issue is enough.

Also, I do not know about such IDE.

**Comment by grumBit** [comment]
Thanks again y-yagi, I appreciate your help.
I couldn't find an alternative Ruby debugger for IDE's, so I'll just go with commenting out bootsnap in boot.rb.

Cheers.  :)

**Comment by alexmorral** [comment]
I'm sorry if this is a bit inappropriate to do but I've wasted an hour trying to find a solution to my project not debugging.

- if your Rails 5.2 debugging or debugger not working on your IDE (RubyMine, VSCode, etc)

- You have to know that there is a problem with bootsnap+Rails so just **comment out the 'require 'bootsnap/setup'' from the boot.rb**

PS: I just want this page to be found by others easier because it solved my issue and it's been very hard to find.

**Comment by augustosamame** [comment]
Hello. It has been a couple of months and this issue is still unresolved. I think it's a bit shortsighted for the Rails team not to acknowledge this issue. The current DEFAULT rails installation include both bootsnap and byebug, and currently these do not work together. See https://github.com/deivid-rodriguez/byebug/issues/452
Byebug debugging breakpoints are broken with no indication of the problem being caused  by bootsnap. I spent 2 hours hunting down the issue, workarounds failed to fix it and I had to just go ahead and disable bootsnap in development.
This would thoroughly stump a beginner though and once again it's the default rails install.
I would love to be able to help but I lack the technical chops to tackle the underlying ruby - bootsnap issue. In the meantime I think that bootsnap needs to be removed from the default rails installation as it's currently broken out of the box.

**Comment by rafaelfranca** [comment]
It is actually Ruby that is broken out of the box https://bugs.ruby-lang.org/issues/14702.

**Comment by augustosamame** [comment]
Thanks for the clarification. But the issue still stands. Due to a bug in Ruby 2.5.x , the default configuration of Rails currently has broken debugging out of the box. Neither the Ruby nor the Bootsnap bug reports suggest a fix is imminent. So IMO it's necessary for the framework to make a change in the default gem configuration (ex. by removing Bootsnap) until there's a fix.

**Comment by rafaelfranca** [comment]
Not really, mostly because other ruby versions are working fine, so the framework will keep its default stack and wait Ruby to fix its bug. If Ruby stars to say that `1 + 1` is `3` we would not have to monkey patch in the framework to fix its issue.

**Comment by augustosamame** [comment]
Other Ruby versions may be working fine, but the LATEST isn't. My main concern is Rails beginners. They will start developing with the latest stable Ruby version, because it's supposedly the one that incorporates the latest performance and security enhancements, and Rails default gems, and debugging is broken. So if the Rails team will not consider a fix, at least a warning would be in order. I'd be happy to make my first PR to Rails by detecting the combination of Ruby 2.5.x, bootsnap and byebug and posting a warning about the bug as a message when running `rails server` or `bundle install`. Any other suggestions were this warning could be shown?

**Comment by rafaelfranca** [comment]
Right, I'm also concerned about the beginners, but not only Rails beginners, also about the Ruby beginners. This is why I'm working to fix what is broken, Ruby. Rails is not broken and thus doesn't need to change anything.

**Comment by rafaelfranca** [comment]
Issue fixed on Ruby and will be present in Ruby 2.5.2 https://github.com/ruby/ruby/commit/b85b10c11f9846908a319e72c92e779e46c2217f
