### ISSUE TITLE
Upload same file multiple time give uninitialized constant ActiveStorage::IntegrityError

### ISSUE THREAD

**Issue by kaluznyo** [rails/rails#32855]
### Steps to reproduce
I use the simple 

```
has_one_attached :main_fr 
has_one_attached :main_de
```

Get a file in a var:

`
img = File.new("#{Rails.root}/db/seeds/images/sales/1/logo_fr.jpg", 'r')
`

Next attach to a has_one_attached :image

`
Sale.first.main_fr.attach(io: img, filename: 'test.jpg')
`

Okay get 

`S3 Storage (294.8ms) Uploaded file to key: PhtGjnKJBoCG5r372JKydNAQ (checksum: LHqoAaKsK/4KISRAB+9mmg==)
   (0.2ms)  BEGIN
  ActiveStorage::Blob Create (0.4ms)  INSERT INTO `active_storage_blobs` (`key`, `filename`, `content_type`, `metadata`, `byte_size`, `checksum`, `created_at`) VALUES ('PhtGjnKJBoCG5r372JKydNAQ', 'test.jpg', 'image/jpeg', '{\"identified\":true}', 9665, 'LHqoAaKsK/4KISRAB+9mmg==', '2018-05-09 11:39:23')
`

Then use the same var to attach to another active storage attribute

`
Sale.first.main_de.attach(io: img, filename: 'test.jpg') #main_de vs main_fr before
`

And I Get an  uninitialized constant ActiveStorage::IntegrityError

`
 ActiveStorage::Attachment Load (0.4ms)  SELECT  `active_storage_attachments`.* FROM `active_storage_attachments` WHERE `active_storage_attachments`.`record_id` = 1 AND `active_storage_attachments`.`record_type` = 'Sale' AND `active_storage_attachments`.`name` = 'main_de' LIMIT 1
  ActiveStorage::Blob Load (0.3ms)  SELECT  `active_storage_blobs`.* FROM `active_storage_blobs` WHERE `active_storage_blobs`.`id` = 115 LIMIT 1
  S3 Storage (170.0ms) Uploaded file to key: Z5v7yW2hxCg2sCFxaDKL8mVu (checksum: 1B2M2Y8AsgTpgAmY7PhCfg==)

`

Backtrace : https://gist.github.com/kaluznyo/b5e25dc602b85254dcfbdc675396a0a1

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by al2o3cr** [comment]
That's an odd error, especially since there's a test for the specific line that seems to be failing to find `ActiveStorage::IntegrityError`. It's in the [shared cases](https://github.com/rails/rails/blob/bf5f41d948b6f3f27db7fdc2b70897aec991065f/activestorage/test/service/shared_service_tests.rb#L40) which get included by the S3 adapter tests.

You may want to ensure that the `File` object in `img` in your example gets reset to the start of the file after the first attachment; I could see that causing issues. Will try to reproduce in more detail later today.

**Comment by redrick** [comment]
hey, sry to comment on old issue, but I was just fighting with this and is exactly as @al2o3cr says, if you try the way is explained up, it gives you `ActiveStorage::IntegrityError` but if you ensure `File` object is rewinded (basicly to assign it again is the solution) it works perfectly... 

I would say this could be closed now right ? thx to @al2o3cr  saved me some time :)

**Comment by sikachu** [comment]
About the IntegrityError issue:

I've seen this problem with Paperclip before. It's because the file has been read _but never get rewinded_. I'd accept a simple patch which try to attach the same file object _twice_ and make sure it passes. The fix, obviously, is to `#rewind` the file once it's get handled by the storage adapter.

---

About this error message:

> And I Get an `uninitialized constant ActiveStorage::IntegrityError`

That seems like a missing require, which is a separate issue. I think we should fix that too.

**Comment by redrick** [comment]
So I quickly put some bindings in code and found out that actually it is in `ActiveStorage::Blob` in [`build_after_upload`](https://github.com/rails/rails/blob/5-2-stable/activestorage/app/models/active_storage/blob.rb#L53) where `blob.upload(io)` is called which causes this trouble over here (I mean first part of your response, I got no idea about uninitialized constant here :( )

but I tried `#rewind` as you said, but the problem is it returns integer (0 - first line) and obviously `File` object is expected over there, so I quickly just tried out putting `File.open(io.path)` in there and it works as i would expect... (may not be the luckiest idea, but gets my point across...)

I will have some time this weekend, will try to come up with test and patch for this, I just wanted to share what I found out since I looked already :)

**Comment by sikachu** [comment]
Ah, yep, I'm sorry for not being clear. the `#rewind` should be a standalone call either before we call `service.upload` (on line 155) ...

https://github.com/rails/rails/blob/5-2-stable/activestorage/app/models/active_storage/blob.rb#L155

or maybe after `service.upload` is called. Either way, it will reset the cursor of that IO object back to the beginning and make the file re-readable again.

Please let me know if you need any help, thanks!

**Comment by EdwardIII** [comment]
Thanks for your time and effort on this folks. In the meantime is there a workaround? I think I'm seeing this error when I try and upload the same image multiple times with a factory. 

I've tried manually rewinding the object but still see `ActiveStorage::IntegrityError: ActiveStorage::IntegrityError`.

I'm not sure if this is an issue with ActiveStorage or FactoryBot? I'm guessing it's related to this issue as it's the same error and it never seemed to happen with paperclip (you'd just send the result of File.open)

My factory looks like this:

    # snipped a bit for clarity
    require 'factory_bot'
    
    FactoryBot.define do
      def file_for_activestorage(path)
        file = File.new(path, 'r')
        {
          io: file, 
          filename: "#{SecureRandom.uuid}_#{File.basename(path)}"
        }
      end
    
      factory :my_thing do
        company
        title "Why Use My Thing"
        image(file_for_activestorage("#{Rails.root}/app/assets/images/hotelroom.jpg"))
      end
    end

**Comment by guilpejon** [comment]
How did you ended up solving this, @EdwardIII?
