### ISSUE TITLE
inconsistent interface between where and where.not when receiving nil

### ISSUE THREAD

**Issue by krainboltgreene** [rails/rails#32906]
### Steps to reproduce

```
[1] pry(main)> Account.where(nil).count
   (28.2ms)  SELECT COUNT(*) FROM "accounts"
=> 0
[2] pry(main)> Account.where.not(nil).count
ArgumentError: Unsupported argument type:  (NilClass)
from /Users/kurtis.rainboltgreene/.rvm/gems/ruby-2.4.3/gems/activerecord-5.1.4/lib/active_record/relation/where_clause_factory.rb:27:in `build'
```

### Expected behavior

`.not()` shouldn't explode

### Actual behavior

It exploded

### System configuration
**Rails version**: All

**Ruby version**: All

**Comment by bogdanvlviv** [comment]
Currently, this is expected behavior that was added in https://github.com/rails/rails/pull/13534.
But I have some doubts about behaviour `where` and `find_by` with blank argument  see https://github.com/rails/rails/pull/28290 and https://github.com/rails/rails/issues/31852
Let's discuss that, maybe there is something we can improve.

**Comment by krainboltgreene** [comment]
While it seems reasonable, how are you supposed to replicate `.where(if false then {a: 1} end)`?

**Comment by bogdanvlviv** [comment]
we might rely on lazy loading
```
relation.where(active: true)
relation = relation.where(a: 1) if condition
```

**Comment by krainboltgreene** [comment]
Right, so I know how to do a conditional where, but the single line option is so much more succinct.
