### ISSUE TITLE
ActiveRecord::Base is not `connected?` after successful `establish_connection`

### ISSUE THREAD

**Issue by thisismydesign** [rails/rails#32918]
### Steps to reproduce

Standalone Ruby gist to reproduce: https://gist.github.com/thisismydesign/021310c596e72867e098097e49327e8e

Run `rspec _rails#32918.rb` or check `output.txt`.

### Expected behavior

`ActiveRecord::Base.connected?` returns truthy value after successful `ActiveRecord::Base.establish_connection`.

### Actual behavior

`ActiveRecord::Base.connected?` returns `false`

### System configuration
**Rails version**:
Using rake 10.5.0
Using concurrent-ruby 1.0.5
Using i18n 1.0.1
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.0
Using activemodel 5.2.0
Using arel 9.0.0
Using activerecord 5.2.0
Using bundler 1.16.0
Using diff-lcs 1.3
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using sqlite3 1.3.13

**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by matthewd** [comment]
This is the expected behaviour: `connected?` returns whether it (more properly, the current thread) is _actually_ connected, while `establish_connection` only sets up the connection details (its naming is historical; we probably wouldn't've called it that today, but it doesn't seem worth a deprecation to change now).

Please do submit a PR if you think the documentation can be improved to make that distinction clearer.

**Comment by thisismydesign** [comment]
@matthewd Thanks. How could I trigger an actual connection then?

**Comment by matthewd** [comment]
`connection` will do it for now, though a future version may go further in deferring it until a query is executed.

**Comment by thisismydesign** [comment]
Yep it work with the Gist. Thanks a lot.
