### ISSUE TITLE
db:drop drops not created DB with postgresql and sqlite3 adapters (but not with mysql2)

### ISSUE THREAD

**Issue by thisismydesign** [rails/rails#32914]
With postgresql and sqlite3 adapters running `db:drop` with a non-created DB acts as if the DB is there:
`Dropped database '<env>'`. As opposed to in case of mysql2 adapter: `Database '<env>' does not exist`.

AFACT this is because connecting to the DB with these adapters creates the DB. Example from sqlite3 adapter: https://github.com/rails/rails/blob/v5.1.6/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L30

### Steps to reproduce

Standalone Ruby gist to reproduce: https://gist.github.com/thisismydesign/c5c188b0094dfd0088115d6cbd81ae97

Switch the `database_configuration` param in `load_active_record_tasks` and execute via `rspec _rails#32914.rb` (or see *_output.txt).

### Expected behavior

Option 1: `db:drop` doesn't find DB unless it's explicitly created
Option 2: behaviour is consistent across adapters (other adapters also create DB on connect)

### Actual behavior

For postgresql and sqlite3 adapters (at least) not existing DB is said to be dropped.

### System configuration
**Rails version**: activerecord 5.1.6, pg 1.0.0, mysql2 0.5.1, sqlite3 1.3.13

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by lxxxvi** [comment]
For sqlite3 it's even more special. I created a new rails project, ran `rake db:drop` once and `rake db:drop` twice, here's the result

```shell
# sqlite

$ rake db:create
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'

$ rake db:drop
Dropped database 'db/development.sqlite3'
Dropped database 'db/test.sqlite3'

$ rake db:drop
Dropped database 'db/development.sqlite3'
Database 'db/test.sqlite3' does not exist
```

So, using the sqlite3 adapater, dropping an non-existent database "fails" differently depending on the environment.

**Comment by thisismydesign** [comment]
Still present.

**Comment by thisismydesign** [comment]
Still present.

**Comment by ubelexe** [comment]
Still present.

**Comment by itsWill** [comment]
I had a look at this issue and I think I got a grasp of whats going on here: 

Before doing a `db:drop` we are going to do a check that the code we are executing is not in a protected environment, the check is here: https://github.com/rails/rails/blob/fe0145c58008d286e53486d94ceeff74dc2407ef/activerecord/lib/active_record/tasks/database_tasks.rb#L57

In this connect when we call: `current = ActiveRecord::Base.connection.migration_context.current_environment`

The `connection` method will end up calling the `sqlite3_connection` method and as @thisismydesign pointed out will create the database.

What we can do is make a check to see if the database exists, and fail early, since if there is no database we can't operate on it.

**Comment by thisismydesign** [comment]
Still present

**Comment by itsWill** [comment]
still present
