### ISSUE TITLE
Unexpected behavior of SCOPE variable in db:migrate task

### ISSUE THREAD

**Issue by Loriowar** [rails/rails#32963]
### Steps to reproduce

Create below migrations with arbitrary content:
1. `20180523073344_create_users.rb`
2. `20180523073355_migrate_users.data_migrations.rb`
3. `20180523073359_create_accounts.rb`

Run:
* firstly `rails db:migrate SCOPE=`
* then `rails db:migrate SCOPE=data_migrations`

### Expected behavior
After `rails db:migrate SCOPE=` executed only migrations 1 and 3.
After `rails db:migrate SCOPE=data_migrations` executed only migration 2.
After `rails db:migrate` executed all migrations 1, 2, 3.

### Actual behavior
Result of `rails db:migrate SCOPE=` and `rails db:migrate` is identical and executed all migrations 1, 2, 3.

#### Suggestion
Is `scope.blank?` in [database_tasks.rb:184](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/tasks/database_tasks.rb#L184) is important? May we change it to `scope.nil?`.

### System configuration
**Rails version**: 5.0.6

**Ruby version**: 2.4.2p198

**Comment by bogdanvlviv** [comment]
Hi. Thanks for the issue but
> Result of rails `db:migrate SCOPE=` and `rails db:migrate` is identical and executed all migrations 1, 2, 3.

seems correct.

**Comment by Loriowar** [comment]
@bogdanvlviv i.e. is not there native way in Rails to run only migrations without scope and skip all migrations with scope? If this is right and described case is not a bug, please, close this issue. Otherwise, if this behaviour in case `SCOPE=` is not determine (and I can't find any documentation about border case with empty `SCOPE`), I suggest to discuss it and implement required changes if possible.

**Comment by y-yagi** [comment]
First, I think that this behavior is correct. 

SCOPE is a feature for executing only the migration of a specific engine, I think that it is appropriate to judge that empty SCOPE was specified when an empty character is specified. 

> is not there native way in Rails to run only migrations without scope and skip all migrations with scope?  

For now this feature is not available. 
If that feature is really necessary, please describe the necessary reasons and create a PR.  
We reserve the Rails issue tracker only for bugs in Rails. Thanks.

**Comment by cklatt** [comment]
I recently ran into an issue with the scope environment variable.  We had defined an application variable "SCOPE" using figaro in application.yml.  We could not figure out why our migrations no longer ran anymore.  After reading the code I discovered that scope = ENV["SCOPE"] in database_tasks.rb was using the same name.  We renamed our variable and migrations worked again.  I'd like to suggest that because this is a common name, db:migrate should use something less common.  Perhaps rename it to MIGRATION_SCOPE or something like that?  Alternatively, detect and output a message if the scope is set.  I would have noticed the problem right away if a message had been output.
