### ISSUE TITLE
Getting Started with Rails : NoMethodError in CommentsController#create

### ISSUE THREAD

**Issue by pitsolu** [rails/rails#33000]
### Steps to reproduce

I'm new to Ruby and Rails. Currently going through the [Getting Started with Rails](http://guides.rubyonrails.org/getting_started.html#adding-a-route-for-comments) Tutorial.
I've been able to resolve all hiccups so far except an error while saving comments.

### Expected behavior
Save comment without error associated to Article on attribute 'title' appearing.

### Actual behavior
I get the error below while trying to save a Comment.

"NoMethodError in CommentsController#create
undefined method `title' for #<Comment:0x00007fe3ee84b2d0>"

The error appears on [line 6](https://github.com/pitsolu/rails-tutorial-demo/blob/master/app/controllers/comments_controller.rb#L6)

### System configuration
**Rails version**: 5.2.0
**Ruby version**: 2.3.7p456

Please assist. Thanks.

**Comment by y-yagi** [comment]
It seems you have added `validates :title` to `ApplicationRecord`. 
https://github.com/pitsolu/rails-tutorial-demo/blob/5fd1870712285622cde941619e17005ddeb7123f/app/models/application_record.rb#L3

This validation is also executed in `Comment` which is a child class of `ApplicationRecord`. 
However, since `title` is not defined in `Comment`, it is an error. 
If you remove that validation it will work correctly. 

Also, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks!
