### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by Tectract** [rails/rails#33009]
I'm trying to learn about how to enqueue jobs into Rails as a "background" task, and the documentation on this topic is really not clear. Maybe someone can help me, and help update the docs. From here:

http://guides.rubyonrails.org/active_job_basics.html

> How to enqueue jobs.
> Enqueue a job like so:
> GuestsCleanupJob.perform_later guest

Ok. What file should that function go into? Does it get called when the server starts? When does it get called? I want a function that will get called when the server starts. How do I do that?

> Rails itself only provides an in-process queuing system, which only keeps the jobs in RAM. If the process crashes or the machine is reset, then all outstanding jobs are lost with the default async backend. 

Yep, that's exactly what I want. How do I use the "in-process" queuing system to start a function that will run in RAM? There is no detail about that in the docs, it appears. I would like to not have to call every one of my "background" processes by hand when I start my server...

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by Tectract** [comment]
I don't think rafaelfranca should be moderating here. I'd ask a more senior member to step in and help, please.

**Comment by rafaelfranca** [comment]
Feel free to improve the documentation. Rails is made by volunteer efforts. Some times the documentation will not answer some questions. Some times those questions don't belongs to the documentation.

There are plenty of books that could answer your questions. The first questions are basic, I agree and the answer for them are:

> What file should that function go into?
Any file were you need to schedule a job. It could be in a controller, in a model, in an initializer, in a library, etc.

> Does it get called when the server starts?
It depends on where you put it. If you put in an initializer it will run after the application initializes.

> How do I do that?
I think I answered that question above.

> Yep, that's exactly what I want. How do I use the "in-process" queuing system to start a function that will run in RAM?
http://guides.rubyonrails.org/active_job_basics.html#enqueue-the-job and make sure you are using the right job adapter.

Your questions are about usage of the Ruby on Rails framework, and looks like you missing some knowledge about how rails works. I can point to you some other pages in the guides that could help you to build the knowledge to come up with the answers for those questions by yourself.

http://guides.rubyonrails.org/configuring.html#initialization-events
http://guides.rubyonrails.org/configuring.html#locations-for-initialization-code
http://guides.rubyonrails.org/configuring.html#rails-general-configuration

If you think this should be in the documentation, please do investigate and contribute back.

Now for the second set of questions:

> Is this a joke?
No. And I'll explain in the next answer.

> Basic functionality questions are not allowed on your github?
It is not. As you can see in the [Contributing file that GitHub linked to you before you opened the issue](https://github.com/rails/rails/blob/master/CONTRIBUTING.md#do-you-have-questions-about-the-source-code), questions about Ruby on Rails usage are not allowed on the issue tracker. We have different forums for that. One of them in Stack Overflow. If you don't like it you can use the rails-talk mailing list linked in the contributing file.

> The issue is about your documentation and the fact that it doesn't answer BASIC USER QUESTIONS!
I don't think this is a documentation problem, but indeed it doesn't answer all basic user questions since it can't. It is a best effort. It can answer some of the questions but some questions it will have to expect users to be able to look on other sources like books, blog posts and other guides pages in order to build the knowledge that is missing to understand how to use it.

> The fact that you guys offer no help at all and just force close issues is really upsetting. Horrible moderatorship, horrible repo maintenance, honestly.
> I don't think rafaelfranca should be moderating here. I'd ask a more senior member to step in and help, please.
That is also your opinion and you are entitled to have it, but also consider that, like I said above, Rails is made by volunteers, and by a limited number of people. If we would be answering basic user questions for everyone that have them, neither if that was our full time job it would be possible to be able to help everyone. This is why we direct people to other forums like Stack Overflow where a wider community can be able to help.

Last, but not least, as per our license: THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.

Even that my colleagues locked the conversations because they do think your comments were too heated, I'll unlock in case you want to rethink your attitude and, given all information and reasons that I gave you to close this issue, you want to suggest improvements.

**Comment by andlrb** [comment]
Although @Tectract was a bit aggressive, I do agree with his opinion on StackOverflow. 
SO usually is toxic and rarely does it provide meaningful feedback which could help with a complex issue (e.g: I've been facing rather strange issue with Rails 5.2 after updating from 5.1.4 and I wasn't able to get any feedback on it on SO or the mailing list, but I won't go into details here and instead will keep waiting and researching). The mailing list is also rather empty and I doubt many people actually read it. I do love the IRC channel but at times it's hard to keep track of a conversation. 

In comparison to the Elixir community, I feel like it's harder to get help and feedback on the issues you're facing with Rails. I'd love to see an equivalent of the elixirforum for our community. 

But anyways, we all love and appreciate all the effort and time put into Rails, the ruby ecosystem, and our somewhat-loving community, by awesome volunteers like you, @rafaelfranca.

**Comment by rafaelfranca** [comment]
That is a valid point @andlrb. I think we as a community can improve the level of support, but I really believe that GitHub is not the right place for questions about usage of software, and waiting to core member to reply those questions doesn't scale.

Food for thought: why the mailing list is empty and people don't read it? Would introducing a forum improve the participation?

My guess the problem lays on the answers for the first question. We as a community should use the appropriated forums to help newcomers, answer questions, help each other. That responsibility is mine, yours and of everyone that is part of this community.

So, if the mailing list is empty, let's fill it.
If nobody reads it, let's read and reply to set the example.
If people don't provide meaningful help, let's be the ones that will.

As someone that had all this support when started to use rails I really believe it is possible and it doesn't require a team of 12 people to be the only ones providing this support.

**Comment by Tectract** [comment]
> http://guides.rubyonrails.org/active_job_basics.html#enqueue-the-job and make sure you are using the right job adapter.

HOW??? HOW DO I "ENQUEUE" JOBS??? For the love of god, people. Just giving me a function prototype and telling me "put it anywhere" doesn't help.

Why don't I use the mailing list? Because it's not anonymous. Same problem with IRC, it's really painful to use without giving up your IP address and network route. Plus, I really and truly BELIEVE that GITHUB is the place for user questions related to a repo! Why? Because it archives, and because you actually interface with the devs responsible for the project.

**Comment by Tectract** [comment]
I guess I'll just keep searching and trying and trying whatever random stuff I find. I'm trying to start a socket monitor with the server, parse and broadcast socket messages. I want it to automatically start with the server, and run basically like a daemon. If it dies, it would be nice it it comes back to life, eventually. If anyone can offer some advise over where to look, I'd appreciate it. I can't make heads or tails of the official documentation about the "queue" system. It seems to indicate there is some way to put jobs in some sort of queue, but it's not real clear on HOW.

**Comment by Tectract** [comment]
I think I need something more like this:
https://coderwall.com/p/mrpebq/background-daemons-in-your-rails-app-with-the-daemons-gem

Honestly I think that one page about how the "enqueue" jobs is just super-confusing and threw me for a loop, sorry.

**Comment by andlrb** [comment]
@rafaelfranca 
> I really believe that GitHub is not the right place for questions about usage of software
That's indeed true and I agree. 

> Food for thought: why the mailing list is empty and people don't read it? Would introducing a forum improve the participation?
Hard to say, I read the mailing list whenever I get a notification but most of the time I do not have an answer to the question or issue that the user is having, so in the back of my mind I just say "Someone else will handle it". I think this "someone else will do it" approach is an issue and I know that I'm not the only one that does it, unfortunately. 

I also believe that the mailing list is rather dull looking, and as we know, fancy stuff make people want to get involved most of the time. 

@Tectract 
> Honestly I think that one page about how the "enqueue" jobs is just super-confusing and threw me for a loop
Quite the opposite, I believe that section of the documentation does what it's supposed to do. It explains how to enque the job. And the section below it explains how to execute the jobs, which I believe is what you were looking for. 

In all honesty, I think you need to relax a bit and not be so aggressive. 
Issues can be frustrating but it does no good to be mean to people.

**Comment by rafaelfranca** [comment]
You are fine to disagree, but your aggressiveness, even though, I respectfully unlock the conversation so we could actually have a discussion with respect, actually bought you a permanent ban of the rails issue tracker. Enjoy!
