### ISSUE TITLE
ActionController::Parameters#transform_values does not convert hashes into ActionController::Parameters

### ISSUE THREAD

**Issue by KevinSjoberg** [rails/rails#33044]
### Steps to reproduce

```ruby
params = ActionController::Parameters.new({ foo: { bar: "baz" } })
params.transform_values { |v| puts v.class.inspect }
# ActiveSupport::HashWithIndifferentAccess
# => <ActionController::Parameters {"foo"=>nil} permitted: false>
```

### Expected behavior

When calling `#transform_values`, `Hash` values should be converted to `ActionController::Parameters` objects. `ActionController::Parameters#each_pair` does this automatically for you. See https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/strong_parameters.rb#L337.

Currently, `#transform_values` will give you different values for `Hash` values depending on whether or not `#each` or `#each_pair` has been called.

```ruby
params = ActionController::Parameters.new({ foo: { bar: "baz" } })

params.transform_values { |v| puts v.class.inspect }
# ActiveSupport::HashWithIndifferentAccess
# => <ActionController::Parameters {"foo"=>nil} permitted: false>

params.each_pair { |_, v| puts v.class.inspect }
# ActionController::Parameters
# => {"foo"=><ActionController::Parameters {"bar"=>"baz"} permitted: false>}

params.transform_values { |v| puts v.class.inspect }
# ActionController::Parameters
# => <ActionController::Parameters {"foo"=>nil} permitted: false>
```

### Actual behavior

`ActionController::Parameters#transform_values` return `ActiveSupport::HashWithIndifferentAccess` for `Hash` objects.

I'd be more than happy to submit a pull request for this. Just want to confirm that this indeed is unexpected behaviour. 🙂 

### System configuration

**Rails version**: Rails 5.2.0

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by y-yagi** [comment]
Unlike `each_pair`, `transform_values` is declared in the document to return `value`.
http://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-transform_values 
http://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-each_pair 

So, this is intentional behavior. 
If you want to change to `ActionController::Parameters`, it is a feature request.
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. Thanks.

**Comment by sikachu** [comment]
@y-yagi actually, this is a bug. The reason this `transform_values` method is defined in `ActionController::Parameters` in the first place because we want to make sure that performing an operation on the `Parameters` object won't make the object transform into a hash.

Parameters transforming into a plain hash object exposing a security risk to the user as it skips parameter whitelisting logic. I think we need to fix this.

@KevinSjoberg do you mind pinging me once you open the PR so I can make sure to take a look?

**Comment by KevinSjoberg** [comment]
@sikachu I've opened a pull request addressing the issue. See #33076. 🙂
