### ISSUE TITLE
Clean up references to config/initializers/session_store.rb

### ISSUE THREAD

**Issue by searls** [rails/rails#33124]
As of 5.2 (this commit: e5a6f7ee9e951dbe0e4e9ea2c0743b4dfb135c57 ), `config/initializers/session_store.rb` is no longer generated, but a couple spots in the repo still reference it, which is a bit confusing. Would a PR to remove these and direct folks to the general application config files be desired?

```
$ git grep session_store.rb
actionpack/lib/action_dispatch/middleware/session/cookie_store.rb:    # Configure your session store in <tt>config/initializers/session_store.rb</tt>:
guides/source/3_0_release_notes.md:* The `session_store` was configured in `ActionController::Base.session`, and that is now moved to `Rails.application.config.session_store`. Defaults are set up in `config/initializers/session_store.rb`.
guides/source/upgrading_ruby_on_rails.md:### config/initializers/session_store.rb
guides/source/upgrading_ruby_on_rails.md:# in config/initializers/session_store.rb```

**Comment by matthewd** [comment]
The three guides references sound right, as they're specific to the versions they're talking about.

The first one,
https://github.com/rails/rails/blob/3fe81d31c320738219e56d1684d219d65167f2fc/actionpack/lib/action_dispatch/middleware/session/cookie_store.rb#L28-L30
could change. Maybe by little more than inserting "e.g."? 

Seems like there's something to be said for encouraging a predictable place/naming if people _are_ going to change the value. Looks like the linked commit changed the guides to "in an initializer", so that'd be fair too.

**Comment by searls** [comment]
That was the one that tripped me up, because googling for the file suggests it really ought to exist, and so I left confused by where the session store was configured (before finding https://github.com/rails/rails/commit/e5a6f7ee9e951dbe0e4e9ea2c0743b4dfb135c57 ). I'd encourage us to change that reference to something like "in an initializer" as well.
