### ISSUE TITLE
ActiveSupport::Duration not correctly works with Float

### ISSUE THREAD

**Issue by taleh007** [rails/rails#33200]
### Steps to reproduce

```bash
~ rails -v
> Rails 5.2.0
~ rails new duration_check
[ ... ]
~ cd duration_check
~ rails console

Loading development environment (Rails 5.2.0)
2.5.1:001:0> 1.5.days
=> 1.5 days
2.5.1:002:0> 1.5.years
Traceback (most recent call last):
        1: from (irb):2
NoMethodError (undefined method `years' for 1.5:Float)
2.5.1:003:0> 3.years / 2.0
=> 1.5 years
```

### Expected behavior

```Ruby
1.5.days                  #> 1.5 days
0.5.years                 #> 0.5 years
0.5.years == 1.year / 2.0 #> true  
0.5.years == 6.months     #> true  
```
### Actual behavior
NoMethodError  raises when you try to call `years` and `months` on Float. But it possible to get float `years` and `months` by dividing "integer year or month" by Float 
```Ruby
3.years / 2.0 == 1.5.years  #> NoMethodError
3.years / 2.0 == 18.months  #> true
1.5.years == 18.months      #> NoMethodError
```
### System configuration
**Rails version**: 5.2.0, 5.1.6

**Ruby version**: 2.5.1, 2.4.2

**Comment by jychen7** [comment]
confirmed in rails 5.2.0

```
> ActiveSupport::Duration::PARTS.map {|part| 1.send(part) rescue nil}
 => [1 year, 1 month, 1 week, 1 day, 1 hour, 1 minute, 1 second]

> ActiveSupport::Duration::PARTS.map {|part| 1.5.send(part) rescue nil}
 => [nil, nil, 1.5 weeks, 1.5 days, 1.5 hours, 1.5 minutes, 1.5 seconds]
```

That's because `Duration` defines `months` and `years`, but `numeric/time.rb` doesn't

https://github.com/rails/rails/blob/ee708cf402ac9ad8bba4ad4808c01266433883a5/activesupport/lib/active_support/duration.rb#L166-L176

https://github.com/rails/rails/blob/ee708cf402ac9ad8bba4ad4808c01266433883a5/activesupport/lib/active_support/core_ext/numeric/time.rb#L45-L56

As for integer, it handles specially at

https://github.com/rails/rails/blob/ee708cf402ac9ad8bba4ad4808c01266433883a5/activesupport/lib/active_support/core_ext/integer/time.rb#L6-L22

is it a bug or on purpose? shall I fix it?

**Comment by jychen7** [comment]
oh, it has been ten years.

I think it would make sense to have `1.5.years`, which we can do `3.years / 2.0` anyway.

**Comment by sikachu** [comment]
If you scroll down to the [comment on the commit](https://github.com/rails/rails/commit/d599b8000968047b4095dd8ff6c8ef10bb4ed462#commitcomment-8715), seems like the rationale was in this discussion: https://groups.google.com/forum/#!topic/rubyonrails-core/5UbFosPYLaU

**Comment by jychen7** [comment]
The definition of month and year is different now and there is no division in 2008

2008
https://github.com/rails/rails/blob/d599b8000968047b4095dd8ff6c8ef10bb4ed462/activesupport/lib/active_support/core_ext/integer/time.rb#L33-L41

https://github.com/rails/rails/blob/d599b8000968047b4095dd8ff6c8ef10bb4ed462/activesupport/lib/active_support/duration.rb#L16-L28

2018
https://github.com/rails/rails/blob/ee708cf402ac9ad8bba4ad4808c01266433883a5/activesupport/lib/active_support/duration.rb#L113-L114

https://github.com/rails/rails/blob/ee708cf402ac9ad8bba4ad4808c01266433883a5/activesupport/lib/active_support/duration.rb#L266-L277

**Comment by eugeneius** [comment]
The message you quoted describes how converting a month into days requires you to specify _which_ month you're converting, while weeks or days can (almost) always be converted into the same number of days or hours, respectively. This is a property of the Gregorian calendar, independent of Rails' implementation.

The behaviour that led to `Numeric#years` and `Numeric#months` being deprecated, and which still exists today, is this:

```ruby
$ tools/console
irb(main):001:0> Time.now.beginning_of_year + 1.month
=> 2018-02-01 00:00:00 +0000
irb(main):002:0> Time.now.beginning_of_year + 1.month / 2
=> 2018-01-01 00:00:00 +0000
```

Which is caused by:

```ruby
irb(main):003:0> Time.now.beginning_of_year.advance(months: 1)
=> 2018-02-01 00:00:00 +0000
irb(main):004:0> Time.now.beginning_of_year.advance(months: 0.5)
=> 2018-01-01 00:00:00 +0000
```

Which in turn is caused by:

```ruby
irb(main):005:0> Date.civil(2018, 1, 1) >> 1
=> Thu, 01 Feb 2018
irb(main):006:0> Date.civil(2018, 1, 1) >> 0.5
=> Mon, 01 Jan 2018
```

[`Date#>>`](https://ruby-doc.org/stdlib-2.5.1/libdoc/date/rdoc/Date.html#method-i-3E-3E) doesn't support fractional months; allowing users to create durations that will behave incorrectly seems undesirable.

**Comment by jychen7** [comment]
@eugeneius thanks for your good insight of how [`advance`](https://github.com/rails/rails/blob/a0a1abb3c7942084111d87ae95837a83bcc794f6/activesupport/lib/active_support/core_ext/time/calculations.rb#L151-L186) work.

I think that may need to fix in another issue. Because it exists before current issue
```
> Time.now.beginning_of_year + 1.month / 2.0
=> 2018-01-01 00:00:00 +0000
```

current issue is target to fix
```
> 1.month
=> 1 month

> 1.month / 2.0
=> 0.5 months

> 0.5.month
Traceback (most recent call last):
        1: from (irb):20
NoMethodError (undefined method `month' for 0.5:Float)
```

**Comment by taleh007** [comment]
This issue is still alive.

**Comment by theblang** [comment]
Also still seeing this behavior, so I think this issue needs to be reopened. Mentioning @y-yagi since he / she labeled the issue.

**Comment by taleh007** [comment]
@y-yagi  In my humble opinion, we need to finish this issue (reopen and fix or write disclaimer and close)
