### ISSUE TITLE
Rollback database when db:seed fails

### ISSUE THREAD

**Issue by 100010** [rails/rails#33302]
If `rails db:seed`  command fails once, it is necessary to rebuild the database from the relation of validation etc,  because the data is made halfway.

This is very inefficient, so I want to roll back database  by default  if `rails db:seed`  fails,  like this.

```ruby:rails/activerecord/railties/databases.rake
task :seed do
  db_namespace["abort_if_pending_migrations"].invoke
  ActiveRecord::Base.transaction do
    ActiveRecord::Tasks::DatabaseTasks.load_seed
  end
end
````

How about this?
Thanks.

**Comment by y-yagi** [comment]
Since PR has already been created, let's track that.

**Comment by estani** [comment]
This is indeed interesting... what happened? Why did it never got merged? I got byte but this and have to recreate the schema in heroku... not pleasent indeed.

Work around: put the whole seed in a transaction block, but this makes in my opinion more sense, since half a seed is no seed at all (and seeds do tend to get outdated...)
