### ISSUE TITLE
 does not reset previous_changes for hasone entity after save 

### ISSUE THREAD

**Issue by katielim** [rails/rails#33374]
### Steps to reproduce
```ruby {.line-numbers}
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string "title", null: false
  end

  create_table :writers, force: true do |t|
    t.bigint "post_id", null: false
    t.string "name", null: false
  end

end

class Post < ActiveRecord::Base
  has_one :writer
end

class Writer < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.new
    post.title = 'Hello'
    writer = Writer.new
    writer.post = post
    writer.name = 'foo'
    post.save

    p "writer persisted? #{post.writer.persisted?}" #=> true

    post.title = 'Hello 2'

    post.save

    p post.previous_changes #=> {\"title\"=>[\"Hello\", \"Hello 2\"]}"
    p post.writer.previous_changes #=> {\"id\"=>[nil, 1], \"post_id\"=>[nil, 1], \"name\"=>[nil, \"foo\"]}"

    assert_equal false, post.writer.previous_changes.any?
  end
end

```
### Expected behavior
post.writer.previous_changes should be empty hash.

### Actual behavior
It's returning all attributes just like saving a new writer object.
If I call `post.writer.save` or `post.reload` before `p "writer persisted? #{post.writer.persisted?}" #=> true` line,
post.writer.previous_changes returns empty hash.

### System configuration
**Rails version**:
5.2
**Ruby version**:
2.4.3p205

**Comment by twitnithegirl** [comment]
This issue is similar to this one https://github.com/rails/rails/issues/23240

According to the guides it looks like this is the [expected behavior](http://guides.rubyonrails.org/association_basics.html#has-one-association-reference-when-are-objects-saved-questionmark)

Specifically

> If the parent object (the one declaring the has_one association) is unsaved (that is, new_record? returns true) then the child objects are not saved. They will automatically when the parent object is saved.

**Comment by katielim** [comment]
@twitnithegirl  I'm still a little confused. After the first `post.save`, I can see the changes in `post.writer.previous_changes`. but I'm expecting `post.writer.previous_changes` to be empty after second `post.save`

**Comment by twitnithegirl** [comment]
@katielim oh, I think I understand what you're saying now. Thank you for rephrasing.

Since you ran `post.save` the second time and nothing changed on `write` you expect for the `previous_changes` to be updated to `{}.`

If that's accurate I have 2 theories on this:
* `#save` on a `has_one` doesn't call `#save` on associations when there are are no changes to the association.
* if a `#save` _is_ being called on the association then  it just doesn't actually _do_ anything if there is nothing new to save and `previous_changes` is just referring to the last time a `#save` call actually resulted in a record getting an `update`

I'll dig in and let you know what I find out.

**Comment by rafaelfranca** [comment]
Yes, this is the expected behavior. The writer instance is only saved on the first `post.save` call, so, the `previous_changes` hash is related to the only save that happened on that model, the first one. Rails do not save object that don't need to be saved.

But, if you change the writer name as @twitnithegirl points out, it should get saved, but only if you set `:autosave` to `true` in the `has_one` association as the documentation explains.

http://guides.rubyonrails.org/association_basics.html#options-for-has-one-autosave.
