### ISSUE TITLE
rails guide rescue_from has an omnious warning

### ISSUE THREAD

**Issue by coldnebo** [rails/rails#33390]
The Rails guide doc on `rescue_from` has [an ominous warning](https://github.com/rails/rails/blame/5f5dc91140dd4513f3eee06d82618eedd31bb170/guides/source/action_controller_overview.md#L1173):

> Using rescue_from with Exception or StandardError would cause serious side-effects as it prevents Rails from handling exceptions properly. As such, it is not recommended to do so unless there is a strong reason.

But doesn't go into details about the 'serious side-effects' if you do have a strong reason to use this?

**Does it make sense to clarify what the serious side-effects of `rescue_from(StandardError,...)` could be?**

## Background

Looking at the source code, the rescue_from handlers are only executed as a result of [action processing](https://github.com/rails/rails/search?q=rescue_with_handler&unscoped_q=rescue_with_handler) (in controller, mailer, and jobs).

If we follow the warning and don't add a `rescue_from(StandardError,...)`, then StandardError raised would escape (via `|| raise`) to other middleware and so the side-effects might be things that process such exceptions (like development debugging).  If we ignore the warning and rescue StandardError, then those middlewares won't trigger.  So that could cause side-effects. 

Previous versions of the warning seem to point in this direction:

> **(e.g. you won't be able to see exception details and tracebacks during development).**
> **If you would like to dynamically generate error pages, see [Custom errors page](#custom-errors-page).**

We don't use tracebacks in production, so maybe the "serious side-effects" aren't too serious? But let's assume they are for a moment 👿 ...  why can't we just reraise to avoid this issue?

```ruby
rescue_from StandardError, with: :rescue_uncaught

def rescue_uncaught(ex)
  ...
  raise ex
end
```

Well, if we put some render code in there and then Rails tries render the 500 separately we might create a DoubleRenderError... so maybe there are more side-effects.

## Opinion

Implementing a [top-level error handler](https://en.wikipedia.org/wiki/Exception_handling#Uncaught_exceptions) is helpful when you want to do something like custom logging for every exception, but you don't want to go through your application and add `begin..rescue` clauses everywhere.

Then again, gems like [exception_notification](https://github.com/smartinez87/exception_notification) use middleware instead of a top-level `rescue_from` handler so they don't risk interfering with Rails error display.  Maybe this is a little cleaner?

There still has to be an assumption that some other middleware hasn't swallowed the error without reraising it before exception_notification has a chance to consume it.  So `rescue_from` with a reraise seems to be an ok solution if you don't want to write custom middleware.

**Comment by rafaelfranca** [comment]
Development debuging is not the only exception application that Rails has.

If you rescue from StandardError things like automatic the 404 for `ActiveRecord::NotFoundError` and `RoutingErrors` will not happen anymore, so now your application have to know about every single exception that the framework that raise and have special meaning.

Also, depending on the order, only the `StandardError` rescue will run and if you have a more specific exception handler it will never run, because `StandardError` is the parent of most of exceptions.

The serious side-effect is explained in that note "as it prevents Rails from handling exceptions properly", if you don't know that means probably you don't want to do it. I feel that explaining what it means will give people the false sensation that they understand the consequences and will want to do it. If anything I'd stronger that text to remove the "unless there is a strong reason".

**Comment by coldnebo** [comment]
Thanks @rafaelfranca , that's enough to convince me... there definitely be dragons here in any case.  In the apps I own, I tend not to use resource routes or ActiveRecord (we use a lot of REST services instead), so I forget that some of those semantics are in play during the controller-action context.  Regular 404's are unaffected because they are handled by routing outside the controller-action context.

It sounds like it is safer to implement a "top-level" error handler in middleware, correct?

Thanks!
