### ISSUE TITLE
Flash inconsistencies between redirect_to & render

### ISSUE THREAD

**Issue by CHTJonas** [rails/rails#33447]
My first Rails bug report so wish me luck! Here goes...

I seem to be observing inconsistencies in the way the flash is handled depending on whether I am using `redirect_to` or `render`.

### Steps to reproduce
Consider the following example in a hypothetical `VenuesController`:
```ruby
def create
  @venue = Venue.new(venue_params)
  if @venue.save
    alert = { class: 'success', message: "Added #{@venue.name}!" }
    flash[:alert] = alert
    redirect_to @venue
  else
    alert = { class: 'danger', message: @venue.errors.full_messages.first }
    flash.now[:alert] = alert
    render 'new'
  end
end
```

This generates Bootstrap alert messages which are rendered with:
```erb
<% if flash[:alert] %>
  <% if flash[:alert][:message].is_a?(String) %>
    <% message = flash[:alert][:message] %>
    <% classes = "alert alert-dismissible alert-#{flash[:alert][:class]}" %>
    <div class="<%= classes %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, message, :id => "flash_#{flash[:alert][:class]}" %>
    </div>
  <% end %>
<% end %>
```

### Expected behaviour
Lovely Bootstrap messages get rendered to the user. Both halves of the if/else on `@venue.save` should produce largely the same result when running `hash.inspect`. I would expect to see something like `@flashes={"alert"=>{:class=>"success", :message=>"Added XXX!"}}` or `@flashes={"alert"=>{:class=>"danger", :message=>"Name can't be blank"}}`.

### Actual behaviour
If `@venue.save` returns false then the expected behaviour is observed. However if validation passes then what I actually see in the flash is something like `@flashes={"alert"=>{"class"=>"success", "message"=>"Added XXX!"}}` ie. my hash symbols are being converted to strings, so the message won't get displayed.

### System configuration
**Rails version**: Rails 5.2.0
**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
**OS**: macOS High Sierra 10.13.6

Thanks in advanced.

**Comment by albertoalmagro** [comment]
Hi @CHTJonas, thanks for your report. I have being trying to reproduce this issue with a test and with and app I created using Rails 5.2.0 and Ruby 2.5.1, but bug doesn't show up. I get something like `{:class=>"success", :message=>"Added Bla!"}` in all situations.

Could you please submit an application/test that reproduces the problem?

**Comment by CHTJonas** [comment]
Hi @albertoalmagro thanks for getting back to me!

I can recreate what I think is a bug using the repo here https://github.com/CHTJonas/rails-bug. It's very very basic but http://127.0.0.1:3000/venues/new returns an error when no 'name' is entered, but returns no success message when one is entered. The console pops up so flash[:alert] is clearly set and evaluates to something like `{"class"=>"success", "message"=>"Added sea!"}` rather than `{:class=>"danger", :message=>"Name can't be blank"}`.

**Comment by CHTJonas** [comment]
Not sure if this helps:
![screen shot 2018-07-27 at 10 29 42](https://user-images.githubusercontent.com/17813061/43313482-15bdf0b0-9188-11e8-8b57-e38539579cc9.png)
![screen shot 2018-07-27 at 10 31 48](https://user-images.githubusercontent.com/17813061/43313564-56d9e4b4-9188-11e8-89e6-a2407106a90a.png)

**Comment by albertoalmagro** [comment]
Awesome @CHTJonas , thanks! I am now getting what you see. I will investigate this further in the afternoon 👍

**Comment by albertoalmagro** [comment]
Hi @CHTJonas, thanks for your patience.

The difference you are experiencing doesn't come because you are using `FlashHash` or `FlashNow`, but because of the different paths followed by `render` and `redirect_to` combined with your session storage settings.

When you call `render` the flash arrives to your next action as it is, without any further processing. However, when invoking `redirect_to` the flash is saved into the session, and here is where the tricky part comes. As you may now, default session storage in Rails is `CookieStore`, that means that on redirect, your session will be saved into a cookie and retrieved again later. When storing data into cookies considering how serialization affects your objects is important. Since Rails 4.1 default cookies serialization mechanism is `:json`  (see [this guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#cookies-serializer) for more information) The point is that JSON serialization is representing your hash as a String before encryption. After it is decrypted, keys are deserialized as a string, and there is where it "breaks".

Having said this, I would not consider this as a bug in Rails since the objects you can store and how you store them depend on your session storage settings. However, in order to avoid further confusion, I have added a NOTE in the documentation to warn about this. This note can be found in this PR #33465

**A solution for you:**
While you could change serialization to `:marshal`, I would recommend you to stick to `:json` (as this is Rails' core team recommendation) Instead, I would change the way you save and display your messages.

You don't need to stick to `:alert` or `:notice` as keys for your flash. Those are some common ones for which Rails has accessor methods set in place, but you can use others. In your case it would help to use the CSS class you want to display. That would be something like:

```ruby
flash[:success] = "Added #{@venue.name}!"
```

And then in the view:

```erb
<% flash.each do |message_type, message| %>
  <div class="<%= message_type %>"><%= message %></div>
<% end %>
```

I hope this helps you and the people that may read this later.

**Comment by CHTJonas** [comment]
Hi again @albertoalmagro - thanks for getting back to me! I've commented in the PR about my idea of storing objects in the flash. I think I'll use something along the lines of the suggestion you list, or just change my hashes so that the keys are strings instead of symbols. Is there a particular performance penalty for storing objects that aren't just simple strings in the flash?

**Comment by albertoalmagro** [comment]
Hi @CHTJonas, the only penalty you should have would be spending more time computing serializations, but I wouldn't be worried about that (provided that you don't store there a lot of stuff 😉 )

Having said that, I wouldn't recommend you storing objects in the Flash. This morning I was reading documentation about this and I found that the Flash module's author pointed out that only temporary primitive-types (String, Array, Hash) should be stored. Please check [ActionDispatch::Flash](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/flash.rb#L6 )'s documentation for more information.

**Comment by CHTJonas** [comment]
Fab ok thank you very much for your help! Since there is no bug and you've explained what's going on I'm going to mark this issue as 'closed'. Thanks for the help! 🏆
