### ISSUE TITLE
config.action_dispatch.cookies_rotations doesn't work as expected 

### ISSUE THREAD

**Issue by edzhelyov** [rails/rails#33503]
### Steps to reproduce

I want to use the keys rotation mechanism in Rails 5.2 to rotate the current secret_key_base with a new one. So I'm setting
```
config.action_dispatch.cookies_rotations.tap do |cookies|
  cookies.rotate :encrypted, "534534543543-old-cookie-value"
end
config.secret_key_base = 'ejwl3l23-new-cookie-value'
```

### Expected behavior
I expect the cookie to be preserved and the user to be still logged in with the old cookie.

### Actual behavior
The user is logged out and old cookie is not used.

### Debugging

I'm debugging the ActionDispatch cookies middleware and ActiveSupport::MessageEncryptor and I find that the encryptor is passed a generated secret:
```
secret = request.key_generator.generate_key(request.encrypted_cookie_salt, key_len)
sign_secret = request.key_generator.generate_key(request.encrypted_signed_cookie_salt)
```
while the one provided in the `rotate` configuration is passed directly. Which means that the rotated key doesn't contain the "real" old secret that was used in the beginning.

If I set the rotating values to the generated values:

```
config.action_dispatch.cookies_rotations.tap do |cookies|
  cookies.rotate :encrypted, "\x8B\xBD\xCD+\xF5S\x96-generated-old-key", "\x8B\xBD\xCD+\xF5S\x96-generated-signed-old-key"
end
```
the rotation works as expected.

But that's not the expected behavior and I would expect that I only provide the old key and everything is handled automatically behind. /cc @mikeycgto 
### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.3

**Comment by mikeycgto** [comment]
Thanks for reporting this and providing great details. Will look into this
soon and will keep you posted. Thanks again!

**Comment by edzhelyov** [comment]
At the moment if I want to configure it properly I need to set it as follow in `config/application.rb`:
```
_generator = ActiveSupport::KeyGenerator.new('old-key-secret', iterations: 1000)
config.action_dispatch.cookies_rotations.tap do |cookies|
  cookies.rotate :encrypted, _generator.generate_key('encrypted cookie', 32), _generator.generate_key('signed encrypted cookie')
end
```

**Comment by mikeycgto** [comment]
Looking back at the commit history, the `ActiveSupport::Messages::Rotator` was simplified to not be concerned with key generation with this commit: b5aa2e0c495b310cbef90b2185ef28cd00745b23. 

This unfortunately means that in order to rotate the key used for session cookies, one must currently deal with key generation manually, which is exactly what you described you had to do.

In the short-term, I can make a PR to update the docs and make this more clear for anyone trying to leverage this functionality now. In the long-term, we need to figure out a good way of rotating the secret key base within an entire application. This is a little tricky though, because this key base can be used by a variety of features and all these features will need to handle key rotation in order to not break on "old" messages regardless if they are encrypted or signed.

I apologize for the confusion here! I think it's reasonable for us to target Rails 6.0 with a app-wide secret key base rotation feature.

/cc @kaspth

**Comment by kaspth** [comment]
Yep, there's no app wide secret key base rotation yet. @mikeycgto 👍 on going for it for 6.0 if you have some ideas. Let's not update the docs yet if we're moving for a public API.
