### ISSUE TITLE
Nu Html Checker (W3C) change report_uri to report_to

### ISSUE THREAD

**Issue by Fudoshiki** [rails/rails#33561]
### Steps to reproduce

*content_security_policy.rb*
```ruby
Rails.application.config.content_security_policy do |policy|
  # Specify URI for violation reports
  policy.report_uri '/csp-violation-report-endpoint'
end
```

### Actual behavior
scan site with `https://validator.w3.org`

**Warning**: A draft of the next version of CSP deprecates report-uri in favour of a new report-to directive.

### System configuration
**Rails version**: Rails 6.0.0.alpha `https://github.com/rails/rails/tree/3000c1490565b3a21376d6444cb6fe24dfe4e383`

**Ruby version**: ruby 2.6.0dev (2018-08-07 trunk 64214) [x86_64-darwin18]

**Comment by y-yagi** [comment]
Your point is correct. `report-uri` directive is deprecated in CSP Level 3. 
https://www.w3.org/TR/CSP3/#changes-from-level-2 

However, major browsers do not yet support `report-to`, and now we need to use `report-uri`. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to#Browser_compatibility 
https://www.chromestatus.com/feature/5826576096690176 

I think that it is probably necessary to take some action by Rails 6, but I think that this is only after CSP Level 3 is published.
Therefore, this is not an issue but an intentional specification (at least for now). Therefore I close. Thanks.
