### ISSUE TITLE
MySQL schema/migration should default to CHARSET=utf8mb4

### ISSUE THREAD

**Issue by dhh** [rails/rails#33596]
Right now we're defaulting to the 3-char utf8 that leads to pain and suffering. We should default to CHARSET=utf8mb4. We should probably also default to COLLATION=utf8mb4.

**Comment by teitei-tk** [comment]
🍣 🍺

**Comment by yahonda** [comment]
I'm interested in this topic.  Let me provide which changes we need to consider.

#### utf8mb4 requires MySQL 5.5 or higher
 - Drop 5.1 support already EOLed
 - At least MariaDB 10.2 supports `utf8mb4` character set https://mariadb.com/kb/en/library/supported-character-sets-and-collations/
 
#### How to address "ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes" 

utf8mb4 character set requires 4 bytes for each character, which could easily cause "ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes" for Rails `string` data type which is mapped to `varchar(255)` type since 255 * 4 = 1020.

To address "Specified key was too long; max key length is 767 bytes", MySQL provides [innodb_large_prefix](https://dev.mysql.com/doc/refman/5.5/en/innodb-parameters.html#sysvar_innodb_large_prefix) which is false in MySQL 5.5 and 5.6 by default.  Also to set `innodb_large_prefix = true` requires `innodb_file_format=BARRACUDA` and `ROW_FORMAT=DYNAMIC or COMPRESSED`. They are not default value with MySQL 5.5 and 5.6.

If Rails 6 can support MySQL 5.7 or higher, we do not have to worry about "ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes" error since the default max key length is already 3072 byte, but it would be too early to drop support for MySQL 5.5 and 5.6.

#### Need to find which collation should be used by default

There are many collations which can work with utf8mb4 character set.

```sql
mysql> select collation_name from information_schema.collations where character_set_name = 'utf8mb4';
+----------------------------+
| collation_name             |
+----------------------------+
| utf8mb4_general_ci         |
| utf8mb4_bin                |
| utf8mb4_unicode_ci         |
| utf8mb4_icelandic_ci       |
| utf8mb4_latvian_ci         |
| utf8mb4_romanian_ci        |
| utf8mb4_slovenian_ci       |
| utf8mb4_polish_ci          |
| utf8mb4_estonian_ci        |
| utf8mb4_spanish_ci         |
| utf8mb4_swedish_ci         |
| utf8mb4_turkish_ci         |
| utf8mb4_czech_ci           |
| utf8mb4_danish_ci          |
| utf8mb4_lithuanian_ci      |
| utf8mb4_slovak_ci          |
| utf8mb4_spanish2_ci        |
| utf8mb4_roman_ci           |
| utf8mb4_persian_ci         |
| utf8mb4_esperanto_ci       |
| utf8mb4_hungarian_ci       |
| utf8mb4_sinhala_ci         |
| utf8mb4_german2_ci         |
| utf8mb4_croatian_ci        |
| utf8mb4_unicode_520_ci     |
| utf8mb4_vietnamese_ci      |
| utf8mb4_0900_ai_ci         |
| utf8mb4_de_pb_0900_ai_ci   |
| utf8mb4_is_0900_ai_ci      |
| utf8mb4_lv_0900_ai_ci      |
| utf8mb4_ro_0900_ai_ci      |
| utf8mb4_sl_0900_ai_ci      |
| utf8mb4_pl_0900_ai_ci      |
| utf8mb4_et_0900_ai_ci      |
| utf8mb4_es_0900_ai_ci      |
| utf8mb4_sv_0900_ai_ci      |
| utf8mb4_tr_0900_ai_ci      |
| utf8mb4_cs_0900_ai_ci      |
| utf8mb4_da_0900_ai_ci      |
| utf8mb4_lt_0900_ai_ci      |
| utf8mb4_sk_0900_ai_ci      |
| utf8mb4_es_trad_0900_ai_ci |
| utf8mb4_la_0900_ai_ci      |
| utf8mb4_eo_0900_ai_ci      |
| utf8mb4_hu_0900_ai_ci      |
| utf8mb4_hr_0900_ai_ci      |
| utf8mb4_vi_0900_ai_ci      |
| utf8mb4_0900_as_cs         |
| utf8mb4_de_pb_0900_as_cs   |
| utf8mb4_is_0900_as_cs      |
| utf8mb4_lv_0900_as_cs      |
| utf8mb4_ro_0900_as_cs      |
| utf8mb4_sl_0900_as_cs      |
| utf8mb4_pl_0900_as_cs      |
| utf8mb4_et_0900_as_cs      |
| utf8mb4_es_0900_as_cs      |
| utf8mb4_sv_0900_as_cs      |
| utf8mb4_tr_0900_as_cs      |
| utf8mb4_cs_0900_as_cs      |
| utf8mb4_da_0900_as_cs      |
| utf8mb4_lt_0900_as_cs      |
| utf8mb4_sk_0900_as_cs      |
| utf8mb4_es_trad_0900_as_cs |
| utf8mb4_la_0900_as_cs      |
| utf8mb4_eo_0900_as_cs      |
| utf8mb4_hu_0900_as_cs      |
| utf8mb4_hr_0900_as_cs      |
| utf8mb4_vi_0900_as_cs      |
| utf8mb4_ja_0900_as_cs      |
| utf8mb4_ja_0900_as_cs_ks   |
| utf8mb4_0900_as_ci         |
| utf8mb4_ru_0900_ai_ci      |
| utf8mb4_ru_0900_as_cs      |
+----------------------------+
73 rows in set (0.00 sec)

mysql>
```

I've pushed [a topic branch](https://github.com/yahonda/rails/tree/use_utf8mb4) to use the utf8mb4 character set.

**Comment by jeremy** [comment]
Excellent, @yahonda. Would you create a PR for the topic branch? We may proceed there.

**Comment by dhh** [comment]
I think it's completely reasonable to require 5.7+. That version is from
2013. And a major Rails version change is a good time to do it.

**Comment by dhh** [comment]
Also worth noting that for MySQL 8+, the defaults are utf8mb4 and the
collation is utf8mb4_800_ci_ai. So probably makes sense to just standardize
on those values for 5.7 as well.

**Comment by georgeclaghorn** [comment]
@dhh, `utf8mb4_0900_ci_ai` is new to MySQL 8, so we should probably default to `utf8mb4_general_ci` or `utf8mb4_unicode_ci` for 5.7.

**Comment by dhh** [comment]
Ah, gotcha. Yeah, whatever is closer sounds good as a default 👍

**Comment by kamipo** [comment]
`utf8mb4_general_ci` and `utf8mb4_unicode_ci` have an well know issue as Sushi-Beer issue in MySQL world.

https://bugs.mysql.com/bug.php?id=76553
https://gist.github.com/kamipo/61ee662ee0b1127f0989
https://mysqlserverteam.com/sushi-beer-an-introduction-of-utf8-support-in-mysql-8-0/

`utf8mb4_unicode_ci` is also a known issue as Haha-Papa issue means Mother-Father issue in Japanese. We had reverted the `utf8_unicode_ci` by default to prevent the issue in the past.

#20000 #22061

New Unicode collations in MySQL 8.0 were introduced to solve the Unicode issues.
As a MySQL DBA, I'm not recommend to force older collation by default.

**Comment by dhh** [comment]
Ryuta, I don't think we should force collation, just provide the most
reasonable default. People should of course be able to change that default.
Which default would you recommend for 5.7?

**Comment by kamipo** [comment]
Since proper collation is language dependent (that is the reason that Unicode provide multi level comparison), I personally would not like to provide any collation by default.

But "Which collation we should use in MySQL?" is FAQ for MySQL DBA.

I basically answer "Please consider using default collation (`utf8mb4_general_ci` in MySQL 5.7 case). If it has any issue for your use case (Sushi-Beer issue, etc), using `utf8mb4_bin` might avoid that issue.".

**Comment by dhh** [comment]
I understand that someone who's going to know everything about MySQL and
collation is going to make a better choice than a default, but not having a
default just means that most people will use whatever is the default in 5.7
standard settings. Unless that answer is the correct answer, I don't think
we're helping anyone by not providing a default.

I'd be surprised if not 90%+ of all Rails applications target English as
their primary language. So I think the best collation for the English
language is the best default. Followed up with a clear explanation of how
to change that.

**Comment by georgeclaghorn** [comment]
I think part of what @kamipo’s saying (please correct me if I’m wrong) is that we can leave it up to MySQL to choose a collation when none is specified, which is what we do now. It has defaults of its own.

**Comment by dhh** [comment]
Right, I get that, I'm just thinking that most people do not change the
collation that comes with MySQL. So if the default in MySQL 5.7 isn't a
good default, then we should set our own, such that most people get the
best combination of charset/collation without having to manually configure
either Rails or MySQL.

**Comment by rafaelfranca** [comment]
I think this was fixed by https://github.com/rails/rails/pull/33608. I reopened to remove the `stale` tag.
