### ISSUE TITLE
#to_query lexicographical sort regression

### ISSUE THREAD

**Issue by latortuga** [rails/rails#33606]
### Steps to reproduce

Hash#to_query (maybe something with Array#to_query ?) no longer returns a lexicographically sorted list of params. This is a regression in 5.2.1 and was working in 5.2.0.

Note that it appears to be related to the Array, because a deeply nested hash still works fine. When I introduce arrays though, the sorting fails.

```rb
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activesupport", "= 5.2.1"
end

require "active_support"
require "active_support/core_ext/array"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_lexico_sort
    hash = { a: [{ a: 1, z: 1 }] }
    other = { a: [{ z: 1, a: 1 }] }

    assert_equal hash.to_query, other.to_query
  end
end
```
This test passes on 5.2.0 and fails on 5.2.1. We use this for computing request signatures so it's rather important that it works.

**Rails version**: 5.2.1
**Ruby version**: Tested on 2.4.2

**Comment by latortuga** [comment]
Did a `git bisect` and 73df2b3be452beb77b37382cedb0b29f742ef390 is the responsible commit.

**Comment by Edouard-chin** [comment]
Good point, I should have added a changelog entry when making the change, it slipped out of my mind.

Since the shipped on 5.2.1 has already sailed, we can introduce a flag and restore the previous behavior with a proper deprecation warning. Something like

```ruby
config.to_query_lexicographycally_sorted = true

def to_query
if config.lexicographycally_sorted
  <previous_behavior>
   deprecation_warning
else
  <current_behavior on 5.2>
end
```

WDYT @matthewd ?

**Comment by latortuga** [comment]
So the intended behavior is really to just give up inside arrays? Hashes inside arrays are sortable and the documentation of `#to_query` is lying about lexicographical sorting if that's the case.

**Comment by Edouard-chin** [comment]
Yes this is the intended behavior

**Comment by matthewd** [comment]
I'd love to see a patch that _doesn't_ give up inside arrays... but that also doesn't fail [the new test](https://github.com/rails/rails/pull/33341/files#diff-9b6c67c61e7e8a25d636c0be2eb73504R80). 

The change was backported because it is a bug fix. And by my measure, "entries sometimes move between hashes in an array" is a bigger bug than "hashes inside an array aren't sorted". Regardless, the ideal situation would be one in which both are good (and in which we have tests to enforce both -- this change didn't involve breaking/changing any existing test around the sorting-within-array behaviour, which it seems it should've, because that is indeed documented).

Going out of your way to _edit in_ how disappointed you are that a bugfix had a bug is not, however, super motivating.

**Comment by latortuga** [comment]
@matthewd you're right, I got carried away. I apologise for being
antagonistic about this.

I rely on the great work y'all do on this project every day and greatly
appreciate all your work.
