### ISSUE TITLE
Replace use of whitelist with allowlist and blacklist with denylist

### ISSUE THREAD

**Issue by dhh** [rails/rails#33677]
Per https://twitter.com/dhh/status/1032050325513940992, I'd like for Rails to set a good example and tone by using better terminology when we can. An easy fix would be to replace our use of whitelist with allowlist and blacklist with denylist.

We can even just use them as verbs directly, as we do with the former terms. So something is allowlisted or denylisted.

I took a quick look and it seems like this change is mostly about docs. We only have one piece of the code that I could find on a search that uses the term whitelist with `enforce_raw_sql_whitelist`. Need to consider whether we need an alias and a deprecation for that.

**Comment by shalvah** [comment]
Good intentions, but I doubt there's any relation of the origin of the terms blacklist/whitelist to race. There are many idioms and phrases in the English language that make use of colours without any racial backstories.
I haven't met any black person (myself included) who were ever offended by the use of "blacklist".

**Comment by praveenperera** [comment]
I find this stupid. I would focus on something important instead of virtue signaling.

**Comment by felixalias** [comment]
At least [one source from a search](https://www.etymonline.com/word/blacklist) suggests the word had its origins around union members.

**Comment by dhh** [comment]
Regardless of origin, allow/deny are simply clearer terms that does not require tracing the history of black/white as representations of that meaning. We can simply use the meaning directly.

**Comment by glaszig** [comment]
1. [etymology is quite important](
https://www.quora.com/Is-the-term-blacklist-racist?share=1). in the end, we might consider plain words „black“ and „white“ racist and enter the realms of newspeak which i figure you especially, @dhh, are familiar with.

2. “allow/deny are simply clearer terms” — now that’s an actual, technically useful argument.

3. can we please stop jumping onto political bandwagons? i am here for the sanity.

**Comment by Alamoz** [comment]
The terms Blocklist and Clearlist are sometimes used in place of Blacklist and Whitelist.

**Comment by robotdana** [comment]
I like the idea of this, but the names seem unwieldy to my ears, 

perhaps instead of e.g. TYPE_WHITELIST => TYPE_ALLOWLIST, => ALLOWED_TYPES etc

**Comment by cbarton** [comment]
One could also argue that in color theory, black is the absence of color (photons which make up the spectrum) and white is the accumulation of all colors. Thus a blacklist is a list which contains elements that are to be absent and a whitelist to be allowed...

**Comment by bitmonk** [comment]
I think this is a great idea, I have proposed internally at multiple companies I've worked at changing master/slave and blacklist/whitelist to leader/replica and allowlist/denylist, if only because in an industry with poor representation it feels incredibly overt to be standing in a room full of mostly white people using these terms outloud.

It doesn't matter what the origin or intent of this was, or whether people can find a narrow lens through which to see it as not a problem.  Consider using these terms in a coding or systems interview with someone you have just met.

I understand that some black people may not consider these terms offensive, but I would rather someone not want to work with me because they think I am too politically correct than because they think I am too insensitive and blind.

@minaslater thanks for beating me to the first PR on this. :) 💯

**Comment by 9jaswag** [comment]
I think the question here should be: is replacing `whitelist` and `blacklist` with `allowlist` and `denylist` a better option? If presented with the word `blacklist` and `denylist`, which is most likely self-explanatory as to the action to be performed?

**Comment by huysentruitw** [comment]
They should stop selling black or white cars!

**Comment by tomhoad** [comment]
40% of the world's rubies are known to be blood rubies.

Therefore, I propose renaming Ruby to something else, because the word Ruby is offensive to me.

**Comment by rafaelfranca** [comment]
A quick search and replace in the codebase shows that all entries for those words were already changed. I'll close this issue.
