### ISSUE TITLE
If a model's name is declared with a suffix ending in "che", the "e" in related controller's variables are deleted

### ISSUE THREAD

**Issue by floriancochard** [rails/rails#33688]
### Steps to reproduce
Start a new project with --api flag:
`new rails project --api `
Replace `config/application.rb` with this content:

```
require_relative 'boot'
require "rails"

require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
require "rails/test_unit/railtie"

Bundler.require(*Rails.groups)

module TestDir
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.2

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.

    # Only loads a smaller set of middleware suitable for API only apps.
    # Middleware like session, flash, cookies can be added back manually.
    # Skip views, helpers and assets when generating a new resource.
    config.api_only = true

    config.app_generators.scaffold_controller = :scaffold_controller

    # Middleware for ActiveAdmin
    config.middleware.use Rack::MethodOverride
    config.middleware.use ActionDispatch::Flash
    config.middleware.use ActionDispatch::Cookies
    config.middleware.use ActionDispatch::Session::CookieStore

  end
end
```

Eventually, create a scaffold with any model's name **ending in "che"** (e.g., Qui**che**, Whateveri**che**, Ni**che**, Ab**che**, etc.):
`rails g scaffold Whateveriche title:string description:string`

### Expected behavior
The whateveriche_controller.rb should have variables declared as @whateveriche.

### Actual behavior
Instead, "e" in @whateveriche are deleted as shown below:

```
class WhateverichesController < ApplicationController
  before_action :set_whateverich, only: [:show, :update, :destroy]

  # GET /whateveriches
  def index
    @whateveriches = Whateveriche.all

    render json: @whateveriches
  end

  # GET /whateveriches/1
  def show
    render json: @whateverich
  end

  # POST /whateveriches
  def create
    @whateverich = Whateveriche.new(whateverich_params)

    if @whateverich.save
      render json: @whateverich, status: :created, location: @whateverich
    else
      render json: @whateverich.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /whateveriches/1
  def update
    if @whateverich.update(whateverich_params)
      render json: @whateverich
    else
      render json: @whateverich.errors, status: :unprocessable_entity
    end
  end

  # DELETE /whateveriches/1
  def destroy
    @whateverich.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_whateverich
      @whateverich = Whateveriche.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def whateverich_params
      params.require(:whateverich).permit(:title, :description)
    end
end
```
This leads to additional problems such as uninitialized constant, dependencies errors, etc.

### System configuration
**Rails version**:
5.2.1
**Ruby version**:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by sikachu** [comment]
This behavior is due to Rails' inflection rule, based on https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb.

So, Rails assumes that the resource name `Whateveriche` is a singular word. In order to make a controller name, it calls `pluralize` on that word, and we get `Whateveriches`. However, to make a singular resource name, instead of using the original word that got passed in, we call `singularize` on `Whateveriches`, resulting in `-es` got removed.

@matthewd I feel like we're on to something here. Should we use the singular version that got passed in instead of going [input] -> pluralize -> singularize?

**Comment by matthewd** [comment]
@sikachu I'm dubious that you can, in general, survive with a model name that only correctly pluralizes in one direction. While this might be a case where it could pass the 'original' through instead of double-converting, I'm confident there are places that unavoidably start with each form respectively (`has_many` comes to mind for having to choice but to singularize)... so I'm not sure it's worth trying to fix here.

What _could_ be an interesting avenue, would be to round-trip the name supplied to the generator, and panic if it doesn't make it through intact.
