### ISSUE TITLE
rails-ujs cleans up url line arguments from ajax get requests originated from a form

### ISSUE THREAD

**Issue by andres** [rails/rails#33716]
https://github.com/rails/rails/blob/e2d8a2ccfd3b0d2030920346a2ff0cad93fcb188/actionview/app/assets/javascripts/rails-ujs/features/remote.coffee#L34

Bug or feature?

The referenced line cleans up parameters from the url, 
The subsequent calls to FormData(element) on line 37
or to serializeElement(element, button) on line 40
do not replace the ?key=value of the url into the "data"
thus losing any reference on the url args

We had some old code with button_to that sends as GET and uses parms.
button_to("whatever", this_url(key: :value), method: 'GET'
and observed this behavior when upgrading to rails-ujs

### Steps to reproduce
Generate an ajax form with button_to and method GET that uses a get method and have some extra params in the url
When the the rails ujs util form triggers the submit, the params on the url go away.

### Expected behavior
Either
1./ even if it's a bad practice, the url should be respected and not sanitized
2./ or if it's sanitized, the params should be placed in the "data"

### Actual behavior
params on the url are cleaned up,

### System configuration
Rails 5.1.6
Ruby 2.4.3

**Comment by y-yagi** [comment]
This is intentional behavior with tests as well.
https://github.com/rails/rails/blob/6d5eefd453c641c317f3cdfa1286f07cfc5b11e7/actionview/test/ujs/public/test/call-remote.js#L169-L186 

> observed this behavior when upgrading to rails-ujs 

Does this mean that this worked with `jquery-rails`?

**Comment by andres** [comment]
Thank you for pointing to the tests. It's a feature then. Yes, it worked until we included rails-ujs.

**Comment by avit** [comment]
> Does this mean that this worked with jquery-rails?

Yes it did and I'm running into the same issue now. [This][1] is where things changed. The code moved a few times since then but maybe @liudangyi remembers why we remove all the query params instead of merging?

The comment on [this commit][2] says _"Allow parameters in both query string and data-params"_ but that seems to be the opposite of what it's doing. Is it actually a well-tested bug?

(The "develop" branch linked here didn't land into rails/jquery-ujs, this was part of when it was moved directly into rails/rails/actionview.)


[1]: https://github.com/liudangyi/jquery-ujs/commit/50dc60adcf0526194338c848043a114971b746f1#diff-353b73ab238662d5421eaa9c5ad8bc9d82db2a615cebfae8054b72d70d9e24f4L19-L21
[2]: https://github.com/liudangyi/jquery-ujs/commit/0d2fb10b7f4a48c750db01ab1b9b074139522436

**Comment by liudangyi** [comment]
I cannot remember my decision 5 years ago but my hypothesis is that maybe I was mimicking the behavior of a normal form submission without Ajax enabled?
