### ISSUE TITLE
to_yaml support for ActiveSupport::TimeWithZone class

### ISSUE THREAD

**Issue by ritikesh** [rails/rails#33865]
I noticed that this [commit](https://github.com/rails/rails/commit/b65bdb1527dbf42d94e5722f6764cebac73d103c#diff-3497a506c921a3a3e40fd517e92e4fe3) removed the to_yaml method for `ActiveSupport::TimeWithZone` but with no references of why this was removed. Can we add this back? This is causing issue when saving timezone instances in serialised fields in Rails 4.2.10. It works as expected in Rails 3.

### Steps to reproduce

Assuming model Post has a serialised field called options, trying the below saves a random YAML dump of the class itself.

post.options = {last_synced_time: Time.zone.now }
post.save

### Expected behavior
It should save the last_synced_time in utc - This is what happens in Rails 3

### Actual behavior
random YAML dump of ActiveSupport::TimeWithZone

### System configuration
**Rails version**: 4.2.10

**Ruby version**: 2.3.7

**Comment by bogdanvlviv** [comment]
> I noticed that this commit removed the to_yaml method for ActiveSupport::TimeWithZone but with no references of why this was removed.

You can read info why this was removed in https://github.com/rails/rails/pull/4298.

We don't support 4.2 anymore, please read [Maintenance Policy for Ruby on Rails](https://edgeguides.rubyonrails.org/maintenance_policy.html).

**Comment by rafaelfranca** [comment]
Even in Rails 3, if you were using psych to serialize yaml only super was being called. We kept the same behavior we only remove special case for syck because it is deprecated. If you also look the implementation before it was removed it didn't special case to return UTC, and I don't think it should. This is not a bug. The behavior is to return the dump of the `ActiveSupport::TimeWithZone` in the timezone that it is.
