### ISSUE TITLE
`count` return incorrect value when using JOIN and GROUP_BY both table IDs

### ISSUE THREAD

**Issue by ledowong** [rails/rails#33988]
I have created a sample project to explain, please take a look. Many thanks.
https://github.com/ledowong/sql_count

### System configuration
**Rails version**:
5.2.1
4.2.10

**Ruby version**:
2.4.4p296
2.3.5

**Comment by petestreet** [comment]
Hi @ledowong, I discovered a few things after running your example: 

It looks like generating the `SELECT COUNT(*) ...` query on `.size` for non-loaded collections goes back to the [_reeeeally_ early days of activerecord](https://github.com/rails/rails/commit/fe8fb574c06156ca7eef7367c85bd12991948806). In this case, `.group` is generating the inner join statement that returns a relation of the Products which have associated Skus (of which there are only four products, as it appears in the hash-like returned value), and `size` is returning the four elements of that object correctly.  

However, `.load` returns the result of [`exec_queries`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L650-L674) on the `Sku` relation. In this case there are 5 skus joined with a product (since all Sku has a foreign key constraint on Product), so calling `.size` on the result of what load returns gives us 5 back.

Which is to say, this all looks like expected behavior. `Sku.joins(:product).size` (without the chained `.group(...)` call) returns 5 here (count of Skus joined on Products, which is all of them), not the hash-like object with 4 entries.

**Comment by ledowong** [comment]
Thanks for your detail reply, I understand that is by design now.
I add kaminari, the pagination gem, in my sample code.
kaminari use `count` to calculate total page, which lead to incorrect result.
I can't use `.load` to solve this problem, due to million of records.
Is there any workaround that don't need to fetch all records to memory, but return a "correct" count?
