### ISSUE TITLE
expanded_key and array inconsistency

### ISSUE THREAD

**Issue by daniel-rikowski** [rails/rails#34000]
### Steps to reproduce

When arrays are used as cache keys the expanded key is generated using `to_param` if it contains only one element. If there is more than one element, `cache_key` is called.

This can be reproduced using anything which eventually ends up in `ActiveSupport::Cache::Store`, e.g. in the Rails console using `ActiveSupport::Cache::Store.new.send(:expanded_key, [...])` or in views using `cache [...] do`.

### Expected behavior

Using `ActiveSupport::Cache::Store.new.send(:expanded_key, key)` with various keys should produce the following results

key | expanded_key
----|------
<span>@</span>article | articles/1-20180217221046452912
[<span>@</span>article] | articles/1-20180217221046452912
[<span>@</span>article, <span>@</span>article] | articles/1-20180217221046452912/articles/1-20180217221046452912

### Actual behavior

This is generated instead:

key | expanded_key
----|------
<span>@</span>article | articles/1-20180217221046452912
[<span>@</span>article] | 1
[<span>@</span>article, <span>@</span>article] | articles/1-20180217221046452912/articles/1-20180217221046452912

### System configuration
**Rails version**: 5.2.1
**Ruby version**: 2.5.1 [x64-mingw32]

### Comments

This is the code which performs the array handling:
https://github.com/rails/rails/blob/ff1b4eb35ecac420d71c552402e1192551413a5f/activesupport/lib/active_support/cache.rb#L642-L647

The code was introduced with https://github.com/rails/rails/commit/f6d2efa9e8d597832510fd20e3b8fee87f6e6df6

IMHO the `if` clause should be gone (as it was before) or - if it is performance criticial - the `else` line should be `key = expanded_key(key.first)`

**Comment by schneems** [comment]
Thanks for the issue Daniel. This is relevant to my interests recently.

A short term fix (I think) would be to call expand key again on the one element.

I think the desired behavior here in the 1 element case is to be a bit faster since to_param allocates and the collect call allocates.

Switching to a class based key expansion as in my WIP PR I think gets rid of this issue as well (though in that case it would appear that it technically does not preserve backwards compat as it does not preserve this bug).

I’m out in Hong Kong this week but I’ll be back next week.

**Comment by y-yagi** [comment]
Fixed by #34005

**Comment by schneems** [comment]
Thanks for the issue close @y-yagi and thanks for the issue @daniel-rikowski ! If you haven't checked the linked PR take a look. This bug dates back to a commit by Yehuda in 2009. It was fixed but then lost somewhere along the way. Interesting stuff.

**Comment by daniel-rikowski** [comment]
Very nice! Thank you @tgturner and @schneems for fixing this.
