### ISSUE TITLE
Lock doesn't work with Postgresql

### ISSUE THREAD

**Issue by emn178** [rails/rails#34048]
### Steps to reproduce
SQLite is ok, but Postgresql doesn't work.

Sample project
https://github.com/emn178/lock-test

Please see
https://github.com/emn178/lock-test/blob/master/test/models/balance_test.rb

### Expected behavior
It should be locked.

### Actual behavior
It doesn't work.

### System configuration
**Rails version**:
5.2.1
5.1.4+

**Ruby version**:
2.3.4

**Postgresql version**
9.6.3

**Comment by Slike9** [comment]
Hi, @emn178. For locking take effect in https://github.com/emn178/lock-test/blob/master/test/models/balance_test.rb, the code inside the threads should use explicit transactions. E.g.
```ruby
Balance.transaction do
  o1 = Balance.lock.find(o.id)
  p o1.value
  o1.value -= 1
  o1.save
end
```

By default, tests are run with `use_transactional_tests = true`, so a test example is wrapped in a transaction. The threads in the first test example did not lock each other because they were running in the same transaction. Using explicit transactions fixes it. Saying strictly, synchronized access to DB-connection object takes place there, not DB-locks. Postgres does not support nested transactions. Wrapping the code with `begin_transaction` and `commit_transaction` instead wouldn't help with the problem in the test.

The second example in https://github.com/emn178/lock-test/blob/master/test/models/balance_test.rb passed because `with_locking` wraps the block in a transaction https://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html#method-i-with_lock.

But what about running the code not in tests?

From https://www.postgresql.org/docs/9.6/static/tutorial-transactions.html
> PostgreSQL actually treats every SQL statement as being executed within a transaction. If you do not issue a BEGIN command, then each individual statement has an implicit BEGIN and (if successful) COMMIT wrapped around it.

So, if the code had run not in tests (had not been wrapped in a transaction), `o1 = Balance.lock.find(o.id)` and `o2 = Balance.lock.find(o.id)` would have executed in such implicit transactions, releasing the locks immediately, and the updates wouldn't be synchronized neither. Explicit transactions are also needed there.

**Comment by y-yagi** [comment]
@emn178
As explained in @Slike9, an explicit transaction is required. Please fix your code.  

@Slike9 
Thanks for your help!
