### ISSUE TITLE
ActiveRecord::Relation#merge replacing where_values is not documented

### ISSUE THREAD

**Issue by faucct** [rails/rails#34176]
Hello. This behaviour happened to be a surprise for me, though while browsing through specs I have found that it was intended.
We should either change `#merge` behaviour, either have something like `ActiveRecord::Relation#and` behaving the way I expected `#merge` to.
I also expect association scopes behave the same way, but they are using merge.

### Steps to reproduce

```ruby
puts Plan.where(id: 1).merge(Plan.where(id: 2)).to_sql
```

### Expected behavior
```sql
SELECT * FROM "plans" WHERE "id" = 1 AND "id" = 2
```

### Actual behavior
```sql
SELECT * FROM "plans" WHERE "id" = 2
```

**Comment by pixeltrix** [comment]
@faucct thanks for the report - whilst your expected behaviour is what chaining two `where` methods together gives you it's not really helpful since there aren't many records that will have id=1 and id=2 :-)

So we could add in logic to check the where values when merging and convert them to Arel conditions but since it's always going to result in an empty set it seems a little pointless. I wonder whether just documenting this behaviour is the better option? @kamipo what do you think?

**Comment by seteen** [comment]
related to https://github.com/rails/rails/issues/33501

**Comment by faucct** [comment]
@pixeltrix, of course real examples can be more complicated:

```ruby
Plan.where(id: ExternalMapping.select(:plan_id)).merge(Plan.where(id: Phase.select(:plan_id))
```

**Comment by pixeltrix** [comment]
@faucct but where you're doing a equality comparison for a column you'll never get a result where `column = A AND column = B` - it's only possible with range comparisons, e.g. `Plan.where(id: 1..10).merge(Plan.where(id: 5..15))` and that seems to work correctly already:

```
>> User.where(id: 1..10).merge(User.where(id: 5..15)).to_sql
=> "SELECT users.* FROM users WHERE users.id BETWEEN 1 AND 10 AND users.id BETWEEN 5 AND 15"
```

**Comment by faucct** [comment]
Filters by subquery get replaced.
I don’t think that this needs any euristics: the result should be predictable. If user gets a conflicting set of filters when merging relations which are coming from some other code then so be it.
