### ISSUE TITLE
`fresh_when` fails when passed a collection with a `group` clause

### ISSUE THREAD

**Issue by yasyf** [rails/rails#34234]
### Steps to reproduce

```ruby
collection = Thing.joins(:other).group('things.id')
if stale?(collection)
  render json: collection
end
```

### Expected behavior
`stale?` and therefore `fresh_when` works as intended 

### Actual behavior
`collection.maximum(:updated_at)` returns a hash, which then causes an error when you try to assign it to `response.last_modified`

### System configuration
**Rails version**:
5.2.1
**Ruby version**:
2.5.1

**Comment by senny** [comment]
Hi @yasyf

Looking at this issue revealed several things to consider. The use of `group` without an aggregate function is problematic. The [documentations indicates](https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-group) the following behavior:

```ruby
User.group(:name)
# => [#<User id: 3, name: "Foo", ...>, #<User id: 2, name: "Oscar", ...>]
```

While this behavior is true for SQLite, it will not work for PostgreSQL and MySQL (only recent versions) and Oracle. A simple group call without the use of an aggregation function will fail like this:

```ruby
Developer.group(:name)
```

**mysql:**
```
ActiveRecord::StatementInvalid: Mysql2::Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'activerecord_unittest.developers.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

**postgresql:**
```
ActiveRecord::StatementInvalid: PG::GroupingError: ERROR:  column "developers.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "developers"."id", "developers"."name", "developers"....
```

Given that `group` without an aggregation does not work for most current databases, I don't think we should add support to `stale?` (more specifically `fresh_when`).

To address your problem, I would suggest to change the relation. Either by only adding the `group` after calling `stale?` (inside the conditional) or by using `distinct` instead of `group`.

Given the narrow support of `group` without the use of an aggregation function, it would probably be a good idea to update the docs.
