### ISSUE TITLE
ActiveSupport Time#to_json strange behavior

### ISSUE THREAD

**Issue by zw963** [rails/rails#34315]
### Steps to reproduce

```rb
Time.now.to_s
# => "2018-10-25 06:55:03 -0700", this is expected result
Time.now.to_json
# => "\"2018-10-25 06:55:08 -0700\"", this is expected result too.
require 'active_support/all'
# => true
Time.now.to_json
# => "\"2018-10-25T06:55:47.949-07:00\"", this is unexpected result
```

### Expected behavior
Time#to_json should same as standard #to_json result.

### Actual behavior
Time#to_json return a strange format (not iso8601)
after require 'active_support/all'

### System configuration
**Rails version**:
5.2

**Ruby version**:
2.5.1

**Comment by GeniusStorm** [comment]
If you look at the activesupport framework code https://github.com/rails/rails/blob/3f8b1353c64825fb665f3ab0c06d3616dc56b6fe/activesupport/lib/active_support/time_with_zone.rb#L155

ActiveSupport defaults to json standard time format which does confirm to ISO 8601. 
You are seeing that result because `ActiveSupport.use_standard_json_time_format = true` by default
If you want the result in "2005/02/01 05:15:10 -1000" then you can try setting `ActiveSupport.use_standard_json_time_format = false`

**Comment by y-yagi** [comment]
All of these are expected behavior as documented. 
Rails `to_json` has returned the correct value as ISO 8601 format. 
I do not know why `Time#to_json` of `json` gem seems to be in a different format. By the way, `DateTime#to_json` is ISO 8601 format. 

```ruby
require 'date'
require 'json' 

Time.now.to_json
# => "\"2018-10-27 17:59:37 +0900\""
DateTime.now.to_json 
# => "\"2018-10-27T17:59:37+09:00\"" 
```
Anyway, I think that there is nothing to do with Rails. Thanks.

**Comment by zw963** [comment]
@y-yagi , why close this issue? , when disable ` ActiveSupport.use_standard_json_time_format = false`,
change default date format to `2018/10/24 10:10:10 +0800`, this is a expected behavior too?

**Comment by y-yagi** [comment]
This is a expected behavior.  
If benefit by changing this for user, may be able to change it. But that is a feature request. We don't take feature request on the issue tracker.
