### ISSUE TITLE
Updating password defined by `has_secured_password` with empty string does not trigger validation error

### ISSUE THREAD

**Issue by jordinl83** [rails/rails#34348]
### Steps to reproduce

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "5.2.1"
  gem "sqlite3"
  gem "bcrypt"
end

require "active_record"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string "password_digest"
  end
end

class User < ActiveRecord::Base
  has_secure_password
end

class TestBlankPasswords < Minitest::Test
  def test_creating_with_nil_password
    user = User.create(password: nil)
    assert_equal 1, user.errors.count
  end

  def test_creating_with_empty_password
    user = User.create(password: '')
    assert_equal 1, user.errors.count
  end

  def test_updating_with_nil_password
    existing_user = User.create!(password: 'password')

    existing_user.update(password: nil)
    assert_equal 1, existing_user.errors.count
  end

  def test_updating_with_empty_password
    existing_user = User.create!(password: 'password')

    existing_user.update(password: '')
    assert_equal 1, existing_user.errors.count
  end
end

```

### Expected behavior
Active Record classes that define a password with `has_secure_password`, when I try to update a record that already exists by setting the password to an empty string, I should get a validation error on password. 

### Actual behavior
The blank password is ignored and no validation errors are triggered.

### System configuration
**Rails version**: `5.2.1`

**Ruby version**: `2.4.2`

### Additional notes
Updating a password to an empty string should have the same behavior as setting it to `nil`, which is to trigger a validation error. The issue seems to be caused by these two [if statements](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/secure_password.rb#L75-L77). I could submit the PR to fix the issue if needed.

**Comment by rafaelfranca** [comment]
I don't think the problem is on those conditionals. `''` is empty so the password_digest would not be updated. The validation doesn't fail because the digest is still the same as before and no changes to the database will be made.

We have a test for it
https://github.com/rails/rails/pull/13772/files#diff-68936e05b27105b053a083bfdea6927bR82. So an empty password doesn't change the current password so it is still valid.

If I remember correctly we tried to fix this before and I'm almost sure there is a reason for this behavior. But please investigate.

**Comment by lsylvester** [comment]
I think that the reason the password is ignored for empty strings is that if a user has a form with multiple fields (including password) and they update details but don't enter the password, then we want to allow the other details to be updated without the password being effected.

**Comment by lsylvester** [comment]
In my opinion the current implentation has the least surprise when using `form.password_field` and `update(params.permit(:password))`, and would make the controller code ugly having to prepare the params by deleting the password param if it is blank.

Can you outline the scenario where this behaviour is causing an issue? Maybe you could be clearing the password_digest before setting the password as it would force the blank validation to run.

**Comment by jordinl83** [comment]
@lsylvester this is for an API, so if I get an empty string I should return a validation error. There are obviously ways around this "limitation", I just find odd that rails ignores empty strings for password fields but it doesn't for other types of inputs.

**Comment by snpd25** [comment]
@lsylvester  Or we can provide the user with an option of having no password by using a checkbox param for passwords, and ignore the password param on the basis of it.

**Comment by brendon** [comment]
I have a scenario. By default a minimum password length isn't enforced. I'd like to have the following:

```
validates_length_of :password, minimum: 8, allow_nil: true, on: :update
```

On create I set the password to a random string and require the user to activate the account via an email link that they click to set their actual password.

The validation works fine provided the password has at least one character. An empty string causes the setter to bypass setting the password resulting in the validation being bypassed (due to `nil`).

I don't see a way around this other than to override the setter so that an empty string still sets the instance variable then `super` from there. Am I missing something?

**Comment by brendon** [comment]
For those interested in finding a way through to fixing this, there is a discussion here: https://discuss.rubyonrails.org/t/enhancements-to-has-secure-password/75078
