### ISSUE TITLE
ActiveSupport::MessageEncryptor.encrypt_and_sign (nearly) doubling size of message when encrypting

### ISSUE THREAD

**Issue by squirrelpoop** [rails/rails#34382]
### Steps to reproduce
https://gist.github.com/squirrelpoop/b4b5091d1f1997fbd788cef5b0035331

### Expected behavior
I would expect the encrypted data to be somewhat similar in size to the original item, not nearly doubled.

### Actual behavior
The encrypted size is SIGNIFICANTLY larger than the original amount of data, which causes smaller cookies to throw CookieOverflow errors.

### System configuration
$ rails -v
ruby -Rails 5.2.1

$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by y-yagi** [comment]
`encrypt_and_sign` uses `Base64.strict_encode64` twice with `MessageEncryptor#_encrypt` and `MessageVerifier#encode`. 

https://github.com/rails/rails/blob/b13a5cb83ea00d6a3d71320fd276ca21049c2544/activesupport/lib/active_support/message_encryptor.rb#L178 
https://github.com/rails/rails/blob/b13a5cb83ea00d6a3d71320fd276ca21049c2544/activesupport/lib/active_support/message_verifier.rb#L193 

Base64 encodes each set of three bytes into four bytes. In addition the output is padded to always be a multiple of four. 
Therefore, for the original data, that size has increased like that. This is intentional behavior.
