### ISSUE TITLE
inverse_of on has_many through: with accepts_nested_attributes_for

### ISSUE THREAD

**Issue by amerritt14** [rails/rails#34419]
### Steps to reproduce
Test case to show failure on the expected behavior
https://gist.github.com/amerritt14/aecd625199e4e62a0873465eeff5d708

The inverse_of option for has_many through associations normally will work as expected, as noted here: https://github.com/rails/rails/issues/21692

When introducing accepts_nested_attributes the inverse_of option stops working. I'm happy to work on a fix if this is something that we agree is a bug in need of a fix.

### Expected behavior
When creating a new object via nested attributes, inverse_of should allow all the relations to be available on the object, even when it is via a has_many through relationship

### Actual behavior
The unsaved has_many through relationships are blank on the unsaved object

### System configuration
**Rails version**:
ActiveRecord 5.0.2. Behavior is noted in Rails 5.0.7
**Ruby version**:
ruby 2.3.1p112

**Comment by gmcgibbon** [comment]
There's lots of noise in your test case. To clarify, its `def user_businesses_exists?` that we should be paying attention to, right?

The error still persists if you remove `accepts_nested_attributes_for`. The fact that you're saving the user's business in the same transaction makes me skeptical to call this a bug. If you drop using separate associations in your validation, it will work.

Specifically, changing `return true if user_businesses.present?` to `return true if user.businesses.present?`. This is because the associated user's businesses' aren't committed to the DB yet (because this is a validation callback) and querying with a separate association loads a separate collection proxy from the DB.

**Comment by amerritt14** [comment]
I appreciate the comment. I'll work on 1) Simplifying the example case, as you said there's a lot of noise in the test case since I was extracting it from business logic, 2) avoid a separate associations in the validations.
I'll post again with the updates.
