### ISSUE TITLE
Request increased because of ActiveStorage

### ISSUE THREAD

**Issue by kaluznyo** [rails/rails#34552]
Since we used ActiveStorage in production, in rush time for our app, ActiveStorage produce à huge number of request (first page of our app contains 40 images).
Each image produce a request to "Active Storage controller" who redirect to S3. Before ActiveStorage, we used paperclip, and paperclip use directly S3 url when we use image_url

This increased number of request make nginx failed because of max_request_queue_size. We increased it to 200 (from 100) But we still have some error. 

Can we use some cache to avoid this number of request ? or image_url we link directly to S3 ?

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3

**Comment by dwightwatson** [comment]
This is a common issue with ActiveStorage and public assets, there is no good solution at this stage.

* #34581 looks to add a method to get a long-lived public URL 
* #34477 looks to provide proxying or downloading for assets, which would allow a CDN to help
* #31419 discussed providing additional access to the file so you'd have more control over what you do with it

Thought it might be beneficial to link some of these issues/PRs up together because it's been a long standing issue. Would love to see a solution make it into Rails 6.0 if it's at all possible.
