### ISSUE TITLE
Improve belongs_to and validates_uniqueness_of from database_validations gem

### ISSUE THREAD

**Issue by djezzzl** [rails/rails#34650]
Hey guys, we're using [database_validations gem](https://github.com/toptal/database_validations). It provides a better experience with `belongs_to` and `validates_uniquness_of`.

Long story short, those improved methods:
- at least 2 times faster;
- provide a compatibility with existing corresponding analogs;
- provide a true database consistency because they use constraints in the database;

 Check out the [repo](https://github.com/toptal/database_validations) to get more details. There are also few articles about it: [here](https://www.reddit.com/r/rails/comments/9x1lsd/consistency_between_database_constraints_and/) and [here](https://www.reddit.com/r/rubyonrails/comments/a1t11j/enhance_your_belongs_to_to_be_two_times_faster/).

The [gem](https://github.com/toptal/database_validations) becomes more popular every day and some guys [support an idea to provide a PR to merge it to the core](https://github.com/toptal/database_validations/issues/18).

Because @dhh introduced [create_or_find_by](https://github.com/rails/rails/pull/31989) we can create a PR to merge the logic from the gem to the `ActiveRecord`. 

*WDYT about it? Any feedback is appriciated!*

**Comment by rafaelfranca** [comment]
Not sure if we can call that better experience. The gem itself already show some disavantages over the in-memory validation. One that is really a deal breaker to me is "Cannot handle multiple validations at once because database raises only one error per query.". This degrades the error message you show to the users and give really bad user experience.

The validations in Rails are not only to give developers ways to protect they database but also to give users of the application good usability. While they can be slower than no running any validation in memory and rely on the database to set constraints we believe in-memory validation improves the user experience, and this was always the goal of the framework regrading validations since the beginning.

That being said while I think some people can use this I prefer to not introduce this behavior in Rails. I'm happy that the plugin exists and people can take advantage of this if they want.

Thank you for the issue.

**Comment by rafaelfranca** [comment]
That makes sense. We do that in https://github.com/Shopify/activerecord-rescue_from_duplicate. This behavior can be merged with the current validator.

**Comment by djezzzl** [comment]
That's very similar to what we did in `database_validations`. Didn't see it before. 

> This behavior can be merged with the current validator.

So if you're fine to have that inside `ActiveRecord`, will you approve my PR if I provide it?

**Comment by djezzzl** [comment]
Hi @rafaelfranca, I have just provided a PR: https://github.com/rails/rails/pull/34725. Please have a look.
