### ISSUE TITLE
Errors#added? method behaviour changed

### ISSUE THREAD

**Issue by rainerborene** [rails/rails#34652]
Before Rails 5.2.2 this piece of code was working fine, now had to be changed as seem on the next block.

It was working on 5.2.1 and failed on latest version (5.2.2):
```ruby
certificate = Certificate.new
certificate.font_family = "Arial"
certificate.validate
assert certificate.errors.added? :font_family, :inclusion
```

All assertions on my code base had to be changed to: 
```ruby
assert certificate.errors.added? :font_family, :inclusion, value: "Arial"
```

I don't see on the CHANGELOG anything related to this change.

**Comment by rafaelfranca** [comment]
Indeed, there is no CHANGELOG entry, we should add this. But this change is a bug fix. They code before was broken since `certificate.errors.added? :font_family, :inclusion, value: "foo"` and `certificate.errors.added? :font_family, :inclusion, value: "Arial"` would return true.

**Comment by rafaelfranca** [comment]
The documentation of the method already explained that was the behavior `If the error message requires an option, then it returns true with the correct option, or false with an incorrect or missing option.` http://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-added-3F.

**Comment by jhubert** [comment]
@rafaelfranca Was there a discussion to determine that a missing option should be false instead of being globally true? That seems like the inverse of what I would expect.

If I say `record.errors.added?(:email, :taken)` I would expect it to return true if a taken error was added to the record, regardless of the additional values. There are many cases where it doesn't matter what the value is because we trust rails.

I'm happy to create a PR to that effect if it would be considered. This has broken a whole bunch of tests in our suite.
