### ISSUE TITLE
add_timestamps works on ActiveRecord::Migration[4.2], but not in 5.0 or 5.1

### ISSUE THREAD

**Issue by is-ma** [rails/rails#34661]
### Steps to reproduce
`rails generate migration CreateBeer name brand`
`rails db:migrate`

`rails generate migration AddTimestampsToBeer`

```ruby
class AddTimestampsToBeer < ActiveRecord::Migration[5.1]
  def change
    add_timestamps :beers
  end
end
```
`rails db:migrate`

### Expected behavior
It should make the migration.

### Actual behavior
SQLite3::SQLException: Cannot add a NOT NULL column with default value NULL: ALTER TABLE "beers" ADD "created_at" datetime NOT NULL

### But it works when...
- If I change the number to `ActiveRecord::Migration[5.0]`, it fails again (same error).
- If I change the number to `ActiveRecord::Migration[4.2]`, **it succeded.**

> == 20181210024827 AddTimestampsToBeer: migrating ==============================
-- add_timestamps(:beers, {:null=>true})
   -> 0.0009s
== 20181210024827 AddTimestampsToBeer: migrated (0.0009s) =====================

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin14]

**Comment by gmcgibbon** [comment]
In my [test script](https://gist.github.com/gmcgibbon/c4f368b21a2b7cec282242929de4c6cf), this seems to work in mysql and postgres, but not sqlite. The problem is, the SQL looks correct to me: `ALTER TABLE "beers" ADD "created_at" datetime NOT NULL`. The difference with `4.2` versioned migrations is that the default is nullable, which avoids the issue.
