### ISSUE TITLE
Log a warning if you run SQLite in production

### ISSUE THREAD

**Issue by irlcatgirl** [rails/rails#34715]
### Steps to reproduce
Create a Rails app which connects to SQLite, run as production.

### Expected behavior
Log a warning that running SQLite in production is not recommended.

### Actual behavior
No warning is logged.

### System configuration
**Rails version**: Rails 5.2.2

**Ruby version**: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

**Comment by fatihorhan** [comment]
There's nothing wrong with running SQLite in production.

**Comment by matthewd** [comment]
Context: https://github.com/rails/rails/issues/34710#issuecomment-447583665

**Comment by nsuchy** [comment]
> There's nothing wrong with running SQLite in production.

It's much more difficult to scale than let's say MySQL or PostgreSQL. Eventually you'll need to start load balancing across servers and the biggest AWS Instance (or similar) will no longer be enough for your needs.

> Context: [#34710 (comment)](https://github.com/rails/rails/issues/34710#issuecomment-447583665)

Thanks for linking to that.

**Comment by fatihorhan** [comment]
While I agree SQLite doesn't have the scaling power of MySQL or PostgreSQL, I'm not sure the best way to inform the developer about this fact is to pester them with a warning log every time the server starts whether they need said extra scaling or not.

For certain people, this warning will be confusing like they're doing something wrong.

Also, if rails start to warn people about potential database scaling issues, it would be reasonable to expect warnings about Active Job backend etc.

These are the problems I see with this approach. Of course you both have much more experience about general voice and direction of Rails project. I fully trust your final decision. I'm just trying to contribute.

**Comment by dhh** [comment]
The key problem with SQLite in production with Rails is a) it's the default, so newcomers might not even know that's what they're on and b) it's a disk-based db in a world of transient, cloud-based pods. I don't think the "I totally intend to run SQLite in production with my Rails app" crowd is very large at all. Are you in that group, @fatihorhan?

**Comment by nynhex** [comment]
.02c

any data source disk heavy like sqlite likely is not a great candidate for prod. not to say there aren’t edge cases but instead of spitting out a warning why don’t we just create a helpful suggestion in the rails guides/docs.  problem solved.  on to other things?

**Comment by dhh** [comment]
The point is to make this pointer when people hit the issue. Not just have some footnote somewhere. I’m content to move forward with a warning. If someone who actually intends to run SQLite in production hits it, we can add a config option to quiet it.

**Comment by nynhex** [comment]
@dhh got it, and understand.

how about a simple pr that at boot/init time checks env and adapter and spits out a logger `info` or `warn` message if prod && sqlite 

or should this be fleshed out further?

**Comment by nsuchy** [comment]
@nynhex `info` would be enough as using SQLite not "breaking" anything however the risks of using SQLite in production are large enough that I would advocate for a `warn`.

What tools are people using to view their log files we should be considerate of how they treat `warn` vs `info` entries?

**Comment by nynhex** [comment]
@nsuchy

aye i’d advocate for a warn as well. i’m honestly not sure what most use. i tail logs, use scalyr, and airbrake for exception handling. 

i want to say many logging interpreters prettify the actual log level. at least scalyr does for me.

**Comment by nynhex** [comment]
ps. if there’s enough traction i’ll pr this

**Comment by fatihorhan** [comment]
Thank you for listening to my viewpoint @dhh.

I understand that majority of rails apps don't run SQLite in production. I have a mini forum app that's chugging along with SQLite in production for over a year but all my other apps run PostgreSQL in development and production. So I'm in both groups, I guess.

Your points about SQLite being default and not being fit for transient pod world are both fair.

I presume the "intention" behind this warning is to tell: Look, you may not know it but you are running SQLite in production and bound to hit scaling issues, so why not switch to PostgreSQL/MySQL/etc now?

The problem I imagine with this warning is people deploying their first app to production, checking logs to see if there's anything wrong and meet this warning. As this a warning and not info, they will be inclined to do something about it. And either will try to setup an RDBMS themselves or pay for a hosted one. We just made the first rails experience more difficult.

**Comment by allenwu1973** [comment]
SQLite is totally fine for most websites, It's not very likely a newcomer who don't know about different RDBMS characteristics also have a heavy load site they need to scale.

And if you need other RDBMS due to heavy site load, you probably need to know more about the specific RDBMS you're going to use rather than just doing a switch.

**Comment by nsuchy** [comment]
@allenwu1973 I see a few problems with using SQLite in production.

1) Containers. Setting up an app inside a container that does not persist data would lose its data frequently  (unless you modified your app to call from another file store, things could get messy!). An example of this is hosting your app on Heroku. (their recommendation is to use Postgresql, every app's needs is different though).
2) Scaling SQLite. It's extremely difficult to scale SQLite in comparison to MySQL or Postgresql.
3) Some Ruby gems (devise) ask for the `.inet` colume type to store an IP Address. SQLite doesn't support this data type. (Changing to a string "fixes" the issue though its not the best solution)
4) I agree, understand your RDBMS. That's going to make developing your app much easier in the long run 😄

**Comment by simi** [comment]
@rafaelfranca since you have removed stale label, any idea what is next action for this?

Is there any core decision on this? Should we warn about SQLite and is this just waiting for PR? Or is SQLite considered totally ok and this can be closed?

**Comment by rafaelfranca** [comment]
We should warn about SQLite and it is just waiting for the PR.

**Comment by simi** [comment]
:thinking: I was thinking about this. Is the reason to warn about SQLite valid only when it is used by default? It would be possible to add "default" virtual adapter (just wrapped SQLite one) which will be used in default database.yml if no other is specified in rails new command. And we can warn about using default SQLite adapter and ask user to change it.

Once user decide to use SQLite with `rails new -d sqlite3` or manually editing `database.yml` to use sqlite3 adapter warning will not be present since it is user's active choice.

**Comment by rafaelfranca** [comment]
I'm more inclined to add a new option to disable that warning if users are choosing to use sqlite3 in production. I don't think we need a new virtual adapter, just a very simple `config.something something`

**Comment by simi** [comment]
I was trying to implement something, but I got a little confused.

Should be warning printed only in production? Isn't that too late to warn about? Or alternatively should we warn in development as well, but just checking for production environment?

:thinking: Alternatively wouldn't be just warning during `rails new` enough informing that sqlite3 adapter was used by default and also some additional info that it is not recommended to use that in production environment and possible change that using `rails db:system:change` command?

**Comment by rafaelfranca** [comment]
We should only warn when booting the application in production.

**Comment by catgirlsec** [comment]
How about we compromise and warn the user by default but provide a configuration option to disable the warnings?

**Comment by simi** [comment]
@rafaelfranca sorry if I miss something, but it doesn't make any sense.

1. user will create app (via rails new)
2. during development and testing no warning will be present
3. once app is deployed, warning will be present (anyway I can imagine scenarios where it will not be visible to users as well, for example if you use heroku-like deploy not showing app boot log)

Isn't that warning showed to user too late (after first sucessful deploy)? What should user do seeing that warning for the first time after first deploy? Stop the app and rethink deployment env.?

To see that warning before deploy you need to start app in production env. locally. From my experience, that is done really rarely.

🤔 It will make sense to show this warning before application is deployed in production. But since adapter is loaded by database.yml and that one can differ in production, there's no easy way how to show this warning during development. The only place where we can warn about default adapter is during "rails new" phase if no explicit database adapter is specified. Short notice that default sqlite adapter was used and it is not recommended to run sqlite in production will make sense IMHO.

**Comment by rafaelfranca** [comment]
We don't want to show this warning in development. We want users to be able to run locally with sqlite and even generate applications with sqlite. Yes, there is a chance users will not see the warning when deploying to heroku. If that still cause problems we can go stronger and raise an error unless a config allowing sqlite is production in set. But right now, even if there is a chance people will not see, we want to warn when the application is booted in the production environment if sqlite is being used as database and the config is not set.

**Comment by intrip** [comment]
Anybody is working on this? Otherwise I'd take a stab at this since it's been there for a while.
/cc @rafaelfranca

**Comment by irlcatgirl** [comment]
> 
> 
> Anybody is working on this? Otherwise I'd take a stab at this since it's been there for a while.
> /cc @rafaelfranca

Unfortunately my employer does not see this as a priority. Feel free to tackle it :)

**Comment by strzibny** [comment]
I am sorry that I didn't see this issue before, and therefore I am probably too late to chip in.

I believe SQLite is a great production database and would simplify a lot of projects. Using SQLite is not the problem at all, and this warning makes no sense. It's actually wrong unless you want to say Rails doesn't like SQLite.

Arguing about Heroku is a bit weird, since a lot of people actually use virtual servers, so they can use local disk without issues.

But most importantly. If the essence of the potential issue is about the mismatch between dev and production, why shouldn't Rails warn if you have different dev and production databases? That would be a clever thing to do and universal to all databases.

If Rails doesn't want to support SQLite for production, fine. But supporting it and issuing this warning makes no sense to me.
