### ISSUE TITLE
[ActionCable] Websocket connection issues with Firefox

### ISSUE THREAD

**Issue by arzeeee** [rails/rails#34848]
### Steps to reproduce
```
git clone git@github.com:arzeeee/pro.git
bundle install
rails db:migrate
rails db:seed
rails s
```
then login with either test_username1, test_username2, test_username3, or test_username4 with password is "password" from seed. After that go to `/chatroom` and try to send some messages

### Expected behavior
When connected to Websocket in chatroom, the browser should be alerted with `"I am connected"` message, and `"I am disconnected"` on disconnect.
After sending a message, browser should append message to the right and to the left when receiving a message. 

### Actual behavior
Firefox does not append message at all and also won't connect to websocket at many times, while Chrome sends and receive, and also appending the messages normally. Also, Firefox would get connected sometime and receive message normally, but upon pressing enter on sending message, the browser then alerts `"I am disconnected"`, then reconnects after a while. I get these errors many times

![Firefox Errors](https://user-images.githubusercontent.com/25842536/50624131-89307c80-0f4f-11e9-973a-ae2a14436604.png)

### System configuration
**Rails version**: 5.2.1

**Ruby version**: ruby 2.3.4p301
I'm also using Cloud9 online workspace, hence the added configuration line in `development.rb`

Edited (8/01/2019): Added bundle install command

**Comment by sheldond** [comment]
@arzeeee Hi! The repo github.com:arzeeee/pro.git doesn't seem to exist, is the link correct?

**Comment by sheldond** [comment]
@arzeeee The repo works now! After having a look I am not sure this is a bug in Rails.

Inside app/views/chatrooms/index.html.erb the form is setup to send a post request synchronously, I think you meant to send it async (remote) but it's not configured properly for that. In order to make a form post async you can use `remote: true` like this:
```
<%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
```

However, maybe using a form post is not ideal for a chatroom. Since you are using ActionCable, you can send the message through AC without a form post. Have you seen DHH's video on building a chatroom in AC? Here is the video: https://www.youtube.com/watch?v=n0WUjGkDFS0

I don't think the issue can be attributed to Rails yet, but if you still think there is a bug in Rails maybe it will help to make a more minimal code example first. I hope this was helpful 🙂

**Comment by arzeeee** [comment]
@sheldond right I tried it a few days ago and it worked, thank you so much for the help. I realized what I've done now. Thank you so much

**Comment by sheldond** [comment]
@arzeeee That's great!
