### ISSUE TITLE
Radio button collections that are disabled incorrectly have an enabled hidden input

### ISSUE THREAD

**Issue by urkle** [rails/rails#34915]
### Steps to reproduce
```erb
<%= form_for @post do |f| %>
  <%= f.collection_radio_buttons :author_id, Author.all, :id, :name_with_initial, disabled: true %>
  <%= f.submit %>
<% end %>
```
### Expected behavior

Creating a set of input elements that when the form is posted NOTHING related to this attribute is posted.

### Actual behavior

a hidden element with a blank value is created which is then posted when the form is posted. This causes unexpected behavior. (or DB null violation errors in our case)

### Workaround
We have worked around the issue by adding include_hidden: false to our disabled radio button collections. However the default behavior should be that when disabled is true the input element is either marked disabled or simply not rendered at all.

### System configuration
**Rails version**:
5.2.2
**Ruby version**:
2.4.4

**Comment by albertoalmagro** [comment]
I can take a look at this one if you want 👍

**Comment by albertoalmagro** [comment]
The point here is that `disabled` isn't meant to be used in that way, but providing a list with the values that should be disabled or a single element if only one value is meant to be disabled. I believe that the confusion comes because our specs are misleading. I have submitted a pull request to improve them by stopping using boolean values that can make developers think that `disabled: true` is meant to disable the whole helper as it happened in this case.
