### ISSUE TITLE
`.titleize` on `"O'Foo"` returns `"O'foo"`

### ISSUE THREAD

**Issue by anujbiyani** [rails/rails#34936]
### Steps to reproduce
Call `.titleize` on a string that has `O'Foo`. My use case involves street names, though I'm not sure if `titleize` is meant for this use case or not.

### Expected behavior
Calling `"123 O'Connell Street".titleize` returns `"123 O'Connell Street"`

### Actual behavior
Calling `"123 O'Connell Street".titleize` returns `"123 O'connell Street"`

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.3p105

### Failing test:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "active_support"
require "active_support/core_ext/string/inflections"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_titleize_with_apostrophe
    assert_equal "123 O'Connell Street".titleize, "123 O'Connell Street"
  end
end
```

**Comment by gmcgibbon** [comment]
Thanks for your report. Unfortunately, we can't change `#titleize` as it may break legacy behaviour. Patches to `ActiveSupport::Inflector` are rejected [as mentioned in the docs](https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html):

`
The Rails core team has stated patches for the inflections library will not be accepted in order to avoid breaking legacy applications which may be relying on errant inflections. If you discover an incorrect inflection and require it for your application or wish to define rules for languages other than English, please correct or add them yourself.
`
