### ISSUE TITLE
ActionText questions and documentation

### ISSUE THREAD

**Issue by tomprats** [rails/rails#34978]
I'm using ActionText in a new project and thought it would be a good time to help update the guide. People can comment here about things that would be helpful to add.

Current Guide: https://edgeguides.rubyonrails.org/action_text_overview.html

1. Adding a note that it doesn't require a column for the field
1. `with_rich_text_content` or `with_rich_text_content_and_embeds` preloads the rich text model
1. Validations like `validates_presence_of :content` can be used

Here are some things that I'm not sure about:

1. Using `as_json`. Doing something like `Message.all.with_rich_text_content.as_json(methods: [:content])` will include the related rich text, but it includes it as a record (with body, id, name, etc.) when most of the time you'd just want it to directly return the body. Is there another way to do this or should a custom method be used? Like `content_html` and doing `Message.all.as_json(methods: [:content_html])`
1. Using ActionText with a javascript framework like React. I asked about this on the [email list](https://groups.google.com/forum/#!topic/rubyonrails-core/rpn_7rpganc) and have my own solution I'm using.

If there's anything else, let me know. I'm also interested in opening a PR to potentially add some more helpers or fix any bugs if anyone runs into any! So far it doesn't look like anything is tagged with the actiontext issue tag.

**Comment by tomprats** [comment]
Is there a better place to talk about ActionText? Here are some additional features/things developers might run into:

1. Truncate the html for a preview
2. Displaying other types of files uploaded to a document (like markdown)

**Comment by cdrrazan** [comment]
> Is there a better place to talk about ActionText? Here are some additional features/things developers might run into:
> 
> 1. Truncate the html for a preview
> 2. Displaying other types of files uploaded to a document (like markdown)

Is there any way to truncate the content for the actiontext right now? Because it seems this need to be handled in different way as the content inside could be anything from text to images.

**Comment by zoras** [comment]
> Is there any way to truncate the content for the actiontext right now? 

@cdrrazan you can use [strip_tags](https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-strip_tags) to truncate the html for preview

`truncate(strip_tags(message.rich_content.to_s), length: 50)`

**Comment by tomprats** [comment]
That looks very helpful, I probably should have used that. But I think I ended up doing it on the javascript side with https://github.com/huang47/nodejs-html-truncate

**Comment by brian-kephart** [comment]
To add to this, the [installation instructions](https://edgeguides.rubyonrails.org/action_text_overview.html#installation) say nothing about how to install the javascript. The JS files are added to application.js, but there should be instructions about how to manually add to a JS bundle.

**Comment by lachlanjc** [comment]
Alongside #35002, we should have some documentation on how to move existing fields/other rich text implementations over to ActionText.

**Comment by MikeLangford** [comment]
How do I get nested comments created with ActionText (Trix Editor) to display in a rails project?

My second-level comments, created using ActionText / Trix Editor are not displaying in my rails app. The original post displays fine as do first-level comments. But, comments on comments will not display.

I created an app using Rails 6 that has posts and nested comments. The posts and comments are working on the database side of things. However, after I installed ActionText so I could allow users to post and comment using rich-text only the post and first-level comments display their respective body content.

The posts and first-level comments render post.body and comment.body wrapped in a "trix-content" div. However, the output for the second-level, nested comment just doesn't seem to be grabbing the comment.body.

Comment Model Code:

class Comment < ApplicationRecord
  has_rich_text :body
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, optional: true, class_name: "Comment"


  def comments
    Comment.where(commentable: commentable, parent_id: id)
  end
end

Comment Controller Code:

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @commentable, notice: "Comment was successfully created."
    else
      redirect_to @commentable, alert: "Something went wrong"
    end
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.destroy
    redirect_to @commentable
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end

end

Comment Form Code:

<%= form_with model: [commentable, Comment.new], local: true, html: { class: local_assigns[:class], data: { target: local_assigns[:target]}} do |form| %>

<div class="form-group">
  <%= form.rich_text_area :body, placeholder: "Add a comment", class: "form-control" %>
</div>

<div class="form-group">
  <%= form.hidden_field :parent_id, value: local_assigns[:parent_id] %>
  <%= form.submit class: "btn btn-primary" %>
</div>

<% end %>


Comment View/Show Page Code:

<% nesting = local_assigns.fetch(:nesting, 1) %>
<% max_nesting = local_assigns[:max_nesting] %>

<div <div class="col-lg-3">

</div>

<div class="col-lg-7">
  <ul class="media-list media-list-stream mb-2">
    <li class="media list-group-item mb-2">

  <img class="mr-0">
    <%= image_tag user_avatar(comment.user, 60), class: "rounded-circle" %>
  </img>

<div class="media-body">
  <div class="media-heading">
    <small class="float-right text-muted"> <%= comment.created_at.strftime("%b %e, %Y") %> </small>
  <h6 class="ml-3"><%= comment.user.name %></h6>
  </div>
  <div class="media ml-3">
    <p><%= comment.body %></p>
  </div>
  <div class="media-footer ml-3">




    <div data-controller="reply">
    <small>
      <%= link_to "Reply", "#", data: { action: "click->reply#toggle" } %>
      <%= link_to "Delete", [comment.commentable, comment], method: :delete, data: {confirm: "Are you sure?"} if comment.user == current_user%>
    </small>

    <%= render partial: "comments/form", locals: {
      commentable: comment.commentable,
      parent_id: reply_to_comment_id(comment, nesting, max_nesting),
      class: "d-none",
      target: "reply.form"
    } %>

    </div>
    </div>
    </div>
</li>
    <%= render comment.comments, nesting: nesting + 1, max_nesting: local_assigns[:max_nesting] %>
  </ul>
  </div>

I suspect the issue has something to do with the association of comments on comments because when I remove the nesting and comment on a comment I see the same result. It looks like someone posted a blank comment.

**Comment by coopeu** [comment]
Rails 6 error: undefined method `truncate' for #<ActionText::RichText
This was working: sanitize(post.content.truncate(300)) after upgrading to ruby 2.6.3 and rails 6.0.0
How to sanitize and truncate text?

**Comment by stingo** [comment]
> Rails 6 error: undefined method `truncate' for #<ActionText::RichText
> This was working: sanitize(post.content.truncate(300)) after upgrading to ruby 2.6.3 and rails 6.0.0
> How to sanitize and truncate text?

Upgraded to ruby 2.6.3 and rails 6.0.0 below works for me as mentioned by @zoras 

	`<%= truncate(strip_tags(@article.rich_text_body.to_s), length: 50) %>`
     
     article.rb
    `has_rich_text :body`

**Comment by lachlanjc** [comment]
This is still relevant even if it's not a priority, I think. ActionText needs more documentation on converting existing fields, JS installation, truncation, etc.

**Comment by matthee** [comment]
@zoras @stingo There is an even better way of doing this, since lists and attachments are converted to their textual representation as well:

```erb
<%= truncate(@article.body.to_plain_text), length: 50) %>
```

This method is documented here:

https://github.com/rails/rails/blob/3a6770fb512572bec904c0d710dc3d0954edcafa/actiontext/lib/action_text/attribute.rb#L17

**Comment by Drus566** [comment]
How I can validate Action Text rich_text_content attachments in active record model? Need attachments count, content type, byte size? Validate need when create model.

**Comment by Drus566** [comment]
`rich_text_content.body.attachments` - this return all attachments when create model in active record models directory and i can use it for custom validate my model.  Link to [source](https://github.com/rails/rails/blob/master/actiontext/app/models/action_text/rich_text.rb)

**Comment by jonathanhefner** [comment]
> This is still relevant even if it's not a priority, I think. ActionText needs more documentation on converting existing fields, JS installation, truncation, etc.

PRs that improve documentation are always welcome!

Since the discussion has veered toward technical support though, I'm going to close this issue.  For technical support, please use the [rubyonrails-talk Discourse](https://discuss.rubyonrails.org/c/rubyonrails-talk/7) or Stack Overflow.

**Comment by carlos-ssh** [comment]
> > Is there any way to truncate the content for the actiontext right now?
> 
> @cdrrazan you can use [strip_tags](https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-strip_tags) to truncate the html for preview
> 
> `truncate(strip_tags(message.rich_content.to_s), length: 50)`

Very helpful!!! thanks.

**Comment by xecutioner** [comment]
Is there a way to generate 'alt' attribute for <img> tags while using action text as WYSIWYG ?
