### ISSUE TITLE
ArgumentError in Controller unsafe redirect 

### ISSUE THREAD

**Issue by nikolaokonesh** [rails/rails#35051]
> Unsafe redirect "http://lvh.me:3000/info/subscribes", use :fallback_location to specify a fallback or :allow_other_host to redirect anyway.

```      
else
  redirect_to subscribes_url(subdomain: false)
end
```
or other url redirect
```
      if response.success?
        redirect_to response.form_url
      else
```

> result Unsafe redirect "https://3dsec.sb.ru/payment_ru.html?mdOrder=3c3ca8f4-604f-72dc", use :fallback_location to specify a fallback or :allow_other_host to redirect anyway.

help!!!
**Rails version**: 6.0.0.beta1
**Ruby version**: 2.5.3

rails 5.2 no problem

**Comment by remomueller** [comment]
Looks like this is related to changes made in https://github.com/rails/rails/issues/33577, and https://github.com/rails/rails/pull/34412. Looking at the diff, it may be enough to add the following to the redirect:

```ruby
if response.success?
  redirect_to response.form_url, allow_other_host: true
else
```

I'll try it on my code as well as I'm running into this with ActiveStorage links.

**Comment by gmcgibbon** [comment]
@remomueller is correct. This was recently reverted and will not be included the next beta release (see https://github.com/rails/rails/issues/35019). In the meantime, try using `master`, or simply adding `allow_other_host: true` to your redirect. Since this isn't a problem on master anymore, I'm going to close this.

Thank you for the report.
