### ISSUE TITLE
ActionCable does not unsubscribe or reuse existing connection to channel on server restart

### ISSUE THREAD

**Issue by jduff** [rails/rails#35103]
### Steps to reproduce
1. Create a channel that adds to a persistent list on `subscribed`, and removes on `unsubscribed` ex.

``` ruby
class PageViewerChannel < ApplicationCable::Channel
  def subscribed
    stop_all_streams
    page = Page.find(params[:page_id])

    stream_for page

    # Add the current user to a list for this page
    # If they open the same page in two tabs they will be in the list twice
    redis.lpush(key_for(page.id), current_user.id)

    # Broadcast the current list of viewers to everyone listening to the stream for this page
    PageViewerChannel.broadcast_to page, viewers_for(page.id)
  end

  def unsubscribed
    # Any cleanup needed when channel is unsubscribed
    page = Page.find(params[:page_id])

    # Remove the current user from the list
    redis.lrem(key_for(page.id), 1, current_user.id)

    # Broadcast the new list of viewers to subscribers of this page
    PageViewerChannel.broadcast_to page, viewers_for(page.id)
  end

  private

  def redis
    @redis ||= ::Redis.new(url: Rails.application.secrets[:redis][:url])
  end

  def viewers_for(ticket_id)
    users = User.where(id: redis.lrange(key_for(page_id), 0, -1))

    users.collect{|u| {id: u.id, name: u.name} }
  end

  def key_for(id)
    "page_#{id}_viewers"
  end
end
```

2. Create a connection to the channel from the page

``` javascript
App.cable.subscriptions.create(
  {channel: 'PageViewerChannel', page_id: page_id},
  {received: function(data) {}}
)
```

3. Start Rails server and load the page.

4. Inspect user list to see user.

5. Restart Rails server.

6. Inspect user list again to see user listed twice.

### Expected behavior
`unsubscribed` should be called on channels when the server is stopped.
OR
Connection for the same client should be reused instead of creating a new subscription.

### Actual behavior
`unsubscribed` is not called and a new subscription is created for the client when the Rails server comes back.

### System configuration
**Rails version**:
5.2.2
**Ruby version**:
2.4.3p205

**Comment by rromanchuk** [comment]
@jduff i'm using actioncable in the context of mobile, do you have any insights on how i'm supposed be cleaning these connections up? I see a lot of different conflicting answers. I've tried sending `unsubscribe` using the same signature as `subscribe` (which is working fine). What are the consequences of simply disconnecting the socket?   Am i required to override `unsubscribed`?  I see some people using `stop_all_streams`, but i don't understand it's purpose haven't looked at source yet though. 

I'm seeing similar unanswered questions all over the internet https://stackoverflow.com/questions/39017691/actioncable-unsubscribe-callback-not-working-when-ios-client-send-unsubscribe

It also makes me a little nervous deploying with puma, i have a feeling that actioncable is responsible for some very difficult to debug timeouts and slow restarts.

**Comment by jduff** [comment]
@rromanchuk what you are describing sounds like a different issue from what I was running into. If the client disconnected everything worked fine for me. My issue was if the server was restarted `unsubscribed` was not called, but when it came back up the clients would connect again and `subscribed` would be called.

To work around this I stopped depending on `unsubscribed` and instead added a keep alive call and ttl for the entry in my list. The keep alive regularly pings and makes sure the id stays in the list, if it stops pinging the ttl passes and the id gets dropped from the list.

I'm not really sure what the issues would be on mobile, but it could be that they are not implementing everything that the `cable.js` client does for web. I would dig into that and model the native mobile behaviour off of it.

I haven't noticed actioncable with puma causing slow restarts or timeouts at all.

**Comment by rromanchuk** [comment]
@jduff yeah it looks like one of my puma issue was resolved with their latest released, looks like new requests were being accepted on shutdown. 

Major digression, but just in case it helps someone else, i also figured out the more insidious problem i was investigating. I recently got an uptick in `Fix PG::ConnectionBad: timeout expired` but it sent me me on a wild goose chase. Finally figured it out, mistakenly modified my puma config with a min threads of zero, I didn't realize puma scales downward when underutilized. It became a frog boil coupled with a a very aggressive `connect_timeout` of 1 second in in my database.yml, which is the equivalent initialization param in `ActiveRecord::Base.establish_connection(connect_timeout: 1, checkout_timeout: 1, ...)`   Our client requests tend to be extremely burst-y in some scenarios, so what was happening was puma would wind down threads, and then a burst of requests would come in causing the master processes to rapidly spin up threads, which would exhaust the connection pool and the 1second timeout expire throwing this exception.

What made this incredibly difficult to debug is I assumed this was a standard bottleneck issue. IO limitation, slow query, network issue, etc etc. The error class also made me think this was at the postgres layer, when in reality it's coming from a timeout thrown by rails connection pool with pg for the postgres adapter. The stack traces were misleading, as it looked like some endpoints were responsible, but then you could trigger it by just launching console, if you were lucky. Even some sidekiq jobs would throw this at what seemed to be random. Turns out the endpoints that were failing were more frequent because they were the latter requests in an onslaught of GET requests. So my guess is either connection pool was frantically asynchronously trying to setup connections which choked at the TCP layer, or connections getting caught in a semaphore along many other concurrent requests to the connection pool. When the timeout was thrown you could be at any frame that was invoking an activerecord call.

Anyways, this issue completely vanished when i made min threads equal to max threads. I also then increased `connect_timeout` per postgres` own documentation 

> connect_timeout
> Maximum wait for connection, in seconds (write as a decimal integer string). Zero or not specified means wait indefinitely. It is not recommended to use a timeout of less than 2 seconds.

Below you can see threads running over time on an extremely underutilized machine. With min threads set to zero you see the threadcount constantly spiking up and down, vs now keeping them alive.
<img width="392" alt="Screen Shot 2019-04-09 at 12 57 58 PM" src="https://user-images.githubusercontent.com/102188/55831079-2b1fb200-5ac7-11e9-9a9c-006b30771b3a.png">

It would become even worse on deploy, depending on random luck, which makes sense as puma shuts down a worker, and the master process is trying to spin up new threads on workers it has available. 

Sorry to hijack, hoping SEO helps out a poor soul in the future. Ended up here thinking actioncable connections weren't playing nice or I was leaking connections/abusing the API. There are probably others out there who are using the rails timeout reference who are seeing this and looking for code smells in the wrong place . see: https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts/issues/27

**Comment by DJ967** [comment]
l
