### ISSUE TITLE
Actiontext not displaying correctly

### ISSUE THREAD

**Issue by EchoUrandom** [rails/rails#35110]
![image](https://user-images.githubusercontent.com/22819862/52039611-e89c9f00-2584-11e9-9a85-6dba5a8bfdfe.png)
I'm trying to use the ActionText trix editor inside a new chapter form and it is not displaying correctly. I've used both latest versions of Firefox and Chrome. I can't know for sure if it is an issue with my end or if this is caused by a bug in rails (or trix editor??) since nothing shows in the console.

I looked into it though but the only source I found was for the official trix editor repo issues [here](url) except mine does not show any problems in the console on both browsers like it does on here and possibly not caused by the same things. I don't even know if this is something that is a rails related issue or whether I should make this issue on their repo instead. 

I'm using rails 6.0.0.beta1
with Ruby 2.5.1

I have my code posted on gitlab for checking out.
https://gitlab.com/jorrellh/freefiction

**Comment by y-yagi** [comment]
Your application is not displayed correctly because trix js require is missing. Please add `trix/dist/trix` to `app/assets/javascripts/application.js`. 
This is not executed by the installer because it uses sprockets. Since Rails 6 is supposed to use webpacker for managing JS, please consider using it. 

Also, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks!
