### ISSUE TITLE
Why do it need to execute SQL when ActiveRecord query conditions is empty array?

### ISSUE THREAD

**Issue by ouyangshi95** [rails/rails#35307]
```User.where(id: [])  # SELECT COUNT(*) FROM `users` WHERE 1=0```
I don't think such queries need to be linked to database, but ActiveRecord actually executes a query. Why?

**Comment by majkelcc** [comment]
@OuGe95 you would probably be less surprised if ActiveRecord would generate a query like:

```sql
SELECT * FROM users WHERE id IN ()
```
but since `id in ()` is not a valid SQL when the brackets are empty, Rails replaces it with a condition producing the same, empty result.

I think that it's better that ActiveRecord is not trying to be too smart here. On the other hand I see how seeing `1=0` in logs would make people confused. Maybe this behaviour could be either configurable or accompanied by a comment in logs (I haven't seen Rails doing it on any other occasion, but just a thought)?

**Comment by xdmx** [comment]
@majkelcc, I think @OuGe95 point here is: if the generated query is `WHERE 1=0`, and thus it'll for sure always return 0 results, why does it need to run that SQL query at all and not just return an empty (`User.none`) result?

**Comment by majkelcc** [comment]
@xdmx because that would be a smart thing to do and sometimes it's better to keep things simple (stupid) 🙂

**Comment by ahorek** [comment]
@xdmx it'll for sure always return 0 results

not always, take this as an example
```ruby
Project.where(id: []).or(Project.where("1=1"))
```
a smart logic for that would slowdown ALL queries just to detect a corner case

if you already know that the query could contain an empty set, just add a condition
```ruby
@projects = ids.any? ? Project.where(id: ids) : Project.none
```

**Comment by OuGe95** [comment]
@xdmx Yes, my English is not good. Thank you for clearly describing my meaning.  
@ahorek @majkelcc I probably see what you mean. Rails can deal with this example, but It will be take a lot more expensive.  
Finally, thank you for your help very much. Rails is awesome! Wish the rails better and better!
