### ISSUE TITLE
Rails 6 multiple database tasks throws exception when environment config is used

### ISSUE THREAD

**Issue by morgoth** [rails/rails#35468]
In Rails 6 with multiple database support, rake tasks are now build dynamically based on db config:
https://github.com/rails/rails/blob/9e34df00039d63b5672315419e76f06f80ef3dc4/activerecord/lib/active_record/railties/databases.rake#L26-L33

This causes problems when evaluating `config/database.yml` that uses some configuration set on app level:
```ruby
# config/environments/development.rb
Rails.application.configure do
  config.some_config = "I'm set"
end
```
```yml
default: &default
  some_config: <%= Rails.configuration.some_config %>
```
as in time of building rake task, app environment is not loaded yet, thus `some_config` method is not defined.

@eileencodes I'm wondering if those task names could be built without loading env, but I guess to get them, `database.yml` has to be evaluated. Other option would be to load the env in time of building them, but this looks like a too big overhead on `rake -T` in example.

**Comment by eileencodes** [comment]
Can you make a basic app on Rails 6 that reproduces this and I will take a look.

Unfortunately we cannot avoid loading ENV at the time we do  - I tried for weeks to work around that, it's just not possible.

**Comment by morgoth** [comment]
Here you go https://github.com/morgoth/ar-bug#readme :-)

**Comment by eileencodes** [comment]
Is this the error you're seeing or a different one?

```
rake aborted!
NoMethodError: Cannot load database configuration:
undefined method `max_threads' for #<Rails::Application::Configuration:0x00007fc39d0b96c8>
(erb):9:in `<main>'
/Users/eileencodes/open_source/rails_apps/ar-bug/Rakefile:6:in `<top (required)>'
```

**Comment by morgoth** [comment]
yes, it's that error

**Comment by eileencodes** [comment]
So there's a deeper problem we identified with setting any environment specific config that we really should have never allowed this behavior to work in the first place.

While it used to work without blowing up it presents some problems. If you set `max_threads` in development to 10 and in test to 5 and then load the configurations the configuration settings will change based on the environment you load that configuration in.

So if you load the configuration in test it will set `max_threads` in dev and test to 5 because Rails can't read a different environment when you're loading another environment.

I'm not sure we can support this going forward because it was a broken system to begin with. I will try to figure out how to not raise an unhelpful error.

**Comment by eileencodes** [comment]
Actually, I'll first experiment a bit more with not blowing up but having been down this road before I'm not sure it's possible or recommended to support this going forward.

**Comment by morgoth** [comment]
> So if you load the configuration in test it will set max_threads in dev and test to 5 because Rails can't read a different environment when you're loading another environment.

Yes, I know about it. it works the same way as `config_for`

**Comment by eileencodes** [comment]
We have a chicken and egg problem here and I don't know how to solve this. Possible solutions are:

1) Just load the YAML to get the namespaces without the ERB. This won't work though if you have multi-line erb, yaml can't parse it and it will blow up with a Psych error.
2) Load the environment when we call `for_each`. Sure this is _possible_ and it _works_ but it means we're loading the env for `bin/rake -T` which may be a performance hit we're not willing to take.
3) Have the app pre-provide the namespaces. If we had a config option like `config.database_namespaces = [:primary, :animals]` we could then just loop through those and create the tables, but this is extra work app engineers need to do.

Clearly it's not acceptable to just break this but I also don't want to release Rails 6 without the rake tasks for multiple databases 😢

**Comment by eileencodes** [comment]
@tenderlove @rafaelfranca and/or @matthewd do you have any ideas how I can create the rake tasks for multiple database like `db:create:animals` without loading the env or without parsing the erb in the yaml file?

We can load the yaml and ignore the ERB but if an app uses multi-line erb like we do at GitHub it will blow up with `Psych::SyntaxError: (<unknown>): found character that cannot start any token while scanning for the next token at line 11 column 3`.

If we try to load the rake tasks assuming there's no Rails configuration we get this issue. Because the env isn't loaded `max_threads` isn't defined.

**Comment by tenderlove** [comment]
We could parse the ERB, but either not evaluate the Ruby code, or just put in dummy values.  Are the namespaces going to be dynamic?  Nobody can configure the namespaces via `Rails.application.configure { }`, right?
