### ISSUE TITLE
rails new with --skip-webpack-install still includes the webpacker gem.

### ISSUE THREAD

**Issue by omnilord** [rails/rails#35484]
### Steps to reproduce
run `rails new app_name --skip-webpack-install`

### Expected behavior
webpacker gem should not be included in Gemfile.

### Actual behavior
webpacker gem is included in Gemfile.

### System configuration
**Rails version**: 6.0.0.beta2

**Ruby version**: 2.6.1

**Comment by bogdanvlviv** [comment]
Hello. The current behavior is correct, [we added `--skip-webpack-install`](https://github.com/rails/rails/pull/34071) to be able to prevent running `rails webpacker:install` when generating new rails app. If you want to skip adding  webpacker gem when generating new rails application use `--skip-javascript` (since [Webpacker the default JavaScript compiler for Rails 6](https://github.com/rails/rails/pull/33079)).
Thank you for the report!

**Comment by omnilord** [comment]
"default" implies there is a way to switch back to what was used in rails 5, or another option.  Since `--skip-javascript` has other side-effects besides not including the webpacker gem, is there an alternative option?

**Comment by y-yagi** [comment]
Currently, we only support webpacker for JavaScript build. If you want to use other libraries, you need to specify `--skip-javascript` option and customize yourself. 
In addition, the side effect of the `--skip-javascript` option is to avoid generating the file used by the webpacker. These should be unnecessary. 

What is the issue with using the `--skip-javascript` option?

**Comment by ferdi2005** [comment]
There should be an option to include sprockets and not webpacker. Webpacker is terrible: to compile a few JS files (that with sprockets compiled perfectly) it runs out of ram my server.

**Comment by jakeNiemiec** [comment]
@ferdi2005 If you post some details in an issue over at the [rails/webpacker](https://github.com/rails/webpacker) repo I'd be happy to troubleshoot with you. There are only a handful of things that can cause exponential ram usage.

**Comment by ferdi2005** [comment]
@jakeNiemiec Done: https://github.com/rails/webpacker/issues/2267

**Comment by AxelTheGerman** [comment]
I followed the discussion in the webpacker issue and it's still not really solved. Just shows how disappointing it is that Rails maintainers decided to shove webpack down our throats.

Don't get me wrong, when you need webpack for JS heavy stuff webpacker is great as it lightens the burden slightly.

But if all I do is write a server rendered web app the way Rails has been working since day 1 then I don't need any of that :-1:

**Comment by aivils** [comment]
You can still create retro-style software.
Generate usual rails 6.

File app/assets/config/manifest.js contains

```
//= link_tree ../images
//= link_directory ../stylesheets .css
//= link_directory ../javascripts .js
```

File app/assets/javascripts/application.js contains

```
//= require rails-ujs
```

Belive me vanilla JS rails-ujs is shipped in the actionview.
Also vanilla JS turbolinks is shipped by turbolinks gem.

File app/views/layouts/application.html.haml has line

```
= javascript_include_tag 'application'
```

Instead of javascript_pack_tag, this is crucial.


File package.json contains

```
{
  "name": "vanillajs",
  "private": true,
  "dependencies": {
  },
  "version": "0.1.0",
  "devDependencies": {
  }
}
```

Folder vendor/assets/javascripts can contain JS libraries.

webpacker is not disabled. Later you can add 1001 node packages by wish.
