### ISSUE TITLE
Grape+Rails example don't work with zeitwerk

### ISSUE THREAD

**Issue by 4ndv** [rails/rails#35567]
I've already checked steps in #35475 and tried all of them. Only disabling zeitwerk (via :classic) solves the issue, disabling bootsnap cache and/or updating ruby does not help.

### Steps to reproduce

1. I've added paths to autoload according to grape's example (https://github.com/ruby-grape/grape#rails):

```ruby
    config.paths.add File.join('app', 'api'), glob: File.join('**', '*.rb')
    config.autoload_paths += Dir[Rails.root.join('app', 'api', '*')]
```

2. I've created this folder structure in app/:

```
app
├── api
│   └── twitter
│       └── api.rb
```

3. api.rb:

```ruby
module Twitter
  class API < Grape::API
    format :json
  end
end
```

4. Added this into the routes:

```ruby
mount Twitter::API => '/api'
```

5. `rails s`

### Expected behavior

It should work the same as without zeitwerk

### Actual behavior

It does not:

```
/config/routes.rb:5:in `block in <main>': uninitialized constant Twitter (NameError)
```

### System configuration
**Rails version**: 6.0.0.beta2

**Ruby version**: 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]

**Comment by y-yagi** [comment]
cc @fxn

**Comment by 4ndv** [comment]
Same result on beta3 and zeitwerk 1.3.3

**Comment by fxn** [comment]
Several things to comment here.

You do not need to modify `config.autoload_paths`, those instructions are incorrect. The directory `app/api` is automatically added to the autoload paths by Rails.

Autoload paths represent root directories, and `app/api/twitter` is not, so it should not be added.  Zeitwerk mode is more strict than classic wrt nested autoload paths and that prevents the `twitter` from being treated as a namespace.

A different detail is that Zeitwerk needs to be told that it should inflect "api" as "API" instead of "Api".

So, you should do two things:

1. Delete `config.autoload_paths += Dir[Rails.root.join('app', 'api', '*')]` in `config/application.rb`.
2. Uncomment the lines at the bottom of `config/initializers/inflections.rb`, and configure "API" as an acronym.

Could you please try?

**Comment by 4ndv** [comment]
Removed everything that i've added to application.rb, added API as an acronym and now it works, thanks!

**Comment by 4ndv** [comment]
And i've had ApplicationHelper included like this in Grape:

```
helpers MyApp::ApplicationHelper
```

It was failing with uninitialized constant, changed to this:

```
helpers ApplicationHelper
```

And now it also works

**Comment by fxn** [comment]
Sounds good, if the module is called `ApplicationHelper` (top-level), then it worked in classic by luck, because of the classic gotchas, but a bare `ApplicationHelper` is the correct reference.

**Comment by fxn** [comment]
Hey! Can we close this one or is there something still not working?

**Comment by 4ndv** [comment]
Yep, I think
