### ISSUE TITLE
Update has_one child model twice with  accepts_nested_attributes_for raises exception

### ISSUE THREAD

**Issue by unasuke** [rails/rails#35699]
### Steps to reproduce

https://gist.github.com/unasuke/f12ba68a6098541fec7cd6fbd50dc385

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails"
  gem "sqlite3", "~> 1.3.6"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :addresses, force: true do |t|
    t.integer :user_id, null: false
    t.string :postal_code, null: false
  end
end

class User < ActiveRecord::Base
  has_one :address, inverse_of: :user
  accepts_nested_attributes_for :address
end

class Address < ActiveRecord::Base
  belongs_to :user, inverse_of: :address
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create!
    user.update!(address_attributes: {postal_code: '1234'})
    user.update!(address_attributes: {postal_code: '6789'})
  end
end
```

### Expected behavior

No raises an exception.

### Actual behavior

That raises `ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: addresses.user_id: UPDATE "addresses" SET "user_id" = ? WHERE "addresses"."id" = ?`

(full stacktrace is here → https://gist.github.com/unasuke/f12ba68a6098541fec7cd6fbd50dc385#gistcomment-2869293 That's using ActiveRecord 5.2.2 , But master is fail also.)

### System configuration
**Rails version**: master

**Ruby version**: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]

**Comment by gmcgibbon** [comment]
The correct behaviour is that the second call will create a new record, according to the test suite. You need specify an ID on subsequent attribute assignments to touch the same record. The problem here is that when it calls `build_address` on the `User` record to build a new `Address`, it needs to unassign the current address, and set the foreign key to null, which executes an update and causes raises this error.

**Comment by sikachu** [comment]
@gmcgibbon's answer is correct. It's also because the `address_attributes` does not include `id` attribute as well, so Rails will try to create a new record. This is an intended behavior.

If you want the second call to always updating the created `Address`, you can actually set `:update_only

**Comment by sikachu** [comment]
@gmcgibbon's answer is correct. It's also because the `address_attributes` does not include `id` attribute as well, so Rails will try to create a new record. This is an intended behavior.

If you want the second call to always updating the created `Address`, you can actually set `:update_only` to tell Rails to update the current model rather than creating new one.

Given that this is an intended behavior, I'm going to close this.
