### ISSUE TITLE
ActiveStorage migration with custom record_id type

### ISSUE THREAD

**Issue by tbuehlmann** [rails/rails#35746]
An application I'm working with uses UUIDs for primary keys. When I generated the migration for ActiveStorage, it created the `active_storage_attachments.record_id` column using the `:bigint` type as it's the default:

https://github.com/rails/rails/blob/7c87fd5635fd830905e17d3cbf1eb2a2215acedf/activestorage/db/migrate/20170806125915_create_active_storage_tables.rb#L17

https://github.com/rails/rails/blob/7c87fd5635fd830905e17d3cbf1eb2a2215acedf/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L129

This lead to funny behaviour where models seemed to have attachments, but really didn't:

```ruby
my_model = MyModel.first
my_model.id # => '8a458af9-1ae9-4704-ab47-0a54390c3328'

unrelated_attachment = ActiveStorage::Attachment.first
unrelated_attachment.record_type # => 'MyModel'
unrelated_attachment.record_id # => 8

my_model.some_has_one_attachment.attached? # => true, since '8a458af9-1ae9-4704-ab47-0a54390c3328'.to_i == 8
```

It was eventually my fault for not checking and updating the generated migration, but it'd be great if others wouldn't have to go through this, too. Is this something we would like to be respected in ActiveStorage or shall this stay as is; the developer's responsibility?

If it is, here's a first thought about a solution:

I don't think the foreign key type is configurable in general, but the primary key type is for generators:

```ruby
# config/application.rb

config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid
end
```

So we could do something like this in the migration:

```ruby
if type = Rails.configuration.generators.options.dig(:active_record, :primary_key_type)
  t.references :record, null: false, polymorphic: true, index: false, type: type
else
  t.references :record, null: false, polymorphic: true, index: false
end
```

### System configuration
**Rails version**: 6.0.0.beta3

**Ruby version**: 2.6.2

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Also, please check #32466. Thanks!

**Comment by tbuehlmann** [comment]
Thanks!

**Comment by asmrtfm** [comment]
```rb
# Rails version 7.2.2.2
# Ruby version 3.2.4

> User.all

[ #<User id: "57c76dd3-5f17-4674-a44e-f5ab8787e181", ...,
 #<User id: "b3669168-0012-4250-95ed-2be1250b8bb2", ... ]


>  ActiveStorage::Attachment.where(record_type: "User")

[#<ActiveStorage::Attachment:0x00007cfd8f0fa640 id: 1407, name: "picture", record_type: "User", record_id: 57, blob_id: 1407, created_at: "2025-11-09 02:19:19.002199000 +0000">,
 #<ActiveStorage::Attachment:0x00007cfd8f0f7440 id: 1409, name: "picture", record_type: "User", record_id: 0, blob_id: 1409, created_at: "2025-11-09 02:21:00.976084000 +0000">]
```

My users has_one :attachment called 'picture'
Somehow, the first user I attach an image to works fine, and the above shows it somehow gets a record_id of 57.
However, all subsequent users fail to attach an image.
No errors are thrown and the logs are identical to the one which succeeded.
The only difference is that they all get a record_id of 0.

I have experimented with altering the create_active_storage_tables migration as follows:
```rb
      create_table :active_storage_attachments, id: primary_key_type do |t|
        t.string     :name,     null: false
        # t.references :record,   null: false, polymorphic: true, index: false, type: foreign_key_type
        t.references :record,   null: true, polymorphic: true, index: false
        t.references :blob,     null: false, type: foreign_key_type
        ...
```

Nothing seems to change.
However, before running my altered migration, if I tried to manually update the attachment's record_id to be the user's actual id, I would get errors about a not null constraint.  This is why I also set `null: true` in the migration.
After recreating active storage tables with my altered migration, I do not get that error, but the record_id is still set to nil.

I assume this is the result of some validation somewhere but due to lack of documentation and no code comments, I am currently still trying to hunt it down.

That being said, if I'm correct, then why not just remove that validation?  I realize that all sides of these changes have there trade-offs, but the current behavior seems like the worst of them by far.

Has anyone found a work around for projects that use active storage but do not use integer IDs for all of their tables?
My project, for example, uses UUID where we consider it necessary, but otherwise stick with integers.

This seems like something that deserves to be handled, even if only through better documentation of this problem and explanation of any known work-arounds.
