### ISSUE TITLE
Migration guide documentation for add_column implies `index: true` is not ignored

### ISSUE THREAD

**Issue by LucasBrandt** [rails/rails#35752]
https://edgeguides.rubyonrails.org/active_record_migrations.html#column-modifiers
```
Column modifiers can be applied when creating or changing a column:
...
index Adds an index for the column.
```

However, as discussed in https://github.com/rails/rails/issues/20400, `index: true` is silently ignored by `add_column`. [The api docs](https://edgeapi.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_column) reflect this, but the guide doesn't.

**Comment by y-yagi** [comment]
Thanks for your report. Can you create a PR?

**Comment by dogweather** [comment]
@y-yagi I'd really like to contribute code to no longer silently ignore options like this. [Here too, for example.](https://github.com/rails/rails/issues/20400#issuecomment-477525837). I believe this would be a positive philosophical shift: instead of a documentation issue, we can think of this as a UX issue for framework users.

Do you think that PR's for this kind of work would be welcomed? E.g., checking supplied options and if there's an unknown one, then at a minimum log a `WARN` message. I also think there's a good case to make to go further and raise because we won't be able to perform according to user's expectations. A middle ground would be an option to "treat warnings as errors."
