### ISSUE TITLE
Job adapter setting ignored in seeds

### ISSUE THREAD

**Issue by trcarden** [rails/rails#35812]
### Steps to reproduce

1. Configure a job adapter in application.rb that is NOT `:inline`
1. Create seeds file that executes an ActiveJob

### Expected behavior
Rails should honor your configuration in application.rb

### Actual behavior
Rails forces seeds to execute with the `:inline` adapter

### System configuration
**Rails version**: 5.2.3
**Ruby version**: 2.6.2

### Why is this a issue
We would like to be able to override the defaults but can't because of this commit: https://github.com/rails/rails/commit/66cc0e768fb092dbcd12feb3387c2a22e4cbeb37#diff-1073ed8063cdf047e123bfdefa114422R551

Generally I like the new default however it should not override an adapter if we have one set already. Seeds should not be a "special" context where our configuration is overridden especially when explicitly configured another way.

**Comment by trcarden** [comment]
As a workaround I have placed our adapter setting in ApplicationJob instead which seems to bypass the forced inline configuration.

```ruby
class ApplicationJob < ActiveJob::Base
  # TODO: Remove me once this is fixed: https://github.com/rails/rails/issues/35812
  self.queue_adapter = XXXX
end
```

**Comment by prathamesh-sonpatki** [comment]
@trcarden This is happening because of this change: https://github.com/rails/rails/pull/34953

The seeding process explicitly uses inline adapter now.

**Comment by rafaelfranca** [comment]
Seeds will execute with inline adapter because they are special. The default is still `:async` with exception of seeds, so the documentation is still correct.

Only overriding the adapter if it is not set is an option but I believe that will create inconsistence. The job will only execute if you have a different process running in development when your adapter is not `async` or `inline` and that means that depending on how you are running the application the state of your database will be different. I'd prefer to have a consistent state and this is what always setting the inline adapter on seed is also trying to accomplish.

**Comment by trcarden** [comment]
@rafaelfranca If this is intentional ok, it seems inconsistent to me to have the adapter change despite explicitly setting it in application.rb (we don't use any of the built in adapters). 

My big question is how do we turn it off if we want to without hacks? We have jobs that run as part of our seeds that we don't want to run inline as they are heavy or reach out to 3rd party systems. That should still be allowed right?

**Comment by rafaelfranca** [comment]
If you don't want those jobs to run when seeding you application you should be explicit about it in your code, not relying on them not be executed just because your job runner is not up. If for some reason your job runner is up when running the seeds the jobs will be executed.

You are relying exactly on the inconsistence I said this commit is fixing. So something like:

```
# db/seed.rb
JobThatIdontWantToRunWhenSeeding.disable!
```

Would be more intention revealing.

**Comment by pwim** [comment]
I'm running into issues due to the combination of this change, and that the inline queue adapter doesn't allow queuing of jobs in the future.

In some of my models I have code like 

``` ruby
class SomeModel < ApplicationRecord
  after_create { SomeJob.set(wait_until: 5.minutes.from_now).perform_later(self) }
end
```

This means I can no longer run my seeds, as it fails with `NotImplementedError: Use a queueing backend to enqueue jobs in the future.`

These jobs aren't essential to my seeding process, and so could theoretically be skipped, but it doesn't matter if they are performed either, so I'd rather not modify code to aid seeding. I understand my situation is a bit of an edge case, and maybe isn't worth handling cleanly within Rails itself, but I suspect others will probably encounter it too, and it isn't immediately obvious why the queue adapter is different when running the seeds. 

My workaround is to set the queue adapter explicitly back to my development queue adapter by placing at the top of my db seeds:

``` ruby
ActiveJob::Base.queue_adapter = Rails.application.config.active_job.queue_adapter
```

(this is basically what @trcarden is suggesting, but the block for `ActiveSupport.on_load` is unnecessary)

**Comment by rafaelfranca** [comment]
That is a good point. I think we should change to only change the adapter to inline if the adapter is the `:async` one. Mind to open an PR?

**Comment by trcarden** [comment]
@rafaelfranca I think you might be misunderstanding my point. We aren't relying on the job runner not running, we have a completely custom one we want to run in there instead. It's very similar to @pwim above except we have a custom adapter that is not `async` or `inline`. 

Also @pwim if you have mailers that are running on a special adapter the `ActiveJob::Base.queue_adapter` won't catch those. 

Also if we go all the way back up the stack for why this discrepancy was introduced was because of this: https://github.com/rails/rails/issues/34939 (it looks like a threading issue). Ironically I have already run into this same problem https://github.com/rails/rails/issues/34310. I don't think we should be patching the seeds job runner files to work around a DB shared lock issue. (I think making it go back to async will just reintroduce the same issue from https://github.com/rails/rails/issues/34939)
