### ISSUE TITLE
Objects cached in Rails 5.1.7 cannot be retrieved in Rails 5.1.4 - Redis

### ISSUE THREAD

**Issue by curtp** [rails/rails#35836]
Upgraded Rails to version 5.1.7 and ran the app for a while.  Rolled back to previous version which was 5.1.4 and received errors when trying to retrieve data cached when running 5.1.7.  Data cached with 5.1.4 can be retrieved in 5.1.7.

Hopefully we won't need to roll back when we deploy the upgrade into production.  This will prevent us from being able to roll back to the previous version or have a mix of 5.1.4 and 5.1.7 running at the same time while deploying.

### Steps to reproduce
Start Rails 5.1.7
Cache an array of objects
bids = Bid.where(type: "proxy").to_a
Rails.cache.write("5.1.7_bids", bids)

Start Rails 5.1.4
Read the cached object
Rails.cache.read("5.1.7_bids")

### Expected behavior
Should be able to retrieve the cached content

### Actual behavior
Receive the following error when trying to retrieve the key:
(Object doesn't support #inspect)

### System configuration
**Rails version**:
5.1.7 & 5.1.4

**Ruby version**:
2.3.1p112

**Redis Version**:
2.8.4

**Redis Gem**:
gem "redis-rails", "5.0.2"

**Comment by rafaelfranca** [comment]
We don't guarantee cached objects works between two versions. Caching of objects rely on Marshal that uses internal data of objects to serialize and serialize. Internal data of objects can change between any version, because they are internal and not part of the public API.

But it would be good if you post the error backtrace so we could understand what is failing so maybe we can do something about it.

**Comment by rafaelfranca** [comment]
This is probably caused by https://github.com/rails/rails/commit/f45de5d190ee57d25ca9bda2a9ea0db6ce53f19f.

We made it able to read the cache dumped from < 5.1.7 but a version behind it can't read the 5.1.7 format.

We don't guarantee an older version will be able to read data generated by a new version, so probably you would have to flush the cache when upgrading.

**Comment by curtp** [comment]
There isn't a stack trace. When I run it in rails console the only output I get is (Object doesn't support #inspect)

I ran it from rails console and the app.  When it fails in the app, the stack trace is all within our code.

**Comment by rafaelfranca** [comment]
It is very likely it was that change, but I don't think we support that use case. You will need to flush the cache after the rollback or add the rails version as prefix of the cache key.
