### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message_types' of undefined

### ISSUE THREAD

**Issue by zaviermiller** [rails/rails#35846]
### Steps to reproduce
To reproduce simply run a patch request in a link_to on Heroku. This error does not occur in development.

### Expected behavior
The patch method should be run because of the data-method which is equal to "patch"

### Actual behavior
Heroku tries to run it as a get method. This is most likely due to the error message in the title which I believe is from the ujs-rails library.

### System configuration
**Rails version**: Rails 5.2.1

**Ruby version**: ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by zaviermiller** [comment]
@rafaelfranca yep, http://test.blinddogclothing.com/products/prod_Eowo9YytqvNEov

**Comment by rafaelfranca** [comment]
I'm asking for the code, not the running application. It would be even more helpful if ti was a new generated application to show us that the problem is in the framework and not in the code that you wrote. In other words we need a way to reproduce the issue ourselves, so we are able to identify what the error is, when it happens, where, and how to fix.

**Comment by rwojnarowski** [comment]
@zaviermiller did you look at this issue with assets on heroku? https://stackoverflow.com/questions/31239576/heroku-proccessing-put-and-delete-request-as-get-rails-4 ? 

`
If you have precompiled assets before, heroku will always serve the last precompiled version. You need to run rake assets:clobber both on localhost and heroku
`
