### ISSUE TITLE
time_zone_options_for_select: Priority Regexp Fails Unless #=~ is Defined on Zone Class

### ISSUE THREAD

**Issue by sshaw** [rails/rails#35973]
### Steps to reproduce

```
select_tag "timezone", time_zone_options_for_select(nil, some_regexp, TZInfo::Timezone)
```
### Expected behavior

Zones returned by `TZInfo::Timezone.all` or any model passed as the 3rd argument to match `some_regexp`

### Actual behavior

Since `TZInfo::Timezone` and its subclasses do not define `#=~` [the priority zone regexp never matches](https://github.com/rails/rails/blob/7c87fd5635fd830905e17d3cbf1eb2a2215acedf/actionview/lib/action_view/helpers/form_options_helper.rb#L583). 

`ActiveSupport::TimeZone` does define this method so it's not an issue. 

Maybe convert to string if`!zones[n].respond_to?("=~")`. Converting everything to a string and then attempting to match will break existing behavior. 

### System configuration
**Rails version**:  6 beta 3

**Ruby version**: 2.3

**Comment by itsWill** [comment]
I think we should definitely support models that don't implement `~=` or at least document that as a requirement. 

Since `TZInfo` is available we can writing a failing test is fairly straightforward: 

``` ruby
  def test_timezone_options_for_select_with_regex_priority_zones_that_dont_implement_match_operator
    expected_options =  "<option value=\"Zulu\">Zulu</option>" \
      "<option value=\"\" disabled=\"disabled\">-------------</option>\n"


    TZInfo::Timezone.stub :all, [ TZInfo::Timezone.get('Zulu') ] do
      options = time_zone_options_for_select(nil, /Zulu/, TZInfo::Timezone)

      assert_dom_equal expected_options, options
    end
  end
```

I like the approach of checking if `zones[n].respond_to?("=~")` to decide wether to convert to a string or not, although we can maybe assume that if the first `zone` in `zones` implements `~=` they all do, this is to avoid checking `responds_to` for every zone. 

If you are not interested in PR this up I'm happy to give it a go.

**Comment by sshaw** [comment]
Thanks. I can put something together in a day or two.

**Comment by sshaw** [comment]
Branch is here: https://github.com/sshaw/rails/tree/fix_time_zone_options_priority

Problem: I forgot that `#=~` is defined on Object. So `respond_to?("=~")` wont work. Ideas?

**Comment by itsWill** [comment]
> Problem: I forgot that #=~ is defined on Object. So respond_to?("=~") wont work. Ideas?

Oh great point!  IMO then we shouldn't solve this at the framework level, but rather whoever is passing in the `priority_zones` regex should make sure that they can match the results returned from `model.all`.  I think this is something we can document better. 

It's possibly better to submit a patch to `TZInfo` so that a `=~` does a match against the zone name.

**Comment by sshaw** [comment]
> .... whoever is passing in the priority_zones regex should make sure that they can match the results returned from model.all

This is the problem. One cannot since `TZInfo::Timezone` does not (re)define `#=~` . I guess the fix is to mention in the docs that the instances must define `#=~` to use regexp matching.

> It's possibly better to submit a patch to TZInfo so that a =~ does a match against the zone name, methinks the fix should probably live there.

Agreed. But it's possible that they don't want it to be used in regexp, hence no definition. We'll see.

Otherwise the workaround would be:

```rb
time_zone_options_for_select(f.object.timezone, TZInfo::Timezone.all.select { |tz| tz.name =~ /\A(?:US|Canada)/ }, TZInfo::Timezone)
```

**Comment by itsWill** [comment]
The PR to define `=~` has been merged upstream on TZInfo so if we’re using master TZInfo we no longer need that work around. I’d suggest closing the issue, but understand if you want to keep it open until the docs are improved.

**Comment by sshaw** [comment]
Hi, great to see!

I updated my PR. It contains changes to the docs that better describe the required interfaces for the model argument.
