### ISSUE TITLE
`update_counters` doesn't respect scopes

### ISSUE THREAD

**Issue by henrik** [rails/rails#36055]
### Steps to reproduce

I run code like `Item.with_finite_inventory.update_counters(item_id, inventory_count: -quantity)`.

That scope is defined as `scope :with_finite_inventory, -> { where("inventory_count IS NOT NULL") }`.

### Expected behavior

I expected it to do nothing for an `item_id` that does not match the scope – in this case, one that has infinite inventory (`inventory_count` is NULL).

Or alternatively, to raise an exception saying the use of scopes here is not allowed.

### Actual behavior

Instead, the scope is ignored:

```
>> Item.with_finite_inventory.update_counters(1140, inventory_count: 0)
  Item Update All (2.4ms)  UPDATE "items" SET "inventory_count" = COALESCE("inventory_count", 0) + 0 WHERE "items"."id" = $1  [["id", 1140]]
=> 1
```

### System configuration

This is in a Rails 5.2.0 project, but from a quick look through issues and code, I think this issue might remain in edge Rails.

Ruby 2.5.1.

**Comment by yoones** [comment]
This is not a bug since `#update_counters` calls `#unscope` first.
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/counter_cache.rb#L105

```ruby
def update_counters(id, counters)
  unscoped.where!(primary_key => id).update_counters(counters)
end
```

That being said, I agree that maybe  `#update_counters` shouldn't take an `id` argument and let us do something like this:

```ruby
Model.whatever_scope.where(id: some_ids).update_counters(inventory_count: -quantity)
```

**Comment by itsWill** [comment]
On rails 6 this is actually supported since this commit: https://github.com/rails/rails/commit/975fa15b47e4ef47a3b46f0e946860a076167149

Since then you can do something like: `ItemInventory.with_finite_inventory.update_counters(inventory_count: -1)` and it should happily work as long as you call it on a relation. 

I think there is a nice opportunity to document and have it in the public docs api.

**Comment by yoones** [comment]
@itsWill While your PR is useful for it adds a missing method documentation, it is not linked to this issue (in the above-example `with_finite_inventory` is a scope, not an association).

**Comment by itsWill** [comment]
🤔 I could be interpreting this issue incorrectly, my reasoning is according to the [docs](https://guides.rubyonrails.org/active_record_querying.html#scopes) a `scope` will always return an `ActiveRecord::Relation`. 

Since the [method](https://github.com/rails/rails/blob/975fa15b47e4ef47a3b46f0e946860a076167149/activerecord/lib/active_record/relation.rb#L372) I was suggesting is defined on an `ActiveRecord::Relation`  we should be able to chain it with a scope or any other method that returns a `ActiveRecord::Relation`. So the api suggested: `Model.whatever_scope.where(id: some_ids).update_counters(inventory_count: -quantity)
`  above should correctly on the latest master, no?

**Comment by yoones** [comment]
> thinking I could be interpreting this issue incorrectly, my reasoning is according to the [docs](https://guides.rubyonrails.org/active_record_querying.html#scopes) a `scope` will always return an `ActiveRecord::Relation`.
> 
> Since the [method](https://github.com/rails/rails/blob/975fa15b47e4ef47a3b46f0e946860a076167149/activerecord/lib/active_record/relation.rb#L372) I was suggesting is defined on an `ActiveRecord::Relation` we should be able to chain it with a scope or any other method that returns a `ActiveRecord::Relation`. So the api suggested: `Model.whatever_scope.where(id: some_ids).update_counters(inventory_count: -quantity) ` above should correctly on the latest master, no?

You're right, it works fine. My bad!

**Comment by henrik** [comment]
Thank you everyone. I take it it does work in master, so I'll close this ticket :)
