### ISSUE TITLE
db:drop loads the full environment but db:create does not

### ISSUE THREAD

**Issue by Ferdy89** [rails/rails#36056]
### Steps to reproduce
* Write `raise 'foo'` on top of the `config/environments/development.rb` file
* Running `db:drop` hits the raised exception; `db:create` doesn't

### Expected behavior
Considering both commands are complementary to each other, I would expect them to load the same kind of environment files.

### Actual behavior
The `db:drop` task runs `db:check_protected_environments`, which loads the full environment. `db:create` doesn't have such checks, so it doesn't.

We ran into this because we're using `dotenv` to load some env vars in our `config/environments/development.rb` file, which are available during `db:reset` but not during `db:create`. We realized this is what was happening after scratching our heads for a while.

We can solve our issue by throwing our configs in `config/application.rb`, but I wonder if this is something worth making less confusing for everybody. I browsed the documentation for clarification over this particular point and I couldn't find any. I think `db:create` is virtually the only rake task in ActiveRecord that has this behavior.

Let me know if this is something worth spending any time into, I'm happy to help with any proposed solution. Thank you!

### System configuration
**Rails version**: `master`

**Ruby version**: 2.5.1

**Comment by itsWill** [comment]
Hey @Ferdy89 I looked to see if  could come up with a suggest approach, but I'm struggling to reproduce it on the latest master. Here's what I got: 

The `create` and `drop` and pretty much all other tasks within `db` depend on `load_config` being executed before.

The load config task depends on the `environment` task which requires the environment: 
https://github.com/rails/rails/blob/b1458218c95d85c4ce911dd3e99da5ae7cf7aeee/activerecord/lib/active_record/railties/databases.rake#L16-L19

The `environment` task is defined here: https://github.com/rails/rails/blob/e81f20702a69ab5d8a8a150a5d1d178c0e1da792/railties/lib/rails/application.rb#L516-L519

You can see that it requires the environment, and what I see is that the `raise` is caught on both `db:drop` and `db:create` operations.

The `check_protected_environments` method might actually be a red herring here, since even when I remove it as  dependency on the `db:drop` task I still hit the raise, and in fact the stacktrace for both `db:drop` and `db:create` shows its the `environment` task that is calling the `development.rb` file. 

I'm not sure where your issue is coming from and I'm not familiar with `.dotenv`, but it seems like these rake tasks do require the environment.

**Comment by Ferdy89** [comment]
Oh wow, I guess I was not running `master` after all, but version 5.1 instead. Very sloppy move on my part, I'm so sorry to have made you spend any time on this! I'll double check next time.

Seems like my solution is to upgrade my Rails version 😃 Thank you so much for helping me out! And again, sorry for my bad reproduction steps.

**Comment by itsWill** [comment]
No worries! ❤️
