### ISSUE TITLE
ActiveSupport::Cache::MemoryStore - undefined method 'megabytes'

### ISSUE THREAD

**Issue by belgoros** [rails/rails#36076]
As explained in the corresponding section of [Caching with Rails Guide](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-memorystore) I added the following line to `config/environment/staging.rb`file:
```
Rails.application.configure do
...
  config.cache_store = :memory_store, { size: 64.megabytes }
...
end
```
When starting the Puma server, it raised the error:
```
undefined method `megabytes' for 64:Integer
```
Adding the following line:
```
require 'active_support/core_ext/numeric/bytes'
```
on the top of the `staging.rb` file fixed the error.

Does it seem the Guides are missing this detail? 
### System configuration
**Rails version**: `5.2.0`

**Ruby version**: `2.6.1`

**Comment by st0012** [comment]
It's a good point, but I think mentioning that in the doc is quite distracting. Because the purpose of that document is for you to know what configs are available instead of a tutorial that you'll need to copy and paste. So if you take a look at those code blocks in the guide, most of them will break if you just copy and paste them.

**Comment by belgoros** [comment]
@st0012 OK, it is just to be sure that I'm not missing anything 😄. In this case, I think it is worth to close the issue.
