### ISSUE TITLE
DateTime, Date comparison doesn't work as expected

### ISSUE THREAD

**Issue by yazinsai** [rails/rails#36175]
### Steps to reproduce

```ruby
may1 = Date.today.beginning_of_month # => Wed, 01 May 2019
may31 = Date.today.end_of_month # => Fri, 31 May 2019

(may1..may31).include? Date.today # => True
(may1..may31).include? DateTime.now # => False
```

### Expected behavior
`(may1..may31).include? DateTime.now` should return `True` for DateTime's in the same month

### Actual behavior
It returns `False`

### System configuration
**Rails version**: Rails 5.2.3

**Ruby version**: ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]

**Comment by chukitow** [comment]
You are trying to compare `DateTime` against `Date`. Your example will work if you change your last expectation with:

```ruby
may1..may31).include? DateTime.now.to_date
```

**Comment by yazinsai** [comment]
I realize that, but my expectation was that DateTime comparison with Date should Just Work

**Comment by kamipo** [comment]
I feel this is an issue for Ruby itself.
Can you file an issue on https://bugs.ruby-lang.org/ ?

**Comment by st0012** [comment]
@kamipo I created https://bugs.ruby-lang.org/issues/16440 for this issue

**Comment by st0012** [comment]
Actually, if the purpose is to check if the given date range covers a specific Date or Datetime, I think [`Range#cover?`](https://ruby-doc.org/core-2.6.4/Range.html#method-i-cover-3F) should be a better API to use.

The grey area of `Range#include?` is that we're not sure if it should treat the date range *a series of individual days*, or *a continuous range between 2 specific times*. This might take some debate to decide. So my suggestion to @yazinsai or anyone that comes across this issue is to just use `Range#cover?` ;-)
