### ISSUE TITLE
eager load doesn't work as expected in Action Text

### ISSUE THREAD

**Issue by willnet** [rails/rails#36177]
### Steps to reproduce

1. create rich texts with attachments
2. access index action and watch logs

```ruby
class Message < ApplicationRecord
  has_rich_text :content
end

class MessagesController < ApplicationController
  def index
    @messages = Message.with_rich_text_content_and_embeds
  end
end
```

```erb
<% @messages.each do |message| %>
  <%= message.content %>  
<% end %>
```

### Expected behavior

Avoid N+1

### Actual behavior

The query fetch blobs is executed as many times as the number of blobs. Because ActionText::Content has attachments as GlobalID and fetch it directly without using associations.

I think it is confusing behavior so it should be documented at least.

### System configuration
**Rails version**:

6.0.0.rc1

**Ruby version**:

2.6.3

**Comment by st0012** [comment]
I can confirm that this is valid. It'll generates 3 queries

```sql
SELECT "messages".* FROM "messages"
SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_type" = ? AND "action_text_rich_texts"."name" = ? AND "action_text_rich_texts"."record_id" IN (?, ?)
SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ? AND "active_storage_attachments"."record_id" IN (?, ?).
```

test script: 

```ruby
  test "loading content without n+1 query" do
    Message.create!(subject: "Greetings", content: "<h1>Hello world</h1>")
    Message.create!(subject: "Greetings2", content: "<h1>Hello world2</h1>")

    assert_queries(1) do
      Message.with_rich_text_content_and_embeds.to_a
    end
  end
```

output:

```
....F

Failure:
ActionText::ModelTest#test_loading_content_without_n+1_query [/Users/st0012/projects/rails/actiontext/test/unit/model_test.rb:99]:
3 instead of 1 queries were executed.
Queries:
SELECT "messages".* FROM "messages"
SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_type" = ? AND "action_text_rich_texts"."name" = ? AND "action_text_rich_texts"."record_id" IN (?, ?)
SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ? AND "active_storage_attachments"."record_id" IN (?, ?).
Expected: 1
  Actual: 3
```

I can fix it. However, on current master the `assert_queries` assertionn only lives in activerecord component. If we want to use it here like the script I pasted above, we may need to merge https://github.com/rails/rails/pull/36031 first.

**Comment by st0012** [comment]
@willnet how did you spot this issue? I can't reproduce this on latest master. In my experiment, the code you posted did create multiple queries. But they're created by `includes` to load the data separately:

```sql
SELECT "messages".* FROM "messages"
SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_type" = ? AND "action_text_rich_texts"."name" = ? AND "action_text_rich_texts"."record_id" IN (?, ?)
SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ? AND "active_storage_attachments"."record_id" IN (?, ?).
```

Can you provide a script/app that can reproduce this issue?

**Comment by willnet** [comment]
@st0012 created a sample app to reproduce. I can reproduce it on latest master.

[willnet/actiontextnplus1](https://github.com/willnet/actiontextnplus1)

**Comment by st0012** [comment]
@willnet Thanks for the repo, I do find it weird now 🤔

**Comment by st0012** [comment]
I’ll need to explain the whole AS attachment rendering process in ActionText in order to point out the cause of n+1 queries.
These are the steps for rendering `message.content`:

1. Load the message’s associated `ActionText::RichText` record
2. Load blobs of the rich text record
3. Go through every blob and get their `sgid`
4. Put `sgid` in `action-text-attachment` node. A node should look like this:

```html
<action-text-attachment sgid=\"BAh7CEkiCGdpZAY6BkVUSSIxZ2lkOi8vZHVtbXkvQWN0aXZlU3RvcmFnZTo6QmxvYi8xP2V4cGlyZXNfaW4GOwBUSSIMcHVycG9zZQY7AFRJIg9hdHRhY2hhYmxlBjsAVEkiD2V4cGlyZXNfYXQGOwBUMA==--fdcd06e5fd87f77a4a93a9274311e764906cb6c9\" content-type=\"image/jpeg\" filename=\"racecar.jpg\" filesize=\"1124062\" previewable=\"true\"></action-text-attachment>
```

5. Then ActionText will search for `action-text-attachment` nodes and start to put attachment contents inside the node.
6. If the node has `sgid` attribute, Action Text will use the `sgid` to find the blob (via a gem called `globalid`) individually. 
7. Once it finds the attachment, it’ll render an image node and put it into the result. It’ll looks like this:

```html
<action-text-attachment sgid="BAh7CEkiCGdpZAY6BkVUSSIxZ2lkOi8vZHVtbXkvQWN0aXZlU3RvcmFnZTo6QmxvYi8zP2V4cGlyZXNfaW4GOwBUSSIMcHVycG9zZQY7AFRJIg9hdHRhY2hhYmxlBjsAVEkiD2V4cGlyZXNfYXQGOwBUMA==--b8c42cc1ed19bf24a8340ee9b8d4cccf679a4ead" content-type="image/jpeg" filename="racecar.jpg" filesize="1124062" previewable="true"><figure class="attachment attachment--preview attachment--jpg">
    <img src="http://example.org/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--423f0314dd3e5a0acfa8fe3f7c26e0fe2c025694/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9VY21WemFYcGxYM1J2WDJ4cGJXbDBXd2RwQWdBRWFRSUFBdz09IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--97ed443daf2b1beef08b2e5a52d3ad206be00a33/racecar.jpg">

  <figcaption class="attachment__caption">
      <span class="attachment__name">racecar.jpg</span>
      <span class="attachment__size">1.07 MB</span>
  </figcaption>
</figure></action-text-attachment>
```

The n+1 query would happen at the 6th step. Because at this phase Rails doesn’t know anything about the previous query, it can’t benefit from previous eager loading and needs to find attachments one by one.

I wonder if Rails team would agree to advance AS blob rendering to the 4th step, then we won’t need to find each blob via `globalid` and cause these n+1 queries.

**Comment by st0012** [comment]
Short explaination for the cause:

`ActionText` doesn't load the blobs via relationship. It loads the blobs in following steps:

1. It parses the content into a tree structure.
2. It goes through each attachment node and find a way to display them.
3. If a node is a file attachment, it takes its `sgid` attribute and uses a gem called [globalid](https://github.com/rails/globalid) to find the blob.


https://github.com/rails/rails/blob/99650550e8dbd7a2f3248d5a0231dda92f58b111/actiontext/lib/action_text/attachable.rb#L22-L26

And it's essentially like 

```ruby
ActiveStorage::Blob.find(decoded_id)
```

Since blobs are found individually when going through each attachment element, it gets 0 benefit from the eager loading scope. In fact, in some cases, it’s even worse to use those scopes because it creates extra queries to eager load the data we couldn’t use.

I'm preparing a blog post which will explain how `ActionText` deal with uploaded files, which would help understanding the cause. However, I don't think this is an issue that can be fixed in short time. It requries some redesign and more discussions.

**Comment by st0012** [comment]
@willnet I've opened a PR to demonstrate my solution for this issue, can you take a look?

**Comment by antoniobg** [comment]
Any update on this?

**Comment by st0012** [comment]
@antoniobg no any feedback atm. would you like to take a look at my spike PR for this issue? https://github.com/rails/rails/pull/36945

**Comment by francois-belle** [comment]
@willnet I'm curious: where did you find `#with_rich_text_content_and_embeds` scope? In a documentation?

**Comment by francois-belle** [comment]
Ok thank you @st0012 , I think it's quite important and maybe it should appear in the documentation, what do you think?

**Comment by st0012** [comment]
@francois-belle I actually prefer to remove them. As this issue reported, they don't really solve the n+1 query issue but just give you an illusion that they do.

**Comment by francois-belle** [comment]
My bad @st0012 , thanks a lot!

**Comment by rigbooks** [comment]
@st0012 removing the includes scope doesn't remove the N+1 for the blobs, but it does remove the N+1 for the attachments.

**Comment by willnet** [comment]
@zzak Yes it is. I've reworked the sample app with the latest rails https://github.com/willnet/actiontextplus1-part2
