### ISSUE TITLE
ActiveStorage::Variant can't composite Vips::Image instances

### ISSUE THREAD

**Issue by lengyelg** [rails/rails#36182]
### Steps to reproduce

In the `Gemfile`:

    gem 'image_processing'
    gem 'ruby-vips'

In `config/application.rb`:

    config.active_storage.variant_processor = :vips

In a model, say `pic.rb`:

    class Pic < ApplicationRecord
      ...
      has_one_attached :image
      ...
      def watermarked
        image.variant(composite: Vips::Image.jpegload('filename.jpg')).processed
      end
    end

The purpose would be to watermark an image with a Vips::Image created from `Vips::Image.text`, but plain image compositing already doesn't work, neither does any image compositing I could think of.

### Expected behavior

I would like the Vips::Image composited as the ImageProcessing documentation [describes](https://github.com/janko/image_processing/blob/master/doc/vips.md#composite).

Note that compositing works correctly when directly calling ruby-vips.

Also note that the same error is thrown if instead of directly creating an image with `Vips::Image.jpegload`, I create it with `ImageProcessing::Vips.source('filename.jpg').call(save: false)`

### Actual behavior

`TypeError: no _dump_data is defined for class Vips::Image::ManagedStruct` upon calling `#processed`.

[Full trace](https://gist.github.com/lengyelg/618f2c61a4394083725a7f32761e1a21)

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

**Comment by janko** [comment]
The issue is that `ActiveStorage::Variant` generates a key for the given transformation, which will be part of the upload location of the processed file. It does so by passing the transformations hash to `ActiveStorage::MessageVerifier`, which uses `Marshal` for serialization. However, `Marshal.dump` is failing to serialize a `Vips::Image`:

```rb
Marshal.dump({ composite: Vips::Image.new_from_file("test/fixtures/image.jpg") })
#~> TypeError: no _dump_data is defined for class Vips::Image::ManagedStruct
```

I think what's preventing Marshalling is that a `Vips::Image` object has an instance variable that derives from an FFI object (`FFI::Struct`), which ties to the libvips C library. It's probably complicated/not possible for Ruby to serialize that.

Not sure what would be a good solution.

**Comment by brenogazzola** [comment]
@janko Hey, now that Vips is the the Rails default, I was talking with a libvips maintainer about this bug and he's proposing something that would also require changes in image processing. Would you mind taking a look and giving us some input?

https://discuss.rubyonrails.org/t/make-vips-the-recommended-default-variant-processor-for-active-storage/78368/17
