### ISSUE TITLE
Rails attribute API typecast is not working properly with Dirty tracking of attributes

### ISSUE THREAD

**Issue by danielnc** [rails/rails#36199]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :post_titleizeds, force: true do |t|
    t.string :title
  end

  create_table :posts, force: true do |t|
    t.string :title
  end
end

# frozen_string_literal: true

class TitleizedType < ActiveRecord::Type::String
  def cast_value(value)
    value.downcase if value.present?
  end

  def serialize(value)
    value.titleize if value.present?
  end
end

class PostTitleized < ActiveRecord::Base
  attribute :title, TitleizedType.new
end

class Post < ActiveRecord::Base
end


class BugTest < Minitest::Test
  def test_attribute_dirty_typecast
    post = PostTitleized.new(title: "Titleized")

    assert_equal "titleized", post.title
    assert_equal({}, post.previous_changes)
    post.save!
    assert_equal "titleized", post.title
    assert_equal({"id"=>[nil, 1], "title"=>[nil, "titleized"]}, post.previous_changes)
    post.save!
    assert_equal "titleized", post.title
    assert_equal({}, post.previous_changes)
  end

  def test_attribute_dirty_without_typecast
    post = Post.new(title: "Titleized")

    assert_equal "Titleized", post.title
    assert_equal({}, post.previous_changes)
    post.save!
    assert_equal "Titleized", post.title
    assert_equal({"id"=>[nil, 1], "title"=>[nil, "TitleizedType"]}, post.previous_changes)
    post.save!
    assert_equal "Titleized", post.title
    assert_equal({}, post.previous_changes)
  end
end
```
### Expected behavior
I expect `PostTitleized` dirty attribute tracking for `attribute :title, TitleizedType.new` dirty tracking to behave same way as `Post`

After calling save twice on the object previous_changes should be empty like it is if I don't overwrite `attribute title`

### Actual behavior
dirty attribute tracking show same string and that the object changed, when it didn't

```
  1) Failure:
BugTest#test_attribute_dirty_typecast [bug.rb:64]:
--- expected
+++ actual
@@ -1 +1 @@
-{}
+{"title"=>["titleized", "titleized"]}
```
### System configuration
**Rails version**: 5.2.3

**Ruby version**:
2.5.3

**Comment by FumiyaShibusawa** [comment]
As long as I saw so far, it seems like only when setting `ActiveRecord::Type::String` it behaves weirdly. I tested another two types (`ActiveRecord::Type::Integer`, `ActiveRecord::Type::Time`), but both has passed.
https://gist.github.com/FumiyaShibusawa/04c9c49019c79d773c46dfe41fe785e3

It might something to do with when overriding serialization of `ActiveRecord::Type::String`. will keep diving into codebase a bit further...

**Comment by FumiyaShibusawa** [comment]
Ok, to make a long story very short, you need to override **#changed_in_place?(raw_old_value, new_value)** method in `TitleizedType` as appropriate.
https://api.rubyonrails.org/classes/ActiveModel/Type/Value.html#method-i-changed_in_place-3F

> ### changed_in_place?(raw_old_value, new_value)
> Determines whether the mutable value has been modified since it was read. Returns false by default. **If your type returns an object which could be mutated, you should override this method.** You will need to either:
> - pass `new_value` to #serialize and compare it to `raw_old_value`
> - pass `raw_old_value` to #deserialize and compare it to `new_value`

Here is the code which pass the test case. You override **#serialize** method, so you need to pass `new_value` to **#serialize**.

```ruby
class TitleizedType < ActiveRecord::Type::String
  def cast(value)
    value.downcase if value.present?
  end

  def serialize(value)
    value.titleize if value.present?
  end

  # raw_old_value: The original value, before being passed to deserialize.
  # new_value: The current value, after type casting.
  def changed_in_place?(raw_old_value, new_value)
    raw_old_value != serialize(new_value) if new_value.is_a?(::String)
  end
end
```

## How `raw_old_value` and `new_value` are manipulated beforehand

`raw_old_value` is from database, `new_value` is from `PostTitleized` instance's attributes after type casting. So in your case,

- `raw_old_value`: "Titleized" which is from the database, `serialize`d when `post.save!` for the first time.
- `new_value`: "titleized" which has been `cast` when fetched.

Initially, `changed_in_place?` is fired at `ActiveRecord::Type::String#changed_in_place?`, which `TitleizedType` inherits, but it doesn't expect the two arguments to be mutated by default. So if you override either #serialize or #deserialize, #cast, you should put the two args in the same condition.

## Why #previous_changes returns the same values
As in the failed test, post.changes returns `{"title"=>["titleized", "titleized"]}`.

In short, it's because both values are `cast` when fetched.

When #previous_changes fires, `mutations_before_last_save.changes` is executed inside.
```ruby
    def previous_changes
      @previously_changed ||= ActiveSupport::HashWithIndifferentAccess.new
      @previously_changed.merge(mutations_before_last_save.changes)
    end
```

And `mutations_before_last_save.changes` fires ActiveModel::AttributeMutationTracker#changes.

```ruby
    def changes
      attr_names.each_with_object({}.with_indifferent_access) do |attr_name, result|
        change = change_to_attribute(attr_name)
        if change
          result.merge!(attr_name => change)
        end
      end
    end
```

Inside this, #change_to_attribute is called, and both #original_value and #fetch_value(attr_name) do type casting before returning the value. That's why both values are downcased; `{"title"=>["titleized", "titleized"]}`.

```ruby
    def change_to_attribute(attr_name)
      attr_name = attr_name.to_s
      if changed?(attr_name)
        [attributes[attr_name].original_value, attributes.fetch_value(attr_name)]
      end
    end
```

---

This is what I found so far, please ping me again if still anything wrong with your codebase, or please some one correct me if I'm reading these wrong.

**Comment by FumiyaShibusawa** [comment]
@danielnc Ok, to make a long story very short, you need to override **#changed_in_place?(raw_old_value, new_value)** method in `TitleizedType` as appropriate.
https://api.rubyonrails.org/classes/ActiveModel/Type/Value.html#method-i-changed_in_place-3F

> ### changed_in_place?(raw_old_value, new_value)
> Determines whether the mutable value has been modified since it was read. Returns false by default. **If your type returns an object which could be mutated, you should override this method.** You will need to either:
> - pass `new_value` to #serialize and compare it to `raw_old_value`
> - pass `raw_old_value` to #deserialize and compare it to `new_value`

Here is the code which pass the test case. You override **#serialize** method, so you need to pass `new_value` to **#serialize**.

```ruby
class TitleizedType < ActiveRecord::Type::String
  def cast(value)
    value.downcase if value.present?
  end

  def serialize(value)
    value.titleize if value.present?
  end

  # raw_old_value: The original value, before being passed to deserialize.
  # new_value: The current value, after type casting.
  def changed_in_place?(raw_old_value, new_value)
    raw_old_value != serialize(new_value) if new_value.is_a?(::String)
  end
end
```

## How `raw_old_value` and `new_value` are manipulated beforehand

`raw_old_value` is from database, `new_value` is from `PostTitleized` instance's attributes after type casting. So in your case,

- `raw_old_value`: "Titleized" which is from the database, `serialize`d when `post.save!` for the first time.
- `new_value`: "titleized" which has been `cast` when fetched.

Initially, `changed_in_place?` is fired at `ActiveRecord::Type::String#changed_in_place?`, which `TitleizedType` inherits, but it doesn't expect the two arguments to be mutated by default. So if you override either #serialize or #deserialize, #cast, you should put the two args in the same condition.

## Why #previous_changes returns the same values
As in the failed test, post.changes returns `{"title"=>["titleized", "titleized"]}`.

In short, it's because both values are `cast` when fetched.

When #previous_changes fires, `mutations_before_last_save.changes` is executed inside.
```ruby
    def previous_changes
      @previously_changed ||= ActiveSupport::HashWithIndifferentAccess.new
      @previously_changed.merge(mutations_before_last_save.changes)
    end
```

And `mutations_before_last_save.changes` fires ActiveModel::AttributeMutationTracker#changes.

```ruby
    def changes
      attr_names.each_with_object({}.with_indifferent_access) do |attr_name, result|
        change = change_to_attribute(attr_name)
        if change
          result.merge!(attr_name => change)
        end
      end
    end
```

Inside this, #change_to_attribute is called, and both #original_value and #fetch_value(attr_name) do type casting before returning the value. That's why both values are downcased; `{"title"=>["titleized", "titleized"]}`.

```ruby
    def change_to_attribute(attr_name)
      attr_name = attr_name.to_s
      if changed?(attr_name)
        [attributes[attr_name].original_value, attributes.fetch_value(attr_name)]
      end
    end
```

---

This is what I found so far, please ping me again if still anything wrong with your codebase, or please some one correct me if I'm reading these wrong.

**Comment by danielnc** [comment]
@FumiyaShibusawa Thanks! It works

I am just wondering if rails should handle this case specifically or if we should improve documentation around string types and which methods should be overwritten

**Comment by FumiyaShibusawa** [comment]
@danielnc API documentation explains that so it will do, but maybe writing this in Railsguide's ActiveModel page could be more dev friendly, though. You can check the relevant commits back like this https://github.com/rails/rails/pull/15788.

Anyway, happy to hear it works. please close this issue if ok. ☺️
