### ISSUE TITLE
config.eager_load has no default

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#36211]
### Steps to reproduce

- remove `config.eager_load = ...` from a rails app

https://github.com/localhostdotdev/bug/tree/eager-load-mendatory

### Expected behavior

- defaults to either true or false

### Actual behavior

- ~~error message~~ warning message:

```
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true
```

### System configuration

**Rails version**: Rails 6.0.0.rc1
**Ruby version**: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]

**Comment by abhaynikam** [comment]
@localhostdotdev I looked at the reproduction app added here. It throws a warning in logs when `config.eager_load` is removed but I think the reproduction app do not have environments config for `development`, `test` or `production`.

Environments config by defaults adds the config for `eager_load` due to which I think the default is not set by Rails. And as the warning message says, it should be different for different env so no need to set the default for `config.eager_load`.

I am no expert here, these are just my findings.

**Comment by localhostdotdev** [comment]
oh right good call, thought it was an error for some reason, it's just a warning, still I think a default should be set (I will edit the issue).

**Comment by rafaelfranca** [comment]
There is no default value because we want to explicitly ask people to set this value. It is a deliberate choice. Thank you for the issue.
