### ISSUE TITLE
Add support for range in where with negative infinity

### ISSUE THREAD

**Issue by PragmaticEd** [rails/rails#36308]
Using range search in active record, looks promising:
```ruby
User.where(created_at: 2.days.ago..)
#  User Load (0.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`created_at` >= '2019-05-18 11:21:53.274976' LIMIT 11
```

However, shouldn't it be reversible, if i want to have records where created at is equal and smaller than date?
```ruby
User.where(created_at: ..2.days.ago)
# SyntaxError ((irb):7: syntax error, unexpected ..)
# ...ass; User.where(created_at: (..2.days.ago) )
# ...                            ^~
```

**Comment by sikachu** [comment]
Thank you for your report! This “startless” range is currently not working properly because Ruby has not released a stable version with a “startless” range yet. You can see by the fact that you are getting a syntax error from Ruby parser itself. 

I just checked today, and it looks like it was recently merged into Ruby trunk as experimental: https://bugs.ruby-lang.org/issues/14799

Once those concerns on that Ruby bug tracker has been resolved, we would definitely welcome a patch to make sure that we are compatible with ”startless” range. 

I am going to close this issue for now. Thank you for your report.
