### ISSUE TITLE
500 on ActionTemplate "no implicit conversion of nil into Array" when error near bottom of file

### ISSUE THREAD

**Issue by Dkendal** [rails/rails#36341]
### Steps to reproduce
 edit an arbitrary template add `<%= render 'my_fake_template %>` to the end of the file. Create a web request that renders that template.

You get a massive exception for:

```
*** Exception TypeError: no implicit conversion of nil into Array
  $bundle/ruby/XXX/bundler/gems/rails-XXX/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:151:in `concat'
  $bundle/ruby/XXX/bundler/gems/rails-XXX/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:151:in `block in log_error'
### Expected behavior
```

Error for the missing template should be reported.

E.g.

```
ActionView::MissingTemplate in App#MyController#show
Showing path/to/my/missing/template.html.erb where line #206 raised:

Missing partial /my/controller/my/template/_my_fake_template, some_part_of_my_view_path/_my_fake_template, application/_sup with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :whatever]}. Searched in:
  * "/$pwd/my/app/domain/app/views"
```

### Actual behavior

Errors from templates have an incorrect line number by a margin of +43 lines.
A middleware tries to log the error by calling annotated source code, which calls what you see below. When source_extract is called the range is out of bounds of the source code (string array) and returns nil which is then concatenated to message (string array), causing the cited error.

```ruby
# ActionDispatch#DebugExceptions
def log_error(request, wrapper)
    ...
    message.concat(exception.annotated_source_code) if exception.respond_to?(:annotated_source_code)
    ...
end
# ActionView::Template::Error#annotated_source_code
# ActionView::Template::Error#source_extract
def source_extract(indentation = 0, output = :console)
  ...
  return unless source_code = source_code[start_on_line..end_on_line]
  ...
end
```

Which returns a 500.

### System configuration
**Rails version**: 6.0.0-rc1

**Ruby version**: 2.5.0

**Comment by vishaltelangre** [comment]
I am not able to reproduce this behavior with Rails v6.0.0.rc1 as well as on the latest master.

I get the expected error [screenshot].

![image](https://user-images.githubusercontent.com/876195/58365474-96d8a580-7ee2-11e9-8e71-3c59d2f541a2.png)

**Comment by rafaelfranca** [comment]
@vishaltelangre you need to not close the string in the name of the template:

```
<%= render 'my_fake_template %>
```

**Comment by kaspth** [comment]
Checked the surrounding source code for `source_extract` and `annotated_source_code` they've been in there for years!

However, this is new https://github.com/rails/rails/pull/35308

**Comment by Dkendal** [comment]
Looks like my original report has a typo, I did indent to close the string in my example. It should be:

```
<%= render 'my_fake_template' %>
```

I think I've narrowed this down to multi line ruby templates being the culprit:

In the below example the line number for the error: "missing partial ..." should be attributed correctly to line 1.

```erb
     1	<%= render 'missing_template' %>
     2	<%=
     3		my_helper(
     4			:a,
     5			:b,
     6			:c,
     7			d: {
     8				e: :e,
     9				f: :f,
    10			}
    11		)
    12	%>
    13	
```

However, when the `render` call appears after the multi-line template the error's line number is equal to it's *real* line number plus the length of the range of the multi-line template.

    n_reported = n_real + (n_templateEnd - n_templateStart)

In the below example, the multi-line template spans 11 lines, and the error should occur on line 12; therefore the reported line number of the error will be line 22.

    n_reported = 11 - 1 + 12 = 22

```ruby
     1	<%=
     2		my_helper(
     3			:a,
     4			:b,
     5			:c,
     6			d: {
     7				e: :e,
     8				f: :f,
     9			}
    10		)
    11	%>
    12	<%= render 'missing_template' %>
```

**Comment by itsWill** [comment]
I had a 👀 into this and found a deeper issue going on here. 

When we find a syntax error in the template, such as a missing `'` in `<%= render 'missing_template' %>`, we wrap the `SyntaxError` into a `SyntaxErrorInTemplate` exception and raise that one: 

https://github.com/rails/rails/blob/aae270de9e0862f31b14642908472d235a17936f/actionview/lib/action_view/template.rb#L341-L345

The issue here is that the `SyntaxErrorInTemplate` constant hasn't gotten required yet. So this line ends up raising a `NameError: unitialized constant ActionView::Template::SyntaxErrorInTemplate` in actuality. 

Later on within the debug exceptions middleware we catch this exception and go to render it, at the point of logging the exception as @Dkendal pointed out the `annotated_source_code` method returns `nil` which causes the type error: `TypeError: no implicit conversion of nil into Array` to be raised. 

What the developer ends up seeing is this page on the first request: 
<details> 
  <summary> Something Went Wrong Page </summary>
<img width="755" alt="Screen Shot 2019-06-19 at 1 53 12 PM" src="https://user-images.githubusercontent.com/6386302/59789205-7e6a6980-929b-11e9-9651-b9562203257e.png">
</details>

Later on the `SyntaxErrorInTemplate` is required by this check that occurs after the attempt to render: 
https://github.com/rails/rails/blob/aae270de9e0862f31b14642908472d235a17936f/actionview/lib/action_view/template.rb#L349-L350

So on the second request the we see the desired exception page: 
<details>
  <summary> Exception View </summary>
<img width="1335" alt="Screen Shot 2019-06-19 at 1 52 51 PM" src="https://user-images.githubusercontent.com/6386302/59789345-bd98ba80-929b-11e9-847a-b3949b690302.png">
</details>

The reason the `annotated_source_code` method returns nil is because when its extracting the source code it will look for the occurrence of the template file name in the backtrace: 
https://github.com/rails/rails/blob/aae270de9e0862f31b14642908472d235a17936f/actionview/lib/action_view/template/error.rb#L107-L108

However in this case the exception was a `NameError` that happened before the evaluation of the template and so the template file name won't be in the backtrace and thus the method returns nil. 

The fix for this is implemented in this PR: https://github.com/rails/rails/pull/36521,  this will resolve the issue of the `TypeError: no implicit conversion of nil into array`. 

It won't however resolve the issue of line numbers however, but that is a separate issue.

**Comment by kaspth** [comment]
@itsWill great job!

I'll move this to the 6.0.x milestone, since I don't think some line numbers being off in dev should be a release blocker. But Please Do Investigate and any PRs are welcome!
