### ISSUE TITLE
Rails 6 zeitwerk autoload problem with gem

### ISSUE THREAD

**Issue by ShakeJ** [rails/rails#36381]
### Steps to reproduce

I did ugrade rails 5.2 to 6.0. and zeitwerk autoload and use it. 
but some case is failed related gem. 
(I know config.load_defaults 6.0 and config.autoloader = :classic, but I wanna use zeitwerk gem :) ) 

1. Gem is not support zeitwerk autoload. 
(maybe I think almost gem is not support zitwerk autoload now)

My application use knock gem. 
and run in terminal 
$ bin/rails zeitwerk:check

like this, 

![image](https://user-images.githubusercontent.com/4054312/58769003-da679980-85dd-11e9-9d65-0d5047fe262b.png)

2. Override issue 

Zeitwork load class when const is use. 
Follow this codes, 

UserTokenController.rb

```
class UserTokenController < Knock::AuthTokenController
  private

  def auth_params
    params.permit(:login, :password, :login_token)
  end
end
```

and run, 
I expect run auth_params in userTokenController method (not auth_params in Knock::AuthTokenController), 
but this is failed.

![스크린샷 2019-06-03 오전 9 09 49](https://user-images.githubusercontent.com/4054312/58769173-60381480-85df-11e9-8947-696da84cbc8d.png)

See the zeitwerk logs, autloader order is 

Zeitwerk@rails.main: autoload set for UserTokenController, to be loaded from /user_token_controller.rb

Zeitwerk@rails.main: constant Knock::ApplicationController loaded from file /Users/ray/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/knock-2.1.1/app/controllers/knock/application_controller.rb

Zeitwerk@rails.main: constant Knock::AuthTokenController loaded from file /Users/ray/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/knock-2.1.1/app/controllers/knock/auth_token_controller.rb

Maybe, authTokenController is last called, and method in userTokenController can't override. 

I think As a solution to the problem, all gem is load first time at once, and later application controllers load. (becuase gem is not changed in run time)

How about that? and if that correct, how to first load gem before load application controllers?
Thanks

### Expected behavior

Call 'auth_params' in UserTokenController

### Actual behavior

Call 'auth_params' in Knock::AuthTokenController

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.0

I creating a test project, and will share it when it is complete.
cc @fxn

**Comment by fxn** [comment]
ACK! Waiting for that test project.

**Comment by ShakeJ** [comment]
So sorry for late. 
This is example project 
https://github.com/ShakeJ/rails6-autoloader-test
migrate and run, request post method "http://localhost:3000/auth/login" and show error logs.

I'm sorry to be late :)

**Comment by fxn** [comment]
The problem here is that the gem is adding all subdirectories of `lib` to the autoload paths via [this code](https://github.com/nsarno/knock/blob/66b60437a5acc28e4863f011ab59324dc1b5d0ae/lib/knock/engine.rb#L3), and this is hitting an edgy difference between `classic` and `zeitwerk` modes, which is that in `zeitwerk` mode nested autoload directories take precedence over ancestors.

In this case, for example, `lib/knock` is in the autoload paths and it is not considered to be a namespace. That is the same principle from wich `Concerns` cannot be a namespace in `app/models/concerns` ([docs in upgrading guide](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#concerns)).

It would be healthier that the Knock gem uses `require` for files in `lib`, or at least that it is more precise about which directories wants to add to the autoload paths.

In your application, you could eager load the part of the project that does not follow conventions:

```ruby
# config/initializers/eager_load_knock.rb
require "knock/version"
require "knock/authenticable"
```

I believe that would be enough to be able to use the gem in its current version with `zeitwerk` mode.

**Comment by ShakeJ** [comment]
@fxn I understood. Thank you so much 😃
