### ISSUE TITLE
Inconsistent behavior on db:prepare task

### ISSUE THREAD

**Issue by morgoth** [rails/rails#36383]
The `db:prepare` task works different for PG adapter than `SQLite3` one.

`db:prepare` task introduced in https://github.com/rails/rails/pull/35768 in case of missing database is supposed to create it, load schema and seeds.

This is working fine on PostgreSQL database, however when using SQLite3 database, seeds are not loaded.
This is happening, because `db:migrate` does not raise `ActiveRecord::NoDatabaseError` which `db:prepare` relies on https://github.com/rails/rails/blob/eece0bf1087dc2cb59605a5a9beb88c6b935c194/activerecord/lib/active_record/railties/databases.rake#L272

Not sure what the proper fix would be. Raising `ActiveRecord::NoDatabaseError` on SQLite3 would be backward incompatible change, so maybe we should add some internal method for existence check of db, that could be used instead of relying on raising error?
/cc @robertomiranda

**Comment by robertomiranda** [comment]
@morgoth thanks for raising up this issue, I've been thinking about this and probably a `db_exists?` method on the different adapters will work better.

**Comment by itsWill** [comment]
The source of this issue is the same as the one for this one: https://github.com/rails/rails/issues/32914

The fact that `Sqlite` will silently create a new database instead of throwing an error upon connecting to a non existing database. 

For what its worth, on my approach to solve the above issue I used the `db_exists?` method @robertomiranda mentioned above: https://github.com/rails/rails/pull/36025 and I think it worked quite well.

**Comment by morgoth** [comment]
it's still an issue being worked on https://github.com/rails/rails/pull/36620 but got a little stale there ;)
