### ISSUE TITLE
ActiveRecord::Calculations#count does not work when using custom `select`s

### ISSUE THREAD

**Issue by Qqwy** [rails/rails#36402]
### Steps to reproduce

1. Have any ActiveRecord model which lives in a Postgres database. (Although the same issue will probably appear when using other SQL databases)
2. Run a statement like the following in e.g. `rails console`: 

```ruby
YourModel.all.select("*", "42 answer").count
```

### Expected behavior

I would expect a reasonable output for `count`.

### Actual behavior

ActiveRecord constructs and attempts to execute an invalid query, along the lines of:

```sql
 SELECT COUNT(*, 42 answer) FROM "your_models"
```

### System configuration
**Rails version**:
5.2.3

**Ruby version**:
2.4.2

### Known mitigation

I know it is possible to 'fix' this by e.g. refining or monkeypatching [ActiveRecord::Calculations#select_for_count](https://github.com/rails/rails/blob/70d64169ae03eff911028be80b7f00bbb5784a67/activerecord/lib/active_record/relation/calculations.rb#L402) as follows:

```ruby

      # Overrides 'select_for_count' that does not play nicely with complicated SELECT queries.
      def select_for_count
        :all
      end

```

however, this seems like a bit of a 'hack': `select_for_count` is probably written the way it is for a particular reason (that is not clear to me; there is no documentation and no comments explaining what its assumptions, invariants or inner workings are).

**Comment by KapilSachdev** [comment]
Duplicate of #27676 _COUNT with multiple columns is invalid SQL_

The invalid query is the expected behaviour here as count works on select if available otherwise chooses `:all`.

You may use `count(:all)` instead of `count` as a plausible solution.

`YourModel.all.select("*", "42 answer").count(:all)` will give you a reasonable output

**Comment by Qqwy** [comment]
Thank you for your response. It was hard to find this in the documentation, but it is there.

So I cannot conclude otherwise than that you are correct. 
It is slightly unfortunate that the burden of this comes to lie on the shoulders of the person who attempts to count the records, since (a) the normal way of doing it suddenly does not work and (b) the error thrown in this case is not at all helpful, and makes them believe that the query itself is problematic.
I do not know how this could be resolved with the current API of ActiveRecord.Calculations

Thank you for your time :slightly_smiling_face: !

**Comment by KapilSachdev** [comment]
If you think otherwise, this is the normal way of counting the records in rails as per the current implementation (maybe not according to us but it is, as count does not handle all cases of select and yes it has to be solved by the person using the API).
Also about the helpfulness of the error thrown, the error thrown would likely be of SQL, which might give us a hint (as it executes a wrong `count `query) that one of the API (here `count`) misbehaved.

If you think your query is resolved, you may choose to close the issue.
