### ISSUE TITLE
Select with Virtual Attribute ( "as" ) not Working and add "count" unnecesary

### ISSUE THREAD

**Issue by JonnyGalassi** [rails/rails#36476]
### Steps to reproduce
When I create this in controller:

Terminales.select("id, estacion as nombre_estacion")
the result is:

PG::SyntaxError: ERROR:  error de sintaxis en o cerca de «as»
LINE 1: SELECT COUNT(id, estacion as nombre_estacion) FROM...
                                          ^
: SELECT COUNT(id, estacion as nombre_estacion) FROM "terminales"

### System configuration
**Rails version**:
 Rails 5.2.3

**Ruby version**:
ruby 2.5.1p57

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by KapilSachdev** [comment]
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class BugTest < Minitest::Test
  def test_count_with_alias
    Post.create!

    assert_equal 1, Post.select('id as P_KEY').count
  end

  def test_count_with_select
    Post.delete_all
    Post.create!

    assert_equal 1, Post.select(:id).count
  end
end

```

**Comment by azbshiri** [comment]
@KapilSachdev If you don't mind I take care of this.

**Comment by KapilSachdev** [comment]
Sure, if you think this is a plausible rails bug.

However i don't think this issue is a rails bug as _not all valid `Relation#select` expressions are valid `count` expressions._ (https://github.com/rails/rails/issues/27676#issuecomment-272992359)

Referencing #27676 and #36402 as i think they have a similarity with respect to how count behaves currently.

The author may choose to use `count(:id)` or `count(:all)`.

**Comment by azbshiri** [comment]
Yes, because in `execute_simple_calculation` we're not extracting alias columns and it's been treated it like an array but after `aggergate_column` alias attribute is `nil` which I think it can be implemented to extract aliases? anyway I'm mean this line:
https://github.com/rails/rails/blob/b6068e6c42a070843b0a3844dc72c2a98ec3c6eb/activerecord/lib/active_record/relation/calculations.rb#L284

**Comment by KapilSachdev** [comment]
_... it can be implemented to extract aliases?_, I think its not about whether we **can** solve this (we definitely can), but more like **should** we support it or not?

Also if we choose to support this, I think then we can also choose to support #27676 and #36402, which though is not closely related but has close resemblance.
