### ISSUE TITLE
Empty array interpolation issue

### ISSUE THREAD

**Issue by anuragverma65** [rails/rails#36509]
This works as expected

`User.where('id not in (?)', %w[1 2 3])`

But if we pass an empty array, for example:

`User.where('id not in (?)', [])`

the generated query is: 

`SELECT users.* FROM users WHERE (id in (NULL))`

Ideally the empty array should should interpolate as an empty string rather than `NULL`. It should be equal to: 
`User.where.not(id: [])`

**Comment by lxxxvi** [comment]
Hello @anuragverma65

`User.where.not(id: [])` creates this query:

```sql
SELECT "users".* FROM "users" WHERE 1=1
```

which returns **all rows** from that table.


`User.where.not('id IN (?)', [])` creates that query:


```sql
SELECT "users".* FROM "users" WHERE NOT (id IN (NULL))
```

which returns **no rows**, because `IN (NULL)` is *not* treated as `IS NULL` in IN filters (at least not in Postgres).

I found [this post on Stack Overflow](https://stackoverflow.com/questions/17877100/postgres-not-in-null-gives-no-result) that covers this question.

In my opinion `User.where.not(id: [])` should *rather not* do `1=1`, but there might be reasons for that behavior...

---

Then you said this

> Ideally the empty array should should interpolate as an empty string rather than `NULL`

I think this would lead to conflicts. 2 reasons:

Reason 1: Data type may not be compatible

Translating `id: []` into `id IN ('')` leads to an error if the column is an Integer:

```sql
-- SELECT count(*) FROM users WHERE id IN ('');
ERROR:  invalid input syntax for integer: ""
LINE 1: SELECT count(*) FROM users WHERE id IN ('');
```

(again, this is Postgres)

Reason 2: `NULL` is not the same as empty string

There might be rows with empty string values. If `NULL` translates to empty string, these records would be fetched, I think this behavior is not wanted either.
