### ISSUE TITLE
Actioncable imports itself incorrectly, causing failures when SSR in react-rails

### ISSUE THREAD

**Issue by BookOfGreg** [rails/rails#36601]
### Steps to reproduce
https://github.com/reactjs/react-rails/issues/968
Clone down https://github.com/BookOfGreg/react-rails-example-app
rails s
visit http://localhost:3000/welcome/index to prove app works
yarn add actioncable
add `var ActionCable = require('actioncable')` to line 3 of `app/javascript/components/Post.js`

### Expected behavior

Absolutely no difference as nothing should happen during `import` or `require` in JS

### Actual behavior

ActionCable's JS crashes the SSR with
```
ActionView::Template::Error (Encountered error "#<ExecJS::ProgramError: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.>" when prerendering Post with {"title":"A working react component","body":"Simple but effective"}
invariant ((execjs):26128:15)
ReactDOMServerRenderer.render ((execjs):29517:7)
ReactDOMServerRenderer.read ((execjs):29235:29)
Object.renderToString ((execjs):29720:27)
Object.serverRender ((execjs):3406:42)
eval (eval at <anonymous> ((execjs):30053:8), <anonymous>:6:45)
eval (eval at <anonymous> ((execjs):30053:8), <anonymous>:18:13)
(execjs):30053:8
(execjs):30059:14
global ((execjs):1:102)
```

### System configuration
**Rails version**: Tested on 5+

**Ruby version**: Any

**Comment by bragovo** [comment]
Thanks, Greg. Usually SSR not working if there is `window` or `document` exists somewhere in code. This line can be a problem https://github.com/rails/rails/blob/master/actioncable/app/javascript/action_cable/index.js#L27

I remove `actioncable` and write ws without it and it's working fine:
```
  componentDidMount () {
    this.ws = new WebSocket(`${this.props.ssl ? 'wss' : 'ws'}://${this.props.host}/cable`)

    this.ws.onopen = () => {
      this.ws.send(JSON.stringify({ command: 'subscribe', identifier:  JSON.stringify({ channel: 'AppChannel' })}))
    }

    this.ws.onmessage = (event) => {
      const data = JSON.parse(event.data)

      if (data.identifier) {
        const { channel } = JSON.parse(data.identifier)

        if (channel == 'AppChannel' && data.message && !data.type) {
          const { user, jwt_token } = data.message

          this.setState({ user, jwt_token })
        }
      }
    }
  }
```

**Comment by BookOfGreg** [comment]
Yep you found the problem.
Line 22 accesses client-only globals in the export statement.
https://github.com/rails/rails/blob/master/actioncable/app/javascript/action_cable/index.js#L22
Can this function be re-written to check if window/document exists before access, or can it not run the function on import and run as more like a caching instance var?

**Comment by rmacklin** [comment]
Hi there,

A few things to note:
- You are both linking to the actioncable frontend source code on the `master` branch, which is _not_ what you'll get when you `yarn add actioncable`. The `master` branch is for Rails 6+ and the `actioncable` package points to the last Rails 5.2 release (currently 5.2.3): https://www.npmjs.com/package/actioncable
  - In Rails 6, the frontend packages have been moved into the `@rails` namespace, so the source code you were looking at is what you'll get when you install `@rails/actioncable` version `6.0.0-rc1`. That said, Rails doesn't support using a different version of the ActionCable frontend and backend, so since that project is using rails `5.1.6`, it should use the `actioncable` npm package at version `5.1.6` (or upgrade rails and then install the matching version of the npm package).
  -  The source code for the actioncable frontend as of `v5.1.6` can be viewed here:  https://github.com/rails/rails/blob/v5.1.6/actioncable/app/assets/javascripts/action_cable.coffee.erb

- Rails doesn't formally support the use of the actioncable javascript package in non-browser environments, per https://github.com/rails/rails/issues/25649#issuecomment-231539885 and https://github.com/rails/rails/issues/25649#issuecomment-354894588
  - You can fix the crash in your example by adding `window = {};` just prior to `var ActionCable = require('actioncable')` - however, you may want to instead avoid importing ActionCable during server-side rendering, like:
    ```js
    if (typeof window !== "undefined") {
      var ActionCable = require('actioncable');
    }
    ```

**Comment by bragovo** [comment]
Thank you, @rmacklin, maybe you right. I prefer when `window` and `document` checking in packages rather in applications, but I don't know it that right way or not.

**Comment by BookOfGreg** [comment]
Thank you for the comments regarding correct adding of ActionCable via yarn.

I understand why this package does not support serverside use as obviously ActionCable can't be used serverside, however it's a different thing to support no-op serverside which most NPM packages do.
Therefore respectfully I do disagree with using that as a fix as not many other packages designed for clientside only use actually access `window` on the `require` statement.

Can you explain why Window is accessed during `require`?

I suspect this issue may sit for a while so @bragovo I may put a utility into react-rails to make ActionCable require correctly. Do you think that would help or add confusion?

**Comment by sebmor** [comment]
I have the same windows is not defined error when SSR within a Vue Nuxt app.
Would be nice if this package checks for windows instead of erroring out.

![Screenshot 2019-07-20 at 01 51 48](https://user-images.githubusercontent.com/405407/61571030-0b6a3380-aa91-11e9-94b7-d8c40737d543.png)
