### ISSUE TITLE
Bug in first_or_create/first_or_initialize block

### ISSUE THREAD

**Issue by usama520** [rails/rails#36625]
### Steps to reproduce
We have a model named User

```
puts User.count # => 50
User.where(email: 'new@email.com').first_or_initialize do |user|
  # other stuff
  puts User.count # => 0
end

User.where(email: 'new@email.com').first_or_create do |user|
  # other stuff
  puts User.count # => 0
end
```

### Expected behavior
User.count in the first_or_create and first_or_initialize block should return 50

### Actual behavior
User.count in the first_or_create and first_or_initialize block returns 0

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.2p47

**Comment by louim** [comment]
This is the expected behaviour, since under the hood it just does:
https://github.com/rails/rails/blob/b9ca94caea2ca6a6cc09abaffaad67b447134079/activerecord/lib/active_record/relation.rb#L103-L113
We can see it invoke `create` or `new`. [The doc of `create` says](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-create):
> Tries to create a new record with the same scoped attributes defined in the relation. Returns the initialized object if validation fails.

When you call `User.count` inside the block, it applies the same scope you used, meaning it does `User.where(email: 'new@email.com').count` which in turn return 0 because the user still hasn't been created.

**Comment by usama520** [comment]
Actually you're right. When I run the command, the query that is generated is:
```SELECT COUNT(*) FROM "users" WHERE "users"."email" = ?```
I'm going to close this but I'm wondering if there a way around this?

**Comment by louim** [comment]
I would try to move the count outside the block. If you _really_ need to have the count inside, you could do `User.unscoped.count` but be aware that it will remove all potential scopes (including `default_scope`).
