### ISSUE TITLE
Introduce ActiveML and ActionClassifier for Rails 7

### ISSUE THREAD

**Issue by LemonAndroid** [rails/rails#36808]
## ActiveML

This would provide the abstraction over Tensorflow.

Most probably only using pre-trained models for now.

## ActionClassifier

Building upon `ActiveML`, ActionClassifiers can be used in models directly.

I'm thinking like

```ruby
## in model class body

classifies :image, [:nudity]
```

By default this would classify the image upon uploading via a pretrained model detecting nudity and make a boolean available on the model.

Keep in mind, this is a spontaneous idea that I had just now.

Feedback appreciated.

**Comment by dvisockas** [comment]
Interesting idea. However, since ruby lacks DL/ML frameworks, how would you go about installing dependencies? Already there are yarn and ruby gems to juggle, adding pip/conda would add even more complexity. 

Also, since this would be an abstraction, maybe it could be executed in a manner similar to ActiveJob so you could switch between Tensorflow/Pytorch/Scikitlearn and whatever you choose?

**Comment by matthewd** [comment]
Thanks, but we reserve the issue tracker for tracking issues in existing code. Feature requests and similar discussions are better addressed on the rails-core mailing list.

**Comment by LemonAndroid** [comment]
@matthewd @dhh This is a good way to hurt contribution. I'm very little inclined to contribute further in any other way now. You know there is tags / projects, basically almost a pm suite, available on GitHub?

@dhh 

Basically you want to capture contribution where it happens, jiu-jitsu style. Not stop it and refer to the old carriage that doesn't seem to bring the innovation power needed anymore.

**Comment by simi** [comment]
@LemonAndroid if you would like to contribute, it will be great start to go thru https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html and follow what's written in there (mainly https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark).

**Comment by LemonAndroid** [comment]
@simi I wanted to contribute. These reactions are very to my disliking. 

But i'm seeing you all can act like cute little robots, this is very fun to observe.

**Comment by dgm** [comment]
@LemonAndroid Do you go into a gym and immediately tell them how to arrange their equipment, or how to run their membership?   Do you walk into a grocery store and immediately talk to the manager about how to arrange the food on the shelves before you even bothered to look?    Do you go to your car mechanic and tell him how the manufacturer should add a new feature?    

It's an interesting idea.  Run it through the correct  channels so the right people can see it in the right context where action can be taken, instead of clogging the wrong channel.   

`classifies :post, [:offtopic]`

Welcome to the community!  Please take a few moments to discover the existing information flows that have been in use for a while.  

(Arrived here via your "sarcastic" tweet)

**Comment by LemonAndroid** [comment]
@dgm thanks, very thoughtful response
