### ISSUE TITLE
Mysql2::Error: No database selected - Multi-database on RC2

### ISSUE THREAD

**Issue by ScottRobbins** [rails/rails#36894]
With multiple databases set up, if a model uses connects_to, when trying to use that model it seems to not be able to find the database.

### Steps to reproduce
I created an example app that shows this issue https://github.com/ScottRobbins/RailsMultipleDatabaseIssue 

You will need to set up the necessary credentials for your local database. 

First, you can go to the commit before "Update to RC2" and run the song test like `bundle exec rails test test/models/song_test.rb`, and it should work correctly. 

Then, go to HEAD, which is now RC2 and run the same test, you will see an error: 
```
Error:
SongTest#test_the_truth:
ActiveRecord::StatementInvalid: Mysql2::Error: No database selected
```

You will notice that creating the database and running migrations is fine, it's just when trying to actually use the active-record model that the error arises.

### Expected behavior
`bundle exec rails test test/models/song_test.rb` should succeed

### Actual behavior
`bundle exec rails test test/models/song_test.rb` fails with the error above

### System configuration
**Rails version**: 6.0.0.rc2

**Ruby version**: 2.6.3

**MySQL version**: 5.6 & 5.7

**Comment by eileencodes** [comment]
Thanks for providing the reproduction script. I was able to reproduce but after digging in I believe that this is an issue with your YAML.

Basically since you named your defaults `primary` and `secondary` Rails is getting confused that you also have a database namespace with the same names. I suggest you make this change:

```diff
-primary: &primary
+default: &default
   adapter: mysql2
   encoding: utf8mb4
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   host: localhost
-  username: sscce
+  username: root
   password: 
   socket: /tmp/mysql.sock
 
-secondary: &secondary
+other_default: &other_default
   adapter: mysql2
   encoding: utf8mb4
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   host: localhost
  username: sscce
   password:
   socket: /tmp/mysql.sock
   migrations_paths: db/secondary_migrate
 
 development:
   primary:
-    <<: *primary
+    <<: *default
     database: development_primary
   secondary:
-    <<: *secondary
+    <<: *other_default
     database: development_secondary
 
 # Warning: The database defined as "test" will be erased and
@@ -37,8 +37,8 @@ development:
 # Do not set this db to the same as development or production.
 test:
   primary:
-    <<: *primary
+    <<: *default
     database: test_primary
   secondary:
-    <<: *secondary
+    <<: *other_default
     database: test_secondary
```

If I do the above the error is fixed.

There's also one other issue with your setup that's not going to break something but may have weird side effects.

If you don't have a replica you shouldn't connect the reading database. I also recommend using ApplicationRecord as your primary base instead of making a new one. Otherwise you'll end up with duplicate connections for the "default" connection (which is primary).

I'm going to send a PR to your app that demonstrates the changes I suggest because I think it's easier shown than explained. 

Thanks for opening this issue and using Rails 🌟

**Comment by eileencodes** [comment]
BTW I'm not saying we _can't_ fix this in Rails, just letting you know how to get past it. I'm on vacation next week so I'm not sure when exactly this will get fixed.

**Comment by ScottRobbins** [comment]
I would have never considered that to cause an issue. Thank you for quickly looking into this and going out of your way to show exactly how to change the code, as well as the bonus tips! I have integrated those into my real project and it seems to be working on RC2.

Thanks for continuing to push rails forward and being responsive @eileencodes

**Comment by ScottRobbins** [comment]
> I also recommend using ApplicationRecord as your primary base instead of making a new one.

In your `active_record_multiple_databases.md` document I see this pattern used as well. Out of curiosity, is the general rule that the subclass's `connects_to` call will win? Curious how rails keeps track of that.

**Comment by tgxworld** [comment]
@eileencodes I have a draft PR to fix this in https://github.com/rails/rails/pull/39791 but I just wanted to quickly run through the solution with you before working out the test cases. The general idea here is that we should prioritize `db_config` that are in the current env when looping through all the configurations.
