### ISSUE TITLE
Wrong route when resource and resources are both present

### ISSUE THREAD

**Issue by collimarco** [rails/rails#36909]
### Steps to reproduce

```
# routes.rb
resource :profile, only: [:edit, :update]
resources :profiles, only: :show
```

### Expected behavior
`profile_path(@profile)` (or `redirect_to @profile`) should generate `/profiles/1`, since the only route matched is the second.

### Actual behavior
`profile_path(@profile)` (or `redirect_to @profile`) generate an incorrect path `/profile.1`

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

### Workaround
It seems that inverting the two lines in `routes.rb` fixes the problem for `profile_path`, but it is just a workaround, not a solution for the bug. Also I fear that I may face similar issues when I add more methods.

**Comment by alfie-max** [comment]
@collimarco i wouldn't say that's a bug. When you add the `resource` line it adds a set of routes.. with specific path prefix

```
      Prefix Verb  URI Pattern             Controller#Action
edit_profile GET   /profile/edit(.:format) profiles#edit
     profile PATCH /profile(.:format)      profiles#update
             PUT   /profile(.:format)      profiles#update
```

As you can see the prefix `profile` is used for the update actions

because of that rails doesn't use the same prefix for the next set of routes it creates with `resources` as that would cause a conflict. 

Inverting the lines seems to be a fix because of how rails prioritises the routes based on the order they are written in your routes.rb

**Comment by collimarco** [comment]
Thanks for the explanation! However this behavior is not what you expect... When the Verb is `GET` there should be another route. 
I think that the problem here is that Rails doesn't consider the Verb when it generates the path. If it considered the Verb, then Rails could generate the correct path.

**Comment by ollietreend** [comment]
I'm experiencing the same behaviour in Rails 6.0.3.3

@collimarco did you ever find a solution for this, or did you just keep the workaround of reordering the lines in `routes.rb`?
