### ISSUE TITLE
DateTime.parse should work with AEST but its not working 

### ISSUE THREAD

**Issue by NomiJ** [rails/rails#36972]
### Steps to reproduce
2.3.1 :014 > d=DateTime.parse('2019-08-13 16:14:34.97300 AEST')
 => Tue, 13 Aug 2019 16:14:34 +0000 
2.3.1 :016 > d=DateTime.parse('2019-08-13 16:14:34.97300 GMT+10')
 => Tue, 13 Aug 2019 16:14:34 +1000 
2.3.1 :001 > d=DateTime.parse('2019-08-13 16:14:34.97300 EST')
 => Tue, 13 Aug 2019 16:14:34 -0500 

### Expected behavior
DateTime.parse should support AEST time zone
d=DateTime.parse('2019-08-13 16:14:34.97300 AEST')
 => Tue, 13 Aug 2019 16:14:34 +1000 
### Actual behavior
DateTime.parse is not supporting AEST time zone 
 => Tue, 13 Aug 2019 16:14:34 +0000 

### System configuration
**Rails version**: Rails 5.0.1

**Ruby version**:ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin18]

**Comment by PericlesTheo** [comment]
Let me prefix this by saying I might be completely wrong 😅 

This is not necessarily an issue with Rails but Ruby. The available options for the timezones can be found in the [zonetab.h](https://github.com/ruby/ruby/blob/c5eb24349a4535948514fe765c3ddb0628d81004/ext/date/zonetab.list)

In there, you cannot see _AEST_. However, according to [this](http://ds.iris.edu/seismon/html/utc.html), it is also abbreviated as _EAST_ which _is_ defined [here](https://github.com/ruby/ruby/blob/c5eb24349a4535948514fe765c3ddb0628d81004/ext/date/zonetab.list#L101)
```ruby
d = DateTime.parse('2019-08-13 16:14:34.97300 EAST')
# => Tue, 13 Aug 2019 16:14:34 +1000
```

Hope that helps..?

**Comment by matt17r** [comment]
Sounds like this issue needs to be moved to the Ruby issues tracker but _EAST_ instead of _AEST_ is very surprising to me...

1. the [linked source](http://ds.iris.edu/seismon/html/utc.html) that references _EAST_ links to a [more comprehensive source](http://www.timeanddate.com/library/abbreviations/timezones/) that uses _AEST_ (or _AEDT_ for DST)
2. the most recent data from [IANA](https://data.iana.org/time-zones/releases/?C=M;O=D) ([2019c at time of writing](https://data.iana.org/time-zones/releases/tzdata2019c.tar.gz)) refers to the timezones as _AEST_ (or _AEDT_ for DST)
3. the [Australian government](https://www.australia.gov.au/about-australia/facts-and-figures/time-zones-and-daylight-saving) uses _AEST_ (or _AEDT_ for DST)

There [are](https://www.worldtimeserver.com/time-zones/east/) [also](https://24timezones.com/time-zone/east) [several](https://time.is/EAST) [sources](https://www.timeanddate.com/time/zones/east) that use _EAST_ for Easter Island, off the coast of Chile (-6 rather than +10).

**Comment by matt17r** [comment]
I have [logged this as an issue in the Ruby project](https://bugs.ruby-lang.org/issues/16286).

Are you happy to close this @NomiJ and follow it over there?

**Comment by NomiJ** [comment]
Thanks
