### ISSUE TITLE
Improper PK guard in `through` reflections

### ISSUE THREAD

**Issue by ekampp** [rails/rails#36984]
### Steps to reproduce

Clone [this demo app](https://github.com/ekampp/pk_cast_demo). And run `bundle exec rspec` to see the failing test. 

Specifically see the [account.rb](https://github.com/ekampp/pk_cast_demo/blob/master/app/models/account.rb), [project.rb](https://github.com/ekampp/pk_cast_demo/blob/master/app/models/project.rb), and [structure.rb](https://github.com/ekampp/pk_cast_demo/blob/master/app/models/structure.rb) files. Structure `has_one :account, through: :project`, which fails even though all the reflections seems to be there throughout the model chain.

This is a regression from the previously functioning 6.0.0.rc2

### Expected behavior

UUID PKs should not raise NotImplemented errors when using the `through` reflection.

### Actual behavior

UUID foreign keys raise NotImplemented error because of [this change](https://github.com/rails/rails/pull/36847).

### System configuration
**Rails version**: 6.1.0.alpha

**Ruby version**:  2.6.2

**Comment by ekampp** [comment]
This is also a regression against the official release of 6.0.0

**Comment by ekampp** [comment]
@gmcgibbon, is there anything I can do to help this issue along?

**Comment by gmcgibbon** [comment]
Thanks for reporting. Indeed I didn't account for `has_one`s correctly in the change you linked. I'll fix it!

In terms of type casting through, I'm still confident we only need to make integers exempt. We _could_ look at adding a `#requires_casting?` method to active record types but that doesn't seem necessary right now to me.

> This is also a regression against the official release of 6.0.0

Correct, https://github.com/rails/rails/pull/36847 wasn't backported so the issue is only on master.

> @gmcgibbon, is there anything I can do to help this issue along?

Sorry, I had a busy week last week. I'll have a patch up soon to address this (with more tests 😉).
