### ISSUE TITLE
Regression in autoloading from 6.0.0.rc2 to 6.0.0 ('const_defined?': wrong constant name)

### ISSUE THREAD

**Issue by thelucid** [rails/rails#36987]
### Steps to reproduce

```
rails new tester
cd tester/
rails g model foo/bar
mkdir -p app/foo/1-baz
touch app/foo/1-baz/file.yml
rails s -e production
```

As discussed in: https://github.com/fxn/zeitwerk/issues/72.

### Expected behavior
This runs fine on Rails 6, RC2 but fails on Rails 6 final release.

### Actual behavior
```
zeitwerk-2.1.9/lib/zeitwerk/loader.rb:705:in 'const_defined?': wrong constant name 1-baz (NameError)
```

### System configuration
**Rails version**: 6.0.0.rc2 & 6.0.0

**Ruby version**: 2.6.3p62

**Comment by fxn** [comment]
This is a known change.

In 2.1.9 eager loading is consistent with autoloading. Before 2.1.7, eager loading issued a mostly a simple recursive `require`, while autoloding uses `const_get`. This created inconsistencies in apps. For example, an application could eager load, but then not work in development.

Applications should work or err consistently regardless of lazy/eager.

This was considered to be a bug, and 2.1.7 implemented eager loading as a recursive `const_get`.

**Comment by fxn** [comment]
BTW, this could be an issue in previous pre-releases, but RC2 requires at least 2.1.8 which already had the change I explained.

If you try to follow the instructions, you'll see that application does not boot in either development or production mode.

And in previous pre-releases, I actually doubt these exact repro steps worked in production mode, because `setup` runs on both modes, `1-baz` is a subdirectory of a root directory, and its camelization (`1-baz`) is an invalid constant name.

**Comment by thelucid** [comment]
@fxn I was definitely running in production fine on rc2. Literally the only change I made to my app was the Rails version in `Gemfile` and therefore just committed `Gemfile` and `Gemfile.lock` after a `bundle`. It's not a problem for me now as I'm using the workaround you suggested, but this might be useful for others.

**Comment by fxn** [comment]
@thelucid I do not doubt it, but the repro steps are not repro steps. Try them.

**Comment by thelucid** [comment]
@fxn Very odd.
