### ISSUE TITLE
Not a directory error on Linux in development (eager_loading issue)

### ISSUE THREAD

**Issue by krismichalski** [rails/rails#37011]
I wanted to have a `README.md` file in rails `/app` directory explaining the code architecture and so on, but I found that it's causing a problem on linux machines in development. Problem does not occur on other environments that use linux or on MacOS.

I'm getting a `not a directory` error for `app/README.md` file.

### Steps to reproduce
```
rails new test_app
cd test_app
cp README.md app/
rails s
```
The same steps reproduced with rails `5.2.3` give the expected behavior.
Reverting [this line change](https://github.com/rails/rails/commit/caa3cc8868206f8109e0d633efb09d31e94ef635#diff-ea498e0b0ed49d4b32a04d0d20c589f6L126) also gives the expected behavior.

### Expected behavior
- Rails server should start

### Actual behavior
- Error: `Not a directory @ dir_initialize - [test_app root]/app/README.md (Errno::ENOTDIR)`
- Rails server not started

### System configuration
**Rails version**: `6.0.0`

**Ruby version**: `2.6.3`

**System**: `Ubuntu 18.04 / Linux Mint 19.1`

### Workaround

In `config/application.rb`:
```
    if Rails.env.development? && Listen::Adapter::Linux.usable?
      path_rejector = ->(path) { path.include?("app/README.md") }
      config.eager_load_paths = config.eager_load_paths.reject(&path_rejector)
    end
```

**Comment by fxn** [comment]
The problem here, really, is that `app/README.md` should not be in the autoload paths in the first place. Autoload paths should be directories, they represent `Object`. I suspect the code that initializes them is too permisive and not filtering out files was an overlook.

The patch that addreesed this issue processes files in `ActiveSupport::Dependencies.autoload_paths` and makes them watchable. However, you don't really want to watch `app/README.md`, don't you. Editing that file should not trigger a reload.

In Rails 7.1 the fix is going to be different. The new code iterates over `Rails.autoloaders.main.dirs`, which has only directories.
