### ISSUE TITLE
ActiveStorage `has_one_attached` not purging attachments

### ISSUE THREAD

**Issue by marclerodrigues** [rails/rails#37069]
I'm not able to purge an attachment using `has_one_attached` and the newest version of Rails.

I was working to update an open-source project from Rails 5.2 to Rails 6.0 and I encountered this issue.

I've created a dummy app with a failing test.

Basically I have a model `Bucket` with a `has_one_attached :image` attribute. I'm able to set the attachment but I'm not able to call `purge` in order to delete it.

I don't know what I'm missing here.

### Steps to reproduce

Just clone the repo:
https://github.com/marclerodrigues/active-storage-not-purging

And run the following commands:
```
bundle install
bundle exec rails db:setup
bundle exec rspec
```

### Expected behavior
Whenever I call `purge` the attachment and its associated blob should be deleted.

### Actual behavior
When I call `purge`, I'm getting a `FrozenError (can't modify frozen Hash)`.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.3

**Comment by georgeclaghorn** [comment]
1. `ActiveStorage::Blob#purge` [destroys](https://github.com/rails/rails/blob/3523b9d0096ec0229e9db336f0fb042b17c73978/activestorage/app/models/active_storage/blob.rb#L226) the blob record, freezing its attributes.

2. Then it [deletes](https://github.com/rails/rails/blob/3523b9d0096ec0229e9db336f0fb042b17c73978/activestorage/app/models/active_storage/blob.rb#L227) the stored file... but the uploaded file hasn’t been stored yet, because the `Bucket` record hasn’t been saved, so the blob doesn’t have a key.

3. `ActiveStorage::Blob#delete` [calls `#key`](https://github.com/rails/rails/blob/3523b9d0096ec0229e9db336f0fb042b17c73978/activestorage/app/models/active_storage/blob.rb#L218), which [attempts to generate a key](https://github.com/rails/rails/blob/3523b9d0096ec0229e9db336f0fb042b17c73978/activestorage/app/models/active_storage/blob.rb#L105) if the blob doesn’t have one already. Writing the generated key back to the blob’s frozen attributes raises.

`ActiveStorage::Blob#purge` should no-op for blobs that haven’t been persisted yet… but can you avoid calling it for those blobs?

**Comment by marclerodrigues** [comment]
Hey @georgeclaghorn, thanks for the explanation!

I can avoid calling it for blobs that haven't been persisted but was this supposed to happen in the first place? Testing with Rails 5.2.3, everything works just fine as you can see in this [example](https://github.com/marclerodrigues/active-storage-purging).

**Comment by K1N5L4Y3R** [comment]
@georgeclaghorn thanks for your explanation. I fixed my FrozenError that I was getting since I upgraded to Rails 6.0 by setting the attachment to nil (translated to this example, I called `image = nil` instead of `image.purge`).

**Comment by tracyloisel** [comment]
this issue is still open or ??

**Comment by chiperific** [comment]
Looking for an in-the-meantime workaround.

would code like `image.purge if image.persisted?` make sense?
or is @georgeclaghorn suggesting using `image.delete` instead of `image.purge`?

**Comment by quoyi** [comment]
> Looking for an in-the-meantime workaround.
> 
> would code like `image.purge if image.persisted?` make sense?
> or is @georgeclaghorn suggesting using `image.delete` instead of `image.purge`?

@georgeclaghorn and @K1N5L4Y3R right. I'm use rspec.
