### ISSUE TITLE
How to fix "Sending mail with DeliveryJob and Parameterized::DeliveryJob is deprecated" deprecation?

### ISSUE THREAD

**Issue by everton** [rails/rails#37068]
### Steps to reproduce

Upgrading from Rails 5 to 6 an application which has calls to `deliver_later` method.

I changed the old style of passing formal parameters to the new one using `with` and calling `params` inside the mailer; I have removed the queue parameter which I was using previously in some of the `deliver_later` calls.

All my mailers inherit from ApplicationMailer which inherits from ActionMailer::Base, there is nothing special from what I'm able to figure out.

There is nothing special I can recall in my configurations about mailers.

### Expected behavior

No warnings or an explanation about what to do, since I was not able to figure out what I'm supposed to do to fix this and be prepared to 6.1

### Actual behavior

All calls to `deliver_later` present the warning:

> Sending mail with DeliveryJob and Parameterized::DeliveryJob
> is deprecated and will be removed in Rails 6.1.
> Please use MailDeliveryJob instead.

But I'm not using directly DeliveryJob! I got the warnings in all my tests (models, controllers, integration), both from direct calls in controllers and also from inside other jobs.

### System configuration
**Rails 6.0.0**:

**Ruby 2.6.3p62**:

**Comment by louim** [comment]
Have you set the `config.load_defaults 6.0` in your `application.rb` file? See https://edgeguides.rubyonrails.org/configuring.html#with-6-0. That should set `config.action_mailer.delivery_job: "ActionMailer::MailDeliveryJob"`. Check that it is correctly set.

**Comment by everton** [comment]
Thank you @louim, this has removed all the warnings.

**Comment by fschwahn** [comment]
Just as a heads up for other people running into this while upgrading: it doesn't seem to work to uncomment the relevant line in the generated `new_framework_defaults_6_0.rb` file. My guess is that it's too late, and mailers from gems are already loaded at that point (in my case `devise`). Putting the line in `application.rb` worked though.

Might also be something peculiar about my app.

**Comment by modullar** [comment]
@louim 
That didn't remove the warnings !

**Comment by louim** [comment]
@modullar If you are using `config.load_defaults 6.0` in your `application.rb`, maybe something is overwriting the specific config. If you are relying on uncommenting the line in `new_framework_defaults_6_0.rb` try to put the line in `application.rb` instead.

The root of the problem is often that ActionMailer is loaded too early before the setting is applied. This makes ActionMailer use the deprecated class, hence the warning. One other possible cause could be a gem referencing the old class directly. Look if you have gems that send email that were not updated. Hope that helps!
