### ISSUE TITLE
New ActiveModel::Error raises FrozenError without deprecation on 6.1

### ISSUE THREAD

**Issue by cpruitt** [rails/rails#37081]
At GitHub we're seeing that the new `ActiveModel::Error` (which I think is a great improvement overall) is raising `FrozenError` in our app. In particular we see it when we call `errors[:some_attribute].clear`.

Migrating away from calling `clear` is warranted but right now the errors prevent us from testing with Rails 6.1 and a deprecation warning is probably more appropriate for 6.1 than a hard failure.

**More Info**

`ActiveModel::Error` was added to Rails 6.1 in https://github.com/rails/rails/pull/32313. Part of the change was the addition of `DeprecationHandlingMessageArray` which serves as a delegate for the `[]` method:

https://github.com/rails/rails/blob/ba38b40e83302cb9da17c95086d93e5071426668/activemodel/lib/active_model/errors.rb#L211

`DeprecationHandlingMessageArray` handles calls to `<<` with a deprecation warning, but does not handle calls to other array methods which mutate the array such as `errors[:base].clear`. In our case, we've run into issues with `.clear` so far but other array methods could conceivably be an issue as well.

Here is a reproduction script which fails under 6.1 and passed under 6.0. It's a pretty contrived example (simplified from our actual use) but I think it serves to highlight the issue. The script will use 6.1 (master) by default and 6.0 can be run by: `RAILS_6_0=1 ruby ./reproduction.rb`

```ruby
# frozen_string_literal: true

require "bundler/inline"

# Run for Rails 6.1 (master) - Failures
# ruby /Users/cpruitt/Desktop/activerecord_errors_repro.rb
#
# Run for Rails 6.0 - Passes
# RAILS_6_0=1 ruby /Users/cpruitt/Desktop/activerecord_errors_repro.rb

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  if ENV["RAILS_6_0"] == "1"
    gem "activerecord", "6.0.0"
  else
    gem "rails", github: "rails/rails"
  end
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :username
    t.datetime :suspended_at
  end
end

class User < ActiveRecord::Base
  validate :must_be_verbose

  def suspend(reason)
    # This clear fails under Rails 6.1 with
    # FrozenError: can't modify frozen Array
    errors[:base].clear

    errors.add(:base, "You need to specify a reason for the suspension.") if reason.blank?
    update_attribute(:suspended_at, Time.now)
  end

  private

    # Usernames must be really long
    def must_be_verbose
      return if username.to_s.length > 100
      errors.add(:base, "You need to be more witty with your username.")
    end
end

class BugTest < Minitest::Test
  def test_email_validation_exists_on_save
    short_username_from_before_length_validation = 'firstuser'
    user = User.new(username: short_username_from_before_length_validation)
    user.save!(validate: false)

    user.save
    user.errors[:base].any?
    assert_equal ["You need to be more witty with your username."], user.errors[:base]
  end

  def test_user_can_be_suspended_even_if_other_validation_fails
    short_username_from_before_length_validation = 'firstuser'
    user = User.new(username: short_username_from_before_length_validation)
    user.save!(validate: false)

    user.save
    user.suspend("Violated TOS")
    assert user.errors.empty?
  end

  def test_email_validation_is_cleared_on_failed_suspend
    short_username_from_before_length_validation = 'firstuser'
    user = User.new(username: short_username_from_before_length_validation)
    user.save!(validate: false)

    # This will add "You need to be more witty with your username." to base errors
    user.save

    # No reason given so will fail and will have error on base but will clear base error added above
    user.suspend("")

    # Only the suspension error should appear here
    assert_equal ["You need to specify a reason for the suspension."], user.errors[:base]
  end
end
```

CC @lulalala, @eileencodes

**Comment by cpruitt** [comment]
I noticed that something like `some_model.errors.messages.delete(:attribute)` will also raise a `FrozenError` with 6.1

**Comment by lulalala** [comment]
Thanks and apologies.

Currently the kind of "smart" cover-all-case solution I can think of, would be to 

1. wrap and delegate all `Enumerable` and `Array` functions to inner array.
2. before delegating, make a copy of message array
3. after delegation, compare the new array with existing message array.
4. for the removed messages, loop through the errors object array and remove them

This handles removal, but not insertion or modification. Would this be an overkill? (compared to just implementing methods as we encounter more use-cases?)

**Comment by cpruitt** [comment]
@lulalala Thanks for the reply. 🙂 My primary concern would be the somewhat significant change in the errors API without deprecation warnings showing up, particularly given that `DeprecationHandlingMessageArray` seems to exist to provide those deprecation warnings.

We're catching these issues early because we dual boot Rails 6.0 and 6.1, but many folks probably won't move to 6.1 until it's released so I wonder if we would be able to catch all the use cases beforehand. I wouldn't want to bloat `DeprecationHandlingMessageArray` and friends unnecessarily, but if possible it seems like having a solution that covers all Array/Enumerable methods would be "nice" to have.

**Comment by enriikke** [comment]
I agree that gracefully deprecating all messages makes sense if possible. I'll update https://github.com/rails/rails/pull/37088 to reflect that. 😃

**Comment by enriikke** [comment]
👋 hello friends! I spent some time looking at wrapping all functions. The solution I came up with is overriding `method_missing` on `DeprecationHandlingMessageHash` and `DeprecationHandlingMessageArray` so that we can show the deprecation warning and compare the copy array. It looks something like this:

```rb
class DeprecationHandlingMessageHash < SimpleDelegator

  # ...

  def method_missing(m, *args, &block)
    r = true
    target = self.__getobj__ {r = false}

    if r && target.respond_to?(m)
      ActiveSupport::Deprecation.warn(<<~MSG)
        Calling `#{m}` on ActiveModel::Errors message hash is deprecated.
      MSG

      res = target.__send__(m, *args, &block)
      @errors.clear
      target.each do |attribute, value|
        Array(value).each do |message|
          @errors.add(attribute, message)
        end
      end
      res
    elsif ::Kernel.method_defined?(m) || ::Kernel.private_method_defined?(m)
      ::Kernel.instance_method(m).bind(self).(*args, &block)
    else
      super(m, *args, &block)
    end
  end

  # ...
end
```

There are a couple of things that I noticed doing this:

- ⚠️ We have more warnings. I'm not sure whether every single method call to `errors.messages` or `errors[..]` is meant to be deprecated but this approach leads to every call having a deprecation message including functions that only read.

- 😕  The deprecation warnings become less clear. We can output _which_ method is being deprecated in the message but it's hard to point users to the new alternative.

- 🔧 This implementation naively updates the source array every single time, even if the delegated method was only reading and not mutating. I chose this route for simplicity since we would have to compare every key and value to know what changed anyway. We can certainly do that if this is a perf issue.

With all that in mind, I'm starting to think that manually defining the delegated methods might be a better option than I had originally thought. It might bloat the delegator classes but I _think_ those are meant to go away in the near future anyway (please correct me if I'm wrong there 🙏).

I'm also not sure if there's a better way to accomplish wrapping these methods so I would ❤️ some thoughts/guidance on that. 

/cc @lulalala @cpruitt

**Comment by lulalala** [comment]
Thanks @enriikke!

I agree with the issues you mentioned, and feel manually defining is easier to understand.


----

As a wild suggestion, how about bringing back the old implementations as a different class. We can have a configuration options which defaults to the older implementation. The user is allowed to migrate to the new implementation when they feel like it. Questions being:

* This way would we still need to maintain 100% compatibility in the new implementation?
* How do we handle documentation in this case?

@eileencodes @cpruitt @enriikke

**Comment by eileencodes** [comment]
> As a wild suggestion, how about bringing back the old implementations as a different class

I think this is an excellent idea if it's possible.

**Comment by cpruitt** [comment]
I definitely support the idea of a config option. 

I don’t think we’d need to be 100% compatible in this case. We were able to fix our app pretty quickly. The biggest difference we hit and the most time spent between the old/new implementations was actually related to the sort order of errors affecting brittle test assertions. I think it’s more important to give an app some time to adjust to the new API after upgrading and using a legacy class allows that.

**Comment by enriikke** [comment]
oof! Sorry I haven't come back to this in a while 🙇 

I think a configuration option sounds like a great idea! I'll look around for examples of this in Rails in the past. Some questions that come to mind:

- I'm assuming that we will remove all deprecation warnings and delegators from the new class altogether since we don't expect to maintain 100% compatibility. Does that sound right?
- Will the legacy class be deprecated at some point? Do we need to include an expected version when the legacy class and configuration option will go away (for deprecation warnings)?
- I'm also assuming the default option will be the legacy class. Is that right?

---

On the other hand, I'm also wondering how much work will be needed to implement this configuration option since I haven't done it in the past. I'm curious what the deprecation timespan of this option will be (if there is any) vs. manually defining the methods as we find issues? 🤔 

@cpruitt given the size of the GitHub codebase, have you seen other errors related to this in addition to the original two you mentioned? 

I'll be spending some time trying to gauge the effort of implementing this still! I just wanted to make sure to ask those questions. 😃

**Comment by lulalala** [comment]
> I'm assuming that we will remove all deprecation warnings and delegators from the new class altogether since we don't expect to maintain 100% compatibility. Does that sound right?

That sounds reasonable (and simplifies the code base by a lot :D). I guess the only place that needs deprecation warnings are during app boot, checking if legacy implementation is used.

> Will the legacy class be deprecated at some point?

I am guessing we would remove the legacy class in Rails 7.

> I'm also assuming the default option will be the legacy class.

I think that would be the most graceful.

 @enriikke not sure if you have already started tackling it. I am happy to help out if you haven't.

**Comment by cpruitt** [comment]
> given the size of the GitHub codebase, have you seen other errors related to this in addition to the original two you mentioned?

@enriikke The two that I mentioned are the only two that I've personally encountered.

**Comment by enriikke** [comment]
Thank you @cpruitt and @lulalala! I haven't yet started on this so feel free to jump at it. 🙇 I'll check back on Thursday (got some time then) and can help out where needed. 😃

**Comment by lulalala** [comment]
@enriikke I've started a PR here: https://github.com/rails/rails/issues/37081

**Comment by lulalala** [comment]
@matthewd [commented on the PR](https://github.com/rails/rails/pull/37910#issuecomment-562944592), saying he do not think implementation switching being a good idea. (@matthewd it may be worth pasting it here too).

@enriikke that being the case, I think we should go your path of https://github.com/rails/rails/pull/37088

**Comment by cpruitt** [comment]
FWIW, we haven't hit any other array methods that have been a problem for us so I think https://github.com/rails/rails/pull/37088 is likely sufficient.

**Comment by enriikke** [comment]
Thank you for the follow up @lulalala, @cpruitt, and @matthewd 🙇 

I'm happy to move #37088 forward! Is there anything else needed to get it merged? (reviews, tests, etc.) 😃
