### ISSUE TITLE
Rails 6 initializer autoloads separate instance of a class

### ISSUE THREAD

**Issue by nbrustein** [rails/rails#37186]
### Steps to reproduce

In rails 6, different instances of the same class can be autoloaded in an initializer vs. a rake task or a rails console.  This is a problem if there is state saved on the class itself.  Saving state on the class might be bad practice in general, but it is supported through things like `cattr_accessor`.  In any case, it seems odd that the class would be autoloaded twice,

Repro steps:

Include the following files in a rails app.

```
# app/models/my_class.rb

class MyClass
end
```

```
# config/initializers/zeitwerk_test.rb

puts "initializer: #{MyClass.object_id}"
```

```
# lib/tasks/zeitwerk_test.rake

namespace :zeitwerk_test do

    task :test => :environment do

        puts "rake task  : #{MyClass.object_id}"

    end

end
```

In a console, run `rake zeitwerk_test:test`

### Expected behavior

The same object_id should be outputted both times (this is what happens in rails 5.2.3).

### Actual behavior

The initializer and the rake task log different object_ids.  

### System configuration
**Rails version**:  6.0.0

**Ruby version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by booleanbetrayal** [comment]
This seems a little scary ...

**Comment by vindvaki** [comment]
@nbrustein we just had a [similar looking problem](https://gitlab.com/gitlab-org/gitlab/issues/199866) (class configured in an initializer is not correctly configured at runtime) affecting development environments, and reverting the [updated file watcher](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/24167) seemed to help.

**Comment by mcansky** [comment]
Seeing something similar on vanilla Rails 6.0.3.4 applications : initialisers are run but the state is not available when accessed in the console or at a later point in general.

**Comment by mcansky** [comment]
after digging a bit more following @vindvaki comment and reading on Zeitwerk I found https://guides.rubyonrails.org/autoloading_and_reloading_constants.html and tested the use of the "classic" autoloader, this solves the issue I was spotting. Not sure what's the conclusion there, but out of the box, including on a freshly generated rails app I could not get the initialisers configuration blocks to "stick" as multiple instances of the classes were handled.

What's the expected behaviour with the current 6.x releases ?
