### ISSUE TITLE
including namespaced concern makes controller method definitions obsolete 

### ISSUE THREAD

**Issue by ezii123** [rails/rails#37193]
### Steps to reproduce
Create a 'concerns' under a namespace folder for controllers. Add a concern module file.
Include the concern in a controller under the same namespace.

### Expected behavior

The method body for the expected action (in my specific case: 'new') should still be called and instance variable definition should be made.

### Actual behavior
The method body is not called, a `.errors` is called on a nil object in the scaffold-generated `_form.html.erb`.

### System configuration
**Rails version**:
Rails 6.0.0

Gemfile.lock pastebin: https://pastebin.com/pc2Tr7aB

**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.

**Comment by ezii123** [comment]
@y-yagi Fuck you

**Comment by ezii123** [comment]
@y-yagi What qualifies this as a non-issue?

**Comment by ezii123** [comment]
What makes you assume I need help?

**Comment by ezii123** [comment]
What do I need help with?

**Comment by ezii123** [comment]
@dhh 

Maybe Rails will fail after all.

I see the big sites moving away from it anyway and your support here is lacking majorly.

Once the Rails bastion falls, you'll know that basecamp.com will only thrive financially with Rails open source ecosystem as the backbone.

**Comment by ezii123** [comment]
1.
There is no Rails Guide about concerns.
2.
The error I observed should not be possible, even if I didn't follow convention.
3.
The thing I was trying (putting a new concerns folder under a controller namespace folder) wasn't something that seems too awkward to me
4.
@y-yagi (Member of the Rails Github team) is referring me to the mailing list, even though this is a bug report
5.
Instead of questioning what lies beyond this issue and why I reported this firstly, @y-yagi hastily closes this issue and refers to the mailing list in order to cheat his way through the Github issue notifications

**Comment by talpava** [comment]
Тогда Вы и верните деньги!:-) За секунду  до бана обмен был!а доступ к деньгам теперь нет:-(11:19, 14 сентября 2019 г., ezii123 <notifications@github.com>:@dhh
Maybe Rails will fail after all.
I see the big sites moving away from it anyway and your support here is lacking majorly.
Once the Rails bastion falls, you'll know that basecamp.com will only thrive financially with Rails open source ecosystem as the backbone.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
Отправлено из мобильной Яндекс.Почты: http://yandex
