### ISSUE TITLE
Memory leak after upgrade Rails 5.2 to 6.0.0

### ISSUE THREAD

**Issue by patriciobi** [rails/rails#37196]
Has anyone experienced this? We upgraded a project from Rails 5.2 to Rails 6.0.0 and after this, the memory consumption skyrocketed... In the release candidate environment, it works fine, but in production, the container dies because of the memory usage... The instances we have in 5.2 can do just fine with 1GB RAM, but the instances we test for Rails 6.0.0 dies immediately, even if we give them 4GB ram.

We already tested https://github.com/schneems/derailed_benchmarks, but the require gems just increased like 10 MiB in total. 

We have some heavy queries but we don't know why this happens in Rails 6 and not in Rails 5.

**Comment by kaspth** [comment]
Hey sorry to hear that. We can’t really help with anything since this is so broad. I recommend trying out an APM service that can breakdown where objects are allocated or try your hand at the Memory Profiler gem.

Once you find something that’s a likely culprit do open a new issue, volunteering a PR is also very welcome. ✌️
