### ISSUE TITLE
TagBuilder has surprising behaviour 

### ISSUE THREAD

**Issue by KaptajnKold** [rails/rails#37209]
I was surprised to find out that TagBuilder has this behaviour. I would have expected it to work more like [Jim Weirich's XML builder gem](https://github.com/jimweirich/builder). The behaviour of TagBuilder may not exactly be buggy, but—to my eye at least—it is not quite as helpful as it could be. 

### Steps to reproduce

In e.g. ApplicationHelper:

```
def unordered_list
  tag.ul do |list|
    list.li "Item 1"
    list.li "Item 2"
    list.li "Item 3"
  end
end
```

In any view:

`<%= unordered_list %>
`
### Expected behavior

I would expect the above to yield the following output:

```
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>

```
### Actual behavior

```
<ul>
  <li>Item 3</li>
</ul>

```

### System configuration
**Rails version**: 5.2.2.1

**Ruby version**: 2.6.1p33

**Comment by joshmn** [comment]
The block only adds the returned object to the output buffer. This is expected behavior. You're looking for [`concat`](https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-concat).

```
def unordered_list
  tag.ul do |list|
    concat list.li "Item 1"
    concat list.li "Item 2"
    concat list.li "Item 3"
  end
end
```

**Comment by kaspth** [comment]
Thanks, I'll close as this is the expected behavior. This has pretty much always been how Rails' helpers have worked and no one, as far as I know, is actively working on changing it.

Any such proposal PR would need to dig in pretty deep: have a pretty clear direction of the future undergirded by extracted use cases from actual apps and understand the history enough to know how to provide (or somehow elide the need for) backwards compatibility.
