### ISSUE TITLE
[No error when migration missing up/change] <s>Migration running twice</s>

### ISSUE THREAD

**Issue by EthanZeigler** [rails/rails#37225]
### Steps to reproduce
Unknown exactly, but as follows.
1. Create new migration
2. Run migration
3. Migration runs twice by rails and causes a duplicate table error

### Expected behavior
Migration doesn't run twice when using the rails command

### Actual behavior
Migration runs twice when using the rails command

### System configuration
**Rails version**:
5.2.3
**Ruby version**:
2.6.4

### Migrations:
https://hastebin.com/likoyicufo.rb
https://hastebin.com/cenonegego.bash

### Log:
https://hastebin.com/exopasekas.sql

What on earth is happening here?

**Comment by latortuga** [comment]
> https://hastebin.com/cenonegego.bash

This file does not have the migration code in an `up` method.

```ruby
class MyThing
  create_table :users
end

# vs

class MyThing
  def up
    create_table :users
  end
end
```

I would venture a guess that the file is getting run multiple times and running the defined migrations each time. The syntax highlighting is a dead giveaway, watch out for that :sunglasses:

**Comment by EthanZeigler** [comment]
*facepalm*

Yeah, that would be it. Why isn't that an error? "Migration has no **up**
or **change** method"

Ethan Zeigler
ethanzeigler.com

Please excuse any typos. Sent from my phone.

**Comment by latortuga** [comment]
Yeah it's just a ruby file and those methods (`create_table`, `add_index`, etc) are class methods. It's definitely a gotcha but unfortunately it's valid ruby. When you require the file, it will perform the method calls just as directed. Also, `up`, `down`, and `change` are all intentionally optional. This allows you to do things like comment out all your methods to force a migration to be marked as ran.

**Comment by matthewd** [comment]
> Why isn't that an error?

Good question!

Migration `up` and `down` methods used to be defined and called on the migration class itself (https://guides.rubyonrails.org/v3.0/migrations.html), which is why the DDL methods are all available there as well as on the instance.

As we have Rails versions inside migrations now, I think we can (and should) remove those unless running in `4.2` mode (the oldest available, because that's when versioning was introduced). If anyone's interested, that's probably a good first PR.

**Comment by EthanZeigler** [comment]
> This allows you to do things like comment out all your methods to force a migration to be marked as ran.

I'd argue that to do that, a field should be necessary to declare that's the intent.

`mark_invalid = true`

**Comment by allcentury** [comment]
@matthewd 

> As we have Rails versions inside migrations now, I think we can (and should) remove those unless running in 4.2 mode (the oldest available, because that's when versioning was introduced). If anyone's interested, that's probably a good first PR.

Meaning, remove the DDL methods from the class?  I'm happy to give this a shot but just to make sure I understand

support this only for 4.2:

```
class MyThing < ActiveRecord::Migration[4.2]
  create_table :users
end
```

otherwise ensure a `#change|#up` method exists on the instance?

**Comment by matthewd** [comment]
@allcentury :+1: -- with the caveat that I haven't looked deeply here, so you might uncover some reason this can't happen along the way, though it does seem to just be a historical artifact.

In practice we should probably only make the change for 6.1+ migrations.. just in case anyone's been unknowingly writing 5.x/6.0 migrations in the old `self.up` form, so we don't break them. (And because this is intended to help people who might make a mistake writing a new migration, which they'd be doing in the current/latest version.)

**Comment by sinsoku** [comment]
> https://hastebin.com/cenonegego.bash

This file has code that includes the wrong table name `'issue_area'`.

```ruby
add_foreign_key 'opportunities', 'issue_area', column: 'issue_area_id'
```

If you fix this line, the migration will be one time.

However, it is better to define `up/down` or `change` instance methods with reference to the migration guide.
https://edgeguides.rubyonrails.org/active_record_migrations.html

**Comment by EthanZeigler** [comment]
Thanks @sinsoku. My issue was fixed a while back, but I left the issue open due to the discussion of changing the system to error when change/up is not provided.
