### ISSUE TITLE
Rails 6: deliver_later doesn't affect ActionMailer::Base.deliveries

### ISSUE THREAD

**Issue by collimarco** [rails/rails#37389]
### Steps to reproduce
After upgrading to Rails 6 I am noticing that default mailer's `.deliver_later` is not working the same as in Rails 5. 

Configuration: 

```
config.active_job.queue_adapter = :inline
```

When running `Mailer.register_email(...).deliver_later` - nothing is stored in `ActionMailer::Base.deliveries`. This array gets filled if I run `perform_enqueued_jobs` - it seams like `queue_adapter = :inline` doesn't work the way I expect it to work. 

[Credits](https://stackoverflow.com/questions/57776074/rails-6-deliver-later-doesnt-affect-actionmailerbase-deliveries)

### Expected behavior
`ActionMailer::Base.deliveries` should contain some mail after calling `.deliver_later`.

### Actual behavior
`ActionMailer::Base.deliveries` is empty.

### System configuration
**Rails version**: 6.0.0
**Ruby version**:  2.6.5

**Comment by kaspth** [comment]
Where are you setting the `:inline` adapter? The behavior is the expected behavior for the async adapter, so it seems it's not taking effect. Try logging `Rails.application.config.active_job.queue_adapter` in your test and see what that says, then you'd probably need to track down where the adapter is assigned. Thanks!

**Comment by collimarco** [comment]
@kaspth I had this code which was working fine with Rails 5.2:

```
around(:each) do |example|
  Sidekiq::Testing.inline! do
    example.run
  end
end
```

There's a breaking change or bug somewhere in Rails 6.0.

**Comment by kaspth** [comment]
Cool cool, please do investigate as we like to say 😊

**Comment by kaspth** [comment]
Wups, forgot to say. There isn't a lot I or others can do without a failing test case using our bug report templates. We'd be doing lots of guesswork, that may not fix what's going on in your app. So we recommend doing the investigation yourself. My first comment provided some hints of how to start.

**Comment by kzkn** [comment]
Maybe caused by this: #37270

**Comment by nethad** [comment]
I've found that using

```ruby
assert_emails 1 do
  # code under test
end
```

helps here instead of using `ActionMailer::Base.deliveries.size`. I found the solution via https://stackoverflow.com/a/57866436/303626

**Comment by inspire22** [comment]
Unfortunately "assert_emails 1" which worked with 6.0 is now broken again when you put "config.load_defaults 6.0" (or 6.1) in application.rb as required to avoid other depreciation messages. Any ideas how to get this working again.  I suspect it's related to the change from this depreciation warning, but don't know where to start.

DEPRECATION WARNING: Sending mail with DeliveryJob and Parameterized::DeliveryJob is deprecated and will be removed in Rails 6.2. Please use MailDeliveryJob instead.

config.load_defaults 6.0 solves this depreciation warning, but then breaks assert_emails

**Comment by mur-wtag** [comment]
why this issue is `closed`!??

**Comment by ghiculescu** [comment]
Hi @mur-wtag , the issue was closed as it was not clear what the issue was, or if there is a bug in Rails here.

It would be really helpful to see an executable test case - https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case - to replicate if there is a specific bug here.

**Comment by zzak** [comment]
@mur-wtag It seems it was due to lack of information available in order to debug the reported issue.

If you're interested in solving this particular problem, it would help us to have a [bug report](https://github.com/rails/rails/tree/main/guides/bug_report_templates) that reproduces the problem. 🙇

**Comment by rhomeister** [comment]
Calling `perform_enqueued_jobs` before inspecting `ActionMailer::Base.deliveries` fixed this problem for me. It isn't very convenient having to call this every single time though, but perhaps this gives anyone a hint about the root cause?

I've tried setting `config.active_job.queue_adapter = :inline` to no avail.

**Comment by cdan-youdo** [comment]
This is most probably linked/same issue as #37270

**Comment by cdan-youdo** [comment]
My workaround was to wrap the code inside a
```
perform_enqueued_jobs do
....
end
```

This way, any jobs that are enqueued inside the block, will be run automatically.

**Comment by constantm** [comment]
> 



> My workaround was to wrap the code inside a
> 
> ```
> perform_enqueued_jobs do
> ....
> end
> ```
> 
> This way, any jobs that are enqueued inside the block, will be run automatically.

This is the correct answer. You'll also need to include `ActiveJob::TestHelper` in your test.
