### ISSUE TITLE
`Model.upsert_all` not playing nicely with partitioned tables

### ISSUE THREAD

**Issue by alex-klepa** [rails/rails#37426]
### Steps to reproduce

SQL schema:
```SQL
CREATE TABLE measurement (
    city            varchar not null,
    logdate         date not null,
    peaktemp        int,
    unitsales       int
) PARTITION BY LIST (city_id);
CREATE TABLE measurement_toronto PARTITION OF measurement FOR VALUES IN ('toronto');
CREATE UNIQUE INDEX on measurement(logdate, city);
```

```
psql: \di
 public | measurement_logdate_city_idx                         | partitioned index | sash  | measurement
 public | measurement_toronto_logdate_city_idx                 | index             | sash  | measurement_toronto
```

```ruby
Measurement.upaset_all(measurements, unique_by: %[logdate city])
# => ArgumentError (No unique index found for "logdate city")
```

The problem is here: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/insert_all.rb#L72

**connection.schema_cache** doesn't have **partitioned indexes** for parent table, only for child tables (which irrelevant for us)

```ruby
ActiveRecord::Base.connection.schema_cache.indexes(:measurement).select(&:unique) 
# => []

ActiveRecord::Base.connection.schema_cache.indexes(:measurement_toronto).select(&:unique)

#[
#    [0] #<ActiveRecord::ConnectionAdapters::IndexDefinition:0x00007fa694c34370 #@table=:measurement_toronto, @name="measurement_toronto_logdate_city_id_idx", #@unique=true, @columns=["logdate", "city_id"], @lengths={}, @orders={}, @opclasses={}, #@where=nil, @type=nil, @using=:btree, @comment=nil>
#]
```

### Expected behavior
Should work

### Actual behavior
Returns ArgumentError
```
ArgumentError (No unique index found for "logdate city")
```

### System configuration
**Rails version:** 6.0

**Ruby version:** 2.6.4

**Postges version:** 10/11/12

**Comment by alex-klepa** [comment]
Also it will fail on non-column indexes, e.g. **lower(range)** because of  

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/insert_all.rb#L144
```ruby
format_columns(index.columns)
``` 
will put quotes around all index "columns".

**Comment by vnhnhm** [comment]
Hi @alex-klepa. I've replicated this error and created a [PR](https://github.com/rails/rails/pull/37585) with the changes to make this work.

The main problems are:
  - You're using `%[logdate city]`, which evaluates to a string `"logdate city"` and that value is passed as the `unique_by` argument. It's never split to get an array as `["logdate", "city"]`. So, in that case, the error is accurate, and there's nothing to do. You should make sure to use `%i[...]` or `%w[...]` to create array literals for the `unique_by` option.

- The elements from the `pg_class` to get the indexes are filtered by those whose `relkind` is `i`, meaning it's an index. But since version 11 of PostgreSQL, there are also partitioned indexes, with `relkind` value of `I`. So they're being filtered out.

It' shouldn't be failing in older versions (other than 11 and 12) of PostgreSQL.

I'd appreciate any feedback. Thanks!

**Comment by simi** [comment]
Not stale at all, problem still present. Anyway since PR (https://github.com/rails/rails/pull/37585) is already opened maybe it is ok to close this.

**Comment by simi** [comment]
@alex-klepa #37585 was merged, can you check if your problem is still present on latest master?

**Comment by alex-klepa** [comment]
Hi Josef, yes working as expected, using it since last week. Thank you!
