### ISSUE TITLE
rails new silently ignores bogus arguments

### ISSUE THREAD

**Issue by p-mongo** [rails/rails#37420]
### Steps to reproduce

Run this command:

<pre>
rails new --foo blah --bar
</pre>

### Expected behavior

I expected this to fail, saying --foo and --bar options are unknown.

### Actual behavior

This creates a new application called `blah` without errors.

This is a bigger issue when the options are valid but are given prior to project name, such as:

<pre>
rails new --skip-bundle foo1
</pre>

The option is valid but rails new does not recognize it if it precedes the project name. No errors are reported but rails tries to bundle install, contrary to the user's intention.

### System configuration
**Rails version**:

Rails 6.0.0

**Ruby version**:

ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**Comment by HeroProtagonist** [comment]
Hi! Can i take a stab at this?

**Comment by matthewd** [comment]
As @joshmn mentioned, the latter part of this issue is #37402, which is a now-fixed upstream issue in Thor.

The more general acceptance of unknown options is trickier: I believe it's pretty much architecturally impossible to prevent that, because we don't know what options might be accepted by the generators (and possibly custom template) we end up invoking.

**Comment by p-mongo** [comment]
The `new` generator is part of Rails, hence it should be within Rails team's ability to ensure that any arguments that this generator gets (i.e. everything that is not recognized by the top level `rails` command) are either valid or produce errors.
