### ISSUE TITLE
Incorrect strings are plucked when joined tables have enum columns with the same name

### ISSUE THREAD

**Issue by NicholasHassan** [rails/rails#37484]
### Steps to reproduce

```
class Customer < ActiveRecord::Base
  has_many :purchases
  enum type %i[active slipping lost recovered]
end

class Purchases < ActiveRecord::Base
  belongs_to :customer
  enum type %i[scheduled shipped delivered late lost]
end

Purchase.joins(:customer).distinct.pluck("purchases.type")
Customer.joins(:purchases).distinct.pluck("purchases.type")
```

### Expected behavior

```
["scheduled", "shipped", "delivered", "late", "lost"]
["scheduled", "shipped", "delivered", "late", "lost"]
```

### Actual behavior
```
["scheduled", "shipped", "delivered", "late", "lost"]
["active", "slipping", "lost", "recovered", nil]
```

### System configuration
**Rails version**:
5.1
**Ruby version**:
1.8.7

**Comment by joshmn** [comment]
Might be happening here https://github.com/rails/rails/blob/90353420a68ba9834608d4d681ae703893c5cbc7/activerecord/lib/active_record/relation/calculations.rb#L186

**Comment by Erol** [comment]
Nah, it's actually happening in: https://github.com/rails/rails/blob/90353420a68ba9834608d4d681ae703893c5cbc7/activerecord/lib/active_record/relation/calculations.rb#L194

The problem is that `ActiveRecord::Result` has no context about the column's table. For the example above, we get a `result` that looks something like: 

```
<ActiveRecord::Result:0x00007fd74ac9ed10 @columns=["type"] ...>
```

Even if we pass a map of attribute types that includes `Purchase`, `result` won't be able to discern if it should cast using `Customer` or `Purchase`.

It gets even worse if we do something like this:

```
Customer.joins(:purchases).pluck('customers.type', 'purchases.type')
```

What we get is a `result` that looks something like:

```
<ActiveRecord::Result:0x00007fd74ac9ed10 @columns=["category", "category"] ...>
```
