### ISSUE TITLE
ActiveRecord model with column named 'tap' makes .reload return the value of the attribute instead of the record

### ISSUE THREAD

**Issue by francescob** [rails/rails#37493]
### Steps to reproduce
Create an active record model with a column named 'tap', save a record, load it and then call .reload on it

### Expected behavior
it should return the reloaded record

### Actual behavior
it returns the value of the column 'tap'

### System configuration
Rails 5.2.3

Ruby 2.6.3

**Comment by louim** [comment]
Ill have a look to see if it's an easy fix or not.

Repro script:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :tap
  end
  create_table :comments, force: true do |t|
    t.text :body
  end
end

class Post < ActiveRecord::Base
end

class Comment < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_tap
    post = Post.create!(tap: "Some text")
    assert_equal Post, post.class
    # Will fail
    assert_equal Post, post.reload.class
  end

  def test_non_tap
    comment = Comment.create!(body: "Some text")
    assert_equal Comment, comment.class
    assert_equal Comment, comment.reload.class
  end
end
```

**Comment by louim** [comment]
Soo, the problem is caused by this line:
https://github.com/rails/rails/blob/02723536f88be1a389908e53239a65680a6147b8/activerecord/lib/active_record/attribute_methods/dirty.rb#L31
having a `tap` attribute generates accessor methods that overwrite the [ruby `tap` method](https://ruby-doc.org/core-2.6.5/Object.html#method-i-tap), causing it to return the value of the attribute there instead of the expected behavior.

I'm still not sure of the best way to fix this, but you should probably change the `tap` attribute to something else to prevent conflicts with the ruby method.

**Comment by kaspth** [comment]
We do some work internally to warn against certain attribute methods use but that only checks ActiveRecord::Base: https://github.com/rails/rails/blob/b305f0e206b0d15ea81f9571669d9e831c9193e0/activerecord/lib/active_record/attribute_methods.rb#L83

However, since `tap` is implemented on Object, and the attribute method overrides that, I think this falls under being careful not to override Object methods when defining attributes. Thanks! I'll close as expected behavior.
