### ISSUE TITLE
Regression When Rendering Templates in Subclasses of ActionView::Base

### ISSUE THREAD

**Issue by olly** [rails/rails#37528]
### Steps to reproduce

In our application we use a subclass of `ActionView::Base` to render templates outside of ActionController. These templates are also rendered in `ActionController`'s context. With Rails v6.0.0 we're seeing a regression, where templates which are rendered in the `ActionView::Base ` subclass then raise a `ActionView::Template::Error` when subsequently rendered in the `ActionView::Base` class.

I believe we're using `ActionView` in a way that's intended to be supported by the public API.

A small test case is below, with sample commands, expected & actual output in [this gist](https://gist.github.com/olly/31d812e15895c24e0854dd9cd2aee4d8).

```ruby
# Run:
#  $ ruby test.rb 5.2.3
#  $ ruby test.rb 6.0.0

require 'bundler/inline'

raise "specify rails verison: #{ARGV[0].inspect}" unless ARGV[0]

gemfile do
  source 'https://rubygems.org'

  gem 'actionpack', ARGV[0], require: false
end

require 'action_view'
require 'pathname'

LOOKUP_CONTEXT = ActionView::LookupContext.new([Pathname.new(__dir__).to_s])

class ViewContext < ActionView::Base
  def initialize
    super(LOOKUP_CONTEXT, {}, nil)
  end
end

subclass = ViewContext.new
puts subclass.render(template: 'sample')

puts
puts "==="
puts

base = ActionView::Base.new(LOOKUP_CONTEXT, {}, nil)
puts base.render(template: 'sample')
```

I suspect the root cause lies in https://github.com/rails/rails/pull/35036 where, as I understand, all subclasses of `ActionView::Base` shared a common module for compiled templates. Now that each subclass has a different module for compiled templates, it seems as if the template gets marked as compiled so when it's rendered in a different context that method isn't available.

However, by reversing the order of the rendering (i.e. first rendering in `ActionView::Base` and then rendering in the subclass) it works as expected. Which perhaps points to this not being the root cause.

### Expected behavior
Rendering the template in both contexts succeeds. However, my expectation would be that different contexts would each have a different caches – in contrast to the behaviour in v5.2.3.

### Actual behavior
Rendering raises a `ActionView::Template::Error`

### System configuration
**Rails version**: v6.0.0

**Ruby version**: v2.6.5

**Comment by mwallba** [comment]
Was able to reproduce this. 

> However, by reversing the order of the rendering (i.e. first rendering in ActionView::Base and then rendering in the subclass) it works as expected. Which perhaps points to this not being the root cause.

It works in that order because the subclass-instance can lookup the compiled template-method on the `ActionView::Base` but not the other way around.

In the case above, the details cache points the resolver towards the compiled method on the subclass, but when the `ActionView::Base`-class tries to execute said method, it naturally won't be dispatched to the subclass.

It works perfectly if you disable caching in the lookup context too and gives you the deprecation warning.

Would be interesting to see if using `new` here is considered public api

**Comment by denisahearn** [comment]
We are also experiencing this regression. In our case, we have some specs that are failing due to the following error:

```
   ActionView::Template::Error:
       undefined method `___sers_denisahearn__rvm_gems_ruby_______gems_activeadmin_______app_views_kaminari_active_admin__paginator_html_erb___2167395329580451730_70225555512320' for #<#<Class:0x00007fbd52a390a0>:0x00007fbd4ae1ee48>
```

The failing specs are in `spec/admin/components/version_panel_spec.rb`, which is listed below:

```
require 'rails_helper'

RSpec.describe VersionPanel, type: :admin do
  before(:all) do
    Temping.create :resource do
      has_paper_trail
    end
  end

  after(:all) do
    Temping.teardown
  end

  let(:resource) { Resource.create }

  subject { render_arbre_view(resource) }

  describe "who did it" do
    before(:each) do
      version = resource.versions.first
      version.update(whodunnit: whodunnit)
    end

    context "when whodunnit is present" do
      let(:whodunnit) { 'Me' }

      it "displays whodunnit" do
        expect(subject.content).to include whodunnit
      end
    end

    context "when whodunnit is not present" do
      let(:whodunnit) { nil }

      it "displays N/A" do
        expect(subject.content).to include "N/A"
      end
    end
  end

  def render_arbre_view(resource)
    assigns = {}

    view_class = ActionView::Base.with_empty_template_cache
    view_class.send(:include, Rails.application.routes.url_helpers)
    view_class.send(:include, ActionView::Helpers)
    view_class.send(:include, ActiveAdmin::ViewHelpers)

    view = view_class.with_view_paths(
      ActionController::Base.view_paths,
      assigns,
      ActionView::TestCase::TestController.new
    )

    arbre_context = Arbre::Context.new(assigns, view) do
      version_panel(resource)
    end

    arbre_context.children.first
  end
end
```

I configured rspec to run the examples in random order. If you run them multiple times, you will see that the first one always passes, however, the second one always fails.

When I play around with this spec code in our actual Rails app, I have been able to get the specs in this one spec file to pass. However, when I run our full suite of specs, then the specs in this one spec file will fail. The full suite of specs run other specs that test code which also uses the same ActiveAdmin view component. So I'm guessing that what @olly says above about this problem appearing when the context changes is the reason for this.

I'm hoping that someone who understands ActionView much better than me can use this sample Rails app to either figure out a solution, or at least find a workaround to the issue.

[action-view-test.zip](https://github.com/rails/rails/files/3806395/action-view-test.zip)
