### ISSUE TITLE
Getting Started Bugs

### ISSUE THREAD

**Issue by saulakravitz** [rails/rails#37607]
### Steps to reproduce

1) If you search for "To do that, you'll modify app/views/articles/new.html.erb to check for error messages:", the code should be:
<% if @article && @article.errors.any? %>
Otherwise, it throws an error before @article is created.
2) The changes for using a form for the new/edit actions don't work.   They result in "No route matches [POST] "/articles/new""

Otherwise, very helpful.

### System configuration
**Rails version**:

**Ruby version**:

**Comment by dmitry** [comment]
@saulakravitz just read it though and getting started works good. Please note `  resources :articles
` in the `routes.rb`. You have to create `def new` inside the controller, and add there a `@article = Article.new`, and you have to point `POST` of th data to the `/article` instead of `new` or `edit` - those actions have a `GET` methods.
