### ISSUE TITLE
There's no way to correctly use the block parameter of around_action

### ISSUE THREAD

**Issue by jolmg** [rails/rails#37616]
### Steps to reproduce

In a controller, use:

```ruby
around_action { yield }
```

### Expected behavior

Actions should work as normal.

### Actual behavior

An exception was raised:

```
LocalJumpError: no block given (yield)
```

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.4p104

### Comment

[This was raised as an issue in another project](https://github.com/toptal/chewy/issues/25). However, the issue was closed when the OP found that moving the code to a method and giving `around_action` a symbol with its name worked. It appears there is no way to correctly use the block parameter of `around_action`, since if no `yield` is provided, then the action doesn't get executed either.

**Comment by seejohnrun** [comment]
Hello, and thank you for the report! You can achieve this with:

``` ruby
around_action { |_controller, action| action.call }
```

I don't see anywhere in the documentation where `yield` is supported by `around_action`, but do agree it's what I would have expected to work. Anyway, if this resolves your original issue, I'll make a PR to add this to the guides (and add a test to make sure this behavior sticks around). ✨

**Comment by jolmg** [comment]
> I don't see anywhere in the documentation where yield is supported by around_action

Though it's not when using a block, [the use of yield is in the guide.](https://guides.rubyonrails.org/action_controller_overview.html#after-filters-and-around-filters)

I suppose it's fine that one can do `action.call`, though it seems inconsistent with the use of `yield` when using a method instead of a block.

The fact that the block given to `around_action` is provided the action as an argument does seem to be undocumented, though. I didn't find it neither in the [guide](https://guides.rubyonrails.org/action_controller_overview.html) nor in [api.rubyonrails.org](https://api.rubyonrails.org/classes/AbstractController/Callbacks/ClassMethods.html#method-i-around_action).

**Comment by seejohnrun** [comment]
We spent some time looking through this to try to understand what was going on here. It turns out, the issue with calling `yield` inside of an inline `around_action` is that `yield` will apply to the block passed to the wrapping method _at_ the point of block creation. Consider this code:

``` ruby
 1  class SomethingController < ApplicationController
 2    def self.wrap
 3      around_action do
 4        yield
 5      end
 6    end
 7
 8    wrap do
 9      puts 'I am in a block'
10    end
11  end
```

With this code we won't see an error anymore, and this illustrates what `yield` is actually referring to:  the block (lines 8-10) passed to the enclosing __method__ (`self.wrap`) at the point of the `around_action` block creation (lines 3-5).

In order to make `yield` work we'd have to introduce some pretty hacky code, likely defining a method on the fly for all `block` uses of `around_action`.  Given there are a few other viable paths (private method, `call`), I think a docs update is the best path forward. Let us know if any questions / concerns, and thanks again for opening this issue!

cc / @dinahshi who helped me looking into this

**Comment by jolmg** [comment]
> In order to make yield work we'd have to introduce some pretty hacky code, likely defining a method on the fly for all block uses of around_action.

I'm surprised to find that it's not as simple as I thought it would be. I just tried:

```ruby
def action
  puts "action"
end

def around(&b)
  b.call { action }
end

around { yield }
```

and variations and get the same error. As far as I can tell, it seems that Ruby has no support for passing blocks to blocks. `Proc#call` seems to ignore block arguments, and `yield {}` is a syntax error. That's a shame.

>  Given there are a few other viable paths (private method, call), I think a docs update is the best path forward.

I agree.

**Comment by zenspider** [comment]
The "proper" way to do this is to use a (block) block arg instead of `yield`:

```ruby
def action
  puts "action"
end

def around(&b)
  b.call { action }
end

around { |&b| b.call } # prints: action
```

**Comment by jolmg** [comment]
@zenspider The second post here showed that was available, and the PR that resolved this issue documented that.
