### ISSUE TITLE
rescue_from doesn't throw an error when used with a non-existent or misspelled exception class

### ISSUE THREAD

**Issue by jasonl** [rails/rails#37650]
### Steps to reproduce
Use `rescue_from` with a non-existent exception class. 

Test case here: https://github.com/jasonl/rescue_from_test_case/commit/878bf48d6483c5c414bff6834a5a093522a7cf90

### Expected behavior
A `NameError` exception should be thrown when Rails boots.

### Actual behavior
No error is raise, but the methods after the faulty `rescue_from` call are simply not defined, leading to `AbstractController::ActionNotFound` at runtime, and hard-to-diagnose test failures.

### System configuration
**Rails version**: 6.0.1

**Ruby version**: 2.6.5

**Comment by casperisfine** [comment]
A few observations.

This only happens with Zeitwerk, the classic autoloaders, if I configure the app to use the classic autoloaders, the test case fails with:

```ruby
DemonstrationControllerTest#test_should_get_show:
ActionController::RoutingError: uninitialized constant DemonstrationController::A
```

The original Zeitwerk error is silenced here: https://github.com/rails/rails/blob/14d958ec71bf800447eaa880f2d30a8cc78a4ada/actionpack/lib/action_dispatch/http/parameters.rb#L99-L103

That rescue has been added in https://github.com/rails/rails/commit/e06f68fdb2132623d27a26ae58213b09ecb308ee

I'll see if I find a way to reconcile both issues.

cc @fxn

**Comment by casperisfine** [comment]
Ok, so I found the root cause. 

With the classic autoloader, `controller_class_for(controller)` raises a `NameError` but `DemonstrationController` stays undefined.

However with Zeitwerk, after the `NameError` `DemonstrationController` is defined (in an incomplete way).

From my knowledge of Zeitwerk I think it will be very hard to replicate to old behavior (and we probably don't want to anyway).

So I think it's that `rescue NameError` that should be challenged.

**Comment by casperisfine** [comment]
I dug a bit more into this, and I think ultimately it's the [`skip_parameter_encoding`](https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/actionpack/lib/action_controller/metal/parameter_encoding.rb) that is implemented in a weird way.

It's what forces `Journey::Router` to load the controller, for what I believe is an exceptional case. Either the encoding should be specified in `routes.rb` so that it can be set this early.

Or either it stays specified in the controller, but then it's the controller that should change the parameters encoding.

cc @rafaelfranca

**Comment by rafaelfranca** [comment]
What is weird in that implementation? It is just setting a value in a hash, it is not doing anything related to constant loading or even rescue_from.

**Comment by casperisfine** [comment]
@rafaelfranca what's "weird" is that since it store the value on the controller, it forces the router to load the controller to access it.

**Comment by rafaelfranca** [comment]
The router needs to load the controller to be able to route to it, I don't think we can avoid that, so I don't see as a problem having to load the controller to try to set the parameters to it.

`DemonstrationController` being defined in an incomplete way after it failed to be loaded seems a bad behavior to me.

**Comment by casperisfine** [comment]
Let's wait to see what @fxn thinks.

**Comment by casperisfine** [comment]
And for the record, the "bad behavior" is just regular ruby core `Module#autoload`.

Same happens if code raise when you `require "something"`.

**Comment by rafaelfranca** [comment]
If I get this behavior correctly does it means that `"Foo".safe_constantize; "Foo".safe_constantize` would return `nil` and a half-backed `Foo` if something failed inside `foo.rb`?

**Comment by casperisfine** [comment]
@rafaelfranca yes.

**Comment by rafaelfranca** [comment]
😱 I see no case were this behavior is desired.

Even if this is the `autoload` behavior maybe `constantize` should be consistent and always raise `NameError`. It may require an internal cache or even undefining the constant (removing from the loaded features list) after the exception but I don't think two consecutive calls to the same method returning different values when no precondition changed is a good behavior to keep.

**Comment by fxn** [comment]
Hey! Only a heads up to say I saw the mention, but too busy these days to sit down and process the thread. I’ll do it as soon as I can!

**Comment by fxn** [comment]
Zeitwerk follows Ruby semantics. To say it in a different way, Zeitwerk does nothing related to this, which is what @casperisfine meant saying that this is just how `Module#autoload` works, which in turn depends on how `Kernel#require` works.

If you have

```ruby
class UsersController < ApplicationController
  1/0

  def foo; end
end
```

you get an exception. However, the constant and its class get defined, and `UsersController` instances do not respond to `foo`.  If you catch the exception upwards and move on, you _accept_ that scenario is possible. That is how Ruby works.

I believe that `NameError` is not right. If the purpose is not to raise when the missing constant is the controller's, we should check for it in the exception message[*]. Silence if equal, reraise otherwise.

[*] A pity this is not available as an attribute of the exception instance.

**Comment by fxn** [comment]
Correction: The exception has the name in an attribute.
