### ISSUE TITLE
Does `rails test` need improvement?

### ISSUE THREAD

**Issue by shime** [rails/rails#37677]
This is not a bug. I would like to get some feedback about the problems I've experienced with the `rails test` command.

Rails provides these commands for running tests:
* `rails test` for running all non-system tests
* `rails test:system` for running system tests

### 1. no command for running all the tests

Unfortunately, there is currently no command for running all the tests. Currently, I run all the tests on my Rails projects by issuing the following command:

```
rails test:system test
```

The problem with this command is that the order is important. The following will not work:

```
rails test test:system # this does not run the test:system command
```

Would it be a good idea to add another task for running all the tests? Something like:

```
rails test:all # this command would run all the tests
```

### 2. fail fast is not supported when running `test:system`

The error is thrown when I attempt to run system tests with the fail-fast flag that is supported in the `test` task:

```
$ rails test:system -f
rails aborted!
Don't know how to build task 'test:system' (See the list of available tasks with `rails --tasks`)
/Users/hrvoje/code/hack/rails/railties/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/hrvoje/code/hack/rails/railties/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/hrvoje/code/hack/rails/railties/lib/rails/command.rb:47:in `invoke'
/Users/hrvoje/code/hack/rails/railties/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

Would it be a good idea to add support for failing fast to the `test:system` task, or even to the `test:all` task?

## Quick fix 

Here are my changes to enable passing the fail fast flag to the `test:system` task:

```diff
diff --git a/railties/lib/rails/commands/test/test_command.rb b/railties/lib/rails/commands/test/test_command.rb
index 00ea9ac4a6..ed60b630ec 100644
--- a/railties/lib/rails/commands/test/test_command.rb
+++ b/railties/lib/rails/commands/test/test_command.rb
@@ -32,6 +32,13 @@ def perform(*)
         Rails::TestUnit::Runner.parse_options(ARGV)
         Rails::TestUnit::Runner.run(ARGV)
       end
+
+      def system(*)
+        $LOAD_PATH << Rails::Command.root.join("test").to_s
+
+        Rails::TestUnit::Runner.parse_options(ARGV)
+        Rails::TestUnit::Runner.rake_run(["test/system"])
+      end
     end
   end
 end
```

With this, the `rails test:system -f` can be run, but after this change, the command is no longer "chainable". Running the previously used command for all tests will no longer work:

```
rails test:system test # this command now runs only system tests
```

This is probably going to cause problems for people relying on this command for running all the tests.

---

Would you accept a PR that would add `rails test:all` command that would also accept all the flags currently accepted by the `rails test` command?

**Comment by kaspth** [comment]
They're split because of the underlying harness, e.g. that users can see puma boot information when running system tests: https://github.com/rails/rails/pull/28283
They're also split to connote that you'd want to run them separately on CI.

Locally, I for the most part run just test and then less often I run the system tests.

So not keen on adding a `test:all` task.

### 1.

Re: `rails test test:system` versus `rails test:system test`. The former runs the Rails TestCommand which interprets `test:system` as a passed file path, e.g. `rails test test/models/post_test.rb`, but doesn't find any matches and proceeds. The latter ends up running via Rake. We don't really support command chaining with the Rails command infrastructure.

### 2.

From your quick fix it seems that the inter-op between the test:system Rake task and the test command doesn't pass options over, which makes sense. We could support adding `test:system` as a command.

I'm not too keen on adding chaining to our internal command infrastructure, sounds like it could be hairy.

**Comment by ccasabona** [comment]
You can write a rake task to add a rails test:all command.  Having rails test:all available is particularly useful when using [simplecov](https://github.com/colszowka/simplecov). I've been using this rake task successfully for a number of years. I store this file as lib/tasks/test_runners.rb.  It add rails test:lib and rails test:all commands.

```
# frozen_string_literal: true

namespace :test do
  desc 'Run lib tests'
  task lib: 'test:prepare' do
    $: << 'test'
    Rails::TestUnit::Runner.rake_run(['test/lib'])
  end

  desc 'Run services tests'
  task services: 'test:prepare' do
    $: << 'test'
    Rails::TestUnit::Runner.rake_run(['test/services'])
  end

  desc 'Run unit tests'
  task unit: 'test:prepare' do
    $: << 'test'
    Rails::TestUnit::Runner.rake_run(['test/unit'])
  end

  desc 'Run all tests'
  task all: 'test:prepare' do
    $: << 'test'
    Rails::TestUnit::Runner.rake_run(['test/models', 'test/helpers', 'test/mailers', 'test/controllers', 'test/integration', 'test/lib', 'test/services', 'test/system', 'test/unit'])
  end
end
```
This code came about as a result of a similar inquiry.  At the time, I thought Rails should have a test:all command.  Since writing this rake task, however, I have discovered a few caveats to rails test:all.

1. There can be no tests with the same names across all the test directories (duh).
2. In non-system tests, to test unpermitted parameters, you set in config/environments.rb

`config.action_controller.action_on_unpermitted_parameters = :raise `

In system tests, however, if you test unpermitted parameters, you may have to account for all the parameters that the browser submits, such as utf8, anchor, and format, if you are not using the require method in a strong parameters list.  Normally, you would add to test/application_system_test_case.rb 

`ActionController::Parameters.action_on_unpermitted_parameters = :log `

This prevents the system tests from raising an exception when an unpermitted parameter is encountered.  If you do this in the case of rails test:all, however, the unpermitted parameter tests will fail as they will be expecting an unpermitted parameter exception to be raised when they are not being raised.

If you don't test unpermitted parameters, then you won't have this problem.  But it added enough  complication to the test process to conclude that a rails test:all command should not be something that rails offers.  Perhaps documenting this technique would be more to the point.

To answer your second point, I get the same error message when entering any of the category-specific test runners, as in:

```
~/sites/defluris_engine/defluris rails test:models -f
rails aborted!
Don't know how to build task 'test:models' (See the list of available tasks with `rails --tasks`)
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/railties-6.0.1/lib/rails/command.rb:48:in `invoke'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/charlie/.rvm/gems/ruby-2.6.5@ruby26rails6/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
bin/rails:9:in `<main>'
(See full trace by running task with --trace)
```

Rails 6.0.1, Ruby 2.6.5
