### ISSUE TITLE
dispatchEvent submit remote not working on firefox

### ISSUE THREAD

**Issue by nhatdt-1507** [rails/rails#37688]
### Steps to reproduce
Create a form tag with remote: true
Button tag with `onclick: document.querySelector('#form').dispatchEvent(new Event('submit', {bubbles: true}))`
Click button on firefox 69.0.1.
-->

### Expected behavior
Completed 200

### Actual behavior
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 0ms (ActiveRecord: 0.0ms | Allocations: 127)

### System configuration
**Rails version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**Ruby version**: Rails 6.0.0

**Comment by nhatdt-1507** [comment]
FYI
request header on chrome:
```
Accept: text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6,ja;q=0.5,af;q=0.4,vi;q=0.3
Connection: keep-alive
Content-Length: 74
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: _session_id=7cd005827323de8b533deb0d7b017f5b
Host: **
Origin: **
Referer: **
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
X-CSRF-Token: r8qBmfo1PhitQQK0x2K/GH3ktwCNQmJtL2bwNVQz5fQLEmQUHUvAIRjL7wpkwR2Ys1oSUdzK9Ulewuy9IviKLQ==
X-Requested-With: XMLHttpRequest
```
request header on firefox
```
Host: **
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: **
Content-Type: application/x-www-form-urlencoded
Content-Length: 26
Connection: keep-alive
Cookie: _ga=GA1.2.2094925534.1561531911; _session_id=4fc050273cc032723bd4d762d0105b47
Upgrade-Insecure-Requests: 1
```

**Comment by davidchenfn** [comment]
running into this issue now:

The line Rails.fire(this.form(), 'submit') is not working correctly in Firefox. The form isn’t being submitted, however this works in Chrome. It’s because in the Rails.fire options for the dispatchEvent method, cancellable option is set to true. For some reason, this causes the dispatchEvent to not work properly. Setting it to false fixes the issue, however it’s not ideal since the code is in the @rails/ujs package. Some more info in this stackoverflow [link](https://stackoverflow.com/questions/49587933/firefox-doesnt-preventing-dispatched-submit-event).
