### ISSUE TITLE
"Try it now" in listing-existing-routes page

### ISSUE THREAD

**Issue by leomao10** [rails/rails#37715]
Currently Rails provide `rails/info/routes` in dev env, which really nice to have. 

But I am thinking if we can make it better and one of the good example is to allow dev to actually try it in `rails/info/routes` just like the `Try it now` in the swagger doc do allow devs to try it directly in `rails/info/routes` or export it as curl command.

Not sure if it is worth to do it, if so, I am happy to contribute some of my time to work out the prototype for it

**Comment by pixeltrix** [comment]
Hi @leomao10,

Thanks for your interest - personally I feel that adding 'Try it now' to the routes info page would be pretty difficult because whilst we know what the path parameters are for non-GET requests the body of the request is pretty much unknown. Swagger can do it because obviously you're documenting what those parameters are. Also most Rails apps are 'navigable' so it's much easier just to follow the app flow than to make custom requests, whereas Swagger is generally used with APIs which are obviously more suited to this kind of feature.

I'm going to close this issue because we don't use the tracker for feature requests, however if you feel that you still want to try to implement such a feature please open a PR and we'll give it due consideration.
