### ISSUE TITLE
Rails 6: `Associations::Preloader` not working when given a scope

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#37720]
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.0"
  gem "activesupport", "6.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.text :body
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    p1 = Post.create!

    c1 = Comment.create!(post_id: p1.id, body: "hi")
    c2 = Comment.create!(post_id: p1.id, body: "hello")

    scope = Comment.where(body: "hi")
    ActiveRecord::Associations::Preloader.new.preload([p1], :comments, scope)

    assert_equal 1, p1.comments.length
  end
end
```

### Expected behavior
My reading of https://github.com/rails/rails/pull/35496 is that it should impact `through` associations, but that for normal associations preload behaviour should not have changed.

While upgrading to Rails 6 many of our tests are failing because we rely on `AR::Associations::Preloader` working with a custom scope.

The above test case fails on Rails 6 but passes on Rails 5.2.3, I'm reasonably confident that PR is the cause.

### Actual behavior
The tests fail.

Rails 6:

```
D, [2019-11-14T12:54:20.451201 #19944] DEBUG -- :   Comment Load (0.2ms)  SELECT "comments".* FROM "comments" WHERE "comments"."body" = ? AND "comments"."post_id" = ?  [["body", "hi"], ["post_id", 1]]
D, [2019-11-14T12:54:20.457603 #19944] DEBUG -- :   Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ?  [["post_id", 1]]
F

# first query is from preloader; second query is because preloader didn't work

Finished in 0.042385s, 23.5933 runs/s, 47.1865 assertions/s.

  1) Failure:
BugTest#test_association_stuff [bug.rb:74]:
Expected: 1
  Actual: 2
```

Rails 5.2.3:

```
D, [2019-11-14T12:52:06.321279 #19915] DEBUG -- :   Comment Load (0.2ms)  SELECT "comments".* FROM "comments" WHERE "comments"."body" = ? AND "comments"."post_id" = ?  [["body", "hi"], ["post_id", 1]]
. # <-- test passing here; preload query here ^
```

### System configuration
**Rails version**: 6.0.0

**Ruby version**: ruby 2.6.3p62

**Comment by clausti** [comment]
I already left a comment on the earlier issue https://github.com/rails/rails/issues/36638, but I am also running into issues with the lack of a supported way to scope an association for preload. I'm trying to implement the ability for one profile to block another, and as far as I can tell there is no supported way for me to fetch, preloaded, a collection of posts that have the replies associations preloaded with only replies from non-blocked profiles? Very willing to be corrected if this is wrong! 

(Probably goes without saying, but: `Post.includes(:replies).where.not(profile_id: blocked_profile_ids).where.not(replies: {profile_id: blocked_profile_ids})` does not work for this use case because it excludes non-blocked Posts which have any replies from blocked profiles.)

**Comment by talpava** [comment]
Мой друг непереживай мы вместе!!! Мы решим задачу!  Мне задали вопрос про$???? Что это?4:07, 18 ноября 2019 г., Christina Austin <notifications@github.com>:I already left a comment on the earlier issue #36638, but I am also running into issues with the lack of a supported way to scope an association for preload. I'm trying to implement the ability for one profile to block another, and as far as I can tell there is no supported way for me to fetch, preloaded, a collection of posts that have the replies associations preloaded with only replies from non-blocked profiles? Very willing to be corrected if this is wrong!
(Probably goes without saying, but: Post.includes(:replies).where.not(profile_id: blocked_profile_ids).where.not(replies: {profile_id: blocked_profile_ids}) does not work for this use case because it excludes non-blocked Posts which have any replies from blocked profiles.)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://yandex

**Comment by talpava** [comment]
У меня 7!!!! Стабильно работающих способов прошедших все проверки я есьм тор ))))4:25, 18 ноября 2019 г., "дмитри1" <notifications@github.com>:Мой друг непереживай мы вместе!!! Мы решим задачу!  Мне задали вопрос про$???? Что это?4:07, 18 ноября 2019 г., Christina Austin <notifications@github.com>:I already left a comment on the earlier issue #36638, but I am also running into issues with the lack of a supported way to scope an association for preload. I'm trying to implement the ability for one profile to block another, and as far as I can tell there is no supported way for me to fetch, preloaded, a collection of posts that have the replies associations preloaded with only replies from non-blocked profiles? Very willing to be corrected if this is wrong!

(Probably goes without saying, but: Post.includes(:replies).where.not(profile_id: blocked_profile_ids).where.not(replies: {profile_id: blocked_profile_ids}) does not work for this use case because it excludes non-blocked Posts which have any replies from blocked profiles.)



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Отправлено из мобильной Яндекс.Почты: http://yandex

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://yandex

**Comment by talpava** [comment]
Они все попроходяит "сс" но с"отрудники тор" банят их ...... я обычно жду до 5 мин на тойэе странице.  И ))) она сама начинает работарь а у вас у всех отчёт о проблеме! А проблемы то нет!!! Уникальный код! Работает!!! Я думаю стою своих денег ) и твоей дружбы 4:29, 18 ноября 2019 г., "дмитри1" <notifications@github.com>:У меня 7!!!! Стабильно работающих способов прошедших все проверки я есьм тор ))))4:25, 18 ноября 2019 г., "дмитри1" <notifications@github.com>:Мой друг непереживай мы вместе!!! Мы решим задачу!  Мне задали вопрос про$???? Что это?4:07, 18 ноября 2019 г., Christina Austin <notifications@github.com>:I already left a comment on the earlier issue #36638, but I am also running into issues with the lack of a supported way to scope an association for preload. I'm trying to implement the ability for one profile to block another, and as far as I can tell there is no supported way for me to fetch, preloaded, a collection of posts that have the replies associations preloaded with only replies from non-blocked profiles? Very willing to be corrected if this is wrong!



(Probably goes without saying, but: Post.includes(:replies).where.not(profile_id: blocked_profile_ids).where.not(replies: {profile_id: blocked_profile_ids}) does not work for this use case because it excludes non-blocked Posts which have any replies from blocked profiles.)







—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.



Отправлено из мобильной Яндекс.Почты: http://yandex



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Отправлено из мобильной Яндекс.Почты: http://yandex

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://yandex

**Comment by talpava** [comment]
Можно даже располовинить малый код и отправить как два ))) и то работает4:29, 18 ноября 2019 г., "дмитри1" <notifications@github.com>:У меня 7!!!! Стабильно работающих способов прошедших все проверки я есьм тор ))))4:25, 18 ноября 2019 г., "дмитри1" <notifications@github.com>:Мой друг непереживай мы вместе!!! Мы решим задачу!  Мне задали вопрос про$???? Что это?4:07, 18 ноября 2019 г., Christina Austin <notifications@github.com>:I already left a comment on the earlier issue #36638, but I am also running into issues with the lack of a supported way to scope an association for preload. I'm trying to implement the ability for one profile to block another, and as far as I can tell there is no supported way for me to fetch, preloaded, a collection of posts that have the replies associations preloaded with only replies from non-blocked profiles? Very willing to be corrected if this is wrong!



(Probably goes without saying, but: Post.includes(:replies).where.not(profile_id: blocked_profile_ids).where.not(replies: {profile_id: blocked_profile_ids}) does not work for this use case because it excludes non-blocked Posts which have any replies from blocked profiles.)







—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.



Отправлено из мобильной Яндекс.Почты: http://yandex



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Отправлено из мобильной Яндекс.Почты: http://yandex

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://yandex

**Comment by rafaelfranca** [comment]
@kamipo can you take a look on this issue please?
