### ISSUE TITLE
How to setup ActionMailer in rails api mode

### ISSUE THREAD

**Issue by RiddhiKcj** [rails/rails#37825]
### System configuration
**Rails version**:

**Ruby version**:

**Comment by eileencodes** [comment]
Hey @RiddhiKcj, we need more information in order to help you. This seems like a how-to question and we generally don't accept "how to use Rails / Rails library" questions on the issues tracker. We reserve this just for issues with the framework and gems. Please use stack overflow for how to questions. Thanks!
