### ISSUE TITLE
Active Storage can't transform animated gifs

### ISSUE THREAD

**Issue by pixeltrix** [rails/rails#37833]
ImageMagick is able to resize animated gifs by first using `-coalesce`, resizing and then using `-deconstruct`. However the Active Storage transform ercode only ever loads the first frame of the animation because it hard codes `loader(page: 0)` in the chain and it doesn't appear that the image_processing gem can override that when applying options.

I guess it's probably to do with creating previews of multi-page PDFs but seems like we should allow resizing animated GIFs even if it's an opt-in process.

cc @georgeclaghorn @janko

**Comment by janko** [comment]
You should be able to cancel the `loader(page: 0)` by setting `:page` to `nil` when generating the variant:

```rb
user.avatar.variant(loader: { page: nil })
```

**Comment by janko** [comment]
The reason for `loader(page: 0)` being the default was compatibility with the MiniMagick transformer, because `MiniMagick::Image#format` sets `page: 0` by default. However, prior to that, you could still execute resizing GIFs normally with MiniMagick transformer, because formatting would be executed only after other operations.

The same behaviour (not using any page on normal operations, using `page: 0` for formatting) isn't really possible with `ImageProcessing::MiniMagick`, as there everything is done in a single ImageMagick command. Unless you separate it out, so that instead of:

```rb
processor.
  source(file).
  loader(page: 0).
  convert(format).
  apply(operations).
  call
```

you do

```rb
transformed =  processor.
  source(file).
  apply(operations).
  call

processor.
  source(transformed)
  loader(page: 0).
  convert(format).
  call
```

However, that's probably going to be generally slower than having it all in one command.

**Comment by pixeltrix** [comment]
@janko thanks for the quick response - can confirm that `loader: { page: nil }` works (I'd tried just an empty hash thinking that nil might blow up).

Since it still works in a single command I think maybe just a well-named macro in the image_processing gem that resets the page option would be fine, e.g:

``` ruby
file.preview(resize_to_fit: [128, 128], animation: true)
```

Could be any appropriate name - haven't checked for clashes with ImageMagick's many options.

**Comment by miharekar** [comment]
I'm sorry to reopen this, but I've been struggling so maybe you can help me out. If I set
`config.active_storage.variant_processor = :mini_magick` the `loader: { page: nil }` trick does indeed work, but I can't get resized animated gif to work with vips, which is now the default.

I've been looking through `image_processing` and `activestorage` source code, but I lack sufficient knowledge to figure out what I should do. No matter what I try, the resized gif that comes from variant does not animate.

@janko could you help me out? 😅

**Comment by porterbayne** [comment]
Same -- I'm on Rails 7 with VIPS, and embedded animated GIFs render correctly in the Trix editor, but not in the output.
