### ISSUE TITLE
Migration generator adds `null: false` to add_reference in Rails 6

### ISSUE THREAD

**Issue by CarlosCD** [rails/rails#37858]
### Steps to reproduce

When generating a new migration adding a `references` column, for example:

    rails g migration AddColumnsToTable name user:references

### Expected behavior

It should generate a migration including a statement of the kind:

    add_reference :tables, :user, foreign_key: true

### Actual behavior

It generates this statement:

    add_reference :tables, :user, null: false, foreign_key: true

There are two problems with the `null: false` option:
1. It doesn't consider that the `belongs_to` association could be optional.
2. If there are already records in the database, running the migration will generate an Exception, as there is not a default value (in PostgreSQL, `PG::NotNullViolation: ERROR:  column "user_id" contains null values`).

This happens in Rails 6.0.1 (ActiveRecord::Migration[6.0]), but it was not the case in Rails 5.2.3.

### System configuration

**Rails version**: 6.0.1
**Ruby version**: 2.6.2p47

**Comment by CarlosCD** [comment]
I hope this is not me being too sleepy this morning... but if it is correct, I don't believe this is an urgent issue, just something a bit unexpected.

If I were more familiar with the codebase, I would suggest a fix.

Thanks!

**Comment by louim** [comment]
Hey!

The `null: false` was added in https://github.com/rails/rails/pull/36001. In Rails, `belongs_to` are required by default since https://github.com/rails/rails/pull/18937, so it make sense to have the foreign_key match the behavior. The generator will still respect the `Rails.application.config.active_record.belongs_to_required_by_default` config if you want to keep the `belongs_to` optional in your app.

If you want to have only one `belongs_to` optional, you could always edit the migration before running it. As for existing data, this should not be a problem, because `add_reference` create a new column, so there shouldn't be any integrity problems with existing data.

**Comment by CarlosCD** [comment]
Hi Louis-Michel,

Thank so much you for pointing out the origin, the rationale and the discussion. It is very helpful.

In most cases, most associations, I do want the association required by default, so I follow the usual convention. And in my use case, I did edit the migration. It is not really a problem at all for me, but it did surprise me a bit.

The question is when you have two existing tables with data (records), and you want to create an optional association (the "Add Columns To Table" generator). If null is not allowed by the constraint, and no other default value is offered, the database would not have a way to decide. That is the reason, at least in PostgreSQL you'd run into an Exception.

So it is not an integrity problem with existing data, but with the default value used in the new (user_id) column. If you know for sure that you had, for example and user with `id: 1`, you could do something like this, to set all existing records to belong to that user by default:

    add_reference :tables, :user, null: false, default: 1, foreign_key: true

And the foreign key constraint would prevent you from removing that user's record.

I understand that in many cases you do know the associations you want to build before any data is added to the tables, so this won't be a problem... In my case new requirements were added after the fact.

Still, this is a just a matter of choice, and I am ok with the decision if the general sentiment is that it is not important.

**Comment by eileencodes** [comment]
This is behavior is intentional so I'm going to close this. 😄

**Comment by stiller** [comment]
Out of the box, this will not work with SQLite3, as it will produce `Cannot add a NOT NULL column with default value NULL`.

Steps to reproduce:

```
rails new ./poc
rails g model dog
rails g model owner
rails g migration AddOwnerToDog owner:references
rails db:migrate
```

**Comment by asfarley** [comment]
Hi Rails folks, I have to say, this feels like there is a bug somewhere but I suppose it's a matter of perspective. 

Considering this discussion:
[how-to-solve-cannot-add-a-not-null-column-with-default-value-null-in-sqlite3](https://stackoverflow.com/questions/3170634/how-to-solve-cannot-add-a-not-null-column-with-default-value-null-in-sqlite3)

and this discussion:
[how-to-add-reference-column-migration-in-rails-6-with-sqlite](https://stackoverflow.com/questions/60080860/how-to-add-reference-column-migration-in-rails-6-with-sqlite)

and @stiller's comment above, and my own experience, this behavior is surprising. It feels like we're using a hack to work around well-understood SQLite behavior because it behaves differently than other databases. 

This feels ugly, doesn't it? My understanding is that using Rails in development mode shouldn't feel different enough from production that we're having to hand-edit migrations or specify less-safe default values just to run a reference-column migration. 

Isn't ActiveRecord trying to provide a consistent interface to whatever database we choose? I understand that abstractions aren't perfect, but I wonder if we could identify which part in the chain is most responsible for breaking this abstraction. 

@eileencodes's comment that this is intended behavior (re: all other databases) makes sense, but is this intended/expected for SQlite, especially when no rows already exist? 

I understand it's a logical conflict to add null values to pre-existing rows, but there is no logical conflict with an empty SQlite table. 

It seems like the simple solution would be either:
 * Modify ActiveRecord to account for this type of migration when running on SQLite, or
 * Modify SQlite to allow the addition of columns to tables 

Do you believe either of these suggestions are reasonable? Would you have a preference?

**Comment by ClayShentrup** [comment]
Deeply unfortunate.

https://medium.com/extreme-programming/skipping-association-validations-in-tests-2f1cd301bee4

**Comment by paddy-hack** [comment]
I arrived here after a good deal of searching and head scratching.  After a fair amount of experimenting I finally arrived at a migration like the one below.

``` ruby
class AddUserToPosts < ActiveRecord::Migration[8.0]
  def up
    add_reference :posts, :user, foreign_key: true
    ghost = User.find_or_create_by!(name: I18n.t("db.migration.user.ghost"))
    Post.update_all user_id: ghost.id
    change_column :posts, :user_id, :integer, null: false
  end

  def down
    remove_reference :posts, :user
    User.find_by(name: I18n.t("db.migration.user.ghost"))&.destroy!
  end
end
```

Compared to @CarlosCD's suggestion, this has the advantage that no `default: 1, ` ends up in `db/schema.rb`.  Such a default may become problematic when the user with that id has been removed (together with all of the user's posts).

The `I18n.t()` bit is of course completely optional.  I just happen to be working on something that has to be internationalized and went overboard 😆

Disclaimer: Only tested with SQLite3!
