### ISSUE TITLE
Saving with touch set to false updates parent updated_at field, is this the expected behavior?

### ISSUE THREAD

**Issue by lmumar** [rails/rails#37933]
### Steps to reproduce
```
begin require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "http://rubygems.org"
  gem "activerecord", "6.0.0"
  gem 'sqlite3'
  gem "pry"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)


ActiveRecord::Schema.define do

  create_table "posts", force: :cascade do |t|
    t.text "text"
    t.timestamps
  end

  create_table "comments", force: :cascade do |t|
    t.belongs_to :post
    t.text "text"
    t.timestamps
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, touch: true
end

class BugTest < Minitest::Test
  def test_save_touch_false_with_belongs_to_association
    post = Post.create!
    comment = post.comments.create!

    post_timestamp_before_updated = post.updated_at
    comment_timestamp_before_updated = comment.updated_at

    comment.text = 'foo'
    comment.save(touch: false)

    post.reload
    comment.reload

    assert_equal comment_timestamp_before_updated, comment.updated_at
    assert_equal post_timestamp_before_updated, post.updated_at
  end
end
```

### Expected behavior

parent (Post) `updated_at` field should not be updated.

### Actual behavior

parent (Post) `updated_at` field gets updated.

### System configuration

**Rails version**;
Rails 6.0.0

**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by abhaynikam** [comment]
@lmumar : I think this is expected behavior. I spent some time debugging the code and following are my findings.

In the documentation, it is clearly stated that `save` or `save!` sets the `update_at/on` of the record. By passing options `save(touch: true)` the timestamp attributes do not get updated. 
Refer the documentation: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/persistence.rb#L458-L460

Here is the test cases to assert the same change: https://github.com/rails/rails/blob/master/activerecord/test/cases/persistence_test.rb#L1064-L1077

When association `belongs_to` is passed `touch: true` option, it adds the callback no matter what is passed to the `save`. Ref: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/builder/belongs_to.rb#L22

**Comment by lmumar** [comment]
@abhaynikam but isn't it logical that if you specify `touch: false` when you save it should propagate that option to the associated objects?

**Comment by abhaynikam** [comment]
Yep. I had the same expectation but the intend of `touch: false` is never to stop the model callback. If you run the reproduction script you would notice that Comment.updated_at is not touched when `touch` is set to false.

I think current documentation is fine but if needed we can add the warning in it. 

```
UPDATE "comments" SET "text" = ? WHERE "comments"."id" = ?  [["text", "foo"], ["id", 1]]
```

**Comment by lmumar** [comment]
@abhaynikam thanks, will be closing this ticket as this an expected behavior.

**Comment by Swastikyadav** [comment]
Although this issue is closed. I want to add something here.

@lmumar you have used `touch: true` in the Comment model.
```
class Comment < ActiveRecord::Base
  belongs_to :post, touch: true
end
```

I think if you remove `touch: true` from there, then the post's updated_at will not get updated when saving the comment.

`touch: false` used while saving the comment will not update the updated_at of the comment. But Post's updated_at will get updated due to the above case.

Thank You!
