### ISSUE TITLE
Rails guides on STI lack section about routing

### ISSUE THREAD

**Issue by hadmut** [rails/rails#37980]
Hi,
I just ran into the problem that the rails tests failed on my rails app using Single Table Inheritance. The controller scaffolded for the base class contains something like 

  def update
    respond_to do |format|
      if @platform_web_storage.update(platform_web_storage_params)
        format.html { redirect_to @platform_web_storage, notice: 'Web storage was successfully updated.' }
  ...

which fails at redirect_to since the subclass consists just of a model and does not have any routes, while redirect_to tries to convert the class name to a url function (which does not exist) and throws

NoMethodError: undefined method `platform_web_storage_local_url'

I've found discussions in the web about this problem, but most from 2011 or 2012 dealing with rails 3 or 4. I did not find a clean and consistent way to solve this routing problem. 

The guide about STI 

https://guides.rubyonrails.org/association_basics.html#single-table-inheritance

should contain a section about how to have this working, since STI models without proper routing break rails' functionality.

**Comment by stuyam** [comment]
I guess part of the question is what is the preferred way to do this. In this post [stackoverflow](https://stackoverflow.com/a/41408686/1231563) they use something like this `@list.becomes(List)` to recast it into the parent STI object. 

I wonder if you could do something like `.sti_base_route` that was more explicit and tested way of doing something like that. That is tricky because that wouldn't actually return a route but an ar object so may be misleading.

**Comment by hadmut** [comment]
Well, my solution was to simply add an url directive, this turning it into

format.html { redirect_to platform_web_storage_path(@platform_web_storage), notice: 'Web storage was successfully updated.' }

thus enforcing a particular URL instead of letting rails find it (and fail to do so). It solves the problem for the moment. 


However, this has a typical „workaround” flavour. 

I'm looking for a clean, future-compatible, rails-ish way to do it. And it should be documented.
