### ISSUE TITLE
'rails new project' command returns error code 1 even if successful as of 6.0.2

### ISSUE THREAD

**Issue by geerlingguy** [rails/rails#38100]
### Steps to reproduce

  1. `gem install rails`
  2. `rails new demo`

### Expected behavior

The command should generate a new rails project and exit with status code `0`.

### Actual behavior

The command generates a new rails project with no error output, but exits with status code `1`.

### System configuration

**Rails version**: `Rails 6.0.2.1`

**Ruby version**: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]`

### Additional Information

See related (closed issue before I could confirm a fix worked in my CI environments): #38001

Full log, running inside an Ubuntu 18.04 server as root:

```
root@instance:/# ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
root@instance:/# rails -v
Rails 6.0.2.1
root@instance:/# rails new demo
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
root@instance:/# echo $?
1
```

**Comment by geerlingguy** [comment]
Full steps to reproduce (just need Docker):

```
$ docker run -it geerlingguy/docker-ubuntu1804-ansible /bin/bash

# apt-get update && apt-get install -y ruby zlib1g-dev libsqlite3-dev ruby-dev tzdata build-essential apt-transport-https
# gem install rails
# rails new demo
# echo $?
1
```

**Comment by eugeneius** [comment]
This looks like a duplicate of https://github.com/rails/rails/issues/38035: `run  git init from "."` shouldn't be the last line of output from the app generator. Rather than succeeding and returning an error status, it's failing silently.

Until https://github.com/rails/rails/issues/38035 is fixed, you can either install git or pass the `--skip-git` option. Based on https://github.com/rails/rails/issues/38001#issuecomment-568961631, you may also want to look at the `--skip-javascript` option to avoid the need to install yarn and fetch a bunch of Node modules your CI script most likely doesn't need.

**Comment by geerlingguy** [comment]
Ah, I see. Yeah, I don't need git or JS for these CI runs. The fix, then, is to switch my command from:

```
rails new demo
```

To:

```
rails new demo --skip-git --skip-javascript
```

(Alternatively, I could install both Git (`apt-get install -y git`) and Yarn (`npm install yarn`).) The command now exits with `1` after a few minutes.

This is definitely a duplicate of #38035, closing it and marking as such. Thanks for the help!
