### ISSUE TITLE
Please make it clear whether Rails.ajax is for internal use only

### ISSUE THREAD

**Issue by jhackett1** [rails/rails#38191]
I'm experimenting with some custom ajax functionality in a Rails 5 project.

I've been struggling and struggling to post some data to the server using `Rails.ajax`, and after reading guide after guide, I eventually understood where I was going wrong from a two-year old [Github issue comment](https://github.com/rails/rails/issues/31507#issuecomment-354680347).

Lots of recent third party guides talk about `Rails.ajax` and recommend using it now that `jquery` isn't included by default any more ([for instance](https://www.rubyguides.com/2019/03/rails-ajax/)). If this isn't recommended, to save others the hassle I just went through, I would really appreciate a note in [these docs](https://guides.rubyonrails.org/working_with_javascript_in_rails.html)?

**Comment by evanschris** [comment]
+1

**Comment by ccasabona** [comment]
Rails may have dropped jQuery by default but rails-ujs is not a substitute.  We use bootstrap and this requires jQuery, so we didn't see much use for Rails.ajax calls until we implemented Content Security Policy (csp).  Then the js.erb templates stopped executing because we were using a csp nonce and the nonce was not being passed to the script tag that rails generates around the js.erb code.  We ended up eliminating several js.erb templates and using the success function of a jquery ajax call to write any results to the views.  But some of our js.erb templates too complex to easily translate into javascript.  We were stuck until rails.ajax got the ability to pass the the csp nonce to the resulting js.erb template so the browser will execute the script.  

Rails.ajax calls come at a price, however, if you are passing any JSON objects as data to the controller method.  Jquery.ajax calls parameterize this data; a rails.ajax call does not.  Since we are using jQuery, we can pass the data to its .param() function. 

```
toURLEncoded = function(element) {
  return $.param(element);
};
```
 If you are not using jQuery in your project, this can be done with javascript as in:

```
toURLEncoded = function(element) {
  var key, list;
  list = [];
  if ('object' === typeof element) {
    for (key in element) {
      key = key;
      if (element.hasOwnProperty(key)) {
        list.push(key + '=' + encodeURIComponent(element[key]));
      }
    }
  }
  return list.join('&');
};
```
Our rails.ajax calls look like this:

```
Rails.ajax({
  type: 'post',
  url: '/controller/do_something.js',
  data: toURLEncoded({
    id: 'a parameter',
    catalog: 'some other parameter'
  }),
  dataType: 'script'
});

```
Any javascript in the template do_something.js.erb will execute.

This may not apply to your problem, but this is the only use we have found for using Rails.ajax.  It has been a while since we looked at any changes in rails-ujs, but this method works as described through rails 6.1 alpha.

**Comment by gmcgibbon** [comment]
I think this also partially stems from [the documentation](https://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html) being severely outdated. It is safe to say that CoffeeScript and jQuery aren't encouraged anymore. I'll see about rewriting the guide to use fetch, es6, and specifically mention our stance on not using rails-ujs.

**Comment by rhumaric** [comment]
Just came across this issue and this last comment. Does that mean that Rails is going to encourage people to move away from rails-ujs altogether? Or would it be just the `.js.erb` approach to it (as opposed to JSON/HTML payloads with event handlers in the JS to handle the updates of the page).

**Comment by p8** [comment]
@gmcgibbon There already was an effort to change the documentation in #37529.

**Comment by gmcgibbon** [comment]
@rhumaric 

> Does that mean that Rails is going to encourage people to move away from rails-ujs altogether? 

Yes, I think the popular opinion is that we want to encourage people to use more standardized APIs (eg. fetch). You can still use rails-ujs, but I don't think we hold any guarantees in terms of API contracts.

@p8 

Thanks, I'll try to push that one forward!

**Comment by silva96** [comment]
They are using a new class in hey.com that wraps around fetch api

```js
import { Response } from "./response"
import { getCookie } from "lib/cookie"

window.breakAllFetchRequestsForTests = false

export class Request {
  constructor(method, url, options = {}) {
    this.method = method
    this.url = window.breakAllFetchRequestsForTests ? "about:blank" : url
    this.options = options
  }

  async perform() {
    const response = new Response(await fetch(this.url, this.fetchOptions))
    if (response.unauthenticated && response.authenticationURL) {
      return Promise.reject(window.location.href = response.authenticationURL)
    } else {
      return response
    }
  }

  get fetchOptions() {
    return {
      method:      this.method,
      headers:     this.headers,
      body:        this.body,
      signal:      this.signal,
      credentials: "same-origin",
      redirect:    "follow"
    }
  }

  get headers() {
    return compact({
      "X-Requested-With": "XMLHttpRequest",
      "X-CSRF-Token":     this.csrfToken,
      "Content-Type":     this.contentType,
      "Accept":           this.accept
    })
  }

  get csrfToken() {
    const csrfParam = document.head.querySelector("meta[name=csrf-param]")?.content
    return csrfParam ? getCookie(csrfParam) : undefined
  }

  get contentType() {
    if (this.options.contentType) {
      return this.options.contentType
    } else if (this.body == null || this.body instanceof FormData) {
      return undefined
    } else if (this.body instanceof File) {
      return this.body.type
    } else {
      return "application/octet-stream"
    }
  }

  get accept() {
    switch (this.responseKind) {
      case "html":
        return "text/html, application/xhtml+xml"
      case "json":
        return "application/json"
      default:
        return "*/*"
    }
  }

  get body() {
    return this.options.body
  }

  get responseKind() {
    return this.options.responseKind || "html"
  }

  get signal() {
    return this.options.signal
  }
}

function compact(object) {
  const result = {}
  for (const key in object) {
    const value = object[key]
    if (value !== undefined) {
      result[key] = value
    }
  }
  return result
}
```
