### ISSUE TITLE
Ignored inflections in classify

### ISSUE THREAD

**Issue by cd-rum** [rails/rails#38289]
### Steps to reproduce
Given this inflection and this code:
```
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.uncountable 'canvas', 'canvas'
end

"authorise_canvas".classify
```

### Expected behavior
I'd expect `AuthoriseCanvas` to be the response.

### Actual behavior
I get `AuthoriseCanva`.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.5

**Comment by anujmiddha** [comment]
While this is debatable, I believe this is the expected behavior. The documentation for `uncountable` says "Specifies words that are uncountable and should not be inflected.", and "authorize_canvas" and "canvas" are not considered as the same words.

Uncountables expect either regex or complete words to be added. If you check the code here,

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/methods.rb#L391

the `apply_inflections` method checks for uncountables as

```
inflections(locale).uncountables.uncountable?(result)
```

which in turn matches against regex patterns.

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/inflections.rb#L53

```
@regex_array.any? { |regex| regex.match? str }
```

Since you specified a specific word as uncountable, "AuthorizeCanvas" doesn't match the uncountable and hence is changed.

You can also verify this by checking against the inbuilt uncountables, e.g. jeans

"authorize_jeans".classify returns "AuthorizeJean"

**Comment by cd-rum** [comment]
This is all fair, but I guess it turns on what uncountable means case by case, but if it's uncountable then the `s` in `Canvas` shouldn't be removed, right? Like if it was a different word like an acronym like `EXS` you surely wouldn't expect `AuthorizeEX` as a result, right?

Maybe I'm just using the wrong inflection, but if `jeans` was uncountable (like it is irl) I'd expect `AuthorizeJeans` as the result.

**Comment by anujmiddha** [comment]
I agree with you, having uncountables work similar to other words would feel more natural.

If `"Canvas".singularize` produces "Canvas", then `"AuthorizeCanvas".singularize` should ideally produce "AuthorizeCanvas".

**Comment by cd-rum** [comment]
I'm happy to submit a PR unless there are any other concerns.

**Comment by rafaelfranca** [comment]
There are other concerns. This means that applications that were expecting `"AuthorizeCanvas".singularize` to not produce `"AuthorizeCanvas"` will now start to break. Because of that we are not going to change the inflector behavior for this case.
