### ISSUE TITLE
Description of sprockets use in the "asset pipeline" guide is out of date

### ISSUE THREAD

**Issue by digitalronin** [rails/rails#38307]
### Steps to reproduce

Visit 

  * https://guides.rubyonrails.org/asset_pipeline.html 
  * https://edgeguides.rubyonrails.org/asset_pipeline.html, or view
  * https://github.com/rails/rails/blob/master/guides/source/asset_pipeline.md

The first section "1 What is the Asset Pipeline?" describes a require statement for sprockets in config/application.rb  But the only reference to sprockets I can find in a freshly-created, default rails 6 application is in the Gemfile.lock

### Expected behavior

I think this section of the guide needs to be updated to describe what happens in rails 6.

### Actual behavior

The guide describes "sprockets" settings in config/application.rb which are not there.

### System configuration
**Rails version**: 6

**Ruby version**: 2.7

**Comment by rmacklin** [comment]
I assume you're referring to this:
https://github.com/rails/rails/blob/aeac447b0ca750294fc0556bd0b9842ecce5ad0f/guides/source/asset_pipeline.md#L43-L53

This is talking about what happens when you run `rails new --skip-sprockets` to generate a new app without sprockets. If you instead run `rails new` with no options, the generated `config/application.rb` will only have `require 'rails/all'`, which is a shorthand for requiring all of the individual rails components (including `sprockets/railtie`):
https://github.com/rails/rails/blob/aeac447b0ca750294fc0556bd0b9842ecce5ad0f/railties/lib/rails/all.rb#L5-L24

You can see the logic for the generated `config/application.rb` here:
https://github.com/rails/rails/blob/aeac447b0ca750294fc0556bd0b9842ecce5ad0f/railties/lib/rails/generators/rails/app/templates/config/application.rb.tt#L3-L20

With all that said, the guide seems okay to me. If there's still something that looks wrong to you, leave a reply and I'll take another look.

**Comment by digitalronin** [comment]
That makes sense. I hadn't noticed the `rails/all` part. 

Thank you for looking into this.
