### ISSUE TITLE
Hi how to compress the html.erb file by removing white spaces 

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [rails/rails#38377]
### Steps to reproduce
Hi how to remove comments and white spaces in html.erb files while deploying to prod
Please help 
Thanks in advance
### System configuration
**Rails version**:
6.0.0
**Ruby version**:
2.6.1

**Comment by dmitry** [comment]
If you are going to do that for the production, I suggest to use HTTP server level (one of the solutions: https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source) compression/truncation. Another solution is to use SLIM/HAML HTML processors, as they are not adding whitespaces in the output as ERB does.

**Comment by olliebennett** [comment]
I agree this is probably better suited to a post-processing step (after Rails has generated the output) when you need to remove all whitespace. If you're doing this to optimize the size of the response, make sure you use gzip as that will have a bigger effect.

If your requirement is to remove whitespace in specific sections of your views only, you could try;

- Replacing HTML comments with ERB comments ...

    ```erb
    <!-- html comment (appears in generated HTML) -->
    <%# erb comment (does not appear in HTML) %>
    ```

- For tweaking whitespace in specific areas of the template, you may also be interested in ERB's `<%= @username -%>` syntax which (due to the `-`) avoids trailing whitespace when rendering. See [ActionView::Base docs](https://api.rubyonrails.org/classes/ActionView/Base.html).

**Comment by tenderlove** [comment]
Hi, I don't think this is a bug in Rails so I'm going to close it.  Thanks!
