### ISSUE TITLE
Autoloading of module scoped concerns not supported by default?

### ISSUE THREAD

**Issue by fanktom** [rails/rails#38455]
Hey there,

I have a module inside the `app/models` folder, e.g. `app/models/foo` that implements a `Foo` module. Now I want to add a concern that is only relevant in the module, say `Foo::Snoozable`.

Based on the structure of `app/models/concerns` I created an `app/models/foo/concerns` folder with the `app/models/foo/concerns/snoozable.rb` file and module.

When in the `app/models/foo/concerns` folder, `Foo::Snoozable` is not autoloaded, when I move it directly into `app/models/foo` it is autoloaded.

Based on https://github.com/rails/rails/blob/758e4f8406e680a6cbf21b170749202c537a2576/railties/lib/rails/engine/configuration.rb#L43, I would have assumed that all concerns inside the `app` folder are autoloaded, which does not seem to be the case.

I also tried to add the autoload path in the `application.rb` using:
```
config.autoload_paths << "#{Rails.root}/app/**/concerns"
```
which unfortunately did not work.

I assume Zeitwerk expects the module inside my `concerns` folder the be of module `Foo::Concerns::Snoozable` to load properly.

Is this expected behavior and how do you suggest to structure module level concerns?

Thanks for any help!

Rails 6.0.2.1 (API mode)
Ruby 2.6.5p114

**Comment by fxn** [comment]
Yes, intermediate folders that do not represent namespaces are not possible. That has been always the case, it is not new with Zeitwerk.

I'll tell you even more. When `app/models/concerns` and friends were introduced, it was an overlook to have them added to the autoload paths. Files below those folders could match two different constant paths! **If Zeitwerk was designed without the existence of this use case, nested root directories would not have been supported**. But since they had been in Rails for a long time, support was written. The only improvement is that Zeitwerk makes the resolution deterministic, removing the ambiguity, as explained in the [upgrading guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#concerns) (also, check [Zeitwerk docs](https://github.com/fxn/zeitwerk#nested-root-directories)).

In Rails applications, the project tree has to match class an module names, you cannot have "holes". Concerns are regular modules that people store in their normal places. Oftentimes that involves a extra folder. For example, if you break the implementation of `Hotel` in a bunch of modules, you put them in the `hotel` folder, under the `Hotel` namespace:

```ruby
# app/models/hotel.rb
class Hotel < ApplicationRecord
  include Hotel::Pricing
end
```

```ruby
# app/models/hotel/pricing.rb
class Hotel::Pricing
end
```

**Comment by fanktom** [comment]
Thanks a lot for the detailed clarification! 

So that means its totally fine to have a `Foo::Event` in `models/foo/event.rb` that includes a `Foo::Snoozable` from `models/foo/snoozable.rb` and the top level `models/concerns` folder is basically there to enable backward compatibility.

**Comment by fxn** [comment]
Absolutely, the organization you said for `Foo` is idiomatic.

The folder `app/models/concerns` is meant to contain mixins that are used by several models.

**Comment by fanktom** [comment]
Thanks, very helpful information!
