### ISSUE TITLE
Routes with wildcards are ignoring constraints

### ISSUE THREAD

**Issue by bethcodes** [rails/rails#38521]
### Steps to reproduce
Establish any route with a wildcard and add a constraint: the constraint will be treated as though it always passes.  I have a repo here with an rspec case that demonstrates the problem:
https://github.com/bethcodes/rails_error

### Expected behavior
Constraints should be applied to all routes

### Actual behavior
Constraints are applied to routes without wildcards, but ignored in the case of routes with wildcards.

### System configuration
**Rails version**:
6.0.2.1
**Ruby version**:
ruby 2.7.0p0

**Comment by evgeniy-r** [comment]
Hello!

In your example in [routes.rb](https://github.com/bethcodes/rails_error/blob/master/config/routes.rb):
```
get '*will/work/', to: 'application#default', constraints: ->() {true}
get '*will/not/work', to: 'application#default', constraints: ->() {false}
```

It looks like the second route ("*will/not") will never be matched due to the first one. You can see this output in the console, if you run your example:
```
Started GET "/will/not/work" for 127.0.0.1 at ................
Processing by ApplicationController#default as HTML
  Parameters: {"will"=>"will/not"}
```

There are examples of how wildcards are working in [guides](https://guides.rubyonrails.org/routing.html#route-globbing-and-wildcard-segments).

If you remove the first route ("*will/work"), the constraint in the second one will work.

**Comment by jonathanhefner** [comment]
Thank you for the issue, but I believe @evgeniy-r is correct.  (Thank you too @evgeniy-r for the thorough explanation!)

Another way to confirm this is to change your first wildcard route from `*will/work/` to `*will/werk/`, and change the corresponding spec to `get '/should/werk'`.

Additionally, I wanted to clarify that the last spec (`get '/'`) fails because Rails automatically maps `/` to `public/index.html` if it exists.  If you delete or rename `public/index.html` and change your controller render to e.g. `render plain: "hello"`, this last spec should pass.
