### ISSUE TITLE
update_all sometimes silently removes Arel criteria

### ISSUE THREAD

**Issue by jjb** [rails/rails#38537]
update_all sometimes ignores criteria defined by Arel.

Of course ideally it would be great if it could use any relation. But maybe shorter term, it would be good if it detected it's being invoked on criteria that it can't handle, and blow up instead of... silently updating all rows in the table 😭 

possibly/probably related to #37140

I put this together the best I could based on my own code, let me know if it's necessary for me to create a standalone recreation app.

rails 5.2.4.1

```ruby
class User
  def things_involved_in
    base_query = Thing.unscope
    owns_as_invitee = base_query.where(other_party_id: id)
    owns_as_creator = base_query.where(user_id: id)
    owns = owns_as_invitee.union(owns_as_creator)
    things_table = Thing.arel_table
    Thing.from(things_table.create_table_alias(owns, :things))
  end
end
```

`user.things`

```sql
SELECT "appointments".*
FROM
  (SELECT "appointments".*
   FROM "appointments"
   WHERE "appointments"."other_party_id" = $1
   UNION SELECT "appointments".*
   FROM "appointments"
   WHERE "appointments"."user_id" = $2) "appointments"
ORDER BY "appointments"."date" ASC [["other_party_id", 1], ["user_id", 1]]
```

`user.things.update_all foo: true`

```sql
UPDATE "appointments"
SET "foo" = TRUE
WHERE "appointments"."id" IN
    (SELECT "appointments"."id"
     FROM "appointments")
```

**Comment by simi** [comment]
@jjb if I understand this well, this is known problem for me and it is on my list to improve.

The problem is https://github.com/rails/rails/blob/1e7f867a7a14403d549edd6b67949d9598192e14/activerecord/lib/arel/nodes/update_statement.rb#L8-L16 and https://github.com/rails/rails/blob/1e7f867a7a14403d549edd6b67949d9598192e14/activerecord/lib/arel/visitors/to_sql.rb#L803-L816 do not keep all possible conditions (I'm aware of `FROM` which seems related to your case and also I'm aware of `WITH` which is related to my cases).
