### ISSUE TITLE
Float calculate result is different between PostgreSQL and MySQL

### ISSUE THREAD

**Issue by wokenqingtian** [rails/rails#38572]
### Steps to reproduce
Run below content in Rails console:

```ruby
# Under PostgreSQL
ActiveRecord::Base.connection.execute("SELECT (ACOS(0.9999250668634809) * 6376.77271) as distance;").first
# => 78.0648632113755

# Under MySQL
ActiveRecord::Base.connection.execute("SELECT (ACOS(0.9999250668634809) * 6376.77271) as distance;").first
# => 78.06486321137547
```

Run below SQL in DB console:

```sql
SELECT (ACOS(0.9999250668634809) * 6376.77271) as distance;
```
Get `78.06486321137547` under both MySQL and PostgreSQL

### Expected behavior

As you can see the expected result is `78.06486321137547`

### Actual behavior

But I get `78.0648632113755` under PostgreSQL

### System configuration

**Rails version**: 5.2.2.1

**Ruby version**: 2.4.4

**PostgreSQL version**:  11.2

**MySQL verson:**  5.5.49

**Comment by louim** [comment]
Hey! i'm not sure this is related to Rails directly. I ran the database query directly:

Postgresql 9.4 on [DbFiddle](https://www.db-fiddle.com/)
> 78.0648632113755

Postgresql 11 on DbFiddle
> 78.0648632113755

Postgresql 12 on DbFiddle
> 78.06486321137547

Postgresql 12.2 on a Mac via Homebrew:
> 78.06486321137545

**Comment by nanaya** [comment]
It's caused by different [`extra_float_digits`](https://www.postgresql.org/docs/12/datatype-numeric.html#DATATYPE-FLOAT) settings. In poster example, rails uses server default which is 0 in postgres 11 and the sql client probably somehow has it set to 1.

The default has been changed in [v12](https://www.postgresql.org/docs/12/release-12.html).

As for why on mac it shows ...7545, I have no idea. It's ...7547 on my freebsd 12.1 postgres 12.2.
