### ISSUE TITLE
TypeError: can't quote Hash

### ISSUE THREAD

**Issue by turok1997** [rails/rails#38633]
### Steps to reproduce
What you need is a model with jsonb attribute:

1. Migration to create a model

```
class CreateBuggyModel < ActiveRecord::Migration[5.2]
  def change
    create_table :buggy_models do |t|
      t.jsonb :the_only_attribute, null: false, default: {}
    end
  end
end
```
2. Trying to convert the model instance to SQL insert query:
```
record = BuggyModel.new
table = Arel::Table.new(record.class.table_name)
attribute_val_pairs = record.send(:attributes_with_values_for_create, record.attribute_names)
  .map { |column_name, val| [table[column_name.to_sym], val] }
insert_query = record.class.arel_table.create_insert.insert(attribute_val_pairs).to_sql
```

### Expected behavior
The variable `insert_query` contains the following string
`"INSERT INTO \"buggy_models\" (\"the_only_attribute\") VALUES ('{}')"`

### Actual behavior
Throws an exception:
```
TypeError: can't quote Hash
from /home/your_username/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/quoting.rb:179:in `_quote'
```

### System configuration
**Rails version**: 5.2.4.1

**Ruby version**: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]

**Comment by eugeneius** [comment]
Rails 5.2 is no longer supported for bug fixes, and your example code uses private API - most notably `attributes_with_values_for_create`, which doesn't exist since https://github.com/rails/rails/commit/56ca81a9111d1a47349299e2b973160885bad767.

We only accept issues which are reproducible with APIs documented on https://api.rubyonrails.org/.
