### ISSUE TITLE
zeitwerk: expected file to define constant Generators:: for custom rails generators

### ISSUE THREAD

**Issue by Geesu** [rails/rails#38671]
### Steps to reproduce
Create a custom generator following this [guide](https://guides.rubyonrails.org/generators.html).

Add `lib` to your autoload/eager load path:

```
    extra_paths = %W(
      #{config.root}/lib
    )
    config.autoload_paths += extra_paths
    config.eager_load_paths += extra_paths
```

### Expected behavior
Running `bin/rails zeitwerk:check` will ignore the lib/generators folder since generators are defined here

### Actual behavior
It fails with:
`expected file lib/generators/my_generator/my_generator.rb to define constant Generators::MyGenerator::MyGenerator`

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.5p114

**Comment by Geesu** [comment]
The fix in case anyone comes across this:

```
    extra_paths = %W[
      #{config.root}/lib
    ]

    # Add generators, they don't have a module structure that matches their directory structure.
    extra_paths += Dir.glob("#{config.root}/lib/generators/*")

    config.autoload_paths += extra_paths
    config.eager_load_paths += extra_paths
```

**Comment by RobinDaugherty** [comment]
There's no need to both autoload and eager load the `lib` directory.

A cleaner solution would be to move the generators and any other development-only classes to a new folder (I've named mine `lib_development` and autoload that in the development environment, while eager-loading the entire `lib` folder in all environments as before.

```rb
    # config/application.rb

    # Eager load things that will be available in production. Don't place development dependencies in this folder.
    config.eager_load_paths += %W[#{config.root}/lib]

    # Only load development dependencies when needed in the development environment.
    if Rails.env.development?
      config.autoload_paths += Dir.glob("#{config.root}/lib_development")
      config.autoload_paths += Dir.glob("#{config.root}/lib_development/generators/*")
    end
```

**Comment by kalleth** [comment]
This bit me today -- for some reason in my staging environment (where config.eager_load is set to true!) Zeitwerk was erroring on application boot about the new generator I'd added, following the rails guide above.

The only way I could "fix" this was to ignore -- explicitly! -- the generator, with this in `config/application.rb`:

```ruby
Rails.autoloaders.main.ignore(Rails.root.join('lib/generators/asset_manifest_generator.rb'))
```

Even though, in the environment, `eager_load` is already enabled for these files:

```ruby
# config/application.rb:
config.eager_load_paths << Rails.root.join('lib')
# config/environments/staging.rb and config/environments/production.rb:
config.eager_load = true
```

This is a pretty nasty issue, because it doesn't manifest until you try and _run the application in production_ -- without zeitwerk:check in your CI/CD (which very few people must have!) you won't notice until your deployment starts failing.

Thankfully I caught it on a staging env :)

I don't know if the rails guide, the rails default configuration for 6.0, or zeitwerk is at fault here, but I'm pretty sure this could end up being nasty for some!

If you can point me in the right direction, I'll happily make an attempt at a pull request -- but I'm not sure where to start!

**Comment by fxn** [comment]
Hey, I just saw this one.

Problem is that if you configure `lib` to be an autoload path, the configuration is saying that all Ruby files under `lib` are expected to follow conventions and define the corresponding constants, and that subdirectories mean namespaces (so, `lib/tasks` defines `Tasks`).

These things are not generally true, and that is why `lib` is not in the autoload paths by default since Rails 3. Also, the current recommendation is to have reloadable code of that kind in `app/lib` and configure nothing.

In the [_Classic to Zeitwerk HOWTO_](https://edgeguides.rubyonrails.org/classic_to_zeitwerk_howto.html#check-zeitwerk-compliance-in-the-test-suite) guide we've documented how to verify that all is good in CI.

That will cover not only Zeitwerk compliance, but also any other possible problem eager loading that does not manifest in the test suite for whatever other reason. That can always happen.

**Comment by jakestonelater** [comment]
For the idiots like me that end up here, check the obvious first.
for me it was simply that a typo in the class name caused the problem.

**Comment by marciopinho** [comment]
@jakestonelater Thanks for your comment, it actually helped me find the issue in my app. Not strictly a typo, but the effect was the same: I had a service, ListingsService, in a file whose name was outdated – events_service.rb .

**Comment by gibsonbett** [comment]
> For the idiots like me that end up here, check the obvious first. for me it was simply that a typo in the class name caused the problem.

got me too

**Comment by bogdan** [comment]
I fixed with this inside `config/application.rb`:

```
    config.autoload_lib(ignore: %w[assets tasks generators])
```

It feels logical to be the default.

**Comment by fxn** [comment]
@bogdan exactly, in 7.1 applications that is the idiomatic solution.

The `autoload_lib` call in `config/application.rb` generated by `rails new` ignores `assets` and `tasks`, but does not ignore `generators` because new applications do not have that directory. However, [the docs](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#config-autoload-lib-ignore) do mention that use case.

**Comment by mikker** [comment]
For anyone landing here with the same problem as me.

I write a gem, it has generators. They confuse Zeitwerk.

In `gem_name/lib/gem_name/railtie.rb`:

```ruby
module GemName
  class Railtie < ::Rails::Railtie
    initializer("gem_name.initialize") do |application|
      # Ignore our generators as they confuse Zeitwerk
      Rails.autoloaders.main.ignore(File.expand_path("../generators", __dir__))
    end
  end
end
```
