### ISSUE TITLE
Rails 6: Invalid class method in controller causes controller to be silently ignored

### ISSUE THREAD

**Issue by jamesbrooks** [rails/rails#38868]
### Steps to reproduce
* Using Ruby 2.6.5
* Running in development (`config.eager_load` will correctly identify the issue).

Include a invalid class method in a controller, e.g.:
```
# app/controllers/books_controller.rb
class BooksController < ApplicationController
  abcdef

  def index
    # any work
  end
end
```

```
# app/views/books/index.html.erb
<h1>Books!</h1>
```

### Expected behavior
An exception should be raised:
`undefined local variable or method 'abcdef' for BooksController:Class`

This is the behavior with Rails 5.2.4.2 on Ruby 2.6.5, as well as Rails 6 with Ruby 2.7.0.

### Actual behavior
**On Rails 6.0.2.2:**
The contents of the controller is ignored, nothing in `BooksController#index` is ran, the template is rendered as as if nothing was wrong (though any instance variables that may have been declared in the controller action are of course absent).

**On Edge Rails:**
The very first request correctly raises the exception, every subsequent request functions as Rails 6.0.2.2 above.

### System configuration
**Rails version**: 6.0.2.2 and master

**Ruby version**: 2.6.5

**Comment by fxn** [comment]
The gist of the problem is that in `zeitwerk` mode Rails is following Ruby semantics.

In pure Ruby, if you define

```ruby
class C
  1/0

  def foo
  end
end
```

and then load that file capturing the exception, you get the `C` class defined, but only partially:

```ruby
begin
  require_relative "c"
rescue
end

c = C.new # fine, the C class is defined
c.foo # error, Ruby did not reach the line that defines foo
```

That is how Ruby works.

This has been reported a few times, for example https://github.com/rails/rails/issues/35453 or https://github.com/rails/rails/issues/37650.
