### ISSUE TITLE
Class not loaded when in the same namespace as gem's classes

### ISSUE THREAD

**Issue by blevine** [rails/rails#38886]
I've created a NOOP implementation of an ActiveJob queue adapter.  The class is ActiveJob::QueueAdapters::NoopAdapter per ActiveJob naming conventions.  This class lives in .../app/foo/active_job/queue_adapters/noop_adapter.rb and is declared like so:

```
module ActiveJob
  module QueueAdapters
    class NoopAdapter
...
```
This class is not autoloaded as evidenced by bin/rails zeitwerk:check and by going into the Rails console and typing ActiveJob::QueueAdapter::NoopAdapter.

However, if I change the first module to ActiveJob1 (or anything other than ActiveJob) and change the first module in the class definition to ActiveJob1, the class is autoloaded.

I have not yet experimented to determine whether this occurs with namespaces from other Gems. 

### Expected behavior
The class should be loaded by the auto loader

### Actual behavior
The class is not loaded

### System configuration
**Rails version**: 6.0.2.2
**Ruby version**: 2.6.5
Spring and bootsnap are disabled.

**Comment by fxn** [comment]
For Zeitwerk to understand that namespace is owned by someone else and not to be autoladed, the module `ActiveJob::QueueAdapters` should be loaded before the `setup` call. You could do that in an application initializer for example.

Could you please give it a try?

**Comment by fxn** [comment]
Just throwing

```
require "active_job/queue_adapters"
```

somewhere before the initialization finishes would suffice. Could be an initializer, or `config/application.rb` for example.

**Comment by blevine** [comment]
Yes, that works.  Thank you.  However, the workaround is nonintuitive unless you have a pretty deep understanding of how Zeitwerk works.

**Comment by fxn** [comment]
@blevine agree, I'll need to document it. Let me leave this open to close it with a doc patch.

**Comment by blevine** [comment]
Much appreciated. Thank you!

**Comment by fxn** [comment]
I have [documented](https://github.com/fxn/zeitwerk#reopening-third-party-namespaces) in Zeitwerk how to work with third-party namespaces.

In this particular case, however, since you're defining the adapter in the source tree of the Rails application that is using it, you really need to put the file that defines the adapter in a place that is not autoloaded or reloaded.

That is because the queue adapter is defined during the boot process, so you need the class at that time (should not autoload at that point, it's too early and won't work in future versions of Rails), and because the adapter instance [is cached by Active Job](https://github.com/rails/rails/blob/960ceb237ac886711b8d50cdca3ac13c2e147be8/activejob/lib/active_job/queue_adapter.rb#L40-L41) when the application boots, and so reloading won't have any effect.

If you want to implement a queue adapter in the application source tree, I'd recommend doing so in the `lib` directory, and then `require` that file before configuring the adapter:

```ruby
# config/application.rb

require "active_job/queue_adapters/noop_adapter.rb" # found in the lib directory
config.active_job.queue_adapter = :noop
```

If you edit the implementation of the adapter while the server is up, you need to restart.
