### ISSUE TITLE
Allow silencing "Rails couldn't infer whether you are using multiple databases" warnings

### ISSUE THREAD

**Issue by grosser** [rails/rails#38924]
.... just leave me in peace with my simple db config, I don't want multiple databases 🤷

**Comment by simi** [comment]
What's your config?

**Comment by grosser** [comment]
does not matter ... but here it is:
```
<%
  uri = URI(ENV['PRECOMPILE'] ? 'mysql2://fake@fake/fake' : ENV.fetch('DATABASE_URL'))
  uri.scheme = 'mysql2'
%>

default: &default
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5

development: &development
  <<: *default
  url: <%= uri.to_s.sub(/[^\/]+$/, "foo_development") %>

test:
  <<: *default
  url: <%= uri.to_s.sub(/[^\/]+$/, "foo_test") %>

<% if ['staging', 'production'].include?(Rails.env) %>
<%= Rails.env %>:
  <<: *default
  url: <%= uri.to_s %>
<% end %>

```

**Comment by jonathanhefner** [comment]
I think the problem might be this line: `<%= Rails.env %>:`.  For the sake of debugging, if you prefix that line with some string (e.g. `foo<%= Rails.env %>:`), do you still receive the warning?

**Comment by simi** [comment]
I think it is related to using `ERB` in your yml file which is not possible to be evaluated for some rake tasks. Anyway I do agree on suggestion to not bother users by this unless they have not configured app directly to use multi-db feature. That feature should be disabled by default IMHO and should not cause any warnings/troubles since it (at least in my :eyes:) is not useful for majority of rails projects.

**Comment by grosser** [comment]
Yes, either make it opt-in or at least have a way to do `multi_db = false` to silence it 🤷

**Comment by eileencodes** [comment]
I'd be fine with silencing it, @grosser do you want to write a PR?

To clarify, ERB is allowed but we have to strip the ERB since it could have Rails env configuration. When there's so much ERB removed that the YAML becomes unparsable we throw the warning. This is a perfect example of a YAML config that would be better as a [configuration DSL when we finish the feature](https://github.com/rails/rails/pull/38721).

**Comment by grosser** [comment]
I silenced it via a hack, so I'm not making a PR :)

**Comment by mileslane** [comment]
@eileencodes, I am also encountering this:

test: &test
  <<: *local_postgres
  database: MyProject_test_<%= ENV.fetch('GIT_BRANCH', 'main').gsub(/\W/, '_') %>

I don't know how to write a PR to fix this and am not sure what the workaround would be.

**Comment by therealrodk** [comment]
Found this [old activerecord changelog from 2020](https://fossies.org/linux/rails/activerecord/CHANGELOG.md), which says:

"Allow users to silence the "Rails couldn't infer whether you are using multiple databases..." message using"
`config.active_record.suppress_multiple_database_warning`

Hopefully it will help someone else coming here.

**Comment by kblicharski** [comment]
> Found this [old activerecord changelog from 2020](https://fossies.org/linux/rails/activerecord/CHANGELOG.md), which says:
> 
> "Allow users to silence the "Rails couldn't infer whether you are using multiple databases..." message using" `config.active_record.suppress_multiple_database_warning`
> 
> Hopefully it will help someone else coming here.

It appears this has been deprecated.

https://github.com/rails/rails/blob/main/activerecord/lib/active_record.rb#L339
