### ISSUE TITLE
Odd SQL from string comparison on an integer column

### ISSUE THREAD

**Issue by vikas-wadhwa** [rails/rails#38955]
This has been driving me a bit batty but I think I've gotten it figured out, I can't seem to find any references to this elsewhere.

When doing a :where clause that has the operand as an integer column, but the value being compared is a string, the where clause gets generated oddly.

Assume you have a User model with an integer 'id' field. The following evaluates:

**User.where(id: 'abc').to_sql**
=> "SELECT `users`.* FROM `users` WHERE `users`.`id` = 0"

**User.where(id: ['']).to_sql**
=> "SELECT `users`.* FROM `users` WHERE `users`.`id` = NULL"

**User.where(id: '').to_sql**
=> "SELECT `users`.* FROM `users` WHERE `users`.`id` = NULL"

**User.where(id: ['', nil]).to_sql**
=> "SELECT `users`.* FROM `users` WHERE (`users`.`id` = NULL OR `users`.`id` IS NULL)"

**User.where.not(id: ['', nil]).to_sql**
=> "SELECT `users`.* FROM `users` WHERE NOT ((`users`.`id` = NULL OR `users`.`id` IS NULL))"

Specifically the **User.where.not(id: ['', nil]).to_sql** example is causing the query to return nothing, that's how this first got reported.

**Comment by vipulnsward** [comment]
Related to https://github.com/rails/rails/issues/36413

The `id = NULL` causes the query to be empty in the last case. Rest scenarios return mostly as "expected".

Script for reproduction: https://gist.github.com/vipulnsward/dd8c8d6a023d289761b7b9c14d67190a

**Comment by lxxxvi** [comment]
In my opinion all examples work as expected.

The rule is that the comparison is resolved to `= NULL` when comparing an non-String column with a String, for example:

```ruby
.where(id: '')        # WHERE id = NULL
.where.not(id: '')    # WHERE id != NULL
```

However, **both** queries return zero rows.

```sql
      SELECT '(none)' AS filter, count(*) AS count FROM users
UNION SELECT 'WHERE id = NULL' , count(*)          FROM users WHERE id = NULL
UNION SELECT 'WHERE id != NULL', count(*)          FROM users WHERE id != NULL;
```
```
      filter      | count
------------------+-------
 (none)           |     4
 WHERE id = NULL  |     0
 WHERE id != NULL |     0
```

We cannot compare `=` anything with `NULL`.
That's why `IS NULL` and `IS NOT NULL` exist, which is the only way to get "expected" results when dealing with `NULL` values.

---

The same rule applies to when we're using an `IN`-clause:

```sql
      SELECT '(none)'                    , count(*) FROM users
UNION SELECT '(existing ID)'             , count(*) FROM users WHERE id IN (123)
UNION SELECT 'IN (NULL, existing ID)'    , count(*) FROM users WHERE id IN (NULL, 123)
UNION SELECT 'NOT IN (NULL, existing ID)', count(*) FROM users WHERE id NOT IN (NULL, 123);
```
```
          filter            | count
----------------------------+-------
 (none)                     |     4
 (existing ID)              |     1
 IN (NULL, existing ID)     |     1
 NOT IN (NULL, existing ID) |     0     # <- this may be considered "unexpected"
```

* `IN ()` returns a row if the attribute's value equals to **at least one** of the provided values.
* `NOT IN ()` returns a row if the attribute's value is **not equal to all** provided values.

That means that no rows are returned due to the rule of not being able to compare `=` anything with `NULL`,

Also, I believe that `column NOT IN (a, b, ..)` is a shortcut for `NOT (column = a OR column = b, ...)`:

```sql
SELECT count(*) FROM users WHERE id NOT IN (NULL, 123);             -- 0 rows
-- is the same as
SELECT count(*) FROM users WHERE NOT ((id = NULL OR id = 123));     -- 0 rows
```

Finally, we could fix/solve this behaviour by putting the comparisons into their own "comparison group":

```sql
SELECT count(*) FROM users WHERE (NOT id = NULL OR NOT id = 123); -- 3 rows (of total 4)
```

Alternatively we could make sure that empty strings `''` are ignored/removed when using `where.not` with a non-String datatype?


(Examples with PostgreSQL 12.2)
