### ISSUE TITLE
ActiveRecord::RecordNotFound error message on an ::Associations::CollectionProxy #find method includes a query statement

### ISSUE THREAD

**Issue by NickSchimek** [rails/rails#38956]
### Steps to reproduce

I'm not sure if this is a bug or a feature.

The method `find` returns a different RecordNotFound error message depending on whether it is called from a CollectionProxy or a Relation.

```ruby
class User < ApplicationRecord
  has_many :posts
end
class Post < ApplicationRecord
  belongs_to :user
end

user = User.create
=> #<User id: 1, name: nil, created_at: "2020-04-15 01:21:12", updated_at: "2020-04-15 01:21:12">

user.posts.create
=> #<Post id: 1, message: nil, user_id: 1, created_at: "2020-04-15 01:23:00", updated_at: "2020-04-15 01:23:00">
```

### Expected behavior

I would expect that when I look up a record that does not exist it would have the same error message regardless if it is called from a CollectionProxy or a Relation.

I would expect:
```ruby
user.posts.find 2 # => ActiveRecord::RecordNotFound (Couldn't find Post with 'id'=2 [WHERE "posts"."user_id" = ?])
```
To Match:
```ruby
Post.find 2 # => ActiveRecord::RecordNotFound (Couldn't find Post with 'id'=2)
```
### Actual behavior

Query statement is included after the useful error message.
```ruby
user.posts.find 2 # => ActiveRecord::RecordNotFound (Couldn't find Post with 'id'=2 [WHERE "posts"."user_id" = ?])
```

### System configuration
**Rails version**:
Rails 6.0.2.2

**Ruby version**:
2.7.0

**Comment by eugeneius** [comment]
This behaviour is very much intentional:
https://github.com/rails/rails/blob/a5469f0239ed210104fdea33d8e5ba87dbad4f5b/activerecord/lib/active_record/relation/finder_methods.rb#L338-L339

It's been around since `Relation#find` was first added in https://github.com/rails/rails/commit/d92c4a84023bc0c8dd75869c9b4d5e50277f4650.

It allows you to differentiate the case where the record doesn't exist at all from the case where it exists but wasn't found because of the scoped query (i.e. it belongs to a different user).

**Comment by jimbali** [comment]
Has this changed in Rails 7.0? In 6.1 I was getting:
```
"Couldn't find MyClass"
```
but in 7.0 I am getting:
```
"Couldn't find MyClass with [WHERE \"my_class\".\"version\" = $1 AND \"my_class\".\"name\" = $2]"
```

**Comment by ispyropoulos** [comment]
> Has this changed in Rails 7.0?

@jimbali it seems yes https://github.com/rails/rails/pull/42454
