### ISSUE TITLE
Fragment caching within render layout: block does not include all necessary template digests 

### ISSUE THREAD

**Issue by marckohlbrugge** [rails/rails#38984]
Given two views like this:

```html+erb
<!-- views/pages/home.html.erb -->
<%= render layout: "wrapper" do %>
  <%= cache @post %>
  <!-- cache fragment name: ["pages/_wrapper:3f4bbb56698f60f9616533df83be7694", #<Post id: 1, …>] -->
    HOME
  <%= end %>
<%= end %>
```

```html+erb
<!-- views/pages/about.html.erb -->
<%= render layout: "wrapper" do %>
  <%= cache @post %>
  <!-- cache fragment name: ["pages/_wrapper:3f4bbb56698f60f9616533df83be7694", #<Post id: 1, …>] -->
    ABOUT
  <%= end %>
<%= end %>
```

The `cache @post` calls returns the same cache key (and thus same fragment cache) despite being called from different views. It only includes a template digest of the `wrapper.html.erb` file, but not the template (`home.html.erb` or `about.html.erb` it's being called from).

Interestingly, when not including @post as a cache key, the cache fragment name includes the URL of the current page, and thus ends up being unique per view.

### Steps to reproduce

I've created a [demo rails app](https://github.com/marckohlbrugge/cache_layout_digest_bug) showcasing the problem:

```
git clone https://github.com/marckohlbrugge/cache_layout_digest_bug
cd cache_layout_digest_bug
bin/rails db:migrate
rails dev:cache
rails server
open https://localhost:3000
open https://localhost:3000/about
```

Alternatively you can see [this commit](https://github.com/marckohlbrugge/cache_layout_digest_bug/commit/774b7c542c154501519b071dba1638589497dbe8) to view all the relevant code.

Note that I accidentally created the demo app with Rails 5.2.4.2, but the same issue occurs in Rails 6.

### Expected behavior

Using `cache` within a `render layout:` block should include a template digest of the view the cache method is called (or something else unique like the URL).

### Actual behavior

Using `cache` within a `render layout:` block does **not** include a template digest of the view the cache method is called. The means different views unexpectedly end up sharing the same fragment caches.

### System configuration

**Rails version**: 6.0.2.2

**Ruby version**: 2.6.6p146

### Possibly related

- https://github.com/rails/rails/issues/14991
- https://github.com/rails/rails/commit/da1b8a786cad277c1e4dc1a9f03acec4268dda1f

**Comment by alipman88** [comment]
I can reproduce this.

At first glance, I wonder if it's possible to generate the fragment MD5 digest using the content between the cache do/end call. Seems like that might improve the robustness of Action View's fragment caching strategy.

(I'm noticing Rails' docs [specify](https://api.rubyonrails.org/classes/ActionView/Helpers/CacheHelper.html#method-i-cache-label-Template+digest) that fragments' MD5 digests are generated using the content of an entire file rather than what's between the cache do/end call, but I'm not certain of the reasoning for this design. I intend to dig through the history here, and see if we might pursue this route.)

If that turns out not to be an option, I believe we can update [actionview/lib/action_view/helpers/cache_helper.rb](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/cache_helper.rb) to ensure consistent & expected behavior regardless of whether an ActiveRecord object passed to as a parameter to cache.

**Comment by marckohlbrugge** [comment]
> At first glance, I wonder if it's possible to generate the fragment MD5 digest using the content between the cache do/end call. Seems like that might improve the robustness of Action View's fragment caching strategy.

I'm not sure what the original reasoning was, but this type of change does seem backwards-incompatible.

For example, it's not unusual for people to set a variable at the top of a template and then use it further down. With the proposed change, the cache digest would not update when the variable gets a different value.

Simplified example:

```html+erb
<!-- app/views/users/show.html.erb -->
<% greeting = "Hello" %>

<% cache @user do %>
  <h1><%= greeting %>, <%= @user.name %></h1>
<% end>
```

Changing `<% greeting = "Hello" %>` currently invalidates the fragment cache and so a new greeting would be used. If the fragment cache digest were to solely depend on the cache block, then changing the greeting would not invalidate the cache.

It's probably not a huge issue (changing helper methods already leads to similar issues), but it is backwards incompatible and makes fragment caching more complicated.

**Comment by alipman88** [comment]
Good point on backwards compatibility, @marckohlbrugge.

To better understand the root cause, I wrote the following view file:

```
<!-- app/views/users/test.html.erb -->
<p>
  <div>cache_fragment_name(@post):</div>
  <div><%= cache_fragment_name(@post) %></div>
</p>

<p>
  <div>cache_fragment_name():</div>
  <div><%= cache_fragment_name() %></div>
</p>
```

Which renders as:

```
cache_fragment_name(@post):
["pages/test:bb7600a351611eb835ec381ce84d4ea9", #<Post id: 1, title: nil, created_at: "2020-04-18 18:02:44", updated_at: "2020-04-18 18:02:44">]

cache_fragment_name():
["pages/test:bb7600a351611eb835ec381ce84d4ea9", "localhost:3000/test"]
```

Basically, if no object (e.g. `@post`) is passed to the `cache` method, the cache key is created using the request domain + port + path (e.g. localhost:3000/test) as a default parameter. Otherwise, the object (i.e. @post) will be used as a parameter.

That default parameter is handy in helping ensure cache keys are unique when the same template is used for multiple actions, but in many cases it's not desirable (e.g. rendering a partial where the cache key and content should be the same regardless of the action/request path). So we don't want to include it regardless of whether an object is passed to `cache`.

I'm not coming up with any immediate solutions, but I'm going to keep thinking about this (and appreciate others' thoughts). I feel we can view this as an acceptable edge case if we don't find a straightforward solution, but it would still be nice to implement one.

**Comment by vipulnsward** [comment]
> I'm not sure what the original reasoning was, but this type of change does seem backwards-incompatible.

If the state of cache depends on external variables(like `greeting `), they need to be passed in for key instead:

https://github.com/rails/rails/blob/4bf9e49ec407d47511fc0ede9f6b810483fdcedb/actionview/lib/action_view/helpers/cache_helper.rb#L36 

So not backwards-incompatible for that case.

**Comment by marckohlbrugge** [comment]
@vipulnsward The comment you link to refers to variables that can very per request, such as `current_user`. These do indeed need to be part of the cache key as otherwise one user might see the cached fragment for a previous user.

In my example however, the variable does not vary per request. It only changes when the developer changes the template file.

With the current approach changing the variable (e.g. to `greeting = "Yo"`) would change the MD5 digest and thus invalidate the cache as expected. With the proposed solution the cache would not invalidate and still use the old value.

You could argue developers shouldn't define variables at the top of the template and then use them within a cache block, but since this has not been advised against and works just fine, I would consider it a backwards-incompatible change if this stops working.

The `greeting` example is rather contrived, but I frequently define variables at the top of the template that I use throughout the file. For example for a "post a new job listing" page in one of my projects I assign a price variable at the top of the template which I use multiple times throughout the template. This way I only need to make a change in one place when the price changes. I'm sure we can come up with other examples as well.

**Comment by alipman88** [comment]
As a functional programming proponent, I personally don't like the idea of passing "invisible" parameters to a cache block. But this may be a moot question, as Ruby doesn't support a Proc#to_source method that would make it easy to create a digest of the code inside a cache do/end block: https://bugs.ruby-lang.org/issues/2080

One thought might be to use Proc#source_location, which would provide a file and line number we could append to fragments' cache keys.

With the inclusion of the location of a cache block in fragment cache keys, you could do things like:

```
<%= cache "foo" do %>
<div>Some content</div>
<% end %>

<%= cache "foo" do %>
<div>Different content</div>
<% end %>
```

Which would then render as:

```
Some content
Different content
```

(In cases where developers want to re-use the same cache key for multiple cache fragments, the cache block could be moved into a shared partial, which we want to be steering folks towards per DRY principle anyway.)

**Comment by alipman88** [comment]
Been thinking about this a little more, and I see a clean solution.

1581cab introduces a "template stack", the top item of which is accessed via the `@current_template` variable and used to build the virtual path + digest segment of the fragment cache key.

If we skip adding templates to the stack when rendered as a layout with a block, this problem goes away. I have a fork I'm working on locally - I'll submit a PR once I figure out the least invasive way to implement this.

(My earlier `Proc#source_location` idea would also work, but would complicate logic following the changes introduced by 1581cab.)

On a side note, it looks like the `virtual_path` keyword arguments found in [actionview/lib/action_view/helpers/cache_helper.rb](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/cache_helper.rb) no longer do anything. I'm going to take a closer look, and if remove them if that's the case.
