### ISSUE TITLE
Inflector produces inconsistent inflections for a TLA

### ISSUE THREAD

**Issue by jessitron** [rails/rails#39117]
### Steps to reproduce
`rails generate scaffold BFF field`

### Expected behavior
Generate some classes that are consistent and work

### Actual behavior
Whatever it comes up with, it isn't consistent.
![image](https://user-images.githubusercontent.com/1149737/80893211-e3e9fd80-8c95-11ea-8abf-4a2a2c9f2884.png)

The generated route :bffs expects BffsController but the controller generated is BfFsController (in bf_fs_controller.rb) 

(wording by @avdi) 

### System configuration
**Rails version**: Rails 6.0.2.2

**Ruby version**: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

**Comment by fxn** [comment]
Just a heads up.

The root cause is that there is a `pluralize` → `underscore`, which results in "BFFs" → "bf_fs". 

The documentation of the scaffold generator explictly says that you can pass an argument using camel case or snake case. However, in my view that is an unfortunate flexibility, because `camelize` and `underscore` are not inverse of each other.

I'll think about it, but I suspect it is hard, or perhaps just not possible, to support both styles, perform all the involved inflections, and generate consistent class and file names.

While this is open, if anyone is coming here, let me suggest to use snake case arguments, as shown in the examples of the documentation:

```
Examples:
    `bin/rails generate scaffold post`
    `bin/rails generate scaffold post title:string body:text published:boolean`
    `bin/rails generate scaffold purchase amount:decimal tracking_id:integer:uniq`
    `bin/rails generate scaffold user email:uniq password:digest`
```

**Comment by avdi** [comment]
"Sorry, Rails can't figure out how to inflect that word consistently" is an acceptable way to handle this. It would still be better than generating classes that are internally inconsistent.

**Comment by fxn** [comment]
@avdi agreed.

**Comment by avdi** [comment]
At a guess I'd say a quick round-trip-and-compare might suffice as a "crap, I don't know how to inflect this reliably" check.

**Comment by fxn** [comment]
The implementation of the generator delegates to other generators. It needs to be checked if the respective encapsulations allow for that.

In any case, we have to investigate what to do.

**Comment by fxn** [comment]
I am not familiar with generators, and my OSS bandwith is limited, going to unassign this one.

**Comment by avdi** [comment]
Tagging @dhh as requested 😊

**Comment by dhh** [comment]
Yeah that's a great example of how sometimes it's better just to say "hey, I can't actually infer what you meant here, so please do either A or B, so I know what's what".

**Comment by avdi** [comment]
I want to suggest that a check for something like `s.singularize.camelcase == s.pluralize.underscore.singularize.camelcase` would be a good starting consistency check. But I'm sure there are aspects I'm missing.

**Comment by dhh** [comment]
Yeah, we can probably extract a test as to whether the word can be round-tripped 👍
