### ISSUE TITLE
activesupport-6.0.3 activerecord error

### ISSUE THREAD

**Issue by Wr0ngPass** [rails/rails#39218]
### Expected behavior
 run rails app 

### Actual behavior
 https://pastebin.com/wxRhRQf9 

### System configuration
**Rails 6.0.3**:

**ruby 2.7.1p83**:

**Comment by eugeneius** [comment]
`raise_in_transactional_callbacks` was deprecated in Rails 5.0 and removed in Rails 5.1, remove any references to it in your application to fix this error.

You should upgrade one minor version at a time, so that this kind of change surfaces as a deprecation warning:

https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#the-upgrade-process
