### ISSUE TITLE
ActionText Not Working With API Only Setup

### ISSUE THREAD

**Issue by aunumever** [rails/rails#39266]
### Steps to reproduce
- Create a new `--api` only based Rails project.
- Add a model with `has_rich_text :content`
- Set the content
- Try to access that content in the rails console or mailers: `@model.content.body`
- `@model.content.body.to_html` does return the proper content, however, in mailers, you must do this: `@model.content.body.to_html.html_safe`

```
class Test < ApplicationRecord
    has_rich_text :content
end
```

```
irb(main):001:0> record = Test.new
irb(main):002:0> record.content = "<p>Hello World</p>"
irb(main):003:0> record.content
=> #<ActionText::RichText id: nil, name: "content", body: #<ActionText::Content " ">, record_type: "Test", record_id: nil, created_at: nil, updated_at: nil>
irb(main):004:0> record.content.body
=> #<ActionText::Content " ">
irb(main):005:0> record.content.body.to_s
=> " "
irb(main):006:0> record.content.body.to_json
=> "\"\\u003cp\\u003eHello World\\u003c/p\\u003e\""
irb(main):007:0> record.content.to_json
=> "{\"id\":null,\"name\":\"content\",\"body\":\"\\u003cp\\u003eHello World\\u003c/p\\u003e\",\"record_type\":\"Test\",\"record_id\":null,\"created_at\":null,\"updated_at\":null}"
```

### Expected behavior
It should return the content of the body that was set. I should be able to see the content in my rails console, as well as in mailers.

### Actual behavior
It returns an empty string, and is only accessible by converting it to JSON or HTML. Values are not available in the rails console, nor mailer views.

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.7.1p83

**Comment by abhaynikam** [comment]
@navimaia I debugged the issue and I think the issue is due to Action Text having a dependency on Action View to render the content. Action Text use partial(https://github.com/rails/rails/blob/master/actiontext/app/views/action_text/content/_layout.html.erb) render its content. 

Since your application is API only, anything which is used for browser applications like views, helpers are skipped and Action Text does not behave the way it should.

The easiest fix would be to inherit the `ApplicationController` with `ActionController::Base` and create another BaseController inheriting from `ActionController::API` use `BaseController` at all places. This would work because ActionText uses `ApplicationController.renderer` to render layouts(https://github.com/rails/rails/blob/master/actiontext/lib/action_text/engine.rb#L50). 

The second solution would be to stop serializing the RichText content to `ActionText::Content` in API only application then you would receive the exact HTML as it is saved in DB without any processing which is done for Trix editor and in API the only app I think it is fair.

If any core team member approves this, I'll try to raise a fix for it.

**Comment by Atiladanvi** [comment]
Are you can add that observation in https://guides.rubyonrails.org/api_app.html#choosing-controller-modules ?

**Comment by Evilbits** [comment]
I've had to manually handle the case of rendering ActionText attachments without using partials. It would be nice to have some native support for this.

**Comment by danjebs** [comment]
@abhaynikam thanks for the tip, that's one more hurdle down 🎉  Noticed your content a few times around getting ActionText working in API-only apps and it's really helped. You rock 👊

**Comment by lylo** [comment]
> I've had to manually handle the case of rendering ActionText attachments without using partials. It would be nice to have some native support for this.

Are you able to explain how you did this at all?

**Comment by MoHayat** [comment]
@abhaynikam can you elaborate a bit more on the second solution you proposed? would 'not serializing the received content' mean building a workaround to ActionText as you create new objects or using methods like `read_attribute_before_type_cast` to fetch the saved content as it is stored? Appreciate the help.
