### ISSUE TITLE
File upload in minitest gets converted to `ActionController::Parameters`

### ISSUE THREAD

**Issue by caseykim** [rails/rails#39370]
### Steps to reproduce
```
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  mount_uploader :media_file, MediaUploader
  ...
end
```
```
require 'test_helper'

class PostsControllerTest < ActionDispatch::IntegrationTest
  setup do
    @file = fixture_file_upload('public/media_file/Perfect Fit.mov')
  end
  ...
  test 'should create comment' do
    assert_difference('Post.count') do
      post posts_url,
           params: { post: {
             media_file: @file
           } },
           as: :json
    end

    assert_response :created
  end
end
```

### Expected behavior
I'm expecting to see `media_file` as `Rack::Test::UploadedFile` or `ActionDispatch::Http::UploadedFile`

I've tried using
```
Rack::Test::UploadedFile.new
ActionDispatch::Http::UploadedFile.new
```
instead of `fixture_file_upload` but encountered the same issue.
Posting to same routes with same file using `Postman` works as expected.
`Post.create(media_file: @file)` works fine as well.

### Actual behavior
above `post` in minitest generates 
```
=> <ActionController::Parameters {"post"=><ActionController::Parameters {"media_file"=><ActionController::Parameters {"original_filename"=>"Perfect Fit.mov", "tempfile"=>"#<File:0x00007fed12e2c488>", "content_type"=>nil} permitted: false>} permitted: false>, "controller"=>"posts", "action"=>"create"} permitted: false>
```

notice `params[:post][:media_file]` is `ActionController::Parameters`
not `Rack::Test::UploadedFile`
and thus `post_params` drops `media_file`

### System configuration
**Rails version**:
Rails 6.0.2.2
**Ruby version**:
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

**Comment by mcgregordan** [comment]
I think this is expected behaviour for a json request. If it wasn't a json request, you’d have an `ActionDispatch::Http::UploadedFile` object, as you expect. Your test should pass if you drop the `as: :json`.

Because this is a json request, the params you pass are encoded to json before the test request is fired. Your file upload, when json-ified, becomes the hash you are seeing: `{"original_filename"=>"Perfect Fit.mov", "tempfile"=>"#<File:0x00007fed12e2c488>", "content_type"=>nil}`.

It seems odd to me that you’d upload a file on a json request. Personally I’d send a `multipart/form-data` request, which your test would work for. Alternatively you could base64-encode the file in the json request and decode in the controller.

**Comment by mcgregordan** [comment]
That said, it is a bit weird you get `"tempfile"=>"#<File:0x00007fed12e2c488>"` as part of the json representation of the file. That’s useless!

**Comment by jonathanhefner** [comment]
@caseykim The explanation provided by @mcgregordan is correct.

Thank you @mcgregordan!

**Comment by woto** [comment]
I also faced this problem, it turned out `..._path(format: :json)` is not the same as post `..._path(...), as: :json`. The first one will work.
