### ISSUE TITLE
"Write query attempted while in readonly mode" in tests

### ISSUE THREAD

**Issue by gravitystorm** [rails/rails#39449]
I've been working on converting [our application](https://github.com/openstreetmap/openstreetmap-website) to use [multiple databases](https://guides.rubyonrails.org/active_record_multiple_databases.html) in order to read from replicas. I have found a problem where the default `:writing` connection can be erroneously marked as readonly, and this causes problems with our test suite. I've managed to isolate the problematic behaviour into a small demo application (one controller, one test, standard DatabaseSelector middleware).

### Steps to reproduce

Demo application to show problem: https://github.com/gravitystorm/prevent_writes

Diff between "rails new" and demo application: https://github.com/gravitystorm/prevent_writes/compare/3e2defa..master

The isolated [testcase](https://github.com/gravitystorm/prevent_writes/blob/d28877247e36de3aee5ad6c28793e487d58c234c/test/controllers/site_controller_test.rb) is essentially:
* `get` a page
* then try writing to the database outside of the read request
* write connection has been marked as readonly and the testcase fails.

It's worth noting the following things:

* The problem only happens if responding to the `get` involves a database connection being used. If you remove the `c = User.count` from the controller action, the problem does not happen.
* The problem can be avoided by accessing the database within the test, before the `get` request. In the demo testcase, if you uncomment the section `# user = User.count` before the `get`, the testcase then passes. This shows that even using the default connection to make a read request is enough to avoid it being later marked as read-only.
* If there are any fixtures files, even if they are blank, then the problem does not happen. I think this is another case of using the database connection for something else first means that we avoid the problem.

Unfortunately I got completely lost while trying to trace through how all this works in ActiveRecord, so I haven't been able to pinpoint the error.

### Expected behavior

The example testcase should pass. The write connection should not end up marked as readonly.

### Actual behavior

Testcase fails with

```
ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode: INSERT INTO "users" ("name", "created_at", "updated_at") VALUES (?, ?, ?)
    test/controllers/site_controller_test.rb:13:in `test_index'
```

### System configuration
**Rails version**: 6.0.3

**Ruby version**: ruby 2.6.5p114

**Comment by eileencodes** [comment]
Hey @gravitystorm this is fixed by https://github.com/rails/rails/commit/d4ebba275e413059c873a1218da73471bcf5e115 in master and in 17d56621ff88d8d5a2a4577572a1d0d98a1fabb1 on 6-0-stable. It will be in the next 6.0 and 6.1 release.

This is the same issue as https://github.com/rails/rails/issues/39205.

**Comment by eileencodes** [comment]
You can alleviate this issue while you wait by ensuring you establish the writing connection first or monkey patching `setup_shared_connection_pool` from `activerecord/lib/active_record/test_fixtures.rb`

**Comment by gravitystorm** [comment]
> This is the same issue as #39205.

Sorry for the duplicate report! I'm feeling a little bit stupid for not having found that during my debugging.

**Comment by eileencodes** [comment]
No worries @gravitystorm! No need to feel stupid, this is complex stuff. 😄

**Comment by sajjadmurtaza** [comment]
@eileencodes I have a get request on the XYZ Controller#index ` def index ... end` method but I am calling another mother which includes `Model.where(column: value).first_or_create`.

 
```
  def index
     ......
     ......
     Model.where(column: value).first_or_create
     ......
  end
```
 
I am not sure if it is expected behavior or I need to change the role for  `Model.where(column: value).first_or_create `?

 `ActiveRecord::ReadOnlyError (Write query attempted while in readonly mode: INSERT INTO...`
 
Here are the logs:
 > %%%%%%%%%% reading
method=GET path=/<ACTION> format=*/* controller=<XYZController> action=index status=500 error='ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode: INSERT INTO....
