### ISSUE TITLE
Blank page displayed after send_file for link_to tag in IE

### ISSUE THREAD

**Issue by kumaranubhaw** [rails/rails#39507]
I have used link_to tag to implement the downloading file. When request is made for downloading file, the controller method uses send_file to download the file in browser.
The downloading for file is working properly in all browsers but after download blank page is displaying in Internet Explorer.   

### Steps to reproduce
Refer this link to get the example code.
https://github.com/kumaranubhaw/blank_page_in_IE 
For setup please see the Readme file

### Expected behavior
After download the same page should be displayed as in all other browser.

### Actual behavior
Blank page is displayed after download.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.5

**Comment by jonathanhefner** [comment]
I do not have a copy of IE to test with, but I believe adding `target="_blank"` to your download link should address the problem.  (Though it will cause a new tab to open and close, even in browsers that don't require it.)

Since Rails can't really know when to do this, I'm going to close.  Thank you for the issue!
