### ISSUE TITLE
Testing controller for a Model with ActiveStorage stucks PostgreSQL

### ISSUE THREAD

**Issue by dima4p** [rails/rails#39514]
### Steps to reproduce

install the application from `channel.bundle` attached

run `bundle exec rspec -c spec/views/channels spec/controllers/channels_controller_spec.rb`

### Expected behavior

The specs should be finished with green

### Actual behaviour

The process stucks 

There are not completed transactions in postgresql.
```
$ psql -U postgres
Pager usage is off.
psql (12.3)
Type "help" for help.

postgres=# SELECT query FROM pg_locks pl LEFT JOIN pg_stat_activity psa ON pl.pid = psa.pid WHERE state = 'idle in transaction';
           query           
---------------------------
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
 SAVEPOINT active_record_1
(18 rows)
```

### System configuration

See the Gemfile from the attachment. It contains in particular:

```
ruby '2.6.3'
gem 'rails', '~> 5.2.3'
```

**Comment by dima4p** [comment]
[channel.zip](https://github.com/rails/rails/files/4718598/channel.zip)

**Comment by vipulnsward** [comment]
Unsure what the channel.bundle file is that you have attached. Can you share sample rails application(code host on GitHub) to reproduce your issue?

**Comment by dima4p** [comment]
`git help bundle`

**Comment by dima4p** [comment]
@vipulnsward [here it is](https://github.com/dima4p/channel)

**Comment by dima4p** [comment]
I think it is a real problem. Please, try my sample to reproduce. [here](https://github.com/dima4p/channel)

**Comment by dima4p** [comment]
This is a very complicated case. I've tried to fix it myself, but failed.

**Comment by fatkodima** [comment]
I reproduced the issue. 
The problem is not within using postgresql, but within some lock contentions while autoloading constants. I changed the rails version to `6.0` and the problem went away. So, you can either upgrade to rails >= 6.0 or for current version you can add
```ruby
# config/environments/test.rb

config.active_job.queue_adapter = :inline
``` 

which also solves the issue.

**Comment by JohnSmall** [comment]
This problem is due to ActiveStorage automatically queuing an ActiveJob to analyse files. It completely trashes transactions in testing and also anything that adds new ActiveStorage blobs in a migration. 

It would be nice if you can turn off auto queuing. I've found that setting the queue adapter to inline doesn't help.

**Comment by dima4p** [comment]
> setting the queue adapter to inline doesn't help.

The only solution I have found is setting the queue adapter to :test

**Comment by zzak** [comment]
@dima4p @JohnSmall Did you both try upgrading Rails?
