### ISSUE TITLE
BigDecimal.limit does not stay when set in initializer

### ISSUE THREAD

**Issue by RobsonKing** [rails/rails#39512]
### Steps to reproduce
1. Create a new Rails app.
2. Create an initializer and set the BigDecimal.limit
`
Rails.logger.debug "Before #{BigDecimal.limit}" # will output 0 (which is the default)
BigDecimal.limit(20)
Rails.logger.debug "After #{BigDecimal.limit}" # will output 20 (which is what we want)
`
3. In any controller method, log what the limit its
`Rails.logger.debug "Controller #{BigDecimal.limit}" ` 
  The limit will output 0. It is back at the default value.

### Expected behavior
I would expect the limit set in the initializer to still be set.  

### Actual behavior
The limit is set back to the default of 0.  Is there somewhere else I should be setting the limit? 

### System configuration
**Rails version**:5.2.4.3

**Ruby version**:2.6.3

**Comment by jonathanhefner** [comment]
This happens because Ruby stores the `BigDecimal` limit in thread local storage:

https://github.com/ruby/ruby/blob/87bc95e7c7b70e14f60b40c0b35d7e79da5e31e5/ext/bigdecimal/bigdecimal.c#L2874-L2883

https://github.com/ruby/ruby/blob/87bc95e7c7b70e14f60b40c0b35d7e79da5e31e5/ext/bigdecimal/bigdecimal.c#L3680-L3686

When e.g. Puma starts a new thread to handle a request, the new thread can't access the `BigDecimal` limit set in the initial thread.

You can try adding `before_action { BigDecimal.limit(20) }` to your controller, but that won't affect threads spawned in other contexts.  Unfortunately, the only way I know of to hook thread spawning in general is to monkey-patch `Thread` (which doesn't seem very nice).

Since this is not a Rails issue, per se, I'm going to close this, but feel free to discuss alternative solutions.
