### ISSUE TITLE
Can't rescue_from ActiveRecord::ConnectionTimeoutError in production

### ISSUE THREAD

**Issue by zaratan** [rails/rails#39646]
### Steps to reproduce

* Create a new rails app (6.0.3.1)
* In the application controller add:
```ruby
  rescue_from ActiveRecord::ConnectionTimeoutError do
    Rails.logger.warn "AR connection timeout"
  end
```
* Launch rails in `production` mode.
* See the app failing

**Quick notes:**
* This was working in Rails 5.2.x
* This work in `development`

### Expected behavior

Should rescue the exception

### Actual behavior

```
`<class:ApplicationController>': uninitialized constant ActiveRecord::ConnectionTimeoutError (NameError)
Did you mean?  ActiveRecord::ConnectionAdapters
```

### System configuration
**Rails version**:
6.0.3.1
**Ruby version**:
2.7.1

**Comment by p8** [comment]
`ConnectionTimeout` should probably be `ConnectionTimeoutError`

**Comment by denispasin** [comment]
You’re right and that’s what I had in my app (fixed it by explicitly triggering load of the file). 

This is bad copy paste from me trying to reproduce on an empty project. I’ll confirm tomorrow that it’s indeed repro on a new Rails app(bit late right now).

**Comment by denispasin** [comment]
Sorry, I checked and it was indeed a bad copy-paste on my side. The issue is still there for `ActiveRecord::ConnectionTimeoutError`.

My current workaround is to touch `ActiveRecord::ConnectionAdapters::ConnectionPool` just before the rescue_from (so it will load the file and load `ActiveRecord::ConnectionTimeoutError` in the ruby context)

I'm willing to fix this in Rails source code but I'm unsure about how to start doing so.

**Comment by jonathanhefner** [comment]
@denispasin My recommendation would be to use the name of the class rather than the class itself:

```ruby
rescue_from "ActiveRecord::ConnectionTimeoutError" do
  # ...
end
```

In fact, in the [implementation of `rescue_from`](https://github.com/rails/rails/blob/v6.0.3.1/activesupport/lib/active_support/rescuable.rb#L61-L67), it is the name that is kept and matched against later.

**Comment by denispasin** [comment]
Thanks a lot for your answer! I should have looked at how `rescue_from` worked.

I'll do it this way.

It still looks a bit like a better workaround to me though. This was working fine in Rails `5.2`. Should I close the issue or should we consider fixing?
