### ISSUE TITLE
ActiveStorage: undefined method `attachment_reflections' for nil:NilClass

### ISSUE THREAD

**Issue by heaven** [rails/rails#39647]
Happens when trying to remove orphaned attachments:
```ruby
ActiveStorage::Attachment.where(record_type: "TournamentRegistration").map(&:destroy)
```
Produces:
```
NoMethodError (undefined method `attachment_reflections' for nil:NilClass)
```

But `#purge` worked.

**Rails version**:
6.0.3.1

**Comment by gentcys** [comment]
Hi @heaven! Can you create an executable test script using one of templates here[](https://github.com/rails/rails/tree/master/guides/bug_report_templates)

**Comment by nshki** [comment]
Hi there! Decided to take some time to see if I could replicate this issue, and was able to do so with [this Gist here](https://gist.github.com/nshki/5698eb03e0427228a7aeb4fd5cc1c283).

At first, I tried to replicate the issue by calling `destroy` on a `TournamentRegistration`, but the associated `ActiveStorage::Attachment` gets successfully destroyed as a result of what I suspect to be the underlying `dependent: :destroy` in [this line](https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/attached/model.rb#L63).

So my second stab was to assume there was some kind of default scope being applied to `TournamentRegistration`, similar to how common gems like [Paranoia](https://github.com/rubysherpas/paranoia) or [acts_as_paranoid](https://github.com/rubysherpas/paranoia) might behave. Adding a default scope in the test script does indeed result in the error being described.

**Comment by heaven** [comment]
Hi, sorry for the lack of feedback from me, didn't have time to provide the script so far. As @nshki mentioned default scope might affect this as well but in our case `Tournament Registrations` were removed previously. I'm not sure how exactly but probably with `delete_all` or the table was truncated. So I then wanted to cleanup orphaned attachments and got this error. After that, I found the docs say to use `#purge` instead and that worked but still looks a bit strange to me. Looks like an additional presence check is missing somewhere in ActiveStorage.

**Comment by nshki** [comment]
Ah, thanks for the additional context @heaven. I updated the Gist to test for the `delete_all` case as well, and it fails in the same way. Also like you mentioned, using `purge` instead of `destroy` produces expected results.

After looking through the [relevant Active Storage docs](https://edgeguides.rubyonrails.org/active_storage_overview.html#removing-files), it does seem like calling `purge` is the recommended way of disposing of attachments. Looking at the method definitions, [`ActiveStorage::Attachment#purge`](https://github.com/rails/rails/blob/8642c564dab37366c2ca8950b428d1aec84eb10d/activestorage/app/models/active_storage/attachment.rb#L22) is calling `delete` on the attachment then `purge` on the corresponding blob. [`ActiveStorage::Blob#purge`](https://github.com/rails/rails/blob/8642c564dab37366c2ca8950b428d1aec84eb10d/activestorage/app/models/active_storage/blob.rb#L265) is calling `destroy` then [`delete`](https://github.com/rails/rails/blob/8642c564dab37366c2ca8950b428d1aec84eb10d/activestorage/app/models/active_storage/blob.rb#L257) on the blob.

It _seems_ like `destroy` is just calling [the method defined in Active Record](https://github.com/rails/rails/blob/fb4a3fbf1f1404be39e6d4027cf6b97c080de30a/activerecord/lib/active_record/persistence.rb#L539), so it wouldn't perform the necessary steps that result from a `purge` call (namely, removing corresponding data from connected services). Although they read similarly, `destroy` and `purge` seem to have very different purposes for Active Storage attachments.

Some possible paths from here could be:
1. Have `ActiveStorage::Attachment#destroy` call `ActiveStorage::Attachment#purge`, but that probably comes with a bunch of violations (cases where `ActiveRecord::Persistence#destroy` is actually needed), so probably not a recommended option.
2. Raise a warning when `destroy` is called on an attachment, pointing to `ActiveStorage::Attachment#purge`.
3. Perhaps mark this as a non-issue.

Please fact check me, though!

**Comment by heaven** [comment]
Well, it seems the main reason is that I didn't read docs carefully and if `#destroy` is used internally by Rails the warning could be disappointing. But from my point of view, it would make more sense to give us the `#destroy` method and use `#purge` one internally.

**Comment by gentcys** [comment]
> Deletes the records without instantiating the records
   first, and hence not calling the {#destroy}[rdoc-ref:Persistence#destroy]
   method nor invoking callbacks.
   This is a single SQL DELETE statement that goes straight to the database, much more
   efficient than #destroy_all. Be careful with relations though, in particular
   <tt>:dependent</tt> rules defined on associations are not honored.

`delete_all` method's [comment](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L561)

After you call `delete_all` or the table was truncated, you call attachment's `destroy` method, then it'll invoke `:purge_dependent_blob_later` callback which will [check relation's(has_one_attached) `dependent` option](https://github.com/rails/rails/blob/master/activestorage/app/models/active_storage/attachment.rb#L52).
 Because of the attachment is orphaned, so it can't find attachment's owner record then return nil.
