### ISSUE TITLE
NoMethodError in preloading belongs_to association

### ISSUE THREAD

**Issue by ranupratapsingh** [rails/rails#39672]
### Steps to reproduce

1. create a rails project
`rails new preload_bug -d mysql`
2. Create a `Lead` model
`rails g scaffold lead name:string email:string agent_code:string`
3. create `Agent` model
`rails g scaffold Agent name:string email:string code:string`
4. prepare db
`rails db:create db:migrate`
5. create a belongs_to relationship in `Lead` model
```
class Lead < ApplicationRecord
  belongs_to :agent, foreign_key: :agent_code, primary_key: :code
end
```
6. In rails console type following
```
Lead.create name: "ranu", email: "abc@xyz.com", agent_code: "susa"
Agent.create name: "Susa", email: "susa@test.com", code: "SUSA"
a = Lead.includes(:agent).where(id: 1).first
```

### Expected behavior
Exception should not come and first lead record should be returned successfully with associated agent as nil.

### Actual behavior
No method error exception occurs
`NoMethodError (undefined method 'first' for nil:NilClass)`

This happens in following code in `lib/active_record/associations/preloader/association.rb`
```
          def records_for(ids)
            scope.where(association_key_name => ids).load do |record|
              # Processing only the first owner
              # because the record is modified but not an owner
              owner = owners_by_key[convert_key(record[association_key_name])].first. # **problematic line**
              association = owner.association(reflection.name)
              association.set_inverse_instance(record)
            end
          end 
```

### System configuration
**Rails version**:
Rails 6.0.3.2
**Ruby version**:
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]

**Comment by maxfelsher** [comment]
I've seen similar issues in earlier versions of Rails. If it's the same issue, the underlying cause is that by default MySQL ignores case when comparing strings, while Ruby doesn't. 

Specifically, Rails takes the value of `agent_code` from the `Lead` record ("susa") and runs a query along the lines of `SELECT * FROM agents where code = 'susa'`. MySQL treats "SUSA" as equivalent to "susa" so it returns the agent record with a code of "SUSA". Rails then tries to figure out which `Lead` record the agent goes with (this is necessary when you have multiple `Lead` records, as is typical when preloading) by using the agent's `code` value: `owners_by_key['SUSA']`. The `owners_by_key` hash, though, is based on the values from the `Lead` records, and it doesn't have a "SUSA" key (only "susa"). The Rails code isn't set up to handle the situation where a key isn't found, and so an exception is raised.

The MySQL comparison rules are controlled by what's known as the _collation_ of the columns, so if you don't want MySQL to consider "susa" and "SUSA" equivalent, you can change the database schema to use a case-sensitive collation for those columns. If you do want them to be considered equivalent, I've had luck using a custom ActiveRecord attribute type to make sure that Rails changes everything to one case before using it.

I believe this is hard to solve in a general way within Rails, since collations relate to much more than case sensitivity--for example, they can declare whether a character with an accent on it is equivalent to the character without the accent. It'd be very hard for Rails to be aware of all the rules for every collation for every database system. Still, it might be possible to have a more specific warning.

**Comment by ranupratapsingh** [comment]
Hey @maxfelsher thanks for the insight. Yes this looks the same bug. I raised this because it comes only in case of preload.
```
a = Lead.includes(:agent).where(id: 1).first
```
raises error while 
```
a = Lead.where(id: 1).first
a.agent
```
does not.
May be exception can be avoided here by a simple nil check but I am not sure if this is as simple as nil check.

**Comment by pixeltrix** [comment]
@maxfelsher I reckon it is possible to make it work - MySQL case insensitive collations end in `_ci` and in those situations it's possible to switch to using `casecmp?`. However, I think a better approach would be warning developers not to use columns that are case insensitive for foreign keys like this - this could be a check in the association builder code so that it only occurs when loading the model.

**Comment by pixeltrix** [comment]
@ranupratapsingh I'd be very wary of using a case-insensitive column for a foreign key like this - this kind of comparison in MySQL has been exploited by hackers before, so it may have unintended side effects.

**Comment by ranupratapsingh** [comment]
@pixeltrix Thank you for the guidance. Closing this issue.

**Comment by maxfelsher** [comment]
@ranupratapsingh 

> Hey @maxfelsher thanks for the insight. Yes this looks the same bug. I raised this because it comes only in case of preload.

That's true. When you don't preload, it goes through a different code path that doesn't hit this issue. Glad I was able to help!

**Comment by maxfelsher** [comment]
@pixeltrix 

> @maxfelsher I reckon it is possible to make it work - MySQL case insensitive collations end in `_ci` and in those situations it's possible to switch to using `casecmp?`. However, I think a better approach would be warning developers not to use columns that are case insensitive for foreign keys like this - this could be a check in the association builder code so that it only occurs when loading the model.

I agree that the case-sensitivity issue could probably be solved with `casecmp?`, and that would probably solve most of the cases affected by this issue. It wouldn't remove the possibility that this could be triggered by other situations where the collation considers two strings equivalent and Ruby doesn't (for example where a character has an accent in one string and not in the other).

I like your suggestion to warn about using foreign keys with case-insensitive collations, if it's feasible (it could possibly even warn about anything that doesn't compare byte-for-byte). I'd also love to see an exception that provides more context than `NoMethodError` if this does get triggered. Does that seem like a good idea?

**Comment by ranupratapsingh** [comment]
Even I agree that there should be a better warning/error. Reopening.

**Comment by pixeltrix** [comment]
> I like your suggestion to warn about using foreign keys with case-insensitive collations, if it's feasible (it could possibly even warn about anything that doesn't compare byte-for-byte). I'd also love to see an exception that provides more context than NoMethodError if this does get triggered. Does that seem like a good idea?

@maxfelsher PRs for better warnings that can be given without affecting runtime performance are always welcome. 👍

**Comment by coorasse** [comment]
We faced the same issue in an old MySQL database. Our solution was to monkey patch the class:

```ruby
# config/initializers/active_record/associations/preloader/association.rb

module ActiveRecord
  module Associations
    class Preloader
      class Association #:nodoc:
        def convert_key(key)
          if key_conversion_required?
            key.to_s
          else
            key
          end
          key = key.downcase if key.is_a? String
          key
        end
      end
    end
  end
end
```

just leaving it here as a reference for others.

**Comment by kuboon** [comment]
@coorasse `key.to_s` should be `key = key.to_s`
