### ISSUE TITLE
Conditions on nested `joins` associations break automatic type conversion and cause schema queries

### ISSUE THREAD

**Issue by arthurschreiber** [rails/rails#39727]
So, first things first - I'm not sure if this is an actual issue in ActiveRecord or just a case of "you're holding it wrong". 😅

We've got the following ActiveRecord models:

```ruby
class Listing
  has_and_belongs_to_many :categories
end

class Category
  has_and_belongs_to_many :listings

  belongs_to :parent_category, class_name: "Category"
end
```

When we build (not run) the following relation

```ruby
Listing.left_joins(categories: :parent_category).where(parent_categories_categories: { id: "1234" })
```

We see that ActiveRecord runs the following schema introspection query:

```sql
SELECT table_name FROM information_schema.tables WHERE table_schema = database() AND table_name = 'parent_categories_categories'
```

Because there is no such table, ActiveRecord can't find the schema definition and thus won't correctly convert the value for `id` to an integer. This can be seen in the generated query:

```sql
SELECT `listings`.* FROM `listings`
LEFT OUTER JOIN `categories_listings` ON `categories_listings`.`listing_id` = `listings`.`id`
LEFT OUTER JOIN `categories` ON `categories`.`id` = `categories_listings`.`category_id`
LEFT OUTER JOIN `categories` `parent_categories_categories` ON `parent_categories_categories`.`id` = `categories`.`parent_category_id`
WHERE `parent_categories_categories`.`id` = '1234'
```

In theory, ActiveRecord could know that the `parent_categories_categories` alias is for the `categories` table (because that alias is generated by ActiveRecord), and could correctly determine that the `id` column referenced in the `where` condition is coming from the `categories` table.

If we change the relation to reflect the joins condition:

```ruby
Listing.left_joins(categories: :parent_category).where(categories: { parent_category: { id: "1234" } })
```

ActiveRecord will correctly determine the type of the `id` column and perform type conversion, but does not correctly figure out the alias it's giving to the joined tables:

```sql
SELECT `listings`.* FROM `listings`
LEFT OUTER JOIN `categories_listings` ON `categories_listings`.`listing_id` = `listings`.`id`
LEFT OUTER JOIN `categories` ON `categories`.`id` = `categories_listings`.`category_id`
LEFT OUTER JOIN `categories` `parent_categories_categories` ON `parent_categories_categories`.`id` = `categories`.`parent_category_id`
WHERE `parent_category`.`id` = 1234
```

---

We found this while trying to understand why ActiveRecord is running introspection queries after deployments, even though we're providing a full schema cache to our app.

Is this an issue in ActiveRecord? Or are we using ActiveRecord wrong? 🤔

### System configuration
**Rails version**: 6.0.x

**Comment by jpanderson-outreach** [comment]
This also happened with us and resulted in full table scans with something like:

```ruby
class Item
  belongs_to :owner, class_name: 'User'
end

Item.joins(:owner).where(users: {id: '1'}).to_sql
# => "SELECT `items`.* FROM `items` INNER JOIN `users` ON `users`.`id` = `items`.`owner_id` WHERE `users`.`id` = '1'"
# Note the string id of '1'

# Similarly:
Item.joins(:owner).where(owner: {id: '1'}).to_sql
# => "SELECT `item`.* FROM `items` INNER JOIN `users` ON `users`.`id` = `items`.`owner_id` WHERE `owner`.`id` = 1"
# Note that we correctly casted but used the wrong table name
```

I'd be curious to know if we, too, are just using ActiveRecord wrong somewhere along the way.

**Comment by drssdinblck** [comment]
@arthurschreiber Is the second query returning correct results? I’m not quite sure what you mean by ‘ does not correctly figure out the alias it's giving to the joined tables’. As to your first question, I think you are referring to AR internals by referring to the alias of the joined table. With AR and includes/joins, one should probably refer to association names and not table names. Or can you point me to a piece of documentation that shows your kind of syntax?

**Comment by jpanderson-outreach** [comment]
> With AR and includes/joins, one should probably refer to association names and not table names.

Not to speak for @arthurschreiber , but I think both of our concerns is that when using the association name in the joins (`Item.joins(:owner)` in my example) we are then unable to query further on the associated table because using the association name in the where clause results in either a nonexistent table in the query (in the case of doing `.where(owner: { id: '1' })`) or a non-casted ID value (in the case of doing `.where(users: { id: '1' })`). To make those two values generic, it's `.where(association_name_that_is_not_the_table_name: { id: '1' })` and `.where(actual_underlying_table_name: { id: '1' })` respectively.

So I think we both come to the question of: can ActiveRecord figure out which table name to use in the query after a joins on an association when using the association name or is this something unsupported?

https://guides.rubyonrails.org/active_record_querying.html#specifying-conditions-on-the-joined-tables

The documentation on [Hash Conditions](https://guides.rubyonrails.org/active_record_querying.html#equality-conditions) may imply this is unsupported given that it only calls out `belongs_to` queries and requiring a model:

> In the case of a belongs_to relationship, an association key can be used to specify the model if an Active Record object is used as the value.
