### ISSUE TITLE
Tag builder doesn't accept options with strings as keys

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#39813]
### Steps to reproduce
I believe this only occurs in rails 5.2.  It seems to work correctly in 6.0.3.2
```
>> tag.span('value', 'aria-hidden' => 'true', class: 'closed')

ArgumentError: wrong number of arguments (given 3, expected 1..2)
```

Additionally, when a value is not provided no error is thrown, but string keys are lost:
```
>> tag.span('aria-hidden' => 'true', class: 'blah') { tag.br }

=> "<span class=\"blah\"><br></span>"
```

### Expected behavior
It should work like content_tag:
```
>> content_tag(:span, 'value', 'aria-hidden' => 'true', class: 'closed')

=> "<span aria-hidden=\"true\" class=\"closed\">value</span>"

```

It works fine if all the keys are Symbols
```
>> tag.span('value', :'aria-hidden' => 'true', class: 'closed')

=> "<span aria-hidden=\"true\" class=\"closed\">value</span>"
```

### Actual behavior
```
ArgumentError: wrong number of arguments (given 3, expected 1..2)
```

### System configuration
Rails 5.2.4.3

**Ruby version**:
2.7.1

**Comment by composerinteralia** [comment]
Thanks for the issue! Since this only occurs on Rails 5.2 and not on 6.0 I am going to close this issue. At this time Rails 5.2 only gets security fixes. Other bug fixes won't generally get applied. You can check out the [maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html) for more details.  If it turns out this is still an issue on Rails 6.0 then we can reopen this issue.
