### ISSUE TITLE
When using Rails.cache.fetch, Please show warning at mistyping the expires_in option.

### ISSUE THREAD

**Issue by takundao71** [rails/rails#39850]
### Problem
When using Rails.cache.fetch, it is easy to mistype the expires_in option.
Incorrectly specified in expires or expired_in,
I haven't noticed it for a long time.

This article specifies expired_in incorrectly.
This article is at the top of the search results, so I think many people have made the same mistakes.
https://morizyun.github.io/ruby/rails-function-cache-fetch-write-delete.html

### Improvement plan
If we specify incorrectly such as expires or expired_in,
Please show warning.
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache.rb

**Comment by victorperez** [comment]
`Rails.cache.fetch` allow to pass some universal options as `expires_in`, but it also allows you pass any other option that will be handled by the specific cache store implementation you are using. That makes difficult to determinate if an option is valid (custom cache stores are also possible).

**Comment by mrpinsky** [comment]
I have also run into this problem. Mistyping `expire_in: 2.seconds` instead of `expires_in: 2.seconds` caused us to accidentally cache an endpoint for 6 hours when we wanted 2 seconds. I understand @victorperez's concern of clobbering other keys, but in the case of keys that are 1 character off from global options, I think that's a pretty low risk. What if the cache store was just more forgiving for these easy, dangerous issues by considering them all as aliases for `:expires_in`?

**Comment by rafaelfranca** [comment]
> What if the cache store was just more forgiving for these easy, dangerous issues by considering them all as aliases for `:expires_in`

That is a good plan. Do any of you are interested in opening a PR to fix this issue adding an alias to `expires_in`?

**Comment by mrpinsky** [comment]
I am. I’ll get a PR up tomorrow
