### ISSUE TITLE
Rails.application.secrets.secret_key_base empty on production

### ISSUE THREAD

**Issue by Aryk** [rails/rails#39910]
### Steps to reproduce:

1) Run your server in production with env variable SECRET_KEY_BASE=foobar
2) Rails.application.secret_key_base will be "foobar"...however
3) Rails.application.secrets.secret_key_base will be nil.
 
### Expected behavior
Rails.application.secrets.secret_key_base should be equal to "foobar" just like it behaves in development and test. I discovered this issue in production which was hard to debug because I was passing through the environment variable correctly but only the Rails.application.secret_key_base was getting populated.

Perhaps this is expected behavior but if it is, could someone clarify the logic of magically having the fallback in development and then surprising a developer in production?  

Code in question [here](https://github.com/rails/rails/blob/master/railties/lib/rails/application.rb#L436)

Rails version 6.

**Comment by gregmolnar** [comment]
> Perhaps this is expected behavior but if it is, could someone clarify the logic of magically having the fallback in development and then surprising a developer in production?

It isn't really a fallback rather different behaviour in development and test, since in those environments, when the `secrets.secret_key_base` is not set, it will generate one even when you set it in the ENV var. So in your example, if you do `SECRET_KEY_BASE=foobar rails c` in development, `Rails.application.secret_key_base` and `Rails.application.secrets.secret_key_base` will be both set and will be equal, but it won't be `foobar`. 
The piece of code you linked above tells you does this indeed and it is pretty self-explanatory what happens if you read it carefully.
