### ISSUE TITLE
default MemoryStore compression

### ISSUE THREAD

**Issue by maxgurewitz** [rails/rails#39931]
In rails 5.1 -> 5.2 the default behavior of all `ActiveSupport::Cache::Store` implementations changed to enable compression by default. This change appears to have been made unintentionally in the following PR.

https://github.com/rails/rails/pull/32539/files#diff-438394335b9c1ce6ec4f67a407f50a42R716

This behavior is probably desirable in most cases for `MemCacheStore`, and `RedisCacheStore`, which both send data over a network to memcached and redis respectively. However, this behavior is probably undesirable in the case of `MemoryStore`, which doesn't send data over a network.

For context, I'm an engineer at [Braze](https://www.braze.com/), and I worked on upgrading our primary rails application from 5.1 -> 5.2. When we upgraded, our sidekiq workers immediately ended up roughly doubling their cpu usage, our latency spiked, and our queues started backing up. We had to roll back to 5.1 in order to avoid an outage.

We tracked down the issue, which ended up being the aforementioned altered default compression behavior of `MemoryStore`. This wasn't a blocker for us, as we were able to override `compression: false`. Nonetheless changing this default would probably benefit other current, and future `MemoryStore` users.

I've submitted an associated PR which disables compression for `MemoryStore` by default: https://github.com/rails/rails/pull/39930

### Steps to reproduce

In order to reproduce, construct a `MemoryStore` with no arguments. Write a string to the cache which exceeds the default compression threshold (1 kb).

### Expected behavior

`MemoryStore` should not perform compression.

### Actual behavior

`MemoryStore` does perform compression.

### System configuration
**Rails version**: 6.1.0.alpha
**Ruby version**: 2.6.5

This behavior seems to be longstanding, extending back to Rails 5.2.

**Comment by eugeneius** [comment]
Enabling compression by default was intentional, see https://github.com/rails/rails/pull/31147.

The pull request description mentions Memcached and Redis explicitly, so it's possible that MemoryStore wasn't considered, although the argument that compression results in higher hit rates should hold true regardless of the backing store.

@jeremy, do you have an opinion here?

**Comment by maxgurewitz** [comment]
@eugeneius any movement on this? It seems like compression for the `MemoryStore` was enabled by default without any thorough benchmarking.

**Comment by eugeneius** [comment]
If your issues were caused by the higher CPU usage required to compress and decompress entries, it seems like they would have happened regardless of which cache store you were using - in which case the issue isn't with MemoryStore per se, and https://github.com/rails/rails/pull/39930 may be over-indexed on your particular problem.

Compression is a tradeoff that uses more CPU to save memory. Clearly it doesn't work well for your application, but that doesn't necessarily mean it's the wrong default behaviour; it depends on how the application uses the cache.

If this was flagged early in the 5.2 release cycle, changing it back in a patch release would help other applications upgrading from 5.1 to avoid the problems you saw. Now though, 5.2 is no longer supported for bug fixes, so those applications will have to deal with the change no matter what we do here. Changing the default again in 6.1 will just add another stumbling block for applications that adjusted their cache usage after upgrading to 5.2, or which were created on 5.2 and built against the current default settings.

I don't think we should disable compression by default for a single cache store - or at least, I think we'd need a more persuasive argument about why it's a better default in order to do so.

**Comment by maxgurewitz** [comment]
@dmitrytra @eugeneius typically one would use an in memory cache as opposed to a remote cache when the network overhead of a remote cache (redis, memcached) is prohibitively expensive in terms of operation latency for one's use case relative to its benefits including:

* Cache servers like memcached are replicated, reducing volatility.
* Remote caches are centralized, enabling users to share cache entries across application servers etc.

However, the range of use cases where applications' latency requirements are strict enough to justify an in memory cache, but lax enough to allow for compressing in memory entries, is relatively narrow in my experience.

Looking forward, the price of memory has, and will continue to improve at a more rapid pace than the performance of individual cpu's.

This decision to trade away cpu time in exchange for reduced memory usage will only make less sense as this trend continues.

![42-years-processor-trend](https://user-images.githubusercontent.com/1750599/97218946-ba6ee200-179f-11eb-9e81-adc5c181cb73.png)

**Comment by rafaelfranca** [comment]
I agree it does make sense to change the default in the memory store to not compress cache entries. If someone uses that store it is because they want speed.
