### ISSUE TITLE
When active_record default_timezone is set, Postgres datetime arrays are saved with null

### ISSUE THREAD

**Issue by rept** [rails/rails#39938]
### Steps to reproduce
Set the default timezone of ActiveRecord
`config.active_record.default_timezone = 'UTC'`

Create a table with an array of datetime
`t.datetime "datetimes", default: [], array: true`

When you now add an element it doesn't commit correctly to the DB but saves NULL instead
```
model.datetimes << Time.now
model.save

=> [null]
```

I've created a Gist here demonstrating the problem:
https://gist.github.com/rept/23a9d775ea59f2d43510188c4d5d120a

### Expected behavior
Array should contain the datetime value.

### Actual behavior
Array should contain the datetime value, instead it contains NULL.

### System configuration
Issue with latest Rails and possibly earlier versions as well

**Comment by sudeeptarlekar** [comment]
Able to reproduce issue on local with Rails v5.2.4, v6.0.3 and PG v11.

**Comment by KapilSachdev** [comment]
Looks like this bug has been there forever and is unintentionally [fixed](https://github.com/rails/rails/commit/575f4e16a7b91da976cfd560ae20fbc32707cbe3) on master.

> 6-0-stable
https://github.com/rails/rails/blob/2d6a726dcb3320ff021c05f3d908adbb2b2e335f/activemodel/lib/active_model/type/helpers/time_value.rb#L58
>master
https://github.com/rails/rails/blob/11f54e12b992f6c8d29fd9bedd89ac438a928a2f/activemodel/lib/active_model/type/helpers/time_value.rb#L60

Though the test case still fails because of precision (maybe, haven;t looked closely), which i'm trying to see if it can be patched  or maybe this failure is expected.
I think @kamipo can shed some light on this aspect.

**Comment by KapilSachdev** [comment]
Actually the unexpectedness will persist with any value other than `:utc` and `:local`
The [change](https://github.com/rails/rails/commit/575f4e16a7b91da976cfd560ae20fbc32707cbe3) will still give unexpected result as the expectation is for `:utc` but as `'UTC'` is passed, `:local` will be used to respond because it is just falling back to use `:local` .

Will adding a warning (or maybe raising an error) if the passed value is neither `:utc` nor `:local` be a good solution here?

```ruby
if [:utc, :local].exclude?(default_timezone)
  logger.warn "unknown default_timezone value #{default_timezone}. " \
    "Accepted values are :utc and :local. Falling back to using :local instead"
end
```

And if its an accepted solution, should the warning be placed in `current_time_from_proper_timezone` before evaluation?
https://github.com/rails/rails/blob/843898c57ac152f6c4a108f3e8b5bd25200efc06/activerecord/lib/active_record/timestamp.rb#L77-L79

**Comment by KapilSachdev** [comment]
The precision difference is expected behaviour as `Time.now` has resolution of `1 nanosecond`  while `postgres's` resolution is `1 microsecond`.
So after reloading the object from the db, the values will difference by that resolution.
