### ISSUE TITLE
undefined method `construct_tables!' for #<ActiveRecord::Associations::JoinDependency:0x000000001267e7d0>

### ISSUE THREAD

**Issue by joshleblanc** [rails/rails#39978]
### Steps to reproduce
Perform a query on nested resources.

```ruby
Player.includes(:game_players).where(game_players: { is_accused: true })
```

You can actually pull this: https://github.com/joshleblanc/stimulus-sc2overwatch, and navigate to /players. No data needed

### Expected behavior
The query should succeed

### Actual behavior
The following error is thrown:

```
NoMethodError (undefined method `construct_tables!' for #<ActiveRecord::Associations::JoinDependency:0x000000001267e7d0>
Did you mean?  construct):
```

### System configuration
**Rails version**: Rails 6.1.0.alpha (commit hash this was installed from b39ea7cc3662345ad8efbe496db5ae594449f85f)

**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]

**Comment by victorperez** [comment]
`construct_tables!` method was removed in this commit: https://github.com/rails/rails/commit/590b045ee2c0906ff162e6658a184afb201865d7#diff-06059df8d3dee3101718fb2c01151ad0

This is failing because Ransack (your project use ActiveAdmin and Ransack is a dependency) uses `construct_tables!` here: https://github.com/activerecord-hackery/ransack/blob/master/lib/polyamorous/activerecord_6.0_ruby_2/join_dependency.rb#L34

This should be fixed in Ransack gem.

**Comment by joshleblanc** [comment]
Ah hah! Thank you!
