### ISSUE TITLE
Rails redirect 500 Internal Server Error

### ISSUE THREAD

**Issue by chongfai13** [rails/rails#39992]
### Expected behavior

"The page you were looking for doesn't exist."
The server responded with the response code "500 Internal Server Error". I am looking respond with response code 2XX or 3XX.

### System configuration
**Rails version**: Rails v6.0.0

**Ruby version**: Ruby 2.5.7

**Comment by KapilSachdev** [comment]
Server errors can come from a undefined variable to `postgres` being unable to handle the SQL query, so literally anything can cause a server to throw an error.
You may choose to rescue from a particular error and redirect.
You may add below code to your `ApplicationController`.
```ruby
  rescue_from ActiveRecord::StaleObjectError, with: :handle_conflict_error

  def handle_conflict_error
    render json: { errors: ['The page you were looking for doesn't exist..'] }, status: :ok
  end
```
In case you want to rescue and redirect regardless of the error replace `ActiveRecord::StaleObjectError` with  `StandardError` (NOT RECOMMENDED, Never do this, otherwise you have stepped into a dangerous territory)
You may choose the error you want to rescue.

That said,  one should never rescue errors of base classes like `ActiveRecordError`.
Responding non-500 for 500 is not a good approach as it will silence an information that should be known and many other reasons.

*The issue reported is more of a question and must be asked on platforms like `stackoverflow`*

**Comment by eileencodes** [comment]
The issues tracker is for tracking bugs in the framework but not application code. As @KapilSachdev mentioned, this question is better for stack overflow or another forum. Additionally there currently isn't enough information in your issue for us or anyone on stack overflow to help so adding more details about what your endpoints are, what data you're interacting with, the environment you're running in, etc will help someone help you. Hope you find the answer.
