### ISSUE TITLE
Zlib::BufError - buffer error - Rails.cache.read on Redis

### ISSUE THREAD

**Issue by victorlcampos** [rails/rails#40005]
### Steps to reproduce
I have a key with a 24.9kb hash size, that when I try to read from it, I get Zlib::BufError

### Expected behavior
Rails.cache.read('vportal_role_schema_display') return my cache key

### Actual behavior
Rails.cache.read('vportal_role_schema_display')

```
[f0d3dd56-5f8f-4465-bb37-ef8fbb06bd06] activesupport (6.0.3.2) lib/active_support/cache.rb:827:in `inflate'
[f0d3dd56-5f8f-4465-bb37-ef8fbb06bd06] activesupport (6.0.3.2) lib/active_support/cache.rb:827:in `uncompress'
[f0d3dd56-5f8f-4465-bb37-ef8fbb06bd06] activesupport (6.0.3.2) lib/active_support/cache.rb:749:in `value'
[f0d3dd56-5f8f-4465-bb37-ef8fbb06bd06] activesupport (6.0.3.2) lib/active_support/cache.rb:368:in `block in read'
[f0d3dd56-5f8f-4465-bb37-ef8fbb06bd06] activesupport (6.0.3.2) lib/active_support/cache.rb:686:in `block in instrument'
[f0d3dd56-5f8f-4465-bb37-ef8fbb06bd06] activesupport (6.0.3.2) lib/active_support/notifications.rb:182:in `instrument'
[f0d3dd56-5f8f-4465-bb37-ef8fbb06bd06] activesupport (6.0.3.2) lib/active_support/cache.rb:686:in `instrument'
[f0d3dd56-5f8f-4465-bb37-ef8fbb06bd06] activesupport (6.0.3.2) lib/active_support/cache.rb:355:in `read'
```

### System configuration
**Rails version**:
Rails 6.0.3.2

**Ruby version**:
2.6.6

I tried to find any clue what can be generating it, but no luck. Someone have an idea?

**Comment by esparta** [comment]
Can you provide a reproduction script?
It's kind of difficult to get an idea on what's happening without it.

**Comment by KapilSachdev** [comment]
Have you try with other `cache_stores`, because the error does not seems to be related to `redis` specific to me.

The data stored is not getting decompressed, and this could be more likely be due to the data it is storing, or maybe the way it is getting stored.
You may confirm if this is happening with every cache key (might be configuration related) or just a single/few keys (might be data related).

As already mentioned a reproduction script would be much appreciated.

**Comment by victorlcampos** [comment]
Hi Guys,
I will try to get the data. How i cannot read because of the error, i don't know what data is inside it.

I know it's a hash

And I write it with this command:
Rails.cache.write('vportal_role_schema_display', display)

I will try to not compress this data now and look what is inside.

**Comment by esparta** [comment]
@victorlcampos  so it happens with a particular key/data, as is not any compressed data will break Rails?

**Comment by KapilSachdev** [comment]
@victorlcampos is there any update against this issue?

In case still you are encountering the issue, maybe you can share some details about your `redis` cache setup.
Also does it happen with every key or only few?

_You said that you are unaware of the data inside because you are unable to read it because `Rails.cache.read` fails.
Maybe try some tools like [redis desktop manager](https://github.com/uglide/RedisDesktopManager) to know better, not sure if that would help_

**Comment by KapilSachdev** [comment]
@victorlcampos as there are no reproduction steps, i think we can close this.
It can be reopened anytime if this seems to be a bug in rails.
