### ISSUE TITLE
ActiveRecord `respond_to?` is false for reader methods with unloaded attributes

### ISSUE THREAD

**Issue by avit** [rails/rails#40019]
### Steps to reproduce

```ruby
  # activerecord/test/cases/attribute_methods_test.rb:144
  test "respond_to?" do
    topic = Topic.select(:title).find(1)
    def topic.author_name
      "custom implementation"
    end
    assert_respond_to topic, "title"
    assert_respond_to topic, "title?"
    assert_respond_to topic, "title="
    assert_respond_to topic, :title
    assert_respond_to topic, :title?
    assert_respond_to topic, :title=
    assert_respond_to topic, "author_name"
    assert_respond_to topic, "attribute_names"
    assert_not_respond_to topic, "nothingness"
    assert_not_respond_to topic, :nothingness
  end
```

### Expected behavior

Calling `respond_to?` should return `true` for custom reader methods defined on the model.

Additionally, is it expected to be false for defined columns from the schema, even without a custom reader method? E.g.

```ruby
topic = Topic.select(:id).first
topic.respond_to?(:title)
#=> false
```
(I would have expected true.)

### Actual behavior

ActiveRecord's `respond_to?` looks like it first checks ActiveModel with a `super`, which ultimately examines the keys on the attributes hash and returns false. This all happens before checking whether the object has a defined (public) method in the first place.

(This impacts usage of decorators like Draper [here](https://github.com/drapergem/draper/blob/master/lib/draper/automatic_delegation.rb#L25).)

### System configuration
**Rails version**: master (6.1.0.alpha)

**Ruby version**: 2.7.1

**Comment by composerinteralia** [comment]
I also would have expected that if you override an attribute method then `respond_to?` would return true for that method, regardless of whether the attribute was selected. I think I want:

https://github.com/rails/rails/blob/8a578c468530dbcc6126757aabb711956cf4852f/activerecord/lib/active_record/attribute_methods.rb#L216

to be:

```rb
return _has_attribute?(name) || method_overriden?(name)
```

but I have no idea how I would write `method_overriden?`

---

> Additionally, is it expected to be false for defined columns from the schema, even without a custom reader method?

Based on this [comment in the method](https://github.com/rails/rails/blob/8a578c468530dbcc6126757aabb711956cf4852f/activerecord/lib/active_record/attribute_methods.rb#L211), `respond_to?` is meant to return `false` if the attribute is not selected, so that much is working as expected.

https://github.com/rails/rails/blob/8a578c468530dbcc6126757aabb711956cf4852f/activerecord/lib/active_record/attribute_methods.rb#L211

**Comment by avit** [comment]
> but I have no idea how I would write `method_overriden?`

One way might involve checking `method(name).source_location` to see if it matches `"active_record/attribute_methods/read.rb"` as the original reader. However, an included module method could still `super` to it, while expecting to behave the same as the original reader.

It's more like we want a `method_is_attribute?` than a `method_overridden?`. The only way to do it that I can think of would be a registry of added attribute methods on the model class. It would then be up to the author to remove from this registry when declaring a method override that doesn't call the original reader. This could be a DSL like `override_attribute :name do` I suppose.

Not sure this is worth considering for such an edge case though.
