### ISSUE TITLE
ActiveSupport::Configuration fails with Safe YAML

### ISSUE THREAD

**Issue by jules2689** [rails/rails#40031]
### Steps to reproduce

1. Use the Safe YAML gem, latest is fine
2. Use Rails on Master

### Expected behavior

Rails boots.

### Actual behavior

Rails master is currently broken if you are using Safe YAML and have certain configs set, like Action Cable.
When you try to run, you will get:
```
NoMethodError: undefined method `with_indifferent_access' for nil:NilClass
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-45add344781b/actioncable/lib/action_cable/engine.rb:33:in `block (2 levels) in <class:Engine>'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-45add344781b/activesupport/lib/active_support/lazy_load_hooks.rb:73:in `instance_eval'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-45add344781b/activesupport/lib/active_support/lazy_load_hooks.rb:73:in `block in execute_hook'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-45add344781b/activesupport/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-45add344781b/activesupport/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
...
```

### System configuration
**Rails version**: master

**Ruby version**: 2.6.6

### What is broken

There was a PR merged/backported that coerces config to symbols before accessing them (https://github.com/rails/rails/pull/37850). This was in December.

In February, a commit (https://github.com/rails/rails/commit/ef7599fe91fd38d883199716ea74bb8f05b271d3#diff-f0df27f2406acba89a9871c7ec56197e) went in that changed calls to `deep_symbolize_keys` to a method kwarg on a new `ActiveSupport::Configuration` object. https://github.com/rails/rails/commit/ef7599fe91fd38d883199716ea74bb8f05b271d3#diff-f0df27f2406acba89a9871c7ec56197eR23

Unfortunately, that kwarg is new and not available in Safe YAML:

System lib YAML:
```
irb(main):002:0> require "yaml"
=> true
irb(main):003:0> YAML.load("a:\n  b")
=> {"a"=>"b"}
irb(main):004:0> YAML.load("a:\n  b", symbolize_names: true)
=> {:a=>"b"} # Symbols
```

With Safe YAML:
```
irb(main):006:0> require "safe_yaml"
=> true
irb(main):007:0> YAML.load("a:\n  b")
Called 'load' without the :safe option -- defaulting to safe mode.
You can avoid this warning in the future by setting the SafeYAML::OPTIONS[:default_mode] option (to :safe or :unsafe).
=> {"a"=>"b"}
irb(main):008:0> YAML.load("a:\n  b", symbolize_names: true)
=> {"a"=>"b"} # No symbols
```

This means that all calls to "symbolize" names will fail in the new active support configuration if Safe YAML is installed.

**Comment by composerinteralia** [comment]
I was able to reproduce this with:

```rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", path: "/Users/daniel/Desktop/oss/rails/rails"
  gem "safe_yaml" # Comment this out and the test will pass
end

require "pathname"
require "minitest/autorun"

class Application < Rails::Application
end

class BugTest < Minitest::Test
  def test_stuff
    yaml_file = Tempfile.new
    yaml_file.write DATA.read
    yaml_file.rewind
    yaml_file_path = Pathname.new(yaml_file)

    assert_equal(
      {key: "value"},
      Rails.application.config_for(yaml_file_path)
    )
  end
end

__END__
development:
  key: value
```

This was changed by https://github.com/rails/rails/pull/37876

**Comment by kamipo** [comment]
Can you use `require "safe_yaml/load"` instead of `require "safe_yaml"`?
I feel it is not an issue for Rails but an issue for safe_yaml.

https://github.com/dtao/safe_yaml#what-if-i-dont-want-to-patch-yaml

**Comment by sikachu** [comment]
I think I agree with @kamipo here. This seems like the issue for `safe_yaml` since it overrides `YAML.load`.

A quick Google gave me this issue from faraday-middleware gem that highlights the differences between the supported keys in `YAML.load` and `SafeYAML.load`: https://github.com/lostisland/faraday_middleware/pull/241#issue-373075800

I think it should be SafeYAML's responsibility to support the same configuration options as `YAML.load` and `YAML.safe_load` (technically `Psych.load` or `Psych.safe_load`) now that Psych is in Ruby standard library. I'm not sure if making us lookout for a library that will override some standard library method is the right way to fix this, as I don't think we don't want to play a cat and mouse game where someone breaks compatibility with `SafeYAML` again because they expect `YAML` to be `Psych` and not overridden version from `SafeYAML`.

**Comment by jules2689** [comment]
So while I agree in theory that this is not Rails' problem, the fact that so many applications (including github.com) uses Safe YAML, I suspect you may find there to be an increase in support.

I also think that Safe YAML brings up a good point:

> since symbols are not garbage collected in Ruby and so deserializing them from YAML may render your application vulnerable to a DOS (denial of service) attack

If this could cause a DOS, then I think it warrants a second look.

This all said, ActiveRecord is apparently a known issue to Safe YAML for similar reasons: https://github.com/dtao/safe_yaml#known-issues

**Comment by composerinteralia** [comment]
I have mixed feelings about this. I sort of want to change from `symbolize_names` to `deep_symbolize_keys` in this case because it is a simple change and is more consistent with what we do in the rest of the codebase. But I can also see why we may not want to.commit to maintaining compatibility between SafeYAML and Rails. How would folks feel about making the change in https://github.com/rails/rails/pull/40053 but without the test? That would fix this for now, but not commit to preserving this behavior forever.

**Comment by sikachu** [comment]
Symbols are actually get garbage collected since Ruby 2.2. https://www.sitepoint.com/symbol-gc-ruby-2-2/

So yes, it was a valid concern at the time SafeYAML was created, but not really much of an issue nowadays.

**Comment by jules2689** [comment]
https://github.com/dtao/safe_yaml/issues/97 I asked if it is a valid concern anymore 🎉

**Comment by strobilomyces** [comment]
I'm getting the error message in the top post not with Safe YAML, but in deploying with Capistrano/Capistrano RVM in 6.1.0.rc1. Everything runs fine in development, but when I try to deploy to my staging environment, I get the exact message with Action Cable. Previously, I was using 6.0.3.4 with no issues.
