### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by jdobkins** [rails/rails#40063]
Hi! I want to let you know that I found a broken link on these pages: 

https://guides.rubyonrails.org/v2.3/getting_started.html

https://guides.rubyonrails.org/v3.2/getting_started.html

It's a link to a Rails tutorial. If you are interested, here is a good tutorial you can link to instead : 
https://www.theblogstarter.com/intro-to-ruby-on-rails/

### System configuration
**Rails version**:

**Ruby version**:

**Comment by KapilSachdev** [comment]
As suggested in #40060 , Please use the latest stable guides rather than older ones.
These are insecure (do not receive security updates) and non-maintained versions of `rails`.

But this issue has raised a good concern when someone stumbles upon an outdated versions of guides.
I think we can add a warning banner on all those version pages that the community has stopped maintaining.
_Some documentation sites does (take [django](https://docs.djangoproject.com/en/2.0/) for example) that._

We can add this warning in _issue template_ **or** in _documentation_ **or** _[CONTRIBUTING](https://github.com/rails/rails/blob/bdfffd1355bbff4df29d59fc479b72027160950a/CONTRIBUTING.md) guide_ **or** _ contributing to fixes for older versions in [guides](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#older-versions-of-ruby-on-rails)_ **or** maintain a _new file_ that clearly define what changes for which version are accepted (like `5.2` is now limited to security fixes AFAIK but there are issues/PR created that reports bug fixes)

**Comment by composerinteralia** [comment]
> maintain a new file that clearly define what changes for which version are accepted (like 5.2 is now limited to security fixes AFAIK

It sounds like you may be describing the [maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html) document.

**Comment by KapilSachdev** [comment]
Thanks for mentioning, i forgot about this document.

Also what do you think about [fixing older-versions-of-ruby-on-rails guide](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#older-versions-of-ruby-on-rails), maybe we could update this guide to point to the maintenance policy document?
Not that there is anything wrong with the example, but adding a link to the maintenance policy document, and asking contributors to check whether the issue/PR adheres to this document rules might be beneficial for first time contributors.

**Comment by composerinteralia** [comment]
I think linking to the maintenance policy within that section is a nice idea.
