### ISSUE TITLE
ActionMailbox breaks with 'ID' inflected as an acronym

### ISSUE THREAD

**Issue by mashedkeyboard** [rails/rails#40068]
### Steps to reproduce

1. Create an application that uses `inflect.acronym 'ID'` in `en` inflections
2. Run `bundle exec bin/rails runner` in `RAILS_ENV=production`

n.b. as soon as 'ID' is removed as an inflection, this bug no longer occurs.

### Expected behavior

The runner functions correctly.

### Actual behavior

```
Aug 19 12:46:03 PM  bundler: failed to load command: bin/rails (bin/rails)
Aug 19 12:46:03 PM  NameError: uninitialized constant #<Class:0x0000557a41832730>::MessageId
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/actionmailbox-6.0.3.2/app/models/action_mailbox/inbound_email.rb:30:in `<class:InboundEmail>'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/actionmailbox-6.0.3.2/app/models/action_mailbox/inbound_email.rb:27:in `<module:ActionMailbox>'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/actionmailbox-6.0.3.2/app/models/action_mailbox/inbound_email.rb:5:in `<main>'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/kernel.rb:27:in `require'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/kernel.rb:27:in `require'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/loader.rb:388:in `const_get'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/loader.rb:388:in `block (2 levels) in eager_load'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/loader.rb:731:in `block in ls'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/loader.rb:723:in `foreach'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/loader.rb:723:in `ls'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/loader.rb:376:in `block in eager_load'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/loader.rb:368:in `synchronize'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/loader.rb:368:in `eager_load'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/loader.rb:483:in `each'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/loader.rb:483:in `eager_load_all'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `instance_exec'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `run'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
Aug 19 12:46:03 PM    /opt/render/project/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
Aug 19 12:46:03 PM    /opt/render/project/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
Aug 19 12:46:03 PM    /opt/render/project/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
Aug 19 12:46:03 PM    /opt/render/project/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
Aug 19 12:46:03 PM    /opt/render/project/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each'
Aug 19 12:46:03 PM    /opt/render/project/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `call'
Aug 19 12:46:03 PM    /opt/render/project/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
Aug 19 12:46:03 PM    /opt/render/project/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
Aug 19 12:46:03 PM    /opt/render/project/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:60:in `run_initializers'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/application.rb:363:in `initialize!'
Aug 19 12:46:03 PM    /opt/render/project/src/config/environment.rb:9:in `block in <main>'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/deprecation/reporting.rb:38:in `silence'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/deprecation/instance_delegator.rb:22:in `silence'
Aug 19 12:46:03 PM    /opt/render/project/src/config/environment.rb:9:in `<main>'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/kernel.rb:34:in `require'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/kernel.rb:34:in `require'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/application.rb:339:in `require_environment!'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/command/actions.rb:28:in `require_environment!'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/commands/runner/runner_command.rb:33:in `perform'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/command/base.rb:69:in `perform'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/command.rb:46:in `invoke'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
Aug 19 12:46:03 PM    /opt/render/project/.gems/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
Aug 19 12:46:03 PM    bin/rails:9:in `<top (required)>'
```

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.7.1

**Comment by composerinteralia** [comment]
I was able to reproduce this as described by adding the given inflection to a new application. It doesn't happen if I set `config.autoloader = :classic`, so I am thinking this is somehow related to Zeitwerk. I haven't dug into this more deeply than that yet. Having an inflector change the way Rails itself loads does seem like unexpected behavior to me.

**Comment by rafaelfranca** [comment]
The inflector always changed how Rails load constants, even in the classic mode. This is a know behavior of the framework. It is not happening in the classic mode because we don't try to find the constant name using the filename.

We have now the possibility of changing this behavior by splitting the constant loader inflector from the string inflections, but this isn't a change we can make in the stable versions or even in the upcoming release.

@fxn what do you think to have two inflector in the app on Rails 6.2? One for Zeitwerk and another for strings?

**Comment by fxn** [comment]
Hey! I am on holidays, have only a phone. Let me try to say something.

Right now, the inflector used by Zeitwerk is swappable. The default inflector delegates to `String#camelize` to ease the transition, but you can tweak it in a few ways, even to the point were AS is totally bypassed and you have full control (see https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#customizing-inflections).

That’ll address all user-related constant resolution.

The framework then, should give a way to ensure that is honored. For example, if you condigure an AJ backend. I thought about that time ago. First idea was to let Rails componenents get an inflector for constants, but did not seem clean to me, because Rails components do not depend on Rails outside of their railties/engines.

I concluded it was easier to always accept a class name that you constantize, and document that a class name is preferred over a symbol with a snake case variant. Remember `helper :alll` to be problematic, but did a pass working on this.

@mashedkeyboard, do the docs linked above help with your particular issue?

**Comment by mashedkeyboard** [comment]
@fxn, thanks for the reply! Am I understanding correctly that using an instance of `Zeitwerk::Inflector` as the inflector for the autoloader means that ActiveSupport's own inflections are completely skipped, and so the constantisation process is removed from the string inflection process? If that's correct, then yes, this is a workaround for the immediate issue here.

In my mind, the expected behaviour for this would be for inflections to affect Zeitwerk's loading of the app's constants, but not Rails' constants, but I don't know how easy or difficult that might be to implement. I can have a crack at defining a custom inflector that would have that behaviour, but I can't promise when I'd get around to doing it.

**Comment by fxn** [comment]
Ah, I believe the AJ example was a bad one because IIRC AJ issues a `require` call. What you’d try to avoid is camelize + constantize.

Bottom line, the robust dynamic idiom for Rails components is `constantize`, not inflections.

@mashedkeyboard cool that it solves your use case. The way things are defined by default, inflections influence Zeitwerk in Rails apps, because the default Zeitwerk inflector delegates to `String#camelize`. That is how it has worked traditionally. The new mode is richer in that you can tweak that at two different levels. One is `inflect`, which stills delegates to AS in the fallback, and the other one is to replace the inflector object in the autoloader, which gives you full control.

**Comment by fxn** [comment]
@mashedkeyboard however, let me dig into this when I am back home. Would like to understand where’s exactly the problem with this particular error, and whether AM should be doing something differently.

**Comment by fxn** [comment]
OK, I've been able to check Action Mailbox to see what is going on.

This has been this way since forever: AS inflections are global. In particular, you can change the inflector in your application and break any engine the application depens on. `classic` mode goes from missing constant name to file name (`underscore`), and `zeitwerk` mode goes from file name to constant name (`camelize`). Therefore, the way to trigger inconsistencies differs, but the root logic stays the same: AS inflection is global, and you can break any engine potentially.

In this case, the engine is Action Mailbox, [this line](https://github.com/rails/rails/blob/211564c6385bcc6ccf5e32804554a6c96c662220/actionmailbox/app/models/action_mailbox/inbound_email.rb#L30)  needs to autoload [this class](https://github.com/rails/rails/blob/211564c6385bcc6ccf5e32804554a6c96c662220/actionmailbox/app/models/action_mailbox/inbound_email/message_id.rb). But the fact that the engine is part of Rails is irrelevant, it could be any regular 3rd party engine.

So yes, the solution is not to change inflections globally. You can afford global changes if they do not break stuff, but if they do, you need to be more precise. Fortunately, Rails 6 gives you the means to be more precise and instead of saying "ID" has to be treated that way _globally_, you may say

```ruby
# Does not affect MessageId.
loader.inflect("open_id", "OpenID")
```

or even configure your own 100% custom inflector for the Zeitwerk loader that checks the absolute path of the file name, or applies a regexp, or anything, to be 100% sure the special rule is scoped to your own files and does not leak.

Yeah, that is the right solution here.
