### ISSUE TITLE
Feature Proposal: Default Options for schema statements

### ISSUE THREAD

**Issue by TomasBarry** [rails/rails#40071]
### Proposal

The ability to configure schema statements with a set of default options. Using `add_column` as an example - often it is preferred that columns are non-nullable by default. However, the current implementation of `add_column` does not allow for a set of default options to be applied:

```ruby
def add_column(table_name, column_name, type, **options)
  return if options[:if_not_exists] == true && column_exists?(table_name, column_name, type)

  at = create_alter_table table_name
  at.add_column(column_name, type, **options)
  execute schema_creation.accept at
end

def add_columns(table_name, *column_names, type:, **options) # :nodoc:
  column_names.each do |column_name|
    add_column(table_name, column_name, type, **options)
  end
end
```

Without monkey patching, it does not seem possible (from what I can see) to provide a default set of values for the `options` argument.

Is this something that would be a valuable addition to the schema definitions?

### Expected behavior
The ability to know that `add_column` will mark the column as non-nullable by unless otherwise specified.

### Actual behavior
Cannot provide default options to schema statements which can result in follow up migrations.

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin19]

**Comment by composerinteralia** [comment]
Thanks for the issue. The issue tracker is mainly used for bug reports, rather than feature proposals. Your best bet may be to bring this up on the [rails core forum](https://discuss.rubyonrails.org/c/rubyonrails-core/5) instead. You can read more about this in the [contributing documentation](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark).

**Comment by TomasBarry** [comment]
@composerinteralia, will do - thanks.
