### ISSUE TITLE
Rails 6 active storage undefined method 'upload' for nil:NilClass

### ISSUE THREAD

**Issue by iheng** [rails/rails#40113]
### Expected behavior

image should be show up in storage directory 

### Actual behavior

![image](https://user-images.githubusercontent.com/6089263/91326968-d04d3000-e779-11ea-9858-45b1cbaa5d6f.png)

### System configuration
**Rails version*6.0.3.1*:
**Ruby version*2.5.8*:
more detailed issue I asked on [stack overflow](https://stackoverflow.com/questions/63591470/rails-6-active-storage-undefined-method-upload-for-nilnilclass)

**Comment by composerinteralia** [comment]
Thanks @iheng. Could you provide a link to a sample application that demonstrates this problem? That would make it a lot easier for people to help debug what is going on.

**Comment by iheng** [comment]
@composerinteralia , it's in my local environment. I don't have a link.

**Comment by composerinteralia** [comment]
Without a way to reproduce this on my own machine it may be difficult for me to help much. If you could create a new Rails application, copy over just enough code to reproduce the failure, and then push that up to a public repo, that would help a lot. If you are unable to do that, a full stack trace may help somewhat (it looks like the stack trace in the screenshot you provided is cut off a bit). Otherwise there is not much to go by here. While it is possible there is a bug in Rails here, it might also be a bug in some part of your application that I can't see.

Thank you!

**Comment by iheng** [comment]
@composerinteralia  it's wired. In the demo I just created. I can't reproduce the error. it's my app have some wired bugs
