### ISSUE TITLE
PostgreSQL inet column - wrong behaviour

### ISSUE THREAD

**Issue by vihai** [rails/rails#40138]
Hello, I'm referring to auto-closed issue #14857 

This problem is still present and makes inet type unusable when containing interface addresses because the host part is zeroed, so the value gets corrupted.

The problem lies in IPAddr which does not semantically distinguish between IP addresses, IP Interface Addresses (address+length), IP Networks (prefix+length) and tries to use a single class for different entities and for some reason thinks it is okay to clear the host part of an address+length.

Is there a way to, at least, override the default mapping and use a custom class for inet/cidr types?

**Comment by composerinteralia** [comment]
Thanks for bringing this back to life. Not much has changed since that last issue was first opened—Ruby's `IPAddr` doesn't expose the host bits, so there is not much we can do here unless we either fix that in Ruby or move to another gem, like https://rubygems.org/gems/ipaddress. Moving to another gem seems a bit more challenging, since folks might be relying on having `IPAddr` objects returned.

In the meantime, as a workaround, you might be able to create your own custom type by inheriting from the [Inet type](https://github.com/rails/rails/blob/7101489293ece071013417aeed2da3aa1b0927c9/activerecord/lib/active_record/connection_adapters/postgresql/oid/inet.rb) and using another library to get the correct behavior. I think you would then need to [register the type with Active Record](https://api.rubyonrails.org/classes/ActiveRecord/Type.html#method-c-register), like we do in [the postgres adapter](https://github.com/rails/rails/blob/7101489293ece071013417aeed2da3aa1b0927c9/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L958).
