### ISSUE TITLE
Proposal: make class attribute generated predicate check for presence

### ISSUE THREAD

**Issue by Drenmi** [rails/rails#40134]
### Steps to reproduce

Given the following class attribute:

```ruby
class_attribute :things, default: []
```

ActiveSupport will generate a predicate method `#translated_attributes?`, which in this case will always be `true`, due to the implementation using `!!value` to infer the result. My proposal is to instead use `#present?` as the canonical way. This would work better collection primitives (and potentially even user defined classes which implement custom `#present?` semantics.)

### Expected behavior

```ruby
klass.things
# => []

klass.things?
# => false
```

### Actual behavior

```ruby
klass.things
# => []

klass.things?
# => true
```

### System configuration

**Rails version**: Rails 6.0.3.2

**Ruby version**: Ruby 2.6.6p146

**Comment by composerinteralia** [comment]
I can see how a presence check might be useful here, but would be concerned about backwards compatibility. It we change this it would probably have to be configurable, defaulting to the new behavior on new apps but opt-in for existing apps.

Within Rails itself I don't think it would make any difference, since most of the uses of the predicate method within Rails are for booleans (the only exception I found was `driver?` in the [system test code](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/system_test_case.rb#L120), and a presence check would work fine as well.)
