### ISSUE TITLE
Could not retrieve association when used enum for reference column

### ISSUE THREAD

**Issue by keymastervn** [rails/rails#40142]
### Steps to reproduce

Running this enum_on_association test 
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.3"
  gem "sqlite3"
  gem "minitest-hooks"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :topics, force: true do |t|
  end

  create_table :posts, force: true do |t|
    t.integer :topic_id
  end
end

class Topic < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  enum topic_id: {
    intro: 1,
    announcement: 2
  }

  belongs_to :topic
end

class BugTest < Minitest::Test
  include Minitest::Hooks

  def before_all
    @topic = Topic.create
    @topic.posts << Post.create!
  end

  def test_association_stuff
    assert_equal 1, @topic.posts.count
    assert_equal 1, Post.count
    assert_equal @topic.id, Post.first.topic&.id # failed
  end

  def test_association_with_joins # failed
    assert_equal @topic.id, Post.joins(:topic).first.topic&.id
  end

  def test_association_with_includes # failed
    assert_equal @topic.id, Post.includes(:topic).first.topic&.id
  end

  def test_association_with_includes_references # passed
    assert_equal @topic.id, Post.includes(:topic).references(:topic).first.topic&.id
  end
end
```

### Expected behavior
`assert_equal topic.id, Post.first.topic&.id` should pass. As association to retrieve the "intro" topic from `Post.first.topic` returns.
```sql
Topic Load (0.1ms)  SELECT "topics".* FROM "topics" WHERE "topics"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
```

### Actual behavior
`Post.first.topic` is loaded with `nil`

```sql
Topic Load (0.1ms)  SELECT "topics".* FROM "topics" WHERE "topics"."id" = ? LIMIT ?  [["id", nil], ["LIMIT", 1]]
```

### System configuration
**Rails version**: 6.0.3

**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin18]

**Comment by composerinteralia** [comment]
Thanks for the issue. 

What is going on here is that your `enum` [defines a `topic_id` attribute](https://github.com/rails/rails/blob/7101489293ece071013417aeed2da3aa1b0927c9/activerecord/lib/active_record/attributes.rb#L246-L251) with type [`EnumType`](https://github.com/rails/rails/blob/7101489293ece071013417aeed2da3aa1b0927c9/activerecord/lib/active_record/enum.rb#L117), which will cast the raw integer value to the enum value:

```rb
post = Post.new(topic_id: 1)
post.topic_id
#=> "intro"
```

But this is a problem for the `topic` association, which doesn't know anything about how to cast "intro" back to the corresponding integer value. You will notice that the query that gets put together is missing the id:

```diff
- SELECT "topics".* FROM "topics" WHERE "topics"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]] 
+ SELECT "topics".* FROM "topics" WHERE "topics"."id" = ? LIMIT ?  [["id", nil], ["LIMIT", 1]]
```

I am going to close this issue, since I wouldn't expect this to work. I don't think it makes sense for a column to be both a foreign_key and an enum.

**Comment by composerinteralia** [comment]
I will reopen and let others weigh in on whether this is supported behavior.
