### ISSUE TITLE
ActiveRecord `pluck(:name)` returning different number of results than without `pluck`

### ISSUE THREAD

**Issue by KNejad** [rails/rails#40164]
### Steps to reproduce

Have a Project model with a `has_many` improvements. Improvements and projects have a `name` column.

Run these 2 queries:

```
Project.includes(:improvements).where(improvements: { name: 'one' })
Project.includes(:improvements).where(improvements: { name: 'one' }).pluck(:name)
```

### Expected behavior

I expect each query to return the same number of results (i.e. running `#count` on them will return the same number)

### Actual behavior

The query with the `pluck(:name)` in it returns a different result set with many duplicates.

Without a pluck it runs this query:

```
SELECT DISTINCT "projects"."id" FROM "projects" LEFT OUTER JOIN "improvements" ON "improvements"."project_id" = "projects"."id" WHERE "improvements"."name" = $1 LIMIT $2
```

Followed by another long query to get all the actual data. However, thanks to the `DISTINCT` restriction, no duplicate data is returned.

With the `pluck(:name)` method, I get this query:

```
 SELECT "projects"."name" FROM "projects" LEFT OUTER JOIN "improvements" ON "improvements"."project_id" = "projects"."id" WHERE "improvements"."name" = $1 
```

Without a second query since no other data is required. However, because this is no longer using `DISTINCT` on the project ID, I am getting multiple results, even though I only have one project.

In my case I have a single project called "hello" with 5 improvements. 4 of which have the name "one" I expect to get an array equal to `["hello"]`, but instead I get `["hello", "hello", "hello", "hello"]`.

I understand WHY this is happening and it makes sense, but the expected behaviour from `pluck(:name)` is that it simply gets a single column from the query results, and does not alter the query itself. In this case it is completely changing what the query does.

**Note:** A temporary solution I am using is to convert the result set to an array and then plucking the results

### System configuration
**Rails version**: Rails 6.0.3.2
**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

## Reproducible script

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :name
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_pluck_does_not_effect_results
    post = Post.create!(name: 'hello')
    post.comments << Comment.create!(name: 'one')
    post.comments << Comment.create!(name: 'one')
    post.comments << Comment.create!(name: 'one')
    post.comments << Comment.create!(name: 'one')

    without_pluck = Post.includes(:comments).where(comments: { name: 'one' }).to_a.count
    with_pluck = Post.includes(:comments).where(comments: { name: 'one' }).pluck(:name).to_a.count

    assert_equal without_pluck, with_pluck
  end
end
```

**Comment by esparta** [comment]
Will be helpful if you can add a reproducible script for this issue: https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case

**Comment by KNejad** [comment]
Thanks @esparta, I just added the script

**Comment by tgxworld** [comment]
> I expect to get an array equal to `["hello"]`, but instead I get `["hello", "hello", "hello", "hello"]`.

I don't think this expectation is right if you look at the SQL query being executed. 

`SELECT posts.name FROM posts LEFT OUTER JOIN comments ON comments.post_id = posts.id WHERE comments.name = 'one'`

Since the query is doing a `LEFT JOIN` on `comments`, PG will actually return 4 rows so `pluck` is actually doing the right thing here. 

Going back to the original query of `Post.includes(:comments).where(comments: { name: 'one' }).to_a`, this is actually equivalent to `Post.eager_load(:comments).where(comments: { name: 'one' }).to_a` because a `where` clause is used with `includes`. Therefore, AR will only return a single `Post` instance but with the `Comment` instances already loaded into the collection proxy.   

Also, I don't think there should be parity between queries when using `pluck` because `pluck` does not create ActiveRecord objects but simply return the relevant rows from the query executed. 

Hopefully my explanation above helps :)

**Comment by KNejad** [comment]
@tgxworld yes of course if I look at the query being executed I expect to see what we are seeing. Which is why I explained in my original post how the queries change and return a different set of results. The problem is, based on the purpose of the `pluck` method, I would not expect it to have any effect on the records being returned other than extracting the specified column.

If you look at the docs for pluck (https://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-pluck) the purpose of the method appears to be to retrieve a single column rather than having to load a bunch of records just to get a single attribute. As in, the resulting query should end up being the same apart from the columns it returns. This is confirmed by the example showing the pluck should be used instead of `.map(&:name)`.

**Comment by tgxworld** [comment]
To clarify, are you saying that you expect `Post.includes(:comments).where(comments: { name: 'one' }).pluck(:name)` to return `["hello"]`?

**Comment by KNejad** [comment]
Yes, because without the pluck it would return only a single Post, so with the pluck I would expect it to return the name of that single post

**Comment by tgxworld** [comment]
That isn't how `pluck` works and is meant to work though. `pluck` does not create any ActiveRecord object and as per the documentation 

> Pluck returns an Array of attribute values type-casted to match the plucked column names, if they can be deduced

**Comment by KNejad** [comment]
Yes I understand that. The purpose of pluck is so that you don't have to load all the AR models when all you want is a single attribute. But I don't see why the internals of how pluck works matter here.

Without an understanding of how it works internally and just by reading the docs would you still say that you would expect it to return 4 strings (the same post name repeated for each comment a post has) even though I am calling `pluck` on the Post and not the Comment?

For me, whist I understand why it's returning 4 results and what's going on internally (to some extent) just by reading the docs I would expect a single result.

`pluck` here is altering the query being run by removing the `DISTINCT` constraint, and returning more results because of it, which isn't what I would expect.

In the end this isn't a big deal. it just seems to me that it should be doing something other that what it currently is, which is why I raised this issue. If you still think I'm completely misunderstanding the purpose of pluck then feel free to close the issue.

**Comment by tgxworld** [comment]
> Without an understanding of how it works internally and just by reading the docs would you still say that you would expect it to return 4 strings (the same post name repeated for each comment a post has) even though I am calling `pluck` on the Post and not the Comment?

It returns 4 strings because of `.includes(:comments).where(comments: { name: 'one' })` which does a `LEFT JOIN` on the comments table which has 4 records that matches the conditions. `pluck` simply takes the specified columns of all the rows and returns the array of type casted columns to the user.

**Comment by yoelblum** [comment]
I actually also don't understand why the first query does a `SELECT DISTINCT ` and the second doesn't , indeed pluck shouldn't really change the query right ?

**Comment by tgxworld** [comment]
When you use `pluck`, it is already changing the query because you're specifying that columns that you want to select directly from the database bypassing ActiveRecord.

**Comment by yoelblum** [comment]
@tgxworld You're right -
So I'll reiterate what I'm seeing here:
Given a relation with an includes, for example  `Post.includes(:comments).where(comments: { name: 'one' })` , should running pluck on that relation ever change the amount of records returned?  I'm not 100% sure of the answer. Maybe this is the correct behavior but we can be a bit clearer about what's returning during includes + pluck.
It may be happening here:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/calculations.rb#L189

**Comment by yoelblum** [comment]
I think this test shows the behaviour is intended 
https://github.com/rails/rails/blob/7387b85ebb4a3f2ba909009210fb3ca4302733cf/activerecord/test/cases/calculations_test.rb#L857

I'm not sure why though. Could be better documented, this isn't 100% intuitive.

`Project.includes(:improvements).where(improvements: { name: 'one' }).pluck(:name)` 
IMO Includes shouldn't have had any bearing here on the number of records returned since includes' job is to preload associations, but we're plucking from the parent model here and not the associations. In fact I would've even thrown a warning here, because what is the point of including an association and then plucking the parent model? Warning or not I don't see the sense of this behaviour.

**Comment by KNejad** [comment]
@yoelblum yeah I guess the includes doesn't make sense in the example case. I should have used `join` instead in this example.

Although for us there is a reason it's written like that. It's because there was a service written to do some fairly complicated queries (with a bunch of filters based on certain conditions) and we would then require all the included attributes at a later step.

I now had to write something else which needs all the same query filters and conditions, but instead of requiring all the data it only required a single column. So I simply called `SomComplexQueryService.call('conditionals').pluck(:name)`, expecting it to work since the service is supposed to return an association.

So I think there is a valid use for doing this even if it isn't the most optimal way of retrieving the data

**Comment by MaxLap** [comment]
`pluck` isn't the one doing special things, it's `includes` which does special things to try to have an intuitive behavior in the general case of getting records, this includes adding `distinct` in some situation. However, without being very wasteful it is basically impossible for `pluck` to return something that exactly matches what loading the records would do. (You would need to basically load the records, and then do a map(&:name) )

It's part of life. `includes` is a complicated beast as it touches eager loading. If you want to avoid those problems, the basic ActiveRecord only solution would be to use `joins` instead of `includes`. In this situation, it would fix your problem with pluck. If you also want eager loading to happen, then you would do add a `preload(:improvements)`.

```
Post.joins(:comments).where(comments: { name: 'one' }) #=> 4
Post.joins(:comments).where(comments: { name: 'one' }).pluck(:name) #=> 4
```

This way, you keep the filtering and the eager loading machinery distinct. They will both return the same thing, which is duplicates. This is because that's what `joins` does naturally.

You could get rid of those duplicated using `distinct`, but that can have unexpected side effects (what if you wanted some duplicated for a different `joins` for example.) A better solution is a tool that I made for the specific purpose of having conditions on associations: [activerecord_where_assoc](https://github.com/MaxLap/activerecord_where_assoc)

With it, you would have no duplicates from just trying to do filtering:
```
Post.where_assoc_exists(:comments, name: 'one')  #=> 1
Post.where_assoc_exists(:comments, name: 'one').pluck(:name) #=> 1
```

The gem has a [pretty detailed introduction](https://github.com/MaxLap/activerecord_where_assoc/blob/master/INTRODUCTION.md)
