### ISSUE TITLE
ActiveRecord queries are not caching for Model.all calls

### ISSUE THREAD

**Issue by John-Garrahan** [rails/rails#40208]
### Steps to reproduce
For a new Rails app -->
```
rails new cache_test
cd cache_test
rails generate controller Sample
rails generate model Sample title:string text:text
rails db:migrate
rails c
b = Sample.new(title: 't', text: 'text')
b.save
c = Sample.new(title: 'tr', text: 'texfdfdsfsdf')
c.save
follow steps below
```

On an existing app -->
In rails c
```
#initial query
@a = Sample.all
irb(main):001:0> @a = Sample.all
   (0.6ms)  SELECT sqlite_version(*)
  Sample Load (0.2ms)  SELECT "samples".* FROM "samples" LIMIT ?  [["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Sample id: 1, title: "t", text: "text", created_at: "2020-09-09 08:58:35", updated_at: "2020-09-09 08:58:35">, #<Sample id: 2, title: "t", text: "texfdfdsfsdf", created_at: "2020-09-09 08:58:41", updated_at: "2020-09-09 08:58:41">]>

#following call, notice it is not cached.
@a
irb(main):002:0> @a
  Sample Load (1.4ms)  SELECT "samples".* FROM "samples" LIMIT ?  [["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Sample id: 1, title: "t", text: "text", created_at: "2020-09-09 08:58:35", updated_at: "2020-09-09 08:58:35">, #<Sample id: 2, title: "t", text: "texfdfdsfsdf", created_at: "2020-09-09 08:58:41", updated_at: "2020-09-09 08:58:41">]>

#ensuring there is a cache_key value:
irb(main):003:0> @a.cache_key
   (0.2ms)  SELECT COUNT(*) AS "size", MAX("samples"."updated_at") AS timestamp FROM "samples"
=> "samples/query-e79641255353450d9b7651e9dd3bd26c"

#NOTE - the cache seems to kick in after making a .length call
irb(main):006:0> @a.length
  Sample Load (0.2ms)  SELECT "samples".* FROM "samples"
=> 2
...
#cached
irb(main):007:0> @a.length
=> 2
...
#and now the full relation is cached. I would have expected this to happen on the first call to @a above.
irb(main):008:0> @a
=> #<ActiveRecord::Relation [#<Sample id: 1, title: "t", text: "text", created_at: "2020-09-09 08:58:35", updated_at: "2020-09-09 08:58:35">, #<Sample id: 2, title: "t", text: "texfdfdsfsdf", created_at: "2020-09-09 08:58:41", updated_at: "2020-09-09 08:58:41">]>
```

### Expected behavior
Calling `Model.all` should cache the results, according [to the docs](https://guides.rubyonrails.org/caching_with_rails.html#sql-caching).

### Actual behavior
We are not caching `Model.all` results.

### System configuration
**Rails version**: 
Tested on `5.2` & `6.0.3`

**Ruby version**:
`2.6.6`

**Comment by eileencodes** [comment]
Calling `@a` by itself doesn't load the relation since relations are lazily loaded. When you called `@a.length` that loaded and cached the relation. You could also call `@a.to_a` or any of the other methods that load the relation. Until you call a method on the relation, it's not actually loaded and therefore cannot be cached.

In the case of the docs example, that's in the context of the request. On your page when you display the relations, you'll be accessing them and they'll be cached.

Hope that makes sense!

**Comment by kashif-umair** [comment]
Hi @eileencodes, basically the behaviour is different here. When we run any code in rails console then lazy loading doesn't work. It loads the result of query in the variable because it prints the results after each line of code. For example this from above example.
```ruby
@a = Sample.all
irb(main):001:0> @a = Sample.all
   (0.6ms)  SELECT sqlite_version(*)
  Sample Load (0.2ms)  SELECT "samples".* FROM "samples" LIMIT ?  [["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Sample id: 1, title: "t", text: "text", created_at: "2020-09-09 08:58:35", updated_at: "2020-09-09 08:58:35">, #<Sample id: 2, title: "t", text: "texfdfdsfsdf", created_at: "2020-09-09 08:58:41", updated_at: "2020-09-09 08:58:41">]>
```

However, once the records are loaded in `@a` variable and printed on the console, calling `@a` second time should bring the results from the cache or it should not run any query at all but as you can see it's again running the query.
```ruby
irb(main):002:0> @a
  Sample Load (1.4ms)  SELECT "samples".* FROM "samples" LIMIT ?  [["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Sample id: 1, title: "t", text: "text", created_at: "2020-09-09 08:58:35", updated_at: "2020-09-09 08:58:35">, #<Sample id: 2, title: "t", text: "texfdfdsfsdf", created_at: "2020-09-09 08:58:41", updated_at: "2020-09-09 08:58:41">]>
```
If it is loading the `@a` variable from cache second time then the output query should have a mention of it. For example, `Sample Load (1.4ms) <query>` should have been `Cache Sample Load (1.4ms)  <query>`

---

A separate question, why the query has a `LIMIT` clause in it as we didn't call any limit on the model.

**Comment by eileencodes** [comment]
The cache for a relation and the query cache (the query cache is what produces the `Cache Sample Load (1.4ms) <query>` log lines) are 2 different things.

You will never see `Cache Sample Load (1.4ms) <query>` in the console because the query cache is installed in a middleware that is not installed in the console context.

**Comment by eileencodes** [comment]
The `LIMIT` comes from `inspect` https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L734-L741

**Comment by John-Garrahan** [comment]
@eileencodes thanks a lot for your explanation, it's a lot clearer now!
