### ISSUE TITLE
Rails 6 doesn't reload changed .erb files in dev mode on Docker (at least on Windows)

### ISSUE THREAD

**Issue by avdi** [rails/rails#40332]
I'm posting this here mainly to document the fact that after trying a number of suggested folk remedies (evidently a LOT of people have issues with file reloading in Docker), the one that worked was this one, via [Ron Williams](https://twitter.com/ron_a_williams/status/1312895406473240577), in an initializer:

```ruby
module ActiveSupport
  class EventedFileUpdateChecker
    private
      def boot!
        Listen.to(*@dtw, force_polling: true, &method(:changed)).start
      end
  end
end
```

I don't pretend to understand HOW this works. Feel free to delete this, incorporate it into another issue, whatever, I just want to capture the magic spell that works, in case someone wants to make it more accessible.

**Comment by alexrudall** [comment]
Thank you Avdi! This is working for me on macOS 10.15.7 / Docker 19.03.13 / Rails 6.0.3.4 when nothing else did.

**Comment by geeksam** [comment]
Was experiencing the same behavior on MacOS 10.15.3 / Docker 19.03.13 / Rails 6.0.2.1, and this incantation fixed it for me as well.  Thanks, @avdi!

Note:  in config/environments/development.rb, changing `config.file_watcher` from `EventedFileUpdateChecker` to `FileUpdateChecker` also fixed the behavior.  IDK if EventedFileUpdateChecker has any advantages over FileUpdateChecker if the former is forced to poll, so maybe just using the non-evented class is an equivalent solution?  The change is certainly less scary.  :)

**Comment by avdi** [comment]
@geeksam yeah I've been meaning to check out one of the less invasive configuration-driven solutions I've seen since. The original I posted is just the first solution I tried that actually worked.

**Comment by masak2009** [comment]
This is works for me on Ruby on Rails 6.1 with Ruby 2.6.5 under Debian12 as Virtual Machine with "shared" project folder from MacOS:

Rails has in config/development.rb:
```
config.file_watcher = ActiveSupport::EventedFileUpdateChecker
```

but for me works this configuration (using FileUpdateChecker with reload_classes_only_on_change):
```
config.file_watcher = ActiveSupport::FileUpdateChecker
config.reload_classes_only_on_change = false
```

For my issue the problem is that Rails can not detect nicely file changes on "shared folder". Does not matter if it's some "custom VM solution" of simple solution like using SAMBA sharing. Both works weird with Rails default config. This weird behavior is there from Rails 3 (first old project when i saw this behavior).

Would be nice to add some better solution or some simple switch "reload everthing on development". I have super fast SSD and i notice no change of speed when everything is standart way cached or reloaded every time from SSD drive.
