### ISSUE TITLE
Model.all() added limit 11 to the collector 

### ISSUE THREAD

**Issue by akhilravuri1** [rails/rails#40415]
### Steps to reproduce

Create a sample project using rails new app 

generated a model using rails generate.

Inserted few rows into the table and tried to retrieve the data using Model.all() in the rails console.

### Expected behavior

Running via Spring preloader in process 8292
Loading development environment (Rails 6.0.3.4)
irb(main):001:0> Tool.all()
  Tool Load (1.1ms)  **SELECT tool.\* FROM tools**

### Actual behavior

Running via Spring preloader in process 8292
Loading development environment (Rails 6.0.3.4)
irb(main):001:0> Tool.all()
  Tool Load (1.1ms)  **SELECT tools.\* FROM tools FETCH FIRST 11 ROWS ONLY**

### System configuration
**Rails version**: Rails 6.0.3.4

**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**Comment by p8** [comment]
Hi @akhilravuri1,

This is by design. The console calls `inspect` on `Tool.all` to show the output.
Inspect on relation is limited to prevent accidentally retrieving a huge amount of records from the database:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L734-L741
If you call `Tool.all.to_a` the limit is removed.

**Comment by akhilravuri1** [comment]
@p8  Thank you so much 
Able to retrieve all the using Tool.all.to_a
-Akhil

**Comment by p8** [comment]
Glad I could help 😄

**Comment by akhilravuri1** [comment]
@p8  Sorry to ask you but if possible can you please help me with this https://github.com/rails/rails/issues/40410

I have been trying for a long time but no progress.

Thanks,
Akhil
