### ISSUE TITLE
ActionText custom attachments disappear when secret_key_base changed

### ISSUE THREAD

**Issue by Maxhou00** [rails/rails#40435]
### Steps to reproduce
Create a Trix attachment by the trix api with a generated `sgid` from 

```
const attachment = new Trix.Attachment({content, sgid})
            _this.element.editor.insertAttachment(attachment)
```
From `ActionText::Attachable attachable_sgid`

([All can be reproduce with the Railsconf2020 video of Chris Oliver)](https://railsconf.com/2020/video/chris-oliver-advanced-actiontext-attaching-any-model-in-rich-text)

### Expected behavior
Generate a custom `trix-attachment` in a rich_text

### Actual behavior
This part is working well but the problem is every attachment will disappear when the `secret_key_base` is changed.

### System configuration
**Rails version**: Rails 6.0.3.3

**Ruby version**: ruby 2.5.3p105

**Comment by excid3** [comment]
Since they are are signed GlobalIDs, they'll need to be re-signed with the new key and saved in the db. If you simply change the secret_key_base, the old IDs can't be verified since they weren't generated with that key. 

Would probably be good to add to the docs how to rotate the ActionText attachment sgids. We already have one for rotating cookies: https://guides.rubyonrails.org/security.html#rotating-encrypted-and-signed-cookies-configurations

**Comment by rafaelrpbelo** [comment]
> Since they are are signed GlobalIDs, they'll need to be re-signed with the new key and saved in the db. If you simply change the secret_key_base, the old IDs can't be verified since they weren't generated with that key.
> 
> Would probably be good to add to the docs how to rotate the ActionText attachment sgids. We already have one for rotating cookies: https://guides.rubyonrails.org/security.html#rotating-encrypted-and-signed-cookies-configurations
> 
> A related PR for ActiveStorage: #39623

@excid3 I'm not sure if it's possible to rotate it. The **sgid** and **urls** are included in `ActionText::Attachment` that's inside of `ActionText::Content` as a node, in other words, they're hardcoded there.

IMHO If you want to change this information you need the old secret_key_base, in order to read the nodes, then you must update them based on the new secret_key_base.

_FYI: I couldn't do that so far._

**Comment by krsyoung** [comment]
@rafaelrpbelo did you ever find a way around this? We rotated our `secret_key_base` this weekend and eded up with a big surprise when all images 404'd :( 

Looks like https://github.com/rails/rails/pull/39623 didn't make it.

**Comment by rafaelrpbelo** [comment]
> @rafaelrpbelo did you ever find a way around this? We rotated our `secret_key_base` this weekend and eded up with a big surprise when all images 404'd :(
> 
> Looks like #39623 didn't make it.

@krsyoung I hope you have the old `secret_key_base`, otherwise, you can't revert it, cause all text nodes were signed with it, and now you can't even download the images to upload to your storage with a fresh URL. Maybe, you could try to parse your `ActionText::Attachment`s matching by filename or id on your storage, then build a new URL to replace those existing ones, but that's going to take a lot of work. Lmk if you got it. :)
