### ISSUE TITLE
Parallel Testing in Windows throws Bug: ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint “xxx_xxxx_xxxx_pkey”

### ISSUE THREAD

**Issue by jeydurai** [rails/rails#40496]
https://stackoverflow.com/questions/64592173/ruby-on-rails-testing-activerecordrecordnotunique-pguniqueviolation-erro/64608237?noredirect=1#comment114244132_64608237

**6.0.3.2**:

**Comment by eileencodes** [comment]
I don't think this is a Rails bug because the threaded version of parallel testing entirely skips Rails and is just a wrapper around minitest's threaded parallelizer. See https://github.com/rails/rails/blob/5cfd58bbfb8425ab1931c618d98b649bab059ce6/activesupport/lib/active_support/test_case.rb#L84

The threaded version doesn't create any databases, nor does it use DRB. This is either a bug in the application or something up with how minitest parallelizes processes.
