### ISSUE TITLE
Date.yesterday returning incorrect result

### ISSUE THREAD

**Issue by silverdr** [rails/rails#40507]
### Steps to reproduce
1. start Rails console
1. Enter `Date.today`
1. Enter `Date.yesterday`

### Expected behavior

The returned dates should differ by one day and the 'yesterday' should return yesterday's date rather than the day before yesterday one

### Actual behavior

```
>> Date.today
=> Mon, 02 Nov 2020
>> Date.yesterday
=> Sat, 31 Oct 2020
```

### System configuration
**Rails version**:
"5.2.3"

**Ruby version**:
"2.5.7"

**Comment by BKSpurgeon** [comment]
@silverdr looks like you're right! 

I looked askance at this problem at first, but below is some code that seems to replicate what you have suggested above. I'll paste it below for everyone's benefit.

The next step involves hopefully solving the problem.

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

  # Activate the gem you are reporting the issue against.
  gem "activesupport", "6.0.3"
  gem 'tapping_device'
  gem "byebug"

end

require "byebug"
require "active_support"
require "active_support/core_ext"
require "active_support/testing/time_helpers"
require "minitest/autorun"
require "date"

class BugTest < Minitest::Test
  include ActiveSupport::Testing::TimeHelpers

  def test_yesterday_is_nov_1
    # let's go back in time to November 2
    travel_to Time.new(2020, 11, 02, 01, 04, 44)

    Time.zone = "UTC"

    today = Date.today
    yesterday = Date.yesterday

    byebug
    # we want yesterday to be Nov 1
    # but it is, for some reason, Oct 31
    # good news is that
    # we have a reproducible bug report

    refute (today - yesterday > 1)
  end
end

```

**Comment by silverdr** [comment]
@BKSpurgeon thank you for having a look at the issue and taking time to reproduce! Yes, I can confirm that it happens only in some cases, most probably on [a] specific date(s) while non-UTC time is in effect.

**Comment by BKSpurgeon** [comment]
The issue seems to be (there are many ways of identifying the issue - so perhaps be forewarned) that `Date.today` is a ruby method that is not monkey patched by [ActiveSupport](https://github.com/rails/rails/blob/fe76a95b0d252a2d7c25e69498b720c96b243ea2/activesupport/lib/active_support/core_ext/date/calculations.rb#L38). This could perhaps be argued as expected behaviour, which begs the question: what exactly should Rails programmers expect?

To get the answer that you are looking for, consider using `Date.current` instead of `Date.today`.

Or the other possibility to handle this type of situation is to, perhaps monkey patch `Date.today`, perhaps with an alias, so that it returns `Date.current`.

**Comment by silverdr** [comment]
To clarify - the problem I encountered was with `Date.yesterday`. At that time, `Date.today` returned correct date, according to the current timezone (concept, which humanity should have ditched long ago, BTW). I wouldn't call making it return an incorrect one, in line with `Date.yesterday` a solution :-) Or I didn't understand you correctly above.

**Comment by BKSpurgeon** [comment]
- The problem is that apples are being compared with oranges, viz:
- "today" and "yesterday" have different meanings, according to the time zone you place them in. "Today" in an +11:00 time zone is 2020-11-5, whereas yesterday in Chicago time might be: 2020-11-3. Accordingly, if you are going to use "today" and "yesterday", in order to get consistent results, you must use the _same_ timezone.

```ruby
    today = Date.today # this should be your local time zone - this is a ruby method
    yesterday = Date.yesterday # UTC timezone - unless otherwise set
```

Rather, one should adopt:

```ruby
   today = Date.current # use .current not .today
   yesterday = Date.yesterday 
```
....or to otherwise set a common timezone.

The behaviour seems to be expected. But it begs the real question:

**Q:** Should Date.today be monkey patched in ActiveSupport (e.g. as an alias of Date.current)?

**Comment by okuramasafumi** [comment]
FYI: `rubocop-rails` gem provides `Date` cop that warns us when we use `Date.today` and suggests us to use `Date.current` instead.
https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsdate

**Comment by gazayas** [comment]
Using `rubcop-rails` to ensure `Date.current` is used seems like a good idea, but it also appears that Active Support uses the `Duration` class to handle `Time` calculations. I guess the question would be whether you want to use the `Date` class specifically, or if the `Time` class will work, since they're different objects.

The [documentation](https://guides.rubyonrails.org/active_support_core_extensions.html) shows that methods like `from_now` and `ago` use `Time.current` to return a value that takes the time zone into consideration. Again, these are methods from the `Duration` class.

From the source code:
```ruby
# Calculates a new Time or Date that is as far in the future
# as this Duration represents.
def since(time = ::Time.current)
  sum(1, time)
end
alias :from_now :since
alias :after :since

# Calculates a new Time or Date that is as far in the past
# as this Duration represents.
def ago(time = ::Time.current)
  sum(-1, time)
end
alias :until :ago
alias :before :ago
```

So if you want to calculate yesterday, you could write
```ruby
1.day.ago # Returns a ActiveSupport::TimeWithZone object
1.day.ago.to_date # Returns a Date object
```

Each would return values like these, respectively:
```
Mon, 16 Nov 2020 14:43:07 UTC +00:00
Mon, 16 Nov 2020
```
