### ISSUE TITLE
Action Controller 12.2 RESTful Downloads document query 

### ISSUE THREAD

**Issue by louise-r-blue** [rails/rails#40519]
Sorry did not know where else to query this as I may be mis-reading the Docs

In the docs [https://guides.rubyonrails.org/action_controller_overview.html#restful-downloads](url) in the section 12.2 RESTful Downloads some of which I copy and paste here for clarity

```
class ClientsController < ApplicationController  
# The user can request to receive this resource as HTML or PDF.  
def show    
  @client = Client.find(params[:id])    
    respond_to do \|format\|
    format.html
    format.pdf { render pdf: generate_pdf(@client) }    
  end
end
--
```
From the docs the private ` generate_pdf` method 

```
def generate_pdf(client)
  Prawn::Document.new do
    text client.name, align: :center
    text "Address: #{client.address}"
    text "Email: #{client.email}"
 end.render
end
```

Question.

would this not create an exception like the following?

`Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action...`

Only I know I have used similar code today except with the Grover gem and I get the above error so I change my controller action to 
```
...
respond_to do |format|
  format.html
  format.pdf { generate_pdf(@invoice) }
end
...
```

**Comment by composerinteralia** [comment]
The example looks OK to me. The `render` method inside `generate_pdf` is a [Prawn method](https://github.com/prawnpdf/prawn/blob/9668b0fcc1b7f08be5c259ec62253b10fc07ccc0/lib/prawn/document.rb#L395) that returns the pdf as a string, so that has nothing to do with Rails rendering. We then take that string and render it inside of the pdf format block.

I'm not sure your final example would work—it looks like it would generate the pdf string and then do nothing with it, rendering no content at all (i.e. a 204 response). You may well have had a double render in your application previously that was fixed when you stopped rendering inside the pdf format block.

Since I think the example holds, I'm going to close this issue for now. Thank you!
