### ISSUE TITLE
ActionDispatch::Cookies::CookieOverflow not triggering when storing values over 4KB in session

### ISSUE THREAD

**Issue by seebq** [rails/rails#40551]
### Steps to reproduce

Set something in the default session:

```
def index
  session[:value_over_4kb] = "a" * 4096
  session[:one_more_thing] = "such as an oauth token or something important"
end
```

In the view, show it:

<%= debug session %>

You will not see the value for  `session[:one_more_thing]` and no CookieOverflow is thrown.

I can create a sample app if necessary.

### Expected behavior

If using the default CookieStore to store session variables, if one sets a value in the session that will overflow, the application should throw a CookieOverflow error.

### Actual behavior

Putting larger than 4KB of data will simply not put it the values in the session on the client side.  It will show up on the server side, but will not persist to the browser.

### System configuration
**Rails version**: gem 'rails', '~> 6.0.3', '>= 6.0.3.2'

**Ruby version**: ruby '2.7.1'

**Comment by seebq** [comment]
OK, I take it back, it's doing it in development, but not on production.  Should production throw an error/exception, or just silently fail?

<img width="1065" alt="Monosnap-e8qjz-2020-11-05-12-50-39" src="https://user-images.githubusercontent.com/220/98277696-a5473f80-1f65-11eb-9134-bf942ada09f6.png">

**Comment by kinduff** [comment]
Bumping this, and seconding this. This is happening to us with a really long URL.

We don't really need to use a different store since this was really an attack. We want to rescue this exception or modify the headers, but we are unable to do so, any recommendations?

**Comment by toomanyjoes** [comment]
I too ran into this and would like to be able to rescue and handle this error but I am not able to.

**Comment by dmitry** [comment]
One of the solutions is it put Middleware before `middleware.insert CookieShrinkerMiddleware, ::ActionDispatch::Cookies` and in this `CookieShrinkerMiddleware` you can have your own logic with `rescue ActionDispatch::Cookies::CookieOverflow` and shrink some values before continue.

Might be better solution is to prevent writing cookies if they are more than 4kb.

**Comment by kinduff** [comment]
Gonna test that out @dmitry thanks for the tip.

I agree that we should avoid doing that, but sometimes it's out of our control like the back URL from Devise, or some other cookie we might need for tracking.

If I understand correctly, exceptions rised from a middleware cannot be rescued in an application level right? Because the execution stops in the middleware and never arrives to the application.

**Comment by seebq** [comment]
That's why I originally filed this, it was out of our control as it was from devise + auth0 that was making our cookie too big.

**Comment by dmitry** [comment]
@kinduff @seebq there cannot be a solution in terms of client-side encrypted session storage. The only solution in this case (when URL is too big) is to store the sessions in the database (redis/memcache/postgres): https://github.com/redis-store/redis-rails or https://github.com/rails/activerecord-session_store. I guess truncation is not the case because you would like to store it for the later redirection or verification.

**Comment by seebq** [comment]
Agree, completely @dmitry.  That was the solution we ended up doing, but it was news to us that we needed to do it, because it a) wasn't our library that was stuffing too much in the client-side cookie, and b) never threw an error, just silently ate it in production.  Was hard to catch too as it was an auth0 library that used a production auth gateway.

**Comment by seebq** [comment]
My original issue should have been re-filed -- and I guess the question remains -- if the cookie is overflowed in production, should it silently eat it, or fail.  All my reading of the code says it should raise, and even tests exist to do so:

https://github.com/rails/rails/blob/43e29f0f5d54294ed61c31ddecdf76c2e1a474f7/actionpack/test/dispatch/cookies_test.rb#L796

But unknown why it never actually raised and 500-errored in production.  I think this ticket should be closed, no-op, as it's clear what the solution is, my beef was not knowing why it never bubbled up as a 500 error in production.

**Comment by jebw** [comment]
I may have found why this isn't triggering an exception when over 4kb - this appears to be a discrepancy between how the browser and the cookie jar is computing the session size

I currently have a cookie on `localhost` which I cannot write to, but which is also not triggering `CookieOverflow`. I've vendored rails, and modified `EncryptedKeyRotatingCookieJar#commit` to `puts` its data and what it thinks the cookie size is

Rails computes size as 4012 bytes - _but_ firefox 112.0.2 is rejecting the cookie as being over 4096

I'm guessing a bit but when I look at the network response, the `Set-Cookie` header value contains more content then rails is using for its size calculation 

- there is also the cookie name
- flags SameSite, HttpOnly
- the cookie's value is also using a different encoding, eg `%2F` instead of `/`

If I add in the other data and substitute `/` for `%2F` in the cookie data then I compute bytesize as 4209, but rails fails to raise an exception because it computes cookie size as 4012

If I change my test code to increment the session in large blocks it does then trigger a `CookieOverflow`

**Comment by skipkayhil** [comment]
@jebw can you open a new issue with reproduction steps? I agree what you describe sounds like a bug, but old/closed issues tend to not get much attention

**Comment by Nathan-Heller** [comment]
Just ran into this issue myself in production, on firefox.
