### ISSUE TITLE
ActiveRecord issues saving Infinity with Timezones

### ISSUE THREAD

**Issue by lcx** [rails/rails#40595]
This kind of looks like https://github.com/rails/rails/issues/17971 

### Steps to reproduce
Create a model with these fields 

```ruby
class CreatePhones < ActiveRecord::Migration[6.0]
  def change
    create_table :phones do |t|
      t.string :number
      t.datetime :routing_start_date
      t.datetime :routing_end_date
      t.timestamps
    end
  end
end
```

in Rails console assign infinity to a datetime field

```ruby
phone = Phone.new
phone.routing_start_date = DateTime::Infinity
```

### Expected behavior

Timestamp should be infinity.

```ruby
phone.routing_start_date #=> Infinity
```

### Actual behavior
The timestamp is converted to nil 

```ruby
phone.routing_start_date #=> nil
```

same applies to `Float::INFINITY` 

If however I assign 'infinity' as string, it is correctly converted to Infiniy in Activrecord. 
Assigning the same value back to itself also converts it to nil 

```ruby
phone.routing_start_date = 'infinity'
phone.routing_start_date.class #=> Float
phone.routing_start_date = phone.routing_start_date
phone.routing_start_date.class #=> NilClass
```

It also works if I disable time zone support. 

```ruby
  config.time_zone = 'Europe/Vienna'
  config.active_record.default_timezone = :local
  config.active_record.time_zone_aware_attributes = false
```

### System configuration
**Rails version**: 6.0.1

**Ruby version**: 2.6.5p114 + 2.7.2

**Comment by tahsin352** [comment]
I have checked it and it's properly gives datetime:infinity
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails", branch: "master"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
    t.text :description
    t.datetime :routing_start_date
    t.datetime :routing_end_date
  end

end

class Post < ActiveRecord::Base
  has_many :comments
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(name: [])
    post.routing_start_date = DateTime::Infinity

    assert_equal DateTime::Infinity, post.routing_start_date
  end
end

```

**Comment by composerinteralia** [comment]
Thanks for the reproduction script! It will fail if you set `ActiveRecord::Base.time_zone_aware_attributes = true`, like in the linked issue #17971.

**Comment by Mr0grog** [comment]
I hit this bug in a really frustrating way yesterday. When you call `.to_a` on a collection containing a record you already have an in-memory reference to with +/-infinity for a timestamp, it changes the field’s value to `nil` and marks the model as `changed?`, even though you haven’t touched it at all. I thought I was OK working around the issues here by using the string `'-infinity'`, but it turns out not.

Here’s a quick example (can provide a full script to repro if needed):

```rb
class Team < ActiveRecord::Base
  has_many :people
end

class Person < ActiveRecord::Base
  belongs_to :team
end

# ...

team = Team.create
person = team.people.create(earliest_time: '-infinity')
person.earliest_time
#=> -::Float::INFINITY   ...great!

# This causes problems, even though it looks like it shouldn't matter:
team.people.to_a

person.earliest_time
#=> nil    ...uh-oh
person.changed?
#=> true   ...uh-oh

# In my case, the :earliest_time field happens to be NOT NULL
# (so queries involving comparisons are easy), but that makes
# the problem even worse: if I update some other innocuous
# value, it raises an exception because it is now trying to
# set the field to NULL (even though it was originally fine and
# I haven't touched it).
person.update(name: 'Alice')
#=> ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "earliest_time" violates not-null constraint
```

This particular effect is triggered by [`ActiveRecord::Associations::CollectionAssociation#merge_target_lists`](https://github.com/rails/rails/blob/46337faa795fa40dedb1b9b906bec1793358d7f3/activerecord/lib/active_record/associations/collection_association.rb#L318-L346), but I don’t think anything is necessarily wrong there. This method updates every attribute in the model’s `@attributes` object with new data from the database, and the updated attribute then calls `#cast` on the new value & type, which is where the problem is — `cast` is failing to handle valid values from the DB.

It seems to me like the main issue here is that [`ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter#cast`](https://github.com/rails/rails/blob/46337faa795fa40dedb1b9b906bec1793358d7f3/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb#L17-L31) returns `nil` for any input it doesn’t know how to handle, unlike all the other logic around casting `DateTime`, which passes through unrecognized values without touching them. For example: https://github.com/rails/rails/blob/46337faa795fa40dedb1b9b906bec1793358d7f3/activerecord/lib/active_record/connection_adapters/postgresql/oid/date_time.rb#L7-L18

(I checked the whole hierarchy and they all behave similarly.)

In my own code, I overrode `ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter#cast` to handle `+/-::Float::INFINITY` specifically since that seemed safest, but it also seems to me like `map_avoiding_infinite_recursion` could be changed to return `value` instead of `nil` if `map(value)` yields `value` (lines 52-53). There might be some cases I’m missing though.

https://github.com/rails/rails/blob/46337faa795fa40dedb1b9b906bec1793358d7f3/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb#L17-L31

https://github.com/rails/rails/blob/46337faa795fa40dedb1b9b906bec1793358d7f3/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb#L50-L58

**Comment by pboling** [comment]
@composerinteralia 
> It will fail if you set ActiveRecord::Base.time_zone_aware_attributes = true

I am not sure if you were stating that as an indication that it is correct behavior, or works-as-designed, but regardless, it seems wrong, and also since https://github.com/rails/rails/issues/17971 was fixed I think this is a regression.

This is the git description from the commit that "fixed" the issue back in 2014:
```
PostgreSQL for example, allows infinity as a valid value for date time
columns. The PG type has explicit handling for that case. However, time
zone conversion will end up trampling that handling. Unfortunately, we
can't call super and then convert time zones.

However, if we get back nil from `.in_time_zone`, it's something we
didn't expect so we can let the superclass handle it.
```

It's clear that it should not be trampling it to `nil`, when `time_zone_aware_attributes = true`, but rather it should let a super class handle.

Do you agree this is a regression?

**Comment by ghiculescu** [comment]
> Do you agree this is a regression?

Yes. Here's a simplified test script.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Base.time_zone_aware_attributes = true

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime :date
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_with_time_zone_aware_attributes
    post = Post.create!
    post.date = DateTime::Infinity

    assert_equal DateTime::Infinity, post.date
  end
end
```

If you change line 23 to `false` it passes.

Do you have any idea how we could fix it in Rails?

**Comment by intrip** [comment]
@ghiculescu https://github.com/rails/rails/pull/42932 fixes this issue. Please note that it expects an instance of `DateTime::Infinity`, not the class itself.

**Comment by intrip** [comment]
Still relevant, as discussed in https://github.com/rails/rails/pull/42932#issuecomment-911666199 I'll make a PR to update the docs later on.
