### ISSUE TITLE
shallow: true, overriding custom URLs

### ISSUE THREAD

**Issue by gaurav945** [rails/rails#40669]
### Steps to reproduce
**Minor Description :**
While using `shallow: true`, get requests on the model on which its used, are not being handled by the proper controller action. However, instead of `shallow:true`, if I simply use `only: %i[index new create]`, then the code works as expected.

**How to reproduce :** 
In the routes.rb, define the routes as following : 
```
Rails.application.routes.draw do
  resources :articles do
    resources :comments, shallow: true
  end

  resources :comments do
    collection do
      get 'all_comments'
    end
  end
end
```
In comments_controller.rb, define an action by the name of `all_comments`, which returns any random html content.
```
class CommentsController < ApplicationController
  def all_comments
    render :inline => "<%= 'all_comments' %>"
  end
end
```

### Expected behavior
When I hit the URL : http://localhost:3000/comments/all_comments, it should render the text 'all_comments'.

### Actual behavior
As of now, it says, `The action 'show' could not be found for CommentsController`, because, it processes the all_comments part of the URL as the id & passes it to a non-existent show action, instead of treating it as part of the collection url all_comments.
But, if I change `resources :comments, shallow: true`, to `resources :comments, only: %i[index new create]`, then the code works as expected.

### System configuration
**Rails version**: Rails 6.0.3.4

**Ruby version**: ruby 2.6.4p104

**Comment by composerinteralia** [comment]
Based on your description, this looks like the expected behavior to me.

```rb
  resources :articles do
    resources :comments, shallow: true
  end
```

This creates all the standard [CRUD endpoints](https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions) for articles, and [shallow nested endpoints](https://guides.rubyonrails.org/routing.html#shallow-nesting) for comments. One of those shallow nested comments endpoints is `

HTTP Verb | Path | Controller#Action
-- | -- | --
GET | /comments/:id(.:format) | comments#show

That route will match `/comments/all_comments`, with `"all_comments"` as the id. Since this route is defined before your `get 'all_comments'` route, it will always match first.

If you want the `get 'all_comments'` route to match that url, you can either get rid of the `comments#show` endpoint if you don't need it (which is what `resources :comments, only: %i[index new create]` would have done), or move `get 'all_comments'` higher in the routes file so it matches first.

**Comment by gaurav945** [comment]
@composerinteralia Okay, thats for clearing that up.
