### ISSUE TITLE
Rails 6.1.0.rc1 tests in my app error out with `SystemStackError: stack level too deep`

### ISSUE THREAD

**Issue by codeodor** [rails/rails#40698]
### Steps to reproduce
I am not sure how to reproduce this, but it has to do with switching database connections. I seem to recall this was an issue a while back too, but I don't quite recall which version. I will try to research it later. 

### Expected behavior
The tests should run and pass. 

### Actual behavior
Running my test suite, eventually all the tests fail with `SystemStackError: stack level too deep`

### System configuration
**Rails version**: 6.1.0.rc1

**Ruby version**: 2.6.5p114

**Comment by codeodor** [comment]
A little more info, but still not reproducible:

1. I tried to rig the app up to run against the first commit to 6.1, 8389f9902c3f0e984df17a77386493f856d7a1bb, and got the same error. So now I'm wondering if this is somehow triggered by all the other failures I'm getting before the stack overflow errors start.

2. Possibly related or unrelated, most of my app runs in the browser, but after clicking around a few times, I'll get a random error about the DB connection pool. My thought about it being related is the fact that it happens with the connection like the stack level too deep error does. I'll try to remember to capture the actual error next time I see it. I haven't seen it when clicking around for this update.

3. I can't seem to find the old issue I had a while back, so maybe it was resolved with a google search. But I seem to recall it happening when running in parallel -- maybe I need to change a config setting?

I'm going to try to reduce the number of other errors and noise in the tests and then report back.

**Comment by codeodor** [comment]
Hrmm... wish I could add that label back. Sorry!

**Comment by composerinteralia** [comment]
I added it back for you 😁

**Comment by codeodor** [comment]
The error reliably happens when I run `ActiveRecord::Base.establish_connection(snapshot_config)` after a lot of tests. 

I recall seeing a stack in some of the `connected_to` code. I wonder if we now need to do something else to make sure we drop old connections where we didn't need to before?

**Comment by codeodor** [comment]
Thanks @composerinteralia! I am sorry I was working on another update at the time! 😅

**Comment by eileencodes** [comment]
If you're running `ActiveRecord::Base.establish_connection(snapshot_config)` in a request or using the deprecated `ActiveRecord::Base.connected_to(database: DB) {}` in a request then I think this might be the error you'd see. It's not safe to establish a connection in the middle of a request which is partially why I deprecated the database kwarg in `connected_to`.

**Comment by codeodor** [comment]
@eileencodes Thank you for the info. We are indeed  doing that. We ran our own version of `connected_to` for many years but removed it in favor of the Rails 6 code that seemed better. We still have a couple of our own `establish_connection` calls that were not easy to remove.

We had the pre-Rails 6 code running well for many years (maybe since Rails 3, definitely 4) and as I recall, the only time we had a problem was when we attempted to switch to Puma and do concurrency with threads, rather than in processes. So we just went back to Unicorn. 

Has Rails 6.1 changed the default testing to use threads as well? If so, maybe I just need to find the config option to turn that off and then see if the tests run and pass like they used to. 

Regarding deprecation of the database kwarg: when you say it's unsafe, are you meaning specifically thread safety or something else? If something else, would we need to wrap our Rails requests in a Rack app that switched connections for us, or would you recommend something else? (We're not doing read/write sharding, ours are sharded by customer so we find out which database to use based on the URL -- but we keep user accounts in a common place so that people could be members of more than one "customer")

Thanks!

**Comment by eileencodes** [comment]
> Regarding deprecation of the database kwarg: when you say it's unsafe, are you meaning specifically thread safety or something else? 

Specifically I mean that every single bug report I got was it being used in requests for "sharding". It wasn't intended for that, nor does it work for that and so I eventually decided it wasn't worth the support cost. It shouldn't be used in requests because it establishes a new connection every time which means replacing a connection in a request. This could result in accidentally overriding the wrong connection.

> If something else, would we need to wrap our Rails requests in a Rack app that switched connections for us, or would you recommend something else? 

I'm not sure what you mean, there's a whole API for switching `role` and `shard` with `connected_to`. You shouldn't need a separate app for that.

> Has Rails 6.1 changed the default testing to use threads as well? 

Are you using parallel testing? Then yes it is using threads.

**Comment by codeodor** [comment]
No we are not using any parallel testing, unless it got enabled by default, but the guides don't say that it is enabled by default, so I suppose that is not the cause of the errors. I was hoping it would be as easy as switching off parallel testing. 

I will look into using the other method of connected_to without the database kwarg. In our case, it worked really well, so I was glad to see it in Rails. If I recall correctly we didn't use the other method because we don't want to edit the database.yml file each time we add a new database. But perhaps we can modify the config at run time and then use connected_to that way?

**Comment by codeodor** [comment]
Ok, I converted all of our direct calls to `ActiveRecord::Base.establish_connection(config)` and wrapped them with `ActiveRecord::Base.connected_to(database: db_name.to_sym)` instead. 

This seems to have removed all of the `SystemStackError: stack level too deep` errors when we run the tests.

But if the database kwarg is going away there, what should we be using to switch database connections instead?

I started trying to use role and shard, but the first thing that came up was when I tried to switch to a DB using that method, it seemed to want to switch my models which had different `connects_to` calls as well. Not completely sure that's what was happening, but I got an error that said `No connection pool for 'ActiveRecord::SessionStore::SessionBase' found for the 'my_app_development' shard.` and needed to quit for the day.

**Comment by codeodor** [comment]
I traced this down to the activerecord-import gem. My apologies!

**Comment by eileencodes** [comment]
Glad you found the issue! I have clarified one of your questions below.

> But if the database kwarg is going away there, what should we be using to switch database connections instead?

From other examples it looks like you're already using roles. Once you switch to the set of pools you need (ie reading) Active Record "just" figures out which connection to pick up from the pool based on the inheritance chain. For example if you have a model called `Dog` and `Dog` inherits from `AnimalsBase` which is an abstract class with a writing and reading connection, calling `connected_to(role: :reading) { Dog.first }` will query the database connected to the AnimalsBase reading role. Currently it's required to have explicit configurations and abstract classes for the connections for multiple databases. This will ensure connections are established on boot and Rails will pick up the ones you need when you switch roles/shards. 

There may be some use cases for establishing connections on the fly but we don't currently support that and the `database` kwarg for `connected_to` didn't technically support that either, it just "kind of" worked in some cases. Features that just kind of work in some cases are dangerous because they have unintended side effects and I didn't want to continue to support a buggy and confusing feature.

Good luck with the rest of your upgrade! 😊

**Comment by codeodor** [comment]
Thank you @eileencodes, I appreciate your guidance on this issue!

**Comment by s0kil** [comment]
I've just finished debugging a `SystemStackError - stack level too deep:` error, and turns out it was due to the [`meta_request`](https://rubygems.org/gems/meta_request) gem.

**Comment by ahmedsayedabdelsalam** [comment]
عليا النعمة framework متلصم
