### ISSUE TITLE
Rails 6.1 - problem with numericality validator

### ISSUE THREAD

**Issue by zhuravel** [rails/rails#40902]
### Steps to reproduce
This test passes on Rails 6.0.3.4 and fails on Rails 6.1.0:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", ARGV[0]
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "mysql2")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :purchases, force: true do |t|
    t.decimal :subtotal, precision: 5, scale: 2
  end
end

class Purchase < ActiveRecord::Base
  validates_numericality_of :subtotal, less_than_or_equal_to: 999.99
end

class BugTest < Minitest::Test
  def test_numericality
    purchase = Purchase.new
    purchase.subtotal = 999.999 # 999.991 should also cause a validation error

    assert_equal 1000.0, purchase.subtotal
    assert purchase.invalid?
    assert_equal ["must be less than or equal to 999.99"], purchase.errors[:subtotal]
  end
end
```

### Expected behavior
```
$ ruby active_record_gem.rb 6.0.3.4
# ...
1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior
```
$ ruby active_record_gem.rb 6.1.0
# ...
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: 6.1.0

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**MySQL version**: mysql  Ver 14.14 Distrib 5.7.32, for osx10.16 (x86_64) using  EditLine wrapper

**Comment by abhaynikam** [comment]
@zhuravel After some debugging, found that Rails 6.1 nows adds support for `scale` NumericalityValidator in commit: https://github.com/rails/rails/commit/f72f743dc380d6b4f3518a8a1047414499b5a6c2

In the reproduction script provided above, since `scale: 2` is used on column `subtotal`. The value `999.999` is parsed and converted to `999.99` before validation check is ran in the validator. 

https://github.com/rails/rails/blob/71bc41477da96bb05edc33c1b6a42203e6999667/activemodel/lib/active_model/validations/numericality.rb#L76-L78

**Comment by intrip** [comment]
@kamipo I'd like to create a PR for this, is it possible?

**Comment by intrip** [comment]
I think the key issue is the inconsistency between:
[the numericality validator](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/numericality.rb#L84) which uses `truncate(scale)` and the [the decimal type conversion](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/decimal.rb#L61-L62) which uses `round(scale)`.

What about making the behaviour consistent in both cases ? 
I propose to use `round` also in the numericality validator (rather than changing the type conversion) because looks like the smallest breaking change to me.

Also: using `round` instead of `truncate` would break edge cases tests using [greater_than_or_equal](https://github.com/rails/rails/blob/master/activerecord/test/cases/validations_test.rb#L190-L192) but using `truncate` will break edge cases for `less_then_or_equal` so I don't think there is a "better" approach, we just need to figure out which approach we decide to follow.

@kamipo @zhuravel WDYT?

**Comment by kamipo** [comment]
Ideally, `apply_scale` should truncate subsecond to me, but the rounding happened more than 5 years ago 4727a94c50e8bb371e9c9e7798a5ba0510320657, so I think the numericality varidator needs to respect it.

The numericality varidator is one of the most complex features, so I don't know yet how it can be fixed, as I haven't looked at it properly.

If I work on the fix, I would fix it to respect the typecasted value on the attribute as much as possible.

**Comment by intrip** [comment]
@kamipo thanks for the feedback! 
I'm on line with you: I'll work on a PR in order to update the numericality such that respects the typecasted value.
