### ISSUE TITLE
Rails 5.2 doesn't work with Ruby 3.0

### ISSUE THREAD

**Issue by st0012** [rails/rails#40938]
### Description

Ruby 3.0 introduced some [argument rule changes](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/), which are handled properly in Rails 6.0 and 6.1. But in Rails 5.2, we can still see issues in `active_record`'s `create_table` method.

### Steps to reproduce

This is part of the Rails' [bug report template for active_record](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 5.2.4"
  gem "sqlite3"
end

require "active_record"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end
```

### Expected behavior

It should work.

### Actual behavior

```
-- create_table(:posts, {:force=>true})
/Users/st0012/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:290:in `create_table': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /Users/st0012/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:871:in `block in method_missing'
        from /Users/st0012/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:840:in `block in say_with_time'
        from /Users/st0012/.rbenv/versions/3.0.0/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
        from /Users/st0012/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:840:in `say_with_time'
        from /Users/st0012/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:860:in `method_missing'
        from report.rb:22:in `block in <main>'
        from /Users/st0012/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-5.2.4.4/lib/active_record/schema.rb:50:in `instance_eval'
        from /Users/st0012/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-5.2.4.4/lib/active_record/schema.rb:50:in `define'
        from /Users/st0012/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-5.2.4.4/lib/active_record/schema.rb:46:in `define'
        from report.rb:21:in `<main>'
```

### System configuration
**Rails version**: `5.2.4.4`

**Ruby version**: `3.0.0`

### Other notes

[This refactoring commit](https://github.com/rails/rails/commit/b04c6339640d87b680f1975f3686fed0d885b1bc) solved the issue for Rails 6 and beyond. So I think a solution could be backporting this commit to the `5-2-stable` branch. Or if `5.2` versions will not be supported with Ruby 3.0, changing gemspecs to make that clear would be good as well.

**Comment by yahonda** [comment]
It should not work. You will need to use Rails 6.0.3 or higher with Ruby 3.

https://weblog.rubyonrails.org/2020/5/6/Rails-6-0-3-has-been-released/
> This version fixes warnings when used with Ruby 2.7.

**Comment by st0012** [comment]
@yahonda thanks for the reference! 
but I still think it'd be better to have it specified in gemspecs so users will notice in a more obvious way 🤔  
the release note also requires some extra thinking & context to understand why it means versions before Rails 6.0.3 won't support Ruby 3.0. and because it doesn't contain the word `3.0`, this won't pop up when searching with `Rails 5.2 Ruby 3.0` 😬

**Comment by jaredbeck** [comment]
> ..  So I think a solution could be backporting this commit to the `5-2-stable` branch. ..

According to the [Maintenance Policy](https://guides.rubyonrails.org/maintenance_policy.html), Rails 5.2 will only receive security patches. The policy doesn't _prevent_ them from backporting this, but it would be in line with the policy to decline.

Because many people will have questions about this, it might make sense to have a post on [Riding Rails](https://weblog.rubyonrails.org/) specifically announcing the incompatibility. Or, maybe people can just find this issue, as I did. :)

**Comment by rafaelfranca** [comment]
Thank you for the issue. Like already pointed Rails 5.2 doesn't receive any non-security fixes as stated in the Maintenance Policy and announced [in the Riding Rails blog](https://weblog.rubyonrails.org/2019/11/23/Rails-5-2-4-rc1-has-been-released/).

> but I still think it'd be better to have it specified in gemspecs so users will notice in a more obvious way

We can't predict when Ruby will break backwards, so at the time we release Rails if we specify in the gemspecs it means that we would have to release a new version of Rails just to allow a new version of Ruby, in case that new Ruby version worked fine with an old version of Rails, and that again would not happen since we don't release non-security releases for a few branches anymore. We prefer to allow users to find their software is not compatible than we having to give users the permission to upgrade, and that is why we don't specify any upper bound requirement for our dependencies, even Ruby.

I'm going to close this issue since changing Rails 5.2 to support Rails 3 goes against our Maintenance Policy, but I'll still review which changes are required, and maybe, if someone in the Core Team care enough to add support to Ruby 3.0, I can make a new release.

**Comment by joshuapinter** [comment]
> if someone in the Core Team care enough to add support to Ruby 3.0, I can make a new release.

If someone from the Core Team cares enough to review a PR, me and my team are happy to start writing the PR for your review. Let me know.

**Comment by rafaelfranca** [comment]
Review a PR, or even writing the patch is the easiest part. Dealing with the bugs and follow up hope people will have that you are going to keep updating a version of Rails that is years old is what matters here. Our policy is being very clear for the last 4 years. As soon a new minor or major version of the framework is released all older versions don't receive bug fixes anymore. That should be the expectation of the community. Anything different from that, is decided case by case, and without any promises.

**Comment by joshuapinter** [comment]
Understood and certainly agree on the long tail of maintenance costs.

Instead, we’ll spend that time on upgrading to Rails 6.

Thanks for the quick responses, especially during holiday season.
