### ISSUE TITLE
Rails 6.1 ARGV incorrect when used in templates

### ISSUE THREAD

**Issue by scratchoo** [rails/rails#40945]
We tested this multiple times, so this might be a bug with Rails 6.1 (with Rails 6.0 it works fine)

We have a template  "template.rb" file  with 

```
args = ARGV.size
throw args
```
if you run:

`rails new applica -d postgresql -m template.rb --key="value" --key2="value2" --key3="value3"`

you get uncaught throw 0 (UncaughtThrowError) ---> (which incorrect - Rails 6.1 only)

with Rails 6.0 you get the correct size

**Comment by jonathanhefner** [comment]
This is due to #38495.  We could forego clearing `ARGV`, but still isolate it via `dup` and `replace`.  But I'm not sure if we want to guarantee that the app generator will accept arbitrary CLI options.  For example, more than once I've wished the app generator would blow up when I type `--skip-webpacker-install` instead of `--skip-webpack-install`, rather than silently ignoring the erroneous option.

Would it be reasonable to convert your extra CLI options to environment variables?  e.g.:

```bash
$ KEY="value" KEY2="value2" KEY3="value3" rails new applica -d postgresql -m template.rb
```

That way you also would not have to parse them.

**Comment by scratchoo** [comment]
@jonathanhefner Thank you for your reply. The most important thing is to be able to pass parameters to the template, so yeah environment variables work just fine and they are a good alternative too :+1:

**Comment by rafaelfranca** [comment]
@jonathanhefner I think we should allow the template to have access to `ARGV` regardless we thing we should allow custom options or not. We could still blow up with custom options, but the template should be able to check the content of ARGV.

**Comment by rmcbarreto** [comment]
Hi,
I do not know if it is related, but after Rails 6.0.3.5, when I try to get the ARGV in an initializer from a rails app (specific in rails 6.1.3) I do not get any value, ARGV is nil. 
I tested for rails 6.1.0, 6.1., 6.1.2.1 and 6.1.3.
How can I get the arguments when starting the rails server (rails s -p 3001 -b 0.0.0.0) -> ['-p', '3001', '-b', '0.0.0.0']
If this is not related, please remove and close my comment.

**Comment by jonathanhefner** [comment]
@rmcbarreto That is also due to #38495.  However, parsing `ARGV` can be error-prone.  For example, all of the following commands use port 3001.

```bash
$ rails server -p 3001
$ rails server -p3001
$ rails server --port 3001
$ rails server --port=3001
$ PORT=3001 rails server
```

Could you share a bit more about your use-case?  Perhaps we could expose the necessary information in a more robust way.

**Comment by rmcbarreto** [comment]
I am migrating several Rails apps from 4.1.5 to the latest version 6.1.3. The apps depend on the opened port to do different tasks. So, in the initializer, I get the ARGV params to a variable to use elsewhere in the APP. 
So, when I do `rails server -p 3001` in rails 4.1.5 (it also works in 6.0.3.5) I get `["-p", "2222"]`. But now, in rails above 6.0.3.5, I only get an empty Array `[]`.

Example:
Old Rails 4.1.5 (also wors in version 6.0.3.5)

```
# rails s -p 2222
=> Booting Thin
=> Rails 4.1.5 application starting in development on http://0.0.0.0:2222
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
ARGV: ["-p", "2222"]
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:2222, CTRL+C to stop
...
```

New Rails 6.1.3
```
# rails s -p 3011
=> Booting Puma
=> Rails 6.1.3 application starting in development
=> Run `bin/rails server --help` for more startup options
ARGV: []
Puma starting in single mode...
* Puma version: 5.2.1 (ruby 3.0.0-p0) ("Fettisdagsbulle")
...
```

**Comment by jonathanhefner** [comment]
@rmcbarreto I understand the behavior you are seeing.  I was interested in the specifics of your use-case to determine if it is worth exposing the relevant information in a more robust way.  In any case, I have submitted #41611 to restore the previous behavior.  If you need a workaround in the mean time, you might consider launching the server with `PORT=2222 rails s`, and changing your initializer to use `ENV["PORT"]` instead of `ARGV`.

**Comment by rmcbarreto** [comment]
Using the values in `ARGV` I think it's just the old way of doing it and is universal. If possible I think it should be maintained. 
In my use case, it would be easier the migration if the `ARGV` option is maintained (and I have a lot of apps to migrate). But also I agree that sometime I will have to maybe start using the environment variable or another strategy. 
So I understand if the `ARGV` option is not maintained.

Anyway, thanks for the response @jonathanhefner
