### ISSUE TITLE
"Getting Started" does not mention Rails incompatible with Node 15?

### ISSUE THREAD

**Issue by sedubois** [rails/rails#41060]
### Steps to reproduce

As instructed in [Getting Started with Rails](https://edgeguides.rubyonrails.org/getting_started.html):
- on a machine with Rails 6.1.0, Node 15.5.1
- `rails new blog && cd blog && rails server`
- open http://localhost:3000

### Expected behavior

Web page shows fine.

### Actual behavior

Various webpacker issues are apparently observed: https://discuss.rubyonrails.org/t/pretty-astonishing/76850/16

In my understanding, Rails will install `@rails/webpacker 5.2.1` which depends on `node-sass 4.14.1`, which is [not compatible](https://www.npmjs.com/package/node-sass#node-version-support-policy) with Node 15. If correct it might be good to update the "Getting Started" guide to instruct against installing Node 15, and ideally have a way to enforce the Node compatibility in the front-end config itself (e.g. an `engine` section in package.json?).

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.6.3

**Node version**: 15.5.1

**Comment by gmcgibbon** [comment]
> Various webpacker issues are apparently observed

These are build errors related to Python 2 not being on the system. As far as I can see, the [support policy](https://www.npmjs.com/package/node-sass#node-version-support-policy) relates to which included binaries are compatible with what version. Since we don't mention Python as a requirement, the logical next step would be to simply fix the issue in webpacker, but then we may have the same problem for Node 14.

> If correct it might be good to update the "Getting Started" guide to instruct against installing Node 15, and ideally have a way to enforce the Node compatibility in the front-end config itself (e.g. an engine section in package.json?).

Most unix systems come with the build tools required to build the node-sass binary, which might warrant a warning for Node 15 users. I think if we add an `engine` section to the `package.json` it would be to specify the node version that generated the project.

It seems the latest webpacker has made sass support optional, and made the switch the dart sass, so this problem might be less of a problem for new users in the next release.

**Comment by yagudaev** [comment]
Beyond what was already said, there seems to be a missing test. 

If indeed version 15 cause all these issues for webpacker and it was release on [October 20](https://nodejs.org/en/about/releases/) we should know about it sooner.

It would be good to have a test run through setting up a basic rails app with the two major versions of node and latest versions of ruby and all gems in the gemfile. This will ensure beginners don't have to hit these problems.

I'd love to help there, but I need:
1. Help understanding our CI setup, we used to use buildkite right? Now it is github actions? Where is the config for that?
2. Any similar test examples in our existing test suite to use as a starting point?

**Comment by sedubois** [comment]
@yagudaev Adding tests would be great. AFAIK buildkite is used for tests and GitHub actions are for rubocop. If you add tests you should see the test results linked in the PR. @gmcgibbon tagged this issue with `railties` so maybe browsing tests in that directory would be a good starting point.

**Comment by gmcgibbon** [comment]
I tagged railties because the `package.json` template is there if we wanted to change that. Thinking further, I don't think that would really solve the issue here though. Any test/ci changes should go to [`rails/webpacker`](https://github.com/rails/webpacker) instead of rails/rails (here).

Looking at the [CI config](https://github.com/rails/webpacker/blob/master/.github/workflows/jest.yml), we don't run tests on Node 15. Since sass support is now optional, and using dart sass instead of node-sass, this won't be an issue in the next webpacker release. Regardless, I think it would be useful to add Node 15 to webpacker's CI config until it reaches EOL in April.

At this point, I think there's two action items:
1. Mention in the guides to make sure you have what's required for https://github.com/nodejs/node-gyp. Probably somewhere around [here](https://guides.rubyonrails.org/getting_started.html#installing-node-js-and-yarn).
2. PR a change to rails/webpacker to add Node 15 to the CI config

**Comment by sedubois** [comment]
@gmcgibbon item 2 has been [done](https://github.com/rails/webpacker/issues/2874) in webpacker.

**Comment by gmcgibbon** [comment]
See https://github.com/rails/webpacker/pull/2877#issuecomment-759594340. Unless I'm misunderstanding something, the constraint doesn't need to exist. I've submitted a patch to amend the constraint and add CI checks. Also given that the next release will not have the same node-gyp issues, I think now the backport doesn't make sense, sorry for the confusion.

On webpacker it seems wether or not my patch is accepted, the version constraint presently on master could also address the problem, so I think this can be closed. Thank you for the issue.
