### ISSUE TITLE
rails new fails at webpacker:install

### ISSUE THREAD

**Issue by f6p** [rails/rails#41103]
**rails 6.1.1**, **webpacker 5.2.1**

When creating new app, during execution of:

`rails  webpacker:install`

command fails with the output as follows:

```
Traceback (most recent call last):
	2: from bin/rails:2:in `<main>'
	1: from bin/rails:2:in `load'
/home/bill_gates/code/mighty_app/bin/spring:7:in `<top (required)>': undefined method `specs' for nil:NilClass (NoMethodError)
```
If I understand it correctly **bin/spring** cant load gem specs while being called outside of application directory.

**Comment by jonathanhefner** [comment]
@f6p You are running `rails new` with `--skip-bundle` or `--skip-gemfile`, yes?

This is because we now generate Spring binstubs when either of those flags are used, and `rails webpacker:install` tries to use those binstubs.  Before #39746, Spring binstubs weren't created when either flag was used, and the user would have to run `spring binstub` manually after creating the app.  (Though this was not documented.)  

I think it's probably questionable that we were skipping `spring binstub` but still running `rails webpacker:install` when those flags were used.  When using `--skip-bundle`, `rails webpacker:install` will fail if no appropriate version of `webpacker` is already installed.  When using `--skip-gemfile`, `rails webpacker:install` will always fail.

So the question is: should we continue trying to run `rails webpacker:install` anyway (with a solution like #41104), or skip `rails webpacker:install` and notify the user that they must run it manually?

**Comment by f6p** [comment]
Ah, thanks for clarification - everything makes a lot more sense now.

I wasn't giving `--skip-bundle` directly but I had long forgotten `.railsrc` with it. Now, as I see it skipping spring obviously makes  little sense (as well as my PR 😄 ).

I also think (as you suggested) that `rails webpacker:install` shouldn't be executed if bundle or gemfile are skipped. After all who knows if it will contain webpacker gem? It doesn't make sense to install webpacker if there is no webpacker in gemfile...

**Comment by f6p** [comment]
@jonathanhefner I updated PR. Now app generator skips webpacker task if called with either `--skip-bundle` or `--skip-gemfile`.

Yet still - after creating new app if `Gemfile` is not locked calling `webpacker:install` fails with method call on `nil` object. I'm not sure if there is better way to prevent this than safe navigating `Bundler.locked_gems` (as discussed in #41104).
