### ISSUE TITLE
Grammar Mistake on the website's main page

### ISSUE THREAD

**Issue by MusabShakeel576** [rails/rails#41130]
Hey there,
In the main page of Ruby on Rails website there is this sentence:
"Ruby on Rails is open source software, so not only is it free to use..."

I think the text should be "it is" not "is it".

![Screenshot_1](https://user-images.githubusercontent.com/46605319/104768638-cf9c5100-578f-11eb-9f61-b9b43601198a.png)

**Comment by composerinteralia** [comment]
I believe the sentence is correct, and English is strange.

I don't know enough about grammar to know exactly what to call this, but I found [an explanation](https://dictionary.cambridge.org/us/grammar/british-grammar/not-only-but-also):

> To add emphasis, we can use not only at the beginning of a clause. When we do this, we invert the subject and the verb:

In this case we invert "it is" to "is it" because it follows "not only" at the beginning of a clause. 🤷🏻‍♂️

FWIW, I am a native English speaker and I would always say "not only is it" and never "not only it is". The second one sounds strange to me.
