### ISSUE TITLE
ActiveRecord query using where() with an array results in SQL without "IN" clause.

### ISSUE THREAD

**Issue by key88sf** [rails/rails#41133]
### Steps to reproduce

With any standard ActiveRecord model (using `Customer` here as an example), issue the AR query:
`Customer.find([1, 10])`

### Expected behavior
I would expect the generated SQL to look like:
`SELECT * FROM customers WHERE (customers.id IN (1,2))`
(this is also what the Rails Guide lists: https://guides.rubyonrails.org/active_record_querying.html)

### Actual behavior
I get this SQL instead:
`SELECT customers.* FROM customers WHERE customers.id IN ($1, $2)  [[nil, 1], [nil, 2]]`

It does work, but when using an array with a lot of elements, this expands out to a query with many variables being substituted. Is this the intended behavior???

The same SQL is generated when using a `.where(id: [1,2])` syntax as well.

### System configuration
**Rails version**:
6.1

**Ruby version**:
2.6.3

**Comment by louim** [comment]
Hey @key88sf

I'm not sure what you mean by:
> without "IN" clause

The SQL you pasted contains an **IN** clause: `... WHERE customers.id IN ($1, $2)`. The reason you get a prepared statement with interpolated variable is because Rails need to sanitize the input. This is the expected behaviour. As for the performance, it was recently improved in https://github.com/rails/rails/commit/72fd0bae5948c1169411941aeea6fef4c58f34a9.

The reason you're seeing `[[nil, 1], [nil, 2]]` instead of `[["id", 1], ["id", 2]]` is a bug. A fix is pending here: https://github.com/rails/rails/pull/41068

**Comment by key88sf** [comment]
👍 Thanks for the explanation. Looking forward to the bugfix. Will close this issue.
