### ISSUE TITLE
Scoping and initializing with IN queries fails for enums

### ISSUE THREAD

**Issue by lipanski** [rails/rails#41295]
As [this comment](https://github.com/rails/rails/issues/40269#issuecomment-696769427) points out, enums are validated when set, not during the normal validation phase.

This triggers a side effect when initializing records via `scoping` while trying to match several enum variants in an IN query:

```ruby
class User
  enum role: %w(user admin)
end

User.where(role: %w(user admin)).scoping do
  # This fails with `ArgumentError: '["user", "admin"]' is not a valid role`
  User.new(role: "user")
end
```

More importantly, the `first_or_initialize` and `find_or_initialize_by` methods are affected in the same way.

In my opininon, `scoping` should only apply scopes of matching types - string columns get populated with string values, array columns get populated with array columns - though I bet that's not trivial.

Do you see any other way around this?

### Steps to reproduce

A full test case:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "6.1.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :role
    t.string :name
  end
end

class User < ActiveRecord::Base
  enum role: %w(user admin)
end

class BugTest < Minitest::Test
  def test_scoping_new
    user = User.where(role: %w(user admin)).scoping do
      User.new(role: "user", name: "name")
    end

    assert_equal "user", user.role
    assert user.save
  end

  def test_find_or_initialize_by
    user = User.where(role: %w(user admin)).find_or_initialize_by(name: "name") do |new_user|
      new_user.role = "user"
    end

    assert_equal "user", user.role
    assert_equal "name", user.name
    assert user.save
  end

  def test_first_or_initialize
    user = User.where(role: %w(user admin)).where(name: "name").first_or_initialize do |new_user|
      new_user.role = "user"
    end

    assert_equal "user", user.role
    assert_equal "name", user.name
    assert user.save
  end
end
```

**Comment by eileencodes** [comment]
I don't see how we could change `scoping` to make this work. The query is actually invalid - if you tried to do an INSERT with an IN it would fail even without `scoping` or `first_or_initialize`. (ie `User.create!(role: %w(user admin))`). I haven't spent much time in the `first_or_intitalize` code but I have been spending a fair amount of time in `scoping` lately. All it does is take the scope you applied as a `where` like it would on any other query. It simply merges in the scope the application supplied. We don't do any checking of values so the suggestion to only apply scopes of matching types would require a complete rework of this feature (and likely isn't that feasible anyway).

I'm leaning towards closing this because I don't think it's a bug, it's the behavior I would expect - the scoping supplied is the scoping used in the create and that's why it breaks - it's not valid for create.

**Comment by lipanski** [comment]
@eileencodes what about moving the enum validation away from the setter and into the normal validation phase?

that's actually the unexpected element here and the blocker, because my intention was to overwrite the enum value anyway. if my field wouldn't have been marked as an enum, the code in the issue would have worked just fine.

**Comment by kamipo** [comment]
Related #39683.

This behavior was due to the `In` node was a subclass of the `Equality` node (now the checking has migrated to `equality?` method).

i.e. It works unless IN queries, for example (BETWEEN):

```ruby
user = User.where(role: 0..1).find_or_initialize_by(name: "name")
```

I think that the `In` node was a subclass of the `Equality` node is accidental, so the behavior is almost a bug to me.

If we want to fix the behavior, it basically just removes `equality?` from the `In` and the `HomogeneousIn` nodes.
