### ISSUE TITLE
perform_enqueued_jobs does not return the type of error raised in the job

### ISSUE THREAD

**Issue by marcomd** [rails/rails#41290]
By executing perform_enqueued_jobs I do not get the type of error raised in the job but a generic Minitest::UnexpectedError

### Steps to reproduce

Having this job:
```ruby
class MyTestJob < ApplicationJob
  queue_as :default

  def perform(param)
    if param == 'raise'
      raise 'This is a stupid error'
    else
      'done'
    end
  end
end
```

Execute this spec:
`rspec ./spec/jobs/my_test_job_spec.rb`

```ruby
require 'rails_helper'

RSpec.describe MyTestJob, type: :job do
  include ActiveJob::TestHelper

  subject { described_class.perform_later(param) }

  context 'when param is NOT raise' do
    let(:param) { 'aaa' }

    it 'queues the job' do
      expect { subject }.to change(enqueued_jobs, :size).by(1)
    end
  end

  context 'when param is raise' do
    let(:param) { 'raise' }
    it do
      expect do
        perform_enqueued_jobs { subject }
      end.to raise_exception RuntimeError
    end
  end
end
```

### Expected behavior
I expect the type of error to be the same as the exception raised.
More precisely, I expect that test to pass.

### Actual behavior
I got this:

```
  1) MyTestJob when param is raise is expected to raise RuntimeError
     Failure/Error:
       expect do
         perform_enqueued_jobs { subject }
       end.to raise_exception RuntimeError

       expected RuntimeError, got #<Minitest::UnexpectedError: Unexpected exception> with backtrace:
         # ./app/jobs/my_test_job.rb:6:in `perform'
         # /Users/mark/.rvm/gems/ruby-2.7.2/gems/i18n-1.8.7/lib/i18n.rb:313:in `with_locale'
         # ./spec/jobs/my_test_job_spec.rb:6:in `block (2 levels) in <top (required)>'
         # ./spec/jobs/my_test_job_spec.rb:20:in `block (5 levels) in <top (required)>'
         # ./spec/jobs/my_test_job_spec.rb:20:in `block (4 levels) in <top (required)>'
         # ./spec/jobs/my_test_job_spec.rb:19:in `block (3 levels) in <top (required)>'
     # ./spec/jobs/my_test_job_spec.rb:19:in `block (3 levels) in <top (required)>'
```

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 2.7.2

**Comment by rafaelfranca** [comment]
Related to https://github.com/rails/rails/pull/37313

**Comment by sikachu** [comment]
I'm running into this problem as well, as one of our test which expects a particular exception to be raised just fail when upgrading from 6.0.x to 6.1.

@rafaelfranca what do you think about a patch which introduce a new option, say, `:fail_on_exception` for `perform_enqueued_jobs`? Something like this:

```diff
diff --git a/activejob/lib/active_job/test_helper.rb b/activejob/lib/active_job/test_helper.rb
index 5d28dba9c0..f8dbc458fb 100644
--- a/activejob/lib/active_job/test_helper.rb
+++ b/activejob/lib/active_job/test_helper.rb
@@ -570,7 +570,7 @@ def assert_performed_with(job: nil, args: nil, at: nil, queue: nil, &block)
     #
     # If the +:at+ option is specified, then only run jobs enqueued to run
     # immediately or before the given time
-    def perform_enqueued_jobs(only: nil, except: nil, queue: nil, at: nil, &block)
+    def perform_enqueued_jobs(only: nil, except: nil, queue: nil, at: nil, fail_on_exception: true, &block)
       return flush_enqueued_jobs(only: only, except: except, queue: queue, at: at) unless block_given?
 
       validate_option(only: only, except: except)
@@ -590,7 +590,11 @@ def perform_enqueued_jobs(only: nil, except: nil, queue: nil, at: nil, &block)
         queue_adapter.queue = queue
         queue_adapter.at = at
 
-        assert_nothing_raised(&block)
+        if fail_on_exception
+          assert_nothing_raised(&block)
+        else
+          block.call
+        end
       ensure
         queue_adapter.perform_enqueued_jobs = old_perform_enqueued_jobs
         queue_adapter.perform_enqueued_at_jobs = old_perform_enqueued_at_jobs
```

And by default it's `true` so we can retain the behavior of https://github.com/rails/rails/pull/37313.

(I'm not sure if `fail_on_exception` is a good name for this, so I'd love to hear everyone's suggestion as well)

**Comment by Aesthetikx** [comment]
I just hit this as well, with basically the same use case as @marcomd above:

```
expect do
  perform_enqueued_jobs do
    described_class.perform_later
  end
end.to rasie_exception('Specific Message').
```

I'm not sure I agree with what was done in https://github.com/rails/rails/pull/37313, but I can see the reasoning. However with that change, the sample test is in many ways still 'broken' because the assert_raise is not actually seeing the 'expected' exception from the `def increment!`, it is instead seeing the exception from `assert_nothing_raised` (which coincidentally happens to also be a RuntimeError, I guess.) To phrase that a different way, if they had an expected raise of a more specific subclass of RuntimeError that wasn't a descendant of `Minitest::UnexpectedError`, the test would be doubly wrong now.

I was also surprised to see a Minitest exception raised while I was using rspec, although I understand Minitest is used within the rails test support infrastructure. I am not familiar with Minitest, is `Minitest::UnexpectedException` handled specially? Is it possible to 'unwrap' the original exception?

Anyway I guess this is just a case of [spacebar heating](https://xkcd.com/1172/), and I will just change how those tests are written. @sikachu I think your change would work but in my opinion is a workaround that possibly just adds more noise to this already complicated interaction.

**Comment by Aesthetikx** [comment]
Upon a second read of @sikachu's suggestion, (unless I am reading this wrong) I think the name could be improved because if you have a job that raises an exception, `fail_on_exception: true` would cause the test to fail by raising a `Minitest::UnexpectedError`, but `fail_on_exception: false` would still cause the test to 'fail', by raising the original exception (unless it was handled with an expectation).

**Comment by sikachu** [comment]
I just found out a _workaround_ that seems to work for me. You can use `expect` inside `perform_enqueued_job` and it will work:

```ruby
perform_enqueued_jobs do
  expect { MyJob.perform_later }.to raise_exception RuntimeError
end
```

This Is because any job that gets enqueued inside `perform_enqueued_jobs` will be run right away, so the exception will happen right away.

With that, I guess it should be fine to leave it the change as-is and reorder your assertions instead.

**Comment by Aesthetikx** [comment]
> I just found out a _workaround_ that seems to work for me. 

Good find, that worked in my case.

**Comment by naps62** [comment]
@sikachu 's solution worked for me too

**Comment by equivalent** [comment]
:+1:+1:+1: on @sikachu  proposition https://github.com/rails/rails/issues/41290#issuecomment-792569339  (or some default config)


:cry: :cry: :cry:  on    https://github.com/rails/rails/issues/41290#issuecomment-800748185   as a permanent workaround as in app I work  for lots of our tests are structured as 

```ruby
def trigger
  perform_enqueued_jobs do
     SomeJob.perform_later
  end
end

it do
 expect { trigger }.to raise_exception(Whatever)
end

```

that means we would how to rewrite tone of tests  :sob:

**Comment by marcomd** [comment]
This is a workaround that requires rewriting the tests, but right now it's better than nothing. 
Thank you @sikachu 


With reference to the test job above:
```ruby
require 'rails_helper'

RSpec.describe MyTestJob, type: :job do
  include ActiveJob::TestHelper

  subject { described_class.perform_later(param) }

  context 'when param is NOT raise' do
    let(:param) { 'aaa' }

    it 'queues the job' do
      expect { subject }.to change(enqueued_jobs, :size).by(1)
    end
  end

  context 'when param is raise' do
    let(:param) { 'raise' }
    it do
      # DOES NOT WORK 🔥
      # expect do
      #   perform_enqueued_jobs { subject }
      # end.to raise_exception RuntimeError

      # IT WORKS 👍
      perform_enqueued_jobs do
        expect { subject }.to raise_exception RuntimeError
      end
    end
  end
end
```

**Comment by rafaelfranca** [comment]
After reviewing the PR that introduced this gem I don't think the "workaround" is a workaround. It is the correct fix for this problem.

Yes, you will have to rewrite some tests, but in reality those tests you had before could be wrong.

Think about this use case:

```ruby
context 'when param is raise' do
  let(:param) { 'raise' }
  it do
    expect(Model.count).to be(10)

    perform_enqueued_jobs do
      subject
      expect(Model.count).to be(10) # Checking the effect of the job was not applied
    end.to raise_exception RuntimeError
  end
end
```

Before the change in that PR your job could be raising the exception after the effect was applied and the assertion to check if the job effect was applied would not run, and your test would pass, where it should not.

If you were expecting the exception inside the `perform_enqueued_jobs` instead the other assertion would run like you would expect.

**Comment by marcomd** [comment]
What you wrote is an improvement because it allows you to do it in a single text. However, the natural way to write a test is to place it inside an "except" block. For me it is not a problem, now I know and I will do so. Thanks for the reply.
