### ISSUE TITLE
Inconsistency for timestamp column type

### ISSUE THREAD

**Issue by anuja-joshi** [rails/rails#41310]
### Steps to reproduce

1. Use `sqlite3` database adapter
2. Run following 3 migrations

```
class CreateMeetings < ActiveRecord::Migration[5.2]
  def change
    create_table :meetings do |t|
      t.string :title
      t.date :date

      t.timestamps
    end
  end
end
```

```
class AddStartTimeToMeetings < ActiveRecord::Migration[5.2]
  def change
    add_column :meetings, :start_time, :timestamp
  end
end
```

```
class ChangeMeetingsDateToEndTime < ActiveRecord::Migration[5.2]
  def change
    rename_column :meetings, :date, :end_time
    change_column :meetings, :end_time, :timestamp
  end
end
```

3. Open db console using `rails db` console and check meetings table schema:
<img width="1440" alt="meetings rails db 2021-02-03 12-37-27" src="https://user-images.githubusercontent.com/5124042/106710881-a9463480-661c-11eb-906d-318e8f1486f6.png">

### Expected behavior

Both `start_time` and `end_time` should have same column type as timestamp.

### Actual behavior

Both `start_time` is having datime as column type and `end_time` is having timestamp as column type

### System configuration
**Rails version**:
Rails 5.2.0

**Ruby version**:
ruby 2.4.4p296

**Comment by eileencodes** [comment]
Thanks for the report @anuja-joshi! I took a look at this and implemented a fix here https://github.com/rails/rails/pull/41324

For sqlite3, `timestamp` types should be converted to `datetime` according to the tests and code. While your report said they should both be `timestamp` my fix makes them both `datetime` since AFAICT that's the correct sql type for this columns and database.
