### ISSUE TITLE
Rails TEST fixture ERB loop pulls data from DEVELOPMENT database!?

### ISSUE THREAD

**Issue by AndrewFreemantle** [rails/rails#41422]
### Scenario
I'm attempting to use ERB in a fixture to create test data for each entry I have in another fixture.

For example:
- for each 👤  User I want the same 🌷 Flower created.
- if there are 2 users in my `users.yml` fixture, I want 2 flowers available to my tests.

### Steps to reproduce
* Create 2 models:
  `rails g model User uuid:uuid name:string email:string`
  `rails g model Flower flower_uuid:uuid user_uuid:uuid name:string`
* Apply the migrations to both development and test
  `rails db:migrate`
  `RAILS_ENV=test rails db:migrate`
* Create one user in the _development_ database with a name of your choosing
  `rails console`
  `> User.create(uuid: SecureRandom.uuid, name: 'Mr Bump', email: 'mr.bump@example.com')`
* Create the following fixtures and test files
* Run the test: `rails test test/models/flower_tests.rb` = FAIL :(

````ruby
# test/fixtures/users.yml
one:
  uuid: daa7b84b-8774-4ce7-887c-79e2680d77fb
  name: User One
  email: user1@example.com

two:
  uuid: cc760c3c-33a4-4203-a1c2-00b4208152e6
  name: User Two
  email: user2@example.com
````

````ruby
# test/fixtures/flowers.yml
<% User.all.each_with_index do |u, i| %>
flower_one_for_user_<%= i %>:
  flower_uuid: daa7b84b-8774-4ce7-887c-79e2680d77fb
  user_id: <%= u.aggregate_id %>
  name: Test Flower One for <%= u.name %>
<% end %>
````

### Expected behaviour
In a test, I expect 2 flowers to be created and available, so the following test should pass:

````ruby
# test/models/flower_tests.rb
require 'test_helper'

test 'checking fixture and initial starting test data' do
  assert_equal(2, Flower.all.count)
end
````

### Actual behaviour
I see one Flower, and the User record used in the ERB loop is *not* from the TEST database as expected, it's from the DEVELOPMENT database!!

### System configuration
**Rails version**: 6.1.2  (also tried 6.1.1)

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**Comment by kaspth** [comment]
Unfortunately fixtures aren't that well suited to reference other tables like this right now, I agree we should have that though! The loading order of `users.yml` and the `flowers.yml` isn't necessarily deterministic either, if I recall correctly.

The workaround I use currently is to load a `FixtureNames` constant that looks like:

```ruby
# test/test_helpers/fixture_names.rb
# Add a `require "test_helpers/fixture_names"` in `test/test_helper.rb`.
module FixtureNames
  def self.users
    %i[ one two ] # You'd have to manually update this, which is ugh.
  end
end
```

```yml
# test/fixtures/flowers.yml
<% FixtureNames.users.each do |user| %>
  flower_for_<%= user %>:
    …
<% end %>
```

I suppose you could add a `method_missing` routine too to auto-lookup `test/fixtures/users.yml`, parse it and extract the keys.

I'd love to fix this in general and I have looked into that but our underlying fixtures code needs a fair amount of work to do something like this automatically.

I agree that Active Record connection to the development database is a bug, but then I wouldn't want to make it seem like you're supposed to use Active Record in fixtures right now. Thanks for the issue! I'll close for now, since there's still a fair bit needed for resolution and I don't want to make it seem like it's actively being worked, when it's not at the moment.

**Comment by AndrewFreemantle** [comment]
@kaspth thank you for such a comprehensive response
