### ISSUE TITLE
ActiveRecord: uniqueness validaion has no way to provide records tat caused validaion failure

### ISSUE THREAD

**Issue by Sudrien** [rails/rails#41494]
https://github.com/rails/rails/blob/3daf2c7b2df8014c928f5640376550191ab712b7/activerecord/lib/active_record/validations/uniqueness.rb#L43

https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/activerecord/lib/active_record/locale/en.yml#L11

The default "errors.messages.taken" does it's job of stating a value is already used, but not of what other record(s) use it.

If `relation` were adder to `error_options`, would a custom error message be able to list out the record names - or ids - that triggered the validation?

**Comment by rafaelfranca** [comment]
If I remember correctly, the reason to not pass relation to the message is because i18n have backends that don't work well with complex objects. I think we could add an option to load the ids and push to the message but I don't think that should be by default.

Thank you for the issue but I'm closing since this is a feature, but feel free to open a PR with this new option.
