### ISSUE TITLE
6.1 - Joining Across Databases

### ISSUE THREAD

**Issue by maxrosecollins** [rails/rails#41537]
[This](https://guides.rubyonrails.org/active_record_multiple_databases.html#joining-across-databases) says it is possible in 6.1 but I can't find any documentation on _how_ to do it?

How do I implement it? How does it work? How do I set up migration files?

**Comment by eileencodes** [comment]
Oops. I need to update those docs because we haven't added support for that yet, it's still not possible. Migrations will be setup the same thought, this is just the relationship functionality. We're actively working on porting our gem at GitHub to rails/rails but it's not been completed yet. We're aiming for 7.0. Sorry for the confusion 😢

**Comment by eileencodes** [comment]
I fixed the docs in 9d4a025be2bb335de7ae2e12a6132d284cb97e21 for main, 0440369d03ae99f9f044b00e39dcd3d9871c65c2 for 6-1-stable, and d918be6e7f61fa6a6fea081ca23f17cecd657c3f for 6-0-stable. The guides will be updated in the next release of each of these.

**Comment by maxrosecollins** [comment]
@eileencodes no problem :). So for now I have to use two selects?

**Comment by eileencodes** [comment]
> So for now I have to use two selects?

Yup, it's kind of a pain at the moment, sorry about that. We were really hoping to get the functionality in for 6.1 but it didn't happen.
