### ISSUE TITLE
config.hosts no longer supports underscores in host name and error message is incorrect

### ISSUE THREAD

**Issue by Scott3377** [rails/rails#41545]
### Steps to reproduce
Create an application with an underscore in the hostname (e.g. rails_example). Add that hostname to config.hosts in your config/environment.rb. Update your local hosts file to point your hostname to 127.0.0.1 so that your local dns will resolve your hostname to your locally running server. When navigating to https://rails_example:3000, you will see the following error:

```
Blocked host: rails_example
To allow requests to rails_example, add the following to your environment configuration:
config.hosts << "rails_example"
```

```ruby
# config/environment.rb
Rails.application.configure do
...
# returns error saying to add "rails_example" to config.hosts
config.hosts << "rails_example"
...
end
```
This issue is due to an [updated regex](https://github.com/rails/rails/compare/v6.0.3.4...v6.0.3.5#diff-401b1f2d4b94c52328880f3baca952f374f24903245327fc4c4527d6d5655a0cR90-R95) for hostname validation introduced in Rails 6.0.3.5 which no longer allows underscores in the hostname. 

### Expected behavior
User should receive a warning that the hostname they specified in config.hosts is not a valid hostname.

### Actual behavior
User is told to add the same host name that they have already added to config.hosts.

### System configuration
**Rails version**: 6.0.3.5

**Ruby version**: 2.6.6

**Comment by nvolker** [comment]
Nice one! Ran into this issue this morning...

**Comment by intrip** [comment]
`_` is not allowed in host name as per [RFC](https://tools.ietf.org/html/rfc952).
I think the possibility of using `_` was just an hidden issue which was fixed indirectly in https://github.com/rails/rails/commit/83a6ac3fee8fd538ce7e0088913ff54f0f9bcb6f

In short: I don't think we should enable `_` in host name thus this is not a regression, anyways the end decision is from the core team.

**Comment by trliner** [comment]
I understand the reasoning for disallowing underscores, but an accurate error message would be really helpful.

**Comment by intrip** [comment]
I'd be happy to write a PR which shows a meaningful error message pointing out that the given URL is invalid.
Waiting for the go from the core team before working on it.

**Comment by estani** [comment]
This took me the whole morning to find out, after some update increased the railties version and within it actionpack...

No message whatsoever... I had to debug rails code to find this... not a good experience.

Anyways, [RFC 1033](https://www.ietf.org/rfc/rfc1033.txt) says:

> The domain system allows a label to contain any 8-bit character.
   Although the domain system has no restrictions, other protocols such
   as SMTP do have name restrictions.  Because of other protocol
   restrictions, only the following characters are recommended for use
   in a host name (besides the dot separator):
>
>          "A-Z", "a-z", "0-9", dash and underscore

Why should be rails more conservative than this RFC?
we use dynamic names with underscores... which forces us to turn this feature off.

A possible trade off, if rails keep on trying to define whats better, would be to have the `valid_host` regex inserted in `config.hosts` per default, so it is possible to overwrite it (and more clean that having this kind of exceptions in code, if you ask me.

**Comment by zzak** [comment]
I agree an error message would be helpful, I'm just not sure _where_ to put it. 🤔

**Comment by estani** [comment]
I'd say just write to the error log in `authorized?(request)`

<details>
  <summary>perhaps here?</summary>

```
File: lib/action_dispatch/middleware/host_authorization.rb
089:       def authorized?(request)
090:         
091:         valid_host = /
092:           \A
093:           (?<host>[a-z0-9.-]+|\[[a-f0-9]*:[a-f0-9\.:]+\])
094:           (:\d+)?
095:           \z
096:         /x
097: 
098:         origin_host = valid_host.match(
099:           request.get_header("HTTP_HOST").to_s.downcase)
100:         forwarded_host = valid_host.match(
101:           request.x_forwarded_host.to_s.split(/,\s?/).last)
102: 
103:         # origin_host.nil? log -> "Rails thinks hostname is not valid"
104:         # !@permissions.allows?(origin_host[:host]) -> "host #{origin_host[:host]} not allowed"
105:         # forwarded_host && !@permissions.allows?(forwarded_host[:host]) -> "forwarded_host #{forwarded_host[:host]} not allowed"
106: 
107:         origin_host && @permissions.allows?(origin_host[:host]) && (
108:           forwarded_host.nil? || @permissions.allows?(forwarded_host[:host]))
109:       end
110: 
111:       def mark_as_authorized(request)
112:         request.set_header("action_dispatch.authorized_host", request.host)
113:       end
```

</details>

And again: RFC 1033 seem to be clear, that underscores should be allowed.
There are good explanations for it too [stackoverflow](https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it)

**Comment by zzak** [comment]
@tenderlove Do you know if disallowing "_" underscores in the host was intentional?

From what I'm reading, its only unsupported for the domain name portion but subdomains could contain this character. 🤔

**Comment by estani** [comment]
Quoting the [RFC 1033](https://www.ietf.org/rfc/rfc1033) again, two paragraph above (just to be clear about this point):

> A domain name is a sequence of labels separated by dots.

Domain is used here in the more general case as the whole sub_domains + domain + top-level domain (think this was written back in 1987)

For what is worth, I can assure the community we have been using underscores in subdomains for years, and had no issue until the mentioned rails update. 

If the rest of the rails community want to start an ad-hoc standard, it's fine with me, but please give the others the possibility to opt-out. Improve the code and pre-fill the `config.hosts` with whatever you like. Just don't hard code exceptions, this is always a bad style, in my opinion.

**Comment by byroot** [comment]
PR here https://github.com/rails/rails/pull/42893. I'll leave a couple days for the authors to jump-in in case we're wrong about the importance of underscores, and then I'll merge.

**Comment by TkTech** [comment]
Realistically, while [there are security concerns](https://access.redhat.com/errata/RHSA-2017:1721) when not following the same spec as everyone else, it's not a _significant_ risk in Rails. It's just not a "valid" domain by convention. Django does not allow underscores, but some other frameworks like Flask do (https://github.com/pallets/werkzeug/blob/main/src/werkzeug/urls.py#L25).

Keep in mind that by allowing underscores, users are likely to run into even more confusing issues. Such as:

- [being unable to get an SSL certificate for that domain](https://cabforum.org/2018/11/12/ballot-sc-12-sunset-of-underscores-in-dnsnames/)
- [Cookies not being saved in IE7-IE11](https://docs.microsoft.com/en-US/troubleshoot/browsers/variables-not-persist-between-requests) (for the poor souls that still have to work with IE)
- Going from development to a production server such as apache, underscores won't work.
- Issues with routing on the local network (_ is not at all valid in hostnames) depending on how strict the components of your particular network are.
- You usually cannot register a public domain with an underscore in it.
- Intranet sites will have issues depending on what's handling the local DNS. For example in Windows Server you have to disable validation entirely for Microsoft's "DNS Server" to reply to underscores.

If you want to re-enable this behavior by default, I believe it should still emit a warning on domains with an underscore at a minimum. Otherwise, it should stick to following convention and prevent domains with underscores.

**Comment by rafaelfranca** [comment]
I agree with @TkTech that we should not allow underscore in hostnames. We can improve the error message to tell which hosts we allow.

Something like:

```
Blocked host: <%= @host %>

To allow requests to <%= @host %> make sure it is a valid hostname (containing only numbers, letters, dashes and dots), add the following to your environment configuration:

  config.hosts << "<%= @host %>"
```

Who wants to open the PR?

**Comment by ghiculescu** [comment]
Made a PR to update the message: https://github.com/rails/rails/pull/42896

**Comment by misheck12** [comment]
Hello team, i have followed every documention on the internet to solve this issues while the error still persists. 

Blocked hosts: site.com
To allow requests to these hosts, make sure they are valid hostnames (containing only numbers, letters, dashes and dots), then add the following to your environment configuration:
    config.hosts << "site.com"
  
For more details view: [the Host Authorization guide](https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization). 

how can i solve this am using rails 7

**Comment by thelastinuit** [comment]
> Hello team, i have followed every documention on the internet to solve this issues while the error still persists.
> 
> Blocked hosts: site.com To allow requests to these hosts, make sure they are valid hostnames (containing only numbers, letters, dashes and dots), then add the following to your environment configuration: config.hosts << "site.com"
> 
> For more details view: [the Host Authorization guide](https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization).
> 
> how can i solve this am using rails 7

Did you find the solution? I have tried `config.hosts.clear` as a final solution but nothing. It doesn't matter what I do any hosts listed or not, get blocked 😔
