### ISSUE TITLE
ActiveRecord::RecordInvalid.new triggers deprecation message in Rails 6.1.3

### ISSUE THREAD

**Issue by pebneter** [rails/rails#41768]
Since upgrading from Rails 5.2.4 to 6.1.3 we were seeing a lot of deprecation messages during our tests.

```
In Rails 6.1, `errors` is an array of Error objects,
therefore it should be accessed by a block with a single block
parameter like this:

person.errors.each do |error|
  attribute = error.attribute
  message = error.message
end

You are passing a block expecting two parameters,
so the old hash behavior is simulated. As this is deprecated,
this will result in an ArgumentError in Rails 6.2.
```
After being able to fix most of them in our controller code, some remained and we had a hard time finding out where they came from.
Finally, I found the line:
https://github.com/rails/rails/blob/30ef29289ba631911564129a1c040f9e81c7a770/activerecord/lib/active_record/validations.rb#L21 which calls the error object in a deprecated way.

Replacing it with something like `errors = @record.errors.map(&:full_message).join(", ")` solves the issue, except the attribute name is not capitalised.

Could someone with experience submitting code to this repository have a look?

**Comment by abhaynikam** [comment]
@pebneter I think the reason for deprecation message is different from the suggested changes in the issue description. Secondly, if `@record.errors` is an Error objects, then `full_messages` would do the same thing you suggested(i.e: `map(&:full_message)`)

https://github.com/rails/rails/blob/30ef29289ba631911564129a1c040f9e81c7a770/activemodel/lib/active_model/errors.rb#L485-L487

I tried to reproduce this on master and Rails 6.1.3 but I could not see why `@record.errors` would be Hash instead of Errors object. I may be wrong but if possible could you to write a [steps to reproduce the issue](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb) or build a sample application for it.

**Comment by pebneter** [comment]
Sure, will try to reproduce with the template.

**Comment by pebneter** [comment]
Hi @abhaynikam,

I tried to reproduce with the template and you are absolutely right. ActiveRecord is fine.
The warning is caused by a not maintained gem that is calling `@record.errors.each` with multiple block parameters, which is now deprecated: https://github.com/jeremydurham/custom-err-msg/blob/master/lib/rails/extensions/active_model.rb

Sorry for not having realised that earlier 🤦‍♂️
