### ISSUE TITLE
Rails 6.1.3.1 NoMethodError: undefined method `extension' for nil:NilClass

### ISSUE THREAD

**Issue by ToTenMilan** [rails/rails#41777]
### Steps to reproduce
Using `.variant` is raising error in Rails 6.1.3.1 
```
> someobject.images.first.variant(resize_to_fill: [100, 100])
NoMethodError: undefined method `extension' for nil:NilClass
from /home/username/.rvm/gems/ruby-2.7.1/gems/activestorage-6.1.3.1/app/models/active_storage/blob/representable.rb:116:in `format'
```
Error is gone after downgrade to rails 6.1.3
```
Rails 6.1.3
> someobject.images.first.variant(resize_to_fill: [100, 100])
=> #<ActiveStorage::Variant:0x00007f6bd81fe2d0
 @blob=
  #<ActiveStorage::Blob:0x0000......>>
```
### Expected behavior
`.variant(resize_to_fill: [100, 100])` to return object

### Actual behavior
`.variant(resize_to_fill: [100, 100])` raises error

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 2.7.1

**Comment by ToTenMilan** [comment]
I was trying to debug it, and so far it looks like task `bundle exec rake rebuild_db` is not creating row `jpg image/jpg` or similar into https://github.com/discourse/mini_mime/blob/master/lib/db/content_type_mime.db

**Comment by georgeclaghorn** [comment]
Is the relevant blob’s `content_type` really `image/jpg`? That’s not an IANA-registered MIME type—the correct one is `image/jpeg`, and I would have expected our content type identification code to correct that.

In any case, we’ll need to cope with `MiniMime.lookup_by_content_type` returning `nil` here:

https://github.com/rails/rails/blob/e3075c17fffb6b8f26571d6b47c33764ad994ec2/activestorage/app/models/active_storage/blob/representable.rb#L116

**Comment by ToTenMilan** [comment]
Yes, in my case it is `image/jpg` (no "e"). Despite not being a correct type, it worked previously with dropped mimemagic

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/42225 will fix the crash.

**Comment by ghiculescu** [comment]
@ToTenMilan something I'm trying to understand (for https://github.com/rails/rails/pull/42227) is how you got `image/jpg` into your blobs table. In my testing, if I upload a file and tell AS it's a `image/jpg`, it'll still treat it as an `image/jpeg` because of [this line](https://github.com/rails/rails/blob/main/activestorage/app/models/active_storage/blob.rb#L247). Do you know if you did something different?

In https://github.com/rails/rails/pull/42227 I'm proposing we remove default content types that don't work as you expect, but that will make certain blobs (like yours) crash in new ways and so I want to figure out if that's something I should be trying to prevent.
