### ISSUE TITLE
Invalid variant format ("JPG")

### ISSUE THREAD

**Issue by pwim** [rails/rails#41796]
Since I updated my application to Rails 6.1.3.1, I've started to receive the exception `Invalid variant format ("JPG")`.

### Steps to reproduce
Unfortunately I don't seem to have an easy way to reproduce this. I downloaded one of the source images that was triggering this issue. However, when re-uploading it, I didn't experience the issue. I also noticed after some time, the variant that was originally experiencing this issue somehow had been created properly. The only obvious lead I have is that the filename ends in `.JPG`.

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 2.0.0

**Comment by georgeclaghorn** [comment]
```
irb(main):001:0> MiniMime.lookup_by_extension("jpg")
=> #<MiniMime::Info:0x00007fde9825df40 @extension="jpg", @content_type="image/jpeg", @encoding="base64">
irb(main):002:0> MiniMime.lookup_by_extension("JPG")
=> nil
```

@SamSaffron, should MiniMime downcase extensions on lookup or should callers?

**Comment by tyler-boyd** [comment]
To be honest, I have no idea how this is possible. The exception is thrown https://github.com/rails/rails/blob/5de2dbff16009ebf8441e259d95d4b22d068ac8c/activestorage/app/models/active_storage/variation.rb#L62, which in my case means that `MiniMime.lookup_by_extension("PNG")` returns nil.

However, AFAICT, the only way that `"PNG"` can make it to that line is if this `if` case happens: https://github.com/rails/rails/blob/5de2dbff16009ebf8441e259d95d4b22d068ac8c/activestorage/app/models/active_storage/blob/representable.rb#L113-L114

The only way *that* can be true is if either `MiniMime.lookup_by_extension("PNG")` returned the actual PNG content type (and then later returned nil when called with the same argument?), or it returned `nil` and `content_type` is somehow also `nil` at this point in time.

Since `MiniMime.lookup_by_extension("PNG")` always returns `nil` in the Rails console, I assume it must be the latter, and `content_type` is nil sometimes. Weird...

Hope this helps. In the short term @pwim, I could imagine some hacks with either downcasing file names, or registering `"PNG"` in MimeMagic

**Comment by tyler-boyd** [comment]
I think I have an explanation.

I believe the specific ActiveStorage representation URL that was requested (and erroring out) after the update had been generated *before* I released the update. When clients fetch a fresh URL (ie. running `rails_representation_url image.variant(...)` again), the URL always works. I only observed this issue when the client was using an old URL, and when I decoded the old URL's variant key, sure enough I see `@transformations={:format=>"PNG", :resize=>"300x300"}`.

So IMO it would be beneficial if MimeMagic downcased the extension when doing a lookup, as it appears that's what the old behaviour was before MimeMagic.

**Comment by SamSaffron** [comment]
Happy to have parity with the mime types gem, does it downcase for lookups?

**Comment by tyler-boyd** [comment]
@SamSaffron as far as I can see, it does https://github.com/mime-types/ruby-mime-types/blob/b8db65ac00b8f23d4274ed47aada475a65cc24d0/lib/mime/type.rb#L560

**Comment by SamSaffron** [comment]
@georgeclaghorn I changed it so lookup_by_extension is case insensitive (also extremely small perf hit only happens when an incorrectly cased lookup happens) 

New gem was just released (1.1.0)

**Comment by benben** [comment]
If I bump `mini_mime` in my Gemfile to `1.1.0`, Rails gets downgraded from `6.1.3.1` to `6.1.3`. Is there anything else we need to do to make that work with `6.1.3.1` ?

**Comment by rainerborene** [comment]
@benben Same here. I think the version requirement on the `gemspec` file of `activestorage` must be changed to `~> 1.0` or something.
