### ISSUE TITLE
webpack-dev-server not working and lingering sassc issues

### ISSUE THREAD

**Issue by tgrushka** [rails/rails#41826]
### Steps to reproduce

When I install a fresh rails 6.1.3.1 app:
* sassc still takes > 5 min. to compile;
* sassc still installs as part of the bundle, even when I manually remove sass-rails from the Gemfile, so I can't skip it if I want to;
* webpack-dev-server / @rails/webpack is still not patched to work correctly with the new webpack version (I know this is a separate package from rails, but it comes by default with rails and is necessary for working with rails-supported webpacks, so rails should probably not be shipped with a broken version of webpack-dev-server... ?).

```
rbenv -v
-> rbenv 1.1.2

ruby -v
-> ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]

gem -v
-> 3.1.4

gem install rails
-> Successfully installed rails-6.1.3.1

time rails new --webpack=vue v6131
-> ... Installing sassc 2.4.0 with native extensions (stalls about 5 minutes)
-> ... Webpacker now supports Vue.js 🎉
-> 276.09s user 31.68s system 100% cpu 5:06.73 total

cd v6131
bin/webpack-dev-server
-> The command moved into a separate package: @webpack-cli/serve
-> Would you like to install serve? (That will run yarn add -D @webpack-cli/serve) (yes/NO) :
y
-> yarn add v1.22.10
-> warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
-> warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
-> warning " > @webpack-cli/serve@1.3.1" has unmet peer dependency "webpack-cli@4.x.x".

...
-> ✨  Done in 2.59s.
-> TypeError: Class constructor ServeCommand cannot be invoked without 'new'
->    at runWhenInstalled (/Users/tom/v6131/node_modules/webpack-cli/bin/utils/prompt-command.js:46:9)
->    at /Users/tom/v6131/node_modules/webpack-cli/bin/utils/prompt-command.js:124:15
->    at processTicksAndRejections (node:internal/process/task_queues:94:5)

bin/webpack-dev-server
-> /Users/tom/v6131/node_modules/webpack-cli/bin/utils/prompt-command.js:46
	return func(...args);
-> 	       ^
-> 
-> TypeError: Class constructor ServeCommand cannot be invoked without 'new'
->     at runWhenInstalled (/Users/tom/v6131/node_modules/webpack-cli/bin/utils/prompt-command.js:46:9)
->     at promptForInstallation (/Users/tom/v6131/node_modules/webpack-cli/bin/utils/prompt-command.js:140:10)
...
```

### Expected behavior
When I perform the above steps, I expect the `rails new` command to run in a reasonable amount of time (not require sassc if sassc is buggy or causes installation problems, especially if sass-rails is disabled).

Then, if `bin/webpack-dev-server` is broken or no longer a supported method, it should not be installed using `rails webpacker:install`, or should be fixed so that it works properly.

If a different method is required to run `webpack-dev-server` in development, that should be in the documentation.

### Actual behavior
`webpack-dev-server` doesn't work, even after installing the suggested dependency, and even after running `yarn add -D @webpack-cli` manually.

### System configuration
**Rails version**:
6.1.3.1

**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]

**Yarn version**:
1.22.10

**Node version**:
v15.11.0

**Comment by dhekimian** [comment]
[LibSass is Deprecated ](https://sass-lang.com/blog/libsass-is-deprecated) for over 2+ years and the recommendation is to move to [Dart Sass](https://sass-lang.com/dart-sass). 

Webpacker has already updated to use Dart Sass instead of LibSass starting with Webpacker v6.x and there is a merge request to backport it for [Webpacker v5.x](https://github.com/rails/webpacker/pull/2914). Not sure if Webpacker v6 will be supported with Rails 6.x or only 7.x or if/when the MR to backport will get merged and released... 

There's a open issue in [sassc-rails](https://github.com/sass/sassc-rails) asking what the [Migration plan now that LibSass is deprecated?](https://github.com/sass/sassc-rails/issues/151). 

Someone smarter than me will probably need to weigh in on if [sassc-rails](https://github.com/sass/sassc-rails) can be dropped as a dependency and use dart-sass via Webpacker in an upcoming Rails release.

**Comment by zzak** [comment]
Correct me if I'm wrong but this seems like a non-rails issue, so closing. :bow:
