### ISSUE TITLE
Use RAILS_ENV to edit different credentials files

### ISSUE THREAD

**Issue by matt17r** [rails/rails#41830]
### Steps to reproduce

1. Run `rails credentials:edit` in development environment and add/edit credentials
2. Run `RAILS_ENV=production rails credentials:edit` to edit production credentials but same file opens up

### Expected behaviour
I expected `RAILS_ENV=production rails credentials:edit` to work much like `RAILS_ENV=production rails console`

### Actual behaviour
You actually need to specify the `--environment` flag in order to change environments. This is documented in the [PR introducing the feature](https://github.com/rails/rails/pull/33521) but not in the [Rails Guide](https://edgeguides.rubyonrails.org/security.html).

It also means you can run confusing commands like `RAILS_ENV=staging rails credentials:edit --environment production`

I suspect it was done this way to maintain backwards compatibility. It's only a minor paper cut but to me it violates the principle of least surprise.

If it needs to remain this way for backwards compatibility then clearer documentation would help (I'm happy to do a PR if that's the way forward). Additionally, if there is any way to detect someone has explicitly passed `RAILS_ENV` to this command, a warning explaining the correct way to edit the environment along with a link to the documentation would be very helpful.

### System configuration
**Rails version**: Rails 6.1.3

**Ruby version**: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

**Comment by matt17r** [comment]
A few more thoughts:

1. Even if we can't tell if someone set `RAILS_ENV` explicitly (or whether it was set by Heroku, for example), it still might make sense to log a warning to STDOUT anytime `credentials:edit` is called in a non-development environment. I would imagine the command is used on development machines the vast majority of the time (in a perfect world, SSHing into a production server and running `rails credentials:edit` should be exceedingly rare) so there is no real downside to "polluting" the production console/logs with a warning if someone deliberately calls `credentials:edit` in production.
2. I found the behaviour is explained in the USAGE docs for `rails credentials`, so it's more documented than I realised.
3. One other thing that is mildly surprising is that `config/master.key` is merely the default (not the master) key whereas `ENV["RAILS_MASTER_KEY"]` is actually a master key that is used on the default credentials file as well as any environment specific files. If `config/master.key` is never used to encrypt/decrypt environment credentials the name is a little misleading. Renaming it `credentials.key` would keep it in line with the naming pattern of the other file pairs.

**Comment by georgeclaghorn** [comment]
> I suspect it was done this way to maintain backwards compatibility. It's only a minor paper cut but to me it violates the principle of least surprise.

The reason is that you shouldn’t have to boot the app in the production environment to edit production credentials.

**Comment by matt17r** [comment]
> The reason is that you shouldn’t have to boot the app in the production environment to edit production credentials.

Thanks for responding! I'm probably missing something (I'm no ~Rails~ expert), but I don't understand what you mean about having to boot the app. I thought environment variables were an OS level feature?

If `rails credentials:edit --environment production` can access the value of `RAILS_MASTER_KEY` to decrypt/encrypt `/config/credentials/production.yml.enc`, couldn't that command just as easily access the value of `RAILS_ENV` to decide which path to take?

**Comment by georgeclaghorn** [comment]
`RAILS_ENV=production rails credentials:edit` loads and initializes the app in the production environment. That means loading production config, which means eager-loading all app classes and connecting to the production DB. There may be other hard dependencies on production systems that aren’t available on a local dev machine.

I cannot run `RAILS_ENV=production rails runner 'puts "Hello world"'` in any of our apps, because production database connections are restricted to production app hosts.

**Comment by matt17r** [comment]
Ahh okay! Thank you for the patient explanation! That explains the decision not to re-use `RAILS_ENV`.

Given there's a good reason not to use `RAILS_ENV`, and that most people should probably be running this command in a dev environment, what do you think of my follow up suggestion to log a warning to standard out (or wherever makes most sense) anytime `credentials:edit` is called in a non-development environment?

If `RAILS_ENV` is not development and the `--environment` flag has not been set (or has but doesn't match `RAILS_ENV`) a message could be displayed along the lines of:  
``"You are editing #{credentials_environment} credentials from the #{RAILS_ENV} environment. Did you mean to run `rails credentials:edit --environment #{RAILS_ENV}`? For more information try `rails credentials:help`"``  
``=> You are editing development credentials from the production environment. Did you mean to run `rails credentials:edit --environment production`? For more information try `rails credentials:help` ``

**Comment by ghiculescu** [comment]
@matt17r that sounds like a good idea, particularly for new users. Just checked and with an out of the box Heroku app `RAILS_ENV=production rails runner 'puts "Hello world"'` doesn't crash, so I can definitely see other users getting confused by the arguments the same way you did.

Do you want to have a go at a PR? The warning would probably get called from [here](https://github.com/rails/rails/blob/main/railties/lib/rails/commands/credentials/credentials_command.rb#L28..L29). You could also update the [Rails guide](https://github.com/rails/rails/blob/main/guides/source/security.md#custom-credentials) while you're at it 👍 .

**Comment by Navdevl** [comment]
@ghiculescu Is this still open? Can I pick this up and work on this? cc: @matt17r

**Comment by jon-sully** [comment]
> The reason is that you shouldn’t have to boot the app in the production environment to edit production credentials.

I agree that one shouldn't _need_ to boot the app in production mode to edit production credentials, and for exactly the type of circumstances @georgeclaghorn provided, one may not even be able to... but can't we have it both ways?

Right now `credentials:edit` full-stop ignores the `Rails.env` which, aside from feeling sort of disjointed from how all the other Rails tasks/commands work (at least the ones I know/use) as described in OP, it also creates a weird disconnect where (how a booted Rails app instance access credentials) =/= (how a developer is able to interface / work with credentials themselves). Particularly in the area where, as prescribed [by DHH](https://github.com/rails/rails/pull/33521#issuecomment-412382031): 

> If you're in the development environment, and config/credentials/development.yml.enc is found, then that'll be loaded. We won't even try to do anything with config/credentials.yml.enc.

And a Rails _application_ does indeed follow that workflow, but `credentials:edit` does not. I often set up my apps to _not_ have a 'global' credentials file and instead have environment-specific credentials for all environments (including dev). When I run `rails credentials:edit` it ignores that my current environment is `development` and that there is indeed a `~/config/credentials/development.yml.enc` file — instead the command actually goes ahead and creates the global credentials file (that I don't want). It feels weird that I should need to pass `--environment development` when I'm already in development and a `development.yml.enc` exists.. especially when the Rails _application_ already works this way.

**Comment by matthewd** [comment]
At a glance, that sounds reasonable. Given that each environment has exactly one credentials file, it makes sense that a plain `credentials:edit` should default to editing the current [`RAILS_ENV`] environment's file -- but also for the above-mentioned reasons, the `--environment` option is available to override that, allowing you to edit a different environment's credentials file without booting into that env.

If the current environment does not have a specific file, then `credentials:edit` would continue to load the global file. (So the common case of no environmental variation remains unaffected.)

However, it breaks down on edge cases:

If you have a global file and a development file, today:
`rails credentials:edit` -> edit global file
`rails credentials:edit --environment development` -> edit development file
`rails credentials:edit --environment production` -> create production-specific file

If we change the default behaviour (assuming `RAILS_ENV=development`):
`rails credentials:edit` -> edit development file
`rails credentials:edit --environment development` -> also edit development file
`rails credentials:edit --environment production` -> ??

The available options there are either "edit global file" (because that's where production currently reads its credentials), or "create production-specific file" (because that's what it used to do, and might be what the user wants to do -- so they need some way of achieving that).

Off the top of my head, that might mean we need a `--global` as an explicit spelling of `--environment (nil)`, or a `--create` to mean "if the specified/current environment would normally read from global, instead of editing that, create and edit a new env-specific file", or both.

**Comment by jon-sully** [comment]
Good thoughts there. I wonder if we could add a more interactive step (and I know I'm scoping big here) that would turn `credentials:edit` into an interactive menu where the user could select which _existing_ set of credentials they wish to edit before launching the editor with those credentials? 

```bash
$ rails credentials:edit
=> Please select which credentials you would like to edit:
=>  (global) credentials.yml.enc
=>  development.yml.enc
=>  production.yml.env <--
```

(`<--` is my beautiful cursor implementation). I think it would nice if this only showed existing files too, perhaps outputting that new credentials can be created with (new command) `credentials:create production` or what-have-you.

Perhaps the interactive menu solves the tension since it doesn't matter what environment you fire the command from and you don't need to (can't) pass in `--environment foo` to convolute the intention of the command.

**Comment by jon-sully** [comment]
I hacked up just enough of my local rails gem to spoof this proof of concept for visuals' sake. To my knowledge I don't think there are any Rails commands that have an interactive menu / interface like this (though I can think of a few others that may actually benefit from it), so I imagine this is a larger undertaking.. but I at least wanted to post the idea PoC in action

![example](https://user-images.githubusercontent.com/8585984/156093473-c7a18bd1-dc48-4fa5-9efc-c68f6a2f4db8.svg)
