### ISSUE TITLE
webpack serve not working out of the box

### ISSUE THREAD

**Issue by mices** [rails/rails#42120]
I created a new rails 6.1.1.3 app and then ran npx webpack serve --mode=development and got the following errors: warning " > @webpack-cli/serve@1.3.1" has incorrect peer dependency "webpack-cli@4.x.x". TypeError: Class constructor ServeCommand cannot be invoked without 'new'
I'm running nodejs 16 on ubuntu 20.04

**Comment by pixeltrix** [comment]
Hi @mices

The correct repo for any issues with webpack issues is the [webpacker][1] repo, however I think your problem is you're trying to run the development server in the wrong way - there's a binstub you can use to boot the server, e.g: 


```
% bin/webpack-dev-server 
ℹ ｢wds｣: Project is running at http://localhost:3035/
...
```

Hope this helps.

[1]: https://github.com/rails/webpacker

**Comment by mices** [comment]
Thanks That method of starting webpack-dev-server has been replaced with the new method `npx webpack serve` I'm using the mode option on the command line becuase I couldn't figure out how to configure I posted in rails gem issues because rails includes webpack and webpacker
