### ISSUE TITLE
ActiveSupport::Configurable config_accessor does not warn about naming conflicts with Hash instance methods and returns unexpected results on conflicts

### ISSUE THREAD

**Issue by tscholz** [rails/rails#42140]
### Test to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  ruby '>= 2.6'

  # Activate the gem you are reporting the issue against.
  gem "activesupport", "6.1.0"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class MyConfigurable
  include ActiveSupport::Configurable

  config_accessor :filter do
    :custom_filter
  end
end

class BugTest < Minitest::Test
  def test_it_returns_the_configured_filter
    assert MyConfigurable.filter == :custom_filter
  end

  def test_it_does_not_call_the_hash_filter_method_introduced_in_ruby_2_6
    refute MyConfigurable.filter.is_a? Enumerable
  end
end
```

### Expected behavior
It should return the configured value or at least print out a warning when trying to define a config accessor that causes method name clashes on the object used as config store, Hash in that case.

### Actual behavior
It calls Hash#filter method instead of returning the configured value.

### System configuration
**Rails version**: 5, 6

**Ruby version**: >= 2.6

**Comment by malclocke** [comment]
This problem runs a bit deeper that `config_accessor`.  In summary, you can't use any of method names from `Hash` for config options and access them as `config.method_name`.  They can be accessed with `config[:method_name]` though.

Root cause is that the `config` object is a kind of `ActiveSupport::OrderedOptions` which inherits from `Hash`.  `OrderedOptions` relies on `method_missing` to do it's thing. 

https://github.com/rails/rails/blob/75ac626c4e21129d8296d4206a1960563cc3d4aa/activesupport/lib/active_support/ordered_options.rb#L43-L56

Because `filter`, `keys` etc are not missing `method_missing` doesn't get called.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activesupport", "6.1.3.2"
end

require "active_support"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_existing_hash_method_name
    ordered_options = ActiveSupport::OrderedOptions.new
    ordered_options.keys = "my keys"

    # Passes
    assert_equal "my keys", ordered_options[:keys]

    # Fails
    assert_equal "my keys", ordered_options.keys
  end
end
```
I personally think `ActiveSupport::OrderedOptions` should raise an error if you try and **set** a name that exists on `Hash`.  The fact that `OrderedOptions#filter=` is OK but `OrderedOptions#filter` is not feels like it can only lead to confusion to me.
