### ISSUE TITLE
"please use symbols for polymorphic route arguments" with 6.0.3.6 -> 6.0.3.7

### ISSUE THREAD

**Issue by thebravoman** [rails/rails#42157]
### Steps to reproduce
Update from 6.0.3.6 to 6.0.3.7

### Expected behavior
All tests should pass

### Actual behavior
Many polymorphic_paths fail with:
"please use symbols for polymorphic route arguments"
We are using objects. We are using strings.

For example this now fails
```
<%= form_with model: @author, url: polymorphic_path([*@namespaces, *@parents,@parent_name,@author]),
```

### System configuration
**Rails version**: 6.0.3.7

**Ruby version**: 2.6.5

**Comment by rylanb** [comment]
I've got this happening after today's upgrade from `5.2.4.5` -> `5.2.6`, as well. 

5.2.4.6 seems to have a mention of `Prevent string polymorphic route arguments.` 
 that might be the cause of this: https://github.com/rails/rails/releases/tag/v5.2.4.6 ?

**Comment by thebravoman** [comment]
Yes, https://github.com/rails/rails/releases/tag/v6.0.3.7 has this mentioned also. Thank you.

Isn't this too large of a change for a minor upgrade?

```
$ git grep polymorphic_path | wc -l
321
```

I will now have to review 321 calls only in this platform. A warning of some kind might have been good.

**Comment by rylanb** [comment]
Yup, I have 57 to run around now and try to figure out the best way to fix before I can get this security release out.

**Comment by G-Rath** [comment]
I believe it's because of https://github.com/rails/rails/commit/c4c21a9f8d7c9c8ca6570bdb82d64e2dc860e62c

**Comment by richardrails** [comment]
also in rails 6.1.3.2

**Comment by thebravoman** [comment]
A perspective on how serious it is to upgrade

All the calls in our platform for polymorphic_path
```bash
$ git grep  "polymorphic_path" | wc -l
321
```

All the file that have calls to polymorphic_path
```bash
$ git grep -l  "polymorphic_path" | wc -l
143
```

Numbers of files that I've changed - 13
Time it took me to review all of them -18:24 to 18:40

Now I am waiting for specs to pass.

I guess it is not a big change and could be migrate in half an hour. Most of our calls were using symbols already and only about 15 calls from 321 were with strings.

**Comment by kjleitz** [comment]
@thebravoman this seems to affect more than just calls to `#polymorphic_path`. We're getting errors in calls to `#link_to` and `#simple_form_for` (from a gem, but I believe it ultimately delegates to `#form_for` under the hood), after upgrading from `5.2.5` to `5.2.6`, like @rylanb.

That's just what our tests caught, though. I'm sure it can present when using other dynamic-route-generating methods as well.

**Comment by rylanb** [comment]
Yeah, it is fine to close and hopefully not too heavy of a lift, but I do worry that it blowing up is going to make its way into production for folks. So it is good that this issue was out there to be found / show the discussion.

**Comment by izzergh** [comment]
```
params[:potentially_insecure_user_submitted_path].to_sym
```
Gets around the error but still causes the underlying problem - how does this fix the CVE? Is it just an awareness campaign?

**Comment by santib** [comment]
I was thinking the same as @izzergh .

First of all I think this deserved a minor version bump because it potentially broke many apps (specially the ones missing test coverage).

Apart from that, I don't get how not allowing strings solve the problem because people could just call `.to_sym` on the untrusted user params, what's more if people end up doing `params[:some_param].to_sym` it'd be a bigger problem (potential denial of service) as stated in the ruby docs https://docs.ruby-lang.org/en/3.0.0/doc/security_rdoc.html#label-Symbols
>Don't create immortal symbols from user inputs. Otherwise, this would allow a user to mount a denial of service attack against your application by flooding it with unique strings, which will cause memory to grow indefinitely until the Ruby process is killed or causes the system to slow to a halt.

Looking at the tests added in the commit, the only possible border case I can imagine this commit fixing is if the user params is an array of strings.

@gmcgibbon can you clarify? 🙏

**Comment by thebravoman** [comment]
To be fair the update I did with our system for 16 minutes was only because there were some instances that stings had to be changed to symbols, but there were no instances of calling polymorphic_path with user input and we have a really good code coverage on the places where polymorphic_path was used. We weren't really affected by this CVE. But as @santib and @izzergh mentioned it is difficult to see how this addresses the underlying issue.

Looking at the CVE https://github.com/advisories/GHSA-hjg4-8q5f-x6fm one of the workarounds is to call param[:some].to_s. So to_s should also work.

What I guess I am missing is what 

````
params[:potentially_insecure_user_submitted_path]
````
looks like for it to require calling .to_s or .to_sym.

But I doubt this would be shared as an example.

**Comment by izzergh** [comment]
@thebravoman I don't see how `to_s` would work, as that turns the input into a String (here is the snippet from https://github.com/rails/rails/commit/c4c21a9f8d7c9c8ca6570bdb82d64e2dc860e62c that shows where my confusion comes from)

```ruby
            route = record_list.map do |parent|
              case parent
              when Symbol
                parent.to_s
              when String
                raise(ArgumentError, "Please use symbols for polymorphic route arguments.")
#...
```

**Comment by thebravoman** [comment]
@izzergh I also don't see how to_s will work with 6.0.3.7 But is is mentioned in the CVE that this would be the workaround for the CVE if you can not upgrade and you stay with 6.0.3.6. tThis confuses me more. So to avoid this issue with 6.0.3.6 we should call .to_s as a workaround while for 6.0.3.7 we should use symbols. 

Does this mean that 6.0.3.6 workaround for calling to_s helps with something. Why is it even mentioned as a workaround, I am wondering.

**Comment by gmcgibbon** [comment]
The problem was related to code like this: `redirect_to(["something"])` which executes `something_url` on the controller performing the redirect. We opted to use symbols because:

1. Params are always strings and not symbols.
2. It is best practice not to use user input to dictate where your app is going to redirect, this is highly exploitable.

See [the HackerOne ticket](https://hackerone.com/reports/1106652) for more info.
Redirection vulnerabilities are also mentioned in the [guides](https://guides.rubyonrails.org/security.html#redirection).

Security patches are released in accordance with the [maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html#security-issues).

**Comment by goulvench** [comment]
@gmcgibbon This error is being raised when using a generated polymorphic_path, which uses neither strings nor symbols: `edit_event_path(event)` (Rails 6.1.3.2 on Ruby 2.5.8).

Looking at the code, it seems that the path helper (`record_path`, `edit_record_path`, `new_record_path` etc) are generated use strings for the action option, thus raising the error. For instance, in [polymorphic_routes.rb line 146](https://github.com/rails/rails/blob/3b1f87aded6d42124e4272428447a642564c6677/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb#L146) the code iterates over an array of strings instead of symbols. 

I'm trying to see if I can submit a PR to work around that but you may spot more places that need adjustments, I'm not very familiar with the codebase.

**Comment by gmcgibbon** [comment]
@goulvench our test suite should've (hopefully) caught any regressions the patch introduced. Please open an issue with a a trivial app showing the issue, and I'd be happy to take a look at it!

**Comment by ukolovda** [comment]
How about `.to_sym` memory attack (Symbols are placed in "forever" memory and does not free)?

When I use `params[:tab_name].to_sym` operator, the application can consume all available RAM, if hacker will call it with different `tab_name` parameter. I should check parameter value in white list, then convert it to `Symbol`.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Arrr why is this happening in a minor update for rails 5? :( This behaviour should be reverted for rails 5 if its just a minor patch.

**Comment by thebravoman** [comment]
I think because it is a security upgrade and this follows the policies for
security. There was a comment

https://github.com/rails/rails/issues/42157#issuecomment-834852064

**Comment by goulvench** [comment]
@gmcgibbon I finally tracked down what was causing the error in my case, and it wasn't a bug in Rails after all :-)
The issue was that I was returning a class name in a `direct` block in my routes. 

Here is the code I'm using, if it can help others track down the source of the problem for them:
```ruby
# config/routes.rb
Rails.application.routes.draw do
  # other routes…

  # Generate 'meetings/1/edit' when calling `edit_event_path` when an event's delegated type is Meeting
  direct :edit_event { |model| [model.eventable_type.to_sym, { id: model.id, action: :edit }] }
end
```

**Comment by 1c7** [comment]
Is there are any simple & easy solution?
I am locking Rails version to 6.0.3.6 in Gemfile.
