### ISSUE TITLE
Cannot read property 'received' of undefined in Actioncable.js

### ISSUE THREAD

**Issue by RynoPi** [rails/rails#42189]
### Steps to reproduce
Not sure how to reproduce the error since we were not able to pin point what is causing it to happen (it does not seem like any of the front-end functionality is not working like expected). We have searched online to see if there is a thread or documentation that can explain what would cause the error and found the following old threads: https://github.com/rails/rails/issues/24418, https://github.com/rails/rails/issues/24841, but they seem unrelated. Any help to identify the cause would be much appreciated.

### Expected behavior
Not throw any error

### Actual behavior
The following error is being raised:
```
TypeError: Cannot read property 'received' of undefined
  at notify(webpack:/./node_modules/actioncable/lib/assets/compiled/action_cable.js:492:42)
  at apply(webpack:/./node_modules/actioncable/lib/assets/compiled/action_cable.js:347:43)
  at apply(webpack:/./node_modules/zone.js/dist/zone.js:1270:43)
  at apply(webpack:/../src/helpers.ts:85:17)
  at invokeTask(webpack:/./node_modules/zone.js/dist/zone.js:421:35)
  at onInvokeTask(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27483:33)
  at invokeTask(webpack:/./node_modules/zone.js/dist/zone.js:420:40)
  at runTask(webpack:/./node_modules/zone.js/dist/zone.js:188:51)
  at invoke(webpack:/./node_modules/zone.js/dist/zone.js:503:38)
  at invokeTask(webpack:/./node_modules/zone.js/dist/zone.js:1671:18)
  at WebSocket.g(webpack:/./node_modules/zone.js/dist/zone.js:1697:21)
```

Here is a snippet of the lines that the error was caused on caught by Sentry:
![Screenshot from 2021-05-10 09-29-19](https://user-images.githubusercontent.com/77432729/117622090-8e7ee100-b172-11eb-8347-43fe792f9320.png)

See the following comment from sentry regarding `at apply(webpack:/../src/helpers.ts:85:17)`:
```
// Attempt to invoke user-land function
// NOTE: If you are a Sentry user, and you are seeing this stack frame, it
//       means the sentry.javascript SDK caught an error invoking your application code. This
//       is expected behavior and NOT indicative of a bug with sentry.javascript.
```

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 2.7.2

**Actioncable.js version**: 5.2.5

**Comment by ollieri3** [comment]
I'm also experiencing an identical issue to @RynoPi in version `5.2.4-3`. Which Sentry is picking up also.

I was able to consistently replicate the issue within my application, it seems to be related to recovering the connection of previously established websocket. 

I found the easiest way to replicate was to start a Subscription thus establishing the websocket then putting my laptop to sleep, then I'd force any further reconnects to the websocket to fail by revoking the auth of the user. When waking the laptop up from sleep this is the error I'd see logged to the console.

As op mentions, I wasn't able to observe any failure in Frontend functionality so I've decided to ignore this issue from within Sentry.

I'm afraid I have no isolated reproduction steps, but hope this comment helps if any want to dive further into why the error might be occurring.

**Comment by natemontgomery** [comment]
I am towards the end of a Rails 5->6 upgrade and started encountering these errors.  In my case (a Vue v2 app) the errors were closely timed with this error in my Rails server running in Heroku:

```Started GET "/ws" for <ip> at 2021-07-02 20:14:06 +0000
Started GET "/ws/" [WebSocket] for <ip> at 2021-07-02 20:14:06 +0000
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
An unauthorized connection attempt was rejected```

I have not dug much into whether this is truly tied directly to these ActionCable errors but if this turns out to be something the Rails team needs to address I would be happy to dig deeper.

**Comment by zzak** [comment]
These types of bugs are really hard to fix if we can't reproduce them ourselves, but I realize re-creating the perfect environment to produce such bugs with ActionCable may be difficult. 🤔

**Comment by natemontgomery** [comment]
So far the only way I have consistently reproduced is to have a persistent ActionCable consumer (ie one that is created on app boot) that is long lived.  While that is open calling the `reject_unauthorized_connection` method in the Rails Channel connection triggers this to begin happening.

It appeared that the subscription in the consumer within `Subscriptions.prototype.notify` in action_cable.js becomes `undefined` and is left in the subscriptions list.  This lead the following for block to begin raising the error whenever it tries to call the `received` callback.

```
for (i = 0, len = subscriptions.length; i < len; i++) {
  subscription = subscriptions[i];
  results.push(typeof subscription[callbackName] === "function" ? subscription[callbackName].apply(subscription, args) : void 0);
}
```

After digging through the event handling JS code some more it appeared that we were getting the 'disconnect' type but without code to handle it.  Turns our we had the old Rails 5 ActionCable npm package.  Updating required us to use the `@rails/actioncable` package, which was bit difficult to track down as it seems to have been split out from the older 'actioncable' package.

For me it turned out to be an outdated client side library so not a 'bug' for Rails.  It could be better called out that you need to use a different package for npm, but that might just be something I missed somewhere.

I am not 100% sure this library mismatch is the only way to wind up with the original error message though.  It does seem to be possible that since the 'receive' event handler is the 'default' pathway for the case statement that you could fall through to that call chain in a myriad of ways.

A parting thought I had was that perhaps the Rails side could introspect on the `HTTP_SEC_WEBSOCKET_PROTOCOL` field in the Rack env with some actioncable version string that indicates semantic breakages like new event types.  Not sure exactly how all that would fit together off the top of my head but it struck me as a possibly interesting.

Hope this helps, and I would be glad to continue digging if there are further discussions around this :)

**Comment by zzak** [comment]
@natemontgomery Thanks for your reply Nate, it sounds like you were able to resolve this by upgrading the npm package?

If we can assume this was simply a compatibility issue and upgrading will resolve it, I think this can be closed.

**Comment by dantevisser** [comment]
@zzak I asked @RynoPi to log this for one of our applications.
We currently have a ticket in our sprint to upgrade the package and see if it resolves the error.

After seeing @natemontgomery 's post I realized we have another application we own that has a more up to date package and it doesn't throw this exception, so I think this is probably the fix.

In any case will ping back as soon as the ticket has been completed and we see the errors dissapear.

**Comment by natemontgomery** [comment]
Hope it helps.  @zzak I think if it turns out to be a shared issue with an outdated client side lib then the only 'work' I can think of directly is maybe documenting the potential need to change to the `@rails/actioncable` package in npm.  Not sure exactly where to do that or if it already exists and I missed it.

**Comment by dantevisser** [comment]
So we've had the updated package in production for about a week now and we're still seeing these error's pop up our side. That said, it might be something else at play. Regardless we'll continue investigation our side and report back if there's any useful information to be shared (might just be something we're doing wrong :shrug: )

Rails 6.1.3.1
Ruby 2.7.2
Actioncable.js version: 6.1.4

**Comment by ghun131** [comment]
It seems that `rails-bot` has closed this error. I have encountered this error as well and not sure how to fix it. We'll investigate and notify if there is any work around.

Rails 6.1.4
Ruby 3.0.2
Actioncable 6.1.4.1

**Comment by BerekHalfhand** [comment]
Anybody managed to solve it?

**Comment by lucasDechenier** [comment]
Anybody managed to solve it? I have de same problem

**Comment by gravytates** [comment]
We had same issue using the `actioncable` npm package version 5.2.8 in our react + rails application:
```
Subscriptions.prototype.notify in action_cable.js becomes undefined and is left in the subscriptions list. This lead the following for block to begin raising the error whenever it tries to call the received callback:

for (i = 0, len = subscriptions.length; i < len; i++) {
  subscription = subscriptions[i];
  results.push(typeof subscription[callbackName] === "function" ? subscription[callbackName].apply(subscription, args) : void 0);
}
```
We have now resolved the issue by doing a straight package swap, removing `actioncable` for `@rails/actioncable` version 8.0.200 (current version).
