### ISSUE TITLE
Cannot fully re-enable db:reset task to invoke it twice from the same Ruby process

### ISSUE THREAD

**Issue by henrahmagix** [rails/rails#42203]
### Steps to reproduce

In test code or a console session, invoke `db:reset` task once, then re-enable it (and all its prerequisites) and invoke again.

```rb
Rails.application.load_tasks
Rake::Task['db:reset'].invoke
Rake::Task['db:reset'].all_prerequisite_tasks.each(&:reenable)
Rake::Task['db:reset'].reenable
Rake::Task['db:reset'].invoke
```

### Expected behavior
The `db:reset` task runs twice: the database is dropped, created, and setup twice.

### Actual behavior
The `db:reset` task runs once, and then prints `Database 'mydb' already exists`: the database is only dropped, created, and setup once.

### System configuration
**Rails version**: `6.0.3.6`

**Ruby version**: `2.6.6`

### Reason

I think this is because the prerequisite task `db:drop` runs `db:drop:_unsafe` but does not list it as a prerequisite, so that task is not re-enabled and is not invoked a second time.

https://github.com/rails/rails/blob/91f0db1353e1b24e2d26ebbbadce510735f66848/activerecord/lib/active_record/railties/databases.rake#L62-L65

### Why am I invoking `db:reset` twice?

I have some tests that I need to run outside of transactions, so I must reset (and more importantly **reseed**) the test database after each test. I am doing this in an RSpec `around` block, so it must be sharing the Rails/Rake application in memory.

I could use `system` to run it in the shell, but that is significantly slower, so I'd rather keep it quick in the test code.

<details><summary>RSpec disable_test_transactions code</summary><p>

```rb
  config.around(:example, disable_test_transactions: true) do |example|
    if ActiveRecord::Base.connection.open_transactions > 0
      raise 'Transactions cannot be disabled when already in a transaction. This method needs reconsidering if it cannot disable transactions for tests.'
    end

    orig_use_transactional_tests = use_transactional_tests
    self.use_transactional_tests = false

    example.run

    self.use_transactional_tests = orig_use_transactional_tests

    retried_get_reset_task = false
    begin
      reset_task = Rake::Task['db:reset']
    rescue StandardError => e
      raise e if retried_get_reset_task

      retried_get_reset_task = true
      Rails.application.load_tasks
      retry
    end

    warn "Running db:reset after `disable_test_transactions: true` test"
    # Cannot run db:reset twice, even with re-enabling, because it doesn't list db:drop:_unsafe as a prerequisite.
    Rake::Task['db:drop:_unsafe'].all_prerequisite_tasks.each(&:reenable)
    Rake::Task['db:drop:_unsafe'].reenable
    reset_task.all_prerequisite_tasks.each(&:reenable)
    reset_task.reenable
    reset_task.invoke
  end
```

</p></details>

### Re-enabling `db:drop:_unsafe` does not fix this issue

Unfortunately, the code above (click to expand) isn't working: whilst it's printing `Dropped database 'mydb'` and `Created database 'mydb'` correctly, all invocations apart from the first aren't fully loading the schema, because I'm getting these errors in the subsequent tests:
```
ActiveRecord::StatementInvalid:
  PG::UndefinedTable: ERROR:  relation "my_table" does not exist
       LINE 1: SELECT 1 AS one FROM "my_table" LIMIT $1
```

**Comment by lfalcao** [comment]
@henrahmagix you should use fixtures instead of seed for tests and take a look at [database_cleaner](https://github.com/DatabaseCleaner/database_cleaner) gem 😉

**Comment by HParker** [comment]
Hey @henrahmagix,

I am confident now that this isn't a rails bug. There is a task that is not a prerequisite task and therefore is not returned from `all_prerequisite_tasks` that is required to drop your database that needs to be reenabled.

I also agree with others that managing your database this way is probably not a great idea. That being said, you can make it work by adding `Rake::Task["db:drop:_unsafe"].reenable`

I think `db:drop:_unsafe` is not listed as a prerequisite task because `drop` does not list it as a prerequisite. Instead, it is called directly from `drop` here: https://github.com/rails/rails/blob/58b46e9440f3460e93b8164205614e3ab85784da/activerecord/lib/active_record/railties/databases.rake#L64

I considered what it would take to make this work in rails the way you expected, but I am not convinced making `all_prerequisite_tasks` able to reset list all tasks `db:reset` relies on is a common enough use case to warrant changing how these database tasks work.

I am going to close this for now, but feel free to open a new issue if you disagree or open a PR if you have a good way of making `all_prerequisite_tasks` return all the tasks you want here.

**Comment by henrahmagix** [comment]
Makes sense, thanks @HParker =)
