### ISSUE TITLE
The parent record’s updated_at value does not change when has_many through: associations change

### ISSUE THREAD

**Issue by Appwerks** [rails/rails#42298]
### Steps to reproduce
I have two tables, kits and items. Each kit can have any number of items, and the tables are connected with has_many through: :kits_items relationship. I use the standard rails set up for this scenario where items_ids: [] is in the kits form params, and everything works as it should.

However, when I edit a kit’s record by adding and removing items from it, the changes are saved but the kit record’s updated_at value does not change unless one of the kit’s attributes is also modified.

### Expected behavior
The parent (kit in the example above) record should update/change updated_at value when kits_items changes are saved.

### Actual behavior
The parent’s record’s updated_at value does not change when kits_items changes are saved and the record is updated.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 3.0.0

**Comment by HParker** [comment]
Hey @Appwerks Thanks for opening this issue!

I am not sure this is a bug. I believe if you remove a `has_many through: ...` item from a relation, I don't believe I would expect the parent record to get updated.

However the behavior you want might be possible with `touch: true`
https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html

In case I am misunderstanding, do you think you can reproduce this issue using the active record reproduction script here:
https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb

This should make it easier to know where the issue is.

Thanks!

**Comment by Appwerks** [comment]
Thanks you, @HParker!

Adding `touch: true` on `belongs_to :kit` in the kits_items model did the trick.

By the way, I should have explained my case better in the original post. I have `has_many :through` for both kits to items, and items to kits, but only need to make sure that the kit model is updated when items are added and removed from each kit. The number of items is finite, so I just list them as a collection of checkboxes.

Thanks again for your reply.
