### ISSUE TITLE
ActionCable connection becomes stale with large number of consecutive events

### ISSUE THREAD

**Issue by blehoux17** [rails/rails#42336]
### Context
We've set up ActionCable to enable realtime updates with our frontend React client. We're seeing an issue where we hit the `staleThreshold` on the client side when we trigger a large number of events from the server. By default the `staleThreshold` is 6 seconds. This happens because the ActionCable server does not send pings while it's working through the queue of events. Once the queue is cleared, pinging continues. 

While the client is receiving events, the `staleThreshold` is reached and the client tries to reconnect because none of those events contains a ping message. This can cause events to be missed while the client disconnects and reconnects.

What we've done to resolve this issue is to patch the `actioncable` npm package by adding a `recordPing` call when default events are received.
``` javascript
  message: function(event) {
    var identifier, message, ref1, type;
    if (!this.isProtocolSupported()) {
      return;
    }
    ref1 = JSON.parse(event.data), identifier = ref1.identifier, message = ref1.message, type = ref1.type;
    switch (type) {
      case message_types.welcome:
        this.monitor.recordConnect();
        return this.subscriptions.reload();
      case message_types.ping:
        return this.monitor.recordPing();
      case message_types.confirmation:
        return this.subscriptions.notify(identifier, "connected");
      case message_types.rejection:
        return this.subscriptions.reject(identifier);
      default:
        this.monitor.recordPing(); // this is the line we added
        return this.subscriptions.notify(identifier, "received", message);
    }
  },
```

### Expected behavior
The client is not disconnected while receiving events from the server.

### Actual behavior
The client is disconnected if it doesn't receive ping events within the `staleThreshold` even though it's receiving other events.

### System configuration
**Rails version**:
6.0.3.7
**Ruby version**:
2.7.3
**actioncable npm version**
5.2.6

**Comment by zzak** [comment]
@blehoux17 I think some of the `staleThreshold` code changed (for example #40229), and it looks like you're on an older version of Rails. Could you try upgrading?

**Comment by jerridan** [comment]
@zzak I'm working with @blehoux17 on this. The issue we ran into is on the client side, from the npm package, and we are using the latest version (5.2.6).

**Comment by zzak** [comment]
@jerridan It looks like the latest version for Rails 6.0 on npm is [6.0.3.7](https://www.npmjs.com/package/@rails/actioncable/v/6.0.3-7), but there are even 6.1 versions available too. Could you try upgrading the npm package and letting us know?

**Comment by jerridan** [comment]
@zzak Oh! That's very interesting, there are 2 different packages, `actioncable` (5.2.6), and `@rails/actioncable` (6.0.3.7). We've been using the former. I will try switching over and see if that makes a difference.

**Comment by jerridan** [comment]
Alright, we've upgraded to use `@rails/actioncable`, and the version installed is `6.1.3` (which is odd because npm docs say `6.0.3-7` is the latest).

In any case, we are able to reproduce the same issue with the newer package. Applying our patch resolves this issue.

One thing we didn't note before is that in order to reproduce this more easily on a local machine, we changed the `staleThreshold` to 3.5s. We also ensure that there is other network activity going on at the same time, to push the server extra hard. What we're effectively doing is mocking out a scenario where there is greater network latency and the rails server is working hard enough that it is taking time to work through a queue of events and is not sending a ping.

To reiterate, the edge case is that if the server is unable to send a ping within the `staleThreshold` set by the client (due to it handling a long queue of events), the client believes it has lost the connection and attempts to reconnect. When we patch the `@rails/actioncable` code to treat regular events as pings, the issue is resolved.

We believe this change makes sense, since if any events are being received by the server, the client should consider itself connected, regardless of whether that event contains a ping message or not. We'd be happy to submit a PR, but perhaps there are other things we haven't considered yet?

Also thanks @zzak for pointing out we were using an old package!

**Comment by nvasilevski** [comment]
Reopening as it seems to be a legit problem with a clean PR to fix it.

**Comment by Amnesthesia** [comment]
We're experiencing this as well in production now. This doesn't happen in staging or other environments, but debugging why Apollo subscriptions are dropping and reconnecting in production leads to this:

<img width="907" alt="Screenshot 2024-04-05 at 11 42 26" src="https://github.com/rails/rails/assets/3265008/3865ad98-b790-4e44-b3e8-b726268abe03">
