### ISSUE TITLE
Load Error: Unable to autoload constant ActiveStorage::Blobs::RedirectController

### ISSUE THREAD

**Issue by davefaliskie** [rails/rails#42367]
### Steps to reproduce
Unfortunately, this isn't easily reproducible and happens intermittently. Active storage images configured with S3 on initial page load sometimes do not load & throw this error. If the page is then manually reloaded the images that were missing also reload. I've seen the issue on production and development, I believe it's related to rails 6. 

This is the error:
```
Unable to autoload constant ActiveStorage::Blobs::RedirectController, expected /Users/davefaliskie/.rvm/gems/ruby-2.6.6/gems/activestorage-6.1.3/app/controllers/active_storage/blobs/redirect_controller.rb to define it
```

### Expected behavior
The image loads every time with no 500 status issue

### Actual behavior
Sometimes images do not load unless the page is refreshed

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 2.6.6p146

### EDIT
I was able to get this logged in my development environment. I can't accurately reproduce this but I'm thinking maybe the S3 link maybe expired? Is there any further thoughts on Active Stroage S3 links expiring & not loading then on the reload the link path is regenerated.

```
Started GET "/portal/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE11QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12aa7d86b416df8fa24dda34f278747f73523ec6/Layla.jpeg" for ::1 at 2021-06-04 10:01:26 -0500
Started GET "/portal/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFF2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebeca7272e07203994d8f82830008e8544b3990d/DEV-mockup-25395-7.png" for ::1 at 2021-06-04 10:01:26 -0500
/Users/davefaliskie/.rvm/gems/ruby-2.6.6/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:502: warning: already initialized constant ActiveStorage::Blobs
/Users/davefaliskie/.rvm/gems/ruby-2.6.6/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:502: warning: previous definition of Blobs was here
Unable to autoload constant ActiveStorage::Blobs::RedirectController, expected /Users/davefaliskie/.rvm/gems/ruby-2.6.6/gems/activestorage-6.1.3/app/controllers/active_storage/blobs/redirect_controller.rb to define it excluded from capture: Not configured to send/capture in environment 'development'
Processing by ActiveStorage::Blobs::RedirectController#show as PNG

LoadError (Unable to autoload constant ActiveStorage::Blobs::RedirectController, expected /Users/davefaliskie/.rvm/gems/ruby-2.6.6/gems/activestorage-6.1.3/app/controllers/active_storage/blobs/redirect_controller.rb to define it):

activesupport (6.1.3) lib/active_support/dependencies.rb:564:in `load_missing_constant'
activesupport (6.1.3) lib/active_support/dependencies.rb:213:in `const_missing'
activesupport (6.1.3) lib/active_support/inflector/methods.rb:288:in `const_get'
activesupport (6.1.3) lib/active_support/inflector/methods.rb:288:in `block in constantize'
activesupport (6.1.3) lib/active_support/inflector/methods.rb:284:in `each'
activesupport (6.1.3) lib/active_support/inflector/methods.rb:284:in `inject'
activesupport (6.1.3) lib/active_support/inflector/methods.rb:284:in `constantize'
activesupport (6.1.3) lib/active_support/dependencies.rb:636:in `get'
activesupport (6.1.3) lib/active_support/dependencies.rb:667:in `constantize'
actionpack (6.1.3) lib/action_dispatch/http/request.rb:93:in `controller_class_for'
actionpack (6.1.3) lib/action_dispatch/request/utils.rb:95:in `action_encoding_template'
actionpack (6.1.3) lib/action_dispatch/request/utils.rb:83:in `encode'
actionpack (6.1.3) lib/action_dispatch/request/utils.rb:45:in `set_binary_encoding'
actionpack (6.1.3) lib/action_dispatch/http/parameters.rb:68:in `path_parameters='
actionpack (6.1.3) lib/action_dispatch/journey/router.rb:48:in `block in serve'
actionpack (6.1.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.3) lib/action_dispatch/routing/route_set.rb:842:in `call'
bullet (6.1.3) lib/bullet/rack.rb:15:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.1.3) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (6.1.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (6.1.3) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.3) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.3) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.3) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.3) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.3) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.3) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
sentry-raven (3.1.1) lib/raven/integrations/rack.rb:51:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
webpacker (5.3.0) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.1.3) lib/rails/engine.rb:539:in `call'
rack (2.2.3) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
puma (5.2.0) lib/puma/configuration.rb:247:in `call'
puma (5.2.0) lib/puma/request.rb:76:in `block in handle_request'
puma (5.2.0) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
puma (5.2.0) lib/puma/request.rb:75:in `handle_request'
puma (5.2.0) lib/puma/server.rb:432:in `process_client'
puma (5.2.0) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

**Comment by ghiculescu** [comment]
Are you using Zeitwerk, or the classic autoloader?

**Comment by davefaliskie** [comment]
> I haven't seen this before, I suspect something might be configured wrong. Are you using Zeitwerk, or the classic autoloader?

Assuming that Zetwerk is the default I initially was using that, but I did recently try `config.autoloader = :classic` and the issue was still there. 

when I migrated to rails 6 I added this to the config `config.active_storage.replace_on_assign_to_many = false` I don't think that would cause this do you?

**Comment by ghiculescu** [comment]
> Assuming that Zetwerk is the default I initially was using that, but I did recently try `config.autoloader = :classic` and the issue was still there.

Hmmm, and it's happening intermittently with either autoloader? That's concerning.

> when I migrated to rails 6 I added this to the config `config.active_storage.replace_on_assign_to_many = false` I don't think that would cause this do you?

No, I don't think so.

**Comment by zzak** [comment]
@davefaliskie Could you create a reproducible example that demonstrates this issue?

**Comment by pixeltrix** [comment]
Since we're certain that `.../blobs/redirect_controller.rb` does define the constant the most likely cause for that error is a an exception when loading the file. There's not much in there so the likely candidates are `include ActiveStorage::SetBlob` and the `ActiveStorage::BaseController` class. The former doesn't seem like it could cause any trouble but the latter calls `protect_from_forgery` - could that be causing an issue?

**Comment by davefaliskie** [comment]
> Since we're certain that `.../blobs/redirect_controller.rb` does define the constant the most likely cause for that error is a an exception when loading the file. There's not much in there so the likely candidates are `include ActiveStorage::SetBlob` and the `ActiveStorage::BaseController` class. The former doesn't seem like it could cause any trouble but the latter calls `protect_from_forgery` - could that be causing an issue?

I'm not sure I do have `protect_from_forgery prepend: true` set in application_controller.rb I don't think that's the same thing your talking about but maybe I need the prepend: true to be added in the ActiveStorage::BaseController? Do you suggest I overwrite that or is there some other way you think I could go about knowing if protect_from_forgery is the issue? I also updated the post with some more context of the error that I was able to capture.

**Comment by davefaliskie** [comment]
> @davefaliskie Could you create a reproducible example that demonstrates this issue?

I wish, unfortunately I'm not able to consistently reproduce this. I did add a bit more context of the error logged to the original post. But I still can't fin the root cause or even get it to happen consistently.

**Comment by brenogazzola** [comment]
@davefaliskie Are you for some reason changing this controller in one of your initializers, maybe to alter its functionality? I've seen this kind of intermittent error happen when I was testing things.

```
# initializers/active_storage.rb

Rails.application.config.to_prepare do
  ActiveStorage::Blobs::RedirectController.class_eval do
    # Changed code
  end
end
```

**Comment by davefaliskie** [comment]
@brenogazzola No I have no `active_storage.rb` initializer, and also don't overwrite anything for `ActiveStorage` or more specifically the `RedirectController`. Is there a change to the controller you would suggest adding, or do you just leave it at the default to prevent the intermittent errors?

**Comment by brenogazzola** [comment]
@davefaliskie Leaving it at default should not cause any intermittent errors. 

I've only seem that happen when a piece a code tries (usually in an initializer) tries to modify before it's loaded. It fails the first time, then it works fine until a change you make causes a reload.

You have a warning before it that looks weird: `already initialized constant ActiveStorage::Blobs`. And then just below someone tries to use the `redirection_controller` and prints `to define it excluded from capture`. I believe that message is from Sentry.

So...
1 - Do you have any gems (maybe in house) that are modifying active storage?
2 - If do not load sentry in the development group, do those intermittent errors stop?

**Comment by rubz0** [comment]
Hello,
Any news on this issue?
I have the same issue on 2 different MacBook with the same project :
For some reason it happens only some times but can't really figure it out why and when. But usually when it happens, I can reproduce it again and again..
It's only in local mode with a react app plugged on.

This is my core error message : 
`LoadError (Unable to autoload constant ActiveStorage::Representations::RedirectController, expected /Users/rubenmoutot/.rvm/gems/ruby-3.0.1/gems/activestorage-6.1.3.1/app/controllers/active_storage/representations/redirect_controller.rb to define it):`

And this is my full stack trace under it :
`activesupport (6.1.3.1) lib/active_support/dependencies.rb:564:in `load_missing_constant'
activesupport (6.1.3.1) lib/active_support/dependencies.rb:213:in `const_missing'
activesupport (6.1.3.1) lib/active_support/inflector/methods.rb:288:in `const_get'
activesupport (6.1.3.1) lib/active_support/inflector/methods.rb:288:in `block in constantize'
activesupport (6.1.3.1) lib/active_support/inflector/methods.rb:284:in `each'
activesupport (6.1.3.1) lib/active_support/inflector/methods.rb:284:in `inject'
activesupport (6.1.3.1) lib/active_support/inflector/methods.rb:284:in `constantize'
activesupport (6.1.3.1) lib/active_support/dependencies.rb:636:in `get'
activesupport (6.1.3.1) lib/active_support/dependencies.rb:667:in `constantize'
actionpack (6.1.3.1) lib/action_dispatch/http/request.rb:93:in `controller_class_for'
actionpack (6.1.3.1) lib/action_dispatch/request/utils.rb:95:in `action_encoding_template'
actionpack (6.1.3.1) lib/action_dispatch/request/utils.rb:83:in `encode'
actionpack (6.1.3.1) lib/action_dispatch/request/utils.rb:45:in `set_binary_encoding'
actionpack (6.1.3.1) lib/action_dispatch/http/parameters.rb:68:in `path_parameters='
actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:48:in `block in serve'
actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack-pjax (1.1.0) lib/rack/pjax.rb:12:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
scout_apm (4.0.4) lib/scout_apm/instant/middleware.rb:53:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
scout_apm (4.0.4) lib/scout_apm/middleware.rb:20:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
newrelic_rpm (6.15.0) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
newrelic_rpm (6.15.0) lib/new_relic/rack/browser_monitoring.rb:33:in `traced_call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
remotipart (1.4.4) lib/remotipart/middleware.rb:32:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
activerecord (6.1.3.1) lib/active_record/migration.rb:601:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.3.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
better_errors (2.9.1) lib/better_errors/middleware.rb:62:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
railties (6.1.3.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
activesupport (6.1.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/static.rb:24:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.1.3.1) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
newrelic_rpm (6.15.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Processing by ActiveStorage::Representations::RedirectController#show as JPEG`

Some help could be very appreciated because it's slowing down a lot our team devlopment.
Everytime it happens the server can't be stop with a simple Ctrl c, we need to open the server.pid of rails to manually kill this process..

**Comment by davefaliskie** [comment]
@rubz0 I never was able to find a solution to this and moved on. Unfortunate, it's very annoying. Would love a solution if you can find one!
