### ISSUE TITLE
controller_name returns nil in Helper Specs

### ISSUE THREAD

**Issue by koki-miyazaki** [rails/rails#42384]
### Steps to reproduce

This minitest will fail
https://gist.github.com/koki-miyazaki/b3918113cb324097ebf2203213c212e9

### Expected behavior

The above test won't fail
`#controller_name` method returns `test` string

### Actual behavior

The above minitest fails
`#controller_name` method returns nil

Before 6.1.0, `controller_name` returned string `test`

The PR made `@controller` to be a subclass of `ActionView::TestCase::TestController`
https://github.com/rails/rails/pull/40125/files#diff-ce84a807f3491121a5230d37bd40454bb1407fcca71179e1a2fa76d4c0ddfa2aR105-R106
So, it's `#name` method will be nil

my project uses `controller_name` in a helper class, so the test for it is affected by the change.

### System configuration
**Rails version**:
6.1.0
**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin18]

**Comment by ghiculescu** [comment]
@jhawthorn do you know if this was an intended side effect of https://github.com/rails/rails/pull/40125 ?

**Comment by HParker** [comment]
> do you know if this was an intended side effect of #40125 ?

Based on the comment on the PR it looks like we are aware, but it looks like `controller_path` will also return nil when the test class is anonymous before this change.

> my project uses controller_name in a helper class, so the test for it is affected by the change.

I am curious about this @koki-miyazaki . Is your helper doing something like `controller_name.match?(<something>)`? I am not sure how much more useful a string "test" is compared to nil.

That being said the PR already discussed how we could preserve `controller_name`s behavior, so it seems like a good idea to have it return something again.

**Comment by jhawthorn** [comment]
> @jhawthorn do you know if this was an intended side effect of #40125 ?

This was intentional https://github.com/rails/rails/pull/40125/files#r481338088 it is valid for `controller_name` to be `nil`. However I don't feel strongly that it must be that was if there's a compelling use case for test controllers to return `"test"`.

**Comment by koki-miyazaki** [comment]
@HParker 
> I am curious about this @koki-miyazaki . Is your helper doing something like controller_name.match?(<something>)? I am not sure how much more useful a string "test" is compared to nil.

In my project, I use `controller_name` like:
```
class SomeHelper
  def current_resource
    instance_variable_get(:"@#{controller_name.singularize}")
  end
end
```
and if controller is PostsController, current_resource returns `@post`

I just not want to break my test case which calls the method above (In fact I can stub `controller_name`, but I want to confirm whether the change was intentional and will fix in later version or not)

**Comment by HParker** [comment]
I see. Thanks @koki-miyazaki !

I think stubbing controller name in your tests might be a good option.

That is actually what rails does as well:
- https://github.com/rails/rails/blob/96f2cd010e27ad66abb5ea435949dbc48324abfd/actionpack/test/controller/render_test.rb#L12
- https://github.com/rails/rails/blob/96f2cd010e27ad66abb5ea435949dbc48324abfd/actionview/test/actionpack/controller/capture_test.rb#L9

Also, to clarify what @jhawthorn means when he says,
> it is valid for `controller_name` to be `nil`

rails won't set the controller name if your controller is anonymous.

Rails sets the controller name here:
https://github.com/rails/rails/blob/0c1ed54a2ad02a14433fda0655a2ead399d06c9e/actionpack/lib/action_controller/metal.rb#L128-L130

This means it is actually not that hard to get a controller with no name

```ruby
a = Class.new(ApplicationController)
=> #<Class:0x00007fb8a3ca3fb0>
irb(main):002:0> a.controller_name
=> nil
```

Because this is a valid state for a controller, your helper is technically already broken for anonymous controllers and this change in rails just made that more obvious.

Another option other than stubbing the controller name is making sure the `controller_name` isn't nil before asking for the instance variable with that name.

```ruby
def current_resource
  instance_variable_get(:"@#{controller_name.singularize}") unless controller_name.ni?
end
```

All this being said, I still don't have a strong opinion on if we should keep the test controller name as `test` or not. I could be persuaded that it is worth making this small change to make upgrading rails easier for people that have code like this.

**Comment by koki-miyazaki** [comment]
@HParker 
> Because this is a valid state for a controller, your helper is technically already broken for anonymous controllers and this change in rails just made that more obvious.

> Another option other than stubbing the controller name is making sure the controller_name isn't nil before asking for the instance variable with that name.

Ah that's reasonable. Thanks so much :)

> All this being said, I still don't have a strong opinion on if we should keep the test controller name as test or not. I could be persuaded that it is worth making this small change to make upgrading rails easier for people that have code like this.

Yes some other guys might be facing the same problem.

**Comment by jhawthorn** [comment]
I also don't feel strongly. It seems a bit more "correct" to return `nil`, since it is an anonymous controller, it isn't named "test" (and in the example given reading the `@test` instance variable also feels off). However I don't know if we gain anything from the more correct behaviour and clearly it's causing some upgrade friction, so let's add the override to restore the old behaviour 🙂.
