### ISSUE TITLE
ActionView::Digestor error resolving template for derived controller inside module

### ISSUE THREAD

**Issue by swalke16** [rails/rails#42417]
### Steps to reproduce
Make a simple rails app with a derived controller inside a module that makes use of caching via `fresh_when`, WITHOUT having it's own view templates and make a request to the derived controller. 

My simple example has two models `Article` and `User` and three controllers `ArticlesController`, `UsersController`, and `ArticlesControllers::UserArticlesController`.  

Routes are defined as:

```
  resources :articles
  resources :users do
    resources :articles, controller: 'articles_controllers/user_articles'
  end
```

If you request `users/1/articles` you'll see the digestor error message in the log.  

For simple reproduction, clone [this reproduction repo](https://github.com/swalke16/digest-test) and run the tests for a failing test case. 

### Expected behavior
Digestor should not raise an error looking for `articles_controllers/user_articles/index` as that is not the actual template being rendered. 

### Actual behavior
Digestor appears to be looking to digest a non-existent template even though it's not the one being rendered. 

![Screen Shot 2021-06-07 at 12 23 48 PM](https://user-images.githubusercontent.com/99454/121074042-51bdfe00-c7a1-11eb-89b3-a7e80a456560.png)

### System configuration
**Rails version**: 6.1

**Ruby version**: 2.7.2

**Comment by HParker** [comment]
Thanks for the issue @swalke16 

This is an interesting one. If you put a template at `articles_controllers/user_articles/index.html.erb` it will actually find it and use it. Since it isn't there Rails file system resolver will find the correct template to use. this code doesn't exist for deciding on etags yet.

for a workaround, you can specify `template:` in your call to `fresh_when`. something like,

```
fresh_when @articles, template: "articles/index"
```

I think it would be good if rails could find the template even though it isn't where the controller would normally have the view, but I suspect that is a nontrivial change and might have a performance cost since looking up templates dynamically like this is expensive and rails doesn't normally do this before your call to `fresh_when`.

**Comment by swalke16** [comment]
@HParker  Thanks for the reply!   I think ideally the etag generation and template resolution system would follow the same lookup rules, but like you said that's likely a nontrivial and possibly non-performant solution for what may not be a common use case.  

We can use the workaround for now, and maybe this becomes a potential enhancement for a future version.
