### ISSUE TITLE
ActiveRecord: `belongs_to :something, optional: true` accepts invalid foreign key values

### ISSUE THREAD

**Issue by dorianmariefr** [rails/rails#42460]
### Steps to reproduce

https://gist.github.com/dorianmariefr/6b0310aad5746c48974f6a2bb5b214c5

### Expected behavior

raises `ActiveRecord::RecordInvalid` like when there is no `optional: true` and an invalid foreign key value is passed

### Actual behavior

passes validations and stores invalid foreign key value

### System configuration

**Rails version**: main, `7.0.0.alpha`

**Ruby version**:`ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]`

### Comments

I think this is open for debate, and it would break backward compatibility, so maybe a new parameter is needed

**Comment by Flixt** [comment]
I understand the confusion.

The `ActiveRecord::RecordInvalid` error is raised when the association is not marked as optional and the associated record is not present. The reason is, that ActiveRecord does add a PresenceValidator onto the association (not the id attribute) when the association is required/not optional (which `belongs_to` is by default).

I am not sure if this really is an issue with Rails itself.
In my opinion if you want to ensure referential integrity, you should add a foreign key constraint.

From the docs:

> belongs_to does not ensure reference consistency, so depending on the use case, you might also need to add a database-level foreign key constraint on the reference column

```
create_table :comments, force: true do |t|
  t.references :post, null: true, foreign_key: true
end
```

This leads to an `ActiveRecord::InvalidForeignKey` error being raised. 

Having the foreign key constraint really is the only way of being 100% sure your referential integrity is not violated.

If you don't want to add a foreign key constraint to the DB, or you need the error on the application level, you could add a validation which ensures the foreign record exists, by adding a presence validator onto the association yourself, like this:

```ruby
class Comment < ActiveRecord::Base
  belongs_to :post, optional: true

  validates_presence_of :post, if: -> { post_id.present? }
end
```

**Comment by dorianmariefr** [comment]
The proposed solution is pretty good thanks
