### ISSUE TITLE
add autocomplete="OFF" to firefox-proof automagically added hidden fields like _method

### ISSUE THREAD

**Issue by jpwynn** [rails/rails#42610]
I suggest "bullet-proofing" any Rails-auto-added hidden fields by **also** auto-adding autocomplete="OFF"

As reported/diagnosed in May of WTFs: https://discuss.rubyonrails.org/t/form-with-first-field-value-is-overriden-with-a-token-like-string/74861/11 there is a 12-year-old **Firefox** bug that (sporadically, but pretty frequently) overwrites the first hidden_field in a form UNLESS it has autocomplete=OFF

The forum discussion doesn't propose any action other than nag Mozilla (who left it there for 12 years).

The results are to semi-randomly crash perfectly-coded Rails apps if, say, Rails inserts "_method=patch" but it gets submitted as "_method=5f4ledBRFGRYSUpaeJ29y-J0SX6KRSzbr1zSjVvgy1fhGmQAXXzsjLxdswyBtqopEnO6pQAaJTEFUJKXDVyisg" as in the specific example shown below (Firefox,on the left, Chrome on the right).

Because the addition of autocomplete=OFF _does_ fortunately seem to workaround 100%, it seems to me to be a simple, safe, benign, no-side-effects addition. I'd submit a PR if I had any idea how.

![sidebyside](https://user-images.githubusercontent.com/446451/123504734-a8776480-d5f6-11eb-8cf7-fb1244b4b52b.jpg)

**Comment by pixeltrix** [comment]
Do you have a link to the Firefox bug report?

**Comment by pixeltrix** [comment]
Nevermind - I can see it in the discussion post

**Comment by jpwynn** [comment]
There are a few, closed, the one that was reopened is https://bugzilla.mozilla.org/show_bug.cgi?id=520561

**Comment by pixeltrix** [comment]
Thanks - has anyone tracked down in the Firefox source code where this is happening?  Also do you have any idea where the autocomplete values are coming from? Seems like there must be some other web framework using `_method` and storing a Base64 encoded value in there.

I'm generally dubious about adding browser specific workarounds as they tend to get forgotten or treated as 'acts of faith' (e.g. for years Rails returned a single space in an empty response because of a Safari bug that had long been fixed). However I'm not 💯 percent against the idea - just need to confirm the exact conditions for this bug occurring.

**Comment by jpwynn** [comment]
Yeah I was hesitant to suggest it, except it is so darned pernicious and gnarly to debug for developers when it does happen, and the fix seems entirely benign (turning off autocomplete for a form field that is hidden hence should NOT be autocompleted anyway).

This other bug report does address reproducibility to some extent:
https://bugzilla.mozilla.org/show_bug.cgi?id=1667657

For my own rails app, while zipping back and forth between a few forms it works fine - until it doesn't and it "stays" broken until I close the browser. Hence the screen gran=b next time it happened.

**Comment by pixeltrix** [comment]
> This other bug report does address reproducibility to some extent: https://bugzilla.mozilla.org/show_bug.cgi?id=1667657

That one is really weird - it's not a generic name like `_method` that could be set by other sites, but a field name specific to that application. How is that getting a Base64 encoded value from autocomplete? Feels like there's more going on here than just Firefox autocomplete ignoring the fact that a field type is 'hidden'.

**Comment by jpwynn** [comment]
Right, not field name at all. I originally went to May of WTFs to report a bug where (I thought) the hidden field name had "key" like "video_key" it got stomped on, then saw that other report I linked and realized _not_ the field name, but the position, and Firefox specific.

Yeah I was hesitant to suggest the fix, _except_ it is so darned pernicious and gnarly to debug for developers when it does happen to a end-user whose Rails app Just Stops Working. (Or any app for that matter, it was originally reported a decade ago for some Microsoft framework) . 

But i did because the fix seems entirely benign: turning off autocomplete for a form field that is hidden anyway hence should NOT be autocompleted anyway under any circumstances.

This other bug report does address reproducibility to some extent:
https://bugzilla.mozilla.org/show_bug.cgi?id=1667657

AFAIK no one knows the conditions "for this bug occurring" since it comes and goes... but what they _do_ know is the conditions for stopping it: autocomplete=OFF really does seem to do the trick.

For my own rails app, by simply zipping back and forth between a few specific forms I can eventually get it to break and "stay" broken until I close the browser. Hence that screen grab above the next time it happened.

Ditto another form page with a little more complicated JQuery going on (in-browser video recording)... worked fine  until it suddenly started post'ing corrupted video identifiers , but in that case, being my form already using POST, I had control over all the form fields (except the authenticity token, which is usually last, and therefore immune) so I could simply add autocomplete=OFF to all MY hidden fields and have not see it occur again.

I assume there is no "setting" in Rails (like with scaffold generators) that allows someone to override the behavior of whatever magic generates the "_method" hidden field?

So the implications for Rails apps, sans a fix, are simple: "Don't use Firefox, it's _not_ our fault, but just don't"

**Comment by pixeltrix** [comment]
> I assume there is no "setting" in Rails (like with scaffold generators) that allows someone to override the behavior of whatever magic generates the "_method" hidden field? (If so, then a code change isn't strictly needed, just let devs know how to override the field generator for any hidden field)

The simplest option would be to monkey patch `ActionView::Helpers::Tags::HiddenField#render` like this:

```
module ActionView
  module Helpers
    module Tags
      class HiddenField < TextField
        def render
          @options[:autocomplete] = "off"
          super
        end
      end
    end
  end
end
```

Not tested but it'll be something like that should add `autocomplete="off"` to all your hidden fields constructed using the `form.hidden_field` method. For the lower level `hidden_field_tag` method you'll need to override it in a helper like this:

```
def hidden_field_tag(name, value = nil, options = {})
  super(name, value, options.merge(autocomplete: "off"))
end
```

> So the implications for Rails apps, sans a fix, are simple: "Don't use Firefox, it's not our fault, but just don't"

Please avoid snarky comments like this - it's a 12 year old Firefox bug that they haven't felt bothered to fix so I don't see why Rails should be rushing out a patch release to work around it. I understand you're frustrated but the suggested fix would affect everyone else's apps so we need to fully understand how/why the issue occurs and any unintended consequences of the suggested fix - for example there's a comment about how some HTML validators would fail which could result in peoples CI breaking if they're using such tools to check output.

Do other frameworks output `autocomplete=off` by default on hidden fields? This doesn't seem to be Rails-specific bug so how have other frameworks 'fixed' this?

**Comment by zzak** [comment]
Not sure how relevant this was but after a brief search it seems Chrome doesn't even support `autocomplete="off"`?

**Comment by jpwynn** [comment]
autocomplete="off" is currently an official tag, and passes validator.w3.org (using an example with it added to a hidden field) for example the snippet below (with the setting added to all hidden fields) passes w3 validator.

Chrome may or may not _act upon_ an autocomplete="off" setting but it is benign for the setting to be there (or not) in Chrome.

```
<!DOCTYPE html>
<html class='h-full antialiased' lang='en'>
<head>
<title>
Hospice Inbox
</title>
<meta content='width=device-width, initial-scale=1' name='viewport'>
<meta content='none' name='robots'>
</head>
<body>

<form action="/posts/send_video_create" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="AAAAAAAAAA" />
<input value="14" autocomplete="off" type="hidden" name="page_id" id="page_id" />
<input type="hidden" name="firefoxidiots" id="firefoxidiots" value="dummystring" autocomplete="off" />
<input type="hidden" name="backupkey" id="backupkey" value="53117ebc9de4d08a3995" autocomplete="off" />
<input value="ziggeo" autocomplete="off" type="hidden" name="video_processor" id="video_processor" />
<input value="210627-53117ebc9de4d08a3995" autocomplete="off" type="hidden" name="video_key" id="video_key" />
<input value="TOKEN" id="field_for_video_token" autocomplete="off" type="hidden" name="video_token" />
<input value="127.0.0.1" autocomplete="off" type="hidden" name="author_ip" id="author_ip" />
<input value="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0" autocomplete="off" type="hidden" name="author_ua" id="author_ua" />
</form>
</body>
</html>
```

**Comment by domchristie** [comment]
FWIW I've also had `authenticity_token` hidden fields autocompleted as well as `_method` fields. Only tested locally.

**Comment by domchristie** [comment]
> Not tested but it'll be something like that should add autocomplete="off" to all your hidden fields constructed using the form.hidden_field method. For the lower level hidden_field_tag method you'll need to override it in a helper

Unfortunately this won't work for framework-generated hidden fields such as [`_method`](https://github.com/rails/rails/blob/91593af849e00ba8de7602ae86670a1e0ac7fbae/actionview/lib/action_view/helpers/url_helper.rb#L761)

**Comment by ryanfb** [comment]
Rolling the suggestions above all together and adding some more, here's what's working for me to force `autocomplete="off"` onto all Rails-generated hidden input tags (as of Rails 6.1.4):
`lib/core_extensions/action_view/helpers/form_tag_helper.rb`:
```ruby
module CoreExtensions
  module ActionView
    module Helpers
      module FormTagHelper
        def hidden_field_tag(name, value = nil, options = {})
          super(name, value, options.merge(autocomplete: 'off'))
        end
      end
    end
  end
end
```
`lib/core_extensions/action_view/helpers/tags.rb`:
```ruby
module CoreExtensions
  module ActionView
    module Helpers
      module Tags
        class HiddenField
          def render
            @options[:autocomplete] = 'off'
            super
          end
        end
      end
    end
  end
end
```
`lib/core_extensions/action_view/helpers/url_helper.rb`:
```ruby
module CoreExtensions
  module ActionView
    module Helpers
      module UrlHelper
        private

        def token_tag(token = nil, form_options: {})
          if token != false && defined?(protect_against_forgery?) && protect_against_forgery?
            token ||= form_authenticity_token(form_options: form_options)
            tag(:input, type: 'hidden', name: request_forgery_protection_token.to_s, value: token, autocomplete: 'off')
          else
            ''
          end
        end

        def method_tag(method)
          tag('input', type: 'hidden', name: '_method', value: method.to_s, autocomplete: 'off')
        end
      end
    end
  end
end
```
`config/initializers/hidden_field_autocomplete.rb`:
```ruby
ActionView::Helpers::FormTagHelper.prepend CoreExtensions::ActionView::Helpers::FormTagHelper
ActionView::Helpers::Tags.prepend CoreExtensions::ActionView::Helpers::Tags
ActionView::Helpers::UrlHelper.prepend CoreExtensions::ActionView::Helpers::UrlHelper
```

**Comment by jwilsjustin** [comment]
This may help. I was also experiencing this in the `name="_method"` input generated by the `button_to` method. I am adding `autocomplete="off"` to the [parent form element](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#disabling_autocompletion).

```erb
<%= button_to post_path(post), method: :delete, form: {autocomplete: "off"} do %>
  <i class="delete"></i>
  Delete
<% end %>
```

This is an easy addition without having to monkey patch.

**Comment by ryanfb** [comment]
I've just published the first version of a Rails plugin gem (`rails-hidden_autocomplete`) that bundles together my solution from the comment above for easy re-use in other Rails applications:

https://github.com/podqueue/rails-hidden_autocomplete

**Comment by brendon** [comment]
This is not an entirely benign change as it's useful to have a hidden field with `autocomplete="username"` to hint the username to password managers on password reset forms. It appears there's no way to override it. Would anyone be interested in looking at a PR that at least allows it to be overridden if required?

**Comment by brendon** [comment]
Thanks @ryanfb :) Having ‘autocomplete’ on the form seems like it might be asking for future trouble. Will browsers one day interpret that as meaning autocomplete is off for the whole form?

I ended up finding a PR that addresses the issue but might need a bit of work. Really all that needs changing as far as I can see is just using ‘reverse_merge’ instead of ‘merge’ on the options and the attribute will be able to be set again.

https://github.com/rails/rails/pull/47798

Hopefully we can get some traction on the PR and the Firefox bug! Seems like a crazy one!

**Comment by pixeltrix** [comment]
@ryanfb I'm just investigating this again due to the fact that it's now invalid HTML but using your [reproduction test website][1] seems to show that even with `autocomplete="off"` the bug is now happening. 🤯 

Can you check if you're seeing what I'm seeing:

Before submission:
![image](https://github.com/user-attachments/assets/060555a3-8812-44a4-8c60-11daef87cbb5)

After submission:
![image](https://github.com/user-attachments/assets/43162f3a-a0c5-4ee7-9e42-8d3241fae641)

If this is truly the case it seems like at this point there's no point in generating the `autocomplete="off"`.

[1]: https://ryanfb.xyz/firefox-autocomplete-poc/

**Comment by brendon** [comment]
> Thanks @ryanfb :) Having ‘autocomplete’ on the form seems like it might be asking for future trouble. Will browsers one day interpret that as meaning autocomplete is off for the whole form?
> 
> I ended up finding a PR that addresses the issue but might need a bit of work. Really all that needs changing as far as I can see is just using ‘reverse_merge’ instead of ‘merge’ on the options and the attribute will be able to be set again.
> 
> #47798
> 
> Hopefully we can get some traction on the PR and the Firefox bug! Seems like a crazy one!

I ended up making my own PR that was recently merged that allows one to override the `off` or remove the attribute by setting it to `nil`.

Sad to see that the workaround isn't working. I wonder if the Firefox team needs a new but report as the old one seems to have languished and perhaps the right people aren't being notified?

**Comment by pixeltrix** [comment]
> Sad to see that the workaround isn't working. I wonder if the Firefox team needs a new but report as the old one seems to have languished and perhaps the right people aren't being notified?

Hmm, seems to have started working again now:

![image](https://github.com/user-attachments/assets/6b59bf77-e2ab-47df-b6f8-5dc3b29198a0)

I probably must have mixed the steps up or something

**Comment by ryanfb** [comment]
@pixeltrix The test can be a little confusing (and the bug can also be a little confusing); it's expected that after clicking submit the first time the form values should be altered. The bug occurs when Firefox persists those JS-altered hidden form values across a reload or a fresh page load, which setting `autocomplete="off"` prevents (no other browser has this behavior).

So for example, if you load the page then click submit, it alters BOTH hidden form inputs. If you click submit again without reloading you should get alerts for BOTH hidden form inputs no longer having a value of "test". You'll see this behavior in every browser.

To test the hidden form value persistence bug (which I've only seen in Firefox), you should load the page then click submit, then reload the page, then click submit again. If the browser is exhibiting the bug, on this first click after reloading you should only get one alert (about the value of `youshouldntseethis` not matching "test"). If you get alerts for both `youshouldntseethis` and `youalsoshouldntseethis` on the first submit after a fresh page load, then that would mean it's also affecting hidden inputs with `autocomplete="off"`.

**Comment by pixeltrix** [comment]
@ryanfb thanks for the clarification - I think I must've not hit the right key combo to reload.

A couple of extra information points:

1. If you hard reload then the form will reset to both inputs being "test"
2. There's a [changeset][1] that changes the behaviour when "cache-control: no-store" is set - that was a fix for bug [1752250][2]

It's arguable that this is correct behaviour because it's restoring input contents on a soft reload in the same way it would with a textarea even if you have set them via JavaScript. The scenario where it's restoring values that weren't set by the page itself that's the bigger concern, however this is virtually impossible to reproduce in a consistent manner.

[1]: https://hg.mozilla.org/integration/autoland/rev/e881ef466324
[2]: https://bugzilla.mozilla.org/show_bug.cgi?id=1752250

**Comment by pixeltrix** [comment]
Another data point is bug [539228][1] which describes how Firefox restores the form based on order and not by id or name. You can see this in the demo if you change the order of the fields after exhibiting the bug then the value reverts to test since there's no saved value for second input.

This explains how the `_method` field can end up with a CSRF token in it since [`extra_tags_for_forms`][2] renders it before the token tag when it's required. With the standard Rails CRUD pattern you end up with forms like this: 

New resource
``` html
<form action="/posts" method="post">
<input type="hidden" name="authenticity_token" value="...">
```

Edit resource
``` html
<form action="/posts/1" method="post">
<input type="hidden" name="_method" value="patch">
<input type="hidden" name="authenticity_token" value="...">
```

There's an argument that always rendering the token tag first would help but it's likely that without `autocomplete="off"` you'd see invalid CSRF token errors instead as Firefox replaced the new token with an old one.

I also looked at some alternatives - `readonly` also isn't valid HTML and doesn't work. Setting `autocomplete` to a valid value like `one-time-code` also doesn't work.

Firefox users must be getting weird errors when using multi-step forms that use hidden fields to record previous steps as it seems like the combination of restoring based on order and restoring hidden fields would be triggered by such a pattern. Also seems an oversight on the HTML spec that there isn't a valid way of telling a browser not to mess with an input.

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=539228
[2]: https://github.com/rails/rails/blob/dd8f718/actionview/lib/action_view/helpers/form_tag_helper.rb#L1013-L1041

**Comment by pixeltrix** [comment]
There's also a similar report from 2019: 
https://github.com/rails/rails/pull/37687

It's interesting because of the turbolinks context - to investigate I modified the demo to add the following links:
![image](https://github.com/user-attachments/assets/e6bedfc0-dfba-41a3-9ae4-bb2e5062158c)

The 'Navigate' link is just a link back to the page and the 'Reload' link does a `window.location.reload()`. The bug is not reproduced with the former but is with the latter. This makes me think that all the instances that people are seeing are related to restoring form state after Javascript-initiated action.

**Comment by awilfox** [comment]
FWIW, I just came to this bug because it no longer validates with w3:

![Image](https://github.com/user-attachments/assets/15a28ffe-17de-43d6-904c-ca4b6d3ceb28)

It seems to be [valid according to the WHATWG standard](https://html.spec.whatwg.org/#hidden-state-(type=hidden)), so I think this is a bug in the validator.
