### ISSUE TITLE
Update of belongs to association resets of variable with associations

### ISSUE THREAD

**Issue by DmytroVasin** [rails/rails#42613]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.4"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamps
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, optional: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!

    post.comments.create!
    post.comments.create!

    all_comments = post.comments
    all_comments.update_all(post_id: nil)

    assert all_comments.any?
  end
end
```

### Actual behavior
The proxy collection was reset to the blank array.

Moreover we receive additional request:
```
Comment Exists? (0.0ms)  SELECT 1 AS one FROM "comments" WHERE "comments"."post_id" = ? LIMIT ?  [["post_id", 1], ["LIMIT", 1]]
```

### Expected behavior
Update of association should not have an influence on `Proxy collection`.

### NOTE
That was broken with the last patch release of `rails 6.1.4`.
I've launched the script on `6.1.3.2`, `6.1.3.1`, `6.1.3`, `6.1.2.1` and it works as expected without additional request.

### System configuration
Rails version: 6.1.3
Ruby version: 2.7

## Related:
Maybe this related to:
* https://github.com/rails/rails/issues/42597
* https://github.com/rails/rails/pull/42601

**Comment by mdemare** [comment]
I recommend `assert !all_comments.proxy_association.empty?` as a starting point as to the difference between 6.1.4 and earlier versions. In that method (in `collection_association.rb`) there's a test for `target.empty?` that yields different results.

In 6.1.4, the target is empty because `reset` was called in `update_all` - this new behavior was introduced in https://github.com/rails/rails/pull/41789.

That's also why there is another query. When `target.empty?` is true, `CollectionAssociation#empty?` executes a `scope.exists?`.

I'd defer to the core committers as to whether this is a bug. `all_comments` is a collection association and there are warnings regarding the behavior of `target` here: https://github.com/rails/rails/blob/0ffdf6dfe7e5dbb7d9119ee68c21ccd813d18b26/activerecord/lib/active_record/associations/collection_association.rb#L21

The behavior is somewhat surprising though, and it does bring this to mind: https://martinfowler.com/bliki/TwoHardThings.html

**Comment by DmytroVasin** [comment]
I assume such an update broke pretty common usage of `update_all`:
```ruby
def async_destroy!
  all_comments = @post.comments
  all_comments.update_all(post_id: nil)

  Packages::BulkDeleteWorker.perform_async(all_comments.map(&:id))
end
```

@kamipo Could you check/prove that this is the expected/new behavior of a feature that you've done in https://github.com/rails/rails/pull/41789?

**Comment by zzak** [comment]
@DmytroVasin Can you verify this was fixed by #42601? 🙏

**Comment by DmytroVasin** [comment]
@zzak No :( 

I've launched the test from the description on `main` branch ( `Using activerecord 7.0.0.alpha` ) and I've received same result (Empty array)

**Comment by mikdiet** [comment]
I also faced with this bug when updating my 6.0 application to rails 6.1.

My workaround was to build another relation with `all`

```
all_comments.all.update_all(post_id: nil)
```

so `update_all` won't mutate `all_comments` variable.
