### ISSUE TITLE
Method doing nothing when we pass a string

### ISSUE THREAD

**Issue by FakeCast** [rails/rails#42628]
When you pass a string as an argument to this sanitisation method, it returns the string without any sanitisation, is this an expected behaviour and has some reason behind it?

https://github.com/rails/rails/blob/75ac626c4e21129d8296d4206a1960563cc3d4aa/activerecord/lib/active_record/sanitization.rb#L22

Thank you

**Comment by alexcameron89** [comment]
Hey @FakeCast, yes that's expected behavior. I'm not sure on the exact reasoning behind it (probably to allow the use of the method in other areas of Active Record and respond happily to string statements), but you could bring up the topic in the [Rails Discussion Forum](https://discuss.rubyonrails.org/) if you want to dig into it more.

We reserve the GitHub issues for bugs in Rails, so I'm going to close this ticket.
