### ISSUE TITLE
rails routes adds not existing structure to path when engine named 'Collection'

### ISSUE THREAD

**Issue by jepzen** [rails/rails#42667]
### Steps to reproduce
Create a new rails app.
Generate and Engine with the name "Collection"
Mount the engine and generate a scaffold in the engine
Run rails routes

Sample repo here
https://github.com/jepzen/bad_module_name

### Expected behavior
I expect the outcome of `rails routes` to be 
`posts GET    /posts(.:format)          collection/posts#index`

### Actual behavior
not prefixed with 'rails/initializable'
`posts GET    /posts(.:format)          rails/initializable/collection/posts#index`

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 3.0.1

**Comment by mdemare** [comment]
In your repo, `Collection::Engine` is a subclass of `Rails::Engine`, which includes `Rails::Initializable`, which contains a constant called `Collection` (full name `Rails::Initializable::Collection`) which according to Ruby's constant lookup rules gets preference over your own `::Collection` module.

So, technically not a bug - use `isolate_namespace ::Collection` instead of `isolate_namespace Collection`. Pretty confusing though!

**Comment by jepzen** [comment]
Yeah you are right. Thanks a lot!
