### ISSUE TITLE
Deprecation warning in 6.1 if a `default_scope` contains a `where.not`

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#42759]
Copying from https://github.com/rails/rails/pull/39328 as a new issue. I tried to fix it but couldn't figure out how to. https://github.com/rails/rails/pull/42481 contains some failing tests that I'm happy for anyone else to use.

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post

  default_scope -> { where.not(post_id: nil) }
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    # DEPRECATION WARNING: Merging ("comments"."post_id" IS NOT NULL) and ("comments"."post_id" = ?) no longer maintain both conditions, and will be replaced by the latter in Rails 7.0. To migrate to Rails 7.0's behavior, use `relation.merge(other, rewhere: true)`. (called from test_association_stuff at test.rb:47)
    post.comments.to_a
  end
end
```

The issue is that I'm not calling `merge` directly, so it's not clear how to fix the deprecation warning.

(In the app that this warning came up on, we ended up removing the default scope.)

**Comment by kreintjes** [comment]
Same issue over here. A fix would be appreciated.

**Comment by intrip** [comment]
@ghiculescu 
https://github.com/rails/rails/pull/39328 introduces a check which handles when we'll merge multiple `where id = ?`  clauses because it's a use case in which we cannot reliably merge the conditions => they are conflicting within each other.

Here's what happens in this particular situation:
- there is a `default_scope` which introduces the following condition: `"comments"."post_id" IS NOT NULL`
- when `post.comments` is called AR adds the condition `"comments"."post_id" = "#{post.id}"` in order to retrieve the correct comments

This is a particular edge case of https://github.com/rails/rails/pull/39328 because in this situation `post_id IS NOT NULL` doesn't interfere with the other conditional (in fact it basically does nothing).
I think we can extend https://github.com/rails/rails/pull/39328 such that when we'll try to merge `id IS NOT NULL` with `ID = ?` we'll just ignore the "NOT NULL" part and don't show the warning. 
If you agree I'll make a PR.

If you want to workaround the deprecation warning in this particular situation you can just use a SQL fragment  `default_scope -> { where("post_id IS NOT NULL") }`.

**Comment by kreintjes** [comment]
I think it's worth it. We need this default scope (for when accessing this model directly, i.e. not through the association) and cannot remove it. Thanks for the workaround @intrip, we will use that for now!

**Comment by ghiculescu** [comment]
@intrip  I tried to fix in https://github.com/rails/rails/pull/42481 but didn't have much luck. If you can fix it that'd be awesome. Feel free to reuse my tests.

Appreciate the workaround.

**Comment by intrip** [comment]
@ghiculescu Thanks! I'll give it a stub starting from #42481.

**Comment by intrip** [comment]
@ghiculescu https://github.com/rails/rails/pull/43354 fixes this edge case: merging a "where not nil" condition.

I've also checked https://github.com/rails/rails/pull/42481 but I think it tries to solve a more general issue and I don't really know how we could  do it since by default the `default_scope` is always merged with the other conditionals and this can sometimes trigger the more general issue handled by https://github.com/rails/rails/pull/39328.

**Comment by intrip** [comment]
ping

**Comment by ghiculescu** [comment]
This is no longer an issue on `main`.
