### ISSUE TITLE
`config.host_authorization.*` missing from the configuration guide

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/rails#42815]
Action Dispatch’s host authorization middleware takes two options, `:excludes` and `:response_app`, which are populated from `config.host_authorization.excludes` and `config.host_authorization.response_app`, respectively. Unless I’m mistaken, those options need to be added to [this guide](https://edgeguides.rubyonrails.org/configuring.html).

**Comment by ShaneBoyer** [comment]
Hello, 
I ran into trouble getting the host authorization `exclude` functionality to work following the Configuring Rails Applications [Configuration Middleware](https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization).  I ended up in the [host_authorization.rb source documentation](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/middleware/host_authorization.rb), which documents  `config.host_authorization` instead of `config.host_configuration`.   Once I made that change, exclusions worked as expected.

I stumbled across this issue looking for any open issues on the Configuring Rails Applications documentation.  Am I reading this correctly that the `host_configuration` references in the documentation should be replaced by `host_authorization`?

**Comment by SkipKayhil** [comment]
> Am I reading this correctly that the `host_configuration` references in the documentation should be replaced by `host_authorization`?

Yeah that looks correct to me, the only occurrences of `host_configuration` I see in the repo are in the guide you mention. I would definitely open a PR
