### ISSUE TITLE
ConnectionHandler#clear_all_connections! doesn't actually clear all connections when using multiple databases

### ISSUE THREAD

**Issue by josh-m-sharpe** [rails/rails#42852]
### Steps to reproduce
1. open mysql client
2. `show status where variable_name = 'threads_connected';`
3. `1` ( the mysql client. good.)
4. `bundle exec rails console`
5. `show status where variable_name = 'threads_connected';`
6. `2` (mysql client and writer)
7. `some_klass = User` # pick your class
8.  `some_klass.last.id`
9. `show status where variable_name = 'threads_connected';`
10.  Still `2`. makes sense. (mysql client, writer)
11.  `some_klass.connected_to(role: :reader){ some_klass.last.id }`
12. `show status where variable_name = 'threads_connected';`
13.  `3`  makes sense (mysql client, writer and reader)
14.  `ActiveRecord::Base.clear_all_connections!`
15. `show status where variable_name = 'threads_connected';`
16. `2` What?  Why not 1?
17. Try all the things:
18. `ActiveRecord::Base.clear_active_connections!`
19. `ActiveRecord::Base.connection_handler.clear_all_connections!`
20. `ActiveRecord::Base.connection_handler.clear_all_connections!`
21. `ActiveRecord::Base.connection_handler.connection_pools.each(&:reap)`
22. `show status where variable_name = 'threads_connected';`
23. Still `2`. No bueno.
24. `ActiveRecord::Base.connected_to(role: :reader){ ActiveRecord::Base.clear_all_connections! }`
25. `1` Finally. (the mysql client, so rails disconnected everything)

### Expected behavior
I would expect step 16 above to show 1 connected thread.
`ActiveRecord::Base.clear_all_connections!` would clear all connections, including 'connected_to' connections.
Or if that doesn't work, maybe we need a new method that does this.

### Actual behavior
ActiveRecord::Base.clear_all_connections doesn't clear connections made with 'connected_to' 

### Bigger picture problem:
We maintain multiple connections using `connected_to` (this is a simplified list: :writing, :reader, :slow_reader, :delayed_reader)

Being somewhat aware of this 'clear_all_connections' shortcoming, we create an array of known connected roles and iterate over that to both disconnect and reconnect before/after forking unicorn and resque during deploy.

However, we found out the hard way today we cannot *remove* roles from our database.yml because (it seems?) there's no good way to simply clear all connections.  Our current architecture reads database.yml to get the list of active connections.  So when we send an 'upgrade' to unicorn it just reloads the new database.yml and attempts to disconnect all connections in the newly reloaded database.yml.  There doesn't seem to be a great way to introspect through ActiveRecord which connections are still open - *especially* those that may have been removed from database.yml.

More specifically, we deploy with two roles:
`writing`, `reader`
We decide to rename `reader` to `reader_new_hotness`
When we deploy, and upgrade unicorn, unicorn reloads database.yml, and gets `[:writing, :reader_new_hotness]` which it then disconnects and reconnects to as it forks itself. It disconnects with: `[:writing, :reader_new_hotness].each{|role_name| ActiveRecord::Base.connected_to(:role: role_name){ ActiveRecord::Base.clear_all_connections! }` `reader` isn't in databse.yml anymore so it's not disconnected.  Bad things proceed to happen.

Certainly, there's more than a few operational things we could do to mitigate this, but it would be helpful if AR could provide a way to disconnect everything.

This thing:
```
ActiveRecord::Base.connection_handlers.keys.each{|k| puts k ; ActiveRecord::Base.connected_to(role: k){ ActiveRecord::Base.clear_all_connections! }}
```
maybe gets us part of the way there, but would need some more vetting to understand if it works during a reload/change as described above.  I think it may not work because `ActiveRecord::Base.connection_handlers.keys` shows all keys from database.yml (including unconnected ones) which makes me think it's not leveraging active connection objects.

### System configuration
6.0.3.7

**Ruby version**:
2.6.8

**Comment by eileencodes** [comment]
I've read over this a couple times and I'm a bit confused. I think there are some issues with the setup of your application because a lot of the behavior described here isn't how multiple databases is designed to be used. Below I've gone over some of the questions/points in your issue.

> ActiveRecord::Base.clear_all_connections doesn't clear connections made with 'connected_to'

Connections are created with `connects_to`. Any call to `connected_to` using `role` switches to already established connections. Originally `connected_to` supported a `database` kwarg that created connections on demand but since I got so many bug reports that were using it incorrectly I've removed that functionality without replacement in 6.1. Lots of apps were using it to kind of implement sharding but that's not what it was built for and it has dangerous side effects if used in requests, so it's removed. If you're using `role` then `connected_to` is not creating new connections, it just switches connection handlers.

> ActiveRecord::Base.clear_all_connections! would clear all connections, including 'connected_to' connections.

The behavior here is intentional. When multiple databases was originally designed (the behavior in 6.0) each of the connections is accessed via the handler so you need to all clear connections _per handler_ rather than all connections. It would be strange for the writing handler to clear connections for the reading handler, a totally separate handler object. In 6.1 we implemented new connection handling behavior so that we have only 1 handler and the pools aren't completely isolated from one another but in order to prevent breaking/surprising changes we maintained the behavior with this method.

If you want to clear connections on all handlers you can do it like this which would avoid any issues with having to know the names of the handler roles:

```ruby
ActiveRecord::Base.connection_handlers.each do |handler|
  handler.clear_all_connections!
end
```

> Or if that doesn't work, maybe we need a new method that does this.

I think we can easily add a new method, but we cannot change the existing method without breaking existing apps.

> However, we found out the hard way today we cannot remove roles from our database.yml because (it seems?) there's no good way to simply clear all connections

The database.yml doesn't define the roles, just connection names. Roles are only defined in `connects_to` and then used in `connected_to` or associated methods, so I don't totally follow this comment. Based on the issues defined here I think that your app might be using multiple databases incorrectly. The guides/docs are here https://guides.rubyonrails.org/active_record_multiple_databases.html

> writing, reader
> We decide to rename reader to reader_new_hotness

If you name your roles something other than `writing` and `reading` you must add the configuration option for `active_record.writing_role` and `active_record.reading_role` otherwise Rails has no idea which database to treat as the primary and replica.

Hope that helps clarify things!

**Comment by josh-m-sharpe** [comment]
@eileencodes Thank you for reading and responding!

Apologies I got my nomenclature wrong.  I agree that that 'names' that are defined in database.yml are not considered 'roles'.  We use `connects_to database: {reader: :reader, reader_2: reader_2, etc...` but we explicitly do not use a `reading` connection because we want o be explicit about when we use different connections and we do that with FooKlass.connected_to(role: :reader){ FooKlass.where(etc...)}`

So, while we aren't using a standard 'reading' connection I don't think we are doing anything unsupported.

----

That all said, the request here is to define a method that normalizes your suggestion (btw, I had to stick a `.values` in there for this to work (v6.0.3.7)):

```
ActiveRecord::Base.connection_handlers.values.each do |handler|
  handler.clear_all_connections!
end
```

I suggest this because apps such as unicorn/resque that fork need to do that before forking.

In our initial implementation I attempted to simply use `ActiveRecord::Base.clear_all_connections!` thinking it would do what it says, then implemented something else that didn't handle the scenario of our database.yml being altered (because my solution re-read that file - and then didn't clobber the old connections which were loaded, but no longer in the file.  this was bad.).

So yea a method that clears all active connections which can be used prior to forking resque/unicorn or the like would be helpful.  `clobber_all_active_connections!` maybe?  or maybe we add an option to clear_all_connections! ?  I'm not sure what's best here.
