### ISSUE TITLE
Action Text Editor does not focus to the sentence when redo or undo

### ISSUE THREAD

**Issue by Ramyani-QI** [rails/rails#43030]
### Steps to reproduce
Write some paragraphs so that page scroll can go down.
Then make few words as bold which are somewhere on the top section of the content and then scroll down again to the end of the content.
Then try to Undo / Redo .

### Expected behavior
page scroll should focus to that section where Undo / Redo is happening.

### Actual behavior
the content was getting changed (unbold / bold) while doing Undo / Redo . But the page scroll focus did not reach to that section. It was still on the end of content.

**Comment by p8** [comment]
Hi @Ramyani-QI, thanks for reporting the issue!
This does seem like a Trix issue instead of a Rails issue as there isn't any interaction with Rails when redoing/undoing.
I see you already opened an issue in the Trix repository: https://github.com/basecamp/trix/issues/924
Hopefully it gets fixed there.
