### ISSUE TITLE
Missing breaking change info

### ISSUE THREAD

**Issue by estani** [rails/rails#43074]
This line:
https://github.com/rails/rails/blob/4ae0390c1051a39ec16a4a95451cd06172a1b260/activerecord/lib/active_record/core.rb#L76

introduced a method `default_role` which is exposed in all ActiveRecords, in our case it collied with a method named the same. It would be great if this could be added as a potential breaking change to version 6.1 (in 6.0 this wasn't there).

A better design, would be to not expose all this methods, since they should grow indefinitely.
Perhaps consider for Rails 7 to encapsulate them all? (e.g. in a "proxy" object or something like that: `model.proxy.active_record_method`)
This will avoid the naming conflicts.

**Comment by eileencodes** [comment]
We introduce new methods to Active Record all the time and it doesn't count as a breaking change if your application implemented the same method and they collided. A breaking change would be if we changed a public API without a deprecation warning. I'm going to close this as there's nothing for us to do here.

**Comment by estani** [comment]
Ok, but a change that breaks things is hardly not a "breaking change"... kind of the definition.

Adding methods to a public interface, which the user is suppose to extend with its own, is definitely a breaking change imho.
Of course you can not mark them as "deprecated", as it will slow down releases a lot. Putting all those methods somewhere else `model.active_record` would not cause this many "breaking changes".

Just wanted lo leave this here, as this needs sooner or later be fixed. ActiveRecords ned to be prefixed, if my proposal is not good, another should be made, but accepting collisions as "non-breaking changes" is not a good solution in my opinion.

**Comment by thomasdziedzic-census** [comment]
I think that a breaking change means different things to different people here:

1. From the perspective of rails, a breaking change is changing a public api.
2. From the perspective of the user, a breaking change is something that breaks the code base suddenly.

I agree with Eileen that this technically isn't a breaking change from the rails api perspective, but I also agree with estani that from the perspective of the user, this is definitely a breaking change because it breaks existing code bases that had a default_role attribute that worked in rails 6.0 but not in 6.1.

Furthermore, if the purpose of your class is to be extended by the end user with custom attributes, then that now becomes part of the users extended api which now breaks with rails 6.1.

I think a rails release warning that an attribute name is going to be reserved in a future release and that you should migrate to another attribute name would have allowed for a smoother migration experience.
