### ISSUE TITLE
Action Cable subscriptions fail in production with Rails 6.1.4 and Ruby 3.0.2: `WebSocket error occurred: wrong number of arguments (given 2, expected 1)`

### ISSUE THREAD

**Issue by ssarunas** [rails/rails#43191]
### Description
After upgrading the Rails 6.1.4 application from Ruby 2.6.5 to Ruby 3.0.2, Action Cable subscriptions no longer work. The following exception is being raised: `WebSocket error occurred: the wrong number of arguments (given 2, expected 1)`. 

If I revert Ruby upgrade and go back to Ruby 2.6.5, application works as expected.

The weird part is that it affects only the production environment. Action Cable works as expected in the development environment with both Ruby versions (2.6.5 & 3.0.2).

#### Backend
```ruby
# app/channels/application_cable/channel.rb
module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end


# app/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_authorized_user
    end

    private

    def find_authorized_user
      if (authorized_user = env['warden'].user)
        authorized_user
      else
        reject_unauthorized_connection
      end
    end
  end
end

# app/channels/product_viewers_channel.rb
class ProductViewersChannel < ApplicationCable::Channel
  def subscribed
    stream_from "#{channel_name}:#{params[:product_id]}"
    broadcast_to params[:product_id], "#{current_user.full_name} joined"
  end

  def unsubscribed
    broadcast_to params[:product_id], "#{current_user.full_name} left"
  end
end

# config/environments/production.rb
  config.action_cable.url = 'wss://XXXX.XX/cable'
  config.action_cable.allowed_request_origins = [ 'https://XXXX.XX' ]
```
#### NGINX
```bash
server {

   ...

   location /cable {

        proxy_set_header        Host $host;
	proxy_set_header        X-Forwarded-Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_read_timeout      90;

	proxy_redirect off;

	proxy_connect_timeout 90;
	proxy_send_timeout    90;
	proxy_buffer_size    64k;
	proxy_buffers     16 32k;
	proxy_busy_buffers_size 64k;
	proxy_temp_file_write_size 64k;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
	proxy_pass              http://XXX.XXX.XXX.XXX:3000;
   }
   
   ...
   
}
```

#### Client
```js
import { createConsumer } from '@rails/actioncable';

(() => {
  const consumer = createConsumer();

  consumer.subscriptions.create({ channel: 'ProductViewersChannel', product_id: 1 }, {
    received(message) {
      console.log(message);
    }
  });
})();
```

### Expected behavior
A message should be broadcasted through a WebSockets connection and appear in the browser's console.

### Actual behavior
Browser's console:
```
action_cable.js:211 WebSocket connection to 'wss://XXXX.XX/cable' failed: WebSocket is closed before the connection is established.
```

Log file:
```bash
I, [2021-09-09T12:47:07.976576 #6996]  INFO -- : [8dc98e26-e703-4c40-87b3-eb4844c74a6d] Started GET "/cable" for XXX.XXX.XXX.XXX at 2021-09-09 12:47:07 +0300
I, [2021-09-09T12:47:07.977492 #6996]  INFO -- : [8dc98e26-e703-4c40-87b3-eb4844c74a6d] Started GET "/cable/" [WebSocket] for XXX.XXX.XXX.XXX at 2021-09-09 12:47:07 +0300
I, [2021-09-09T12:47:07.977617 #6996]  INFO -- : [8dc98e26-e703-4c40-87b3-eb4844c74a6d] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)
E, [2021-09-09T12:47:07.978140 #6996] ERROR -- : [8dc98e26-e703-4c40-87b3-eb4844c74a6d] WebSocket error occurred: wrong number of arguments (given 2, expected 1)
```

### System configuration
**Rails version**: 6.1.4

**Ruby version**: 3.0.2

**Comment by ssarunas** [comment]
The issue was caused by an outdated passenger version. Passenger upgrade fixed the problem.

**Comment by coolprobn** [comment]
I was getting the similar issue with the same error `websocket error occurred: wrong number of arguments (given 2, expected 1)`.

I had pinpointed the issue to breaking change in Ruby 3 [Separation of positional and keyword arguments in Ruby 3.0](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) but couldn't exactly figure out the exact location or the gem/package/code which was throwing the error.

I had tried upgrading Passenger after I stumbled upon this issue.

We are on ubuntu 18 (due to be updated!!) for our production server in the client project and passenger was not being upgraded with simple `sudo apt-get update && sudo apt-get upgrade`. I also noticed that issue was not there in Staging server which is running the same Ubuntu version BUT different Passenger version.

Today I researched for a way to upgrade only the Passenger without upgrading the Ubuntu version and the issue was resolved after following instructions from https://madebot.com/upgrading-passenger-on-ubuntu/ 

Passenger upgrade commands:

```
$ sudo apt-get --allow-releaseinfo-change update
$ sudo apt-get update
$ sudo apt-get upgrade
```

This upgraded the Passenger from "Passenger 6.0.4" to "Phusion Passenger(R) 6.0.17" and the issue was resolved 😌

The issue seemed to be because of Ruby version incompatibility issue with Passenger. It was using syntax and code from old Ruby (< 3.0) while our production Rails app had already been upgraded to Ruby 3.
