### ISSUE TITLE
Rails standardized error reporting interface

### ISSUE THREAD

**Issue by byroot** [rails/rails#43472]
### Context

A very common pattern when dealing with exceptions is to report them asynchronously to the developer and continue with some fallback. E.g.

```ruby
begin
  do_something
rescue SomethingIsBroken => error
  MyErrorReportingService.notify(error)
  some_fallback_code_or_value
end
```

An example in Rails is [in `ActiveSupport::Cache::RedisCacheStore` we simply log handled errors](https://github.com/rails/rails/blob/46bb4dee09e9a3dc7db2cfded2221212fdf183ff/activesupport/lib/active_support/cache/redis_cache_store.rb#L58-L62).

That is the kind of errors you'd want reported to your error monitoring service so that even though the error is not directly breaking the user experience, you are alerted early that some part of your infrastructure is no longer working, and might take action, or that some edge case is causing a degraded experience.

Another example is [the recent `ActiveSupport::Notifications` handling of exceptions raised by `finish`](https://github.com/rails/rails/pull/43282).
In such case the most appropriate behaviour could be to swallow the exception, as to not interrupt the notification chain, but to report it to the application developer.

In application code it's easy because you know where to send the exception report, but in libraries and frameworks, usually the best you can do is log the error. But people usually don't look at logs unless they know something is happening.

### Introducing a standard interface for error reporting services

Since the vast majority of Rails application out there do setup an error reporting service (Sentry, Airbrake, Errbit, HoneyBadger, and plenty others), 
I believe there's an opportunity for Rails to provide a generic interface to report errors, with an adapter API to allow using the service of your choice. 
In other term, introducing an Active Job or Active Support Cache for error reporting.

There would be several upsides to this.

#### Reporting the errors handled by Rails

When Rails handles an error like in the examples listed above, it could report them properly to the developer, instead of logging them where no-one will see.

#### Reporting warnings

Similarly [there are places in Rails were we emit warnings](https://github.com/rails/rails/blob/46bb4dee09e9a3dc7db2cfded2221212fdf183ff/activerecord/lib/active_record/railtie.rb#L156), but they aren't easy to notice.
Many error reporting service have some kind of `severity` attribute, so Rails could report these as exceptions with `severity: warning`.

#### Simplified collection of unhandled errors

The hooking mechanism would be simplified. The various error reporting gems out there are doing a lot of work to hook into Rack / Sidekiq / Resque etc.
It's brittle and hard to maintain and setup. It's also often not covering all entry points such as `rails runner` being invoked from a crontab, etc.

If Rails was in charge of collecting unhandled errors, it could do it more easily, likely as part of `ActiveSupport::Executor`, and it would automatically cover all Rails entry points.

#### Simplified errors notification service setup

The setup of the various error reporting service could be heavily simplified. They could ship a `Railtie` in their gem and
automatically register themselves to receive the exceptions. No need to add a middleware in Rack, or require some code to hook into Sidekiq and such.

### Interface Requirements

I believe that along the error itself with its backtrace, there are two essential attributes that need to be communicated:

  - `handled: true/false`: Wether the error was properly handled by the application, or if it was "final" (e.g. displayed a 500)
  - `severity: error/warning`: Even when it's handled by the application, an error can either be "nice to know about", or important to fix quickly. As such I think it's important to be able to communicate this.

Of course all reporting services don't just log the error, they collect various contextual data alongside it.
This often include request or job parameters, sometimes app specific data such as an `user_id`, etc.

So the interface would need to be extensible. 

We can probably draw some inspiration from the recent `ActiveRecord::QueryLogs`, the need is similar, as we enter some paths we do want to append some data to the error reporter context. e.g. Job class and parameters when performing a job.

Or even refactor `ActiveRecord::QueryLogs.set_context`, to move it to a more generic namespace, and share it with the error reporter, as many of the data will be the same.

And it is also important to be able to pass extra data when reporting an error, e.g.:

```ruby
Rails.error.report(some_error, context: { foo: "bar" })
```

The signature could be something like:

```ruby
def report(error, handled: true, severity: :error, context: {})
end
```

There is likely some other interface requirements I'm not thinking about, so I'd like to involve as many of these gems maintainers as possible to collect some feedback.

### Feedback

At this early stage I would love to hear some feedback from the maintainers of the various error monitoring gems out there:

@imjoehaines (Bugsnag)
@st0012 (Sentry)
@joshuap, @shalvah (HoneyBadger)
@kyrylo (Airbrake)
@waltjones (Rollbar)
@samuel-holt, @mogest (Raygun)
@composit, @dlanderson, @okapusta (Scout)
@angelatan2, @amhuntsman, @tannalynn, @jasonrclark (NewRelic)

Sorry if I forgot other popular services. And apologies if you didn't wish to be pinged.

If not, I'd have a few questions:

  - Would you integrate with such interface?
  - What kind of metadata do you need provided by this interface?

cc @rafaelfranca @eileencodes @jhawthorn

**Comment by SamSaffron** [comment]
Some things to consider are boundaries here between Rails and the apps. 

Specifically stuff like https://github.com/discourse/logster likes to grab backtraces, if it got the call from rails in a dedicated thread it may or may not have a backtrace, similar concerns around "env". 

I guess the "subscriber" needs some way of telling rails what context it needs passed on and maybe even give it a lambda so the decision can be made at call time. 

At Discourse we use: 

https://github.com/discourse/discourse/blob/main/lib/discourse.rb#L854-L874

**Comment by SamSaffron** [comment]
> I'm not certain I correctly understand what you describe.

Sorry, I was thinking more about the "subscribe" side of things: 

```
Rails.error.subscribe("logster") do |err, ctx|
   ctx ||= {}
   ctx[:backtrace] = caller
   Logster.report(err, ctx)
end

Rails.error.report("hello") # Hello
```

If "subscribe" lambda is called on a different thread to `report` then you can not fill in context there. So I guess we would need some callback for context filling.

```
Rails.error.context("logster") do |ctx|
   # fill in thread context here
end
```

**Comment by byroot** [comment]
Ok, I think I get what you mean now.

So first, I think it should be called in the same thread, if the reporter then want to use background threads to submit the error asyncronously great, but I don't think this API should do the threading.

Second, that's why I mentioned `ActiveRecord::QueryLogs.set_context`, I think for the most part the context object should be built along the way like we do for query logs.

**Comment by SamSaffron** [comment]
I see, then 👍 from me I would certainly add support for this kind of interface to both logster and rack-mini-profiler.

How do Rails core developers decide when to write something to the logs with severity :error or :fatal vs using the new interface? Does the new interface automatically ship with a Logger subscriber?

**Comment by st0012** [comment]
@byroot Thanks for proposing this and sorry for being so late on providing feedback. I just want to add more information about how Sentry's SDK work with Rails.

### What does Sentry do with its middleware?

`sentry-rails` injects a middleware called `Sentry::Rails::CaptureExceptions` to the middleware stack. This is mainly to

1. Capture exceptions raised from controller actions and some middlewares (e.g. `ActiveRecord::Migration::CheckPending`).
2. Capture rack env and store it in the current context.
3. Wrap the rest of middleware stack inside a Transaction (a performance tracking unit in Sentry), which will be reported after the block returned.

Regarding 1), it may be replaced by the `DebugExceptions` interceptors once we drop Rails 5 support.
3) still needs to be done in a middleware to capture traffics that doesn't enter Rails controllers. I'm not sure if Rails would provide interface for such use case? 
And because 3) needs to happen in a middleware, 2) also needs to be at the same middleware to provide enough information for it. 

### Available Contextual Data in Sentry

These are the main contextual data used in the SDK:

- User - a Ruby hash, e.g. `{ id: 1, name: "John" }`
- Level (severity) - a symbol, e.g. `:warning`
- Context - key-hash paris, like `character: { name: "John", age: 5 }`. It'll provide detail information about the event's context.
- Extra - key-value paris, like `name: "John", age: 5`. It's similar to Context but more loosely structured. We'll deprecate this in the future.
- Transaction name - a simple string value indicates the current action. e.g. `PostsController#index` or `OrderConfirmationJob`.
- Tags - simple key-value pairs, like `name: "Stan"`. They're mainly used for filtering/grouping events.

And the SDK adds contextual data:

- When the request enters the SDK middleware, we records the request's rack env.
- When the request enters the controller, we use the controller & action name to set the transaction name.
- Before a ActiveJob starts, we set the transaction name with the job class.

So my questions are:

- Will `set_context` be the only interface for setting all the contextual data? Or it'll be possible to add `set_tags` and `set_user` in the future?
    - Same question for the `Rails.error.report` interface. Will `context` be the only valid key, or it'll be more flexible to accept other keys, as long as the underneath implementation accepts it?
- SDKs usually support a wide range of Rails versions. For example, Sentry supports Rails 5.0+ all the way to 7.0. This means we'll likely keep the old implementation until we can retire all the pre-7 support and use the new and nice interface. Otherwise, mainaining 2 implementations will just be too expensive.
  Given this situation, do you think it's possible to have a Rails-supported gem that provides the same interface for 6.0+ versions too? That way, we can migrate to the new interface once we drop Rails 5 support.

**Comment by byroot** [comment]
> 3) still needs to be done in a middleware to capture traffics that doesn't enter Rails controllers. I'm not sure if Rails would provide interface for such use case?

I believe the proper interface for this is executor's hooks. It will allow you to wrap jobs and requests alike at a fairly low level.

> Will set_context be the only interface for setting all the contextual data? Or it'll be possible to add set_tags and set_user in the future?

At this stage yes. I believe it's fine to continue using `Sentry.set_user` or whatever other service specific API. The goal isn't to make `Sentry` and other APIs disapear from app code, but to allow service agnostic code to report errors too.

So something like:

```ruby
Sentry.set_tags('page.locale': 'de-at')
...
Rails.error.handle { ... }
```

Is perfectly fine to me.

> Otherwise, mainaining 2 implementations will just be too expensive.

Have you looked at #43625 ? Right now the adapter would look like this:

```ruby
module Sentry
  def self.report(error, handled:, severity:, context:)
    # Translate context however you like 
    Sentry.capture_exception(error, level: severity)
  end
  # in sentry/railtie.rb
  class Railtie < Rails::Railtie
    initializer "sentry.error_subscriber" do
      Rails.error.subscribe(Sentry)
    end
  end
end
```

I don't think you are required to change much to your gem, just add a thin translation layer.

**Comment by st0012** [comment]
> I believe the proper interface for this is executor's hooks.

I'm not familiar with this yet but will check it. thanks for the hint 👍 

>  The goal isn't to make Sentry and other APIs disapear from app code, but to allow service agnostic code to report errors too.

I see 👍 

> Have you looked at #43625 ? Right now the adapter would look like this:

what I meant is that, ideally this can replace the current error capturing logic we have in the middleware. but because we also need to support Rails 6, which doesn't have this interface yet, we need to keep that error capturing code for it.

so now, the SDK will have
- the new error subscriber for Rails 7
- the current error capturing logic for Rails 6 and below
  - also, to avoid repeated reporting in Rails 7, we need a condition to disable this mechanism in Rails 7.

what I proposed is that, it'd be great to have a gem to also add the error subscriber concept to Rails 6. then we can complete remove the old error capturing code and use the new subscriber pattern.

**Comment by casperisfine** [comment]
> it'd be great to have a gem to also add the error subscriber concept to Rails 6

Ok. I'll keep that in mind and consider it once I'm done with Rails 7 (assuming this actually ship for 7).

**Comment by tenderlove** [comment]
I really like this idea.  @casperisfine it seems like this issue is more of a "requirements gathering" issue.  Should I leave feedback here or on the PR?  I'd like to see this feature merged, so please direct me where I can be most useful (whether it's here or the PR)!

**Comment by byroot** [comment]
@tenderlove either place is fine
