### ISSUE TITLE
activerecord typecasts strings in "exponential notation"

### ISSUE THREAD

**Issue by v1ct0r** [rails/rails#43724]
### Steps to reproduce

ActiveRecord's typecasts string values from DB to Floats if strings looks like floats in exponential notation, for instance "4e2" 

```sql
CREATE TABLE public.messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    client_key character varying
);

insert into messages(client_key) values ('4e2');
```

Then read client_key attribute in rails console:
```ruby
> message.client_key 
NoMethodError: undefined method `[]' for 400.0:Float
```

### Expected behavior

to receive value as string without typecast to float
"4e2"

### Actual behavior

Exception during reading value
NoMethodError: undefined method `[]' for 400.0:Float
...
/usr/local/bundle/gems/ruby/3.0.0/gems/activerecord-7.0.0.alpha2/lib/active_record/attribute_methods/read.rb:32:in `read_attribute'
/usr/local/bundle/gems/ruby/3.0.0/gems/activerecord-7.0.0.alpha2/lib/active_record/attribute_methods.rb:330:in `[]'
...
### System configuration
**Rails version**: 7.0.0-alpha2

**Ruby version**: 3.0.0

**Comment by v1ct0r** [comment]
it can be solved by specifying `::ActiveRecord::Type::String.new` as a field custom typecast class
```ruby
class Message < ApplicationRecord
  attribute :client_key, ::ActiveRecord::Type::String.new
  ...
```

**Comment by hahmed** [comment]
Thanks for reporting this issue, I have a few questions;
- What database are you using? (I'm guessing it's Postgresql because of the `character varying` db type)
- What is the db version?
- When you read the value from the database, what is the value? Is the value returned as a string?
- I'm assuming the client_key attribute in the schema.rb is marked as a string? (I'm guessing it is, but just making sure)...

I tried to recreate this using the bug template, even though I'm assigning a float, it's still working as expected, as in the message attribute is returned as string. Could you get a reproduction script up by any chance?

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: "testdb")
ActiveRecord::Base.logger = Logger.new(STDOUT)


ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :message
  end
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_string
    u =  User.create(message: Float('4e2')) # or User.create(message: 4e2)
    assert u.message
  end
end
```

**Comment by himanshugoyal-git** [comment]
Same observation as @hahmed  on the specified rails version i.e 7.0.0-alpha2.

**Comment by fatkodima** [comment]
@v1ct0r, @himanshugoyal-git can you provide a reproducible script?
