### ISSUE TITLE
ActiveSupport::Cache::MemoryStore not "reload safe?"

### ISSUE THREAD

**Issue by speckins** [rails/rails#43767]
### Steps to reproduce
Run with `bundle exec rails runner <script>`

```ruby
File.write('app/models/foo.rb', 'class Foo; end', mode: 'wx')

begin
  # Load our newly created Foo model
  Rails.application.reloader.reload!

  # Cache an instance of Foo
  cache = ActiveSupport::Cache::MemoryStore.new
  cache.write :foo, Foo.new

  # Reload constants
  Rails.application.reloader.reload!

  # Read the Foo
  cache.read :foo
  # *boom*
  # Foo can't be referred to (TypeError)
ensure
  File.unlink 'app/models/foo.rb'
end
```

### Expected behavior

It doesn't raise an error.

### Actual behavior
`TypeError` ("Foo can't be referred to") is raised.

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 2.7.4

https://github.com/ruby/ruby/blob/master/marshal.c#L267
https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache.rb#L1005

I ran across this in the "development" environment when caching one of my application's PORO objects.  It only happens once a file is edited, presumably triggering a zeitwerk reload.  I ran the above script in a new Rails 6.1.4.1 + Ruby 2.7.4 application and reproduced the behavior.

**Comment by ghiculescu** [comment]
This is similar to https://github.com/rails/rails/issues/43856

**Comment by ghiculescu** [comment]
@fxn to me this seems like it would be hard/unlikely to get fixed, but I thought I'd check with you too.

**Comment by fxn** [comment]
Yeah, you do not store objects in caches, sessions, job arguments, etc. It's brittle. I'll followup with a more comprehensive answer for this particular case.

**Comment by fxn** [comment]
## The gist of it

Using just Ruby, the gist of what's happening here is the following

```
% irb
> C = Class.new
> c = C.new
=> #<C:0x00007f790b9a1678>
> C = Class.new
(irb):3: warning: already initialized constant C
(irb):1: warning: previous definition of C was here
=> C
> Marshal.dump(c)
(irb):4:in `dump': C can't be referred to (TypeError)
```

AS uses `Marshal.load(Marshal.dump(value))` do deep clone the object.

## This is fundamental

This issue is not a bug, it is conceptual, let me explain.

In general, it is a bad practice to store instances in places that survive your lifecycle. Why? Because when you reload, or when you redeploy in production, the classes may have changed. They may have been even deleted. Those serialized instances are stale and potentially invalid, but the application is going to try to use them. I mentioned some examples in the previous comment.

This is not an issue with numbers or strings, say, but it is with application code.

In the case of the memory store, instances do not survive the process. But in development you reload in order to have fresh definitions of everything. So it is like a redeploy, anything reloadable may have changed. You can see this in the console using a simple variable that holds the stale object:

```
% bin/rails c
Loading development environment (Rails 7.0.0)
> user = User.new
=> #<User:0x00007fed35d2ad28>
> reload!
Reloading...
=> true                                                       
> User.object_id
=> 13680
> user.class.object_id
=> 60220
```

See? The class object `user` is an instance of is stale and invalid. It's a different object. Indeed, maybe you added a method to `User` and removed another one, and `user` wouldn't reflect those changes.

If instead of using `ActiveSupport::Cache::MemoryStore` the application used a hash table in memory, the same would happen: on reload, instances of reloadable classes would become stale.

So this is not something you can "fix", it is a fundamental issue: The application serializes stuff that is subject to change, and that is not going to work conceptually, regardless of whether you are using the console, a hash, or the memory cache.

## What to do?

1. If that cache is Redis in production or something else that survives redeploys, I'd recommend to not serialize application objects at all. Like you don't do in sessions or job arguments.
2. If you totally need to serialize objects for some reason, then you need to deal with potential discrepancies, because you're going to find them in production.

In development, you can also clear the cache on reload by running in an initializer the following (off the top of my head):

```ruby
unless Rails.application.config.cache_classes
  Rails.application.config.to_prepare { Rails.cache.clear }
end
```

But the first option you'd want to consider is not storing instances serialized in the first place.

**Comment by ghiculescu** [comment]
I think it’s worth adding some notes to this effect to the caching guide, what do you think?

**Comment by fxn** [comment]
@ghiculescu yes please :).

**Comment by se2342** [comment]
@fxn Thank you so much for taking the time to explain this in detail!
