### ISSUE TITLE
TypeError on Rails.cache.fetch after modifying cached instance's class

### ISSUE THREAD

**Issue by se2342** [rails/rails#43856]
### Steps to reproduce

* Rails in `development` environment
* Use `ActiveSupport::Cache::MemoryStore`

__Controller__
```ruby
Rails.cache.fetch("organisations/by_subdomain/#{request.subdomain}", expires_in: 5.minutes) do
  current_organisation = Organisation.find_by(subdomain: request.subdomain)
end
```

__organisation.rb__
```ruby
class Organisation < ApplicationRecord
  has_many :users, dependent: :destroy

  validates :name,
    presence: true

  validates :subdomain,
    presence: true,
    uniqueness: true,
    length: { minimum: 4, maximum: 32 }
end
```

### Expected behavior

Calling `Organisation.find_by()` in the `Rails.cache.fetch` block results in the returned instance of the model's class being cached. When performing changes on the model's class (`organisation.rb`) while being in development the cached (and marshalled) data gets invalidated gracefully.

### Actual behavior

After performing changes on the model's class while in development a `TypeError` (`Organisation can't be referred to`) is being raised when calling the `Rails.cache.fetch` block.

### System configuration

**Rails version**: main @ `e8c0293`

**Ruby version**: `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin20]`

**pg Gem**: 1.2.3

**Postgres**: 13.5.1

**Comment by ghiculescu** [comment]
Yes, keeping an instance of the record in memory while code is reloaded can be unreliable. I'm not sure if this *could* be improved in the reloader; I think it's always going to be a bit finicky.

In general I'd recommend caching IDs and then using them for fast primary key lookups rather than caching AR objects. Otherwise you might cache the wrong thing in a variety of cases. In your given example, if the `Organisation` is changed in any way you'll have a stale organisation object cached for up to 5 minutes.

**Comment by se2342** [comment]
See https://github.com/rails/rails/issues/43767#issuecomment-1000988644.
