### ISSUE TITLE
Fix for CVE-2021-44528 broke config.hosts by domain on version 6.1.4.3

### ISSUE THREAD

**Issue by mshtawythug** [rails/rails#43879]
### Steps to reproduce
Add a domain in your hosts configuration
```ruby
 config.hosts = %w(.example.com)
```

### Expected behavior
Any subdomain of example.com should be allowed to send requests

### Actual behavior
Blocked host: error is raised
```
Blocked host:somedomain.example.com
To allow requests to somedomain.example.com, add the following to your environment configuration:
config.hosts << "somedomain.example.com"
```

### System configuration
**Rails version**:  `6.1.4.3`

**Ruby version**: ANY

**Comment by ghiculescu** [comment]
Hmm, these tests are both passing against `main` for me:

```ruby
  test "passes requests to allowed hosts with domain name notation from a subdomain" do
    @app = ActionDispatch::HostAuthorization.new(App, [".example.com"])

    get "/", env: {
      "HOST" => "somedomain.example.com",
      "action_dispatch.show_detailed_exceptions" => true
    }

    assert_response :ok
    assert_equal "Success", body
  end

  test "passes requests to allowed hosts with domain name notation from a top level domain" do
    @app = ActionDispatch::HostAuthorization.new(App, [".example.com"])

    get "/", env: {
      "HOST" => "example.com",
      "action_dispatch.show_detailed_exceptions" => true
    }

    assert_response :ok
    assert_equal "Success", body
  end
```

Is there any more detail you can share to help replicate?

**Comment by brittlewis12** [comment]
we are also seeing this since our update to 6.1.4.2 — localhost is being blocked in development, despite the default configuration, without an explicit reference to the port:

## broken (default):
<img width="458" alt="Screen Shot 2021-12-15 at 12 50 41" src="https://user-images.githubusercontent.com/4894936/146239116-74ed22f3-dacf-42ec-8e2c-ca73ba2d0366.png">
<img width="854" alt="Screen Shot 2021-12-15 at 12 50 55" src="https://user-images.githubusercontent.com/4894936/146239120-5ed24033-b695-42f5-81bf-19dd1b148034.png">

## working:
<img width="459" alt="Screen Shot 2021-12-15 at 12 51 31" src="https://user-images.githubusercontent.com/4894936/146239173-ac0d29ce-fd44-4ad3-8c82-6900a16f2079.png">

also want to note the leading dot for subdomain wildcards had no impact in either case.

**Comment by SkipKayhil** [comment]
> we are also seeing this since our update to 6.1.4.2 — localhost is being blocked in development, despite the default configuration, without an explicit reference to the port:

This is a bug in 6.1.4.2 that should be fixed in 6.1.4.3, have you tried updating?

**Comment by brittlewis12** [comment]
@SkipKayhil thanks, I misinterpreted this issue as reporting that behavior persisting — the upgrade to 6.1.4.3 does seem to have resolved what we were seeing!

**Comment by rafaelfranca** [comment]
Duplicate of #43870

**Comment by ghiculescu** [comment]
@rafaelfranca I thought this was a different issue since it doesn't involve a port.

**Comment by rafaelfranca** [comment]
People just forget to include that important part in the report.

**Comment by mshtawythug** [comment]
@rafaelfranca We were seeing this in production on 6.1.4.3, I will test this again and see if I missed something
