### ISSUE TITLE
find_by_sql empty list when using 'NOT IN' clause

### ISSUE THREAD

**Issue by roharon** [rails/rails#43935]
### Steps to reproduce

```ruby

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.string :description
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_find_by_sql_with_not_in_clause
    Post.create!(title: "First Post", description: "description")
    Post.create!(title: "Second Post", description: "description")

    post_ids = []
    posts = Post.find_by_sql(["SELECT * FROM posts WHERE id NOT IN (:post_ids)", post_ids: post_ids])

    assert_equal 2, posts.count
  end
end

```
### Expected behavior

```ruby
2
Post Load (0.1ms)  SELECT * FROM posts WHERE id NOT IN (FALSE)
# OR
Post Load (0.1ms)  SELECT * FROM posts WHERE 1=1
# same as Post.where.not(id: [])

```

`Post.find_by_sql(["SELECT * FROM posts WHERE id NOT IN (:post_ids)", post_ids: post_ids])'` return `[]` seems like unnatural when it passed empty list on NOT IN CLAUSE variable.

I think it should be return `#<ActiveRecord::Relation [#<Post id: 1, title: \"First Post\", description: \"description\">, #<Post id: 2, title: \"Second Post\", description: \"description\">]>`
Because category_post id is matched and `titles` list variable is not include category_post.title ("First Title").

### Actual behavior

```ruby
0
Post Load (0.1ms)  SELECT * FROM posts WHERE id NOT IN (NULL)
```

### System configuration
**Rails version**: 7.1.0.alpha

**Ruby version**: 3.0.2

**Comment by jesselasalle** [comment]
Should the line below be changed?

`posts = Post.find_by_sql(["SELECT * FROM posts WHERE id NOT IN (:post_ids)", post_ids: post_ids])`

`posts = Post.find_by_sql(["SELECT * FROM posts WHERE id NOT IN (:post_ids)", {post_ids: post_ids}])`

**Comment by roharon** [comment]
> Should the line below be changed?
> 
> `posts = Post.find_by_sql(["SELECT * FROM posts WHERE id NOT IN (:post_ids)", post_ids: post_ids])`
> 
> `posts = Post.find_by_sql(["SELECT * FROM posts WHERE id NOT IN (:post_ids)", {post_ids: post_ids}])`

Oh, I missed it.
It's right to have curly brackets

**Comment by roharon** [comment]
> Should the line below be changed?

I think without curly bracket is okay because it only passed sql argument in this code and `{post_ids: post_ids}` is last positional parameter that acts as hash parameter 

```
    def find_by_sql(sql, binds = [], preparable: nil, &block)
```

**Comment by omegahm** [comment]
It seems to be https://github.com/rails/rails/blob/main/activerecord/lib/active_record/sanitization.rb#L190 that replaces the empty array with a `NULL`. I don't know if there are cases where an empty array needs to be `NULL` or if `0` (a sanitized `false`) will be okay for all cases?

**Comment by nickborromeo** [comment]
>  don't know if there are cases where an empty array needs to be NULL or if 0 (a sanitized false) will be okay for all cases?

like you mentioned, it does look like https://github.com/rails/rails/blob/cece8077d4a6add9857013bd6463cf0797bdf3fa/activerecord/lib/active_record/sanitization.rb#L189-L191 

is where it sanitizes an empty enumerable to `NULL`. Grepping for `quote_bound_value` this seems to be the only place the method is called with `nil` as the argument. So I changed the value to `""` to see what tests will fail. 

There are 3 active record tests that fail with this change

 - `SanitizeTest#test_bind_empty_enumerable`
 -  `SanitizeTest#test_bind_empty_range`
 -  `RelationTest#test_finding_with_sanitized_order`

These tests all assert that the value returned should be `"NULL"`, so it does not really show what possible side effects there will if this change is indeed made.

There might be a specific use case for using `find_by_sql` that is more complex than the example originally given, because the work around would be to use `not` instead of passing in a SQL string. 

As a side note, it would be interesting to find out how SQL parses 

```sql
SELECT * FROM table_one
WHERE id NOT IN (
  SELECT id FROM table_two
)
```

because this does return the full list for table_one when the sub query returns no rows.

**Comment by matthewd** [comment]
There is no other possible value to approximate an empty list -- first, any other value is a real value, and could meaningfully occur (0 is a perfectly valid `id`)... but more importantly, nothing else will pass SQL type checking in all the cases that NULL will.

> `SELECT * FROM posts WHERE 1=1`

We can't do that, because you've supplied an SQL string that contains `id NOT IN (`; there is no string we can append after that which will remove the characters you've put in there.

If you need to manually construct an SQL query like this, and the default best-effort fallback of NULL is not suitable in your query, then you'll need to customize it further to vary the query when your array is empty.
