### ISSUE TITLE
ActiveRecord::Type::Time::Value crashes when loaded from YAML on rails 7.0

### ISSUE THREAD

**Issue by Intrepidd** [rails/rails#43966]
### Steps to reproduce
```
# Rails 6.1
(byebug) YAML.load(YAML.dump(ActiveRecord::Type::Time::Value.new(Time.current))) + 1.day
Thu, 23 Dec 2021 10:24:42.873895000 UTC +00:00

# Rails 7
(byebug) YAML.load(YAML.dump(ActiveRecord::Type::Time::Value.new(Time.current))) + 1.day
*** ArgumentError Exception: not delegated
```
### Expected behavior
Should return an `ActiveRecord::Type::Time::Value` object

### Actual behavior
Raises `ArgumentError Exception: not delegated`

### System configuration
**Rails version**: 7.0

**Ruby version**: 3.0.3 and 2.7.3

# Details

We are trying to make the paper_trail gem [compatible with rails 7](https://github.com/paper-trail-gem/paper_trail/pull/1356) and encountered this issue. It looks like `ActiveRecord::Type::Time::Value` is not properly deserializable from YAML.

In Rails 6.1, it used to be dumped as `ActiveSupport::TimeWithZone` which avoided the issue.

Looks like this line is the one raising the exception : 

https://github.com/rails/rails/blob/a8d088fbdc7744d1806729dc8b4e477677056dce/activerecord/lib/active_record/type/time.rb#L24

**Comment by pedrocarmona** [comment]
I think it has to do with this change:

https://github.com/rails/rails/commit/db9ba1865916985212b02a73e24500555532be2b

**Comment by pedrocarmona** [comment]
@pixeltrix Maybe we should add

```
::YAML.dump_tags[ActiveRecord::Type::Time::Value] = "!ruby/object:ActiveSupport::TimeWithZone"
```

Wdyt?

**Comment by AlfonsoUceda** [comment]
@Intrepidd have you checked what @pedrocarmona suggested in the rail 7 PR?

**Comment by Intrepidd** [comment]
> @Intrepidd have you checked what @pedrocarmona suggested in the rail 7 PR?

Yes but this is way below my pay grade unfortunately, I don't have the context about the changed that were done around `ActiveRecord::Type::Time::Value` and YAML dumping

**Comment by chrisortman** [comment]
I agree with @pedrocarmona but slightly amended. Add to the bottom of activerecord/lib/active_record/type/time.rb

```ruby
::YAML.dump_tags[ActiveRecord::Type::Time::Value] = ::YAML.dump_tags[ActiveSupport::TimeWithZone]
```

It looks like the intent has always been that AR Time::Value delegates yaml serialization to `TimeWithZone`. `TimeWithZone` changed how it implements yaml serialization because of the way Psych works:

https://github.com/ruby/psych/blob/e8d262fa108a1605443d7426c185452b538775be/lib/psych/visitors/yaml_tree.rb#L498

Psych calls `Class.name` before calling `encode_with`. Because `Class.name` triggers the new deprecation warning the coding / serialization behavior was changed to rely on `dump_tags` But dump tags is sensitive to the actual class being serialized so needs to be aware of *any* classes that might rely on `TimeWithZone` to perform serialization (because the old behavior allowed `TimeWithZone` to set the YAML tag 

I did a grep for any other classes that used `DelegateClass(::Time)` and didn't find any, so I think this is the only file that needs to change. 

@pixeltrix can you weigh in here?

**Comment by rafaelfranca** [comment]
Doesn't changing the dump tags mean that the load will get a different type? In this case `ActiveSupport::TimeWithZone` instead of `ActiveRecord::Type::Time::Value`?

**Comment by pedrocarmona** [comment]
Hi @rafaelfranca,

I was following this comment in [paper_trail gem issue](https://github.com/paper-trail-gem/paper_trail/pull/1356#issuecomment-998826254), however I got different results:

`bundle exec appraisal rails-6.0 -- rspec spec/models/widget_spec.rb:317`
(with a `binding.irb` inside paper_trail's `lib/paper_trail/serializers/yaml.rb`)

```
>> object['a_time'][1].class
=> ActiveRecord::Type::Time::Value
>> ::YAML.dump object['a_time'][1]
=> "--- !ruby/object:ActiveRecord::Type::Time::Value\ndelegate_dc_obj: 2000-01-01 00:23:16.902056000 Z\n"
```

and for rails 7 the output of the yaml dump is different
```
>> object['a_time'][1].class
=> ActiveRecord::Type::Time::Value
>> ::YAML.dump object['a_time'][1]
=> "--- !ruby/object:ActiveRecord::Type::Time::Value\nutc: 2000-01-01 00:24:14.919125000 Z\nzone: !ruby/object:ActiveSupport::TimeZone\n  name: Etc/UTC\ntime: 2000-01-01 00:24:14.919125000 Z\n"
>>
```

**Comment by rafaelfranca** [comment]
Are you able to bisect the commit that changed this behavior? I don't see how db9ba1865916985212b02a73e24500555532be2b would change the behavior of YAML dump of an unrelated object.

**Comment by pedrocarmona** [comment]
ah, this is what was in the original comment, for 6.1 is also different than for 6.0 and 7.0:

` bundle exec appraisal rails-6.1 -- rspec spec/models/widget_spec.rb:317`
 
```
>> object['a_time'][1].class
=> ActiveRecord::Type::Time::Value
>> ::YAML.dump object['a_time'][1]
=> "--- !ruby/object:ActiveSupport::TimeWithZone\nutc: 2000-01-01 01:02:16.574301000 Z\nzone: !ruby/object:ActiveSupport::TimeZone\n  name: Etc/UTC\ntime: 2000-01-01 01:02:16.574301000 Z\n"
```

**Comment by pedrocarmona** [comment]
for bisecting the commit,  I was scrolling all merge commits from `6-1-stable` to `7-0-stable`

<img width="1319" alt="Screenshot 2022-01-06 at 01 38 26" src="https://user-images.githubusercontent.com/2815199/148314434-f783d9ca-63f4-4292-8944-b108ad9d91ce.png">


```
appraise "rails-commit-1" do
  gem "rails", github: 'rails/rails', ref: '57cbf4136fa0e7cab69286706bd2a0d967344e6d'
  gem "rails-controller-testing", "~> 1.0.3"
end

appraise "rails-commit-2" do
  gem "rails", github: 'rails/rails', ref: 'db9ba1865916985212b02a73e24500555532be2b'
  gem "rails-controller-testing", "~> 1.0.3"
end
```

for commit-1 (57cbf4136fa0e7cab69286706bd2a0d967344e6d) the paperclip tests pass with deprecation warning:
```
---
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2000-01-01 01:43:13.178032000 Z
  zone: !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2000-01-01 01:43:13.178032000 Z
-
DEPRECATION WARNING: ActiveSupport::TimeWithZone.name has been deprecated and
from Rails 7.1 will use the default Ruby implementation.
 (called from dump at /Users/pedrocarmona/Developer/paper_trail/lib/paper_trail/serializers/yaml.rb:22)
```

for commit-2 (db9ba1865916985212b02a73e24500555532be2b):
```
---
- !ruby/object:ActiveRecord::Type::Time::Value
  utc: 2000-01-01 01:43:18.929286000 Z
  zone: !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2000-01-01 01:43:18.929286000 Z  
```

and the test fails, therefore this is the change that affects the paperclip test suite.
However, given that the output in rails 6-0 is different than 6-1 and 7-0, maybe there is more to it than just the change that makes the test fail.

**Comment by pedrocarmona** [comment]
<img width="1115" alt="Screenshot 2022-01-06 at 01 54 15" src="https://user-images.githubusercontent.com/2815199/148315528-b4dc9e99-e9db-4ee6-aed5-4ead6ad88795.png">


did also for `d0719825aca3509ac97978c3966e716ecdb94aa7` was ok, and in the `3dd0af563b5ebdccf1e3c1993f8a64f4ab5fce48` was introduced

**Comment by chrisortman** [comment]
Hasn’t Time::Value always serialized itself as TimeWithZone though? Even though a straight Yaml#dump isn’t showing it, in practice Time::Value called TimeWithZone#encode_with

**Comment by chrisortman** [comment]
The changes specifically applies to the behavior of `Time::Value` when `ClassToDelegateTo` is `TimeWithZone`

---

I ran a git bisect (shakes fist mimemagic and curses) using this script:

```
require "bundler"
Bundler.setup

require "rails/all"
require "active_support/all"

Time.zone = "America/Chicago"
output = YAML.dump(ActiveRecord::Type::Time::Value.new(Time.current))
puts output
if output.starts_with?("--- !ruby/object:ActiveRecord::Type::Time::Value")
	puts "BAD"
	exit(false)
elsif output.starts_with?("--- !ruby/object:ActiveSupport::TimeWithZone")
	puts "GOOD"
	exit(true)
else
	puts "Indeterminate"
	exit(false)
end
```

It is definitely commit db9ba1865916985212b02a73e24500555532be2b that introduces the breaking change

_Because_ `Time::Value` delegates it's YAML serialization behavior to it's `ClassToDelegateTo` 

When `ClassToDelegateTo` is a `TimeWithZone` that means that `YAML#dump` will eventually send `encode_with` to `Time::Value` which delegates to `ClassToDelegateTo` which is `TimeWithZone`

Before commit db9ba1865916985212b02a73e24500555532be2b `TimeWithZone#encode_with` would explicitly set the `tag` of the `coder` And it would do this no matter the underlying type of the class being serialized.

After commit db9ba1865916985212b02a73e24500555532be2b the tag is set via the built-in behavior of Psych by looking in `dump_tags`

But because `dump_tags` is a simple Hash with the key being the `type` it only gets the correct tag when the type is specifically `TimeWithZone`

In order to maintain compatibility with previous behavior _any_ class that delegates YAML serialization behavior via `encode_with` needs to output the same `tag` as `TimeWithZone`

**Comment by chrisortman** [comment]
> Are you able to bisect the commit that changed this behavior? I don't see how [db9ba18](https://github.com/rails/rails/commit/db9ba1865916985212b02a73e24500555532be2b) would change the behavior of YAML dump of an unrelated object.

Specifically this line because it sets the tag for the coder. https://github.com/rails/rails/commit/db9ba1865916985212b02a73e24500555532be2b#diff-aa0ae5ccf92f812f874b632afe70375c52772636f927fe6e34ffeaebf54af9d1L185

**Comment by rafaelfranca** [comment]
Got it. So even on 6.1 the behavios is wrong. The roadtrip of a `ActiveRecord::Type::Time::Value` instance should always return a `ActiveRecord::Type::Time::Value` instance, not a `ActiveSupport::TimeWithZone`. We are tagging the Time object inside a `Value` for a reason and yaml dumping is losing that information. I think it would be better to define `init_with` and `encode_with` in that `Value` type and make sure we always get the right instance.

**Comment by chrisortman** [comment]
@rafaelfranca I can take a shot at it. I started a pull request with a failing test case that I think captures the problems.

I'm not sure if we should be aiming for "do what it used to do" or if we should try to change the behavior. It seems odd that when `::Time::Value` get's serialized it comes back as `TimeWithZone`

Old Behavior: 

`Time::Value[TimeWithZone]` --YAML#dump--> --YAML#load--> `TimeWithZone`

But given how this has been used (paper_trail) there is likely a lot of legacy data (captured for audit purposes) stored the old way

**Comment by rafaelfranca** [comment]
We could make the code aware of this legacy data and load `TimeWithZone` as a Time::Value as well, so in memory it is always the same.

**Comment by chrisortman** [comment]
I think that will it impossible to serialize / deserialize TimeWithZone by itself? Maybe that is OK it seems like that type is going to be going away post ruby 3 anyway?

**Comment by chrisortman** [comment]
> We could make the code aware of this legacy data and load `TimeWithZone` as a Time::Value as well, so in memory it is always the same.

I added a test to the PR that shows what this would look like.

**Comment by chrisortman** [comment]
@rafaelfranca first pass solution is in the PR , not sure if should keep discussion here or move there.

- Somehow we have to tell Psych to send `init_with` to `Time::Value` .  I think that means either  
  1. a soft dependency from active_support -> active_record because of the mapping setup in `load_tags` (this is currently in PR)
  2. no dependency but different / inconsistent behavior when deserializing `TimeWithZone` depending on what's loaded
- If we're going to up-convert `TimeWithZone` I think I need to do more testing / investigation to make sure I'm giving back a correct time instance in the correct zone.
- Confirm we're really ok with removing the ability to materialize a `TimeWithZone` instance from YAML

I'd like other opinions on potential for breaking compatibility here. It feels like this could really trip people up who might have code treating YAML as YAML and looking for specific keys. 

I'm not sure if we should provide a flag to toggle the behavior and / or change `TimeWithZone` serialization to include some sort of version flag. Presence of flag would mean we expect it to stay `TimeWithZone` absence would mean it was a really a `Time::Value`

Or possibly we need to fix 7.0 for compatibility and do the rest of the changes in 7.1?

**Comment by pixeltrix** [comment]
Ugh, this is a bit of a mess - unintended consequences spread across six years 😢 

So the reason that `ActiveRecord::Type::Time::Value` [was introduced][1] was to handle a [bug in MariaDB][2] where it wouldn't ignore the date part of a timestamp when comparing against a `TIME` column unlike other databases. This is a class that isn't documented and shouldn't be relied upon to exist - therefore we should definitely not dump it out as YAML.

I think the fix to restore previous behaviour should be to add the following:

``` ruby
::YAML.dump_tags[ActiveRecord::Type::Time::Value] = "!ruby/object:ActiveSupport::TimeWithZone"
::YAML.load_tags['!ruby/object:ActiveRecord::Type::Time::Value'] = 'ActiveSupport::TimeWithZone'
```

We can put these in Active Record so that we don't tie Active Support to it. The `load_tags` change will handle any YAML that's been dumped since the change in db9ba18 was made and convert them to AS::TWZ instances which is what would happen with Rails 6.1.

There's a wider issue of what `TIME` columns should be dumped as - YAML does support them, and they get loaded as seconds since midnight, e.g.

``` 
>> YAML.load("lunch: 12:00")
=> {"lunch"=>43200}
```

However that's outside the scope of this issue.

I'm going to have a closer look at the papertrail failure - I'd like to know how these instances are being exposed.

[1]: https://github.com/rails/rails/pull/24542
[2]: https://jira.mariadb.org/browse/MDEV-9541

**Comment by chrisortman** [comment]
> 
> I think the fix to restore previous behaviour should be to add the following:
> 
> ```ruby
> ::YAML.dump_tags[ActiveRecord::Type::Time::Value] = "!ruby/object:ActiveSupport::TimeWithZone"
> ::YAML.load_tags['!ruby/object:ActiveRecord::Type::Time::Value'] = 'ActiveSupport::TimeWithZone'
> ```
> 

I have implemented @pixeltrix  fix in #44095 
It required a little more code because the `AR::Time::Value` still needs to look like TWZ when it is dumped to YAML and Psych [doesn't look at the thing returned from `dump_tags`](https://github.com/ruby/psych/blob/e8d262fa108a1605443d7426c185452b538775be/lib/psych/visitors/yaml_tree.rb#L498) to see if it has an `encode_with` it instead sends that message to the instance being dumped.

Pending some review cleanup is this the direction we want to go?

**Comment by pixeltrix** [comment]
@chrisortman since `ActiveRecord::Type::Time::Value` is unique in being a delegate I'm tending to favour this change - this will make the YAML dump consistent with other internal type classes for values. The question is whether it's possible to make this change in a patch release - I think it's safe since the class is only used to provide a hint to Active Record's quoting code though I need to check non-included database adaptors like Oracle and SQLServer.

Is it possible for you to test this against PaperTrail?

``` diff
diff --git a/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb b/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb
index 928a72181c..195b1c36c1 100644
--- a/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb
+++ b/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb
@@ -19,7 +19,7 @@ def quote(value)
         when BigDecimal then value.to_s("F")
         when Numeric, ActiveSupport::Duration then value.to_s
         when Type::Binary::Data then quoted_binary(value)
-        when Type::Time::Value then "'#{quoted_time(value)}'"
+        when Type::Time::Value then "'#{quoted_time(value.time)}'"
         when Date, Time then "'#{quoted_date(value)}'"
         when Class      then "'#{value}'"
         else raise TypeError, "can't quote #{value.class.name}"
@@ -38,7 +38,7 @@ def type_cast(value)
         # BigDecimals need to be put in a non-normalized form and quoted.
         when BigDecimal then value.to_s("F")
         when nil, Numeric, String then value
-        when Type::Time::Value then quoted_time(value)
+        when Type::Time::Value then quoted_time(value.time)
         when Date, Time then quoted_date(value)
         else raise TypeError, "can't cast #{value.class.name}"
         end
diff --git a/activerecord/lib/active_record/type/time.rb b/activerecord/lib/active_record/type/time.rb
index 4e4f2acc63..864e93210e 100644
--- a/activerecord/lib/active_record/type/time.rb
+++ b/activerecord/lib/active_record/type/time.rb
@@ -5,7 +5,12 @@ module Type
     class Time < ActiveModel::Type::Time
       include Internal::Timezone
 
-      class Value < DelegateClass(::Time) # :nodoc:
+      class Value # :nodoc:
+        attr_reader :time
+
+        def initialize(time)
+          @time = time
+        end
       end
 
       def serialize(value)
@@ -21,7 +26,7 @@ def serialize(value)
         def cast_value(value)
           case value = super
           when Value
-            value.__getobj__
+            value.time
           else
             value
           end
```

**Comment by pixeltrix** [comment]
Having had a look at the [Oracle adapator][1] I can see they [might suffer a similar issue][2] since they follow a similar pattern for timestamp_tz type but since Oracle doesn't support the `TIME` data type I don't think we need to worry about it.

Looking at the [SQL Server adaptor][3] I can see they've implemented a custom type for their `TIME` columns which [doesn't use `DelegateClass`][4] so we're probably fine there too. One thing to note from their implementation is that we probably need to implement `unserialize` like this:

``` ruby
def deserialize(value)
  value.is_a?(Value) ? super(value.time) : super
end
```

Feeling more confident that this is the right approach now.

[1]: https://github.com/rsim/oracle-enhanced
[2]: https://github.com/rsim/oracle-enhanced/blob/4ac11553d1e31297b1f7ad421883c9e398e5e9ff/lib/active_record/type/oracle_enhanced/timestamptz.rb
[3]: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter
[4]: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/5decfd28a6b4dbbd9777dc6e6477eec44fa9a0a3/lib/active_record/connection_adapters/sqlserver/type/time.rb

**Comment by chrisortman** [comment]
@pixeltrix I applied this directly to 7-0-stable
paper_trail tests pass

I'm not sure what this means for backwards compatibility though. 
It looks like AR::Time::Value  will now serialize like a normal PORO and time will either use the built-in Psych scalar or TWZ encode_with.

When `@time` is `::Time`
```
--- !ruby/object:ActiveRecord::Type::Time::Value
time: 2000-01-01 10:30:00.000000000 -06:00
```

When `@time` is `TimeWithZone`

```
--- !ruby/object:ActiveRecord::Type::Time::Value
time: !ruby/object:ActiveSupport::TimeWithZone
  utc: 2000-01-01 16:30:00.000000000 Z
  zone: !ruby/object:ActiveSupport::TimeZone
    name: America/Chicago
  time: 2000-01-01 10:30:00.000000000 Z
```

Maybe this won't matter as TWZ phases out? Do we still need to account for things that have been generated since 7.0 release?

It is also a change (maybe better though?) that you used to get a TWZ directly back from a `::YAML#load` but now you will get back an `AR::Time::Value`
if someone's got some overly specific `is_a?` kind of logic they might get broken?

**Comment by pixeltrix** [comment]
> Do we still need to account for things that have been generated since 7.0 release?

Hopefully the `deserialize` method I suggested would handle that - the `Value` objects are unwound and passed to the super method so all non-`Value` objects should behave as before.

> It is also a change (maybe better though?) that you used to get a TWZ directly back from a ::YAML#load but now you will get back an AR::Time::Value
if someone's got some overly specific is_a? kind of logic they might get broken?

You only get an `ActiveRecord::Type::Time::Value` when calling `serialize` in preparation for using in a database query so apps are very unlikely to be affected, therefore the main source of issues is likely to be gems like papertrail that hook into that layer somehow. I can look into some other gems to see if there might be any issues - any suggestions like alternative connection adaptors? After MySQL, PostgreSQL, SQLite, Oracle and SQL Server are there any other adaptors worth looking at?
