### ISSUE TITLE
Suggestion to add a note about SQL injection in the rails security guide

### ISSUE THREAD

**Issue by wonda-tea-coffee** [rails/rails#43987]
How about adding a note to the rails security guide about sanitizing the SQL LIKE clause?
This is because, in my opinion, I often see code like the following.

```ruby
User.where('name LIKE ?', params[:name])
```

Specifically, I think it would be a good idea to include a code example using sanitize_sql_like.

**Comment by KSH-code** [comment]
https://api.rubyonrails.org/classes/ActiveRecord/Sanitization/ClassMethods.html#method-i-sanitize_sql_like
it already exists.

**Comment by KSH-code** [comment]
I think that'd be sanitized is good by default. it could be sql injected.

**Comment by Ankk98** [comment]
I tried something like
`User.where('email LIKE ?', "'").to_a` 
and the query escaped my quote
```
ActiveRecord -- User Load -- {:sql=>"SELECT `users`.* FROM `users` WHERE (email LIKE '\\'')", :cached=>nil}
```
I can see that it is escaping the quote. Can you provide an example where this can be exploited?

**Comment by wonda-tea-coffee** [comment]
@Ankk98 

The wildcards % and _ in the like clause are not sanitized.

```ruby
pry(main)> User.where("name like ?", "%foo").select(:id).to_a
SELECT `users`.`id` FROM `users` WHERE (name like '%foo')
=> []
```

**Comment by Ankk98** [comment]
Oh, got it.
So, in case this foo was coming from user input, he will be able to add % himself and make the query return unwanted results.
Thank you for the example, now I see how this can be misused.

I wonder why we don't already have a wrapper of `LIKE %%` type of queries.
It is a very common use case.
We can use sanitize_sql_like to sanitize it as suggested here also.
https://stackoverflow.com/a/26094593

But I don't think that we should expect all developer to know this.
People are bound to make mistakes.
Having a wrapper will eliminate all chances of human errors.

I would like to contribute in case we want to implement a wrapper for this type of query.

**Comment by tmyksj** [comment]
Is this working in progress?

It seems easy to overlook the need to sanitize sql like clause because of [this querying guide](https://github.com/rails/rails/blob/v7.0.2.3/guides/source/active_record_querying.md#array-conditions). So, I think, we should add a note about the sql injection to the security guide as soon as possible, and also update the querying guide.

**Comment by wonda-tea-coffee** [comment]
There is no progress.
Unfortunately, I do not plan to work on it as I have not received a positive response from the maintainer.

**Comment by tmyksj** [comment]
Thanks.

I don't have a response from the maintainers too. But we can open a pull request without the response, right? If so, would you like me to make the pull request like following?

**[the security guide](https://github.com/rails/rails/blob/v7.0.2.3/guides/source/security.md#sql-injection)**:
In this, I'll add some sentences about the SQL LIKE sanitization after "Note the previous mentioned countermeasures ..." paragraph.

~~~markdown
Also if you want to use SQL LIKE like below, it may not be enough because SQL LIKE characters (i.e., `%` and `_`) are not sanitized.
```ruby
Model.where("name LIKE ?", params[:name])
```

In this case, we can use `sanitize_sql_like`.
```ruby
Model.where("name LIKE ?", Model.sanitize_sql_like(params[:name]))
```
~~~

**[the querying guide](https://github.com/rails/rails/blob/v7.0.2.3/guides/source/active_record_querying.md#array-conditions)**
In this, I'll only update TIP because the description is for array conditions. I think the SQL LIKE sanitization is out of scope. Or does more description needed in this guide?
```markdown
TIP: The example does not sanitize SQL LIKE characters i.e., `%` and `_`. This behavior may not be you expected. For more information on the dangers of SQL injection, see the [Ruby on Rails Security Guide](security.html#sql-injection).
```

**Comment by wonda-tea-coffee** [comment]
I would appreciate it if you could work on it.
I think the above sounds good.

**Comment by wonda-tea-coffee** [comment]
@tmyksj 
Thank you for your response!
I appreciate it very much!
I'll close it now that it's resolved 👌
