### ISSUE TITLE
config.active_record.migration_error = false not working to disable pending migration check

### ISSUE THREAD

**Issue by princejoseph** [rails/rails#43985]
### Steps to reproduce
- have a database with migrations not ran
- have `config.active_record.migration_error = false` in development.rb file
- Start rails server
- take the home page
- See ActiveRecord::PendingMigrationError being raised

### Expected behavior
ActiveRecord::PendingMigrationError should not be raised so that we can play around with a read only database from local if we want

### Actual behavior
ActiveRecord::PendingMigrationError is raised and `config.active_record.migration_error` config is not honored

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 2.7.2p137

**Comment by andrehjr** [comment]
I was not able to reproduce this on 7.0 (main) and 6.1. Can you reproduce this on a new Rails project?

**Comment by will-gant** [comment]
Just a note to any users of `rspec-rails` hitting this in the _test_ environment — this issue clearly concerned the development environment, but since I stumbled upon it I figure others may do the same — that you may have the following in `rails_helper.rb`:

```ruby
ActiveRecord::Migration.maintain_test_schema!
```

This seems to be part of the default [template](https://github.com/rspec/rspec-rails/blob/c112d70acd0e1a3e5ef1f5ddd391dc75179e763f/lib/generators/rspec/install/templates/spec/rails_helper.rb#L30-L40) for that file, and gives you output like the following even when you've set `config.active_record.migration_error = false` in `config/environments/test.rb`.

```ruby
Failure/Error: ActiveRecord::Migration.maintain_test_schema!

ActiveRecord::PendingMigrationError:


  Migrations are pending. To resolve this issue, run:

          bin/rails db:migrate

  You have 3 pending migrations:
```
