### ISSUE TITLE
SchemaCache.data_source_exists? - unnecessary schema queries

### ISSUE THREAD

**Issue by EQuincerot** [rails/rails#44024]
### Steps to reproduce
When running an application we face to frequent schema queries, even when using schema cache.

Indeed, when tables/views have been listed once, I don't understand why we should check in the db again when the table is not in the cache.

Here is a gist to reproduce the issue: https://gist.github.com/EQuincerot/75bb931441751560b21bc505d1d9403e

I would suggest this implementation for `ActiveRecord::ConnectionAdapters::SchemaCache#data_source_exists?` but I may miss some impact:
```ruby
      def data_source_exists?(name)
        return if ignored_table?(name)
        prepare_data_sources if @data_sources.empty?
        @data_sources[name]
      end
```

### Expected behavior
Once the tables/views have been listed once, no need to query the database again for checking that a table exists.

### Actual behavior
In the gist provided, if you remove the expect-never on SQLite3Adapter, you will cause a query like:
```
SELECT name FROM sqlite_master WHERE name <> 'sqlite_sequence'
```

**Comment by eileencodes** [comment]
Hey @EQuincerot I've been looking at this issue and I'm not sure it's a bug - at least not a bug with the schema cache.

Looking at your example, the caller seems incorrect to me. The data source passed that keeps querying the database is `tag`, but should be `tags` since that's the actual data source name. Try changing the assertion to the following (note `where(tag...)` is now `where(tags...)`) you'll see there's no extra query.

```ruby
assert_equal book.id, Book.left_outer_joins(book_tag: :tag).where(tags: { id: tag.id }).pick(:id)
```

I don't think we can really tell the schema cache to skip the table if it's not found the first time because an application could run migrations out of band (like with pt-osc or gh-ost or lhm) which doesn't require rebooting the application. In that case we would want the cache to pick up the new data source.

If this is a bug it's in the fact Rails doesn't convert the `tag` to `tags` to get the correct data source from the connection. However I'm not sure there's an easy way to fix this offhand or how big of an issue this actually is.

I'm not sure if your example is written like this on purpose but I found it odd that `Tag` is missing it's association set up for the other side of the has many through. In addition `book_tag` should be `book_tags` as has many is plural. But fixing that doesn't change the behavior seen in the test case. Currently it's difficult to tell if the callers are incorrect or if Rails is incorrect. Do you have a more straightforward example of this happening?
