### ISSUE TITLE
Migration names should use autoloader inflections

### ISSUE THREAD

**Issue by jaredbeck** [rails/rails#44075]
#### Step 1

```ruby
rbenv local 3.0.3
rails -v # 7.0.0
rails new migration_inflection_issue
cd migration_inflection_issue
bin/rails g migration create_ssns
```

Open the migration and name the class `CreateSSNs`.

#### Step 2

Create `config/initializers/autoloading.rb`:

```ruby
Rails.autoloaders.each do |loader|
    loader.inflector.inflect(
      "create_ssns" => "CreateSSNs",
    )
end
```

#### Step 3

```bash
bin/rails db:migrate
```

### Expected behavior

The migration should succeed.

### Actual behavior

The migration fails with:

```plain
NameError: uninitialized constant CreateSsns
Did you mean?  CreateSSNs
```

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

### Analysis

`ActiveSupport::Inflector.camelize` is used. Maybe we could use `Rails.autoloaders.main.inflector.camelize` instead?

**Comment by rafaelfranca** [comment]
Generators use the Active Support Inflector. You need to configure it as well.

**Comment by jaredbeck** [comment]
Hi Rafael, thanks for the quick reply.

> Generators use the Active Support Inflector. 

I _did_ already state this fact in my analysis. I'm proposing that autoloader inflections should _also_ be used.

Is there a technical reason not to make this improvement?

**Comment by rafaelfranca** [comment]
Yes. It will change behavior for all existing applications.

**Comment by rafaelfranca** [comment]
@fxn do you remember why `Rails::Autoloaders::Inflector` exists and we don't use `ActiveSupport::Inflector` directly as the Zeitwerk autoloader? It given people the false idea that changing it will change all the behavior of Rails that uses inflector which is not the reality today. Since that class delegates to `ActiveSupport::Inflector` but allows overrides, those overrides are not picked by the rest of the framework unless we change everything to use the autoloaders which it seems unnecessary coupling between generators and autoloader for example.

**Comment by jaredbeck** [comment]
> It will change behavior for all existing applications.

Makes sense, thanks for the explanation.

>  It gives people the false idea that changing it will change all the behavior of Rails ...

I definitely suffered from this false idea. To give another example, I also learned today that routes ignore autoloader-inflections.

**Comment by fxn** [comment]
Hey! Several things:

The autoloaders inflectors are the autoloader inflectors, used by the autoloaders (there are two). **Migrations are not autoloaded**, the file name does not even inflect to a valid constant name. You do not use a constant to have a file loaded, see what I mean?

We could cover this use case explicitly in the documentation of migrations and/or autoloading, but I don't think we should delegate to the autoloaders inflectors (again, plural,  remember there are *two* autoloaders with independent inflectors that could be configured differently). 

@rafaelfranca regarding your remark. The [documentation](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#customizing-inflections) gives priority to AS inflections, that's you option A and that's what we stress there and in the [HOWTO guide](https://guides.rubyonrails.org/classic_to_zeitwerk_howto.html#acronyms) as well.

`Rails::Autoloaders::Inflector` exists because experience says you may want more fine-grained control occasionally, because touching AS inflections has a global effect. When is a global effect bad? For example, if it breaks how a 3rd-party engine inflects a certain filename. If you don't have an alternative, you have a problem. (This was already the case in Rails 5, being able to fine-tune autoloading inflections is an improvement.)

Another use case: When migrating from `classic` to `zeitwerk`, what if the project has `JSON` in some class/module names and `Json` in others? (I have seen this). Should you block the migration until you write a monster patch that renames them all? No, with this fine-control you can cherry-pick inflections, ship the migration. With Zeitwerk in place, then you can rename case by case in controlled patches, if you want uniformity.

There's also a technical difference, which is that `camelize` in the inflectors of autoloaders receive [two arguments](https://github.com/fxn/zeitwerk#custom-inflector), while AS `camelize` expects only one. That is OK, because AS `camelize` is a generic inflector of Strings, whereas Zeitwerk inflectors are specifically written to inflect files in autoload paths. So signatures are naturally different.

However, that last point is technical, the reason of the existence of `Rails::Autoloaders::Inflector` is the fine control.

Makes sense?

**Comment by rafaelfranca** [comment]
It makes sense to me, but the problem of people wanting some kind of inflector that affects code generator and autoload behavior still exists and I think we solve it, and most of the time you want to change both at the same time, without affecting the text camelization for application users, which is the problem being described in this issue.

Migrations are not autoloaded, but models are, and `bin/rails g mode create_ssns` would create `CreateSsns` and in order to generate the right name and load the right class one would have to change the text camelization inflector, when they only want to change the code generators/autoloader inflector.

So it seems we are missing something like `Rails.application.code_inflectors` which would be the one we use for generators and autoload leaving the global `ActiveSupport::Inflector` instance only for text.

**Comment by fxn** [comment]
Agree, we should have a list of code inflections performed by Rails like those, migrations, routes, etc. and provide a better interface for them than the global AS inflections.

Regarding control and engines, an ideal future for me would be that each engine has its own autoloaders. Today I moved the autoloders to be per application. In a far future, they could be per engine. That way, you could publish an engine and know you have full control about the inflections in your engine. Also, about whether you want to reload when the parent application reloads or not (I believe there's a good deal of engines that do not need reloading, it's wasted cycles).

The groundwork for individual loaders is in place, but backwards compatibility will make this difficult. No concrete plan for this, just sharing a vision I have for it.

**Comment by rafaelfranca** [comment]
Great! We are aligned non this. Just need someone to do the work now.

A start would be to have a per-application code inflector available so we could change all places to use that instead of the global inflector.

@jaredbeck if you are interested this should not be too far from what you proposed in the issue body, do you want to give it a try?

**Comment by jaredbeck** [comment]
> @jaredbeck if you are interested this should not be too far from what you proposed in the issue body, do you want to give it a try?

I'd be honored. Let me see if I understand the proposal:

- Continue to use AS:Inflector for text, e.g. in `String#camelize`
- Add a configuration option `Rails.application.code_inflector` (singular?)
  - Type: nil or a Zeitwerk::Inflector
  - Default: nil
  - If nil, the AS:Inflector will be used, as in 7.0
  - To be used in places like 
    - `ActiveRecord::MigrationContext#migrations`
    - `ActionDispatch::Request#controller_class_for`
    - where else?

**Comment by rafaelfranca** [comment]
* "Type: nil or a ActiveSupport::Inflectior::Inflections" since I believe that class is more powerful

> where else?

All generators that use inflection today. `rails g model`, `rails g controller`
I think i18n lookup is also affected by an inflector

**Comment by fxn** [comment]
More than nils, I believe they should be always set, but delegate to AS if the inflection is not overridden. Like the autoloading inflectors do ([here](https://github.com/rails/rails/blob/6417428b71197ef7f24fbcd9fdbacc934346b50e/railties/lib/rails/autoloaders/inflector.rb#L13)).

Note that the `camelize` of autoloading inflectors has two arguments. In this new idea, I suppose that the fallback

```ruby
basename.camelize
```

would call to your new code inflector. That one would be the one falling back to `basename.camelize` now.

**Comment by fxn** [comment]
Oh, also note that the autoloading inflectors do not implement `underscore`, `tableize`, etc., those ones only go from filename in snake case to class name, and that is `camelize`. That should stay the same, which squares with the comment above, I imagine the same `Rails::Autoloaders` class that invokes the code inflectors instead of doing `basename.camelize`.

**Comment by fxn** [comment]
Another note: Rails components do not assume they run in a Rails application.

**Comment by jaredbeck** [comment]
Just brainstorming here: two other reasons not to use `ActiveSupport::Inflector::Inflections`

1. It can't `camelize("create_ssns")` into `"CreateSSNs"` (see gist below). To have this level of control, we need something like `Zeitwerk::Inflector#overrides`.
2. It's (sort of) a singleton. It is intended to have exactly one instance per locale. It can still be instantiated (see gist below) but it could be misleading to have an instance in memory other than the intended `@__instance__`.
 
https://gist.github.com/jaredbeck/8e65388a1389c989b5594195a7dfe66a

> Another note: Rails components do not assume they run in a Rails application.

Good point. So, instead of a config option under `Rails.application`, the new config should be under ActiveSupport?

**Comment by fxn** [comment]
> Good point. So, instead of a config option under Rails.application, the new config should be under ActiveSupport?

Exactly, like today. These components depend on AS and use its global inflector.

I can think of two approaches:

1. There's a new global thing in AS used by all Rails components.
2. Each Rails component has a code inflector. It has a default, and railtie/engine initializers override it. Or somesuch.

I don't think there's a use case for being able to inflect differently per Rails component, and (1) is simpler. I think I personally would go with (1) first.
