### ISSUE TITLE
rails 7.0.1 does not deliver updated assets in a dev environment if they've been previously precompiled.

### ISSUE THREAD

**Issue by thebravoman** [rails/rails#44164]
### Steps to reproduce

```
#!/bin/bash
npm --version

# Create
rails _7.0.1_ new bProject --css bootstrap

# enter
cd bProject

# controller
echo 'class HomeController < ApplicationController

  def index
  end
end' > app/controllers/home_controller.rb

# views folder
mkdir app/views/home

# view
echo '
<h1>Title</h1>
<div data-controller="toast">
  <button type="button" class="btn btn-primary" data-action="click->toast#show">Show live toast</button>
</div>
' > app/views/home/index.html.erb

# routes
echo '
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 root "home#index"
end' > config/routes.rb

# precompile
rails assets:precompile

# new controller
bin/rails generate stimulus toastController

# run dev
./bin/dev

```
Go to localhost:3000, open Dev Console->Sources.
There is no toast_controller
![Screenshot from 2022-01-13 10-11-43](https://user-images.githubusercontent.com/1311493/149293526-59594331-3d9b-44ee-9940-c5d5923aca53.png)

### Expected behavior
Although we've previously precompiled the assets minutes or even hours ago (it might have been yesterday), today we are starting the ./bin/dev servers and I would expect to be able to develop and to see the newly created controllers in the browser. 

### Actual behavior
Non of the changes that we are doing are reflected in the resulting html and js delivered to the browser. 
We have to run rails assets:clobber and only then changes are reflected.

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 2.7.4

**npm version**: 8.3.0

**OS**: Ubuntu 20.04.3 LTS

**Comment by brenogazzola** [comment]
That is the expected behavior, not an error. When you precompile assets you create a manifest file for sprockets/propshaft in the `public/assets` folder. From that point on both gems will only serve the files/versions that are mapped in that manifest. 

If you want to go back to "live" files you must first run `rails assets:clobber`.

**Comment by thebravoman** [comment]
Thanks @brenogazzola. It's was different and was strange. 
Three of our platforms are webpack/webpacker based and generally as you start ./bin/webpack-dev-server you don't do rails assets:clobber

It might be a reasonable expectations for many developers that once you start ./bin/dev you expect to get the dev files and not the public/assets files? Probably ./bin/dev could clobber the the assets for us.

Let me know your thoughts.

**Comment by brenogazzola** [comment]
That is a reasonable expectation. In fact I’ve changed my bin/dev to remove the manifest file (without clobbering the assets) when starting so that we can more quickly switch between the two. 

If you feel strongly enough about this, opening an issue in either cssbundling-rails or jsbundling-rails gems (which are responsible for said file) would probablu make this more visible for people who made the switch to weight in.

**Comment by brenogazzola** [comment]
Sorry, I should have been more specific. When I say “this is the expected bahevior” I meant for Sprockets and Propshaft. They are the ones responsible for noticing that files have changed and serving the new ones. 

The reason it’s the expected behavior is a matter of performance. To do live updates you need a file watcher running and something to check it and reload assets before every request. This makes the app much slower. Therefore the behavior we adopted (I was the one who implemented this in Propshaft, but the PR was reviewed by core members), was that instead of checking for production to disable the watcher, we’d check for the presence of manifest file. 

However, this does not mean that the bin/dev file itself cannot be modified to remove the manifest. In this case, since I’m not a contributor in cssbundling and jsbundling, I cannot say what is the expected behavior and ot would be best to ask there.

**Comment by thebravoman** [comment]
@brenogazzola that was also my understanding. That the code is written this way and this is why it is behaving in this way. 

The current issue is that probably, the code should not behave in this way.

**Comment by brenogazzola** [comment]
I’d say it differently: Propshaft and Sprockets are behaving exactly as they should. It’s cssbundling and jsbundling that are not. 

We want to be able to check what our assets are going to look like in production even thought we are on our computer, and the presence of the manifest file does exactly that. Changing propshaft/sprockets to always live load would prevent that. 

On the other hand I fully agree that if you run bin/dev you expect stuff to update. Which is why I changed my bin/dev to remove the manifest before running foreman. 

You can solve your immediate problem by making the same change and then open an issue or PR in the two bundling gems to propose this improvement so others can benefit from it.

**Comment by brenogazzola** [comment]
Just to make it clear: I fully agree that this is not the expected behavior, unlike my original message suggested. I should not have mentioned the manifest as it was not relevant to the discussion. Sorry.

**Comment by thebravoman** [comment]
Thanks @brenogazzola. I will be happy to explore in a PR. I hope to gather input in this issue whether I am missing something, or there might be an idea or discussion (that I've missed) for this to be addressed in a different way.
