### ISSUE TITLE
ActiveStorage controllers leak ActiveRecord database connections

### ISSUE THREAD

**Issue by bubba** [rails/rails#44242]
We've been noticing a lot of connection pool timeout errors in our application as of recent, all being thrown from the active storage controllers. I.e., the notorious `could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use`.

After a bit of debugging we've noticed that every time the timeout occurs, the connection pool is bunged up with dead threads spawned by ActionController::Live:

```
{:size=>5, :connections=>5, :busy=>0, :dead=>5, :idle=>0, :waiting=>0, :checkout_timeout=>5.0}
#<Thread:0x00007f5d80ad97d0 /var/www/minm/shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/live.rb:340 dead>
#<Thread:0x00007f5d8811c208 /var/www/minm/shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/live.rb:340 dead>
#<Thread:0x0000558b8891b838 /var/www/minm/shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/live.rb:340 dead>
#<Thread:0x00007f5d80b488d8 /var/www/minm/shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/live.rb:340 dead>
#<Thread:0x00007f5d80811520 /var/www/minm/shared/bundle/ruby/3.0.0/gems/actionpack-7.0.0/lib/action_controller/metal/live.rb:340 dead>
```

Our connection pool is set to five and our puma workers are capped at five as well, and we aren't using any multithreaded code in our app or gems: Except for ActiveStorage, which spins up a thread to stream blobs back.

Should ActiveStorage/ActionController be checking in these threads before its thread dies?

### Steps to reproduce

Here's an test file script that logs the connection pool every time a blob is requested. You can see it fill up over time with dead threads:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.0.0"
  gem "sqlite3"
end

require "rack/test"
require "active_record/railtie"
require "action_controller/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  # config.active_record.legacy_connection_handling = false
  secrets.secret_key_base = "secret_key_base"

  # config.logger = Logger.new($stdout)
  # Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end


db_path = Rails.root.join('test.sqlite3')
File.delete(db_path) if File.exists? db_path
ENV["DATABASE_URL"] = "sqlite3:#{db_path}"

Rails.application.initialize!

Rails.application.routes.disable_clear_and_finalize = true  #add this line
Rails.application.routes.draw do
  get "/log_connections/:signed_id/*filename" => 'log_connections#show'
end

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :profile
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

class LogConnectionsController < ActiveStorage::Blobs::RedirectController
  skip_before_action :verify_authenticity_token
  include Rails.application.routes.url_helpers
  def show
    s = ""
    ActiveRecord::Base.connection_pool.connections.each { |c|
      if c.owner.nil?
        s += "---\n"
      else
        s += "#{c.owner.inspect}\n"
      end
    }
    s += "Current thread: #{Thread.current.inspect}\n"
    puts s
    super
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods
  def test_upload_and_download
    user = User.create!(
      profile: {
        content_type: "text/plain",
        filename: "dummy.txt",
        io: ::StringIO.new("dummy"),
      }
    )

    10.times do
      get "/log_connections/#{user.profile.signed_id}/#{user.profile.filename}"
    end
  end

  private
  def app
    Rails.application
  end
end

```

### Actual behavior
```
---
---
---
---
#<Thread:0x00007fac8de0a3a8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 run>
Current thread: #<Thread:0x00007fac8de0a3a8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 run>
---
---
---
#<Thread:0x00007fac8de714b8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 run>
#<Thread:0x00007fac8de0a3a8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 dead>
Current thread: #<Thread:0x00007fac8de714b8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 run>
---
---
#<Thread:0x00007fac8de41678 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 run>
#<Thread:0x00007fac8de714b8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 dead>
#<Thread:0x00007fac8de0a3a8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 dead>
Current thread: #<Thread:0x00007fac8de41678 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 run>
---
#<Thread:0x00007fac8deaaf38 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 run>
#<Thread:0x00007fac8de41678 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 dead>
#<Thread:0x00007fac8de714b8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 dead>
#<Thread:0x00007fac8de0a3a8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 dead>
Current thread: #<Thread:0x00007fac8deaaf38 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 run>
#<Thread:0x00007fac8df115a8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 run>
#<Thread:0x00007fac8deaaf38 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 dead>
#<Thread:0x00007fac8de41678 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 dead>
#<Thread:0x00007fac8de714b8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 dead>
#<Thread:0x00007fac8de0a3a8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 dead>
Current thread: #<Thread:0x00007fac8df115a8 /usr/local/lib/ruby/gems/3.0.0/gems/actionpack-7.0.1/lib/action_controller/metal/live.rb:340 run>
```

### Expected behavior
I would expect the threads to check back in their connection to the thread pool.
I presume this is happening because active storage is accessing some information on the blob records, which creates an implicit checkout.

### System configuration
**Rails version**:
7.0.0
**Ruby version**:
3.0.3

**Comment by bubba** [comment]
In particular what confuses me about this is that this is happening in the redirect controllers for blobs and representations. They don't actually need to stream any data from my understanding, and it seems to be a by-product of that activestorage::base controller includes the streaming concern

**Comment by byroot** [comment]
I merged #44244 which should limit the impact a bit, but this `ActionController::Live` thread leak seems concerning, I'll try to find some time to repro and investigate it.

**Comment by casperisfine** [comment]
Ok, so I had a quick look, I'm pretty sure the `ConnectionPool::Reaper` will get these threads back into the pool eventually. Problem is the default reap frequency is 60 seconds, which is huge.

I think `AC::Live` should try to check the connection back in eagerly. It's a bit tricky because Action Controller isn't supposed to know much about Active Record and connections, but we can probably figure something out.

**Comment by casperisfine** [comment]
That being said `ConnectionPool#checkout` does end up calling `reap` if there's no connection available: https://github.com/rails/rails/blob/bd41655d17ff85c3118a4c69d19bad47b6a2890f/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L633-L646

So ultimately this *should* work. I wonder if you problem isn't that since the newly spawned thread take a while to complete, you end up with much more active threads than you expect.

I mean, since the original puma thread returns and is ready to pick up a new request, a single puma thread could end up spawning threads faster than they complete, so theoretically I don't think there's any limit to how many thread can be alive concurrently.

Unless I'm missing something that's a big problem. It might make sense to use a thread pool with a max size for AC::Live so that you can at least right size your connection pool. e..g 5 puma thread and 10 AC::Live threads = 15 connections.

**Comment by casperisfine** [comment]
Quick correction on the above after a quick chat with Matthew. The main thread always block on the "live" thread, so you can only have at most as many "live" threads than "puma" threads. 

> Our connection pool is set to five and our puma workers are capped at five as well

If we're right this means in the current state of things, you'd need to set the connection pool to twice the puma workers count.

I'll see if I can figure something so it wouldn't be necessary. If anything it's the main thread that should check the connection back in so that the live thread can use it. But I'm likely missing something.

**Comment by casperisfine** [comment]
I think a good solution to this would be to use a Fiber instead of a Thread. It would drastically simplify `AC::Live` and solve a lot of other wonky pitfalls. 

It's quite a lot of work though, so might take a while before I come up with a fix (if any).

**Comment by Skulli** [comment]
Not sure if its 100% related, but i noticed the mentioned exception as well. I have a small app, which shows avatars for list of people at once (maybe 40 people) and i get quite a bit of *could not obtain...* errors there. Setup is puma with 5 threads, sidekiq 5 threads, connection pool 10 on postgres.
Found a similar description here:

https://discuss.rubyonrails.org/t/activerecord-connectiontimeouterror-as-soon-as-upgrading-from-rails-6-1-to-rails-7-what-changed-in-activerecord-or-activestorage/80276

**Comment by tisba** [comment]
Am I missing something or did https://github.com/rails/rails/commit/5d08b95874594188d1f4e44581b5bea8e5a228ad by @gmcgibbon not make it into 7.0.2.3? It's definitely not in the changelog https://github.com/rails/rails/blob/v7.0.2.3/activestorage/CHANGELOG.md.

Is there something we can track to see when this gets released? (sorry if this is a stupid question - I don't quite understand the release processes 🙈).

**Comment by SkipKayhil** [comment]
> Is there something we can track to see when this gets released? (sorry if this is a stupid question - I don't quite understand the release processes 🙈).

Not a stupid question! Your idea to check the changelog is definitely the best way to see if that change has been released. 

Regarding releases since the change was merged to `7-0-stable`, I don't think there hasn't been a release of `7-0-stable` branch since `7.0.2` on Feb 8th. `7.0.2.1`, `7.0.2.2`, `7.0.2.3` were all security releases (which as far as I know means the security fix was added onto the previously released commit and no other changes were released). I would expect it to see it for sure in `7.0.3`

**Comment by tisba** [comment]
That's what I suspected as well, thx @SkipKayhil 🙇 Let's hope `7.0.3` is not too far out.

**Comment by casperisfine** [comment]
@tisba if that patch is important to you, you can point your Gemfile to the `7-0-stable` branch until `7.0.3` is out.

**Comment by jprosevear** [comment]
The streaming behaviour also impacts direct_uploads_controller.rb since it also inherits from ActiveStorage::BaseController

**Comment by tisba** [comment]
Since 7.0.3 has been released, I think this issue here can finally be closed.

**Comment by bubba** [comment]
5d08b95874594188d1f4e44581b5bea8e5a228ad only fixes the redirect controller cases. From my understanding threads spawned by ActionController::Live still leak in the general case, and the recommended fix was to move from threads to fibres. Perhaps a new issue should be created for this?

**Comment by jdelStrother** [comment]
Is it possible to manually check connections back in at the end of a Live action? We have a non-ActiveStorage controller that uses ActionController::Live and have hundreds of dead connections left lying around.

**Comment by vvitto** [comment]
Not sure if it's related, but I'm facing the same problem with a leaking of connections with such code.

```
  include ActionController::Live
  def index
    headers.delete('Content-Length')
    headers['Cache-Control'] = 'no-cache'
    headers['Content-Type'] = "text/event-stream"
    headers['X-Accel-Buffering'] = 'no'
    headers['Last-Modified'] = Time.now.httpdate.to_s
    response.status = 200

    ApplicationRecord.transaction(isolation: :repeatable_read) do
        sub_customer.external_contacts.find_each(batch_size: 500) do |row|
            response.stream.write to_json(row)
            response.stream.write "\n"
        end
    end
  ensure
        response.stream.close
  end
  ```
  I don't use ActiveStorage here. The database is configured for 3 pools and the 4th request to the controller application crashes with `could not obtain a connection from the pool within 5.000 seconds (waited 5.002 seconds); all pooled connections were in use`. I've tried to fix it by closing the connection manually and the end of the action method `ActiveRecord::Base.connection.close` and seems it works, but I'm not sure if it's a good solution due to lack of knowledge about the internals of this module.
 
rails version - 7.0.8
ruby version - 3.1.4

**Comment by collimarco** [comment]
Related: https://github.com/rails/rails/discussions/57604

**Comment by collimarco** [comment]
Another useful article related to this issue:  https://tekin.co.uk/2023/07/active-record-connection-timeout-errors-with-puma
