### ISSUE TITLE
StiPreload implementation from Rails Guides results in uninitialized constant errors on Rails 7

### ISSUE THREAD

**Issue by dwillett** [rails/rails#44252]
When using the [StiPreload module implementation](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#single-table-inheritance) suggested in the Rails Guides it results in `NameError: uninitialized constant` for typical use cases with existing STI `type` data.

I believe the fact that this issue pops up with Rails 7 stems from the changes here: https://github.com/rails/rails/commit/ffae3bd8d69f9ed1ae185e960d7a38ec17118a4d .

### Steps to reproduce
I've added a repo to demonstrate the problem here: [@dwillett/rails_7_sti_preload](https://github.com/dwillett/rails_7_sti_preload)

```shell
$ bin/rails db:create
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
$ bin/rails db:migrate
== 20220124235533 AddUsers: migrating =========================================
-- create_table(:users)
   -> 0.0022s
== 20220124235533 AddUsers: migrated (0.0023s) ================================

$ bin/rails r "Member.create(name: 'Foo')"
$ bin/rails r "puts Member"
Member
$ SHOWCASE_BUG=true bin/rails r "puts Member"
Please specify a valid ruby command or the path of a script to run.
Run 'rails runner -h' for help.

uninitialized constant Member
```

When the environment variable is present, `self.descendants` will be invoked as part of requiring the `User` base STI class. It appears that invoking `Class.descendants` while the class is being loaded has implicitly been a circular problem with the `StiPreload` module (In this example: `Member` autoloads `User`, which invokes `.descendants` which tries to constantize `Member`), but with the changes in Rails 7 it now invokes that method directly when setting up association callbacks instead of `ActiveSupport::DescendantsTracker.descendants(self)`.

### Expected behavior
Class should be autoloaded correctly without error.

### Actual behavior
Class encounters unitialized constant error when attempting to autoload and preload class.

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 3.0.3

**Comment by casperisfine** [comment]
So the issue here is that you call `User.descendants` from the top level of `user.rb` so so before `user.rb` has finished to load.

If you delay the call it works, e.g. remove `puts self.descendants if ENV['SHOWCASE_BUG']` and then:

```ruby
$ bin/rails r 'p User.descendants.map(&:name)'
["Member"]
```

A way to handle this a bit more gracefully would be to modify the `StiPreload` module to use `safe_constantize`:

```ruby
module StiPreload
  unless Rails.application.config.eager_load
    extend ActiveSupport::Concern

    included { cattr_accessor :preloaded, instance_accessor: false }

    class_methods do
      def descendants
        preload_sti unless preloaded
        super
      end

      # Constantizes all types present in the database. There might be more on
      # disk, but that does not matter in practice as far as the STI API is
      # concerned.
      #
      # Assumes store_full_sti_class is true, the default.
      def preload_sti
        types_in_db =
          base_class.unscoped.select(inheritance_column).distinct.pluck(inheritance_column).compact

        self.preloaded = types_in_db.map { |type| }.all?
      end
    end
  end
end
```

However with this change instead of raising an error, `descendants` will be missing some classes, so I'm not sure it's really better.

I'll dig a bit more to see if I can find some better fix, but I'm not overly optimistic.

**Comment by casperisfine** [comment]
Oops, the code snippet in my previous response was missing a small bit, I edited it.

**Comment by casperisfine** [comment]
So to better explain what's going on, you can use a much simpler repro:

```ruby
# app/models/user.rb
class User < ApplicationRecord
  p ::Member
end

# app/models/member.rb
class Member < User
end
```

```bash
$ echo 'puts Member' > tmp/repro.rb; bin/rails r tmp/repro.rb
app/rails_7_sti_preload/app/models/user.rb:2:in `<class:User>': uninitialized constant Member (NameError)
	from app/rails_7_sti_preload/app/models/user.rb:1:in `<top (required)>'
	from ~/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:27:in `require'
	from ~/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:27:in `require'
	from app/rails_7_sti_preload/app/models/member.rb:1:in `<top (required)>'
	from ~/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:27:in `require'
	from ~/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:27:in `require'
	from app/rails_7_sti_preload/tmp/repro.rb:1:in `<top (required)>'
	from ~/gems/railties-7.0.1/lib/rails/commands/runner/runner_command.rb:43:in `load'
	from ~/gems/railties-7.0.1/lib/rails/commands/runner/runner_command.rb:43:in `perform'
	from ~/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from ~/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from ~/gems/railties-7.0.1/lib/rails/command/base.rb:87:in `perform'
	from ~/gems/railties-7.0.1/lib/rails/command.rb:48:in `invoke'
	from ~/gems/railties-7.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

So what's going on here is that:

  - You reference `Member` which trigger a `require "member.rb"`
  - Ruby see `class Member < User`, so it first evaluate `User` which trigger a `require "user.rb`
  - `User` is defined
  - `Member` is referenced again, which triggers a second `require "member.rb"`, but this time it's a noop because we're already requoring it.
  - `Member` still isn't defined yet, so the reference isn't found.


So yeah, it's kind of a bog standard circular reference during load issue, it isn't really specific to Zeitwerk or the `StiPreload` module.

So you must find a way to delay this loading.

Hope this helps.

**Comment by dwillett** [comment]
Yeah, that all sounds in line with with my investigation as well. My current workaround is to detach the preloading from the `Class.descendants` method and manually invoke the preloading logic on all STI base classes in an initializer, eg:

```ruby
# Eager load the StiPreload base classes. Workaround for circular autoloading:
# https://github.com/rails/rails/issues/44252
unless Rails.application.config.eager_load
  db_exists =
    begin
      ActiveRecord::Base.connection
    rescue StandardError
      false
    else
      true
    end
  if db_exists
    ActiveSupport::Reloader.to_prepare do
      [
        User,
        ...
      ].map(&:preload_sti)
    end
  end
end
```

That seems like it should achieve the same effect without the lazy loading.

I wanted to raise the issue in case it was appropriate to revise the guidance on the StiPreload approach in the guides in some way. I think that the changes to use `self.descendants` instead of the `ActiveSupport::DescendantsTracker.descendants(self)` in the association callbacks would make the current StiPreload approach a problem for most nominal use cases

**Comment by rsieb** [comment]
Thanks so much @casperisfine and @dwillett for figuring this out. @dwillett's solution solved my problem!

**Comment by byroot** [comment]
Using `to_prepare` like this means that model is no longer autoloaded. 

If you need all descendants to be loaded when `User` is, Something more elegant would be to use my modified `StiPreload`: https://github.com/rails/rails/issues/44252#issuecomment-1024078428

And in an initializer:

```ruby
Rails.application.autoloaders.main.on_load("User") do |user|
  user.descendants
end
```

I haven't tested it, but unless I'm missing something this way:

  - `User` isn't loaded unless needed
  -  As soon as you reference `User` or any of its descendants, they're all loaded together.


> I wanted to raise the issue in case it was appropriate to revise the guidance on the StiPreload approach in the guides in some way.

Yeah, we could use my updated snippet.

**Comment by fxn** [comment]
I documented something like that in https://github.com/rails/rails/commit/c04cf690f1060e7268567474ccf1ab2753a70940  (draft to be polished), but found some edge cases with circular dependencies and reverted the patch to play it safe.

Which edge cases? I'd also like to know, can't remember :). I believe that approach may work for most projects, but depending on what you refer to in class bodies, it might not work.

But perhaps we could revisit this, because the `on_load` callback is super nice for this use case.

**Comment by fxn** [comment]
Ah! I got it!

With the `on_load` callback, the application cannot hit a descendant directly.

If you have:

```ruby
class Root
end

class Child < Root
end
```

and you hit `Child`, Ruby performs a `require` for (the full path of) `child.rb`. The superclass reference triggers autoloading `Root`, and that happens before the `Child` constant is created. You need first the superclass in order to define the class.

Cool, so (the full path of) `root.rb` is required, and `on_load` is called when the file has been loaded. If "Child" is in the database, the callback tries to constantize it, and at that point Ruby won't find it. So it just raises `NameError` for `Child`.

Doesn't work.

And this is something that tricked us in the past for solutions with the `classic` autoloader. You came up with a solution, and the solution didn't work if you hit the hierarchy in the weak spot.

**Comment by byroot** [comment]
Yeah, that's why a modified the snipper slitghly to use `safe_constantize`, still not perfect but should handle most cases.

But yeah, I really don't see how this could be handled correctly in 100% as long as we're in an autoloaded environment (regardless of the autoloader). There might be a way, but I don't see it :/

**Comment by fxn** [comment]
I believe then the issue is moved to further descendants

```ruby
class Grandchild < Child
end
```

If you hit `Child`, the callback won't be able to load `GrandChlid`, because it won't find the superclass.

**Comment by fxn** [comment]
STIs are an ugly corner I'd love there was an elegant solution for.

We are in an autoloading setting that needs eager loading for some files, and we don't know which ones.

One simple way to address it is admit you need to be explicit and you need to eager load this, so sacrifice just a bit performance and eager load in `to_prepare`. If you keep a list of tree leaves there, you don't even need to go to the database. Superclass pointers will load it all upwards.

**Comment by byroot** [comment]
> STIs are an ugly corner I'd love there was an elegant solution for.

Agreed.

> One simple way to address it is admit you need to be explicit and you need to eager load this, so sacrifice just a bit performance and eager load in to_prepare.

Beside the performance concern (which applies to large apps like our but probably not to the average Rails app), my concern is about DRYness. This kind of list can easily go out of sync as one person set it up once, and another person that doesn't know about it introduce a new subclass making the list outdated. etc. etc.

That's why we developed the database query solution back in the day.

But also this snippet goal was only to make AR STI queries work properly because AR will add `WHERE type in (...)`. Maybe `descendants` is simply the wrong hook point as like this issue shows it can be called too early. But if we were to list possible subclasses right before the STI query is done, I think it wouldn't be a concern anymore.

**Comment by fxn** [comment]
> Beside the performance concern (which applies to large apps like our but probably not to the average Rails app), my concern is about DRYness. This kind of list can easily go out of sync as one person set it up once, and another person that doesn't know about it introduce a new subclass making the list outdated. etc. etc.

Totally.

**Comment by dwillett** [comment]
> Maybe descendants is simply the wrong hook point as like this issue shows it can be called too early. But if we were to list possible subclasses right before the STI query is done, I think it wouldn't be a concern anymore.

This was my original inclination - hoping there was an obvious place the preload lazy load moment could be shifted to.

I tried the updated snippet with `on_load("base")` and `safe_constantize` and was unsuccessful.

**Comment by byroot** [comment]
I'll dig a bit more Monday, see if I can find a better hook, but it's likely to end up being a prepend on some private method, so hardly something we'll be able to recommend :/

**Comment by fxn** [comment]
> I'll dig a bit more Monday, see if I can find a better hook, but it's likely to end up being a prepend on some private method, so hardly something we'll be able to recommend :/

Awesome man :).

Something that perhaps we could consider would be: If we can determine if a class instance is an AR STI somehow, the AR railtie could schedule a generic `main.on_load` that does whatever private thing AR wants to do, like injecting dynamically a mixin.

Not sure this would be of any help in your approach, just throwing an idea.

**Comment by casperisfine** [comment]
Here's the updated module with the proper (private API) hook:

```ruby
module StiPreload
  unless Rails.application.config.eager_load
    extend ActiveSupport::Concern

    class_methods do
      def type_condition(...)
        unless @_sti_preloaded
          types_in_db = base_class.unscoped.select(inheritance_column).distinct.pluck(inheritance_column).compact
          @_sti_preloaded = types_in_db.map { |type| type.safe_constantize }.all?
        end
        super
      end
    end
  end
end
```

It only aims at solving the main issue which is querying. e.g. if you have `User > Member > VIPMember`, then in autoloading mode, `Member.all` don't include `VIPMember` records unless `VIPMember` is already load.

This new module does fix this issue, which is pretty much we wanted to do in https://github.com/rails/rails/pull/36487

Note that it doesn't try to make `descendants` or `subclasses` behave like they would in an eager loaded environment, as I don't think it's as much of a problem.
