### ISSUE TITLE
Not depending on unmaintained dependencies

### ISSUE THREAD

**Issue by Segaja** [rails/rails#44292]
Hello,

according to https://github.com/rails/sprockets/issues/661#issuecomment-906666544 sprockets is unmaintained. It hasn't seen new releases in almost 2 years and it relies on a bunch of outdated dependencies (babel, yui-compressor...).

Such outdated dependencies shouldn't be moved and make it very hard to package this for linux distributions like Archlinux.

Best regards

**Comment by byroot** [comment]
Rails 7 doesn't have any hard dependency on sprockets.

**Comment by dvzrv** [comment]
@byroot sprockets may not be used during runtime, but it is a requirement for the tests. This is a huge problem for downstreams trying to test, build and integrate this software against their ecosystem.

Please reopen this ticket until it is solved (all requirements on sprockets are removed).

- actionview requires sprockets during testing:
  https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/actionview/Rakefile#L112-L113
  This is not specified in [actionview.gemspec](https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/actionview/actionview.gemspec)
- activerecord requires sprockets during testing:
  https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/activestorage/test/dummy/config/application.rb#L11
  This is not specified in [activestorage.gemspec](https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/activestorage/activestorage.gemspec)
- railties requires sprockets during testing:
  https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/railties/test/isolation/abstract_unit.rb#L564
  This is not specified in [railties.gemspec](https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/railties/railties.gemspec).

Furthermore sprockets, sprockets-rails and sprockets-export is still mentioned in Gemfile and Gemfile.lock (which are removed in the context of system packaging, but will still lead to others effectively having to install sprockets when relying on the Gemfile):

https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/Gemfile#L14
https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/Gemfile#L112
https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/Gemfile.lock#L163
https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/Gemfile.lock#L504
https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/Gemfile.lock#L507
https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/Gemfile.lock#L508
https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/Gemfile.lock#L511
https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/Gemfile.lock#L629
https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/Gemfile.lock#L630

Sprockets is also still mentioned in the initialization guide (which is more of a documentation problem of course):

https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/guides/source/initialization.md?plain=1#L545
https://github.com/rails/rails/blob/41dd8d0bd7f544230701878130f840bafbef7928/guides/source/asset_pipeline.md?plain=1#L27-L34

Unless the test requirements are addressed (i.e. removed), downstreams effectively *have to* package sprockets to run the tests, which is a problem.

**Comment by byroot** [comment]
Reopening in case someone wish to work on this (not me). But IMO packaging Rails as a distro package really make little sense. Anyway.

**Comment by ghiculescu** [comment]
> Please reopen this ticket until it is solved (all requirements on sprockets are removed).

I don't think sprockets is likely to happen for a long time. rails-ujs is soft deprecated (in favor of Hotwire which is outside this repo) but sprockets will be needed to compile and test all its code, and I don't think that will be removed anytime soon.

Is there anything specifically broken with the current setup? If not then I don't think there is much that can be done here.

**Comment by dvzrv** [comment]
> Is there anything specifically broken with the current setup? If not then I don't think there is much that can be done here.

Yes, as mentioned in https://github.com/rails/rails/issues/44292#issuecomment-1036036941. If downstreams have to package a deprecated and discontinued project (see https://github.com/rails/sprockets/issues/661#issuecomment-906666544) to build and test this project, then that is a problem. It means a lot of work and a lot of patches just to remove its use, which is why the cleanest approach would be to completely remove its use from the rails sources or to make its use during build and test entirely optional (less great as sprockets is discontinued and should not be used at all).

To circle back on 

> but sprockets will be needed to compile and test all its code, and I don't think that will be removed anytime soon.

Why is it still used for build and test scenarios, if it is later on not used though?
Why not remove this legacy integration (it seems to be [superseded by webpacker](https://github.com/rails/rails/blob/70aafe079c37816c70f96af2aeb3c2937019cf9d/guides/source/webpacker.md#how-is-webpacker-different-from-sprockets))? Is there a support guideline for the rails project, that I am not aware about which prevents to fully remove the use of sprockets?

FWIW, sprockets has not seen a release since 2016 and only supports custom/legacy javascript tooling, which also from a security standpoint should be reason enough to fully remove its use.
Webpacker has been [added in 5.1](https://github.com/rails/rails/blob/8a7a9d0a0b27e113e6d0a6087299c4bd41d29738/guides/source/5_1_release_notes.md) and has been [made the default in 6.0.0](https://github.com/rails/rails/blob/f84eecec7127cff916c89a20b0eb5678fefc572c/guides/source/6_0_release_notes.md).

**Comment by rafaelfranca** [comment]
Sprockets is not discontinued and we have no plans to remove it from the Rails test suite because it is still being used. When we finish the transition to propshaft in the future we will remove, but right now it will continue here.
