### ISSUE TITLE
ActiveSupport::Duration gives unexpected results when subtracting durations

### ISSUE THREAD

**Issue by adampal** [rails/rails#44331]
### Steps to reproduce
Open the Rails console and run:
```
result = 1.hour - 30.minutes
result.parts
=> {hours: 1, minutes: -30}
```

### Expected behavior

I expected the result to be:
```
{hours: 0, minutes: 30}
```

### Actual behavior
It returns a positive hour value with a negative minute value.  Ie
```
{hours: 1, minutes: -30}
```

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

This seems like a simple error in the way we're doing duration maths but I'm hesitant to call it a bug given it must have been like this for a long time.
I'm happy to work on a fix if everyone agrees that the current behaviour is _not_ what should be expected.

**Comment by nickpellant** [comment]
Hi, @adampal. 👋 

What you've reported isn't a bug; it's an intentional part of the `ActiveSupport::Duration` class design.

`#parts` are the duration totals of each time unit (i.e. seconds, minutes, hours, etc.). Duration totals aren't converted to seconds and combined until that operation is needed (i.e. when using `#to_i` for seconds total, or `#since` to calculate a time offset). Durations are tallied individually until then.

See the class docs for more: https://api.rubyonrails.org/classes/ActiveSupport/Duration.html

**Comment by adampal** [comment]
Thanks @nickpellant appreciate the response.

I'll change the way I'm using it now that I know that's a deliberate design decision.

I was using durations to display information in the UI and created a helper method that takes a duration and uses the `parts` to create a string like `5 hours, 27 minutes`.  However sometimes that string ends up containing negative values that don't really make sense to the user.

Seems like the easiest fix is to do something like `new_duration = ActiveSupport::Duration.build(duration.to_i)` then use that new duration to create the string.
