### ISSUE TITLE
ActiveStorage, how to alter the key in direct uploads? Use of a Prefix for S3 buckets.

### ISSUE THREAD

**Issue by resistorsoftware** [rails/rails#44376]
I have a bucket at s3 called **my-bucket** and the CORS for the bucket works. I can direct upload files to it. I have a folder (key) under that bucket called **special-stuff** where I want my direct uploads to go. That folder has security credentials that work, as I logged in the AWS console and successfully uploaded files to the location **my-bucket/special-stuff**. 

I assigned those credentials to the **:amazon** settings in my Rails 7.0.2 App, and then I tried an upload going to the bucket **my-bucket**. It passed CORS but failed on the PUT. I think the reason is, it tried uploading to **my-bucket** and not the desired **my-bucket/special-stuff**. 

So my big question is, where in my code can I inform S3 the key is **my-bucket/special-stuff/myfile.csv** when my upload form submits the direct upload filename myfile.csv. At this time, it just goes to the bucket which is not where I would like the file to be saved, ie)  **my-bucket/myfile.csv**

I see in the attach method, my desired upload is available to me, but it is already some encrypted string. 

"my_upload"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ff2502d7aa2eec5b97405b86070b4d50c86fb9a6"

So I see no way of getting in there and adding in my needed prefix.

Thanks

**Comment by gmcgibbon** [comment]
> So my big question is, where in my code can I inform S3 the key is my-bucket/special-stuff/myfile.csv when my upload form submits the direct upload filename myfile.csv. At this time, it just goes to the bucket which is not where I would like the file to be saved, ie) my-bucket/myfile.csv

Active Storage does not support specifying custom keys or placing assets in subdirectories of buckets. I would be open to accepting a PR that added support for scoping a storage service to a subdirectory, but the keys Active Storage are dynamic by design.

**Comment by resistorsoftware** [comment]
I find this so strange. At the end of the day, it is some payload in a bucket. No one cares what that payload is, as long as when they ask for it back on a read, that the payload is there. So if I want to save coke.csv in bucket pepsi, I get it. ActiveStorage saves whateverfancypantsblobthing in the bucket pepsi and calls it a day. 

You can still save whateverfancypantsblobthing in the bucket pepsi, but really, it it somehow too hard to add in a prefix to the blog so that it makes sense in the pepsi bucket as pepsi/:prefix/whateverfancypantsblobthing? 

Ok.. I get it. too hard to do... 

Thanks for looking into this though. Much appreciated.

**Comment by jeropaul** [comment]
I get that this issue is closed but the change may not be all that large! I haven't traced the full path so I may have missed something... but it looks like a PR could be pretty small:

- Allow a key to be specified in the [DirectUpload constructor](https://github.com/rails/rails/blob/a6099ed2b7a544d8fe67688e8a0f9237847404ee/activestorage/app/javascript/activestorage/direct_upload.js#L8)
- Pass the key through to the [BlobRecord constructor and attributes](https://github.com/rails/rails/blob/a6099ed2b7a544d8fe67688e8a0f9237847404ee/activestorage/app/javascript/activestorage/blob_record.js#L7C10-L7C20)

- add `key` to the permitted blob args in the [DirectUpload controller](https://github.com/rails/rails/blob/a6099ed2b7a544d8fe67688e8a0f9237847404ee/activestorage/app/controllers/active_storage/direct_uploads_controller.rb#L14)

Which will then be used by [create_before_direct_upload](https://github.com/rails/rails/blob/a6099ed2b7a544d8fe67688e8a0f9237847404ee/activestorage/app/models/active_storage/blob.rb#L109)

I get the point raised by @gmcgibbon above that the keys used by active storage are dynamic by design. I suspect adding a prefix arg would be a similar amount of work...

**Comment by jm3** [comment]
ActiveStorage now supports a [custom S3 bucket sub-dir key](https://edgeguides.rubyonrails.org/active_storage_overview.html#attaching-file-io-objects) in your controller logic, which may boost the relevance of this request to support passing a custom key with `DirectUpload`:

> There is an additional parameter key that can be used to specify folders/sub-folders in your S3 Bucket. AWS S3 otherwise uses a random key to name your files. This approach is helpful if you want to organize your S3 Bucket files better.

```ruby
@message.images.attach(
  io: File.open("/path/to/file"),
  filename: "file.pdf",
  content_type: "application/pdf",
  key: "#{Rails.env}/blog_content/intuitive_filename.pdf",
  identify: false
)
```

> This way the file will get saved in the folder `[S3_BUCKET]/development/blog_content/` when you test this from your development environment. Note that if you use the key parameter, you have to ensure the key to be unique for the upload to go through.
