### ISSUE TITLE
RoutingError on destroy test when use carrierwave

### ISSUE THREAD

**Issue by phuongnd08** [rails/rails#44382]
### Steps to reproduce
Check out this commit
https://github.com/phuongnd08/movereader/commit/b53bf41b0f46cfcff5b33951514d5570e8649a7e

And setup your rails app using PostgreSQL db: 
```
bundle install
bin/rails db:test:prepare
```

Then run the test: 
```
bin/rails test test/system/moves_test.rb
```

### Expected behavior
Test pass 

### Actual behavior
Test failed with ActionController::RoutingError

### System configuration
**Rails version**: 7.0.2

**Ruby version**: 2.7.2

**Comment by gmcgibbon** [comment]
I can't reproduce the error in the app provided. The test passes. You could try using a [bug report template](https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller_gem.rb) to narrow down a potential issue with actionpack, but anything related to third party gems we aren't responsible for.

Since this doesn't look like a rails bug to me, I'm going to close. Thanks for the report.
