### ISSUE TITLE
ActiveRecord::RecordNotFound error in fixture array when deleting or destroying objects through model callbacks during test execution

### ISSUE THREAD

**Issue by jlucartc** [rails/rails#44400]
I wrote a test case which verifies if children(B model) objects are deleted from database after their parent(A model) is deleted. The parent object is always deleted successfully, but for some reason the children fixtures array ends up being broken and failing the test with an unexpected error. The error message is as follows:

```
Error:
ATest#test_destroying_A_should_delete_all_associated_B:
ActiveRecord::RecordNotFound: Couldn't find B with 'id'=980190962
    test/models/a_test.rb:6:in `block in <class:ATest>'

```

##### Creating project
```ruby
rails new testing-fixtures
cd testing-fixtures
rails g model A
rails g model B
```
##### Migrations
```ruby
class CreateAs < ActiveRecord::Migration[7.0]
  def change
    create_table :as do |t|
      t.string :name
      t.timestamps
    end
  end
end
```
```ruby
class CreateBs < ActiveRecord::Migration[7.0]
  def change
    create_table :bs do |t|
      t.integer :a_id
      t.string :description
      t.timestamps
    end
  end
end
```
##### Fixtures

```yml
# A objects
one: {
  id: 1,
  name: 'A-object number 1'
}
```

```yml
# B objects
one: {
  a_id: 1,
  description: 'Belongs to A#1'
}
two: {
  a_id: 2,
  description: 'Belongs to A#2'
}
```
##### app/models/a.rb

```ruby
class A < ApplicationRecord
	after_destroy :delete_all_associated_bs

	def delete_all_associated_bs
		B.where(a_id: self.id).destroy_all
	end

end
```
##### test/models/a_test.rb

```ruby
require "test_helper"

class ATest < ActiveSupport::TestCase
  test "destroying A should delete all associated B" do
    as(:one).destroy
    refute B.find(bs(:one)[:id]).present?
  end
end
```
##### Running migrations
`rails db:migrate`

##### Running test

`rails test test/models/a_test.rb`

### Expected behavior

`bs` array should still contain both entries, while `B.all` should return an array containing only the `:two` object. The test case should pass.

### Actual behavior

Any interaction with `bs` array  (ex: executing `puts bs`,`bs.class`,`bs.nil?` on console ) triggers:
```
Error:
ATest#test_destroying_A_should_delete_all_associated_B:
ActiveRecord::RecordNotFound: Couldn't find B with 'id'=980190962
    test/models/a_test.rb:6:in `block in <class:ATest>'

```

### System configuration
**Rails version**: 7.0.2

**Ruby version**: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

**Comment by nvasilevski** [comment]
You may want to change your test as following:
```ruby
  test "destroying A should delete all associated B" do
    b_object_to_be_destroyed = bs(:one)
    as(:one).destroy
    refute_predicate B.where(id: b_object_to_be_destroyed.id), :exists?
  end
```

I think it's an expected behaviour. 
`bs(:one)` tries to lookup an object in the database using `.find` an raises an exception because `as(:one).destroy` destroyed the record.

I believe your expectations are slightly misleading because of this assumption:

>bs array should still contain both entries

`bs` in this case is not an array but a method that performs fixture lookup. And it's being defined here:
https://github.com/rails/rails/blob/8ae1339ae0b6f79a53bcb08cb4d7d07a605b67d6/activerecord/lib/active_record/test_fixtures.rb#L63

**Comment by jlucartc** [comment]
@nvasilevski thank you for the reply. I had already fixed the test case, but as it seemed like an unexpected behavior I decided to create the issue just for the record since someone may find the same problem.

It doesn't seem like an expected behaviour to me because destroying `as(:one)` didn't raise any errors when accessing `as` (eg: putting some line `puts as` after the destroy line), so I would expect the same from `bs`, since B objects were also destroyed. This should hold especially when deleting/destroying B records directly through ActiveRecord methods, because if fixture methods will be affected by ActiveRecord calls throughout the code, then there would be no point in using them, since they would be prone to errors like this and their use would need to be avoided somehow (eg: in your suggestion, the object is stored beforehand so that it can be used later) so that the test can pass.

**Comment by nvasilevski** [comment]
Ah, I see what you mean, so accessing `as(:one)` is possible after destroy as it cached after being loaded once on `as(:one).destroy`
https://github.com/rails/rails/blob/8ae1339ae0b6f79a53bcb08cb4d7d07a605b67d6/activerecord/lib/active_record/test_fixtures.rb#L75

I guess preloading cache to address this problem is not reasonable and not really sustainable. But I wonder if fixture method could be changed so instead of `.find` it uses something like `.new` to build in-memory object that is always `.present?` and `persisted?` based on columns defined in the fixture file and regardless of the actual database state. 
Could break a lot of other expectations though, but I'm a little curious
