### ISSUE TITLE
Rails 7 - referring an ActiveRecord model in an initializer does not work

### ISSUE THREAD

**Issue by kapso** [rails/rails#44424]
We have an initializer that refers to an ActiveRecord model, so something like this...

`config/initializers/user_init.rb`
```ruby
# User is an ActiveRecord model
User.load_settings # Pre-load app settings in the initializer from an external HTTP source
```

But Rails cannot find the model (this works in Rails 6.1.x)
```
/Users/kapil/projects/test_me/config/initializers/user_init.rb:1:in `<main>': uninitialized constant User (NameError)
```

### System configuration
**Rails version**: 7.0.2.2

**Ruby version**: 3.1.0

Is this expected behavior in `v7.x`?

**Comment by julienchabanon** [comment]
From what I understand, **ActiveSupport::Reloader.to_prepare** run for each request in the development environnement and once in production. Whereas Rails.configuration.after_initialize run only once for both dev and prod env.

**Comment by jmcbri** [comment]
This works great in development. One issue I had is that I'm using Kamal, and I think Kamal, when it runs the asset precompile, sets a dummy variable as the secret (SECRET_KEY_BASE_DUMMY=1) for image generation, runs rails, and it gets to the initializer, which failed because the database is not yet up, at least in my setup.  An easy hack was to check "Rails.application.config.assets.compile" before the meat of the initializer runs. If it's true, it's precompiling.
