### ISSUE TITLE
Make before_commit hook public API

### ISSUE THREAD

**Issue by splattael** [rails/rails#44458]
The hook `before_commit` was added back in https://github.com/rails/rails/pull/18936 and was considered private API:

> Keep in mind all this APIs are private for now, so we can use on https://github.com/rails/rails/pull/18824, and shape them before making them public.(if even we will)

In https://github.com/rails/rails/issues/25896 it was stated:

> It is not public API and should be not used in applications. It is for Rails internal usage.

This happened 6 years ago.

Do we consider `before_commit` hook stable now and should this API made public? :thinking: 

Refs https://gitlab.com/gitlab-org/gitlab/-/merge_requests/79964#note_844034381

**Comment by rafaelfranca** [comment]
No. We have no interest of making this hook public. It was never the plan to make them public. There is no much usage of a `before_commit` hook that can't be implemented with a `before_save`.

**Comment by avit** [comment]
Generally I agree it makes sense to keep this private because of tricky interactions with other callbacks that have already been run.

Otherwise, using `before_commit` too freely could become difficult to reason about if you're not careful: a record updated in that transaction phase could cause it to register more transaction records for commit callbacks (e.g. via `touch: true` associations), so hooking into it incorrectly would probably cause some strange behaviour.

Using `before_commit` with caveats does allow for some useful scenarios where I would disagree with the comment above:

1. Provide a place for executing dependent updates that might otherwise cause deadlocks when called from `after_save` of each record, thus avoiding interleaved DB locks between updates of other records. ActiveRecord added `touch_later` to do this at the end of the transaction precisely for that reason. (It's still possible to cause deadlocks within `touch_later` by the way — I fixed this in #38146; still waiting for a review.)

2. Provide a way to execute the callback for a record only once. With `after_save`, a record could be updated multiple times within a transaction, and trigger the callback each time. (It might be possible to set a flag on the record instance and prevent it from repeating the `after_save` callback, but then it would only run the first time — not with the final state of the updated record after multiple saves.)
