### ISSUE TITLE
`precision: nil` added to datetime columns in `schema.rb` in 7.0.2 causes a change in value

### ISSUE THREAD

**Issue by thisismydesign** [rails/rails#44571]
### Steps to reproduce

Running `db:migrate` in `7.0.2` adds `precision: nil` to datetime columns using postgres (a change from `7.0.1` discussed here https://github.com/rails/rails/issues/43909).

After this, one of our spec comparing dates is failing because of what looks like a precision related error:
```
Diff:
       @@ -1 +1 @@
       -Mon, 21 Feb 2022 14:10:49.640199500 CET +01:00
       +Mon, 21 Feb 2022 14:10:49.640199000 CET +01:00
```

The test basically asserts:

```
period = create(:period)
user = create(:user, period: period)

expect(period.start_at).to eq(user.period.start_at)
```

More importantly, this leads me to think there's an actual precision change that would not be reflected on production, only locally. I'm not sure how to rectify this.

In addition, it's unclear what `nil` means in this case. I liked the explicit `6` or no mention for default, but a change to `nil` was confusing. I assume it stands for the default.

### Expected behavior

No DB/value change

### Actual behavior

DB change

### System configuration
**Rails version**: 7.0.2.2

**Ruby version**: 3.0.3

**postgres version**: 13.4

**Comment by rafaelfranca** [comment]
`precision: 6` and `precision: nil` have different behavior. `nil` means use the database default for that type, the other means use `6` as precision. `t.datetime :foo, precision: 6` should not be changed to `t.datetime :foo, precision: nil`, it should be changed to `t.datetime :foo`.

Are you sure the database schema was correct before you did the `db:schema:dump`?

**Comment by rafaelfranca** [comment]
> More importantly, this leads me to think there's an actual precision change that would not be reflected on production, only locally.

There should not be change in behavior in any environment. The format of the schema changed, but its result should stay the same.

**Comment by thisismydesign** [comment]
I can reproduce this on our codebase by the following:
- on `7.0.1` I run `db:migrate:reset`, no change to the schema, no `precision` fields are added or present
- on `7.0.2` I run `db:migrate:reset`, `precision: nil` is being added and the described spec fails

So AFAICT the issue is with changing to `precision: nil`.

In our case, we somehow had `precision: 6` at some point during migrating to Rails 7, but I didn't mention that in this issue because it doesn't seem relevant anymore: on `7.0.1` there is no precision in the schema and the issue also happens when going from no precision to nil with 7.0.2.

**Comment by rafaelfranca** [comment]
> * on `7.0.2` I run `db:migrate:reset`, `precision: nil` is being added and the described spec fails

`db:migrate:reset` will drop the database before loading the shema, but that schema will not be the versioned one. You should not do that. First, load the schema in 7.0.1, then dump the schema in 7.0.2. Does that still generate the wrong precision?

**Comment by rafaelfranca** [comment]
BTW, adding `precision: nil` is not a problem, in the schema in 7.0.1, unless there was a explicit `precision: 6` before, that meant `precision: nil`. This are just explicit in 7.0.2. They should not have any behavior change. So those following lines are equivalent in 7.0.1 and 7.0.2.

```
# 7.0.1
t.datetime :foo

# 7.0.2
t.datetime :foo, precision: nil
```

```
# 7.0.1
t.datetime :foo, precision: 6

# 7.0.2
t.datetime :foo
```


What would cause a behavior change is:

```
# 7.0.1
t.datetime :foo, precision: 6

# 7.0.2
t.datetime :foo, precision: nil
```

What is the diff for the table that you saw the behavior change?

**Comment by rafaelfranca** [comment]
Also can you provide the date type in the postgresql console before and after for the column you are having different behavior?

**Comment by rafaelfranca** [comment]
What is the database type generated in both cases?

**Comment by rafaelfranca** [comment]
Ahhh, ok, I got what is happening. `t.datetime :foo` in 7.0.1 is actually `t.datetime :foo, precision: 6`. But, if you load the schema in 7.0.1 and them dump (not `db:migrate`, `db:schema:dump`) with 7.0.2 you should get the right schema. Did you try that?

**Comment by rafaelfranca** [comment]
It would really help if you could provide an example application. At the moment, I can't see a way this should have a different behavior if the database schema was correct already in the database before upgrading and after you upgrade you did do a schema dump before loading the schema.

**Comment by rafaelfranca** [comment]
`t.datetime :foo` in 7.0.1 should create a `timestampz (6)` type. A `timestampz (6)` type in 7.0.2 should be generated as `t.datetime :foo` in the schema dump as you can see in this test here https://github.com/rails/rails/pull/44358/files#diff-9140a6bb770421fd3b4c3b32dc511f8a4b6af9a670efb142eb815d73e35ac744R121.

**Comment by mattscilipoti** [comment]
I am seeing similar issues. I just upgraded from 7.0.1 to 7.0.2.2, I see this change in my schema.rb:
``` diff
-ActiveRecord::Schema.define(version: 2022_01_25_231940) do
-
+ActiveRecord::Schema[7.0].define(version: 2022_01_25_231940) do
   # These are extensions that must be enabled in order to support this database
   enable_extension "plpgsql"
 
@@ -20,7 +19,7 @@ ActiveRecord::Schema.define(version: 2022_01_25_231940) do
     t.string "record_type", null: false
     t.bigint "record_id", null: false
     t.bigint "blob_id", null: false
-    t.datetime "created_at", precision: 6, null: false
+    t.datetime "created_at", null: false
     t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
```

**Comment by matthewd** [comment]
@mattscilipoti that's expected: `precision: 6` is the default in schema version `7.0`. (But before 7.0.2, it was still [unnecessarily] being dumped explicitly.)

**Comment by mattscilipoti** [comment]
I stand corrected. My apologies for taking up your time.

**Comment by thisismydesign** [comment]
So I found out more. Thanks @rafaelfranca for mentioning `db:schema:dump` and to check for column type in the DB.

### Issue 1

In our production (and local setups created some time ago) we have no precision on DB fields:

```
created_at    | timestamp without time zone |           |          | 
updated_at    | timestamp without time zone |           |          | 
```

We're on `7.0.1` and the schema contains no precision fields, i.e. `t.datetime "created_at"`. In case I do `db:schema:dump` the schema remains the same.

Now suppose I want to set up this project from scratch. I do `db:preapre`. Now the DB columns are created with explicit precision 6:

```
created_at    | timestamp(6) without time zone |           |          | 
updated_at    | timestamp(6) without time zone |           |          | 
```

Now doing `db:schema:dump` actually adds `precision: 6` to the schema. So I ended up with a different setup than in production. This is an issue.

As a workaround I can do `db:migrate:reset` instead of `db:preapre` to have the correct DB column types (without explicit precision).

### Issue 2 (original issue)

So we have this ping-pong between old and new local setups of the project on `7.0.1`. But of course, we want the same setup as production, so back to this DB:

```
created_at    | timestamp without time zone |           |          | 
updated_at    | timestamp without time zone |           |          | 
```

Given this local DB setup, rails `7.0.1` and no precision fields in the schema (this seems consistent, `db:schema:dump` changes nothing).

I update rails to `7.0.2`. I run specs, they work. I do `db:schema:dump`. Schema is now updated to have explicit `precision: nil` for every date column. This seems fine, as it reflects the DB setup correctly. When I set up the project from scratch with `db:prepare` I get the correct DB column types (`timestamp without time zone`).

I run specs, they fail.

```
Diff:
       @@ -1 +1 @@
       -Mon, 21 Feb 2022 14:10:49.640199500 CET +01:00
       +Mon, 21 Feb 2022 14:10:49.640199000 CET +01:00
```

This is the original issue. `precision: nil` in the schema changes something even though the underlying DB didn't change.

**Comment by sclinede** [comment]
We faced related issue on MySQL specifically, if you try to assign default value to a timestamp column:
```
t.datetime :foo, precision: 6, default: -> { 'current_timestamp(6)' }
```
Then `db:migrate` will run just fine, but if you try `db:schema:load` from the result schema, you'll get:
```
ActiveRecord::StatementInvalid: Mysql2::Error: Invalid default value
```
This basically leads to CI failures all the time if we create a migration with timestamp column with `precision: 6` AND default value

cc @rafaelfranca @thisismydesign

**Comment by rafaelfranca** [comment]
> Then db:migrate will run just fine, but if you try db:schema:load from the result schema, you'll get:

> ActiveRecord::StatementInvalid: Mysql2::Error: Invalid default value

This error doesn't seems to have anything with this. Invalid `default` value should not be about the precision.

**Comment by rafaelfranca** [comment]
@thisismydesign I think the failing test you are seeing makes sense to the schema you created in production. Your test needs to be updated given in production you have those columns without precision.

Again, please provide an example application if you believe this is still an issue so I can reproduce. I upgrade many applications to Rails 7.0 and we had no difference in behavior and the schema.rb file matched what it is in the database.

The schema

```
updated_at    | timestamp without time zone |           |          | 
```

Should really mean `precision: nil`

**Comment by thisismydesign** [comment]
@rafaelfranca I provided clear instructions to reproduce IMO on both issues I mentioned. Can't spend more time on this unfotunately.

**Comment by sclinede** [comment]
Sorry for being tedious but before the change was introduced there was no issue with `db:schema:load` while I agree solution has to be somewhere in MySQL client/driver it is related to the change

Secondly "This error doesn't seems to have anything with this. Invalid default value should not be about the precision." It **IS** related. For timestamps or datetime in MySQL default value has to match the precision. E.g. 
```
t.timestamp :foo, precision: 6, default_value: -> { "current_timestamp" } 
```

**Comment by thisismydesign** [comment]
FWIW I had my issues with postgres, so perhaps there's something common in the AR layer.

**Comment by rafaelfranca** [comment]
> @rafaelfranca I provided clear instructions to reproduce IMO on both issues I mentioned. Can't spend more time on this unfotunately.

I can't reproduce the problem with your instructions sorry. The generated schema is correct all the times I trie your reproduction steps. What I'm looking at is if the schema in the database is the same after I upgrade to 7.0.2, dump the schema, and load it. If a test is failing, I think your test was passing by mistake before.

@sclinede your issue is a different one and while it is related to the precision dumping, it is caused by mismatch in precision. Could you open a new issue?

**Comment by rafaelfranca** [comment]
Let me try to say clearly what are the steps to upgrade from 7.0.1 to 7.0.2.

# Rails 6.1
bin/rails db:schema:load

# Rails 7.0.2
bin/rails db:schema:dump
# Commit the generated file

If you are already on Rails 7.0.1, unfortunately loading the schema from the schema.rb will give you the wrong database schema, that is why you get `timestamp(6)` when you do `db:prepare` in 7.0.1. That was the bug that was fixed on 7.0.2. So it is important to load the schema from a version of Rails that doesn't have the bug. I'm not sure if that would if you load on 7.0.2, but I believe so.

Unfortunally, the bug on 7.0.0 make this very hard to upgrade, that is why in 7.0.2 the Rails version is bumped in the schema to keep backward compatibility easier to achive.

I believe the fact you are getting test errors when upgrading to 7.0.2 ie because the test was relying in the bug existing in 7.0.1 and that test now should be updated to match the schema generated by 7.0.2, or your schema should be changed by introducing a new migration that would change the precision of the column to what the test is expecting.

**Comment by rafaelfranca** [comment]
I'm still puzzled by this and I trying really to understand the problem to help you to fix it.

> This is the original issue. `precision: nil` in the schema changes something even though the underlying DB didn't change.

The schema.rb only exists to create the db schema. It has no effect in the execution. So what could happen is that the test database have a different schema as the previous version of Rails now. Did you inspect the test database to see if the schema was matching the production/development database?

I'm not at all doubting of your issue, but this issue can be caused by a lot of different causes, like order commands are run, difference in environments, and of course a bug in the framework. When I try to reproduce I'm not being successful probably because I know the order to execute the migration path.

If you could, checking if the test database changed between the two versions would be of great help. If you see a difference, which one if more correct, >= 7.0.2 or before that? What I see is that the 7.0.2 version of the database schema is the correct one, when the precision on schema.rb matches what I was expecting the production schema to be.

**Comment by jcbpl** [comment]
I'm running into a similar problem on 7.0.2.4. Steps:

1. Run `db:schema:dump` against a Postgres database where the default precision is 6.
2. The resulting schema.rb includes `precision: nil`.
3. Load the schema on another Postgres database where the default precision is higher (9).

Because the schema contains `precision: nil`, the column created in step 3 has the maximum precision (9).

If I _remove_ `precision: nil` from schema, then step 3 creates the column with Rails' default precision (6) instead of Postgres' (9), which is what I want, since that matches the database the schema was dumped from.

In my view, the expected behavior would be for the schema dumper **not to add** `precision: nil` if the database's default precision matches Rails' default precision.

**Comment by rafaelfranca** [comment]
> In my view, the expected behavior would be for the schema dumper **not to add** `precision: nil` if the database's default precision matches Rails' default precision.

That is what it does right now. It only adds `precision: nil` if the column has no precision in the database. Rails can't know the database's default precision, so it can't check to see if it matches the Rails' default precision.

`precision: nil` should not create columns with Rails default precision. It should just generate a SQL that includes no precision. If that isn't the case it is a bug. Can you please paste the SQL generated by Rails on step 3?

**Comment by jcbpl** [comment]
> Rails can't know the database's default precision, so it can't check to see if it matches the Rails' default precision.

Ah, interesting. I assumed it could be derived from `SELECT current_timestamp`.

> `precision: nil` should not create columns with Rails default precision.

It's not—it's only using the Rails default when the schema doesn't include `precision`. I agree that `precision: nil` has the expected behavior. I'd just rather `db:schema:dump` didn't include it when the result of "no precision" matches the default precision, but I hear ya that that may not be possible to determine.

I suspect part the confusion is that Rails didn't always set the precision when creating columns, so older columns don't have it set, while newer ones do, and when we dump older tables, we get `precision: nil` on its timestamps even if their precision matches the current default.

It sounds like the solution might be to manually set `precision: 6` on those old columns, which would then yield a schema that doesn't include `precision: nil`.

**Comment by jcbpl** [comment]
Right… I don't think it's a bug? `precision: nil` does not set any precision on the SQL. This is the SQL with `precision: nil`:

```
CREATE TABLE "examples" ("id" bigserial primary key, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
```

vs ths SQL **without** `precision`:

```
CREATE TABLE "examples" ("id" bigserial primary key, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)
```

My understanding of the OP is that schema.rb now includes `precision: nil` where it didn't on previous versions. That change is technically correct, because the database columns do **not** specify precision, but some applications (or test suites) were relying on the previous behavior, which meant that Rails used its default when loading the schema. Now, instead, it uses the database default.

I think it's less a bug than an unintentional consequence.

**Comment by rafaelfranca** [comment]
Ahhh. Got what you mean. Yeah. That is by design. Using the Rails default was the problem we had before because Rails defaults can change with time. In that cause, users should change their database schema using a migration to reflect their needs. Rails is now reflecting what the existing database schema is telling Rails to do.

**Comment by jcbpl** [comment]
Yep, that makes sense! Thanks for your help 👍
