### ISSUE TITLE
ENOENT with bin/rails tailwindcss:watch

### ISSUE THREAD

**Issue by 9mm** [rails/rails#44646]
### Steps to reproduce

Create a new project with these configurations (specifically, using tailwind):

    rails new test-app --database=postgresql --skip-action-mailer --skip-action-mailbox --skip-action-text --skip-active-job --skip-active-storage --skip-action-cable --asset-pipeline=propshaft --skip-hotwire --skip-jbuilder --skip-test --skip-system-test --skip-bootsnap --css=tailwind

Now run the included `bin/rails tailwindcss:watch`

Now edit `application.html` several times, hitting save

### Expected behavior

The watch command should always watch the saved file

### Actual behavior

About 1 out of 10 saves for me, it aborts the terminal command with the following error. I assume it is a race condition. I have tried saving very slowly and it still occurs even if I don't do 2 quick saves in succession:

```
Rebuilding...
Done in 63ms.

Rebuilding...
Done in 66ms.

Rebuilding...
Done in 65ms.
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/9mm/Code/test-app/app/layouts/application.html.erb~'
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:739:32)
    at Object.readFileSync (node:fs:453:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1025:36)
    at /snapshot/tailwindcss/lib/cli.js:687:42 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/9mm/Code/test-app/app/layouts/application.html.erb~'
}
```

### System configuration

**Rails version**: Rails 7.0.2.3

**Ruby version**: ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin19]

**Comment by pixeltrix** [comment]
@9mm the correct place for this issue in the future would be on [tailwindcss-rails][1] but the `tailwindcss:watch` command is just a wrapper around the `tailwindcss` tool being called with the `-w` option. In this case it looks like it's trying to compile vim backup files since the path ends in `~`. Looking at the [default config][2], it seems that it's including `./app/views/**/*` by default - if you're just using ERB templates you can tweak that to `./app/views/**/*.erb` and that should fix the issues you're seeing.

[1]: https://github.com/rails/tailwindcss-rails
[2]: https://github.com/rails/tailwindcss-rails/blob/4dddc6bbe1d66f2738ab94fb39f9bf2b90184bdf/lib/install/tailwind.config.js

**Comment by 9mm** [comment]
Very interesting... thank you
