### ISSUE TITLE
Abnormal query executes if ActiveRecord scope has OR clause.

### ISSUE THREAD

**Issue by oohyun15** [rails/rails#44737]
### Steps to reproduce

You can checkout this issue from [here](https://github.com/oohyun15/activerecord-scoping).

or

```ruby
class Post < ApplicationRecord
  has_many :comments

  scope :scope1, -> {
    left_joins(:comments)
    .where(status: 'open')
    .or(where(comments: { status: 'open' }))
  }

  scope :scope2, -> {
    left_joins(:comments)
    .where(status: 'open')
    .or(Comment.where(status: 'open'))
  }
end

class Comment < ApplicationRecord
  belongs_to :post
end
```

### Expected behavior

I confirmed that `scope1` and `scope2` are the same query.

```ruby
Post.scope1.to_sql
=> "SELECT `posts`.* FROM `posts` LEFT OUTER JOIN `comments` ON `comments`.`post_id` = `posts`.`id` WHERE (`posts`.`status` = 'open' OR `comments`.`status` = 'open')"

Post.scope2.to_sql
=> "SELECT `posts`.* FROM `posts` LEFT OUTER JOIN `comments` ON `comments`.`post_id` = `posts`.`id` WHERE (`posts`.`status` = 'open' OR `comments`.`status` = 'open')"

Post.scope1.to_sql == Post.scope2.to_sql
=> true
```

So, I expected same query even if there is another where clause in front of scope.

```ruby
Post.where(id: [1, 2, 3]).scope1.to_sql == Post.where(id: [1, 2, 3]).scope2.to_sql
...
```

### Actual behavior

Unlike my expectation, queries are not same if there is another where clause in front of scope.

```ruby
Post.where(id: [1, 2, 3]).scope1.to_sql
=> "SELECT `posts`.* FROM `posts` LEFT OUTER JOIN `comments` ON `comments`.`post_id` = `posts`.`id`" \
   "WHERE `posts`.`id` IN (1, 2, 3) AND (`posts`.`status` = 'open' OR `comments`.`status` = 'open')"

Post.where(id: [1, 2, 3]).scope2.to_sql
=> "SELECT `posts`.* FROM `posts` LEFT OUTER JOIN `comments` ON `comments`.`post_id` = `posts`.`id`" \
   "WHERE (`posts`.`id` IN (1, 2, 3) AND `posts`.`status` = 'open' OR `comments`.`status` = 'open')"

Post.where(id: [1, 2, 3]).scope1.to_sql == Post.where(id: [1, 2, 3]).scope2.to_sql
=> false
```

As you can see, bracket position is different. I wonder if this result was intended.

**note1**: if use `merge` method between where and `scope2`, result is same as `scope1`'s query.
```ruby
Post.where(id: [1, 2, 3]).scope1.to_sql == Post.where(id: [1, 2, 3]).merge(Post.scope2).to_sql
=> true
```
**note2**: if `scope2` calls before where clause, result is same as `scope1`'s query.
```ruby
Post.scope1.where(id: [1, 2, 3]).to_sql == Post.scope2.where(id: [1, 2, 3]).to_sql
=> true
```

### System configuration
**Rails version**: 7.0.2.3 (also 6.1.4.4)

**Ruby version**: 2.7.4

Thanks, rails.

**Comment by eypsrcnuygr** [comment]
I find this one is interesting and wondering, on your first note what is the result of this;

`Post.where(id: [1, 2, 3]).scope1.to_sql == Post.where(id: [1, 2, 3]).merge(Post.scope2, rewhere: true).to_sql`

Because from the [doc](https://edgeguides.rubyonrails.org/active_record_querying.html#merging-of-scopes), it says if you want to last where clause to win, use `merge`. It seems like this behavior comes into play.

Your two where chained queries somehow trigger a `rewhere:nil` and make the last where clause not to win. There is a merge method inside `active_record/lib/active_record/relation/where_clause.rb.`
It is an intended effect to run where clause again on a query and merge the result. This is the [PR](https://github.com/rails/rails/pull/39250).

So using a relational attribute and calling where on a Model have different `rewhere` options I guess. One is true the other is nil. @oohyun15
