### ISSUE TITLE
SQL query cache does not work when configured with multiple databases after code is loaded/reloaded in dev mode

### ISSUE THREAD

**Issue by evanlok** [rails/rails#44817]
### Steps to reproduce

1. Create an application that utilizes multiple database connections
2. Define a controller action that triggers duplicate SQL queries
3. Send a request to the controller action
4. Notice that no queries are cached
5. Modify source code
6. Send a request to the controller action
7. Notice that no queries are cached

```ruby
# Base model with multiple database connections
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to database: { writing: :primary, reading: :primary_replica }
end

# Model for testing
class Post < ApplicationRecord
end

class PostsController < ApplicationController
  def index
    8.times { Post.first }

    render plain: "Home"
  end
end

Rails.application.routes.draw do
  resources :posts

  root to: 'posts#index'
end
```

Database config with multiple databases
```yml
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: blog

development:
  primary:
    <<: *default

  primary_replica:
    <<: *default
```

### Expected behavior

SQL queries are cached on the first request to the action and after subsequent code reloads.

### Actual behavior

Query caching is not utilized for the first request after server boot and any request that occurs after a code reload. Caching does work after those initial uncached requests.

This is because the query cache is enabled at the start of the request on the existing connection pool. However, the `connect_to` method in base model triggers `establish_connection` which recreates the connection pool with query caching disabled. Since code is lazy loaded in development mode, the call to `connect_to` occurs after the code that enables query caching. Query caching works as expected with a single database because the connection pool is stored on `ActiveRecord::Base` and is never recreated since it's not an autoloaded constant.

### System configuration
**Rails version**: 6.1.5

**Ruby version**: 2.7.3

### Workaround

Enable query caching with middleware
```rb
class QueryCacheFix
  def initialize(app)
    @app = app
  end

  def call(env)
    ActiveRecord::Base.connection.enable_query_cache!
    @app.call(env)
  end
end

config.middleware.insert_after(ActionDispatch::Reloader, QueryCacheFix)
```

**Comment by eileencodes** [comment]
Thanks for opening this issue @evanlok.

I debugged this and determined this is a problem with lazy loading and multiple databases. If you turn on eager loading you'll see the queries are cached correctly on the first and subsequent requests. In production eager loading is on so your query cache will work fine there.

The reason this is happening for multiple databases and doesn't happen for a single db app is because the connection gets re-established in ApplicationRecord via connects_to. Even if we fixed this in development with lazy loading for ApplicationRecord, any other primary writer would have the same bug, because the connection isn't established until the model is loaded.

I'm going to close this because there's not a good way to fix this without creating a confusing experience for other databases and with eager loading on it's working correctly.
