### ISSUE TITLE
ActiveSupport::FileUpdateChecker dramatically slows down Rails 7 on WSL

### ISSUE THREAD

**Issue by spazer5** [rails/rails#44837]
### Steps to reproduce
- Install Ubuntu on WSL 2
- Install Ruby 3.1.1 via RVM
- Create a Rails 7 app with at least 100 classes (models or controllers, doesn't matter)
- Run `rails server` and observe high response latency for very simple requests.

### Your reproduction script goes here
```
class PingController < ApplicationController
  def index
     render json: { ok: true }
  end
end
```

### Behavior
By default, this simple action will produce over 400ms latency, even much higher on apps with a large amount of classes (more specifically watched paths by the Rails File Reloader).

### Cause
I ran `rbspy` and i tracked down the cause of 90% of latency. Is is `ActiveSupport::FileUpdateChecker` and specifically this section but more likely the entire approach on WSL:

```
block in max_mtime - /usr/share/rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/file_update_checker.rb:137
mtime [c function] - (unknown):0
```

As soon as i disabled it by switching to: `config.file_watcher = ActiveSupport::EventedFileUpdateChecker` and adding `gem 'listen'` as [mentioned here](https://stackoverflow.com/a/60134982), The latency immediately dropped from ~400ms to ~20ms.

However now the classes don't reload when i make changes.

Keep in mind this was tested on a speedy machine with an SSD drive so file seeking shouldn't be an issue.

**Comment by Earlopain** [comment]
Cross filesystem access with WSL2 is horribly slow which I think you are running into. Are your project files on your windows host instead of in wsl? https://docs.microsoft.com/en-us/windows/wsl/compare-versions#exceptions-for-using-wsl-1-rather-than-wsl-2 In that case you also won't recieve inotify events, which is why `EventedFileUpdateChecker` doesn't work https://github.com/microsoft/WSL/issues/4739

**Comment by spazer5** [comment]
@Earlopain Yes the files do reside on windows, not the wsl2 container.

**Comment by Earlopain** [comment]
It's unfortunate, but I don't think rails can do anything about it, since it's a inherit limitation of wsl. You can use something like [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) for example if you're using vscode (not sure if something similar exists for other editors) or access the filesystem with `\\wsl$` directly and move your files there.

**Comment by spazer5** [comment]
Thanks @Earlopain for the links, they're definitely helpful!

**Comment by linyiru** [comment]
@spazer5 I encountered exactly the same problem just like what you met, then I solved by adding the following line to `development.rb`

```ruby
config.file_watcher = ActiveSupport::EventedFileUpdateChecker
```

and it depends on `listen` gem according to Rails doc: https://guides.rubyonrails.org/configuring.html

P.S. the default value: `ActiveSupport::FileUpdateChecker`

**Comment by cannikin** [comment]
Thanks @linyiru I was seeing slow requests in a [devcontainer](https://code.visualstudio.com/docs/devcontainers/containers), pages that did no processing at all were taking ~250ms to render. I switched to `EventedFileUpdateChecker` and they dropped to <5ms!
