### ISSUE TITLE
Wrong error is show when an enum validation is misspell

### ISSUE THREAD

**Issue by TanZng** [rails/rails#44912]
### Steps to reproduce

1. Create a class with a enum and add a validation for the enum. Misspell the name of the enum in this example I wrote `in: parentesco_proveedores.keys` instead of the correct value `{ in: parentesco_proveedors.keys }`.

```ruby
class Seguro < ApplicationRecord
  enum parentesco_proveedor: { madre: "Madre", padre: "Padre"}, _prefix: true

  validates :parentesco_proveedor, inclusion: { in: parentesco_proveedores.keys }
end
```

2. Go to http://127.0.0.1:3000/ you will see the correct error, then refreh the page.
3. The error chage.

### Expected behavior

The error should be the same even after refesh
```
undefined local variable or method `parentesco_proveedores' for Seguro:Class
Did you mean?
parentesco_proveedors
...
```

### Actual behavior

At first the error is (what actually is happening)
```
undefined local variable or method `parentesco_proveedores' for Seguro:Class
Did you mean?
parentesco_proveedors
...
```

But when the site is refresh the error changes to:

```
You tried to define an enum named "parentesco_proveedor" on the model "Seguro", but this will generate a instance method "parentesco_proveedor_madre?", which is already defined by another enum.

```
If you keepo refreshing this error will continue showing and the one about the `undefined local ` will not show again

### System configuration
**Rails version**:
gem "rails", "~> 7.0.2", ">= 7.0.2.3"

**Ruby version**:
ruby "3.1.1"

**Comment by SkipKayhil** [comment]
I believe this is caused by the exception during the first autoload as described in a similar issue: https://github.com/rails/rails/issues/44842#issuecomment-1090850955. 

The summary is that because the model failed loading it ends up in a partially loaded state: the enum has already been defined and the second attempt to autoload the model tries to define it again leading to the conflicting enum error.

**Comment by gabo-cs** [comment]
> I believe this is caused by the exception during the first autoload as described in a similar issue: [#44842 (comment)](https://github.com/rails/rails/issues/44842#issuecomment-1090850955).
> 
> The summary is that because the model failed loading it ends up in a partially loaded state: the enum has already been defined and the second attempt to autoload the model tries to define it again leading to the conflicting enum error.

I don't think so, @SkipKayhil. I think this is just a language thing! _Proveedor_ is a Spanish word, and the plural is _Proveedores_, but Rails by default works with English plurals, that's why it's giving _Did you mean parentesco_proveedors_.

@TanZng Rails is not bilingual/polyglot if we don't tell it to be, however, even though you can work this out by making these settings in Rails, I'd suggest that you write everything in English even though your end users are Spanish speakers.

**Comment by gabo-cs** [comment]
> gain leading to the conflicting enum error.

So yeah, the second error seems related to the autoload issue, but in this case the first error (the plural thing) looks easily fixable and then the second error wouldn't show up anymore. So that should be the way go to! Unless I'm missing something.
