### ISSUE TITLE
I can not migrate from webpacker to esbuild 

### ISSUE THREAD

**Issue by dima4p** [rails/rails#45006]
### Steps to reproduce

My project is using sass, coffeescript, and vue.js. All works perfectly with `webpacker`. It was created with Rails6 and I have upgraded it to Rails7.
Since the `webpacker` is soft deprecated I am trying to migrate do `esbuild`. And there are problems.

1. There is no official guide how to do that. I have found some unofficial guides but none of them is 100% compatible with my project.
2. To get the assets compiled I have tried 4 or more guides until I got a single `.css` and `.js` files. OK, I've done it.
3. But it turned out, I can not receive `Source map` files. To get the source map for js I was requesting the same file adding to the end ".map". (See the line 398 in the atttached `.diff` file). Now it does not work. The code below is the failing attempt to get the source map file.
4. The same problem is with source map file for `css`. With both variants for `config.assets.debug`. With `true` value I see in the browser only one file `app.css`, and at the end there is two the magic comments `/*# sourceMappingURL=`. The first has no fingerprint, the second does, but requesting the file results in 404. With `false` value I see the list of all the files that are present in the project. But the content is available only for the `.css` that comes from vue.js. For all other files I see the following message
```
Error loading the readable source text: request failed with status 404
Address of the readable source text: <unknown>
```
5. I should mention that vue.js code does not work as well. 

```ruby
# Your reproduction script goes here
```

### System configuration
**Rails version**:
rails (7.0.2.3)
**Ruby version**:
ruby '3.1.1'

I need help!!!

[esbuild.diff](https://github.com/rails/rails/files/8604971/esbuild.txt)
[Gemfile](https://github.com/rails/rails/files/8604979/Gemfile.txt)

**Comment by la-ruby** [comment]
chrome inspector was showing my vue js source - I don't know if thats thanks to source maps or chrome nowadays understanding es6.
anyways this is [my steps](https://github.com/la-ruby/create-rails-app/blob/f3128cd/create-rails-app#L346-L354) and typical rails [setup](https://github.com/la-ruby/create-rails-app/blob/main/create-rails-app)

<img width="1307" alt="screenshot" src="https://user-images.githubusercontent.com/55279023/166328439-add59b47-5085-4bff-a050-6a4f9b3da49b.png">

btw [a question on SO](https://stackoverflow.com/questions/72074436/how-to-set-up-vue-js-with-rails-7-and-esbuild/72091739#72091739)

**Comment by dima4p** [comment]
> chrome inspector was showing my vue js source - I don't know if thats thanks to source maps or chrome nowadays understanding es6. anyways this is [my steps](https://github.com/la-ruby/create-rails-app/blob/f3128cd/create-rails-app#L346-L354) and typical rails [setup](https://github.com/la-ruby/create-rails-app/blob/main/create-rails-app)
> 
> <img alt="screenshot" width="1307" src="https://user-images.githubusercontent.com/55279023/166328439-add59b47-5085-4bff-a050-6a4f9b3da49b.png">
> 
> btw [a question on SO](https://stackoverflow.com/questions/72074436/how-to-set-up-vue-js-with-rails-7-and-esbuild/72091739#72091739)

Thanks but the problem is **not** how to _create_ a new project. The problem is how to _migrate_ from `webpacker` to `esbuild`. 

And till now I have jet the problem with `css`. With the `js` I even did not start considering them. Though, there is an `application.js` file with the code inside that is collected from my code.

**Comment by eileencodes** [comment]
Hi @dima4p, are you trying to migrate to [esbuild-rails](https://github.com/rails/esbuild-rails)? That repo is archived and is no longer supported by the Rails team. If you want to migrate to esbuild, you need to use [jsbundling-rails](https://github.com/rails/jsbundling-rails) which supports esbuild, webpacker, and rollup.

I think the easiest thing will be to follow this migration guide to migrate from webpacker to webpack on jsbundling here https://github.com/rails/jsbundling-rails/blob/main/docs/switch_from_webpacker.md and then switch to esbuild. Your other option is to switch to [shackapacker](https://github.com/shakacode/shakapacker), which is webpacker maintained and improved by the Shackacode team.

If you hit an issue with esbuild on jsbundling, you'll want to open an issue on https://github.com/rails/jsbundling-rails rather than here, because it doesn't sound like the problem lies in the code in this repo. Hope that helps!
