### ISSUE TITLE
ActiveRecord silently triggers a rollback when using return in the transaction block in Rails 7

### ISSUE THREAD

**Issue by majkelcc** [rails/rails#45017]
### Steps to reproduce

```ruby
require "bundler/inline"

RAILS_VERSION = "7.0.2.4"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", RAILS_VERSION
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :records, force: true do |t|
  end
end

class Record < ActiveRecord::Base
end

def transaction_with_return
  ActiveRecord::Base.transaction { return Record.create! }
end

def transaction_without_return
  ActiveRecord::Base.transaction { Record.create! }
end

class BugTest < Minitest::Test
  def setup
    Record.delete_all
  end

  def test_transaction_block_with_return
    transaction_with_return
    assert_equal 1, Record.count
  end

  def test_transaction_block_without_return
    transaction_without_return
    assert_equal 1, Record.count
  end
end

```

### Expected behavior

Since using `return` in the transaction block was deprecated in https://github.com/rails/rails/pull/29333, I would expect that ActiveRecord is not triggering a rollback silently.

### Actual behavior

ActiveRecord silently triggers a rollback when `return` is used in the transaction block.

### System configuration
**Rails version**: 7.0

**Ruby version**: 3.0

**Comment by majkelcc** [comment]
Reading discussion in that topic I thought it was agreed that Rails 7 was supposed to throw an exception in this case (https://github.com/rails/rails/pull/29333#issuecomment-305941090 and https://github.com/rails/rails/pull/29333#issuecomment-305959285).

**Comment by majkelcc** [comment]
@matthewd wrote there also that:

> silently rolling back on a non-error return is also a hugely surprising behaviour

And indeed, it was a nasty thing to discover 😬

**Comment by majkelcc** [comment]
This is the commit with the actual rollback: https://github.com/rails/rails/commit/15aa4200e083e0229553ddb53b7280cc12ccbf92#diff-dd0ea9dfea1fd486f2b1b5eac8c798f839467173a1c2315d3ad04f4098f7dda3R342.

**Comment by dylanahsmith** [comment]
Well, https://github.com/rails/rails/pull/29333 was more about not **committing** the transaction silently, especially from an edge case like Timeout.timeout, since committing a partial transaction can invalidate invariants that are trying to be preserved and lead to a need to handle this new undesirable state going forward.

The original intention of that deprecation was that it would raise as well as rollback, but it looks like the deprecation warning was changed in https://github.com/rails/rails/pull/39453 to remove the mention of raising, out of concern for changing the the timeout exception.  Again, this would be a surprising and unexpected change that is likely to not get caught during testing.

If we could have this behaviour targeted at the timeout case, then it would be better to deprecate the use of `Timeout.timeout` without providing an exception class, since providing an exception class will let it be handled like any other exception that aborts the transaction.  Unfortunately, we need to have the same behaviour for `return`, `break` or `throw`, so there is the question of what semantics make sense for them going forward (aside from just the deprecation period).

Those keywords actually do introduce a normally unexpected effect when called in blocks, since they semantically skip over the remaining code in the method that yields to that block.  E.g. if there wasn't a need for code to handle the error case, then a method yielding to a block would typically look something like this

```ruby
def with_something
  prepare
  yield
  on_success
end
```

any `return`, `break` or `throw` would skip the `on_success` code.  Skipping over the `on_success` code also seems quite reasonable when the block calls `break` and `throw`.  It may not seem like the obvious behaviour for `return`, but perhaps it is a safe assumption to make in general to think of `return` as aborting the method yielding to the block.  It might be desirable to discourage the use of `return` in this way for transactions to keep the code clearer, but that would also affect the use of `break` which seems like a reasonable way to abort a transaction from within the transaction block.

I think I had expected that existing rails developers would discover this problem in existing code through the deprecation warning to avoid a nasty surprise.  It also seems like this behaviour is easier to discover for the `break` or `return` case since those are done explicitly in the method under test, compared to `throw` and `catch` that can be done implicitly from code far removed from transactional unit of code.

**Comment by majkelcc** [comment]
@dylanahsmith thanks for the context!

> I think I had expected that existing rails developers would discover this problem in existing code through the deprecation warning to avoid a nasty surprise.

I'm worried about my future kids learning Rails and writing perfectly looking Ruby code just to learn _the hard way_ that `return` is sometimes a nono! Jokes aside, I think that no one expected that the deprecation will turn into silent rollbacks.

This is a very controversial change, pretty much everyone taking part in the discussion on the deprecation PR raised some concerns about the potential consequences of this change. The only thing that was making it easier to swallow was the promise of making it clear to the user by throwing an exception after the rollback.

**Comment by joevandyk** [comment]
Thoughts on how to get this resolved? Seems sorta dangerous.

**Comment by lesliev** [comment]
Please could we just have a log message that says:
`ROLLBACK triggered because of return statement in transaction block` ?

This will give someone something to Google. I just spent a day dismantling a model, trying to find the cause of the silent rollback - taking out every association, every validation, every callback, whittling down all the code in the transaction, only to finally discover that it was `return true` that was the cause of it all.

**Comment by pre** [comment]
Came here to say that I spent some hours debugging why a transaction was silently rolled back even though everything worked perfectly (including tests) before upgrading to Rails 7.

**Comment by joevandyk** [comment]
Is there a recommended way to patch Rails to disable this behavior?

**Comment by dmarcoux** [comment]
I'm also hitting this while upgrading to Rails 7. I really wonder how I should handle this... Any idea?

**Comment by lesliev** [comment]
> Is there a recommended way to patch Rails to disable this behavior? We are blocked on upgrading to 7 because of this.

Can you refactor your code so that instead of returning from within the transaction block you set a variable and then return outside of the block? That's what I had to do.

**Comment by lesliev** [comment]
@zzak yes this is intended behaviour, but we are suggesting improvements, since the behaviour is surprising.

One suggestion is to raise an exception instead of quietly rolling back the transaction:
https://github.com/rails/rails/issues/45017#issuecomment-1118134642

Another suggestion is to add a log message so at least someone can come to understand why the rollback happened, without spending a day removing all other code from a block and eventually, somehow, finding their way to this page:
https://github.com/rails/rails/issues/45017#issuecomment-1216158244

Right now, all you see in the log is ROLLBACK. There's no way to know why the rollback happened.

I like the second option more because I think an exception will be difficult to suppress if the early-return rollback is desired.

**Comment by eric-christian** [comment]
I just had a moment of great confusion with this new behavior.

Not only is rolling back a transaction on a non erroneous condition very surprising, it does so silently. 😮
This goes against the "Principle of least astonishment".

And the cause for this change or "workaround" is also questionable. The problem with `Timeout.timout` sounds like something that could have been patched within `Timeout`. 

I don't like it.

**Comment by bughit** [comment]
@jeremyevans [wrote](https://bugs.ruby-lang.org/issues/15567#note-20): 

> I think that non-local, non-exception exits should commit the transaction, and only exceptions should roll the transaction back. Changing the behavior just because of Timeout's design (even if Timeout is not used) seems to be a mistake to me. I certainly have a lot of code that uses throw to exit transactions and expects the transaction will be committed. Sinatra and Roda both use throw for returning responses to web requests

That makes sense. Timeout is an error and externally it doesn't pretend otherwise but implements unwinding internally via a non-error mechanism (throw). That seems to be the flaw, not the original rails transaction behavior. Timeout unwinding should probably be done via a low level exception (below StandardError). There's already an understanding in ruby that you shouldn't be swallowing or recovering from those, in a general fashion (`rescue Exception => e`).

The current transaction behavior is surprising, incoherent and undocumented. For years everyone knew that you aborted transactions with exceptions and only exceptions. So when people intentionally used early exists they obviously weren't trying to abort.

Does it really make sense that an early transaction block exit via next, commits, but an early block (and method) exit via return, rolls back? What is the fundamental difference that they should do the opposite?

**Comment by nikonoid** [comment]
I was caught out by this today. I would wholeheartedly agree that this is not expected behaviour and I spend a good deal of time reverse engineering the cause.

**Comment by majkelcc** [comment]
How can we bring more attention to this issue? People are losing their data and spend many hours trying to figure out what is happening. Maybe even we could learn something from it to avoid adding more sharp edges to Rails in the future. The series of events that led to this change getting merged is very unfortunate.

**Comment by pre** [comment]
@dhh what’s your take on sharp edges in Rails?

**Comment by majkelcc** [comment]
I remember when Rails finally stopped swallowing exceptions in the `after_commit` callback, it's strange seeing things like this coming back.

**Comment by byroot** [comment]
This issue was discussed again recently. Unfortunately we're stuck between a rock and a hard place, and we have to chose between a bad solution and a worse solution.

For those who maybe don't fully understand the problem, we can't make the difference between the `transaction` block being exited because of a `return` and `Timeout.timeout` firing. This is because since Ruby 2.1, `Timeout.timeout` no longer `raise` an exception, but it `throw` it https://github.com/ruby/ruby/commit/1a3bcf103c582b20e9ea70dfed0ee68b24243f55

So we had only two choices:

  - `ROLLBACK` the transaction on `return` (clearly not great)
  - `COMMIT` the transaction on `timeout` (absolutely terrible).

Initially the plan was to raise an error on such case, to make the problem more visible to users, but that means breaking `Timeout.timeout` which isn't good either.

There are some discussion going on upstream in ruby/timeout and the Ruby bug tracker about some possible changes and new features in Ruby to solve this issue in the future, but this won't happen fast, and until then there is no better solution we can see.

Neither of us are happy we had to make this change, and we hear your frustration, but there really isn't much we can do about it.

**Comment by majkelcc** [comment]
Help me understand - isn't a solution to the `Timeout` problem simply passing a second argument?

**Comment by majkelcc** [comment]
@matthewd it's problematic that there is no trace of any discussion on removing the exception from the initial PR. Unless I missed it?

> we're not the ones calling Timeout: user/app code is.

Why not warn users about the dangers of using Timeout (without the second argument) then? One day the issue with Timeout will hopefully be gone, but Rails will be stuck with silent rollbacks?

**Comment by bughit** [comment]
Couldn't both old and new behavior be supported via an option to `transaction` with the default coming from Rails.config?

**Comment by byroot** [comment]
> isn't a solution to the `Timeout` problem simply passing a second argument?

No, that doesn't change anything to the problem.

`Timeout.timeout` uses `throw / catch` regardless of the error class: https://github.com/ruby/timeout/blob/cae26ed02b8f6dd34a84b04c7c71a844e5a87d48/lib/timeout.rb#L44

It's only after the `catch` that it does raise the exception.

> Why not warn users about the dangers of using Timeout 

We can't reasonably detect `Timeout.timeout` has been used, that's the problem.

> One day the issue with Timeout will hopefully be gone, but Rails will be stuck with silent rollbacks?

Absolutely not. We're tracking and are participating on the issue with upstream. The second there is a way to solve this problem that will be integrated in Rails.

Again, I understand everyone frustration, but we've spent quite a lot of time on this, we welcome new ideas but please don't assume we just don't care or are idiots.

**Comment by jeremyevans** [comment]
> > isn't a solution to the `Timeout` problem simply passing a second argument?
> 
> No, that doesn't change anything to the problem.
> 
> `Timeout.timeout` uses `throw / catch` regardless of the error class: https://github.com/ruby/timeout/blob/cae26ed02b8f6dd34a84b04c7c71a844e5a87d48/lib/timeout.rb#L44

That code is only called if a second argument is not provided.  See https://github.com/ruby/timeout/blob/cae26ed02b8f6dd34a84b04c7c71a844e5a87d48/lib/timeout.rb#L195

**Comment by byroot** [comment]
> That code is only called if a second argument is not provided.

My bad, I misremembered the code.

**Comment by bughit** [comment]
There is one issue with the current implementation of using a custom exception in Timeout. The same exception class is used for internal (inside the timeout block) unwinding and external (outside the timeout block) raising. But internal and external needs are different.

For internal unwinding a low level `InternalTimeoutError < Exception` should be used to discourage inadvertent timeout handling/swallowing. For external raising it should be a `StandardError`, like the current `Timeot::Error`.

**Comment by majkelcc** [comment]
Serious question - if we're assuming that users can be educated not to use `return` in transactions, why instead of that not educate users on how to use Timeout properly? That way we would avoid any harmful changes to Rails.

It's baffling that there is already a rule in Rubocop warning against using `return` in transactions, but there is no warning on using Timeout.

**Comment by byroot** [comment]
Because non-local returns are directly inside the `transaction` block, it's a local issue.

`Timeout.timeout` may be anywhere in the stack, it may even be in a middleware from a gem or something you haven't audited yourself.

Whether we like it or not, `Timeout.timeout` is a reality, we have no choice but to handle it.

**Comment by majkelcc** [comment]
> Timeout.timeout may be anywhere in the stack, it may even be in a middleware from a gem or something you haven't audited yourself.

In the same way, there might be a return in a transaction block in a gem I didn't audit, no?

If it's ok to expect that everyone now will be auditing their codebases in search of returns, why not tell users to fix their Timeout usages?

**Comment by byroot** [comment]
> In the same way, there might be a return in a transaction block in a gem I didn't audit, no?

No, it's not the same way.

In such case the issue is fully in the gem, it's for the gem to fix.

With timeout, it's two totally different parts of the code interacting badly, it's much harder to track down.

> why not tell users to fix their Timeout usages?

Again, the information about why `Timeout.timeout` shouldn't be used is a dime a dozen, but it's still everywhere. You can educate people as much as you want, it won't ever eliminate a problem.

This is about what the safest behavior is, and as bad as rolling back a transaction may be, it will always be less bad than committing an interrupted transaction.

I don't think this discussion add any more value now. As I said I understand everyone frustration, but I think it's pointless discussing this further until something changes upstream.

**Comment by majkelcc** [comment]
> This is about what the safest behavior is, and as bad as rolling back a transaction may be, it will always be less bad than committing an interrupted transaction.

Both are bad, I wouldn't be going as far as to say that one is **always** better than another. Depending on the application, one could be far better with a small inconsistency in their database than with data loss.

Can we at least gain control over whether the exception should be raised or not in our codebases? This is the biggest source of controversy and could help eliminate the element of surprise.

**Comment by akostadinov** [comment]
If I understand correctly, the general opinion is that `return` should not cause rollback. But because we can't distinguish it from a `throw`, we opt to handle it as any other `throw`. I think that it is much better for a proper distinction to be made even if this requires a language feature, than this silent surprise behavior in Rails 7. But I guess presented current situation, everybody safes themselves as they can :(

**Comment by jeremyevans** [comment]
> I think it's pointless discussing this further until something changes upstream.

Something changed upstream, as https://github.com/ruby/timeout/pull/30 was merged : https://github.com/ruby/timeout/commit/f16545abe68b908f91074086c3166b4dffc57802

**Comment by byroot** [comment]
> [ruby/timeout#30](https://github.com/ruby/timeout/pull/30) was merged

Yes, now if a 0.4.0 release do happen, we can consider added a dependency on `timeout >= 0.4.0` and change the behavior.

I want to stress the "consider", as adding a new dependency in a patch level release isn't something we normally allow ourselves to do, and this could have knock-on effect on user code (because `Timeout.timeout` would now be rescuable).

**Comment by jeremyevans** [comment]
> Yes, now if a 0.4.0 release do happen, we can consider added a dependency on `timeout >= 0.4.0` and change the behavior.

timeout 0.4.0 was released today: https://rubygems.org/gems/timeout/versions/0.4.0

**Comment by mohamedhafez** [comment]
> we can consider added a dependency on timeout >= 0.4.0 and change the behavior.

Granted people complaining on this issue might not be a representative sample of Rails devs, but I think there's at least a lot of us that feel that this was a big enough of a step backwards that it would merit a return to the old behavior in Rails 7.1 at least, if it would be too big of a change for a patch level release. Perhaps there's some way to poll the Rails community to see how many would be for or against something like that?

(Don't get me wrong, I understand that you guys were stuck between a rock and a hard place with the Timeout throw behavior and am not trying to knock you all for the route you chose, I understanding the reasoning and appreciate the engagement with the community about it here!)

**Comment by plusor** [comment]
FBI WARNING!!!

**Comment by ozydingo** [comment]
I see this has headed in an excellent direction in rails 7.1, thanks all for the work! I'm chiming in mostly because I don't see mention of `with_lock` here and I believe that's a very common use case that folks will have that leads them to this blocker for upgrading to Rails 7.0, as I am currently doing. IOW I'm doing it for the SEO of this thread :-D

For example, our code base has a lot of methods such as

```rb
    def reserve(job, user, duration: DEFAULT_RESERVATION_DURATION)
      job.with_lock do
        return { success: false, error: ALREADY_RESERVED } if job.reserved_for_any_user?
        return { success: false, error: INVALID_STATE } if !job.available? && !job.holding?

        job.update!(reserved: true, reserved_for_user_id: user&.id, reserved_until: duration.from_now)
        return { success: true }
      end
    end

```

Yes, in this case, the solution is a simply refactor to take the final `return` out of the block, at the slight cost of stylistic parallelism to the `return` statements. Nevertheless, doing so across the entire application, carefully considering if there are any other early returns after writes or other nested `throw`s is quite a lift for a large project! This is doubly surprising as this is not called out as a breaking change (AFAICT)

In our case, we are working around this until we upgrade to 7.1 by monkey-patching the implementation of `within_new_transaction` by simply copying the 6.1.8 implementation but removing the latter condition from

```rb
  elsif Thread.current.status == "aborting" || (!completed && transaction.written)
```

**Comment by groue** [comment]
Hello, I'm glad I found this page because I was banging my head about the cause of this ROLLBACK without any error visible anywhere. 🤯
