### ISSUE TITLE
[Doc] "Getting Started" - the status select is incorrect

### ISSUE THREAD

**Issue by duzenko** [rails/rails#45028]
### Steps to reproduce
Following the Getting started guide, progress to status select section

### Expected behavior
The status select should match the DB value (nil - empty)

### Actual behavior
The status select is hardcoded to show 'public'

### System configuration
**Rails version**: Rails 7.0.2.4

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [i386-mingw32]

**Comment by SkipKayhil** [comment]
Hey @duzenko, I think the select is working as intended.

After generating the migration to add the status column, the next step in the guide is adding a validation to the new column to ensure it isn't saved as nil:
```
class Article < ApplicationRecord
  # ...snip

  VALID_STATUSES = ['public', 'private', 'archived']

  validates :status, inclusion: { in: VALID_STATUSES }

  def archived?
    status == 'archived'
  end
end
```

So because of that, there shouldn't be a situation where the select should have to display a nil status. 

Since this doesn't appear to be a bug, I'm going to close this since we reserve the issue tracker for bugs only. If you have any other issues with the Getting Started guide, I would highly recommend asking on the [rubyonrails forum](https://discuss.rubyonrails.org/c/rubyonrails-talk/7) or [Stack Overflow](https://stackoverflow.com/questions/tagged/ruby-on-rails).

**Comment by duzenko** [comment]
The existing DB records have status = nil after migration. I'm talking about editing/displaying those existing records.

**Comment by SkipKayhil** [comment]
Yeah that's fair point. Maybe its worth adding an extra step about creating a migration to backfill the statuses of existing records? Definitely feel free to open a PR with any changes you think would make it better.
