### ISSUE TITLE
Incorrect SQL creation for numbers

### ISSUE THREAD

**Issue by walterhorstman** [rails/rails#45046]
### Steps to reproduce
Enter in the console.

```ruby
Item.where('amount > ?', 3).to_sql
```

### Expected behavior
SELECT `items`.* FROM `items` WHERE (amount > 3)

### Actual behavior
SELECT `items`.* FROM `items` WHERE (amount > '3')

The comparison value for amount should not have been quoted. I've found this while migrating a Rails 4.2 application to 7.0. In Rails 4.2 this does not happen.

### System configuration
**Rails version**: 7.0.2.4

**Ruby version**: 3.1.2p20

**Comment by eileencodes** [comment]
Hi @walterhorstman, there's not quite enough information here for us to determine if this is a bug or intentional behavior. We need more information.

1) What version of Rails did this change in? Rails 4.2 support ended 5 years ago which is a pretty long time ago, if this changed in 6.1 to 7.0 it would be easier to bisect, but without knowing which version it's almost impossible to track down the change. If you can use the provided [bug report templates](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb) to make a script that reproduces the behavior and run it against different versions of Rails to find which one it changed in, that would be helpful.
2) What change in behavior is this causing in your app? I tested it in a demo app and it doesn't throw an exception, so it looks like active record can handle the serialization fine.

**Comment by nvasilevski** [comment]
I think that was introduced as a security fix and it sounds like that currently it works as intended even though it's a bit unfortunate
a bit more context and some workarounds here - https://github.com/rails/rails/issues/44312#issuecomment-1030809850

**Comment by walterhorstman** [comment]
@eileencodes I've seen the bug report templates, but am in such time pressure, that I don't have the time to investigate further right now, so whenever the time's there that I really need to fix this, I will look into it. I hoped this information was enough for now.

Conceptually I think this behavior is incorrect because comparisons between numbers will fail in some cases. I think if amount is 13 and the comparison value is 2, it should return a record, but it won't if I'm not mistaken because the string "13" is not greater than "2".

**Comment by byroot** [comment]
@nvasilevski is right this is a duplicate of https://github.com/rails/rails/issues/44312#issuecomment-1030809850.

@walterhorstman I'll close as duplicate, please read the rationale and proposed workarounds there.

I'm really sorry it breaks your use case, unfortunately the alternative is to open the door to some really nasty security vulnerabilities. Until MySQL offer some other way to disable this automatic casting, I'm afraid we'll have to continue to cast integers as strings in this context.
