### ISSUE TITLE
Inconsistency between Cache #increment behaviors

### ISSUE THREAD

**Issue by alan-pie** [rails/rails#45069]
### Steps to reproduce
1. Set cache to :memory_store
2. Call `#increment('key')` where 'key' does not already exist

### Expected behavior
`#increment` returns 1 for a key that does not already exist

### Actual behavior
`:memory_store` and `:file_store` return nil and do nothing, `:redis_cache_store` and `:mem_cache_store` return 1.

Technically this discrepancy is documented in the implementations and the tests `CacheIncrementDecrementBehavior`, but it is not desirable. It prevents me from using `:memory_store` in my tests and `:redis_cache_store` in other environments. I want to use `:memory_store` in the tests because I want to use the TimeHelpers. If we have to be backwards compatible here can we at least implement an option on Memory store to initialize the increment operations the same way Redis and Memcache do? I'm happy to provide a PR if that strategy will work.

### System configuration
**Rails version**:
Rails 7

**Ruby version**:
2.7.6

**Comment by byroot** [comment]
At first sight I'd say it's a bug and that `memory_store` and `file_store` should be modified to start from 1 like `mem_cache_store` and `redis_store`.

That being said there might be a good reason for this, so I think the first step should be to find the commits that either introduced this difference or the one that codified it in the test suite. If we don't find any indication that this discrepancy was deliberate, then I'm in favor of fixing it, because to me it's a bug.

**Comment by alan-pie** [comment]
The test and the discrepancy for RedisCacheStore was added here: 9f8ec3535247ac41a9c92e84ddc7a3b771bc318b.

No discussion of it in #31134 that I can see. Nothing is specified for the behavior on the `Cache#increment` method either.

**Comment by byroot** [comment]
Thanks for doing the spelunking. 👍 to have them all handle a missing key as `0`.

**Comment by alan-pie** [comment]
Related PR #45068

**Comment by skipkayhil** [comment]
I believe this was fixed by #45068, but feel free to ping me if I'm misunderstanding and I can re-open
