### ISSUE TITLE
QueryCacheTest#test_query_cache_does_not_allow_sql_key_mutation fails

### ISSUE THREAD

**Issue by yahonda** [rails/rails#45108]
Managed to reproduce https://buildkite.com/rails/rails/builds/86503#8b66cfc1-cbec-4331-a5ce-5fbac2a37ee8/1053-1064

### Steps to reproduce
```
$ cd activerecord
$ ARCONN=postgresql bin/test test/cases/adapters/postgresql/composite_test.rb test/cases/query_cache_test.rb  -n "/^(?:PostgresqlCompositeWithCustomOIDTest#(?:test_column)|QueryCacheTest#(?:test_query_cache_does_not_allow_sql_key_mutation))$/" --seed 50299
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ cd activerecord
$ ARCONN=postgresql bin/test test/cases/adapters/postgresql/composite_test.rb test/cases/query_cache_test.rb  -n "/^(?:PostgresqlCompositeWithCustomOIDTest#(?:test_column)|QueryCacheTest#(?:test_query_cache_does_not_allow_sql_key_mutation))$/" --seed 50299
Using postgresql
Run options: -n "/^(?:PostgresqlCompositeWithCustomOIDTest#(?:test_column)|QueryCacheTest#(?:test_query_cache_does_not_allow_sql_key_mutation))$/" --seed 50299

# Running:

.F

Failure:
QueryCacheTest#test_query_cache_does_not_allow_sql_key_mutation [/home/yahonda/src/github.com/rails/rails/activerecord/test/cases/query_cache_test.rb:395]:
0 instead of 1 queries were executed..
Expected: 1
  Actual: 0


bin/test test/cases/query_cache_test.rb:389



Finished in 0.096603s, 20.7033 runs/s, 72.4617 assertions/s.
2 runs, 7 assertions, 1 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by casperisfine** [comment]
Thanks, I'll merge it later today.

Also I realize It's not necessarily clear what the source of the failure is. So for the record, as @yahonda pointed that `"SHOW search_path"` is memoized, so normally it wouldn't be triggered as part of this test.

But `PostgresqlCompositeWithCustomOIDTest` reset the connection, clearing that memoized state. So when it run right before, the first query the subscriber hit is `query_value("SHOW search_path", "SCHEMA")`.

And since `SCHEMA` queries are ignored by `assert_queries`, it causes this mismatch.
