### ISSUE TITLE
`minitest` is a runtime dependency of `activesupport`

### ISSUE THREAD

**Issue by pirj** [rails/rails#45182]
### Steps to reproduce

I've noticed `minitest` in a project's `Gemfile.lock`, while the project exclusively uses RSpec.
It turns out that [`minitest` is a runtime dependency of `activesupport`](https://github.com/rails/rails/blob/4d5a570cfe1890f71a1d198a5fe40d528f2b60d4/activesupport/activesupport.gemspec#L40).
Other Rails gems don't seem to specify `minitest` at all, e.g. [`activerecord`](https://github.com/rails/rails/blob/4d5a570cfe1890f71a1d198a5fe40d528f2b60d4/activerecord/activerecord.gemspec#L38), [`activejob`](https://github.com/rails/rails/blob/4d5a570cfe1890f71a1d198a5fe40d528f2b60d4/activejob/activejob.gemspec#L35).

It's not a big deal, but shaving off 150KB of code from each deployment is a nice bonus.

I can track this down to [this commit](https://github.com/rails/rails/commit/6f74d36c4263a6cbbc6dc32a03edeed04faefbd9) that moved `minitest` from the `Gemfile` (development only) to `gemspec`.
`add_development_dependency` was introduced a couple of years before this commit, [in `rubygems` 1.2](https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#120--2008-06-21) but probably Rails couldn't rely on a wider adoption. Now, nearly a decade later, this should be possible.

I'll be happy to work on a PR for that.

### Expected behavior

1. `minitest` is a development dependency
2. `minitest` is explicitly specified as a development dependency for each Rails gem

### Actual behavior

`minitest` is bundled along with the application code for production deployment

### System configuration

**Rails version**: 6.0.5 (4.0.0 up to latest 7.0)

**Ruby version**: any

**Comment by skipkayhil** [comment]
Hey @pirj, thanks for the report. Minitest is actually a runtime dependency of the testing feature of Active Support, you can see it being required in a few places:

https://github.com/rails/rails/blob/4d5a570cfe1890f71a1d198a5fe40d528f2b60d4/activesupport/lib/active_support/test_case.rb#L3-L4
https://github.com/rails/rails/blob/4d5a570cfe1890f71a1d198a5fe40d528f2b60d4/activesupport/lib/active_support/testing/method_call_assertions.rb#L3
https://github.com/rails/rails/blob/4d5a570cfe1890f71a1d198a5fe40d528f2b60d4/activesupport/lib/active_support/testing/autorun.rb#L3-L7

so running `bin/rails test` in an application would error if Minitest wasn't a runtime dependency.

That being said, I think it would be cool if Minitest wasn't required by default and was added to Gemfiles instead (and load errors may have to be handled a little better). 

Since this is more of a feature request than a bugfix, I'm going to have to close this as we reserve the issue tracker for bugs only. 
However, since I do think this is a good idea, would you be interested in creating a PR? That would be a more appropriate place to discuss features

**Comment by bethesque** [comment]
I'd be really keen to have the minitest dependency as optional. It's causing some dependency issues in my project.

**Comment by ndbroadbent** [comment]
I was just looking through all my dependencies in `Gemfile.lock` and was also surprised to see minitest in here, since I only use RSpec. I might be wrong, but I don't believe I use any of these testing features in ActiveSupport.
