### ISSUE TITLE
Problems with URL generation

### ISSUE THREAD

**Issue by alec-c4** [rails/rails#45331]
Hey!
In my rails7 application, I have following code:

routes.rb
```ruby
    resources :animals, controller: "customer/animals"  do
      resources :animal_documents, as: :documents,
                controller: "customer/animal_documents", except: :show, shallow: true
    end
```

app/views/customer/animal_documents/_form.html.erb
```ruby
<%= simple_form_for(@animal_document) do |f| %>
  <div class="form-inputs">
    <%= f.input :attachment %>
  </div>

  <div class="form-actions mt-3">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>
```

When i create a resource - everything works fine, but when i try to edit resource - I see following error

```
undefined method `animal_document_path' for #<ActionView::Base:0x000000001445d8>

              recipient.public_send(method, *args, options)
                       ^^^^^^^^^^^^
Did you mean?  animal_documents_path
               animal_documents_url
```

My routes looks like

```
                        animal_documents GET      /animals/:animal_id/animal_documents(.:format)                                                    customer/animal_documents#index
                                         POST     /animals/:animal_id/animal_documents(.:format)                                                    customer/animal_documents#create
                     new_animal_document GET      /animals/:animal_id/animal_documents/new(.:format)                                                customer/animal_documents#new
                           edit_document GET      /animal_documents/:id/edit(.:format)                                                              customer/animal_documents#edit
                                document PATCH    /animal_documents/:id(.:format)                                                                   customer/animal_documents#update
                                         PUT      /animal_documents/:id(.:format)                                                                   customer/animal_documents#update
                                         DELETE   /animal_documents/:id(.:format)                                                                   customer/animal_documents#destroy
```

```
>> url_for @animal_document

NoMethodError: undefined method `animal_document_path' for #<ActionView::Base:0x000000001445d8>

              target.public_send(method, *args)
                    ^^^^^^^^^^^^
Did you mean?  animal_documents_path
               animal_documents_url
```

How to fix url generation? It looks like url_for does not take into account the presence of `as:`

**Comment by skipkayhil** [comment]
Isn't `animal_document_path` undefined because you have `except: :show` in your route definition?

It's going to be hard to give much more help without more information though, do you have a sample repository where you can reproduce these issues?

**Comment by alec-c4** [comment]
It isn't public repo, sorry. But if I remove `except: :show` - nothing changes.

**Comment by skipkayhil** [comment]
> It isn't public repo, sorry.

Right, can you make a public sample repo of a Rails application with just enough code to demonstrate the issue?

**Comment by alec-c4** [comment]
@skipkayhil I've created something similar - https://github.com/alec-c4/routes_problem_demo

**Comment by phendrick** [comment]
@alec-c4 I think you'll need to specify the url to use by passing `url: documents_path` into the `simple_form_for` call. 

I might be wrong but I dont think the url helper looks up the path for a model; it'll always use the generated route key.

**Comment by alec-c4** [comment]
@phendrick yep, I know, but it looks like a workaround :( from my point of view it would be better if you need not specify extra parameters and url_for will check routes to create correct url

**Comment by skipkayhil** [comment]
Thanks for the repo, that definitely helped me to understand! As phendrick said above, I think in this situation you need to specify the url yourself. I agree it would be cool if it could just figure out `as:` renames, but I think trying to infer anything more complicated than the most basic mapping of `ThingSubroute` to `thing_subroutes_path` would be quite difficult. Taking an example from the [routing guide](https://edgeguides.rubyonrails.org/routing.html#prefixing-the-named-route-helpers):

```ruby
scope 'admin' do
  resources :photos, as: 'admin_photos'
end

resources :photos
```

What url should `form_for(Photo.new)` resolve to here? I think there would be too many edge cases to try to figure out and it makes sense to only handle the basic case and let people specify `admin_photos_path(Photo.new)` for anything more complex.

I'm going to close this issue since it sounds like there aren't any bugs and we reserve the issue tracker for bugs only. If you need additional help I recommend heading to the [rubyonrails forum](https://discuss.rubyonrails.org/c/rubyonrails-talk/7) or [Stack Overflow](https://stackoverflow.com/questions/tagged/ruby-on-rails), where a wider community can help you.
