### ISSUE TITLE
Rails 7.0.3 vs Rails 6.1.4.4 regression when using shards in production

### ISSUE THREAD

**Issue by net1957** [rails/rails#45390]
### Steps to reproduce

```ruby
# I'm using sharding for some models.
module Cmdmary
  # base class for AR
  class CmdmaryRecord < ApplicationRecord
    self.abstract_class = true

    connects_to shards: {
      fr: { writing: :comdev_fr },
      de: { writing: :comdev_de }
    }
  end
end

database.yml contain:
default: &default
  adapter: oracle_enhanced
  pool: 5
  timeout: 5000
development:
  primary:
    <<: *default
    database: sk-oracle11.sk.loc/XE
    username: xx
    password: xx
  comdev_fr:
    <<: *default
    migrations_paths: db/migrate_none
    database: sk-oracle11.sk.loc/XE
    username: xx
    password: xx
  comdev_de:
    <<: *default
    migrations_paths: db/migrate_none
    database: sk-oracle11.sk.loc/XE
    username: xx
    password: xx
production:
  primary:
    <<: *default
    database: sk-oracle11.sk.loc/XE
    username: xx
    password: xx
  comdev_fr:
    <<: *default
    migrations_paths: db/migrate_none
    database: sk-oracle11.sk.loc/XE
    username: xx
    password: xx
  comdev_de:
    <<: *default
    migrations_paths: db/migrate_none
    database: sk-oracle11.sk.loc/XE
    username: xx
    password: xx

in the controller the connection is managed by:
        def handle_tenant
          ::Cmdmary::CmdmaryRecord.connected_to(shard: api_params[:tenant].to_sym, role: :writing) do
            Rails.logger.warn { "Tenant used:'#{api_params[:tenant]}', api:'#{api}'" }
            yield
          end
        end
      around_action :handle_tenant
```

### Expected behavior
in rails 7.0.3 Rails should boot without error in production mode

### Actual behavior
the rails server crash with:
````
SECRET_KEY_BASE=xx DEVISE_SECRET_KEY=xx RAILS_SERVE_STATIC_FILES=1 bundle exec rails server -b 0.0.0.0 -e production --log-to-stdout
=> Booting Puma
=> Rails 7.0.3 application starting in production
=> Run `bin/rails server --help` for more startup options
Exiting
/home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/connection_handling.rb:309:in `connection_pool': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/connection_handling.rb:305:in `connection_db_config'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/type.rb:50:in `adapter_name_from'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/attributes.rb:216:in `attribute'
        from /var/www/dbpresenter-test/html/app/models/cmdmary/etudprix.rb:11:in `<class:Etudprix>'
        from /var/www/dbpresenter-test/html/app/models/cmdmary/etudprix.rb:5:in `<module:Cmdmary>'
        from /var/www/dbpresenter-test/html/app/models/cmdmary/etudprix.rb:3:in `<main>'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:239:in `block (2 levels) in eager_load'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `ls'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:234:in `block in eager_load'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `synchronize'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `eager_load'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:318:in `each'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:318:in `eager_load_all'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `run'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/application.rb:372:in `initialize!'
        from /var/www/dbpresenter-test/html/config/environment.rb:7:in `<main>'
        from config.ru:5:in `require_relative'
        from config.ru:5:in `block in <main>'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:36:in `start'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:143:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:134:in `perform'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/serge/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
````

### System configuration
**Rails 7.0.3**:

**Ruby 3.0.4**:

In development mode it work in rails 7.0.3 ans in rails 6.1.4.4
In production mode it work in rails 6.1.4.4 and fail in rails 7.0.3

while debuging I found this in ActiveRecord::ConnectionAdapters
      def retrieve_connection_pool(owner, role: ActiveRecord::Base.current_role, shard: ActiveRecord::Base.current_shard)
        pool_config = get_pool_manager(owner)&.get_pool_config(role, shard)
        pool_config&.pool
      end

the shard value  is :default so the result is nil

This method is used for all models at **initialization** time and the shard is not specified at this time (my code is not run)
But in 6.1.4.4 I didn't find this behavior during **initialization**

zeitwerk is used in the 2 cases and it fail with or without bootsnap gem.

Is this behavior normal or not ?
this should be specified in the documentation

As a workaround I modified the model abstract class:
    connects_to shards: {
      fr: { writing: :comdev_fr },
      de: { writing: :comdev_de },
      default: { writing: :comdev_fr },
    }
and with this it's working, but I'm not sure it's the correct solution...

**Comment by eileencodes** [comment]
With the current implementation (which I'm working on improving) you are required to set a default shard. Without being able to see the actual code or an example of the code that is erroring (ie what is in app/models/cmdmary/etudprix.rb that is querying the database on boot?) it's harder for me to give a specific answer as to why. 

The main reason is that Rails has to make some guesses about your application because apps are lazily loaded in development. Because of that we need to estalbish a default connection on boot. This happens in the Railtie [here](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railtie.rb#L270). Because of this we made Rails always set a default shard when establishing connections to a model. 

If you wanted to not use the default shard (you can't avoid it being set), you would need to make sure that every query was wrapped in a `connected_to` block to another shard. I get this setup isn't ideal which is why I'm working on a way to make sharding better, but at the moment this isn't really a bug, just an issue with the design.

So your work around to add `default` is the correct way - although I'd drop `fr: { writing: :comdev_fr }` because then you're opening 2 connections to `comdev_fr` when you only need one. Sorry for the confusion.

**Comment by net1957** [comment]
Thanks for this explanation.

I retried with rails 6.1.4.4 in **_production_** mode and it's working as expected, but a startup I get this message:
````
Failed to define attribute methods because of ActiveRecord::ConnectionNotEstablished: ActiveRecord::ConnectionNotEstablished
````
So I assume that this error is not fatal, and the application is running without any error after that.

it's seems to be defined in the same file in v6.1.4.4 and v7.0.3 in railtie.rb
````
 initializer "active_record.define_attribute_methods"
````
In 7.0.3 it fail before reaching this point in **_production_** mode

During debugging I found that the attribute method in my model trigger this error:
````
module Cmdmary
  # Etudprix model
  class Etudprix < CmdmaryRecord
    include ArelHelpers::ArelTable

    self.table_name = 'etudprix'
    self.primary_key = :neturef, :nveretu, :nversim

    attribute :dexport, :oracle_date
    attribute :dmaj, :oracle_date

    scope :transferable, -> { where(Etudprix[:cexport].eq('O')).where(Etudprix[:nhut].not_eq(nil)) }

    # @return [Relation]
    def self.datetime_start(start_datetime = nil)
      rel = all
      rel = rel.where(Etudprix[:dmaj].gteq(transform_to_time(start_datetime))) if start_datetime
      rel
    end

    def self.nhut_list(nhut)
      list = (nhut || '').split(',').compact
      rel = all
      rel = rel.where(Etudprix[:nhut].in(list)) unless list.empty?
      rel
    end

    def self.inc_transferred(include_transferred)
      rel = all
      rel = rel.where(Etudprix[:dexport].eq(nil)) unless include_transferred == 'O'
      rel
    end

    def self.study(neturef, nveretu)
      rel = all
      rel = rel.where(Etudprix[:neturef].eq(neturef)) if neturef
      rel = rel.where(Etudprix[:nveretu].eq(nveretu)) if nveretu
      rel
    end
  end
end
````
and the types:
````
# Oracle Date Type to suppress usec when writing to DB and the Oracle column is a Date type.
# If possible use TIMESTAMP Oracle column which is default SQL type for Rails :datetime attribute since Rails 5
# see  https://github.com/rsim/oracle-enhanced/issues/1679
class OracleDateType < ActiveRecord::Type::DateTime
  # from DB to app
  def deserialize(value)
    value.is_a?(String) ? super(value) : super(value&.change(usec: 0))
  end

  # from app to DB
  def serialize(value)
    value.is_a?(String) ? super(value) : super(value&.change(usec: 0))
  end
end

# Register the type
ActiveRecord::Type.register(:oracle_date, OracleDateType)
````

as soon I remove it, the application start.
The Type  Module fail in:
````
      def adapter_name_from(model) # :nodoc:
        model.connection_db_config.adapter.to_sym
      end
````

That diverge from the rails 6.1.4.4 way of work.

Any clue?

**Comment by eileencodes** [comment]
> Any clue?

If you can make a demo application that reproduces this (without oracle) I can try to figure out what changed, but I don't know offhand and can't dig into this without a reproduction. It's possible this is due to a change that works fine with mysql but breaks with Oracle.

**Comment by net1957** [comment]
will try

**Comment by net1957** [comment]
Hi @eileencodes

I setup a minimal project at https://github.com/net1957/shards based on sqlite3 DB.

See the readme for more information.

I can confirm that the attribute definition in the model trigger the issue.
The same application work on rails 6.1.4.4.

I can open a new issue or perhaps you can re-open this one.

Regards

**Comment by eileencodes** [comment]
Ok I've identified the source of the issue but I don't know the fix because it wasn't caused by a change to the database connections but rather a change to attributes.

If I revert both #41166 and #41302 the application you provided boots properly.

**Comment by eileencodes** [comment]
Ok I have figured out what's going on here, why the change had an impact, but I can't fix it, easily because there is no obvious path to a fix.

1) In 6.1 and prior attributes would raise an unknown type error at runtime instead of definition time. #41166 (7.0+) changed this so that the attributes are defined at definition time rather than runtime. You weren't seeing this error in 6.1 because the type check was happening _after_ boot (and after connections are established) rather than _on_ boot. This works fine in development because the app is not eager loaded, production is eager loaded. You can repro this problem in development by setting `eager_load` to `true` in the environment config.
2) Now because of this change when Rails tries to eager load the app and loads the `Comment` model, Rails has no idea which shard you want to load attributes for so it tries to load them for the current_shard, which by default is named `:default`. If `connected_to` was not called then `default` will always be used. Here's the code that's loading the `connection_pool`. https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_handling.rb#L2833

So this leads to a big question without an easy answer: In a sharded application what is the expected behavior? Which connection (fr or de) should be used to load the attribute types from the adapter? Active Record makes assumptions about there being a default role and shard because apps won't boot without it. I am hoping to make some changes to improve the way this behaves but I am no where near a solution at the moment.

For now you can get around this one of two ways:

1) Pick one shard to be `:default` or add a new shard called `:default`. This is probably advisable because Active Record makes a lot of assumptions about the default shard.
2) OR wrap your `attribute` call in a `connected_to` block like this:

```ruby
class Comment < ComdevRecord
  ComdevRecord.connected_to(shard: :fr) do
    attribute :remark, :capitalize
  end
end
```

Either works, but 1 is probably less problematic for Active Record until a better design is in place for sharding.

Given the attribute needs to be loaded off a connection, because that's where the adapter is defined, what would you expect Rails do in a sharded situation? Pick the first shard? Raise an error to require a default shard? Set the adapter information elsewhere without establishing a connection? I'm asking because I don't know the best route and want your opinion since you're using sharding.

**Comment by net1957** [comment]
Hi @eileencodes

Thanks for this great explanation.

At this time I do it this way:

in abstract model:
````
    connects_to shards: {
      default: { writing: :comdev_fr },
      de: { writing: :comdev_de }
    }
````

in the controller:
````
        def handle_tenant
          ::Cmdmary::CmdmaryRecord.connected_to(shard: shard(api_params[:tenant]).to_sym, role: :writing) do
            Rails.logger.warn { "Tenant used:'#{api_params[:tenant]}', api:'#{api}'" }
            yield
          end
        end

        def api_params
          params.permit(:token, :tenant, :format, :start_date, :neturef, :nveretu, :nhut,
                        :include_transferred)
        end

        # Consider the first defined tenant as the default on
        def shard(tenant)
          Rails.configuration.cfg.api.fetch(api).tenants.first == tenant ? 'default' : tenant
        end
````
In the config file:
````
development:
  desc: 'Comdev to Marygest'
  tenants:
    - fr
    - de
````

So Rails is happy and boot. But this at the cost of greater complexity.

About your question:
In this case the 2 databases have an identical schema, but I suppose that in other uses, the schemas could be different.

An idea would be to add a parameter default = true or false on an entry of connects_to or assume that the 1st entry is the default one. So the name of the shard could keep a meaning for the business part.
````
    connects_to shards: {
      fr: { writing: :comdev_fr, default: true },
      de: { writing: :comdev_de }
    }
````
or
```
    connects_to shards: {
      fr: { writing: :comdev_fr}, # first entrie is the default one.
      de: { writing: :comdev_de }
    }
````

I suspect the second one is more in the Rails way (convention/configuration), but the first is more explicit. Perhaps we could accept the 2 ways to do it.

Hope this can help.
Regards

**Comment by eileencodes** [comment]
> But this at the cost of greater complexity.

I don't understand how this increases complexity, it's should only require changing the name and callers of `fr` to `default`.

**Comment by net1957** [comment]
The complexity increase because I need to to translate the  tenant parametre to a shard key:
````
        # Consider the first defined tenant as the default on
        def shard(tenant)
          Rails.configuration.cfg.api.fetch(api).tenants.first == tenant ? 'default' : tenant
        end
````
ApplicationRecord:

In my case, the User model is on the primary database (its in the minimal example application also) and  other parts of applications connects to others databases but without sharding.
Because of this  I use ComdevRecord class.

So; I my case I use a user passed parameter tenant (validated before usage) as shard key.
So no need to translate this information to a shards key of a connect_to.

My proposed ideas should restore this in Rails 7.
I don't known if it is difficult or not to code it or if a better way exist.
````
    connects_to shards: {
      fr: { writing: :comdev_fr, default: true },
      de: { writing: :comdev_de }
    }
````
or
````
    connects_to shards: {
      fr: { writing: :comdev_fr}, # first entrie is the default one.
      de: { writing: :comdev_de }
    }
````
I think that for the usage of a :default key should be avoided in the shards hash.
But use a :default parameter on a entry or use the first entry as default is more manageable for me. It has less impact of the business code.

We can explain that the :default entry is replaced with a :default parameter or by the first entry.
The default key no longer has any special meaning.
Cheers.

**Comment by grobie** [comment]
Thanks for the detailed explanation @eileencodes!

We're also using different shards and want to avoid a default shard at all costs (to ensure any code querying the database selects the correct shard explicitly). This has worked fine so far, but doesn't work anymore when trying to define a custom type for an attribute, as that code will call `Type.adapter_name_from` which currently depends on the retrieving a connection pool based on the default_shard: https://github.com/rails/rails/blob/3872bc0e54d32e8bf3a6299b0bfe173d94b072fc/activerecord/lib/active_record/attributes.rb#L216

Though in most applications I expect all shards to use the same adapter, so we could just fallback here to static database configurations in order to retrieve the adapter name, removing the need to define a default shard:

```diff
diff --git a/activerecord/lib/active_record/type.rb b/activerecord/lib/active_record/type.rb
index dadc02095e..6da45368b8 100644
--- a/activerecord/lib/active_record/type.rb
+++ b/activerecord/lib/active_record/type.rb
@@ -48,6 +48,9 @@ def default_value # :nodoc:
 
       def adapter_name_from(model) # :nodoc:
         model.connection_db_config.adapter.to_sym
+      rescue ConnectionNotEstablished
+        adapters = model.configurations.configurations.map(&:adapter)
+        adapters.uniq.size == 1 ? adapters.first.to_sym : raise
       end
 
       private
```

Would you accept a pull request to add this fallback to `Type.adapter_name_from` in order to make it independent of the presence of the `default_shard`?

**Comment by eileencodes** [comment]
> Would you accept a pull request to add this fallback to Type.adapter_name_from in order to make it independent of the presence of the default_shard?

No, I don't think a fallback here is the right fix because this is indicative of a larger issue in Active Record and it's reliance on `Base.connection`. I plan on fixing this a more correct way but it's going to take some time. It requires redesigning parts of Active Record, which I'm in the process of doing. I will update this issue when there's a PR solving this particular problem.

**Comment by net1957** [comment]
@eileencodes ,

did you get some time to redesign parts of  ActiveRecord?

**Comment by eileencodes** [comment]
> did you get some time to redesign parts of ActiveRecord?

This isn't a one month project, it's probably 6mo to a year. I haven't been able to merge the first PR since we've been blocked upgrading Shopify, hopefully can pick it back up this week.

**Comment by net1957** [comment]
Thanks for your reply. 
I'm not in a hurry.  I can live some time with the current code. Take your time!

**Comment by eileencodes** [comment]
Hi @grobie I actually found a solution for this that doesn't require me to refactor a ton of active record code. Since it is a slight behavior change I don't think I'm going to backport it to 7.0. However, if you want to implement the same behavior as Rails for 7.0 you can set the `default_shard` in the `Comdev` model like this:

```ruby
  class CmdmaryRecord < ApplicationRecord
    self.abstract_class = true
    self.default_shard = :fr

    connects_to shards: {
      fr: { writing: :comdev_fr },
      de: { writing: :comdev_de }
    }
  end
```

**Comment by grobie** [comment]
Thanks for getting back to me @eileencodes.

We're aware that setting a default shard prevents the errors, but it comes at the serious downside of risking accidental writes to the wrong shard if code paths no longer have to set the shard explicitly before any query. See my original comment https://github.com/rails/rails/issues/45390#issuecomment-1235858128

> We're also using different shards and want to avoid specifying a default shard at all costs (to ensure any code querying the database selects the correct shard explicitly).

**Comment by eileencodes** [comment]
But my change doesn't make your problem worse @grobie, it just chooses a different default shard if that's what you're hoping for. The bug I fixed was the original reported bug here, and your issue is different (although the symptom is the same)

The `adapter_name_from` isn't only one place in Rails we need a single connection, there are a bunch of internal methods that look for / assume `default_shard` is `default` and those will blow up if `default` doesn't exist. The change I made ensures that these internal methods keep working by finding the new "default" connection.

I think your issue is a separate feature, and one I'm not sure Rails can really implement easily. That's going to be a big refactoring given Rails requires a single connection in a bunch of places. I think you should open a separate issue because it's not technically directly related to this problem IMO.

**Comment by net1957** [comment]
@eileencodes  Thanks for the solution in Rails 7.0 (self.default_shard)

It solve my problem until 7.1 is released

One more question:
 In Rails 7.1 will this solution work or will it be replaced with the first shard entry,  ignoring this setting?

Regards

**Comment by eileencodes** [comment]
> In Rails 7.1 will this solution work or will it be replaced with the first shard entry, ignoring this setting?

First shard entry will win so you should make sure that the default_shard setting in 7.0 is the same shard as the one you set first. When you upgrade to 7.1 you should remove `self.default_shard=` from your model.

**Comment by net1957** [comment]
Thanks for this information.

**Comment by aksharj** [comment]
Hi, 

sorry for reviving this thread but wanted to check before creating a new issue. I am on `Rails 7.0.3` and have the following model definition

```

class ExternalRecord < ApplicationRecord
  self.abstract_class = true
  #establish_connection :main_red
  connects_to database: {
    reading_main_red: :main_red,
    reading_main_green: :main_green,
    reading_main_blue: :main_blue
  }
end

```

I want to switch to reading from different databases based on few conditions, this seems to be working fine well on development environment 

i am using below code to switch to different databases

```
ActiveRecord::Base.connected_to(role: @main_db_name.to_sym) do
        result = Api::V2::Gom::T1::Platform.ransack(params[:q]).result.page(params[:page]).per(get_rows_limit)
      end
```


but when when i try to run rspec tests, i get an error 


```
ArgumentError (The `pool_config` for the :reading_main_red role and :default shard was `nil`. Please check your configuration. If you want your writing role to be something other than `:writing` set `config.active_record.writing_role` in your application configuration. The same setting should be applied for the `reading_role` if applicable.):

```

database.yml  as pool setting. it would be great if someone can point me in the right directions, should i create a new issue or may be something in rspec that i a missing?

please help.

Thanks.
