### ISSUE TITLE
database schema: foreign key causes json default to become string instead of object

### ISSUE THREAD

**Issue by kyrofa** [rails/rails#45430]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "accounts", force: :cascade do |t|
    t.text "name"
  end

  create_table "products", force: :cascade do |t|
    t.integer "account_id"
    t.json "foo", default: {}
  end

  # If you comment this out, this test will pass
  add_foreign_key "products", "accounts", column: "account_id"
end

class Product < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_product_foo_default
    product = Product.new
    assert_equal({}, product.foo)
  end
end
```

### Expected behavior
A json column with a `default: {}` should be an empty JSON object by default.

### Actual behavior
The expected behavior is what happens until you add a foreign key. Then suddenly it quotes the braces, turning the default into a string. Note that this happens in both main and v7 (I have not tested anything else).

### System configuration
**Rails version**: main and 7.0.3

**Ruby version**: 3.0.2

**Comment by adrianna-chang-shopify** [comment]
Hey @kyrofa ! I'm not sure setting an empty object as the default works for `json` columns with SQLite. From [the docs](https://www.sqlite.org/json1.html):
> SQLite stores JSON as ordinary text. Backwards compatibility constraints mean that SQLite is only able to store values that are NULL, integers, floating-point numbers, text, and BLOBs.

I dug into the repro steps you set up, and pinpointed the specific problem. 
`sqlite3` uses `alter_table` to handle `add_foreign_key`:
https://github.com/rails/rails/blob/1003e974ed9cdae6a057a1857374bceb09b34a7b/activerecord/lib/active_record/connection_adapters/sqlite3/schema_statements.rb#L55-L56

which calls `#move_table` to copy the table to a temp table + add the FK, then copy this table back over the original. To copy the table we reconstruct a table definition, which involves fetching the array of Columns for the table:
https://github.com/rails/rails/blob/1003e974ed9cdae6a057a1857374bceb09b34a7b/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L494
https://github.com/rails/rails/blob/1003e974ed9cdae6a057a1857374bceb09b34a7b/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L107-L112

And this involves performing a query to fetch the table info from the db:
https://github.com/rails/rails/blob/1003e974ed9cdae6a057a1857374bceb09b34a7b/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L405-L410
Since JSON is stored as text in SQLite, we'll retrieve the default for `"foo"` as `"{}"`. 

Interestingly, seems like we've intentionally tried to emulate JSON types in the `sqlite3` adapter for the sake of making db-agnostic migrations:
https://github.com/rails/rails/blob/1003e974ed9cdae6a057a1857374bceb09b34a7b/activerecord/test/cases/adapters/sqlite3/json_test.rb#L11-L14

But I'm not sure we should 🤔 As soon as we end up needing to call `alter_table` for a schema operation, we'll end up running into the same issue where an empty JSON object is converted to a string when the table is copied. Given that SQLite3 isn't intended to store anything other than the aforementioned data values (ints, floats, etc.) I think we should be explicit about not allowing incompatible defaults to be used.

**Comment by adrianna-chang-shopify** [comment]
Ah, yep you're totally right -- sorry, I got thrown off by the SQLite docs stating that there's no support for a JSON storage class and was wondering if it was problematic to support this entirely, but deserializing on copy as @fatkodima suggested definitely makes sense 👍
