### ISSUE TITLE
CSS File with [application-*.css] name causes "No route matches" error

### ISSUE THREAD

**Issue by mfa777** [rails/rails#45547]
### Steps to reproduce

First I use webpack and jsbundling-rails to build a CSS file from JavaScript code, which name is `application-webpack.css`, it located under builds folder.

```
app/assets
├── builds
│   ├── **application-webpack.css**
│   ├── application.css
│   ├── application.js
│   └── application.js.LICENSE.txt
```

webpack.config.js
```javascript
module.exports = {
    mode,
    optimization: {
        moduleIds: 'hashed',
    },
    entry: {
        application: "./app/javascript/application.js"
    },
    output: {
        filename: "[name].js",
        sourceMapFilename: "[file].map",
        path: path.resolve(__dirname, '..', '..', 'app/assets/builds')
    },
    plugins: [
        new webpack.optimize.LimitChunkCountPlugin({
            maxChunks: 1
        }),
        new RemoveEmptyScriptsPlugin(),
        new MiniCssExtractPlugin({
            // **This will output application-webpack.css**
            filename: "[name]-webpack.css"
        }),
    ],
    module: {
        rules: [{
            // Add CSS/SASS/SCSS rule with loaders
            {
                test: /\.(?:sa|sc|c)ss$/i,
                use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
            },
        ]
    }
}

```
Then include CSS from erb view:

`<%= stylesheet_link_tag 'application', "application-webpack", media: 'all', 'data-turbo-track': 'reload' %>`

This will generate

```html
<link rel="stylesheet" href="/assets/application-webpack.css" media="all" data-turbo-track="reload" />
<link rel="stylesheet" href="/assets/application.css" media="all" data-turbo-track="reload" />
```

When access "http://dev-server/assets/application-webpack.css" from browser, you will see 'No route matches [GET] "/assets/application-webpack.css' error.

If I change the out file name to another name such as `a-webpack.css`, repeat same test, the route error will NOT raise any more.

After do some google search, I found there's a similar issue: https://github.com/rails/rails/issues/44260

### Expected behavior
Should see CSS file content.

### Actual behavior
Encounter 'No route matches [GET] "/assets/application-webpack.css' error.

### System configuration
**Rails version**:
Rails 7.0.3
**Ruby version**:
ruby 3.1.2p20

**Comment by skipkayhil** [comment]
Hey @mfa777, do you have an example repo that you could share to show how this error happens? Without this it is much harder to figure out what's going wrong

**Comment by mfa777** [comment]
> Hey @mfa777, do you have an example repo that you could share to show how this error happens? Without this it is much harder to figure out what's going wrong

Hi, @skipkayhil  have just set a new [Rails 7 demo app](https://github.com/mfa777/demo7), please start server with `bin/dev`

Error if keep application-webpack.css name
```javascript
// demo7/webpack.config.js
module.exports = {
     plugins: [
        new MiniCssExtractPlugin({
            filename: "[name]-webpack.css"
        })
    ],
}
```
Page source of 127.0.0.1:3003/hello/index
![application-webpack](https://user-images.githubusercontent.com/2765931/178233405-4e663f6c-6fd8-4588-804b-90470460907b.png)

Screenshot of Routing Error when access http://127.0.0.1:3003/assets/application-webpack.css
![application-webpack-error](https://user-images.githubusercontent.com/2765931/178233425-17cab9fe-c595-4bc7-9e83-28a7c7431e21.png)

Success if change name in webpack config
```javascript
// demo7/webpack.config.js
module.exports = {
     plugins: [
        new MiniCssExtractPlugin({
            filename: "a-webpack.css"
        })
    ],
}
```
Page source of 127.0.0.1:3003/hello/index
![a-webpack](https://user-images.githubusercontent.com/2765931/178234573-9f42caef-aaad-4a96-b983-8f7928883f7a.png)

Screenshot of css content when access http://127.0.0.1:3003/assets/application-webpack.css
![a-webpack-success](https://user-images.githubusercontent.com/2765931/178234594-30f8e6db-34cb-473b-aa8b-4a99ad6ef012.png)

**Comment by skipkayhil** [comment]
Thank you for the repo! It helped me narrow down the issue:

Sprockets is misidentifying the `-webpack` postfix as a fingerprint since rails/sprockets@53ce8d6. (previously it would only match if it was a digit or a-f). I don't have a good answer yet for a way to determine whether something is intentionally dash cased or if its a fingerprint.

At the moment it seems like not using dash case is the way forward, but that seem suboptimal ☹️ 

---

To expand on why `application-webpack` doesn't work but `a-webpack` does work:

https://github.com/rails/sprockets/blob/e36620745d7150fc33eccffeaf79e741a774499c/lib/sprockets/server.rb#L45-L48

The `fingerprint` (`-webpack`) gets stripped from the `path`.

https://github.com/rails/sprockets/blob/e36620745d7150fc33eccffeaf79e741a774499c/lib/sprockets/server.rb#L65-L75

The asset is first looked up using that truncated `path` (it finds `application.css` but not `a.css`), and if not found it looks up the asset by the `full_path` (`a-webpack.css`). 

Then it ensures that the asset's etag matches the fingerprint, which fails because `application.css`'s etag doesn't match `-webpack`, and `a-webpack.css`'s etag correctly matches because it found the correct asset.
