### ISSUE TITLE
Included in project gem with controller that inherits from ActionController::API breaks Jbuilder

### ISSUE THREAD

**Issue by TakaiSaisei** [rails/rails#45601]
### Steps to reproduce

```rails new example_api --api```, ```bundle gem example_gem```, actual content of both can be seen in these commits:
https://github.com/TakaiSaisei/example_gem/commit/83f3c802171f2c9b334feceb681e2059daaea672
https://github.com/TakaiSaisei/example_api/commit/dd99c144278aecaab903ad05c62f402cb024c62d
```shell
git clone https://github.com/TakaiSaisei/example_api.git && cd example_api
bundle
rails s
curl 127.0.0.1:3000/users.json
```

### Expected behavior
Template ```views/users/index.json.jbuilder``` rendered
curl printed ```{"users":[{"id":1},{"id":2},{"id":3}]}```

### Actual behavior
Rails will skip template rendering because the project includes a gem that have a controller that inherits from ActionController::API

As soon as the BaseController from the gem is inherited from ::Metal or ::Base, everything will work fine. If ApplicationController from Rails project inherits from ::Base (and ::Metal, I guess), everything will work fine. If gem is excluded from Gemfile, everything will work fine.

### System configuration
**Rails version**:
7.0.3.1
**Ruby version**:
3.1.2

**Comment by skipkayhil** [comment]
Hey @TakaiSaisei, thanks for opening an issue! 

I believe the behavior you are seeing is caused because you are requiring a controller in your gem. Since the gem is required by the application before initialization, the controller is autoloading Action Controller too early. The best way to use a controller in a gem would be to create an [Engine](https://guides.rubyonrails.org/engines.html), and then putting the controller in the gem's `app/controllers` folder as you would with a regular application. You shouldn't need to require it then, and Rails will be able to load Action Controller at the correct time.

I'm going to close this as it doesn't seem to be an issue with Rails, but feel free to reply if you are still having trouble!
