### ISSUE TITLE
ActiveRecord `with_options` should merge and combine options

### ISSUE THREAD

**Issue by james-em** [rails/rails#45682]
### Steps to reproduce

```ruby
# my_model.rb

class MyModel < ApplicationRecord
  with_options if: -> { email.present? } do
    validates :first_name, presence: true
    validates :last_name, if: -> { first_name.present? }
   end
end
```

### Expected behavior

**First name** should be mandatory if email is present.
**Last name** should be mandatory if email **and** first_name is present.

### Actual behavior

**First name** is mandatory if email is present.
**Last name** is mandatory if first_name is present **even if the email is blank.**

The inner **if** seems to override the parent **if** that is defined with the **with_options** instead of testing both condition.

### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: 3.1.0

### Possible workaround for that specific scenario

```ruby
# my_model.rb

class MyModel < ApplicationRecord
  with_options unless: -> { email.blank? } do
    validates :first_name, presence: true
    validates :last_name, if: -> { first_name.present? }
   end
end
```

It works as expected because inner if will not replace parent unless and both condition will be executed.

Related article https://stackoverflow.com/questions/13174435/rails-nested-with-option-if-used-in-validation

**Comment by skipkayhil** [comment]
This is specifically documented, so I think its working as expected:
https://github.com/rails/rails/blob/752b566152ca3e8daf4804c90777cc1a01d003f6/activesupport/lib/active_support/core_ext/object/with_options.rb#L53-L65

I'm going to close this since this isn't a bug and we reserve the issue tracker for bugs only. However, feel free to [try to implement the feature](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-code) and send us a pull request, or start a discussion on [rubyonrails-talk Discourse](https://discuss.rubyonrails.org/c/rubyonrails-talk/7) to gauge interest before writing code.
