### ISSUE TITLE
Define correct constant with Zeitwerk

### ISSUE THREAD

**Issue by vs37559** [rails/rails#45687]
Hi, 
I am trying to add a file in custom directory as `app/data_dispatchers/file_dispatcher.rb`.
``` ruby
module DataDispatchers
  class FileDispatcher
    # some logic
  end
end
```
I am getting this error on running `rails zeitwerk:check`
``` ruby
expected file app/data_dispatchers/file_dispatcher.rb to define constant FileDispatcher
```

Is there any workaround with which I can define `DataDispatchers::FileDispatcher` as my constant ?

### System configuration
**Rails version**: `v7.0.3.1`

**Ruby version**: `v3.1.2`

**Comment by simi** [comment]
as mentioned at https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#config-autoload-paths

> Rails adds custom directories under app to the autoload paths automatically. For example, if your application has app/presenters, you don't need to configure anything in order to autoload presenters, it works out of the box.

That means `app/*anything*/file_dispatcher.rb` expects `FileDispatcher` to be defined in there. You can move your code out of app directory (into `lib` or so) or nest it into additional directory like `app/services/data_dispatchers/file_dispatcher.rb`. That file would expect `DataDispatchers::FileDispatcher`.

Alternativelly you can try to tweak Zeitwerk to load your original path in given way - https://github.com/fxn/zeitwerk#root-directories-and-root-namespaces.

**Comment by vs37559** [comment]
@simi Thanks for the direction. I tried tweaking Zeitwerk as per above reference but it seems zeitwerk is simply ignoring the custom configurations. Any specified way to do this?

**Comment by skipkayhil** [comment]
> That means `app/*anything*/file_dispatcher.rb` expects `FileDispatcher` to be defined in there. You can move your code out of app directory (into `lib` or so) or nest it into additional directory like `app/services/data_dispatchers/file_dispatcher.rb`. That file would expect `DataDispatchers::FileDispatcher`

I definitely recommend trying to stay within the default configuration as described here. 

> Any specified way to do this?

Without a repo showing what you are trying to do, it's practically impossible to know what isn't working.

Since this doesn't appear to be an issue with Rails/Zeitwerk, I'm going to close this as we reserve the issue tracker for bugs only. I recommend bringing your question to the [rubyonrails-talk](https://discuss.rubyonrails.org/c/rubyonrails-talk/7) forum or [Stack Overflow](https://stackoverflow.com/questions/tagged/ruby-on-rails), where a wider community can help you.
