### ISSUE TITLE
SameSite error logged in Firefox (rails/main)

### ISSUE THREAD

**Issue by strobilomyces** [rails/rails#45681]
### Steps to reproduce
- Create a new rails app using main or on/after d29e755aea0cd01d3bb27f5a9db14b9a1a346bb0
- Add a model, change default route to its index
- Start server, open in Firefox (I'm using 103.0)

### Expected behavior
No console errors

### Actual behavior
The good old:

`Cookie “_fuck_session” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

### System configuration
**Rails version**: rails/main (currently at b8964e53100f66197e0adbd96c194285651cae4e)

**Ruby version**: 3.1.2p20

### Fix

Rolling back to the previous commit, 646bff6091af8067a9ec898d1c2399c255d75ffd, the console error is not logged.

### Etc.

Setting config.action_dispatch.cookies_same_site_protection in application.rb has no effect on this.

I don't know if the changelog for d29e755aea0cd01d3bb27f5a9db14b9a1a346bb0 is supposed to be suggesting a workaround, but where exactly it would be set for ordinary session cookies is unclear to me. Regardless, out of the box, the error is present.

Oh, yeah, and there aren't any errors in Chrome (hence the title).

Thanks in advance :)

**Comment by Matt-Yorkley** [comment]
Just a heads up; this issue is fixed when using `ActionDispatch::Session::Cookiestore` by https://github.com/rails/rails/pull/45688, but it's _not_ fixed for `ActionDispatch::Session::CacheStore` :warning:

When using `config.session_store :cache_store`, SameSite is `nil` on the session cookie and Firefox throws the warning mention in the original bug description above. This is a regression that's present in `7.1` (including `7.1.3.2`) but not in `7.0`.
