### ISSUE TITLE
ActiveStorage: Partial downloads with incorrect range throw a RoutingError and 404 not found

### ISSUE THREAD

**Issue by alietz** [rails/rails#45890]
### Steps to reproduce
```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'rails', '~> 7.0.0'
  gem 'sqlite3'
end

require 'active_record/railtie'
require 'active_storage/engine'
require 'tmpdir'

class TestApp < Rails::Application
  config.root = __dir__
  config.eager_load = false
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_key_base = 'secret_key_base'
  config.hosts << 'www.example.com'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: 'Disk'
    }
  }
end

ENV['DATABASE_URL'] = 'sqlite3::memory:'

Rails.application.initialize!

require ActiveStorage::Engine.root.join('db/migrate/20170806125915_create_active_storage_tables.rb').to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :pdf
end

require 'minitest/autorun'

# Download a file with incorrect partial byte range
class PartialDownloadTest < ActionDispatch::IntegrationTest
  test 'Partial download' do
    user = User.create!(
      pdf: {
        content_type: 'application/pdf',
        filename: 'dummy.pdf',
        io: ::StringIO.new(SecureRandom.random_bytes(1000))
      }
    )
    # Get URL for download
    get "/#{Rails.application.routes.url_helpers.rails_blob_path(user.pdf, only_path: true)}"
    assert_response :redirect
    # Download with non-existing range
    get(response.location, headers: { 'Range' => 'bytes=10000-10000' })
    # Should respond with status 416 Range not satisfiable, but throws a RoutingError and responds with 404 not found
    assert_response 416
  end
end
```

### Expected behavior
When a browser asks for a part of a file that doesn't exist (Safari is prone to doing this), the response should be 416 'Range not satisfiable'.

### Actual behavior
The response is 404 'Not found' and an ActionController::RoutingError occurs.

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.0.2p107

**Comment by fatkodima** [comment]
The problem is:
1. Active Storage uses `Rack::File` to serve files
https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/activestorage/app/controllers/active_storage/disk_controller.rb#L14
https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/activestorage/app/controllers/concerns/active_storage/file_server.rb
2. Rack sets `X-Cascade => pass` when we have incorrect ranges
https://github.com/rack/rack/blob/856c4f9a81c3c1e73b02a0c2937225aaeef5ff64/lib/rack/files.rb#L89-L93
3. When this header is set, rails's router tries other routes to match the request and fails
https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/actionpack/lib/action_dispatch/journey/router.rb#L52-L62

So, maybe we should not set the `X-Cascade` header in the 2-nd step from the rack? From my understanding, `X-Cascade` header is to say (from middlewares, for example) something like: "I can't handle this request, try to handle it by yourself if you can". But the "Byte range unsatisfiable" error seems like the fatal error and should be reported directly without retries.

**Comment by skipkayhil** [comment]
> So, maybe we should not set the `X-Cascade` header in the 2-nd step from the rack? From my understanding, `X-Cascade` header is to say (from middlewares, for example) something like: "I can't handle this request, try to handle it by yourself if you can". But the "Byte range unsatisfiable" error seems like the fatal error and should be reported directly without retries.

I agree we probably shouldn't be passing this header, but I'm not sure we should be trying to change Rack. I think it would be easiest to not include "X-Cascade" when copying headers in stream_file: https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/activestorage/app/controllers/concerns/active_storage/file_server.rb#L10-L12 or manually clearing it after copying.

(As a side note, we should ensure we don't set "X-Cascade" or "x-cascade" since Rack 3 will be downcasing headers)

**Comment by hahmed** [comment]
Looking at the spec https://httpwg.org/specs/rfc7233.html#header.range 

> If all of the preconditions are true, the server supports the Range header field for the target resource, and the specified range(s) are invalid or unsatisfiable, the server SHOULD send a [416 (Range Not Satisfiable)](https://httpwg.org/specs/rfc7233.html#status.416) response.

Seems like Rack is the appropriate place for this fix?
