### ISSUE TITLE
rails test not working in windows by default: FFI is required

### ISSUE THREAD

**Issue by githubrarp** [rails/rails#45930]
### Steps to reproduce
rails test

# Your reproduction script goes here
`rescue in <main>': FFI is a required pre-requisite for Windows or posix_spawn support in the ChildProcess gem. Ensure the `ffi` gem is installed. If you believe this is an error, please file a bug at http://github.com/enkessler/childprocess/issues

### Expected behavior
test to run

### Actual behavior
error shows up

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.0.3p157

**Comment by flavorjones** [comment]
Hi! Sorry you're experiencing a problem resolving dependencies. It looks like the `childprocess` gem requires `ffi` on windows -- you can see this documented [in that project's README](https://github.com/enkessler/childprocess#requirements). You can likely add `ffi` to your project's `Gemfile` to resolve this dependency.

Because this isn't directly related to Rails functionality, I'm going to close this issue. But if you have any questions about what I said above, please comment and I'll try to get back to you.

If you'd like to follow up on this, can I suggest that you open an issue on the [childprocess repository](https://github.com/enkessler/childprocess/issues)? (There seem to be a few there already.) Thank you for understanding!
