### ISSUE TITLE
Add strict table mode (by default) to sqlite adapter

### ISSUE THREAD

**Issue by jrz** [rails/rails#45937]
SQLite supports 'strict tables' since 3.37.1 https://sqlite.org/stricttables.html

This forces a datatype to be specified when creating a table. This is the preferred method in any application created by developers. 

Unspecified/ANY datatypes are useful for quick tryouts as an enduser, similar to excel. But it's counterproductive when creating an application.

If this will become a configurable setting, the default should be set to strict.

**Comment by thearpist123** [comment]
@ghiculescu thanks for adding the `good first issue` label 🙂 I'm new here and I'm trying to submit a PR for this issue in the next few days.

I was planning on basing my PR off of https://github.com/rails/rails/pull/45346. The logic will be different, but it makes sense to me to use the same template for defining, naming, documenting, passing, and testing a new sqlite3 configuration value.

I was planning on extracting the database logic and some of the test code from https://github.com/rails/rails/pull/46639 after addressing the PR change requests, because it looked like that PR was nearly done.

There is already a `strict` configuration option in the sqlite database config
https://github.com/rails/rails/blob/3926b8e5c792f273c406474709b02d28d2669f8e/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L127
https://github.com/rails/rails/blob/3926b8e5c792f273c406474709b02d28d2669f8e/activerecord/test/config.example.yml#L97
I was wondering if it made sense to change the existing `strict` to be something like `strict_string_literals`, because having both `strict` and `strict_tables` config options is a bit confusing, in my opinion. Normally wouldn't want to change an existing option, but I don't think `strict`/`sqlite3_adapter_strict_strings_by_default` is in a released version of Rails yet?

Again, I'm very new to this codebase, so I'd appreciate a sanity-check on my approach before I submit the PR.

**Comment by ghiculescu** [comment]
I was thinking the same thing. IMO we should:

- Rename the setting from `strict_strings_by_default` to `strict_mode` or something more generic like that. This setting hasn't been shipped yet so it's okay to rename it.
- `strict: true` in `database.yml` still enables this setting.
- When `strict_mode` is true, we use string strings mode (https://github.com/rails/rails/pull/45346) *and* strict tables mode (https://github.com/rails/rails/pull/46639).
- I also think the logic in https://github.com/rails/rails/pull/46639 should be changed slightly such that if the setting is true it automatically makes new tables `STRICT`, but there is a way to opt out of this in your `create_table` statement. Currently you need to say `true` twice to actually get a strict table.

@byroot @fatkodima does this sound okay to you?

**Comment by matthewd** [comment]
> if the setting is true it automatically makes new tables STRICT, but there is a way to opt out

My first temptation is to use migration versioning to force strict mode on by default for all new migrations (while adding a `strict: false` option to `create_table`)... but I don't think it's practical for us to require SQLite 3.37.0 (2021-11-27) yet -- people are beholden to whatever version is in their OS's package system. 

The danger of a configurable default value is that it sets people up for future trouble: they'll create new migrations with the strict-by-default setting off in Rails 7.1, then upgrade SQLite and want to turn it on, and their future migrations will go great... but if they re-run their previous 7.1-era migrations, the schema will change. 

Unless we want to use it purely to affect generator output, I don't think there's anything to globally configure: per above we need migrations to opt in individually, and once they've done so, we certainly don't want to overrule them back to non-strict.

**Comment by ghiculescu** [comment]
> but if they re-run their previous 7.1-era migrations, the schema will change.

Hmm. This would apply to any setting that impacts how any migration command runs, right? Not to say it's not a valid issue, just trying to understand if it's unique to this.

**Comment by thearpist123** [comment]
> My first temptation is to use migration versioning to force strict mode on by default for all new migrations (while adding a `strict: false` option to `create_table`)... but I don't think it's practical for us to require SQLite 3.37.0 (2021-11-27) yet -- people are beholden to whatever version is in their OS's package system.

What if we also add a `supports_strict_tables` check like https://github.com/rails/rails/blob/345e1deb86d33712f16a92223d77a98aa549e933/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L151-L153
then in new migrations make the table & strings strict if `supports_strict` is true, and either stop the migration or emit a warning and proceed without strict tables and strings if `supports_strict` is false?

Incidentally, if we use database version checks for we could have separate checks for `supports_strict_strings` and `supports_strict_tables` since those options were added a few years apart.

**Comment by matthewd** [comment]
> either stop the migration or emit a warning and proceed without strict tables and strings if supports_strict is false

Stopping the migration is effectively requiring the new SQLite. "Use a newer version or explicitly opt out of safety" might be reasonable for something further off the day-one path, but creating a table is one of the first steps in every tutorial -- breaking that seems pretty unfriendly.

And warn+proceed puts us back at the same migration producing different schema when it's re-run. :confused:

(Note that `supports_expression_index?` is used to decide whether we run tests that rely on it, but does not affect migration execution. If I claim we never do that I'm sure I'll be wrong... but we do and should avoid it whenever possible.)

**Comment by thearpist123** [comment]
From a UX perspective, the only way I can think of to to seamlessly add this option would be

- add a `strict_typing: false` option to `create_table` and document it.
- type strictness is set on a table by table basis and is disabled by default for new migrations; no database-level setting is added.
- Leave the existing `strict` option alone, aside from a possible rename, because string strictness is configured at the database level independently of table type strictness.

Then in a future release, at a time when using SQLite > 3.37.0 is expected, `strict_typing` is enabled by default for new migrations.

Am I getting warmer, or did I accidentally suggest an antipattern again?

**Comment by northeastprince** [comment]
Under what circumstances would a datatype be violated (within Active Record)?
