### ISSUE TITLE
LoadInterlockAwareMonitor deadlock when clearing cache (multiple databases, test)

### ISSUE THREAD

**Issue by kuahyeow** [rails/rails#45994]
With multiple databases, we observe hangs within system tests.

See also https://gitlab.com/gitlab-org/gitlab/-/issues/371468 (GitLab is at Rails 6.1, Ruby 2.7.5)

### Steps to reproduce

Here's a minimal reproduction with Rails 7.0.3.1

1. Checkout https://gitlab.com/tkuah/multi_database_system_test
2. `bundle install`
3. `bundle exec rails db:migrate`
4. `bundle exec rails test test/system/home_pages_test.rb`

The conditions are:

1. Multiple databases
2. System test where there's an async request which overlaps with the main thread

### Expected behavior

It does not hang, and the test completes

### Actual behavior

It hangs. It looks like it's hanging when clearing query cache (see https://gitlab.com/gitlab-org/gitlab/-/issues/371468#note_1087203883, and https://gitlab.com/gitlab-org/gitlab/-/issues/371468#note_1088779499)

A backtrace dump taken while the test is hanging [sigdump-68442.log](https://github.com/rails/rails/files/9539878/sigdump-68442.log)

My suspicion is that:

1. `lock_thread` is true for system tests
3. Therefore both the main thread, and the Puma thread attempt to clear query cache for the same set of connections

So we have two connections:

1. Puma thread takes a `LoadInterlockAwareMonitor` lock for primary connection via `Post.transaction`
2. Main thread takes a `LoadInterlockAwareMonitor` lock for animal connection via implicit transaction that `create` does
3. Due to 2, main thread attempts to clear query cache for primary connection. **Waits for 1's lock**
4. Due to 1, and because of `lock_thread`, puma thread clears query cache for primary connection. It takes a `LoadInterlockAwareMonitor` lock for primary connection which succeds
5. Due to 1, puma thread now attempts clears query cache for animal connection. **Waits for 2's lock**

See [`clear_query_caches_for_current_thread` method](https://github.com/rails/rails/blob/e24fbf71fa0a10f63346b9b42604451958740844/activerecord/lib/active_record/connection_handling.rb#L244-L248)

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]

**Comment by casperisfine** [comment]
So I dug into this a bit.

Your suspicion is correct about the fact that both the puma and the test threads are blocked on the monitor trying to clear the query cache.

However it makes very little sense, because monitor is supposed to be re-entrant. Since the main thread already hold the lock, it should be able to enter the monitor again to clear the query cache without blocking.

I'll keep digging a bit more, but I must admit I'm quite puzzled about this.

**Comment by casperisfine** [comment]
Essentially what we notice is more or less:

```ruby
monitor = ActiveSupport::Concurrency::LoadInterlockAwareMonitor.new
monitor.synchronize do
 Thread.new { monitor.synchronize { p 2} }.join(1)
  monitor.synchronize { p 1 }
end
```

But of course this works as expected. It's very unclear what is special in the reproduction repo so that `monitor.synchronize { p 1 }` blocks.

**Comment by casperisfine** [comment]
Oh wow, I tried to add the above snippet in the test case to see if there was anything special, and it does somehow fix the problem:

```
diff --git a/test/system/home_pages_test.rb b/test/system/home_pages_test.rb
index e2466d4..c4c9571 100644
--- a/test/system/home_pages_test.rb
+++ b/test/system/home_pages_test.rb
@@ -6,6 +6,13 @@ class HomePagesTest < ApplicationSystemTestCase
 
     visit 'home_page/index'
 
+    monitor = ActiveSupport::Concurrency::LoadInterlockAwareMonitor.new
+    monitor.synchronize do
+     Thread.new { monitor.synchronize { p 2} }.join(1)
+      monitor.synchronize { p 1 }
+    end
+
+    Thread.current[:deb] = true
     Animal.create!(name: 'cat')
 
     assert_selector "h1", text: "HomePage"
```

This is getting really weird.

From my observations the puma thread was blocked inside `ActiveSupport::Dependencies.interlock.permit_concurrent_loads { super }`, so it seems that having the main thread call `permit_concurrent_loads` unblocks the whole thing. Still no idea why but that's an interesting clue.

**Comment by eileencodes** [comment]
One thing that's special about system tests is they need to share the DB thread for the process, otherwise Puma will spin up one thread and Capybara will spin up another and then transactions in tests won't work. I implemented that a long time ago here https://github.com/rails/rails/pull/28083. I suspect any issues with multi-db and system tests are directly related to that "feature".

**Comment by eileencodes** [comment]
Or I would check whether parallelization is a component in this as well. Does this occur with PARALLEL_WORKERS set to 1 or 0?

**Comment by casperisfine** [comment]
> One thing that's special about system tests is they need to share the DB thread for the process

Yes I'm aware of that. And both threads are stuck calling `clear_query_cache` on the same connection. It should work though, since the main (test) thread already entered the monitor.

> Does this occur with PARALLEL_WORKERS set to 1 or 0?

It's stuck with both.

**Comment by kuahyeow** [comment]
Thanks for looking into this !

> Essentially what we notice is more or less:
> 
> ```ruby
> monitor = ActiveSupport::Concurrency::LoadInterlockAwareMonitor.new
> monitor.synchronize do
>  Thread.new { monitor.synchronize { p 2} }.join(1)
>   monitor.synchronize { p 1 }
> end
> ```
> 
> But of course this works as expected. It's very unclear what is special in the reproduction repo so that `monitor.synchronize { p 1 }` blocks.

The thing here is that we are dealing with two `LoadInterlockAwareMonitor` objects. You can see this by adding `puts` to `clear_on_handler`:

```
     # lib/active_record/connection_handling.rb
     private                                                                                                                                           
       def clear_on_handler(handler)                                                                                                                   
         handler.all_connection_pools.each do |pool|                                                                                                   
++        puts "#{Thread.current} #{pool.connection.lock}" if pool.active_connection?                                                                 
           pool.connection.clear_query_cache if pool.active_connection?                                                                                
         end                                                                                                                                           
       end 
```

And then when we run the test we see:

```
$     bundle exec rails test test/system/home_pages_test.rb
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 59645

# Running:

#<Thread:0x000000015805fb00 run> #<ActiveSupport::Concurrency::LoadInterlockAwareMonitor:0x0000000112b92518>
#<Thread:0x000000015805fb00 run> #<ActiveSupport::Concurrency::LoadInterlockAwareMonitor:0x0000000112cfa6f8>
DEBUGGER: Attaching after process 5798 fork to child process 5819
Capybara starting Puma...
* Version 5.6.5 , codename: Birdie's Version
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:63906
#<Thread:0x000000015805fb00 run> #<ActiveSupport::Concurrency::LoadInterlockAwareMonitor:0x0000000112b92518>
#<Thread:0x0000000116074fb0@puma srv tp 003 /Users/tkuah/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:104 run> #<ActiveSupport::Concurrency::LoadInterlockAwareMonitor:0x0000000112b92518>
#<Thread:0x0000000116074fb0@puma srv tp 003 /Users/tkuah/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:104 run> #<ActiveSupport::Concurrency::LoadInterlockAwareMonitor:0x0000000112cfa6f8>
```

**Comment by matthewd** [comment]
> The thing here is that we are dealing with two LoadInterlockAwareMonitor objects

Ah yep, the two threads are deadlocking because they each hold a (transaction-length) lock of one database, and then try to lock the other. 

It's happening because each thread directly modifies one connection, then attempts to clear _all_ connections' query caches.

Ideally we should only be clearing the query cache for the subset of connections that point to the same physical database or its replicants... but we don't really have a good way of distinguishing that subset.

**Comment by casperisfine** [comment]
Oh wow, I totally missed these were distinct locks 🤦 

> Ideally we should only be clearing the query cache for the subset of connections that point to the same physical database or its replicants... 

Hum, didn't revert a PR that tries to do just that recently?



Either way, this can probably be solved by adding another lock that is to be acquired before trying to clear ALL caches.

**Comment by casperisfine** [comment]
> Either way, this can probably be solved by adding another lock that is to be acquired before trying to clear ALL caches.

Nevermind, that doesn't work because the main thread already locked one connection. 🤔

**Comment by matthewd** [comment]
This might be an option, though I'm not sure how I feel about it: https://github.com/rails/rails/commit/e5a815df3bf6249367eb09de89be8773e764caa9

**Comment by eileencodes** [comment]
> maybe even disable transactional fixtures for system tests

We wouldn't be able to do this without building in functionality like Database Cleaner. It was an intentional design decision to not add that complexity. I'm fine revisiting this decision but removing the locking threads is not viable without another solution in place.

**Comment by casperisfine** [comment]
>  in production, no two threads will believe they co-own a connection

Yes that was my understanding.

> Removing the lock would convert this deadlock into a potential segfault.

How so? We're basically clearing a Hash, so we're protected by the GVL. It's more of problem for JRuby & such.

Since this is a test only behavior, rather than one lock per connection, we could just have a single global lock around all DB operations, that we check only when the connections are being shared.

> We wouldn't be able to do this without building in functionality like Database Cleaner.

No we can. You can just set `self.use_transactional_tests = false` and tables will get cleared and re-populated after each test. The transactional fixtures are only a speed optimization.

**Comment by matthewd** [comment]
Oh, I understood you to mean removing the _entire_ lock, rather than this particular synchronize block -- isn't avoiding the lock in this particular case basically what my proposed change does? It doesn't explicitly constrain to a particular environment, but it only changes behaviour in that env, while remaining safe even in that case.

It feels inelegant to alloc a new hash when we clear the cache, but I don't see why we'd want to tank system test performance to avoid it.

**Comment by casperisfine** [comment]
> isn't avoiding the lock in this particular case basically what my proposed change does?

Indeed, that's relatively close.

>  I don't see why we'd want to tank system test performance to avoid it.

Well, my thinking is:

  - Would it really be significantly slower? It depends how many fixtures you have I guess.
  - It would be more representative of what is happening in production. 
  - It would get rid of code that is there only to support a test use case. I'm always uneasy with these.

**Comment by kuahyeow** [comment]
https://github.com/rails/rails/commit/e5a815df3bf6249367eb09de89be8773e764caa9 may work (I need to try it out) - what's slightly in-consistent about it is that we remove `lock.synchronize` only in `clear_query_cache` but not in the other methods.

Here's a tiny test-only work-around which prevents the hang.

```
     # lib/active_record/connection_handling.rb
     private
       def clear_on_handler(handler)
         handler.all_connection_pools.each do |pool|
++         next unless pool.instance_variable_get(:@lock_thread) == Thread.current

           pool.connection.clear_query_cache if pool.active_connection?
         end
       end

```

Ah no, this will result in the puma threads not clearing its query cache.

**Comment by kuahyeow** [comment]
> > in production, no two threads will believe they co-own a connection
> 
> Yes that was my understanding.
> 
> > Removing the lock would convert this deadlock into a potential segfault.
> 
> How so? We're basically clearing a Hash, so we're protected by the GVL. It's more of problem for JRuby & such.
> 
> Since this is a test only behavior, rather than one lock per connection, we could just have a single global lock around all DB operations, that we check only when the connections are being shared.
> 
> > We wouldn't be able to do this without building in functionality like Database Cleaner.
> 
> No we can. You can just set `self.use_transactional_tests = false` and tables will get cleared and re-populated after each test. The transactional fixtures are only a speed optimization.

Thanks this might be possible work-around too. (We have been sprinkling `wait_for_requests` to prevent concurrent requests instead)

I just tried setting `self.use_transactional_tests = false` on a capybara spec at GitLab - https://gitlab.com/gitlab-org/gitlab/-/merge_requests/102829. It does fix the hanging problem but the feature spec is about twice as slow (2m30s vs 4m40s). 

It may not be the number of fixtures but that I had to switch out from [`let_it_be`](https://github.com/test-prof/test-prof/blob/master/docs/recipes/let_it_be.md)

**Comment by byroot** [comment]
I had a chat with some Gusto people tonight (I encouraged them to post here, so they may post more details), and they ran into more or less this bug, but because of an enumerator implicit fiber (pseudo code):

```ruby
Post.transaction do
 enum =  Enumerator.new do
   Post.first # stuck
 end
 enum.next
end
```

This worked on older rubies, but recently Monitor was fixed to be owned by fibers not threads (https://bugs.ruby-lang.org/issues/17827).

So I think we really need to remove that lock, and purely rely on the connection pool to avoid concurrent access of the connection.

**Comment by ngan** [comment]
👋 Gusto person here!

> I don't see why we'd want to tank system test performance to avoid it.

Agree. System tests sharing the same connection as Puma is the best thing since sliced bread. It would be a massive detriment if we had to resort to database truncation. Before we were on system tests (feature tests via RSpec), we were paying about ~3 seconds penalty per test case to do the cleanup.

Is there a reason we have to use Ruby's `Monitor` for this particular lock? This might be a naive suggestion, but would it make sense to implement a new, private, Monitor that Rails can implement that has Threads as owners? Since this lock is primarily just for tests, it doesn't have to be tremendously performant.

**Comment by byroot** [comment]
> would it make sense to implement a new, private, Monitor that Rails can implement that has Threads as owners?

Well, it's not that easy to make it performant. 

Have you tried the monkey patch I suggested? (replace the lock by a noop).

I'm not even sure we need a lock in the first place. The connections are stored in a pool, threads are not supposed to use the same connection. Now in your cases it's two fibers of the same thread, it's a bit questionable whether it should work, but that's yet another debate.

**Comment by ngan** [comment]
Yup, lots of failures:

```
ActiveRecord::StatementInvalid:
--
  | Mysql2::Error: This connection is in use by: #<Thread:0x000055eb067948b0@puma srv tp 001 /var/www/vendor/bundle/ruby/2.7.0/gems/puma-6.0.0/lib/puma/thread_pool.rb:107 sleep>
```

**Comment by ngan** [comment]
> Let me try patching the actual lock later.

Same problem.

**Comment by ngan** [comment]
I think our problem was initially brought up here: https://github.com/rails/rails/pull/44219#issuecomment-1125524583
In which you responded, @byroot: https://github.com/rails/rails/pull/44219#issuecomment-1126125529

**Comment by ngan** [comment]
At this point, I'm wondering if this is a fix in Ruby or a fix in Rails.

This basic ruby code:
```
require "monitor"

lock = Monitor.new
lock.synchronize do
  Enumerator.new do
    lock.synchronize do
      puts "can't get here because of deadlock"
    end
  end.next
end
```
will cause a deadlock and just hang (It will raise with your [patch](https://github.com/ruby/ruby/pull/6680) applied, @byroot).
Is that ☝️ a feature or a bug? Either way, it's a little confusing if you didn't know `Enumerator` and `Monitor`/`Mutex` uses Fibers.

**Comment by casperisfine** [comment]
> Yup, lots of failures:

Is that for system test or regular tests?

The root cause here is that we're using the same connection for two distinct thread when doing system tests, so we'll still need some kind of synchronization that's for sure. I'm just not convinced that synchronization should be on the connection itself.

But I'd need to dig more into system tests to see how we could do that synchronization at a higher level.

Outside of system tests, a connection should never be accessible by more than one thread, so it should be safe not to lock.

**Comment by ngan** [comment]
> Is that for system test or regular tests?

As far as I can tell it’s system tests

**Comment by ngan** [comment]
> do that synchronization at a higher level.

interesting. Are you thinking maybe at the request level? Maybe in a test-only middleware?

**Comment by casperisfine** [comment]
> Are you thinking maybe at the request level? Maybe in a test-only middleware?

Something like this yeah. I haven't used system tests in a while, but IIRC they're generally like:

```ruby
test "something" do
  visit "/posts/new"
  assert_difference -> { Post.count }, +1 do
    submit
  end
end
```

So I think we could allow puma to use the connection when we navigate or do page assertions.

Of course that's the theory, I assume that when I'll actually get to open the code I'll find some reason why this isn't easy to do.

**Comment by ngan** [comment]
Thinking a bit more on this problem...

- We can add a `Thread::Monitor` to ruby stdlib, similar to [`Thread::Mutex`](https://ruby-doc.org/core-3.1.1/Thread/Mutex.html), that has threads as owner instead of fibers. We can have `LoadInterlockAwareMonitor` inherit from that and it would solve our problems.
- I think it'd also be interesting to see if we can remove this lock for non-system tests (ie development and production) by making the `lock` swappable or settable on Rails boot.

**Comment by technicalpickles** [comment]
@casperisfine would you be able to make that repo public?

**Comment by casperisfine** [comment]
🤦 

It's public now.

**Comment by technicalpickles** [comment]
@casperisfine thanks! I haven't tried repdocuing yet but taking an initial look, the app is using sqlite3 not mysql. Does that change anything? We're using latest mysql2, 0.5.4

**Comment by ngan** [comment]
I've tested this noop-ing the lock (just like [how you did it](https://github.com/casperisfine/rails-test-app/blob/main/app/controllers/posts_controller.rb#L1-L5)) on Ruby 2.7.6 and Ruby 3.1.2. Both yield errors. Notably, not all the same system tests fail for each run. I'm also unable to reproduce the failure on CI locally. All of this makes me think that it's probably a timing issue.

Additionally, we also have the [isolator gem](https://github.com/palkan/isolator), which errors when we're enqueueing a sidekiq job within a DB transaction. Nooping the lock also raises a handful of these errors as well.

Conceptually, I think the lock makes sense because we do have multiple threads (puma and test runner) trying to use the same connection. I can't get over the thought that we simply need a proper thread-based Monitor in Ruby. Either a new class or allow `Monitor` to be configurable.

**Comment by casperisfine** [comment]
> Conceptually, I think the lock makes sense because we do have multiple threads (puma and test runner) trying to use the same connection.

I don't think so. I can't think of a legitimate reason to use the connection at the same time.

e.g. the scaffolded test:

```ruby
class PostsTest < ApplicationSystemTestCase
  setup do
    @post = posts(:one)
  end

  test "visiting the index" do
    visit posts_url
    assert_selector "h1", text: "Posts"
  end
end
```

When the test code do DB operations, puma is idle, and when puma does db operations, the test code is using the browser driver.

So I really don't see how concurrent db operations would happen.

> I can't get over the thought that we simply need a proper thread-based Monitor in Ruby.

To be honest it's really debatable wether your code should have worked in the first place:

```ruby
Post.transaction do
 enum =  Enumerator.new do
   Post.first # stuck
 end
 enum.next
end
```

Here it's fine as the order of execution is predictable, but if you were to enable the fiber scheduler, then it would become very racy.

**Comment by ngan** [comment]
> When the test code do DB operations, puma is idle, and when puma does db operations, the test code is using the browser driver.

This is true for simple cases. But I suspect we have JavaScript that runs and does stuff and eventually makes a request to Puma causing it to serve a subsequent request while the test code is running. This means both threads would be using the db, no?

**Comment by casperisfine** [comment]
> But I suspect we have JavaScript that runs and does stuff and eventually makes a request to Puma causing it to serve a subsequent request while the test code is running.

Right, which makes me think that the lock should be much higher, e.g. in a rack middleware. 

This way we'd acquire the lock to enter the system test, release it when we call helpers such as `visit`.

**Comment by casperisfine** [comment]
Ok, I managed to repro using JS requests: https://github.com/casperisfine/rails-test-app/commit/1afdc07c352cc1376e956f042c9d754b77711680

**Comment by casperisfine** [comment]
As I suspected, turning off transactional fixtures solves the issues:

```
diff --git a/test/system/posts_test.rb b/test/system/posts_test.rb
index d464cf3..e23673d 100644
--- a/test/system/posts_test.rb
+++ b/test/system/posts_test.rb
@@ -1,6 +1,7 @@
 require "application_system_test_case"
 
 class PostsTest < ApplicationSystemTestCase
+  self.use_transactional_tests = false
   setup do
     @post = posts(:one)
   end
```

I'm really tempted to just get rid of that shared connection hack, and just disable transactional fixtures for system tests. That would make them a bit slower, but probably not enough to matter in most cases?

More importantly it would make them much more close to reality.

**Comment by eregon** [comment]
I had a call with @casperisfine about this issue.

First of all, in the cases it's possible it's best to avoid `Enumerator#{next*,peek*}` as that avoids this issue, but also passing extra state to it, etc.
If the Enumerator is used for e.g. batched queries or DB accesses, a good way is to reimplement those with manual Enumerators/"iterators". For example we can keep the DB cursor, and implement peek/next based on that, and that doesn't involve any Fiber and so just works.
I think this is worth exploring in Rails and might be little code to change, but for that we need to know what Enumerator is typically used for/what APIs would be needed to replace those `Enumerator`s by custom enumerators provided by Rails/AR/DB adapters (with the same methods as Enumerator but not using Fibers).

For the users of Enumerator within a transaction, could you share what you use Enumerator for and some code snippet closer to the actual logic (so it's not a trivial example where there is no need for `Enumerator`)?

If we introduce something like a per-thread monitor (https://bugs.ruby-lang.org/issues/19141), the problem is such a per-thread mutex or monitor would still not let Enumerator-with-Fiber work on a Fiber-based server like Falcon.
So it is an incomplete solution, but it may still be helpful. My current feeling is it's just a workaround, not a real solution.

As @casperisfine mentioned, it'd be nice if we could just remove the lock around the transaction, a lock held so long is likely to cause various problems. And the lock is only necessary for transactional fixtures system tests, which share the transaction and connection across threads (a rather hacky approach which also makes it really hard to reason about it).
Here is a few ideas how to still make transactional fixtures system tests work without the current lock:
* use a global (for all requests) lock on Puma threads. Unfortunately this is not enough with the JS example, as we have the main thread running asserts also accessing the connection. (if we also lock the test/main thread we didn't change anything)
* don't lock the whole transaction but lock only what's necessary around interactions (e.g., socket IO) with the DB. That probably means using asynchronous APIs for the DB, or if there isn't for a DB use a a Thread with a Queue which is the only one actually accessing the connection as a fallback which seems reasonable for system tests.
* are there maybe other mechanisms to efficiently "restore" fixtures after a system test? Maybe some kind of "save & restore" built in the DB which is fast enough? Or maybe for system tests the overhead of the drop + insert fixtures is fast enough or a small enough overhead compared to a system test?

I think the 2nd idea the most promising there, but needs some work in DB adapters, AR, etc.

In any case, using the lock only for the place it's needed (transactional fixtures system tests) in https://github.com/rails/rails/pull/46519 seems a good step forward.

**Comment by simi** [comment]
:information_source: cross-referencing https://github.com/rails/rails/pull/44219#issuecomment-1125524583

**Comment by kuahyeow** [comment]
Thanks for working on this @byroot (and others!)

It seems though the original report with multiple databases) is still hanging on LoadInterlockAwareMonitor. I switched to using edge rails, and the system test still hangs:


Here's a minimal reproduction with Rails 7.0.3.1

1.  Clone https://gitlab.com/tkuah/multi_database_system_test, `git clone https://gitlab.com/tkuah/multi_database_system_test.git`
2.  Checkout `rails-main` branch
3.  bundle install
4.  bundle exec rails db:migrate
5.  bundle exec rails test test/system/home_pages_test.rb

Observe it still hanging. Attached is the backtrace dump when it is hanging:
[sigdump-86440.log](https://github.com/rails/rails/files/10172374/sigdump-86440.log)

**Comment by byroot** [comment]
Right, we piggy backed on your issue because it was similar, but it's actually distinct.

We still have a deadlock scenario in `clear_query_caches_for_current_thread` in system tests that is unrelated to the Monitor change in Ruby 3.

**Comment by casperisfine** [comment]
I think I have a fix for your issue https://github.com/rails/rails/pull/46661

**Comment by casperisfine** [comment]
Ref: https://github.com/teamcapybara/capybara/issues/2623

**Comment by technicalpickles** [comment]
We've backported the fix from https://github.com/rails/rails/pull/46661 . Will followup after running it for a few days!
