### ISSUE TITLE
Where would a newcomer find that `:status` is a parameter on `render`?

### ISSUE THREAD

**Issue by dumbledad** [rails/rails#46022]
### Steps to reproduce

1. Imagine you are new to Rails and need to check which parameters can be passed to `ActionController::Rendering#render`
2. Go to the documentation https://api.rubyonrails.org/classes/ActionController/Rendering.html#method-i-render
3. Find any mention of the parameter `:status`

### Expected behavior
`render` is an important commonly used method on `ActionController::Rendering`. `:status` is an important commonly passed parameter. Therefore I expect Rails API documentation to tell me that `:status` is a possible parameter on `render`

### Actual behavior
None of the API documentation I can find for `render`, nor the API documentation for methods in render's calling chain like `render_to_body`, mention what the options parameter can be, i.e. I am never alerted to being able to include `:status`. 

### System configuration
**Rails version**:
<= 7

**Comment by dumbledad** [comment]
It is mentioned in the Layouts and Rendering in Rails guide, e.g. https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-an-action-s-view but I would expect not to have to read the guide to look up a method's available parameters.

**Comment by sreeram-venkitesh** [comment]
@p8 Like you mentioned in #46024, since `ActionController` is inherited from `AbstractController`, should we add this in the documentation for `AbstractController::Rendering#render` ([here](https://api.rubyonrails.org/classes/AbstractController/Rendering.html#method-i-render)) instead? How would you recommend we go about adding a section for `status` in the API docs?

**Comment by rafaelfranca** [comment]
https://api.rubyonrails.org/classes/ActionController/Renderer.html#method-i-render would be the right place since this is specific for Action Controller, not Abstract Controller.

**Comment by skipkayhil** [comment]
> https://api.rubyonrails.org/classes/ActionController/Renderer.html#method-i-render would be the right place since this is specific for Action Controller, not Abstract Controller.

Should the change made in #46024 also be pointing to this `#render` instead?

**Comment by p8** [comment]
Hmm, I think you are right about #46024 @skipkayhil.
I think I got confused because the Rendering#render doesn't exist but Renderer#render does:
https://edgeapi.rubyonrails.org/classes/ActionController/Rendering.html#method-i-render
https://edgeapi.rubyonrails.org/classes/ActionController/Renderer.html#method-i-render
cc @sreeram-venkitesh

**Comment by sreeram-venkitesh** [comment]
I've opened PR #46050 for this. Please review this and let me know if any changes are required.

What I understood from @dumbledad's requirement was that users should know that `status` is a possible parameter. No need to go in detail since its explained over at the [layouts and rendering guide](https://guides.rubyonrails.org/layouts_and_rendering.html#the-status-option) which was also linked by him. I've added the `status` option along with the rest of the parameters in [ActionController::Renderer#render](https://api.rubyonrails.org/classes/ActionController/Renderer.html#method-i-render).

**Comment by dumbledad** [comment]
@sreeram-venkitesh I'm too new to be familiar with rails idioms etc. so I won't submit a proper review, but that looks good to me.
