### ISSUE TITLE
`(5.minutes + 360.seconds).minutes` # => 660 minutes

### ISSUE THREAD

**Issue by dorianmariefr** [rails/rails#46066]
### Steps to reproduce

```ruby
>> (5.minutes + 360.seconds).minutes
=> 660 minutes
```

### Expected behavior

`11 minutes`

### Actual behavior

`660 minutes`

### System configuration
**Rails version**: Rails 7.0.3.1

**Ruby version**: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]`

**Comment by ume3119** [comment]
I was able to reporduce this as well.
ruby: ruby 3.1.1p18
rails: 7.0.3

<img width="527" alt="Screenshot 2022-09-19 at 16 44 35" src="https://user-images.githubusercontent.com/45059736/191009941-f5d15764-b088-4357-b6f2-3335d91d9492.png">

**Comment by ume3119** [comment]
The issue is these methods i.e minutes, hours are implemented only to take seconds and convert them into minutes or hours.
Here take a look at [this](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/duration.rb#L158) for example

Another example for hours.
<img width="503" alt="Screenshot 2022-09-19 at 16 52 54" src="https://user-images.githubusercontent.com/45059736/191011722-33b6df01-dc0d-46aa-92a2-ef37d54e36b8.png">

**Comment by fschwahn** [comment]
See https://github.com/rails/rails/issues/45433 which is (more or less) the same issue. Also, there's a proposed fix to mitigate this problem.
