### ISSUE TITLE
Query log tags docs are unclear on configuration steps 

### ISSUE THREAD

**Issue by bdewater** [rails/rails#46103]
I found the [Active Record query log tags documentation](https://api.rubyonrails.org/classes/ActiveRecord/QueryLogs.html) confusing on what needs to be configured in which file to result in the behaviour I was looking for. Happy to open a PR and make it more clear, but I also wanted to check I'm not running in a bug.

### Steps to reproduce
```
rails new query_log_tags
cd query_log_tags
bin/rails g scaffold post
bin/rails db:migrate
```
Reading the docs: "The tags used in a query can be configured directly [example 1] or via Rails configuration: [example 2]". Opening up `config/application.rb` and added a tweaked version of example 2:
```ruby
config.active_record.query_log_tags = [
  :controller,
  :action,
  :job,
  {
    request_id: ->(context) { context[:controller]&.request&.request_id },
    job_id: ->(context) { context[:job]&.job_id },
  },
]
```
run `bin/rails s` and visit http://localhost:3000/posts results in:
```
Post Load (0.1ms)  SELECT "posts".* FROM "posts"
```
That's not working. I find https://github.com/rails/rails/pull/42240 and learn about `query_log_tags_enabled` which is not mentioned in the docs at all 😬. 

The bottom of `config/application.rb` now looks like this:
```ruby
config.active_record.query_log_tags_enabled = true
config.active_record.query_log_tags = [
  :controller,
  :action,
  :job,
  {
    request_id: ->(context) { context[:controller]&.request&.request_id },
    job_id: ->(context) { context[:job]&.job_id },
  },
]
```
Restarting the Rails server and trying again results in:
```
Post Load (0.3ms)  SELECT "posts".* FROM "posts" Post Load (0.1ms)  SELECT "posts".* FROM "posts" /*controller:posts,action:index,request_id:486050d1-76c8-4afa-b88d-35b6ffb04ff4,controller:posts,action:index*/
```
I'm seeing double! Perhaps application.rb is too early in the boot process? I'll move it to `config/initializers/query_log_tags.rb` based on a mention of initializers at the bottom of the API guide and try again:
```ruby
Rails.application.config.active_record.query_log_tags_enabled = true
Rails.application.config.active_record.query_log_tags = [
  :controller,
  :action,
  :job,
  {
    request_id: ->(context) { context[:controller]&.request&.request_id },
    job_id: ->(context) { context[:job]&.job_id },
  },
]
```
Resulting in:
```
Post Load (0.1ms)  SELECT "posts".* FROM "posts" /*controller:#<PostsController:0x00000001080ec4d8>,request_id:6de8f562-cb44-4b71-ad53-db7d72a986cb*/
```
Not the controller output I was expecting and it's missing the action.

After some more fiddling, I get the expected output to work in the following way:
```ruby
# config/application.rb
config.active_record.query_log_tags_enabled = true

# config/initializers/query_log_tags.rb
Rails.application.config.active_record.query_log_tags = [
  :controller,
  :action,
  :job,
  {
    request_id: ->(context) { context[:controller]&.request&.request_id },
    job_id: ->(context) { context[:job]&.job_id },
  },
]
```
Result:
```
Post Load (0.1ms)  SELECT "posts".* FROM "posts" /*controller:posts,action:index,request_id:8f56eaac-c05a-406a-9df4-692055f1a58f*/
```

### How to fix [the documentation](https://api.rubyonrails.org/classes/ActiveRecord/QueryLogs.html)
While this split between `application.rb` and an initializer works, it seems overly dependant on the order of the Rails initialization process and when the [Action Controller](https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/actionpack/lib/action_controller/railtie.rb#L108-L124) and [Active Job](https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/activejob/lib/active_job/railtie.rb#L60-L72) railties are lazily loaded? 

If it is supposed to work this way, that deserves to be documented more clearly alongside the the missing mention of `query_log_tags_enabled = true`. I'm happy to rewrite the docs after confirmation this is working correctly or not.

### System configuration
**Rails version**:
7.0.4
**Ruby version**:
3.1.2

**Comment by skipkayhil** [comment]
> While this split between `application.rb` and an initializer works, it seems overly dependant on the order of the Rails initialization process and when the [Action Controller](https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/actionpack/lib/action_controller/railtie.rb#L108-L124) and [Active Job](https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/activejob/lib/active_job/railtie.rb#L60-L72) railties are lazily loaded?

Yeah, this doesn't seem ideal. As you point out, what's happening is this:

- `config/application.rb` is loaded
- framework initializers run
  - if `config.active_record.query_log_tags_enabled = true` then append `:controller, :action` and `:job` to `config.active_record.query_log_tags` and setup `taggings` for them
- application initializers run
- `after_initialize`
  - `ActiveRecord::QueryLogs.tags = config.active_record.query_log_tags`

So there are a few important things to note:
- for the `taggings` to be setup for Action Controller and Active Job, `config.active_record.query_log_tags_enabled` MUST be set in `config/application` (or `config/<env>`). The `controller:#<PostsController:0x00000001080ec4d8>` type output is the result of the `taggings` not being set up
- `:controller`, `:action`, and `:job` will all be appended to `query_log_tags` if you configure them in `config/application` or `config/<env>`. If you include any of those values when configuring `query_log_tags` in `config/application` or `config/<env>` then you will get duplicates.

---

I think a documentation update would definitely help clarify some of the complexity here. I'm also wondering if there's a way that the configuration could be refactored so that it doesn't end up so complex.
