### ISSUE TITLE
Member route takes priority over collection route leading to exception

### ISSUE THREAD

**Issue by tylerdiaz** [rails/rails#46135]
It's unclear to me whether this is a bug or a rule we couldn't spot in the documentation. In either case, it caught our team by surprise.

### Steps to reproduce

Here is a repository with a specific commit for reproduction code: https://github.com/tylerdiaz/RailsRouteBugExample/commit/b5d4fa78b48b683265d5dbb72c178e47dddb10f7

In short:

1. Create a member route that takes a parameter `/:id`
2. Create a collection route like `get :approved`
3. Visit new collection url: http://localhost:3000/comments/approved 
4. Response is an exception (500) `ActiveRecord::RecordNotFound in CommentsController#show \n Couldn't find Comment with 'id'=approved` instead of 200.

```ruby
resources :comments do
  member do
    get :show
  end

  collection do
    get :approved
  end
end
```

### Expected behavior
Expected collection route (/comments/approved) to be handled before member route (/comments/:id). 

### Actual behavior
Member route is handled first and returns 500 since it does not have expected parameters.

### System configuration
**Rails version**: 7.0.3
**Ruby version**: 2.7.1

cc @benjichen16 @john-diaz

**Comment by clouvet** [comment]
@tylerdiaz, `/comments/approved` matches the requirements for the explicit member `show` route. Because the member `show` route is first in the file, it gets selected. ["Rails routes are matched in the order they are specified."](https://guides.rubyonrails.org/routing.html#resource-routing-the-rails-default)

Maybe part of the confusion here comes from having two `show` routes?

Here's the relevant output of `rails routes`: 
```
             Prefix Verb   URI Pattern                        Controller#Action
             comment GET    /comments/:id(.:format)            comments#show
   approved_comments GET    /comments/approved(.:format)       comments#approved
            comments GET    /comments(.:format)                comments#index
                     POST   /comments(.:format)                comments#create
         new_comment GET    /comments/new(.:format)            comments#new
        edit_comment GET    /comments/:id/edit(.:format)       comments#edit
                     GET    /comments/:id(.:format)            comments#show
                     PATCH  /comments/:id(.:format)            comments#update
                     PUT    /comments/:id(.:format)            comments#update
                     DELETE /comments/:id(.:format)            comments#destroy
```

The first `show` route comes from the member block, while the second `show` route comes from calling `resources :comments`. In this specific example, you don't need the member block. 

If you want only the show route and none of the other CRUD, you can use the `only:` option for the resource:
```ruby
resources :comments, only: [:show] do
  collection do
    get :approved
  end
end
```
If you give that member route a different, non-CRUD-conventional name, you end up with a different URL structure that doesn't conflict with the collection URL:
```ruby
resources :comments, only: [:show] do
  member do
    get :example
  end

  collection do
    get :approved
  end
end
```
```
   example_comment GET    /comments/:id/example(.:format)  comments#example
```

So in this case, by adding a duplicate `show` route, the actual behavior is the expected behavior.
