### ISSUE TITLE
Can not configure the connection using mysql2 & Rail 7.0.4

### ISSUE THREAD

**Issue by snowsolutions** [rails/rails#46145]
### Steps to reproduce
```
- OS: Ubuntu 20.04 on WSL2
- install Rails 7.0.4 with Ruby 2.7.2
- install mysql2 gem & activerecord-mysql2-adapter
- config database.yml with database variable
```
```ruby
default: &default
  adapter: mysql2
  encoding: utf8
  database: rb_ezcollect
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "rb_ezcollect"
```

### Expected behavior

- Application boot up with no error

### Actual behavior

- Application boot up throw error
```
can't modify frozen Hash: {:adapter=>"mysql2", :encoding=>"utf8", :database=>"rb_ezcollect", :username=>"root", :password=>"root", :host=>"127.0.0.1", :port=>3306, :pool=>5, :timeout=>5000}
```
![image](https://user-images.githubusercontent.com/42315625/192755538-1da00422-e4e4-4241-b383-912f7c59b27c.png)

### System configuration
**Rails version**: 7.0.4
**Ruby version**: 2.7.2

**Comment by yahonda** [comment]
`activerecord-mysql2-adapter` is not Rails bundled one. It is https://rubygems.org/gems/activerecord-mysql2-adapter/versions/0.0.3 because this exception has been raised at this line.

https://github.com/kronn/activerecord-mysql2-adapter/blob/433f145073262b1d54de471b5366c023aa6b81a7/lib/active_record/connection_adapters/mysql2_adapter.rb#L11

Just remove this kind of line from your Gemfile. Or report it to https://github.com/kronn/activerecord-mysql2-adapter
```
gem 'activerecord-mysql2-adapter'
```

**Comment by eileencodes** [comment]
[activerecord-mysql2-adapter](https://github.com/kronn/activerecord-mysql2-adapter) does not look maintained anymore (last update in 2012), and it's not an official active record adapter so I'm going to close this. The official adapter is mysql2_adapter and is part of Rails.
