### ISSUE TITLE
sanitize_sql_array converts numeric values into string

### ISSUE THREAD

**Issue by vsandeepdev** [rails/rails#46221]
### Steps to reproduce

I encountered this issue after upgrading my application to rails 7, it was working fine in rails 6.
```ruby
updates = ["`bed_count` = `bed_count` + ?", "`operating_room_count` = `operating_room_count` + ?", "`updated_at` = ?"]
values = [3.14159, 1, "2022-09-17 18:15:05"]
ActiveRecord::Base.send(:sanitize_sql_array, [updates.join(','), *values])
```

If you look carefully in the values array, two of my values are numeric but as output it converts them into string. See Actual  behaviour.

### Expected behavior

"`bed_count` = `bed_count` + 3.14159,`operating_room_count` = `operating_room_count` + 1,`updated_at` = '2022-09-17 18:33:44'"

### Actual behavior

"`bed_count` = `bed_count` + '3.14159',`operating_room_count` = `operating_room_count` + '1',`updated_at` = '2022-09-17 18:33:44'"

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**Comment by nvasilevski** [comment]
If not a duplicate, must be very similar to https://github.com/rails/rails/issues/44312

In which case I'm afraid this is expected behavior and was introduced intentionally to close a vulnerability

Unrelated but `sanitize_sql_array` doesn't seem to be private so you should be able to just do `ActiveRecord::Base.sanitize_sql_array([updates.join(','), *values])`

**Comment by byroot** [comment]
Yes, this is a duplicate of https://github.com/rails/rails/issues/44312, and is expected behavior for MySQL. I know it's annoying, but that is unfortunately necessary to avoid some security issues.

Please refer to that other issues for the various ways to handle casting.
