### ISSUE TITLE
Strict loading, opt in action per request

### ISSUE THREAD

**Issue by mildred** [rails/rails#46234]
Strict loading is very nice to prevent the N=1 query issue. However, with an existing codebase it is difficult to convert the code enough to be strict loading safe enough to use the raise action.

It would be nice if strict loading could be opt-in per request where we could make new requests raise an error and existing requests just log the error. 

Perhaps the easiest way could be to allow custom actions on `action_on_strict_loading_violation` (a proc could be given for example). Ideally the proc could access the current request and controller

**Comment by eileencodes** [comment]
Hey @mildred thanks for the suggestion. In general we don't accept feature requests on the issues tracker because it is reserved for bugs in the framework. In most cases we ask that the requester either do the implementation themselves or open a discussion on the [forum](https://discuss.rubyonrails.org/) to see if anyone else would like to pick it up. If you want to work on it and need help, you can use our [Discord](https://discord.gg/xSb5z6GK) to ask for advice.

That aside I'm not sure how valuable this feature would be for applications in general. We already support per-model enable/disable since https://github.com/rails/rails/pull/39491 and I think it would be unwieldy to do it by request rather than by model. If you want to try implementing it might be easier to see the value when we see the code, but it's up to you.

**Comment by eileencodes** [comment]
Gonna close this since we don't have feature requests here but please do reach out on the Discord if you have questions about contributing 😄
