### ISSUE TITLE
Methods generated by enums may override methods without a warning

### ISSUE THREAD

**Issue by arielj** [rails/rails#46247]
When defining an enum, it creates extra instance and class methods for `#{value}?` and `#{value}!`. Before defining them it does some checks but the checks are not thorough and methods end up overridden with no warning to the developer.

### Steps to reproduce

For example, `frozen` as an enum value creates the `frozen?` method that overrides the method defined by ActiveRecord's core with a completely different internal logic.

```rb
class SomeModel < ApplicationRecord
  puts "frozen? before enum"
  puts instance_method(:frozen?).source_location.inspect
  enum :status, %i[pending ready frozen canceled]
  puts "frozen? after enum"
  puts instance_method(:frozen?).source_location.inspect
end
```

outputs:
```
frozen? before enum
[".../rails/activerecord/lib/active_record/core.rb", 593]
frozen? after enum                    
[".../rails/activerecord/lib/active_record/enum.rb", 251]
```

I understand we could add `frozen?` to this list to fix this specific one https://github.com/rails/rails/blob/main/activerecord/lib/active_record/attribute_methods.rb#L37

But the issue is that a list of methods needs to keep up to date manually. Maybe any method in that list should raise errors but if we detect that a method already exist (but not in that list) we could at least print a warning in the console?

Also related, if an `enum` declaration does NOT define its methods, there's no indication either (I don't understand yet why in this case it's not overriding the `ready?` method):

```rb
class MyModel < ApplicationRecord
  def ready?
  end

  puts "ready? before enum"
  puts instance_method(:ready?).source_location.inspect
  enum :status, %i[pending ready frozen canceled]
  puts "ready? after enum"
  puts instance_method(:ready?).source_location.inspect
end
```

outputs:
```rb
ready? before enum
[".../app/models/my_model.rb", 2]
ready? after enum
[".../app/models/my_model.rb", 2]
```

### Expected behavior

Enums should NOT silently override methods. It should either raise an error or show a warning so the developer can pick a different value, but not be silent. Also, failing to add an enum method should not be silent either.

### Actual behavior

If an enum declaration fails to detect that it would override an important method and it actually does override it, there's no indication anywhere that that's happening.

Similarly, if the method that the enum wants to create already exists and is not overriden, it should also show some indication to the developer.

### System configuration
**Rails version**: main branch

**Ruby version**: 3.1.0

**Comment by casperisfine** [comment]
Agreed that we should check for the `dangerous_attribute_methods` list, just like for attribute methods.

The code generation could use a revamp as well, there are a few small inefficiencies.

**Comment by dsusviela** [comment]
I did some digging into this, and apparently the method you mentioned was recently touched in #45883

In the PR it states:

> So I propose to add a small explicit list of the most likely used dangerous methods. I did not add __send__/send/method_missing/etc (as mentioned in https://github.com/rails/rails/issues/45879#issuecomment-1226293544), because they require arguments and this will already blow up and won't go unnoticed.

I think that they just forgot to add `frozen?` into this array because its part of the Kernel, and AFAIK its the only method together with `tainted?` from this module that hasn't been considered that takes in no arguments.

However I do think that this list is rather arbitrary and as you mentioned, it requires to be manually updated. One would be tempted to just add the `Object.instance_methods` instead of this list, but Rails wants to be flexible enough to allow somewhat non-problematic methods that depict "normal" words. For example; `display` is "common" word and the method it implements has a use case that is niche enough for Rails to say, ok we can override this. Arguably that's the same with `frozen`.

So I think that's why they took the compromise to do the solution they did. For your case I think you can get away with adding the value.

On a very tangential note;

We do have a situation tho if we use `frozen?` as a possible value instead, that's because the method `frozen?` will defined for the class (to create the scope), therefore we will be using the `dangerous_class_method?(method_name)` instead.  Since the condition to mark it as dangerous methods `ActiveRecord::Base` has *not* redefined from the original `Object`, `frozen?` will pass. Why is this a problem? Because when calling the association, we will go through many places, but the important one is [this method](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/module/introspection.rb#L15) in active support which will trigger a recursive call.

Lmk if i made any mistakes

**Comment by casperisfine** [comment]
👍 to adding `frozen` to the list of dangerous methods.

**Comment by ghiculescu** [comment]
Closed in https://github.com/rails/rails/pull/46394
