### ISSUE TITLE
Purging An Attachment Does Not Purge Blob of Active Record Variants

### ISSUE THREAD

**Issue by kad92** [rails/rails#46389]
### Steps to reproduce

Define model:

```
class ExampleModel < ActiveRecord::Base
   has_one_attached :photo
end
```

Attach an image to a model through Rails console:

```
example_model = ExampleModel.find(pass the id of the example model)
example_model.photo.attach(io: URI.open('https://thispersondoesnotexist.com/image'), filename: 'example.png', content_type: 'image/png')
```

Create a variant Rails console:
```
example_model.photo.variant(resize_to_limit: [75,75])
```

Purge attachment through Rails console:

```
example_model.photo.purge
```

### Expected behavior
The blob of the variant record should be deleted as well.

### Actual behavior
The variant record gets deleted, but its blob is not deleted.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.6.1

**Comment by fatkodima** [comment]
Can you verify if this is still happening on the `main` branch?

**Comment by alexandreruban** [comment]
I couldn't reproduce on `main`, both blobs ended up being destroyed:

```sh
> user.photo.purge

Disk Storage (0.6ms) Deleted file from key: x4ny1mf3zmxpb93we952exypq30n
Disk Storage (0.1ms) Deleted files by key prefix: variants/x4ny1mf3zmxpb93we952exypq30n/
```

**Comment by hungmi** [comment]
This is still happening with Rails 6.1.7, but not on 7.0.4.3.
It's not a big problem to us, because we have a daily rake task to purge all redundant blobs: https://guides.rubyonrails.org/active_storage_overview.html#purging-unattached-uploads
This will also purge those photo variants because they will become unattached after `example_model.photo.purge`.
