### ISSUE TITLE
[BUG] Active Record `only_integer: true` validation doesn't always work with `accepts_nested_attributes_for`

### ISSUE THREAD

**Issue by mrabets** [rails/rails#46509]
### Steps to reproduce
**1. Create `Post` and `Comments` models with `has_many` association and `accepts_nested_attributes_for`**

`app/models/post.rb`
```
class Post < ApplicationRecord
  has_many :comments

  accepts_nested_attributes_for :comments
end
```
`app/models/comment.rb`
```
class Comment < ApplicationRecord
  belongs_to :post

  validates :likes_count, numericality: { only_integer: true  }
end
```

**2. Setup posts params for nested attributes in the controller**

`app/controllers/posts_controller.rb`
```
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
    @post.comments.build
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params
        .require(:post)
        .permit(:title,
                comments_attributes: [:id, :post_id, :likes_count])
    end
end

```

**3. Setup posts form**

`app/views/posts/_form.html.erb`
```
<%= form_with(model: @post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="nested_field">
    <%= form.fields_for :comments do |comment_subform| %>
      <%= comment_subform.label :likes_count %>
      <%= comment_subform.text_field :likes_count %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
```

**4. Create a post with `likes_count = 5`. Go to the edit page of this post and change `likes_count` to `5.1` (or any float number from `5.0` to `5.999...`)**

### Expected behavior
Should generates the error message: **"Must be integer"**

### Actual behavior
It doesn't generate the error message and it saves the record

### System configuration

Rails version: 7.0.4 (tried also with 6.1.5)

Ruby version: 2.7.6

### Video showing the bug

https://user-images.githubusercontent.com/36799843/202196709-13d04e96-483c-4faf-88b2-d4225133f319.mp4

**Comment by fatkodima** [comment]
I was not able to reproduce it and the video link is broken.
Can you create a small rails app that reproduces an issue and share with us?

**Comment by simi** [comment]
@fatkodima :thinking: video works for me.

**Comment by fatkodima** [comment]
Ah, ok, thanks. I have an old Safari, works in Chrome.

**Comment by fatkodima** [comment]
Ok, I identified a problem. The problem is really not in the `accepts_nested_attributes`, but in how Active Record identifies if the attribute changed or not.

To reproduce the issue (this is demonstrated in video also), create a Post with nested Comment with a valid `likes_count` value (for example, 5). Try to edit/update the record by changing its value's fractional part only (e.x., 5.2) and the record will be saved successfully, because the nested record was not changed (as per Active Record change detection) and thus validation was not run. If you change an integral part too (e.x, 6.2), you will get the expected validation error.

Simply speaking:
```ruby
comment.likes_count # => 4
comment.likes_count = "4.2"
comment.changed? # => false
comment.likes_count = "5.2"
comment.changed? # => true
```

This is also described in a test case: 
https://github.com/rails/rails/blob/994bce4e32306b957eb61b8d6edd1cbb3f3120b8/activemodel/test/cases/attributes_dirty_test.rb#L188-L200

You can trace the relevant logic for nested attributes implementation from here https://github.com/rails/rails/blob/994bce4e32306b957eb61b8d6edd1cbb3f3120b8/activerecord/lib/active_record/nested_attributes.rb#L362 and here https://github.com/rails/rails/blob/994bce4e32306b957eb61b8d6edd1cbb3f3120b8/activerecord/lib/active_record/autosave_association.rb#L319-L325  

So, seems like we could do nothing with this.

**Comment by ghiculescu** [comment]
Hmm, I think the issue is that no validation warning shows if you save via nested attributes. But it *does* if you save the record directly. Executable test case to show what I mean:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.integer :likes_count
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  accepts_nested_attributes_for :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  validates :likes_count, numericality: { only_integer: true }
end

class BugTest < Minitest::Test
  def test_bug_with_direct_access
    comment = Comment.new(likes_count: 4)
    assert comment.valid?
    assert comment.save

    comment.likes_count = 4.1
    assert !comment.valid?
    assert !comment.save
    assert_equal ["Likes count must be an integer"], comment.errors.to_a

    assert_equal 4, comment.reload.likes_count
  end

  def test_bug_with_nested_attributes_and_update
    post = Post.create
    comment = post.comments.create(likes_count: 4)

    post.update(comments_attributes: { id: comment.id, post_id: post.id, likes_count: 4.1 })
    assert_equal [], post.errors.to_a # I think the issue is expecting something here

    assert_equal 4, comment.reload.likes_count
  end

  def test_bug_with_nested_attributes_and_assign
    post = Post.create
    comment = post.comments.create(likes_count: 4)

    post.assign_attributes(comments_attributes: { id: comment.id, post_id: post.id, likes_count: 4.1 })
    assert post.valid?
    assert_equal [], post.errors.to_a
    assert_equal [], post.comments.first.errors.to_a # I think the issue is expecting something here
    assert post.save

    assert_equal 4, comment.reload.likes_count
  end
end
```

**Comment by fatkodima** [comment]
Child records changes are not detected (because of the reasons I mentioned in the previous comment) here - https://github.com/rails/rails/blob/38d79151022217c238a648e76b484fb1e6ee7261/activerecord/lib/active_record/autosave_association.rb#L319-L325
https://github.com/rails/rails/blob/38d79151022217c238a648e76b484fb1e6ee7261/activerecord/lib/active_record/autosave_association.rb#L282-L283
https://github.com/rails/rails/blob/38d79151022217c238a648e76b484fb1e6ee7261/activerecord/lib/active_record/autosave_association.rb#L271-L273

So that is why records are saved without validations. Not sure how `accepts_nested_attributes_for` logic should be changed to not rely on `changed?`.

**Comment by ghiculescu** [comment]
I agree it's not yet clear the solution. But thinking out loud, `changed?` doesn't seem to matter when not using nested attributes. This passes, with an extra assertion added compared to last time:

```ruby
  def test_bug_with_direct_access
    comment = Comment.new(likes_count: 4)
    assert comment.valid?
    assert comment.save

    comment.likes_count = 4.1
    assert !comment.changed? # The comment is not considered changed, but validation still fails and adds an error.
    assert !comment.valid?
    assert !comment.save
    assert_equal ["Likes count must be an integer"], comment.errors.to_a

    assert_equal 4, comment.reload.likes_count
  end
```

**Comment by dsusviela** [comment]
Noob here trying to chime in with some questions

From what i saw, the validation is failing because its comparing the value against `record.likes_count_before_type_cast`, and not against `record.likes_count` itself. The check is being done over at `/activemodel/lib/active_model/validations/numericality.rb#129`.

I guess this is expected, however `likes_count` stays at 4 and that makes `changed?` not realize that there was an at

```ruby
comment.likes_count = 4.1
comment.valid? # false & this makes sense

puts comment.likes_count # this is still 4
puts comment.likes_count_before_type_cast # this is 4.1 which causes validation to fail
```

Would it make sense to have a method `raw_value_changed?` that gives true if the `raw_value` changed, and then compare against `changed` and `raw_value_changed?` when determining to run the validations?

Maybe i got all wrong 😅

**Comment by JohnAnon9771** [comment]
> I agree it's not yet clear the solution. But thinking out loud, `changed?` doesn't seem to matter when not using nested attributes. This passes, with an extra assertion added compared to last time:
> 
> ```ruby
>   def test_bug_with_direct_access
>     comment = Comment.new(likes_count: 4)
>     assert comment.valid?
>     assert comment.save
> 
>     comment.likes_count = 4.1
>     assert !comment.changed? # The comment is not considered changed, but validation still fails and adds an error.
>     assert !comment.valid?
>     assert !comment.save
>     assert_equal ["Likes count must be an integer"], comment.errors.to_a
> 
>     assert_equal 4, comment.reload.likes_count
>   end
> ```

I thought of a solution that checks if there were changes in relation to the value before the type_cast, something like `likes_count_raw_changed?` (I still don't know how it could be). Then from these changes in raw values could be pulled into `associated_records_to_validate_or_save` to run a validation. What do you think? I made a pseudo code and apparently it fixed it. But I still have uncertainties to be able to open the PR.
