### ISSUE TITLE
String.pluralize  ignores I18n.locale, I18n.default_locale 

### ISSUE THREAD

**Issue by jpgeek** [rails/rails#46526]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_pluralize_respects_i18n_locale
    I18n.available_locales = [:en, :ja]
    I18n.locale = :en
    assert_equal("blargles", "blargle".pluralize(2))
    I18n.locale = :ja # :ja has no plurals, does not add "s"
    assert_equal("blargle", "blargle".pluralize(2))
  end

  def test_pluralize_respects_i18n_default_locale
    I18n.available_locales = [:en, :ja]
    I18n.default_locale = :en
    assert_equal("blargles", "blargle".pluralize(2))
    I18n.default_locale = :ja # :ja has no plurals, does not add "s"
    assert_equal("blargle", "blargle".pluralize(2))
  end
end
```

### Expected behavior
When no locale is passed as a parameter to `pluralize()`, it should use I18n.locale.

### Actual behavior
It ignores I18n.locale and uses :en.

### System configuration
**Rails version**:7.04, 7.1.0.alpha

**Ruby version**:3.1.2

I am happy to send a pr after this is confirmed.

**Comment by fatkodima** [comment]
There is view helper that uses `I18n.locale` as the default, see - https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-pluralize

I am sure just bare `pluralize` uses `:en` as the default, because Rails internally uses this method for its needs, for example to generate a table name from the model name etc and this should always be in English.

So you can manually pass a locale if you want a different behavior.

**Comment by jpgeek** [comment]
Thanks @fatkodima.  
I knew about the Actionview::Helpers method, just that it is more verbose and doesn't chain well.  In any case it does look like pluralize is used internally in quite a few places without specifying `:en` , so it probably isn't going to change.
