### ISSUE TITLE
Incorrect error message when mistyped validation in related association

### ISSUE THREAD

**Issue by loqimean** [rails/rails#46532]
### Steps to reproduce

```ruby
class Parent < ApplicationRecord
  has_one :child, dependent: :destroy
end

class Child < ApplicationRecord
  belongs_to :parent
  
  valisates :something, presen: true
end
```

### Expected behavior
Rails shows error of mistyping, like a "`method_missing': undefined method `valisates' for Child:Class (NoMethodError)"

### Actual behavior
Instead of this I have had an error:
"Rails couldn't find a valid model for Child association. Please provide the :class_name option on the association declaration. If :class_name is already provided, make sure it's an ActiveRecord::Base subclass.

          raise NameError, msg"
And spent a lot of my time to resolve this issue by a relation changing

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.2

**Comment by fatkodima** [comment]
Works for me as expected. Can you create a reproducible example using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb or create a sample app and share with us?

**Comment by nvasilevski** [comment]
But `valisates` is a non-existing method and that's what the error is telling us. Am I missing something?
`presen: true` is also wrong

There is really not much about rails, it's more about ruby and I wonder if there was a suggestion generated by https://github.com/ruby/did_you_mean telling that perhaps you meant to use `validates` instead of `valisates`

**Comment by rafaelfranca** [comment]
I think we can't reproduce outside of a Rails app. It is related to autoloading and probably only happens when the `Parent` class is loaded before the `Child` class. It happens in this code here https://github.com/rails/rails/blob/28b5771d559f0ce538a68335bac8e202410b3ab8/activerecord/lib/active_record/reflection.rb#L421-L443.

I'm pretty sure we have another issue related to this. Loading `Child` will raise an exception that then we transform in NameError, and then we show that exception message instead of the original NoMethodError. Maybe we should include the original exception message in our message.

**Comment by ghiculescu** [comment]
> Maybe we should include the original exception message in our message.

https://github.com/rails/rails/pull/46560

**Comment by ghiculescu** [comment]
I made a test app to replicate the issue. And this is the error page I got:

<img width="1707" alt="image" src="https://user-images.githubusercontent.com/509837/204401187-033c424f-9b0b-46d3-b80b-aec1d2f8a65a.png">

If you click on the cause it expands to show the original error:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/509837/204401243-9ebaf4c3-1f6b-4b1a-ae09-aac110423138.png">

This is with:
<img width="944" alt="image" src="https://user-images.githubusercontent.com/509837/204401304-f8b510af-7f67-4a9f-a00f-8f7d60b790af.png">

@loqimean did you see a similar error page?

**Comment by loqimean** [comment]
> I made a test app to replicate the issue. And this is the error page I got:
> 
> <img alt="image" width="1707" src="https://user-images.githubusercontent.com/509837/204401187-033c424f-9b0b-46d3-b80b-aec1d2f8a65a.png">
> 
> If you click on the cause it expands to show the original error:
> 
> <img alt="image" width="1082" src="https://user-images.githubusercontent.com/509837/204401243-9ebaf4c3-1f6b-4b1a-ae09-aac110423138.png">
> 
> This is with: <img alt="image" width="944" src="https://user-images.githubusercontent.com/509837/204401304-f8b510af-7f67-4a9f-a00f-8f7d60b790af.png"> (I tried with Ruby 2.7 and got the same 👍 )
> 
> @loqimean did you see a similar error page?

yeah, me too
