### ISSUE TITLE
Crashes with "rb_vm_insn_addr2insn: invalid insn address"

### ISSUE THREAD

**Issue by turion** [rails/rails#46540]
### Steps to reproduce

1. Install Mastodon 4.0.2 on a recent NixOS machine with nixos-unstable.
2. Observe frequent HTTP 502 errors, look into the server log.
3. Find many lines like `Nov 21 15:25:18 manuelbaerenz puma[1006220]: /nix/store/1m8li3dkfj33kk4xhx6bhjbqi6y9bq6x-mastodon-gems-4.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/json/encoding.rb:58: [BUG] rb_vm_insn_addr2insn: invalid insn address: 0x00007f0646b56e20`

### Expected behavior
 
No crash

### Actual behavior

A crash, starting with `Nov 21 15:25:18 manuelbaerenz puma[1006220]: /nix/store/1m8li3dkfj33kk4xhx6bhjbqi6y9bq6x-mastodon-gems-4.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/json/encoding.rb:58: [BUG] rb_vm_insn_addr2insn: invalid insn address: 0x00007f0646b56e20` and with a long stacktrace, e.g. https://github.com/mastodon/mastodon/files/10057376/mastodon.log.

Also see https://github.com/mastodon/mastodon/discussions/21311.

### System configuration
**Rails version**: 6.1.7

**Ruby version**: 3.0.4

System: NixOS-unstable

**Comment by eileencodes** [comment]
Hey - if the crash is in Ruby then it needs to be reported (with a core dump ideally and the full stack trace) to https://bugs.ruby-lang.org/. This is the issues tracker for the Rails framework. Usually segv crashes aren't caused by Rails but by Ruby. We don't have any other reports of this that I can find (on Ruby or on Rails) so it's also possible it's related specifically to your OS, but the Ruby core team would be more likely to know the answer.

Before you open an issue over on ruby-lang, I would recommend upgrading to Ruby 3.0.4 first, it's possible the crash is fixed.

**Comment by turion** [comment]
Reported as a ruby bug in https://bugs.ruby-lang.org/issues/19140
