### ISSUE TITLE
Also in Rails 6, should not require 'selenium-webdriver' gem with non-selenium drivers

### ISSUE THREAD

**Issue by yokoto** [rails/rails#46695]
Since https://github.com/rails/rails/pull/39179 and https://github.com/rails/rails/pull/42672, `selenium/webdriver` seems to be required only when using the `:selenium` driver.

However, the commit of https://github.com/rails/rails/pull/42672 is released for Rails 7.0.0 and above, although https://github.com/rails/rails/pull/39179 is for Rails 6.0.1 and above.

Now, unless Rails 7.0.0 and above, `selenium/webdriver` is still required even when using non-selenium drivers(such as Poltergeist, [Cuprite](https://github.com/rubycdp/cuprite), etc.).

### Expected behavior
Non-selenium drivers are available without `selenium/webdriver` in Rails **6.0.1** and above.

### Actual behavior
Non-selenium drivers are available without `selenium/webdriver` in Rails **7.0.0** and above.

**Comment by skipkayhil** [comment]
Hey @yokoto, thanks for opening an issue! The only release of Rails accepting bug fixes is 7.0, and 6.0 in particular is only accepting Severe Security fixes. You can view the maintenance policy [here](https://guides.rubyonrails.org/maintenance_policy.html)

I recommend upgrading to a more recent release as soon as you can so that you can receive the latest bug fixes
