### ISSUE TITLE
[ActiveRecord] Allow alias_attributes in includes() and joins()

### ISSUE THREAD

**Issue by OskarEichler** [rails/rails#46959]
As far as I can tell it is currently not possible to use alias_attributes for .includes() and .joins() in ActiveRecord.

Here is an example:

```
class Artist
  has_many :tracks
  alias_attribute :songs, :tracks
end
```

When performing the following query everything works fine:
`Artist.includes(:tracks).last`

However when using the alias_attribute it gives an error:
`Artist.includes(:songs).last`

--> ActiveRecord::AssociationNotFoundError: Association named 'songs' was not found on Artist; perhaps you misspelled it?

It would be great if ActiveRecord could recognize the alias_attributes and replace them when generating the query!

**Comment by nvasilevski** [comment]
To be honest I'm surprised `alias_attribute` on an association works as I don't think it was intended to be used like this. Most likely  `artist.songs`  works because the reader for an aliased attribute simply calls into the original. But `songs` is not being treated as an association on the `Artist` model which means most of the association-related logic won't work.

It would work if there was a capability like `alias_association` which doesn't exist at the moment.

The easiest way to achieve similar behavior would be to define another association like:
```ruby
class Artist < ActiveRecord::Base
  has_many :tracks
  has_many :songs, class_name: "Track"
end
```
but it has its own implications as its not going to be treated as an alias and loading `tracks` association wouldn't mean loading `songs` association even though they represent the same relation

**Comment by OskarEichler** [comment]
@nvasilevski Your example is indeed exactly how we solved it as well... `alias_associations` would be awesome though! 🙌🏼

**Comment by ghiculescu** [comment]
@OskarEichler thanks for the feedback, we do reserve this issue tracker for bugs though. A PR that proposes `alias_associations` would be cool, if you want more feedback the [discussion forum](https://discuss.rubyonrails.org/) is a good place to start.
