### ISSUE TITLE
`form_with` ignores `inflect.uncountable` with namespaced model

### ISSUE THREAD

**Issue by smitssjors** [rails/rails#47006]
### Steps to reproduce

None of the provided test cases included all the aspects but the following commands set up a new project which exhibits the bug.
```bash
rails new bug
cd bug
echo "ActiveSupport::Inflector.inflections(:en) do |inflect| inflect.uncountable(\"stripe\"); end" >> config/initializers/inflections.rb
rails g scaffold endpoints/stripe
rails db:migrate
rails s
```
Then head over to `localhost:3000/endpoints/stripe/new`

### Expected behavior

Rails can properly render the form with the action pointing to `endpoints_stripe_path`

### Actual behavior

Rails throws an `ActionView::Template::Error (undefined method 'endpoints_stripes_path' for #<ActionView::Base:0x000000000099e8>`

A workaround is adding `inflect.uncountable("endpoints_stripe")` or `inflect.plural("stripe", "stripe")` before the original call to `inflect.uncountable("stripe")`

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.0.2

**Comment by andrewn617** [comment]
Hi @smitssjors I took a look into this issue. 

It looks like the problem is happening when determining the `@route_key` in `ActiveModel::Naming`. We call `ActiveSupport::Inflector.pluralize` on the namespaced string `endpoints_stripe` (`activemodel/lib/active_model/naming.rb:182`).

The inflector does check if the string is `uncountable` (`activesupport/lib/active_support/inflector/methods.rb:379`). However the regex it uses is `\bstripe\Z`, which is looking for a word boundary. So `endpoints_stripe` is not matched by that regex. 

Unfortunately, the rails team is not accepting any patches to the inflector, so I don't think this issue can be fixed. The best course of action is to continue using the `inflect.plural("stripe", "stripe")` work around.
