### ISSUE TITLE
Speed up ActiveRecord::Relation#blank?

### ISSUE THREAD

**Issue by tracyloisel** [rails/rails#47195]
### Steps to reproduce

1. Take any model
2. Apply any scope
3. call #blank? method

```ruby
any_scope.blank?
```

### Expected behavior
It should call #empty? so if the collection has not been already loaded it will call #exists? and will return result much faster

### Actual behavior
it currently loads the entire relation no matter if the collection has been already loaded or not

### System configuration
**Rails version**: > 5.2

**Ruby version**: > 2.0

**Comment by skipkayhil** [comment]
Previous discussion:
#37317
#29424
#29400

I'm going to close because this has been rejected previously, and we reserve the issue tracker for bugs only. I would recommend bringing this up on [Discourse](https://discuss.rubyonrails.org/) or [Discord](https://discord.com/invite/d8N68BCw49) if you want to discuss further
