### ISSUE TITLE
`ActiveSupport::SafeBuffer` substring html-safety

### ISSUE THREAD

**Issue by flavorjones** [rails/rails#47361]
I'm opening this issue to start a conversation about whether the current html-safety behavior of `ActiveSupport::SafeBuffer` should be considered incorrect or insecure and should be changed.

## Context

The current (edge) behavior of the `ActiveSupport::SafeBuffer#html_safe?` attribute is to _preserve_ that attribute's value when the string is sliced with many methods:

``` ruby
string = "<div>test</div>".html_safe

string[0..1].html_safe? # => true
string.slice(0, 1).html_safe? # => true
string.slice!(0, 1).html_safe? # => true
string.chr.html_safe? # => true
```

This behavior was originally introduced for `#[]` with 2 arguments in 8ccaa341 (Rails 3.2.2), later extended in https://github.com/rails/rails/pull/33808 (Rails 6.0) to any number of arguments, and was later extended again to include `#slice`, `#slice!`, and `#chr` in https://github.com/rails/rails/pull/47344 (Rails 7.1.0.alpha).

_Note: edited the above section on 2023-02-11 to reflect the first commit to support preserving html-safe in a slice-like method was 8ccaa341_

## Problem

[About a year ago](https://github.com/rails/rails/pull/33808#issuecomment-1044647597) I thought the current behavior was fine; but I've learned some painful lessons about sanitization since then and have changed my mind.

Substrings of an HTML-safe string are not themselves safe. Prior decisions supporting this statement:

- 1300c034 (2011) which originally introduced the "unsafe" list to ensure `#gsub`, `#chop`, `#chomp`, `#delete`, etc. (and their bang methods) do not return safe buffers
- https://github.com/rails/rails/pull/33990 which applied this "unsafe" policy to new Ruby methods `#delete_prefix` and `#delete_suffix`.

Hopefully it's obvious that slice methods like `#[]` and `#slice` can be used to implement the existing unsafe methods, and are therefore equivalent, which means _at best_ SafeBuffer is still inconsistent:

``` ruby
original = "abcdefghi".html_safe

original.delete_prefix("abc").tap do |subject|
  subject # => "defghi"
  subject.html_safe? # => false
end

original.slice(3..).tap do |subject|
  subject # => "defghi"
  subject.html_safe? # => true
end
```

Here's a contrived example showing that it's possible to construct unsafe strings that are marked "html safe" using nothing but a source "html safe" string:

``` ruby
safe = "<span>title (critic 1)</span>".html_safe

# methods like append do the right thing with unsafe strings, HTML-escapes them
subject = safe + "<" # => "<span>title (critic 1)</span>&lt;"
subject.html_safe? # => true

subject = safe + "<script>alert(1)</script>" # => "<span>title (critic 1)</span>&lt;script&gt;alert(1)&lt;/script&gt;"
subject.html_safe? # => true

# but slicing gets around this because it returns strings marked "safe"
subject = safe + safe[0] # => "<span>title (critic 1)</span><"
subject.html_safe? # => true

# in the absurd extreme
subject = safe +
          safe[0] + safe[1] + safe[13] + safe[14] + safe[15] + safe[2] + safe[6] + safe[5] +
          safe[3] + safe[9] + safe[10] + safe[14] + safe[6] + safe[12] + safe[20] + safe[21] +
          safe[0] + safe[23] + safe[1] + safe[13] + safe[14] + safe[15] + safe[2] + safe[6] + safe[5]
subject # => "<span>title (critic 1)</span><script>alert(1)</script>"
```

Here's a much more realistic example that uses the Rails sanitizer and takes advantage of comments being unescaped by HTML parsers:

``` ruby
class ViewSanitizer
  include ActionView::Helpers::SanitizeHelper
end

tags = ["comment", "div"] # a departure from the default, we'll let comments through
original = ViewSanitizer.new.sanitize("<div><!-- <script>alert(1)</script> --></div>", tags: tags)

original # => "<div><!-- <script>alert(1)</script> --></div>"
original.html_safe? # => true

subject = original[10..34] # => "<script>alert(1)</script>"
subject.html_safe? # => true
```

I would like to note that I commented in https://github.com/rails/rails/pull/33808#issuecomment-1044647597:

> If you are able to generate a string that, once it's been sanitized and marked safe, would have a
> malicious substring in it, please open an issue so we can discuss?

The previous example _is_ that case, and @SampsonCrowley was right that it's probably dangerous to allow this behavior to remain. Also, @ggmichaelgo was right in https://github.com/rails/rails/pull/46259 when he tried to revert #33808.

## Short-term suggestion

I think we need to revert the changes from https://github.com/rails/rails/pull/47344 and https://github.com/rails/rails/pull/33808.

I'll prepare a PR for folks to review.

## Longer-term suggestion

I think there is a problem with the design used in `SafeBuffer`, which is an ["unsafe list"](https://github.com/rails/rails/blob/c88ca3b72083449fd242ed5aaf1b557f88a9e7b2/activesupport/lib/active_support/core_ext/string/output_safety.rb#L20) that names the methods which are unsafe.

In the past, this approach has required additional action by Rails maintainers when new unsafe string methods are introduced upstream -- see https://github.com/rails/rails/pull/33990 for an example to make sure `#delete_prefix!` marked the string as unsafe.

I think a better approach might be to redesign this class to:

1. avoid exclude lists
2. convert the string to unsafe upon _any_ bang method being invoked

My suspicion is that we don't even need an exclude list -- methods like `String#capitalize` will return a new object which will be, by default, `html_safe? == false` (with the exception of empty strings). This assumption will greatly simplify the code.

I'll schedule some time to work on this in the future.

## Resources

Relevant commits / issues / PRs:

- https://github.com/rails/rails/commit/8ccaa34103f1c37f7549f7f6c47a21dba21624db
- https://github.com/rails/rails/pull/33808
- https://github.com/rails/rails/pull/33990
- https://github.com/rails/rails/pull/46259
- https://github.com/rails/rails/issues/47343
- https://github.com/rails/rails/pull/47344

**Comment by flavorjones** [comment]
One more piece of prior art: commit 8ccaa341 which originally introduced some `#[]` html-safe behavior to address the vulnerability described in https://groups.google.com/g/rubyonrails-security/c/7dKPHj0E6RM. I think the proposed short-term solution will ensure this method returns a String which is always marked html-unsafe.

**Comment by matthewd** [comment]
I think I am broadly fine with the current state of affairs (without expressing a strong opinion on any particular method's behaviour).

`html_safe` is a _safety_ mechanism, designed to prevent developers from accidentally placing unescaped user input into a context that expects HTML content. It's not a _security_ mechanism -- its job is not to prevent any possible construction that might rearrange safe-marked data into a new form. 

In particular, the idea it's possible, through some method or other, to decompose a safe string into individually-safe characters and then compose a new string by concatenating those is uninteresting IMO: we are protecting plausible code from its own flaws and mistaken assumptions, not protecting the system from arbitrary / attacker-supplied code.

Any time we strip a previously-`html_safe` string of that flag, we set up likely double-escaping of HTML entities, and in turn train people to sprinkle extra `.html_safe` to fix it. There are plenty of circumstances where the potential for substantive change is too wide for anything else to be appropriate... but every time we make someone write `existing_safe_string.some_op.html_safe`, they encode an assumption that the input string was safe and open themselves to injection the moment this code sees an input that came straight from the user unescaped.

**Comment by flavorjones** [comment]
@matthewd Thank for you that additional context on the intention behind the class! That's helpful to redirect the conversation, since my mental model didn't match yours.

Let me try to say back to you what I think I'm hearing (I'd like to try to add some documentation if we can arrive at a clear description):

- the `html_safe?` property is meant to be set _once_ on untrusted data as it enters the system and it gets sanitized;
- and from that point on any modification to that string should preserve the `html_safe?` property value.

That's what I _think_ you said above, and makes a ton of sense to me; but that doesn't match the current behavior of the class. For example, take a look at the behavior introduced in 1300c034: many bang methods that modify the string (e.g., `#upcase!`) set the `html_safe?` property to `false`, as do methods like `#upcase` that return a modified version of the string.

So I'm not totally sure I'm understanding yet. I like your explanation, but I'm struggling to reconcile that with the code as it exists today.

**Comment by matthewd** [comment]
(I'll first note that this behaviour predates me, so, while I might argue on the merits, I can't claim to canonically define the original intent. Also, this comment ended up very long, sorry... it's an attempt to summarize my conception of how this should work from underlying principles, so I've ended up saying a lot of things that I know you know. :smile:)

I think those points loosely match my model, with the caveats 1) that "the system" is "the HTML rendering pipeline"[^1], and 2) the second point needs a prominent "ideally":

For discussion purposes, we can stipulate that all strings contain character sequences that look like HTML tags and entities.

If a string is not `html_safe?`, then it is a safety violation for us to use that value in an HTML-expecting context without escaping it -- we'd cause the browser to interpret intended-for-display content as HTML tags -- so any time we encounter a non-safe string in such a place, we escape it.

If a string _is_ `html_safe?`, then it is a developer-experience violation for us to escape it again: either it started life as a user-supplied `">"` and has already been escaped to `"&gt;"` to make it safe, or it came from explicitly HTML-generating application code, like `link_to`.

If we strip the `html_safe?` attribute from a string that was previously marked as such, then (while we're not literally applying an extra level of escaping in that moment) we're setting that up to happen in the future: it's destined to be used in an HTML-expecting context, and because of the earlier rule, our HTML-expecting contexts must apply escaping to non-safe strings they receive.

For an application to behave correctly (show the link, or the originally-supplied ">" and not "&amp;gt;", on its page), the developer will be forced to re-declare the safety of the transformed string. That's dangerous (for the above comment's "what if the input is sometimes _not_ safe?" case, and also just because it trains people to unthinkingly slap `.html_safe` decorations on whatever is necessary to get their page to look right, likely undermining the entire escape-by-default mechanism).

A loosely related example here is `safe_join`: in the common case, all the array elements are `html_safe?`, and so `.join.html_safe` would be equivalent... but despite both producing a safe-flagged string, the actual safety of the two mechanisms is quite different.

---

So that's a long story of [my mental model as to] why it's bad to strip the safe flag from an existing string. Here comes the "it depends".

We do also need to protect users from easy mistakes on other parts of the string API: having `gsub` strip safety is annoying [and risky, once the caller compensates], but allowing a simple `gsub` to be tricked into recomposing HTML tags that were supposed to have been sanitized/stripped away is also dangerous.

To contrast this with my earlier position that `#[]` is fine, I guess I care to protect `some_string.foo(*params[:injected_arguments])`, but not `params[:sequence].each { |x| some_string = some_string.foo(*x) }`... just as a matter of one being a plausible [if questionable] choice for a real person to write without considering the implications.

In my mental model, I would expect e.g. `upcase` to retain safety, because it seems... safe. There's no way it can accidentally (or even deliberately) affect the HTML-level composition of the output.

**However**, in practice, I would not expect such methods to see enough use that anyone would notice or care either way: by definition once you have an HTML-safe string, _it contains HTML_. Sometimes that HTML might be identical to the pre-HTML input, but you're still committing a type error by manipulating it as if it were ASCII prose.

If you're writing a function that intends to manipulate HTML, then you should really escape your input [if it's not html safe], work in a way that is conscious of the fact you're manipulating HTML (don't break tags, attributes, or entities you didn't intend to), and then explicitly mark your output as HTML-safe. You know you're dealing with HTML, so as long as things are reasonably predictable, you'll be fine. If you're slicing, this is where I assume you are.

If you're writing a function that doesn't intend to manipulate HTML, then if it's receiving an HTML-safe value, you're calling it too late / in the wrong place, and you're probably going to have a bad time. If you want to slice out the user's first name (ignoring all the higher-level social reasons that's a bad design choice), the time to do that was when it was an ordinary non-HTML string. 

[^1]: Most strings, including user-supplied ones, should spend most of their life not marked as HTML safe; escaping should occur right around the time the string is being surrounded by other HTML tags.

**Comment by flavorjones** [comment]
@matthewd Thanks again for the thoughtful reply.

> If you're writing a function that intends to manipulate HTML, then you should really escape your
> input to work in a way that is conscious of the fact you're manipulating HTML, and then explicitly
> mark your output as HTML-safe

> If you're writing a function that doesn't intend to manipulate HTML, then if it's receiving an
> HTML-safe value, you're calling it too late / in the wrong place

+100 couldn't agree more.

A brief search I just did in some large Rails apps of `gsub`, `slice`, or `chomp` used with `html_safe` shows that this seems to be how SafeBuffer is used.

From Mastodon:

```haml
%title= content_for?(:page_title) ? safe_join([yield(:page_title).chomp.html_safe, title], ' - ') : title
```

From Discourse:

``` ruby
EmailStyle
  .new
  .html
  .sub("%{email_content}") { capture { yield } }
  .gsub("%{html_lang}", html_lang)
  .gsub("%{dark_mode_meta_tags}", dark_mode_meta_tags)
  .gsub("%{dark_mode_styles}", dark_mode_styles)
  .html_safe
```

From Gitlab:

``` ruby
# We use Elasticsearch highlighting for results from Elasticsearch. Sanitize the description, replace the
# pre/post tags from Elasticsearch with highlighting, truncate, and mark as html_safe. HTML tags are not
# counted towards the character limit.
text = search_sanitize(search_highlight[issuable.id].description.first)
text.gsub!(::Elastic::Latest::GitClassProxy::HIGHLIGHT_START_TAG, '<span class="gl-text-gray-900 gl-font-weight-bold">')
text.gsub!(::Elastic::Latest::GitClassProxy::HIGHLIGHT_END_TAG, '</span>')
search_truncate(text).html_safe
```

``` ruby
# Converts newlines into HTML line break elements
def nlbr(str)
  ActionView::Base.full_sanitizer.sanitize(+str, tags: []).gsub(/\r?\n/, '<br>').html_safe
end
```

From a large private rails app:

``` ruby
text = sanitize(text)

if text.blank?
  text
else
  text.gsub(/\B#\w*[a-zA-Z]+\w*/, '<strong class="highlight hashtag">\0</strong>').html_safe
end
```

``` ruby
html_safe = string.html_safe?
string = string.gsub(/\s+/, " ").strip
string = string.slice(0, limit) if limit
string = string.html_safe if html_safe
```

All of these seem like reasonable uses of the string functions -- they're treating the string like HTML and then flagging it as `html_safe` when it's done.

Which brings me back to my [earlier point](https://github.com/rails/rails/issues/47361#issuecomment-1426791147) ...

> from that point on any modification to that string should preserve the html_safe? property value

It seems like _all_ String methods should preserve `html_safe`. Or, if we're not comfortable doing that for all String methods, then maybe `SafeBuffer` shouldn't inherit from `String`, but should use composition and support only a limited API. Do either of these end states seem worth driving towards (with some deprecation cycle)? Or is this inconsistency just not a big enough problem to warrant the effort?

**Comment by jhawthorn** [comment]
I can see the argument either way as well, but as we've traditionally protected our users from making the mistake of mutating or modifying an escaped string, I feel we have some obligation to continue doing so or to be very clear about communicating the change in expectation.

> maybe `SafeBuffer` shouldn't inherit from `String`, but should use composition and support only a limited API

I don't know how viable it is, but I find this pretty compelling. In addition to avoiding [CVE-2023-28120](https://discuss.rubyonrails.org/t/cve-2023-28120-possible-xss-security-vulnerability-in-safebuffer-bytesplice/82469), it could make the `html_safe?` check faster.

As a smaller change we could try using `undef_method` to "mask" the undesirable string methods.

I think we might be in a better place than we were previously to look into a major change like this to `SafeBuffer`, as `ActionView::OutputBuffer` no longer inherits from it (and uses a plain string Internally).

**Comment by matthewd** [comment]
I think disinheriting SafeBuffer is a tall order: it makes it much harder for APIs (ours or otherwise) to use the more intent-carrying type without forcing callers to know that what they get back isn't quite a string. The benefit of the current approach is that if you stay in SafeBuffer-land, everything will Just Work, but if you treat it as a plain string, that's fine too.

Not a real solution to anything, but what if:

```ruby
string.html_safely do |s|
  s = s.gsub(/\s+/, " ").strip
  s = s.slice(0, limit) if limit
  s
end
```

... for the "preserve/re-apply safety iff the input is safe" behaviour? (or even just define this as the block form of `html_safe`?)

It would at least hopefully allow Mastodon to `html_safely(&:chomp)` rather than `chomp.html_safe`, which seems like an improvement in safety.

(In the specific case of `chomp`, I don't see any reason it shouldn't retain safety automatically, but we can still use it for discussion. IMO 1300c034775a5d52ad9141fdf5bbdbb9159df96a went too far and pushes callers toward the more-dangerous "just add `.html_safe`" approach.)

**Comment by flavorjones** [comment]
I'm going to close this, since I think we've adequately discussed all the aspects I was hoping for. I may find time to open up an issue with a concrete proposal.
