### ISSUE TITLE
ActiveRecord 5.2.8.1 uses incorrect parameters for YAML.safe_load, thereby requiring ruby 2.6

### ISSUE THREAD

**Issue by matthewhively** [rails/rails#47362]
The implementation of `ActiveRecord::Coders::YAMLColumn.yaml_load` in rails 5.2.8.1 currently follows the parameter definition in the ruby 2.6 function definition.

The method was introduced by this commit:
https://github.com/rails/rails/commit/6576aa7bbcf52ebd39853363e29f92b4dd53b6f1  (july 12th 2022)

It looks like the issue was resolved by this commit: 
https://github.com/rails/rails/commit/5ab06e54b6868b249185e9fdf46349155665c54a  (july 13th 2022)
but was not included in rails 5.2.8.1 (released Nov 23, 2022) so therefore the required ruby version has effectively become 2.6 instead of 2.2.2 as listed in the gemspec.

### System configuration
**Rails version**: 5.2.8.1

**Ruby version**: 2.5.7

**Comment by zzak** [comment]
Looks like there is context here:
https://github.com/rails/rails/pull/45593#issuecomment-1185819691

Since this version is EOL, it's unlikely to receive a bugfix release, but that decision is beyond me.

It's suggested to point your Gemfile at the `5-2-stable` branch, are you able to use that?

Because there is a workaround and this version is unsupported, I think we can close this ticket.
