### ISSUE TITLE
Change from Gem.ruby_version to RUBY_VERSION

### ISSUE THREAD

**Issue by rubys** [rails/rails#47417]
### Steps to reproduce

Run `rails new` with any Ruby with a gem patch level

### Expected behavior

Dockerfile contains FROM statement specifying a three part version number for the Ruby image

### Actual behavior

Dockerfile contains FROM statement specifying a non-existent ruby image containing four parts

### System configuration
**Rails version**: 7.1

**Ruby version**: any ruby version with a patch level

## See also

https://github.com/rubys/dockerfile-rails/commit/57e066da24b86d038bb862f5300c5c747e47309e

**Comment by simi** [comment]
:thinking: Patch level was removed with Ruby 3.0 if I remember well (did some checks locally and it seems to). Ruby 2.7 is EOL soon. It would be also possible to fix this by removing Ruby 2.7 support (seems to EOL at 31.3.2023). But maybe that's too drastic.

**Comment by rubys** [comment]
An actual fly.io user with Ruby 3.1.0.0 failed to deploy due to this error.  See https://community.fly.io/t/rails-cant-deploy-an-app-following-the-getting-started-guide/10026/4?u=rubys where the error was reported.

**Comment by skipkayhil** [comment]
> See https://community.fly.io/t/rails-cant-deploy-an-app-following-the-getting-started-guide/10026/4?u=rubys where the error was reported.

I read through this thread and it looks like the user was using Rails 7.0.4. Perhaps their rubygems version is not up to date? (Ruby 3.1.2 shipped with rubygems 3.3.7)

The change to `Gem.ruby_version` from `RUBY_VERSION` was discussed previously in #45979. The conclusion was that for Rails 7.1, the minimum required rubygems version would be bumped in #46817 because previous versions returned extra decimals as you describe.

So as long as the `Gem.ruby_version` usage is only on the main branch and not on `7-0-stable`, I think it is preferable over `RUBY_VERSION`.

**Comment by rubys** [comment]
> So as long as the Gem.ruby_version usage is only on the main branch and not on 7-0-stable, I think it is preferable over RUBY_VERSION.

Just curious, why?

I have a business need to support prior versions of Rails; given this, what am I missing out since I'm currently using RUBY_VERSION?

**Comment by skipkayhil** [comment]
> Just curious, why?
> 
> I have a business need to support prior versions of Rails; given this, what am I missing out since I'm currently using RUBY_VERSION?

The benefit would be being able to generate Dockerfiles pointing to prerelease versions of Ruby, as described in #45979 but in this case for the Dockerfile instead of the Gemfile.

I suppose that would also require a small change because `Gem.ruby_version` would generate `3.2.0.preview3` but the image tags use a dash instead :/

https://hub.docker.com/layers/library/ruby/3.2.0-preview3/images/sha256-a4a644a3675101fb543a966450769257d7f40cd4112ecb3e3c67f189c695b4cf

---

I was assuming this issue was about updating this line, so that's why I was only thinking about Rails 7.1: https://github.com/rails/rails/blob/6cea2589a45a67a3e58cddc2d5d223f92c57fb76/railties/lib/rails/generators/rails/app/templates/Dockerfile.tt#L4

Maybe I'm not understanding what the plan is to support older Rails versions. Is the goal to use `dockerfile-rails`? In that case you could raise the minimum required rubygems version to `">= 3.3.13"` and `Gem.ruby_version` should work as expected.

---

Unrelated to the current discussion, are these issues you've opened TODO items for yourself that you plan to open PRs for? Or are they open issues that you wouldn't mind someone else grabbing?

**Comment by rubys** [comment]
> prerelease versions of Ruby

gotcha.  Thanks.  modulo that small bug, I can see the value.  It is not a use case that I'm likely to encounter, but given that future Rails 7.1 apps will have upgraded rubygems, any Dockerfiles generated with the current template will work with fly.io, so this issue can be closed.

> Is the goal to use dockerfile-rails? 

That's a multi-faceted question :-)

I believe that there is significant overlap between the requirements that Rails, fly.io, and others like mrsk have, and would love to collaborate.  If, for example, you personally were to create a substantive PR on dockerfile-rails, my response likely would be to add you as a collaborator.

Overlap doesn't mean congruence.  For example, I have customers running Rails 5 apps on unsupported versions of Ruby.  Yes, they should upgrade, but it isn't my best interest to make that a barrier or prerequisite.

But, yes, is is my stated preference that Rails 7.1 uses dockerfile-rails much in the same way that it runs commands like `bin/rails turbo:install stimulus:install` during the creation of a new application.

> issues that you wouldn't mind someone else grabbing

The current batch are issues that actual fly.io customers have encountered that I thought (in this case mistakenly) that would prevent future Rails 7.1 applications from being immediately deployable on fly.io.

And ones that I hope that somebody would pick up.  I have an unpublished cathartic rant regarding my experience with the current process for pull requests for Rals 7.1.
