### ISSUE TITLE
Main recently broke TagHelpers in Haml v5

### ISSUE THREAD

**Issue by kyrofa** [rails/rails#47443]
c5303039f452915b8c84822ddc90f6f4e1972430 has broken Haml v5's ability to use `TagHelpers`. Here's the test:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "haml", '5.2.2'
  gem "rails", github: "rails/rails", branch: "main"
end

require "rack/test"
require "action_controller/railtie"
require "haml"
require "haml/template"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "www.example.com"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

module TestHelper
  # c5303039f452915b8c84822ddc90f6f4e1972430 BROKE THIS
  def content
    content_tag(:span, class: 'foo') do
      concat image_tag('img.svg', class: 'bar')
    end
  end
end

class TestController < ActionController::Base
  def index
  end
end

require "minitest/autorun"

class BugTest < ActionDispatch::IntegrationTest

  def test_returns_success
    Dir.mktmpdir do |d|
      Dir.mkdir("#{d}/test")
      File.open("#{d}/test/index.html.haml", 'w') do |f|
        f.write('= content')
      end

      TestController.prepend_view_path d
      get "/"
    end

    assert_select '.foo' do
      assert_select 'img.bar', count: 1
    end
  end

  private
    def app
      Rails.application
    end
end
```

On Rails 7.0.4 (and on main prior to c5303039f452915b8c84822ddc90f6f4e1972430), that helper results in `<span class="foo"><img class="bar" src="/images/img.svg" /></span>` as expected. After c5303039f452915b8c84822ddc90f6f4e1972430, you get `<img class="bar" src="/images/img.svg" /><span class="foo">&lt;img class=&quot;bar&quot; src=&quot;/images/img.svg&quot; /&gt;</span>`, which obviously isn't correct.

Note that the latest Haml v6 seems to handle this okay, so it must have moved to a different API, but I at least have a good number of applications still on v5. I'm sure lots of folks do. Any chance we can keep it working?

**Comment by ghiculescu** [comment]
@camertron this issue relates to https://github.com/rails/rails/pull/47194. Any chance you could have a look? If the issue is entirely on the `haml` side then we can push it over to there, but it does seem to me like it's regressed.

**Comment by ghiculescu** [comment]
@kyrofa FYI, changing this:

```ruby
    content_tag(:span, class: 'foo') do
      concat image_tag('img.svg', class: 'bar')
    end
```

To this:

```ruby
    content_tag(:span, class: 'foo') do
      image_tag('img.svg', class: 'bar')
    end
```

Makes the test pass. The `concat` isn't necessary; `capture` gets called on the block (which presumably is where your issue is coming from), so the block just needs to return whatever will go inside the tag.

So I guess the issue here is that it used to work despite the API being used incorrectly. Given that I am not sure it will get fixed, but let's see what camertron says.

**Comment by camertron** [comment]
It looks like the problem here comes from the fact that Haml expects `output_buffer=` to be called in the view context, which doesn't happen anymore. To ensure both ActionView and Haml are appending to the same buffer, Haml's version of `output_buffer=` sets `haml_buffer.buffer = new_buffer` before calling `super`. Since `output_buffer=` is no longer called, Haml's buffer doesn't get set appropriately and any string appends happen on the wrong buffer.

I would expect `concat` to continue working because `capture` is designed to handle both the cases where the block either appends to the buffer _or_ returns a value, i.e. appending to the buffer inside the block is explicitly allowed.

I tried to fix the problem by setting `@haml_buffer.buffer = @output_buffer` in the Temple compiler, which worked but also resulted in a bunch of test failures when I ran the test suite 🙁 

In my opinion, any attempt to fix the problem will have to happen in Haml, since its Haml's monkeypatches that are assuming an architecture that's no longer valid. I _think_ it's just a matter of maintaining a reference to ActionView's output buffer, which isn't reassigned anymore.

I hope that helps :) I would be happy to pair on this at some point if necessary.

**Comment by kyrofa** [comment]
> The concat isn't necessary; capture gets called on the block (which presumably is where your issue is coming from), so the block just needs to return whatever will go inside the tag.

Ah, my minimal reproducer was a little TOO minimal! Good catch. My real use-case has multiple things contained inside that span such that `concat`s are actually required (I think-- can you confirm?). This breaks, for example:

```
content_tag(:span, class: 'foo') do
  concat image_tag('img1.svg', class: 'bar')
  concat image_tag('img2.svg', class: 'baz')
end
```

**Comment by kyrofa** [comment]
> In my opinion, any attempt to fix the problem will have to happen in Haml, since its Haml's monkeypatches that are assuming an architecture that's no longer valid. I think it's just a matter of maintaining a reference to ActionView's output buffer, which isn't reassigned anymore.

Alright thank you. I look the liberty of logging an issue against haml notifying them of this. Sounds like it's time to update to v6!

**Comment by ghiculescu** [comment]
What happens if you remove just the last concat, so the block is never returning a “concat” call?

**Comment by kyrofa** [comment]
Oh main, that results in `<img class="bar" src="/images/img1.svg" /><span class="foo"><img class="baz" src="/images/img2.svg" /></span>`. On 7.0.4, `<span class="foo"><img class="bar" src="/images/img1.svg" /></span>`. Neither pass this test, which is the behavior I would expect:

```
assert_select '.foo' do
  assert_select 'img.bar', count: 1
  assert_select 'img.baz', count: 1
end
```

**Comment by ghiculescu** [comment]
This works:

```ruby
    content_tag(:span, class: 'foo') do
      image_tag('img1.svg', class: 'bar') + image_tag('img2.svg', class: 'baz')
    end
```

**Comment by ghiculescu** [comment]
@camertron were you able to see how HAML v6 fixed this? That might give a clue as to where in HAML v5 the fix should go.

**Comment by kyrofa** [comment]
@ghiculescu sadly those types of solutions don't scale quite the same way in more complex helpers, which is my real use-case. They are valid workarounds, of course, as are not using the tag helpers at all. Or updating haml.

**Comment by skipkayhil** [comment]
> were you able to see how HAML v6 fixed this? That might give a clue as to where in HAML v5 the fix should go.

It may be hard to figure out because the old implementation appears to have been replaced in v6: https://github.com/haml/haml/blob/d0a86c3eba4563073e950f9e7307a947d4379a64/CHANGELOG.md?plain=1#L86

**Comment by camertron** [comment]
@ghiculescu my understanding is Haml 6 is almost a complete rewrite and takes a different approach when it comes to output buffers. I'd be happy to dig in, but I'm not sure what good that would do.

Something I didn't try would be to redefine `concat` in Haml 5 to return `nil`, could that work?

**Comment by AkshayGoyal022** [comment]
Any idea how to make haml v5 compatible with rails v7.1? We are not able to upgrade haml because of legacy reasons.
@camertron @ghiculescu

**Comment by camertron** [comment]
@AkshayGoyal022 unfortunately this was long enough ago that all the necessary context has left my brain 😓 My [previous comment](https://github.com/rails/rails/issues/47443#issuecomment-1439474327) seems to indicate setting `@haml_buffer.buffer = @output_buffer` does the trick, maybe you can try that and fix the test failures?
