### ISSUE TITLE
Hash#from_xml fails with LoadErrors on Ruby 3+

### ISSUE THREAD

**Issue by alimi** [rails/rails#47549]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activesupport", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/hash/conversions"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_hash_from_xml
    xml = <<-XML
      <?xml version="1.0" encoding="UTF-8"?>
        <hash>
          <foo type="integer">1</foo>
          <bar type="integer">2</bar>
        </hash>
    XML

    expected_hash = {"hash"=>{"foo"=>1, "bar"=>2}}
    assert_equal expected_hash, Hash.from_xml(xml)
  end
end
```

### Expected behavior
I expect `Hash#from_xml` to return a Hash [as documented](https://edgeapi.rubyonrails.org/classes/Hash.html#method-c-from_xml).

### Actual behavior
`Hash#from_xml` raises a LoadError on Ruby 3+:

```ruby
LoadError: cannot load such file -- rexml/document
```

This is happening because Ruby 3+ no longer includes REXML by default. I think this could be fixed by adding REXML as an ActiveSupport gem dependency.

### System configuration
**Rails version**: main, 7.0.4.2, 6.1.7.2, 6.0.6.1

**Ruby version**: 3.0.5, 3.1.3, 3.2.1

**Comment by alimi** [comment]
I just came across https://github.com/rails/rails/commit/f624ed09abba4a0bae64eb699c9fc2e3f9bdc2dc so I guess this is working as intended?

**Comment by skipkayhil** [comment]
Yeah, I think the current behavior is intended. Did your logs contain the other error message added in f624ed0?

```ruby
$stderr.puts "You don't have rexml installed in your application. Please add it to your Gemfile and run bundle install"
```

**Comment by alimi** [comment]
I see the other message in the test script when it's run against ActiveSupport 6.1+ since that's when it was added. I'm working in app that's on Rails 6.0.6 so I'm not seeing it there.

This could be the source of some very subtle bugs. For example, our app has gem dependencies that require REXML in development and test so we don't get the LoadError when we're building features that use `Hash#from_xml`. Everything looks good so we deploy to production (or prod-like environments) and we get surprise LoadErrors because none of the production gems require REXML. It sucks that the issue isn't surfaced until really late in a feature's lifecycle.

It feels a little weird that `Hash#from_xml` depends on REXML but its not included as a gem dependency.

**Comment by rafaelfranca** [comment]
It doesn't depend on rexml alone. It can use nokogiri or anything that mini_xml supports. So like all other optimal dependencies, we don't include as a gem dependency because you might be using something else that isn't rexml.

Rails 6.0 isn't supported anymore, so there isn't much we can do about that version

It wasn't https://github.com/rails/rails/commit/f624ed09abba4a0bae64eb699c9fc2e3f9bdc2dc that removed the dependency. It wasn't never there. Before https://github.com/rails/rails/commit/f624ed09abba4a0bae64eb699c9fc2e3f9bdc2dc we added it momentarily, because we thought that would fix the problem, but in reality, it would be adding a dependency that might never be used, even if you used `Hash#from_xml` (if you chose nokogiri as default).

If your application depends on rexml, the fix is add it to your gemfile. You can also chose to use nokogiri that is already a dependency of Rails as well.

Thank you for the issue.

**Comment by zzak** [comment]
REXML is not a dependency because it comes from Ruby's standard library. That may have changed recently, however.

**Comment by alimi** [comment]
Ahh gotcha.

How would we configure `Hash#from_xml` to use Nokogiri? It seems like [REXML is the default](https://github.com/rails/rails/blob/53a47a989012bd1577c964008e013a6969aae4bf/activesupport/lib/active_support/xml_mini.rb#L201), and we could set `ActiveSupport::XmlMini.backend` to `Nokogiri` in an initializer? Sorry if this documented somewhere but I'm not finding much about it.

**Comment by skipkayhil** [comment]
> and we could set `ActiveSupport::XmlMini.backend` to `Nokogiri`

Yeah, that looks like the best option to be (anywhere during boot). I also don't see much documentation about this, but it should probably be included in https://guides.rubyonrails.org/configuring.html . Would you like to make a PR?

**Comment by robotfelix** [comment]
Coincidentally I've just run into the same issue in the exact same circumstances (issue not present in development or test environments, and only found when testing in a production-like environment).

The error we got in production wasn't the error about `rexml` not being installed, instead we just got
```
LoadError (cannot load such file -- rexml/document):
```
being raised from a line that used `Hash#from_xml `, and to confuse things there were no mentions of either `active_support/core_ext/hash/conversions.rb` or `xml_mini` in the backtrace.

I fixed the problem by adding this initializer:
```ruby
# config/initializers/active_support.rb
Rails.application.config.to_prepare do
  ActiveSupport::XmlMini.backend = 'Nokogiri'
end
```

I could be wrong but I don't think a more Rails-y way of configuring this (eg: something like `config.active_support.xml_mini_backend = 'Nokogiri'`) exists currently.

To give my 2 cents, given
* Rails doesn't depend on rexml
* Rails does depend on nokogiri
* my understanding is that Nokogiri is faster
then it does seem like having Rails configure the ActiveSupport::XmlMini backend to Nokogiri and not erroring would be a sensible default.

Whether or not the default of ActiveSupport itself should change is perhaps a more tricky question, since it may be used outside of Rails where nokogiri isn't available.

**Comment by skipkayhil** [comment]
> The error we got in production wasn't the error about rexml not being installed, instead we just got

Would you be able to share the whole stack trace?

**Comment by alimi** [comment]
> Whether or not the default of ActiveSupport itself should change is perhaps a more tricky question, since it may be used outside of Rails where nokogiri isn't available.

Maybe ActiveSupport shouldn't be setting a default for `ActiveSupport::XmlMini.backend`? As it stands today, you could either find yourself with a dependency you didn't know about or you're gonna be surprised with production errors. If ActiveSupport didn't set a default, app developers would have more visibility around what's going on.

**Comment by robotfelix** [comment]
@skipkayhil I've scrubbed a few module names out, but the stack trace was this:
```
  
LoadError (cannot load such file -- rexml/document):
  
app/lib/some_module/some_service/put_session/response.rb:17:in `parse_reply'
app/lib/some_module/some_service/response_base.rb:39:in `parse_response'
app/lib/some_module/some_service/response_base.rb:11:in `initialize'
app/lib/some_module/some_service/put_session/request.rb:16:in `new'
app/lib/some_module/some_service/put_session/request.rb:16:in `success'
app/lib/some_module/some_service/request_base.rb:24:in `perform'
app/lib/session_handler.rb:24:in `fetch_token'
app/lib/session_handler.rb:12:in `block in token'
app/lib/session_handler.rb:10:in `synchronize'
app/lib/session_handler.rb:10:in `token'
app/lib/some_module/parts_pricing.rb:13:in `initialize'
app/services/pricing_service.rb:30:in `new'
app/services/pricing_service.rb:30:in `add_pricings'
app/services/pricing_service.rb:13:in `call'
app/services/service_object.rb:3:in `call'
app/controllers/v1/pricing_controller.rb:9:in `index'
```
And the line at _app/lib/some_module/some_service/put_session/response.rb:17_
is
```ruby
@fields = Hash.from_xml(reply.to_xml)['REPLY']
```

In case it helps:
* Log level is set to `:warn`
* Ruby: 3.1.3
* Rails: 7.0.4.2

**Comment by jaredbeck** [comment]
> Coincidentally I've just run into the same issue in the exact same circumstances (issue not present in development or test environments, and only found when testing in a production-like environment).

Same here.

webmock, rubocop, and selenium-webdriver are all examples of dev/test gems (not usually installed in prd) which currently (Oct 2024) depend on rexml. As stated above, this prevents the warning message from being displayed.
