### ISSUE TITLE
Exclude certain files from CSS compressor

### ISSUE THREAD

**Issue by the-pulli** [rails/rails#47553]
As discussed in https://github.com/rails/tailwindcss-rails/discussions/243 and in the corresponding closed PR https://github.com/rails/tailwindcss-rails/pull/248, I encountered an issue in production while setting the `Rails.application.config.assets.css_compressor = :yui` to compress my custom CSS in a TW CSS project. If I use yui it compresses the already minified tailwind.css again and messes it up.
So I'm left with disabling yui and not compress my custom CSS. What I'm looking for is an option to exclude the tailwind.css from compression via yui. I'm not sure if this is possible right now? I haven't found anything in the Asset Pipeline Guide. 

### Steps to reproduce
rails new yui-test -c tailwind
set `Rails.application.config.assets.css_compressor = :yui` in `config/environments/production.rb`

### Expected behavior
Should compress all CSS files

### Actual behavior
Compresses the already minified tailwind.css again and makes it unusable.

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 3.2.1

**Comment by flavorjones** [comment]
Some additional context for readers ...

In https://github.com/rails/tailwindcss-rails/pull/248 I had suggested implementing a "do not minify" setting in `tailwindcss-rails` to allow the Rails compressor to handle all compression. But in [@dhh suggested an alternative](https://github.com/rails/tailwindcss-rails/pull/248#issuecomment-1433467726):

> I think this should be fixed elsewhere rather than in TW. The minifier should be able to opt out
> of being applied to a given CSS. Rather than TW knowing about not having to minify.

I'm not very familiar with other asset-related gems, are there others that also compress their assets?

If `tailwindcss-rails` is the only one, it feels like the easiest thing to do might be for that gem to check if `Rails.application.config.assets.css_compressor` is set, and conditionally skip compression when it generates its assets.

Are there other ideas on how to implement this?

**Comment by flavorjones** [comment]
I've opened a PR with the above approach at https://github.com/rails/tailwindcss-rails/pull/253 that I'd love feedback on.

**Comment by hahmed** [comment]
I might be missing something but can you exclude it using `Rails.application.config.assets.precompile -= %w( tailwind.css )` maybe from here https://github.com/rails/tailwindcss-rails/blob/05c5753c1051d5eb792cc60ee1e90564e8165af9/lib/tailwindcss/engine.rb#LL6C7-L6C73 or in the client app?

From what I'm seeing the way tailwind-rails works is that it enhances the `assets:precompile` rake command, so it invokes the tailwind:build command https://github.com/rails/tailwindcss-rails/blob/05c5753c1051d5eb792cc60ee1e90564e8165af9/lib/tasks/build.rake#L20 which is totally independent of how sprockets works? So if tailwind is excluded, it means sprockets will not touch that file and tailwind-rails will have run the rake command independently because of the file being included https://github.com/rails/tailwindcss-rails/blob/05c5753c1051d5eb792cc60ee1e90564e8165af9/lib/tailwindcss/commands.rb#L61

**Comment by the-pulli** [comment]
Thanks @hahmed for the detailed answer. I just tried it out with a dummy project. One uses `yui` without the `Rails.application.config.assets.precompile -= %w( tailwind.css )` directive and the other one does, but the output is still the same. You can check it out here:

https://yui.pulli.dev/

https://yui-without-tailwind.pulli.dev/

**Comment by flavorjones** [comment]
I've shipped the fix from https://github.com/rails/tailwindcss-rails/pull/253 in tailwindcss-rails v2.0.24. That change detects when Rails has a CSS compressor configured, and turns off tailwindcss's minification.

**Comment by the-pulli** [comment]
Just tested it, works perfectly. Great job @flavorjones 👍
