### ISSUE TITLE
add_foreign_key should support composite primary_key

### ISSUE THREAD

**Issue by jiridenteo** [rails/rails#47593]
`add_foreign_key` now accepts an argument `primary_key` and it is also possible to send in an array. however, only the first element from the array is taken.

To support multitenancy, it should be possible to send in a composite primary key, eg.

```
add_foreign_key :from, :to, primary_key: [:tenant_id, :id]
```

**Comment by fatkodima** [comment]
I doubt it is even possible to create tables with composite primary key currently?

@nvasilevski Is working (from what I saw) on implementing composite primary keys throughout the whole activerecord, so migration helpers for foreign keys, creating tables with composite primary keys would be a part of that, I think.

**Comment by jiridenteo** [comment]
Thanks for the hint, will check it out! :) 
Yes, it is not possible to create them via activerecord helpers, but it is possible to create them like this

```
      execute "ALTER TABLE #{table_name} ADD PRIMARY KEY (tenant_id, id)"
```
This also correctly bumps schema.rb

```
  create_table "users", primary_key: ["tenant_id", "id"], force: :cascade do |t|
```
However, there is no easy/clear way, how to add foreign keys (you can write raw SQL but then this will not be added to schema.rb)

**Comment by fatkodima** [comment]
Interesting. Rechecked - it is actually possible for `create_table` to create a table with a composite key and it is correctly dumped to the `schema.rb`, so I think it is reasonable to have the same behavior for foreign keys? Unless I am missing something 🤔

I will try to implement this behavior.

**Comment by jiridenteo** [comment]
Thanks! :)

**Comment by nvasilevski** [comment]
>so migration helpers for foreign keys, creating tables with composite primary keys would be a part of that

Yep, that's the intention though wasn't a priority.

I'm actually surprised to learn that the composite primary key in `create_table` is documented and tested 

https://github.com/rails/rails/blob/3ac5229f32433405628dbca0ec190f7df5013841/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L246-L251

I initially thought that it just works because the implementation was flexible enough to support it but it looks like it was intentionally implemented.

So it sounds reasonable for `add_foreign_key` to support referencing a composite primary key. Let's just make sure we see the whole picture of the public API. I'm basically speaking out loud trying to reveal all corner cases, not because I have a concern:

Given a database schema like:
```ruby
      create_table(:cars, primary_key: [:make, :model]) do |t|
      end
     
     create_table(:brochures) do |t|
         t.string :car_make
         t.string :car_model
     end
end
```

And a model setup where `Broschure.belongs_to :car` (we may not have every piece ready for the foreign key to be automatically derived but let's assume it belongs to by `[:car_make, :car_model]` foreign key derived on the `cars` table primary key)

Let's list all possible ways of using `add_foreign_key` starting from the one where everything should be derived and ending with the most verbose one.

1. The most conventional one:
```ruby
add_foreign_key :brochures, :cars
```

Should result in
```sql
ALTER TABLE "brochures" ADD CONSTRAINT fk_rails_e74ce85cbc FOREIGN KEY ("car_make", "car_model") REFERENCES "cars" ("make", "model")`
```

Seems ok so far as it should be possible to derive the foreign key as `primary_key.map { |pk_column| "#{table_name.singularize}_#{pk_column}"`

2. Let's say our setup is less conventional and we have to manually pass the `primary_key` 
```ruby
add_foreign_key :brochures, :cars, primary_key: [:make, :model, :year]
```

Should result in
```sql
ALTER TABLE "brochures" ADD CONSTRAINT fk_rails_e74ce85cbc FOREIGN KEY ("car_make", "car_model", "car_year") REFERENCES "cars" ("make", "model", "year")`
```
This also seems doable by deriving the foreign key using the same logic

3. Let's consider the most custom setup like:
```ruby
add_foreign_key :brochures, :cars, column: [:vehicle_make, :vehicle_model], primary_key: [:make, :model]
```

Should produce
```sql
ALTER TABLE "brochures" ADD CONSTRAINT fk_rails_e74ce85cbc FOREIGN KEY ("vehicle_make", "vehicle_model", "car_year") REFERENCES "cars" ("make", "model")`
```

And this is where the public API seems to be inconsistent as `column` argument implies a single-column foreign key. Not a big problem, most likely we should be solving it by supporting `columns` argument along with the `column` for backwards compatibility. I just want us to have the same expectations on the public API and make sure we are considering all use-cases (mainly tenant-based sharding setups and pure composite primary key setup)

Also can we have a look on the provided example `add_foreign_key :from, :to, primary_key: [:tenant_id, :id]` 
Do we expect the statement to be:
```sql
ALTER TABLE "from_table" ADD CONSTRAINT fk_rails_e74ce85cbc FOREIGN KEY ("tenant_id", "to_table_id") REFERENCES "to_table" ("tenant_id", "id")`
```
Then we will have to add the `columns:` argument support as I don't see a way for rails to derive `("tenant_id", "to_table_id")` foreign key as has no knowledge of `tenant_id` column being a tenant key which has the same name across tables. By convention it will most likely try to derive it as "to_table_tenant_id"` which is not what we want.


Also I want to add that I just came up with these examples and may be missing some other use-cases or mistaken about the usages as I haven't actually ran the code so feel free to point out inconsistencies

**Comment by fatkodima** [comment]
I think we can actually use just `:column` for multiple columns, similar to how [remove_index](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_index) is implemented. `add_index` actually also accepts 1 or many columns (and a required argument is named `column_name`), but it is not a kwarg, so user does not specify its name.

> Also I want to add that I just came up with these examples and may be missing some other use-cases

I do not see any other use-cases too, currently.

**Comment by nvasilevski** [comment]
>similar to how [remove_index](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_index) is implemented

Oh, good catch, so it looks like we can just go with `column` accepting an array to be consistent with existing apis. 
@fatkodima I don't mind if you want to work on making both `column` and `primary_key` args work properly with Arrays. Not sure if we should try to include the deriving logic into the same PR. Personally to make the change smaller I would make it work for an explicit usage like `add_foreign_key :documents, :accounts, column: [:account_branch_id, :account_party_id], primary_key: [:branch_id, :party_id]` and then consider supporting implicit versions like 
`add_foreign_key :documents, :accounts, column: [:account_branch_id, :account_party_id]` as the `primary_key` can be derived from `accounts` table. Though Rails core folks may see this as an incomplete feature and prefer the deriving logic to be included in the same PR

**Comment by fatkodima** [comment]
@eileencodes Sure. That will probably be tomorrow.

**Comment by shobee** [comment]
Today I ran into a problem with the current solution of this topic. Given the example from above:

```SQL
ALTER TABLE "from_table" ADD CONSTRAINT fk_rails_e74ce85cbc FOREIGN KEY ("tenant_id", "to_table_id") REFERENCES "to_table" ("tenant_id", "id")
```

it generates these two lines in schema.rb:

```ruby
add_foreign_key "from_table", "to_table", column: "tenant_id", primary_key: "tenant_id", name: "fk_rails_e74ce85cbc"
add_foreign_key "from_table", "to_table", column: "to_table_id", primary_key: "to_table_id", name: "fk_rails_e74ce85cbc"
```

No problem so far but now when I try to load schema into a test database it will fail with

`ActiveRecord::StatementInvalid: Mysql2::Error: Can't write; duplicate key in table '#sql-786_d35'`

I think it happens because of the duplicated foreign key name `fk_rails_e74ce85cbc`.

Any ideas how to solve this? Currently we are on Rails 6.0.6.1.

Thanks in advance for any help.
