### ISSUE TITLE
ActiveRecord returning wrong string representation of interval

### ISSUE THREAD

**Issue by hassan-allocator** [rails/rails#47612]
### Steps to reproduce
Run a query that returns interval::text

```ruby
ActiveRecord::Base.connection.exec_query("SELECT AGE(NOW()::date, (NOW() - interval '1 month')::date)::text as age_month")[0]
```

### Expected behavior
If you run the same query in a psql console, it returns '1 mon' as a text representation of the interval datatype. But once I convert it into ::text, rails should not change what it looks like.

### Actual behavior
Returns a representation of interval I am completely unfamiliar with. For 1 month, it's P1M.

### System configuration
**Rails version**: 6.1.7

**Ruby version**: 2.7.7

**Comment by matthewd** [comment]
We configure `intervalstyle` on the connection so that we can parse raw interval values that are returned. Unfortunately, that also affects the behaviour of explicit `::text` casting.

If you need to convert intervals into `postgres` traditional format regardless of the connected session's configured value, you might need to define a wrapper function.
