### ISSUE TITLE
OptionMergerTest#test_method_with_options_copies_options_when_options_are_missing fails with Ruby 3.3.0dev

### ISSUE THREAD

**Issue by yahonda** [rails/rails#47627]
Managed to reproduce the CI failure at https://buildkite.com/rails/rails/builds/94497#0186be64-c342-4494-b50b-e0362040cc9e/1134-1174 and found it is triggered by https://github.com/ruby/ruby/commit/e87d0882910001ef3b0c2ccd43bf00cee8c34a0c

### Steps to reproduce

```ruby
Install Ruby 3.3.0dev using `rbenv install 3.3.0-dev`
git clone https://github.com/rails/rails
cd rails
rm Gemfile.lock
bundle install
cd activesupport
bin/test test/option_merger_test.rb -n test_method_with_options_copies_options_when_options_are_missing
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ bin/test test/option_merger_test.rb -n test_method_with_options_copies_options_when_options_are_missing
Running 14 tests in a single process (parallelization threshold is 50)
Run options: -n test_method_with_options_copies_options_when_options_are_missing --seed 51119

# Running:

F

Failure:
OptionMergerTest#test_method_with_options_copies_options_when_options_are_missing [/home/yahonda/src/github.com/rails/rails/activesupport/test/option_merger_test.rb:42]:
Expected {:hello=>"world"} (oid=5300) to not be the same as {:hello=>"world"} (oid=5300).


bin/test test/option_merger_test.rb:40



Finished in 0.000405s, 2472.0410 runs/s, 2472.0410 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.3.0dev (2023-03-06T06:03:06Z master e87d088291) [x86_64-linux]

**Comment by yahonda** [comment]
cc @eugeneius Just wanted to ask you before opening a bug report to bugs.ruby-lang.org because this test code has been added via #39407

**Comment by eugeneius** [comment]
👋  @yahonda! Here's the smallest test case I could find (prints `false` on 3.2.1, `true` on 3.3.0-dev):

```ruby
options = { hello: "world" }

def test(opts) = opts

puts test(*[], **options).equal?(options)
```

I guess since https://github.com/ruby/ruby/commit/e87d0882910001ef3b0c2ccd43bf00cee8c34a0c, passing a hash as keyword arguments—along with positional arguments—to a method that doesn't accept keyword arguments now forwards the original hash as the final positional parameter instead of a copy.

Note that this was already the case when calling the method without positional arguments; the following prints `true` all the way back to Ruby 3.0:

```ruby
options = { hello: "world" }

def test(opts) = opts

puts test(**options).equal?(options)
```

I think we should fix this in Rails by reverting https://github.com/rails/rails/commit/9e4ff29f748b05c3a949f0d75167950039b6cda8.

I don't know whether this should be reported upstream or not; it's an observable change in behaviour, but copying the hash previously may have been unintentional since it didn't happen unless positional arguments were also passed. I think you're in a better position to make that decision than I am, since you're closer to the Ruby project.

**Comment by yahonda** [comment]
Thanks for the detailed information and the minimal test case. I'm inclined to report this behavior change to bugs.ruby-lang.org.
Because https://github.com/ruby/ruby/pull/7128 says this is https://github.com/ruby/ruby/pull/6920, which aims for better performance. I'd like to hear from Ruby developers to see if it is an expected behavior.

**Comment by yahonda** [comment]
Opened https://bugs.ruby-lang.org/issues/19526

**Comment by yahonda** [comment]
Confirmed https://github.com/ruby/ruby/commit/6462c1a042 via https://github.com/ruby/ruby/pull/7507 addressed this issue.

```ruby
$ ruby -v
ruby 3.3.0dev (2023-03-15T09:05:13Z master 6462c1a042) [x86_64-linux]
$ bin/test test/option_merger_test.rb -n test_method_with_options_copies_options_when_options_are_missing
Running 14 tests in a single process (parallelization threshold is 50)
Run options: -n test_method_with_options_copies_options_when_options_are_missing --seed 1049

# Running:

.

Finished in 0.000423s, 2365.4418 runs/s, 2365.4418 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
$
```

CI is also green https://buildkite.com/rails/rails/builds/94785#0186e624-fed8-4300-be93-81050571d845 .
