### ISSUE TITLE
pre/alpha/release candidates on rubygems.org

### ISSUE THREAD

**Issue by nickhammond** [rails/rails#47772]
Hi there,

All of the new changes in 7.1 have been really great and I've been starting new projects pointing at the main branch on github. I've been noticing really slow bundles because of the dependency resolution that needs to be done against github to make this happen though and with Rails being a large repository.

With 7.0 there were a few alpha releases that were published to rubygems.org, so you can easily point your gemfile to those alpha and release candidate versions.  

<img width="317" alt="image" src="https://user-images.githubusercontent.com/17698/227790326-148c044e-f4f0-448f-ab5e-f45d46f2d5be.png">

Would it be possible to publish something similar for 7.1.0.alpha so that people can point to the pre-cut gem on rubygems?

**Comment by skipkayhil** [comment]
Are you using Bundler 2.4+? Git gems were made much faster in https://github.com/rubygems/rubygems/pull/4475

As far as I know, alpha/RC releases are only done in preparation for the real release. It comes with additional constraints, such as only accepting bug fixes between alpha/RC and stable releases.

Since we reserve the issue tracker for bugs only, I'm going to have to close this issue. If you have further questions/suggestions I recommend asking on the [discord](https://discord.com/invite/d8N68BCw49) or the [forums](https://discuss.rubyonrails.org/)

**Comment by nickhammond** [comment]
Ah, yes thank you. I'll post on Forums.
