### ISSUE TITLE
Maintenance Policy chart

### ISSUE THREAD

**Issue by zzak** [rails/rails#47811]
Inspired by @gotoken's PR to ruby-lang: ruby/www.ruby-lang.org#2970, I'd love to see a similar chart for Rails maintenance policy.

I believe this should live on this page:
https://guides.rubyonrails.org/maintenance_policy.html

This document is important, and we still get asked about supported versions on a somewhat regular basis, so I think having an image that visualizes the current state will be very impactful.

I've just created a mock using Speadsheets:
![Screenshot 2023-03-30 at 9 08 30](https://user-images.githubusercontent.com/277819/228695864-ac76b5b6-533a-4e18-86ff-abddf0ef0896.png)

It would be great if this could be done in code, I've thought about maybe using a Gantt chart, but since we're not restricted by time (like Ruby releases on a schedule), it's a bit harder to do. The guides are published using markdown, so there might be something there -- or we can add something like Mermaid to the generator.

Open to ideas and suggestions there, last resort we just drop an image on the page.

**Comment by vipulnsward** [comment]
I can pick this up to do pragmatically if this gets a go ahead :-)

**Comment by matthewd** [comment]
I don't think it's practical to put this in the guides, because guides are versioned and published as part of the stable-branch release process. 

I think https://rubyonrails.org/maintenance would be the place to put it, so it exists outside the versioning continuum.

However, I'm fairly skeptical that an image can offer much insight; as you note, unlike Ruby, we don't have a strict calendar-driven release schedule / support period. The above page awkwardly defers to the guide version (through the security policy), but the guide you linked boils down to that same spreadsheet-style image, with the axes inverted, plus explanations of the terms. 

> we still get asked about supported versions

We do? I see occasional requests for backports to unsupported versions, but IMO they read more like someone not bothering to look (or knowing the answer and hoping that a specific request might bypass the policy), rather than people who've tried to find the policy and then failed to understand it.

---

One thing that I do think could be interestingly valuable for us to publish, in approximately this place, would be a recommended Ruby version range per Rails release series. It doesn't come up super often, but I have definitely seen people who are several versions behind on both dimensions, trying to work out which sequence of upgrades is likely to be smoothest.
