### ISSUE TITLE
Ambiguity in url_for

### ISSUE THREAD

**Issue by vovanmozg** [rails/rails#48013]
### Steps to reproduce

1. Create controller
```ruby
class PagesController < ApplicationController
  def page
    url = url_for(lang: params[:lang], country: params[:country])
    render json: {
      params: params,
      url_for: url
    }
  end
end
```

2. Create two routes the same controller
```ruby
Rails.application.routes.draw do
  scope '(:lang-:country)' do
    get 'page1', to: 'pages#page'
  end

  scope 'subdomain' do
    get 'page2', to: 'pages#page'
  end
end
```

3. Visit http://localhost:3000/subdomain/page2?lang=en&country=au

### Expected behavior
`url_for` must return "http://localhost:3000/subdomain/page2?lang=en&country=au"

### Actual behavior
`url_for` method returns "http://localhost:3000/de-de/page1"

###  Test case for `url_for`
```ruby
def test_multiple_routes
  with_routing do |set|
    set.draw do
      scope ':lang-:country' do
        get 'page1', to: 'index#index'
      end

      scope 'subdomain' do
        get 'page2', to: 'index#index'
      end
    end

    kls = Class.new { include set.url_helpers }
    kls.default_url_options[:host] = "www.basecamphq.com"

    assert_equal "http://www.basecamphq.com/page2?lang=en&country=au", kls.new.url_for(controller: "index", lang: "en", country: "us")
  end
end
```
changed file: https://github.com/vovanmozg/rails/commit/687d051ba4800b8d10cf93fc464b7eeb93470d1f

Maybe it's not really a bug, but it's unexpected behavior. url_for under the hood has to guess which route best matches the parameters passed. Most of the time it works well. But sometimes, when more than one route corresponds to one controller, errors can occur.

Could there be a way to avoid this problem? Maybe there is not enough information about the current route in the controller context?

### System configuration
**Rails version**: 7.0.4.3

**Ruby version**: 3.1.1

**Comment by JoeDupuis** [comment]
Hi! 
Thank you for providing an example test, but do try to provide a minimal (one file) reproduction script instead when opening an issue. 
It **really** helps the maintainers and will get you a faster answer.
There is some templates for it [here](https://github.com/rails/rails/tree/main/guides/bug_report_templates). You can ask for help on the [discord](https://discord.gg/d8N68BCw49) or the [forum](https://discuss.rubyonrails.org/) if you need help with building a repro script. 

[I have built one for you.](https://gist.github.com/JoeDupuis/e0f18020c85a05d5188ee35485685387) The route scopes and url params are red herrings.  
The issue is that `url_for` doesn't have enough info to guess which route it should return. 
It returns the first route that matches your controller and action.  You can play with the script or your own app. Switch the order of the two route and you'll see the other one.

[Repro script](https://gist.github.com/JoeDupuis/e0f18020c85a05d5188ee35485685387)

I am not sure using the current url (not just controller and action) to help infer the route is easily doable and desirable (could lead to bad performance), but I'll take a look this week.

**Comment by JoeDupuis** [comment]
I ended up building [a quick proof of concept.](https://github.com/rails/rails/commit/b6825f96834f05cdc8bac09f95278fe9f07159cf)
It's passing the repro script, but breaks 3 tests.
