### ISSUE TITLE
MIME type validation too strict

### ISSUE THREAD

**Issue by mak-dunkelziffer** [rails/rails#48052]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_simple_mime_type_parameter_works
    Mime::Type.register("application/vnd.api+json; profile=\"cursor-pagination\"", :jsonapi)
  end
  
  def test_mime_type_parameter_with_url_fails
    Mime::Type.register("application/vnd.api+json; profile=\"https://jsonapi.org/profiles/ethanresnick/cursor-pagination/\"", :jsonapi)
  end
end
```

### Expected behavior

Rails should understand MIME types of the following form:
```
application/vnd.api+json; profile="https://jsonapi.org/profiles/ethanresnick/cursor-pagination/" ext="https://jsonapi.org/ext/atomic"
```

Use case: creating a spec-conform implementation of the `JSON:API` spec with applied extensions and/or profiles:
- https://jsonapi.org/format/#media-type-parameter-rules
- https://jsonapi.org/extensions/

### Actual behavior

I was not able to register a MIME type with URLs as parameter values. The following error gets raised:
- `Mime::Type::InvalidMimeType: "application/vnd.api+json; profile=\"https://jsonapi.org/profiles/ethanresnick/cursor-pagination/\"" is not a valid MIME type`

Source: the following regex seems to be too strict and imposes the same limitations on parameter values that should only apply to parameter names:
- https://github.com/rails/rails/blob/3cca0d5205329e28a9879739bb2d3ae3cff1b14f/actionpack/lib/action_dispatch/http/mime_type.rb#L230

Maybe this is also a user error. Maybe the parameter value needs to be escaped or encoded in some manner. However, as even `\` and `%` are not allowed, I don't even know which escaping/encoding to use.

### System configuration
**Rails version**: 7.0.4.3

**Ruby version**: 3.2.0

**Comment by zzak** [comment]
I found #42177 which references [this cve](https://discuss.rubyonrails.org/t/cve-2021-22902-possible-denial-of-service-vulnerability-in-action-dispatch/77866), so I wonder if that is the reason for it being so strict.

@eregon Do you have any recommendations here? :bow:

**Comment by eregon** [comment]
I only refactored to avoid duplication, I didn't change any semantics, so I'm the wrong person to ask about this.

**Comment by ThunderKey** [comment]
I think that the issue is, that according to [RFC 2045 5.1.](https://datatracker.ietf.org/doc/html/rfc2045#section-5.1) the value can be either a token (like `MIME_NAME`) or a quoted string. In [RFC 822 3.3](https://datatracker.ietf.org/doc/html/rfc822#section-3.3) a quoted string can contain everything, including characters that are escaped with `\`.

I'm not sure if we need to be as relaxed as this definition. Potentially `(#{MIME_NAME}|"[^"\r\\]")` might suffice.

Additionally, whilst looking into this I've detected that the current implementation of `PARAMETER_SEPARATOR_REGEXP` does not work as intended. https://github.com/rails/rails/blob/48e4d99c75b7fded3d54c42883e49eddac879b39/actionpack/lib/action_dispatch/http/mime_type.rb#L155

To get the q-value, `split` is used with this Regexp: https://github.com/rails/rails/blob/48e4d99c75b7fded3d54c42883e49eddac879b39/actionpack/lib/action_dispatch/http/mime_type.rb#L199

```
irb(main):001:0> 'some/test; q=0.6'.split /;\s*\w+="?\w+"?/
=> ["some/test", ".6"]
irb(main):002:0> 'some/test; q="0.6"'.split /;\s*\w+="?\w+"?/
=> ["some/test", ".6\""]
```

This would be my first time contributing, but I'd be happy to tackle those issues.
