### ISSUE TITLE
Add Vite to javascript options

### ISSUE THREAD

**Issue by wJoenn** [rails/rails#48096]
I've been looking at the generator code for javascript and I figured that vite could fairly easily be added to the javascript options for new projects

I might be mistaken but I think that if we add an elsif in railties/lib/rails/generators/app_base.rb
```
def javascript_gemfile_entry
  return if options[:skip_javascript]

  if adjusted_javascript_option == "importmap"
    GemfileEntry.floats "importmap-rails", "Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]"
  elsif adjusted_javascript_option == "vite"
    GemfileEntry.floats "vite_rails", "Javascript and CSS bundler [https://github.com/ElMassimo/vite_ruby]"
  else
    GemfileEntry.floats "jsbundling-rails", "Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]"
  end
end
```

Then another when to run the installation
```
def run_javascript
  return if options[:skip_javascript] || !bundle_install?

  case adjusted_javascript_option
  when "importmap"                           then rails_command "importmap:install"
  when "vite                                         then run "bundle exec vite install"
  when "webpack", "esbuild", "rollup" then rails_command "javascript:install:#{adjusted_javascript_option}"
  end
end
```

Then it'd be pretty much it.
The asset-pipeline is not necessary when using Vite so that option would need to be ignored in the process if it wasn't set as `--skip-asset-pipeline` during project generation too

I've seen the subject of Vite being discussed in some closed issues but never with a simple option solution like this would be so hopefully I won't be the dude that offers the same idea that's been discussed and refused a number of time

Is this something you would be willing to explore ?
vite_rails isn't being developped by the Rails core team so maybe that'd be a reason you wouldn't, I don't know.
Just figured I would throw this idea because I'd really like to see it made.
Cheers

**Comment by eileencodes** [comment]
Hey @wJoenn we don't generally take feature requests on the issues tracker, we reserve it for bugs in the framework. The best place to have this discussion is on the forum https://discuss.rubyonrails.org/ or the contributors discord https://discord.gg/hCEnpP22.

That said, I think we'd be more likely accept a change to add a non-rails owned javascript option if the interface was agnostic to the external JS tool you're using. IE we don't want to have to keep doing if/elseif endlessly to add all the options. We should allow you to pass what you want and add it to the gemfile and it should just work. I'm not sure how feasible this is, but adding all the custom possibilities is not desirable (I get that you're only asking for 1 option, but if we add this we'll get more and more PRs to add on to it).

I'm going to close this because it's a feature request, let's move the discussion to the forum or discord
