### ISSUE TITLE
`String#blank?` raises when called on strings with invalid encoding

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#48149]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_blank_encodings
    raised = Encoding.list.select do |encoding|
      s1 = (+"foo_#{encoding.name.underscore}").force_encoding(encoding)
      s2 = (+"").force_encoding(encoding)

      begin
        s1.blank?
        s2.blank?
        false
      rescue
        true
      end
    end

    assert_equal 0, raised.length, raised
  end
end
```

### Expected behavior
Test should pass. `String#blank?` shouldn't raise when trying to check a regex.

### Actual behavior
`String#blank?` raises with the following encodings:

`
[#<Encoding:UTF-16BE>, #<Encoding:UTF-16LE>, #<Encoding:UTF-32BE>, #<Encoding:UTF-32LE>, #<Encoding:UTF-16 (dummy)>, #<Encoding:UTF-32 (dummy)>, #<Encoding:IBM037 (dummy)>, #<Encoding:ISO-2022-JP (dummy)>, #<Encoding:ISO-2022-JP-2 (dummy)>, #<Encoding:CP50220 (dummy)>, #<Encoding:CP50221 (dummy)>, #<Encoding:UTF-7 (dummy)>, #<Encoding:ISO-2022-JP-KDDI (dummy)>]
`

My read of https://github.com/rails/rails/pull/31049 and https://github.com/rails/rails/issues/28953 is that we want the method to work with *any* encoding.

### System configuration
**Rails version**: `main`

**Ruby version**: Same results in 2.7.3 and 3.1.3

**Comment by ghiculescu** [comment]
This diff passes the test:

```diff
diff --git a/activesupport/lib/active_support/core_ext/object/blank.rb b/activesupport/lib/active_support/core_ext/object/blank.rb
index 372f725047..05cc80e89f 100644
--- a/activesupport/lib/active_support/core_ext/object/blank.rb
+++ b/activesupport/lib/active_support/core_ext/object/blank.rb
@@ -126,7 +126,13 @@ def blank?
       begin
         BLANK_RE.match?(self)
       rescue Encoding::CompatibilityError
-        ENCODED_BLANKS[self.encoding].match?(self)
+        begin
+          ENCODED_BLANKS[self.encoding].match?(self)
+        rescue Encoding::ConverterNotFoundError, RegexpError
+          false
+        end
+      rescue ArgumentError
+        false
       end
   end
 end
diff --git a/activesupport/test/core_ext/string_ext_test.rb b/activesupport/test/core_ext/string_ext_test.rb
index aa52848962..2f31352eea 100644
--- a/activesupport/test/core_ext/string_ext_test.rb
+++ b/activesupport/test/core_ext/string_ext_test.rb
@@ -1195,3 +1195,15 @@ def some_method(x, y)
     assert_equal " foo\n \n bar", "foo\n\nbar".indent(1, nil, true)
   end
 end
+
+class StringBlankTest < ActiveSupport::TestCase
+  test "#blank? with any encoding" do
+    Encoding.list.each do |encoding|
+      string = (+"foo_#{encoding}").force_encoding(encoding)
+      assert_not string.blank?
+
+      string = (+"").force_encoding(encoding)
+      assert string.blank?
+    end
+  end
+end
```

But I wouldn't mind a second opinion because I'm not confident the solution is right.

**Comment by jonathanhefner** [comment]
Dummy encodings [don't have proper character handling anyway](https://ruby-doc.org/3.2.2/Encoding.html#method-i-dummy-3F), so I don't think we need to worry about them.  For the other encodings you mentioned, if you use `encode` instead `force_encoding`, the test passes.  Note the difference:

```ruby
"foo".force_encoding(Encoding::UTF_32LE).bytes
# => [102, 111, 111]

"foo".encode(Encoding::UTF_32LE).bytes
# => [102, 0, 0, 0, 111, 0, 0, 0, 111, 0, 0, 0]
```

I think it's probably reasonable for `blank?` to raise when the string has an invalid encoding.  If we were to return `false` instead, it might lead to surprising results.  Consider `" ".force_encoding(Encoding::UTF_32LE).blank?`.  Right now it raises, but I don't think returning `false` would be better.

With all that said, I've opened #48160 to ensure `String#blank?` is indeed compatible with every non-dummy encoding that is bundled with Ruby.

**Comment by ghiculescu** [comment]
For context, I suggested looking at every encoding because we expect Rails cache keys with any encoding to be valid: https://github.com/rails/rails/blob/114e9748679e0ed92a3f5395a212d6fee0dd8416/activesupport/test/cache/behaviors/encoded_key_cache_behavior.rb#L7

**Comment by casperisfine** [comment]
This is a bit of a tricky problem.

It's not that `blank?` doesn't work with some encoding, it's that it may not work on Strings with broken encoding. (e.g. `ISO-8859-1` bytes in a `Encoding::UTF_8` string).

I don't think there's wrong or bad solution to this, it could be argued either way.

On one hand you could argue that `blank?` shouldn't mess with encodings because if the string is broken, all bets are off.

On the other, `blank?` is often called on totally unknown values (including type), often received from e.g. `params`, so you could easily argue that it should never raise.

One solution could be for `String#blank?` to rescue the encoding error and to fallback to `self.b.blank?`.

**Comment by casperisfine** [comment]
A couple more notes:

> I suggested looking at every encoding because we expect Rails cache keys with any encoding to be valid

I saw your suggestion to use blank, but I used (or asked the implementer to use) `nil? || empty?` instead of `blank?` not to avoid a dependency on `String#blank?`, but because semantically, I don't think a "blank" string is necessarily an invalid cache key, only an empty or missing one.

That said, this hint to the fact that `blank?` is often used as a shortcut for `!nil? && !empty?`, similar to Python's "truthiness" (where `{}`, `[]`, `0` and `""` evalutate to `False` in boolean context).

But blank actually kinda have a "data validation" semantic by considering that a non empty string containing only "blank" characters is not present. The implementation intent is clearly: "Is this HTML form / database field blank business wise?".

But when you are working at a lower abstraction layer (typically a Rack middleware), this semantic is often undesirable. 

IMO it's a bit unfortunate that these two concepts got muddled together.

Maybe we need another method that is more like Python's `bool()` https://docs.python.org/3/library/stdtypes.html#truth-value-testing, but maybe that would have more it's place in a discussion on Ruby's tracker.

No idea how such method could be named though :/

**Comment by ghiculescu** [comment]
> That said, this hint to the fact that `blank?` is often used as a shortcut for `!nil? && !empty?`

Yes, that’s what I had in mind. But your explanation regarding business logic is correct, thank you for spelling it out.

**Comment by byroot** [comment]
Ok, closing as I think the current behavior is correct. We can reopen if you disagree.

**Comment by ghiculescu** [comment]
> On the other, `blank?` is often called on totally unknown values (including type), often received from e.g. `params`, so you could easily argue that it should never raise.
> 
> One solution could be for `String#blank?` to rescue the encoding error and to fallback to `self.b.blank?`.

Would you be open to a PR for this?

I think I still fall in the “it should never raise” camp.

**Comment by byroot** [comment]
> Would you be open to a PR for this?

I am, but wouldn't merge it without first getting an opinion from some other core members.
