### ISSUE TITLE
Exception in ERB template does not render exception view properly

### ISSUE THREAD

**Issue by jasonkim** [rails/rails#48173]
We've noticed that any error within the ERB template does not handle the error the same way as the error coming from controller. After some debugging, I noticed that there's an error thrown within [`create_template` call](https://github.com/rails/rails/blob/8226bba57f2dea0b97c02b4df4d0e9638644de03/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L77). From there, I found [this PR](https://github.com/rails/rails/pull/46171) that touched the relevant section. And validated the behavior with modified test below.

### Steps to reproduce

I've [changed the test scenario here](https://github.com/jasonkim/rails/commit/c7841c5e3acddaf046d0437a8011d1bd5e1573ae) to wrap the error case with noop if-statement, which should not change the behavior.
It changes the file `actionview/test/fixtures/test/runtime_error.html.erb` to
```erb
<h1>Oh no!</h1>
This template has a runtime error
<% if true %>
  <%= method_that_does_not_exist %>
<% end %>
Yikes!
```
This is used by the test `actionview/test/template/render_test.rb`

# Your reproduction script goes here
After making the above change (or checkout [this fork](https://github.com/jasonkim/rails)), run
```
cd actionview
bin/test test/template/render_test.rb
```

### Expected behavior
The test should pass

### Actual behavior
Test fails with error
```
Error:
LazyViewRenderTest#test_render_runtime_error:
RuntimeError: 
    /workspaces/rails/actionview/lib/action_view/template/handlers/erb.rb:113:in `find_offset'
    /workspaces/rails/actionview/lib/action_view/template/handlers/erb.rb:44:in `translate_location'
    /workspaces/rails/actionview/lib/action_view/template.rb:182:in `translate_location'
    /workspaces/rails/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:238:in `spot'
    /workspaces/rails/actionview/test/template/render_test.rb:220:in `test_render_runtime_error'


bin/test test/template/render_test.rb:212
```

### System configuration
**Rails version**:
main

**Ruby version**:
3.2

**Comment by casperisfine** [comment]
cc @tenderlove.

I'm not very familiar with this code, but the parser very clearly give up by raising `RuntimeError` when it fails to parse the template somehow.

Such raw `raise` suggest that it was expected this case wouldn't be hit, but clearly it is.

I suspect there are two fixes needed here:
  - This code is clearly valid, so we should be able to parse it fine, something in the parser need to be improved.
  - Even if we fixed that particular error, we should raise a proper error when we fail to parse, so that we can fallback to not mapping the source code.

I'll have a quick look at the second part of the fix.
