### ISSUE TITLE
Passing object with `id` in `where` parameters behaves differently in Rails 6.1 

### ISSUE THREAD

**Issue by rahul342** [rails/rails#48242]
In Rails 6.1, if you have a PORO with a attr_reader `:id`, Rails will pick up the `id` as a parameter to SQL conditional clause vs using the defined serialization method (like defining `value_for_database`?), but for `inserts` it will still use your overridden serialization method.
This wasn't the case in Rails 6.0.

### Steps to reproduce

Let's say I have this class
```ruby

#
# Table name: purchasable_items
#
#  id                  :integer          not null, primary key
#  name                :string(191)      not null
#  price_cents         :integer          not null
#  currency            :string(191)      not null
# index_purchasable_items_on_name_and_currency  (name,currency) UNIQUE
class PurchasableItem < ApplicationRecord
  enumerize :currency, in: ["USD", "KRW"], predicates: true
end
```
When the running the following code 

```ruby
2.times do |_|
 amount = Money.new(5000, 'KRW')
 PurchasableItem.find_or_create_by!(
      price_cents: amount.cents,
      currency: amount.currency,
      name: "some_name",
  )
end

```

In Rails 6.0, the following SQL queries are issued for mysql2 adapter
```sql
  [master] PurchasableItem Load (2.1ms)  SELECT `purchasable_items`.* FROM `purchasable_items` WHERE `purchasable_items`.`price_cents` = 5000 AND `purchasable_items`.`currency` = 'KRW' AND `purchasable_items`.`name` = 'some_name' LIMIT 1
  [master] (1.7ms)  BEGIN
  [master] PurchasableItem Create (2.4ms)  INSERT INTO `purchasable_items` (`name`, `price_cents`, `currency`) VALUES ('some_name', 5000, 'KRW')
  [master] (3.8ms)  COMMIT
  [master] PurchasableItem Load (1.8ms)  SELECT `purchasable_items`.* FROM `purchasable_items` WHERE `purchasable_items`.`price_cents` = 5000 AND `purchasable_items`.`currency` = 'KRW' AND `purchasable_items`.`name` = 'some_name' LIMIT 1
```
In Rails 6.1, the following SQL queries are issued for mysql2 adapter

```sql
PurchasableItem Load (4.9ms)  SELECT `purchasable_items`.* FROM `purchasable_items` WHERE `purchasable_items`.`price_cents` = 5000 AND `purchasable_items`.`currency` = 'krw' AND `purchasable_items`.`name` = 'some_name' LIMIT 1
TRANSACTION (2.1ms)  BEGIN
PurchasableItem Create (2.3ms)  INSERT INTO `purchasable_items` (`name`, `price_cents`, `currency`) VALUES ('some_name', 5000, 'KRW')
TRANSACTION (5.6ms)  COMMIT
PurchasableItem Load (1.8ms)  SELECT `purchasable_items`.* FROM `purchasable_items` WHERE `purchasable_items`.`price_cents` = 5000 AND `purchasable_items`.`currency` = 'krw' AND `purchasable_items`.`name` = 'some_name' LIMIT 1 
TRANSACTION (1.8ms)  BEGIN
PurchasableItem Create (4.4ms)  INSERT INTO `purchasable_items` (`name`, `price_cents`, `currency`) VALUES ('some_name', 5000, 'KRW')
TRANSACTION (2.8ms)  ROLLBACK
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry 'some_name-KRW' for key 'index_purchasable_items_on_name_and_currency'
```
This example uses [enumerize](https://github.com/brainspec/enumerize) and [money](https://github.com/RubyMoney/money)
Here's the stacktrace from my local for Rails 6.0
```ruby
 "/Users/rahulagrawal/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/money-6.13.2/lib/money/currency.rb:364:in `to_s'",
 "/Users/rahulagrawal/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/enumerize-2.3.1/lib/enumerize/attribute.rb:44:in `find_value'",
 "/Users/rahulagrawal/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/enumerize-2.3.1/lib/enumerize/activerecord.rb:102:in `serialize'",
 "/Users/rahulagrawal/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activemodel-6.0.6.1/lib/active_model/attribute.rb:55:in `value_for_database'",
 "/Users/rahulagrawal/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activerecord-6.0.6.1/lib/active_record/relation/query_attribute.rb:13:in `value_for_database'",
 "/Users/rahulagrawal/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activerecord-6.0.6.1/lib/active_record/statement_cache.rb:53:in `map'",
 "/Users/rahulagrawal/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activerecord-6.0.6.1/lib/active_record/statement_cache.rb:53:in `sql_for'",
 "/Users/rahulagrawal/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activerecord-6.0.6.1/lib/active_record/statement_cache.rb:132:in `execute'",
 "/Users/rahulagrawal/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activerecord-6.0.6.1/lib/active_record/core.rb:214:in `find_by'"
```

I am not sure if this is internal API that was not supposed to be used.

### Expected behavior

Ideally, IMO, for non-rails types Rails should either error or simply allow the user to define a way to cast value for database. I tried to read through the code and documentation, but couldn't find a recommended way to be able to pass custom objects to ActiveRecord methods.
Irrespectively, it looks the behavior varies for insert vs selects.

### Actual behavior
In Rails 6.1, if you have a PORO which has attr reader `:id`, Rails will pick up the `id` as a parameter to SQL conditional clause vs using the defined serialization method (like defining `value_for_database`), but for `inserts` it will still use your overridden serialization method.

### System configuration
**Rails version**:
Rails 6.0.6.1
enumerize-2.3.1
money-6.13.2

**Ruby version**:
ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-darwin22]

**Comment by nickborromeo** [comment]
👋 @rahul342 hope you don't mind that I took a stab at making the repro script for this and dig a little as to what is happening. 

Using this script (please make sure I am capturing your report correctly 🙇 )

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  # gem "activerecord", "6.0.6.1" # makes the test pass
  gem "activerecord", "6.1" # throws and exception
  gem "sqlite3"
  gem "money"
  gem "enumerize"
  gem "pry"
end

require "active_record"
require "minitest/autorun"
require "logger"
require "money"
require "pry"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :purchasable_items do |t|
    t.string :name
    t.integer :price_cents
    t.string :currency
    t.string :thing
  end

  add_index :purchasable_items, [:name, :currency], unique: true
end

class PurchasableItem < ActiveRecord::Base
  extend Enumerize

  enumerize :currency, in: ["USD", "KRW"], predicates: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    2.times do |_|
      amount = Money.new(5000, 'KRW')
      PurchasableItem.find_or_create_by(
        price_cents: amount.cents,
        currency: amount.currency,
        name: "some_name",
      )
    end
  end
end
```

Looking at the difference between `6.0.6.1` and `6.1.0` the `find_by` method has changed

###  6.1.0
https://github.com/rails/rails/blob/914caca2d31bd753f47f9168f2a375921d9e91cc/activerecord/lib/active_record/core.rb#L329-L363

### 6.0.6.1
https://github.com/rails/rails/blob/28bb76d3efc39b2ef663dfe2346f7c2621343cd6/activerecord/lib/active_record/core.rb#L192-L218

Specifically its this line

https://github.com/rails/rails/blob/914caca2d31bd753f47f9168f2a375921d9e91cc/activerecord/lib/active_record/core.rb#LL335C8-L335C8

Looking at the attributes being passed to `find_by` we see its

```
attributes {:price_cents=>5000, :currency=>#<Money::Currency id: krw, priority: 100, symbol_first: true, thousands_separator: ,, html_entity: &#x20A9;, decimal_mark: ., name: South Korean Won, symbol: ₩, subunit_to_unit: 1, exponent: 0, iso_code: KRW, iso_numeric: 410, subunit: , smallest_denomination: 1, format: >, :name=>"some_name"}
```

because of that new line added to `find_by` that checks if the arg responds to `id` we return the value of `krw` in this particular example. When we query for the second time to see if the record already exists, it uses the lower case `krw` instead of `KRW`. This will not make the query return anything thus it will attempt to insert and raise the unique constraint error.

I took a look at the Money gem and I think one way to do this is to use the `iso_code` method it provides on its Currency object

```
      PurchasableItem.find_or_create_by(
        price_cents: amount.cents,
        currency: amount.currency.iso_code,
        name: "some_name",
      )
```

Doing this passes the repo script in both 6.0 and 6.1

**Comment by rahul342** [comment]
Hi @nickborromeo, thank you very much for reproducing this and trying it. Much appreciated.

And you're correct it's checking for `:id` method on any object and simply defaulting to use that irrespectively of whether the developers intends to. Even if that's the agreeable behavior, it doesn't do the same thing when doing `INSERT`.
Doing `amount.currency.iso_code` or `amount.currency.to_s` would all work. The point was around handling in ActiveRecord ruby objects that are not of base types (like `string`)

**Comment by nickborromeo** [comment]
@rahul342 from the things I have looked I am more inclined this is happening because of how the `Currency` object is modeled and what it uses for its `id`. 

From what I understand, creating a record and passing an object to one of it attributes, ActiveRecord will automatically type cast that into the type in the schema. In this case its a string and when you call `to_s` on `amount.currency` as we already saw returns `"KRW"`.

As for the finding the record, this is where I think the gem is at _fault_ here (not the best word but could not think of another). Since its a object that responds to `:id` and that value is `krw`; which in the query to find the record, it will not match because of its lower case.

**Comment by rahul342** [comment]
> As for the finding the record, this is where I think the gem is at fault here (not the best word but could not think of another).

I am not a contributor on the gem, but I think it's OK to have `:id` as an attribute on any random class. Nor does Rails marks it as a reserved keyword afaik.

As mentioned in previous posts, Rails behaving inconsistently between `create`/`INSERT` and `find`/`SELECT` is definitely a problem IMO.

Anyhow, doesn't look the ticket is getting any traction per se, nor have other users of Rails raised this issue (from what I could search on Github). Happy to close it, if there's nothing to solve here currently.

**Comment by rafaelfranca** [comment]
I agree there is a problem on how `create` is handling objects that respond to `id`. I believe that we should make it consistent and also call `:id` if the object responds to it. The problem is that changing this behavior will start to silently corrupt databases since the values being written will change and people will not notice until it is too late.

So I think the best course of action is to keep the behavior as is.

Change change on `SELECT` was made so you could pass a Active Record object decorated, so maybe we should the code the select code to call something that is more Active Record specific in this decoration instead of `id`? I'd be open for a PR that does that.

**Comment by nickborromeo** [comment]
> so maybe we should the code the select code to call something that is more Active Record specific in this decoration instead of id

@rafaelfranca I think doing this will revert back to what it looked before and it seemed like the move was done intentionally in https://github.com/rails/rails/commit/19850107cdaf0525861a4c88748d0e1d9d41516b which was primarily done for https://github.com/rails/rails/pull/40554

**Comment by rafaelfranca** [comment]
We will not revert back, we will fix forward. We should allow decoration, but not using `id`. Maybe we should allow decoration with `to_param` or any other method (`to_record` maybe) that we define which `ActiveRecord::Base` can alias to `id`.

**Comment by rafaelfranca** [comment]
Maybe `to_key` is the right method to be used http://api.rubyonrails.org/classes/ActiveModel/Conversion.html#method-i-to_key
