### ISSUE TITLE
[Question] any plan to support `load_async()` with `ActiveRecord::Base.connected_to` ?

### ISSUE THREAD

**Issue by r-plus** [rails/rails#48351]
Hi guys

Is it possible to use async query by `load_async()` inside the block of `ActiveRecord::Base#connected_to` method to connect to replica database?

In my investigation, currently no.
Because `connected_to` method immediately call `load` method if return value is `ActiveRecord::Relation`, as the result asynchronous query execution back to foreground.
https://github.com/rails/rails/blob/4e71edfca8525417597b079440d876310dd6290d/activerecord/lib/active_record/connection_handling.rb#L355

Do you have any plan to support `load_async()` support inside the `ActiveRecord::Base#connected_to` ?

**Comment by eileencodes** [comment]
I hadn't thought about whether this was supported until now. I don't even love that we call `load` in here - the only reason we do is because I saw too many cases where applications were expecting to use the return value of a `connected_to` block and have it been loaded already.

I think a way we could support this is to add an `async` option to `connected_to` and pass that down - if it's true we call `load_async` otherwise we call `load`. 

Do you want to work on a PR?

**Comment by r-plus** [comment]
@eileencodes 

I understand that your proposal is such a change.

```diff
-      def with_role_and_shard(role, shard, prevent_writes)
+      def with_role_and_shard(role, shard, prevent_writes, async)
         prevent_writes = true if role == ActiveRecord.reading_role

         append_to_connected_to_stack(role: role, shard: shard, prevent_writes: prevent_writes, klasses: [self])
         return_value = yield
-        return_value.load if return_value.is_a? ActiveRecord::Relation
+        if return_value.is_a? ActiveRecord::Relation
+          if async
+            return_value.load_async
+          else
+            return_value.load
+          end
+        end
         return_value
```

How about this change without adding argument to method?

```diff
-        return_value.load if return_value.is_a? ActiveRecord::Relation
+        return_value.load if return_value.is_a? ActiveRecord::Relation && !return_value.scheduled?
```

expected usage in this case.

```ruby
ActiveRecord::Base.connected_to(role: :reading) do
  User.where(id: 1).load_async
end
```

**Comment by eileencodes** [comment]
I don't know if the second one will work and I'm not able to test right now. I'm fine with either, but we need to make sure the second option actually does what we expect (load async from the replica db). 

The reason `load` was added was because if you assign the block to a return value, the relation won't be loaded until it's used outside the block which will result in reading from the primary db and not the replica as intended. So with `load_async` , regardless of the method we choose, we need to be sure it's reading from the right db.

More information can be found in the PR https://github.com/rails/rails/pull/38339 and reported issue https://github.com/rails/rails/issues/38332

**Comment by r-plus** [comment]
yah, I know why calling `load` method for `ActiveRecord::Relation` instance.
I believe that concern does not apply to `load_async` method because it will start query in background thread even if not used returned instance out side the block.

I implemented the second change with a test, and it passed, so I think it's fine.
I'll open a pull request with this change, thanks :)

**Comment by matthewd** [comment]
I think your challenge is going to be around the possibility of `load` being called, outside the block, after the relation has been told to `load_async` (on the correct connection), but before the background execution has started.

In that case I believe `load` will actively run the query itself... and that's going to need to happen on the right connection.

I wonder if we could/should _not_ do the `load` behaviour at all, and instead arrange to "pin" the choice of connection on the relation as it leaves the block, so we'll then use the right connection whenever, and however, it later gets loaded. 🤔

**Comment by r-plus** [comment]
thanks for your suggestion.
hmm, Is there any code that would be helpful in pinning the connection?

**Comment by eileencodes** [comment]
> hmm, Is there any code that would be helpful in pinning the connection?

This isn't currently possible and I'm not sure what mechanism we'd use for this. Essentially the `connected_to` block changes the _context_ in which a connection is looked up, but does not actually handle finding the correct connection from the PoolManager. So to illustrate what I mean here's a code example with comments.

```ruby
# every connection is keyed like Owner Class name -> `PoolManager` -> `role` -> `shard` 
# where `PoolManager` holds multiple role to shard mappings for a given class
# outside block default context is writing role and shard named default
ActiveRecordBase.connected_to(role: :reading, shard: :one) do # changes "context" to reading role and shard one
  Post.first # goes up the inheritance chain looking for the connection based on the given context
end
# we've left the block, context is returned to default values (role writing, shard default)
```
  
The thing is once we leave the block, we no longer have the context to switch the connection. Active Record doesn't (yet) have a way to track the connection context in order to pin it. I once tried to do something like this so we could have an API for switching connections in individual queries but it ended up feeling really hard and I tabled it for now.
