### ISSUE TITLE
Pattern matching for ActionController::Parameters

### ISSUE THREAD

**Issue by Timmitry** [rails/rails#48429]
### Steps to reproduce

```ruby
ActionController::Parameters.new(a: 1, b: 2) => {a:}
```

### Suggested behavior

The statement will match and assign `a = 1`.

### Actual behavior

```
NoMatchingPatternError: #<ActionController::Parameters {"a"=>1, "b"=>2} permitted: false>: #<ActionController::Parameters {"a"=>1, "b"=>2} permitted: false> does not respond to #deconstruct_keys
```

### Workaround

```ruby
ActionController::Parameters.new(a: 1, b: 2).to_unsafe_hash => {a:}
```

### System configuration
**Rails version**:
7.0.4.3

**Ruby version**:
3.1.3

### Comments

I wonder if this is something that might be worth implementing. It would be as easy as to add the following code:

```ruby
# lib/action_controller/metal/strong_parameters.rb
def deconstruct_keys(_keys)
  @parameters
end
```

Since we are explicitly matching variables here, I do not see the need for something like `permit` - it's the same as using `a = params.fetch(:a)`, which is perfectly valid for me.

Some thought should be taken to the usage of

```ruby
ActionController::Parameters.new(a: 1, b: 2) => {a:, **kwargs}
```

which will lead to a variable `kwargs = { b: 2 }`, which again would be problematic if used for mass updating.

**Comment by skipkayhil** [comment]
Hey @Timmitry, thanks for the suggestion! The best place to discuss this would be on the [forum](https://discuss.rubyonrails.org/) or [discord](https://discord.gg/d8N68BCw49). Since we reserve the issue tracker for bugs only, I'm going to close this

(I will link you to a related discussion about pattern matching for Active Model: https://github.com/rails/rails/pull/45553#issuecomment-1179568855)

**Comment by seanpdoyle** [comment]
This has been implemented by https://github.com/rails/rails/pull/55789.
