### ISSUE TITLE
Replacing an association removes entries even when the parent doesn't pass validations

### ISSUE THREAD

**Issue by Earlopain** [rails/rails#48469]
I've been investigating an issue in my app where an association doesn't correctly undo changes when the parent fails validation. This seems to be the case because I'm directly setting the association which then updates to the database before even calling save.

Adding to the association is not possible, however removing from the association goes through. Please see the attached reproduction script, that should hopefully make it a bit more clear what I'm talking about.

Edit: Initially I thought it had something to do with `autosave: true` but it's reproducable without that as well.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :title
  end

  create_table :groups, force: true do |t|
    t.integer :post_id
    t.text :text
  end
end

class Post < ActiveRecord::Base
  has_many :groups

  attr_accessor :fail_validation

  validate :always_fail, if: :fail_validation

  def always_fail
    errors.add(:base, "Fail")
  end

  def group_string
    groups.map { |a| a.text }.sort.join(" ")
  end

  def group_string=(string)
    self.groups = string.split(" ").map do |group|
      self.groups.find_or_initialize_by(text: group)
    end
  end
end

class Group < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(title: "Hello!")
    post.group_string = "1 2"
    post.save

    assert_equal("1 2", post.group_string)
    assert_equal("Hello!", post.title)

    post.fail_validation = true

    post.group_string = "1 2 3"
    post.title = "Goodbye!"
    post.save

    post.reload
    assert_equal("Hello!", post.title, "Title got changed despite failed validation")
    assert_equal("1 2", post.group_string, "Group '3' got added despite failed validation")

    post.fail_validation = true

    post.group_string = "1"
    post.title = "Goodbye!"
    post.save

    post.reload
    assert_equal("Hello!", post.title, "Title got changed despite failed validation")
    assert_equal("1 2", post.group_string, "Group '2' got removed despite failed validation")
  end
end

```

### Expected behavior
Both adding and removing associations should fail if the parent fails validation.

### Actual behavior
Only added associations fail, removing is possible.

### System configuration
**Rails version**: master

**Ruby version**: 3.2.2

**Comment by adrianna-chang-shopify** [comment]
👋 Hey @Earlopain , thanks for opening this issue! Took a look at the repro, and I don't think the behaviour is related to autosave (and indeed the test still fails if I remove the `autosave` option). If we add some print statements to your script:

```ruby
class Post < ActiveRecord::Base
  def group_string=(string)
    puts "--- finding / initializing groups" # added
    groups = string.split(" ").map do |group|
      self.groups.find_or_initialize_by(text: group)
    end
    puts "--- setting groups" # added
    self.groups = groups
  end
end

...

class BugTest < Minitest::Test
  def test_association_stuff
    ...

    post.group_string = "1"
    post.title = "Goodbye!"
    puts "--- saving post" # added
    post.save

    post.reload
    assert_equal("Hello!", post.title, "Title got changed despite failed validation")
    assert_equal("1 2", post.group_string, "Group '2' got removed despite failed validation")
  end
```

And then take a look at the output in conjunction with the SQL:

```
# Running:

D, [2023-06-15T15:33:33.498392 #80813] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2023-06-15T15:33:33.498482 #80813] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" ("title") VALUES (?)  [["title", "Hello!"]]
D, [2023-06-15T15:33:33.498575 #80813] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
--- finding / initializing groups
D, [2023-06-15T15:33:33.556106 #80813] DEBUG -- :   Group Load (0.1ms)  SELECT "groups".* FROM "groups" WHERE "groups"."post_id" = ? AND "groups"."text" = ? LIMIT ?  [["post_id", 1], ["text", "1"], ["LIMIT", 1]]
D, [2023-06-15T15:33:33.566520 #80813] DEBUG -- :   Group Load (0.1ms)  SELECT "groups".* FROM "groups" WHERE "groups"."post_id" = ? AND "groups"."text" = ? LIMIT ?  [["post_id", 1], ["text", "2"], ["LIMIT", 1]]
--- setting groups
D, [2023-06-15T15:33:33.567008 #80813] DEBUG -- :   Group Load (0.0ms)  SELECT "groups".* FROM "groups" WHERE "groups"."post_id" = ?  [["post_id", 1]]
D, [2023-06-15T15:33:33.567758 #80813] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2023-06-15T15:33:33.567894 #80813] DEBUG -- :   Group Create (0.2ms)  INSERT INTO "groups" ("post_id", "text") VALUES (?, ?)  [["post_id", 1], ["text", "1"]]
D, [2023-06-15T15:33:33.568063 #80813] DEBUG -- :   Group Create (0.0ms)  INSERT INTO "groups" ("post_id", "text") VALUES (?, ?)  [["post_id", 1], ["text", "2"]]
D, [2023-06-15T15:33:33.568139 #80813] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
--- finding / initializing groups
D, [2023-06-15T15:33:33.570388 #80813] DEBUG -- :   Group Load (0.0ms)  SELECT "groups".* FROM "groups" WHERE "groups"."post_id" = ? AND "groups"."text" = ? LIMIT ?  [["post_id", 1], ["text", "1"], ["LIMIT", 1]]
D, [2023-06-15T15:33:33.570679 #80813] DEBUG -- :   Group Load (0.0ms)  SELECT "groups".* FROM "groups" WHERE "groups"."post_id" = ? AND "groups"."text" = ? LIMIT ?  [["post_id", 1], ["text", "2"], ["LIMIT", 1]]
D, [2023-06-15T15:33:33.570837 #80813] DEBUG -- :   Group Load (0.0ms)  SELECT "groups".* FROM "groups" WHERE "groups"."post_id" = ? AND "groups"."text" = ? LIMIT ?  [["post_id", 1], ["text", "3"], ["LIMIT", 1]]
--- setting groups
D, [2023-06-15T15:33:33.571629 #80813] DEBUG -- :   Post Load (0.1ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
D, [2023-06-15T15:33:33.571876 #80813] DEBUG -- :   Group Load (0.0ms)  SELECT "groups".* FROM "groups" WHERE "groups"."post_id" = ?  [["post_id", 1]]
--- finding / initializing groups
D, [2023-06-15T15:33:33.572092 #80813] DEBUG -- :   Group Load (0.0ms)  SELECT "groups".* FROM "groups" WHERE "groups"."post_id" = ? AND "groups"."text" = ? LIMIT ?  [["post_id", 1], ["text", "1"], ["LIMIT", 1]]
--- setting groups
D, [2023-06-15T15:33:33.572451 #80813] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2023-06-15T15:33:33.572512 #80813] DEBUG -- :   Group Update All (0.1ms)  UPDATE "groups" SET "post_id" = ? WHERE "groups"."post_id" = ? AND "groups"."id" = ?  [["post_id", nil], ["post_id", 1], ["id", 2]]
D, [2023-06-15T15:33:33.572594 #80813] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
--- saving post
D, [2023-06-15T15:33:33.574228 #80813] DEBUG -- :   Post Load (0.0ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
D, [2023-06-15T15:33:33.574509 #80813] DEBUG -- :   Group Load (0.0ms)  SELECT "groups".* FROM "groups" WHERE "groups"."post_id" = ?  [["post_id", 1]]
F

Failure:
BugTest#test_association_stuff [../scripts/48469_autosave_rollback.rb:90]:
Group '2' got removed despite failed validation.
Expected: "1 2"
  Actual: "1"


bin/rails test ../scripts/48469_autosave_rollback.rb:63
```

you'll see that we update the groups in the database via `self.groups = groups` _before_ even calling `save!` on the post:
```
--- setting groups
D, [2023-06-15T15:33:33.572451 #80813] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2023-06-15T15:33:33.572512 #80813] DEBUG -- :   Group Update All (0.1ms)  UPDATE "groups" SET "post_id" = ? WHERE "groups"."post_id" = ? AND "groups"."id" = ?  [["post_id", nil], ["post_id", 1], ["id", 2]]
D, [2023-06-15T15:33:33.572594 #80813] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
--- saving post 
# At this point, we've already updated the association in the db
```

Taking a closer look at the code, this is because the `groups=` writer will replace records directly, without taking into consideration whether the parent is valid or not:
https://github.com/rails/rails/blob/87ab32f72a494ea18a4e2335becaebb66f5ce673/activerecord/lib/active_record/associations/collection_association.rb#L44-L46

https://github.com/rails/rails/blob/87ab32f72a494ea18a4e2335becaebb66f5ce673/activerecord/lib/active_record/associations/collection_association.rb#L251

https://github.com/rails/rails/blob/87ab32f72a494ea18a4e2335becaebb66f5ce673/activerecord/lib/active_record/associations/collection_association.rb#L412-L422

(Contrarily, attempting to add a new group _doesn't_ work because it's only via `post.save!` that we would attempt to persist the new group "3" to the db, and since the parent is invalid, this doesn't work).

It seems like the behaviour we care more about is whether [`#collection=` on a `has_many` association](https://guides.rubyonrails.org/association_basics.html#methods-added-by-has-many-collection-objects) should care about whether the parent is valid when mutating the collection, and I don't think it does 🤔

**Comment by Earlopain** [comment]
Hi Adrianna,

Thanks for taking a peek at this. I didn' think of trying without autosave, it just seemed so obvious to me that this behaviour has something to do with that. I've updated the issue/repro script accordingly.

I edited the title to what I believe you are saying, but feel free to update it if I didn't get it right.

**Comment by adrianna-chang-shopify** [comment]
The title looks right to me, but I'm not sure it should be considered a bug (maybe others have input though..?) The [docs](https://api.rubyonrails.org/v7.0.5/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many) say:
> collection=objects
Replaces the collections content by deleting and adding objects as appropriate. If the :through option is true callbacks in the join models are triggered except destroy callbacks, since deletion is direct by default. You can specify dependent: :destroy or dependent: :nullify to override this.

So there's no mention of whether the collection should _not_ be mutated if the parent is invalid. Interestingly, the `#collection<<(object, …)` mentions
> Adds one or more objects to the collection by setting their foreign keys to the collection's primary key. Note that this operation instantly fires update SQL without waiting for the save or update call on the parent object, unless the parent object is a new record. This will also run validations and callbacks of associated object(s).

So this one mentions more explicitly that the collection is modified without saving / validating the parent.

**Comment by Earlopain** [comment]
`create` seems to specify direct modification as well.

The mixed behaviour for adding/removing really threw me for a loop when figuring out what was happening. I my application I have an `after_save` callback on the parent class which is supposed to log changes to the group string. If validations fail I am missing out on these edits which gives a wrong impression of the history.

I guess a large part of my confusion is coming from the fact that the attribute looks like it's from the parent when it really is a proxy to the collection. Either way, very surprising behaviour.

**Comment by Earlopain** [comment]
Closing because the behaviour seems documented.
