### ISSUE TITLE
ActiveStorage: Convert has no effect on content_type in the variants Options

### ISSUE THREAD

**Issue by vincent-the** [rails/rails#48801]
### Steps to reproduce

In Model:
```ruby
class User < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :medium, {resize_to_limit: [500, 500], convert: :webp}
  end
end
```
In View:

```ruby
<%= image_tag user.image.variant(:medium) %>
```

### Expected behavior
The content_type should be set to image/webp, and the filename extension should be changed to .webp as well.

### Actual behavior
The image is converted to webp, but content_type and extension remains jpeg.

### System configuration
**Rails version**: 7.0.4
**Ruby version**: 3.2.2

**Comment by pdmholden** [comment]
I can confirm that the variant conversion itself seems to be working. I tested with the following specs:

```
diff --git a/activestorage/test/models/variant_test.rb b/activestorage/test/models/variant_test.rb
index 15beb3e664..49bb915b9d 100644
--- a/activestorage/test/models/variant_test.rb
+++ b/activestorage/test/models/variant_test.rb
@@ -146,6 +146,22 @@ class ActiveStorage::VariantTest < ActiveSupport::TestCase
     assert_equal "PNG", read_image(variant).type
   end
 
+  test "WEBP variation of JPEG blob with lowercase format" do
+    blob = create_file_blob(filename: "racecar.jpg")
+    variant = blob.variant(format: :webp).processed
+    assert_equal "racecar.webp", variant.filename.to_s
+    assert_equal "image/webp", variant.content_type
+    assert_equal "WEBP", read_image(variant).type
+  end
+
+  test "WEBP variation of JPEG blob with uppercase format" do
+    blob = create_file_blob(filename: "racecar.jpg")
+    variant = blob.variant(format: :WEBP).processed
+    assert_equal "racecar.webp", variant.filename.to_s
+    assert_equal "image/webp", variant.content_type
+    assert_equal "WEBP", read_image(variant).type
+  end
+
   test "variation of invariable blob" do
     assert_raises ActiveStorage::InvariableError do
       create_file_blob(filename: "report.pdf", content_type: "application/pdf").variant(resize_to_limit: [100, 100])
```

I'll keep poking around and see if I can find the source of the problem.

### System Configuration

Rails: 7.1.0.alpha
Ruby: 3.2.2

**Comment by pdmholden** [comment]
I think the option you need to pass is `format`, not `convert`. I wrote a test that I've linked [in this gist](https://gist.github.com/pdmholden/ba01ddfff30b252f3f15253083ec2fa9) that shows it works with the `format` option.

Caveat: While I've been a Rails application developer for a while, I'm relatively new to the Rails codebase itself, so I could have missed something.

**Comment by vincent-the** [comment]
> I think the option you need to pass is `format`, not `convert`. I wrote a test that I've linked [in this gist](https://gist.github.com/pdmholden/ba01ddfff30b252f3f15253083ec2fa9) that shows it works with the `format` option.
> 
> Caveat: While I've been a Rails application developer for a while, I'm relatively new to the Rails codebase itself, so I could have missed something.

Many thanks @pdmholden for your efforts! I have also tested with `format` unfortunately this has no other effect for me like `convert`.

**Comment by brenogazzola** [comment]
Can you give more detail on where you are seeing the wrong filename and content type? Is it in the network tab of your browser? Is it in the created blob? Also, do you have variant tracking enabled?

I'm asking because there are some gotchas in AST behaviour. For example, when if you have variant tracking disabled, this works, because the result of `processed` is a `Variant`, and that's what you are seeing on your test:
```
ActiveStorage::Blob.find(ID).variant(format: :webp).processed.filename
# => logo.webp
```

On the other hand, if you have variant tracking enabled, the same line will break, because the result of `processed` is a `VariantWithRecord`, and that class does not have a `.filename` method. So if you try to go to the blob instead:
```
ActiveStorage::Blob.find(ID).variant(format: :webp).processed.blob.filename
# => logo.jpg
```

You will get the impression that filename did not change, but that's actually because `.blob` is the blob of the **original** image, not the variant's.

**Comment by vincent-the** [comment]
Many thanks @brenogazzola for your efforts! im Network tab hat das Bild das Format jpg und den content type image/jpeg. This corresponds to the original format or content type of the image. I cannot fully understand what you say in your commentary or derive measures for my Issue.

**Comment by brenogazzola** [comment]
The difference you are seeing is because you are using Active Storage in redirect mode, while I'm using it in proxy mode.

As for a webp being loaded behind a jpeg, that's perfectly fine. It's normal for us to look at your URL and think "Ok, that's the URL of a JPEG image", but the browser does not do that. They don't make assumptions about the response based on what the URL looks like. They will simply make the GET request and only after taking a look at the `Content-Type` header in the response will they decide how to deal with body of the response (in this case, an image).

CDNs like Cloudflare in fact take advantage of this by taking a look at what image formats the browser can handle, and then serving the most modern one they can. For example, send a JPEG image through Cloudflare and if it notices that your user's browser can handle WEBP, it will automatically convert the image to WEBP before sending it.
