### ISSUE TITLE
Direct Routes aren't reflected in list of available routes via `bin/rails routes`

### ISSUE THREAD

**Issue by dylanfisher** [rails/rails#48866]
Adding [direct routes](https://guides.rubyonrails.org/routing.html#direct-routes) to your application don't seem to be reflected in the list of available routes. I'm not sure if this is intentional or not, but it seems counterintuitive in my first time using the `direct` route option.

### Steps to reproduce

```ruby
# routes.rb

direct :homepage do
  "http://www.rubyonrails.org"
end
```

```
bin/rails routes | grep homepage
=> no results
```

The direct route helpers do work in the app, but they aren't reflected in the list of routes.

### System configuration
**Rails version**: 7.0.6

**Ruby version**: 3.2.2

**Comment by geraldspreer** [comment]
I have looked into this issue. `direct` routes are not added to the collection of routes. Instead, when these `direct`, `resolve` and `polymorphic` routes are defined, they are added as `url_helpers` which are available throughout the application.
Making these `direct` "routes" appear in the list provided by `rails routes` or `rails/info/routes` is a good idea, but it would be necessary to distinguish between `url_helpers` that are defined in `routes.rb` and `url_helpers` which are created elsewhere.

**Comment by Jay0921** [comment]
The fact that the `direct` method or named routes do not appear in the `rails routes` list makes sense. The `direct` method is used to create a URL helper method, not to define a route that the application will respond to. Therefore, it won't show up in the list of routes because it doesn't represent a request that the application handles.

We define the helper method in order to make it accessible throughout the entire application.
```
# routes.rb
direct :homepage do 
  "https://rubyonrails.org/" 
end
  
#index.html
<%= link_to "Visit Ruby on Rails", homepage_url %>
```

If you want the application to respond to the path `/homepage`, you can make the following adjustments. By doing so, your application will not only respond to `/homepage` but also make the `homepage_url` helper method available throughout the entire application. Additionally, the path will be included in the `rails routes` list.
```
# routes.rb
get "/homepage", to: redirect("https://rubyonrails.org/"), as: :homepage
  
#index.html
<%= link_to "Visit Ruby on Rails", homepage_url %>
```
