### ISSUE TITLE
Rails 7.0.6 cannot update credentials from files

### ISSUE THREAD

**Issue by m2wasabi** [rails/rails#48900]
### Steps to reproduce

```shell
EDITOR="cat .config_development.yml >" bundle exec rails credentials:edit -e development
```

### Expected behavior

`.config_development.yml` is encrypted into `config/credentials/development.yml.enc`

This works successful up to Rails 7.0.5.1 .

### Actual behavior

Encrypt task finish with error.

> cat: '>': No such file or directory

Decrypted content is deferent from input file.

```shell
bundle exec rails credentials:edit -e development
```

```yaml
# aws:
#   access_key_id: 123
#   secret_access_key: 345
```

### System configuration
**Rails version**:
7.0.6

**Ruby version**:
3.0.4

**Comment by Ballen7** [comment]
why do you have the `>` in the `EDITOR="cat .config_development.yml >"  `? Isnt that the issue.

**Comment by jonathanhefner** [comment]
We could special case `EDITOR` strings that include `>`, but I think including `>` in `EDITOR` is not widely supported.  For example, it doesn't appear to work with `git`.  We used `>` in that test as a hack to simulate editing and saving a file.

Also, in Rails 7.1, I think the given use case could be accomplished using #45544.  Instead of `EDITOR="cat .config_development.yml >"`, you could rename `.config_development.yml` to `lib/templates/rails/credentials/credentials.yml.tt` and just run `credentials:edit` normally.

But #44910 was backported to `7-0-stable` in 30a287a97ac020fb3556c5f8cc35af549c8921be.  Do we want to revert that?

**Comment by rafaelfranca** [comment]
I believe the windows bug has more precedence over accepting `>` in EDITOR. Let's just consider this new behavior correct.

@m2wasabi you can use the same technic in https://github.com/rails/rails/pull/44910/files#diff-352759d9ffcbbe0ddf7f2917f5b850ae42a158936878ed31e3120d7b355a795aR39 to apply your template.
