### ISSUE TITLE
Eager loading selects freshly dropped column (Mysql2::Error Unknown column)

### ISSUE THREAD

**Issue by marinmeister** [rails/rails#49018]
### Description
From my understanding, eager loading uses the cached list of columns for a model. This cache persists until the next code reload. This can potentially introduce errors with online database migrations (LHM), when dropping columns specifically. You expect the column to be safe for dropping because no code referencing it exists, but turns out it's not true under the hood.

Not sure if this is an actual bug so I'd be happy to hear about options to avoid errors like these, apart from not using eager loading (intended and accidental) or not dropping columns in Production.

The snippet in the screenshot was executed after removing the `renewal_state` column:
<img width="1792" alt="Screenshot 2023-08-23 at 18 37 25" src="https://github.com/rails/rails/assets/117302791/9d84cd74-6ae8-44a0-8f88-e400d3eb8820">

### Steps to reproduce
1. Have Post model
2. Have Comment model as an association on Post
3. Start Rails console
4. Drop any column on Post in a separate tab, simulating an online database migration
5. Try to execute Post.eager_load(:comments).to_a
6. Observe that the resulting SQL includes all the columns, including the one that doesn't exist in the DB anymore and that the query fails

### Expected behavior
The eager loading SQL should not include the column that was just dropped and should not fail.

### Actual behavior
The eager loading SQL includes the column that was just dropped and fails.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.2.2

**Comment by skipkayhil** [comment]
Hey @marinmeister, thanks for opening an issue! This can be solved by setting `ignored_columns` on a Model before dropping the column: https://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-ignored_columns-3D

By setting this value, Active Record will stop including the column in queries so that its safe to drop the column in an online migration. After the migration is run, the column can be removed from `ignored_columns`.

Hope this helps! I'm going to close since this isn't a bug, but feel free to reply if you have more questions

**Comment by marinmeister** [comment]
Hello!
Thanks for another solution, albeit a counter-intuitive one - instead of removing all the code referencing the column to make it safe for dropping you need to add code 😅
