### ISSUE TITLE
ActionView::Template::Error (undefined method `allow_forgery_protection' for #<Info:0x00007f9b403659b0>):

### ISSUE THREAD

**Issue by ali-hassan-mirzaa** [rails/rails#49077]
Completed 500 Internal Server Error in 2386ms (ActiveRecord: 1.8ms)

  
ActionView::Template::Error (undefined method `allow_forgery_protection' for #<Info:0x00007f9b403659b0>):
    4:   <fieldset>
    5:     <legend>Modify user details</legend>
    6: 
    7:     <% form_for(:user, :url => {:action => 'update', :id => @user}) do |form| %>
    8:       <p>
    9:         <label for="user_name">Name:</label>
   10:         <%= form.text_field :name, :size => 40 %>
  
app/views/test_reqs/index.html.erb:7:in `_app_views_test_reqs_index_html_erb__927500844528406705_27580'

Facing this error on rails 5.1.7
Ruby 2.7.0
The issue is only coming at form_for, If I comment form / form_for the issue doesn't came for static content or not in form.

I run the rails 2.3.8 code in new rails 5.1.7 app and getting this ERROR please help me to solve this issue.

Thanks,

**Comment by eileencodes** [comment]
Hi @ali-hassan-mirzaa thanks for opening an issue. The issues tracker is reserved for bugs in the framework. We don't have the bandwidth to provide application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help. 

If you are upgrading straight from 2.3 to 5.1 that is going to be pretty difficult. I recommend going from 2.3->3.2->4.0->4.1->4.2->5.0->5.1 etc. Otherwise you miss the deprecation warnings. Additionally, Rails 5.1 is also no longer supported, we are only supporting bugs in 7.0+, and security issues in 6.1+.
