### ISSUE TITLE
MySQL2::Error caused when upgrading to MySQL8

### ISSUE THREAD

**Issue by eduAntequera** [rails/rails#49087]
https://github.com/rails/rails/blob/0f6a4f5895a4366abe6951ec7fad99cec031cee9/activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb#L143C72-L143C89

It seems that the line referenced above leads to a  `Mysql2::Error: Unknown system variable 'innodb_file_format'` when using MySQL8 and not specifying a value for `ROW_FORMAT`. This is caused due to the deletion of innodb_file_format on MySQL8, compared to MySQL5.7 where it was deprecated, hence triggering the error when querying it for the `Barracuda` value.
Would you agree that this is unexpected behaviour and worth an issue?

**Comment by yahonda** [comment]
Hi,

This statement is not executed if MySQL version is 5.7.9 or higher. So it is not an issue.

https://github.com/rails/rails/blob/0f6a4f5895a4366abe6951ec7fad99cec031cee9/activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb#L140

https://github.com/rails/rails/blob/0f6a4f5895a4366abe6951ec7fad99cec031cee9/activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb#L131-L137

Going forward, it would be appreciated if you create a repro to see if it actually reproduces.

**Comment by karn09** [comment]
I came across this thread as I am running into a similar issue. Running Rails 6.1.7.5, with mysql2 gem 0.5.4. 

```ruby
ActiveRecord::Base.connection.get_database_version
=> #<ActiveRecord::ConnectionAdapters::AbstractAdapter::Version:0x000000015cd95af0 @full_version_string="5.5.30", @version=[5, 5, 30]>
```

While connected to a MySQL db:
```
mysql> SHOW VARIABLES LIKE 'version';
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| version       | 8.0.34 |
+---------------+--------+
1 row in set (0.02 sec)
```

It seems like the result from the method is cached as a result of running the sql from the above example during boot-up. 

I am running ProxySQL v5.5.30 in front of my MySQL 8.0.34 server. It seems rails is fetching the version string from the ProxySQL instance rather than the instance being proxied. 

While I don't expect the version of ProxySQL I am running to have any bearing on the functionality or compatibility with the proxied MySQL DB, I am wondering if this is intentional on the part of Rails. 

If not intentional, could this be a bug in the lifecycle during which the DB version is fetched and cached?

**Comment by zzak** [comment]
Well, you're using a proxy so my guess is there _is_ some impact. But I've never used it.

Since I don't think this is related to the bug reported here, would you be able to open a new issue with a [repro](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) that can demonstrate the bug on at least 7-1-stable?

**Comment by marinmeister** [comment]
Someone had a similar version problems with Azure SQL as well: https://www.reddit.com/r/rails/comments/keam79/rails_mysql_server_on_azure_unknown_system

The monkeypatch there still works.
