### ISSUE TITLE
[BUG] Segmentation fault at 0x0000000000000024 between rails 6.1 and ruby 3.2

### ISSUE THREAD

**Issue by mohamadzoh** [rails/rails#49158]
### Steps to reproduce
you can recreate this error by downloading any 3.2.2 docker image with rails 6.1

step to reproduce
1-bundle exec rails c
2-system("ls") or any system command will throw this issue

### Error
[BUG] Segmentation fault at 0x0000000000000024
and it will create zombie proccess 
ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [x86_64-linux]

using `ls` or any other command  instead of system will run the code but will create zombie proccess 
### System configuration
**Rails version**: 6.1

**Ruby version**:  3.2.2

### Resource 
https://hub.docker.com/_/ruby

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports.

Segmentation fault are usually issues in Ruby itself, or in gems that include C extensions. Rails doesn't include any C extension, so this isn't an issue in Rails.

Thanks!
