### ISSUE TITLE
Drop DHH and 37signals dependency from Rails for CoC violations

### ISSUE THREAD

**Issue by ro31337** [rails/rails#49207]
Issue initially explained here: https://github.com/hotwired/turbo/issues/977 - while the issue is self-explanatory, the reply from DHH was not about addressing the issue or providing a comment that would explain decision in a peaceful manner, but closing and limiting the conversation:

> This is elevating a disagreement of a technical decision to a level of nonsense that has no place here. This project has been founded, funded, and maintained predominantly by the resources and investment of 37signals. We will set the direction as we see fit, accepting input and contributions as they're presented, but with no guarantee of concurrence or merging. All the best finding a project that's more to your liking in direction or leadership or otherwise somewhere else 👋

Given [recent (1)](https://schneems.com/2021/05/12/the-room-where-it-happens-how-rails-gets-made/#the-basecamp-incident) [exodus (2)](https://www.theverge.com/2021/5/3/22418208/basecamp-all-hands-meeting-employee-resignations-buyouts-implosion) from 37signals, multiple toxic comments, it's only a matter of time when the next dose of toxicity percolates into Rails.

Rails is not 37signals. Why it has dependency on hotwired/* in the first place while this library(-ies) "maintained predominantly by the resources and investment of 37signals"? He does whatever he wants with the library and the direction we're all going. Community effort, future of Ruby language and Rails framework are jeopardized by one single person. This should not happen.

**Comment by JohnAnon9771** [comment]
Rails doesn't belong to 37signals; it's an independent project. To manage this project, there's the Rails Core Team. Even though DHH is part of this team, his authority isn't sufficient to override everyone, as that would impact many companies that invest much more in Rails than 37signals. Furthermore, I see no issue with Rails having a dependency on Turbo, even if it's a product of 37signals. Most of the gems used by Rails are maintained and even funded by entirely external organizations. They are in Rails because we believe they are the best default options.

I believe this discussion has gone beyond its limits, and there's no reason to involve Rails in it.

**Comment by ro31337** [comment]
> Most of the gems used by Rails are maintained and even funded by entirely external organizations. 

I bet there is no very vocal and toxic maintainer with history in those multitude gems, who drivers the development of these gem(s), that power community tool to the direction he wants to go, without listening to others. Ignoring opinions, making public comments that hurt community. You know what, there is nothing wrong with the gems itself, but with that guy, who can easily calm down the storm by apologizing, reopening PRs, listening (!) and doing pretty much the same work technically, but showing more respect to small little people out there. But he prefers to stay jerk and demonstrating his powers.

**Comment by JohnAnon9771** [comment]
> > Most of the gems used by Rails are maintained and even funded by entirely external organizations.
> 
> I bet there is no very vocal and toxic maintainer with history in those multitude gems, who drivers the development of these gem(s), that power community tool to the direction he wants to go, without listening to others. Ignoring opinions, making public comments that hurt community. The buzz out there isn't for no reason. Yes, let's ignore these comments one more time, let's ignore opinions, close discussions one more time. And what's next? Waiting for another surprise? If there is no pushback, he'll do whatever he wants to (because we can) or because "the project has been funded". Funded, really? We can do this work for free like it's done now for thousands of open source tools, by community effort only. It shouldn't be justification for CoC violation.
> 
> You know what, there is nothing wrong with the gems itself, but with that guy, who can easily calm down the storm by apologizing, reopening PRs, listening (!) and doing pretty much the same work technically, but showing more respect to small little people out there. But he prefers to stay jerk and demonstrating his powers.

I understand and agree that the recent actions taken by DHH were questionable. However, my point is that this doesn't need to have a negative impact on Rails. Whether we like it or not, Turbo will always be a well-maintained gem funded by 37signals, which still benefits Rails users. Removing this gem just because you don't like how DHH manages Turbo's maintenance is not beneficial to anyone, as it is a very important gem for Rails at the moment. There are other ways to express your dissatisfaction without harming the Rails project.

**Comment by matthewd** [comment]
We don't drop recommendations because of project-internal decisions made by the maintainers of those projects. I already spend enough of my time working to insulate our users from Ruby-level API changes in our hard dependencies.

The linked discussion has no bearing on Rails, but for the record, the Rails core team will _also_ make decisions about our build tooling etc., without community consultation. 

Declaring someone a jerk for not providing a point-for-point refutation of a post that opened with an admission that it was "stirring the pot", _is_ a violation of this project's code of conduct. 

> We can do this work for free like it's done now for thousands of open source tools, by community effort only.

Sorry, I don't spend much time keeping up on the latest in frontend technology; if you've been working on a Turbo-like library that might be interesting for us to consider using instead, I'll be glad to check it out.
