### ISSUE TITLE
ActiveRecord: TypeError when trying to destroy a composite primary key parent with a present `dependent: :restrict_with_error` association

### ISSUE THREAD

**Issue by mateigl** [rails/rails#49408]
### Steps to reproduce

A TypeError rises when destruction a parent object (with a composite primary key!) gets prevented by a `dependent: :restrict_with_error` child association.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "7.1.0.rc1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, primary_key: ["title", "category"], force: true do |t|
    t.string :title
    t.string :category
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :category
  end
end

class Post < ActiveRecord::Base
  self.primary_key = [:title, :category]

  has_many :comments,
           primary_key: :post_id,
           foreign_key: :category,
           dependent: :restrict_with_error
end

class Comment < ActiveRecord::Base
  belongs_to :post,
             primary_key: [:title, :category],
             foreign_key: :category
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    post.destroy!
  end
end

```

### Expected behavior

The following exception should rise instead:
```bash
ActiveRecord::RecordNotDestroyed: Failed to destroy Post with category=
```

### Actual behavior

A TypeError rises because the composite primary key is an Array but gets handled like a method:

```bash
TypeError: ["title", "category"] is not a symbol nor a string
```

### System configuration
**Rails version**: v7.1.0.rc1

**Ruby version**: 3.2.2

**Comment by eileencodes** [comment]
cc/ @nvasilevski do you have bandwidth to look at this?

**Comment by nvasilevski** [comment]
Hey folks, I'm going to have a look but I wanted to say that the associations setup doesn't seem to be correct. 
A few things:

1. `Post.create!` is not a correct way to create a post identified by a composite primary key and none of the CPK columns are auto-populated. We must provide both `category` and `title` on creation. A real world schema would most likely have `NOT NULL` on both of the columns
2. `comments.post_id` will most likely should be called `post_title` but even if we want to call it `post_id` it needs to be a string since we would want to store post's `title` here as there is no integer `id` column on `posts`
3.   `belongs_to :post, primary_key: [:title, :category], foreign_key: :category` association is misconfigured as shape of the PK should always match the FK shape. I was expecting a warning here but we don't seem to print anything so I'll additionally check why is that.
4. `has_many :comments, primary_key: :post_id, foreign_key: :category` setup is also wrong since both `primary_key` and `foreign_key` columns should refer to the same column by meaning but in different tables. `post_id` and `category` have completely different meanings

Here is a bit more cleaned up reproduction script which still reproduces the bug:

```ruby
# typed: true
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "7.1.0.rc1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, primary_key: ["title", "category"], force: true do |t|
    t.string(:title)
    t.string(:category)
  end

  create_table :comments, force: true do |t|
    t.string(:post_id)
    t.string(:category)
  end
end

class Post < ActiveRecord::Base
  has_many :comments,
    primary_key: :title,
    foreign_key: :post_id,
    dependent: :restrict_with_error
end

class Comment < ActiveRecord::Base
  belongs_to :post, query_constraints: [:post_id, :category]
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(title: "foo", category: "bar")
    post.comments << Comment.create!(category: "bar")

    post.destroy!
  end
end
```

In the meantime I'll prepare a fix. Thank you for the report!
