### ISSUE TITLE
Cast "False" to `false` for boolean casting.

### ISSUE THREAD

**Issue by mikestone14** [rails/rails#49697]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activemodel", "~> 7.1.0"
end

require "active_model"
require "minitest/autorun"
require "logger"

class BugTest < Minitest::Test
  def test_boolean_casting
    assert_equal false, ActiveModel::Type::Boolean.new.cast("False")
  end
end
```

### Expected behavior

The test should pass because "False" should be considered falsey. Some other programming languages use capitalized words for booleans so it's reasonable to assume developers might use this syntax when setting string values like environment variables that they want to cast to boolean values in their application code.

### Actual behavior

`ActiveModel::Type::Boolean` treats "False" as a truthy value so the test fails.

**Comment by skipkayhil** [comment]
This type of change has been previously rejected:

- https://github.com/rails/rails/pull/46635#issuecomment-1336192186
- https://github.com/rails/rails/pull/42971#issuecomment-998318908
- https://github.com/rails/rails/pull/40606#issuecomment-725702912
- https://github.com/rails/rails/pull/41485#issuecomment-781035690
- https://github.com/rails/rails/pull/43527#issuecomment-954595781

The recommendation is to create your own `ActiveModel::Type::Value` and use that instead of `Boolean` if you want to add additional strings to cast: https://github.com/rails/rails/pull/46635#issuecomment-1336151591
