### ISSUE TITLE
Blocked host: *.queue.ngrok.io. Not accepting "config.hosts << /[a-z0-9]+\.queue\.ngrok\.io/" in development.rb

### ISSUE THREAD

**Issue by masudhossain** [rails/rails#49785]
### Steps to reproduce

```ruby
# development.rb file has 
  config.hosts << "queue.ngrok.io"
  config.hosts << /[a-z0-9]+\.queue\.ngrok\.io/
```

### Expected behavior
Work with ngrok wildcard domain as expected. Issue started today 2-3 hours ago. Haven't touched the development.rb file in over a year. 

### Actual behavior
![image](https://github.com/rails/rails/assets/16615124/39443564-0c8b-41f1-989a-87557ae9856f)

### System configuration
**Rails version**:
gem 'rails', '~> 6.1', '>= 6.1.7.3'

**Ruby version**:
ruby "3.0.3"

**Comment by Edouard-chin** [comment]
Most likely because Ngrok is now sending a different `X-Forwarded-Host` header (which in your case looks to be "*.queue.ngrok.io").

You can confirm by making a request and look at the ngrok web interface for what headers were sent. You'd need to add that host to the allowed list or tweak the existing regex to accept "*" literally.

**Comment by masudhossain** [comment]
> Most likely because Ngrok is now sending a different `X-Forwarded-Host` header (which in your case looks to be "*.queue.ngrok.io").
> 
> You can confirm by making a request and look at the ngrok web interface for what headers were sent. You'd need to add that host to the allowed list or tweak the existing regex to accept "*" literally.

We tried to make it request everything such as `config.hosts = nil`, but the `request.host_with_port` shows as `*.queue.ngrok.io` and doesn't show the subdomain and instead shows an *. 

So what should I email ngrok support exactly or how can i test this using postman?

**Comment by Edouard-chin** [comment]
Just add `config.hosts << "*.queue.ngrok.io"` in your config

**Comment by masudhossain** [comment]
> Just add `config.hosts << "*.queue.ngrok.io"` in your config

Does not work, same error.

**Comment by Edouard-chin** [comment]
> but the request.host_with_port shows as *.queue.ngrok.io and doesn't show the subdomain and instead shows an *.

I'd advise checking your ngrok config. The only reason I could think of that the host is "*.queue.ngrok.io" literally would be because you are rewriting it (this can be done in ngrok with the `--host-header` flag: `ngrok http 3000 --host-header="*.queue.ngrok.io"`).

Can you go to the ngrok web interface (http://127.0.0.1:4040/inspect/http), and inspect a request to see its headers?

**Comment by Edouard-chin** [comment]
Hopefully you figured it out! I'll close this since this issue since it's not related to Rails
