### ISSUE TITLE
`active_support.cache_format_version` defaults to 6.1 and not the latest version

### ISSUE THREAD

**Issue by ahasunos** [rails/rails#49892]
When using `activesupport` version 7.1.1 gem directly (without rails) in my ruby application, it gives the deprecation warning as:

```
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.
```

The issue gets fixed if I set the version to be greater than 6.1
```
::ActiveSupport::Cache.format_version = 7.0
```
---

Is there any particular reason for having the default `@format_version` as 6.1 

https://github.com/rails/rails/blob/bbc6230ae7a708750a9bc14102bd4627ba85cd1a/activesupport/lib/active_support/cache.rb#L55

and not the latest 7.1 
https://github.com/rails/rails/blob/bbc6230ae7a708750a9bc14102bd4627ba85cd1a/activesupport/lib/active_support/cache.rb#L774

### Steps to reproduce

Use ActiveSupport::Cache in your ruby application

```ruby
::ActiveSupport::Cache.lookup_store(:file_store, Dir.tmpdir)
```

### Expected behavior
 
format_version should default to the latest serializer version i.e. 7.1. 
_Unless this is intentional and kept to 6.1 for some reason. In that case, please feel free to close this issue_

### Actual behavior

format_version defaults to 6.1

### System configuration
**ActiveSupport version**:
7.1.1

**Ruby version**:
3.1.4

**Comment by akhilgkrishnan** [comment]
@ahasunos Thanks for raising this. This issue will resolved in the next release https://github.com/rails/rails/pull/49804

**Comment by skipkayhil** [comment]
Hey @ahasunos, thanks for opening an issue!

Generally, any default configuration values cannot be changed between versions without first being deprecated. This is intentional because apps could be relying on these configurations that are set by default, and changing them without warning could break their application (and the breakage doesn't necessarily show up as failing tests).

For the cache format in particular, this is even more important due to the way the cache works between versions of Rails. The cache formats are all backwards compatible but not forwards compatible. This means that Rails 7.0 can decode cache formats 6.1 and 7.0, but it cannot decode the 7.1 format (since it was first added in 7.1). Therefore the cache version should not be updated to the latest version (by either us or applications) until the application knows for sure that it has no plans to roll back to a previous version of Rails. If an app were to update to 7.1, change their cache format to 7.1 immediately, and then rollback, they will end up with cached data that Rails 7.0 can't decode. Application should instead only upgrade to Rails 7.1, but not change the cache format to 7.1 until they know for sure they will not rollback to Rails 7.0.

So the reason that this deprecation warning is being shown now is because we would like to drop support for the 6.1 version in Rails 7.2. But because of the backwards compatibility concerns, apps themselves need to update the version.

Does this all make sense? Happy to clarify anything if it does not

**Comment by ahasunos** [comment]
@skipkayhil It makes sense! Appreciate you and the entire rails team.
