### ISSUE TITLE
the method gem_group duplicate the information into the Gemfile

### ISSUE THREAD

**Issue by cprodhomme** [rails/rails#50045]
### Steps to reproduce
Use the method [gem_group](https://github.com/rails/rails/blob/89e48cf27eef272c6c2a2e7e0e13f2abe321e957/railties/lib/rails/generators/actions.rb#L111) and write it multiple times.

The method will not check if the Gemfile have already this group

When i want to write a Rails Application Template who add a specific gem for an existing app, i can add 2 times the gem group

```ruby
# your script

gem_group :development, :test do
  gem "rspec-rails"
end

gem_group :development, :test do
  gem "rspec-rails"
end
```

```ruby
# Gemfile

group :development, :test do
  gem "rspec-rails"
end

group :development, :test do
  gem "rspec-rails"
end
```

### Expected behavior
i want to have only one group : 

example of generation :
```ruby
# Gemfile

group :development, :test do
  gem "rspec-rails"
end
```

### Actual behavior

```ruby
# Gemfile

group :development, :test do
  gem "rspec-rails"
end

group :development, :test do
  gem "rspec-rails"
end
```

### System configuration

**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Not only `gem_group`, but other methods (like `gem`) do not do any checks. They simple append the needed contents in the files. I believe, this is by design and you should avoid these duplicates from your app by yourself. 

Furthermore, when such a Gemfile with duplicates is generated, when you try running `bundle install`, you already will get an error.

**Comment by byroot** [comment]
I think this is more akin to a feature request so I'll close.

If you or someone wish to try to implement this a PR is welcome.
