### ISSUE TITLE
Please create an official Ruby on Rails Mastodon account

### ISSUE THREAD

**Issue by mlcohen** [rails/rails#50074]
This is a very humble request for someone on the Ruby on Rails team to please setup an official Ruby on Rails [Mastodon](https://joinmastodon.org/) account. Currently the Ruby on Rails team only has a [Twitter/X account](https://twitter.com/rails). There are many developers that use Ruby on Rails who would prefer to follow updates on Mastodon. This would be very easy to do. Just setup an account on [mastodon.social](https://mastodon.social/) or [fosstodon.org](https://fosstodon.org) (e.g. rubyonrails@mastodon.social, rubyonrails@fosstodon.org), get the account [verified](https://joinmastodon.org/verification), and add a prominent link to the account on the [RoR website](https://rubyonrails.org).

<img width="1259" alt="Screenshot 2023-11-16 at 10 01 44 AM" src="https://github.com/rails/rails/assets/100445/470bff3b-e598-40f4-887b-c5c36e8be1ee">

**Comment by mlcohen** [comment]
Update to this: There is an *unofficial* Ruby on Rails account: https://ruby.social/@rails. It would be better if there was an official account either on ruby.social or one of the other popular Mastodon instances (mastodon.social, fosstodon.org, etc).

**Comment by mguan2020** [comment]
Thank you @mlcohen for bringing this issue to our attention. I have created an official Mastodon account for Ruby on Rails (link: @rubyonrails@mastodon.social). 

Could anyone please guide me regarding how to make changes to the Rails website?

**Comment by mlcohen** [comment]
@mguan2020 I've gone ahead and created a PR for the RoR website https://github.com/rails/website/pull/199

As part of this process, please update the new RoR Mastodon account's profile to include a link to the RoR homepage. As well, best to update account bio to say that it is indeed the official account. Include required avatar and background image. For reference, take a look at the official Python Software Foundation (PSF) Mastodon [account](https://fosstodon.org/@ThePSF) and the official Rust lang Mastodon [account](https://social.rust-lang.org/@rust).

**Comment by AmandaPerino** [comment]
Hello! Amanda from the Rails Foundation here. 👋🏻 Thank you for the suggestion, but the official channels for Rails news are [LinkedIn](https://www.linkedin.com/company/ruby-on-rails-org/), [Twitter/X](https://twitter.com/rails), and the [RSS feed](https://rubyonrails.org/feed.xml). We will not be running accounts or posting on Mastodon, Bluesky, Threads, etc at this time. But thanks for the idea!

**Comment by mzagaja** [comment]
@AmandaPerino just weighing in to say as a Mastodon user I am surprised. Part of the appeal of Mastodon is it runs on Ruby with a strong community of Rubyists at Ruby.social. In fact I learned of Mastodon at RubyConf last year. Ultimately up to the foundation what its strategy and bandwidth is, but think it cannot hurt to meet folks where they are. Just know that even without the presence of Rails, the "water is fine" at Mastodon and the third party apps such as [Ivory](https://tapbots.com/ivory/) are vastly superior to what its available in other ecosystems. Even if you do not want an official presence, I encourage you to give it a try in a personal capacity, and follow the #Ruby hashtag. I think you'll find plenty of content to enjoy. In my experience, the signal-to-noise ratio is vastly superior to X and LinkedIn for Ruby related topics.

**Comment by AmandaPerino** [comment]
Hi @mzagaja thanks for weighing in. I do, in fact, have a personal Mastodon account, and I do check in on #Ruby news regularly. But putting aside my personal thoughts on what I read there 😅, I am happy to explain the decision further. 

For those already in the Ruby and Rails community, there are already so many ways to get Rails news and updates:

- Follow the blog via [RSS feed](https://rubyonrails.org/feed.xml)
- Sign up for the [This Week in Rails newsletter](https://world.hey.com/this.week.in.rails)
- Follow Rails on [LinkedIn](https://www.linkedin.com/company/ruby-on-rails-org/)
- And finally, you can follow Rails on [Twitter/X](https://twitter.com/rails)
- From a content perspective, we will also be posting more to [YouTube](www.youtube.com/@railsofficial) soon.

If someone hates Twitter, there _**are**_ other options. If the options above don’t work, the best of Rails news ends up in a multitude of newsletters and podcasts that you can enjoy as well (and further support the community by subscribing and listening and reading).  

But also: the Rails Foundation was formed in part to improve marketing efforts around Rails in order to attract new people to the community, and I'm not so sure Mastodon is a good platform for reaching _outside_ of one’s own network. There seems to be less potential for folks to serendipitously stumble on to Rails content and become curious about the framework. LinkedIn, YouTube, and Twitter seem to offer that opportunity a little better, so for now, that’s where our efforts will be focused.

Back to my personal opinion: The constant spring boarding to new social media platforms is a modern day madness that I don’t think will ever end. This is in part why I left a career in social media marketing. The best strategy, IMHO, is to stick to a few platforms, and commit to them as well as you can. Hence the compact list of ways to get Rails news above.

Hope that explains the decision a bit more.

**Comment by mzagaja** [comment]
@AmandaPerino Fair enough. I'll continue to follow the RSS feed and YouTube. I too find keeping up with it all a challenge.

**Comment by ThisIsMissEm** [comment]
@AmandaPerino I think something really important to note here is that you'll only grow on a network if you actively use it; There's a large and thriving open-source and developer community on Mastodon, whilst the numbers may not be as large as Twitter/X, the engagement is often much higher (e.g., a post on Mastodon can easily get 250-500 boosts over a few days, far more engagement than is seen on Twitter/X), as [documented](https://notes.ghed.in/posts/2023/mastodon-engagement-twitter/) by [in various](https://martinfowler.com/articles/exploring-mastodon.html) places. Not only that, but engagement tends to be positive rather than negative in my experience due to the higher quality of overall network moderation & community standards.

One thing that you could do is use [Buffer](https://buffer.com/) to maintain both Twitter/X and Mastodon, they also support your LinkedIn as well, which would likely simplify a fair bit of your social media operations. (It'd maybe be a cost of $18/month for the Rails accounts), there's also [Zoho Social](https://www.zoho.com/social/pricing.html) in this same space.

Another "nice" thing about setting up an official Mastodon account would be to give a nod of appreciation to the Mastodon project for using Ruby on Rails, and being a starting point for people to contribute & maybe even learn Rails by having hands on experience with a complex rails codebase — there's not that many of those that are fully open source.


_(Another thing to keep in mind is that just today IBM has pulled all ads from X given that their [ads were showing up alongside antisemitic and pro-nazi posts](https://www.ft.com/content/647b4c4d-f4d5-46cd-bc26-8c943b6995e7), so being on X could actually be doing reputational damage to Rails even, though this is debatable. Although, X says this should not happen, it happens repeatedly time and again)_

**Comment by mlcohen** [comment]
Hi @AmandaPerino -- I very much appreciate your thoughtful response and can certainly empathize with your sentiment about the dizzying number of social media options now available. 

> the Rails Foundation was formed in part to improve marketing efforts around Rails in order to attract new people to the community, and I'm not so sure Mastodon is a good platform for reaching outside of one’s own network

For those who are new to Rails or simply curious about Rails, they'd most likely go to the Rails website as part of their discovery process. It's there where people would find links to the official communication channels. On the Rails website, there are prominent links to the Twitter/X account and Rails blog. The Rails community could thrive on Mastodon (and Bluesky, Threads) with knowledge that those spaces exist and are viable options.

Not to dwell on Twitter/X, but focusing on microblogging social media spaces, Mastodon, Bluesky and Threads are viable alternatives for those who prefer that format of communication. And with the way things are going on Twitter these days, having choice in microblogging services is, at least to me, most welcome.

In any case, it's good to know the Ruby Foundation's official position on the matter. I hope at some point the Foundation reconsiders and sees Mastodon (and others) and worth investing in.

**Comment by AmandaPerino** [comment]
@ThisIsMissEm & @mlcohen You both bring up valid points, the strongest for me being that Mastodon is built on Rails. I actually didn't know that! (Matthew mentioned Ruby above, but not Rails specifically.) That's really cool, and that does make me want to check it out more. For now the Rails Foundation will stick to these platforms I mentioned above, but we'll keep the option open for the future. You never know! In the meantime, you'll probably see me come out of lurk-mode more while I poke around. Thanks a lot for your messages, I appreciate it! Have a great weekend.

**Comment by renchap** [comment]
Chiming in here as a Mastodon core team member :)

With more than 1.6 million monthly active users, Mastodon may be one of the biggest open-source software built on Rails, and we are proud of it! We will be very happy to have an official Rails account on the network.

Another thing to note is that Mastodon is part of the Fediverse. Threads will join the Fediverse some time next year, and people on Threads will be able to follow and interact with the official Rails Mastodon account without the need to manage yet another account. And we hope more social networks will join the Fediverse, as one of our goals is to make those networks interoperable and avoid the need to have accounts everywhere.

**Comment by AmandaPerino** [comment]
@renchap That's very cool on both counts. I'll keep an eye on it, and like I said above, poke around a bit more. Thanks for weighing in!

**Comment by lazyatom** [comment]
(A year later...)

I'm the instance admin of https://ruby.social, and if/when Rails would like it, the [@rails username](https://ruby.social/@rails) is available -- when the unofficial RSS-posting bot was created, the creator and I had a very clear understanding that the handle would be made available for official use if/when required. Just let me know!
