### ISSUE TITLE
`credentials:edit` with no explicit environment set now defaults to `development`

### ISSUE THREAD

**Issue by rspeicher** [rails/rails#50080]
### Steps to reproduce

Prior to Rails 7.1, if I were to run `rails credentials:edit` with no environment argument, it would edit the "global" `config/credentials.yml.enc` file.

I had a case where I wanted to override some of those credentials _only in the `development` environment_, so I would run `rails credentials:edit -e development`, and that all worked fine.

Now on Rails 7.1.2, omitting the environment argument seems to use the environment of whatever's running the command, which defaults to `development`, and now edits the environment-specific configuration rather than the "global" one.

From what I can tell, there is no longer a way to edit the non-specific environment credentials.

Now, the argument could be made that I'm doing this backwards and that local environments should have sane default values and only `production` should override them, and while I don't disagree, this was already in place and working prior to 7.1.

### Expected behavior

`credentials:edit` with no environment argument should edit the `config/credentials.yml.enc` file, as was the previous behavior.

### Actual behavior

`credentials:edit` with no environment argument edits the `config/credentials/development.yml.enc` file.

### System configuration

**Rails version**: `7.1.2`

**Ruby version**: `ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]`

**Comment by jonathanhefner** [comment]
This is due to #47107.  __If__ you have a `config/credentials/development.yml.enc` file and are in the development environment, then that is what `credentials:edit` will edit.

It sounds like you have both a `config/credentials/development.yml.enc` file for development and a `config/credentials.yml.enc` for other environments (instead of e.g. `config/credentials/production.yml.enc`).  In that case, you can specify the appropriate `RAILS_ENV` which `credentials:edit` will now respect:

```console
$ RAILS_ENV=production bin/rails credentials:edit
```

(The difference between using `RAILS_ENV` and the `-e` option is that `-e` will create the file in `config/credentials/` if it does not exist, whereas `RAILS_ENV` will simply choose the appropriate already-existing file.)

**Comment by rspeicher** [comment]
Was just going to say this seems intentionally introduced by https://github.com/rails/rails/pull/40778.

Thank you @jonathanhefner, that's very helpful. 👍🏻

**Comment by Xeitor** [comment]
hi,  so there is no built in way to have default credentials in the `config/credentials.yml.enc` file?

**Comment by kcdragon** [comment]
> hi, so there is no built in way to have default credentials in the `config/credentials.yml.enc` file?

Try `RAILS_ENV=notarealenv bin/rails credentials:edit`. If you use a real RAILS_ENV it will open that environments credentials but using one that doesn't exist seems to accomplish what you want. It's not elegant and might not even be intended behavior but I don't know of another way.
