### ISSUE TITLE
`counter_cache` not decrementing with has_many through association

### ISSUE THREAD

**Issue by zbokostya** [rails/rails#50139]
### Steps to reproduce
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '7.1.1'
  # gem 'activerecord', '6.1.7.6'
  # gem 'activerecord', '5.2.8.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true do |t|
  end

  create_table :parts, force: true do |t|
    t.integer :book_id
    t.integer :series_id
  end

  create_table :series, force: true do |t|
    t.integer :books_count, default: 0
  end
end

class Book < ActiveRecord::Base
  has_many :parts
  has_many :series, through: :parts
end

class Part < ActiveRecord::Base
  belongs_to :book
  belongs_to :series, counter_cache: :books_count
end

class Series < ActiveRecord::Base
  has_many :parts
  has_many :books, through: :parts
end

class BugTest < Minitest::Test

  def test_counter_cache_after_assign_and_clear
    book = Book.create!
    series = Series.create!

    series.books = [book]
    series.books = []
    assert_equal 0, series.books_count
  end

  def test_counter_cache_after_assign_and_clear_with_reload
    book = Book.create!
    series = Series.create!

    series.books = [book]
    series.books = []
    assert_equal 0, series.reload.books_count
  end
end
```

### Expected behavior
`counter_cache` should become to eq 0 after assign has_many field with empty array

### Actual behavior
`counter_cache` not decrementing

### System configuration
**Rails version**:
7.1.1, 6.1.7.6, 5.2.8.1
**Ruby version**:
3.2.2, 2.7.5

**Comment by nvasilevski** [comment]
It sounds very similar to an old https://github.com/rails/rails/issues/7630

Where the fix was https://github.com/rails/rails/commit/a765c8426fe39c73cf9f3ad7f8edcf588c01a11d and it is still present in almost the same shape

https://github.com/rails/rails/blob/04f29cb134cfe367d3b6c555c1203ece9b599e5e/activerecord/lib/active_record/associations/has_many_through_association.rb#L157-L160

I'll try to dig further a bit later unless someone finds the problem quicker

**Comment by nvasilevski** [comment]
@zbokostya It looks like the setup is missing `Series.has_many :parts, counter_cache: :books_count` definition to work. 

I can't immediately tell if that's intentional or not. The setup doesn't seem to be very friendly and I don't think we have any docs explaining the setup. Perhaps we could at least improve documentation? 

Also just to make sure it doesn't break anything else I added an assertion like:
```ruby
    series.books = [book]
    assert_equal 1, series.books_count
```

To explicitly make sure that first it increments to `1` and then decrements to `0`

**Comment by zbokostya** [comment]
> It looks like the setup is missing `Series.has_many :parts, counter_cache: :books_count` definition to work.

`source_reflection.options` doesn't have `:counter_cache` without adding this definition. So the counter is not decremented because it returns `nil`. Should it have or am I wrong?

**Comment by nvasilevski** [comment]
>Should it have or I am wrong?

Well I mean it should in order to work against released Rails versions but I'm not sure it's the best API or even was intentionally designed like this. It feels excessive to have two repeating `counter_cache: :books_count` definitions for the same `has many through` association. So even if it's not a pure bug because there is a way to make it work perhaps there is an opportunity to improve the API or at least make sure docs are clear that both `belongs_to` and `has_many` need `counter_cache:` option to be set
