### ISSUE TITLE
ActiveStorage::VariantWithRecord should keep the variant key to store the file

### ISSUE THREAD

**Issue by brunto** [rails/rails#50176]
### Steps to reproduce
With `config.active_storage.track_variants = false`
```ruby
MyModel.last.photo.variant(resize_to_fit: [200, 100]).key
=> "variants/xxxxxxx"
```

With `config.active_storage.track_variants = true`
```ruby
MyModel.last.photo.variant(resize_to_fit: [200, 100]).key
=> nil
```

### Expected behavior
With `config.active_storage.track_variants = true` the variant should use [the key method](https://github.com/rails/rails/blob/354d68e8a63b21e47a529105a508411bfe8be869/activestorage/app/models/active_storage/variant.rb#L73) in order to store the variants in the folder "variants".

### Actual behavior
It stored the variation_digest in the root "folder" instead of the "variants" folder.

### System configuration
**Rails version**: 7.1

**Ruby version**: 3.2.2

**Comment by alexandreruban** [comment]
Hello! 

I'm not sure I understand your problem. When we write the following code: 

```rb
user.avatar.variant(resize_to_limit: [100, 100])
```

We end up calling the `#variant` method defined in `ActiveStorage::Blob::Representable`:

```rb
def variant(transformations)
  if variable?
    variant_class.new(self, ActiveStorage::Variation.xxx)
  else
    raise ActiveStorage::InvariableError
  end
end
```

The `variant_class` here is determined by the configuration: 

```rb
def variant_class
  ActiveStorage.track_variants ? ActiveStorage::VariantWithRecord : ActiveStorage::Variant
end
```

When we `track_variants`, we use the `ActiveStorage::VariantWithRecord` class. In that case, when we `process` the image, we download the original image, transform it according to the variations and create a new `VariantRecord` to which we attach the transformed image:

```rb
# activestorage/app/models/active_storage/blob/representable.rb
has_many :variant_records

# activestorage/app/models/active_storage/variant_record.rb
belongs_to :blob
has_one_attached :image

# activestorage/app/models/active_storage/variant_with_record.rb
# When processing the variant: 
def process
  transform_blob { |image| create_or_find_record(image: image) }
end

def transform_blob
  # Transforms the image
end

def create_or_find_record(image:)
  # Create a variant record and attach the transformed image to it
end
```

Note that before the variant is `process`, no image blob is created and that's why you have: 

```rb
user.avatar.variant(resize_to_limit: [100, 100]).key
# => nil
``` 

However, if you `process` the variant, you will get a key (the key of the new blob): 

```rb
user.avatar.variant(resize_to_limit: [100, 100]).processed.key
# => "mtbjgx3jz5zbt65ij08yx9hjcdew"
```

When you don't track the variants, things are a little bit different. We use the we use the `ActiveStorage::Variant` class to process the variant. When processing the variant, the code looks like this: 

```rb
# activestorage/app/models/active_storage/variant.rb

def process
  blob.open do |input|
    variation.transform(input) do |output|
      service.upload(key, output, content_type: content_type)
    end
  end
end
```

In that case, we upload the transformed file to the service without creating a record in our database. In order to be able to the transformed image later on the service, we need to derive a key from the original blob and that's why we have a key method in that case: 

```rb
def key
  "variants/#{blob.key}/#{OpenSSL::Digest::SHA256.hexdigest(variation.key)}"
end
```

I hope it helps. Let me know it it's not clear.

Note that I'm not a frequent contributor so someone might have something to add here!

**Comment by brunto** [comment]
Thanks for your feedback, I'll detail my request a little better.

For example, I take the following configuration:

`config.active_storage.track_variants = false`

and generate a variant :

`my_model.photo.variant(:thumb).url`

My variant is created in the `variant/` "folder" of my S3 bucket.
![Screenshot 2023-12-14 at 18 46 27](https://github.com/rails/rails/assets/1003351/f782a49e-cba1-413e-bdab-0ef718de5a32)


If I now set the following configuration:

`config.active_storage.track_variants = true`

and generate a variant :

`my_model.photo.variant(:thumb).url`

then the variant will be created directly at the bucket root instead of in the `variant/` "folder".

![Screenshot 2023-12-14 at 18 43 02](https://github.com/rails/rails/assets/1003351/5f66dc70-1082-4130-88d0-f5d8121099b4)

**Comment by brunto** [comment]
I tried to add some tests and find a way to fix that. It works, but I broke some other tests.
Here is an example: https://github.com/brunto/rails/commit/a610536e521917041194bde308e0510ba1054606

**Comment by dthanhtuan** [comment]
Sorry for bothering you :pray: , Do you know how to change the variants uploading path ?

**Comment by brunto** [comment]
@dthanhtuan You must overwrite the key method https://github.com/rails/rails/blob/main/activestorage/app/models/active_storage/variant.rb#L73

**Comment by dthanhtuan** [comment]
> @dthanhtuan You must overwrite the key method https://github.com/rails/rails/blob/main/activestorage/app/models/active_storage/variant.rb#L73

This only works if `config.active_storage.track_variants` is set to `false` , Am I correct ?

**Comment by brunto** [comment]
Exactly

**Comment by jrfurini** [comment]
@alexandreruban  your explanation regarding the Variant and VariantRecord classes was exceptionally clear. However, there's an issue with the way the VariantRecord class operates. Unlike the Variant class, which allows control over the location where the variant file is created, the VariantRecord class automatically generates the variant file at the root of the Bucket in the S3 service.

Notably, the performance with VariantRecord is superior to that with Variant. It would be beneficial if we could either specify the creation location for the variant or, by default, have the variant created in the same location as the original file (as determined by its key).

Please, what do you think about this suggestion?
