### ISSUE TITLE
Enabling the autosave option disables uniqueness validation

### ISSUE THREAD

**Issue by akicho8** [rails/rails#50173]
Even if you have validation in place to prevent the creation of articles with the same content, the validation becomes invalid if the auto-save option is enabled.

### Steps to reproduce

```ruby
require "active_record"

RUBY_VERSION                    # => "3.2.2"
ActiveRecord::VERSION::STRING   # => "7.1.2"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Migration.verbose = false
ActiveRecord::Schema.define do
  create_table :users do |t|
  end
  create_table :articles do |t|
    t.belongs_to :user
    t.string :name
  end
end

class User < ActiveRecord::Base
  has_many :articles, autosave: true
end

class Article < ActiveRecord::Base
  belongs_to :user
  validates :name, uniqueness: true
end

ActiveRecord::Base.logger = ActiveSupport::Logger.new(STDOUT)
ActiveSupport::LogSubscriber.colorize_logging = false

user = User.create! do |e|
  e.articles.build(name: "a")
  e.articles.build(name: "a")
end
user                            # => #<User id: 1>
user.articles.count             # => 2
# >>   TRANSACTION (0.0ms)  begin transaction
# >>   Article Exists? (0.1ms)  SELECT 1 AS one FROM "articles" WHERE "articles"."name" = ? LIMIT ?  [["name", "a"], ["LIMIT", 1]]
# >>   Article Exists? (0.0ms)  SELECT 1 AS one FROM "articles" WHERE "articles"."name" = ? LIMIT ?  [["name", "a"], ["LIMIT", 1]]
# >>   User Create (0.0ms)  INSERT INTO "users" DEFAULT VALUES RETURNING "id"
# >>   Article Create (0.0ms)  INSERT INTO "articles" ("user_id", "name") VALUES (?, ?) RETURNING "id"  [["user_id", 1], ["name", "a"]]
# >>   Article Create (0.0ms)  INSERT INTO "articles" ("user_id", "name") VALUES (?, ?) RETURNING "id"  [["user_id", 1], ["name", "a"]]
# >>   TRANSACTION (0.0ms)  commit transaction
# >>   Article Count (0.0ms)  SELECT COUNT(*) FROM "articles" WHERE "articles"."user_id" = ?  [["user_id", 1]]
```

### Expected behavior

Because you are trying to create an Article record with the same name, the uniqueness validation will fail and the creation of the User and Article records will fail.

### Actual behavior

A User record is created despite having a unique validation check, leading to an inconsistent state.

### System configuration

```
RUBY_VERSION                    # => "3.2.2"
ActiveRecord::VERSION::STRING   # => "7.1.2"
```

**Comment by fatkodima** [comment]
Actually validations are ran, as you can see from the log. They are successful, because when each article is validated, other is not stored yet. I do not know if this problem can be solved, seems like a limitation of autosave association. But you definitely need to have a unique index for this.

**Comment by akicho8** [comment]
@fatkodima Thank you for your comment.
It seems that the order of operations, in which child record instances are created in bulk and then processed upon saving the parent, is different from what I had anticipated. Thus, for safety, I will explicitly write it as follows for the time being. (Furthermore, I will also add a unique index to the DB in reality.)

```ruby
begin
  ActiveRecord::Base.transaction do
    user = User.create!
    user.articles.create!(name: "a")
    user.articles.create!(name: "a")
  end
rescue => error
  error # => #<ActiveRecord::RecordInvalid: Validation failed: Name has already been taken>
end
# >>   TRANSACTION (0.0ms)  begin transaction
# >>   User Create (0.0ms)  INSERT INTO "users" DEFAULT VALUES RETURNING "id"
# >>   Article Exists? (0.0ms)  SELECT 1 AS one FROM "articles" WHERE "articles"."name" = ? LIMIT ?  [["name", "a"], ["LIMIT", 1]]
# >>   Article Create (0.0ms)  INSERT INTO "articles" ("user_id", "name") VALUES (?, ?) RETURNING "id"  [["user_id", 1], ["name", "a"]]
# >>   Article Exists? (0.0ms)  SELECT 1 AS one FROM "articles" WHERE "articles"."name" = ? LIMIT ?  [["name", "a"], ["LIMIT", 1]]
# >>   TRANSACTION (0.0ms)  rollback transaction
```

However, writing it like above, it becomes unclear why the autosave function was enabled. It might be better to simply disable the autosave option.

**Comment by febeling** [comment]
I can see why one would expect the uniqueness validation to catch that duplication, but it's unambiguous from the documentation that this wouldn't prevent it. The validations guide [states](https://guides.rubyonrails.org/active_record_validations.html#uniqueness) that uniqueness is established by an SQL query, and the build collection objects aren't persisted at that point. It has a explicit call-out about the possibility of still having conflicts. It goes on to suggest using a unique index to ensure uniqueness, even if it only mentions multiple connections, not the same collection as the cause for conflict.

Not a bug, but documented behavior.

**Comment by akicho8** [comment]
@febeling Thank you for your comment.
You say that this is documented and natural behavior, but I don't think anyone other than a committer who knows the inner workings of the system would be able to read from the linked documentation that the uniqueness validation is only disabled when the `autosave: true` option is specified.

**Comment by febeling** [comment]
@akicho8 It's not quite accurate to say the validation is disabled by autosave. It's more a situation where you lean on some abstractions more than they can carry. They don't offer the guarantee that you expect. Autosave means one call saves several objects, not transactional guarantees.

What your example does is build a number of objects in memory, configure that save will be a single call, and that's it. They all get validated according to their respective validation, and then saved if valid. The details are up to the specific validations. Uniqueness, which you have picked, is an expensive operation, because it makes logical constraints on all objects, persisted and unpersisted. It's a bit of a headache to implement in any large system consistently, to the point where some people try to avoid it completely by using UUID just for that.

AR, as a pragmatic and expressive package, offers a solution which makes a trade-off, by looking once at the database. That comes with documented caveats, like the fact the once you write the db might not be in the same state as it was when your validation read it.

All that is in line with the philosophical underpinnings of Rails and AR (see [Provide Sharp Knives](https://www.freelancermap.de/projekt/ruby-developer-3-days-per-week) in the Rails Doctrine). It's very expressive, and offers lots of conveniences, but you need to know what you're doing. 

In your presented case there is an easy solution available, which you already presented in your comment where you save/create objects sequentially (inside a transaction). Granted, it would be nice to handle validation errors instead of a rollback, but that difficulty is largely due to the tricky nature of the uniqueness property in concurrent systems.
