### ISSUE TITLE
Migrating from Rails 7.0.8 to Rails 7.1.2 without any config breaks encryption

### ISSUE THREAD

**Issue by zaratan** [rails/rails#50212]
#### Setting up the App

```sh
rails _7.0.8_ new test_rails_enc
cd test_rails_enc
bin/rails db:encryption:init
rails credentials:edit # Copying the keys
rails g model user email:string name:string
```

```ruby
class User < ApplicationRecord
  encrypts :email, deterministic: true
  encrypts :name
end
```

```ruby
User.create(name: "Zaratan", email: "zaratan@hey.com")
```

#### Migrating to Rails 7.1
In the Gemfile
```ruby
gem "rails", "~> 7.1.2"
```

```sh
rails app:update # Answering Yes to every question
rails db:migrate
```

### Testing
Email:
```ruby
User.pluck(:email).first
```
```
  User Pluck (0.3ms)  SELECT "users"."email" FROM "users"
/Users/zaratan/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/encryption/encryptor.rb:58:in `rescue in decrypt': ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption)
/Users/zaratan/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/encryption/cipher/aes256_gcm.rb:79:in `rescue in decrypt': ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption)
/Users/zaratan/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/encryption/cipher/aes256_gcm.rb:75:in `final': OpenSSL::Cipher::CipherError
```
Name:
```ruby
User.pluck(:name).first
```
```
  User Pluck (0.1ms)  SELECT "users"."name" FROM "users"
=> "igor"
```

#### If Adding : 
```
config.active_record.encryption.support_sha1_for_non_deterministic_encryption = true
```

=> Same behaviour

#### If Changing to Rails 7.1 defaults
```
    config.load_defaults 7.1
```

Reading the name will trigger a cipher error and the email will be read correctly

#### If setting config.active_record.encryption.hash_digest_class to `OpenSSL::Digest::SHA1`

```
config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA1
```

=> Email: Cipher Error, Name: Ok

#### If setting config.active_record.encryption.hash_digest_class to `OpenSSL::Digest::SHA256`

=> Email: Ok, Name: Cipher Error

### Expected behavior
If a user didn't configure anything the upgrade path should exist or be documented in a way. I think I tried every configuration option documented and couldn't make it work.

Production is still on 7.0.8 so I didn't get any terrible damage but what would be an upgrade path for me (and for others)

### Actual behavior
`OpenSSL::Cipher::CipherError`

### System configuration
**Rails version**: 7.0.8 => 7.1.2

**Ruby version**: 3.2.2

**Comment by trevorturk** [comment]
I'm running into a similar issue myself, so I stepped through the exact process as described by @zaratan to try to debug. However, I was able to find a working config as follows:

```ruby
config.load_defaults 7.1
config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256
config.active_record.encryption.support_sha1_for_non_deterministic_encryption = true
```

This is with rails `7.1.3` now, though, so perhaps a fix was added in the meantime? If someone else would like to try to confirm the issue still exists, please do, but I think this might be safe to close.

**Comment by zaratan** [comment]
@trevorturk this issue can be closed indeed. The issue I was facing was caused by another gem which was causing loading of models in an `after_initialize` which ran **before** the one from `encryption.support_sha1_for_non_deterministic_encryption = true` rendering it useless.

If anyone interested and falling in the same issue (caused by [Forest Admin](https://www.forestadmin.com) on my side), here was my fix : 

```ruby
# HACK: This is a monkey patch because Forest eager load all the models in an after_initialize.
#       This is a problem because during the Rails 7.0.8 => 7.1.2 upgrade,
#       in order for the encryption to continue working we need to use
#       Rails.application.config.active_record.encryption.support_sha1_for_non_deterministic_encryption = true
#       which configure the extra sha1 encryption in an after_initialize that runs AFTER forest's.
#       This way it's too late, models are already loaded and the fallback encryption is not working.
#
#       This hack should be removed after we forcibly re-encript all the data in the database.

# The hack forcing encryption config to load
module HackForestAfterInitialize
  def eager_load_active_record_descendants(app)
    ActiveRecord::Encryption.configure(
      primary_key: app.credentials.dig(:active_record_encryption, :primary_key),
      deterministic_key:
        app.credentials.dig(:active_record_encryption, :deterministic_key),
      key_derivation_salt:
        app.credentials.dig(:active_record_encryption, :key_derivation_salt),
      **config.active_record.encryption,
    )

    super
  end
end

# Inserting it at the right place
module ForestLiana
  class Engine < ::Rails::Engine
    prepend HackForestAfterInitialize
  end
end
```

**Comment by trevorturk** [comment]
Ah, thank you for the additional info! I'm still working through a related issue on my end. I'll report back if/when I figure out what's gone wrong, but good to know about the hack needed here. 

I wonder if it's worth considering raising an error if the initialization process attempts to set the encryption config more than once, since this silent config failure must have been really tricky to track down?

**Comment by zaratan** [comment]
A better option would be to run the `encryption.support_sha1_for_non_deterministic_encryption` `after_initialize` before any other but I have any idea it that would be possible. Your solution would have invalidated my trick 😅

And yeah… That was "fun" to track down (this is sarcasm 😅).

**Comment by trevorturk** [comment]
Potentially related possible fix? https://github.com/rails/rails/pull/50606

**Comment by trevorturk** [comment]
I'm wondering if we should reopen this issue. 

My thinking is that at a minimum we should have some clear instructions in the upgrade guide to suggest a new recommended config. In my case, had I not thought to check against my production database first, I would have run into decryption errors unexpectedly, even though I've been using the default config (not having any explicit config).

If I'm understanding things correctly, if upgrading from 7.0.8 to 7.1.3 with no config, you'd need to add the following:

```
config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256
config.active_record.encryption.support_sha1_for_non_deterministic_encryption = true
```

...with the caveat that you won't be able to roll back as per https://github.com/rails/rails/issues/50226

...or else you won't be able to read preexisting encrypted data, and I think that should be made more clear somehow.

**Comment by unRARed** [comment]
We upgraded to Rails 7, but we didn't notice the SHA change for a while. In particular, this seems to have broken all ActiveStorage "permanent URLs" prior to the cutover. Our CMS uses these URLs heavily. We tried further upgrading to Rails 7.1, and from what I've gathered, the following is the proper config to handle both encryption algorithms:

```ruby
class Application < Rails::Application
  ...
  config.load_defaults(7.1)

  config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256
  config.active_record.encryption.
    support_sha1_for_non_deterministic_encryption = true
  ...
```

However, the prior URLs are still broken. Does Active Storage need to be handled differently? [This was the article that led us here](https://systemweakness.com/unravelling-signed-url-changes-in-rails-7-e9156da43022), but I can't tell if this is supposed to be solved with the above fix or not. Is there a config we're missing for Active Storage, or do we simply need to bite the bullet and either do some regex work or go through them 1 by 1?

**Comment by skipkayhil** [comment]
> Does Active Storage need to be handled differently?

Yes, as mentioned in the article you linked the important configuration is `config.active_support.hash_digest_class`

**Comment by trevorturk** [comment]
Take care to review this as well: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#active-record-encryption-algorithm-changes

You'll need to track which versions you deployed to check, but it could be that you need to follow @skipkayhil's suggestion here, and perhaps configure `hash_digest_class` to be `OpenSSL::Digest::SHA1`. 

Note that `support_sha1_for_non_deterministic_encryption` is only available in 7.1 and above.

**Comment by unRARed** [comment]
> Note that support_sha1_for_non_deterministic_encryption is only available in 7.1 and above.

Our initial upgrade to 7.1 was still loading the 7.0 defaults and that's when we noticed this issue as most of our embedded active storage image references in blog posts were suddenly broken. We've since bumped to Rails 7.1 enabling the new defaults per the `config.load_defaults(7.1)` but the issue persists.

> Take care to review this as well: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#active-record-encryption-algorithm-changes

It doesn't explicitly mention how it affects permanent URLs in Active Storage and to my knowledge, we didn't have `config.active_support.key_generator_hash_digest_class` explicitly set.

>  it could be that you need to follow @skipkayhil's suggestion here, and perhaps configure hash_digest_class to be OpenSSL::Digest::SHA1.

Assuming this config does affect Active Storage URLS, wouldn't everything following our move to Rails 7, which should be `OpenSSL::Digest::SHA1`, break if we go back to the prior default? And this would be worse as it's the newer / more current URLs. Seems like `support_sha1_for_non_deterministic_encryption` is supposed to provide the fallback for the prior SHA1 default.

I'm worried about making the situation worse at this point.

**Comment by trevorturk** [comment]
Yeah, I'm sorry, but I'm not sure how this all interacts with Active Storage. You might want to go spelunking through the relevant commits (via the Rails Guides and referenced PRs and/or some git blaming) to see what you can find. Perhaps the PR introducing `support_sha1_for_non_deterministic_encryption` would be a good place to look, to see if you can trace it back to possible interactions (or lack thereof) with Active Storage. Chattering on those issues could get better visibility from people in the know and/or the Rails Discord is a good place to ping as well. 

Apologies I don't know more about this area -- I wish I could be more helpful!

**Comment by skipkayhil** [comment]
It sounds like two completely different things are being conflated here. Configuring Active Record Encryption should have no effect on how Active Storage encrypts URLs.

> Our initial upgrade to 7.1 was still loading the 7.0 defaults
> It doesn't explicitly mention how it affects permanent URLs in Active Storage and to my knowledge, we didn't have config.active_support.key_generator_hash_digest_class explicitly set.

The default value for `config.active_support.key_generator_hash_digest_class` and `config.active_support.hash_digest_class` both changed with `load_defaults 7.0`: https://guides.rubyonrails.org/configuring.html#default-values-for-target-version-7-0

> Assuming this config does affect Active Storage URLS, wouldn't everything following our move to Rails 7, which should be OpenSSL::Digest::SHA256, break if we go back to the prior default? And this would be worse as it's the newer / more current URLs. Seems like support_sha1_for_non_deterministic_encryption is supposed to provide the fallback for the prior SHA1 default.

Yes, SHA256 has been used since the config changed so you likely have both now. You should use the rotator mentioned in the article you linked to read both versions. 

(`support_sha1_for_non_deterministic_encryption` has nothing to do with Active Storage and so will not be helpful)

**Comment by unRARed** [comment]
> Configuring Active Record Encryption should have no effect on how Active Storage encrypts URLs.

Ok, thank you! We'll try out the rotator code. Seems like this should be burning more users, but perhaps they simply don't know they've been affected yet? We'll report back.

**Comment by unRARed** [comment]
Appreciate all the help everyone! I can confirm following our deploy this morning that the rotator initializer resolves both the prior and new permanent URLs ActiveStorage generates with `Rails.application.routes.url_helpers.url_for(active_storage_attachment_instance)`.

The referenced blog article used an image for describing the code snippet, so here's the our `./config/initializers/active_storage_key_rotation.rb` (if it helps anyone):

```ruby
# frozen_string_literal: true

# config/initializers/active_storage_key_rotation.rb
#
# Per https://systemweakness.com/\
#   unravelling-signed-url-changes-in-rails-7-e9156da43022#9599
Rails.application.config.after_initialize do |app|
  verifier = "ActiveStorage"

  sha1_key_generator = ActiveSupport::KeyGenerator.new(
    app.secret_key_base,
    iterations: 1000,
    hash_digest_class: OpenSSL::Digest::SHA1,
  )
  app.message_verifier(verifier).
    rotate(sha1_key_generator.generate_key(verifier))
end
```

This issue seems to have been documented better in the [hotwired/turbo-rails upgrading docs](https://github.com/hotwired/turbo-rails/blob/main/UPGRADING.md#key-digest-changes-in-111) than it was in the general rails 7 upgrading docs. In our case, the URLs were originally generated by the gem we're using for our CMS [occams](https://github.com/CloudSecurityAllianceCI/occams)  (which more or less replaced the abandoned `comfortable-mexican-sofa` gem) and uses `redactor` as the front-end rich text conversion. I have to imagine there are other combinations of CMS tooling / gems, or anything that uses the value that `url_for(active_storage_attachment_instance)` returns, where this is going to burn folks.

**Comment by trevorturk** [comment]
I'm so happy you found the issue and thanks for the detail here! You might consider a PR for the Rails Guides to explain the issue a bit more to help others avoid a similar fate? If you work that up please do let us know!
