### ISSUE TITLE
Cannot define rails tasks that take command line arguments since Rails 7.1 Rails::Command::UnrecognizedCommandError

### ISSUE THREAD

**Issue by mildred** [rails/rails#50220]
https://github.com/rails/rails/blob/6b93fff8af32ef5e91f4ec3cfffb081d0553faf0/railties/lib/rails/commands/rake/rake_command.rb#L21-L24

In rails 7.0 it was possible to define a rake task invoked using rails that would take command-line arguments. You just had to read the arguments in `ARGV` and to call `exit` in order to prevent rails from looking up the arguments as if they were rake tasks.

In rails 7.1, before even starting the tasks, rails is looking up all command-line arguments to ensure they are valid rake tasks, and arguments are not, and it produces a Rails::Command::UnrecognizedCommandError

Example task that worked in rails 7.0 and no longer works:

```rb
namespace :import do
  task from_v5: :environment do
    if ARGV.length < 1
      warn 'Usage: rails import:from_v5 FILENAME'
      exit 1
    end
    puts "importing #{ARGV[0]}..."
    exit 0
  end
end
```

**Comment by mildred** [comment]
Workaround possible by monkey-patcking the `bin/rails` script:

```
```

**Comment by jonathanhefner** [comment]
Hmm, that seems to be a very non-standard usage of Rake.  The typical way to support positional args with Rake would be something like:

```ruby
namespace :import do
  task :from_v5, [:filename] => :environment do |task, args|
    if !args.key?(:filename)
      warn 'Usage: rails import:from_v5[FILENAME]'
      exit 1
    end
    puts "importing #{args[:filename]}..."
    exit 0
  end
end
```

And then you would call it with

```console
$ bin/rails import:from_v5[path/to/file]
importing foo/to/file...
```

However, if you really want to use `ARGV`, you could run the task with `bin/rake` instead.  You would just need to account for `ARGV[0]` being the command name:

```ruby
namespace :import do
  task from_v5: :environment do
    ARGV.shift # <=== remove "import:from_v5" at ARGV[0]

    if ARGV.length < 1
      warn 'Usage: rails import:from_v5 FILENAME'
      exit 1
    end
    puts "importing #{ARGV[0]}..."
    exit 0
  end
end
```

```console
$ bin/rake import:from_v5 path/to/file
importing path/to/file...
```

**Comment by mildred** [comment]
Using brackets is probably the rake way to do it, but standard shell is to use positional args and rails commands follow this generally.

Also, I tried using `rake` instead of `rails` but it fails down the line. I believe there is not the same application initialization taking place.

The `(rake.top_level_tasks-args).find { |task| !rake.lookup(task[/[^\[]+/]) }` seems good. Updating my comment above

**Comment by jonathanhefner** [comment]
> Using brackets is probably the rake way to do it, but standard shell is to use positional args and rails commands follow this generally.

Indeed, most Rails commands accept positional args because they are implemented using `Rails::Command::Base`, not Rake tasks.  The ones that are implemented using Rake tasks either use ENV-style args, such as [`app:template LOCATION=path/to/file`](https://github.com/rails/rails/blob/d6197c5efc84161bb507b73b9d7f5bb064c33cf2/railties/lib/rails/tasks/framework.rake#L7-L9), or brackets, such as [`time:zones[-5]`](https://github.com/rails/rails/blob/d6197c5efc84161bb507b73b9d7f5bb064c33cf2/railties/lib/rails/tasks/misc.rake#L4-L8).

> Also, I tried using `rake` instead of `rails` but it fails down the line. I believe there is not the same application initialization taking place.

Perhaps that is something we can address (either in Rails or your app)?  For example, I see that `bin/rake` does not set `APP_PATH` the way that `bin/rails` does.

> The `(rake.top_level_tasks-args).find { |task| !rake.lookup(task[/[^\[]+/]) }` seems good (it is working). Updating my comment above

Unfortunately, that is not a valid solution.  `args` here is simply the other Rake tasks, if any.  For example, when running `bin/rails task1 task2 task3`, `task` will be `"task1"`, `args` will be `["task2", "task3"]`, and `rake.top_level_tasks` will be `["task1", "task2", "task3"]`.  So using `rake.top_level_tasks-args` would defeat the purpose of checking each task name.

(The reason the variable is named `args` is because `perform` is overriding [`Rails::Command::Base.perform`](https://github.com/rails/rails/blob/d6197c5efc84161bb507b73b9d7f5bb064c33cf2/railties/lib/rails/command/base.rb#L67).)

**Comment by stadniklksndr** [comment]
@jonathanhefner thanks for clarification

**Comment by mildred** [comment]
Isn't this code called each time a rake task is to be executed? If so, it's only necessary to check the first rake task, and the oters would be checked when called later on.

**Comment by jonathanhefner** [comment]
> Isn't this code called each time a rake task is to be executed? If so, it's only necessary to check the first rake task, and the oters would be checked when called later on.

No, `RakeCommand.perform` is executed once per invocation of `bin/rails`.  It then handles control over to Rake.

**Comment by mildred** [comment]
In the meantime, adding this to the top of `config/application.rb` seems to work

```rb
$LOAD_PATH << File.join(File.dirname(__dir__), 'lib')
```
