### ISSUE TITLE
Encrypted columns in DB are not backwards compatible between 7.0 and 7.1

### ISSUE THREAD

**Issue by Linuus** [rails/rails#50226]
I'm not sure if this is expected or a bug, but I can't find it in the changelogs. There were changes related to encryption though so maybe it's not a bug.

The issue is that we upgrade from Rails 7.0.8 to 7.1.1 and had to roll back due to some unrelated issues. Now, after the roll back we couldn't decrypt fields that were encrypted while on 7.1.1 anymore (using AR `encrypts(:foo)`). I tested with 7.1.2 and had the same issue.

### Steps to reproduce

1. Generate a new rails app on 7.0.8
2. Add a model with an encrypted field
3. On 7.0.8, create a record in the DB
4. Change gemfile to have rails 7.1.2 and bundle
5. Create another record in the DB. At this point it's possible to decrypt the old record
6. Add the setting `config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256` to application.rb
7. Create a third record in the DB
8. Go back to Rails 7.0.8
9. Read the records in the DB. First and second records are fine, but the third will fail with
```
/Users/.../.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/active_record/encryption/encryptor.rb:58:in `rescue in decrypt': ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption)
/Users/.../.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/active_record/encryption/cipher/aes256_gcm.rb:80:in `rescue in decrypt': ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption)
/Users/.../.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/active_record/encryption/cipher/aes256_gcm.rb:76:in `final': OpenSSL::Cipher::CipherError
```

I created a repository to easier reproduce this: https://github.com/Linuus/rails-encryption/

1. Clone the repo
2. `git checkout 8a4a807faed975545b13fb710f7e119501daa261`
3. `bundle`
4. `rails c`
5. `Bar.create!(secret: "rails708")`
6. `git checkout e213132e7c85747560b395f0f34f6628b3b202cc` (switch to 7.1.2)
7. `bundle`
8. `rails c`
9. `Bar.create!(secret: "rails712")`
10. `git checkout 05f77873a0fb71de34e1fc15c8c786b543ead2b6` (sets `config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256`)
11. `rails c`
12. `Bar.create!(secret: "rails712-2")`
13. `git checkout 8a4a807faed975545b13fb710f7e119501daa261` (Roll back to 7.0.8)
14. `rails c`
15. `Bar.first.secret #=> rails708`
16. `Bar.second.secret #=> rails712`
17. `Bar.third.secret` crashes with the above decryption error

In 7.0.8 we have this:

```
Loading development environment (Rails 7.0.8)
irb(main):001> Rails.configuration.active_support.key_generator_hash_digest_class
=> OpenSSL::Digest::SHA256
```

In 7.1.2 we haven't set the SHA1 setting (makes no difference as far as I can see. 7.1.2 can still decrypt data from 7.0.8)

```
Loading development environment (Rails 7.1.2)
irb(main):001> Rails.configuration.active_record.encryption.support_sha1_for_non_deterministic_encryption
=> nil
```

So as far as I understand the docs, the encryption shouldn't change?

### Expected behavior

The records should all be decryptable

### Actual behavior

The record created in Rails 7.1.2 and with `config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256` fail to decrypt.

### System configuration
**Rails version**: 7.0.8 -> 7.1.2 (or 7.1.1.)

**Ruby version**:  ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

**Comment by Linuus** [comment]
Update

If I'm in 7.1.2 and set `config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA1` instead. Create a record and then go back to 7.0.8 it seems to work. So maybe it's [this](https://github.com/rails/rails/issues/42922) and the data encrypted on 7.0.8 is SHA1?

So... can 7.1.2 decrypt SHA1 (even if configured for SHA256) but 7.0.8 can't decrypt SHA256 after rolling back?

**Comment by Linuus** [comment]
Okay, so the issue seems to be:

1. The data in 7.0.8 is SHA1 (even if it says SHA256)
2. When moving to 7.1 and set SHA256, it reports `Rails.configuration.active_record.encryption.support_sha1_for_non_deterministic_encryption => nil` but internally it is set to `true` ([link](https://github.com/rails/rails/blob/v7.1.1/activerecord/lib/active_record/encryption/configurable.rb#L25-L27)).
3. 7.1 can now decrypt the SHA1 data until you load the 7.1 defaults which sets `support_sha1_for_non_deterministic_encryption` to `false`.

So, the alternatives for existing apps are:

1. Go with the less secure SHA1. All should work.
2. Go with SHA256, and set `support_sha1_for_non_deterministic_encryption` to `true` and accept that it is impossible to roll back to < 7.1.

Can 2 above be made more clear in the upgrade docs since it looks like everything is fine until you need to roll back?

**Comment by Flixt** [comment]
I'm currently going through the upgrade from 7.0 to 7.1 and experience the same.
I think we will stick with SHA1 for now, but I tried to fiddle around a bit.

It should be possible to add a KeyProvider using SHA256 with Rails 7.0.x. So if you need to go back from 7.1 to 7.0 and have used SHA256 with 7.1 you can do something like this in application.rb:

```ruby
class Sha256KeyGenerator < ActiveRecord::Encryption::KeyGenerator
  def derive_key_from(password, length: ActiveRecord::Encryption.cipher.key_length)
    ActiveSupport::KeyGenerator.new(password, hash_digest_class: OpenSSL::Digest::SHA256)
                               .generate_key(Rails.application.credentials.active_record_encryption.key_derivation_salt!, length)
  end
end

class Sha256KeyProvider < ActiveRecord::Encryption::KeyProvider
  def initialize(passwords)
    super(Array(passwords).collect { |password| derive_key_from(password, using: Sha256KeyGenerator.new) })
  end

  private

  def derive_key_from(password, using: key_generator)
    secret = using.derive_key_from(password)
    ActiveRecord::Encryption::Key.new(secret)
  end
end


module MyApp
  class Application < Rails::Application
    # ...
    config.active_record.encryption.previous = [
      {key_provider: Sha256KeyProvider.new(Rails.application.credentials.active_record_encryption.primary_key!)}
    ]
    # ...
  end
end
```

This is basically the same what Rails 7.1 does for compatibility with SHA1 when setting `support_sha1_for_non_deterministic_encryption = true`.
The custom KeyProvider and KeyGenerator are necessary because ActiveRecord 7.0.x `ActiveRecord::Encryption::KeyGenerator` does not support setting the `hash_digest_class` and `ActiveRecord::Encryption::DerivedSecretKeyProvider` does not support setting the `key_generator`.

**Comment by Linuus** [comment]
@Flixt Thanks! Yeah we are currently doing something very similar in our codebase as well 👍

**Comment by trevorturk** [comment]
I'm stumbling over this same thing now, and I think the downgrade problem is a known issue. See the following comment: https://github.com/rails/rails/pull/44540#issuecomment-1082623602

> ...that still leaves inaccessible data if someone upgrades and then reverts, say

Perhaps it's worth adding more detail about this to the Rails upgrade guide to warn about this gotcha?

There's another somewhat related issue having to do with initialization order that I think may also be worth highlighting: https://github.com/rails/rails/issues/50212#issuecomment-1907637879

Also (this might be a stretch, but worth mentioning) we could consider trying to add a patch back in Rails 7.0 so that it would be possible to decrypt both sha1 and sha256. To my mind, if Rails 7.0 (and 7.1, ideally) could decrypt both sha1 and sha256, it doesn't much matter what the default is when writing since you'd be able to decrypt either.

**Comment by ezekg** [comment]
@trevorturk just FYI, and for others attempting the upgrade, this allows rollbacks to be easier to manage:

```rb
config.active_record.encryption.store_key_references = true
```

That way, any new encrypted data populated by Rails 7.1 can still be decrypted if you happen to need to rollback to Rails 7.0, because the encryption key's ID is stored in the dataset itself.

I've had to do a couple rollbacks so far, and I'm glad I had this enabled otherwise we would've had big problems.

**Comment by trevorturk** [comment]
Thanks for the tip! I hadn't seen that before. I gave it a try following a modified script from https://github.com/rails/rails/issues/50212 but I still ran into an issue in the end where I had data created in Rails 7.1.3 that I wasn't able to decrypt in 7.0.8. I might be doing something wrong (or getting confused, because this is all very confusing!) but here's the script I ran through in case you'd like to try to reproduce:

```
cd test_rails_enc
rails _7.0.8_ new test_rails_enc
cd test_rails_enc
bin/rails db:encryption:init
rails credentials:edit
rails g model user email:string name:string
rake db:migrate

# app/models/user.rb
class User < ApplicationRecord
  encrypts :email, deterministic: true
  encrypts :name
end

# config/application.rb
config.active_record.encryption.store_key_references = true

rails c
User.create(name: "Zaratan", email: "zaratan@hey.com")

# all good so far on Rails 7.0.8, now let's upgrade to Rails 7.1.3...

# Gemfile
gem "rails", "~> 7.1.3"

bundle install

rails c
User.pluck(:email).first
=> ActiveRecord::Encryption::Errors::Decryption # bad!
User.pluck(:name).first
=> "Zaratan"

# I wish we didn't have to make configuration changes here, but I believe it's necessary as per https://github.com/rails/rails/pull/44873 and I wonder if we should update the upgrade guide to make this more clear

# config/application.rb
config.load_defaults 7.0 # 7.1 also works
config.active_record.encryption.store_key_references = true
config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256
config.active_record.encryption.support_sha1_for_non_deterministic_encryption = true

rails c
User.pluck(:email).first
=> "zaratan@hey.com" # good!
User.pluck(:name).first
=> "Zaratan" # good!

# Now let's create a record in Rails 7.1.3 with the above config...

User.create(name: "Zaratan2", email: "zaratan2@hey.com")

# ...and then downgrade back to Rails 7.0.8...

# Gemfile
gem "rails", "~> 7.0.8"

# config/application.rb
config.load_defaults 7.0
config.active_record.encryption.store_key_references = true

bundle install

rails c
User.pluck(:email).last
=> "zaratan2@hey.com"
User.pluck(:name).last
=> ActiveRecord::Encryption::Errors::Decryption # bad!

# ...and this is where I think I've confused myself, because now I'm not able to read the record that was created in Rails 7.1.3 even with what I think should be the correct config:

# config/application.rb
config.load_defaults 7.0
config.active_record.encryption.store_key_references = true
config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256
config.active_record.encryption.support_sha1_for_non_deterministic_encryption = true

rails c
User.pluck(:email).last
=> "zaratan2@hey.com"
User.pluck(:name).last
ActiveRecord::Encryption::Errors::Decryption # bad!
```

Again, I might be getting something wrong here (please do try to reproduce!) but it looks to me like it's impossible to downgrade from Rails 7.1.3 to 7.0.8 without data loss, if new encrypted records were created in Rails 7.1.3?

**Comment by ezekg** [comment]
@trevorturk sorry, I was mistaken. I redact what I said. I was looking at a deterministically encrypted model, which wasn't effected. That was an oversight on my part. Upon further inspection, we do have some botched data now since we had to do a rollback and are implementing the above workaround until we can successfully roll out with 7.1. This has been a headache.

**Comment by trevorturk** [comment]
Gotcha, ok. Yeah, I'm also dealing with some issues upgrading from 7.0.8 -> 71.13 that I'm still trying to debug, but luckily didn't deploy to production yet, and I'll be testing carefully before proceeding further!

I'm trying to get my head around all of this so at least perhaps I can suggest some improvements to the documentation to reduce the chances that others will run into similar issues, but I left a comment here https://github.com/rails/rails/pull/48530#issuecomment-1908595655 because I'm wondering if the best solution would be a new config option for 7.1.x (also back-ported to 7.0.x) to enable decrypting any of the possible configs Rails has shipped with thus far. 

I'm not terribly concerned about which config I'm using, but I would like some assurance that I'll be able to read any preexisting data if the defaults change. With my current app, for example, I intentionally left things in the default state (no explicit config options) which I was hoping would be safest. But now I believe I'll have to add config options in order to read older data after I upgrade, since the default has changed.

**Comment by calebhearth** [comment]
I also ran into this issue and have opened a PR to [document it in the upgrade guide and release notes](https://github.com/rails/rails/pull/53587).

(Originally published at: https://calebhearth.com/rails-7-1-encryption-errors)

**Comment by buihung-wogi** [comment]
> I also ran into this issue and have opened a PR to [document it in the upgrade guide and release notes](https://github.com/rails/rails/pull/53587).
> 
> (Originally published at: https://calebhearth.com/rails-7-1-encryption-errors)

Hello @calebhearth Forgive me if I missed something, but I think your article is talking about the side 7.0->7.1.
Otherwise this issue is opening for case downgrade from 7.1 -> 7.0? May someone got this case in staging environment?
