### ISSUE TITLE
Broken `order("included.column").includes(:included).ids` in PostgreSQL

### ISSUE THREAD

**Issue by manuelvanrijn** [rails/rails#50263]
### Steps to reproduce

This bug was introduced by using `group` over `distinct` in #48101. The original problem was when having a `order` on the object that is being queried and having a `includes` it would fail. After the change, this works, but results in an issue when the order is added for the object which is in the `includes`.

```ruby
  def test_includes_with_order_on_includes_object
    Post.includes(:comments)
        .order("comments.created_at DESC")
        .ids
  end
```

I would like to create a fix, but think we first need to make sure what the best path for the solution should be.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "pg"
end

require 'active_record'
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
begin
  config = { adapter: "postgresql", encoding: 'unicode', url: "postgresql://postgres@localhost:5432", password: 'postgres', database: 'rails-test' }
  ActiveRecord::Base.establish_connection(config.except(:database))
  ActiveRecord::Base.connection.drop_database(config[:database]) rescue nil
  ActiveRecord::Base.connection.create_database(config[:database])
end

ActiveRecord::Base.establish_connection(config)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamps
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.timestamps
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_includes_ids
    Post.includes(:comments)
        .order("comments.created_at DESC") # or .merge(Comment.order(created_at: :desc))
        .ids
  end
end
```

### Expected behavior
no exception

### Actual behavior
```
ActiveRecord::StatementInvalid: PG::GroupingError: ERROR:  column ~ must appear in the GROUP BY clause or be used in an aggregate function
```

I've created this issue for Postgres, but MySQL would also give an error with default configurations. Changing `sql_mode` would resolve the error
```
ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'sqltest_tmp_db.comments.description' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

### System configuration
**Rails version**: main

**Ruby version**: 3.2.2

**Comment by manuelvanrijn** [comment]
So after some digging, having an includes would result in a getting back a list of `ids` which aren't unique. Like if I have 2 comments on 1 post, I get the `id` twice.

- Adding the `order` columns to the `group by` doesn't seem like a good fit because this will result in duplicate id's.
- Removing the `order` would be a possibility, although the order of the `.ids` would then be based on the primary key of the model.

**Comment by commitshappen** [comment]
## Replication

I was able to replicate this issue locally using some of the data we have in Weedmaps. We're currently migrating from 7.0 to 7.1, so we ran the comparison against these two versions. 

**Ruby We Ran**

> What we _actually_ ran was slightly different and specific to WM, but it was around the same style of `has_many` relationship.

```ruby
Post.includes(:comments).order("comments.created_at DESC").ids
```

**7.0 SQL Output**

Works as you might expect by returning the list of IDs.

```sql
SELECT "posts"."id" FROM "posts"
LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id"
ORDER BY posts.created_at DESC
```

**7.1 SQL Output**

Raises a `ActiveRecord::StatementInvalid: PG::GroupingError`.

```sql
SELECT "menus"."id" FROM "menus"
LEFT OUTER JOIN "menu_items" ON "menu_items"."menu_id" = "menus"."id"
GROUP BY "menus"."id"
ORDER BY menu_items.created_at DESC
```

However, if you switch the `includes` to a `joins` it works just as it did in 7.0 and does not raise an error.

```ruby
Post.joins(:comments).order("comments.created_at DESC").ids

# -- Generated the following SQL --
#
# SELECT "posts"."id" FROM "posts"
# LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id"
# ORDER BY posts.created_at DESC
```

## Suggestions

If this is intended behavior, perhaps we should document it as a breaking change. I didn't notice anything in the [includes section](https://guides.rubyonrails.org/active_record_querying.html#includes) of the guides about this, so perhaps that's the best place for it. There is a small reference in the [ordering section](https://guides.rubyonrails.org/active_record_querying.html#ordering) about raising an exception, but that doesn't clearly state it's because of an `includes` instead of a `joins`.

Personally I think using an `includes` here should raise in favor of a `joins`. If you just want the ids, there's no reason to use an AR method that loads the data. In either case, improved documentation or error output would be amazing.

**Comment by commitshappen** [comment]
## Replication

I was able to replicate this issue locally using some of the data we have in Weedmaps. We're currently migrating from 7.0 to 7.1, so we ran the comparison against these two versions. 

**Ruby We Ran**

> What we _actually_ ran was slightly different and specific to WM, but it was around the same style of `has_many` relationship.

```ruby
Post.includes(:comments).order("comments.created_at DESC").ids
```

**7.0 SQL Output**

Works as you might expect by returning the list of IDs.

```sql
SELECT "posts"."id" FROM "posts"
LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id"
ORDER BY posts.created_at DESC
```

**7.1 SQL Output**

Raises a `ActiveRecord::StatementInvalid: PG::GroupingError`.

```sql
SELECT "posts"."id" FROM "posts"
LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id"
GROUP BY "posts"."id"
ORDER BY comments.created_at DESC
```

However, if you switch the `includes` to a `joins` it works just as it did in 7.0 and does not raise an error.

```ruby
Post.joins(:comments).order("comments.created_at DESC").ids

# -- Generated the following SQL --
#
# SELECT "posts"."id" FROM "posts"
# LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id"
# ORDER BY posts.created_at DESC
```

## Suggestions

If this is intended behavior, perhaps we should document it as a breaking change. I didn't notice anything in the [includes section](https://guides.rubyonrails.org/active_record_querying.html#includes) of the guides about this, so perhaps that's the best place for it. There is a small reference in the [ordering section](https://guides.rubyonrails.org/active_record_querying.html#ordering) about raising an exception, but that doesn't clearly state it's because of an `includes` instead of a `joins`.

Personally I think using an `includes` here should raise in favor of a `joins`. If you just want the ids, there's no reason to use an AR method that loads the data. In either case, improved documentation or error output would be amazing.
