### ISSUE TITLE
`ActiveSupport::BroadcastLogger` does not respect `config.log_level` in Rails 7.1

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#50324]
I am working on upgrading an app from Rails 7 to 7.1 and onto edge. I've come across an issue that I think is a bug, but could also be configuration not being used as intended.

Rails 7 config:

```ruby
# config/application.rb
config.logger = Logist::Logger.new($stdout)
other_logger = AnotherLogger.new

config.logger.extend(ActiveSupport::Logger.broadcast(other_logger))

config.log_level = :info if Rails.env.production?
```

With this config, `Rails.logger.debug` does nothing in production. 🟢 

The Rails 7 config relied on the private API described in https://github.com/rails/rails/pull/48615, so we have to refactor it for 7.1. 7.1/Edge Rails config:

```ruby
# config/application.rb
config.logger = Logist::Logger.new($stdout)
other_logger = AnotherLogger.new

config.logger = ActiveSupport::BroadcastLogger.new(config.logger, other_logger)

config.log_level = :info if Rails.env.production?
```

With this config, `Rails.logger.debug` logs in production. 🔴 

I think the issue comes from https://github.com/rails/rails/pull/49721, since the `log_level` is no longer being assigned to the broadcast loggers. I would expect `config.log_level` to work for whatever you assign `config.logger` too, and if that's changing it seems like a breaking change to me.

Is the expectation that if you use `BroadcastLogger`, you set the `level` manually on loggers?

cc @Edouard-chin @andrewn617  @rafaelfranca 

### System configuration
**Rails version**: `main`

**Ruby version**: 3.2

**Comment by Edouard-chin** [comment]
👋 

I think the real issue is the `log_level` config being set to `:debug` which shouldn't apply when a broadcast is configured:
https://github.com/rails/rails/blob/89d8569abe2564c8187debf32dd3b4e33d6ad983/railties/lib/rails/application/configuration.rb#L54

In Rails 7, if you had configured a broadcast with different logger levels, this would have had to be done inside an initializer after Rails' `initialize_logger` one, otherwise the level on your broadcast would be changed to the default DEBUG value.
https://github.com/rails/rails/blob/87f3f811a7320dc8cb79695a1f965189357421b9/railties/lib/rails/application/bootstrap.rb#L57


I agree with you that `config.log_level` being ignored seems off, so I think the behaviour that would make the most sense is:

- Ignore the default `DEBUG` log_level when using a Broadcast Logger
- Set the whole broadcast level when `log_level=` is explicitly called

**Comment by ghiculescu** [comment]
Thanks - I can work on a fix for that over the coming days.

Proposing we take https://github.com/rails/rails/pull/49721 off `7-1-stable` while this gets sorted out: https://github.com/rails/rails/pull/50329

**Comment by Edouard-chin** [comment]
> So either you've set one manually on them (which overrides the DEBUG default)

The default `log_level` had precedence and was overriding the whole broadcasts, e.g.
```ruby
# config/application.rb

stdout = Logger.new(STDOUT, level: Logger::INFO)
stderr = Logger.new(STDOUT, level: Logger::ERROR)
config.logger = ActiveSupport::BroadcastLogger.new(stdout, stderr)

# After the app boots
puts Rails.logger.broadcasts.map(&:level) # => [Logger::DEBUG, Logger::DEBUG]
```

> Although as I write that, I realise that is at odds with the issue described by https://github.com/rails/rails/pull/49721

That's true, but if an application sets a broadcast logger with various levels and then explicitly calls `config.log_level=`, then it's a configuration error at the application level, not a bug in Rails.

I believe https://github.com/rails/rails/pull/49721 was originally opened to fix the issue in my first snippet, with the side effect that it's now completely ignoring Rails' `log_level`.

_______

I don't think it's worth reverting #49721. I can open a fix today (hopefully my rationale makes sense 😅).

**Comment by ghiculescu** [comment]
Thanks for your help, makes total sense to me.
