### ISSUE TITLE
logs are not generating in production.log file when rails app environment is production

### ISSUE THREAD

**Issue by mamirad** [rails/rails#50369]
### Steps to reproduce

```ruby
config.logger = ActiveSupport::Logger.new(STDOUT)
  .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
  .then { |logger| ActiveSupport::TaggedLogging.new(logger) }
```
the above code in production.rb file is not generating logs in production.log file

### Expected behavior

logs should be generated in production.log file when application is running in production environment
### Actual behavior

rails app is running in production environment but
logs are not logging in production.log file

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.0.2

**Comment by fatkodima** [comment]
Can you create a sample app that reproduces the issue and share a link to it?

**Comment by mamirad** [comment]
Thank you, I have followed you and log issue has been resolved

**Comment by salex** [comment]
I'm not sure, but I think this issue needs to be reopened!

If you generate an new rails 7.1.2 application, that code is there (and has been forever)

```ruby
  # Log to STDOUT by default
  config.logger = ActiveSupport::Logger.new(STDOUT)
    .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
    .then { |logger| ActiveSupport::TaggedLogging.new(logger) }

  # Prepend all log lines with the following tags.
  config.log_tags = [ :request_id ]

  # Info include generic and useful information about system operation, but avoids logging too much
  # information to avoid inadvertent exposure of personally identifiable information (PII). If you
  # want to log everything, set the level to "debug".
  config.log_level = ENV.fetch("RAILS_LOG_LEVEL", "info")
```

I've spent the last few day trying to figure out why my production server was not working.  I finally put a couple things together.

- I didn't notice that production wasn't logging a few weeks ago.
- I though is was something I did and tried all kinds of stuff. Notice that the log_level was set after the STDOUT block,
- I finally noticed that it stopped logging on Nov 11, 2023. The day I upgraded to 7.1.2 from 7.1.1.
- I checked the issues and found this.

That STDOUT block has been there forever and it worked. Somewhere else in the config's it states that but default it will log debug in development and :info in staging and production. That's what it did until Nov 11th! The production.rb file was not changed from 7.1.1.

Maybe since production logs are rarely looked at someone  changed the default to STDOUT for production.

I'd at least try to find someone else who upgraded to 7.1.2 and have the same problem. You at least have two who had the problem.

**Comment by salex** [comment]
I think I misunderstood the difference on how 7.1.2 logs in production.

7.0 the stdout stuff is 

```ruby
 if ENV["RAILS_LOG_TO_STDOUT"].present?
    logger           = ActiveSupport::Logger.new(STDOUT)
    logger.formatter = config.log_formatter
    config.logger    = ActiveSupport::TaggedLogging.new(logger)
  end
```
In my 2 deployed 7.0 apps,  I have a production log. In 7.1.2 the production log was empty.

```ruby
  config.logger = ActiveSupport::Logger.new(STDOUT)
    .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
    .then { |logger| ActiveSupport::TaggedLogging.new(logger) }
```

So it appears I that **ENV["RAILS_LOG_TO_STDOUT"].** was not set in 7.0 and so it logged to the production.log

If I can read in-between the lines in the update, they made log to STDOUT the default. No production.log

I guess that is what caused me to spend a couple days trying to figure out why there was no production.log!

I'm just a _hobbist_ developer so it takes a little longer!  

If there is an error that didn't show up in staging or development - where is it logged? (I'm also not proficient in testing!)

I guess I can take out logrotate for the production long.

Don't know if this change (default) was in the release notes or not.  I probably just scanned them.

Sorry for the "should be re-opened" comment,
