### ISSUE TITLE
Rails 7.1: ActiveRecord polymorphic raise error after add query_constraints

### ISSUE THREAD

**Issue by azhaizhai** [rails/rails#50435]
### Steps to reproduce

I got an error when I try to use Composite Primary Keys in Rails 7.1. When I add query_constraints to the model, the polymorphic won't work any more.
Is it a bug or may I do something wrong? 

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.1.0"
  gem "sqlite3"
  gem "debug"
end

require "active_record"
require "logger"
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :comments do |t|
    t.bigint :ts, null: false
    t.bigint :nonce, null: false
    t.string :owner_type, null: false
    t.string :owner_id, null: false

    t.timestamps
  end

  create_table :articles do |t|
    t.timestamps
  end
end

class Comment < ActiveRecord::Base
  query_constraints :ts, :nonce
  belongs_to :owner, polymorphic: true
end

class Article < ActiveRecord::Base
  has_many :comments, as: :owner
end

article = Article.new
article.save!
article.comments
```

### Expected behavior

It should work well and won't raise error
### Actual behavior

raise error
```ruby
~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.2/lib/active_record/reflection.rb:799:in `derive_fk_query_constraints': The query constraints on the `Comment` model does not include the primary key so Active Record is unable to derive the foreign key constraints for the association. You need to explicitly define the query constraints for this association. (ArgumentError)

            raise ArgumentError, <<~MSG.squish
```
### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**Comment by bparanj** [comment]
Working example:

```ruby
class Comment < ActiveRecord::Base
  belongs_to :owner, polymorphic: true
end

class Article < ActiveRecord::Base
  has_many :comments, as: :owner, query_constraints: [:ts, :nonce]
end
```

Please refer the [docs](https://guides.rubyonrails.org/association_basics.html)

**Comment by nvasilevski** [comment]
@bparanj I'm afraid this is not a correct configuration to make the setup work.  `query_constraints:` option in associations can be seen as a "composite foreign key" and it won't make sense to say that the foreign key for the `article#comments` association is `[:ts, :nonce]` as there are no such fields on `Article`.

I think the error message could be improved as it is not particularly clear which association needs attention and it explicitly asks for `query_constraints:` argument to be provided while it's not the only option here.
```
The query constraints on the `Comment` model does not include the primary key so Active Record is unable to derive the foreign key constraints for the association. You need to explicitly define the query constraints for this association.
```
What it intends to tell is that because `Comment` model has a query constraints defined by default it expects the model to be queried by the composite key which means it tried to derive a composite foreign key automatically. Since it's not possible to reliably derive foreign key to match `[:ts, :nonce]` query constraints it raises an error. In order to prevent Rails from guessing the foreign key we could set it manually to preserve the non-composite primary key behavior:

```ruby
class Comment < ActiveRecord::Base
  query_constraints :ts, :nonce
  belongs_to :owner, polymorphic: true, foreign_key: :owner_id
end

class Article < ActiveRecord::Base
    has_many :comments, as: :owner
end

article = Article.create!
comment = Comment.create(ts: 1, nonce: 111, owner: article)

raise "owner is not the article"  unless comment.owner == article

comments = article.comments.to_a

raise "comments are different" unless [comment] == comments
```

But this brings a question whether Rails could fallback to a default non-CPK `foreign_key: :owner_id` configuration instead of raising an error? In this case that would have worked but I believe the reason for raising an error was to at all cost avoid silently choosing a wrong foreign key and leaving an association in a broken or simply wrong state even if it works. We can have a closer look on it after the holidays to see if Rails could continue follow the convention in this case without risking to configure the association in a wrong way.

@azhaizhai Let me know if the suggested `foreign_key: :owner_id` configuration doesn't work as you expected. Thanks!

**Comment by azhaizhai** [comment]
@nvasilevski `foreign_key: :owner_id` worked for me as expected. Thank you!
