### ISSUE TITLE
Add basic authentication generator

### ISSUE THREAD

**Issue by dhh** [rails/rails#50446]
Rails now include all the key building blocks needed to do basic authentication, but many new developers are still uncertain of how to put them together, so they end up leaning on all-in-one gems that hide the mechanics. While these gems are great, and many people enjoy using them, they should not be seen as a necessity. We can teach Rails developers how to use the basic blocks by adding a basic authentication generator that essentially works as a scaffold, but for authentication.

Note: This ticket serves as a placeholder for the intention to do this work. Not as an open invitation to feature requests. Before we engage in broad discussion of what should or shouldn't be in such a generator, the core team will propose a solution first, so there's something tangible to discuss.

cc @rafaelfranca

**Comment by devcamke** [comment]
Great!

Have been waiting for this.

**Comment by claudiug** [comment]
@dhh are you thinking something similar to: https://github.com/lazaronixon/authentication-zero

**Comment by dhh** [comment]
@claudiug That's too much for what I have in mind, but the general direction of using generators instead of engines is correct.

**Comment by seanwmitchell** [comment]
Could a simple magic link approach be an elegant yet simple solution?

**Comment by dhh** [comment]
Going to tap the sign in the issue description about now diving into specific feature discussions before there's a PR proposal 😄

**Comment by inkyvoxel** [comment]
Amazing! Authentication has been my biggest stumbling block to take my hobby projects from localhost to something I want to share with others.

**Comment by dixpac** [comment]
@dhh is this open for a PR, or we wait for the core team to build initial "version"?

**Comment by arianvp** [comment]
Should include Passkey support ideally. If rails just supports that out of the box that'd be huge

**Comment by kwhandy** [comment]
> We can teach Rails developers how to use the basic blocks by adding a basic authentication generator that essentially works as a scaffold, but for authentication.

Is this finally an early signals that the foundation will do video course on youtube too?

**Comment by revskill10** [comment]
Because it's DHH said, everyone will follow. But it's Rails problem for monopoly on DHH decision.

100% of application has authentication builtin, this decision should be decided sice Rails 2.0.

Alright, too late, but it's better than never.

**Comment by crbelaus** [comment]
The Elixir Phoenix team used the same generator approach with the mix [phx.gen.auth](https://hexdocs.pm/phoenix/mix_phx_gen_auth.html) command.

Even though it is a different language and framework I'm just mentioning it in case it can be interesting or useful to examine.

**Comment by dhh** [comment]
"Device is the reason Rails sucks" adds nothing of value to the technical discussion, and it's a violation of our Code of Conduct. This has merited a 30-day suspension from engagement here. Let's get back to discussing technical progress.

**Comment by tobi** [comment]
I think that's an excellent decision. 

One of the reasons authentication has always been a DIY/Userspace feature has been that our Browsers didn't have a native solution ready. The common implementations of user/password have been an unmitigated disaster for security by shifting identity responsibilities to the uses. This has now changed with Passkeys being implemented well on all evergreen browsers and operating systems. 

The passkey spec is not perfect but it's a very good set of tradeoffs with a workable API. I feel it makes sense to consider a strong push towards passkeys as a default convention.

**Comment by bparanj** [comment]
I would rather go in passwordless or passkey based authentication approach.

**Comment by tcannonfodder** [comment]
Seconding the calls for a passkeys-first approach; for the reasons outlined here: https://github.com/heartcombo/devise/issues/5527

**Comment by dhh** [comment]
We built a full passkey solution for ONCE #1 but the user ergonomics left a ton to be desired. So we pulled it out again. Long term, I can definitely see the appeal. But right now the way passkeys are synced or not on different platforms and browsers is hella confusing.

So I want to keep watching the puck, but for an application made with regular users today, it seems too soon to skate there.

But we should get all our infrastructure ready for when passkeys are not just viable but obvious everywhere. We will extract our work into a gem. Too much machinery to all just generate as part of a controller.

**Comment by Ukaypromise** [comment]
I strongly believe that this is an excellent decision.

**Comment by arianvp** [comment]
That makes sense. Happy that it's on the radar though.

**Comment by kobaltz** [comment]
I've been working on https://github.com/kobaltz/action_auth for this very reason. Basically using only the Rails provided mechanisms, I wanted to have a simple authentication solution that could be yanked out in hopes that a Rails built-in solution would seamlessly (as much as possible) take over when or if that time ever came.

**Comment by AlexeyMatskevich** [comment]
I just use [rodauth](https://rodauth.jeremyevans.net/) and [rodauth-rails](https://github.com/janko/rodauth-rails). Simply because its out-of-the-box feature set is incomparably larger than Devise and any other authentication framework I've seen.
Webauth? no problem, JWT ? Have you ever tried to embed jwt + refresh in devise? it's just available immediately here.
Both View and JSON api are available at once.

And the library author is pretty reliable, after all it's a rack, ruby and sequel orm maintainer.

And if something isn't there, it's either just integrate it yourself or there are plugins available:
1. [oauth](https://gitlab.com/os85/rodauth-oauth)
2. [omniauth](https://github.com/janko/rodauth-omniauth)
3. [pwned](https://github.com/janko/rodauth-pwned)
4. etc...

**Comment by dhh** [comment]
That is vastly out of scope for what this intends to be. Plenty of room for kitchen sink with gems to continue to serve that. In any case, as per the issue, let’s hold off on discussing features until there’s a proposal PR ready.

**Comment by laptopmutia** [comment]
this is cool finally some masterchef would do the omakase for auth in rails

**Comment by sergiotapia** [comment]
This is a great idea! In Phoenix land, there's the [phx.gen.auth](https://hexdocs.pm/phoenix/mix_phx_gen_auth.html) generators that use basic building blocks to build a secure solution out of the box. 

Once generated you can tweak the code to your specific needs if necessary. Maybe something like this would be terrific for Rails.

**Comment by AndreyAzimov** [comment]
I switched from devise to authentication-zero, because it's generate all the code and I can see it all, so I can modify it as much as I want.

https://github.com/lazaronixon/authentication-zero

**Comment by joyoy96** [comment]
> great to here it. I switched from devise to authentication-zero, because it's generate all the code and I can see it all, so I can modify it as much as I want.
> 
> https://github.com/lazaronixon/authentication-zero

that is cool, I wonder where u all keep discovering these shiny gems

**Comment by ababich** [comment]
even basic requirements are missing here :)

what is auth here? auth for humans? auth for APIs? and this is only beginning of long question/decision tree about how auth _may_ work

I believe auth is so extremely broad question with so many opinions that to put into rails “distribution “ would be too questionable and opinionated ;)

**Comment by mtimofiiv** [comment]
If the goal is to give people a quick, easy to roll out alternative to the step of installing one of several rich featured gems out there - I would imagine then the focus should be on authenticating humans, and giving the developer the most dead-simple functionality that covers the most common use-case:

 * Sign up
 * Log in
 * Log out

A user model, with some basic infrastructure (like views) to handle this would go (in my opinion) as far as this would need to go.

For anything else there are gems. Maybe I'm over-simplifying here.

The new system would obviously need to be extendable. But maybe this could even be the realm of additional, optional, possibly 3rd party gems.

For example, if you need to have single sign on via providers like Github, Meta, etc - this will require things like callback routes, managing the tokens issued on the return trip, auth provider API keys, etc.

**Comment by n-studio** [comment]
>  * Sign up
> 
>  * Log in
> 
>  * Log out
> 
>  * A couple helpers to the tune of `current_user`

I think there are other features that are not avoidable such as "reset password", "confirm email", "safe email update".

I'd also advocate to have other security related features all websites should have, such as the ability to discard all existing sessions after a hack recovery.

**Comment by mtimofiiv** [comment]
@n-studio yep, agreed, things like you mentioned would also be important.

**Comment by bparanj** [comment]
Here is my wishlist:

- Auto register
- Login with magic link
- No signup
- No password storing
- No password reset
- No confirm email

If craigslist using Perl can have magiclink login, then in 2024 Rails should be able to accomplish this feature. Here is the requirements documented and functioning [FastAPI project](https://github.com/whythawk/full-stack-fastapi-postgresql)

**Comment by kwhandy** [comment]
@bparanj you mean [passwordless gem](https://github.com/mikker/passwordless/)? we can also do that with rails built-in auth that released in current v7.1 but it needs some effort. this gonna be great if generator has options to do **passwordless** that **force user has valid email before signup**, **sudo** to **protect certain user actions, like cash withdrawal**, also MFA & multi sessions management(cuz why not)

so we can slowly move on from omniauth things, like why we rely user identity to big giants?

**Comment by 1klap** [comment]
I think a default auth generator can do as little as a sessions_controller, a registrations_controller, an authorizable concern and some before hooks in the right places.
I (for myself) extracted the minimal required code into [this gem](https://github.com/1klap/tinytokenauth-rails), this is enough to get started and easy to move on if it needs to be extended.
 ([Release post](https://dev.to/1klap/user-auth-in-rails-without-devise-a-step-into-a-simpler-world-17hi))

**Comment by bparanj** [comment]
The reason I want to replicate FastAPI way of doing this is due to security issues. They have already adopted best security practices for this feature. It is very well thought out with the end to end flow: You see it in their [authentication guide](https://github.com/whythawk/full-stack-fastapi-postgresql/blob/master/docs/authentication-guide.md). 

I glanced over those repos. They don't have much in terms of security. I was thinking something very lightweight:

```ruby
has_magiclink
```

declaration in the model. Bake in the best security practices in this method.

**Comment by brunoprietog** [comment]
It has already been said that a proposal will be submitted. I don't think it's worth discussing things ahead of time.

**Comment by cvalencia1991** [comment]
hello @dhh one way could be implement is using [device](https://github.com/heartcombo/devise) i think could be use full also give a feature to implement OAuth

**Comment by philipithomas** [comment]
A small thing to consider based on my recent auth work:

Magic links don't work with PWAs on iOS. If you click the login link, it always opens in Safari and always log into Safari. The cookies in Safari are separate from the cookies in the PWA. So, it's impossible to get the magic link to open in the PWA. 

I preferred pin-based login over links for this reason.

**Comment by sandergroen** [comment]
Perhaps it is an idea to add something similar like has_secure_password that can store multiple credentials for a user. This way you can have a password and a passkey (or whatever other credential) at the same time.

I once was investigating a simple setup in Rails to do something like this but i could not find a way to use has_secure_password to make something like this to work. I know it is not intended for any use other than passwords but it would be nice to have the functionality to encrypt credentials extracted out of has_secure_password.

A data model like this would be awesome:

```ruby
class User < ApplicationRecord
  has_many :credentials, dependent: :destroy
end

class Credential < ApplicationRecord
  has_credential
  belongs_to :user
end
```

The authentication will become more complex but you will have more authentication options this way.

**Comment by redvoilin** [comment]
> @claudiug That's too much for what I have in mind, but the general direction of using generators instead of engines is correct.

Would it be possible to consider adding a RABC generator in Rails 8?

**Comment by dhh** [comment]
Work has begun on this in https://github.com/rails/rails/pull/52328.

**Comment by dhh** [comment]
Closed via https://github.com/rails/rails/pull/52328.

**Comment by fthobe** [comment]
Hey @dhh , with great appreciation I am following the work you just did on [Bundle Audits](https://github.com/rails/rails/pull/54695), I agree on a lot with you, but the state of Auth on rails in terrifying. 

Let's for a moment assume that best practice would be this: 
- auth is not written by a single developer; 
- a team of skilled people with appropriate seniority review PRs individually; 
- nobody suffers through touching fundamentals of encryption. 

I do not believe that most teams meet those requirements and believe that the fact that rails, different to python, node or lavarel, does not have an either strongly sponsored (nextauthjs) or core team maintained (Laravel) solution for this is a systemic risk. 

I know that this is no popular opinion, but the situation became dire: 
- Devise has seen no significant development in years; 
- Omniauth is doing much better due to @BobbyMcWho ;

But for how long do we want to rely on single individual rolling entire auth stacks for the entire community. 
I am sure if anybody would look realistically into this with a risk analysis nobody really understands what's happening inside devise or omniauth apart from the maintainers themselves right now.

Looking what other frameworks do it is clear that they either come with Auth or have strong corporate backed solutions, we can't afford to not have one. 

|                	| Laravel [(workos)](https://github.com/workos/workos-php-laravel) 	| [Django](https://docs.djangoproject.com/en/5.1/topics/auth/) 	| [Node](https://github.com/nextauthjs) 	|
|----------------	|------------------------------------------------------------------	|--------------------------------------------------------------	|---------------------------------------	|
| Sessions       	| Yes                                                              	| Yes                                                          	| Yes                                   	|
| Basic Auth     	| Yes                                                              	| Yes                                                          	| Yes                                   	|
| Single Sign-On 	| Yes                                                              	| No                                                           	| Yes                                   	|
| Directory Sync 	| Yes                                                              	| No                                                           	| No                                    	|
| MFA            	| Yes                                                              	| No                                                           	| No                                    	|
| Social login   	| Yes                                                              	| No                                                           	| Yes                                   	|
| Roles          	| Yes                                                              	| Yes (Groups)                                                 	| Yes                                   	|

Maybe you @dhh can look into this, you drive large parts of the security topic here and really ask yourself if the current state of auth is a sane default or if something has to be done about it. I believe yes, but I am aware this is not a popular opinion among maintainers here.

**Comment by gregmolnar** [comment]
> but the state of Auth on rails in terrifying

Why do you think that? There are plenty of options for authentication in the Rails ecosystem. There is Devise, it has maintenance issues, but that can be resolved, even though posts like what has been posted to reddit doesn't really motivate folks to work on open-source.
Then there is rodauth is you want something different. There is also authentication-zero and revise-auth if you want a generated solution.
And there is the built-in authentication generator too, that showcases a bunch of useful Rails helpers that one can use for various security related stuff.

```
Shouldn't rails core look into this with more open eyes and maybe consider that we all basically need the same 4 things:

basic auth;
api auth;
social logins;
MFA for any credit card transactions on admin level.
```

I don't think this is that simple. Even the basic authentication can have a wide range of requirements. API auth is the same. Which social logins do you wish to be supported? Who will maintain all of those when they start to break due to changes on the provider side?
What kind of MFA? TOTP, SMS, security key, passkeys? All of them? 
Who will maintain all of the code? Especially given that if someone is not responsive enough, they might see their face on a "Wanted for not merging and responding to issues" poster.

**Comment by fthobe** [comment]
@gregmolnar do you stalk me on github? 

Look, I get your approach, what you do on Github is great, I really mean it. 

But I do not believe auth should be either self rolled nor a one man show repo. 

> I don't think this is that simple. Even the basic authentication can have a wide range of requirements. API auth is the same. Which social logins do you wish to be supported? Who will maintain all of those when they start to break due to changes on the provider side?
What kind of MFA? TOTP, SMS, security key, passkeys? All of them?

All other major frame works had to face the same questions: django took a very conservative approach, laravel a more opinionated one. You are a security researcher, what would you tell any of your customers if they tell you "one guy in the basement writes our auth". 

Yeah, I do have beef with this approach, because the ones praising this strategy are mostly consultants or agencies lacking the responsibility to actually having to warrant security. 

While I in detail try to reply to all your critics, Baden actually tried to interact with them, apart from telling me that there's plenty (all "one-man-shows" or unmaintained) or do it yourself approaches, I haven't seen that you have in any of the conversations contributed in meaningful manor to any of this pain points people that actually have to underwrite an audit have: 

- can I trust my current auth? 
- do I have a sufficient level of audit by multiple people? 
- can I suffice to externally given requirements?

So if your response to that is not "I put my own buttox in the line" with all admiration for your work, the rails comunity on it's own and anybody who contribute time to devise, omniauth or any of the great tools out there, I think you are entirely missing the point and I think most people currently using devise do not know that it's not maintained.

**Comment by gregmolnar** [comment]
> do you stalk me on github?

Nope, I am just subscribed to a few repositories and you happen to have discussions on them. 

> You are a security researcher, what would you tell any of your customers if they tell you "one guy in the basement writes our auth".

I do penetration tests and code audits(although I focus on bug bounties now) and I never ask who writes the code, because that doesn't matter. I don't test Rails apps exclusively and I don't see any difference between Rails or other stacks authentication implementations. Other than some recommended improvements, I rarely find issues with the authentication. 

```
can I trust my current auth?
do I have a sufficient level of audit by multiple people?
can I suffice to externally given requirements?
```
How can you answer yes to these if you use a third-party solution? Do you think Devise ever had a security audit? Do you think that a third-party that satisfies the requirements of everyone would be good and maintainable? Do you really think that ISO27001 and SOC auditors will force you to have a validation for special characters in the passwords? They are reasonable and the requirement is to have strong passwords, not a facade of strong passwords.

> I think you are entirely missing the point and I think most people currently using devise do not know that it's not maintained.

I don't miss your point, but what you are doing on the internet is not gonna help to get Devise maintained. Especially the Reddit post. 

> would you advise your customers right now to use any of the existing auth versions and tell them it's a future safe investment?

There is no such thing as "future safe", things consistently change. During an audit, the tool used doesn't matter, what matters it that the implementation meets certain requirements and that can be achieved with any of the options.

**Comment by buncis** [comment]
open source is not a democracy

**Comment by fthobe** [comment]
@buncis 
> open source is not a democracy

Nobody here assumes that, but I do not believe that contributes to the discussion we are having. 

@gregmolnar 

Man, if just the world would only be composed of projects able to afford security audits. I do think we both agree that people that have audits usually have less problems because they can afford audits. We audit, we also avoid what looks like a hot burning plate of unmaintained dependencies.

**Comment by skipkayhil** [comment]
I'm locking because this issue was created to track work for the basic authentication generator, which has been implemented, and now we're way off topic.
