### ISSUE TITLE
Add browser version guard by default

### ISSUE THREAD

**Issue by dhh** [rails/rails#50445]
To take full advantage of our #nobuild defaults, we need to ensure that developers have easy control over which versions of the major evergreen browsers they intend to support, and guard their application from being accessed by unsupported versions.

This shouldn't take much machinery, as the useragent gem already offers the ability to parse the user agent string, but it needs to be presented with an easy default configuration/initializer setup for setting the guards, and a default screen for serving as a blocker.

**Comment by codergeek121** [comment]
I started with a rough implementation that currently looks like this in an initializer:

```ruby
Rails.application.configure do
  config.browser_guard do |guard|
    guard.require_at_least :chrome, 63
    guard.require_at_least :safari, 16.7
    guard.require_at_least :edge, 89
    guard.require_at_least :firefox, 108
    guard.require_at_least :opera, 76
  end

  config.browser_guard_error_handler = ->(request) {
    Rails.logger.info("#{request.user_agent} blocked from application")
  }
end
```

This will basically configure a middleware and return 503 with a standard error page for Chrome, Safari, Edge, FireFox and Opera with lower versions than the specified ones.

![error](https://github.com/rails/rails/assets/4910785/2479fa61-1a37-478b-ba90-d730db7313a4)

There's a potential to reimplement a lot of browser version mangling similar to browserslist, but I think specifying a minimal version for the big browsers and (maybe?) blocking certain browsers would be enough for most apps that want to use such a middleware.
E.g. in the above config, IE11 would still be able to access the app, because only browsers with a specified minimal version will be blocked. I could introduce a `guard.block_browser(:internet_explorer)` or similar to block certain browsers without specifying a minimal required version.

I'd would love to implement a dry-run feature, similar to CSP report only configurations. That way, an app can deploy a `browser_guard` configuration to production, setup some reporting in the error handler and test a configuration against the actual production traffic without accidentally blocking the app for a lot of users.

**Comment by dhh** [comment]
I like the thinking here. Have some thoughts on the API. Do open a PR and we can collaborate there. You can assign me when opening. Thanks for working on this!

**Comment by dhh** [comment]
Solved via https://github.com/rails/rails/pull/50505.
