### ISSUE TITLE
Setup Kamal by default for new applications

### ISSUE THREAD

**Issue by dhh** [rails/rails#50441]
[Kamal](https://kamal-deploy.org) has given us the power to easily deploy Rails applications anywhere without any commercial entanglements. This should be the default path we recommend for new people getting started with Rails, so it should be configured by default. This basically just means adding kamal to the gemfile by default and running kamal init during setup. You should be able to turn this off using `--skip-kamal`.

**Comment by dhh** [comment]
cc @djmb

**Comment by devcamke** [comment]
Awesome 👍

**Comment by laptopmutia** [comment]
this is great, just wish there is official use case example of only using 1 server

**Comment by brunoprietog** [comment]
If Kamal will be included by default, I think it would be nice if there is an official implementation guide as well, incorporating production level stuff. What would a production level implementation look like?

I'm still very curious how you set up the databases in 37signals. Do you have any tools that automate MySQL backups for example? Maybe using XtraBackup along with something else for retention policy, etc.

I mean, if Rails has a opinionated way of doing so many things, why couldn't you recommend something that works for most users by default? This would make developers feel more confident. Disaster recovery... etc. It would clear up many doubts

**Comment by dhh** [comment]
Would be happy to see someone work on that. But it’s out of scope for this feature to also teach people everything they would ever have to know about running databases in production. Kamal merely facilitates the easy deployment of such systems.

**Comment by brunoprietog** [comment]
I'm glad to hear you're open to that, although there's a problem with just anyone documenting that sort of thing. While I would love to contribute to that, I wouldn't be the right person to do it because I simply don't have the same experience on that scale to recommend one approach over another. One thing is theory and another is the real world that is sustained by years of baggage, which at least at my young age I can't have haha.

I just wanted to show the need and that it would be great if there was some minimal convention or recommended Rails implementation procedure safe enough for most. I don't imagine something too complicated either, maybe [this comment](https://github.com/basecamp/kamal/discussions/106#discussioncomment-5555234) from @jeremy can serve as a starting point for the general idea of the database using Kamal.

Before Kamal the answer for the database was simple, because the implicit default path was just Heroku (or recently Fly.io or Render). But if the path will now be Kamal, what is the answer to that question?

In my case I use Kamal just for the application and PostgreSQL (on a server without Kamal) for my side projects and could not come up with a reliable way to run backups within Kamal and send them to S3. That was the reason that led me to run it separately, using Ansible to automate it, with recurring full and incremental backups with pgBackRest sent to Cloudflare R2 and a retention policy configuration. Just as I found my way, many other people need to solve the same thing for Rails and are reinventing the wheel. I tried the same thing with Percona MySQL to see if I would be able to do it with Kamal, I succeeded but using a custom script and a somewhat more complicated configuration to achieve the same thing. I'm sure there is some simpler way to do it that at least I don't know about at the moment. Ultimately, I imagine the ultimate goal is to describe the entire application infrastructure in Kamal without having to use so many other tools, at least in the beginning when things are simpler.

With the rest, of course I could contribute by making a guide. The question is the final level of detail, ex: mention services like Cloudflare or some low-cost provider like Contabo in the process or not? So I understand that all these nuances have influenced why there is no official guide so far.

I would be happy to contribute if you could give me some baseline guidelines and help me address those little concerns. I really think it would add a lot of value.

This is a very recurrent problem that exists in the community, you just need to read Kamal's Discord to notice it.

**Comment by bparanj** [comment]
Rails as a framework is focused on developer's happiness and productivity. It should not include DevOps Day 2 operations. Providing a great DX is important. I can imagine doing:

```ruby
rails deploy staging
```

or 

```ruby
rails deploy perf
```

to work on performance issues. It just deploys and I can give demos and iterate on the MVP. As a one person framework, it frees up my time in doing time consuming and beyond my skillset DevOps work. Eventually, DevOps team will use Cloud-Init, Ansible, Packer, Terraform etc to deploy to production, setup automated backups etc. As a developer, all I care is deploying as often as I can and iterate on the MVP.

**Comment by dhh** [comment]
@brunoprietog Would love to have a much more in-depth manual for Kamal! If you're up for it, please do pursue that in the kamal repos. Then we can link to those instructions from a Rails tutorial that talks broadly about deployment.

**Comment by Austio** [comment]
I think SSL setup out the box would be a great add here, or at least boilerplate for it commented out.  Figuring that out inside of a real app was painful.

**Comment by dhh** [comment]
Going to solve the SSL question via Thruster 👍

**Comment by dhh** [comment]
Work happening in https://github.com/rails/rails/pull/51798
