### ISSUE TITLE
Add Thruster to Docker setup to get HTTP/2, X-Sendfile, Caching by default in Rails 8

### ISSUE THREAD

**Issue by dhh** [rails/rails#50479]
Puma does not support HTTP/2 out of the box, and there does not seem to be a short-term path to that changing. That means most people have to either stick nginx or a CDN in front of their app, which means more configuration and more moving parts.

As part of developing ONCE #1, we built a tiny, no-config Go-based proxy that sits in front of Puma to provide HTTP/2, public caching, and X-Sendfile setup. You run it by starting it with `airlock puma`, and that's it, you gain those speed upgrades without any hassle. This makes it a great fit for people who just want to run their Rails app off the default Dockerfile and with a minimum of fuss.

**Comment by bparanj** [comment]
How about:

- airstream
- airboost
- aircache

**Comment by vovimayhem** [comment]
ozzmosis :)

**Comment by northeastprince** [comment]
@dhh what's the timeline for it being open-sourced?

**Comment by dhh** [comment]
Oh, this also supplies gzip compression AND SSL certificate handling through Lets Encrypt. It's gonna be great!

**Comment by bparanj** [comment]
Just curious why are we still using Rack? Why not use [ASGI](https://asgi.readthedocs.io/en/latest/)?

**Comment by northeastprince** [comment]
Because Rails isn't a Python framework? 😆

**Comment by dhh** [comment]
Correct, same container. Meaning you won't need another container to connect your app to the internet with the performance measurements in place.

**Comment by brendanh-katalyst** [comment]
How about "Porthole" as a name?

**Comment by northeastprince** [comment]
It might not be mature enough to be the new default, but [Falcon](https://github.com/socketry/falcon) has built-in HTTP/2 support - it might be worth considering a move from Puma.

**Comment by samgranieri** [comment]
@dhh how will this be different than using Caddy, which is written in Go and has excellent AMCE integration built in. I've had success using Caddy with Step-CA. https://smallstep.com/blog/private-acme-server/

**Comment by dhh** [comment]
It's no config (literally, there's no config file). Focused on far fewer features. Caddy is great, but not appropriate at all as a default.

**Comment by leehericks** [comment]
> It might not be mature enough to be the new default, but [Falcon](https://github.com/socketry/falcon) has built-in HTTP/2 support - it might be worth considering a move from Puma.

I was going to say the same thing. I wish people would push the Ruby concurrency story as hard as Samuel @ioquatix has been (fiber scheduler) and work to optimize his Falcon server, built on top of his async and async-http gems, rather than bailing to other languages.

https://rubykaigi.org/2022/presentations/ioquatix.html
https://github.com/socketry/async

I guess you have to go with what's available now.

**Comment by ioquatix** [comment]
If it helps, I think Falcon will be stable (v1.0 release) by the end of this year. Since we are talking about HTTP standards, one goal is to land HTTP/3 support before then. While I'd generally still recommend using a load balancer on any major application, I have actually been running Falcon in a small production system for several years now directly facing the internet (supporting both HTTP/1 and 2). In Rails 7.1 there are some caveats to using Falcon (ActiveRecord being one of the biggest), however they are not unsolvable problems and the vast majority have either been solved already or are in the process of being solved. In summary, while putting a proxy in front of Puma may solve some of the performance issues (while potentially introducing others), it doesn't significantly change the concurrency of Rails itself, and thus from an application point of view is less exciting (which is a valid goal too). Falcon improves on performance, while also exposing new opportunities to the application layer (streaming, WebSockets, etc).

**Comment by dhh** [comment]
Work happening in https://github.com/rails/rails/pull/51793.

**Comment by dhh** [comment]
This will actually get sorted by Kamal 2's new proxy instead.
