### ISSUE TITLE
Add DB-backed Action Cable adapter as new default in Rails 8

### ISSUE THREAD

**Issue by dhh** [rails/rails#50480]
Out of the box, Action Cable will only work with a single process setup using the in-memory adapter. If you run multiple processes, let alone multiple app servers, you have to add Redis to the mix or be running PostgreSQL. Redis is great, but it's another moving part, and PostgreSQL is also lovely, but it's only one out of our 3 supported databases. Action Cable should work with multiple processes out of the box regardless of which of the supported databases you use.

For ONCE #1, we built a tiny Active Record-based cable adapter, which works for both MySQL and SQLite. Plan is to extract this and add it in as the new default.

**Comment by northeastprince** [comment]
Does this mean that you figured out how to completely drop Redis from ONCE?

**Comment by vovimayhem** [comment]
Hey I tried Postgres a couple year ago as backend for ActionCable /Hotwired, and a big caveat is that there's a limit on the size of the notification, that if the HTML is carelessly high (which was common when working with Tailwind), it all starts breaking... maybe a warning when the rendered HTML exceeds the size limit perhaps?

**Comment by RyanVasichko** [comment]
> Hey I tried Postgres a couple year ago as backend for ActionCable /Hotwired, and a big caveat is that there's a limit on the size of the notification, that if the HTML is carelessly high (which was common when working with Tailwind), it all starts breaking... maybe a warning when the rendered HTML exceeds the size limit perhaps?

@vovimayhem - this is due to Postgres' 8KB limit on the size of the payload when using SUBSCRIBE/NOTIFY, which is what the ActionCable Postgres adapter uses. I'm guessing that the new database-backed ActionCable adapter will use polling like SolidQueue does so this won't be an issue.

**Comment by drale2k** [comment]
> > Hey I tried Postgres a couple year ago as backend for ActionCable /Hotwired, and a big caveat is that there's a limit on the size of the notification, that if the HTML is carelessly high (which was common when working with Tailwind), it all starts breaking... maybe a warning when the rendered HTML exceeds the size limit perhaps?
> 
> @vovimayhem - this is due to Postgres' 8KB limit on the size of the payload when using SUBSCRIBE/NOTIFY, which is what the ActionCable Postgres adapter uses. I'm guessing that the new database-backed ActionCable adapter will use polling like SolidQueue does so this won't be an issue.

Additionally when using page refreshes with Turbo 8 this should be even less of an issue

**Comment by brunoprietog** [comment]
I opened #49903 to address the PostgreSQL adapter limit, in theory it's ready to merge but nothing has happened yet

**Comment by washu** [comment]
I built an adapter for rails 6 using mongodb and watch operation on the colkection. Woukd the api be more flexible to add your own adapter?

**Comment by ArglosStudios** [comment]
> For ONCE https://github.com/rails/rails/issues/1, we built a tiny Active Record-based cable adapter, which works for both MySQL and SQLite. Plan is to extract this and add it in as the new default.

We have bought a license for campfire (great chat product btw). Checking the code, I still see the redis adapter for cable. I assume it will be coming later (campfire 1.x > ), correct?

In addition, did you see any big performance hits against using redis vs polling sqlite during once#1 tests?

**Comment by dhh** [comment]
We ended up using Redis anyway for Campfire because we wanted it for transient caching, so then it made sense to use it for Action Cable as well, since it's more efficient. But would ALSO like to see an action cable adapter for sqlite ship in the box. So nobody should need Redis.

**Comment by dbackeus** [comment]
WRT the Postgres NOTIFY size limit. This is fully handled by the [actioncable-enhanced-postgresql-adapter](https://github.com/reclaim-the-stack/actioncable-enhanced-postgresql-adapter) gem which extends Rails's built in Postgres adapter to handle large payloads via a dedicted table, adhering to the suggested best practice in [Postgres documentation](https://www.postgresql.org/docs/current/sql-notify.html):

> In the default configuration it must be shorter than 8000 bytes. (If binary data or large amounts of information need to be communicated, it's best to put it in a database table and send the key of the record.)

**Comment by brunoprietog** [comment]
Oops sorry, I haven't had enough time to make progress on the PR, I think this weekend I can address the comments and move forward with the compression. I think that's enough for most people honestly, in fact, it was mentioned in the discussion that it's not so good to transmit such long strings either, and with Turbo's page refreshes it will be even less necessary.

**Comment by washu** [comment]
Here is a mongoid one
https://gist.github.com/washu/a2b5415e7b9a538fe782d32ff5bb9109

**Comment by nickhammond** [comment]
Is there a PR for this yet? I noticed the solid_cable gem is utilizing this approach, just started testing it with a project. https://github.com/npezza93/solid_cable

**Comment by dhh** [comment]
Oh, Solid Cable looks interesting. Would need to do some SOLID BENCHMARKING to make sure such a straight implementation is performant enough. But glad someone is taking a stab at it! It's silly for us to need Redis just for Action Cable.

**Comment by npezza93** [comment]
@dhh I can work on some benchmarks and report back to see if it's worth upstreaming into a pr.

**Comment by dhh** [comment]
That would be great, @npezza93! Thanks for working on this.

**Comment by npezza93** [comment]
All right ran some benchmarks. I used https://k6.io/ along with a plugin from Evil Martians to make testing websockets easier. (See https://evilmartians.com/chronicles/real-time-stress-anycable-k6-websockets-and-yabeda for more info).

Heres the load testing script i used:

<details>
  <summary>JS Script</summary>
 <code><pre>
import { check, sleep, fail } from "k6";
import cable from "k6/x/cable";
import { randomIntBetween } from "https://jslib.k6.io/k6-utils/1.1.0/index.js";
import { Trend } from "k6/metrics";

let rttTrend = new Trend("rtt", true);

const WS_URL = __ENV.WS_URL || "ws://localhost:3000/cable";
const WS_COOKIE = __ENV.WS_COOKIE; // we need a valid cookie to authorize request
const MAX = parseInt(__ENV.MAX || "20");
// Total test duration
const TIME = parseInt(__ENV.TIME || "90");
const MESSAGES_NUM = parseInt(__ENV.NUM || "5");

export let options = {
  thresholds: {
    checks: ["rate>0.9"],
  },
  scenarios: {
    ping: {
      // We use ramping executor to slowly increase the number of users during a test
      executor: "ramping-vus",
      startVUs: (MAX / 10 || 1) | 0,
      stages: [
        { duration: `${TIME / 3}s`, target: (MAX / 4) | 0 },
        { duration: `${(7 * TIME) / 12}s`, target: MAX },
        { duration: `${TIME / 12}s`, target: 0 },
      ],
    },
  },
};


export default function () {
  const client = cable.connect(WS_URL, { cookies: WS_COOKIE, receiveTimeoutMS: 60000 });

   if (!check(client, { "successful connection": (obj) => obj })) {
    fail("connection failed");
  }

  const channel = client.subscribe("BroadcastChannel", {});
  if (!check(channel, { "successful subscription": (obj) => obj })) {
    fail("failed to subscribe");
  }

  for (let i = 0; i < MESSAGES_NUM; i++) {
    let startMessage = Date.now();
    channel.perform("ping", { message: `Hello ${i}` });

    let message = channel.receive();
    if (!check(message, { "received res": (obj) => obj.message === `pong Hello ${i}` })) {
      fail("expected message hasn't been received");
    }

    let endMessage = Date.now();
    rttTrend.add(endMessage - startMessage);

    sleep(randomIntBetween(5, 10) / 10);
  }

  // Terminate the WS connection
  client.disconnect();
}
</pre></code>
</details>

I ran this against a real domain using ssl and it was run on Digital Ocean with 1 premium intel cpu and 2 gb ram.

The gist of the load test is that the connection subscribes to the BroadcastChannel which sets up a stream for a uuid thats set for the connection, we then sends out 5 messages to that channel, and measure how long it takes to get the return message(rtt).

I first ran the test against redis as the adapter with varying amounts of Virtual Users to compare against.

@dhh Let me know if theres any other benchmarks i should run or what you think about these benchmarks!

### Redis

50 VUs
<img width="1083" alt="Pasted Graphic 23" src="https://github.com/rails/rails/assets/5059927/db6f37a3-93d7-4358-8658-4d162fb46001">

100 VUs
<img width="1097" alt="Pasted Graphic 22" src="https://github.com/rails/rails/assets/5059927/55e8063c-a75c-4e71-b0b8-8a20372d8e9d">

250 VUs
<img width="1078" alt="Pasted Graphic 3" src="https://github.com/rails/rails/assets/5059927/ac363f37-f8f4-4aa1-9982-6278ff546f97">

500 VUs
<img width="1111" alt="Pasted Graphic" src="https://github.com/rails/rails/assets/5059927/7acbd06b-6019-4d54-b283-d0475e03926b">

750 VUs
<img width="1129" alt="Pasted Graphic 4" src="https://github.com/rails/rails/assets/5059927/ae2e8099-2938-42ac-a0c3-3946124cdecf">

1000 VUs
<img width="1108" alt="Pasted Graphic 1" src="https://github.com/rails/rails/assets/5059927/b87c27c3-eea2-4e60-9d01-8b166f4471fc">

1500 VUs
<img width="1095" alt="Pasted Graphic 5" src="https://github.com/rails/rails/assets/5059927/4cd58c08-c04f-4092-8065-d623a8a2d02c">

### Solid Cable

Then i ran against solid cable using sqlite with the few patches described in https://github.com/rails/rails/pull/51958#issuecomment-2146881692 on rails main. I varied the polling interval to also see what would happen.  

50 VUs

0.2 seconds polling interval
<img width="1118" alt="Pasted Graphic 26" src="https://github.com/rails/rails/assets/5059927/0a9d3cab-c47a-432e-97f5-f07790c96b9e">

0.1 seconds polling interval
<img width="1138" alt="Pasted Graphic 25" src="https://github.com/rails/rails/assets/5059927/04931990-daf7-409a-acac-f88a070bba53">

0.01 seconds polling interval
<img width="1127" alt="Pasted Graphic 24" src="https://github.com/rails/rails/assets/5059927/25cee664-27b3-4a4f-b8d6-c8908f483a97">


100 VUs
0.2 seconds polling interval
<img width="1101" alt="Pasted Graphic 11" src="https://github.com/rails/rails/assets/5059927/48f6949c-9746-4351-8409-c8ac6f687bcc">

0.1 seconds polling interval
<img width="1112" alt="Pasted Graphic 12" src="https://github.com/rails/rails/assets/5059927/5c48319b-fd3d-4cfa-b763-ad4f9180140a">

0.01 seconds polling interval
<img width="1076" alt="Pasted Graphic 18" src="https://github.com/rails/rails/assets/5059927/f93e0a05-e7a2-4dd9-8eec-8fc3bed74bbe">


250 VUs
0.2 seconds polling interval
<img width="1139" alt="Pasted Graphic 6" src="https://github.com/rails/rails/assets/5059927/5f510a57-5fa9-4f1c-88a1-4feda4bf6837">

0.1 seconds polling interval
<img width="1113" alt="Pasted Graphic 13" src="https://github.com/rails/rails/assets/5059927/3018a518-55af-4c23-806b-50573e54f57a">

0.01 seconds polling interval
<img width="1110" alt="Pasted Graphic 19" src="https://github.com/rails/rails/assets/5059927/3dc3ad33-d339-485b-a82c-8f9f990e8401">


500 VU
0.2 seconds polling interval
<img width="1119" alt="Pasted Graphic 7" src="https://github.com/rails/rails/assets/5059927/9e3b4c95-b125-4d34-a38c-f73ae96e9fcc">

0.1 seconds polling interval
<img width="1113" alt="Pasted Graphic 14" src="https://github.com/rails/rails/assets/5059927/3ca139b3-72f8-43f2-9ca1-e1781aac1304">

0.01 seconds polling interval
<img width="1100" alt="Pasted Graphic 20" src="https://github.com/rails/rails/assets/5059927/cd382147-4d30-4cf9-b2a6-28a19985cbf2">


750 VUs
0.2 seconds polling interval
<img width="1096" alt="Pasted Graphic 8" src="https://github.com/rails/rails/assets/5059927/b4a734ba-665c-461c-8b85-dce5981fe9af">

0.1 seconds polling interval
<img width="1118" alt="Pasted Graphic 15" src="https://github.com/rails/rails/assets/5059927/3aca8c5b-cf22-4e75-8c41-8f391d397125">

0.01 seconds polling interval
<img width="1119" alt="Pasted Graphic 21" src="https://github.com/rails/rails/assets/5059927/4700467d-e0a3-4391-b7a2-204f7dd88253">


1000 VUs
I didnt run these with 0.01 polling interval since we were starting to not see any benefit
0.2 seconds polling interval
<img width="1104" alt="Pasted Graphic 9" src="https://github.com/rails/rails/assets/5059927/41e1b376-44a1-49e4-b378-35fd36211597">

0.1 seconds polling interval
<img width="1072" alt="Pasted Graphic 16" src="https://github.com/rails/rails/assets/5059927/77914b80-b5e2-4fd7-a7be-4db99cce52c9">


1500 VUs
0.2 seconds polling interval
4 connections didnt recieve messages back. Honestly less than i expected
<img width="1076" alt="Pasted Graphic 10" src="https://github.com/rails/rails/assets/5059927/c3fc4dbe-6474-4002-81c3-085f37366068">

0.1 seconds polling interval
1 connection failed
<img width="1048" alt="Pasted Graphic 17" src="https://github.com/rails/rails/assets/5059927/a5b2abed-d82f-40e3-8c52-60892155e094">

**Comment by ArglosStudios** [comment]
checking these results seems like solid cable takes twice the rtt of when using redis, correct ?

**Comment by npezza93** [comment]
Yea, for the most part

**Comment by ArglosStudios** [comment]
yep that is good enough, any idea on memory/cpu utilization during the tests? I wonder if there was any backpressure

**Comment by npezza93** [comment]
CPU for all the tests(solid cable and redis) never went above 75%
<img width="1057" alt="image" src="https://github.com/rails/rails/assets/5059927/360351e5-0716-47fd-87f8-a7a7f8703ad9">

As for memory, looks like DO didnt capture it by default and i forgot to enable it. I can enable enhanced metrics and run a few of the load tests again to see what that looks like.

**Comment by npezza93** [comment]
With 750 VUs heres what memory looked like:
Pretty much the same for both. 

Both tests:
<img width="1017" alt="image" src="https://github.com/rails/rails/assets/5059927/4fe9ed64-3cae-42d3-bf52-0a55f668d34a">

**Comment by washu** [comment]
Nick could you add https://github.com/washu/solid_cable_mongoid to you test harness, thats your soldi cable using mongoid instead of sqlite. i already did a solid cache with mongoid and perf is about on par

**Comment by npezza93** [comment]
Well this is awkward. I forgot an index which turns out makes a huge difference 😅 

Seems like running the prune action on disconnect causes a bunch of slowdown so it be worth running it in a job periodically instead. 

### SolidCable with SQLite with 0.05 polling interval and pruning disabled. 
On the higher end solid cable ends up being about the same as redis.

100 VUs
<img width="1150" alt="image" src="https://github.com/rails/rails/assets/5059927/79296ed0-eb26-4ca9-9d23-8d2640208e50">

250 VUs
<img width="1106" alt="image" src="https://github.com/rails/rails/assets/5059927/6814ecfb-7430-49d5-ae1c-fa7167403f35">

500 VUs
<img width="1087" alt="image" src="https://github.com/rails/rails/assets/5059927/917bc425-086e-4921-908f-9288390a0953">

750 VUs
<img width="1059" alt="image" src="https://github.com/rails/rails/assets/5059927/e9af1a72-dcb5-46f3-8035-eee6f696200b">

1000 VUs
<img width="1072" alt="image" src="https://github.com/rails/rails/assets/5059927/ea953595-6c90-456a-9352-68586333b1d5">

### SolidCable with SQLite with 0.05 polling interval and pruning enabled. 

100 VUs
<img width="1105" alt="image" src="https://github.com/rails/rails/assets/5059927/d1bb48e4-af6c-4f11-ad3d-86b7a697acb9">

250 VUs
<img width="1128" alt="image" src="https://github.com/rails/rails/assets/5059927/3230d298-8bd1-4d21-8e19-50b719ed4952">

500 VUs
<img width="1137" alt="image" src="https://github.com/rails/rails/assets/5059927/134963e0-745d-4c89-8d06-03d578af986e">

750 VUs
<img width="1133" alt="image" src="https://github.com/rails/rails/assets/5059927/7ea75d0c-c517-4237-88b8-d133de80cce7">

1000 VUs
<img width="1111" alt="image" src="https://github.com/rails/rails/assets/5059927/4cede72f-a84e-4c0e-bcad-de704ba44181">

### SolidCable with MYSQL with 0.05 polling interval and pruning disabled where mysql is on a hosted DO instance

100 VUs
<img width="1114" alt="image" src="https://github.com/rails/rails/assets/5059927/442d7b15-1df3-4495-ae6c-54e167efc996">

250 VUs
<img width="1119" alt="image" src="https://github.com/rails/rails/assets/5059927/2c7a05ee-27a9-4f42-9972-71f49f01c271">

500 VUs
had 2 connection breakdowns
<img width="1126" alt="image" src="https://github.com/rails/rails/assets/5059927/c8de515c-b5ae-4068-8d68-25db22cfc4a0">

### SolidCable with MYSQL with 0.1 polling interval and pruning disabled where mysql is on same machine as server inside docker

100 VUs
<img width="1133" alt="image" src="https://github.com/rails/rails/assets/5059927/d43a8140-e981-48c6-a401-24932c390ffb">

250 VUs
<img width="1119" alt="image" src="https://github.com/rails/rails/assets/5059927/dd5800a0-ed64-4946-9651-299c20ff6e6d">

500 VUs
<img width="1110" alt="image" src="https://github.com/rails/rails/assets/5059927/fb25ea04-5d5d-4038-b741-82b25c7badbb">

**Comment by npezza93** [comment]
Tweaking pumas worker_timeout and `config.action_cable.worker_pool_size` resolved mysqls connection timeouts

**Comment by koenhandekyn** [comment]
> Out of the box, Action Cable will only work with a single process setup using the in-memory adapter. 

I'm a bit puzzled here. Why is the single process setup mentioned as a constraint for the async adapter (i'm assuming you are referring to the async adapter)? 

When one is running with SQLITE (single server, still optionally multi process), for ONCE like use cases, i'm not seeing a huge value add of persisting. When the single server goes down, it goes down, having the action cable messages persisted won't bring a lot of value to the table, on the contrary, it might even cause surprises the moment the server comes up again. 

So my thinking is that a production quality in-memory adapter does make a lot of sense for some common deployment models (the ONCE style single server deployments), and running multiple processes (e.g. puma) doesn't seem to interfere with that in my understanding?

I actually started using async in production for such a use case. (now it says "The async adapter is intended for development/testing and should not be used in production.") Maybe the current 'development' implementation is good enough and maybe the documentation can be refined to clarify in which deployment architectures it could be considered?

The main concern seems to be scalability related to the GIL but i'm no sure that for many lower volume scenarios that would actually be a concern and more fundamentally, that a db backed adapter would be more scalable in that single node setup.

**Comment by washu** [comment]
mysql is being used as a braodcasting mechanism, instead of say redis.. its a reduction of your stack.. you already have a db connection, so why redis ontop when the db can be your message queue

**Comment by npezza93** [comment]
@dhh Any thoughts here on the benchmarks and if we should move forward with this approach?

**Comment by dhh** [comment]
Thanks for your work on this! Still interested in pursuing it, but had some specific questions about implementation that I need @djmb to free up on his Kamal 2 work before we can answer. So will have to hold a little longer.

**Comment by npezza93** [comment]
No problem! Thanks @dhh!

**Comment by dhh** [comment]
Happening here: https://github.com/rails/rails/pull/52889
