### ISSUE TITLE
Clarification on button_to Default Behavior in Rails 7.0

### ISSUE THREAD

**Issue by yin0110** [rails/rails#50801]
Hello,

I'm updating to Rails 7.0.8 and noticed a change in button_to method behavior regarding the HTTP verb used. The Rails 7.0 release notes suggest button_to uses PATCH for persisted Active Record objects, contrasting the Rails API documentation which indicates POST as the default. Could you clarify this behavior, specifically the conditions under which button_to defaults to PATCH in Rails 7.0?

Steps to reproduce: 
```
<%= button_to 'add_news', new_admin_news_path,  class: 'btn btn-primary' %>
```
without setting method.

Expected behavior: 
Expected this behavior would be PATCH, as document said.
![截圖 2024-01-19 下午3 18 44](https://github.com/rails/rails/assets/95560433/3bcca04d-4140-456e-9184-cce5b0c2cff2)

Actual behavior: 
I got POST instead. As rails API document said.
![截圖 2024-01-19 下午3 21 23](https://github.com/rails/rails/assets/95560433/dd24e8fb-69db-4ac1-bf8e-6982db98f4b7)

System configuration: Rails Version: 7.0.8 

Thank you.

**Comment by 3v0k4** [comment]
`button_to` is defined in [`ActionView::Helpers::UrlHelper`](https://github.com/rails/rails/blob/main/actionview/lib/action_view/helpers/url_helper.rb#L295).

The `method` is calculated with:

```ruby
 method     = (html_options.delete("method").presence || method_for_options(options)).to_s
```

which means use what was specified explicitly in the `html_options` or delegate to `method_for_options`:

```ruby
        def method_for_options(options)
          if options.is_a?(Array)
            method_for_options(options.last)
          elsif options.respond_to?(:persisted?)
            options.persisted? ? :patch : :post
          elsif options.respond_to?(:to_model)
            method_for_options(options.to_model)
          end
        end
```

In other words, it's `patch` if the object is persisted and `post` otherwise.

---

What you say is incorrect. When you pass:

```ruby
<%= button_to 'add_news', new_admin_news_path,  class: 'btn btn-primary' %>
```

the options argument (`new_admin_news_path`) is not persisted, so it will generate a `post`, which is documented as "The form submits a POST request by default."

Though, you may have a point in saying that the docs could mention the behaviour with the persisted object.

**Comment by 3v0k4** [comment]
You are welcome. Happy to hear that the breakdown was useful.

You may want to read [Contributing to the Rails Documentation](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation). If the Rails team is interested in having this documented, you could take care of it!

**Comment by rafaelfranca** [comment]
Yeah, it would be great to have it documented. I'm closing this issue because things are documented, but please do send a PR if you want to
