### ISSUE TITLE
Rails 7.1 doesn't render Enumerator in view correctly

### ISSUE THREAD

**Issue by kuwabarahiroshi** [rails/rails#50930]
Prior to Rails 7.1, returning an Enumerator in a view rendered the content correctly. However, starting from Rails 7.1, it appears to render only the Enumerator's string representation (Enumerator#to_s), resulting in a response like `"#<Enumerator:0xXXXXXX>"`.

Setting `self.response_body = Enumerator.new` in an action works for both 7.0 and 7.1 (fixed in https://github.com/rails/rails/issues/49588).

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "rails", "~> 7.0.0" # => works
  gem "rails", "~> 7.1.0" # => fails
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "enumerator_in_action", controller: :test
    get "enumerator_in_view", controller: :test
  end
end

class TestController < ActionController::Base
  def enumerator_in_action
    self.response_body = Enumerator.new do |buff|
      10.times { buff << _1.to_s }
    end
  end

  def enumerator_in_view
    render inline: <<~EOS, layout: false, type: :ruby
      Enumerator.new do |buff|
        10.times { buff << _1.to_s }
      end
    EOS
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_enumerator_in_action
    get "/enumerator_in_action"
    assert_equal "0123456789", last_response.body
  end

  def test_enumerator_in_view
    get "/enumerator_in_view"
    assert_equal "0123456789", last_response.body
  end

  private

    def app
      Rails.application
    end
end
```

### Expected behavior

The content should be rendered by evaluating the Enumerator.

I'm not sure whether it is guaranteed behavior in specification when it's returned from view, but I expect it works as was the case until Rails 7.0.

### Actual behavior

It currently renders the Enumerator's string representation, such as "#<Enumerator:0xXXXXXX>".

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.2.2

**Comment by julik** [comment]
We are facing a similar issue with https://github.com/cheddar-me/rails-twirp at the moment - our rendering assigns the return value of the view to an instance variable via the ActionController rendering mechanics, but that return value is actually a `Proto::Message` - not a rendered string. This happens due to this bit in ActionView actually:

https://github.com/rails/rails/blob/f14401aa17c02cfad2213b5bb92a650f43ee4b86/actionview/lib/action_view/template.rb#L275

There is a forced string conversion that has been added with `&.to_s` - since there is no specification on _what_ `render` must return or set exactly (what type) I wonder what the reasoning was for this change. For us this works correctly on 7.0x but broke on 7.1 and the only thing I could imagine we could do is subclass `ActionView::Template`

@eileencodes was there any decision made we should be aware of that "anything that renders must return strings or else" by any chance?

**Comment by kuwabarahiroshi** [comment]
As a result of `git bisect`, the first commit that introduced this issue was https://github.com/rails/rails/commit/4e8e82829182cc2c1dc07997acc210bc0656eda4.

**Comment by julik** [comment]
Oh - thank you for the bisect @kuwabarahiroshi Interesting! @byroot could you help us out figuring out whether the forced stringifiement was intentional and is now a core ActionView expectation? Because it would mean that anything renderable must render strings 🤔

**Comment by byroot** [comment]
> whether the forced stringifiement was intentional and is now a core ActionView expectation?

It kinda is yes. At least when there is multiple templates involved.

But I'll try to find some time to have a look if we could keep supporting the case outlined in the repro script (a single template that returns something responding to `:each`).

**Comment by julik** [comment]
That would be unfortunate because it means that it becomes impossible for a template to set a pre-filled object somewhere for later manipulation. While it will work for an enumerator, I wonder whether there should be a hook someplace where non-serialized rendered outputs could be accommodated. For example, in our library we generate a proto message and then either embed it inside another or manipulate it in some way (using `after` of the controller and similar). One could say this is a corner case, but at the same time - ActionView used to allow this, and the behaviour changed. If we want to do some manipulation on protos for instance, we would then need to unmarshal them and then change them. Besides, protos are not streaming - so would be even less efficient 😢  Could there be a way to bypass the buffer path?

**Comment by byroot** [comment]
As I said I'll have a look. In the meantime what would be useful would be to provide a repro script so I can see how hard it would be to restore that capability without losing the perf gains.

Unless of course the already provided `Enumerator` example is representative enough of your use case.

**Comment by kuwabarahiroshi** [comment]
In my case, the real use case is to render CSV in view and returning as a streaming response.

```ruby
# controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @records = Record.all
  end
end

# views/records/index.html.erb
# providing paginated view for html format
<% @records.page(params[:page]).each do |r| %>
  <%= r.id %>
<% end %>

# views/records/index.csv.ruby
# providing all records for CSV format in streaming response
headers['Content-Disposition'] = "attachment; filename=records.csv"
Enumerator.new do |buff|
  @records.find_each do |r|
    buff << CSV.generate_line([r.id, r.name])
  end
end
```

In this case, it'll be covered by @byroot 's proposal (a single template that returns something responding to `:each`)
