### ISSUE TITLE
Enums should accept a proc for `default`

### ISSUE THREAD

**Issue by ldlgds2** [rails/rails#50965]
### Steps to reproduce
Trying to define a flexible (hence a lambda) default for an enumeration on a model.
 
```ruby
enum status: STATUSES.keys, _default: -> { account.in?(%i[superadmin admin]) ? :to_validate : :validated }
```

### Expected behavior
It should take into account the attribute of the current model instance.

### Actual behavior
```ruby
NoMethodError:
        undefined method `account' for User:Class
        Did you mean?  accounts
```

### System configuration
**Rails version**: 6.1.7.6

**Ruby version**: 3.1.4

I would love to contribute by submitting a PR for this.

**Comment by nvasilevski** [comment]
Hey @ldlgds2, thanks for the report!

There are a few things I wanted to note.
First of all it looks like the `_default` option is not publicly documented which usually implies it is reserved for Rails itself and not intended for application's use. Also the name starting with an underscore `_` often implies the same.

Which means we need to be treating this case as a feature proposal and feature proposals should be discussed on other platforms (Discord, [discourse](https://discuss.rubyonrails.org/)) as github issues tracker is reserved for bug reports only.

I should also note that since most likely it's going to be a new feature it won't be released in a patch version and certainly won't be backported to Rails 6.

Let me know if you'd like to work on a proposal. If the change is relatively simple to make it could just be a pull request. I haven't though deeply enough about this but I think one of the possible APIs is for the proc to receive an instance as an argument, like: `default: -> (user)  { account.in?(%i[superadmin admin]) ? :to_validate : :validated }`

**Comment by skipkayhil** [comment]
> First of all it looks like the `_default` option is not publicly documented which usually implies it is reserved for Rails itself and not intended for application's use. Also the name starting with an underscore `_` often implies the same.

Just to note: underscored options are expected when an `enum` is defined using keywords arguments so that the arguments defining the `enum` name(s) can be separated from the options. Since I agree that this is incredibly confusing, I opened a PR to deprecate the keywords argument style #50987

**Comment by nvasilevski** [comment]
>underscored options are expected

Ah, right, thanks for clarifying 👍 And also I overlooked the fact that `default:` option is documented 
https://github.com/rails/rails/blob/f0d433bb46ac233ec7fd7fae48f458978908d905/activerecord/lib/active_record/enum.rb#L51
If I'm following the code correctly, `default:` eventually gets passed to the `attribute` definition which makes me think this issue is very similar to 
https://github.com/rails/rails/issues/50961#issuecomment-1925794170
