### ISSUE TITLE
Sidekiq ActiveJob adapter resets provider_job_id on with retry_job

### ISSUE THREAD

**Issue by nhorton** [rails/rails#51003]
### Issue
The `retry_job` method on ActiveJob jobs is basically a wrapper for `enqueue`. Enqueue for Sidekiq just calls the factory for wrapping the ActiveJob job in a Sidekiq JobWrapper. (See
https://github.com/rails/rails/blob/babad404a9ae563fff7aa624859845772a4de4b6/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb#L22).

The issue is that when that happens, it is effectively a completely new Sidekiq job. Several of the attributes of the originating ActiveJob instance get passed into a `set` on that Sidekiq job, but the provider_job_id is not one of them.

### Expected behavior
`retry_job` should result in the job having the same `provider_job_id` as it did before the retry.

### Actual behavior
'retry_job' results in a change to the `provider_job_id` every time.

### System configuration
**Rails version**:
7.1.2

**Ruby version**:
3.2.2

**Comment by nhorton** [comment]
Two quick notes: 

- I would be up for trying to fix this, but want to make sure it is accepted as a bug before doing the work there.
- The impact of this is largely that you can't track jobs. ActiveJob itself doesn't expose an API for checking on jobs, so one has to use the backing service. Having this ID change all the time means that one cannot ever look up an ActiveJob job.

**Comment by bensheldon** [comment]
I'm fairly certain all of the Active Job adapters that are bundled with Rails have this problem and have always had this problem since they were introduced.

I'm the author of GoodJob. I'll share how GoodJob addresses this in the hope that it's helpful. GoodJob handles it in the job backend:

- When executing a job, GoodJob puts that job's details (`job_id`, `job_provider_id`,etc.) into the local thread context
- If a job is enqueued through Active Job, [GoodJob checks if the `job_id` being enqueued matches the current thread context's executing job](https://github.com/bensheldon/good_job/blob/131e0cc8cfca183b736d5bdab1e348a8801cea21/lib/good_job/engine.rb#L18-L30) as an indicator that the job is being retried and handles that differently
- GoodJob has a bunch of [workarounds to capture the exact circumstances of what happened](https://github.com/bensheldon/good_job/blob/131e0cc8cfca183b736d5bdab1e348a8801cea21/lib/good_job/engine.rb#L18-L30): whether the job is retried, retry-stopped (all retries have been exhausted), or discarded.

I'm not sure what API is available within Sidekiq to trigger a retry state; the job passed back by Active Job to the adapter's enqueue method on retry contains an `error` and `job_provider_id` attribute which is sufficient (though not amazing) to indicate "hey, this job already exists in the job backend and is being retried because of an error". 

Also, of "things I learned along the way" the retry's enqueue happens before the current job's Active Job execution wrapper finishes (and can be manually invoked too in the middle of a job's perform, even multiple times), so there is some necessary asynchronicity to be aware of.

**Comment by nhorton** [comment]
@bensheldon - thanks for that. The logic here is excellent, and the point about "the old job is running while the new is enqueued" is a point taken.
