### ISSUE TITLE
Array primary keys (e.g. composite) break `collection_singular_ids` method when using preload

### ISSUE THREAD

**Issue by Slotos** [rails/rails#51129]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  self.primary_key = [:id]
  has_many :comments
end

class Comment < ActiveRecord::Base
  self.primary_key = [:id]
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments.create!

    assert_equal 1, post.comments.count
    assert_equal 1, Comment.count
    assert_equal post.id, Comment.take.post.id

    assert_equal Comment.ids, Post.take.comment_ids
    assert_equal Comment.ids, Post.preload(:comments).take.comment_ids
  end
end
```

### Expected behavior

`collection_singular_ids` should work the same when preloading or not.

### Actual behavior

Preloaded associations' `collection_singular_ids` returns an array of `nil` values when association was preloaded.

### Analysis

The problem lies in different handling of array arguments to `Enumerable#pluck` and `ActiveRecord::Relation#pluck`:

```ruby
      def ids_reader
        if loaded?
          target.pluck(reflection.association_primary_key) # -> Enumerable#pluck
        elsif !target.empty?
          load_target.pluck(reflection.association_primary_key) # -> Enumerable#pluck
        else
          @association_ids ||= scope.pluck(reflection.association_primary_key) # -> ActiveRecord::Relation#pluck
        end
      end
```

`ActiveRecord::Relation#pluck` efectively flattens its arguments in `#arel_columns` call, whereas `Enumerable#pluck` uses them as is.

Incidentally, arguments flattening results in column names not being processed with `#arel_column`.

### System configuration

**Rails version**: 7.1

**Ruby version**: 3.3.0

**Comment by Jay0921** [comment]
https://github.com/rails/rails/blob/51ce412d1b51949de18089df6aed5b86fb6eb176/activerecord/lib/active_record/associations/collection_association.rb#L51
https://github.com/rails/rails/blob/51ce412d1b51949de18089df6aed5b86fb6eb176/activesupport/lib/active_support/core_ext/enumerable.rb#L145

In this case, `reflection.association_primary_key` returns `["id"]`, which, when passed to the pluck method, is further nested into `[["id"]]` due to the splat operator `(*keys)` in the method's parameters. Consequently, this nesting results in `keys.first` within the pluck method being `["id"]`, rather than the expected straightforward `"id"`.

When using the Enumerable#pluck method with an array argument, like `[:id, :post_id]`, it leads to unexpected behavior. The method interprets the array as a single, composite attribute, which doesn't match any keys in the hash, resulting in nil values for each element:
```
[{ id: 1, post_id: 1 }, { id: 2, post_id: 1 }, { id: 3, post_id: 1 }].pluck([:id, :post_id])
# Output: [nil, nil, nil]
```
To accurately extract multiple attributes, each attribute name should be passed as a separate argument. This allows the method to correctly identify and retrieve the values for each attribute from the hashes:
```
[{ id: 1, post_id: 1 }, { id: 2, post_id: 1 }, { id: 3, post_id: 1 }].pluck(:id, :post_id)
# Output: [[1, 1], [2, 1], [3, 1]]

# This works too
[{ id: 1, post_id: 1 }, { id: 2, post_id: 1 }, { id: 3, post_id: 1 }].pluck(*[:id, :post_id])
# Output: [[1, 1], [2, 1], [3, 1]] 
```

We can utilize the splat operator (*) to distribute the array's elements as separate arguments to the method.
```
target.pluck(*reflection.association_primary_key)
```

**Comment by Jay0921** [comment]
Upon a second look, I realize the example above might not be the best example. If we simply change `self.primary_key = [:id]` to `self.primary_key = :id` for the case above, everything will work as expected. The issue arose because Rails treated the primary_key as a composite primary key due to it being an array. 

From 7.1.3.2:
https://github.com/rails/rails/blob/6f0d1ad14b92b9f5906e44740fce8b4f1c7075dc/activerecord/lib/active_record/attribute_methods/primary_key.rb#L118-L120

From Edge:
https://github.com/rails/rails/blob/9f1dec2ea5155205a880f6e6e232cf9ea6da2d8c/activerecord/lib/active_record/attribute_methods/primary_key.rb#L134-L135

I've written another test case for the composite primary key.

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "7.1.3.2"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :authors do |t|
  end

  create_table :posts, primary_key: [:author_id, :id], force: true do |t|
    t.integer :id
    t.integer :author_id
  end

  create_table :comments, primary_key: [:author_id, :id], force: true do |t|
    t.integer :id
    t.integer :author_id
    t.integer :post_id
  end
end

class Author < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

class Post < ActiveRecord::Base
  self.primary_key = :author_id, :id

  belongs_to :author
  has_many :comments, query_constraints: [:author_id, :post_id]
end

class Comment < ActiveRecord::Base
  self.primary_key = :author_id, :id

  belongs_to :author
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    author = Author.create!
    post_id = rand(1..10)
    post = Post.create!(id: [author.id, post_id])
    comment1 = Comment.create!(id: [author.id, rand(1..5)], post_id: post_id)

    assert_equal 1, post.comments.count
    assert_equal 1, Comment.count
    assert_equal post.id, Comment.take.post.id

    assert_equal Comment.ids, Post.take.comment_ids
    assert_equal Comment.ids, Post.preload(:comments).take.comment_ids
  end
end
```
