### ISSUE TITLE
`update_all` raises an exception with an empty list of attributes but `update` not

### ISSUE THREAD

**Issue by GitToTheHub** [rails/rails#51122]
### Steps to reproduce

When I'm doing

`model.relations.update_all({})`

it raises an exception: `ArgumentError: Empty list of attributes to change`

but when I do

`model.update({})`

there is no exception and it returns `true`

Why is there a difference?

### Expected behavior
The behaviour of `update` and `ùpdate_all` should be equivalent

### Actual behavior
`update_all` raises an exception with the value `{}`, but `update` not.

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.2.2

**Comment by rafaelfranca** [comment]
They are different methods. They behave differently. The difference is because `update_all` needs to build a SQL to send to the database and without any information it can't. `model.update` already have information, so even you don't pass anything this code should still work:

```
model = Model.find(1)
model.name = "rafael"
mode.update({})
```

This should update the name of the mode with id 1 to `"rafael"`.
