### ISSUE TITLE
Setting an assets prefix leads to 405 errors on POST requests

### ISSUE THREAD

**Issue by maxlein** [rails/rails#51163]
I try to get my app running under a special path with `RAILS_RELATIVE_URL_ROOT`.  
I do that because my app runs in a kubernetes cluster and I need a specific route, e.g.: localhost/team-tracker  
But if I set the assets prefix path, the site and styles are working but the POST request are failing like that:  

`POST http://127.0.0.1:3000/team-tracker/import_external_issues 405`

RAILS_RELATIVE_URL_ROOT = /team-tracker

I have my routes scoped like that:  

routes.rb  
```
Rails.application.routes.draw do
  
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    resources :board_issues
    resources :board_lists
    resources :homes

    post 'import_external_issues', to: 'issues#import_external_issues'

  end
end
```

Then I set an assets prefix, so that my assets are linked correctly:  
development.rb   
`  config.assets.prefix = ENV['RAILS_RELATIVE_URL_ROOT'] || '/assets'`

But this step breaks the POST requests.  

Am I dong something wrong? Is there an easier way to use an ingress with a special route?

### Steps to reproduce
 
Set RAILS_RELATIVE_URL_ROOT and a corresponding assets prefix.  

### Expected behavior
POST requests are working the same like without setting the assets prefix.

### Actual behavior
POST requests don't work:
`POST http://127.0.0.1:3000/team-tracker/import_external_issues 405`

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.3.0

**Comment by skipkayhil** [comment]
It sound like you should be setting `config.assets.prefix = "#{ENV['RAILS_RELATIVE_URL_ROOT']/assets"` or something like that so that `/assets` is _appended_ to the relative root.

However, we reserve the issue tracker for bugs in Rails as we don't have the bandwidth to provide application support. I'm going to close this issue because it doesn't sound like there's a bug here, but if you believe there is one I can re-open.
