### ISSUE TITLE
normalizes doesn't work with store / store_attributes

### ISSUE THREAD

**Issue by Roguelazer** [rails/rails#51218]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :items, force: true do |t|
    t.json :misc
  end
end

class Item < ActiveRecord::Base
  store :misc, accessors: [:numbers]
  normalizes :numbers, with: ->(value) { value&.map(&:to_i)&.sort }
end

class BugTest < Minitest::Test
  def test_normalized_store_attribute
    item = Item.create!(numbers: [3, "1", 2])
    assert_equal [1, 2, 3], item.numbers
  end
end

```

### Expected behavior
I had hoped that the cool new `normalizes` helper in Rails 7.1 would work with the pseudo-fields created by `store` / `store_accessor`

### Actual behavior
`normalizes` has no effect on these fields

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.3.0

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is more a feature request. The feature never had the intention to work with store attributes. This doesn't mean it can't, but we don't take feature requests in the issue track. If you like to have this feature, feel free to implement and open a pull request. Otherwise, if you want help to implement it you can ask for help in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5.
