### ISSUE TITLE
ActionView::Helpers::DateHelper #distance_of_time_in_words Leap Day bug

### ISSUE THREAD

**Issue by jclemans** [rails/rails#51227]
I discovered today that running distance_of_time_in_words("2024-02-29", "2025-02-28") does not return a result of "1 year". Instead, it returns "11 months, 4 weeks, and 2 days". While numerically accurate, expectation is that the last day of the month to the last day of the same month the next year would return "1 year". Is this intentional or is this just an edge case that everyone works around?

### Steps to reproduce
pry(main)> include ActionView::Helpers::DateHelper
=> Object
pry(main)> distance_of_time_in_words("2024-02-29", "2025-02-28")
=> "11 months, 4 weeks, and 2 days"

### Expected behavior
Returns "1 year"
### Actual behavior
Return "11 months, 4 weeks, and 2 days"

### System configuration
**Rails version**: 6.1.7.7

**Ruby version**: 3.1.4

**Comment by skipkayhil** [comment]
```
$ rails c
Loading development environment (Rails 7.2.0.alpha)
dm(dev)> helper.distance_of_time_in_words("2024-02-29", "2025-02-28")
=> "almost 1 year"
```

Interestingly, I get a different result on `main`, and I don't see any changes to the method in ~7 years (Rails 5.2).

---

Anyways, the documentation states this is "the approximate distance in time", so I'm not sure there's anything to change here. Trying to exactly calculate the distance between two dates/times is extremely hard (`Duration` was created to help but it still isn't perfect), and `almost 1 year` seems close enough.

I'm going to close because the method appears to be working as expected, but feel free to reply if you can provide a reproduction of it doing something wrong.
