### ISSUE TITLE
[Question]`mark_for_destruction` not destroying records when loading using `find_by`

### ISSUE THREAD

**Issue by sarvesh-sankaranarayanan** [rails/rails#51332]
### Steps to reproduce

```ruby
class Incident < ApplicationRecord
  has_many :service_mappings, class_name: 'IncidentServiceMapping', inverse_of: :incident, foreign_key: 'incident_id', dependent: :delete_all, autosave: true
  has_many :services, through: :service_mappings

class IncidentServiceMapping < ApplicationRecord
  belongs_to :service
  belongs_to :incident
end

# Test script which is not working

incident = Incident.last
service = incident.services.first

ism = incident.last.service_mappings.find_by(service_id: service.id)
ism.mark_for_destruction
incident.save!


# Test script which is woking
incident = Incident.last
service = incident.services.first

incident.service_mappings.detect{ |service_mapping| service_mapping.service_id == service.id }.mark_for_destruction

incident.save!
```

### Expected behavior

The incident service mapping should be destroyed in the first script

### Actual behavior

The incident service mapping is not destroyed in the first script

### System configuration
**Rails version**: 7.0.6

**Ruby version**: 3.2.0

**Comment by nvasilevski** [comment]
Hey, Rails reserves github issues for bugs only. It's better to post questions in public forums like Discourse https://discuss.rubyonrails.org/ or Discord

But to answer your question, `mark_for_destruction` sets `@marked_for_destruction` instance variable to `true` and since `find_by` initializes a new instance, completely detached from `incident.service_mappings` association, it has no effect when you `save!` the `incident` instance.

Let me know if It's not clear and I can try explaining it in a different way. Thanks

**Comment by sarvesh-sankaranarayanan** [comment]
Thanks. I understood. I didn't know about the discussion forum. Will take my queries there henceforth.
