### ISSUE TITLE
Ability to pass options to `empty?`

### ISSUE THREAD

**Issue by loqimean** [rails/rails#51370]
### Expected behavior
Enter params as on a `exists?` method to detect missing records etc.
Source: https://apidock.com/rails/v5.2.3/ActiveRecord/Relation/empty%3F

### Actual behavior
There is no such ability

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.0

**Comment by JoeDupuis** [comment]
Hi! As per the [contributing guide](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark), Rails reserves github issues for bugs only.  You should try posting in the [Ruby core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) with examples of what the api would look like.

Since contributors bandwidth is limited, even if there is interest in the feature, I would not expect anyone to work on it. It is very likely that you'd have to build the feature yourself.
