### ISSUE TITLE
Large arel tree causes ActiveRecord preloader to throw SystemStackError

### ISSUE THREAD

**Issue by markedmondson** [rails/rails#51386]
### Steps to reproduce
Changes in https://github.com/rails/rails/pull/41597 added a tracker for preloaders using their hash value to better group duplicate queries. 

If you have a complicated ActiveRecord::Relation with ~5,000 nodes (note that it seems that it's less about the number of tree nodes and as much about the sheer number of duplicate iterations in the `hash` call on Arel::Nodes::Binary) passed through a preloader as the scope, the preloader will attempt to hash the scope which causes the SystemStackError.

This is repeatable simply with a query with 5,000 condition values regardless of preloader usage, see below.

The example is intentionally basic, a simple IN statement would resolve the issue in this case but our more complicated example does genuinely include thousands of arel nodes.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def setup
    @post = Post.create
    5000.times.each do
      @post.comments.create!
    end

    # Build a scope with 5000 OR conditions
    scope = Comment.all
    @or_scope = scope.collect do |comment|
      Comment.where(id: comment.id)
    end.reduce(:or)
  end

  def test_where_clause
    @or_scope.where_clause.hash
  end

  def test_preloader
    ActiveRecord::Associations::Preloader.new(
      records: [@post],
      associations: :comments,
      scope: @or_scope
    ).call
  end
end

```

### Expected behavior
A hash should be generated regardless of the tree or number of nodes.

### Actual behavior
```
Error:
BugTest#test_where_clause:
SystemStackError: 9794 -> 29
     +->> 9768 cycles of 1 lines:
     | /3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/arel/nodes/binary.rb:21:in `hash'
     +-<<
    /3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/arel/nodes/unary.rb:15:in `hash'
     +->> 3 cycles of 1 lines:
     | /3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/active_record/relation/where_clause.rb:78:in `hash'
     +-<<
    ./rails_7_bug.rb:55:in `test_where_clause'
```

```
Error:
BugTest#test_preloader:
SystemStackError: 9794 -> 37
     +->> 9760 cycles of 1 lines:
     | 3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/arel/nodes/binary.rb:21:in `hash'
     +-<<
    3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/arel/nodes/unary.rb:15:in `hash'
     +->> 3 cycles of 1 lines:
     | 3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/active_record/relation/where_clause.rb:78:in `hash'
     +-<<
     +->> 3 cycles of 1 lines:
     | 3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/active_record/associations/preloader/association.rb:25:in `hash'
     +-<<
    3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/active_record/associations/preloader/batch.rb:41:in `each'
    3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/active_record/associations/preloader/batch.rb:41:in `group_by'
    3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/active_record/associations/preloader/batch.rb:41:in `group_and_load_similar'
    3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/active_record/associations/preloader/batch.rb:27:in `call'
    3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-68b20b6513fe/activerecord/lib/active_record/associations/preloader.rb:121:in `call'
    ./rails_7_bug.rb:64:in `test_preloader'
```

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.2.0

**Comment by casperisfine** [comment]
Interesting. 

So this limitation isn't very surprising when you know that Arel compilation uses the common [visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern), so Arel will commonly use `K * tree_depth` stack frames to compile an AST, and Ruby the Ruby stack is finite, hence Arel has an implicit max depth limit.

Interestingly, in your stacktraces, it's the `hash` method that raises, but it's because it similarly recursively digest child nodes, so same problem. https://github.com/rails/rails/pull/41597 is what started calling `hash`, but I suspect compiling to SQL would similarly run out of stack space (if not the limit probably isn't that much further).

One way we may be able to improve this is by changing the `Or` node, so it's no longer a binary node, but can contain any number of conditions.

That would fix your specific problem, and generally probably reduce the depth of trees a bit, but the same problem may exist with other types of nodes. And I'm also not sure yet whether this solution is even doable, I'd need to try to see.

And also, even if it works, it would be a big enough change that I don't think it would be realistic to backport it as a bug fix to be honest.

**Comment by markedmondson** [comment]
Thank you @casperisfine - I'll try patching this locally and see if it solves our specific use-case!
