### ISSUE TITLE
Validation Does Not Work with Multiple Encryption Scheme

### ISSUE THREAD

**Issue by aveedibya** [rails/rails#51553]
### Steps to reproduce
Uniqueness validation with multiple encryption scheme does not work. The uniqueness validation is skipped if the field is set up with current deterministic encryption scheme and previously non-deterministic encryption scheme. Example model class shown below:

```ruby
  class UserSensitiveTable < ApplicationRecord
   
      ...
      
      validates :sensitive_field, uniqueness: true
      encrypts :sensitive_field, deterministic: true, previous: { deterministic: false }
    
      ...
  
  end
```

### Expected behavior
Records with a duplicate sensitive field should not be created.

### Actual behavior
Multiple records can be created for the `sensitive_field` even though the uniqueness validation is added for this field.

### System configuration
Rails 7.0.8.1
Ruby 3.1.2

**Comment by liaden** [comment]
The only way that uniqueness could work is if the previous encryption scheme was deterministic because you could have multiples of that value already inserted with the non-deterministic encryption, and the uniqueness validator cannot issue a DB query to check for uniqueness.

Out of the box, I can only see it working with `downcase` changing between the two schemes. If you are trying to rotate a key, previous will need to specify a `key: 'old_key'` (or specifying `key_provider:`) because assigning an array of keys as part of determinstic encryption config results in the `DeterministicKeyProvider` raising an error since key rotation is unsupported. 

Note: You also need to enable extended query support: https://guides.rubyonrails.org/v7.0/active_record_encryption.html#config-active-record-encryption-extend-queries
