### ISSUE TITLE
find_by called with no paramaters

### ISSUE THREAD

**Issue by stevenconnelly** [rails/rails#51600]
### Steps to reproduce
Model.find_by(234) correctly does not work.

But

Model.find_by('234') will return a record. 

This is to stop a possible error whereby

User.find(params[:id])

is incorrectly updated to

User.find_by(params[:id]) 
when what was intended was
User.find_by(id: params[:id])
# Your reproduction script goes here
```

### Expected behavior
Model.find_by('234') should not work

### Actual behavior
It does

### System configuration
**Rails version**:

**Ruby version**:

**Comment by fatkodima** [comment]
Provide a rails version and a reproduction test script using this template https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb

**Comment by nvasilevski** [comment]
>Expected behavior: Model.find_by('234') should not work

I don't see this is a legit expected behavior. Passing string to `find_by` should work to support something like:

`User.find_by("age > 18")`

Also I doubt that `Model.find_by('234')` returns a record with `id` 234. It most likely returns just the first row database finds as the clause will be `WHERE (234)` which is basically `where true`. So a decent tests coverage should catch it

**Comment by fatkodima** [comment]
Yeah, with `find_by('123')` it just raises.
So, this is a legit behavior for me too.
