### ISSUE TITLE
`.pluck` with multiple sql fragment arguments using `min` incorrectly casts types when using PostgreSQL

### ISSUE THREAD

**Issue by gyfis** [rails/rails#51991]
### Steps to reproduce

`.pluck` calls with multiple SQL fragment arguments, using the same function (such as `min` or `max`) incorrectly sets types for the returned values when using PostgreSQL.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", branch: "main"
  gem 'pg', '~> 1.1'
end

require "active_record"
require "minitest/autorun"
require "logger"

# Run this in psql to setup the test database
# ```
# CREATE USER rails_repro_test WITH PASSWORD 'rails_repro_test';
# ALTER USER rails_repro_test WITH SUPERUSER;
# CREATE DATABASE rails_repro_test;
# GRANT ALL PRIVILEGES ON DATABASE rails_repro_test to rails_repro_test;
# ````

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "rails_repro_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :file_parts, force: true do |t|
    t.string :part_name, null: false
    t.datetime :part_start_at, null: false
  end
end

class FilePart < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_pluck_with_multiple_min
    FilePart.delete_all

    FilePart.create!(part_name: '2024/06/01/14_16.a1b2c3d4.txt', part_start_at: '2024-06-01 14:16:00')
    FilePart.create!(part_name: '2024/05/31/11_12.a2b3c4d5.txt', part_start_at: '2024-05-31 11:12:00')

    # this case works
    assert_equal [['2024/05/31/11_12.a2b3c4d5.txt', DateTime.parse('2024-05-31 11:12:00')]], FilePart.pluck('min(part_name), min(part_start_at)')

    # this case doesn't work
    assert_equal [['2024/05/31/11_12.a2b3c4d5.txt', DateTime.parse('2024-05-31 11:12:00')]], FilePart.pluck('min(part_name)', 'min(part_start_at)')

    # this is returned instead, where the first element is type casted to datetime too
    # => [[2024-05-31 00:00:00 UTC, 2024-05-31 11:12:00 UTC]]
  end
end

```

### Expected behavior
The `.pluck` call should return correct types, e.g. a string and a datetime, not two datetimes

### Actual behavior
The `.pluck` call incorrectly casts types for the string argument

### System configuration
**Rails version**: 7.0.8.3, 7.1.3.3, 7.2.0.beta1, edge

**Ruby version**: 3.2.2

**Comment by maniSHarma7575** [comment]
https://github.com/rails/rails/blob/eddf8465f66ca4fc92ec9ca615cfa87db0910e25/activerecord/lib/active_record/relation/calculations.rb#L316-L318

Pluck method internally calls this method which is responsible for the incorrect result.

https://github.com/rails/rails/blob/eddf8465f66ca4fc92ec9ca615cfa87db0910e25/activerecord/lib/active_record/relation/calculations.rb#L592

**What's the problem with this code?**

Let me take an example:

When we execute this code the test fails:
```ruby
assert_equal [['2024/05/31/11_12.a2b3c4d5.txt', DateTime.parse('2024-05-31 11:12:00')]], FilePart.pluck('min(part_name)', 'min(part_start_at)')
```
```ruby
  1) Failure:
BugTest#test_pluck_with_multiple_min [51991.rb:61]:
--- expected
+++ actual
@@ -1 +1 @@
-[["2024/05/31/11_12.a2b3c4d5.txt", Fri, 31 May 2024 11:12:00 +0000]]
+[[2024-05-31 00:00:00 UTC, 2024-05-31 11:12:00 UTC]]
```

**Why is this test failing?**

If we examine the output, the `part_name` field is also being cast as a timestamp.

Why is `part_name` getting cast as a timestamp?

To understand this, we need to look at this piece of code 
https://github.com/rails/rails/blob/eddf8465f66ca4fc92ec9ca615cfa87db0910e25/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L63-L74

Here, we are creating the `types` hash for each field required in the pluck result. Each field will have a corresponding type. Correct?

However, the issue lies in the fact that in our case, both columns have the `min` function applied, so our `fields = result.fields` will have the value:

```ruby
fields == ["min", "min"]
```

Hence, when creating the key with `min`, it will be overridden by `part_start_at`.

In the following code, we are filtering out the type based on the `name`, which will give the same type (timestamp) for columns with the same name.
https://github.com/rails/rails/blob/eddf8465f66ca4fc92ec9ca615cfa87db0910e25/activerecord/lib/active_record/relation/calculations.rb#L592

**Solution:**

With [this commit](https://github.com/rails/rails/commit/100c86c00eefc69661e9abdfcb6e0a4a2b46676e), 

https://github.com/rails/rails/blob/eddf8465f66ca4fc92ec9ca615cfa87db0910e25/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L70-L70
since we are also storing the type based on the column or field index, it's better to utilize that for a more accurate result.

Hence we change the line to

**Before:**
```ruby
  result.column_types[name] || Type.default_value
```
**After:**
```ruby
  result.column_types[i] || Type.default_value
```

**Comment by maniSHarma7575** [comment]
@tenderlove we have same issue with `select` method as well.

Detailed mentioned here: https://github.com/rails/rails/issues/52029
