### ISSUE TITLE
[Rails 6.1] Rails 6.1 vulerable to CVE-2024-34341 (trix and actiontext)

### ISSUE THREAD

**Issue by melefabrizio** [rails/rails#52009]
I'm getting some warnings from `bundler audit` on a Rails 6.1.7.7 app, it seems that it is vulnerable to CVE-2024-34341 regarding actiontext and the trix editor.

Searching on the web I found[ this announcement](https://discuss.rubyonrails.org/t/xss-vulnerabilities-in-trix-editor/85803), which states that rails 6.1 does not embed trix, but looking at the source I found [this](https://github.com/rails/rails/blob/481c3b941ba5b78031796ac088e7c2e6bc6e8567/actiontext/package.json#L27) on the `6-1-stable` branch:

```json
  "peerDependencies": {
    "trix": "^1.2.0"
  }
```

It seems that Rails 6.1 should also be patched to fix the trix issue.

### System configuration
**Rails version**: 6.1.7.7

**Ruby version**: 3.3.1

**Comment by skipkayhil** [comment]
`^1.2.0` means `> 2.0, >=1.2.0`, so it includes the fixed version `1.3.3`. Any Rails applications on 6.1 should `yarn add trix@1.3.3` to update their Trix version if they are using it.

Rails does not upgrade minimum dependency versions for security releases since the best place to do that is in application files, see https://github.com/rails/rails/pull/42402#issuecomment-856302678
