### ISSUE TITLE
rescue_from ActiveRecord::DeleteRestrictionError - uninitialized constant with eager load enabled

### ISSUE THREAD

**Issue by adriely-dourado** [rails/rails#52051]
### Steps to reproduce
Add a rescue_from in the ApplicationController, for example:
```
rescue_from ActiveRecord::DeleteRestrictionError, with: :delete_restriction_error
```
Change the eager load configuration to true, example in config/environments/development.rb:
```
config.eager_load = true
```
Run the project and the error will occur
```
bin/rails s
```
### Expected behavior
rescue_from ActiveRecord::DeleteRestrictionError works as intended within app/controllers/application_controller.rb
### Actual behavior
When usings eager load, it fails to load the constant ActiveRecord::DeleteRestrictionError.
### System configuration
**Rails version**: 8.0.0.alpha
**Ruby version**: 3.3.1

**Comment by fatkodima** [comment]
Can you create a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller.rb template?

**Comment by adriely-dourado** [comment]
> Can you create a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller.rb template?

Sorry, but I couldn't reproduce it. 🥲 In the script, if I load the `active_record/associations`, it passes; if I don't load it, it fails, regardless of the eager load configuration. But to reproduce it, simply create a new project, add the rescue_from `ActiveRecord::DeleteRestrictionError, with: :delete_restriction_error` in the ApplicationController, and try to run the project. I opened the issue because in other projects I worked on, it worked this way.
If you put the error class as string, it works.

**Comment by fatkodima** [comment]
So I identified this is happening because the app code is eager loaded *before* the framework code. Making this change
```diff
diff --git a/railties/lib/rails/application/finisher.rb b/railties/lib/rails/application/finisher.rb
index 61a7be9291..37fdbcd558 100644
--- a/railties/lib/rails/application/finisher.rb
+++ b/railties/lib/rails/application/finisher.rb
@@ -77,9 +77,9 @@ module Finisher
       initializer :eager_load! do |app|
         if config.eager_load
           ActiveSupport.run_load_hooks(:before_eager_load, self)
-          Zeitwerk::Loader.eager_load_all
           Rails.eager_load!
           config.eager_load_namespaces.each(&:eager_load!)
+          Zeitwerk::Loader.eager_load_all

           if config.reloading_enabled?
             app.reloader.after_class_unload do
```

seems like fixes the issue. But I am not enough familiar with the internals of the changed code. 
@fxn Do you have an idea about this?

**Comment by fxn** [comment]
@fatkodima I believe that could be a red herring.

Eager vs not eager should not influence what is available, provided you have required the gems in the Gemfile or `config/application.rb`.

Eager vs not eager only says whether you want your code to be loaded on demand, or upfront. But the code should be loadable regardless.

In this case, if Active Record provides `ActiveRecord::DeleteRestrictionError` and says to users "this class is available (you do not need to issue a require call to load it)", then eager vs lazy does not matter, because the availability of the constant does not depend on eager loading. In development mode:

```
bin/rails r 'p ActiveRecord::DeleteRestrictionError'
ActiveRecord::DeleteRestrictionError
```

The contract is never "the constant is available if you eager load", the contract is "the constant is available whenever you need it (after requireing the entrypoint)".

I suspect the problem may be that `active_record/base`, which is necessary to have those constants available, is being loaded too late, in a way that does not agree with that contract.

**Comment by fxn** [comment]
Having said that, I believe your patch makes sense conceptually.

The problem with `active_record/base` is deeper than the scope of this issue. It is a problem of defining "Active Record is ready" by a `require` of that file, which in my view is not a good definition. Applications and libraries should be able to load a Ruby file they need when they need the code defined in there.

"Being ready" is a more complex concept involving configuration and stuff that would probably be better expressed in an initializer.

A consequence of the current way in which things are defined is that Rails tries to load `active_record/base` as late as possible to delay the execution of `on_load` hooks as much as possible. So that interfers with the actual availability of the classes, which is a smell to me.

This is a design issue, and not an easy one given that this system has been in place forever.

So, I think we could apply your patch because that reorder, by itself, seems good. But at the same time we know the root cause of the issue, design, remains.

**Comment by fatkodima** [comment]
Thank you for explanations, appreciated! ❤️ Another way to fix this exact issue is to move all the error classes from the `associations.rb` file to the `errors.rb` file, where all the active record related errors live. This file is required explicitly by the  `active_record.rb` itself 🤔.

**Comment by fxn** [comment]
Great idea, that makes sense.

**Comment by fatkodima** [comment]
Opened a PR with that fix.

**Comment by fxn** [comment]
Hmmm, this particular exception seems to point to a logic error in the application. Or, maybe you deleted optimistically and catch the exception as a way to say: OK, there are children, we cannot do this.

Most of the times, you want that error to bubble up and fix the issue, but, who knows. Maybe you inherited a legacy code base that is raising and you need contention in production while working on the source of the errors.

@adriely-dourado which is your use case?

**Comment by adriely-dourado** [comment]
> @adriely-dourado which is your use case?

In my case, it's a new project. I try to perform the deletion optimistically, and if there's any restriction defined in the model, I'd like to handle the error by displaying a message to the user.
