### ISSUE TITLE
Rails server --pid option does not seem to work as expected. Also no documentation found.

### ISSUE THREAD

**Issue by georgeu2000** [rails/rails#52073]
### Steps to reproduce

`rails s --pid=tmp/pids/realtime.pid`

creates 2 pidfiles: `realtime.pid` as well as `server.pid`.

### Expected behavior
I gather that there should be only one pidfile created: `realtime.pid`.

### Actual behavior
2 pidfiles created: `realtime.pid` as well as `server.pid`.

However, `PIDFILE=tmp/pids/realtime.pid rails s` **_does_** have the expected behavior. It only creates 1 pidfile: `realtime.pid`.

Also, I could not find any documentation about this feature in the Rails Guides.
There should be an explanation here: https://guides.rubyonrails.org/command_line.html#bin-rails-server

### System configuration
**Rails version**: Rails 7.1.2

**Ruby version**: ruby 3.3.0

**Comment by nikhilbhatt** [comment]
Please check for `puma.rb` file in your application, if it is looking for `PIDFILE` env variable.

#### Old Puma Configuration Template
```
if ENV["PIDFILE"]
  pidfile ENV["PIDFILE"]
else
  pidfile "tmp/pids/server.pid" if ENV.fetch("RAILS_ENV", "development") == "development"
end
```

#### Why?
if it is set puma will use that path and will not create additional PID file.

If it is not set puma will create PID file at default location. i.e. `/tmp/pids/server/pid`


#### Solution
You can update your puma.rb file with following code.

This is already fixed in https://github.com/rails/rails/pull/50669/files#diff-e25cab4832f078ca2f9dffa8918f895c8474f8086878e4ced9f5795131fc2de2R52

**Comment by georgeu2000** [comment]
Great. Thank you.
