### ISSUE TITLE
Rails 7.0: `form_with` does not prefix id with namespace when namespace is given

### ISSUE THREAD

**Issue by heratyian** [rails/rails#52381]
### Steps to reproduce

1. Render a form using `form_with` with a `namespace` parameter.
```erb
<%= form_with model: @post, namespace: "my_namespace" do |form| %>
  ...
<% end %>
```
2. Rendered form id does not include a prefixed namespace

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "minitest/autorun"
require "action_view"

class BugTest < ActionView::TestCase
  def test_form_with_id_prefixes_namespace
    render inline: <<~ERB
      <%= form_with model: Post.new, namespace: "my_namespace" do |form| %>
      <% end %>
    ERB

    element = rendered.html.at("form")

    assert_equal element.id, "my_namespace_new_post"
  end
end
```

### Expected behavior
`form_with` should prefix `namespace` option on rendered form id.

### Actual behavior
`namespace` is not applied to rendered form id

### System configuration
Rails 7.0.4.1

**Ruby version**:
Ruby 3.1.2

**Comment by felipedmesquita** [comment]
Hi!
From what I understood of your test code, you are looking to set an id on the html form itself, not the form fields. To achieve this, use the `:id` option instead of `:namespace`:
```ruby
form_with model: Post.new, id: "my_namespace" do |form|
```
`:namespace` is [intended to prefix the ids on the form's fields](https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with-label-form_with+options), and this behavior works correctly in rails main and in version  7.0.4.1 you mentioned.
