### ISSUE TITLE
Serialized column in Rails 6 app not parsable in Rails 7 app

### ISSUE THREAD

**Issue by noctivityinc** [rails/rails#52445]
This seems insane to me.  We are upgrading our app from Rails 6.1.7.7 (with load_defauls set to 5.2) to rails 7.1.3.4 and ruby 3.3.2 to 3.3.4.

In our items model, we have a simple serializer:

```serialize :keywords, coder: JSON, type: Array```

We have millions of records stored using this form our 6.1.7.7 app and can write and read from it without issue:

```
Loading production environment (Rails 6.1.7.7)
irb(main):001> i = Item.find(4443084)
=>
#<Item:0x00007f6b6fb909d8
...
irb(main):002> i.keywords
=> "brain,web design,mind-blowing,development,vintage"
```

but when we attempt to read the EXACT same data using our Rails 7 app, it crashes:

```
Loading production environment (Rails 7.1.3.4)
irb(main):001> i = Item.find(4443084)
An error occurred when inspecting the object: #<JSON::ParserError:"unexpected token at '--- brain,web design,mind-blowing,development,vintage\n'">
Result of Kernel#inspect: #<Item:0x00007f52b5e882d0 @new_record=false, @attributes=#<ActiveModel::LazyAttributeSet:0x00007f52b5ed0cd8 @attributes={"id"=>#<ActiveModel::Attribute::FromDatabase
...
```

I can't seem to find anything on this at all!  We used serialize in many places in our app and if we can't read any of them in our Rails 7 app, we're in trouble.

How do we fix this?  Why would the same coder and type not work the same between the two?

**Comment by MatheusRich** [comment]
@noctivityinc it would be helpful if you could write a reproduction script.

**Comment by noctivityinc** [comment]
@MatheusRich I know but how do I write a reproducable script for a model for two different rails versions?

It's literally

```
class Item < ActiveRecord::Base`
  serialize :keywords, coder: YAML, type: Array
end
```

one running in Rails 6.1 and the same in Rails 7.1.  That's it.  Then in Rails 6:

```
i = Item.new(keyword: {test: 'this'})
i.save
```

and in Rails 7.1

```
i = Item.first
```

crash.

Ive already written a migration to move both the fields over to a true JSON postgres field and not use serialize, which seems to have worked and fixed the problem.  Still super odd though.

**Comment by Earlopain** [comment]
I'm a bit confused by your reproduction. You first specified `JSON` as the coder which then fails on `YAML` data and later on you say you use the yaml coder all along and I guess it now tries to use the `JSON` coder.

You're also jumping from 6.1 straight to 7.1 which I wouldn't recommend. Rails doesn't follow strict semver and minor versions contains breaking changes. I doubt this is related to your problem but I can't say it doesn't.

**Comment by jeromedalbert** [comment]
Assuming that the issue is with `serialize :keywords, coder: JSON, type: Array` (the first one noctivityinc mentioned).

Here is a reproduction script:

```ruby
# repro.rb

RAILS_MAJOR_VERSION = ARGV[0].to_i
if RAILS_MAJOR_VERSION != 6 && RAILS_MAJOR_VERSION != 7
  raise "Please provide Rails major version (6 or 7)"
end

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rails', RAILS_MAJOR_VERSION == 6 ? '6.1.7.7' : '7.1.3.4'
  gem 'sqlite3', '~> 1.4'
end

require 'rails'
require 'active_record'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: 'repro.sqlite3')
if !File.exist?('repro.sqlite3')
  ActiveRecord::Schema.define do
    create_table :items do |t|
      t.string :keywords
    end
  end
end

class MyApp < Rails::Application
  config.eager_load = false
end

class Item < ActiveRecord::Base
  serialize :keywords, coder: JSON, type: Array
end

MyApp.initialize!

if Item.none?
  Item.create!(keywords: ['brain' , 'web design', 'mind-blowing' , 'development', 'vintage'])
end

puts "\nLast item: #{Item.last.inspect}"
```

Steps to reproduce:

```
$ ruby repro.rb 6

Last item: #<Item id: 1, keywords: ["brain", "web design", "mind-blowing", "development", "vintage"]>

$ ruby repro.rb 7

/Users/jerome/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/json/common.rb:219:in `parse': unexpected token at '--- (JSON::ParserError)
- brain
- web design
- mind-blowing
- development
- vintage
```

**Comment by jeromedalbert** [comment]
After playing around with that repro script, I think I found the cause of the issue and a solution.

### Problem

Your Rails 6 code was doing `serialize :keywords, coder: JSON, type: Array`. Rails 6 didn't recognize the coder option ([source](https://github.com/rails/rails/blob/v6.1.7.7/activerecord/lib/active_record/attribute_methods/serialization.rb#L66)). If the original intent was to use the JSON coder, the code should have been `serialize :keywords, JSON, type: Array`. Since Rails 6 did't recognize your `coder:` option, it defaulted to a YAML coder ([source](https://github.com/rails/rails/blob/v6.1.7.7/activerecord/lib/active_record/attribute_methods/serialization.rb#L74-L75)).

So your data was encoded with YAML. This can be verified after running the repro script by doing the following, where we can see that the data looks like YAML:

```
$ sqlite3 repro.sqlite3
sqlite> select * from items;
sqlite> select * from items;

1|---
- brain
- web design
- mind-blowing
- development
- vintage
```

But Rails 7.1+ recognizes the `coder:` option. So when loading an `Item`, your code tried to deserialize YAML data from your database with a JSON serializer, which is why you got the following error:

`unexpected token at '--- brain,web design,mind-blowing,development,vintage\n'`

### Solution

Assuming all your data is YAML data because of the problem above, the solution is to change your Rails 7 code to use the YAML serializer:

```ruby
serialize :keywords, coder: YAML, type: Array
```

or just

```ruby
serialize :keywords, type: Array
```

since YAML is the default coder ([source](https://github.com/rails/rails/blob/3acf87e26d3171e0e385aa7301389bda9bebb0f8/activerecord/lib/active_record/attribute_methods/serialization.rb#L20)).

**Comment by byroot** [comment]
```
#<JSON::ParserError:"unexpected token at '--- 
```
Very clearly show it's not JSON in the database, but YAML. So pretty sure @jeromedalbert is right here. Especially since I don't see what we could have changed to break that use case.

You very unfortunately fell into the footgun we wanted to avoid when we made the `serialize` arguments stricter in 7.0 :/

**Comment by noctivityinc** [comment]
> Since Rails 6 did't recognize your coder option

Just want to thank you for this. Quick note though, in these cases shouldn't a warning have been displayed to avoid these exact situations?

**Comment by byroot** [comment]
> in these cases shouldn't a warning have been displayed to avoid these exact situations?

That's one solution, another is to make the arguments stricter to avoid this confusion entirely, which we did and made you realize the problem that was silently in your codebase.
