### ISSUE TITLE
Active Record `where` doesn't fail when passed an array

### ISSUE THREAD

**Issue by janko** [rails/rails#52516]
### Steps to reproduce

```rb
require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define do
  create_table :items do |t|
    t.string :name
  end
end

class Item < ActiveRecord::Base
end

items = [Item.create!, Item.create!, Item.create!]
item_ids = items.map(&:id).map(&:to_s)

ActiveRecord::Base.logger = Logger.new($stdout)

Item.find(item_ids) # correct
# SELECT items.* FROM items WHERE items.id IN (1, 2, 3)
Item.where(item_ids).to_a # silently generates invalid query
# SELECT items.* FROM items WHERE (1)
Item.where(id: item_ids).to_a # correct
# SELECT items.* FROM items WHERE items.id IN (1, 2, 3)
```

### Expected behavior

Since it's easy to make this mistake when going from `find` to `where`, I expected passing an array of strings to `WHERE` to raise an error, because this input cannot be processed in a reasonable way.

That is how Sequel behaves:

```rb
require "sequel"

DB = Sequel.sqlite
DB[:foo].where(["1", "2", "3"])
#~> Sequel::Error: Invalid filter expression: ["1", "2", "3"]
```

### Actual behavior

Active Record silently generates a filter that just matches all records, which makes it easy to accidentally introduce a bug.

### System configuration

**Rails version**: 7.1.3.4

**Ruby version**: 3.3.3

**Comment by fatkodima** [comment]
Rails supports `where` with arrays, where array of strings can be a valid argument - https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-where 

So is there a way to tell when user provided not what he wanted? Probably check if the first argument of the array is not a template (does not include `?`, `:` or `%s`) string and raise. This will not completely solve the problem, because the passed array values can still contain that symbols, but greatly reduce the number bad arguments passed.

**Comment by janko** [comment]
I see, I didn't know about this syntax. For me it would make sense to deprecate the array argument over passing multiple arguments, since there doesn't appear to be a difference in behavior. If the array argument has to be kept, then I don't see how we could error on an array of string IDs without magical guesswork.

**Comment by vlado** [comment]
👍 for deprecating the array argument over passing multiple arguments.

I do not remember ever using array argument with `where`. It could be useful I suppose when you need to build conditions in advance but it could still be possible with splat operator `Item.where(*[...])`.

**Comment by Fjan** [comment]
Way back in Rails 1 the way to write ActiveRecord went something like `find(:condition => ['id > ?',params[:id]])`. So older code bases can have a ton of `where([...])` in them because that's how that got converted with search/replace. Easy enough to fix with another search/replace of course, just mentioning that at quick grep in our code base gave hundreds of hits.
