### ISSUE TITLE
Action Mailer config documentation is not secure

### ISSUE THREAD

**Issue by janie314** [rails/rails#52708]
This documentation advises users to configure passwords directly in files that are not included in gitignore by default (`config/environments/*.rb`).

https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration-for-gmail

This is not secure. When these instructions are followed literally, they will cause credentials to be uploaded to Github.

We should replace `'<password>'`with `Rails.application.credentials.smtp_password` and so on, and link readers to the documentation below for how to use Rails creds mgmt.

https://edgeguides.rubyonrails.org/security.html#custom-credentials

**Comment by rafaelfranca** [comment]
Let's update to what Rails generates as recommendation https://github.com/rails/rails/blob/9558f00f59fbdc1a533af22810c0ae4e9a674688/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt#L99-L100

**Comment by rafaelfranca** [comment]
See #52513

**Comment by sharvy** [comment]
@rafaelfranca I want to work on this issue, please can I take it?

**Comment by jeromedalbert** [comment]
Go ahead

**Comment by sharvy** [comment]
Hi @rafaelfranca sorry for my ignorance, but can anyone work on any issue irrespective others are working on it or not? I was about to push my PR, but looks like you closed this issue since you got a PR from someone.

I don't know the tradition here, but we should at least confirm before working on a ticket, no?

**Comment by rafaelfranca** [comment]
Urgh, sorry about that. We can't control what other do. We also don't require people to ask permission to work on anything, but I agree with you, good practice would be to wait you to open the PR since you said you were going to work on it. That is my fault, I should have closed the PR instead of merging but to be fair I didn't even looked at who opened the PR..

**Comment by rafaelfranca** [comment]
You can work on changing the Active Storage guide. I'll pay attention this time

**Comment by sharvy** [comment]
@rafaelfranca Thanks man! I appreciate your help ❤️
