### ISSUE TITLE
Active Storage Overview guide should promote use of custom credentials, and  use of environment suffixed bucket names

### ISSUE THREAD

**Issue by sharvy** [rails/rails#52724]
If we visit [Active Storage Overview](https://edgeguides.rubyonrails.org/active_storage_overview.html) page, we can see suggestions like: 
```ruby
amazon:
  service: S3
  access_key_id: ""
  secret_access_key: ""
  bucket: ""
  region: "" # e.g. 'us-east-1'
```
People would need to update empty `""` credential values to make it work, but if they're being literal, this may be interpreted as an implicit encouragement to insert credentials right in there.

Regarding environment suffixed bucket names: there is already a merged [PR](https://github.com/rails/rails/pull/42188) which describes the benefit nicely.
### Expected behavior

We should use `Rails.application.credentials` which [Rails generates as recommendation](https://github.com/rails/rails/blob/9558f00f59fbdc1a533af22810c0ae4e9a674688/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt#L99-L100)
```Ruby
# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  bucket: your_own_bucket-<%= Rails.env %>
  region: "" # e.g. 'us-east-1'
```

**Comment by jonathanloos** [comment]
As someone who fell victim to this, thank you so much for logging the issue here! We upgraded our Rails application from 7.1.4 -> 7.2 and our AWS SDK exploded because of a missing region which, without modification, works fine in Rails 7.1.4. Otherwise our Rails 7.2 upgrade went as smooth as can be.

The specific error is the exact same as mentioned in [this article](https://blog.driftingruby.com/rails-7-2-upgrade-problems-of-my-own-making/): 

```bash
** Invoke vite:build_all (first_time)
** Invoke vite:verify_install (first_time)
** Invoke environment (first_time)
** Execute environment
Error retrieving instance profile credentials: Aws::InstanceProfileCredentials::TokenRetrivalError
bin/rails aborted!
Aws::Errors::MissingRegionError: No region was provided. Configure the `:region` option or export the region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)

        raise Errors::MissingRegionError if region.nil? || region == ''
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
/usr/local/bundle/gems/aws-sdk-core-3.203.0/lib/aws-sdk-core/plugins/regional_endpoint.rb:84:in `after_initialize'
```

It took us a while to find this issue, but I do still have one question if anyone else finds themselves here: **Where in the 7.2 upgrade is the change which now causes these ENV variables to return `nil` during the assets:precompile phase?**

Any guidance would be appreciated.
