### ISSUE TITLE
Clarfication on seeds and when they are called

### ISSUE THREAD

**Issue by thomasdarde** [rails/rails#52733]
### Description of the issue
We have a rails project, since update to rails 7.1 tests where ok when run locally but not when run on CI (github action)
Changing the schema.rb to keep ActiveRecord::Schema[7.0] instead of ActiveRecord::Schema[7.1] was sufficient for tests to pass.

When updating ton rails 7.1.4 (from rails 7.1.3.4) tests stopped to pass on CI again.

In the end the issue was linked to seeds: they where not called until schema.rb was mentionning version 7.1 or we update the whole app to 7.1.4

Removing the seeds did fix the issue, it seems they are called if the database was not existing yet ?

I would like to clarify paragraph 8 of this file : https://guides.rubyonrails.org/active_record_migrations.html#migrations-and-seed-data but I need to better understand two things:

Seeds are only for data that is really needed for the app to work not fake data for a test/staging env ?
Where can I find information on when does seeds need to be called ?

### System configuration
**Rails version**: 7.1.4

**Ruby version**: 3.3.4

**Comment by rafaelfranca** [comment]
> Seeds are only for data that is really needed for the app to work not fake data for a test/staging env ?

By default, seeds aren't loaded in the test environment. They can be if you set your CI to do so, but to create fake data for a test, you usually use fixtures.

> Where can I find information on when does seeds need to be called ?

You usually don't need to call them directly. `bin/rails db:setup` call them as part of the database setup flow. It creates the database, load the schema and run seeds.

It is hard to know what happened in your application without seeing the errors, but "Changing the schema.rb to keep ActiveRecord::Schema[7.0] instead of ActiveRecord::Schema[7.1]" should not interfere with seeds.
