### ISSUE TITLE
Change controller generators to use _path instead of _url for redirects

### ISSUE THREAD

**Issue by dhh** [rails/rails#52756]
Since HTTP 1.1, you've been allowed to use paths for 3xx redirects. But Rails has had a convention of using full URLs. We should change that. You should only use a full URL when you intend to change the domain or port or other non-path element. So let's set the correct example in generated controllers.

**Comment by jeromedalbert** [comment]
The basic controller scaffold generator in the Rails codebase [generates](https://github.com/rails/rails/blob/5c0b7496ab32c25c80f6d1bdc8b32ec6f75ce1e4/railties/lib/rails/generators/rails/scaffold_controller/templates/controller.rb.tt#L28) code like this:

 ```ruby
redirect_to @post, notice: "Post was successfully created."
```

But in default Rails apps those generators are overridden by the `jbuilder` generators which use urls like so:

```ruby
format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
format.json { render :show, status: :created, location: @post }
```

So it looks like a PR should be made in https://github.com/rails/jbuilder.

**Comment by skipkayhil** [comment]
(I commented on the other post but writing here as well)

My understanding of the issue was that we need to change `redirect_to @post` to use `path_for` instead of `url_for`, but I agree that the jbuilder template should also be updated if possible because it doesn't always stay in sync with the templates in rails/rails.

**Comment by JonhyOliveira** [comment]
There's a `url_for` in the `_compute_redirect_to_location` method that should probably be changed.

**Comment by dhh** [comment]
We also generate `redirect_to posts_url`, which needs to be changed.

**Comment by jeromedalbert** [comment]
Ok so if I understand correctly, we need to:

- change `redirect_to posts_url` to `redirect_to posts_path`
- make `redirect_to @some_record` / `redirect_to some_path` redirect with a response `Location` that looks like `/posts/24` instead of the current behavior which is to return a full URL for the `Location` like `http://localhost:3000/posts/24`. This involves changing some of the internals in [`_compute_redirect_to_location`](https://github.com/rails/rails/blob/main/actionpack/lib/action_controller/metal/redirecting.rb#L158).

**Comment by Procrustes5** [comment]
I want to start contributing this, and it seems #52764 has partially fix.
May I ask what is remained?

**Comment by jeromedalbert** [comment]
I believe this issue can be closed as all PRs that updated controller generators on the Rails side (https://github.com/rails/rails/pull/52764) and JBuilder side (https://github.com/rails/jbuilder/pull/569) have been merged.

**Comment by dhh** [comment]
Only thing that's missing is that redirect_to @post doesn't produce a path but a URL, I think? But we were searching for a simpler implementation. I'll close this for now though.
