### ISSUE TITLE
ActiveRecord won't convert to interval from string

### ISSUE THREAD

**Issue by alex-tan** [rails/rails#52784]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  gem "pg"
  gem "byebug"
end

require "active_record"
require "action_controller"
require "minitest/autorun"
require "logger"

# docker run --rm -e POSTGRES_PASSWORD=postgres -p 9999:5432 postgres
ActiveRecord::Base.establish_connection("postgres://postgres:postgres@localhost:9999/postgres")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :timings, force: true do |t|
    t.string :name
    t.integer :count
    t.interval :duration
  end
end

class Timing < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_duration
    params = ActionController::Parameters.new({
      timing: {
        name: "A",
        count: "5",
        duration: "300"
      }
    })

    permitted = params.require(:timing).permit(:name, :count, :duration)
    timing = Timing.create!(permitted)

    assert_equal "A", timing.name
    assert_equal 5, timing.count # Works even though count was a String param
    assert_equal 5.minutes, timing.duration # Fails because duration was a String param

    timing.update!(duration: 300)
    assert_equal 5.minutes, timing.duration # Works after being assigned a number directly.
  end
end
```

### Expected behavior

It should accept integers strings similar to integer columns.

### Actual behavior

The attribute ends up as nil.

### System configuration

**Rails version**: 7.2.1
**Ruby version**: 3.3.4

**Comment by fatkodima** [comment]
I think, this behavior is expected. When you pass a string, it expects that string to be in a certain format to be valid - https://github.com/rails/rails/blob/d5c2ff8345c9d23b7326edb2bbe72b6e86a63140/activerecord/lib/active_record/connection_adapters/postgresql/oid/interval.rb#L18-L23

If an integer is provided, it is simply considered as seconds.

**Comment by alex-tan** [comment]
Ah I see. Ok thank you

**Comment by amiel** [comment]
Hi,  I wanted to add some context to this issue in case it's worth revisiting.

The original report touches on what I think is a broader problem: in a standard Rails form workflow, attribute values always arrive as strings via params. Rails generally handles this transparently — an integer column will happily accept `"5"` and cast it to 5. The interval type is the only (that I'm aware of) type where this round-trip breaks silently.

Consider: if you render a form with a duration value, the value= attribute in the HTML will be the serialized integer (seconds). When the form is submitted, that same value comes back as a string, and the column silently sets itself to `nil`. This isn't a case of a developer passing the wrong type — it's the default Rails form lifecycle producing a value that the type can't round-trip.

I understand the current behavior is intentional in that strings are expected to be ISO 8601, but the result is that interval columns don't work out of the box with plain Rails forms without manual .to_i conversion in the controller, which is a gotcha that doesn't exist for any other column type.

For what it's worth, we solved this with a simple check in a custom setter:

```ruby
  if value.to_i.to_s == value.to_s
    super(value.to_i)
  else
    super
  end
```

This correctly identifies numeric strings (serialized seconds) while remaining backwards compatible with ISO 8601 strings and all other inputs.

Separately, #49799 proposes extracting a general-purpose `ActiveModel::Type::Duration` that defaults to ISO 8601 serialization, which would solve this problem from the other direction — if the serialized form value is ISO 8601 rather than integer seconds, the round-trip works natively. That would likely be a breaking change, but it's worth cross-referencing here since both issues stem from the same tension between numeric and ISO 8601 representations.

Just wanted to flag the form-lifecycle angle since it didn't come up in the original discussion.

I would be happy to submit a PR if there's interest in a fix.
