### ISSUE TITLE
Support the Prism parser with ErrorHighlight

### ISSUE THREAD

**Issue by kddnewton** [rails/rails#52902]
Currently when a template has a syntax error, the backtrace location is used to determine the node id, and the file is re-parsed using `RubyVM::AbstractSyntaxTree` to find the location to highlight. This work comes from https://github.com/rails/rails/pull/46908.

When the default parser is Prism, this will raise an error because the node ids do not match up. Instead it needs to be re-parsed with Prism. The relevant API is `Prism::Node#breadth_first_search`, and you can find an example of how this works in error highlight itself here: https://github.com/ruby/error_highlight/blob/a75ddf78b35ef015e2ba7c9303a730070b1d0201/lib/error_highlight/base.rb#L84-L95.

**Comment by zzak** [comment]
Maybe related to #51092

**Comment by byroot** [comment]
Adding this back to the 8.0 milestone because I'm adding Ruby 3.4.0-preview2 to CI and this is failing CI.

Unless we really can't fix it, I'd really want 8.0 final to be compatible with 3.4.0-preview2 so that hopefully people can upgrade to Ruby 3.4 in January.

I'll try to fix this myself or to find someone who can.
