### ISSUE TITLE
Mapping column manually like type/class to c_type/c_class

### ISSUE THREAD

**Issue by sebyx07** [rails/rails#52968]
How can i map the the class column to smth like c_class?
```ruby
#  class                          :integer          default(0), unsigned, not null
```

I tried adding 

```ruby
self.ignored_columns = %w[class]
```

but then I cannot read/write it anymore.

I cannot change the column name, because it's used by the azerothcore server

https://github.com/sebyx07/rails-on-azerothcore/blob/main/app/models/characters/character.rb#L16

If there isn't support I can look more into and make a PR for `alias_attribute` or `map_attribute`(new) to support any kind of combination

**Comment by lazyscript05** [comment]
> How can i map the the class column to smth like c_class?
> 
> ```ruby
> #  class                          :integer          default(0), unsigned, not null
> ```
> 
> I tried adding
> 
> ```ruby
> self.ignored_columns = %w[class]
> ```
> 
> but then I cannot read/write it anymore.
> 
> I cannot change the column name, because it's used by the azerothcore server
> 
> https://github.com/sebyx07/rails-on-azerothcore/blob/main/app/models/characters/character.rb#L16
> 
> If there isn't support I can look more into and make a PR for `alias_attribute` or `map_attribute`(new) to support any kind of combination

In your case, you need to work around the conflict of using the **class** column, which is a reserved keyword in Ruby. While you can't rename the column (since it's required by AzerothCore), there are ways to map it to another attribute in Rails without entirely removing it from usage. Instead of using **self.ignored_columns**, you can use **alias_attribute** to create a readable and writable alias for this column.

Here's how you can achieve this using **alias_attribute:**

```ruby
module Characters
  class Character < CharactersApplicationRecord
    self.table_name = 'characters'
    self.primary_key = 'guid'

    # Alias the `class` column to `c_class`
    alias_attribute :c_class, :class

    has_many :inventory_items, class_name: 'Characters::CharacterInventory', foreign_key: :guid, primary_key: :guid
    has_many :instance_items, class_name: 'Characters::ItemInstance', foreign_key: :owner_guid, primary_key: :guid

    belongs_to :c_account, class_name: 'Auth::Account', foreign_key: :account

    def items
      instance_items.map(&:item)
    end
  end
end
``` 

Explanation:
**alias_attribute :c_class, :class:** This creates an alias **c_class** for the **class** column. You can now read/write the **class** column using the **c_class** attribute. The original **class** column remains in the schema, but you don't need to access it directly.

Usage:
To read the **class** column value: **character.c_class**
To write to the **class** column: **character.c_class = 1**

This should allow you to interact with the **class** column without conflicting with Ruby's reserved word, while maintaining compatibility with the AzerothCore schema.

Hope it helps :)

**Comment by sebyx07** [comment]
worked with

```
module Characters
  class Character < CharactersApplicationRecord
    self.table_name = 'characters'
    self.primary_key = 'guid'

    alias_attribute :c_class, :class

    has_many :inventory_items, class_name: 'Characters::CharacterInventory', foreign_key: :guid, primary_key: :guid
    has_many :instance_items, class_name: 'Characters::ItemInstance', foreign_key: :owner_guid, primary_key: :guid

    belongs_to :c_account, class_name: 'Auth::Account', foreign_key: :account

    # needed this to work otherwise
    # ActiveRecord::DangerousAttributeError: class is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.
    # from /usr/local/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/attribute_methods.rb:166:in `instance_method_already_implemented?'
    def self.instance_method_already_implemented?(_)
      true
    end

    def items
      instance_items.map(&:item)
    end
  end
end
```

**Comment by sebyx07** [comment]
that's why I suggested a patch for alias_attribute

**Comment by sebyx07** [comment]
@lazyscript05
