### ISSUE TITLE
HashWithIndifferentAccess#deep_stringify_keys vs non-string keys

### ISSUE THREAD

**Issue by zverok** [rails/rails#53008]
### Steps to reproduce

```ruby
h = {a: {1 => true}}
hi = h.with_indifferent_access

h.deep_stringify_keys  #=> {"a"=>{"1"=>true}} -- all keys strings
hi.deep_stringify_keys #=> {"a"=>{1=>true}}   -- integer keys remains integer
```

### Expected behavior

I am not sure it should be considered a “bug” per se, but it seems to be an inconsistency (which, on one not-so-modern codebase, cost me some half an hour of debugging). I would rather expect that aggressive stringification that `deep_stringify_keys` perform will be retained for HWIA, but it is not so, its `deep_stringify_keys`/`deep_stringify_keys!` are defined as [no-ops](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/hash_with_indifferent_access.rb#L319).

HWIA is quite widespread, and it is easy to convert arbitrary deep data hashes into it. .

### Actual behavior

Integer keys remain integer. 

In our particular use case, it was a hash returned by `Dirty#previous_changes`, and the code tried to send it as ActiveJob argument, and got an error on integer keys, which remained integer even after `deep_stringify_keys`.

### System configuration
**Rails version**: checked with latest ActiveSupport (7.2.1)

**Ruby version**: 3.2.2

**Comment by jeromedalbert** [comment]
Yeah, seems inconsistent, although the `HashWithIndifferentAccess` docs mention that the intended use case is string of symbol keys (while other types like integer keys are accepted):

https://github.com/rails/rails/blob/31818edb035266c487510db933ed97a33093751e/activesupport/lib/active_support/hash_with_indifferent_access.rb#L34-L42

**Comment by jeduardo824** [comment]
Thinking on the consistency of the keys and the usage of the method, maybe the HWIA `deep_stringify_keys` method should call `to_hash.deep_stringify_keys` just as the method `deep_symbolize_keys` does

https://github.com/rails/rails/blob/31818edb035266c487510db933ed97a33093751e/activesupport/lib/active_support/hash_with_indifferent_access.rb#L324

It probably makes sense since the behavior of `deep_stringify_keys` in a regular hash would be to convert the Integer to a String.

**Comment by kabirpathak** [comment]
@jeduardo824 can I open a PR with the changes you suggested? Let me know if you're already working on the same.

**Comment by jeduardo824** [comment]
@kabirpathak I was thinking about waiting for more comments from other team members, but I'm not working on this right now. Feel free to open a PR!

**Comment by zalom** [comment]
> Thinking on the consistency of the keys and the usage of the method, maybe the HWIA `deep_stringify_keys` method should call `to_hash.deep_stringify_keys` just as the method `deep_symbolize_keys` does
> 
> https://github.com/rails/rails/blob/31818edb035266c487510db933ed97a33093751e/activesupport/lib/active_support/hash_with_indifferent_access.rb#L324
> 
> It probably makes sense since the behavior of `deep_stringify_keys` in a regular hash would be to convert the Integer to a String.

Hi @jeduardo824, I was curious about your suggestion, so I went out of my comfort zone to check this. I like this intricacy of Rails that @zverok mentioned. (Btw., Zverok, we missed you at EuRuKo 2024 in Sarajevo)

`deep_symbolize_keys` preserves integer keys for HWIA and standard Hashes alike. The specific test case confirms the method contract/signature and puts this to light. ->
https://github.com/rails/rails/blob/ebd9beebebe9cea916de4fe0179105c05d9e7c0b/activesupport/test/hash_with_indifferent_access_test.rb#L101-L104

The only difference is in `deep_stringify_keys`. 
In the `deep_stringify_keys` test case for the HWIA, we see that integers were not even considered ->
https://github.com/rails/rails/blob/ebd9beebebe9cea916de4fe0179105c05d9e7c0b/activesupport/test/hash_with_indifferent_access_test.rb#L106-L111

And if we check the `setup` method, we can see that `@mixed` and `@nested_mixed` ivars don't include integer keys at all.
https://github.com/rails/rails/blob/ebd9beebebe9cea916de4fe0179105c05d9e7c0b/activesupport/test/hash_with_indifferent_access_test.rb#L40-L51

All of this points to integers being accepted as a nuance or dissonance in HWIA more than a bug. And I am afraid we will end up debating this because it has been like this for a long time. And even if we do fix the inconsistency, it will probably have to go in some major version.

@byroot, can you provide some thoughts? Can we consider this change a worthwhile or welcome addition?
(btw good thinking with `Symbol === k ? k.name : k.to_s` change)

**Comment by byroot** [comment]
> can you provide some thoughts?

I'd say it would make sense to not longer define `HashWithIndifferentAccess#stringify_keys`, and just let the `Hash#stringify_keys` behavior operate.

With the provision that this has been acting like this for ages, so it may break quite a bit of code out there, so we may decode to backtrack if it prove too problematic. 8.0 is still in beta, so this might be a good window of opportunity, I'll ask for second opinions.

**Comment by zalom** [comment]
I went in a little bit more, and this change suffices the intended behavior ->
```diff
index 2f771d7e97..8bc551ff2b 100644
--- a/activesupport/lib/active_support/hash_with_indifferent_access.rb
+++ b/activesupport/lib/active_support/hash_with_indifferent_access.rb
@@ -314,9 +314,9 @@ def except(*keys)
     alias_method :without, :except

     def stringify_keys!; self end
-    def deep_stringify_keys!; self end
+    def deep_stringify_keys!; super end
     def stringify_keys; dup end
-    def deep_stringify_keys; dup end
+    def deep_stringify_keys; super end
```
With just a few more tests added, it seems like a trivial change, but I am never too optimistic when it comes to trivial changes of the "old" ways 😊.

I can open the POC pull request in case that can make things clearer for conversation, but I would like some more opinions.

**Comment by fxn** [comment]
I believe this is a bug. I don't know if the return value should be a HWIA or a regular hash, but I'd say `stringify_keys` and `deep_stringify_keys` should make the keys be strings.

**Comment by zalom** [comment]
And one more observation.
The current implementation of bang methods of both `stringify_keys` and `deep_stringify_keys` in HWIA makes no sense. They don't mutate the origin ->


> I believe this is a bug. I don't know if the return value should be a HWIA or a regular hash, but I'd say `stringify_keys` and `deep_stringify_keys` should make the keys be strings.

I completely agree.

One further observation. 
The current implementation of the HWIA bang methods for `stringify_keys` and `deep_stringify_keys` makes no sense. As is, starting from either `hash.with_indifferent_access` or `ActiveSupport::HashWithIndifferentAccess.new` makes all keys (except integer keys) stringified. Thus, there is no change in the origin unless I tested it wrong somehow.

_`with_indifferent_access`_
```ruby
Loading development environment (Rails 8.0.0.alpha)
dummy-app(dev)> h = { 1 => { a: { "b" => 2, 3 => "c" } } }
=> {1=>{:a=>{"b"=>2, 3=>"c"}}}
dummy-app(dev)> h.with_indifferent_access.stringify_keys!
=> {1=>{"a"=>{"b"=>2, 3=>"c"}}}
dummy-app(dev)> h.with_indifferent_access.deep_stringify_keys!
=> {1=>{"a"=>{"b"=>2, 3=>"c"}}}
dummy-app(dev)> h
=> {1=>{:a=>{"b"=>2, 3=>"c"}}}
```

_`ActiveSupport::HashWithIndifferentAccess.new`_
```ruby
dummy-app(dev)> hash = ActiveSupport::HashWithIndifferentAccess.new(a: 1)
=> {"a"=>1}
dummy-app(dev)> hash[0] = 0
=> 0
dummy-app(dev)> hash
=> {"a"=>1, 0=>0}
dummy-app(dev)> hash.stringify_keys
=> {"a"=>1, 0=>0}
dummy-app(dev)> hash
=> {"a"=>1, 0=>0}
dummy-app(dev)> hash[:b] = 1
=> 1
dummy-app(dev)> hash
=> {"a"=>1, 0=>0, "b"=>1}
dummy-app(dev)> hash[:c] = { 1 => 2, a: 3 }
=> {1=>2, :a=>3}
dummy-app(dev)> hash
=> {"a"=>1, 0=>0, "b"=>1, "c"=>{1=>2, "a"=>3}}
dummy-app(dev)> hash.stringify_keys
=> {"a"=>1, 0=>0, "b"=>1, "c"=>{1=>2, "a"=>3}}
dummy-app(dev)> hash.deep_stringify_keys
=> {"a"=>1, 0=>0, "b"=>1, "c"=>{1=>2, "a"=>3}}
dummy-app(dev)> hash.deep_stringify_keys!
=> {"a"=>1, 0=>0, "b"=>1, "c"=>{1=>2, "a"=>3}}
dummy-app(dev)> hash
=> {"a"=>1, 0=>0, "b"=>1, "c"=>{1=>2, "a"=>3}}
```

**Comment by zalom** [comment]
> I don't know if the return value should be a HWIA or a regular hash

@fxn (Hi), I went through tests. There are explicit checks to return HWIA, and I am leaning toward leaving it as is. It inherits from Hash anyway, and whenever I used it or saw it used, it was an intentional conversion for the sake of consistent keys (excluding integer keys).

Of course, this is just an observation and a suggestion, and I am glad to have wiser heads than mine in this conversation 😊.

**Comment by fxn** [comment]
@zalom makes sense.

I was wondering, because, in a sense, HWIA provides a uniform input interface, which internally gets normalized to something. So, if you force that something to be of a concrete type, you kind of have asked for a regular hash. Just like `symbolize_keys` does (I just checked motivated by this point of view).

But on the other hand, the fact that the internal mapping to strings is documented and it is an explicit contract you can rely on, allows `stringify_keys` to be different from `symbolize_keys` in that regard.

That means, `stringify_keys` would be a no-op, and I guess that was the intention of the original `dup`. However, I do think that `dup` overlooked the documented condition that anything but symbols is not normalized (integers are just one particular case, the normalization is `Symbol === key ? key.name : key`).

To me, if I ask for the keys to be stringified, of course I am in particular saying that what is not already a string, should become a string. Leaving object that are not strings cannot be considered to be correct, for me.

@byroot's concern is understandable and I'll defer to him the resolution of this ticket. On one hand, if we categorize this as a bug, we are allowed to ship without intermediate steps. On the other hand, ..., maybe it is debatable in this particular API.

**Comment by zalom** [comment]
@fxn very well elaborated and what a learning session!

Looking forward to see how we will resolve this.
