### ISSUE TITLE
`commit_transaction_on_non_local_return` deprecation is misleading

### ISSUE THREAD

**Issue by davidcornu** [rails/rails#53057]
## Context

The 7.2 release notes (https://edgeguides.rubyonrails.org/7_2_release_notes.html#active-record-deprecations) state:

> Deprecate `Rails.application.config.active_record.commit_transaction_on_non_local_return`

but also

> Remove deprecated behavior that would rollback a transaction block when exited using `return`, `break` or `throw`.

This can be misleading as applications that still set

```ruby
config.active_record.commit_transaction_on_non_local_return = false
```

will get a deprecation warning

```
DEPRECATION WARNING: `Rails.application.config.active_record.commit_transaction_on_non_local_return` is deprecated and will be removed in Rails 8.0. (called from <top (required)> at /Users/david/Developer/patch/config/environment.rb:7)
```

which suggests the behaviour will still work in 7.2 but be removed in Rails 8.0. This is wrong given that the config is now a no-op

![CleanShot 2024-09-26 at 16 11 56](https://github.com/user-attachments/assets/dda2b105-7ca5-40fc-bc7b-786d43058e9e)

https://github.com/rails/rails/blob/5a735e9e05f8c045741b26b2ba74ed936ca04f73/activerecord/lib/active_record.rb#L347-L359

and the actual logic was removed in https://github.com/rails/rails/commit/eccc6061f4f3abdfdeb9a363987a898418d9498f.

## Why is this a problem?

Applications that did rely on the old behaviour could now be inadvertently be opted in to the new behaviour, which can break existing logic in subtle ways.

## Recommendations

In the 7.2 line,

- `Rails.application.config.active_record.commit_transaction_on_non_local_return` should either be removed or raise an error so as to fail loudly and let users know to proceed with caution.
- The release notes should be updated to make this clearer.

Happy to submit a PR with the above.

**Comment by Earlopain** [comment]
`commit_transaction_on_non_local_return` can't be removed in 7.2 because it would error without notifying the user in some way.

Is there a situation in 7.1 where you would not get this deprecation warning? https://github.com/rails/rails/blob/a36c06d38abf3a091b1b7d5ca9231089c5667621/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L553-L561 I don't think you are able to opt-out in some way.

**Comment by davidcornu** [comment]
> Is there a situation in 7.1 where you would not get this deprecation warning? 

In 7.1, `commit_transaction_on_non_local_return` actually does something so the deprecation warning is correct in that the functionality still works but is deprecated.

![CleanShot 2024-09-27 at 08 28 35@2x](https://github.com/user-attachments/assets/aac42512-9744-45f0-aae6-1bb8a1cd0630)

> `commit_transaction_on_non_local_return` can't be removed in 7.2 because it would error without notifying the user in some way.

In 7.2 the setting _does absolutely nothing_, which could lead folks astray. IMHO erroring would be a good thing here as users would have to remove the setting and make a decision about whether they're ready to opt-in to the new behaviour rather than wrongly assume it's deprecated.

**Comment by Earlopain** [comment]
You only get the deprecation warning from 7.1 if you actually have transactions that would change behaviour in 7.2. I don't think there is any advice to set it to `false`, and if you did, you would still get the deprecation warning from 7.1.

I'm a bit confused how you even ended up in this situation, if that makes sense.

**Comment by davidcornu** [comment]
> I'm a bit confused how you even ended up in this situation, if that makes sense.

Ah I see. 

For context, we have a lot of existing code in service objects that leverages [dry-monads](https://dry-rb.org/gems/dry-monads/1.6/do-notation/) to do things like

```rb
ActiveRecord::Base.transaction do
  # ...
  return Failure("...") unless precondition_met?
  # ... 
end
```

and relies upon the old behaviour to abort the transaction rather than continue.

When 7.1 was released we configured `commit_transaction_on_non_local_return = false` to keep it that way (basically to save ourselves having to audit every transaction block). 

When 7.2 was released, we started getting a deprecation warning for `commit_transaction_on_non_local_return` but mistakenly thought (based on the deprecation message) that this meant the old behaviour was still enabled and that we had until Rails 8 to audit our code. Thankfully after reading through the 7.1 source code we realized the setting is a no-op and that rolling out 7.2 would have opted us into the new behaviour.

IMHO this is a bad user experience as having the setting be deprecated despite the behaviour it controls being removed is surprising, and could lead to unexpected and subtle changes in behaviour.

----

Ultimately we're now aware of this issue and will fix our code before upgrading to 7.2, but I think it's worth flagging as a potential footgun.

**Comment by zzak** [comment]
If you want the old behavior, how about `raise AR::Rollback` inside the `Failure` handler?

Maybe the confusion is because the initial warning didn't mention the flag being deprecated.

So we had this type of scenario:

* 7.1
  * https://guides.rubyonrails.org/v7.1/configuring.html#config-active-record-commit-transaction-on-non-local-return
  * We said use this flag, and we're going to change the value to `true` in `load_defaults 7.1`.
* 7.2
  * We remove the behavior, and deprecate the flag making it no-op
* 8.0
  * Flag should be removed, but no warning or error if you try to change it

This does seem like it might have been a mistake on our part, that the flag was not first deprecated before becoming a no-op. Given the number of deprecations and removals in each release of Rails, there is room for error. We try to get all of these types of changes out in the first beta (like #51146), so that gives people time to test those pre-releases, review the changes, and help us get it right.

Still, I don't know if there is anything actionable here, short of reviving that flag but given we're already close to 7.1.5 it might be too late. /cc @rafaelfranca

**Comment by Earlopain** [comment]
On 7.1 this still warns even if `config.commit_transaction_on_non_local_return = false`.

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 7.1.0"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord.commit_transaction_on_non_local_return = false

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    Post.transaction do
      Post.create!
      return
    end
    # => DEPRECATION WARNING: A transaction is being rolled back because the transaction block was
  end
end
```

The warning disappears on 7.2 and moves to the new behaviour, showing the deprecation about the config itself, but at that point the notices from 7.1 didn't fully get addressed before moving to 7.2. I believe this is working as expected.

**Comment by davidcornu** [comment]
> This does seem like it might have been a mistake on our part, that the flag was not first deprecated before becoming a no-op. Given the number of deprecations and removals in each release of Rails, there is room for error. We try to get all of these types of changes out in the first beta (like #51146), so that gives people time to test those pre-releases, review the changes, and help us get it right.

Completely understandable! We're just a very odd case of caring very deeply about this one setting in a sea of other changes 😅.

> Still, I don't know if there is anything actionable here, short of reviving that flag but given we're already close to 7.1.5 it might be too late.

I'd be happy to at least tweak the deprecation warning and release notes to mention that it's a no-op.

**Comment by zzak** [comment]
I'm not sure what phrasing would make sense, but the thing that gets me is that we added a new flag and it was deprecated and no-op'ed in the very next release. The behavior behind the flag was deprecated at the time the flag was added, but still the flag itself did not receive the proper deprecation period IMO. Does it make sense?

**Comment by davidcornu** [comment]
@zzak yup that's pretty much my understanding. I'm also assuming it's too late to do anything about it in code.

> I'm not sure what phrasing would make sense, but the thing that gets me is that we added a new flag and it was deprecated and no-op'ed in the very next release.

I would add a clarification to the bit about the setting being deprecated stating that it is a no-op and that applications upgrading to 7.2 will always use the new behaviour.

**Comment by zzak** [comment]
I think we can tweak this message in 7.1 branch:

>To opt-in to the new behavior now and suppress this warning you can set:

Open to suggestions, if you want to open a PR and point it at `7-1-stable`.

**Comment by skipkayhil** [comment]
> I'm not sure what phrasing would make sense, but the thing that gets me is that we added a new flag and it was deprecated and no-op'ed in the very next release. The behavior behind the flag was deprecated at the time the flag was added, but still the flag itself did not receive the proper deprecation period IMO. Does it make sense?

I'm not sure I understand the suggestion that something was removed without deprecation

### Behavior Deprecation
In 7.1
- `commit_transaction_on_non_local_return` is added (defaults to `false`)
- if its `false` and you hit the specific case, *you get a deprecation warning* saying that this behavior will change in Rails 7.2 (or you can set the config to `true` to get the 7.2 behavior now

In 7.2
- we exercise the behavior deprecation by making `commit_transaction...` effectively always `true` (like the deprecation message said we would)

### Config Deprecation

In 7.2
- since the config is now a no-op, both the getter and setter emit a deprecation warning

In 8.0
- we'll exercise the deprecation by removing the getter/setter

> I would add a clarification to the bit about the setting being deprecated stating that it is a no-op and that applications upgrading to 7.2 will always use the new behaviour.

Is this a suggestion for code or the upgrading guide/release notes? (I think adding a mention in the guide probably makes sense)

**Comment by rafaelfranca** [comment]
@skipkayhil's reading is correct. Setting the flag would always print a deprecation in 7.1, meaning that that behavior would change in 7.2 with no escape hatch. That was already the correct deprecation period. 7.2 is just deprecating the config, not the possibly to set it to `false`. That was already deprecated in 7.1.

The message in 7.1 is clear in my opinion:

```
                  A transaction is being rolled back because the transaction block was
                  exited using `return`, `break` or `throw`.
                  In Rails 7.2 this transaction will be committed instead.

                  To opt-in to the new behavior now and suppress this warning
                  you can set:

                    Rails.application.config.active_record.commit_transaction_on_non_local_return = true
```

There is no mention that you can set this to `false` and keep the transaction not being committed on non-local return. It clear states that in 7.2 the transaction will be committed.

I can see we changing the message in 7.2 to be:

```
The configuration setter `Rails.application.config.active_record.commit_transaction_on_non_local_return` is deprecated and will be removed in Rails 8.0
```

But isn't that redundant?

**Comment by matthewd** [comment]
In retrospect I think it would be fair to argue that 7.2 could/should have raised when setting it to the now-invalid mode, while reporting the new deprecation for the noop case. 🤔

(But I'd be quite reluctant to make that change now, because we might break someone's app from booting when it might actually be working fine despite not having the behaviour they're requesting.)

**Comment by davidcornu** [comment]
> There is no mention that you can set this to `false` and keep the transaction not being committed on non-local return. It clear states that in 7.2 the transaction will be committed and all you can do is opt-in early to the new behavior and suppress that deprecation message by setting the config to `true`.

@rafaelfranca while there isn't a clear "you can also set this to `true`", my read is it's implied because it's a boolean. If there's a similar intent in the future I'd recommend something like

```ruby
Rails.application.config.active_record.commit_transaction_behaviour = :on_non_local_return
```

which might make it more obvious that it's an opt-in flag rather than a toggle.

**Comment by davidcornu** [comment]
Gonna close this one as it sounds like
1. It's too late to do anything meaningful about it
2. There isn't a consensus on whether a no-op configuration flag is problematic

Thanks for hashing this one out with me ❤️
