### ISSUE TITLE
undefined method `transform_values' for an instance of ActiveRecord::Result::IndexedRow

### ISSUE THREAD

**Issue by arni1981** [rails/rails#53081]
Now, I'm not sure if this is indeed a bug or if I missed a breaking change somewhere, I did read thru the changelogs though and found nothing.

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # This works, version 7.2
  # gem "rails", "~> 7.2"

  # This does not, version 8.0
  gem "rails", github: "rails/rails"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

class BugTest < Minitest::Test
  def test_stuff
    data = ActiveRecord::Base
        .connection
        .select_all("select 1 as id, 20 as age")
        .first

      data = data.transform_values(&:to_f)
      OpenStruct.new(data)
  end
end
```

### Expected behavior
This worked great in 7.2

### Actual behavior
In version 8 this produces

> NoMethodError: undefined method `transform_values' for an instance of ActiveRecord::Result::IndexedRow

### System configuration
**Rails version**: 8.0.0.beta1

**Ruby version**: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]

**Comment by fatkodima** [comment]
Was changed in https://github.com/rails/rails/pull/51744 (cc @byroot)

Should we fix something about this (like delegate missing methods to `to_h`)?

In the meantime you can use `data = data.to_h.transform_values(&:to_f)`.

**Comment by vipulnsward** [comment]
Related: https://github.com/rails/rails/pull/51744/files , @arni1981 please see updated docs, it doesn't return a hash anymore.

cc @byroot probably needs a changelog to highlight this change?

**Comment by arni1981** [comment]
https://github.com/rails/rails/pull/51744#issuecomment-2097932615

Delegating to `to_hash` (to_h) is mentioned here but then never actually implemented.

**Comment by byroot** [comment]
Yeah, I was hoping `delegate_to_missing` wouldn't be required, but I'm afraid we'll have to do it.

But it might not solve all compatibility issues though. If people use `!` methods like `transform_values!`, the issue remains.

It's unfortunate though because exposing an array of hashes here is really detrimental.

**Comment by byroot** [comment]
I'm traveling right now, but I'll address this issue soon. @arni1981 as you probably guessed, in the meantime you can work around this by using `data = data.to_h.transform_values(&:to_f)`

**Comment by fatkodima** [comment]
I made an attempt to fix this issue. It is a bit smarter than a simple `delegate_missing_to` - we explicitly disallow hash destructive (suffixed with `!`) methods as these will not work correctly, because will modify a throwaway temporary hash.

Maybe we can also raise an error message for `!` hash methods in `method_missing` suggesting to call `.to_h`?

**Comment by byroot** [comment]
I think the way to go is more to restore the hold behavior, return plain hashes, even if it's detrimental for performance, and return `IndexedRow` only from a different method that Active Record can use.
