### ISSUE TITLE
Rails 8.0.0.beta1: Parameters#expect does not raise ActionController::UnpermittedParameters when configured to do so and an unpermitted parameter is submitted

### ISSUE THREAD

**Issue by ccasabona** [rails/rails#53091]
What happens when an unpermitted parameter is submitted to a controller can by configured by setting in an environment file:

`ActionController::Parameters.action_on_unpermitted_parameters = :raise`  

In our test environment, we use this setting to identify illegal parameters.

[#51674](https://github.com/rails/rails/pull/51674) introduced `Parameters#expect` to replace params.require to define permitted parameters.  In our testing, we have found that Parameters#expect does not raise an `ActionController::UnpermittedParameters` exception when an unpermitted parameter is submitted and the above setting is set to `:raise`

In the test below, the attribute `nae:` is not permitted.  Run this test as written, and an `ActionController::UnpermittedParameters` exception should be raised.  Then in `def user_params`, comment out the `params.require` statement and uncomment the `params.expect` statement.  The test passes.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", '8.0.0.beta1'
  gem 'sqlite3'
  gem 'ostruct'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"
require "active_record"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActionController::Parameters.action_on_unpermitted_parameters = :raise

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
    t.string :ids
  end
end

class User < ActiveRecord::Base
end

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    resources :users
  end
end

class UsersController < ActionController::Base
  include Rails.application.routes.url_helpers

  def create
    # print submitted params for reference
    puts params
    @user = User.new(user_params)
  end

  def user_params
    # Runing the test with params.require raises ActionController::UnpermittedParameters (found unpermitted parameter: :nae):
    params.require(:user).permit(:name, { ids: [] })

    # Running the test with params.expect does not raise an exception
    # params.expect(user: [ :name, { ids: [] }])
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_parameters
    # the parameter nae: is illegal
    post '/users', user: { nae: 'User Name', ids: ['21']}
  end

  private
    def app
      Rails.application
    end
end

```

### Expected behavior
An ActionController::UnpermittedParameters should be raised when using params.expect.

### Actual behavior
No exception is raised despite the configuration setting being set to :raise.

### System configuration
Rails 8.0.0.beta1
Ruby 3.3.5

**Comment by fatkodima** [comment]
So this is expected? https://github.com/rails/rails/pull/51674/files#diff-283f0ca468d869eedc5972e7638755db3079db950783f6586410a8c865888b0fR34-R56

**Comment by rubyrider** [comment]
I think this expected when using `.expect` instead of `.expect!`.  You may want to expect an exception for an invalid or wrong parameter when using `.expect!`.

Here is the reference:
https://github.com/rails/rails/pull/51674/files?diff=split&w=0#diff-99dab0dfb4d0cfa044997480d5aa1b100dc60347a10cedd6d8f7a0395f6a6efdR44

**Comment by rkofman** [comment]
Not sure if I should open a new documentation issue. [Rails docs claim](https://api.rubyonrails.org/classes/ActionController/Parameters.html):

> Provides methods for filtering and requiring params:
> - `expect` to safely permit and require parameters in one step.
> - `permit` to filter params for mass assignment.
> - `require` to require a parameter or raise an error.

This strongly implies that the behavior will be similar, and it is surprising for it to diverge. IMO the divergence should either be treated as a bug (and fixed); or the documentation should be updated to make users aware of the difference.

Edit: found the relevant discussion for introducing the feature:
On the one hand, DHH seemed to [explicitly suggest](https://github.com/rails/rails/pull/51674#issuecomment-2316016113) a path to deprecating `action_on_unpermitted_parameters` using `expect!`. On the other, the conversation landed on `expect!` only raising on _missing_ parameters rather than _unpermitted_. Which is.. not what that setting is for.

I will open a new issue to discuss what I see as the two remaining problems with the current state: (1) incorrect docs (2) an important use-case (unpermitted params) no longer covered with the new approach.
