### ISSUE TITLE
[ActiveRecord] Broken db:migrate:reset 

### ISSUE THREAD

**Issue by javierav** [rails/rails#53216]
### Expected behavior
`db:migrate:reset` command should drop the database, create it and then re-apply all migrations.

### Actual behavior
After the introduction of the PR #52830, `db:migrate:reset` command is broken. If any changes have been made in a migration, they are not reflected in the database as migrations are not re-run. Instead, the database is initialized with the schema stored in the schema file.

### System configuration
**Rails version**: 8.0.0.beta1
**Ruby version**: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]

**Comment by JoeDupuis** [comment]
While investigating this, I noticed that it does the opposite for the solid gems.
It reads the schema before running the migrations for the primary, but empties the schema for the other solid DBs. 

Unrelated, but the solid gems should probably install a migration instead of a schema. 

Maybe migrate:reset could delete the schema before starting.

**Comment by JoeDupuis** [comment]
Dumping the schema after creating the db fix it for me: #53240
