### ISSUE TITLE
I can't install rails on my computer

### ISSUE THREAD

**Issue by DjPolloSixPack** [rails/rails#53280]
### Steps to reproduce
Hi, I tried to install rails several but every time I get an error. I installed node, sqlite3 and ruby (the versions are below). I have a decent connection to internet, I can open https://rubygems.org/ in any navigator (i use brave and edge), I dont have any proxy connection and I executed the command  "gem install rails" in the windows cmd and git bash. I can provide more information if needed.

Im a noob in this so I aprecciate a lot your help.

### Expected behavior
With the comand "gem install rails" it should install rails.

### Actual behavior
ERROR:  Could not find a valid gem 'rails' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - IO::TimeoutError: Failed to open TCP connection to rubygems.org:443 (Blocking operation timed out!) (https://rubygems.org/specs.4.8.gz)

I get this error code and I didnt found any solution.

### System configuration
**Rails version**: I can't install rails

**Ruby version**: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x64-mingw-ucrt]

**Node version**: v20.18.0

**Sqlite3 version**: 3.46.1 2024-08-13 09:16:08 c9c2ab54ba1f5f46360f1b4f35d849cd3f080e6fc2b6c60e91b16c63f69a1e33 (64-bit)

**Comment by vic778** [comment]
hi @DjPolloSixPack  It looks like you're encountering an issue with downloading the Rails gem due to a timeout when connecting to RubyGems. Here are some steps to troubleshoot and resolve this:
## Test Connection via Curl
 `curl https://rubygems.org/specs.4.8.gz` 

- Ensure that your internet connection is stable.
- If you have any firewall, antivirus software, or VPN running, try disabling them temporarily as they might be blocking the connection to `rubygems.org`.
 ### Update SSL Certificates 
- Sometimes the issue could be with SSL certificates on your system. Try updating your certificates by running the following command: 
`gem update --system`
- If this doesn't work, you can manually install the rubygems-update gem
` gem install rubygems-update` then `update_rubygems`
### Set a Mirror for RubyGems
- You can try using a mirror to download gems in case there's a specific issue with your connection to rubygems.org:
` gem sources --add https://gems.ruby-china.com/ --remove https://rubygems.org/` then `gem install rails`
hope this will help

**Comment by DjPolloSixPack** [comment]
Hi, thanks a lot for your help, updating the certificates worked for me!
