### ISSUE TITLE
sqlite: query logs part of column name

### ISSUE THREAD

**Issue by eval** [rails/rails#53517]
### Steps to reproduce
When executing certain selects on SQLite, the query log becomes part of the column name:

```
ActiveRecord::Base.connection.exec_query('select 1').columns
# => ["1 /*application='Ror'*/"]
# expected: ["1"]
```

Apparently this is how SQLite works:
```shell
❯ sqlite3 -box ':memory:' "select 1 /*foo */"
┌────────────┐
│ 1 /*foo */ │
├────────────┤
│ 1          │
└────────────┘
```

Apart from being surprising/annoying, it seems to only affect queries like `select <expr>` i.e. where you don't specify a column-alias.

Maybe as fix it would be enough to prepend the comment with `;`. Happy to provide a patch.

### System configuration
**Rails version**: `8.0.0.rc1`

**Ruby version**: `3.3.5`

**Comment by flavorjones** [comment]
This seems like it's a bug in SQLite3. I'll dig into the upstream codebase and see what I find.

Can you help me understand more deeply the real-world problem you're experiencing because of this? I'm not sure the use case of selecting a constant expression is worth Rails working around an underlying database issue (especially since there's a pretty easy workaround when you construct the query).

**Comment by eval** [comment]
> Can you help me understand more deeply the real-world problem you're experiencing because of this?

None really, apart from looking off and wondering if there's more to it. This happened when trying some raw sql on the console to see what sqlite makes of some expressions, e.g. `select julianday('now')` etc. you'd never refer to those columns. But it seems indeed a bug in sqlite, not something worth fixing here. Thanks!
