### ISSUE TITLE
Rails 7.2.2: Uniqueness validator requires a class argument

### ISSUE THREAD

**Issue by tagliala** [rails/rails#53598]
Hello,

I've noticed that #52983 broke some specs in a gem that I'm maintaining

The gem initializes validators for testing purposes, so I don't know if it is a legit use case, 
but I think it is worth to report that now the Uniqueness validator behaves differently from other ones:

```
> Rails.version
=> "7.2.2"

> ActiveRecord::Validations::AbsenceValidator.new(attributes: [:name])
=> #<ActiveRecord::Validations::AbsenceValidator:0x000000012e30c8f0 @attributes=[:name], @options={}>

> ActiveRecord::Validations::PresenceValidator.new(attributes: [:name])
=> #<ActiveRecord::Validations::PresenceValidator:0x000000012f6824e8 @attributes=[:name], @options={}>

> ActiveRecord::Validations::UniquenessValidator.new(attributes: [:name])
NoMethodError: undefined method `singleton_class?' for nil
from ~/.rvm/gems/ruby-3.3.0/gems/activerecord-7.2.2/lib/active_record/validations/uniqueness.rb:17:in `initialize'
```

It appears that after the change, the `class:` option is now mandatory for `UniquenessValidator`

Ref: DavyJonesLocker/client_side_validations#953

_Originally posted by @tagliala in https://github.com/rails/rails/issues/52983#issuecomment-2464260619_

**Comment by Earlopain** [comment]
I don't think you are supposed to use these classes directly, they are nodoc. I _think_, while you were able to create one like this in the past, using it for validations would be broken since the class is required to check for database indices, among other things. Any validator will automatically get the class attribute when used through the public api here: https://github.com/rails/rails/blob/f511cd3adc055fad53c9b4728c83430431f22998/activemodel/lib/active_model/validations/with.rb#L88-L90

**Comment by tagliala** [comment]
Thanks, just to make sure this is not a regression.

I will happily update the test, closing here
