### ISSUE TITLE
db:drop db:create db:migrate - run only difference migrations

### ISSUE THREAD

**Issue by kubatron117** [rails/rails#53649]
When I do `db:drop`, the **database is deleted**. Then I create it using `db:create` and migrate it using `db:migrate`. 

**Problem:**
- The **original `db:schema` is started**, and thus the **changes made in the migration are not reflected**.

**Current Solution:**
- **Manually delete the contents of `schema.rb`**.
- Run `db:migrate` again, which **generates `schema.rb` including the changes**.

**Additional Information:**
- In **Rails 7.x**, this worked correctly.
- The issue is **noticed in Rails 8.0.0**.

### System configuration
**Rails version**:
8.0.0

**Ruby version**:
3.3.6

**Comment by thorvn** [comment]
I have the same issue as you. It seems to be caused by this PR: https://github.com/rails/rails/pull/52830.

I don't understand the strange behavior of the following commands:

```bash
rm -rf db/migrate
bin/rails db:drop
bin/rails db:migrate
```

Why do we need to run `rm -rf db/migrate` before executing `db:migrate`? 

I thought that when we run `db:drop`, it should also clean up the schema file, right?

**Comment by JoeDupuis** [comment]
`bin/rails db:migrate` now load the schema before migrating. It caused a couple of issues, but it was done to solve #52829

Use `bin/rails db:migrate:reset` to work around this. It:

```
bin/rails db:drop
bin/rails db:create
bin/rails db:schema:dump
bin/rails db:migrate
```

https://github.com/rails/rails/pull/53240

**Comment by tomkr4l** [comment]
I can confirm this and thank's for `rails db:migrate:reset` command. The problem I see is that when I do `rails db:drop` I don't expect database schema to be remembered and I think this could be confusing for newcomers.

**Comment by LukasSkywalker** [comment]
I have used Rails for about a decade now, and would always run `rails db:drop db:create db:migrate` if I was creating a new migration, so I could test if it did the right thing. If it didn't, I would modify it and run the command again. This ensured that I was working off a clean state.

So I agree with @tomkr4l , it is confusing, and I would add that it is not confusing not only for newcomers, but for everyone, since even the Rails guides explicitly state that `db:migrate` should run the migrations.

> [...] bin/rails db:migrate. In its most basic form it just runs the change or up method for all the migrations that have not yet been run. [...] Note that running the db:migrate command also invokes the db:schema:dump command, which will update your db/schema.rb file to match the structure of your database.

The behavior therefore changed quite a bit...

**Comment by avogel3** [comment]
I agree with @LukasSkywalker. If you're running that chain of `drop -> create -> migrate`, you are knowingly trying to start from a fresh state where the structure hasn't been loaded. If you wanted to load the structure, then there's a separate command for that.

@marybethlee and I are working on a project where we need to load some foreign table definitions before our app's migrations run. I understand this is probably a non-standard thing to do in Rails... But because the new changes to `db:migrate` load the structure file first, our `db:migrate` command fails because those tables already exist.

We have some options to work around this for now, but ideally, we'd prefer the previous behavior of Rails 7.

**Comment by lxxxvi** [comment]
@JoeDupuis Thanks for pointing to `bin/rails db:migrate:reset`. Would it make sense to add the task to `bin/rails --tasks`?

```sh
# bin/rails --tasks | grep migrate
bin/rails db:migrate                         # Migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)
bin/rails db:migrate:down                    # Run the "down" for a given migration VERSION
bin/rails db:migrate:redo                    # Roll back the database one migration and re-migrate up (options: STEP=x, VERSION=x)
bin/rails db:migrate:status                  # Display status of migrations
bin/rails db:migrate:up                      # Run the "up" for a given migration VERSION
```

**Comment by ycbencheng** [comment]
Thankyou! I was losing my mind because of this.

**Comment by rafaelfranca** [comment]
This is the expected behavior. Before running migrations we need to load the schema since it is possible that the original migrations aren't in the application anymore. You should not edit old migrations, but if you do, you can use `bin/rails db:migrate:reset` or redo the specific migration you are editing.

And yes, `bin/rails db:migrate:reset` should be documented.

**Comment by mackuba** [comment]
> Before running migrations we need to load the schema since it is possible that the original migrations aren't in the application anymore

Wait, why would the original migrations ever not be in the application anymore?… The migrations should always include the complete code for bringing the db from 0 to final state, no?

**Comment by JoeDupuis** [comment]
> Wait, why would the original migrations ever not be in the application anymore?… The migrations should always include the complete code for bringing the db from 0 to final state, no?

Not necessarily. Some teams clean up old migrations.

Additionally, while uncommon, a Rails app can target a database that wasn’t originally created by the app itself. For example:

- Migrating from another framework, like Laravel, to Rails.
- Multiple Rails apps pointing to the same database.
