### ISSUE TITLE
ActiveStorage Content MD5 base64

### ISSUE THREAD

**Issue by JaysonMandani** [rails/rails#53660]
### Steps to reproduce

```ruby
presigned_upload_params[:checksum] = "GxfTxSFE/CB+NXv3ZqRk8Q=="

ActiveStorage::Blob.create_before_direct_upload!(filename: presigned_upload_params[:filename], byte_size: presigned_upload_params[:byte_size], checksum: presigned_upload_params[:checksum], content_type: presigned_upload_params[:content_type])
# Your reproduction script goes here
```

### Expected behavior
The content md5 should match the params `checksum` base64

BASE64 `GxfTxSFE/CB+NXv3ZqRk8Q==`

### Actual behavior
It returns a mismatch result the `+` replaced to whitespace.
`Content-MD5: 'GxfTxSFE/CB NXv3ZqRk8Q=='`

### System configuration
**Rails version**:
"rails", "~> 7.2.1"
**Ruby version**:
ruby "3.3.3"

**Comment by seanpdoyle** [comment]
Thank you for opening this issue. Could you expand your reproduction script so that it is executable?

You could use the [Active Storage bug report template](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_storage.rb) script as a starting point:

https://github.com/rails/rails/blob/4df235f7c0149ac7be86580d41a74a7785cb9bb9/guides/bug_report_templates/active_storage.rb#L1-L67

**Comment by JaysonMandani** [comment]
Thanks for this template I have to close this issue I already figured out the problem on my front end when passing parameters the checksum was changed for some reason.
