### ISSUE TITLE
`has_one/belongs_to ..., touch: true` on both ends behaves differently in 7.0.8.6 and 7.1.0.beta1

### ISSUE THREAD

**Issue by woto** [rails/rails#53671]
Hello, everyone, am I missed something or rails has a regression in `has_one/belongs_to, touch: true` on both ends between 7.0.8.6 and 7.1.0.beta1?

#### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", '7.1.0.beta1'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3", '1.5'
end

require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamps
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.timestamps
  end
end

class Post < ActiveRecord::Base
  has_one :comment, touch: true
end

class Comment < ActiveRecord::Base
  belongs_to :post, touch: true, optional: true
end

class BugTest < ActiveSupport::TestCase
  def test_post_touches_comment
    post = Post.create!
    assert_changes -> { post.updated_at } do
      Comment.create!(post: )
    end
  end

  def test_comment_touches_post
    comment = Comment.create!
    assert_changes -> { comment.updated_at } do
      Post.create!(comment:)
    end
  end
end
```

Here is the output, using Rails 7.0.8.6
![image](https://github.com/user-attachments/assets/b5e29a3e-c3c5-4027-be0e-890e6808c9a7)

And here is output, using Rails 7.1.0.beta1
![image](https://github.com/user-attachments/assets/f4626d2b-b9ea-48a7-bdbc-5c1ec97cd955)
![image](https://github.com/user-attachments/assets/bfd870ab-800f-4aeb-84be-cf942fa55523)

**Comment by Flixt** [comment]
What actually happens is in the reproduction example is a stack overflow because of circular touching.

I tracked the change in behavior down to the following commit: c68c360e2af743f907d5a5c2c8669ff5f5790ad2

The commit is part of https://github.com/rails/rails/pull/46410 to fix touching not bubbling up its way when `belongs_to` and `has_one` macros are mixed in the chain of associations configured with `touch: true`. However, we also had a hint in the upgrade guides explaining that this problem can occur (https://github.com/rails/rails/pull/46582). I fear you have to remove the circular touching from your code.

**Comment by woto** [comment]
Yeah, already used workaround. Thank you anyway! Can be closed then.

пт, 29 нояб. 2024 г., 17:08 Felix Tscheulin ***@***.***>:
