### ISSUE TITLE
app:update tends to downgrade Rails 8

### ISSUE THREAD

**Issue by igbanam** [rails/rails#53729]
### Steps to reproduce

```ruby
rails --version  # Rails 8.0.0
rails new something
cd something
bin/rails app:update
[d]
```

### Expected behavior
There should be no diff

### Actual behavior
```
@@ -47,13 +47,11 @@
   config.active_support.report_deprecations = false

   # Replace the default in-process memory cache store with a durable alternative.
-  config.cache_store = :solid_cache_store
+  # config.cache_store = :mem_cache_store

   # Replace the default in-process and non-durable queuing backend for Active Job.
-  config.active_job.queue_adapter = :solid_queue
-  config.solid_queue.connects_to = { database: { writing: :queue } }
+  # config.active_job.queue_adapter = :resque

-
   # Ignore bad email addresses and do not raise email delivery errors.
   # Set this to true and configure the email server for immediate delivery to raise delivery errors.
   # config.action_mailer.raise_delivery_errors = false
Retrying...
Overwrite /Users/igbanam/projects/januaree/upgrade8/config/environments/production.rb? (enter "h" for help) [Ynaqdhm] 
```

### System configuration
**Rails version**: Rails 8.0.0

**Ruby version**: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]

**Comment by skipkayhil** [comment]
Thank you for opening an issue.

This is generally what happens to any generated configuration that comes from gems (in this case `solid-*`) when running `app:update`, because Rails doesn't know about the changes those other gems make.

When deciding whether to apply changes from `app:update`, you should only accept them if they make sense (and in this case they clearly do not).

I'm going to close this as I think everything is behaving as expected.

Previous discussion: https://github.com/rails/rails/issues/53141#issuecomment-2415336255
