### ISSUE TITLE
:try isn't working through delegation

### ISSUE THREAD

**Issue by austinthecoder** [rails/rails#5790]
As you can see here, using `try` calls the method on the delegated object and not the delegator:

```
require 'delegate'
require 'active_support/core_ext/object/try'

class Fighter < SimpleDelegator
  def fighting?
    true
  end
end

class Person
  def fighting?
    false
  end
end

fighter = Fighter.new Person.new

fighter.fighting?       # true
fighter.try :fighting?  # false
```

I'm on ruby 1.9.3p125

**Comment by chancancode** [comment]
I'm two years late to this discussion, but it doesn't look like we had a very satisfying resolution yet, so I'm reopening the discussion!

I can see the argument that this would be the expected behavior on `BasicObject`, but I would argue that you would expect `#try` to actually work on `SimpleDelegator`. If you look at the source, `(Simple)Delegator` tries pretty hard for things like these – it overrides things like `*_methods` to add its own method, etc.

Also:

```ruby
>> require 'delegate'
=> true
>> class Zomg < SimpleDelegator
>>   def to_s
>>     'zomg ' + super
>>   end
>> end
=> :to_s
>> Zomg.new("boom").to_s
=> "zomg boom"
>> Zomg.new("boom").send(:to_s)
=> "zomg boom"
>> Zomg.new("boom").public_send(:to_s)
=> "zomg boom"
```

As you can see, things like `send` and `public_send` also work seamlessly on a wrapped object.

So, I propose that in Rails 5 we patch `Delegator` to work with `#try`. Thoughts @jeremy @fxn @drogus @rafaelfranca @matthewd @sgrif?

**Comment by matthewd** [comment]
:+1:

**Comment by sgrif** [comment]
Definitely less bad than the alternatives.
