### ISSUE TITLE
Limit replaces select clause when used with having

### ISSUE THREAD

**Issue by wb-lifebooker** [rails/rails#8103]
Practical Problem:
`Thing.group("things.id, other_things.id").having("other_things.id = 1").
                        includes(:other_things).count`
vs
`Thing.group("things.id, other_things.id").having("other_things.id = 1").
                    includes(:other_things).limit(1)`

Easy way to reproduce it:

`Thing.select("b").group("things.id").having("other_things.id = 1").includes(:other_things).limit(1)`

`SELECT DISTINCT `things`.id FROM `things` LEFT OUTER JOIN `other_things` ON `other_things`.`thing_id` = `things`.`id` ...`

the select clause is completely replaced

`Thing.select("b").group("things.id").having("other_things.id = 1").includes(:other_things).count`

`SELECT COUNT(DISTINCT b) AS count_b, b, things.id AS things_id FROM `things` 
LEFT OUTER JOIN `other_things` ON `other_things`.`thing_id` = `things`.`id` GROUP BY things.id 
HAVING other_things.id = 1`

---

.count has the correct behavior, and leaves the extra columns in the select clause. .limit() replaces the select clause and breaks the query.

**Comment by yuthura** [comment]
I'm not sure if I should mention this here or if I should create a new issue, but I seem to have this (or a very similar) problem. When using mysql2 and combining `limit`, `having` and `pluck`, somewhere Rails seems to first want to fetch `SELECT DISTINCT id FROM ...` instead of the actual pluck (which breaks the `having` conditions). When I remove the `limit`, it works as I expect. Don't know if this is a Rails issue, MySQL adapter issue (within Rails) or MySQL driver issue (within the mysql2 gem), but I wrote a simple failing test to prove my scenario:

https://gist.github.com/yuthura/ac8e738af75db22918972e60248d9a5d

Problem does not seem to occur when using sqlite3, but I don't know if that's because the `having` condition is not a problem in sqlite, or because the "prefetch" of distinct ID's is not performed with sqlite3.

Worked around the problem by using `connection.select_all("...")` with a custom query for now, but still would like to see this fixed (or at the very least justified with an explanation). :)

**Comment by senny** [comment]
@kamipo Any thoughts on the findings of @yuthura ?

**Comment by kamipo** [comment]
Looks like that MySQL have the limitation of columns that can be used in having clause.
#25997 solves this issue.
