### ISSUE TITLE
assert_recognizes don't aware of constraints

### ISSUE THREAD

**Issue by mmontossi** [rails/rails#8679]
I notice in the method recognized_request_for used in assert_recognizes that it's not aware of the constraints of a route, so will always trigger an RoutingError exception.

https://github.com/rails/rails/blob/v3.2.9.rc3/actionpack/lib/action_dispatch/testing/assertions/routing.rb#L210

**Comment by jensb** [comment]
I tried something similar (see http://stackoverflow.com/questions/27840410) on Rails 3.2.21 and 4.1.9 and my tests fail as soon as I insert a `constraints:` hash into my namespaced route. If I remove it, tests work again, but since the constraints hash defines a subdomain, this is not a solution for production.
The code referenced on StackOverflow worked fine on Rails 3.0.20.

**Comment by jensb** [comment]
Is anybody working on this issue? Please respond. Thank you!

**Comment by dmitry** [comment]
Don't believe so. If you are really need this to be fixed, please write at least test case and create a PR.

**Comment by maclover7** [comment]
#22435 could end up being a solution for this.

**Comment by robbyrussell** [comment]
Seems safe to close as it's been stale for nearly a decade

**Comment by ghiculescu** [comment]
Looks like it was fixed by https://github.com/rails/rails/pull/6399
