### ISSUE TITLE
skip_before_filter strange behavior when using if and only together

### ISSUE THREAD

**Issue by ginter** [rails/rails#9703]
I'm running into an issue when using skip_before_filter with both the "if" and "only" options.

```ruby
before_filter :test
skip_before_filter :test, only: [:show], if: -> { false }
```

When running the above, I expect "test" to be called when hitting the show action, but this isn't the case.

```ruby
before_filter :test
skip_before_filter :test, only: [:random], if: -> { false }
```

When running the above, I expect "test" to be called regardless of the conditional when hitting the show action, but this isn't the case. It is called in this case when the conditional evaluates to false but it is not called if the conditional evaluates to true.

**Comment by rafaelfranca** [comment]
Closed by #18404

**Comment by bluehallu** [comment]
@rafaelfranca That commit didn't close the issue, it merely documented this weird behaviour. Hate to use the old "least surprise principle" argument, but if this isn't totally unexpected behaviour I don't know what it is!

**Comment by joshuapinter** [comment]
I'm with @bluehallu, I think this issue should be re-opened and fixed properly so it doesn't burn people in the future. 

@rafaelfranca Are you able to re-open this so it doesn't get lost?

**Comment by rafaelfranca** [comment]
There is nothing to be fixed here. If you are using `if` and `only` together you are already asking to be burned. There is no defined behavior for this so there is no "least surprise principle" to follow. Any behavior we chose is going to be surprising, so the correct fix is: don't use them together

**Comment by leo-souza** [comment]
But isn't this behavior inconsistent with `before_action` interface?

**Comment by rafaelfranca** [comment]
The same happens with `before_action`

**Comment by lichtamberg** [comment]
This is a really weird behaviour to be honest... At least this should output some log warning?

Our usecase is not very special:

```rails
skip_before_action :authenticate_account!, only: [:show, :index], if: -> { request.format.js? }
```

**Comment by david-ape** [comment]
I hesitate to comment further, but it seems like the common expectation is that the "only|except" and "if|unless" conditions should be anded together. Would it not make sense to make this the defined behaviour (thus minimising surprise when it doesn't work)?

**Comment by h0jeZvgoxFepBQ2C** [comment]
At least this should raise an exception, if it's not possible to get it working like people think it does?

**Comment by simonbaird** [comment]
Another potential trap:

This looks quite reasonable:
```
  # Avoid InvalidCrossOriginRequest in controller test
  skip_before_action :verify_authenticity_token, only: :foo, if: -> { Rails.env.test? }
```

But, IIUC, it will silently ignore the `if:` and behave the same as the following, which is quite the security problem:
```
  skip_before_action :verify_authenticity_token, only: :foo
```

My unpleasant workaround:
```
  # Beware: https://github.com/rails/rails/issues/9703
  skip_before_action :verify_authenticity_token, if: -> { Rails.env.test? && action_name == 'foo' }
```

**Comment by joshuapinter** [comment]
@simonbaird Is that true? I'm coming back after 7 years to look at this but that seems crazy and if that's the case that the `if` gets completely ignored then this should 100% be "fixed". Above it said that `only` and `if` acted independently of each other, but they should work as `&&` elements where both have to be true for `skip_before_action` to be enacted.

**Comment by simonbaird** [comment]
It behaves as documented, [see here](https://github.com/rails/rails/blob/099776069c4be64be8be7e3fdb0232d7824a38a9/actionpack/lib/abstract_controller/callbacks.rb#L81-L87), and also [this PR](https://github.com/rails/rails/pull/18404), but I do think it is surprising and unintuitive, and that changing it (carefully and with plenty of warning) should be considered.

**Comment by simonbaird** [comment]
Rubocop can help you avoid the trap: https://www.rubydoc.info/gems/rubocop-rails/2.3.2/RuboCop/Cop/Rails/IgnoredSkipActionFilterOption .

**Comment by palexvs** [comment]
We have just found out this issue for ourself. Was surprised `skip_before_action :authenticate_user!, only: :health_check, if: -> { true }` disabled authentication for all action inside a controller. 
And seems like [documentation](https://api.rubyonrails.org/classes/AbstractController/Callbacks/ClassMethods.html#method-i-_normalize_callback_options) is not correct: only `skip_before_action` has an issue, but not `before_action`. 

> only: :index, if: -> { true } # the :if option will be ignored.

if not correct too - `only` option is ignored

Asked ChatGPT help me to summarize and format findings:

### Summary
The `skip_before_action` method incorrectly handles the combination of `:only` and `:if` options, causing unexpected behavior where the `:only` restriction is effectively ignored.

### Current Behavior
When using `skip_before_action` with both `:only` and `:if` options, the `:only` restriction is not properly applied, leading to the callback being skipped for all actions instead of just the specified ones.

**Example:**
```ruby
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

class ApiController < ApplicationController
  skip_before_action :authenticate_user!, only: :health_check, if: -> { true }
end
```

**Expected behavior:** The `authenticate_user!` callback should only be skipped for the `health_check` action when the `:if` condition is true.

**Actual behavior:** The `authenticate_user!` callback is skipped for **all actions** when the `:if` condition is true, completely ignoring the `:only` restriction.

### Root Cause Analysis

The issue stems from how Rails processes callback options in the `_normalize_callback_options` method:

1. **Normalization Process:** The `:only` option is converted to an `:if` condition using an `ActionFilter` object
2. **Option Merging:** When both `:only` and `:if` are present, they get merged into a single `:if` array
3. **Skip Logic:** The `skip_callback` method processes these conditions incorrectly, treating the combined conditions as a single filter

**Code Location:** `actionpack/lib/abstract_controller/callbacks.rb:93-102`

```ruby
def _normalize_callback_options(options)
  _normalize_callback_option(options, :only, :if)
  _normalize_callback_option(options, :except, :unless)
end

def _normalize_callback_option(options, from, to)
  if from_value = options.delete(from)
    filters = options[:filters]
    from_value = ActionFilter.new(filters, from, from_value)
    options[to] = Array(options[to]).unshift(from_value)  # This merges :only into :if
  end
end
```

### Impact

This bug has significant security implications:

- **Authentication bypass:** Controllers may unintentionally skip authentication for all actions
- **Unexpected behavior:** Developers expect `:only` to restrict which actions are affected
- **Security vulnerabilities:** Sensitive endpoints may be exposed due to this behavior

### Test Case

The issue is demonstrated in the existing test `test_if_is_ignored_when_used_with_only` in `actionpack/test/controller/filters_test.rb:172`:

```ruby
class ConditionalFilterController < ActionController::Base
  before_action :auth

  private
    def auth
      @ran_filter ||= []
      @ran_filter << "auth"
    end

    def if_filter
      puts caller
      @ran_filter ||= []
      @ran_filter << "if_filter"
      true
    end
end

class SkipFilterUsingOnlyAndIf < ConditionalFilterController
  skip_before_action :auth, only: :livecheck, if: -> { if_filter }
  
  def livecheck
    render plain: "ok"
  end
  
  def pii_data
    render plain: "ok"
  end
end

def test_if_is_ignored_when_used_with_only
  test_process(SkipFilterUsingOnlyAndIf, "pii_data")
  assert_equal %w( auth ), @controller.instance_variable_get(:@ran_filter)
end
```

This test expects the `:auth` callback to run for `pii_data` action, but due to the bug, it gets skipped.

### Documentation Inconsistency

The current documentation at [AbstractController::Callbacks](https://api.rubyonrails.org/classes/AbstractController/Callbacks/ClassMethods.html#method-i-_insert_callbacks) is incorrect:

> `only: :index, if: -> { true } # the :if option will be ignored.`

This statement is false for `skip_before_action`. The `:if` option is **not** ignored; instead, the `:only` option is ignored.

### Proposed Solutions

#### Option 1: Fix the Bug (Recommended)
Modify the `skip_callback` logic to properly handle the combination of `:only` and `:if` options by ensuring both conditions are respected.

#### Option 2: Add Warning/Deprecation
If breaking changes are a concern, add a deprecation warning when `:only` and `:if` are used together with `skip_before_action`.

#### Option 3: Configuration Flag
Add a configuration option to enable the correct behavior while maintaining backward compatibility.

### Workaround

Until this is fixed, developers should avoid combining `:only` and `:if` with `skip_before_action`. Instead, use conditional logic within the callback itself:

```ruby
# ❌ Problematic (current buggy behavior)
skip_before_action :authenticate_user!, only: :health_check, if: -> { Rails.env.production? }

# ✅ Workaround (explicit conditional logic)
before_action :authenticate_user!, unless: -> { action_name == 'health_check' && Rails.env.production? }
```

### Rails Version
This issue affects all current Rails versions (tested on Rails 7.x).

**Comment by palexvs** [comment]
cc: @claudiob

**Comment by sdhull** [comment]
> There is nothing to be fixed here. If you are using if and only together you are already asking to be burned

@rafaelfranca this does not seem in keeping with the promise of Rails (good developer experience) and POLS. There's something we can do better here, even if only raising in development & test envs.

However I think we can do even better than that. As outlined by Mr GPT (thanks @palexvs), I think the best option forward is `Option 3` ("Add a configuration option to enable the correct behavior while maintaining backward compatibility") _in addition_ to raising in development and/or test envs.

**Comment by zzak** [comment]
Sorry I didn't read the whole thread, but I feel like you're getting confused, this behavior is documented:
https://edgeapi.rubyonrails.org/classes/AbstractController/Callbacks/ClassMethods.html#method-i-_normalize_callback_options

> Note that :only has priority over :if in case they are used together.
> Note that :if has priority over :except in case they are used together.

**Comment by palexvs** [comment]
@zzak what the documentation says about this situation:

```
skip_before_action :authenticate_user!, only: :health_check, if: -> { true }

def index; end
def health_check; end
```

which action will require auth and which not?
